### ISSUE TITLE
AsyncLocal<T>.Value boxes Dictionary<TKey, TValue> enumerator allocating ~0.2% of VS open solution

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#22133] opened 2017-07-12 06:26 UTC
AsyncLocal<T>.Value and hence (ExecutionContext.SetLocalValue) boxes `Dictionary<TKey, TValue>.Enumerator`:

``` C#
        internal static void SetLocalValue(IAsyncLocal local, object newValue, bool needChangeNotifications)
        {
           [...]

            if (current._localValues == null)
                current._localValues = new Dictionary<IAsyncLocal, object>();
            else
                current._localValues = new Dictionary<IAsyncLocal, object>(current._localValues); <!-- Boxes Dictionary<TKey, TValue>.Enumerator

           [...]
```

![image](https://user-images.githubusercontent.com/1103906/28104349-f66eb176-671d-11e7-857c-0a38ffe5eaf9.png)

Can we add an overload to Dictionary that avoids the box, or manually adding the new values to the dictionary? 

Would like this ported to .NET Framework.

**Comment by davkean** [comment] 2017-07-12 06:27
Note, it also appears to box the notifications collection enumerator in the same method - but this is not showing up on the radar.

**Comment by justinvp** [comment] 2017-07-12 08:53
I believe this has already been addressed in .NET Core: https://github.com/dotnet/coreclr/pull/8216

Additionally, Dictionary's constructor has been optimized in Core to avoid the enumerator box allocation when the passed-in IDictionary is Dictionary: https://github.com/dotnet/coreclr/commit/ee52a8ffcaab89524a4137c807bbde65445f61ab

These need to be ported to .NET Framework.

**Comment by davkean** [comment] 2017-07-12 13:25
Looks like https://github.com/dotnet/corefx/issues/13856 is tracking the port - but it's closed, @AlexGhiondea @karelz How does that work?

**Comment by stephentoub** [comment] 2017-07-12 13:47
> How does that work?

https://github.com/dotnet/corefx/issues/13856#issuecomment-262010744

Any issue/PR marked as `netfx-port-consider` ends up opening a bug in TFS.  It doesn't matter whether the issue is open or closed.

**Closed** 2017-07-12 13:47 UTC

**Comment by davkean** [comment] 2017-07-12 14:12
Okay, I meant "how do I find the bug?" as it wasn't linked, but I ended up finding it. 

I've pointed it to this, to add a litte more data, AsyncLocal.SetValue is basically the cause of 2% of all data when you open a solution:

![image](https://user-images.githubusercontent.com/1103906/28121891-e54032ca-675f-11e7-8824-aa8d0b3141f7.png)
