### ISSUE TITLE
How to run Unit tests on Windows run on 32-bit CoreCLR?

### ISSUE THREAD

**Issue by syalachigere** [dotnet/corefx#3206] opened 2015-09-12 18:55 UTC
Is it possible to run corefx tests on 32 bit CoreCLR?

After building corefx, I opened a corefx solution and changed `platform target``to``x86`` but it doesn't work.

**Comment by ellismg** [comment] 2015-09-12 20:46
I doubt that will work at this point.  The problem is part of running the tests is restoring a CoreCLR based runtime and the runtime we restore today is only 64 bit.

I think that the easiest way to change the behavior (I haven't tried to do this) would be to get an enlistment in [dotnet/buildtools](https://github.com/dotnet/buildtools/), revert: https://github.com/dotnet/buildtools/commit/8e386703a31ff7ea594d7b59a41c0be8245e11af, build a private copy of build tools and use the logic described here: https://github.com/dotnet/buildtools/wiki/Local-testing-of-BuildTools-in-another-repo to use your private copy.

Then, rebuilding should cause us to restore a 32 bit test runtime which you can debug.

**Comment by weshaggard** [comment] 2015-09-16 16:23
This is something we will be looking into enabling in the future but as @ellismg points out right now it isn't fully supported.

**Comment by weshaggard** [comment] 2017-01-27 22:12
@joperezr added x86 support for our test runs fairly recently so that is supported now so closing this issue.

**Closed by weshaggard** 2017-01-27 22:12 UTC
Labels: area-Infrastructure, question
