### ISSUE TITLE
UWP F5 tests broken on ARM

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26218] opened 2018-01-08 18:25 UTC
eg https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180108.02/workItem/Canonicalization.Tests/wilogs

```
2018-01-08 07:15:25,947: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\56f3b3d4-ba95-4a90-a2f4-de67da412029\Work\0643d265-c6e2-45c8-9f80-4a0d2f39267b\Unzip>call C:\dotnetbuild\work\56f3b3d4-ba95-4a90-a2f4-de67da412029\Payload\Launcher\WindowsStoreAppLauncher.exe -test appxmanifest.xml Canonicalization.Tests.dll  -xml testResults.xml -notrait category=nonuaptests -notrait category=nonwindowstests  -notrait category=failing 
2018-01-08 07:15:26,040: INFO: proc(54): run_and_log_output: Output: Got manifest file appxmanifest.xml
2018-01-08 07:15:26,165: INFO: proc(54): run_and_log_output: Output: Removing any previous installation...
2018-01-08 07:15:26,181: INFO: proc(54): run_and_log_output: Output: Installing the application...
2018-01-08 07:15:26,963: INFO: proc(54): run_and_log_output: Output: 
2018-01-08 07:15:26,963: INFO: proc(54): run_and_log_output: Output: FAILED 0x80073CFF (To install this application you need either a Windows developer license or a sideloading-enabled system.
2018-01-08 07:15:26,963: INFO: proc(54): run_and_log_output: Output: )

```

@dotnet/dnceng did anything change about the ARM machine setup? They need to have a developer license or sideloading enabled.

cc @safern

**Comment by Chrisboh** [comment] 2018-01-08 18:47
These machines did just get imaged.  @MattGal do you know if the developer license got installed?

**Comment by MattGal** [comment] 2018-01-08 18:54
Filed https://github.com/dotnet/core-eng/issues/2368, will investigate shortly.  It looks like that wasn't  part of the setup scripts when we first stood up machines in early 2017, I'll get the tests working there and fix up the setup script.

**Comment by danmosemsft** [comment] 2018-01-08 19:02
Thanks ! Nice that the test log produced an actionable error.

**Comment by danmosemsft** [comment] 2018-01-10 17:45
fixed!

**Comment by danmosemsft** [comment] 2018-08-03 07:57
@MattGal these ARM tests are all failing again in the same way. eg
https://mc.dot.net/#/product/netcore/30/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180803.01/workItem/Canonicalization.Tests/wilogs

Is it the same issue again - developer license? (or is this the bad C++ runtime again -- I can't find that issue to check what symptoms that had)

**Comment by danmosemsft** [comment] 2018-08-03 07:58
@tommcdon

**Comment by danmosemsft** [comment] 2018-08-03 07:59
It looks like the ILC run tests are failing with -1073741515 == 0xC0000135 == STATUS_DLL_NOT_FOUND which is presumably because the CRT issue is not fixed yet, and is distinct to this failure mode here.

**Comment by MattGal** [comment] 2018-08-03 16:01
@danmosemsft I've moved a copy of the issue to core-eng and will investigate a machine with your tests this morning; I'm suspecting it's our issue since this correlates in time with turning off the old "Seattle" boxes and turning on new ones, which may have not been properly configured.

**Comment by wtgodbe** [comment] 2018-12-28 22:52
@MattGal can this be closed?

**Comment by MattGal** [comment] 2018-12-31 18:03
The problem is not fixed, so that's up to you:  The last UWP ARM run happened on 12/18 and had this problem.  I believe that's when we switched over to YML only and just lost the coverage.  If these tests will end up turned back on in the YML world, you'll need to solve this then, if not feel free to close.

**Comment by ViktorHofer** [comment] 2019-01-05 13:21
Closing as dupe of https://github.com/dotnet/corefx/issues/26218

**Closed by ViktorHofer** 2019-01-05 13:21 UTC
Labels: arch-arm32, area-Infrastructure, bug, os-windows-uwp

**Comment by MattGal** [comment] 2019-01-07 17:00
You closed the bug as a duplicate of itself?

**Comment by mmitche** [comment] 2019-01-07 17:22
If that's the case, we can close LOTS of bugs.  We're done!

**Comment by ViktorHofer** [comment] 2019-01-07 19:18
LOL 😱 thanks Santi!
