### ISSUE TITLE
Regression in System.IO.FileInfo .Net Core 2.1 RC1 Final

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#29784] opened 2018-05-18 13:17 UTC
Repo with PowerShell
- with .Net Core 2.0
```c#
[System.IO.FileInfo]::new('C:\pagefile.sys')

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
              4/18/2018  10:48 AM    11811160064 pagefile.sys

[System.IO.FileInfo]::new('C:\pagefile.sys') | fl

Name           : pagefile.sys
Length         : 11811160064
CreationTime   : 9/15/2015 2:14:30 AM
LastWriteTime  : 4/18/2018 10:48:59 AM
LastAccessTime : 8/24/2016 4:58:08 PM
Mode           :
LinkType       :
Target         :
VersionInfo    : File:             C:\pagefile.sys
                 InternalName:
                 OriginalFilename:
                 FileVersion:
                 FileDescription:
                 Product:
                 ProductVersion:
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:
```
- with .Net Core 2.1 RC1 Final
```powershell
[System.IO.FileInfo]::new('C:\pagefile.sys')

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
                                                 pagefile.sys

[System.IO.FileInfo]::new('C:\pagefile.sys') | fl

Name           : pagefile.sys
Length         :
CreationTime   :
LastWriteTime  :
LastAccessTime :
Mode           :
LinkType       :
Target         :
VersionInfo    :
```

The problem is that only name property is accessable.

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by SteveL-MSFT** [comment] 2018-05-18 15:47
I'm able to repro this and it seems specific to `pagefile.sys`

**Comment by danmosemsft** [comment] 2018-05-18 16:18
@JeremyKuhne ?

**Comment by danmosemsft** [comment] 2018-05-18 17:00
Dupe of #29782

**Comment by danmosemsft** [comment] 2018-05-18 18:45
Dupe as it is the same issue in FillAttributeInfo

**Closed by danmosemsft** 2018-05-18 18:45 UTC
Labels: Servicing-Consider-2.1.1, area-System.IO, bug, tenet-compatibility
