### ISSUE TITLE
[Preview5] JsonSerializer cannot convert boolean to string

### ISSUE THREAD

**Issue by ianjirka** [dotnet/corefx#37740] opened 2019-05-17 02:25 UTC
It converts to a string using newtonsoft.  Workaround is easy, filing a bug as FYI.

```
System.Text.Json.JsonReaderException: The JSON value from [RecaptchaVerificationResponse].success could not be converted to System.String.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException_DeserializeUnableToConvertValue(Type propertyType, Utf8JsonReader& reader, ReadStack& state)
...
```

```csharp
public class RecaptchaVerificationResponse
    {
        public string success {get;set;}
        public DateTime challenge_ts {get;set;}
        public string hostname {get;set;}
        [JsonProperty("error-codes")]
        public string[] error_codes {get;set;}
    }
```

```json
{"success": true,"challenge_ts": "2019-05-17T02:23:27Z","hostname": "testkey.google.com"}
```

**Comment by ahsonkhan** [comment] 2019-05-17 23:26
This is a known limitation of the JsonSerializer, by design. We generally avoid loose types/inferring what types could work between JSON and .NET types and only do "strict" matching.

We are working to provide an extension capability that will let callers write their own converters which is more flexible.

cc @steveharter, @JeremyKuhne

**Comment by ahsonkhan** [comment] 2019-05-17 23:26
Also cc @JamesNK

**Comment by ianjirka** [comment] 2019-05-18 00:31
Makes sense, thank you @ahsonkhan

**Comment by ahsonkhan** [comment] 2019-05-21 20:48
The extension/converter feature is tracked by https://github.com/dotnet/corefx/issues/36639.

Closing as by-design.

**Closed by ahsonkhan** 2019-05-21 20:48 UTC
Labels: area-System.Text.Json
