### ISSUE TITLE
System.Memory; nuget does not add reference on Xamarin (4.5.0-preview2-26406-04)

### ISSUE THREAD

**Issue by jasallen** [dotnet/corefx#29523] opened 2018-05-04 20:02 UTC
Latest prerelease nuget appears to have specific Xamarin listing that do nothing and trump the .NetStandard listings that would otherwise work correctly

**Comment by jasallen** [comment] 2018-05-04 20:08
originally had wrong nuget version.  To be clear: `4.5.0-preview1-26216-02` *does work* on Xamarin, it is `4.5.0-preview2-26406-04` that does not

**Comment by joperezr** [comment] 2018-05-07 21:30
This is by design. Xamarin wants to provide its own implementation for this assembly, which is why we put the placeholder in so that if you reference this project from Xamarin you will get the Inbox implementation provided by them instead of the .NetStandard implementation provided by the package. cc: @marek-safar

**Comment by joperezr** [comment] 2018-05-07 21:37
You can see how we force to use the inbox version if you check the following line on the System.Memory package project.

https://github.com/dotnet/corefx/blob/ccda77cfeb25acbc738b7895cc8cd81cdaf740e2/src/System.Memory/pkg/System.Memory.pkgproj#L10

**Comment by marek-safar** [comment] 2018-05-10 09:47
Yes, this is synchronization issue the preview package needs the preview version of Xamarin which ships the inbox version

**Comment by joperezr** [comment] 2018-05-11 17:18
Closing since this is by design. @jasallen feel free to reopen if you feel necessary.

**Closed by joperezr** 2018-05-11 17:18 UTC
Labels: area-System.Memory, packaging
