### ISSUE TITLE
Win10 WSL at Linux target platform for tests?

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#18247] opened 2017-04-12 00:44 UTC
Is it worth adding [Windows 10 Subsystem for Linux](https://blogs.msdn.microsoft.com/wsl/2017/04/11/testing-the-windows-subsystem-for-linux/) as a test build target?

**Comment by karelz** [comment] 2017-04-12 01:05
Practically/tactically for now, we don't have the time :( (we're lacking coverage even on Nano server and arm64), so we left it up to manual verification by WSL team.

Long-term, I am not sure if we truly need WSL as yet another platform in CoreFX. Given that it is development scenario only and that it should be compatible (in theory) with other distros, we would be testing more the WSL implementation itself than CoreFX. In grand scheme it is goodness. From practical point of view ... it might be under the cut line to retain sanity.

**Comment by danmosemsft** [comment] 2017-04-12 02:11
We'd likely take patches though. Last I heard the WSL team indicated that many of the tests we disabled for WSL no longer need disabling. It would be interesting if someone wanted to remove all those attributes and re-run to see which if any still need them.

**Comment by benaadams** [comment] 2017-04-26 20:51
Should I close this or do you want it for tracking attribute removal?

**Comment by karelz** [comment] 2017-04-26 21:54
If it is the only thing tracking attribute removal, let's keep it opened ...

**Comment by ViktorHofer** [comment] 2018-09-25 12:36
Closing as duplicate of https://github.com/dotnet/corefx/issues/7597

**Closed by ViktorHofer** 2018-09-25 12:36 UTC
Labels: area-Infrastructure, enhancement, os-windows-wsl
