### ISSUE TITLE
DeflateStream decompression throughput is dependent on size of internal buffer

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#28058] opened 2018-03-14 16:54 UTC
We have an internal buffer in `DeflateStream` and its size has significant impact on the throughput of the API.  Currently this buffer is defined by DefaultBufferSize which is [fixed at 8KB](https://github.com/dotnet/corefx/blob/3fca26cedf6c54aabc100e69106fc7e263db7815/src/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L16)

This was brought to my attention by some partner code that re-implemented DeflateStream to get better performance.  The primary difference in their implementation was the size of the backing buffer.

A simple fix would be to expose our buffer size.  Here's a change that does so:
https://github.com/ericstj/corefx/commit/423b9bb0644a432ac565ec1382b571a28012ab8b

I measured our performance in relation to this using a [benchmark](https://gist.github.com/ericstj/0651461ac37b1420097f285148c59c80) (partner code removed).  Here's the result:
```
               Method |     Mean |     Error |    StdDev |
--------------------- |---------:|----------:|----------:|
     <partner-stream> | 26.52 ms | 0.5310 ms | 0.9159 ms |
 DeflateStreamDefault | 42.59 ms | 0.8534 ms | 1.2239 ms |
    DeflateStream32kb | 27.21 ms | 0.5415 ms | 0.5318 ms |
   DeflateStream128kb | 24.76 ms | 0.4891 ms | 0.6007 ms |
   DeflateStream512kb | 22.09 ms | 0.2712 ms | 0.2265 ms |
  DeflateStream1024kb | 22.86 ms | 0.4036 ms | 0.3775 ms |
```

Now this may not be the only / best solution but it does put control in the hands of the caller.  Other things to consider might be some internal heuristic, pipelines, or even exposing the backing DEFLATE alogrithm as [was done with Brotli](https://github.com/dotnet/corefx/issues/25785).

**Comment by ericstj** [comment] 2018-03-14 20:59
@stephentoub mentioned to me:
>>Re: “We wouldn’t want to change the defaults”

> To play devil’s advocate, why not?  The buffer is now pooled; is there a significant downside to increasing the buffer size if a larger size demonstrates significantly better performance?
 
> I’m not against exposing the option of configuring the buffer size, or better yet allowing the creator of the DeflateStream to provide the Memory<byte> to be used, but that requires new API, whereas changing the default doesn’t.

I don’t think one could say that a larger size is universally better here.  I measured one case: a FileStream from a fast disk examining throughput while reading everything at once.  What about a NetworkStream measuring latency?  What about an application that uses many concurrent DeflateStreams and cares about density/memory footprint?  The ASP.NET [issue](https://github.com/dotnet/corefx/issues/12549) shows that people care about density and notice when the GC doesn’t keep up so that seems to be at least one data point towards the latter case.

I do think @stephentoub's suggestion of exposing a Memory<byte> overload is interesting.  Granted that will cause a bit of a cliff since folks need to manage pooling, but maybe its not so bad, and maybe they already care about pooling if they care about this buffer size.

I also think this may be an interesting case to look at WRT pipelines /cc @pakrym

**Comment by stephentoub** [comment] 2018-05-03 15:55
As an aside, note that you can already extract the inflated data at basically equivalent speeds using existing APIs, namely CopyToAsync.

I pulled down @ericstj's changes for comparison, and then also added this to the benchmark:
```C#
[Benchmark]
public void DeflateStreamCopyAll128kb() => CopyAll(new DeflateStream(File.OpenRead(Constants.DataFile), CompressionMode.Decompress, false), 128 * 1024);
[Benchmark]
public void DeflateStreamCopyAll512kb() => CopyAll(new DeflateStream(File.OpenRead(Constants.DataFile), CompressionMode.Decompress, false), 512 * 1024);
[Benchmark]
public void DeflateStreamCopyAll1024kb() => CopyAll(new DeflateStream(File.OpenRead(Constants.DataFile), CompressionMode.Decompress, false), 1024 * 1024);

public void CopyAll(Stream stream, int bufferSize)
{
    using (stream) stream.CopyToAsync(Stream.Null, bufferSize).GetAwaiter().GetResult();
}
```
to use the existing `CopyToAsync` overload that takes a buffer size.  The numbers here thus include the calls to transfer the data to the destination stream, for which I'm just using `Stream.Null` to best match the existing benchmark that reads into the array and then ignores the data.  Here are the results on my machine:
```
                     Method |     Mean |     Error |    StdDev |
--------------------------- |---------:|----------:|----------:|
       DeflateStreamDefault | 40.35 ms | 0.8001 ms | 1.9477 ms |
          DeflateStream32kb | 24.45 ms | 0.4142 ms | 0.3672 ms |
         DeflateStream128kb | 22.07 ms | 0.5883 ms | 1.7254 ms |
         DeflateStream512kb | 19.11 ms | 0.2673 ms | 0.2232 ms |
        DeflateStream1024kb | 18.77 ms | 0.2463 ms | 0.2183 ms |
  DeflateStreamCopyAll128kb | 27.55 ms | 0.5238 ms | 0.5379 ms |
  DeflateStreamCopyAll512kb | 20.99 ms | 0.4246 ms | 0.5054 ms |
 DeflateStreamCopyAll1024kb | 21.81 ms | 0.3906 ms | 0.3654 ms |
```

**Comment by carlossanlop** [comment] 2019-12-18 18:54
Triage:
This is related to the buffer pooling issue: #24083 , we could address them both at the same time. Using CopyTo is a workaround to select the buffer size.

**Comment by carlossanlop** [comment] 2019-12-18 18:54
Duplicate of #24083

**Closed by carlossanlop** 2019-12-18 18:54 UTC
Labels: area-System.IO.Compression, enhancement, tenet-performance
