### ISSUE TITLE
CamelCase not applied to list of KeyValuePair

### ISSUE THREAD

**Issue by vladinvancouver** [dotnet/corefx#41813] opened 2019-10-16 05:05 UTC
CamelCase naming policy is not applied to list of KeyValuePair.

Code to reproduce:

JsonSerializerOptions options = new JsonSerializerOptions()
{
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DictionaryKeyPolicy = JsonNamingPolicy.CamelCase
};
           
Dictionary<string, object> dict = new Dictionary<string, object>();
dict.Add("Item1", "Value1");
dict.Add("Item2", 22);

string json = JsonSerializer.Serialize(dict.ToList(), options);

Console.WriteLine(json);

Actual results:

[
  {
    "Key": "Item1",
    "Value": "Value1"
  },
  {
    "Key": "Item2",
    "Value": 22
  }
]

Expected results:

[
  {
    "key": "Item1",
    "value": "Value1"
  },
  {
    "key": "Item2",
    "value": 22
  }
]

**Comment by safern** [comment] 2019-10-21 21:47
cc: @ahsonkhan

**Comment by layomia** [comment] 2019-10-23 23:40
Duplicate of https://github.com/dotnet/corefx/issues/41309.

**Closed by layomia** 2019-10-23 23:40 UTC
Labels: area-System.Text.Json
