### ISSUE TITLE
DecodeUtf8Prefixed Debug conf

### ISSUE THREAD

**Issue by laanaithossam** [dotnet/corefx#102] opened 2014-11-16 22:37 UTC
Hi,

I cloned recently the Corefx Repo, and i was able to build it using the build.cmd and all tests were Green. 

But when i ran the tests from visual studio 2013 for the System.Reflection.Metadata solution, using the Debug configuration, all tests based on System.Reflection.Internal.EncodingHelper.DecodeUtf8Prefixed method failed, after disassembling the assembly, the code looks like bellow, so the function returns always (null | String.Empty) : 

![image](https://cloud.githubusercontent.com/assets/690254/5063466/2bcbf676-6de8-11e4-8b5e-b824c59db8d0.png)

The code disassembled based on the Release config is shown below :

![image](https://cloud.githubusercontent.com/assets/690254/5063464/0b5cb90c-6de8-11e4-9907-4f038c282889.png)

So, to make this code working, and tests success on both configurations, i updated this function. Now  the results of the disassembled code looks like bellow: 

Debug version : 
![image](https://cloud.githubusercontent.com/assets/690254/5063487/edfb4652-6de8-11e4-9275-e7e2ed6c08b1.png)

Release version : 
![image](https://cloud.githubusercontent.com/assets/690254/5063484/b27ea9fc-6de8-11e4-9fe8-0e9d38d8abe3.png)

So, if you have this same behavior, and this fix is legitim. Let me kwow if i have to push this change.

**Comment by ellismg** [comment] 2015-02-08 08:47
@nguerrera I'm assuming that you're still looking into this.  Let me know if that's not the case.

**Comment by nguerrera** [comment] 2015-02-08 19:11
@ellismg Thanks for bringing this back to my attention.

@laanaithossam Sorry for the delay. I cannot reproduce this using Visual Studio 2013 Update 4. Is it possible that you had a bad build that was still considered 'up-to-date' after the upgrade? Does it still repro for you after a rebuild?

/cc @theoy Any idea what might be happening. Does this look like a (pre-Roslyn) compiler bug that got patched at some point?

**Comment by nguerrera** [comment] 2015-02-14 03:06
@laanaithossam  I am closing this bug because there is no repro available and it only affected debug builds in the single place it was reported. The code generated by both the latest VS 2013 compiler and VS 2015 Preview is correct in all configurations that I've been able to try.

**Closed by nguerrera** 2015-02-14 03:06 UTC
Labels: bug, grabbed by assignee, needs more info, System.Reflection.Metadata

**Comment by nguerrera** [comment] 2015-02-14 03:08
@laanaithossam With that said, if you are still tracking and seeing this and can answer the question about whether you hit it with a full rebuild and the upgraded VS installation, I can gladly reopen and investigate further.
