### ISSUE TITLE
SocketAsyncEventArgs's buffer operations are not correct when the same SocketAsyncEventArgs is used for multile Socket

### ISSUE THREAD

**Issue by linluxiang** [dotnet/corefx#33246] opened 2018-11-05 14:47 UTC
I was trying to fix an unexpected behavior in Olreans and it turns out to be a bug in .net runtime.
The link below is the origin issue that I posted in orleans project.
https://github.com/dotnet/orleans/issues/5160

The behavior was that what I received on the server side was different from what I sent. The data on the receiver side was corrupted.

```
Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://192.168.15.165:30000/279114651 - =====!!: send msg: header length: 150, body length: 16
```
Receiver side
```
12:00:52,019 UTC [63] INFO  Orleans.Runtime.IncomingMessageBuffer -   =======  received header length: 131 bodyLength: 16
12:00:52,020 UTC [63] INFO  Orleans.Runtime.IncomingMessageBuffer -   =======  received header length: 1628480243 bodyLength: -1477026000
```

In the orleans project, it created an ObjectPool for all SocketAsyncEventArgs, so the same SocketAsyncEventArgs instance may be used for a newly accepted socket. When the same SocketAsyncEventArgs was reused, its Buffer still contained the data from previous Socket and SocketAsyncEventArgs.SetBuffer won't change it. If I use Array.Clear to clean all the bytes in the Buffer, then later whenever this SocketAsyncEventArgs instance receives any bytes, the SocketAsyncEventArgs.Buffer will always be empty.

My testing environment was Ubuntu 16.04 LTS and I tried to reproduce it under dotnet-runtime-2.0.9, dotnet-runtime-2.1.5 and dotnet-runtime-2.2-preview 3.

Only in dotnet-runtime-2.1.5 and dotnet-runtime-2.2-preview 3 I could reproduce it. My program worked well on dotnet-runtime-2.0.9.

**Comment by stephentoub** [comment] 2018-11-05 15:03
Can you share an isolate repro that doesn't depend on Orleans?

**Comment by linluxiang** [comment] 2018-11-07 13:35
@stephentoub  Sorry I've tried but I couldn't reproduce it without Orleans. So I guess this is an Orleans Bug? But howcome different runtime versions made different behavior?

**Comment by stephentoub** [comment] 2018-11-07 15:30
> So I guess this is an Orleans Bug? But howcome different runtime versions made different behavior?

It's hard for me to answer that without a repro.  It could be that there's a bug in Sockets and it's just difficult to expose.  It could be that Orleans has a race condition and it's depending on timing that ended up changing due to performance improvements or bug fixes or other such things in Sockets.  It could be that Orleans was depending on some buggy behavior that was fixed in Sockets.  Etc.

**Comment by linluxiang** [comment] 2018-11-08 11:50
@stephentoub  Sorry I've tried but I couldn't reproduce it without Orleans. So I guess this is an Orleans Bug? But howcome different runtime versions made different behavior?

**Comment by stephentoub** [comment] 2018-11-08 11:58
Same answer as yesterday :)

**Comment by karelz** [comment] 2018-11-12 17:47
It may be best to debug into Orleans code, or to ask Orleans experts to help with that.
Closing for now here. If you find there is specific bug in BCL, please give us repro without Orleans and we can reopen. Thanks!

BTW: There can be hundreds of reasons why something works on 1 runtime and fails on another version (and lots of them are not runtime/BCL bugs). Without debugging it, it is premature to speculate what is the root cause.

**Closed by karelz** 2018-11-12 17:47 UTC
Labels: area-System.Net.Sockets, bug, needs more info, os-linux
