### ISSUE TITLE
StringComparer not working as expected on Linux

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/corefx#17052] opened 2017-03-13 17:18 UTC
The following test works on Windows but not on Linux (RHEL 7.2 or Ubuntu 16.04):

Assert.AreEqual(0, StringComparer.CurrentCultureIgnoreCase.Compare("ss", "ß"));

Our Microsoft consultant Ben Gimblett has confirmed it and requested that we raise it as an issue here for follow-up.

We understand that .Net Core uses Windows's own comparison service, which is not available on Linux operating systems. How would one perform these culture aware operations on .Net core - irrespective of operating system?

**Comment by tarekgh** [comment] 2017-03-13 17:43
this can be by design as we are using the OS for such features. I'll need to look first if there is anything else missing in our wrappers.

**Comment by migajek** [comment] 2018-03-20 19:21
I'm afraid the problem is wider.
I was struggling to find out why my app doesn't work on .net core on Ubuntu. 
I've been digging through librariers, but was able to narrow it down to just this 

ladies, gentlemen ... behold:

```
me@system:/tmp/netcoredemo$ more Program.cs
using System;

namespace netcoredemo
{
    class Program
    {
        static void Main(string[] args)
        {
            var s = "Id";
            Console.WriteLine($"current / ignore {s.Equals("id", StringComparison.CurrentCultureIgnoreCase)}");
            Console.WriteLine($"invariant / ignore {s.Equals("id", StringComparison.InvariantCultureIgnoreCase)}");
            Console.WriteLine($"culture: {System.Globalization.CultureInfo.CurrentCulture.Name}");
        }
    }
}
me@system:/tmp/netcoredemo$ dotnet run
current / ignore False <--- !!!!!!!!!!
invariant / ignore True
culture: en-US-POSIX
```

**Comment by migajek** [comment] 2018-03-20 19:59
setting the culture at the beginning of the program fixes the issue 

```
System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en-US");
```

**Comment by tarekgh** [comment] 2018-03-20 23:26
@ChristophB125 you can use the CompareOptions.IgnoreNonSpace to get comparison of "ß" evaluated as equal to "ss". CompareOptions can be passed to string APIs, CompareInfo APIs and also you can create StringComparer in 2.1 version using the following code:

```C#
        string sb = "ß";
        string ss = "ss";

        StringComparer sc1 = StringComparer.Create(CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace);
        Console.WriteLine(sc1.Compare(sb, ss));
```

@migajek en_US_POSIX is very special locale and its string sorting behavior is special too. This is why you got this surprising result when you used it. switching to en-US as you did will give you the logical results.

**Comment by tarekgh** [comment] 2018-03-20 23:48
I am closing this issue, feel free to send any more questions or issue. thanks all.

**Closed by tarekgh** 2018-03-20 23:48 UTC
Labels: area-System.Globalization, bug

**Comment by migajek** [comment] 2018-03-21 00:09
@tarekgh so the right question is .. why does .net core detect current culture as en-US-POSIX? 
I cannot seem to find any information on where does current culture come from on Linux.

LANG env variable is en_US.UTF-8 ...

```
root@system:~/netcoredemo# dotnet run
current / ignore False
invariant / ignore True
culture: en-US-POSIX
root@system:~/netcoredemo# echo $LANG
en_US.UTF-8
```

**Comment by tarekgh** [comment] 2018-03-21 00:39
@migajek 

You may look at https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/locale.cpp#L123 for how we get the default user locale. in short, we call ICU function ```uloc_getDefault()``` to get the default locale.

**Comment by tarekgh** [comment] 2018-03-21 00:43
you may check if the values of the environment variables LC_MESSAGES and LC_ALL in your system.

**Comment by migajek** [comment] 2018-03-21 07:17
@tarekgh thank you, this seems to work as expected then as `uloc_getDefault` returns en_US_POSIX for me.
I'll look into system configuration
