### ISSUE TITLE
Manual_CertificateSentMatchesCertificateReceived_Success failed on Windows CI

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#9212] opened 2016-06-07 05:46 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2007/consoleFull#-4102119967b4762c-faac-47f0-8268-9f6835e4535e

```
System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 3, reuseClient: True) [FAIL]
16:28:34         System.Net.Http.HttpRequestException : An error occurred while sending the request.
16:28:34         ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
16:28:34         Stack Trace:
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34   Starting:    System.Threading.Tasks.Tests
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(381,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(172,0): at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(88,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__2>d.MoveNext()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(106,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass5_2.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__4>d.MoveNext()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\Common\tests\System\Net\Http\LoopbackServer.cs(57,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
16:28:34               at System.Threading.Tasks.Task.Execute()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.ClientCertificates.cs(98,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>d__5.MoveNext()
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34            --- End of stack trace from previous location where exception was thrown ---
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34            ----- Inner Stack Trace -----
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
16:28:34               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
16:28:34               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
16:28:34            D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(845,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
```

**Comment by davidsh** [comment] 2016-06-07 14:07
cc: @stephentoub These are the new client certificate tests that you added.

**Comment by stephentoub** [comment] 2016-06-07 14:09
> These are the new client certificate tests that you added.

And they've been passing, on both Windows and Unix.  We shouldn't rule out a product bug.

**Comment by CIPop** [comment] 2016-06-16 18:03
Duplicate of #4171.

**Closed by CIPop** 2016-06-16 18:03 UTC
Labels: os-windows, System.Net
