### ISSUE TITLE
NetworkAddressChanged event hangs process on Mac

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#41740] opened 2019-10-11 21:09 UTC
# Repro steps

1. Install 3.0 RTM
2. `dotnet new console`
3. Replace Program.cs with the following:

```C#
using System;

namespace MacMinimal
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            System.Net.NetworkInformation.NetworkChange.NetworkAddressChanged += (sender, e) => {
                
            };
        }
    }
}
```

# Expected Result

The process should exit.

# Actual Result

The process does not exit.

# Details

Thread dumps indicate that this line is the problem:

https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.OSX.cs#L184

We believe that this Thread should be marked as background so it doesn't block the process exiting.

## Real world cases

We found this when we noticed that applications which use AppInsights don't close when they would normally exit on a Mac. This isn't noticed normally because the normal workflow for AspNetCore apps is that when you want the server to exit you send Ctrl-C.

CC @danmosemsft @karelz @davidfowl

**Comment by karelz** [comment] 2019-10-11 21:21
@wfurt can you please take a look?

**Comment by danmosemsft** [comment] 2019-10-11 21:25
It should be background. I looked at all the othre managed threads we start, and found two others that look like they should be set to background as well.

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L180
https://github.com/dotnet/corefx/blob/ec1ab377f9dfa2daa379df4eb22fbe73ebd3aa69/src/System.Net.Requests/src/System/Net/TimerThread.cs#L477

**Comment by wfurt** [comment] 2019-10-14 19:19
For the timer, we set IsBackground = true inside of ThreadProc. For the SystemProcess, it seems like we explicitly call `Join()`. In this case I think user is in charge when they execute  new process. I posted PR for NetworkAddressChanged. That change is simple and it should be easy to port to maintenance branches. It also hangs with 2.1 so it is not 3.0 regression. 
Workaround would be to unregister handler using `NetworkAddressChanged -=` but that may not be practical for lambda functions.

**Comment by danmosemsft** [comment] 2019-10-15 02:57
> For the SystemProcess, it seems like we explicitly call Join(). In this case I think user is in charge when they execute new process.

I think in some cases ShellExecuteExW can jam and in that case you may well want Ctrl-C to work. For example, if your file exists but the extension is not registered with an app, the shell will pop a dialog:
```c#
            var psi = new ProcessStartInfo() { UseShellExecute = true, FileName = @"c:\\temp\\foo.baz" };
            psi.ErrorDialog = true;
            var p = new Process();
            p.StartInfo = psi;
            var t = System.Threading.Thread.CurrentThread;
            p.Start(); // pops dialog
```

Having said the above, despite the ShellExecuteExW thread definitely not being Background, Ctrl-C does seem to work. I tried to debug it, but when I do that Ctrl-C doesn't work. @jkotas can you educate me why ?

I think it is best to just mark this thread background rather than rationalizing about whether it is ever needed.

**Comment by danmosemsft** [comment] 2019-10-15 02:59
(You are right about TimerThread. I had assumed IsBackground could not be set after the thread starts, just like setting the apartment)

**Comment by jkotas** [comment] 2019-10-15 03:22
>  I tried to debug it, but when I do that Ctrl-C doesn't work

Debugger tries to intercept Ctrl-C. The behavior that you are seeing may be a bug or a feature - I do not know.

**Comment by danmosemsft** [comment] 2019-10-15 03:36
I guess I meant - in the absence of debugger, why does Ctrl-C terminate successfully when this managed thread is waiting and it's not Background.

**Comment by jkotas** [comment] 2019-10-15 04:08
The default Ctrl-C handler behavior is to exit the process. (E.g. from https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler : Initially, the handler list for each process contains only a default handler function that calls the ExitProcess function.)

**Comment by danmosemsft** [comment] 2019-10-15 04:54
Oh - my bad - I thoroughly confused myself due to mention of Ctrl-C at the top. Ctrl-C always works, background or not.

My original observation stands -- if I run "process.Start" in a Background thread, it will potentially hang because (if UseShellExecute==true) we will spawn a non background thread to do the potentially indefinite call into ShellExecuteEx. We should mark the spawned thread as background so this does not hang.

**Comment by wfurt** [comment] 2019-10-15 05:30
I can try to craft some test with example above. That can also be separate change to keep this small for back-porting.

**Comment by danmosemsft** [comment] 2019-10-21 17:53
Just noticed this got closed by the master fix. @ryanbrandenburg do you believe this should be backported to 3.1? The risk is very low.

**Comment by davidfowl** [comment] 2019-10-21 18:41
Yep

**Comment by danmosemsft** [comment] 2019-10-21 18:52
Alright, I threw up a port. https://github.com/dotnet/corefx/pull/41960

**Comment by danmosemsft** [comment] 2019-10-21 22:05
ported

**Closed by danmosemsft** 2019-10-21 22:05 UTC
Labels: area-System.Net, bug
