### ISSUE TITLE
PostNonRewindableContentUsingAuth_PreAuthenticate_Success failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8426] opened 2016-05-10 11:13 UTC
"The handle is invalid" error.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1074/consoleText
```
System.Net.Http.Functional.Tests.PostScenarioTest.PostNonRewindableContentUsingAuth_PreAuthenticate_Success(serverUri: http://corefx-net.cloudapp.net/Echo.ashx?auth=basic&user=user1&password=password1) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.Http.WinHttpException : The handle is invalid
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(207,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostUsingAuthHelper>d__23.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(149,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostNonRewindableContentUsingAuth_PreAuthenticate_Success>d__21.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1331,0): at System.Net.Http.WinHttpHandler.InternalSendRequestAsync(WinHttpRequestState state)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(843,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__102.MoveNext()
```

**Comment by davidsh** [comment] 2016-05-26 19:25
Moving post RTM.

**Comment by davidsh** [comment] 2016-06-17 16:37
Closing this since it is a dupe of the root issue in #9228

**Closed by davidsh** 2016-06-17 16:37 UTC
Labels: System.Net
