### ISSUE TITLE
Can StreamWriter buffers be rented?

### ISSUE THREAD

**Issue by Wraith2** [dotnet/corefx#35797] opened 2019-03-05 22:00 UTC
Doing text to binary conversions often ends up using StreamWriter because it's much easier than using the encoding api directly. StreamWriter uses char and byte buffers internally which are created in the [Init](https://github.com/dotnet/corefx/blob/327d8ed428b40491b499cad4d4114af4fa3f8f30/src/Common/src/CoreLib/System/IO/StreamWriter.cs#L158) method, and while you can specify the buffer size you can't direct it to use/reuse a specific buffer. 

It looks like the buffers are fully contained and could be fairly easily changed from allocating to renting from the ArrayPool. @benaadams did start working on something much more ambitious than this in https://github.com/dotnet/corefx/pull/23727 but ultimately closed the branch. Is there any reason that the simple approach of renting in Init and returning in the internal disposal function would be a bad idea?

/cc @JeremyKuhne

**Comment by JeremyKuhne** [comment] 2019-03-05 22:18
We don't pull in a shared buffer in the streams as they have asynchronous APIs. The concern is that streams get disposed with pending writes. The buffer could be re-rented before those writes complete. We couldn't guard for that without tanking perf.

**Comment by Wraith2** [comment] 2019-03-05 22:29
Ah, i thought it was too obvious to be missed but couldn't see the reason. That should only be possible with a non-awaited async operation right?

**Comment by Wraith2** [comment] 2019-03-15 19:34
In the case of an async call am I right to think that you'd just need to detect that the async operation was still in flight and defer disposal until it completed. I appreciate that it wouldn't be good in general performance terms to do that in the bcl but It might be justifiable in a specific use case I have.

**Comment by benaadams** [comment] 2019-03-15 23:02
Yes, the issue is holding a pooled buffer at class lifetime rather than operation lifetime. At class lifetime you are starving the buffer pool, but potential not doing any work with the buffer; just sitting on it. At operation lifetime, its at least active during that time.


The issue with StreamWriter was when trying to scope the buffer to minimum lifetime (e.g. return after flush) it had a perf hit.

**Comment by stephentoub** [comment] 2019-03-19 21:49
Looks like the question has been answered.  Closing.

**Closed by stephentoub** 2019-03-19 21:49 UTC
Labels: area-System.IO
