### ISSUE TITLE
ReadOnlySpan<T> debug view error

### ISSUE THREAD

**Issue by Sharpiro** [dotnet/corefx#25499] opened 2017-11-25 22:57 UTC
VS 15.5.0 Preview 4.0
System.Memory 4.5.0-preview1-25925-02

The error occurs when viewing debug information of the "readonlySpan" variable.

repro:
```
var stringData = "hello Steve";
var readonlySpan = stringData.AsReadOnlySpan();
```

error:
```
Specified cast is not valid.

at System.SpanDebugView`1[[System.Char, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(ReadOnlySpan`1 collection)
```

**Comment by jkotas** [comment] 2017-11-26 14:52
#14376

**Comment by KrzysztofCwalina** [comment] 2017-11-28 17:39
@ahsonkhan, what's the plan if we cannot fix the debugger before we ship System.Memory? Would we live or remove the proxy? If we leave it (hoping that the debugger will catch up), should/could we convert the exception to something more explanatory?

**Comment by ahsonkhan** [comment] 2017-11-29 03:10
I don't know if we can convert the exception to something more explanatory, if we leave the SpanDebugView as is.

If we explicitly throw a meaningful exception in the SpanDebugView then we would have to revert that when the VS debugger catches up.

cc @plnelson  

Calling ToArray calls the JIT intrinsics and that is resulting in the debugger view error.
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/ReadOnlySpan.cs#L316
```C#
Span.CopyTo<T>(ref Unsafe.As<byte, T>(ref destination.GetRawSzArrayData()), ref _pointer.Value, _length);
```

**Comment by ahsonkhan** [comment] 2017-12-04 23:48
Closing as duplicate of https://github.com/dotnet/corefx/issues/14376

**Closed by ahsonkhan** 2017-12-04 23:48 UTC
Labels: area-System.Memory
