### ISSUE TITLE
HttpClient.Post sends separate TCP packets for Header and Body

### ISSUE THREAD

**Issue by calvin-pietersen** [dotnet/corefx#29080] opened 2018-04-13 03:35 UTC
This is a general issue with .net I am assuming.

Using Microsoft Message Analyzer, I can see that post data using the HttpClient is being sent in two tcp packets. One for the header, then one for the post body. This data could easily fit into one packet, however it is being split into two. I have explicitly turned on nagling and expect 100 continue off using the ServicePointManager, though, it doesn't seem to help.

```
public void TestRequest()
    {
        var uri = new Uri("http://www.webscantest.com/");
        ServicePointManager.Expect100Continue = false;
        ServicePointManager.UseNagleAlgorithm = true;
        var p = ServicePointManager.FindServicePoint(uri);
        p.Expect100Continue = false;
        p.UseNagleAlgorithm = true;
        HttpClient client = new HttpClient();
        client.DefaultRequestHeaders.Add("Connection", "close");

        var values = new Dictionary<string, string>
        {
            { "thing1", "hello" },
            { "thing2", "world" }
        };

        var content = new FormUrlEncodedContent(values);

        var response = client.PostAsync("http://www.webscantest.com/", content, CancellationToken.None).Result;
    }
```
I raised this on [stackoverflow](https://stackoverflow.com/questions/49727720/c-sharp-httpclient-post-force-single-packet/49788340#49788340) and did some research to find the problem.

**Comment by stephentoub** [comment] 2018-04-13 04:40
Are you able to repro this with .NET Core 2.1 Preview 2?  I wouldn't think so.

**Comment by davidsh** [comment] 2018-04-17 20:28
```c#
        ServicePointManager.Expect100Continue = false;
        ServicePointManager.UseNagleAlgorithm = true;
        var p = ServicePointManager.FindServicePoint(uri);
        p.Expect100Continue = false;
        p.UseNagleAlgorithm = true;
```

This code from the above example is a no-op on .NET Core.  In general, .NET Core doesn't support ServicePointManager/ServicePoint classes.  They aren't compatible with the HTTP stack(s) in .NET Core:

And the referenced StackOverflow article refers to the .NET Core 1.x, 2.0 HTTP implementation which uses WinHTTP on Windows. However, .NET Core 2.1 is shipping a new HTTP stack written in all managed code. While it still won't support the ServicePointManager/Service classes, it should have better performance. And depending on request header/body sizes, the data would be coalesced into a smaller (perhaps) single TCP packet(s).

**Comment by davidsh** [comment] 2018-04-17 20:37
I can confirm that using .NET Core 2.1 Preview 2 (which uses the SocketsHttpHandler by default) will use a single TCP packet for this repro case:

![image](https://user-images.githubusercontent.com/7684835/38895276-74768de4-4244-11e8-9908-ee46d832212a.png)

**Comment by davidsh** [comment] 2018-04-17 20:41
Since this is fixed now in .NET Core 2.1, I will close this issue now.

cc: @karelz

**Closed by davidsh** 2018-04-17 20:41 UTC
Labels: area-System.Net.Http, enhancement, tenet-performance

**Comment by stephentoub** [comment] 2018-04-17 21:05
Thanks for validating, @davidsh.

**Comment by calvin-pietersen** [comment] 2018-04-20 06:27
Sorry for the delayed response @davidsh. Looks good with .Net Core 2.1. SocketsHttpHandler now solves this issue. Thank you for the quick response.
