### ISSUE TITLE
Latest version of System.Reflection.Emit is missing DynamicMethod.DefineParameter

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#31675] opened 2018-08-09 18:03 UTC
The latest version of https://www.nuget.org/packages/System.Reflection.Emit/ is 4.3.0, released November 2016. It seems that the method [has been defined since .NET Core 1.0.0](https://github.com/dotnet/coreclr/blob/abbb8f685929c7aeaa087dae46fedc1bc2af4b17/src/mscorlib/src/System/Reflection/Emit/DynamicMethod.cs#L779). Why is it missing from the NuGet package and can it be added back?

**Comment by jkotas** [comment] 2018-08-09 18:30
Duplicate of https://github.com/dotnet/corefx/issues/29715

**Closed by jkotas** 2018-08-09 18:30 UTC
Labels: area-System.Reflection.Emit
