### ISSUE TITLE
XmlSerializerOutputFormatter can't serialize DataSets with object (sql_variant) columns

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/corefx#29560] opened 2018-05-07 23:22 UTC
_From @SWarnberg on May 7, 2018 14:27_

#### Bug:
The following exception is thrown when a DataSet is serialized with the **XmlSerializerOutputFormatter**, and the DataSet contains a column of type "xs:anyType".
```
There was an error generating the XML document. Invalid name character in 'xmlns:xs'. The ':' character, hexadecimal value 0x3A, cannot be included in a name.
```
#### Steps to reproduce or link to a repro project:

1. Create a Controller with an Action that returns a DataSet.
2. The Action must be configured to return xml. For instance by using the Produces("application/xml") attribute.
3. Add **XmlSerializerOutputFormatter** to the OutputFormatters collections in the Startup method.
4. Create and return a DataSet that returns a column of type xs.anyType. For instance, by executing the following SQL query: 
`"select SERVERPROPERTY ( 'ServerName' ) AS ServerName"`

#### Version of Microsoft.AspNetCore.All:
2.0.7

_Copied from original issue: aspnet/Mvc#7741_

**Comment by yujayee** [comment] 2018-05-30 17:44
@mkArtakMSFT Do you have any updates on this?

**Comment by huanwu** [comment] 2018-05-31 18:55
@mkArtakMSFT

**Comment by huanwu** [comment] 2018-05-31 18:55
@mkArtakMSFT Please reopen it if you can repro it.

**Comment by mkArtakMSFT** [comment] 2018-05-31 19:04
Hi @yujayee. Sorry, I didn't see these notifications. You should rather engage with the person who had filed the original issue, rather than me.  That would be @SWarnberg!

**Comment by yujayee** [comment] 2018-06-01 01:52
@mkArtakMSFT I didn't follow all the steps to create the repro because I'm not familiar with aspnet mvc. I only did step 4 to create this dataset and directly serialize it with XmlSerializer and I didn't see any issues. Could you guys help create a simple repo directly related to serialization so I can investigate further?

**Comment by SWarnberg** [comment] 2018-06-01 07:50
I can't believe it would be that hard to reproduce. It has nothing to do with ASP .NET.  
I'm attaching a quick code snippet that will reproduce the problem.
[DataSetSerializationProblem.zip](https://github.com/dotnet/corefx/files/2061624/DataSetSerializationProblem.zip)

**Comment by yujayee** [comment] 2018-06-04 18:48
The repro doesn't call XmlSerializer. Moving this issue to area System.Data. 
We did some investigation with customer's repro and find out the problem is probably in [`XmlDataTreeWriter.XmlDataRowWriter(DataRow row, string encodedTableName)` Line 3048](http://source.dot.net/#System.Data.Common/System/Data/xmlsaver.cs,3048) .
`WriteAttributeString(string localName, string value)` passes in the localName "xmlns:xs", then it throws exception when check this localName.
BTW, this issue also exists on full framework.

**Comment by AfsanehR** [comment] 2018-07-10 18:10
updated @SWarnberg 's sample repro to a non SqlClient dependent repro in [here](https://gist.github.com/AfsanehR/58d9561daf24bfbeff81cbf844f28037): 

Requesting the area owners to take on this issue. Please use the suggestions @krwq  mentioned in [this pr](https://github.com/dotnet/corefx/pull/30757) as fix.

**Comment by krwq** [comment] 2018-07-19 20:23
Per conversation in the PR (starting here: https://github.com/dotnet/corefx/pull/30757#issuecomment-406103196) this is a System.Data failure

**Comment by divega** [comment] 2019-02-25 18:56
@AfsanehR are you still pursuing this issue for 3.0? It seems from https://github.com/dotnet/corefx/pull/30757#issuecomment-406103196 that you know the fix.

cc @ajcvickers

**Comment by AfsanehR** [comment] 2019-02-26 16:26
@divega Sure. I will revisit the issue and send a PR.

**Comment by stephentoub** [comment] 2019-07-16 14:44
@AfsanehR, this is still marked 3.0.  Is it really intended for 3.0?

**Comment by cheenamalhotra** [comment] 2019-07-16 18:41
Hi @stephentoub 

I'm taking over this issue and will submit the PR soon.

**Closed** 2019-07-18 22:45 UTC
Labels: area-System.Data, bug
