### ISSUE TITLE
System.Collections.Concurrent.Tests not producing testResults.xml in UapAot

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#22385] opened 2017-07-18 18:47 UTC
This tests haven't produced testResults.xml in Debug-x64 and Release-x64 for UapAot in the past days.

I tried to repro locally but wasn't lucky. I just missed to use the Helix repro tool, but hadn't have time for that.

**Comment by AtsushiKan** [comment] 2017-07-19 15:11
One test never terminates. The only machine that I had that repros the hang is a crappy VM running WIndows RS3. May be the windows version, maybe it's the speed but either way, it reliably passes (quickly) or reliably hangs.

`-method System.Collections.Concurrent.Tests.ConcurrentQueueTests.MultipleProducerConsumer_AllItemsTransferred
`

Disabling conditionally:
https://github.com/dotnet/corefx/pull/22439

**Comment by joshfree** [comment] 2017-07-20 17:10
@tijoytom could you help get a repro for @AtsushiKan?

**Comment by AtsushiKan** [comment] 2017-07-20 17:13
This is likely something related to threading or tasks on RS3 vs. RS2. It should be looked at by someone in that space.

**Comment by safern** [comment] 2017-07-20 17:15
cc: @kouvel @AntonLapounov who have context in threading and tasks

**Comment by tijoytom** [comment] 2017-07-20 17:34
@AntonLapounov Can you take a look?

**Comment by danmosemsft** [comment] 2017-08-07 05:59
@AntonLapounov are you investigating?
/cc @joshfree

**Comment by AntonLapounov** [comment] 2017-08-07 18:14
I have not been able to reproduce this failure so far.

**Comment by safern** [comment] 2017-08-07 19:00
@AtsushiKan mentioned that the only way that he could repro was by using an RS3 machine: https://github.com/dotnet/corefx/issues/22385#issuecomment-316418873

And he disabled the test in: https://github.com/dotnet/corefx/pull/22439

**Comment by AntonLapounov** [comment] 2017-08-07 22:07
@safern I re-enabled the test by removing the lines from #22385 and still cannot reproduce the issue neither on RS2 nor on RS3 (UWPDogFood-d15prerel-26803_3009-Enterprise image).

**Comment by danmosemsft** [comment] 2017-08-07 23:42
Helix machines were just now updated to rs_prerelease.170805-2131. If it still reproes, you could grab an image (dev test labs) for that particular build.

**Comment by danmosemsft** [comment] 2017-08-08 20:18
@safern I don't see this test failing in https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Filc~2F/build/20170808.01
withe the new OS version

does that mean we can close this

**Comment by AntonLapounov** [comment] 2017-08-08 20:24
@danmosemsft The test is still disabled for UapAot in the repo; I enabled it in my machine only.

**Comment by safern** [comment] 2017-08-08 22:46
@AntonLapounov would it be worth enabling it temporarily in master branch to see if it repro in the next builds? Since you can't repro locally in an RS2 nor RS3 machine, might be worth givinig it a try. If it reproes then you could use the repro tool.

**Comment by danmosemsft** [comment] 2017-08-10 17:01
+1 for that suggestion.

**Comment by safern** [comment] 2017-08-10 21:39
Thanks @AntonLapounov for re-enabling the test.

**Comment by safern** [comment] 2017-08-10 23:23
So we got what we wanted, it just hung again: 

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170810.02/workItem/System.Collections.Concurrent.Tests/wilogs

**Comment by AntonLapounov** [comment] 2017-08-12 01:53
I used Helix repro tool, but still cannot reproduce it on my RS3 machine.

**Comment by safern** [comment] 2017-08-14 23:53
:( Maybe logging in into a helix machine? @MattGal could you help us repro this? This seems very consistent in the daily runs.

**Comment by adityamandaleeka** [comment] 2017-08-15 19:05
I have been able to repro this behavior locally, and am investigating it. I'll assign the issue to myself.

**Comment by safern** [comment] 2017-08-15 22:02
Thanks @adityamandaleeka

**Comment by adityamandaleeka** [comment] 2017-08-16 02:32
I had a chance to look at this, and this is my current hypothesis:

The test that hangs (`MultipleProducerConsumer_AllItemsTransferred`) has a `ConcurrentQueue<int>`. It creates a bunch of tasks: some tasks that dequeue from the queue and maintain a running sum, and some other tasks that enqueue numbers on the queue. My hypothesis (and what seems to be occurring on the 1-proc machine where I can repro this) is that the tasks that enqueue are being starved and don’t get to run since the tasks that dequeue just keep trying to dequeue until the number of things they’ve dequeued is the total amount.

The sequence numbers in the segment slots and the layout of the queue itself seem to support my hypothesis.

cc: @kouvel

**Comment by stephentoub** [comment] 2017-08-16 02:40
> and what seems to be occurring on the 1-proc machine where I can repro this

Am I remembering correctly that the thread pool used in uapaot has a more limited thread injection policy than the one in coreclr?  The test runs multiple times with varying numbers of producers/consumers:
```C#
        [InlineData(1, 4, 1024)]
        [InlineData(4, 1, 1024)]
        [InlineData(3, 3, 1024)]
        public void MultipleProducerConsumer_AllItemsTransferred(int producers, int consumers, int itemsPerProducer)
```
If the pool might have fewer than 5 threads and never inject another, then I'd hypothesize your hypothesis is a good one :)

**Comment by adityamandaleeka** [comment] 2017-08-16 21:31
@stephentoub I think that's what's happening. I haven't looked at this code before, but it appears that we rely on the Windows threadpool for uapaot, and I guess it may be conservative about injecting new threads. In this particular case, the dequeue Tasks are just hogging cycles, which may be part of the problem. I'll try to find out more about the heuristics the Windows thread pool uses.

I'm not sure yet what the right way to fix this is (without making major changes to the thread pool logic).

**Comment by kouvel** [comment] 2017-08-16 21:40
My limited understanding is that the Windows thread pool compensates very well for blocking tasks. For CPU-bound tasks, it is not obliged to inject more threads. Having not looked at the code involved, would adding a Sleep(1) in the dequeue tasks on the test side help? I assume they're spinning for work and a periodic wait state is in order and that would hopefully help the thread pool inject threads to compensate for the blocking.

**Comment by adityamandaleeka** [comment] 2017-08-16 21:46
@kouvel We can try doing that to hopefully get the test passing, but is there anything we should do on the product side for people who hit this issue in real usage? I assume cases like this work fine on non-uapaot scenarios because we have different thread pool logic there (with hill climbing and all the misc. tuning things we do) that potentially can prevent bugs like this.

**Comment by kouvel** [comment] 2017-08-16 22:00
It's reasonable to expect that busy-spinning starves other threads. If busy-spinning in the test is the only issue, I think fixing that is sufficient. A thread pool can't be expected to compensate for busy-spinning because it typically can't tell the difference between that and long-running CPU-bound work where it wouldn't make sense to add more threads. The CoreCLR thread pool compensates for busy-spinning only because it doesn't know the difference between long-ruuning CPU-bound work and blocking work. If it knew the difference, it wouldn't compensate for CPU-bound work.

**Comment by adityamandaleeka** [comment] 2017-08-16 22:06
I agree. I'll try adding the sleep when I get some time.

**Comment by adityamandaleeka** [comment] 2017-08-18 00:58
I confirmed that even adding a Sleep(1) fixes the issue on my repro machine. Just sent a PR.

**Comment by adityamandaleeka** [comment] 2017-08-18 02:23
So @stephentoub raised concerns in the PR which moved my opinion on this back to where it was yesterday 😄. Ideally, we'll find a way to address this in such a way that code out in the wild that depends on busy waiting for new work doesn't break.

**Comment by kouvel** [comment] 2017-08-18 04:15
Maybe I was too quick in looking at the test change, I guess it doesn't have to sleep every iteration, only when it fails to find work and maybe with some sort of a backoff scheme. But if a sleep(1) at any point would defeat the test then another thought is to use separate threads instead of the thread pool.

**Comment by stephentoub** [comment] 2017-08-18 11:46
> another thought is to use separate threads instead of the thread pool

Yeah, that sounds like the right solution.

**Comment by adityamandaleeka** [comment] 2017-08-18 22:19
I just opened another PR. I couldn't reactivate the previous one since I modified branch history after it was closed.

**Comment by adityamandaleeka** [comment] 2017-08-21 19:21
Fixed in master and uwp6.0. Closing issue.

**Closed by adityamandaleeka** 2017-08-21 19:21 UTC
Labels: area-System.Threading, test-run-uwp-ilc
