### ISSUE TITLE
Test failure: System.Diagnostics.Process.Tests

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/corefx#28630] opened 2018-03-30 00:34 UTC
(I'm new, so maybe I'm totally missing something, but I'm following the instructions as best I can and I keep getting test errors.)

So I (successfully) ran the build, made some changes to some libraries and started experiencing some issues. I wanted to get back to a good state, so I did

> git checkout master
> clean -all
> build-tests.cmd     # Failed with lots of errors, cause I should have run build first.
> build.cmd              # Success
> build-tests.cmd

Error:

> D:\Repos\dotnet\corefx\dir.traversal.targets(77,5): error : (No message specified) [D:\Repos\dotnet\corefx\src\tests.builds]
> 
> Build FAILED.
> 
> D:\Repos\dotnet\corefx\Tools\tests.targets(492,5): warning :    System.Diagnostics.Process.Tests  Total: 254, Errors: 0, Failed: 1, Skipped: 2, Time: 68.485s [D:\Repos\dotnet\corefx\src\System.Diagn
> ostics.Process\tests\System.Diagnostics.Process.Tests.csproj]
> D:\Repos\dotnet\corefx\Tools\tests.targets(492,5): warning MSB3073: The command "D:\Repos\dotnet\corefx\bin/tests/System.Diagnostics.Process.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd D:\Re
> pos\dotnet\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [D:\Repos\dotnet\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests.csproj]
> D:\Repos\dotnet\corefx\Tools\tests.targets(500,5): error : One or more tests failed while running tests from 'System.Diagnostics.Process.Tests' please check D:\Repos\dotnet\corefx\bin/tests/System.D
> iagnostics.Process.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [D:\Repos\dotnet\corefx\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests.csproj]
> D:\Repos\dotnet\corefx\dir.traversal.targets(77,5): error : (No message specified) [D:\Repos\dotnet\corefx\src\tests.builds]
>     2 Warning(s)
>     2 Error(s)

"testResults.xml" does not exist in the specified location.

With build.cmd taking 8 minutes and build-tests.cmd taking 14 minutes, debugging this blindly just isn't going to work. (On a Quad-core, 16 GB RAM, SSD)

I'm currently on
> commit 22d053f88c619199b38da4a098e47a087cf98c56 (HEAD -> master, origin/master, origin/HEAD)
> Author: Jan Kotas <jkotas@microsoft.com>
> Date:   Wed Mar 28 15:46:00 2018 -0700
> 
>     Delete workaround for ComImport types on Unix (#28518)
> 
>     https://github.com/dotnet/coreclr/issues/16804 is fixed. We do not need the workaround anymore.

Ideas? In the meantime, I'll pull the latest and then run clean (do I need to do this?), build and build-tests again.

**Comment by danmosemsft** [comment] 2018-03-30 17:35
Yeah quickest thing is `clean -all` (I think that is kill Roslyn process + `git clean -fdx`) and then do build.cmd then buildtests.cmd.

You can build/test in individual libraries. This is what we do after running build* from the root once. See https://github.com/dotnet/corefx/blob/8e842fa29e14694cca96c6e39a38199c55a3a02e/Documentation/project-docs/developer-guide.md#tests

When you pull, you sometimes will pull down a pointer to new dependencies. At that point you may find you need to go build from the root again, if building at the leaf has issues.

**Comment by MisinformedDNA** [comment] 2018-03-30 17:54
So I already had run

```
git checkout master
clean -all
build-tests.cmd # Failed with lots of errors, cause I should have run build first.
build.cmd # Success
build-tests.cmd
```

Would running `build-tests.cmd` out of order really cause issues?

**Comment by MisinformedDNA** [comment] 2018-03-30 18:13
Also, are these instructions still valid?

From https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows

> Note: If you have both VS 2017 and 2015 installed, you need to copy DIA SDK directory from VS 2015 installation into VS 2017 (VS installer bug). The build script will detect the situation and tell you what to do

I tried that and then it failed earlier in the build instead of in build-tests.

**Comment by danmosemsft** [comment] 2018-03-30 20:18
@MisinformedDNA If you don't see a message about DIA in the console, you can disregard that. 

> Would running build-tests.cmd out of order really cause issues?

I don't know, but it is usually quicker to jsut clean build while I do something else, rather than try to rationalize what it may have done.

**Comment by MisinformedDNA** [comment] 2018-03-30 21:40
OK, I spun up a Win10 VM on Azure. Installed VC2017 will all necessary components and pulled the repo. Ran `build.cmd` and got:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\Microsoft.Win32.Registry.AccessControl\ref\Microsoft.W
> in32.Registry.AccessControl.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\Microsoft.Win32.Registry\ref\Microsoft.Win32.Registry.
> csproj]
>   System.Buffers -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Buffers\4.0.2.0\netstandard\System.Buffers.
>   dll
>   Microsoft.Win32.SystemEvents -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\Microsoft.Win32.SystemEvents\4.0.0.0
>   \netstandard\Microsoft.Win32.SystemEvents.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.CodeDom\ref\System.CodeDom.csproj]
>   System.Collections.Immutable -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Collections.Immutable\1.2.3.0
>   \netstandard\System.Collections.Immutable.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\CoreFx.Private.TestUtilities\ref\CoreFx.Private.TestUt
> ilities.csproj]
>   System.ComponentModel.Annotations -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.ComponentModel.Annotatio
>   ns\4.2.0.0\netstandard\System.ComponentModel.Annotations.dll
>   System.ComponentModel.Composition -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.ComponentModel.Compositi
>   on\4.0.0.0\netstandard\System.ComponentModel.Composition.dll
>   System.Data.DataSetExtensions -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Data.DataSetExtensions\4.0.0
>   .0\netstandard\System.Data.DataSetExtensions.dll
>   System.Data.Odbc -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Data.Odbc\4.0.0.0\netstandard\System.Data
>   .Odbc.dll
>   System.Data.SqlClient -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Data.SqlClient\4.3.1.0\netstandard\S
>   ystem.Data.SqlClient.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Diagnostics.EventLog\ref\System.Diagnostics.Eve
> ntLog.csproj]
>   System.Diagnostics.DiagnosticSource -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Diagnostics.Diagnostic
>   Source\4.0.3.0\netstandard\System.Diagnostics.DiagnosticSource.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Configuration.ConfigurationManager\ref\System.C
> onfiguration.ConfigurationManager.csproj]
>   System.Diagnostics.PerformanceCounter -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Diagnostics.Performa
>   nceCounter\4.0.0.0\netstandard\System.Diagnostics.PerformanceCounter.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.DirectoryServices.Protocols\ref\System.Director
> yServices.Protocols.csproj]
>   System.Drawing.Common -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Drawing.Common\4.0.0.0\netstandard\S
>   ystem.Drawing.Common.dll
>   System.IO.Packaging -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.IO.Packaging\4.0.3.0\netstandard\Syste
>   m.IO.Packaging.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.DirectoryServices.AccountManagement\ref\System.
> DirectoryServices.AccountManagement.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
>   System.IO.Ports -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.IO.Ports\4.0.1.0\netstandard\System.IO.Por
>   ts.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Management\ref\System.Management.csproj]
>   System.Net.Http.WinHttpHandler -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Net.Http.WinHttpHandler\4.0
>   .3.0\netstandard\System.Net.Http.WinHttpHandler.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.IO.FileSystem.AccessControl\ref\System.IO.FileS
> ystem.AccessControl.csproj]
>   System.Memory -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Memory\4.0.1.0\netstandard\System.Memory.dll
>   System.Reflection.Context -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Reflection.Context\4.0.3.0\netst
>   andard\System.Reflection.Context.dll
>   System.Numerics.Vectors -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Numerics.Vectors\4.1.4.0\netstanda
>   rd\System.Numerics.Vectors.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Net.WebSockets.WebSocketProtocol\ref\System.Net
> .WebSockets.WebSocketProtocol.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.IO.Pipes.AccessControl\ref\System.IO.Pipes.Acce
> ssControl.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.DirectoryServices\ref\System.DirectoryServices.
> csproj]
>   System.Reflection.DispatchProxy -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Reflection.DispatchProxy\4
>   .0.4.0\netstandard\System.Reflection.DispatchProxy.dll
>   System.Runtime.Caching -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Runtime.Caching\4.0.0.0\netstandard
>   \System.Runtime.Caching.dll
>   System.Reflection.TypeExtensions -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Reflection.TypeExtensions
>   \4.1.2.0\netstandard\System.Reflection.TypeExtensions.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Security.AccessControl\ref\System.Security.Acce
> ssControl.csproj]
>   System.Runtime.CompilerServices.Unsafe -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Runtime.CompilerSer
>   vices.Unsafe\4.0.4.0\netstandard\System.Runtime.CompilerServices.Unsafe.dll
>   System.Security.Cryptography.Cng -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Security.Cryptography.Cng
>   \4.3.0.0\netstandard\System.Security.Cryptography.Cng.dll
>   System.Security.Cryptography.Pkcs -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Security.Cryptography.Pk
>   cs\4.0.3.0\netstandard\System.Security.Cryptography.Pkcs.dll
>   System.Security.Cryptography.OpenSsl -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Security.Cryptography
>   .OpenSsl\4.1.0.0\netstandard\System.Security.Cryptography.OpenSsl.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Reflection.Metadata\ref\System.Reflection.Metad
> ata.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Security.Cryptography.Xml\ref\System.Security.C
> ryptography.Xml.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Security.Permissions\ref\System.Security.Permis
> sions.csproj]
>   System.Security.Cryptography.ProtectedData -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Security.Crypto
>   graphy.ProtectedData\4.0.3.0\netstandard\System.Security.Cryptography.ProtectedData.dll
>   System.Security.Principal.Windows -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Security.Principal.Windo
>   ws\4.1.1.0\netstandard\System.Security.Principal.Windows.dll
>   System.ServiceModel.Syndication -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.ServiceModel.Syndication\4
>   .0.0.0\netstandard\System.ServiceModel.Syndication.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.ServiceProcess.ServiceController\ref\System.Ser
> viceProcess.ServiceController.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Threading.AccessControl\ref\System.Threading.Ac
> cessControl.csproj]
>   System.Text.Encoding.CodePages -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Text.Encoding.CodePages\4.1
>   .1.0\netstandard\System.Text.Encoding.CodePages.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(
> 1603,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The n
> ame of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and imple
> ments the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project
>  file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15
> .0\bin" directory. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Threading.Channels\ref\System.Threading.Channel
> s.csproj]
>   System.Threading.Tasks.Dataflow -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Threading.Tasks.Dataflow\4
>   .6.3.0\netstandard\System.Threading.Tasks.Dataflow.dll
>   System.Threading.Tasks.Extensions -> C:\Users\diosloco\Documents\Repos\corefx\bin\ref\System.Threading.Tasks.Extensio
>   ns\4.2.0.0\netstandard\System.Threading.Tasks.Extensions.dll

Any ideas?

**Comment by danmosemsft** [comment] 2018-03-30 23:31
Hmm maybe this fix helps? https://stackoverflow.com/questions/47797510/the-getreferencenearesttargetframeworktask-task-was-not-found

Seems like a VS issue.

**Comment by MisinformedDNA** [comment] 2018-03-31 01:49
Build succeeded, tests failed.

> C:\Users\diosloco\Documents\Repos\corefx\Tools\tests.targets(492,5): warning :    System.Drawing.Common.Tests  Total: 4491, Errors: 0, Failed: 2, Skipped: 0, Time: 102.167s [C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\System.Drawing.Common.Tests.csproj]
> C:\Users\diosloco\Documents\Repos\corefx\Tools\tests.targets(492,5): warning MSB3073: The command "C:\Users\diosloco\Documents\Repos\corefx\bin/tests/System.Drawing.Common.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd C:\Users\diosloco\Documents\Repos\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\System.Drawing.Common.Tests.csproj]
> C:\Users\diosloco\Documents\Repos\corefx\Tools\tests.targets(500,5): error : One or more tests failed while running tests from 'System.Drawing.Common.Tests' please check C:\Users\diosloco\Documents\Repos\corefx\bin/tests/System.Drawing.Common.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\diosloco\Documents\Repos\corefx\src\System.Drawing.Common\tests\System.Drawing.Common.Tests.csproj]
> C:\Users\diosloco\Documents\Repos\corefx\dir.traversal.targets(77,5): error : (No message specified) [C:\Users\diosloco\Documents\Repos\corefx\src\tests.builds]
>     2 Warning(s)
>     2 Error(s)
> 
> Time Elapsed 00:40:36.88
> Command execution failed with exit code 1.

So close.

**Comment by MisinformedDNA** [comment] 2018-03-31 02:50
Is it normal for tests to fail? Should this just not concern me?

Ah, nevermind, it's part of a known issue: https://github.com/dotnet/corefx/issues/26637

**Comment by wtgodbe** [comment] 2018-04-02 18:50
@MisinformedDNA closing as duplicate of https://github.com/dotnet/corefx/issues/26637, and looks like you have https://github.com/dotnet/corefx/issues/28721 to track the bug in question. Please re-open if I've misinterpreted.

**Closed by wtgodbe** 2018-04-02 18:50 UTC
Labels: area-System.Diagnostics.Process

**Comment by danmosemsft** [comment] 2018-04-02 18:59
As for this

> Is it normal for tests to fail? Should this just not concern me?

No it is not normal for tests to fail: if you clone and build and run tests they should all pass. Sometimes folks have machines that are slightly different somehow, and then we track down the problem. Or, not every test is 100% stable and again we should fix that. However unless you're planning on working on Drawing, you shouldn't be too impeded.
