### ISSUE TITLE
Core does't read the server certificate

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#25817] opened 2017-12-09 16:36 UTC
@hammond-of-texas commented on [Fri Dec 08 2017](https://github.com/dotnet/core/issues/1142)

# Issue Title

Core doesn't read the server certificate

# General

In general, a simple request like this will work in .Net:

        static void Main(string[] args)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://www.sbb.ch");
            HttpWebResponse response = (HttpWebResponse) request.GetResponse();
            X509Certificate cert = request.ServicePoint.Certificate;
        }

The same thing will fail in core 2.0 with a "System.PlatformNotSupportedException: 'Operation is not supported on this platform.'" exception.

---

@richlander commented on [Sat Dec 09 2017](https://github.com/dotnet/core/issues/1142#issuecomment-350486532)

PTAL @davidsh

**Comment by davidsh** [comment] 2017-12-09 17:57
Duplicate of #25816

**Closed by davidsh** 2017-12-09 17:57 UTC
