### ISSUE TITLE
Does the upcoming .net core 2.0 support System.Drawing fully in Linux?

### ISSUE THREAD

**Issue by ZhiqiangTao** [dotnet/corefx#18649] opened 2017-04-20 01:36 UTC

**Comment by danmosemsft** [comment] 2017-04-20 04:15
@ZhiqiangTao .NET Core 2.0 does not support System.Drawing on any platform. (Although it does offer a small number of primitives commonly used in the System.Drawing namespace). Porting it to .NET Core (ideally for all platforms) is something we're considering for post 2.0, depending on demand.

Can you tell me a little about what you would use it for?

@karelz do we have an issue tracking porting S.D? If not we can use this one.

**Comment by ZhiqiangTao** [comment] 2017-04-20 05:00
I just use S.D to load the width, height and other based properties,  to resize the image, and so on...

**Comment by danmosemsft** [comment] 2017-04-20 05:12
How important is the existing API to you, vs. having equivalent functionality through some other library? Eg., do you have much existing code or rely on existing libraries that use the API?

**Comment by karelz** [comment] 2017-04-20 06:32
@danmosemsft I don't see anything about System.Drawing in [port-to-core](https://github.com/dotnet/corefx/labels/port-to-core) - it's probably just in your offline list ... let's keep this issue

**Comment by ViktorHofer** [comment] 2017-04-20 09:51
We have kind of an issue for that: https://github.com/dotnet/corefx/issues/5921

Unfortunately nobody did an API proposal for it

**Comment by karelz** [comment] 2017-04-20 15:05
Ooops, missed that - closing as dupe of #5921, thanks for finding it @ViktorHofer!

**Closed by karelz** 2017-04-20 15:05 UTC
Labels: area-System.Drawing, enhancement, port-to-core

**Comment by danmosemsft** [comment] 2017-04-20 15:22
That one is about new API, not S.D right?

**Comment by ViktorHofer** [comment] 2017-04-20 15:34
> to create system drawing primitives - such as in DotImaging.Primitives2D

It's definitely about bringing the existing APIs back but more in a more portable way than in current netfx. I think that issue fits.

**Comment by karelz** [comment] 2017-04-21 00:33
Not sure what you meant @ViktorHofer by "issue fits". Given this is about porting and the other is about new APIs, I would be ok to reopen - I'll leave it to area owners.
@alexperovich thoughts?

**Comment by alexperovich** [comment] 2017-04-21 19:06
I don't think we will ever actually "port" the majority of System.Drawing to .net core. We may expose the same API surface with a different implementation at some point but that is not something we could ever get to in time for 2.0

**Comment by mellinoe** [comment] 2017-04-21 19:10
.NET Core does not support System.Drawing natively, except for the geometric primitives.

There is a "third-party" library for System.Drawing compatibility produced by @qmfrederik. Perhaps he has some more pointers for you. https://github.com/CoreCompat/CoreCompat. I say "third-party" because the code is based on mono's version of System.Drawing.

**Comment by danmosemsft** [comment] 2017-04-21 19:25
Please let's have 2 issues tracking proposals:
(1) bring back same API as far as possible, with whatever implementation, working cross platform
(2) add equivalent library
They are distinct.

**Comment by qmfrederik** [comment] 2017-04-21 20:22
@ZhiqiangTao I'm the package maintainer for CoreCompat.System.Drawing, and it brings Mono's version of System.Drawing to .NET Core.

It has the same API surface. You can use it to load the width, height and other based properties, to resize the image, and so on..., using the same API's you have on full .NET.

Feel free to give it a try, and let me know if it works for you.

**Comment by ZhiqiangTao** [comment] 2017-04-27 02:32
I have used the the "third-party" library , and it can works well.
thanks for everyone.

**Comment by dougajmcdonald** [comment] 2017-11-21 11:56
@qmfrederik I've tried CoreCompat.System.Drawing and it unfortunately still errors for me with if I try to use the core compat `ImageFormat` as a param for other methods:

![image](https://user-images.githubusercontent.com/1190042/33071305-ed565902-ceb2-11e7-8560-1525391739f3.png)

**Comment by qmfrederik** [comment] 2017-11-21 12:09
@dougajmcdonald Can you try the latest version of System.Drawing.Common instead?

**Comment by dougajmcdonald** [comment] 2017-11-21 12:15
Certainly I gave that a whirl but still seem to a similar error. Is this likely to a problem with the library I'm providing the parameter to?

![image](https://user-images.githubusercontent.com/1190042/33071985-90ff2f00-ceb5-11e7-8058-fbbbc74275cb.png)

**Comment by danmosemsft** [comment] 2017-11-21 14:44
@safern facade but working for @dougajmcdonald here...?

**Comment by mafav** [comment] 2017-11-30 03:47
same issue as @dougajmcdonald

**Comment by safern** [comment] 2017-11-30 17:44
Assigned to me, so that I take a look this week. Thanks for reporting it, it seems like a missing facade.

**Comment by safern** [comment] 2017-12-22 01:12
@dougajmcdonald or @mafav I can't repro this issue locally, could you please share the project where you're hitting this? I want to see what you're targeting, what APIs you're using and the package version that you're using.

**Comment by dougajmcdonald** [comment] 2018-01-23 09:08
@safern I'm not 100% sure I can remember which project I was working on when I saw this (soz) will have a look about for any evidence and drop a reply if I can find any.
