### ISSUE TITLE
Add DebuggerDisplay/DebuggerTypeProxy to JSON reader / writer / dom

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#36768] opened 2019-04-10 17:05 UTC
Tracking issue for creating the debugger visualizer of JSON reader/writer/document

As an example of how to get started, see https://github.com/dotnet/corefx/blob/95fa11b014ff7eeffdb325a7a0b3aa3afacc2f4a/src/Common/src/CoreLib/System/Span.cs#L19-L20

**Comment by ahsonkhan** [comment] 2019-04-10 18:42
Related: https://github.com/dotnet/corefx/issues/34663

**Comment by layomia** [comment] 2019-04-11 00:06
Duplicate of https://github.com/dotnet/corefx/issues/34663.

**Closed by layomia** 2019-04-11 00:06 UTC
Labels: area-System.Text.Json, enhancement
