### ISSUE TITLE
Reference assemblies should not be loaded for execution

### ISSUE THREAD

**Issue by Abexdatl** [dotnet/corefx#24200] opened 2017-09-21 20:38 UTC
I am getting this build error after upgrading to .net core 2

'Could not load file or assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken= ***' or one of its dependencies. 
Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)'

**Comment by danmosemsft** [comment] 2017-09-21 23:03
@terrajobst @ericstj does this fall into one of the categories in https://github.com/dotnet/announcements/issues/31 ?

**Comment by danmosemsft** [comment] 2017-09-21 23:04
Ah, it's https://github.com/dotnet/corefx/issues/23229. @Abexdatl there are workarounds there.

**Comment by karelz** [comment] 2017-09-22 03:44
Duplicate of #23229.

**Comment by Abexdatl** [comment] 2017-09-22 04:21
Non of the workarounds in the issue you identified as "duplicate" resolved my issue ..... so far.

Well ... we can also say .net core is of to a good start 😉

**Comment by danmosemsft** [comment] 2017-09-22 07:10
@ericstj can you help here?

**Comment by ericstj** [comment] 2017-09-22 15:50
Perhaps: What type of project is it?  Can you share some more information about the repro?  (perhaps a msbuild /flp:diag log as well)

This is different based on the version I see of System.Data.Common, that one isn't coming from the netstandard2 support package in desktop (it contains 4.2.0.0).  4.1.0.0 shipped in the System.Data.Common 4.3.0 package.  Regardless of the cause there is a bad-tool involved here that's loading a reference assembly for execution we just need to track it down to find the appropriate workaround.

**Comment by Abexdatl** [comment] 2017-09-22 18:39
It is an ASP.NET CORE project . It references other class library projects. All the class libraries build fine . The issue is in the web project.

**Comment by ericstj** [comment] 2017-09-22 19:11
When you say ASP.NET Core project is this project targeting .NETCore or is it targeting .NETFramework (desktop).  Can you share a build log for the failing project and the project.assets.json from the obj folder?

**Comment by Abexdatl** [comment] 2017-09-22 20:03
Application details
   **Target fw** - 4.6.1
   **output type** - console application 

**Build log** : Below is the error info from the build log. I replaced the project name and replaced by *** to remove propitiatory info 

**==================================**
LC : error LC0000: 'Could not load file or assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
or one of its dependencies. Reference assemblies should not be loaded for execution. 
 They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)'
5>Done building project "***.Web.csproj" -- FAILED.
**=============================**

Finally on the asset file , it contains so much propitiatory info and I cannot put it in public .

**Comment by ericstj** [comment] 2017-09-27 16:10
Hmm, so this is desktop (net461).  Are you referencing the System.Data.Common package in the net461 project?  Is that project using PackageReference or packages.config?

The thing that makes this different from the referenced issue is that System.Data.Common 4.1.0.0 reference assembly only shipped in the System.Data.Common *package* version 4.3.0.  That same package has a `net451` ref, which should be preferred by NuGet and is *not* a reference assembly.

Perhaps if you can share just part of your log that shows where System.Data.Common is coming from in order to inform my theory that might be enough.  Barring that an isolated repro would really help.

**Comment by weshaggard** [comment] 2018-01-18 01:00
@Abexdatl are you still having an issue here?

**Closed** 2018-02-07 23:36 UTC
Labels: area-Infrastructure

**Comment by sansjunk** [comment] 2019-02-08 13:33
I have run into a possibly similar issue when the License Compiler (LC.exe) tool invokes my class for fetching the licensing information. This works fine for .NET Framework build but not for .NET Core. I looked at the referenced #23229 but none of the workarounds seem to apply.

Here is the full error:

> Properties\licenses.licx(1): error LC0004: Exception occurred creating type 'Acme.Licensing.License, Acme.Documents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fc8cb3ab6a24df63' System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Could not load file or assembly 'file:///C:\Users\AcmeUser\.nuget\packages\system.security.permissions\4.5.0\ref\netstandard2.0\System.Security.Permissions.dll' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.

**Comment by ericstj** [comment] 2019-02-08 14:24
@sansjunk can you open the issue on the LC task in https://github.com/Microsoft/msbuild?  This looks to me like a problem in the core version of MSBuild.

**Comment by ericstj** [comment] 2019-02-08 14:42
Related: https://github.com/Microsoft/msbuild/issues/2006
