### ISSUE TITLE
Unable to enable TCP KeepAlive in System.Net.HttpClient

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#42044] opened 2019-10-23 17:30 UTC
Unable to enable TCP KeepAlive in System.Net.HttpClient. It is off by default, doesn't have its own option to turn it on, and the generic API that did this in Framework does nothing.

https://github.com/dotnet/corefx/blob/a62579502cb9e86b761c2249d0d04af3d827b3a3/src/System.Net.ServicePoint/src/System/Net/ServicePointManager.cs#L214

We are currently discussing what ridiculously overweight thing to do about this.

**Comment by stephentoub** [comment] 2019-10-23 17:41
The plan to address this is to expose one or more delegates/interfaces to let you configure the socket employed by SocketsHttpHandler or to replace the stream entirely.  That's tracked by https://github.com/dotnet/corefx/issues/35404.
cc: @scalablecory

**Comment by karelz** [comment] 2020-01-07 21:40
Duplicate of #35404

**Closed by karelz** 2020-01-07 21:40 UTC
Labels: area-System.Net
