### ISSUE TITLE
MemoryExtensions ToUpper / ToLower don't properly support overlapping buffers

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#34799] opened 2019-01-24 08:14 UTC
Per the devdoc on `MemoryExtensions.ToUpper` / `ToLower` and similar methods, these APIs are supposed to behave correctly if the source and destination buffers partially overlap.

```cs
/// <remarks>If the source and destinations overlap, this method behaves as if the original values are in
/// a temporary location before the destination is overwritten.</remarks>
```

However, I don't think any shipped version of `ToUpper` or `ToLower` ever had this behavior. At least, the most recent version just blasts forward without checking to see if the buffers are overlapped.

```cs
Span<char> chars = new char[] { 'a', 'b', 'c', 'd' };
((ReadOnlySpan<char>)chars).Slice(0, 2).ToUpperInvariant(chars.Slice(1, 2));
Console.WriteLine(chars.ToString()); // prints "aAAd", not "aABd"
```

We should update the documentation to reflect the actual behavior or change the implementation to satisfy the documented behavior, whichever is appropriate.

**Comment by ahsonkhan** [comment] 2019-01-29 03:20
Hmm, that's strange. These tests would have failed if overlapping spans don't work:
https://github.com/dotnet/corefx/blob/db7daabdb592da062d8a80f27bbad1178c364530/src/Common/tests/Tests/System/StringTests.cs#L5185

FYI, here is when we added the comment + tests: https://github.com/dotnet/corefx/pull/27193/commits/3131eefab18053725521cbdb98c7b7c6d93b1671

**Comment by ahsonkhan** [comment] 2019-02-14 02:24
It turns out the above example just happens to work on .NET Core 3.0 due to recent changes like https://github.com/dotnet/coreclr/pull/20275 since the input is small.

On .NET Core 2.1, the above example would fail (i.e. print aAAd).

We do not support overlapping spans for ToUpper/ToLower and hence we should change the documentation.

For example, a test like this fails:

```C#
[Fact]
public static void ToUpperOverlappingLarger()
{
    var expectedSource = new char[4] { 'a', 'A', 'B', 'C' };
    var expectedDestination = new char[4] { 'A', 'B', 'C', 'D' };
    var expectedWhole = new char[5] { 'a', 'A', 'B', 'C', 'D' };

    char[] a = { 'a', 'b', 'c', 'd', 'e' };

    string s1 = new string(a, 0, 4);                
    Assert.Equal(expectedDestination, s1.ToUpperInvariant().ToArray());

    var source = new ReadOnlySpan<char>(a, 0, 4);
    var destination = a.AsSpan(1, 4);
    Assert.Equal(source.Length, source.ToUpperInvariant(destination));
    Assert.Equal(expectedWhole, a.ToArray());   // Char[] ['a', 'A', 'B', 'B', 'D']
    Assert.Equal(expectedDestination, destination.ToArray()); // Char[] ['A', 'B', 'B', 'D']
    Assert.Equal(expectedSource, source.ToArray()); // Char[] ['a', 'A', 'B', 'B']
}
```

**Comment by GSPP** [comment] 2019-02-15 12:37
Can overlapping be determined reliably? If it can be, it should be part of argument validation.

**Comment by ektrah** [comment] 2019-02-15 15:24
@GSPP Yes. There is an `Overlaps` extension method in `MemoryExtensions`:

https://github.com/dotnet/corefx/blob/f078da3a4ddcb99cbb26b59fb67f59fdfb200548/src/Common/src/CoreLib/System/MemoryExtensions.cs#L1461-L1465

**Comment by ahsonkhan** [comment] 2019-02-15 21:09
> Can overlapping be determined reliably? If it can be, it should be part of argument validation.

We should definitely consider it. However, one thing we should measure is potential performance regression that might be introduced due to this check, especially for operations on small payloads. Given that its going through `TextInfo` anyway, it may not matter all that much. We did recently change the methods being called to statics to avoid the overhead: https://github.com/dotnet/coreclr/pull/17890

cc @jkotas, @tarekgh

**Comment by jkotas** [comment] 2019-02-15 23:17
> owever, one thing we should measure is potential performance regression that might be introduced due to this check, especially for operations on small payloads

This is very cheap check. I am not worried about its cost.

**Comment by MarcoRossignoli** [comment] 2019-02-27 11:18
> We should definitely consider it.

@ahsonkhan  do you mean check and throw exception?

**Comment by ahsonkhan** [comment] 2019-02-27 21:15
> do you mean check and throw exception?

Yes.

**Comment by ahsonkhan** [comment] 2019-06-15 00:43
@adamsitnik, are you still planning on working on this issue?

**Comment by adamsitnik** [comment] 2019-06-17 07:35
@ahsonkhan I was hoping to do it when I was flying from Seattle to Europe, but I did not. I have unassigned myself

**Comment by ahsonkhan** [comment] 2019-06-18 22:57
@GSPP, @ektrah, @MarcoRossignoli, are any of you interested in working on this issue?

**Comment by MarcoRossignoli** [comment] 2019-06-19 13:58
Some specs methods to fix
```cs
public static int ToLower(this ReadOnlySpan<char> source, Span<char> destination, CultureInfo culture)
public static int ToLowerInvariant(this ReadOnlySpan<char> source, Span<char> destination)
public static int ToUpper(this ReadOnlySpan<char> source, Span<char> destination, CultureInfo culture)
public static int ToUpperInvariant(this ReadOnlySpan<char> source, Span<char> destination)
```
Should throw `internal static void ThrowNotSupportedException(ExceptionResource resource)` with new `ExceptionResource.NotSupported_SpanOverlappedOperation` ?
Error message `Operation on overlapped buffers not supported`?
Tests on corefx `System.Memory`?

**Comment by ahsonkhan** [comment] 2019-06-22 01:38
> Some specs methods to fix

Yes.

> Should throw `internal static void ThrowNotSupportedException(ExceptionResource resource)` with new `ExceptionResource.NotSupported_SpanOverlappedOperation` ?
Error message `Operation on overlapped buffers not supported`?

I would throw `ArgumentException` (or maybe `InvalidOperationException`, but probably not `NotSupportedException`). The message seems fine to me. 
Maybe `This operation is invalid on overlapping buffers.`

> Tests on corefx `System.Memory` close to https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Memory/IndexAndRange.cs#L38?

Most of the ToLower/ToUpper tests live next to the StringTests so that would probably be better.
https://github.com/dotnet/corefx/blob/42ecf717478504fd7cc072f3586c6edd1ba57daa/src/Common/tests/Tests/System/StringTests.cs#L5040-L5053

I would also be OK with them being in a new file next to since they are specifically about spans/overlapping (which isn't relevant in the string case):
https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ReadOnlySpan/Overlaps.cs

Let me know if you are planning to submit a fix by Monday, because we want to get the fix in before 6/26. Otherwise, just give me a heads up and I will try to address this issue myself.

Thanks.

**Comment by MarcoRossignoli** [comment] 2019-06-22 07:26
I'll work to have a fix by monday, if something unexpected will happen I'll tell you asap.

**Comment by ahsonkhan** [comment] 2019-06-25 02:55
Fixed in https://github.com/dotnet/corefx/pull/38778 / https://github.com/dotnet/corefx/pull/38782

**Closed by ahsonkhan** 2019-06-25 02:55 UTC
Labels: area-System.Memory, bug
