### ISSUE TITLE
The buffers supplied to a function was too small

### ISSUE THREAD

**Issue by ietvijay** [dotnet/corefx#31611] opened 2018-08-06 14:59 UTC
Hi ,

I am getting this error while trying to make https get call using HTTPClient api. The issue is consistent and happens when i run a batch that makes https call . I am using HttpClient from Assembly System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

The buffers supplied to a function was too small

The buffers supplied to a function was too small ----|---- STACKTRACE :   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

**Comment by davidsh** [comment] 2018-08-06 15:48
What version of Windows are you using?

What version of .NET Core are you using?

This sounds like a dupe of #7812.

**Comment by ietvijay** [comment] 2018-08-06 17:25
I am using Windows 7 Enterprise  Service Pack 1 and .Net core 2.0

**Comment by davidsh** [comment] 2018-08-06 17:30
>I am using Windows 7 Enterprise Service Pack 1 and .Net core 2.0

Windows 7 is affected by the issues that are described in #7812. Windows 7 as the client would be affected by certain TLS/SSL cipher suites that the server might be negotiating.  The problems described in #7812 are actually a bug in Windows OS due to certain TLS protocol cipher suites.

What HTTPS servers are you connecting to?  There are certain workarounds that can be done on the client or server to mitigate the problem depending on what TLS cipher suites are being used by the server. Or you will need to run on latest Windows 10 OS.  Please see #7812 for details.

We recommend you also try .NET Core 2.1 which might help.

**Comment by ietvijay** [comment] 2018-08-06 17:39
I am hitting third party Http REST api so no control over that.  My dev box is windows 7. but i have to test it at local first so what is the work around for Client side? 
is this issue fixed in .Net Core 2.1 on windows 7?

Thanks!

**Comment by davidsh** [comment] 2018-08-06 17:46
>what is the work around for Client side?

Work-around is detailed in #7812. It involves disabling certain cipher suites.  See: https://github.com/dotnet/corefx/issues/7812#issuecomment-305848835

>is this issue fixed in .Net Core 2.1 on windows 7?

If the problem is really #7812 then .NET Core 2.1 probably won't help.  But it is recommended anyways since it uses a newer, higher performance HTTP stack.

**Comment by ietvijay** [comment] 2018-08-06 18:00
Thanks David! I am trying to see best working solution for me. 
Is this issue also present on .Net Full frameworks on win 7? or this is specific to .Net Core frameworks?

**Comment by davidsh** [comment] 2018-08-06 18:10
>Is this issue also present on .Net Full frameworks on win 7? or this is specific to .Net Core frameworks?

The root cause is due to a bug in Windows OS SCHANNEL component.  So, yes, it can occur with .NET Framework or .NET Core.  The bug was fixed in Windows 10.

**Comment by karelz** [comment] 2018-08-15 02:08
Duplicate of #7812

**Closed by karelz** 2018-08-15 02:08 UTC
Labels: area-System.Net.Http
