### ISSUE TITLE
SqlDataSourceEnumerator is not supported in System.Data.SqlClient

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#32874] opened 2018-10-17 23:02 UTC
From standard created by [marqdouj](https://github.com/marqdouj) : dotnet/standard#851  

The .NET System.Data.Sql namespace contains both the SqlNotificationRequest and SqlDataSourceEnumerator classes. .NET Standard System.Data.SqlClient contains the SqlNotificationRequest class but did not include the SqlDataSourceEnumerator class.  I would like to suggest adding the SqlDataSourceEnumerator class to .NET Standard System.Data.SqlClient.

**Comment by jnm2** [comment] 2018-10-17 23:06
`SqlDataSourceEnumerator` sends out a UDP broadcast and then blocks the thread for a fixed amount of time, collecting any response messages from listening servers. I wrote my own version which was based on UdpClient and provided an ObservableCollection which was much nicer to use. 
I preferred to immediately receive the collection to use in UI binding and to keep listening indefinitely, rather than stopping after an arbitrary duration and not being able to show *any* servers until it stops listening. If you'd consider it, having something like this in the BCL would be fantastic!

**Comment by divega** [comment] 2019-05-15 00:36
@saurabh500, @terrajobst wondering if this is issue is just a duplicate of https://github.com/dotnet/corefx/issues/20323, or if this one has more to do with .NET Standard that .NET Core (sorry, I find the text a bit difficult to parse).

**Comment by saurabh500** [comment] 2019-05-15 00:39
Yeah, this is a dupe of #20323

**Comment by divega** [comment] 2019-05-16 00:25
Closing as duplicate of #20323.

**Closed by divega** 2019-05-16 00:25 UTC
Labels: area-System.Data.SqlClient, port-to-core
