### ISSUE TITLE
Reflection breaking change in Microsoft.NETCore.App 1.1.0

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/corefx#13897] opened 2016-11-22 23:18 UTC
One of the packages that `Microsoft.NETCore.App` brings in has a breaking change in 1.1.0 compared to 1.0.1 that causes an exception when using `Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript`:
>{System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at Roslyn.Utilities.ReflectionUtilities.CreateDelegate[T](MethodInfo methodInfo)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.Build[T](Compilation compilation, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Repro.Program.Main(String[] args) in C:\Users\ansvyryd\Documents\Visual Studio 2015\Projects\Repro\src\Repro\Program.cs:line 16}

[Repro13897.zip](https://github.com/dotnet/corefx/files/607804/Repro13897.zip)

```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            var script = "new Point {X = 1, Y = -2}";
            var result = CSharpScript.EvaluateAsync<Point>(
                script,
                ScriptOptions.Default
                    .WithReferences(typeof(Point).GetTypeInfo().Assembly)
                    .AddImports(typeof(Point).GetTypeInfo().Namespace))
                .GetAwaiter().GetResult();

            Console.WriteLine($"{result.X} {result.Y}");
        }
    }

    public class Point
    {
        public int X { get; set; }
        public int Y { get; set; }
    }
```

**Comment by karelz** [comment] 2016-11-23 17:20
Did you try to get it under a debugger to find out which code starts passing invalid data or behaves incorrectly? It would be a great help.

**Comment by AndriySvyryd** [comment] 2016-11-23 23:04
@karelz There isn't enough information in the debugger to say for sure, because the assemblies are optimized. My best guess is that the `TypeInfo.GetDeclaredMethod(string)` has different behavior. Roslyn uses it to get the entry point method in the compiled script.

**Comment by AndriySvyryd** [comment] 2016-11-24 07:18
On a second look `COMDelegate::IsMethodDescCompatible` might the culprit, it returns false when the delegate return type is not a framework type. Here's a simpler repro:
```C#
public class Program
{
    public static void Main(string[] args)
    {
        PrintDelegateName<Func<object>>();
        PrintDelegateName<Func<Program>>(); // throws
    }

    public static void PrintDelegateName<T>()
    {
        var methodInfo = typeof(Test<object>).GetTypeInfo().GetDeclaredMethod("Factory");
        Console.WriteLine(methodInfo.CreateDelegate(typeof(T)));
    }
}

public class Test<T>
{
    public static T Factory()
    {
        return default(T);
    }
}
```

**Comment by karelz** [comment] 2016-11-24 18:07
@AndriySvyryd why did you delete the simplified repro? Didn't it repro?

cc: @jkotas to help route it

**Comment by AndriySvyryd** [comment] 2016-11-24 21:03
@karelz Yes, that repro was incorrect. It seems to only affect runtime emitted assemblies. I managed to save one to a file, but couldn't create a static repro with it yet.
[CompiledRepro.zip](https://github.com/dotnet/corefx/files/612174/CompiledRepro.zip)

**Comment by jkotas** [comment] 2016-11-25 07:45
The crash is caused by two copies of the same assembly getting loaded - one copy is loaded in the default load context, and second copy is loaded in the custom load context created by Microsoft.CodeAnalysis.Scripting.Hosting at this callstack:

```
coreclr!AssemblyNative::LoadFromPath [d:\a\_work\33\s\src\vm\assemblynative.cpp @ 813]
System_Private_CoreLib_ni!DomainNeutralILStubClass.IL_STUB_PInvoke(IntPtr, System.String, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack)+0xaa
System_Private_CoreLib_ni!System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(System.String)+0x4a [D:\A\_work\33\s\src\mscorlib\src\System\Runtime\Loader\AssemblyLoadContext.cs @ 103]
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.CoreAssemblyLoaderImpl.LoadFromPath(System.String)+0x5d
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader.Load(System.String)+0xa4
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader.ShadowCopyAndLoadDependency(System.String)+0x4d
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader.GetOrLoadKnownAssembly(Microsoft.CodeAnalysis.AssemblyIdentity)+0x163
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader.ResolveAssembly(Microsoft.CodeAnalysis.AssemblyIdentity, System.String)+0x2f3
Microsoft_CodeAnalysis_Scripting!Microsoft.CodeAnalysis.Scripting.Hosting.CoreAssemblyLoaderImpl+LoadContext.Load(System.Reflection.AssemblyName)+0x2e
System_Private_CoreLib_ni!System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(System.Reflection.AssemblyName)+0x1b [D:\A\_work\33\s\src\mscorlib\src\System\Runtime\Loader\AssemblyLoadContext.cs @ 245]
```

The binding of the delegate fails because of the target signature references types from one copy of the assembly, but the delegate signature references types from other copy of the assembly.

**Comment by jkotas** [comment] 2016-11-25 07:49
.NET Core 1.0 had a bug where certain assembly loads into custom load contexts were not routed through the AssemblyLoadContext.Load method correctly. This bug was fixed on .NET Core 1.1. It may explain the change in behavior.

cc @gkhanna79 @rahku

**Comment by jkotas** [comment] 2016-11-25 08:08
@tmat What is the expected behavior of the InteractiveAssemblyLoader in this case? When does it want to load second copy of the assembly? It looks like it is loading second copy of the assembly more often than necessary.

**Comment by karelz** [comment] 2016-11-25 08:10
In that case I assume we should move the bug to roslyn. Will wait for @tmat's assesment first.
Thanks @jkotas!

**Comment by tmat** [comment] 2016-11-25 18:41
Seems like the same issue as https://github.com/dotnet/roslyn/issues/15352

**Comment by karelz** [comment] 2016-11-25 23:05
Closing as dupe

**Closed by karelz** 2016-11-25 23:05 UTC
Labels: area-System.Runtime, bug, tracking-external-issue
