### ISSUE TITLE
JsonSerializer does not support System.Uri

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/corefx#38536] opened 2019-06-14 07:46 UTC
### Describe the bug
JsonSerializer fails to handle Uri's properly.
Version: 3.0 Preview 6 

### To Reproduce

```csharp
using System;
using System.Text.Json.Serialization;

namespace BugNamespace
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var content = new UriResponse
            {
                Uri = new Uri("https://someserver.co/")
            };
            var requestJson = JsonSerializer.ToString(content);
        }
    }

    class UriResponse
    {
        public Uri Uri { get; set; }
    }
}

```

### Expected behavior
`requestJson == {"uri": "https://someserver.co/"}`

### Actual behavior
`requestJson == {"Uri":{"AbsolutePath":"\u002f","AbsoluteUri":"https:\u002f\u002fsomeserver.co\u002f","LocalPath":"\u002f","Authority":"someserver.co","HostNameType":2,"IsDefaultPort":true,"IsFile":false,"IsLoopback":false,"PathAndQuery":"\u002f","Segments":["\u002f"],"IsUnc":false,"Host":"someserver.co","Port":443,"Query":"","Fragment":"","Scheme":"https","OriginalString":"https:\u002f\u002fsomeserver.co\u002f","DnsSafeHost":"someserver.co","IdnHost":"someserver.co","IsAbsoluteUri":true,"UserEscaped":false,"UserInfo":""}}` 

On the other hand, attempt to parse json `{"uri": "https://someserver.co/"}` fails with error:
`The JSON value could not be converted to System.Uri. Path: $.uri | LineNumber: 0 | BytePositionInLine: 32.`

**Comment by ahsonkhan** [comment] 2019-06-17 20:33
cc @layomia

**Comment by ahsonkhan** [comment] 2019-06-17 20:45
Like I mentioned in https://github.com/dotnet/corefx/issues/38568#issuecomment-502842664, I think `Uri` will occur quite a bit in common models and JSON payloads, so we will try to squeeze support for that in for 3.0.

**Comment by ahsonkhan** [comment] 2019-06-18 23:06
Closing this as a duplicate of https://github.com/dotnet/corefx/issues/38536 which is tracking adding Uri support.

**Closed by ahsonkhan** 2019-06-18 23:06 UTC
Labels: area-System.Text.Json, enhancement, up-for-grabs
