### ISSUE TITLE
HttpWebRequest POST operation doesn't work with 5.2.2 UWP

### ISSUE THREAD

**Issue by romainbecheau** [dotnet/corefx#13768] opened 2016-11-17 20:38 UTC
Hi
I notice something between the v5.2 and 5.1 of the .netCore.UWP nugets version in Visual Studio
I have an APP in v5.1 and a do a "POST" opperation whith a HttpWebRequest , with parameter in the body encode in UTF8. (to simulate a login on a webSite)
If a upgrade to v5.2, my POST stop working !
I restore to v5.1 and it work again !
Have you got an idea ?

i've make a small VS project .

In 5.1 , we have an OK, in 5.2.2 : a KO pop up :)

**Comment by romainbecheau** [comment] 2016-11-17 20:39
the VS project : https://www.dropbox.com/s/o0u399cna5ygn06/bug.ZIP?dl=0

**Comment by davidsh** [comment] 2016-11-18 19:13
Thank you for submitting the repro solution. I have reproduced the problem and there is a different in behavior from the 5.1 to the 5.2.2 UWP meta-package.

The problem seems to be that cookies are not being sent back to the server.

I took a Fiddler trace of the HTTP request/response transactions from the repro solution.

First request:
```
GET https://www.cyclefeminin.net/ HTTP/1.1
Host: www.cyclefeminin.net
Connection: Keep-Alive
X-P2P-PeerDist: Version=1.1
X-P2P-PeerDistEx: MinContentInformation=1.0, MaxContentInformation=2.0
Accept-Encoding: peerdist
```
Response:
```
HTTP/1.1 303 See other
Date: Fri, 18 Nov 2016 18:53:53 GMT
Server: Apache/2.2
Set-Cookie: a92cbbaa96ac0c062508bbbfa5606b0a=bbt5noqh0ai8m9u2a1prp2koh0vae0dc; path=/; secure
Location: https://www.cyclefeminin.net/log-out
Vary: Accept-Encoding
Content-Length: 0
Keep-Alive: timeout=5, max=500
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
Via: 1.1 alproxy
```

In the 5.1 case, the cookie is sent back on the next request:
```
GET https://www.cyclefeminin.net/log-out HTTP/1.1
Host: www.cyclefeminin.net
Connection: Keep-Alive
X-P2P-PeerDist: Version=1.1
X-P2P-PeerDistEx: MinContentInformation=1.0, MaxContentInformation=2.0
Accept-Encoding: peerdist
Cookie: a92cbbaa96ac0c062508bbbfa5606b0a=bbt5noqh0ai8m9u2a1prp2koh0vae0dc
```

But in the 5.2.2 case, the cookie is not sent back:
```
GET https://www.cyclefeminin.net/log-out HTTP/1.1
Host: www.cyclefeminin.net
Connection: Keep-Alive
X-P2P-PeerDist: Version=1.1
X-P2P-PeerDistEx: MinContentInformation=1.0, MaxContentInformation=2.0
Accept-Encoding: peerdist
```

We did make various changes in the HTTP stack from the 5.1 UWP meta-package to the 5.2.2 meta package. I'm not sure exactly what broke but thank you for reporting this bug.

**Comment by davidsh** [comment] 2016-11-18 19:32
I have determined the root cause of the bug.  It seems that any `Set-Cookie` headers that arrive in HTTP responses that are 3xx responses (i.e. redirects) will not end up in the .NET CookieContainer store. That means that they won't be sent back on subsequent requests.

The reason this is happening is due to a set of changes made last year to fix other Cookie related issues in UWP apps.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/netcore50/System/Net/HttpClientHandler.cs#L726

Since the redirects are happening automatically in the WinRT layer, the .NET layer doesn't seem the 3xx response and thus doesn't see the `Set-Cookie` header.  Since the redirection logic is currently set for "automatic redirects", the WinRT layer is handling the subsequent HTTP request.

We will further investigate this and hope to provide a fix in the near future.

**Comment by davidsh** [comment] 2016-11-18 20:26
Seem like this is a dupe of #9003

**Comment by romainbecheau** [comment] 2016-11-18 20:32
Thanks

So I will keep the v5.1 waiting a correction :)
Le ven. 18 nov. 2016 à 21:26, David Shulman <notifications@github.com> a
écrit :

**Comment by davidsh** [comment] 2016-11-22 17:02
Closing this as a duplicate of #9003.

**Closed by davidsh** 2016-11-22 17:02 UTC
Labels: area-System.Net, bug, os-windows-uwp
