### ISSUE TITLE
DateTime.Now.UTC Bug

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#32310] opened 2018-09-16 00:14 UTC
_From @muzzammilhussain on Friday, 14 September 2018 05:09:15_

On Windows Based Machine , When i am using DateTime.Now.UTC it gives me UTC time as soon as I use this on Ubuntu Machine it gives Ubuntu Time instead of UTC time.

On ubuntu the behavior of DateTime.Now= DateTime.UtcNow

Int32 unixTimestamp = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;

_Copied from original issue: aspnet/Home#3535_

**Comment by Eilon** [comment] 2018-09-16 00:14
_From @muzzammilhussain on Friday, 14 September 2018 09:13:32_

I am using .Net Core 2.0 along with Production Machine is Ubuntu 16 Server

**Comment by Eilon** [comment] 2018-09-16 00:14
_From @muzzammilhussain on Friday, 14 September 2018 09:51:11_

When I use Console Application on Core. It works Fine

alliedschools@allieschools:~/utc$ dotnet UCTTEST.dll 
Hello World!
My Computer Time Is :
9/14/18 2:49:34 PM
UTC TIME IS:
9/14/18 9:49:34 AM


As soon as I run it into web Project it starts doing the same behavior

**Comment by Clockwork-Muse** [comment] 2018-09-16 02:59
@muzzammilhussain - among other things, you should probably be using `DateTime.UTCNow`.  Or even better, `DateTimeOffset.UtcNow`.

Here's the thing about `DateTime` - it's really the equivalent of [Java's `LocalDateTime`](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html).  The ticks are an offset since a given epoch _in an implied timezone_.  Most of the methods/operators don't actually take the "timezone" into account, because `DateTimeKind` was added later.

This: 
```csharp
new DateTime(1970, 1, 1)
```

Is going to give you a `DateTime` with `DateTimeKind.Unspecified`.  Note that the code should still _work_, given it will only consider the ticks, but it might be indicative of you doing something that could be causing problems elsewhere.

I think we need a minimum example piece that shows the behavior.
>On ubuntu the behavior of DateTime.Now= DateTime.UtcNow

My first **guess** is that when you're starting things up as a web app, ubuntu is helpfully setting the process timezone as UTC, because the timezone of the server should be irrelevant.

**Comment by karelz** [comment] 2018-09-17 16:14
cc @krwq @tarekgh

**Comment by tarekgh** [comment] 2018-09-17 16:32
@muzzammilhussain could you please tell us the value of the TimeZoneInfo.Local.StandardName when you see DateTime.Now= DateTime.UtcNow. I think @Clockwork-Muse guess is right regarding the time zone settings was set to UTC when running as web app. 

@Eilon any idea of how the time zones set in the context of the web apps?

**Comment by Eilon** [comment] 2018-09-17 20:26
Nothing special about time zones in web apps as far as I know. Regardless of .NET FX vs. .NET Core, and ASP.NET (System.Web) vs. ASP.NET Core, I think it just picks up whatever .NET would normally pick up.

The only thing I can think of is that sometimes the *culture* of a thread is set to something (by the app, or the app telling ASP.NET to do so), but that shouldn't affect the date/time, just how it is displayed.

**Comment by jhudsoncedaron** [comment] 2018-09-17 21:32
Time zone is in the environment variable TZ on Linux with a fallback to /etc/localtime. Have your code output the value of environment variable TZ and try again.

**Comment by tarekgh** [comment] 2018-09-17 22:09
let's wait for @muzzammilhussain to tell us the time zone setting when executing DateTime.UtcNow

**Comment by muzzammilhussain** [comment] 2018-09-19 03:31
@tarekgh My Time Zone settings on Ubuntu are Asia/Karachi. Yes i do think so its the Web App which is messing with something as console works fine with the same code. In the Web App I am using tokens Auth Tokens for their validity I pass the time Zone in config file as Asia/Karachi. I think that is messing up when the Web App is starting up and setting its time. The web app is setting Asia/Karachi as UTC

**Comment by muzzammilhussain** [comment] 2018-09-19 03:34
I fixed the issue using Noda Time. I use Noda Time Library and It is working Perfectly fine. The main issue which I would treat as a bug is when I am running in development mode in windows I am still passing the timezone as +5GMT in Config file. In that case web app doesnt messes up things. Why it do so on ubuntu?

**Comment by muzzammilhussain** [comment] 2018-09-19 03:35
Last login: Tue Sep 18 10:42:19 2018 from 192.168.7.12
alliedschools@allieschools:~$ timedatectl status | grep "Time zone"
       Time zone: Asia/Karachi (PKT, +0500)
alliedschools@allieschools:~$

**Comment by muzzammilhussain** [comment] 2018-09-19 03:36
@Clockwork-Muse  this also doesnt works DateTimeOffset utcTime = DateTimeOffset.UtcNow;

**Comment by muzzammilhussain** [comment] 2018-09-19 03:37
Whenever I want to fetch UTC it gives me Time of my Current TimeZone.

**Comment by Clockwork-Muse** [comment] 2018-09-19 06:58
>My Time Zone settings on Ubuntu are Asia/Karachi. Yes i do think so its the Web App which is messing with something as console works fine with the same code. In the Web App I am using tokens Auth Tokens for their validity I pass the time Zone in config file as Asia/Karachi. I think that is messing up when the Web App is starting up and setting its time. The web app is setting Asia/Karachi as UTC

When you actually run as a web app, try printing out your timezone, after removing whatever overrides you put in place in config files.
Note that, unless something truly bizarre is going on (or your code is doing something inadvisable), UTC should not be overridden to a different timezone.  However, this shouldn't affect the result of `UtcNow`, unless _you're changing the current time_.

>I fixed the issue using Noda Time. I use Noda Time Library and It is working Perfectly fine. The main issue which I would treat as a bug is when I am running in development mode in windows I am still passing the timezone as +5GMT in Config file. In that case web app doesnt messes up things. Why it do so on ubuntu?

I doubt just using NodaTime would magically fix your problem - the library uses the native types under the hood in some areas, and so would still be subject to the same problems.  In particular, it uses `DateTime.UtcNow` for getting the current time.

>this also doesnt works DateTimeOffset utcTime = DateTimeOffset.UtcNow; 
Whenever I want to fetch UTC it gives me Time of my Current TimeZone.

Yeah, no, something else is going on.  Whatever you're experiencing, it is **not** a common problem, because accurate timestamps drive quite a lot of things.

We need a sample of your code to be able to troubleshoot what's going wrong here.  Please, if at all possible, give us a [minimal, verifiable example](https://stackoverflow.com/help/mcve).  If you can get your issue to reproduce in a Docker container, including the dockerfile would be interesting.

**Comment by tarekgh** [comment] 2018-09-19 16:18
@muzzammilhussain  could you please tell us the value of the TimeZoneInfo.Local.StandardName when you see DateTime.Now= DateTime.UtcNow? this will help to get this value during the runtime.  Also, as @Clockwork-Muse  mentioned, if you can get us some small repro to help see the problem that will be great!

**Comment by stephentoub** [comment] 2019-03-11 19:00
Closing due to lack of info.  It can be reopened when additional details are available.

**Closed by stephentoub** 2019-03-11 19:00 UTC
Labels: area-System.Globalization, question
