### ISSUE TITLE
Difference in File/DirectoryNotFoundException behavior when both directory and file don't exist

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#19850] opened 2017-05-16 23:03 UTC
This code on Windows:
```C#
using System;
using System.IO;

class Program
{
    static void Main()
    {
        long x = new FileInfo(@"C:\users\stoub\doesntExist\doesntExist.txt").Length;
    }
}
```
throws a FileNotFoundException, whereas this code on Linux:
```C#
using System;
using System.IO;

class Program
{
    static void Main()
    {
        long x = new FileInfo(@"/home/stoub/doesntExist/doesntExist.txt").Length;
    }
}
```
throws a DirectoryNotFoundException.  (If the whole directory exists and just the file doesn't, then we throw a FileNotFoundException on Linux as expected.)

Difference reported by @polarapfel at https://github.com/dotnet/corefx/issues/1728#issuecomment-301935624

cc: @ianhays, @JeremyKuhne

**Comment by stephentoub** [comment] 2017-05-16 23:17
Hmmm.  We have code in the Unix implementation especially to deal with what the comment claims is a difference:
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.Unix.cs#L270-L281
but that cited difference on Windows directly goes against the example I included in this issue.  And if as an experiment I set:
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.Unix.cs#L280
to always be false, no tests fail.  I'm confused what situation this was meant to be handling.

**Comment by JeremyKuhne** [comment] 2017-05-16 23:46
Are you talking about the trimming of the final separator change to the original logic? You added the original check for this, didn't you?

**Comment by JeremyKuhne** [comment] 2017-05-17 00:52
Ok, so _normally_ the Windows behavior matches what we're seeing on Unix. You get PATH_NOT_FOUND if the path to the left of the last separator doesn't exist. The kicker here is that on [desktop](https://referencesource.microsoft.com/#mscorlib/system/io/filesysteminfo.cs,293) we _explicitly_ ignore the error value (`_dataInitialised = File.FillAttributeInfo(FullPath, ref _data, false, false);`).

The error always comes back as FileNotFound for FileInfo as a result. Ugh. If someone else gets a chance to take this before Thursday please assign it to yourself. Otherwise I'll take it then.

**Comment by JeremyKuhne** [comment] 2017-05-17 00:55
Note that I validated the Windows error behavior for both `GetFileAttributes` and `FindFirstFile`. They return PATH_NOT_FOUND in the same way.

**Comment by stephentoub** [comment] 2017-05-17 02:26
> Are you talking about the trimming of the final separator change to the original logic? 

I'm talking about the whole thing. I must have added this in response to something failing, but none if the existing tests are failing without it, and the behavior on Windows doesn't match the comment.

**Comment by ianhays** [comment] 2017-05-18 18:36
I remember us discussing this. If I recall correctly, the issue was that Windows would provide more information in the error that we would use to determine whether to throw a DirectoryNotFound or a FileNotFound. On Unix the exceptions thrown from the interop call didn't include that info, so we did some manual parsing to throw a DirectoryNotFound or a FileNotFound depending on which piece was missing.

An example of this is [way back when I added the parsing to the FileInfo CopyTo function](https://github.com/ianhays/corefx/blob/481d5c645763da79145af50d123db3f4041aa05e/src/System.IO.FileSystem/src/System/IO/FileInfo.cs#L271). We had the same issue there and did the directory Exists check to throw a DNFE.

>and the behavior on Windows doesn't match the comment.

Could this be because our interop exception catching/rethrowing logic has changed?

**Comment by JeremyKuhne** [comment] 2017-05-18 18:47
The problem is that in the case of the Info wrappers we ignored the actual error on NetFX. It is just obfuscated a bit as Refresh() explicitly asks to ignore errors on not found.

I'm working on this now, writing a full set of tests that match desktop.

**Comment by polarapfel** [comment] 2017-05-18 18:52
Hey guys, it's great to see issues reported being picked up so quickly (and discussed openly here). Really enjoying this!!

Thanks!

**Comment by stephentoub** [comment] 2017-05-18 18:54
> The problem is that in the case of the Info wrappers we ignored the actual error on NetFX. It is just obfuscated a bit as Refresh() explicitly asks to ignore errors on not found.

Ah!  So am I correct in understanding that this same logic is exercised via File/Directory (rather than FileInfo/DirectoryInfo), we have tests for the former but not for the latter, and my comment / fix was relevant to the former but causes problems for the latter?  I guess that makes me feel a bit better that I wasn't totally crazy ;)

> Hey guys, it's great to see issues reported being picked up so quickly (and discussed openly here). Really enjoying this!!

Excellent :)

**Comment by stephentoub** [comment] 2017-05-18 18:59
And indeed changing the code from:
```C#
long x = new FileInfo(@"C:\users\stoub\doesntExist\doesntExist.txt").Length;
```
to:
```C#
File.GetAttributes(@"C:\users\stoub\doesntExist\doesntExist.txt");
```
results in a DirectoryNotFoundException instead of a FileNotFoundException.

**Comment by JeremyKuhne** [comment] 2017-05-18 19:07
> Gotta love inconsistency

Yeah- in this case it looks accidental as well (or at best evil). After the `Refresh()` call `_dataInitialized` will be `0` and `_data.fileAttributes` will be `0xFFFFFFFF`.

``` C#
    if (_dataInitialised == -1)
        Refresh();
    
    if (_dataInitialised != 0) // Refresh was unable to initialise the data
        __Error.WinIOError(_dataInitialised, DisplayPath);

    if ((_data.fileAttributes & Win32Native.FILE_ATTRIBUTE_DIRECTORY) != 0)
        __Error.WinIOError(Win32Native.ERROR_FILE_NOT_FOUND, DisplayPath);
    
    return ((long)_data.fileSizeHigh) << 32 | ((long)_data.fileSizeLow & 0xFFFFFFFFL);
```

**Comment by stephentoub** [comment] 2017-05-25 22:16
@JeremyKuhne, this can be closed now, right?

**Comment by daxian-dbw** [comment] 2017-05-30 19:34
> Yeah- in this case it looks accidental as well (or at best evil). After the Refresh() call _dataInitialized will be 0 and _data.fileAttributes will be 0xFFFFFFFF.

Could #20456 be related to the discussion here? `FileSystemInfo.Attributes` gets set to -1 on Unix if the file is somehow deleted during an enumeration of all files in the parent directory. This happens with `Microsoft.NetCore.App 2.0.0-preview2-25324-03` (built on 5/24). But the behavior is different with `Microsoft.NetCore.App 2.0.0-preview1-002106-00`, where a `FileNotFoundException` exception is thrown.

**Comment by JeremyKuhne** [comment] 2017-06-05 18:56
https://github.com/dotnet/coreclr/pull/11757 fixed this in CoreCLR for master.
https://github.com/dotnet/coreclr/pull/11807 ported the CoreCLR fix.

**Closed by JeremyKuhne** 2017-06-05 18:56 UTC
Labels: area-System.IO, bug, os-linux, os-mac-os-x
