### ISSUE TITLE
[arm32/Linux] System.ServiceModel.Syndication.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33993] opened 2018-12-11 21:21 UTC
Running the arm32 tests on linux for System.ServiceModel.Syndication.Tests produced the following results: passed 1108/1211 tests.

Most of the tests failing here are throwing PlatformNotSupported so they should be skipped on Linux-arm.

Attaching the testResults.xml in order to have the list of all failing tests:

[testResults.zip](https://github.com/dotnet/corefx/files/2669457/testResults.zip)

**Comment by danmosemsft** [comment] 2018-12-11 22:49
These are all Linux/Windows line endings issues. eg
```
-<![CDATA[System.NotSupportedException : -- Expected -\n<WorkspaceTests.ExtensionObject xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.datacontract.org/2004/07/System.ServiceModel.Syndication.Tests\">\r\n    <Value>10</Value>\r\n</WorkspaceTests.ExtensionObject>\r\n<WorkspaceTests.ExtensionObject xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.datacontract.org/2004/07/System.ServiceModel.Syndication.Tests\">\r\n    <Value>11</Value>\r\n</WorkspaceTests.ExtensionObject>\n-- Actual -\n<WorkspaceTests.ExtensionObject xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.datacontract.org/2004/07/System.ServiceModel.Syndication.Tests\">\n    <Value>10</Value>\n</WorkspaceTests.ExtensionObject>\n<WorkspaceTests.ExtensionObject xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.datacontract.org/2004/07/System.ServiceModel.Syndication.Tests\">\n    <Value>11</Value>\n</WorkspaceTests.ExtensionObject>\n]]>
```
This is because the repo was checked out on Windows, then built either on Windows or Linux then run on Linux.
The fix is to modify `public static void AssertEqualLongString(string expected, string actual)` to replace \r\n with \n and \r with \n.

**Comment by wfurt** [comment] 2018-12-27 23:47
I could not reproduce this (running on clrjit-tegra26)

>   === TEST EXECUTION SUMMARY ===
     System.ServiceModel.Syndication.Tests  Total: 1211,  Errors: 0, Failed: 0, Skipped: 0, Time: 3.479s

If we get test data mangled that would suggest infrastructure issues. I would expect that even on Windows we should be able to checkout files exactly as submitted. 
I don't think the suggested change is good fix @danmosemsft . We already pass this on Windows and Linux so there should be no reason IMHO to make updates for ARM.

**Comment by danmosemsft** [comment] 2018-12-28 17:50
@wfurt, agreed, unless we want to regularly build on Windows the test binaries for Unix. Then we will always have this problem on a few tests.

**Comment by yujayee** [comment] 2019-03-19 22:00
Is there anything we need to do for this issue? @danmosemsft

**Comment by wfurt** [comment] 2019-03-19 22:13
I'm in process of getting daily test runs for arm32. When ready, we can look at results and either close or investigate.

**Comment by wfurt** [comment] 2019-05-16 20:33
Daily test runs seems to be ok. I'm closing it now. If we see CI failures, we should open new bug with more specific info.

**Closed by wfurt** 2019-05-16 20:33 UTC
Labels: arch-arm32, area-System.ServiceModel.Syndication, os-linux, test-run-core
