### ISSUE TITLE
HashSet.Remove regression, not honoring comparer

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#42598] opened 2019-11-14 18:56 UTC
Recent optimizations in HashSet have caused a regression in HashSet.Remove when a non-default comparer is used. 
```
            var hashSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            hashSet.Add("Foo");
            hashSet.Add("Bar");
            Assert.True(hashSet.Remove("Bar")); // Works
            Assert.True(hashSet.Remove("FOO")); // Fails
```
I think the issue is that this line uses the default comparer rather than the specified one:
https://github.com/dotnet/corefx/pull/40106/files#diff-a80c75678ed2d070e638bcb93ba26bccR419
Compare to the same code in Add that uses the specified comparer:
https://github.com/dotnet/corefx/pull/40106/files#diff-a80c75678ed2d070e638bcb93ba26bccR1388

This broke a few MVC tests in AspNetCore.

**Comment by Tratcher** [comment] 2019-11-14 19:34
@JeffreyZhao can you take a look?

**Comment by JeffreyZhao** [comment] 2019-11-15 16:21
@Tratcher Thanks for pointing it out. It's clearly a bug.

The fix is quick and simple, but the repo consolidation is coming up, is there anything special I need to do?

**Comment by dougbu** [comment] 2019-11-15 16:39
@JeffreyZhao the repo consolidation is in progress 😺 

I would say the urgency of a fix depends on whether the problem is in 3.0 or 3.1 too. If the problem is only in 5.0, a fix is important but not nearly as urgent. We can wait 'til the new repo is open for product fixes.

**Comment by JeffreyZhao** [comment] 2019-11-15 16:42
@dougbu It's newly introduced in 5.0. I can work on the missing unit test and the fix. Probably I'll also create a PR, but feel free to close it if it's not a good time to merge it. I can always do it again after the consolidation.

**Comment by dougbu** [comment] 2019-11-15 16:48
Not my call on your PR.

It's my understanding PRs targeting 'master' in this repo will just be closed soon if they haven't already. You might be able to open a PR here to validate your changes but will need to port it to dotnet/runtime when that's available.

**Comment by Tratcher** [comment] 2019-11-20 17:43
This caused significant regressions in Entity Framework (400+ test failures) and they will not be able to take dependency updates until this is fixed.

**Comment by stephentoub** [comment] 2019-11-20 19:10
To unblock EF I've put up a fix for this in the (still private but soon to be public) dotnet/runtime repo.

**Comment by dougbu** [comment] 2019-11-20 19:22
@stephentoub I believe it'll be a while (weeks?) after the dotnet/runtime repo is public before it begins pushing to the '.NET Core 5 Dev'. Good thing we're not in a rush for new CoreFx features.

Or was @mmitche being pessimistic when he said that in https://github.com/aspnet/EntityFrameworkCore/pull/18949#issuecomment-555622384 ?

**Comment by mmitche** [comment] 2019-11-20 19:26
@jaredpar says "december 15th" but optimistically first week of december.

**Closed** 2019-11-20 21:06 UTC
Labels: area-System.Collections, blocking-partner, bug
