### ISSUE TITLE
RuntimeBinderException when using Task extension method on the result of an async method in a call tree that includes a dynamic parameter

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25461] opened 2017-11-23 04:01 UTC
_From @bungeemonkee on November 22, 2017 23:31_

I ran into a very specific case where the clr appears to not properly resolve extension methods at runtime for code involving both dynamics and async and throws a RuntimeBinderException.

CLI version: 2.0.3
CLR versioin: 2.0.3

If the code below is added to a netcoreapp2.0 console project it will reproduce the exception.

Program.cs
```csharp
using System;
using System.Threading.Tasks;

namespace RuntimeBinderException
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            Go(args).Wait();

            Console.WriteLine("Should not get here.");
        }

        public static async Task Go(dynamic thing)
        {
            await DoSomething(thing).TaskExtension();
        }

        public static async Task DoSomething(object parameter)
        {
            // The function needs only be declared async - it doesn't need to actually await anything
        }
    }
}

TaskExtensions.cs
```csharp
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace RuntimeBinderException
{
    public static class TaskExtensions
    {
        public static async Task TaskExtension(this Task task)
        {
            await task;
        }
    }
}
```

The exception is:
>Unhandled Exception: System.AggregateException: One or more errors occurred. ('System.Threading.Tasks.Task' does not contain a definition for 'TaskExtension') ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Threading.Tasks.Task' does not contain a definition for 'TaskExtension'
>   at CallSite.Target(Closure , CallSite , Object )
>   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
>   at RuntimeBinderException.Program.<Go>d__1.MoveNext() in /mnt/c/_Local/Playground/RuntimeBinderException/RuntimeBinderException/Program.cs:line 17
>   --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>   at System.Threading.Tasks.Task.Wait()
>   at RuntimeBinderException.Program.Main(String[] args) in /mnt/c/_Local/Playground/RuntimeBinderException/RuntimeBinderException/Program.cs:line 10

I have included a zip archive of the solution to reproduce the issue.
[RuntimeBinderException.zip](https://github.com/dotnet/coreclr/files/1497723/RuntimeBinderException.zip)

_Copied from original issue: dotnet/coreclr#15186_

**Comment by JonHanna** [comment] 2017-11-23 09:55
This is correct behaviour. A much shorter reproduction of the same behaviour is `((dynamic)new int[0]).Any()`. The dynamic binder does not—and should not—consider extension method syntax in deciding which overload to bind to. They should use the static method call syntax of `TaskExtensions.TaskExtension(DoSomething(thing));` instead.

**Comment by JonHanna** [comment] 2017-11-23 10:35
(Or alternatively, cast the result of `DoSomething(thing)` back from `dynamic` to `Task` before calling the extension method. Which is preferable would depend on the use case.)

**Comment by OmarTawfik** [comment] 2018-02-05 23:38
@bungeemonkee closing as by design. Please let me know if you're not happy with the suggestions provided.

**Closed** 2018-02-05 23:38 UTC
Labels: area-Microsoft.CSharp
