### ISSUE TITLE
Process.Start not working properly in Mac

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#26340] opened 2018-01-14 22:39 UTC
@viswa18 commented on [Mon Dec 18 2017](https://github.com/dotnet/core/issues/1171)

# Process.Start not working properly in Mac

I have simple C++ command line application , which is running from .net core 2.0. I have set pinfo.CreateNoWindow = true;
 and 
pinfo.WindowStyle = Hidden;

When running the application in mac, it opens the application icon in dock and close it. But it does not show any icon in windows and Linux. Can anyone help me to overcome this. I do not want the icon in dock. If it is a issue in .net core, when it will be fixed?

Thanks in advance.

**Comment by karelz** [comment] 2018-01-16 16:51
Duplicate of #26337

**Closed by karelz** 2018-01-16 16:51 UTC

**Comment by wfurt** [comment] 2018-01-16 18:53
You should be able to for example start it from user's Login Items with Hidden flag @viswa18. 
You should also be able to publish native app and than use something like http://hints.macworld.com/article.php?story=20010420005353216

**Comment by karelz** [comment] 2018-01-16 19:50
@wfurt is it something we could/should do in .NET Core Process API? (i.e. should we reopen the issue?)

**Comment by wfurt** [comment] 2018-01-16 19:54
I'm not sure @karelz . As I was trying to explain in linked bug Unix console does not have concept of windows or dock so it is difficult for console app to control such behavior.  
@viswa18 should confirm, but did that call opened new window or Dock entry? 
More complete example would be needed to do better triage.

**Comment by wojtpl2** [comment] 2018-01-24 09:28
It should be described in documentation https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netcore-2.0#System_Diagnostics_ProcessStartInfo_CreateNoWindow

**Comment by karelz** [comment] 2018-01-24 15:48
@wojtpl2 good idea - would you mind submitting docs change? (Edit button on that page)
