### ISSUE TITLE
Implement DbProviderFactories

### ISSUE THREAD

**Issue by naster01** [dotnet/corefx#10859] opened 2016-08-16 16:54 UTC
DbProviderFactories is not currently implemented in the CoreFx but was in the full framework since version 2.0.

Doc : 
https://msdn.microsoft.com/fr-fr/library/system.data.common.dbproviderfactories(v=vs.110).aspx

Source code : 
http://referencesource.microsoft.com/#System.Data/System/Data/Common/DbProviderFactories.cs

Any advise on porting the code?

**Comment by karelz** [comment] 2016-11-10 23:52
Dupe of #4571.

**Closed by karelz** 2016-11-10 23:52 UTC
Labels: area-System.Data
