### ISSUE TITLE
Implement SocketAsyncEventArgs FILE_SKIP_COMPLETION_PORT_ON_SUCCESS - TODO Tracking Issue

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#4900] opened 2015-12-09 10:35 UTC
While there is a TODO comment for this in SocketAsyncEventArgs, I think this is important enough to be tracked as an issue.

**Comment by CIPop** [comment] 2016-01-14 23:52
Thanks for opening this @clrjunkie! Will shortly add the back-link in code.
Unfortunately, while the external API supports synchronous completions, the implementation doesn't appear to do so even for .Net Desktop. Marking this as a feature.

**Comment by stephentoub** [comment] 2016-06-13 11:48
It'd be great if this could be addressed for 1.1.  The Unix implementation is mirroring this behavior (https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L14-L23), which is in turn making it difficult to put in place some important optimizations in the managed WebSockets implementation we're using on Unix.  All operations end up completing asynchronously, which in turn means that all async methods up the call chain end up yielding (since an await rarely completes synchronously), resulting in many more allocations and queued work items than are actually necessary.
cc: @ericeil

**Comment by pgavlin** [comment] 2016-06-13 16:26
Just a note that there are tests that expect the existing behavior. I don't remember the exact cases, only that they exist. This is how I found out I was missing something in an early *nix Sockets implementation, which completed some operations synchronously. IIRC the pattern to look for is `Assert.True(socket.*Async())`.

**Comment by CIPop** [comment] 2016-12-12 23:58
Summary from the other issue:

1. We would like to have this implemented: requires code changes for Windows and non-Windows code, changing the tests and eventually adding new tests. We would need to modify the perf tests and get A/B perf test results. I believe this is a medium-size item.
2. We agreed that we would enable this by default.
3. @nayato confirmed with the WinSock team that enabling this on Win7 SP1 isn't possible.

/cc @nayato @stephentoub @geoffkizer 

Given point 3 and @weshaggard's [response](https://github.com/dotnet/corefx/issues/13752#issuecomment-262015686) solving the issue will require OS/Version detection to avoid issues on Win7 SP1.

@nayato Outstanding question from @geoffkizer :

> Anyone know more details of the Windows bug? What exactly happens if you try to use this with UDP on a pre-Win8?

**Comment by geoffkizer** [comment] 2016-12-13 18:37
I have an implementation of this for Windows at https://github.com/geoffkizer/corefx/tree/synccompletion.

It has a few minor issues, but it works.  Feedback welcome.

Looking at the Linux stuff next.

**Comment by geoffkizer** [comment] 2017-01-12 23:19
See #15141

**Comment by geoffkizer** [comment] 2017-01-16 22:31
implemented in #15141

**Closed by geoffkizer** 2017-01-16 22:31 UTC
Labels: area-System.Net.Sockets, enhancement, netfx-port-consider, up for grabs
