### ISSUE TITLE
SystemNative_SysConf does not check for errors

### ISSUE THREAD

**Issue by khyperia** [dotnet/corefx#24663] opened 2017-10-16 16:48 UTC
It returns the result of calling `sysconf` directly:
https://github.com/dotnet/corefx/blob/c4d0529c24a8abc50009e561e96efed6b3e002b9/src/Native/Unix/System.Native/pal_io.cpp#L844-L859

From the man page of `sysconf`:

```
RETURN VALUE
       The return value of sysconf() is one of the following:

       *  On error, -1 is returned and errno is set to indicate the cause of the error (for example, EINVAL, indicating that name is invalid).

       *  If name corresponds to a maximum or minimum limit, and that limit is indeterminate, -1 is returned and errno is not changed.  (To distinguish an indeterminate limit from an error, set errno to zero before the call, and then check whether  errno  is  nonzero
          when -1 is returned.)

       *  If name corresponds to an option, a positive value is returned if the option is supported, and -1 is returned if the option is not supported.

       *  Otherwise, the current value of the option or limit is returned.  This value will not be more restrictive than the corresponding value that was described to the application in <unistd.h> or <limits.h> when the application was compiled.
```

Sysconf is indeed failing (I'm trying to get a minimal repro, but it's taking a while to narrow down). The end effect is [`Environment.ProcessorCount`](https://github.com/dotnet/corefx/blob/475c578fc77e16344679e337276c91a70fe1c79c/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L361) returns `-1`, which is... bizarre, to say the least!

[EDIT] Making code link inline for readability by @karelz

**Comment by karelz** [comment] 2017-10-17 19:03
So what happens afterwards?
The code already returns -1 and sets EINVAL for a wrong argument:
https://github.com/dotnet/corefx/blob/c4d0529c24a8abc50009e561e96efed6b3e002b9/src/Native/Unix/System.Native/pal_io.cpp#L857-L858

I would expect interop to kick in and translate it into an exception ...

**Comment by stephentoub** [comment] 2017-10-17 21:18
> I would expect interop to kick in and translate it into an exception ...

That's not how P/Invoke works.  And I believe @khyperia's concern is that we're just returning the result rather than checking it and throwing an appropriate exception here:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L361

**Comment by stephentoub** [comment] 2017-10-18 04:31
> Sysconf is indeed failing (I'm trying to get a minimal repro, but it's taking a while to narrow down). The end effect is Environment.ProcessorCount returns -1, which is... bizarre, to say the least!

@khyperia, if you're able to get a repro, that would be great.  I agree it's bizarre to return -1 from ProcessorCount, but throwing an exception is equally strange, so it'd be good to better understand in what situations that could end up happening.

What OS/distro/version are you on?

**Comment by khyperia** [comment] 2017-10-19 15:48
> What OS/distro/version are you on?

Ubuntu 16.04.3, in an Azure VM.

I _think_ this _might_ be a duplicate of https://github.com/dotnet/corefx/issues/21386 ... I can only seem to repro it when running the bootstrapped Roslyn compilers, which is not a very nice minimal repro, and so I think there's some really strange things going on - I think somehow we're pulling in `System.Native.so` from the installed SDK and the pinvoke wrapper (whatever managed dll its in) from a nuget package (or vice versa), so `PAL_SC_NPROCESSORS_ONLN == SysConfName._SC_NPROCESSORS_ONLN` might not have lined up (or something).

However, regardless of the reasoning, debugging this would have been a _LOT_ easier if an exception was thrown, instead of silently returning -1. In particular, the current implementation completely drops `errno`, which would be very, very useful to diagnose the particular issue that's happening (for example, it would rule out a mismatched `.so`, if `errno != EINVAL`. I assume there's a standard way in corefx to translate errno into an exception, which would be great here.

**Comment by stephentoub** [comment] 2017-10-19 15:54
> I think there's some really strange things going on - I think somehow we're pulling in System.Native.so from the installed SDK and the pinvoke wrapper (whatever managed dll its in) from a nuget package (or vice versa), so PAL_SC_NPROCESSORS_ONLN == SysConfName._SC_NPROCESSORS_ONLN might not have lined up (or something).

If that's true, we should figure out why that's happening and fix it.  @eerhardt, anything here sound familiar?

> In particular, the current implementation completely drops errno

That's not entirely true.  The SysConf P/Invoke has SetLastError==true:
https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/System.Native/Interop.SysConf.cs#L18
so the errno value will be available from `Marshal.GetLastWin32Error()`; Environment.ProcessorCount currently doesn't call that, but if you see -1 come back, you can call it to get the last errno value.

> debugging this would have been a LOT easier if an exception was thrown, instead of silently returning -1

I'd be nervous about an exception if there are real cases this could happen (though I don't know what a better alternative is, it's very unexpected for ProcessorCount to throw), but if it'll only happen if the system is misconfigured, it seems reasonable to do.

**Comment by eerhardt** [comment] 2017-10-19 17:47
Nothing really jumps out for me.  @khyperia - if you could send a .zip of an app (it doesn't even need to be a minimal repro) that would help.  It would also be interesting to see what your `.deps.json` file says.  Does it have an entry for `System.Runtime.Extensions` in it?  If it does, then it is quite possible that you are running with a mix of shared framework assemblies and non-shared framework assemblies.

**Comment by khyperia** [comment] 2017-10-19 20:32
> if you could send a .zip of an app

Zipped up the bootstrap build of Roslyn that's showing the issue. Github has a maximum filesize of 10MB (it's 31MB), so I've uploaded to my personal website (let me know if there's a permanent place I can put it). I'm running it with `dotnet --version` `15.5.0-preview-007082`. [https://khyperia.com/f/repro.zip](https://khyperia.com/f/repro.zip)

Run it with `dotnet csc.dll /dev/null` (or `dotnet vbc.dll /dev/null`) (the `/dev/null` is because it needs a filename to compile and hit the place in code where it uses `Environment.ProcessorCount`)

The assert should fail at:

```
at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
at Microsoft.CodeAnalysis.PooledObjects.ObjectPool`1..ctor(Factory factory, Int32 size)
at Microsoft.CodeAnalysis.CachingIdentityFactory`2.CreatePool(Int32 size, Func`2 valueFactory)
```

Those two lines of code are http://source.roslyn.io/#Microsoft.CodeAnalysis/ObjectPool%25601.cs,111 (`Debug.Assert(size >= 1);`) and here http://source.roslyn.io/#Microsoft.CodeAnalysis/Collections/CachingFactory.cs,196 (`new ObjectPool<...>(..., Environment.ProcessorCount * 2);`)

> it is quite possible that you are running with a mix of shared framework assemblies and non-shared framework assemblies.

This is almost certainly the issue - it does indeed have `System.Runtime.Extensions`. So I think @stephentoub's suggestion that if it's only thrown on a misconfigured system, that's good.

**Comment by stephentoub** [comment] 2017-10-20 04:19
I took a look at the .zip.  The System.Native.so in it is old, e.g. it's missing exports that were added in support of .NET Core 2.0.  And Environment.ProcessorCount only relied on SystemNative_SysConf starting in 2.0, such that prior to 2.0, SystemNative_SysConf didn't know about PAL_SC_NPROCESSORS_ONLN; thus the 2.0 System.Runtime.Extensions.dll is calling SystemNative_SysConf(PAL_SC_NPROCESSORS_ONLN) and it's getting errno == EINVAL: https://github.com/dotnet/corefx/blob/release/1.1.0/src/Native/Unix/System.Native/pal_io.cpp#L783-L784 because this switch:
https://github.com/dotnet/corefx/blob/release/1.1.0/src/Native/Unix/System.Native/pal_io.cpp#L774-L780
is missing the PAL_SC_NPROCESSORS_ONLN entry added for 2.0:
https://github.com/dotnet/corefx/blob/release/2.0.0/src/Native/Unix/System.Native/pal_io.cpp#L852-L853

Thus the problem is that somehow this app is getting a 1.1 era System.Native.so, which can't be used with a 2.0 app.

**Comment by stephentoub** [comment] 2017-10-20 04:31
(I'm going to add an exception that gets thrown in this case, to help with future debugging, but that's not an actual fix; the fix is to figure out why an old native binary is being used with a newer managed one.)

**Comment by joperezr** [comment] 2017-11-21 19:34
@stephentoub Do we want to close this issue though? or do we want to keep it open to track the fact that we are using an older System.Native.so?

**Comment by stephentoub** [comment] 2017-11-21 19:57
> or do we want to keep it open to track the fact that we are using an older System.Native.so?

I don't think such an issue would be a corefx issue.  I'm fine closing it out.

**Closed by stephentoub** 2017-11-21 19:57 UTC
Labels: area-System.Runtime.Extensions, bug
