### ISSUE TITLE
NotSupportedException when Deserializing object that has default values for constructor parameters

### ISSUE THREAD

**Issue by EdiWang** [dotnet/corefx#41102] opened 2019-09-14 09:15 UTC
The following code throws exception. 

```csharp
static void Main(string[] args)
{
    var obj = new Response(true, "Hi") { ResponseCode = 100 };
    var json = System.Text.Json.JsonSerializer.Serialize(obj);

    // System.NotSupportedException: 'Deserialization of reference types without parameterless constructor is not supported.
    var response = System.Text.Json.JsonSerializer.Deserialize<Response>(json);

    Console.WriteLine(response.Message);
}

public class Response
{
    public bool IsSuccess { get; set; }

    public string Message { get; set; }

    public int ResponseCode { get; set; }

    public Response(bool isSuccess = false, string message = "")
    {
        IsSuccess = isSuccess;
        Message = message;
    }
}
```

Response class is considered not having a parameterless constructor, but actually it does use default values for parameters, that can be used just like a parameterless constructor, like this:

```csharp
var test = new Response();
```

Could the new JSON API check if the constructor parameters have default values before consider it not paremeterless?

Related Issues: 
https://github.com/dotnet/corefx/issues/37537

PR:
https://github.com/dotnet/corefx/pull/38061

**Comment by ahsonkhan** [comment] 2019-09-17 23:18
cc @steveharter

**Comment by steveharter** [comment] 2019-09-19 21:39
cc @layomia PTAL along with similar support for probing for collection ctors (typically immutable)

**Comment by layomia** [comment] 2019-11-23 10:56
Closing as duplicate of https://github.com/dotnet/corefx/issues/38569 which considers parameterless/custom constructor support.

We shouldn't do any unguided probing here - the constructor to use should be explicitly marked with an attribute.

**Closed by layomia** 2019-11-23 10:56 UTC
Labels: area-System.Text.Json, enhancement

**Comment by sanzor** [comment] 2019-12-03 21:11
Hello i have the same error message , and i can't deserialize even if i put a parameterless constructor !
```
public abstract class MessageClass {
        public enum MessageType {
            Player_Action=0,
        }
        [JsonPropertyName("type")]
        public abstract MessageType Type { get; }
        public MessageClass() {

        }
    }
public class PlayerAction : MessageClass {


        [JsonPropertyName("eventId")]
        public long EventId { get; set; }
        [JsonPropertyName("playerId")]
        public long PlayerId { get; set; }
        public PlayerAction() {

        }
        public override MessageType Type => MessageType.Player_Action;
    }

```

The error trace is the following;

> System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'LS.Models.MessageClass'
>    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_DeserializeMissingParameterlessConstructor(Type invalidType)
>    at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
>    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
