### ISSUE TITLE
System.Diagnostics.PerformanceCounter is missing in .Net Core

### ISSUE THREAD

**Issue by srinigithub2016** [dotnet/corefx#9376] opened 2016-06-12 22:26 UTC
missing  Performance counter in .Net Core

**Comment by danmosemsft** [comment] 2016-06-23 17:15
This is not currently available in Xamarin on mobile, so it would be motivated by Desktop compat. Marking Future for now.

**Comment by danmosemsft** [comment] 2016-09-20 17:57
Not in NS 2.0

**Comment by joperezr** [comment] 2016-11-10 17:31
related: #10633

**Comment by karelz** [comment] 2016-11-10 18:35
Dupe of #3906.

**Closed by karelz** 2016-11-10 18:35 UTC
Labels: area-System.Diagnostics
