### ISSUE TITLE
System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected failed

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19991] opened 2017-05-19 06:25 UTC
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170519.01/workItem/System.Net.Sockets.Tests/wilogs

~~~
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:    System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:       Timed out after 60000ms waiting for remote process 15571
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:34:52,014: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(208,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
~~~

**Comment by CIPop** [comment] 2017-05-22 21:30
duplicate of #20128

**Closed by CIPop** 2017-05-22 21:30 UTC
Labels: area-System.Net.Sockets, test-run-portable
