### ISSUE TITLE
Possible WebSocket problem - .NET Native different behavior

### ISSUE THREAD

**Issue by alexiordan** [dotnet/corefx#33231] opened 2018-11-03 07:41 UTC
I write this here because I have found: #17317

I run **Windows 10 IoT**  (17763.1.armfre.rs5_release.180914-1434)  on  a **DragonBoard 410C**.

My appllication is an **UWP application** (refenrces Microsoft.NetCore.UniversalWindowsPlatform ver. 6.1.7)  that runs as **BackgroundTask** (enabled to run on startup). The application uses SignalR to connect to a server. It tries to connect/reconnect with an exponential backoff (after 1 sec, 2 sec, 4 sec ... up to 256 sec after that remains at that interval).

DragonBoard has WiFi on board and also USB that I use to connect a 4G LTE K5150 modem. For some reason that is not part of this report here, the USB modem enters a state in which it loops between Connect/Disconnect state.

When WiFi is also available my application runs smoothly over the WiFi. However when I disable the WiFi and rely only on USB Modem that is in that unstable state, the OS eventually **reboots**.

I have memory dumps from such moments. As I investigated them it seems that IoTShell.exe monitors apps and restarts them if they crash. It also makes a dump and restarts the entire OS via _fail_fast if application keeps crashing (https://docs.microsoft.com/en-us/windows/iot-core/release-notes/insider/17686#shell-management-of-application-crashes). 
However I was not able to read from those dumps any information to be able to relate that behavior to my app's process ( I need help here).

As a user experience feedback, since I have a display connected to it, just before restart the OS is unresponsive.

My apps logs only show exceptions that seem to be normal in absence of connection. On the other hand there is no _OnApplicatonException_ mechanism to catch all exceptions (also raised here: https://social.msdn.microsoft.com/Forums/en-US/9950633f-a6ab-4441-98ca-d8e91885ea6b/how-to-handle-applevel-exceptions-in-an-iot-background-task?forum=WindowsIoT).

So I don't know what to do since I don't think is normal that a lack of connectivity error should reboot the entire OS.

I also referenced the System.Net.WebSockets.Client ver. 4.3.2 since I wanted to be on the safe side after reading the referenced issue (#17317).

IMPORTANT!
This happens only if my app is compiled with following options unchecked:

- [ ] Compile with .NET Native tool chain

- [ ] Enable static analysis for .NET Native

**If I compile with them checked, I don't encounter that error.**

Please advise! I don't want to rely on .NET Native only.

**Comment by karelz** [comment] 2018-11-06 17:14
It is hard to say what is causing the troubles. Are you able to create minimal repro? (HelloWorld style application, doing minimum to still reproduce the problem)
Another way is to identify what the exception is - try to attach debugger to the process, then trigger the state change. Is that an option?

**Comment by alexiordan** [comment] 2018-11-06 17:49
1. I will try to make a simple app for sample.
2. Cannot attach over ethernet since lack of internet connection seems to
cause the trouble.
2.a. I will try to reproduce it by stopping internet somewhere upstream.
2.b Maybe I can attach debug over USB? (I think I have seen something in
the debug help page for windows 10 iot :
https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/windowsdebugger#dragonboard-db)
but this is something new for me.

În mar., 6 nov. 2018, 19:15 Karel Zikmund <notifications@github.com a scris:

**Comment by davidsh** [comment] 2018-11-06 22:42
>So I don't know what to do since I don't think is normal that a lack of connectivity error should reboot the entire OS.
I also referenced the System.Net.WebSockets.Client ver. 4.3.2 since I wanted to be on the safe side after reading the referenced issue (#17317).
IMPORTANT!
This happens only if my app is compiled with following options unchecked:
  Compile with .NET Native tool chain
  Enable static analysis for .NET Native

I don't understand why you might think that .NET Core System.Net.WebSockets.Client is the cause of the system rebooting due to connectivity errors.  There is nothing in the .NET Core WebSockets code that can cause the OS to reboot since that would require high process privileges. 

It sounds like the root problem with system instability is the use of the USB Modem for your network connections:

> When WiFi is also available my application runs smoothly over the WiFi. However when I disable the WiFi and rely only on USB Modem that is in that unstable state, the OS eventually reboots.

This points to a problem with the operating system itself and/or the device driver for the USB Modem.  The fact that you are using WebSockets in your app seems irrelevant to the actual cause.  My guess is that if you app used HTTP directly (i.e. HttpClient APIs), you would also see the same instability.  The trigger for the OS reboots appears to be any use of the network via networking APIs (i.e. WebSocket in your case).

I am not familiar with debugging OS level problems with Windows IoT.  But perhaps you might be able to consult those repos and forums directly to get advise.  They might be some system logs and/or OS-level crash dumps that could be reviewed to help pinpoint the root cause.  And I suspect it is related to the USB Modem driver not being able to handle network connectivity loses.

**Comment by alexiordan** [comment] 2018-11-07 08:16
Thank you for response. 
I dont't think WebSocket library restarts the OS.

I only believe the System.Net.WebSockets.Client is throwing an exception that I cannot catch and so it makes my process crash.  
Yes, the root of the system instability seems to be the USB Modem for my network connection. 
However I believe this instability only reflects to the status of network connection and I think  System.Net.WebSockets.Client should handle such connection issues gracefully.

Is my expectation wrong?

The OS restart is not strictly related to System.Net.WebSockets.Client. It's just an OS mechanism that is  triggered when an app crashes too often in a specific period of time.

**Comment by davidsh** [comment] 2018-11-07 18:16
>However I believe this instability only reflects to the status of network connection and I think System.Net.WebSockets.Client should handle such connection issues gracefully.

It sounds like the problem was related to this issue: #17317.  This issue was fixed with PR #1600.  That fix was done in the release/2.1 branch.

However, I'm not sure we have released an update to the [Microsoft.NetCore.UniversalWindowsPlatform](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.0-preview1-26926-04) package that includes fixes from release/2.1 branch for UWP apps.  I think the current set of X packages are from release/2.0 branch.

You indicated that you are using 6.1.7 of that package. You might the most recent 6.1.9 version of the package.  However, it is possible that it also doesn't have the fix.

@karelz @danmosemsft - Can you clarify where the most recent package for Microsoft.NetCore.UniversalWindowsPlatform builds out of?  That answer would determine whether or not it has this fix in it.

**Comment by karelz** [comment] 2018-11-12 19:02
@wtgodbe @HollyAM can you please confirm if UWP package includes 2.1 CoreFX branch or just 2.0 CoreFX branch payload?

**Comment by alexiordan** [comment] 2018-11-19 22:46
News?
In the meanwhile UWP 6.2.2 has been released. Does it contain the fix?

**Comment by alexiordan** [comment] 2019-02-02 13:55
@karelz Any update?

**Comment by karelz** [comment] 2019-02-02 15:53
I have confirmed that UWP contains just 2.0 CoreFX payload.
@davidsh is this the bug you tracked for porting to UWP, or did I mix it up or did I misinterpret intentions?

**Comment by davidsh** [comment] 2019-02-02 16:05
I recently did PR #34558 into the release/uwp6.2 servicing branch. which was a ClientWebSocket fix.  That port was for a fix already done in master (#29810).  It dealt with issue #33704.  That issue was about ClientWebSocket properly handling 0-byte receives.

The problem being described in this issue is probably about a different ClientWebSocket bug, i.e.  issue #17317 (unhandled exception during WebSocket disconnect). That issue was fixed with PR #21600 but was fixed in release/2.1 branch which was not released as UWP packaging fix.

So, it's possible that this particular fix needs to be done into release/uwp6.2 servicing as well.

**Comment by alexiordan** [comment] 2019-02-02 16:11
@davidsh, what needs to be done in order for this fix to  be done into release/uwp6.2 servicing as well?

**Comment by davidsh** [comment] 2019-02-02 16:32
@alexiordan We need to confirm that the root cause is the same as what was fixed by PR #21600.  Then I need to confirm that the fix isn't yet in the release/uwp6.2 branch.  It's possible it's there now since other fixes were ported recently.  Once that is determined, we can open a PR to port the fix and get necessary shiproom approval to merge the fix into release/uwp6.2.

@tommcdon

**Comment by karelz** [comment] 2019-02-02 16:34
I would also like to understand the impact - is there a workaround? What kind of scenarios does it block and how common they are? ... Those are questions needed for any fix in servicing (of any product).

**Comment by alexiordan** [comment] 2019-02-02 16:41
@karelz, a more detailed explanation is at the bottom of my initial post, but long story short is:
In a backgroundTask application, this behavior leads to a system reboot. 

This means that other running functionalities will be restarted as well.

**Comment by davidsh** [comment] 2019-02-02 16:42
>I would also like to understand the impact - is there a workaround?

The bug that was fixed in master with PR #21600 was about an exception being thrown on a threadpool thread.  It was un-catchable and should have been caught and handled by our .NET Core ClientWebSocket implementation.  There was no workaround for that.

**Comment by alexiordan** [comment] 2019-02-02 16:54
@karelz, a BackgroundTask in Windows 10 IoT has a specific role (https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/backgroundapplications). In order to create that, your entry point class should implement IBackgroundTask interface. I am not aware of how to use .NET Core directly. (given also GPIO access).

In IoT world, using WebSockets in a Gateway device running Windows 10 IoT as a BackgrounTask I don't believe it is a rare scenario. 

Dows this answer your question?

**Comment by davidsh** [comment] 2019-02-04 01:07
I looked at the source code in release/uwp6.2 branch for WinRTWebSocket.cs:
https://github.com/dotnet/corefx/blob/release/uwp6.2/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinRTWebSocket.cs

It appears to have the fixes from master that were done with PR #21600.

So, perhaps the problem you are seeing is not actually related to that fix?

**Comment by alexiordan** [comment] 2019-02-04 13:10
1. Are you talking about the try here: https://github.com/dotnet/corefx/blob/da15505db459931486fa2c571d94cac558728646/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinRTWebSocket.cs#L355 ?

2. What version of Microsoft.NETCore.UniversalWindowsPlatform should I reference in order to benefit from the fix on the release/uwp6.2? What is the lowest version that benefits? I ask because right now 6.2.2 and 6.2.3 have been unlisted (see here: https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.3), by the way, do you know why?

**Comment by davidsh** [comment] 2019-02-05 00:16
>Are you talking about the try here:

Yes.  The try/catch is one part of the overall fix to prevent the unhandled exception from crashing the process.

I looked at the [Microsoft.NETCore.UniversalWindowsPlatform version 6.1.9]( https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.1.9) NuGet package.  That package doesn't actually contain the runtime binaries.  But it links to [runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform version 6.1.9](https://www.nuget.org/packages/runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform/6.1.9) package.

Using ILSPY I looked at the code in WinRTWebSocket as I see the try/catch in there for OnMessageReceived() method:
![image](https://user-images.githubusercontent.com/7684835/52245845-1ee56180-2898-11e9-9fb4-361176a21b4d.png)

So, that means that the fix for that issue is in the code already.  Are you sure you are using that package and have no other references to separate System.Net.WebSockets.Client NuGet packages (which are much older)?

**Comment by alexiordan** [comment] 2019-02-05 15:11
I will re-test with 6.1.9 and see if it happens again. I remember that I have already did this and problem occured, but I will retry.

**Comment by davidsh** [comment] 2019-03-15 00:33
@alexiordan 

Were you able to re-test with 6.19?

**Comment by alexiordan** [comment] 2019-03-15 15:05
Unfortunately I had some other things on top of that. I hope I can give you an answer following days. Sorry again for the delay.

**Comment by alexiordan** [comment] 2019-03-17 12:40
I just finished the tests. I did not encountered the problem anymore.
So thank you guys for help!

I have also removed reference to nuget package System.Net.WebSockets.Client ver. 4.3.2 

I tested using following versions of Microsoft.NetCore.UniversalWindowsPlatform:
- 6.2.3
- 6.2.8

Everything seems to be OK now!

**Comment by stephentoub** [comment] 2019-03-17 12:45
Thanks for confirming.

**Closed by stephentoub** 2019-03-17 12:45 UTC
Labels: area-System.Net, bug, needs more info, os-windows-uwp
