### ISSUE TITLE
Uri.ToString replaces %20 with space in Uri query (non-compliant URI)

### ISSUE THREAD

**Issue by AlbertoSadoc** [dotnet/corefx#41733] opened 2019-10-11 12:59 UTC
## Simplified repro
```c#
new Uri("https://foo/?bar=a%20b").ToString()
// https://foo/?bar=a b
```

-------------------------------------------
## Original repro

I have created a new Uri to use in [OpenApiOAuthFlows](https://github.com/microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Models/OpenApiOAuthFlow.cs) which contains query parameters with %20 instead of spaces.

OpenApiOAuthFlows is used to generate a JSON file to comply with OpenAPI in Swagger but the %20 are replaced with spaces, which in the end create a Uri not compliant with [RCF3986](https://tools.ietf.org/html/rfc3986#appendix-B).

Here's an example:
```
var authorizationUri = new Uri("https://token-host/connect/authorize?client_id=secure.platform&response_type=id_token%20token&scope=openid%20profile%20email");
```

Using that Uri as the AuthorizationUrl for a new OpenApiOAuthFlow when the JSON is generated it shows
```
"authorizationUrl": "https://token-host/connect/authorize?client_id=secure.platform&response_type=id_token token&scope=openid profile email"
```

I was going to suggest to have a parameter in ToString to chose whether to keep the encoded values or not but maybe is better to have a property in Uri to specify whether to replace them or not.

Also I have not tested this issue with other characters but I am sure it can raise futher compliance errors.

**Comment by SusLes** [comment] 2019-10-21 21:11
@karelz

**Comment by karelz** [comment] 2019-12-17 21:57
@AlbertoSadoc are you able to reproduce it with just `Uri`?
cc @MihaZupan

**Comment by MihaZupan** [comment] 2019-12-17 22:05
Reproducible:

```c#
new Uri("https://foo/?bar=a%20b").ToString()
// https://foo/?bar=a b
```

**Comment by karelz** [comment] 2019-12-18 00:17
Cool, much simple repro. Thanks @MihaZupan!
@MihaZupan do you know if `ToString` is recommended way to get encoded string on `Uri`? If yes, we should fix it. Though it may break people.
The alternative is that `ToString` is used only for logging in which case, space would be fine.

**Comment by danmosemsft** [comment] 2019-12-18 00:56
The documentation says
```
Uri.ToString Method
A String instance that contains the unescaped canonical representation of the Uri instance. All characters are unescaped except #, ?, and %.
```
https://docs.microsoft.com/en-us/dotnet/api/system.uri.tostring?view=netframework-4.8

**Comment by MihaZupan** [comment] 2019-12-18 11:17
Closing as the behavior is by design.

**Closed by MihaZupan** 2019-12-18 11:17 UTC
Labels: area-System.Net, bug

**Comment by karelz** [comment] 2019-12-18 16:30
@MihaZupan is there another API on `Uri` to return back the escaped representation of the Uri?

**Comment by MihaZupan** [comment] 2019-12-18 22:21
To my knowledge, `AbsoluteUri`

**Comment by karelz** [comment] 2019-12-19 00:05
Great, thanks @MihaZupan! @AlbertoSadoc is that something you can use in your scenario instead?

**Comment by MihaZupan** [comment] 2019-12-19 00:09
Looking at the code, it looks like this is a problem with [how OpenAPI.Net handles URI serialization](https://github.com/microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Models/OpenApiOAuthFlow.cs#L57-L63), as they are using `ToString` directly.

For example, NewtonsoftJson will properly serialize the URL if you pass it in directly `JsonConvert.SerializeObject(new Uri("https://foo/?bar=a%20b"))`.
