### ISSUE TITLE
ASP.NET Core 2.1 impersonation WSALookupServiceEnd error

### ISSUE THREAD

**Issue by ssilviu87** [dotnet/corefx#32948] opened 2018-10-22 10:49 UTC
Setup:
Client: IE or Chrome
Server: Asp.Net Core 2.1 via IIS with Windows Auth enabled.

Scenario: A client logs into a web app using windows credentials. The web app in turn impersonates that user to make outgoing HTTP requests also using windows credentials.

Expected: The outgoing HTTP request should made using the impersonated user's credentials.

Actual: A System.Net.WebException is thrown.

Sample code:
```c#
    [ApiController]
    [Route("[controller]/[action]")]
    public class ImpersonationTestController : ControllerBase
    {
        private readonly ILogger<ImpersonationTestController> _logger;

        public ImpersonationTestController(ILogger<ImpersonationTestController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public ActionResult Test()
        {
            try
            {
                return WindowsIdentity.RunImpersonated(((WindowsIdentity) User.Identity).AccessToken, () =>
                {
                    var url = $"";

                    using (var client = new WebClient {UseDefaultCredentials = true})
                    using (var responseStream = client.OpenRead(url))
                    using (var reader = new StreamReader(responseStream))
                    {
                        var response = reader.ReadToEnd();

                        return Ok(response);
                    }
                });
            }
            catch (Exception ex)
            {
                var message = "Impersonation Test Error!!";
                _logger.LogError(ex, message);
                return StatusCode(500, message);
            }
        }
    }
```

Stack Trace:
```
System.Net.WebException: A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled ---> System.Net.Http.HttpRequestException: A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled ---> System.Net.Sockets.SocketException: A call to WSALookupServiceEnd was made while this call was still processing. The call has been canceled
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.OpenRead(Uri address)
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass60_0`1.<RunImpersonated>b__0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass64_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated[T](SafeAccessTokenHandle safeAccessTokenHandle, Func`1 func)
```

**Comment by karelz** [comment] 2018-10-22 20:46
@ssilviu87 does it happen outside of ASP.NET as well? (e.g. impersonating from console app)

**Comment by karelz** [comment] 2018-10-22 21:41
@ssilviu87 no idea, that's why Console repro would be helpful :) (remove things and dependencies which themselves might cause the problem)

**Comment by caesar1995** [comment] 2018-12-05 00:54
@ssilviu87 Any updates for the repro?

**Comment by AndreasFetzer** [comment] 2019-01-17 13:38
Are there any updates? We run into the same issue with a very similar setup:

* Client logs into a web app
* Web app uses impersonating to forward the request to another rest api using windows identity

**Comment by karelz** [comment] 2019-01-17 15:54
@AndreasFetzer as you see in the replies, we are still waiting for a small console app repro. Without it we will likely close the issue as not actionable.

**Comment by VaniKulkarni** [comment] 2019-01-18 11:33
We are also facing similar issue

**Comment by DarranShelton** [comment] 2019-03-21 14:42
Hi. 

We are also getting this issue. Can you give an idea of an expected fix or provide a work around?

Thanks

Darran

**Comment by karelz** [comment] 2019-03-21 16:22
See https://github.com/dotnet/corefx/issues/32948#issuecomment-455223311 - the issue is not actionable for us. If you have something we can work investigate (small repro), please send it to us.

**Comment by satyendrasinghpanwar** [comment] 2019-03-26 09:03
I am also facing the same issue. Issue only comes if I am using SocketsHttpHandler. If I switch back to older HTTPHandler using AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);, then things are working. 
I even upgraded to netcore 2.2. Their also i m getting same issue

**Comment by karelz** [comment] 2019-03-26 15:29
@satyendrasinghpanwar are you able to give us a (small) repro? With current information, the problem is not actionable for us.

**Comment by nikhil-vankadia** [comment] 2019-04-03 13:22
In order to resolve this, we change the default value of Socket hander to false. 

you can set environment variable 
<environmentVariable` name="DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER" value="0">
or 
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false); 

The impersonated user does not have privilege to open socket in a local machine. that's why application throws exception.

**Comment by karelz** [comment] 2019-04-03 16:03
Still no reproduce, not actionable for us, closing.
Feel free to reopen when there's reproduce/actionable info. Thanks!

**Closed by karelz** 2019-04-03 16:03 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, bug, needs more info

**Comment by LeroyPakade** [comment] 2019-04-04 12:22
Im having the same problem , what do you need to re-look at this

**Comment by Cynthia-Jiang** [comment] 2019-04-20 02:12
> In order to resolve this, we change the default value of Socket hander to false.
> 
> you can set environment variable
> <environmentVariable` name="DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER" value="0">
> or
> AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
> 
> The impersonated user does not have privilege to open socket in a local machine. that's why application throws exception.

This resolved my issue, i was getting the same exception. thanks!

**Comment by wyf5188** [comment] 2019-05-02 17:55
Not working on my case until I put the application pool account running the the web site into Administrators group. Does the function: RunImpersonated really requires Administrative rights in order to call a second web api with the first incoming request context user identity?
