### ISSUE TITLE
Crossgen binaries in the flat NETCoreApp package

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#14595] opened 2016-12-17 00:40 UTC

**Comment by ericstj** [comment] 2016-12-20 20:50
We plan to do this in core-setup

**Comment by mellinoe** [comment] 2017-01-12 19:12
Do we actually want to have the binaries in the nuget package crossgen'd (rather than just the shared framework)? Crossgen'ing has a particular set of tradeoffs, so it'd be unfortunate if we forced standalone applications to take those tradeoffs, instead of giving them the choice to do so if it makes sense for them.

**Comment by ericstj** [comment] 2017-01-12 20:12
We haven't done this yet.  Cross-gen'ing still happens only for shared framework.  Are you thinking about the file-size tradeoffs?

**Comment by mellinoe** [comment] 2017-01-12 20:14
(R2R) crossgen trades off runtime speed and file size for startup speed, correct? I'm just suggesting that those tradeoffs are not ideal for all applications (selfishly I'm thinking of my own side projects), and it would be nice if folks could opt-in to those tradeoffs rather than being forced into them (since there's no other way to deploy a standalone application than through the nuget assets).

**Comment by ericstj** [comment] 2017-01-12 20:45
I see.  I am ok leaving the packages un-cross-gened.  Alternatively we could look at producing some packages that are not cross-gen'ed and giving them a architecture-less-RID.  @weshaggard what are your thoughts.

**Comment by mellinoe** [comment] 2017-01-12 20:54
From my viewpoint, the right way to offer this would be as an option in `dotnet publish`. Build customizations like this shouldn't be too difficult to accomplish with custom MSBuild targets, anyways (whether or not they are built-in).

If I could just run `dotnet publish -crossgen` (or `/p:Crossgen=true`) instead of `dotnet publish`, I think that would be simple enoughh to cover the scenario without forcing everyone into it.

**Comment by weshaggard** [comment] 2017-01-12 23:03
@jkotas @gkhanna79 do you guys have any opinions on whether or not we should have binaries already cross-gen'ed in our new flat NETCore.App package? 

Assuming the size isn't too much larger I think I would prefer them to already be R2R images.

**Comment by gkhanna79** [comment] 2017-01-13 00:05
> crossgen trades off runtime speed and file size for startup speed, correct?

R2R is not focused only for startup - it also helps execution time (i.e. runtime) speed as well as the JIT is not invoked for every method invocation during the life of the app.

Since M.N.App would be RID split, I would prefer to have the SharedFW binaries crossgened in them so that attempt to publish for a cross-target (e.g. publish on Windows for OSX) would get the target platform precompiled assets of the SharedFW published as part of the app. This would immediately make the app performance overall better than what it is today.

This scenario is not possible today without making non-trivial changes to crossgen.

**Comment by gkhanna79** [comment] 2017-01-13 00:06
> Assuming the size isn't too much larger

This size impact is there - comfort level depends upon who is looking at it :)

**Comment by mellinoe** [comment] 2017-01-13 00:33
> R2R is not focused only for startup - it also helps execution time (i.e. runtime) speed as well as the JIT is not invoked for every method invocation during the life of the app.

Interesting; I thought there was some overhead due to the indirections needed to be version-resilient in the generated code. If runtime speed is actually greater, then I have less concerns about this.

My big fear is that we will end up slipping on the "dependency trimming" feature in MSBuild, and when combined with a R2R'd framework, I will end up with a 150+MB application when it used to be ~30 MB.

**Comment by gkhanna79** [comment] 2017-01-13 00:37
> some overhead due to the indirections 

This overhead exists, happens at runtime and happens only for the first time the fixup is required. R2R does not make runtime speed better - it simply alleviates the need to JIT for every call.

> will end up slipping on the "dependency trimming" feature in MSBuild

What is this about? Can you please share more details?

**Comment by mellinoe** [comment] 2017-01-13 00:44
> This overhead exists, happens at runtime and happens only for the first time the fixup is required

I see, so essentially runtime performance will become identical after this fixup is run, compared to after a "regular method" is JIT'd?

> What is this about? Can you please share more details?

This is about not publishing the entire BCL in a standalone application. Previously this was facilitated by the modular package graph. In the new world (with one giant package), we will need to do explicit analysis and trimming in order to avoid deploying unnecessary and un-reachable parts of the framework. I'm not sure where the work is tracked.

**Comment by jkotas** [comment] 2017-01-13 00:48
> so essentially runtime performance will become identical after this fixup is run

There is performance loss, but it is primarily caused by lack of cross-module inlining.

**Comment by jkotas** [comment] 2017-01-13 00:48
> we will need to do explicit analysis and trimming in order to avoid deploying unnecessary and un-reachable parts of the framework

I believe @russellhadley team is working on that.

**Comment by ericstj** [comment] 2017-04-04 23:56
@Petermarcu are we ready to commit to this one?  If so I'll make the changes in core-setup.

**Comment by Petermarcu** [comment] 2017-04-04 23:59
I think so unless anything else is blocking. This will get us to parity between shared and self contained.

**Comment by ericstj** [comment] 2017-04-06 00:08
I've gotten part of the way there: https://github.com/ericstj/core-setup/commit/1693be3e83527714357c6e9f109be6912d3c637f

The remainder will likely overlap a lot with the core-setup infrastructure work that @chcosta is doing so I'm handing off to him.

The change I've made so far runs cross-gen on the binaries that we pick up from other repos.  The remainder of the work is to plumb an entry point to these depprojs so that they can be built after the host and before signing.  Then update the host signing to also sign the cross-gen'ed bits.  After doing that the packaging should be made to build without rerunning cross-gen (eg: /p:BuildPackageLibraryReferences=false).  Then delete all the shared-framework cross-gening and signing.

**Comment by weshaggard** [comment] 2017-04-25 20:06
@chcosta is this still on your radar for enabling in core-setup?

**Comment by ericstj** [comment] 2017-04-28 19:04
Closing in favor of https://github.com/dotnet/core-setup/issues/1550 since we only need one issue tracking this and the work is happening in core-setup.

**Closed by ericstj** 2017-04-28 19:04 UTC
Labels: area-Infrastructure, enhancement
