### ISSUE TITLE
System.Net.Sockets tests hung

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20747] opened 2017-06-06 20:11 UTC
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/centos7.1_release_prtest/228/consoleText
```
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
/mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_release_prtest/Tools/tests.targets(345,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build. [/mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_release_prtest/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
```

No other information available. @mellinoe @MattGal in this case we definitely terminated the test, and it's not possibel to investigate unless we enable dumpling to grab dumps from the relevant processes before we kill them.

**Comment by mellinoe** [comment] 2017-06-06 20:20
I wonder how we can accomplish that, though. I believe Jenkins terminates our stuff once it reaches the timeout limit, right? Should we have a finer-grained timeout feature within test execution that knows how to handle this case?

**Comment by davidsh** [comment] 2017-11-30 21:59
Needs investigation.

**Comment by MattGal** [comment] 2017-11-30 22:40
Couple Points:

- Today in official runs of rel/2.0.0 we're only using Centos 7.3.  We have machine pools and work queues for 7.1, can add this if desired.
- From this log: 
https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20171121.02/workItem/System.Net.Sockets.Tests/wilogs  ... the test is passing without hang in the most recent rel/2.0.0 run on 7.3.
- Thanks to the awesome investigations of @wfurt we added some firewall exceptions to Centos (all) on 11/8 that should help with these tests timing out.

Also, the Dumpling folks are working now (I've only seen a prototype on Windows but it's not far from usable) on automated dumps of timeouts.

**Comment by wfurt** [comment] 2017-12-07 20:00
I'm closing for now unless new evidence pops up. It seems like the original post is very old and new hangs fixed. I would suggest to open new bug if this happens again as root cause may be different.

**Closed by wfurt** 2017-12-07 20:00 UTC
Labels: area-System.Net.Sockets, bug, os-linux, test-run-core
