### ISSUE TITLE
Using HttpClient.PatchAsync() from .NET Standard 2.0 library

### ISSUE THREAD

**Issue by cclauson** [dotnet/corefx#34534] opened 2019-01-10 23:33 UTC
HttpClient.PatchAsync() is documented:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.patchasync?view=netcore-2.2

Is this only available in .NET Core, and not .NET Standard?

Thanks!

**Comment by davidsh** [comment] 2019-01-11 00:16
`HttpClient.PatchAsync` is not part of .NET Standard 2.0.

It is part of the current .NET Core.

@terrajobst Can you comment on whether this API will eventually be part of a future .NET Standard?

cc: @karelz

**Comment by karelz** [comment] 2019-01-11 03:31
I think .NET Standard API requests should be done in https://github.com/dotnet/standard repo, but I am not 100% sure - @terrajobst?

**Comment by karelz** [comment] 2019-01-15 17:23
@terrajobst ping?

**Comment by karelz** [comment] 2019-01-23 17:07
Duplicate of https://github.com/dotnet/standard/issues/1056

**Closed by karelz** 2019-01-23 17:07 UTC
Labels: area-System.Net.Http, question
