### ISSUE TITLE
Two ComponentModel tests fail after updating dependencies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12372] opened 2016-10-05 03:22 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1099/
```
System.ComponentModel.Tests.PropertyDescriptorTests.CopyConstructorAddsAttribute [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
  Finished linking needed files, moving to running tests.
  Running tests... Start time: 20:07:00.76
  Command(s):
  call CoreRun.exe xunit.console.netcore.exe System.ComponentModel.TypeConverter.Performance.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.ComponentModel.TypeConverter\src\System\ComponentModel\TypeDescriptor.cs(544,0): at System.ComponentModel.TypeDescriptor.CreateProperty(Type componentType, PropertyDescriptor oldPropertyDescriptor, Attribute[] attributes)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.ComponentModel.TypeConverter\tests\PropertyDescriptorTests.cs(19,0): at System.ComponentModel.Tests.PropertyDescriptorTests.CopyConstructorAddsAttribute()
     System.ComponentModel.Tests.MemberDescriptorTests.MemberDescriptorFromNameAndAttributes [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: MemberDescriptorFromNameAndAttributes
        Actual:   
                  ↑ (pos 0)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.ComponentModel.TypeConverter\tests\MemberDescriptorTests.cs(49,0): at System.ComponentModel.Tests.MemberDescriptorTests.MemberDescriptorFromNameAndAttributes()
```

**Comment by karelz** [comment] 2016-10-05 17:11
@stephentoub is it consistent failure (aka regression)?

**Comment by stephentoub** [comment] 2016-10-05 17:12
Yes. The tests are new, they passed, then changes came in around new attribute members, they failed.

**Comment by AlexGhiondea** [comment] 2016-10-05 18:16
@twsouthwick this might be caused by the introduction of the IsDefaultAttribute/TypeId/Match overrides which might make the change you did a while back not work as expected.

I am going to implement the methods in all the attributes now.

**Comment by twsouthwick** [comment] 2016-10-05 18:36
Perfect - that was my first guess when I saw the failures since these features were slated to come online.

**Comment by AlexGhiondea** [comment] 2016-10-05 19:14
Re-introducing the right overloads fixes the issues.

**Comment by karelz** [comment] 2016-10-08 02:45
@AlexGhiondea is there anything left, or should we close the issue?

**Comment by AlexGhiondea** [comment] 2016-10-08 14:41
Yes. The tests have not yet been re-enabled. I am waiting for the updated packages to be available. 
I will finish this Monday.

**Closed** 2016-10-11 15:27 UTC
Labels: area-System.ComponentModel, bug
