### ISSUE TITLE
"Cyclic" (but not cyclic) generic structure results in ReflectionTypeLoadException

### ISSUE THREAD

**Issue by ApocDev** [dotnet/corefx#24271] opened 2017-09-27 00:52 UTC
In the full .NET platform, the following is a non-issue, however in .NET Core/Standard, it results in a ReflectionTypeLoadException (with a fairly useless exception message)

Given the following structures:

```c#
    public struct GenericStruct<T> where T : struct
    {
        public IntPtr Ptr;
    }

    public struct StructA
    {
        public GenericStruct<StructB> B;
    }

    public struct StructB
    {
        public GenericStruct<StructA> A;
    }
```

Notice that StructA has a reference to StructB, and vice versa, however neither structure actually implements a field containing either. (They boil down to `IntPtr Ptr`)

In the full framework, these types of things are allowed, and (at least personally) used heavily in certain interop scenarios to help with native code interfaces that use a lot of templates.

Loading the assembly via `AssemblyLoadContext.Default.LoadFromAssemblyPath` and calling `GetTypes` on it results in the following ReflectionTypeLoadException:

> Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Could not load type 'GenericStructureTest.StructB' from assembly 'GenericStructureTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'GenericStructureTest.StructA' from assembly 'GenericStructureTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

[EDIT] Add C# syntax highlighting by @karelz

**Comment by danmosemsft** [comment] 2017-09-27 03:17
@ApocDev could you share a more complete repro case? I tried the code below on .NET Core and on desktop (flipping the commented lines) and get the same output. I'm guessing it's necessary to load from separate assemblies.
```c#
using System.Reflection;
using System;
using System.Collections.Generic;
using System.Linq;

namespace repro
{
    public struct GenericStruct<T> where T : struct
    {
        public IntPtr Ptr;
    }

    public struct StructA
    {
        public GenericStruct<StructB> B;
    }

    public struct StructB
    {
        public GenericStruct<StructA> A;
    }

    internal class Program
    {
        public static void Main()
        {
            var a = System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromAssemblyPath(Assembly.GetExecutingAssembly().CodeBase.Replace("file:///", ""));
            //var a = Assembly.LoadFrom(Assembly.GetExecutingAssembly().CodeBase);

            try
            {
                a.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                ex.LoaderExceptions.ToList().ForEach(x => Console.WriteLine(x.ToString()));
            }

        }

    }
}
```

**Comment by ApocDev** [comment] 2017-09-27 10:57
Yes, you must have the structures in a separate assembly, without a direct reference from the "console" assembly.

For example, given the following project structure:

- GenericStructure.csproj 
- ConsoleTest.csproj

Neither project with a dependency on each other. GenericStructure contains the structures in question, and the ConsoleTest simply contains something similar to the following:
```
using System;
using System.Reflection;
using System.Runtime.Loader;

namespace ConsoleTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            try
            {
                var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(@"..\..\netstandard2.0\GenericStructure.dll");
                Type[] types = assembly.GetTypes();
                Console.WriteLine($"Assembly loaded with {types.Length} types.");
            }
            catch (ReflectionTypeLoadException ex)
            {
                Console.WriteLine(ex.Message);
                foreach (var lex in ex.LoaderExceptions)
                    Console.WriteLine(lex.Message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            Console.ReadLine();
        }
    }
}
```
If it is simpler, I can just provide my test sln.

I did test this with the structures being in the "console" assembly, and there didn't seem to be an issue, it's only when using `LoadFromAssemblyPath` on an assembly that isn't already loaded.

**Comment by jkotas** [comment] 2017-10-05 19:50
> In the full .NET platform, the following is a non-issue

This recursive generic definition does not work in neither .NET Framework not .NET Core. Both of them fail with the same TypeLoadException.

It is duplicate of https://github.com/dotnet/coreclr/issues/7957

**Closed** 2017-10-12 20:09 UTC
Labels: area-System.Runtime
