### ISSUE TITLE
.NET Core 2.2 CultureInfo derivation from .NET Framework 4.7.1

### ISSUE THREAD

**Issue by mahidaturgana** [dotnet/corefx#36524] opened 2019-04-01 17:15 UTC
While using CultureInfo provided in .NET Core 2.2, I noticed a difference in one of the values from its counterpart in .NET Framework 4.7.1.

`new CultureInfo("es-ES").DisplayName;`

.NET Core 2.2 displays the value as: "Spanish (Spain, International Sort)"
.NET Framework 4.7.1 displays the value as: "Spanish (Spain)"

Is this intended?

**Comment by Gnbrkm41** [comment] 2019-04-01 17:25
Could you tell what the `CultureInfo.CurrentCulture` was when running? I cannot seem to test it because the DisplayName depends on the UI culture (it's giving me Spanish in Korean.)

**Comment by mahidaturgana** [comment] 2019-04-01 17:31
@Gnbrkm41 - Both were run under en-US

**Comment by Gnbrkm41** [comment] 2019-04-01 21:12
Can repro on Core 3.0 P3.

**Comment by karelz** [comment] 2019-04-02 00:20
Duplicate of #36531

**Comment by Gnbrkm41** [comment] 2019-04-02 09:45
Is it a duplicate? this one is about DisplayName returning slightly different text when compared to netfx, and mine's about DisplayName not following the `CultureInfo.CurrentCulture`.

**Comment by karelz** [comment] 2019-04-02 16:14
Fair, the descriptions were too similar, so I thought it was dupe, sorry ...

**Comment by Gnbrkm41** [comment] 2019-04-02 17:06
In my opinion, I think the current behaviour is somewhat desirable; Sure, it is different from what .NET Framework did but it actually is including more detail than what it used to. I can't imagine what kind of things this will break due to incompatibility between full framework and Core.

**Comment by mahidaturgana** [comment] 2019-04-02 17:15
@Gnbrkm41 - If that bit of data is what you want why not just use EnglishName? In this context both .NET Core and .NET Framework's EnglishName return "Spanish (Spain, International Sort)".

**Comment by Gnbrkm41** [comment] 2019-04-02 17:38
I don't have a use for it, to be honest. It's just a thought about it.

* [DisplayName](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.displayname?view=netcore-2.2#System_Globalization_CultureInfo_DisplayName)
* [EnglishName](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.englishname?view=netcore-2.2)

Also, documents for both properties mention that this returns the locale information in the same `languagefull [country/regionfull]` format (albeit one in the localised format), which makes me think that both should be the same if the language used in the current locale is English. If they are supposed to be in the same format, and if the system locale uses English, then by definition `EnglishName` is already _the full localized culture name_, and therefore they should be the same, isn't it?

I don't disagree with the fact that this is a breaking change from .NET Framework. [Even the example given in the CultureInfo docs](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netcore-2.2#examples) results in `Spanish (Spain)`. It's just that I don't think it should be changed only because it is different from what .NET Framework did.

**Comment by Gnbrkm41** [comment] 2019-04-02 17:44
Other way around, why do you want the string to be in that format?

**Comment by tarekgh** [comment] 2019-04-02 18:08
I am closing this one again as duplicate of #36531

Here is some more information:

- We have different behavior when requesting DisplayName on .NET Core than the full framework. The full framework try to get the needed data from the resources. In .NET Core we don't carry such resources (so far by design). 
- For this specific es-ES, the full framework resources has the name ```Spanish (Spain)``` and that is why you are seeing that. 
- In .NET Core looks most of the time we call the OS  to get the name. and we use what we get here.

We'll continue having some discrepancy between .NET Core and the full framework because we don't carry any resources.

**Closed by tarekgh** 2019-04-02 18:08 UTC
Labels: area-System.Globalization, bug
