### ISSUE TITLE
NetworkInterface.GetIsNetworkAvailable fails with exception that can't be caught

### ISSUE THREAD

**Issue by AlexanderSher** [dotnet/corefx#22048] opened 2017-07-10 20:31 UTC
Reproduced in Bash/WSL on Ubuntu on Windows.

1. Create .Net Core Console App with the following code:
```cs
        static void Main(string[] args) {
            try {
                if (NetworkInterface.GetIsNetworkAvailable()) {
                    Console.WriteLine("Available!");
                } else {
                    Console.WriteLine("Unavailable!");
                }
            } catch (Exception) {
                Console.WriteLine("Crashed!");
            }
        }
```
2. Open bash and execute "dotnet run"

**Actual**
Application crashes with `FileNotFoundException`:
```cs
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/proc/sys/net/ipv4/conf/eth0/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStr
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, File
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* l
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDis
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at DotNetCoreGetNetworkLoad.Program.Main(String[] args) in /mnt/d/Work/Temp/DotNetCoreGetNetworkLoad/DotNetCoreGetNetworkLoad/Program.cs:line 11
```

**Expected**
Console prints either `Available!` or `Unavailable!`

**Comment by mellinoe** [comment] 2017-07-10 21:02
This is because `Interop.Sys.EnumerateInterfaceAddresses` starts a reverse PInvoke call, and everything in the call chain after this must never throw an exception, because they are uncatchable in a reverse PInvoke. It seems that in "Bash on Windows", some expected system files do not exist, which causes an uncatchable `FileNotFoundException`.

These calls need to be made resilient to missing files:

https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxIPv4InterfaceProperties.cs#L39
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxIPv4InterfaceProperties.cs#L45
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxIPv6InterfaceProperties.cs#L31

In general, we should take a look at all of the calls that the reverse PInvoke makes to ensure there's no possibility of unhandled exceptions.

**Comment by attilah** [comment] 2017-10-23 18:26
Any work is being done on this?

**Comment by WillooWisp** [comment] 2018-01-13 09:21
I experience this as well, please fix since debugging VS Code on Windows through WSL would be nice, but currently it is to limited due to this issue.

**Comment by danmosemsft** [comment] 2018-01-13 15:36
Nobody is working on this at the present moment but A PR would be welcomed if anyone is interested.

**Comment by WillooWisp** [comment] 2018-01-14 21:39
But clearly it is very easily reproduced, why not add it to the backlog?

**Comment by karelz** [comment] 2019-10-02 18:55
Triage: Does it happen on WSL2?
@ManickaP can you please check it?

**Comment by ManickaP** [comment] 2019-10-04 10:49
@karelz It runs on WSL2, the file is present. However this was already fixed in [PR 32350](https://github.com/dotnet/corefx/pull/32350). I retested it on WSL1 and it doesn't crash, returns `Unavailable!`.

I'm closing it, it's already fixed.

**Closed by ManickaP** 2019-10-04 10:49 UTC
Labels: area-System.Net, bug, os-windows-wsl
