### ISSUE TITLE
[CI Failure] AccessViolationException in System.Net.Mail.Functional.Tests

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16371] opened 2017-02-22 03:25 UTC
Found here during a code coverage run: https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_prtest/31/consoleFull#-61246470379fe3b83-f408-404c-b9e7-9207d232e5fc

```
08:26:44   Unhandled Exception: 
08:26:44   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
08:26:44      at System.Net.DebugThreadTracking.SetThreadKind(ThreadKinds kind)
08:26:44      at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in D:\j\workspace\code_coverage---d5838fef\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 69
08:26:44      at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
08:26:44      at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
08:26:44   System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
08:26:44      at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
08:26:44      at System.Net.Sockets.NetworkStream..ctor(Socket socket, Boolean ownsSocket) in D:\j\workspace\code_coverage---d5838fef\src\System.Net.Sockets\src\System\Net\Sockets\NetworkStream.cs:line 42
08:26:44      at System.Net.Sockets.TcpClient.GetStream() in D:\j\workspace\code_coverage---d5838fef\src\System.Net.Sockets\src\System\Net\Sockets\TCPClient.cs:line 149
08:26:44      at System.Net.Mail.Tests.SmtpServer.Run() in D:\j\workspace\code_coverage---d5838fef\src\System.Net.Mail\tests\Functional\SmtpServer.cs:line 60
08:26:44      at System.Threading.Thread.ThreadMain_ThreadStart() in D:\j\workspace\code_coverage---d5838fef\src\System.Threading.Thread\src\System\Threading\Thread.cs:line 103
08:26:44      at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
08:26:44      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:26:44      at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Priya91** [comment] 2017-03-14 21:34
This seems related to issues #16348  #15839

Code coverage runs producing AV in multiple test libs..

**Comment by karelz** [comment] 2017-03-14 22:44
Dupe of #17127

**Closed by karelz** 2017-03-14 22:44 UTC
Labels: area-System.Net, os-windows, test-run-core
