### ISSUE TITLE
HttpClient on UWP does not parse all cookies

### ISSUE THREAD

**Issue by SolalPirelli** [dotnet/corefx#11207] opened 2016-08-28 13:11 UTC
**Code**: https://1drv.ms/u/s!AhFj09QCPE9Yhsohgs1Hn3_coKtb2g

**Steps to run**: Run the project; breakpoints are already set. You'll need Fiddler to look at the HTTP request it's making.

**Expected**: Both cookies the server sends should be in `HttpResponseMessage`'s `Set-Cookie` headers.

**Actual**: Only one cookie is parsed, the other one is an empty value.

This does _not_ appear to be #6737, I can't get it to repro. I've included its test case in the repro code just in case, there's one line to uncomment.

**Comment by davidsh** [comment] 2016-08-28 14:59
@SolalPirelli What version of Windows is this running on?  I assume it's Windows 10, but please let me know that exact version.  Open up a cmd.exe window and type `ver`.  Then let me know the output.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/7684835/18034572/4538e494-6cf5-11e6-93fe-662bfdc6d819.png)

There were some bugs in the cookie processing logic of HttpClient. Some of the bugs required the most recent version of Windows 10.

**Comment by SolalPirelli** [comment] 2016-08-28 15:27
10.0.14393 indeed.

**Comment by davidsh** [comment] 2016-08-28 17:35
Do you have a repro without using SSL? This is hard to debug using SSL. I see that you specify redirection in the URL but yet have turned off redirection in the HttpClientHandler.  Does this repro without a redirection response.

I'm wondering if this is related to #9003.

**Comment by davidsh** [comment] 2016-08-28 18:06
I did a little more debugging. There is something going on here. In fact, I modified the repro you had so that I could see the `HttpClientHandler.CookieContainer` and see how many cookies were in that. It showed 0 cookies which is wrong.

And the response headers using Fiddler vs. looking in Visual Studio at the HttpResponseMessage object itself are different.  There is something about that 2nd cookie that is causing problems.

```
RESPONSE (as seen by HttpResponseMessage)
{StatusCode: 302, ReasonPhrase: 'Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Server: Apache/2.2.15
  Server: (Red Hat)
  Location: https://tequila.epfl.ch/tequila/auth?requestkey=26hgafpqbsul3a2gsx51sdgu5tnvgt2w
  Set-Cookie: Tequila_OAuth2IdP=removed; path=/; expires=Sun 28-Aug-2016 16:58:40 GMT;
  Set-Cookie: 
  Date: Sun, 28 Aug 2016 17:58:40 GMT
  WWW-Authenticate: Tequila serverurl="https://tequila.epfl.ch/tequila" requestkey="26hgafpqbsul3a2gsx51sdgu5tnvgt2w"
  Content-Length: 264
  Content-Type: text/html; charset=iso-8859-1
}}

RESPONSE (as seen by Fiddler)
HTTP/1.1 302 Found
Date: Sun, 28 Aug 2016 17:58:40 GMT
Server: Apache/2.2.15 (Red Hat)
WWW-Authenticate: Tequila serverurl="https://tequila.epfl.ch/tequila" requestkey="26hgafpqbsul3a2gsx51sdgu5tnvgt2w"
Set-Cookie: Tequila_OAuth2IdP=removed; path=/; expires=Sun 28-Aug-2016 16:58:40 GMT;
Set-Cookie: Tequila_req_OAuth2IdP=26hgafpqbsul3a2gsx51sdgu5tnvgt2w; path=/;
Location: https://tequila.epfl.ch/tequila/auth?requestkey=26hgafpqbsul3a2gsx51sdgu5tnvgt2w
Content-Length: 264
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

**Comment by davidsh** [comment] 2016-08-29 01:05
In terms of the number of cookies that should end up in an `HttpClientHandler.CookieContainer` object, there should be only 1. The first cookie sent () appears to be an expired cookie all the time.

I tested this code using a non-UWP app (ASP.NET Core app). It works fine.

I think I understand where the bug might be. The UWP version of System.Net.Http runs on top of WinRT Windows.Web.Http. This stack has some differences especially in how the 'Set-Cookie' header shows up when enumerating the HTTP response headers.

In particular, the Windows.Web.Http stack returns a single `Set-Cookie` header string with both cookies even though the server actually sent two separate `Set-Cookie` headers.  

```
Set-Cookie: Tequila_OAuth2IdP=removed; path=/; expires=Mon 29-Aug-2016 00:00:01 GMT;, Tequila_req_OAuth2IdP=kkkegg62o4lhjly27zs0kussuddqt2jg; path=/;
```

We have some to separate those out so that they appear as two `Set-Cookie` headers. This code is done here via the `CookieHelper` class:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/netcore50/System/Net/CookieHelper.cs

I think this is where the bug lies and the 2nd cookie is getting lost during this split parsing.

**Comment by davidsh** [comment] 2016-08-29 03:22
cc: @CIPop @stephentoub 

I think I understand why the 2nd cookie is not being parsed correctly.  The problem is that once the 2 separate 'Set-Cookie' headers were combined by the UWP stack, the .NET cookie parser is looking for the comma that separates the 2 cookies in order to split them apart again.

The unique thing here is that the first cookie from this server is missing an expected comma character after the day of week.  The RFC for cookies
https://tools.ietf.org/html/rfc6265#section-5.1.1

specifies that the date format for the "Expires" attribute be in a format such as:

```
Sun, 28-Aug-2016 16:58:40 GMT
```

Note the comma after the day of week ("Sun"). However, the actual 'Set-Cookie' header from this server doesn't have that comma after the day of week:

```
Set-Cookie: Tequila_OAuth2IdP=removed; path=/; expires=Mon 29-Aug-2016 00:00:01 GMT;
```

I think this lack of a comma is confusing the CookieParser logic that is used to separate out the cookies. There is also a different bug in that it is allowing an empty string to be added to the collection of cookies returned (probably need an Assert in the code). This code is very old and we don't have a lot of tests in this specific area.

I don't know why this server is returning a malformed date format (without the comma after day of week). Some HTTP stacks might be more resilient to parsing problems like this.  We might need to figure out how to make this .NET cookie parser able to handle small issues like this.

**Comment by davidsh** [comment] 2016-08-29 20:09
I did some research and wrote additional tests.

It turns out that there are 2 problems with these cookies from this particular server. Both of the problems are because the cookies are malformed (in small ways) according to the RFC.

The first problem is that the date format in the "expires" attribute is missing the comma after the day of week. The second problem is that there is a trailing semi-colon after the last attribute of the cookies.  The "path" attribute has a trailing semi-colon.

The semi-colon character is used as a separator between attributes in a 'Set-Cookie' header.  It should not be used as a terminator for each attribute.

https://tools.ietf.org/html/rfc6265#section-4.1.1

These problems combined are what is causing the bug you see.

**Comment by Priya91** [comment] 2017-02-16 00:04
Per @davidsh last comment, seems like the bug is caused due to malformed cookies from server. Closing the issue as not a bug in .net.

**Comment by SolalPirelli** [comment] 2017-02-16 00:24
@Priya91 Sure, it's malformed cookies from the server, but dealing with non-compliant servers is part of a client's job; also, the full .NET Framework handles it just fine, so it's a regression in .NET for UWP.

**Comment by Priya91** [comment] 2017-02-16 00:46
@SolalPirelli Is the implementation from desktop giving a non-empty value for malformed cookie?

**Comment by Priya91** [comment] 2017-02-16 01:10
I checked the following code under desktop and .NET Core 1.1, they have the same output:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ParseCookies
{
    class Program
    {
        static void Main(string[] args)
        {
            MyBug().GetAwaiter().GetResult();
        }

        private static async Task MyBug()
        {
            var url = "https://tequila.epfl.ch/cgi-bin/OAuth2IdP/auth?response_type=code&client_id=1b74e3837e50e21afaf2005f@epfl.ch&redirect_uri=https://pocketcampus.epfl.ch/&scope=Tequila.profile,Moodle.read,ISA.read,Camipro.read,Camipro.write&doauth=Approve";
            var client = new HttpClient(new HttpClientHandler
            {
                AllowAutoRedirect = false
            });

            // Open Fiddler when this breakpoint is hit
           // Debugger.Break();

            var response = await client.GetAsync(url);
            var cookies = response.Headers.GetValues("Set-Cookie");

            // Compare the Fiddler response with the cookies here.
            // There *should* be 'Tequila_OAuth2IdP' with value 'removed',
            // and 'Tequila_req_OAuth2IdP' with some random chars as value.
            //Debugger.Break();
            foreach (var cookie in cookies)
            {
                Console.WriteLine(cookie);
            }
        }
    }
}
```

On desktop:

```
Tequila_OAuth2IdP=removed; path=/; expires=Thu 16-Feb-2017 00:09:25 GMT;
Tequila_req_OAuth2IdP=11hhh4o0rfhludqjtconxytly7fa3qgb; path=/;
```

From .NET Core 1.1

```
Project parsecookies (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Tequila_OAuth2IdP=removed; path=/; expires=Thu 16-Feb-2017 00:08:31 GMT;
Tequila_req_OAuth2IdP=gvuzuzwloaujypxy0wp3vbol55ka6wys; path=/;
```

**Comment by davidsh** [comment] 2017-02-16 01:38
> @davidsh do you know where the difference in UWP is from?

The UWP version of System.Net.Http dll is very different than the non-UWP version.  The UWP version uses the code in 'netcore50' source directory.  It uses the WinRT Windows.Web.Http stack (based on Wininet).  This is very different from the non-UWP System.Net.Http.dll which on .NET Core uses WinHTTP.

If you want to repro this problem, you need to write a UWP app.

**Comment by davidsh** [comment] 2017-02-16 01:40
>Although am confused, UWP should be using .net core binaries

Yes, UWP uses the System.Net.Http package built from CoreFx.  So, it is ".net core binaries".  But remember that there are multiple binaries in the NuGet package.  The UWP one is using the 'netcore50' target (to be renamed the uap10.1 target).  This is a different binary than non-UWP.  Most of the source code is the same for System.Net.Http except the implementation of the handler (HttpClientHandler).

**Comment by davidsh** [comment] 2017-08-06 17:33
Update on this issue:

PR https://github.com/dotnet/corefx/pull/22895 fixed the problem where a trailing semi-colon after a cookie would prevent that cookie to be read.

**Comment by davidsh** [comment] 2017-08-06 17:52
I have also re-checked the behavior on .NET Framework (Desktop) and .NET Core.  In both cases, a cookie with a malformed date string (in this case, a comma missing after the day-of-the-week) is not a valid cookie and will not be added to the CookieContainer.  However, the 'Set-Cookie:" raw header will still show up in the HttpResponseMessage.Headers collection.

At this point, with #22895 fixed (for UWP6.0 milestone), the behaviors of .NET Framework, .NET Core and UWP all match.  So, closing this issue now.

**Closed by davidsh** 2017-08-06 17:52 UTC
Labels: area-System.Net, bug, os-windows-uwp
