### ISSUE TITLE
Failure in EnumerateEnvironmentVariables

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16518] opened 2017-02-28 01:59 UTC
This is the test fixed in #16156, now it's failing in a new way. @JeremyKuhne 

https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3892/consoleText

```
     System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(target: Process) [FAIL]
        Assert.Equal() Failure
        Expected: true
        Actual:   (null)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime.Extensions\tests\System\Environment.GetEnvironmentVariable.cs(199,0): at System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(EnvironmentVariableTarget target)
  Finished:    System.Runtime.Extensions.Tests
```

**Comment by JeremyKuhne** [comment] 2017-02-28 02:10
Dupe of #16481

**Closed by JeremyKuhne** 2017-02-28 02:10 UTC
Labels: area-System.Runtime, blocking-clean-ci
