### ISSUE TITLE
Remove dependency System.Private.Xml dependency on System.Reflection.Emit.* on uapaot

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#18283] opened 2017-04-12 17:53 UTC
System.Reflection.Emit.* is not available on uapaot. System.Private.Xml dependency on System.Reflection.Emit.* should be removed.

https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System.Private.Xml.csproj#L517

**Comment by sepidehMS** [comment] 2017-06-06 20:32
@krwq This seems to be a dupe of https://github.com/dotnet/corefx/issues/20739

**Comment by krwq** [comment] 2017-06-06 20:36
Yep

**Closed by krwq** 2017-06-06 20:36 UTC
Labels: area-System.Xml, bug, os-windows-uwp
