### ISSUE TITLE
 zombie process when start a linux process in dotnet core 

### ISSUE THREAD

**Issue by mayamoon** [dotnet/corefx#19695] opened 2017-05-12 02:54 UTC
```c#
            var processId = Process.GetCurrentProcess().Id;
            var process = Process.Start(new ProcessStartInfo
            {
                FileName = @"top",
                Arguments = $@" -n 1 -p {processId} -b",
                RedirectStandardOutput = true,
            });
            process.Start();
            process.WaitForExit();
            
            var result = await process.StandardOutput.ReadToEndAsync().ConfigureAwait(false);
            try
            {
                process.Kill();
              
            }
            finally {
                process.Dispose();
            }
        
            return result.Trim();
```
when this application run .
it cause  a  zombie procss in linux
![image](https://cloud.githubusercontent.com/assets/8044586/25980482/693e413c-3701-11e7-92bb-fa6cc05a0f32.png)

**Comment by stephentoub** [comment] 2017-05-12 16:54
I'm not able to repro this.  I also don't understand the repro code, e.g. that Kill should fail because you've already waited for the process to exit.

What OS are you on?  What version of .NET Core are you using?

**Comment by stephentoub** [comment] 2017-05-21 15:18
@mayamoon?

**Comment by stephentoub** [comment] 2017-05-23 21:02
Closing for now due to lack of details.  @mayamoon, if this issue persists for you, please re-open and share more details on the environment as well as a small repro we can run to try to reproduce it.  Thanks.

**Closed by stephentoub** 2017-05-23 21:02 UTC
Labels: area-System.Diagnostics.Process

**Comment by flaksirus** [comment] 2017-10-04 19:34
It's well reproduced by this code:
``` cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace testApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Lets run 1000 processes!");
            for(int i=0; i<1000; i++)
                RunNewProcess();

            Console.ReadLine();
        }

        static void RunNewProcess()
        {
            var process = CreateProcess(@"top", "-n 1 -b");

            Task.Run(() => WaitProcessSync(process));
        }

        static bool WaitProcessSync(Process process, int timeoutMs = -1)
        {
            var result = false;
            using(process)
            {
                process.OutputDataReceived += (sender, args) => {};
                process.ErrorDataReceived += (sender, args) => {};

                process.Start();
                process.BeginOutputReadLine();
                if (!process.WaitForExit(timeoutMs))
                    process.Kill();

                process.CancelOutputRead();      
                result = process.ExitCode == 0;
            }
            return result;
        }

        static Process CreateProcess(string path, string args)
        {
            var process = new Process();

            ProcessStartInfo startInfo = new ProcessStartInfo(path, args);
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardOutput = true;
            startInfo.RedirectStandardError = true;
            startInfo.RedirectStandardInput = true;

            process.StartInfo = startInfo;

            return process;
        }
    }
}
```
The key to resolve this issue is set the property Process.EnableRaisingEvents equels true:
``` cs 
process.EnableRaisingEvents = true;
```
