### ISSUE TITLE
When use the when keyword in a catch expression the app crashes instead of do what the document says

### ISSUE THREAD

**Issue by walterlv** [dotnet/corefx#41047] opened 2019-09-12 01:01 UTC
## Issue

The document [Using User-Filtered Exception Handlers](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers) says:

> The expression of the user-filtered clause is not restricted in any way. If an exception occurs during execution of the user-filtered expression, that exception is discarded and the filter expression is considered to have evaluated to false. In this case, the common language runtime continues the search for a handler for the current exception.

When there is an exception occurred in the when expression the exception will be ignored and the expression will return false.

This works in .NET Core and also works in .NET Framework in old-style project. But the app will **crash** when building a .NET Framework app using sdk-style project.

Maybe it's a bug in the sdk-style project.

## Demo

See such a demo below:

```csharp
try
{
    try
    {
        Console.WriteLine("Try");
        throw new FileNotFoundException();
    }
    catch (FileNotFoundException ex) when (ex.FileName.EndsWith(".png"))
    {
        Console.WriteLine("Catch 1");
    }
    catch (FileNotFoundException)
    {
        Console.WriteLine("Catch 2");
    }
}
catch (Exception)
{
    Console.WriteLine("Catch 3");
}
Console.WriteLine("End");
```

This is the output of .NET Core 3.0 and everything works fine:

![image](https://user-images.githubusercontent.com/9959623/64590498-437b5c00-d3da-11e9-895b-5494c5eee268.png)

But this is the output of .NET Framework 4.8 and we can notice that the app crashes:

![image](https://user-images.githubusercontent.com/9959623/64590536-5b52e000-d3da-11e9-9df9-b61aa020a5d1.png)

---

The original issue is here:

- [When use the when keyword in a catch expression the app crashes instead of do what the document says · Issue #14338 · dotnet/docs](https://github.com/dotnet/docs/issues/14338)

The document is here:

- [Using User-Filtered Exception Handlers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers)

**Comment by jkotas** [comment] 2019-09-12 05:02
Duplicate of https://github.com/dotnet/coreclr/issues/25534

**Comment by am11** [comment] 2019-09-12 06:32
Configuration knob works with both:

Environment variable
```sh
set COMPlus_legacyCorruptedStateExceptionsInFilterPolicy=1
dotnet run
```
and app.config

```xml
<configuration>
  <runtime>
    <legacyCorruptedStateExceptionsInFilterPolicy enabled="true" />
  </runtime>
</configuration>
```

delete `obj` directory before `dotnet run` in case of app.config changes.

**Comment by walterlv** [comment] 2019-09-12 06:46
@jkotas Thanks for helping me find the duplicated one. I searched everywhere yesterday but I can't find my original issue so I reported a new one. Sorry about that. Maybe this one can be closed.

**Closed** 2019-09-12 07:04 UTC
