### ISSUE TITLE
WinHttpHandler/CurlHandler hangs or fails when connection pooling and connection dropped

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#27067] opened 2018-02-12 16:51 UTC
See GetAsync_DontDisposeResponse_EventuallyUnblocksWaiters test.  It sets MaxConnectionsPerServer to 1, and then proceeds to issue a ResponseHeadersRead request but drops the response object without disposing it.  It then creates a second request to the same server, and that request is never processed.

**Comment by davidsh** [comment] 2018-04-16 20:00
>It sets MaxConnectionsPerServer to 1, and then proceeds to issue a ResponseHeadersRead request but drops the response object without disposing it. It then creates a second request to the same server, and that request is never processed.

@stephentoub Why would you expect this test to do anything other than hang?  If MaxConnectionsPerServer is 1 and that connection isn't dropped (since the request/response is still using it), any further requests will need "hang" waiting for a connection to become available, or the request will timeout.

**Comment by stephentoub** [comment] 2018-04-16 20:02
> that connection isn't dropped (since the request/response is still using it)

I said "but drops the response object without disposing it".  In other words, no one is using that request/response anymore.

**Comment by davidsh** [comment] 2018-04-16 20:05
>I said "but drops the response object without disposing it". In other words, the developer isn't using that request/response anymore.

I don't see a solution here because until that object is finalized, the connection won't be closed down.

What would you suggest as a solution here? This seems like a "by design". The solution is for a developer to use .Dispose() explicitly.

**Comment by stephentoub** [comment] 2018-04-16 20:10
> I don't see a solution here because until that object is finalized, the connection won't be closed down.

That's my point: it's not finalized.

> What would you suggest as a solution here?

Either a) say we don't care and that the way forward is SocketsHttpHandler, or b) that we do care and utilize finalization/weak references/etc. to allow it to be cleaned up when dropped.

**Comment by davidsh** [comment] 2018-04-16 20:16
>utilize finalization/weak references/etc. to allow it to be cleaned up when dropped.

HttpResponseMessage implements IDisposable.  But it doesn't have an explicit finalizer  So, would it need to have an explicit finalizer for the GC to clean it up?  Won't it get finalized anyways?

Most likely the answer will be "a" and the suggestion is for developers to use SocketsHttpHandler.  But how does SocketsHttpHandler fix this?  HttpResponseMessage is still the same.

**Comment by stephentoub** [comment] 2018-04-16 21:14
> Most likely the answer will be "a" and the suggestion is for developers to use SocketsHttpHandler

I'm ok with that.

> But how does SocketsHttpHandler fix this?

It puts a finalizer on the HttpConnection object itself (or, rather, on a derived object):
https://github.com/dotnet/corefx/blob/c998e559dc3682bda42bedd8379442f1e457d136/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L370-L372
Things are arranged so that the response object is the only thing that's keeping the connection object alive.  If the response object (or its stream) gets disposed, then the connection is returned to its pool.  If the response object is dropped without being disposed, then all references to the connection also cease and it becomes eligible for GC; when its finalizer runs, the finalizer signals to the pool that space has been freed up.

**Comment by karelz** [comment] 2018-05-17 00:55
Seems that we agreed to not care - SocketsHttpClient behaves well, closing.

**Closed by karelz** 2018-05-17 00:55 UTC
Labels: area-System.Net.Http, bug
