### ISSUE TITLE
Expand the API surface/features for multicast in Sockets

### ISSUE THREAD

**Issue by PilgrimViis** [dotnet/corefx#21624] opened 2017-06-27 14:12 UTC
When I call SetSocketOption on Windows it's work, but on Linux it throws

> System.Net.Sockets.SocketException: Unknown error -1
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Byte[] optionValue)

I tried with dotnet v1.0.4 and debian 8.2. 
Example:

```c#
using System;
using System.Net;
using System.Net.Sockets;

namespace SetSocketOptionExample
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Configuration started");
            byte[] groupIp = { 0xef, 0xc3, 0x01, 0x29 };
            byte[] srcIp = { 0x5b, 0xcb, 0xfd, 0xe3 };
            Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            byte[] membershipAddresses = new byte[12];
            Buffer.BlockCopy(groupIp, 0, membershipAddresses, 0, 4);
            Buffer.BlockCopy(srcIp, 0, membershipAddresses, 4, 4);
            Buffer.BlockCopy(IPAddress.Any.GetAddressBytes(), 0, membershipAddresses, 8, 4);
            try
            {
                socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddSourceMembership, membershipAddresses);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.WriteLine("Configuration ended");
            Console.ReadLine();
        }
    }
}
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by stephentoub** [comment] 2017-06-29 14:42
@PilgrimViis, I see two issues here:
1. The main problem is that the native call to setsockopt is returning ENODEV ("no such device").  Seems like this is related to the machine's configuration?
2. We're successfully getting back the ENODEV error into Socket, but then dropping that value when the SocketException is thrown, as there's nothing ENODEV reasonably maps to in the SocketError enumeration.  We should address this by at least creating an inner exception that represents the errno value so that the cause isn't lost.

**Comment by PilgrimViis** [comment] 2017-07-03 10:02
@stephentoub, thanks for reply.
1. How did you know about it? Is it depends on machine where you're testing? I'm not big specialist in network programming and I can be wrong, but when I wrote code with same functionality on C it's works and didn't returned any -1's.
And by the way, where I can get full list of errors which can be returned by this call, cause in man (http://man7.org/linux/man-pages/man2/setsockopt.2.html) there is no ENODEV listed. 
2. It'll be very good.

**Comment by stephentoub** [comment] 2017-07-03 13:12
@PilgrimViis, can you share the C program you used?

> Is it depends on machine where you're testing?

Yes, although it's also possible there's a bug that makes it more common.

**Comment by PilgrimViis** [comment] 2017-07-03 14:24
@stephentoub, of course. 
```
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netdb.h>
#include <unistd.h>
#include <stdio.h>

#define ERROR -1

int main(int argc, char *argv[])
{
	char* sourceIp = argv[1];
	char* groupIp = argv[3];
	int port = atoi(argv[2]);
	printf("Source:%s, port:%d, group:%s\n", sourceIp, port, groupIp);
		
        struct ip_mreq_source ip_mreq_source;
      	int statusCode;

	int fd = socket(PF_INET,SOCK_DGRAM,0);	
	if (fd == ERROR){
		printf("Can't create socket\n");
		getchar();
		return -1;
	}

    /* Group */
	ip_mreq_source.imr_multiaddr.s_addr = inet_addr(groupIp);
	/* Interface */
	ip_mreq_source.imr_interface.s_addr = htonl(INADDR_ANY);
    /* Source */
	ip_mreq_source.imr_sourceaddr.s_addr = inet_addr(sourceIp);
    statusCode = setsockopt(fd,SOL_IP,IP_ADD_SOURCE_MEMBERSHIP, &ip_mreq_source,
                                sizeof(ip_mreq_source));
	printf("Setsocketopt status code: %d\n", statusCode);
	if(statusCode == ERROR){
		printf("Can't set socket optiono\n");
		getchar();
		return -1;
	}
	struct sockaddr_in bindaddr;
	bindaddr.sin_family = AF_INET;
	bindaddr.sin_port = htons(port);
	bindaddr.sin_addr.s_addr = htonl(INADDR_ANY);
	statusCode = bind(fd, (struct sockaddr*)&bindaddr,sizeof(bindaddr));
	
    if(statusCode == ERROR){
		printf("Can't bind socket\n");
		getchar();
		return -1;
	}
    
    int ret = 1;
	while(ret) {
		printf("Started recieving\n");
        char buffer[2048];
		ret=recv(fd,(char*)buffer,sizeof(buffer),0);
		write(1,buffer,ret);
		printf("\nGetted\n");
        break;
    }
       
    printf("Finished\n");
    getchar();
    return 0;
}

```

**Comment by PilgrimViis** [comment] 2017-07-04 18:45
@stephentoub, looks like structure **ip_mreq_source** defined in linux slightly different then in windows.
Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/ms738704(v=vs.85).aspx)
```
typedef struct ip_mreq_source {
  struct in_addr  imr_multiaddr;
  struct in_addr  imr_sourceaddr;
  struct in_addr  imr_interface;
} IP_MREQ_SOURCE, *PIP_MREQ_SOURCE;
```
Linux (http://man7.org/linux/man-pages/man7/ip.7.html)
```
struct ip_mreq_source {
    struct in_addr imr_multiaddr;
    struct in_addr imr_interface; 
    struct in_addr imr_sourceaddr; 
};
```
When I changed bytes order it's stopped work on Windows, but started work on linux. 
Can we do something with it? I've only one idea - define our own managed structures or classes which will be passed to SetSocketOptions.

**Comment by stephentoub** [comment] 2017-07-05 14:27
@davidsh, @cipop, it looks like there's no SetMulticastOption-equivalent for AddSourceMembership instead of AddMembership.  Is there a reason for that?  SetMulticastOption is able to smooth over the platform-specific differences here, but leaving it up to the caller to bake into their C# the native C struct data requires them to bake in the platform-specific nature of the option.

@PilgrimViis, I expect that for now your best bet is to conditionalize the call based on platform, e.g.
```C#
byte[] membershipAddresses = new byte[12];
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    ... // fill in the right options bytes for Windows
}
else
{
    ... // fill in the right options bytes for Unix
}
```

**Comment by PilgrimViis** [comment] 2017-07-05 15:03
@stephentoub, thanks for advice, but I already did it. I hope the community will find out some clever solution for this problem and I'll remove this dirty hack in future.

**Comment by davidsh** [comment] 2017-07-05 16:27
>@davidsh, @CIPop, it looks like there's no SetMulticastOption-equivalent for AddSourceMembership instead of AddMembership. Is there a reason for that? SetMulticastOption is able to smooth over the platform-specific differences here, but leaving it up to the caller to bake into their C# the native C struct data requires them to bake in the platform-specific nature of the option.

The multicast APIs were added to the .NET Framework a long time ago (about 10 -15 years ago).  At the time, the API surface added was sufficient.

If there is a desire/need to expand the API surface/features for multicast in Sockets, then we can review the proposal.  Testing multicast is difficult in the CI system and so we would want to have additional offline testing done in a controlled environment.

**Comment by PeterSmithRedmond** [comment] 2017-11-30 22:41
If the underlying structures are different on Linux than they are on Windows, then the only good solution is to make our own object (like we make for the LingerOption or MulticastOption) and then do the conversion ourselves. At the same time, we should compare each of the Linux and Windows structures and find all of the differences.

The obvious class would be something like
```C#
public class IPMReqSourceOptions
{
    public IPAddress MulticastGroupAddress;
    public IPAddress LocalInterfaceAddress;
    public IPAddress MulticastSourceAddress;
}
```

**Comment by karelz** [comment] 2019-09-10 21:02
Multicast does not seem to play that much important role anymore. E.g. in enterprise, etc.
Only 1 vote in 2 years, closing.

**Closed by karelz** 2019-09-10 21:02 UTC
Labels: api-suggestion, area-System.Net.Sockets
