### ISSUE TITLE
GZipStream throws an exception on creation since 5.0.1-rc2-23614

### ISSUE THREAD

**Issue by jeffboulanger** [dotnet/corefx#5479] opened 2016-01-16 00:43 UTC
I cannot get any version past 5.0.1-rc2-23614 to work when calling the following code.

```

        public Task<byte[]> CompressAsync(byte[] uncompressedData)
        {
            return Task.Run(() =>
            {
                using (MemoryStream compressedMemoryStream = new MemoryStream())
                {
                    using (GZipStream zipStream = new GZipStream(compressedMemoryStream, CompressionMode.Compress, true))
                    {
                        zipStream.Write(uncompressedData, 0, uncompressedData.Length);
                    }

                    return compressedMemoryStream.ToArray();
                }
            });
        }
```
Receives the following exception:
```
System.IO.Compression.ZLibException was unhandled by user code
  HResult=-2146232800
  Message=The underlying compression routine could not be loaded correctly.
  Source=System.IO.Compression
  ZLibContext=""
  ZLibErrorCode=0
  ZLibErrorMessage=""
  StackTrace:
       at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
       at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
       at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
       at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits)
       at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
       at CCC.Core.Framework.Compression.GZipCompressor.<>c__DisplayClass1_0.<CompressAsync>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: 
       HResult=-2146233052
       Message=Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
       Source=System.IO.Compression
       TypeName=""
       StackTrace:
            at Interop.zlib.deflateInit2_(Byte* stream, Int32 level, Int32 method, Int32 windowBits, Int32 memLevel, Int32 strategy, Byte* version, Int32 stream_size)
            at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
            at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
            at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
       InnerException: 
```

**Comment by stephentoub** [comment] 2016-01-16 01:51
This looks like https://github.com/dotnet/corefx/issues/5380 which was fixed by https://github.com/dotnet/corefx/pull/5481.

**Comment by ianhays** [comment] 2016-01-16 02:17
This issue certainly looks similar, though the cause of  #5380 didn't arise until rc2-23707 I believe.

@jeffboulanger can you give some more details on your setup so I can try to repro this?

**Comment by ianhays** [comment] 2016-01-21 20:38
Closing as duplicate of #5380 / non-repro.

**Closed by ianhays** 2016-01-21 20:38 UTC
Labels: System.IO.Compression
