### ISSUE TITLE
AssemblyLoadContextTest tests failing on Unix in outerloop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7252] opened 2016-03-25 19:43 UTC
I assume this is the same problem as with https://github.com/dotnet/corefx/issues/7125 and is due to https://github.com/Microsoft/msbuild/issues/541, but unless we're going to pick up a new msbuild imminently, we should temporarily change this to avoid breaking the outerloop runs.
cc: @mellinoe, @gkhanna79 
```
03:17:12      System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly [FAIL]
03:17:12         System.IO.FileNotFoundException : Could not load the specified file.
03:17:12         Stack Trace:
03:17:12               at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
03:17:12               at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly()
03:17:12   Finished:    System.Runtime.Loader.Tests
03:17:12   
03:17:12   === TEST EXECUTION SUMMARY ===
03:17:12      System.Runtime.Loader.Tests  Total: 10, Errors: 0, Failed: 3, Skipped: 0, Time: 0.265s
03:17:12      System.Runtime.Loader.Tests.AssemblyLoadContextTest.GetLoadContextTest_ValidUserAssembly [FAIL]
03:17:12         System.IO.FileNotFoundException : Could not load the specified file.
03:17:12         Stack Trace:
03:17:12               at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
03:17:12               at System.Runtime.Loader.Tests.AssemblyLoadContextTest.GetLoadContextTest_ValidUserAssembly()
03:17:12      System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly [FAIL]
03:17:12         System.IO.FileNotFoundException : Could not load the specified file.
03:17:12         Stack Trace:
03:17:12               at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
03:17:12               at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly()
```

**Comment by gkhanna79** [comment] 2016-03-28 17:26
@joshfree @weshaggard @mellinoe Are we planning to take a refresh of MSbuild for CoreFX that address https://github.com/Microsoft/msbuild/issues/541 (and fix this issue and https://github.com/dotnet/corefx/issues/7125)?

**Comment by gkhanna79** [comment] 2016-03-28 17:27
@stephentoub I presume this is a regression from MSBuild since the tests were passing earlier?

**Comment by stephentoub** [comment] 2016-03-28 17:31
> I presume this is a regression from MSBuild

Hence my comments at the beginning of the mail.

> since the tests were passing earlier?

I'm not sure they were.  Due to https://github.com/dotnet/corefx/issues/6495, we only very recently started running the inner loop tests as part of outerloop runs, which means up until very recently we weren't actually running these tests in these legs.

**Comment by gkhanna79** [comment] 2016-03-29 15:13
@joshfree @weshaggard Let me know if there are any plans to bring in new MSBuild with the fix in Rc2. If not, then moving this to RTM for now until msbuild update is in CoreFX.

**Comment by mellinoe** [comment] 2016-03-29 16:59
We actually have the new version of MSBuild that should have this fix. I can check whether these tests are fixed in a little while, but if they are like the others exhibiting this problem, then they should be fixed.

**Comment by gkhanna79** [comment] 2016-03-29 17:44
@mellinoe Thank you for the update. Will wait for your confirmation about the test pass status.

**Comment by mellinoe** [comment] 2016-03-29 18:40
I tried this out in my VM and the tests all pass now. I'll submit a PR to re-enable the tests.

**Comment by mellinoe** [comment] 2016-03-30 17:47
The latest MSBuild has fixed this issue. The tests are re-enabled with #7324 .

**Closed by mellinoe** 2016-03-30 17:47 UTC
Labels: System.Runtime
