### ISSUE TITLE
Slow Console.SetCursorPosition on Linux in .NET core

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#32174] opened 2018-09-08 00:10 UTC
_From @markfinal on September 7, 2018 21:37_

I've noticed a performance oddity in some console logging code, but only on Linux. It's working as expected in Windows and macOS. I've simplified it down to a small test case.

Repro steps:
1) create new directory & cd to it
2) dotnet new console
3) copy [the gist content](https://gist.github.com/markfinal/d7f16fef54499fb379bdf022fd31a266) into Program.cs
4) dotnet build -c Release <csproj>
5) dotnet <path to generated assembly .dll>

On Linux (Ubuntu 14):
```
mark@ubuntu:/tmp/test$ dotnet bin/Release/netcoreapp2.1/test.dll 
Hello World! 0%Hello World! 1%Hello World! 2%Hello World! 3%Hello World! 4%Hello World! 5%Hello World! 6%Hello World! 7%Hello World! 8%Hello World! 9%Hello World! 10%Hello World! 11%Hello World! 12%Hello World! 13%Hello World! 14%Hello World! 15%Hello World! 16%Hello World! 17%Hello World! 18%Hello World! 19%Hello World! 20%Hello World! 21%Hello World! 22%Hello World! 23%Hello World! 24%Hello World! 25%Hello World! 26%Hello World! 27%Hello World! 28%Hello World! 29%Hello World! 30%Hello World! 31%Hello World! 32%Hello World! 33%Hello World! 34%Hello World! 35%Hello World! 36%Hello World! 37%Hello World! 38%Hello World! 39%Hello World! 40%Hello World! 41%Hello World! 42%Hello World! 43%Hello World! 44%Hello World! 45%Hello World! 46%Hello World! 47%Hello World! 48%Hello World! 49%Hello World! 50%Hello World! 51%Hello World! 52%Hello World! 53%Hello World! 54%Hello World! 55%Hello World! 56%Hello World! 57%Hello World! 58%Hello World! 59%Hello World! 60%Hello World! 61%Hello World! 62%Hello World! 63%Hello World! 64%Hello World! 65%Hello World! 66%Hello World! 67%Hello World! 68%Hello World! 69%Hello World! 70%Hello World! 71%Hello World! 72%Hello World! 73%Hello World! 74%Hello World! 75%Hello World! 76%Hello World! 77%Hello World! 78%Hello World! 79%Hello World! 80%Hello World! 81%Hello World! 82%Hello World! 83%Hello World! 84%Hello World! 85%Hello World! 86%Hello World! 87%Hello World! 88%Hello World! 89%Hello World! 90%Hello World! 91%Hello World! 92%Hello World! 93%Hello World! 94%Hello World! 95%Hello World! 96%Hello World! 97%Hello World! 98%Hello World! 99%
Without carriage return in 2 ms
Hello World! 99%
With carriage return in 3097 ms
```

On macOS (10.13.6)
```
mark-mba:tmp mark$ dotnet bin/Release/netcoreapp2.1/tmp.dll
Hello World! 0%Hello World! 1%Hello World! 2%Hello World! 3%Hello World! 4%Hello World! 5%Hello World! 6%Hello World! 7%Hello World! 8%Hello World! 9%Hello World! 10%Hello World! 11%Hello World! 12%Hello World! 13%Hello World! 14%Hello World! 15%Hello World! 16%Hello World! 17%Hello World! 18%Hello World! 19%Hello World! 20%Hello World! 21%Hello World! 22%Hello World! 23%Hello World! 24%Hello World! 25%Hello World! 26%Hello World! 27%Hello World! 28%Hello World! 29%Hello World! 30%Hello World! 31%Hello World! 32%Hello World! 33%Hello World! 34%Hello World! 35%Hello World! 36%Hello World! 37%Hello World! 38%Hello World! 39%Hello World! 40%Hello World! 41%Hello World! 42%Hello World! 43%Hello World! 44%Hello World! 45%Hello World! 46%Hello World! 47%Hello World! 48%Hello World! 49%Hello World! 50%Hello World! 51%Hello World! 52%Hello World! 53%Hello World! 54%Hello World! 55%Hello World! 56%Hello World! 57%Hello World! 58%Hello World! 59%Hello World! 60%Hello World! 61%Hello World! 62%Hello World! 63%Hello World! 64%Hello World! 65%Hello World! 66%Hello World! 67%Hello World! 68%Hello World! 69%Hello World! 70%Hello World! 71%Hello World! 72%Hello World! 73%Hello World! 74%Hello World! 75%Hello World! 76%Hello World! 77%Hello World! 78%Hello World! 79%Hello World! 80%Hello World! 81%Hello World! 82%Hello World! 83%Hello World! 84%Hello World! 85%Hello World! 86%Hello World! 87%Hello World! 88%Hello World! 89%Hello World! 90%Hello World! 91%Hello World! 92%Hello World! 93%Hello World! 94%Hello World! 95%Hello World! 96%Hello World! 97%Hello World! 98%Hello World! 99%
Without carriage return in 3 ms
Hello World! 99%
With carriage return in 54 ms
```

On Windows (8.1):
```
C:\Users\mark\AppData\Local\Temp\test>dotnet bin\Release\netcoreapp2.1\test.dll
Hello World! 0%Hello World! 1%Hello World! 2%Hello World! 3%Hello World! 4%Hello
 World! 5%Hello World! 6%Hello World! 7%Hello World! 8%Hello World! 9%Hello Worl
d! 10%Hello World! 11%Hello World! 12%Hello World! 13%Hello World! 14%Hello Worl
d! 15%Hello World! 16%Hello World! 17%Hello World! 18%Hello World! 19%Hello Worl
d! 20%Hello World! 21%Hello World! 22%Hello World! 23%Hello World! 24%Hello Worl
d! 25%Hello World! 26%Hello World! 27%Hello World! 28%Hello World! 29%Hello Worl
d! 30%Hello World! 31%Hello World! 32%Hello World! 33%Hello World! 34%Hello Worl
d! 35%Hello World! 36%Hello World! 37%Hello World! 38%Hello World! 39%Hello Worl
d! 40%Hello World! 41%Hello World! 42%Hello World! 43%Hello World! 44%Hello Worl
d! 45%Hello World! 46%Hello World! 47%Hello World! 48%Hello World! 49%Hello Worl
d! 50%Hello World! 51%Hello World! 52%Hello World! 53%Hello World! 54%Hello Worl
d! 55%Hello World! 56%Hello World! 57%Hello World! 58%Hello World! 59%Hello Worl
d! 60%Hello World! 61%Hello World! 62%Hello World! 63%Hello World! 64%Hello Worl
d! 65%Hello World! 66%Hello World! 67%Hello World! 68%Hello World! 69%Hello Worl
d! 70%Hello World! 71%Hello World! 72%Hello World! 73%Hello World! 74%Hello Worl
d! 75%Hello World! 76%Hello World! 77%Hello World! 78%Hello World! 79%Hello Worl
d! 80%Hello World! 81%Hello World! 82%Hello World! 83%Hello World! 84%Hello Worl
d! 85%Hello World! 86%Hello World! 87%Hello World! 88%Hello World! 89%Hello Worl
d! 90%Hello World! 91%Hello World! 92%Hello World! 93%Hello World! 94%Hello Worl
d! 95%Hello World! 96%Hello World! 97%Hello World! 98%Hello World! 99%
Without carriage return in 19 ms
Hello World! 99%
With carriage return in 19 ms
```

Note the time with carriage return on Linux being an order of magnitude _slower_ than both macOS and Windows.

Both Linux and macOS are running in bash shells. Windows was in a CMD prompt.

Environments:
macOS:
mark-mba:tmp mark$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Windows:
C:\Users\mark\AppData\Local\Temp\test>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Linux:
mark@ubuntu:/tmp/test$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Does anyone have an idea of why Linux is so slow?

_Copied from original issue: dotnet/coreclr#19871_

**Comment by jkotas** [comment] 2018-09-08 00:10
_From @janvorli on September 7, 2018 23:57_

@markfinal were you running it from a GUI based terminal? I've tried to run it on my Ubuntu 16.04 via SSH and got this result:
```
Without carriage return in 3 ms
Hello World! 99%
With carriage return in 182 ms
```
If you were running it from the GUI, I think the slowness might be caused by the terminal itself.

**Comment by markfinal** [comment] 2018-09-08 06:29
@jkotas I was indeed running it from X.

Switching to a non-X TTY, and re-running gives me this:

```
Without carriage return in 9ms
Hello World! 99%
With carriage return in 16ms
```

So yes, your suspicion that it's the terminal looks to be correct.

Since the original app I saw this slowdown in was recently ported from .NET framework to .NET core, and I hadn't seen this issue in .NETframework, I have converted my test case to .NET framework under mono. This is what I get while in the same X terminal:

```
mark@ubuntu:~/Projects/testframe/testframe$ mono ./bin/Release/testframe.exe 
Hello World! 0%Hello World! 1%Hello World! 2%Hello World! 3%Hello World! 4%Hello World! 5%Hello World! 6%Hello World! 7%Hello World! 8%Hello World! 9%Hello World! 10%Hello World! 11%Hello World! 12%Hello World! 13%Hello World! 14%Hello World! 15%Hello World! 16%Hello World! 17%Hello World! 18%Hello World! 19%Hello World! 20%Hello World! 21%Hello World! 22%Hello World! 23%Hello World! 24%Hello World! 25%Hello World! 26%Hello World! 27%Hello World! 28%Hello World! 29%Hello World! 30%Hello World! 31%Hello World! 32%Hello World! 33%Hello World! 34%Hello World! 35%Hello World! 36%Hello World! 37%Hello World! 38%Hello World! 39%Hello World! 40%Hello World! 41%Hello World! 42%Hello World! 43%Hello World! 44%Hello World! 45%Hello World! 46%Hello World! 47%Hello World! 48%Hello World! 49%Hello World! 50%Hello World! 51%Hello World! 52%Hello World! 53%Hello World! 54%Hello World! 55%Hello World! 56%Hello World! 57%Hello World! 58%Hello World! 59%Hello World! 60%Hello World! 61%Hello World! 62%Hello World! 63%Hello World! 64%Hello World! 65%Hello World! 66%Hello World! 67%Hello World! 68%Hello World! 69%Hello World! 70%Hello World! 71%Hello World! 72%Hello World! 73%Hello World! 74%Hello World! 75%Hello World! 76%Hello World! 77%Hello World! 78%Hello World! 79%Hello World! 80%Hello World! 81%Hello World! 82%Hello World! 83%Hello World! 84%Hello World! 85%Hello World! 86%Hello World! 87%Hello World! 88%Hello World! 89%Hello World! 90%Hello World! 91%Hello World! 92%Hello World! 93%Hello World! 94%Hello World! 95%Hello World! 96%Hello World! 97%Hello World! 98%Hello World! 99%
Without carriage return in 14 ms
Hello World! 99%
With carriage return in 46 ms
```

This was built using

`msbuild /property:Configuration=Release`

and I've zipped up the project I created using MonoDevelop (identical source code though)
[testframe.zip](https://github.com/dotnet/corefx/files/2363086/testframe.zip)

So although I agree there is a different of behaviour between an X terminal and a TTY terminal, there is also a difference just in an X terminal between .NET framework and .NET core.

**Comment by argentini** [comment] 2018-09-13 20:45
I see this in bash on Ubuntu 18. I wrote a threaded output class, and need to reposition the cursor as multiple threads update their lines of output. Linux is painfully slow. macOS is a bit slower than Windows, but decent. I haven't determined if linefeeds and cursor movement cause it, or just cursor movement.

On a related note, the fact that Windows returns cursor top positions relative to the line buffer (absolute) and others return top positions relative to the screen height, is a real pain too :)

**Comment by argentini** [comment] 2018-09-13 20:58
Confirmed: my class being used in a TTY terminal is lightning fast.

**Comment by markfinal** [comment] 2018-09-14 06:36
@argentini Is your code compatible with Mono & .NET framework on Linux? If so, do you still see slow performance with cursor movement when executed in X terminals?

Although I do feel Mono and .NET core are different takes on a common set of APIs, I can't help but think this feels like a regression for Linux support.

Console output isn't usually high on my performance agenda, but when trying to give visual progress feedback on a terminal to users is causing substantial performance issues, I felt something needed to be said.

**Comment by argentini** [comment] 2018-09-14 19:28
I don't know (or think) it would be compatible with Mono for Linux.

**Comment by sangkilc** [comment] 2019-02-15 03:30
I have exactly the same problem in Ubuntu 18.04 terminals. I can confirm that Mono doesn't have any issue. I am currently using dotnet core version `2.2.104`, and mono `4.6.2`.

**Comment by sangkilc** [comment] 2019-02-15 03:48
It seems that dotnet core produces unnecessarily many system calls. I created a simple script in fsharp:
```fsharp
open System

let rec move () =
  Console.SetCursorPosition (Console.CursorLeft - 1, Console.CursorTop)
  if Console.CursorLeft = 0 then () else move ()

let str = "ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD"
Console.Write(str)
#time
move ()
Console.WriteLine ()
#time
```

And here are the results (Note almost 0 CPU time):
```
$ dotnet /usr/share/dotnet/sdk/2.2.104/FSharp/fsi.exe test.fsx 
ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD
Real: 00:00:05.511, CPU: 00:00:00.020, GC gen0: 0, gen1: 0, gen2: 0

$ fsharpi test.fsx 
ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD
Real: 00:00:00.000, CPU: 00:00:00.001, GC gen0: 0, gen1: 0
```

I also ran `strace` with both Mono and .NET core. and observed 10x more system calls from .NET core. For example:
```
$ grep -c ioctl dotnet.strace mono.strace 
dotnet.strace:1264
mono.strace:20

$ grep -c lstat dotnet.strace mono.strace 
dotnet.strace:2132
mono.strace:287
```

Hope this helps!

**Comment by janvorli** [comment] 2019-02-18 14:17
cc: @stephentoub - the number of times we call `ioctl` is huge w.r.t. the fact that the code just moves the cursor left 60 times.
Running it locally and extracting more details on which `ioctl`s we run:
* 904 `TCGETS`
* 360 `TCSETS`

I've experimented with modifying the code to get even more details:
* After removing the call to `move()` between the `Console.Write` and `Console.WriteLine` calls, there are 4 calls to `TCGETS` and none to `TCSETS`.
* With the move modified to perform the move just once (removing the `else` part), there were 19 calls to `TCGETS` and 6 calls to `TCSETS`. 

That means that per single move, there are 15 `TCGETS` syscalls and 6 `TCSETS` ones. The `ioctls` are used to read the position, setting the position is just a write of a ncurses control string to stdout. Since there are three reads of current position (`Console.CursorLeft`, `Console.CursorTop`, `Console.CursorLeft`) in the code per single move, it means we do 5 calls to `TCGETS` and 2 calls to `TCSETS` per each cursor position read.

The calls to `TCSETS` happen from `SystemNative_InitializeConsoleBeforeRead`.

I'm not familiar with the console handling code and so I am not sure if we can reduce the number of syscalls in any way or not.

**Comment by stephentoub** [comment] 2019-02-22 16:38
> After removing the call to move() between the Console.Write and Console.WriteLine calls, there are 4 calls to TCGETS and none to TCSETS.

Are you sure those TCGETS are coming from this code?  I don't see anything on our Console.Write paths that would cause a TCGET.

> The calls to `TCSETS` happen from SystemNative_InitializeConsoleBeforeRead.

Presumably so do the `TCGETS`?
https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/Native/Unix/System.Native/pal_console.c#L124
I'd have expected those to be all of the `TCGETS`, and then to see `TCSETS` coming from:
https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/Native/Unix/System.Native/pal_console.c#L140
and
https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/Native/Unix/System.Native/pal_console.c#L156
So, 2 calls to `TCSETS` makes sense to me (one for setup, one for cleanup).  I'd expect 1 `TCGET` here in addition.  So if those 4 other `TCGETS` were coming from something else, such as the terminal validating state before and after executing the program, or something to do with the `dotnet` host, or some such thing, then the numbers make sense to me, 2 `TCSETS` and 1 `TCGET` per call to either CursorLeft or CursorTop.

> it means we do 5 calls to `TCGETS` and 2 calls to `TCSETS` per each cursor position read

Part of the problem is we don't expose a way to get both the "Left" and "Top" at the same time; exposing that would cut the number in half.  That's covered by:
https://github.com/dotnet/corefx/issues/34885
cc: @wtgodbe 

> so I am not sure if we can reduce the number of syscalls in any way or not.

Assuming I'm right about the 2+1 above, I'm not sure there's much we can do unless we rearchitect how we handle all of this.  There are two related pieces here that come up not infrequently:
1. How we handle echo / tty settings
2. How we handle getting the current cursor position

For (1):
https://github.com/dotnet/corefx/issues/34501
https://github.com/dotnet/corefx/issues/25916#issuecomment-376689779
https://github.com/dotnet/corefx/issues/30610#issuecomment-399522462
https://github.com/dotnet/corefx/issues/16352#issuecomment-281431102

For (2):
https://github.com/dotnet/corefx/issues/31517

> I can confirm that Mono doesn't have any issue.

Mono tries to cache the current cursor position, such that CursorLeft and CursorTop hand back the cached value.  That can lead to problems though if anything that's not being monitored invalidates the cached notion of where it currently is.  For example, it doesn't monitor terminal scrolling / resizing with regards to cursor position, so try a program like this:
```C#
using System;
using System.Threading;

class Program
{
    public static void Main()
    {
        while (true)
        {
            Thread.Sleep(1000);
            Console.WriteLine(Console.CursorLeft + ", " + Console.CursorTop);
        }
    }
}
```
let it output a few lines, and then shrink the window by pushing up the bottom of the terminal such that the terminal is only a few lines tall.  It'll continue to still say the position is what it was, because it's pulling it from its cache that wasn't invalidated.

That's not casting aspersions at Mono, just highlighting that there are difficulties here.  Of course has been pointed out, Mono's implementation of CursorTop/Left is really fast when compared to the current implementation in corefx, so it may very well be the case that we should pursue this route instead.  It comes up enough.  We just need to do real due diligence in making sure that we are aggressive about invalidating the cache when anything that could impact it happens; we should be able to do that, though, we just need a lot of eyes on it to make sure nothing slips through the gaps.

**Comment by stephentoub** [comment] 2019-02-22 16:43
@tmds, I know you expressed interest before in the whole echo problem.  Any interest in trying to tackle both that and the cursor position caching stuff?  It comes up frequently enough that it really seems like it's causing pain we should try to fix.

**Comment by janvorli** [comment] 2019-02-22 18:10
> Are you sure those TCGETS are coming from this code? I don't see anything on our Console.Write paths that would cause a TCGET.

Those 4 TCGETS - two are coming from calls to SystemNative_IsATty, one from SystemNative_InitializeConsole and one from SystemNative_GetControlCharacters.

**Comment by stephentoub** [comment] 2019-02-22 18:19
> Those 4 TCGETS - two are coming from calls to SystemNative_IsATty, one from SystemNative_InitializeConsole and one from SystemNative_GetControlCharacters.

And the ones for IsATty and GetControlCharacters are happening on every Console.WriteLine()?  GetControlCharacters should only be called once for the whole process:
https://github.com/dotnet/corefx/blob/c7a4807728206d959e1878242c0bd6d35948fc2d/src/System.Console/src/System/ConsolePal.Unix.cs#L840
and unless the app itself is calling Is*Redirected, I'd expect IsATTy to show up at most three times for the whole process, because the consuming calls are cached, e.g.
https://github.com/dotnet/corefx/blob/c7a4807728206d959e1878242c0bd6d35948fc2d/src/System.Console/src/System/Console.cs#L144
and GetCursorPosition uses that cached version:
https://github.com/dotnet/corefx/blob/c7a4807728206d959e1878242c0bd6d35948fc2d/src/System.Console/src/System/ConsolePal.Unix.cs#L354

**Comment by janvorli** [comment] 2019-02-22 18:23
I am sorry, I was probably not clear. I meant those 4 calls are per process run, no matter how many console.WriteLine calls are in there (even when there are no calls to those, there are 4 TCGETS calls)

**Comment by stephentoub** [comment] 2019-02-22 18:24
> I meant those 4 calls are per process run, no matter how many console.WriteLine calls are in there (even when there are no calls to those, there are 4 TCGETS calls)

Aha!  Yes, that's true.  The world makes sense again :)  I'm also not particularly concerned about those 4 syscalls for the whole process.  It would be nice to eliminate the 2+1 on every Console.CursorLeft/Top, but that goes back to my previous comment: https://github.com/dotnet/corefx/issues/32174#issuecomment-466460581.

**Comment by janvorli** [comment] 2019-02-22 19:10
I have tried to figure out the exact callers of the 5 TCGETS and 2 TCSETS in a single Console.CursorLeft. Here they are:
* TCGETS from SystemNative_InitializeConsoleBeforeRead
* TCGETS from SystemNative_InitializeConsoleBeforeRead
* TCSETS from SystemNative_InitializeConsoleBeforeRead
* TCGETS from SystemNative_InitializeConsoleBeforeRead
* TCGETS from SystemNative_UninitializeConsoleAfterRead
* TCSETS from SystemNative_UninitializeConsoleAfterRead
* TCGETS from SystemNative_UninitializeConsoleAfterRead

**Comment by tmds** [comment] 2019-02-22 19:25
> @tmds, I know you expressed interest before in the whole echo problem. Any interest in trying to tackle both that and the cursor position caching stuff? It comes up frequently enough that it really seems like it's causing pain we should try to fix.

Currently the echoing is turned off and back on, to allow interactive applications (e.g. `Process.Start("nano")`) to have echo on. In https://github.com/dotnet/corefx/issues/25916#issuecomment-432401198 I suggested we can turn off echo by default, and turn it on when we have (possibly) interactive child processes.

I can take a shot at implementing that. I'll also look at the cursor position issue.

**Comment by stephentoub** [comment] 2019-02-22 20:37
> Here they are

Well now I'm confused again.  I'll need to look into why that's happening.

> I suggested we can turn off echo by default, and turn it on when we have (possibly) interactive child processes. I can take a shot at implementing that. 

Thanks, @tmds.  That sounds like a reasonable approach to try.  It's a little concerning that we'd be tying the console implementation to the process implementation, but I guess that ship has already sailed, in particular around signal handlers.

> I'll also look at the cursor position issue.

Thanks!  Caching the position is easy, of course.  I think the harder part is understanding all the things that should invalidate the cache and force us to get it again.  Some things like typing we should reasonably be able to update the cache ourselves, guessing at the moves.  Other things like window resizing we probably need to either listen for the appropriate signal.  I'm not sure what we need to do with regards to child processes potentially updating the cursor position, but maybe there's something reasonable we can do any time the app regains terminal control.  Etc.

**Comment by janvorli** [comment] 2019-02-22 21:53
> Well now I'm confused again.

I have looked at the strace log with stack calls more carefully. I think it will remove the confusion:

* SystemNative_InitializeConsoleBeforeRead calls tcgetattr function
  * TCGETS ioctl syscall
* SystemNative_InitializeConsoleBeforeRead calls tcsetattr function
  * TCGETS ioctl syscall
  * TCSETS ioctl syscall
  * TCGETS ioctl syscall
* SystemNative_UninitializeConsoleAfterRead calls tcsetattr function
  * TCGETS ioctl syscall
  * TCSETS ioctl syscall
  * TCGETS ioctl syscall

**Comment by stephentoub** [comment] 2019-02-23 00:37
Ah, so a single call to tcsetattr makes 3 syscalls.

**Comment by stephentoub** [comment] 2019-03-11 17:23
Optimistically moving this back to 3.0 for now, as @tmds said he'd take a look.  Might need to bump it back out to Future.

**Closed** 2019-03-22 02:49 UTC
Labels: area-System.Console, bug
