### ISSUE TITLE
Support writing C# object into Utf8JsonWriter

### ISSUE THREAD

**Issue by skatpgusskat** [dotnet/corefx#38806] opened 2019-06-24 08:56 UTC
## Problem Senario

It's impossible to make Json Array using Utf8JsonWriter which contains multiple objects.

``` C#
using (var writer = new Utf8JsonWriter(stream, options))
{
    writer.WriteStartArray();
    writer.WriteStringValue(DateTimeOffset.UtcNow); // OK.
    writer.WriteNumberValue(42); // OK.

    writer.WriteValue(myObject); // NO
    writer.WriteValue(myObject2, myObjectType); // NO

    writer.WriteEndArray();
}
```

## What I found

`JsonSerializer` has APIs which work with Utf8JsonReader,
```C#
public static object ReadValue(ref System.Text.Json.Utf8JsonReader reader, System.Type returnType, System.Text.Json.JsonSerializerOptions options = null);
public static TValue ReadValue<TValue>(ref System.Text.Json.Utf8JsonReader reader, System.Text.Json.JsonSerializerOptions options = null);
```

So we can read specific type's C# object from Utf8JsonReader.

## What I want to suggest

I suggest new API at JsonSerializer which write object into Utf8JsonWriter.

```C#
public static void WriteValue(ref System.Text.Json.Utf8JsonWriter writer, object value, System.Type type, System.Text.Json.JsonSerializerOptions options = null);
public static void WriteValue<TValue>(ref System.Text.Json.Utf8JsonWriter writer, TValue value, System.Text.Json.JsonSerializerOptions options = null);
```

So we can write object into Utf8JsonWriter like below,

``` C#
using (var writer = new Utf8JsonWriter(stream, options))
{
    writer.WriteStartArray();
    writer.WriteStringValue(DateTimeOffset.UtcNow); // OK.
    writer.WriteNumberValue(42); // OK.

    JsonSerializer.WriteValue(ref writer, myObject); // <<
    JsonSerializer.WriteValue(ref writer, myObject2, myObjectType); // <<

    writer.WriteEndArray();
}
```

If there is another way to write object into Utf8JsonWriter, Please let me know.

**Comment by khellang** [comment] 2019-06-24 11:48
Duplicate of #ToUpperConversion

**Comment by ahsonkhan** [comment] 2019-06-24 17:08
Yep. Closing.

**Closed by ahsonkhan** 2019-06-24 17:08 UTC
Labels: area-System.Text.Json
