### ISSUE TITLE
Need a way to configure the project in corefx to work with CLI

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#19930] opened 2017-05-18 17:38 UTC
Currently, the project in corefx cannot be executed using CLI command. Need a way to support it.
e.g.
https://github.com/dotnet/corefx/blob/master/src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.csproj

Refer the issue https://github.com/dotnet/cli/issues/6612

@mellinoe

**Comment by mellinoe** [comment] 2017-05-18 17:47
Could you provide more information about this project? We do build some executable projects here in corefx, but they are generally used for testing purposes only, so they run on the "test shared framework". Is this project something that is going to be bundled into a tool somewhere for custom projects to use? Or is it another thing that is going to just be used in tests?

**Comment by huanwu** [comment] 2017-05-18 17:50
@mellinoe yes, this is a tool used to generate the serializer code. It is not test project. e.g. I am supposed to run the command:
dotnet Microsoft.XmlSerializer.Generator.dll data.dll
It will generate a code file data.XmlSerializers.cs

**Comment by mellinoe** [comment] 2017-05-18 17:54
I see; interesting. How will customers get ahold of this DLL? Will they need to download a nuget package and then pass the path inside of that? Or will there be custom MSBuild targets involved?

To make it an executable project, make sure you include <OutputType>Exe</OutputType> in the project. You will also likely want to retarget it to `netcoreapp2.0` rather than `netstandard` given that it is an executable project, not a library. You mentioned doing that in the other issue and hit issues; it looks like you  might have been missing some dependencies when you ran, or you used the wrong runtime version.

**Comment by huanwu** [comment] 2017-05-18 19:07
@mellinoe yeah, good question. The customer will download a nuget package for it. And we might involve the MSBuild target. That's the user experience we will work on. 

And we know it will work if target to netcoreapp2.0. But we need this tool target at netstandard. Can we have the CLI support in our case? Thanks!

**Comment by mellinoe** [comment] 2017-05-18 19:17
The CLI doesn't really support building or running .NET Standard executables If you want to target .NET Standard and involve an MSBuild target, you might be better off creating a portable MSBuild task, rather than creating an executable. If this is something that you intend to be hooked into the SDK targets, perhaps you can just include the basic logic in a nuget package here, and then hook an MSBuild task and targets up in the SDK repo?

**Comment by huanwu** [comment] 2017-05-18 21:35
@shmao @zhenlan

**Comment by huanwu** [comment] 2017-05-19 23:38
@mellinoe I now let my app target at NetCoreApp. The change is as the following
https://github.com/huanwu/corefx/commit/0ca8fbfb74be3168b169a981f54e03ad0a014ba9
 Build success. But I got the following error when execute the app.
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()

```

**Comment by huanwu** [comment] 2017-05-24 18:11
@mellinoe do you have idea on above errors I got when target my app at NetCoreApp?

**Comment by mellinoe** [comment] 2017-05-24 18:16
I'll check out your branch and see if I can figure out what is missing.

**Comment by mellinoe** [comment] 2017-05-24 18:52
@huanwu The problem is that corefx doesn't really support publishing "shared framework" applications -- it will produce the binary (Microsoft.XmlSerializer.Generator.exe) that you need, but not the other stuff to make a shared framework application work. When I copied the runtime next to the executable, it worked as expected (and I was able to get it to spit out a .cs file for some assembly).

Generally speaking, we don't need or want to build any shared framework applications here in corefx; it's a little bit outside of the scope of the repo, because it relies on the SDK, which we don't really use. I think we should understand some of the questions I raised above (e.g. how this tool will be acquired and used) before we figure out whether we need to add support for building a whole new kind of project in corefx.

**Comment by huanwu** [comment] 2017-05-26 18:18
@mellinoe  For the tool usage, we expect the customer will download it from the nuget package and then use dotnet CLI to run the tool and get the code file. The customer can compile a serializer assembly with this code file.  In the future milestone, we will consider if to provide a compiled assembly to customer directly when run this tool.

**Comment by huanwu** [comment] 2017-05-31 20:16
@mellinoe do you have idea how to make our scenario work?

**Comment by mellinoe** [comment] 2017-05-31 20:34
@huanwu This is a pretty interesting case. I think we need to try to identify all of the different pieces involved here, because I don't think I have all the context to point you in the right direction yet. I'm not familiar enough with CLI tools to say what needs to go into them, although I have a vague understanding. I believe you are going to need a complete "shared framework application" to be placed in the nuget package. Like I mentioned above, we don't currently have the capability to produce such things in this repository; partially because we just haven't done the work (never needed it), and partially because it is the wrong place in the stack to do such things. That said, support could potentially be added if it makes sense and can be done cleanly.

@eerhardt @livarcocc  Could you guys help remind me what needs to be in a "CLI tool" package, e.g. which assets are needed and in which structure? At the very least, we do need a .exe file and a .deps.json file, correct?

cc @weshaggard @ericstj

**Comment by eerhardt** [comment] 2017-05-31 22:01
There's a few levels of information to wade through here.

1. If you just want the dotnet host to run an executable, you need 3 things:
 a. An IL assembly with a Main method
 b. A .deps.json file that lists the dependent assemblies
 c. A runtimeconfig.json file that points to the version of the shared framework to use.  If one doesn't exist, the dotnet host expects the runtime to be in the same directory - i.e. why you get the error `A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found`.
2. If you want to make your program a "CLI Tool" which is an extension to the CLI that can be added through `DotNetCliToolReference` in a .csproj, you just need the `1.a.` and `1.c` above and then you package it into a .nupkg with your dependencies listed in the .nuspec.  The CLI will generate `1.b` when the tool is restored/invoked.
3. All that being said, a real question is: Have we considered making this an MSBuild Task instead?  CLI tools were the choice way to customize your build in `project.json` based projects.  But now that everything is MSBuild based, using MSBuild Tasks and Targets is the preferred way to extend/customize a build.  You can still deliver the assets in a NuGet package.  A difference is that a user would invoke the target using `dotnet msbuild /t:YourName` instead of `dotnet YourName`.  But that is easily fixed by creating a thin wrapper DotNetCliToolReference app that just invokes `dotnet msbuild /t:YourName` under the covers.

Here's some of our docs on extending the CLI: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility.  Arguably, they could be better.

**Comment by huanwu** [comment] 2017-06-07 01:30
@eerhardt I tried the first way. I added .deps.json and runtimeconfig.json as https://github.com/huanwu/corefx/commit/a8e993d09804b791a084bfcc626b8c81f4e746c8

When I run dotnet Microsoft.XmlSerializer.Generator.dll, it gives me the following error:
Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Microsoft.XmlSerializer.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Do you know what's wrong of it?  It works for the assembly built from VS2017.

**Comment by eerhardt** [comment] 2017-06-07 19:21
Where's ConsoleApp2 coming from?

https://github.com/huanwu/corefx/blob/a8e993d09804b791a084bfcc626b8c81f4e746c8/src/Microsoft.XmlSerializer.Generator/src/Microsoft.XmlSerializer.Generator.deps.json#L8-L10

**Comment by huanwu** [comment] 2017-06-08 23:52
@eerhardt That's my mistake. I already corrected here https://github.com/huanwu/corefx/commit/6d60213e56c62ca7037902042b73822940d12380
But it still won't work. And actually I will expect it would auto generate these two files when build the project. And I need include the dll and two json files into the nuget package.

**Comment by shmao** [comment] 2017-09-28 18:39
We discussed this with Eric offline and found a solution for the issue. Closing this.

**Closed by shmao** 2017-09-28 18:39 UTC
Labels: area-Infrastructure
