### ISSUE TITLE
System.Collections.Immutable and System.Reflection.Metadata cause some dependency weirdness

### ISSUE THREAD

**Issue by tuespetre** [dotnet/corefx#10949] opened 2016-08-18 04:45 UTC
I have a library targeting `netstandard1.5` which brings in these two libraries as dependencies (directly or indirectly, doesn't seem to make a difference.) When I reference this library from another project targeting `net462`, I can see in the Visual Studio dependency tree that several references sort of 'drop out' of 'package dependency' mode and into 'framework assembly' mode:

- System.Runtime (4.1.0, drops to 4.0.20)
- System.Runtime.Extensions (4.1.0, drops to 4.0.10)
- System.Reflection (4.1.0, drops to 4.0.10)

Now, there is another somewhat similar issue with the current 4.1.0 package for System.Net.Http, where it drops to 4.0.0 and causes problems, but I have been able to work around that by locking the project.json file and deleting the portion that specifies it as a framework assembly. I see no such analog for these other libraries and I can't find anything of note in their .nuspec files. Changing the test library to target as low as `netstandard1.1` yields no desirable effect.

Although I would prefer not to mention this sort of thing, a current project I am working on is blocked by this because at runtime it is causing a failure to load the System.Runtime library. I mention this because I want to be clear that it is not a nitpicking issue but rather an actual impediment. Please let me know what else I can do to help.

**Comment by tuespetre** [comment] 2016-08-18 05:39
Here's a really easy example you can try:

- Create a class library project that targets `netstandard1.5`
- Add `System.Reflection.Metadata` version `1.3.0` as a dependency
- In a simple class, write a static method that contains `throw new NotSupportedException();`
- Create a console application project that targets `net462`
- Add the class library as a dependency
- In the `static void Main`, call the static method you just wrote in the class library
- Run the program
- Observe an exception complaining about `System.Runtime` version `4.1.0`
- Change the dependency in the class library project from `System.Reflection.Metadata` to `System.Runtime` version `4.1.0`
- Run the program
- Observe the appropriate behavior -- a `NotSupportedException` is thrown

**Comment by tuespetre** [comment] 2016-08-18 13:37
FWIW I was able to add a net462 target to the class library for the project I'm working on and now things are moving again, but I feel this highlights a flaw with the implementation of the .NET Standard, or at least the targeting. Perhaps the steps I've outlined above to reproduce the issue could be used to create some kind of test harness that validates the compatibility of different TFMs with the netstandard TFMs. If that sounds like a good idea I would be more than glad to contribute something.

**Comment by tmat** [comment] 2016-08-18 17:16
@ericstj Could you take a look?

**Comment by ericstj** [comment] 2016-08-18 17:20
I believe the problem is here:
>Create a console application project that targets net462
Add the class library as a dependency

When you did this are both projects using project.json?

If not, did you make sure to install all the same nuget packages in the console application as you did in the class library?

Not flowing transitive dependencies was one of the main things that was fixed with nuget v3 + project.json.  It sounds to me like you're hitting that issue here.

**Comment by tuespetre** [comment] 2016-08-18 18:18
@ericstj:

Both projects are `project.json`/`*.xproj`, and this occurs even when the console application declares specific dependencies on the 4.1.0 packages.

**Comment by ericstj** [comment] 2016-08-18 18:30
Sounds to me like XProj is either missing bindingRedirect generation and or breaking with how it decides to replace packages with framework assemblies.  /cc @davidfowl @piotrpMSFT 

In that case this issue likely belongs in the dotnet/CLI repo.

**Comment by ericstj** [comment] 2016-08-18 20:18
Indeed, I just did a mockup of your sample using just CSProj + project.json and things worked for me.  I believe the bug here is in how XProj targets the desktop framework.

**Comment by piotrpMSFT** [comment] 2016-08-18 20:52
does this repro using project.json only via the CLI? Knowing this would help isolate the problem. A bunch of extra machinery gets involved with VS+msbuild in the picture...

**Comment by ericstj** [comment] 2016-08-18 21:04
I can confirm a repro with pure CLI and project.json.  CLI is both not writing the binding redirects in the app.config and is ignoring the dll in the project.lock.json.

MSBuild-based desktop CSProj does the right thing on both counts.

**Comment by piotrpMSFT** [comment] 2016-08-18 21:08
@Sridhar-MS who implemented binding redirects for CLI. We should move this issue to CLI repo as it's clearly not a corefx issue. @tuespetre I have a question for you: given the [changes](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) coming to the CLI's build system, the code path affected by this issue is not one we want to invest in too heavily at the moment. I think you said above that you are unblocked for your immediate needs. Is your workaround sufficient as-is, or are you still blocked?

**Comment by tuespetre** [comment] 2016-08-18 21:11
@piotrpMSFT the workaround is good enough for us for the time being. Thanks for asking! Sounds like this should be taken care of with the cut over to MSBuild then?

**Comment by Sridhar-MS** [comment] 2016-08-18 21:12
@ericstj Can you share your sample project.json which repros the issue?

**Comment by ericstj** [comment] 2016-08-18 21:12
Oddly enough if I remove the reflection.metadata dependency (that isn't even being used) it does indeed cause the issue to go away.  BindingRedirects are generated and the correct files are copied.  @Sridhar-MS I'll send it to you offline.

**Comment by piotrpMSFT** [comment] 2016-08-18 21:42
@tuespetre thanks for confirming. We won't make any changes to the project.json CLI then, but @Sridhar-MS will look into the issue enough to see if there is concern we need to track in csproj. The binding redirects capabilities of csproj are much more mature, so I do expect this to be much less likely in that context.

**Comment by ericstj** [comment] 2016-08-18 22:08
Closing this.  Feel free to use the issue to report any findings or open one in CLI if you intend to make any changes.

**Closed by ericstj** 2016-08-18 22:08 UTC
Labels: System.Reflection.Metadata
