### ISSUE TITLE
Performance tests do not run under netfx targetgroup

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#31805] opened 2018-08-16 18:07 UTC
Seems like we don't support running perf tests in netfx.

For example when running:
```
msbuild src\System.IO.Compression\tests\Performance\ /t:rebuildandtest /p:ConfigurationGroup=Release /p:TargetOs=Windows_NT /p:Performance=true /p:targetgroup=netfx
```
it just ends up running with default targetgroup (being netcoreapp)

Although there are other ways (e.g. using BenchmarkDotnet) to do performance testing in netfx, it could still be useful to enable this in cases when we want to compare netfx vs netcoreapp performances with each other for the existing perf tests written in corefx.

**Note:** When trying to test the above script I believe you need to add netfx value in the configuration.props file [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/tests/Performance/Configurations.props).

cc: @danmosemsft @safern

**Comment by ViktorHofer** [comment] 2018-08-18 20:45
Duplicate of https://github.com/dotnet/corefx/issues/19200

**Closed by ViktorHofer** 2018-08-18 20:45 UTC
Labels: area-Infrastructure
