### ISSUE TITLE
Registered i/o

### ISSUE THREAD

**Issue by unicomp21** [dotnet/corefx#24861] opened 2017-10-25 10:21 UTC
We need interop delarations for RIO in the corefx repo

**Comment by danmosemsft** [comment] 2017-10-25 14:06
Can you clarify? What definitions and for what purpose?

**Comment by karelz** [comment] 2017-10-25 17:39
Check out https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines.Networking.Windows.RIO

Duplicate of #721

**Closed by karelz** 2017-10-25 17:39 UTC
