### ISSUE TITLE
HttpClient Error "An internal response size limit was exceeded"

### ISSUE THREAD

**Issue by zenixgrace** [dotnet/corefx#18000] opened 2017-04-06 09:18 UTC
Hello,

I got an error "An internal response size limit was exceeded" when calling SendAsync method in HttpClient
Is it about buffer size or what?
try to set MaxResponseContentBufferSize but no luck.

**Comment by stephentoub** [comment] 2017-04-06 10:15
On what OS? On what version of .NET Core? Can you share a small repro?

**Comment by zenixgrace** [comment] 2017-04-06 11:02
Hello,

After playing with this error, I found the  cause of error.
If I set the auto redirect to false, the error is gone. Otherwise the error show up..
Is it have a limitation when the page that we call return the redirect action to another page?

I'm on 1.1.1 Net Core and Window OS.

**Comment by davidsh** [comment] 2017-04-06 14:09
Please attach a full repro solution using Visual Studio 2015 or 2017. It is the only way we will be able to troubleshoot this.  Thx.

**Comment by karelz** [comment] 2017-04-12 17:09
@zenixgrace will you be able to provide us a repro?
Otherwise I fear the problem will not be actionable for us. Thanks!

**Comment by zenixgrace** [comment] 2017-04-13 00:35
@karelz I get some issue when make a sample simple project to show the error. The site that I crawl is airline b2b system that use username and password to sign in the system. I tried to make it offline by save the html page and connect it via localhost. But if I do that way, I get no problem. Everything is OK (no error "An internal response size limit was exceeded")

[sample_html.txt](https://github.com/dotnet/corefx/files/918214/sample_html.txt)

Note :
Change the .txt extension to .zipb (because i'm not able to upload the zip file)

**Comment by karelz** [comment] 2017-04-13 16:32
Moving to Future milestone as we are blocked on missing repro.

BTW: My experience over years with complicated repros is: Either it is sign of something fishy in the application (app code bug), or it is sign of a very corner case bug in Runtime/BCL (which sometimes can be pretty nasty and impactful for apps that hit it).
Either way, it is usually not cost-efficient for us to go after it. It is typically easier to wait for another report of the same problem (i.e. lower chance it is app code bug), or to wait for smaller-ish repro from the person who reported it.
It is extremely inefficient to just guess around from bits and pieces of information (it's like guessing root-cause of perf issues from just its symptoms, without looking at code at all). However, it is typically useful to discuss various kinds of logging that can be used to narrow down the problem.
... anyway, that's just my experience from investigations of hard Runtime bugs over last ~12 years, maybe this is an exception ;)

**Comment by davidsh** [comment] 2017-04-25 00:59
@zenixgrace I looked at the attached html files from the "sample_html.zip" file.  I don't see anything in there that is wrong.

If you can't attach a full repro Visual Studio solution, can you send us a Fiddler trace?  That would be helpful.  Thx.

**Comment by zenixgrace** [comment] 2017-04-25 09:55
Hello @davidsh , I attach the fiddler trace file.
Is it true, this trace file you need?

![untitled](https://cloud.githubusercontent.com/assets/17761222/25379541/8669126e-29d7-11e7-8899-fc9bdb2ef718.jpg)
[45_Request.txt](https://github.com/dotnet/corefx/files/954612/45_Request.txt)
[45_Response.txt](https://github.com/dotnet/corefx/files/954613/45_Response.txt)

**Comment by davidsh** [comment] 2017-04-25 18:31
Thank you for the traces of the request and response.  I assume that these represent the final request/response that was processed just before the error "An internal response size limit was exceeded" was triggered?

What is interesting about this repro is that the HTTP response (a redirection response) has a lot of response body content attached to it.  In most cases a redirection response such as 302 will have very little response body content.

This response:

```
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Location: /LionAirAgentsIBE/OnlineBooking.aspx
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 25 Apr 2017 09:38:33 GMT
Content-Length: 149958

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/LionAirAgentsIBE/OnlineBooking.aspx">here</a>.</h2>
</body></html>

...

```
 
has a lot of HTML code with it. Perhaps having so much response payload in a redirection HTTP response is what is triggering the error condition.

Based on this, we'll see if we can trigger a simpler, standalone, repro case for this.

**Comment by zenixgrace** [comment] 2017-04-26 00:34
hello @davidsh, yes the response have more than 1 body content. For now, I make the auto redirect false, and manually call the redirect page.

**Comment by mmv** [comment] 2017-07-02 18:52
Can confirm that this reproduces with any site that replies with a `301 Moved Permanently` header and a big enough content within that very same reply.

**Comment by davidsh** [comment] 2018-03-22 19:03
It turns out this is caused by a bug in WinHTTP. When a redirect response occurs, WinHTTP prefers to reuse the same connection to follow the redirect. In order to do that, the entire response must be drained.  The number of bytes drained is controlled by the `WinHttpHandler.MaxResponseDrainSize` property:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/ref/System.Net.Http.WinHttpHandler.cs#L37

However, if the response contains more than the MaxResponseDrainSize limit, WinHTTP aborts the request. This is the bug. Instead of aborting the request, it should simply drop the old connection and open up a new connection.

The default value for the `MaxResponseDrainSize` is being set to 64KB by WinHttpHandler.  The repro here in this issue involves a large (300KB+) response body in the redirect response.

It is unlikely that the root bug in WinHTTP will be fixed. And even so, the fix wouldn't apply except to some future Windows OS release.

The workarounds here are to either use WinHttpHandler directly and set the MaxResponseDrainSize property to a large value such as 1,000,000 bytes (this is actually the default for WinHTTP).

The other mitigation is to use .NET Core 2.1 which will use a new HTTP stack (SocketsHttpHandler) by default. This new stack doesn't have this bug.

**Closed** 2018-03-22 19:05 UTC
Labels: area-System.Net.Http, bug, os-windows

**Comment by MatthewLymer** [comment] 2018-05-22 20:43
Do you know if it's required to have the runtime installed on the machine or to build your solution against core 2.1?

Reason I ask is I was able to get SSL's SNI working on Linux by just installing the 2.1 runtime while still targeting netcoreapp2.0, I'm wondering if this is going to be the same for this issue too.

**Comment by davidsh** [comment] 2018-05-22 20:51
You must install .NET Core 2.1.  And your app must target 2.1 as well.  Apps that currently target 2.0 don't "roll forward" to 2.1.  At most, they will use the latest 2.0.x installed (i.e. servicing version).

**Comment by karelz** [comment] 2018-05-22 21:29
Actually technically, 2.0-targetting apps will attempt to run on 2.1.x if 2.0.x is not present on the machine. It is fallback roll-forward feature of the host. It may not work in all cases (e.g. ASP.NET Core apps are not supported in that scenario).
That said, I would recommend to retarget to 2.1 if you can.
