### ISSUE TITLE
System.Runtime.Extensions failures on UAPAOT

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#21680] opened 2017-06-28 22:56 UTC
Currently those tests are disabled and need to be investigated

```
      <test name="System.Tests.AppDomainTests.FirstChanceException_Called" type="System.Tests.AppDomainTests" method="FirstChanceException_Called" time="23.9606987" result="Fail">
      <test name="System.Tests.AppDomainTests.TypeResolve" type="System.Tests.AppDomainTests" method="TypeResolve" time="22.4219193" result="Fail">
      <test name="System.Tests.AppDomainTests.SetData_SameKeyMultipleTimes_ReplacesOldValue" type="System.Tests.AppDomainTests" method="SetData_SameKeyMultipleTimes_ReplacesOldValue" time="22.3727791" result="Fail">
      <test name="System.Tests.AppDomainTests.ResourceResolve" type="System.Tests.AppDomainTests" method="ResourceResolve" time="22.7862551" result="Fail">
      <test name="System.Tests.AppDomainTests.ExecuteAssemblyByName" type="System.Tests.AppDomainTests" method="ExecuteAssemblyByName" time="22.7847328" result="Fail">
```

**Comment by tijoytom** [comment] 2017-06-30 00:02
@AtsushiKan These AppDomain APIs are not supported on UAPAOT right?

**Comment by AtsushiKan** [comment] 2017-06-30 00:37
The TypeResolve and ResourceResolve event handlers: you can set them - by design, we'll never fire them.

ExecuteAssemblyByName doesn't look like an api problem - it looks like an infrastructure problem (the test assembly not being binplaced by the ILC test plumbing.) 

I don't know about the others - @DnlHarvey did the appdomain work.

**Comment by DnlHarvey** [comment] 2017-07-07 19:13
FirstChanceException_Called and SetData_SameKeyMultipleTimes_ReplacesOldValue should be supported on UAPAOT. We probably just never plumbed through FirstChanceException, I'm a little surprised SetData isn't working correctly though.

**Comment by krwq** [comment] 2017-07-07 19:15
@DnlHarvey SetData seems to be by design https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/AppContext.cs#L76 - where should I look at the FirstChanceException fix? I do not much about this code? Would it be easier if you took this bug if you got time?

**Comment by DnlHarvey** [comment] 2017-07-07 19:23
Sorry, I should have said SetData should behave the same on UAPAOT as any other target. The FirstChanceException thing won't be straightforward or intuitive. I'll take the bug.

**Comment by krwq** [comment] 2017-07-07 19:24
@DnlHarvey thank you!

**Comment by joshfree** [comment] 2017-07-10 20:52
@AtsushiKan can you please load balance this bug please?

**Comment by AtsushiKan** [comment] 2017-07-10 22:05
Unless the work can be done entirely in the open-source (Git-controlled) subdirectory (and it doesn't look like it to me from a quick look - exception dispatch occurs inside mrt100_app.dll)), the FirstChanceException part is not efficient for me to load-balance.

**Comment by AtsushiKan** [comment] 2017-07-11 17:01
Made the SetData() fix. @DnlHarvey - it sounds like you already have context on the FirstChanceExceptions event. I don't think it's practical for me to poach this one as it crosses GIT-TFS boundaries.

**Comment by DnlHarvey** [comment] 2017-07-17 20:53
Fixed with https://github.com/dotnet/corefx/pull/22330

**Closed by DnlHarvey** 2017-07-17 20:53 UTC
Labels: area-System.Runtime.Extensions
