### ISSUE TITLE
ClientWebSocket proxy support

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#26144] opened 2018-01-04 00:38 UTC
System.Net.WebSockets.ClientWebSocket 

tracking: 
Allow customers to use a proxy with AMQP+WS and MQTT+WS

**Comment by karelz** [comment] 2018-01-04 00:48
Related to #9503

**Comment by stephentoub** [comment] 2018-01-04 01:25
What is the work here? Isn't this done once those linked issues are fixed?

**Comment by karelz** [comment] 2018-01-04 16:40
We do not have anyone signed up yet. It is 2.1 ask from partner team, so we will cost it and try to schedule it.
The ManagedHandler work is not tracked for 2.1 at this moment (it may change as we're discussing on emails).
Either way, I assume that there will be small amount of work specific to this issue (although majority is the same and reusable), as ManagedWebSocket does not depend directly on ManagedHandler. Is that correct?

**Comment by stephentoub** [comment] 2018-01-04 16:43
> ManagedWebSocket does not depend directly on ManagedHandler

ClientWebSocket DOES depend directly on ManagedHandler.

> we will cost it 

Cost what? Back to my question... what is this tracking that those issues aren't?

**Comment by karelz** [comment] 2018-01-04 16:47
> ClientWebSocket DOES depend directly on ManagedHandler.

OK, that's news to me. I thought it had its own small copy based on info I got in December.
In that case, the work is the same (when the 2 will happen). The ask / scenario / motivation is just different. Given that it is partner ask, there was a desire to track it explicitly.

**Comment by karelz** [comment] 2018-01-12 22:16
Clarification of the ask from @CIPop:
They need `ClientWebSocketOptions.Proxy` to be supported also on Linux/OSX -- it was not supported in 2.0: https://github.com/dotnet/corefx/wiki/ApiCompat#systemnetwebsocketsclient

This was resolved in #24288 (issue #23152) for 2.1. Default proxy detection is not part of the ask.
Closing as duplicate of #23152.

**Closed by karelz** 2018-01-12 22:16 UTC
Labels: area-System.Net, enhancement

**Comment by karelz** [comment] 2018-01-20 18:04
@CIPop - moving discussion from PR to here: https://github.com/dotnet/corefx/pull/26429#issuecomment-359089814

I have marked [2] and [4] as blocking release:
1. SSL proxy tunneling - #23136
2. ~~Support https proxy - #26460~~ (Not supported even by .NET Framework)
3. Default proxy configuration - #23150
4. Basic proxy authentication does not work - #26405

Can you please confirm they are blocking your scenarios and that [3] is not?

**Comment by CIPop** [comment] 2018-01-25 00:37
@karelz /cc @davidsh @stephentoub @Priya91 @tameraw
it appears some of our customers are interested in SSL filtering proxies which means that we should be able to use the proxy configuration to send the traffic to another machine. 
Unfortunately I don't have more details but I believe these work more or less the same as Fiddler (installing a trusted CA on the local machine).

**Comment by karelz** [comment] 2018-01-25 01:03
@CIPop is that related to [3] about? Or is it something else?

**Comment by CIPop** [comment] 2018-01-25 17:29
@karelz That would be related to 1 or 2. We are currently trying to find out more information from our customers but I believe this would be the [Fiddler HTTPS scenario ](https://www.fiddlerbook.com/fiddler/help/httpsdecryption.asp) which, I believe, still works in .Net Framework.

**Comment by karelz** [comment] 2018-01-25 18:00
Thanks, the scenario makes sense. I am still not sure how it affects the plan laid out above. It does not seem to require https proxy support (2). Does it require some additional certificate APIs?

**Comment by CIPop** [comment] 2018-01-26 04:22
@davidsh / @stephentoub may have more insight about this. (We should match NetFX/WinINet/WinHTTP's behavior.)

My current understanding is that it should simply flow the data as it would be towards a HTTP proxy and use the CONNECT verb. (Which means that the https URI checks would need to be removed.) 

The user must import a debug-only Root CA. The proxy (Fiddler) will need to handle dynamic host-name certificate generation and sign these certificates with the debug root.
