### ISSUE TITLE
Enum.TryParse() Is Always Returning True for String Numbers

### ISSUE THREAD

**Issue by rtaylor72** [dotnet/corefx#35697] opened 2019-03-01 16:46 UTC
I am having an issue with Enum.TryParse() always returning true if the string looks like any number. This is causing major issues because there is no way to tell if the string is really a true value in the Enum or not!

**Comment by bartonjs** [comment] 2019-03-01 17:37
`Enum.TryParse` parses the numbers because the ToString value from an enum might produce them.

If you want to know if it's defining the name of a field you could do something like

```C#
// For any given T you could replace both the long and ulong with their underlying type.
if (!long.TryParse(s, out _) && !ulong.TryParse(s, out _) && Enum.TryParse<T>(s, out value))
{
    // This was a named field.  Or a combination of fields if the enum is [Flags]
}
```


Or manually compare against the array from `Enum.GetNames(typeof(T))`.

**Comment by jkotas** [comment] 2019-03-02 05:10
Duplicate of https://github.com/dotnet/corefx/issues/17002

**Closed by jkotas** 2019-03-02 05:10 UTC
Labels: area-System.Runtime, question

**Comment by rtaylor72** [comment] 2019-03-04 14:10
The other issue is closed also.  This was also a code break for me.  This has always thrown an exception in the original framework if any string did not match.  A string is a string, not a number.  Should float.TryParse("pi", out float x) return true based on the logic given?

**Comment by stephentoub** [comment] 2019-03-04 16:36
> This has always thrown an exception in the original framework if any string did not match.

Can you please share an example?
