### ISSUE TITLE
HttpListenerWebSocketTests.SendAsync_SendWholeBuffer_Success hangs in UAP/UAPAOT on Windows 10 Version 1703

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#22164] opened 2017-07-12 19:33 UTC
Tracking further investigation for this hang in Windows 10 Version 1703 but not vNext.
This is most likely related to the Windows vNext enhancements for WebSocket buffer management. 

/cc @Diego-Perez-Botero

**Comment by caesar1995** [comment] 2017-07-12 20:06
This issue is actually dup of #22053.

**Comment by caesar1995** [comment] 2017-07-12 20:08
When `endOfMessage == false`, the expected behavior is hanging on UWP.

@Diego-Perez-Botero @davidsh

**Comment by CIPop** [comment] 2017-07-12 20:08
@caesar1995 this works fine on RS3 but fails on RS2. Any ideas why?

**Comment by caesar1995** [comment] 2017-07-12 20:16
I will test on my RS3 dev box.

**Comment by caesar1995** [comment] 2017-07-12 20:24
I can confirm the test passed on my RS3 dev box.

I think the reason is here: [here](https://github.com/dotnet/corefx/issues/22053#issuecomment-314282854)

> #21102 improved the receive path of partial messages in UWP, but the existing WinRT APIs still lack partial message support in the send path.

**Comment by CIPop** [comment] 2017-07-12 20:38
@caesar1995 in that case, we probably need to do an OS version check similar to what @Diego-Perez-Botero did in the client ws tests.

**Comment by Diego-Perez-Botero** [comment] 2017-07-12 20:45
Caesar is right. This hang doesn't happen in RS3 because of my #21102 fix. If you look at the test case's code, this one is trying to **receive** a partial message (endOfMessage==false) in some _InlineData_ combinations. The receive is carried out using a **ClientWebSocket** object, so that will only work post-#21102 in RS3 machines.

**Comment by Diego-Perez-Botero** [comment] 2017-07-12 20:47
I think that this issue can be closed, and @CIPop's suggestion of adding the OS version check would be appropriate.

**Comment by Diego-Perez-Botero** [comment] 2017-07-12 20:48
@caesar1995 there should be a **PartialMessagesSupported** ConditionalTheory clause like the one used in [SendReceiveTests,cs](https://github.com/dotnet/corefx/blob/09d029cbe1734ffb4f2ee5f259acfd69ea172158/src/System.Net.WebSockets.Client/tests/SendReceiveTest.cs):

**Comment by caesar1995** [comment] 2017-07-12 20:51
@CIPop do you want to add the ConditionalTheory in #22114? Or I can do that after the PR is merged.

**Comment by CIPop** [comment] 2017-07-12 21:30
> @CIPop do you want to add the ConditionalTheory in #22114? Or I can do that after the PR is merged, to avoid conflict.

I've just merged that. Feel free to add the condition. 
It's best if we could add it to the common/test folder since it's going to be shared between WS and HttpListener.

**Comment by caesar1995** [comment] 2017-07-12 21:31
Sure, I will look into this.

**Closed** 2017-07-14 17:50 UTC
Labels: area-System.Net, bug, disabled-test, os-windows-uwp
