### ISSUE TITLE
Facing an error "System.Net.Sockets.SocketException : Connection refused" on Linux with .Net Core 2.2

### ISSUE THREAD

**Issue by jaydeept** [dotnet/corefx#35583] opened 2019-02-26 07:53 UTC
I am facing an issue on `Linux OS` with `.Net Core 2.2`, while executing some integration test cases. Here is the stacktrace:

> Failed   mytest()
> Error Message:
>  System.Net.WebException : Failed after 5 retries
>   ----> System.Net.WebException : Connection refused Connection refused
>   ----> System.Net.Http.HttpRequestException : Connection refused
>   ----> System.Net.Sockets.SocketException : Connection refused
> Stack Trace:
>    WebApiClient.cs:line 56
>    WebApiClient.cs:line 34
>    at PdsWebAppTests.ClientForTestPdsWebApp.Call(Method method, String url, String requestContent, WebClientHeaders headers) in ClientForTestPdsWebApp.cs:line 19
>    at IntegrationTests.IntegrationTests`1.mytest() in IntegrationTests.cs:line 44
> --WebException
>    at System.Net.HttpWebRequest.GetResponse()
>    at WebApiClient.GetResponse(WebRequest webRequest) in WebApiClient.cs:line 117
>    at WebApiClient.ReceiveResponse(WebRequest webRequest) in WebApiClient.cs:line 97
>    CallWithRetries(Method method, String uriString, String requestContent, WebClientHeaders headers, Int32 retryCount) in WebApiClient.cs:line 46
> --HttpRequestException
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at System.Net.HttpWebRequest.SendRequest()
>    at System.Net.HttpWebRequest.GetResponse()
> --SocketException
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

Here is my high-level code flow:
```
        public Response Call(Method method, string uriString, WebClientHeaders headers, string requestContent)
        {
            var response = CallWithRetries(method, uriString, requestContent, headers, NumberOfTimesToRetry); //WebApiClient.cs:line 34
            return response;
        }

        private Response CallWithRetries(Method method, string uriString, string requestContent, WebClientHeaders headers, int retryCount)
        {
            var lastException = new WebException();
            for (var retriesLeft = retryCount; retriesLeft > 0; --retriesLeft)
            {
                try
                {
                    var webRequest = CreateRequest(method, uriString, requestContent, headers);
                    var response = ReceiveResponse(webRequest);
                    return response;
                }
                catch (WebException e)
                {
                    lastException = e;
                }
                Thread.Sleep(RetryBackoffPeriod);
            }
            throw new WebException($"Failed after {retryCount} retries", lastException);
        }

        private Response ReceiveResponse(WebRequest webRequest)
        {
            var json = "no json returned :-(";
            var webResponse = GetResponse(webRequest); //at WebApiClient.ReceiveResponse(WebRequest webRequest) in WebApiClient.cs:line 97
            if (webResponse == null) return null;
            using (webResponse)
            {
                var responseStream = webResponse.GetResponseStream();
                if (responseStream != null)
                {
                    using (var y = new StreamReader(responseStream))
                    {
                        json = y.ReadToEnd();
                    }
                }
                return new Response(((HttpWebResponse)webResponse).StatusCode, json);
            }
        }
```

P.S.
This test case is working fine in Windows. Also from Linux machine, I am able to launch my web app and able perform all operations so I think it's just `WebRequest.GetResponse()` which is throwing an exception.

**Comment by wfurt** [comment] 2019-02-27 18:53
can you post complete, minimalistic and runable repro? 
It is hard to tell how server side is handled from the example. You can also run it with "strace -f -e trace networking XXX" to see what is going on.

**Comment by jaydeept** [comment] 2019-03-01 07:05
Hi @wfurt ,

This issue got resolved after changing signature of `Main()` method. I did modify Main() method to return `Async Task` instead of `void`. 
Here is how was my `Main `method earlier in `Startup `class:
```
private static void Main(string[] args)
{
    ..............
    var host = configuration.build()
    using (var webAppTask = host.RunAsync(cancellationToken))
    {
        webAppTask.Wait(new CancellationToken());
    }
}
```

And I had one class which I was invoking from Test case which was calling the method using `Task.Run()`

**Comment by davidsh** [comment] 2019-04-01 18:36
>This issue got resolved after changing signature of Main() method. I did modify Main() method to return Async Task instead of void.

Glad you found the root cause of your problem.  Your Main() method is using async methods inside it so it is important to use the async variant of the Main() method.

>System.Net.WebException : Failed after 5 retries
----> System.Net.WebException : Connection refused Connection refused
----> System.Net.Http.HttpRequestException : Connection refused
----> System.Net.Sockets.SocketException : Connection refused

FYI, using WebRequest/HttpWebRequest on .NET Core is not recommended.  It does not perform well compared to using HttpClient.  On .NET Core, HttpWebRequest is built as a compatibility layer on top of HttpClient. It creates a new HttpClient, #15460, for every HttpWebRequest.  That results in no TCP connections being reused (pooled connections). This can easily result in socket port exhaustion. This might also contribute to your here.

I suggest you try using HttpClient directly.

**Comment by davidsh** [comment] 2019-04-01 18:37
Since your problem is resolved (using the async Main() method), we'll close this issue.

**Closed by davidsh** 2019-04-01 18:37 UTC
Labels: area-System.Net.Http
