### ISSUE TITLE
System.Runtime.WindowsRuntime adds incorrect Binding Redirects

### ISSUE THREAD

**Issue by rido-min** [dotnet/corefx#35034] opened 2019-02-01 20:13 UTC
Repro steps:

- Create a .NETStandard Library project
- Reference the Contracts NuGet pkg
- Use some types in the library that use IAsyncOperation
- Create a WPF project
- Reference the library project
- build

You will notice that the .exe.config gets generated with this binding redirect:
```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.WindowsRuntime" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.14.0" newVersion="4.0.14.0" />
      </dependentAssembly>
 ```
 
And since in your .NuGet package you are not copying the System.Runtime.WindowsRuntime.dll locally this will fail as it cannot find the assembly from the NuGet package.

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
```

/cc @jeffschwMSFT

**Comment by rido-min** [comment] 2019-04-23 16:09
This issue is still happening with Preview4
https://www.nuget.org/packages/System.Runtime.WindowsRuntime/4.6.0-preview4.19212.13 I

We still have the wrong binding redirect

```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.WindowsRuntime" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.14.0" newVersion="4.0.14.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

Repro steps:
1 - Create WPF (net472)
2 - Add [Microsoft.Toolkit.Wpf.UI.XamlHost](https://www.nuget.org/packages/Microsoft.Toolkit.Wpf.UI.XamlHost/6.0.0-preview4)
3 - Add a packaging project to the solution
4 - F5 on wapproj

The app fails with:

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Initialization of 'Microsoft.Toolkit.Wpf.UI.XamlHost.WindowsXamlHost' threw an exception.' Line number '12' and line position '35'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at WpfApp6.MainWindow.InitializeComponent() in C:\Users\rmpablos\source\repos\WpfApp6\WpfApp6\MainWindow.xaml:line 1

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

```

**Comment by jeffschwMSFT** [comment] 2019-04-23 16:55
@rido-min can you try referencing the win10 meta contracts from your main project?

**Comment by rido-min** [comment] 2019-04-23 17:06
@jeffschwMSFT  I tried referencing the contracts and the interop packages from the main project but I still got the same FileNotFound exception

**Comment by ericstj** [comment] 2019-04-25 02:54
Is NuGet writing the bindingRedirect to the source app.config?  That could be getting in your way.

**Comment by jeffschwMSFT** [comment] 2019-04-25 14:59
RAR is writing the bindingRedirect.  From what I can see the System.Runtime.WindowsRuntime nuget packageReferences are not being used, and instead the version from the GAC.  As a result, the props to ensure the bindingRedirects are not inserted are not run.  This package has 3 layers of packageReferences, is there anything that we can do to ensure it references the preferred S.R.WR?

**Comment by ericstj** [comment] 2019-04-25 17:58
Using the one from the GAC would only happen if something better wasn't found.  I would expect these packages to provide something [better](https://github.com/Microsoft/msbuild/blob/adb180d394176f36aca1cc2eac4455fef564739f/src/Tasks/Microsoft.Common.CurrentVersion.targets#L545-L571).

Even if the RAR suggests the redirect, I thought you remove it via targets.

3 layers shouldn't matter.  Your package should still be installed to the project and its targets should be used.  Is that not happening?

**Comment by ericstj** [comment] 2019-04-25 18:00
Also can folks clarify if this is happening using Packages.config, PackageReference, or both.

**Comment by rido-min** [comment] 2019-04-25 18:10
PackageReference. The contracts package uses `refs`  that are not supported with packages.config

**Comment by ericstj** [comment] 2019-04-25 20:03
Ok, then this really doesn't jive.  Took a look at the package heirarchy and found out why.

Microsoft.Toolkit.UI.XamlHost is specifying exclude=build on the the SDK.Contracts package, and therefore transitively on its dependencies.  This causes the targets not to apply.
```
    <dependencies>
      <group targetFramework=".NETFramework4.6.2">
        <dependency id="Microsoft.Windows.SDK.Contracts" version="10.0.18362.2002-preview" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp3.0">
        <dependency id="Microsoft.Windows.SDK.Contracts" version="10.0.18362.2002-preview" exclude="Build,Analyzers" />
      </group>
```
This needs to be fixed in the Microsoft.Toolkit.UI.XamlHost package.

@rido-min the reason you didn't see a direct reference fix the problem is due to an incremental build issue with MSBuild: https://github.com/Microsoft/msbuild/blob/adb180d394176f36aca1cc2eac4455fef564739f/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2215-L2231

If you happen to delete the config file and rebuild after directly referencing the packages that workaround it.

Regardless, the bug here is in Microsoft.Toolkit.UI.XamlHost.  @rido-min can you hook up the owners of that package with this analysis?  Action item for them is do not specify ExcludeAssets on their packageReference.  It could be the SDK that's doing that for them, they should turn that off.

**Comment by azchohfi** [comment] 2019-04-25 21:31
The specific line of code we use to reference the SDK Contracts is this:
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/dea259fa43e19382740f341b1b2b46b79af5b10e/Directory.Build.targets#L10
It feels weird to me that this is being excluded by default.
I could happily add the PrivateAssets="analyzers", but it feels to me that this is something else.

**Comment by onovotny** [comment] 2019-04-25 21:36
Build is excluded by default by NuGet and it doesn’t work well anyway. 

The better answer is to use buildTransitive, but that’s currently 2019 only. There’s an open issue tracking a back port.

**Comment by michael-hawker** [comment] 2019-04-25 21:43
Is 2017 supported for this scenario?  The .NET Core Previews have this warning calling out to use VS 2019:

![image](https://user-images.githubusercontent.com/24302614/56770219-35e57280-6768-11e9-8815-45319c5a1e4e.png)

It's also called out in the announcement [blog post](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-4/) for preview4.

**Comment by onovotny** [comment] 2019-04-25 21:49
No, but wasn’t this issue about targets that affect the . NET Framework?

**Comment by ericstj** [comment] 2019-04-25 21:54
> The contracts package uses refs that are not supported with packages.config

Yeah, but it also has targets which can do the same thing as `ref` on packages.config...  Granted that too will depend on targets, ironically packages.config always applies targets so it won't be impacted by this issue.

> wasn’t this issue about targets that affect the . NET Framework?

Correct, we want this stuff to work downlevel & in desktop projects.  I'm not opposed to duplicating the folders, though it seems a little unusual.  I'd still like to get the package heirarchy fixed so that the packages that distribute these don't suppress meaningful functionality in their dependencies.

**Comment by onovotny** [comment] 2019-04-25 21:58
IIRC, the problem with Build is that it requires all consuming packages to declare their dependency correctly, in a non-default scenario. It’s not something the source package alone can fix.

**Comment by ericstj** [comment] 2019-04-25 22:02
Also, looks like we aren't the only broken dependency here, Microsoft.Windows.SDK.Contracts itself also uses targets that are being suppressed.

@onovotny you're correct in general for packages which need to persist as dependencies.  At least for the CoreFx packags we're talking about here, they are more like an SDK.  I'd expect any project that wants to use this functionality would bring in a reference to some "Entry point" package that represents the SDK used to be able to target WinRT.  I don't think its neccesarrily intuitive for some library to transitively bring in WinRT support into an otherwise vanilla project.  Maybe @rido-min has a spec for this experience.

**Comment by azchohfi** [comment] 2019-04-25 22:13
If they also have this transient dependency issue, we need to wait on them to push a new version to push an update on our side, since we depend on them. I don't think it would make sense for us to depend on the glue assemblies just to fix their issue.
@rido-min what do you think?

**Comment by ericstj** [comment] 2019-04-25 23:56
They don't have an issue, they do the right thing WRT these packages.  I was pointing out that the bug in Microsoft.Toolkit.UI.XamlHost was resulting in both the System.*.WindowsRuntime.* packages and Microsoft.Windows.SDK.Contracts to lose their targets.

First step should be for Microsoft.Toolkit.UI.XamlHost to remove exclude="build".

Second step would be for both Microsoft.Windows.SDK.Contracts and System.*.WindowsRuntime.* packages to duplicate all their build assets in buildTransitive folder.

**Comment by azchohfi** [comment] 2019-04-26 20:13
https://www.nuget.org/packages/Microsoft.Toolkit.Wpf.UI.XamlHost/6.0.0-preview4.1

**Comment by ericstj** [comment] 2019-04-27 05:30
Thank you for this fix @azchohfi.  @jeffschwMSFT remaining work is for us to duplicate build folder into buildTransitive.  @rido-min can you let the owners of Microsoft.Windows.SDK.Contracts know they need to do the same?

**Comment by jeffschwMSFT** [comment] 2019-04-30 19:56
Thanks for tracking this down @ericstj et. al.  Just so I am clear on what is needed for this issue.. I need to duplicate the contents of 'build' into a folder called 'buildTransitive'?  Correct?

**Comment by ericstj** [comment] 2019-04-30 20:56
Yep, that will do it.

**Closed** 2019-05-07 19:38 UTC
Labels: area-System.Runtime.InteropServices
