### ISSUE TITLE
Extension methods and dynamic

### ISSUE THREAD

**Issue by pianoman4873** [dotnet/corefx#34327] opened 2019-01-02 12:12 UTC
in Visual Studio 2015 version , the following code snippet throws a runtime exception when running method MethodFailingOnRuntime , although it shouldn't ( compliation passes successfully ) - 

```
static class ExtentionMethodsClass { 

  public static void FuncA ( this A a )  { 

  }
}


class A { }


static class B() { 

   static A FuncB ( dynamic d ) { 
     return new A();
   }
  static void  MethodFailingOnRuntime( dynamic d ) { 

      var a = FuncB (d);
      a.FuncA();
  }

}
```

If in MethodFailingOnRuntime , I change the assignment to - 

A a = FuncB(d);

then , invocation of a.FuncA()  passes successfully.
Seems that although  FuncB explicitly returns type A in its signature, the runtime / compiler doesn't recognize the instance variable a is of type A when the assignment is done using 'var' and throws an exception stating FuncA doesn't exist when trying to apply it.  Note that as said previously, compilation passes successfully.

**Comment by jkotas** [comment] 2019-01-03 12:45
Extension methods are not supported by `dynamic` keyword. E.g. https://stackoverflow.com/questions/5311465/extension-method-and-dynamic-object talks about it.

I do not see it mentioned anywhere in the official docs (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic). We should update the docs to mention this.

**Comment by pianoman4873** [comment] 2019-01-03 12:49
Note that I'm not applying an extension method on the dynamic type.
The extension method is on class A , and FuncB returns type A.
There's no invocation in the example above of an extension method on a dynamic type.

**Comment by jkotas** [comment] 2019-01-03 13:06
cc @jaredpar

**Comment by jaredpar** [comment] 2019-01-03 19:22
@pianoman4873 

> There's no invocation in the example above of an extension method on a dynamic type.

That's incorrect. The type of `a` in this example is `dynamic`, not `A`. That means that `a.FuncA` is evaluated dynamically not statically. The reason the type is `dynamic` here is that one of the inputs to the initialization expression, `d`, is `dynamic` hence the entire expression is `dynamic`.

**Comment by jaredpar** [comment] 2019-01-03 19:30
@pianoman4873 

> That seems very peculiar to me :)

That's just how `dynamic` functions. In this very specific case yes the compiler could probably deduce the method which is being invoked statically. The more general `dynamic` case though, which the language rules are designed around, cannot be statically deduced.

**Comment by pianoman4873** [comment] 2019-01-03 19:38
@jaredpar 
OK , and would the compiler deduce the type had FuncA was not an extension method , but a proper method on class A?

i.e 

```
class A { 

void funcA();

}
```

**Comment by jaredpar** [comment] 2019-01-03 19:40
@pianoman4873 

> OK , and would the compiler deduce the type 

No. Once `dynamic` is involved in an expression then the type of the expression is `dynamic`. The only exception to this rule, that I'm aware of, is a special case with local functions.

**Comment by pianoman4873** [comment] 2019-01-03 19:42
@jaredpar 
Ok , good to know  :)
So we must explicitly specify the type when doing the assignment  e.g. 

A a = FuncB(d)
a.FuncA(); 

 this works :)

Thanks a lot.

**Comment by cston** [comment] 2019-02-25 18:33
Closing since the existing behavior is by design.

**Closed by cston** 2019-02-25 18:33 UTC
Labels: area-Microsoft.CSharp, documentation
