### ISSUE TITLE
HttpRequestStreamTests.Read_FullLengthAsynchronous_Success failed in CI with "invalid response"

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18590] opened 2017-04-19 01:29 UTC
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/6549/consoleText
```
  Test: ExecuteReaderWithCommandBehaviorTest Enabled Listeners
     System.Net.Tests.HttpRequestStreamTests.Read_FullLengthAsynchronous_Success(transferEncodingChunked: True, text: \"\") [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
        Stack Trace:
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(462,0): at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.HttpListener\tests\HttpRequestStreamTests.cs(72,0): at System.Net.Tests.HttpRequestStreamTests.<Read_FullLengthAsynchronous_Success>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  Test: ExecuteReaderWithCommandBehaviorTest Started Server
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\windows_nt_de---4526f5ff\src\Common\src\System\Threading\Tasks\RendezvousAwaitable.cs(62,0): at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(863,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
  Test: ExecuteReaderWithCommandBehaviorTest SqlOperation Successful
  Test: ExecuteReaderWithCommandBehaviorTest Listeners Disabled
  Test: ExecuteReaderWithCommandBehaviorTest Server Disposed
  Test: ExecuteReaderWithCommandBehaviorTest Listeners Disposed Successfully
  Test: ConnectionOpenAsyncErrorTest Enabled Listeners
  Finished:    System.Net.HttpListener.Tests
```

**Comment by hughbe** [comment] 2017-04-19 03:07
Dupe of https://github.com/dotnet/corefx/issues/18376

**Closed** 2017-04-19 03:19 UTC
Labels: area-System.Net.Http
