### ISSUE TITLE
System.Text.Json Deserialization issue

### ISSUE THREAD

**Issue by JulienM28** [dotnet/corefx#41244] opened 2019-09-21 10:50 UTC
I have a Json string starting like this:

````json
{"nameid":"1",
.............
"exp":1566506525
.............
}
````
the nameid is part of claims and is automatically serialized to string.

But my dto defines an integer:

````csharp
   [JsonPropertyName("nameid")]
        public int Id { get; set; }
............
  [JsonPropertyName("exp")]
        public int Expiration { get; set; }
````
When I Deserialize the Json in Blazor WebAssembly App I get this error:

WASM: Exception: The JSON value could not be converted to System.Int32. Path: $.nameid | LineNumber: 0 | BytePositionInLine: 13.

**Comment by huoyaoyuan** [comment] 2019-09-22 05:12
#39473

**Comment by scalablecory** [comment] 2019-09-24 21:43
Closing as dupe of #39473.

**Closed by scalablecory** 2019-09-24 21:43 UTC
Labels: area-System.Text.Json
