### ISSUE TITLE
EmailAddressAttribute accepts invalid email address

### ISSUE THREAD

**Issue by davidbutt** [dotnet/corefx#4923] opened 2015-12-10 16:41 UTC
The following email address is accepted as valid by the EmailAddressAttribute:

a@aa.aa.

Note the trailing dot. This is an invalid address.

This only works if there is already a dot earlier in the address (as above).

**Comment by davidsh** [comment] 2015-12-10 16:45
Are you talking about the `System.ComponentModel.DataAnnotations.EmailAddressAttribute` class?

**Comment by stephentoub** [comment] 2015-12-10 17:44
cc: @lajones

**Comment by lajones** [comment] 2015-12-10 18:21
cc: @Eilon, @divega We had earlier decided that the purpose of `EmailAddressAttribute` was just to prevent "fat-fingering" errors - not to prevent every possible invalid email address. The algorithm we currently use is "must have at least one '@' and the '@' cannot be at the start or the end." The above passes that test (along with many other potential errors). Suggest we don't fix this, but feel free to chime in.

**Comment by Eilon** [comment] 2015-12-10 22:03
@lajones yup that's totally how I look at this. The value of parsing an RFC-valid email address is close to zero for me.

**Comment by lajones** [comment] 2015-12-10 22:26
Closing as "By Design" then.

**Comment by divega** [comment] 2015-12-10 22:27
:+1: The main scenario for the attribute is the validation of existing email addresses (as opposed to creating new email addresses). There are added costs and diminishing returns in trying to improve the validation to get closer to any standard. And ultimately even an email address that complies perfectly to those RFCs will still not be a valid email address if it doesn't exist.

**Closed by lajones** 2015-12-10 22:26 UTC
