### ISSUE TITLE
System.Net.NetworkInformation manifest error

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/corefx#17014] opened 2017-03-12 00:00 UTC
My app references the nuget package for System.Net.NetworkInformation 4.3.0.  
When I attempt a call to, say, NetworkInterface.GetIsNetworkAvailable() I get this error:

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I have manually deleted nuget cache, obj and bin directories multiple times.

When I look at the assemblies in Object browser I see System.Net.Networkinformation [4.1.0.0] and [4.1.1.0] - they are installed in c:\yada\packages\system.net.networkinformation\ **4.3.0** \ref\yada.

When I roll back to 4.1.0.0 everything works.
My csproj:

```xml
<PropertyGroup>
    <TargetFrameworks>net462;netcoreapp1.1</TargetFrameworks>
  </PropertyGroup>
```

**Comment by karelz** [comment] 2017-03-12 06:16
If 4.1.0.0 assembly version is required and you have 4.1.1.0, then you need a binding redirect. Is that the case?

**Comment by sam-wheat** [comment] 2017-03-12 15:06
No - 4.3.0 is required.  For some reason I am finding 4.1.0.

**Comment by sam-wheat** [comment] 2017-03-12 18:32
Here is how to reproduce the problem:
Create a library project, target netstandard 1.3.  Add a reference to System.Net.NetworkInformation as shown below.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="4.4" />
      <PackageReference Include="System.Data.SqlClient" Version="4.3.0" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.1" />
      <PackageReference Include="System.Net.NetworkInformation" Version="4.3.0" />
      <PackageReference Include="NETStandard.Library" Version="1.6.1" />
    </ItemGroup>
</Project>
```

Create a console app or test project and reference the library project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFrameworks>net46</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\bindingTest\bindingTest.csproj" />  
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```


Create a unit test:

```
public class UnitTest1
{
	[Fact]
	public void Test1()
	{
		var x = new bindingTest.Class1();
	}
}
```


Error:

```
System.IO.FileLoadException occurred
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=bindingTest
  StackTrace:
   at bindingTest.Class1..ctor() in C:\Users\Sam\documents\visual studio 2017\Projects\bindingTest\bindingTest\Class1.cs:line 10
   at XUnitTestProject1.UnitTest1.Test1() in C:\Users\Sam\documents\visual studio 2017\Projects\bindingTest\XUnitTestProject1\UnitTest1.cs:line 11
```

**Comment by sam-wheat** [comment] 2017-03-12 18:49
I should tell you that my ultimate objective is to use my library (netstandard1.3 or better) in my WPF app that targets Net46.  I created a dummy WPF app targeting Net46, referenced library as shown above and I crash with the same error.

**Comment by karelz** [comment] 2017-03-12 19:20
System.Net.NetworkInformation 4.3.0 has assembly version 4.1.1.0. Another of your dependencies depends on older version - assembly version 4.1.0.0. You need binding redirect.

You can check out dependencies of DLLs in your app directory (use ildasm/Reflector/ILSpy/ObjectBrowser/other ways) to find out which assembly drags it in.

What is the bindingTest reference in your project?
I would love to get my hands on a repro locally to understand what is broken in the end to end VS experience. AFAIK the binding redirects should be generated automatically. Can you please try to repro it from console app without xunit? Can you try to eliminate unnecessary dependencies? (if you find which DLL drags in the 4.1.0.0 assembly ref, it should be sufficient information)
Thanks!

**Comment by sam-wheat** [comment] 2017-03-12 19:59
>Another of your dependencies depends on older version - assembly version 4.1.0.0. You need binding redirect.

No that is not the case as far as I can tell.  I did not remove the other dependencies before I pasted my lib .csproj.  Here is the corrected one:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.3</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Net.NetworkInformation" Version="4.3.0" />
    </ItemGroup>
</Project>
```

Here is the only code in the lib project:


```

public class Class1
{
	public Class1()
	{
		bool x = System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable();
	}
}

```

> I would love to get my hands on a repro locally to understand what is broken in the end to end VS experience.


Please take a moment to create the two very simple projects as I have demonstrated.  I am using VS2017 released version.  If you would rather not create an xunit project than just create a WPf projct.  It crashes in both of them.
Do you get the same result?

**Comment by sam-wheat** [comment] 2017-03-12 20:11
for the record here is the output of dotnet

> Microsoft .NET Core Shared Framework Host
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

**Comment by sam-wheat** [comment] 2017-03-12 21:48
I thought I discovered a workaround by adding System.Net.Networkinformation directly to my WPF project and test projects.  My test project actually runs, but WPF crashes with the error below.
System.IO.FileSystem is already part of that project so I'm stuck here.



> System.IO.FileLoadException occurred
  HResult=0x80131040
  Message=Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Application.Core
  StackTrace:
   at Application.Core.JSONDeserializer.Deserialize[T](String filePath) in C:\Git\AdaptiveClient.AdvancedDemo\AdaptiveClientDemo\src\Application.Core\EndPointFileParser.cs:line 20
   at WCFServer.Global.ReadEndPoints() in C:\Git\AdaptiveClient.AdvancedDemo\AdaptiveClientDemo\src\WCFServer\Global.asax.cs:line 45
   at WCFServer.Global.Application_Start(Object sender, EventArgs e) in C:\Git\AdaptiveClient.AdvancedDemo\AdaptiveClientDemo\src\WCFServer\Global.asax.cs:line 33

**Comment by sam-wheat** [comment] 2017-03-12 22:31
Why is this post marked as "Future"?  What does that mean?  Am I doing something wrong?  Can I do more to troubleshoot?  Please answer my questions directly including [this one](https://github.com/dotnet/corefx/issues/17032).  I have been at this all weekend with nothing accomplished - everything I touch with VS2017 appears to be broken.  When so many things break I start to doubt myself (and I am often the culprit) so I have to ask basic questions like this to make sure I'm on track.  Thanks for your help.

**Comment by karelz** [comment] 2017-03-13 00:05
I am able to reproduce it.

To get unblock, just use a [bindingRedirect](https://msdn.microsoft.com/en-us/library/eftw1fys(v=vs.110).aspx) which I suggested earlier. It should be fairly straightforward.

@weshaggard, it looks like yet another example of OOB replacing Desktop :(. Can you please confirm?

**Comment by davidsh** [comment] 2017-03-13 00:14
>@weshaggard, it looks like yet another example of OOB replacing inbox Desktop :(. Can you please confirm?

We have not OOB'd System.Net.NetworkInformation from the .NET Framework. That DLL does NOT exist in the .NET Framework in terms of being in the GAC.  It might be registered as a facade in some fashion but there is not implementation of an OOB for this.

**Comment by karelz** [comment] 2017-03-13 15:40
@davidsh the assembly seems to be part of .NET Framework:
C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Net.NetworkInformation.dll

If we ship NuGet with the same assembly identity (with higher assembly version), then we OOB'ed, right? What am I missing?

**Comment by karelz** [comment] 2017-03-13 15:43
That said, I think we need a good education on what to do when you hit the assembly version mismatch and direct developers to bindingRedirects. They will be always part of our lives, esp. on Desktop.

**Comment by davidsh** [comment] 2017-03-13 23:59
>@davidsh the assembly seems to be part of .NET Framework:
 C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Net.NetworkInformation.dll

That dll is a facade and not implementation.  And I thought, the .NET Core builds for 'net46' binary should also create a facade as well even though there is a downloadable NuGet package for System.Net.NetworkInformation.  It's possible that facade assemblies also have the same "binding redirects" problem on .NET Framework (Desktop) that the implementation assemblies have as well.  @weshaggard can answer more fully on this.

**Comment by karelz** [comment] 2017-03-14 00:07
cc @ericstj for insight ...

**Comment by weshaggard** [comment] 2017-03-15 17:47
Yes any assembly that ships in box, facade or implementation, will have the same binding redirection problem if we ship a facade with a higher version in a package, which it appears we have done in this case. This is another instance of https://github.com/Microsoft/msbuild/issues/1346 where the auto-binding redirects don't work, but if you manually create them then it will work.

@sam-wheat try adding the following to your app.config

```
   <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">  
         <dependentAssembly>  
            <assemblyIdentity name="System.Net.NetworkInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />  
            <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0"/>  
         </dependentAssembly>  
      </assemblyBinding>  
   </runtime>  
```

Please let us know if that doesn't resolve your issue.

**Comment by davidsh** [comment] 2017-03-15 19:45
Change label tag since the binding redirect problem is not System.Net specific.

**Comment by davidsh** [comment] 2017-03-20 20:09
The current, stable, System.Net.NetworkInformation NuGet package is this one:
https://www.nuget.org/packages/System.Net.NetworkInformation/4.3.0

The 'net46' binary in that package is a DLL with assembly version:

```C#
[assembly: AssemblyVersion("4.1.1.0")]
```

When using this package in a .NET Framework based solution, the use of binding redirects are REQUIRED  in order to vaoid problems.

So, adding something like this to your app.config/web.config is required:

```c#
  <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">  
         <dependentAssembly>  
            <assemblyIdentity name="System.Net.NetworkInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />  
            <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0"/>  
         </dependentAssembly>  
      </assemblyBinding>  
   </runtime> 
```

There is no actionable change we can do.  This is by-design behavior when using updated assemblies from the inbox .NET Framework.

I am closing this issue. Please let us know if the use of the binding redirects doesn't solve your problem.

**Closed by davidsh** 2017-03-20 20:09 UTC
Labels: area-System.Net, question

**Comment by oliverjanik** [comment] 2017-05-15 06:05
Are you saying that by design we get a broken experience? Right now I'm experiencing a ***DLL HELL*** It's making me reconsider the whole .net core and netstandard.

If I create a netstandard library and reference it in a 461 project it blows up during runtime. Is that by design? Really? You average .NET Joe doesn't have a clue what a binding redirect even is.

VS2017 has shipped a **stable** version, yet we get a barely beta experience when it comes to actually working on .netcore and .netstandard projects. How is this an acceptable situation?
