### ISSUE TITLE
[RC1 blocker] AV in System.Linq.Expressions tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4149] opened 2015-10-26 22:59 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3850/console
```
15:34:41 Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
15:34:41    at Tests.Expressions.InterpreterTests.Verify(Expression expr)
15:34:41    at Tests.Expressions.InterpreterTests.CompileInterpretCrossCheck_Divide()
15:34:41    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
15:34:41    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
15:34:41    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
15:34:41    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
15:34:41    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
15:34:41    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
15:34:41    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
15:34:41    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
15:34:41    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
15:34:41    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
15:34:41    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
15:34:41    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestClassRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
15:34:41    at System.Threading.Tasks.Task`1.InnerInvoke()
15:34:41    at System.Threading.Tasks.Task.Execute()
15:34:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:34:41    --- End of inner exception stack trace ---
15:34:41    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
15:34:41    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
15:34:41    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
15:34:41    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
15:34:41    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
15:34:41    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
15:34:41    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
15:34:41    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
15:34:41    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
15:34:41    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
15:34:41    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
15:34:41    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
15:34:41    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestClassRunner`1.RunAsync()
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
15:34:41    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
15:34:41    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
15:34:41    at System.Threading.Tasks.Task`1.InnerInvoke()
15:34:41    at System.Threading.Tasks.Task.Execute()
15:34:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:34:41    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
15:34:41    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
15:34:41    at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
15:34:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:34:41    at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
15:34:41    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
15:34:41    at System.Threading.Tasks.Task.Execute()
15:34:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:34:41    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
15:34:41    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
15:34:41    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
15:34:42 ./run-test.sh: line 130: 39009 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
```

**Comment by bartdesmet** [comment] 2015-10-27 10:00
Not sure what triggers this...

Does the build include https://github.com/dotnet/corefx/commit/1bc138af86b0c8048e6a21e0d8ca8768f1cba9d8? If so, the exception should have been caught and wrapped with an Exception that contains the expression that triggers the condition (and the bare exception showing up like this would indicate the error occurs in the `Expression` factory method invocations, which seems unlikely).

Also notice the failing test is `CompileInterpretCrossCheck_Divide`. The closest related tests that we've seen failing on Unix platforms were disabled in https://github.com/dotnet/corefx/commit/54aa88d42d410f240118de6940da9797f0eb7545 (and subsequently reenabled after the root cause was fixed). It could have to do with nullables once more, but that's just a wild guess...

**Comment by VSadov** [comment] 2015-10-27 16:43
@stephentoub   I see the change was merged in. Does the issue no longer reproduce?

**Comment by stephentoub** [comment] 2015-10-27 16:51
> @stephentoub I see the change was merged in. Does the issue no longer reproduce?

The PR that was merged simply updated some metadata on a completely unrelated assembly (https://github.com/dotnet/corefx/pull/4139/files).  The AV was unrelated to those changes, and just happened to occur during that CI run.  Whatever the issue is, it's very likely still there, e.g. maybe some memory is being written to incorrectly and this will fail if that memory happens to be in the wrong spot during a given run.

**Comment by joshfree** [comment] 2015-10-29 19:59
@VSadov can you provide an update now that https://github.com/dotnet/coreclr/issues/1831 has been fixed by https://github.com/dotnet/coreclr/pull/1879 in 23429.00.  Are we still seeing this Linq.Expressions AV?

**Comment by VSadov** [comment] 2015-10-30 16:26
It does not seem to be reproduce as far as I see in the build history. The test is enabled.

It is either fixed or the issue is extremely rare and we are not hitting it. 
Regardless, without repro, it is not actionable, so I will close the bug.

**Closed by VSadov** 2015-10-30 16:26 UTC
Labels: System.Linq.Expressions
