### ISSUE TITLE
DispatchProxy and .NET Native: Cannot create proxies with generic type parameter

### ISSUE THREAD

**Issue by peter-f-s** [dotnet/corefx#5821] opened 2016-02-01 16:03 UTC
Inside a UWP project I defined a System.Reflection.DispatchProxy like this:

```c#
    public class MyProxy<T> : DispatchProxy
    {
        private T _instance;

        public static T Create(T instance)
        {
            var proxy = Create<T, MyProxy<T>>();
            var myProxy = (MyProxy<T>)(object)proxy;
            myProxy._instance = instance;
            return proxy;
        }

        protected override object Invoke(MethodInfo targetMethod, object[] args)
        {
            // do something here with _instance
            return 42;
        }
    }
```
This works fine in compilation and usage, as long as it is not compiled for .NET Native.
In this case the compiler states the following:
**Internal compiler error: Unable to cast object of type 'Microsoft.Cci.Immutable.GenericTypeInstance' to type 'Microsoft.Cci.INamedTypeDefinition'.**

Reason seems to be the generic type parameter. If this is omitted, compilation works again.

I am using Visual Studio 2015.1

**Comment by roncain** [comment] 2016-02-04 16:08
@peter-f-s thanks for reporting this.  We appreciate it.
Would you mind opening an issue at http://connect.microsoft.com/ for this? And adding a link to it from this issue? This current dotnet/corefx project is currently tracking only issues that can be reproduced by code in this repo, and as it turns out, the DispatchProxy in this repo is not the same implementation you encountered in your UWP apps.

I have opened an issue internally for this and assigned it to the right team, but you will be able to track progress if you open an issue at http://connect.microsoft.com/ yourself.

We're happy to support you with the UWP ahead of time compiler (".NET Native") if you send us a mail at dotnetnative@microsoft.com. 

I'm closing the issue here and look forward to following up with you via email.  Thanks again for taking the time to report this.

**Closed by roncain** 2016-02-04 16:08 UTC

**Comment by peter-f-s** [comment] 2016-02-04 16:41
Thanks!
Here is the follow-up: [https://connect.microsoft.com/VisualStudio/feedback/details/2322483](url)

**Comment by MelbourneDeveloper** [comment] 2017-09-05 23:52
We think this may be a problem for us as as well, but the link above is broken.

**Comment by peter-f-s** [comment] 2017-09-06 06:42
I tried to find the ticket again, but without luck. It seems that Microsoft removed it...
