### ISSUE TITLE
System.Text.Json.JsonSerializer.Serialize throws ArgumentOutOfRangeException for a long string with unicode characters

### ISSUE THREAD

**Issue by markvincze** [dotnet/corefx#40409] opened 2019-08-19 10:21 UTC
I bumped into an issue on our production system with `System.Text.Json.JsonSerializer.Serialize()`, which throws an `ArgumentOutOfRangeException` for certain strings. I'm on version `4.6.0-preview8.19405.3` of `System.Text.Json`, running `3.0.0-preview8-28405-07` of the framework. The issue happens both on Windows and Linux.

Here is a full repro.

```
namespace JsonSerializerExceptionRepro
{
    public class Model
    {
        public string Foo { get; set; }
    }

    public class JsonSerializerTest
    {
        [Fact]
        public void DeserializeObject_LongStringInput_Success()
        {
            var fieldValue = "{\"xxxxxxxXxxxXxxXxxxxxx\":\"XXXXXX XXXXXXXXX XXXXXXXXX\",\"xxxxxxxXx\":\"xx1x95xx-xxx4-4611-9x80-39x15x08xxx5\",\"xxxxXxxx\":{\"xxxxXxxx\":{\"xxxxxxxxxXxxx\":\"2019-08-22\",\"xxxxxxXxxx\":\"2019-08-26\",\"xxxxxxxXxxxXxxxxxxXxxx\":\"2019-08-19\",\"xxxxxXxxxxxxXxxx\":\"2019-08-19\",\"xxxxxxXxxx\":[{\"xxxxx\":0,\"xxxxxxXxxxxxx\":\"XXX\",\"xxxxxxXxxxxxx\":\"XX\",\"xxxxxxxxxxxXxxxxxx\":\"XXX\",\"xxxxxxxxxxxXxxxxxx\":\"XX\",\"xxxxxxx\":\"Xxxxxxxx Xxxxxxxx\",\"xxxxxxxXxxx\":\"XX\",\"xxxxxxxxx\":\"Xxxxxxxx\",\"xxxxxXxxx\":\"2019-08-22X19:50:00X\",\"xxxXxxx\":\"2019-08-23X03:45:00X\",\"xxxxXxxxxx\":\"474\"},{\"xxxxx\":1,\"xxxxxxXxxxxxx\":\"XXX\",\"xxxxxxXxxxxxx\":\"XX\",\"xxxxxxxxxxxXxxxxxx\":\"XXX\",\"xxxxxxxxxxxXxxxxxx\":\"XX\",\"xxxxxxx\":\"Xxxxxxxx Xxxxxxxx\",\"xxxxxxxXxxx\":\"XX\",\"xxxxxxxxx\":\"Xxxxxxx\",\"xxxxxXxxx\":\"2019-08-26X04:40:00X\",\"xxxXxxx\":\"2019-08-26X09:55:00X\",\"xxxxXxxxxx\":\"642\"}],\"xxxXxxxxxxx\":\"XXX\",\"xxxxXxxxx\":\"861.99\",\"xxxxXxxx\":\"XxxxxXxxx\",\"xxxxxXxxxxx\":{\"xxxxx\":0,\"xxxxxxXxxxxxx\":\"XXX\",\"xxxxxxXxxxxxx\":\"XX\",\"xxxxxxxxxxxXxxxxxx\":\"XXX\",\"xxxxxxxxxxxXxxxxxx\":\"XX\",\"xxxxxxx\":\"Xxxxxxxx Xxxxxxxx\",\"xxxxxxxXxxx\":\"XX\",\"xxxxxxxxx\":\"Xxxxxxxx\",\"xxxxxXxxx\":\"2019-08-22X19:50:00X\",\"xxxXxxx\":\"2019-08-23X03:45:00X\",\"xxxxXxxxxx\":\"474\"},\"xxxxXxxxxx\":{\"xxxxx\":1,\"xxxxxxXxxxxxx\":\"XXX\",\"xxxxxxXxxxxxx\":\"XX\",\"xxxxxxxxxxxXxxxxxx\":\"XXX\",\"xxxxxxxxxxxXxxxxxx\":\"XX\",\"xxxxxxx\":\"Xxxxxxxx Xxxxxxxx\",\"xxxxxxxXxxx\":\"XX\",\"xxxxxxxxx\":\"Xxxxxxx\",\"xxxxxXxxx\":\"2019-08-26X04:40:00X\",\"xxxXxxx\":\"2019-08-26X09:55:00X\",\"xxxxXxxxxx\":\"642\"}},\"xxxXxxx\":{\"xxxxxxxXxxxxx\":{\"xxxxx\":0,\"xxxxxx\":\"X\",\"xxxxx\":\"Xx.\",\"xxxxxXxxx\":\"Xxxxx\",\"xxxxXxxx\":\"Xxxxxxxxxx\",\"xxxxxxx\":\"XX\",\"xxxx\":\"Xxxxxxxx\",\"xxxxxx\":\"Xxxxxxxxx\",\"xxx\":\"4553\",\"xxxxXxxxx\":\"0792856408\",\"xxxxx\":\"xxxxx.xxxxxx77@xxxxx.xxx\",\"xxxxXxXxxxx\":\"1977-05-17+00:00\",\"xxxxXxxx\":\"861.99\",\"xxxxxxXxxx\":\"Xxx-xxxxxxxxxx\",\"xxxXxxx\":\"XXX\"},\"xxxxxxxxx\":[{\"xxxxx\":0,\"xxxxxx\":\"X\",\"xxxxx\":\"Xx.\",\"xxxxxXxxx\":\"Xxxxx\",\"xxxxXxxx\":\"Xxxxxxxxxx\",\"xxxxxxx\":\"XX\",\"xxxx\":\"Xxxxxxxx\",\"xxxxxx\":\"Xxxxxxxxx\",\"xxx\":\"4553\",\"xxxxXxxxx\":\"0792856408\",\"xxxxx\":\"xxxxx.xxxxxx77@xxxxx.xxx\",\"xxxxXxXxxxx\":\"1977-05-17+00:00\",\"xxxxXxxx\":\"861.99\",\"xxxxxxXxxx\":\"Xxx-xxxxxxxxxx\",\"xxxXxxx\":\"XXX\",\"xxxxxXxxxx\":\"Xxxxxxx\",\"xxxxxxXxxxxxx\":xxxxx,\"xxxxxxxxXxxxx\":xxxxx}]},\"xxxxxxxxxXxxxxxxXxxx\":\"XX\",\"xxxxxxxxXxxxxxxx\":\"XX\",\"xxxxxxxxxXxxx\":\"XxxxxxxxxxxxXX\"},\"xxxxxxxxxxxXx\":\"xxxxx://xxxxxxxxxxxxxxx.xxxxxx.xxx/xxxxxxx/1xxx6x0x-53xx-40xx-88xx-5xx79x071x62?xxxxxxxxXx=xx1x95xx-xxx4-4611-9x80-39x15x08xxx5&xxxxxxxxx=XxxxxXxxxxxxXX&xxxxxxxx=XX\",\"xxxxxxxxXxxxxxxxx\":{\"xxxx\":\"Xxxxxxxxxxxxxxxx\",\"xxxxxxxxxxx\":\"Xxxxxxxxx\",\"xxxxxxxXxx\":\"XXXXXX.022033\",\"xxxxxxxx\":\"XXX\",\"xxxxxxxXxxxxx\":[{\"xxxx\":\"XXXXXX XXXXXXXXX XXXXXXXXX\",\"xxxx\":\"XXXXXX\",\"xxxxxxxXx\":\"000000\",\"xxxxx\":20.0,\"xxxxXxxxx\":19.05,\"xxxxxxxxxx\":9.71,\"xxxxxxxxx\":0.0,\"xxxxxxXxxx\":3.5,\"xxxxxXxxxXxxxxxxXxxx\":23.5,\"xxx\":0.95,\"xxxxxxxxXxxxxXxxXxxxxx\":23.5,\"xxxxxxxx\":0.0,\"xxxxxxxxxXxxxxx\":0,\"xxxxx\":[\"Xxxxxxxxüxxxxxxxxxxx\",\"Xxxxxxxxx xüx Xxxxxxxxxx\",\"Xxxxxxxxx xüx Xxxäxxxxxxxx xxx xxx xx XXX 1.950\"],\"xxxxxxxxXxxx\":\"Xxxx Xxxxxxxxxxxxx\",\"xxxxxxx\":{\"xxxx\":\"XXX\",\"xxxx\":\"XXX\"},\"xxxxxxxx\":xxxxx}],\"xxxXxxxxxxx\":xxxxx,\"xxxxxxxxXxxx\":\"Xxxxxxx Xxxxxx - XXXXXXXXXXX\",\"xxxxxxxxXxxx\":\"XXX\",\"xxxxx\":23.5,\"xxxxxxxxxx\":9.71,\"xxxxxxXxxx\":3.5,\"xxx\":0.95,\"xxxxxXx\":0}}";

            var obj = new Model
            {
                Foo = fieldValue
            };

            var str = JsonSerializer.Serialize(obj);

            Assert.NotNull(str);
        }
    }
}
```

(I obfuscated the input string, hence the lot of `x`es.)

I expect this test to be successful, but the `Serialize()` call throws this exception:

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
   at System.Text.Json.JsonWriterHelper.EscapeString(ReadOnlySpan`1 value, Span`1 destination, JavaScriptEncoder encoder, Int32& written)
   at System.Text.Json.JsonWriterHelper.EscapeString(ReadOnlySpan`1 value, Span`1 destination, Int32 indexOfFirstByteToEscape, JavaScriptEncoder encoder, Int32& written)
   at System.Text.Json.Utf8JsonWriter.WriteStringEscapeValue(ReadOnlySpan`1 value, Int32 firstEscapeIndexVal)
...
```

Sorry for the long input string, this is a real-life value that triggered this problem, and I couldn't narrow it down further. For example if I pass in just the first half, or just the second half of the string, then it works.  
The string contains a couple of unicode characters (`ü`, `ä`), but those in themselves don't cause the issue either.

I verified that this works properly with `Newtonsoft.Json.JsonConvert.SerializeObject()`.

**Comment by ahsonkhan** [comment] 2019-08-19 10:41
Can you try with preview 9 bits (or latest nightly)? It is no longer reproducible on master.

Please try the nightly SDK/runtime with the fix to verify it works (https://github.com/dotnet/core-sdk#installers-and-binaries), or wait till preview 9 ships. Alternatively, you could reference the latest S.T.Json NuGet package. For example:

```csproj
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="4.6.0-preview9.19413.13" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.6.0-preview9.19413.13" />
  </ItemGroup>
```

This bug was introduced in preview 8 but has since been fixed (preview 9 and in master). See https://github.com/dotnet/corefx/pull/39524#discussion_r314138162

> Sorry for the long input string, this is a real-life value that triggered this problem, and I couldn't narrow it down further.

Yep, it is difficult to hit that code path easily.

cc @steveharter

**Comment by markvincze** [comment] 2019-08-19 11:09
@ahsonkhan Thanks for the info!

I tested with `4.6.0-preview9.19413.13`, and it works properly.

**Comment by ahsonkhan** [comment] 2019-08-19 11:16
Great. Closing.

**Closed by ahsonkhan** 2019-08-19 11:16 UTC
Labels: area-System.Text.Json
