### ISSUE TITLE
Matrix4x4CreateFromYawPitchRollTest2 failed on OS X in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4882] opened 2015-12-08 15:37 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/79/console

```
07:00:32    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2 [FAIL]
07:00:32       Yaw:-265 Pitch:155 Roll:-405
07:00:32       Expected: True
07:00:32       Actual:   False
07:00:32       Stack Trace:
07:00:33             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2()
```

**Comment by stephentoub** [comment] 2015-12-10 00:53
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/109/console

**Comment by mellinoe** [comment] 2016-01-22 19:11
We attempted to get a repro of this (see discussion at https://github.com/dotnet/coreclr/issues/2266), but even running on the same CI machine, with the same bits as one of the past failures, we were unable to get a repro. Since this seems to be such an obscure problem, I'm moving to Future but leaving it open for now. Hopefully we can get some better information in the future regarding why this happens. In any case, the issue is almost certainly in the runtime, as the code here is unchanged for a very long time and passes in all other configurations.

**Comment by stephentoub** [comment] 2016-01-26 06:16
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/144/console
```
22:09:56    System.Reflection.Tests  Total: 685, Errors: 0, Failed: 0, Skipped: 0, Time: 1.225s
22:09:56    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2 [FAIL]
22:09:56       Yaw:-580 Pitch:610 Roll:-55
22:09:56       Expected: True
22:09:56       Actual:   False
22:09:56       Stack Trace:
22:09:57             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2()
```

**Comment by stephentoub** [comment] 2016-01-26 07:46
And again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/145/console
```
23:01:59    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2 [FAIL]
23:01:59       Yaw:260 Pitch:-440 Roll:50
23:01:59       Expected: True
23:01:59       Actual:   False
23:01:59       Stack Trace:
23:01:59             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2()
```

**Comment by stephentoub** [comment] 2016-01-29 08:35
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst/326/console
```
00:04:41    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2 [FAIL]
00:04:41       Yaw:-160 Pitch:330 Roll:-125
00:04:41       Expected: True
00:04:41       Actual:   False
00:04:41       Stack Trace:
00:04:41             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2()
```

**Comment by stephentoub** [comment] 2016-02-02 00:59
Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/357/console
```
15:50:42    System.Reflection.CoreCLR.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 1.075s
15:50:45    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2 [FAIL]
15:50:45       Yaw:505 Pitch:-615 Roll:-440
15:50:45       Expected: True
15:50:45       Actual:   False
15:50:45       Stack Trace:
15:50:45             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateFromYawPitchRollTest2()
```

**Comment by stephentoub** [comment] 2016-02-02 01:00
@mellinoe, this test is failing frequently enough, I suggest it be disabled on OS X until the root cause can be determined.

**Comment by stephentoub** [comment] 2016-06-05 23:20
These tests were re-enabled. Closing the issue.

**Comment by danmosemsft** [comment] 2016-11-02 22:40
This is being worked on in https://github.com/dotnet/coreclr/issues/2266

**Closed** 2016-11-18 13:13 UTC
Labels: area-System.Numerics, os-mac-os-x, test bug, test-run-core, tracking-external-issue
