### ISSUE TITLE
Failure in System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16430] opened 2017-02-24 04:30 UTC
```
Stacktrace

MESSAGE:
Timed out after 60000ms waiting for remote process 7172\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in D:\j\workspace\outerloop_win---097a300f\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 176 at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest() in D:\j\workspace\outerloop_win---097a300f\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs:line 95
```

**Comment by Jiayili1** [comment] 2017-02-24 08:09
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/103/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ExecuteNonQueryErrorTest/

**Comment by danmosemsft** [comment] 2017-02-24 17:38
@saurabh500 not sure how we can make this more diagnosable. Logging maybe?

**Comment by stephentoub** [comment] 2017-02-24 17:54
This is the same as https://github.com/dotnet/corefx/issues/16421

**Comment by saurabh500** [comment] 2017-02-24 18:14
@danmosemsft I left some suggestions in #16421

**Comment by Jiayili1** [comment] 2017-03-02 08:02
This issue is repro here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/109/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

**Comment by Jiayili1** [comment] 2017-03-02 08:05
This issue also repro here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/115/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ConnectionOpenTest/

**Comment by saurabh500** [comment] 2017-03-02 16:06
@stephentoub @danmosemsft The logs show that the server did not crash and it responded to the login request on time. Also the SqlConnection Open happened successfully.

**Comment by stephentoub** [comment] 2017-03-02 16:11
> Also the SqlConnection Open happened successfully.

Does it show anything about the subsequent operation against the server, though?  In that other case we saw, there was a timeout coming from the Execute operation, and if the Execute operation is timing out here, it could be the same underlying problem, just a different symptom.

**Comment by saurabh500** [comment] 2017-03-02 16:13
There is a confusion here. I left the comment above for the Connection Open Test for which @Jiayili1 reported a failure link in this issue. We should take the discussion to #16421  where the server starts and the connection is opened to the server. That's where the logs were added

**Comment by stephentoub** [comment] 2017-03-02 16:15
I believe they're the same issue.

**Comment by saurabh500** [comment] 2017-03-02 16:16
Why?

**Comment by saurabh500** [comment] 2017-03-02 16:18
For ExecuteNonQueryErrorTest  there Query Execution and an expectation of an error apart from just the connection being opened. ConnectionOpenTest is a subset of the operations in ExecuteNonQueryTest.

There is a possibility that the underlying problem is the same, in which case it better to figure out what's going wrong with ConnectionOpenTest because it has lesser moving parts.

**Comment by stephentoub** [comment] 2017-03-02 16:20
I should say I suspect they're the same issue.  My guess is that there's a problem / race condition / etc. that's causing the client to miss responses from the server, or something like that, such that it ends up hanging waiting for a response that either has already come and it missed or will never come, or something like that.  I of course could be wrong.

**Comment by saurabh500** [comment] 2017-03-02 16:23
Let's continue this discussion on #16421

**Comment by saurabh500** [comment] 2017-03-02 16:29
@Jiayili1 
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/109/testReport/System.Net.Http.Functional.Tests/DiagnosticsTest/SendAsync_ExpectedDiagnosticCancelledLogging/

The failure at the link above is not related to this particular test. Can you open a different issue for it?

**Comment by danmosemsft** [comment] 2017-03-02 17:11
I broke it out and deleted @Jiayili1 's comment to avoid confusion

**Comment by karelz** [comment] 2017-03-02 17:26
@Jiayili1 please don't use 2 area labels on issues in future. It confuses the ownership and who should take a look. Thanks!

**Comment by Jiayili1** [comment] 2017-03-03 01:10
@karelz Thanks for reminding me, I got it.

**Comment by karelz** [comment] 2017-03-03 01:47
Great, thanks! Mistakes happen ... (also to me ;-))

**Comment by joperezr** [comment] 2017-03-03 18:05
one more hit: https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/4119/

**Comment by danmosemsft** [comment] 2017-03-08 00:02
Failed again today -- @saurabh500 would it make sense to disable it while you investigate? @Jiayili1 can make that change if you like.

**Comment by saurabh500** [comment] 2017-03-08 00:06
@danmosemsft I dont think I can debug it without the kind of workload that the CI is running. 
I haven't gotten to adding more logging. I should be able to do it by EOD or tomorrow. 

Can you provide the link for today's failure?

**Comment by danmosemsft** [comment] 2017-03-08 01:14
Sure @saurabh500 
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/consoleText

```
  TestCase:ReadElementContentAsBinHex - CharCheckingReader
     System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest [FAIL]
        Timed out after 60000ms waiting for remote process 2952
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\outerloop_win---bf7c4efa\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs(176,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           D:\j\workspace\outerloop_win---bf7c4efa\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs(95,0): at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest()
```

If it requires the full run to repro, it makes total sense to keep it enabled in CI while you do logging etc.

**Comment by saurabh500** [comment] 2017-03-08 02:26
PR with more logging https://github.com/dotnet/corefx/pull/16845

**Comment by danmosemsft** [comment] 2017-03-08 06:01
@Jiayili1 this test now has more logging -- next time you see it failing, please grab all relevant parts of the log and paste the link to the log here.

**Comment by Jiayili1** [comment] 2017-03-08 06:13
@danmosemsft OK, I got it.

**Comment by Jiayili1** [comment] 2017-03-08 06:42
Failed again on OuterLoop_Windows8.1_debug ([build#124](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/testReport/))

Message:
~~~
Timed out after 60000ms waiting for remote process 2952\r\nExpected: True\r\nActual: False
~~~

Stack Trace:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in D:\j\workspace\outerloop_win---bf7c4efa\src\Common\tests\System\Diagnostics\RemoteExecutorTestBase.cs:line 176 at System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs:line 95
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/consoleText

**Comment by saurabh500** [comment] 2017-03-08 07:00
this failure is from the morning of 3/7
The test runs show TDS logs being recorded from `[3/7/2017 10:55:24 AM]`
The build timestamp is Build #124 (Mar 7, 2017 10:43:11 AM)

This run doesn't have the logging changes. They were merged during the PM of 3/7

**Comment by danmosemsft** [comment] 2017-03-14 16:07
@Jiayili1 any more hits?

**Comment by stephentoub** [comment] 2017-03-14 16:10
(I'm hopeful #16903 fixed this.)

**Comment by danmosemsft** [comment] 2017-03-14 16:20
In that case, I'm happy to close this and we'll reopen if it occurs again. @saurabh500

**Comment by CIPop** [comment] 2017-06-15 22:57
I've seen this in https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/ubuntu14.04_release_prtest/264/consoleFull#6029473722d31e50d-1517-49fc-92b3-2ca637122019 while testing innerloop for #21100:

```
     System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryErrorTest [FAIL]
13:26:46         Assert.Equal() Failure
13:26:46         Expected: 42
13:26:46         Actual:   134
13:26:46         Stack Trace:
13:26:46            /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(208,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
13:26:46   Test: ExecuteReaderTest Enabled Listeners

At least part of the error log:

13:26:43   Exception from RemoteExecutorConsoleApp(System.Data.SqlClient.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, System.Data.SqlClient.Tests.DiagnosticTest+<>c, <ExecuteNonQueryErrorTest>b__6_0):
13:26:43   Assembly: System.Data.SqlClient.Tests, Version=4.2.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
13:26:43   Type: System.Data.SqlClient.Tests.DiagnosticTest+<>c
13:26:43   Method: Int32 <ExecuteNonQueryErrorTest>b__6_0()

13:26:44   Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
13:26:44      at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs:line 373
13:26:44         Connection Strings Not Setup
13:26:44      at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionFactory.cs:line 136
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSqlCommandExecuteScalarThrowsPlatformNotSupportedException [SKIP]
13:26:44   Running tests... Start time: 20:26:44
13:26:44   Commands:
13:26:44   source Dumpling.sh
13:26:44   chmod +x /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/bin/testhost/netcoreapp-Linux-Release-x64//dotnet
13:26:44   /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/bin/testhost/netcoreapp-Linux-Release-x64//dotnet xunit.console.netcore.exe System.ComponentModel.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
13:26:44   CollectDumps 0 System.ComponentModel.Tests
13:26:44   /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/bin/AnyOS.AnyCPU.Release/System.ComponentModel.Tests/netstandard /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.ComponentModel/tests
13:26:44   executing ulimit -c unlimited
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSqlDataReaderGetStreamSequentialAccess [SKIP]
13:26:44      at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 114
13:26:44         Connection Strings Not Setup
13:26:44      at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 476
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSqlDataReaderGetBytes [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSchemaMetadata [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 1187
13:26:44      at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 792
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.XmlTest [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSqlDataReaderGetSqlBytesSequentialAccess [SKIP]
13:26:44      at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs:line 711
13:26:44      at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 281
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDDataTypesTest.TestUdtSqlDataReaderGetStream [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.DDMARSTest.TestMain [SKIP]
13:26:44      at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionInternal.cs:line 453
13:26:44         Connection Strings Not Setup
13:26:44      at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 1062
13:26:44      at System.Data.SqlClient.SqlConnection.Open() in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnection.cs:line 598
13:26:44      System.Data.SqlClient.ManualTesting.Tests.MultipleResultsTest.TestMain [SKIP]
13:26:44      at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryErrorTest>b__6_1(String connectionString) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 114
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.ReaderTest.TestMain [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.AsyncTest.ExecuteTest [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.AsyncTest.FailureTest [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44      at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnostics(Action`1 sqlOperation, Boolean enableServerLogging, String methodName) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 705
13:26:44      at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryErrorTest>b__6_0() in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs:line 130
13:26:44      --- End of inner exception stack trace ---
13:26:44      System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.PlainMARSCancelTest [SKIP]
13:26:44      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
13:26:44      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
13:26:44      at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_corefx/release_2.0.0/ubuntu14.04_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 51
13:26:44         Connection Strings Not Setup
13:26:44      System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.PlainCancelTest [SKIP]
13:26:44         Connection Strings Not Setup
13:26:44   
13:26:44   Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

```

**Comment by danmosemsft** [comment] 2017-06-16 03:28
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/ubuntu14.04_release_prtest/275/consoleText

**Comment by Petermarcu** [comment] 2017-06-29 23:54
I see some fixes merged. Is this still an issue in 2.0.0? Are we on track to address it and does it meet the bar at this point?

**Comment by danmosemsft** [comment] 2017-06-30 16:36
@saurabh500 I moved this out as there's never been evidence it's more than a test issue.

**Comment by Jiayili1** [comment] 2017-08-09 08:03
Another test failed with same issue: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug/3976/testReport/System.Data.SqlClient.Tests/DiagnosticTest/ExecuteXmlReaderErrorTest/

Failed test: System.Data.SqlClient.Tests.DiagnosticTest.ExecuteXmlReaderErrorTest

**Comment by Jiayili1** [comment] 2017-08-21 06:06
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170821.01/workItem/System.Data.SqlClient.Tests/wilogs

~~~
2017-08-20 21:00:22,695: INFO: proc(54): run_and_log_output: Output:    System.Data.SqlClient.Tests.DiagnosticTest.ExecuteReaderErrorTest [FAIL]
2017-08-20 21:00:22,696: INFO: proc(54): run_and_log_output: Output:       Timed out after 60000ms waiting for remote process 24488
2017-08-20 21:00:22,696: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-08-20 21:00:22,697: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-08-20 21:00:22,700: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-08-20 21:00:22,713: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/30/s/corefx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(161,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
2017-08-20 21:00:22,792: INFO: proc(54): run_and_log_output: Output: Test: ExecuteScalarAsyncErrorTest Enabled Listeners
2017-08-20 21:00:22,986: INFO: proc(54): run_and_log_output: Output: TDSServerEndPoint ExecuteScalarAsyncErrorTest Is Server Socket Bound: True Testing connectivity to the endpoint created for the server.
2017-08-20 21:01:22,767: INFO: proc(54): run_and_log_output: Output:    System.Data.SqlClient.Tests.DiagnosticTest.ExecuteScalarAsyncErrorTest [FAIL]
2017-08-20 21:01:22,767: INFO: proc(54): run_and_log_output: Output:       Timed out after 60000ms waiting for remote process 24498
2017-08-20 21:01:22,767: INFO: proc(54): run_and_log_output: Output:       Expected: True
2017-08-20 21:01:22,767: INFO: proc(54): run_and_log_output: Output:       Actual:   False
2017-08-20 21:01:22,767: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-08-20 21:01:22,768: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/30/s/corefx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(161,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
~~~

**Comment by saurabh500** [comment] 2018-01-30 18:11
These failures were due to a timeout caused by resource starvation, particularly threads while opening a connection to SqlServer. The Connection.Open() was changed by @geleems to take care of this issue.

**Closed by saurabh500** 2018-01-30 18:11 UTC
Labels: area-System.Data.SqlClient, test-run-core
