### ISSUE TITLE
HttpClient is not able to send Client certificate unless the cert is in Windows Cert Store

### ISSUE THREAD

**Issue by softwaretecture** [dotnet/corefx#24211] opened 2017-09-22 14:06 UTC
HttpClient is using HttpClientHandler  to attach a client certificate to the request sent to a server.
The certificate isn't being attached when ClientCertificateOptions is set to `Manual` mode and the client cert is not in the Windows Certificate Store. I looked through the code in GitHub and it looks that the provided client cert is always being verified for WinRT against a "MY" local windows cert store.
The call is made to https://github.com/dotnet/corefx/blob/472b8d8ec212c2afb107dea305b4624c4989a79f/src/Common/src/System/Net/Security/CertificateHelper.Uap.cs 
line 35 in from this code https://github.com/dotnet/corefx/blob/f7bc8b413406e94549f21be79e67641f11ae8266/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs

Please see the sample code below:

`using System;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace CertClient
{
    public class Program
    {
        private static async Task Main(string[] args)
        {
            var result = await GetSecureApiResultsAsync();
            Console.WriteLine(result);
            Console.WriteLine("Press any key to continue...");
            Console.ReadKey();
        }

        public static async Task<string> GetSecureApiResultsAsync()
        {
            //create an HttpClient handler
            using (var handler = new HttpClientHandler())
            {
                //we need to configure the handler with client certificate. 
                //This is where it gets interesting

                //set client certificate to manual mode so we can provide a client certificate we want.
                handler.ClientCertificateOptions = ClientCertificateOption.Manual;

                //NOTE: this is a gotcha of the Microsoft implementation requiring client certs to be stored in a cert store.
                var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                store.Open(OpenFlags.ReadOnly);
                //for some reason the cert collection .Find(...) method can't find a cert by thumprint so we created our own.
                var clientCert = FindCert(store, "5162b416b44f854e2571ffa86d4430dcdb83d723");
                store.Dispose();

                //add the cert to the handler
                handler.ClientCertificates.Add(clientCert);

                //create an HttpClient and pass a handler to it
                using (var httpClient = new HttpClient(handler))
                {
                    //make an API call
                    return await httpClient.GetStringAsync(@"https://localhost:4430/api/values");
                }
            }
        }

        private static X509Certificate2 FindCert(X509Store store, string thumbprint)
        {
            foreach (var cert in store.Certificates)
                if (cert.Thumbprint.Equals(thumbprint,
                    StringComparison.CurrentCultureIgnoreCase))
                    return cert;
            return null;
        }
    }
}`

**Comment by fletchsod-developer** [comment] 2017-09-22 15:29
Are you saying the certificate couldn't be obtain from the certificate store?

We're using Azure's KeyVault and we didn't have any issues with Client Certificate attachment using HttpClientHandler and assigning it to HttpClient.  It works as good when executing the code.

Window Platform issues?

Code below

            var x509Certificate2 = new X509Certificate2();  // Replace this class instantation with actual X509Certificate2 data form Azure's KeyVault.

            var httpClientHandler = new HttpClientHandler() {
                SslProtocols = SslProtocols.Tls12,
                AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip,
                ClientCertificateOptions = ClientCertificateOption.Manual
            };
            httpClientHandler.ClientCertificates.Add(x509Certificate2);

            using (var httpClient = new HttpClient(httpClientHandler))  // TODO: Use BackChannelFactory
            {
            }

**Comment by davidsh** [comment] 2017-09-22 16:28
This is, unfortunately, a current limitation of the UWP HttpClient.  It is caused by an interop issue between converting .NET certificates (which have private key) into WinRT certificates.

cc: @bartonjs

**Comment by davidsh** [comment] 2017-09-22 16:32
You can see the explanation in the code comments you linked:

```c#
// There are currently only two ways to convert a .NET X509Certificate2 object into a WinRT Certificate without
        // losing its private keys, each with its own limitations:
        //
        // (1) Using the X509Certificate2.Export method with PKCS12/PFX to obtain a byte[] representation (including private
        //     keys) that can then be passed into the IBuffer-based WinRT Certificate constructor. Unfortunately, the
        //     X509Certificate2.Export operation will only succeed if the app-provided X509Certificate2 object was created
        //     with the non-default X509KeyStorageFlags.Exportable flag.
        //
        // (2) Going through the certificate store. That is, retrieving the certificate represented by the X509Certificate2
        //     object as a WinRT Certificate via WinRT CertificateStores APIs. Of course, this requires the certificate to
        //     have been added to a certificate store in the first place.
        //
        // Furthermore, WinRT WebSockets only support certificates that have been added to the personal certificate store
        // (i.e., "MY" store) due to other WinRT-specific private key limitations. With that in mind, approach (2) is the
        // most appropriate for our needs, as it guarantees that WinRT WebSockets will be able to handle the resulting
        // WinRT Certificate during ConnectAsync.
```

**Comment by softwaretecture** [comment] 2017-09-22 16:59
@fletchsod-developer: I don't see how this works, unless the app runs in Azure and different code is executed? Based on the implication I see in GitHub, the code always wants to compare the cert provided with a cert from "MY" store. 

@davidsh: Also, does this mean there is no support on Linux for this currently? Trying to deploy this to a Linux Docker container. Thanks for the feedback.

**Comment by davidsh** [comment] 2017-09-22 17:03
>@davidsh: Also, does this mean there is no support on Linux for this currently?

The behavior and code you referenced above is only for the Windows UWP HttpClient.

Linux uses a different implementation.  Have you tried your code on Linux?  HttpClientHandler.ClientCertificates property is implemented on Linux in latest .NET Core.

cc: @stephentoub

**Comment by softwaretecture** [comment] 2017-09-22 17:06
I have not. I was trying to make it work on Windows 10 first. I've created this post with a sample on how to do it as I couldn't find a complete example anywhere: https://softwaretecture.wordpress.com/

Is there a Linux implementation of HttpClientHandler.ClientCertificates that I'm not seeing in GitHub?

**Comment by davidsh** [comment] 2017-09-22 17:11
>I have not. I was trying to make it work on Windows 10 first.

The behavior you observed is for Windows 10 UWP.  But for Windows 10 non-UWP, there is no WinRT involved and it has no restrictions.

Linux is implemented.
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L266

**Comment by softwaretecture** [comment] 2017-09-22 17:18
@davidsh Thank you!

**Comment by softwaretecture** [comment] 2017-09-22 17:25
@fletchsod-developer is it possible that you're running on Windows non UWP and that's why it works for you based on @davidsh explanation?

**Comment by fletchsod-developer** [comment] 2017-09-22 18:16
No idea if my workstation have UWP installed or not.  Nor do I know of that on Azure cloud servers.

**Comment by davidsh** [comment] 2017-09-22 18:29
>No idea if my workstation have UWP installed or not.

The UWP (UAP) version of HttpClient is only used if you are building and running a Windows Store App.  If you are not doing that, then you are not using that implementation.  It sounds like you are not running a Windows Store app.  Rather, you are building some other type of application/service.

**Comment by softwaretecture** [comment] 2017-09-22 18:35
That's interesting cause I don't see any specific project configuration that says I'm building for WinRT. It's just a Console Application.

**Comment by davidsh** [comment] 2017-09-22 18:41
>That's interesting cause I don't see any specific project configuration that says I'm building for WinRT. It's just a Console Application.

If you're building a console app, then it's not a UWP (Windows Store App).  That means that this code is not used:
https://github.com/dotnet/corefx/blob/f7bc8b413406e94549f21be79e67641f11ae8266/src/System.Net.Http/src/uap/System/Net/HttpClientHandler.cs.

Only UWP apps use core from the src/uap/System/Net folder.

**Comment by softwaretecture** [comment] 2017-09-22 18:43
but without the cert in the store, the cert isn't being attached to the request. That's what I have observed, which is why I started digging through the MS code.

**Comment by fletchsod-developer** [comment] 2017-09-22 18:44
Ah!  I'm not using Windows Store on this one.

**Comment by softwaretecture** [comment] 2017-09-22 18:48
internal static partial class CertificateHelper has a bunch of partial classes that all seem to look for certs in the MY store. Am I missing something here? I could not make it work without placing the cert in the store.

**Comment by davidsh** [comment] 2017-09-22 19:01
Please attach a full repro (Visual Studio solution).  

Your code above i looking for a cert in the MY store and using that to set the .ClientCertificates property of HttpClientHandler.  Is that not working?

If you're trying to pass in a cert that is not in the MY store, (perhaps from a PFX file), please attach that repro.  Please note that the cert must have private key attached in order to be eligible to be sent on the wire during TLS handshake for client auth.

**Comment by softwaretecture** [comment] 2017-09-22 20:31
Based on the information provided here, I was able to make it work with just passing the certificate file "pfx" which was created with a private key like this:

makecert -r -n "CN=testCert" -pe -sv c:\temp\certPrivate.pvk c:\temp\certPublic.cer
pvk2pfx.exe -pvk c:\temp\certPrivate.pvk -spc c:\temp\certPublic.cer -pfx C:\temp\testCert.pfx -pi test

I was not including the private key in the PFX file before and the code failed. Maybe we could use some improvements on the errors and messages here. By adding the cert into the cert store resolved the issue without having the private key exported. 
Thanks everyone for their help!

**Comment by davidsh** [comment] 2017-09-23 00:58
Closing this issue since since the question was answered.

**Closed by davidsh** 2017-09-23 00:58 UTC
Labels: area-System.Net.Http
