### ISSUE TITLE
resx with (text) files doesn't return file content

### ISSUE THREAD

**Issue by Roraa** [dotnet/corefx#8200] opened 2016-04-30 14:01 UTC
When using a resx file which contains SQL files, the following code: "ResourceManager.GetString("a", resourceCulture)" returns 

> a.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8

Instead of returning the file content.

**Comment by ramarag** [comment] 2016-05-02 19:24
@Roraa can you please provide a working repro ?

**Comment by Roraa** [comment] 2016-05-03 19:10
Sure, [ResxTestConsoleApp.zip](https://github.com/dotnet/corefx/files/247562/ResxTestConsoleApp.zip)

**Comment by gkhanna79** [comment] 2016-05-09 14:29
@ramarag PTAL at this today and update the thread.

**Comment by gkhanna79** [comment] 2016-05-11 15:53
Based upon @ramarag investigation, this appears to be broken for XProj scenarios. @barrytang I am assigning this to you for rerouting as applicable.

**Comment by joshfree** [comment] 2016-05-25 00:14
@barrytang what is the right location to track this?

**Comment by joshfree** [comment] 2016-06-01 18:12
@barrytang can you give an update?

**Comment by joshfree** [comment] 2016-06-02 01:25
Closing this as it's being tracked in an external bug repo and there's been no action or update here for 3 weeks that requires action from corefx.  @barrytang feel free to reactivate if there is an issue here on the corefx side

**Comment by BillHiebert** [comment] 2016-06-20 22:39
This looks like a compilation/dotnet core issue. I verified the generated .designer.cs file is identical to the one that is generated in a csproj resx file (where this works). 
```
        public static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
```

The resx file contains the following:
```
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="TextFile" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>textfile.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
  </data>
```
However, when I run the same code which just calls Resource.TestResourceRsx.TexttFile it is returns the following string: 

`"Resx file content: textfile.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8"`

**Comment by gkhanna79** [comment] 2016-06-20 22:49
According to https://msdn.microsoft.com/en-us/library/system.resources.resxfileref(v=vs.110).aspx, ResXFileRef is part of WinForms and is what performs the I/O to return actual content to ResourceManager.

Is this scenario even supported given that WinForms is not supported by .NET Core? @tarekgh Thoughts?

**Comment by gkhanna79** [comment] 2016-06-21 01:37
Thanks @tarekgh. 

> as indicated before in this thread, looks the issue is with the xproj.

By this, do you mean the XProj infrastructure and the way it is embedded resources in assemblies? Or something else?

**Comment by gkhanna79** [comment] 2016-06-21 15:40
@tarekgh Can you please share more details on the XProj aspect?

@BillHiebert Did you try with XProj where @tarekgh confirmed this to be an issue?

**Comment by tarekgh** [comment] 2016-06-21 16:13
@gkhanna79 

When compiling as csproj, I am seeing the msbuild target CoreResGen get invoked which will invoke the msbuild task "GenerateResource". this task will convert the .resx file to .resources file this include reading TextFile.txt and getting its contents and embed this content into the .resources file. and that is why is working fine with csproj. 

when loading the attached xproj in VS and compiling it, I am seeing the following:

```
1>Target "CoreResGen: (TargetId:37)" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets" from project "F:\Temp\RemoveIt\remove\src\ResxTestConsoleApp\ResxTestConsoleApp.xproj" (target "ResGen" depends on it):
1>                   Set Property: GenerateResourceMSBuildArchitecture=CurrentArchitecture
1>                   Set Property: ResgenToolPath=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\
1>                   Set Property: GenerateResourceMSBuildRuntime=CurrentRuntime
1>                   Task "GenerateResource" skipped, due to false condition; ('%(EmbeddedResource.Type)' == 'Resx' and '%(EmbeddedResource.GenerateResource)' != 'false' and '$(GenerateResourceMSBuildRuntime)' != 'CLR2') was evaluated as ('' == 'Resx' and '' != 'false' and 'CurrentRuntime' != 'CLR2').
1>                   Task "GenerateResource" skipped, due to false condition; ('%(EmbeddedResource.Type)' == 'Resx' and '%(EmbeddedResource.GenerateResource)' != 'false' and '$(GenerateResourceMSBuildRuntime)' == 'CLR2') was evaluated as ('' == 'Resx' and '' != 'false' and 'CurrentRuntime' == 'CLR2').
1>09:03:18.151     1>
1>Done building target "CoreResGen" in project "ResxTestConsoleApp.xproj".: (TargetId:37)
```

which show the GenerateResource task is skipped. so someone familiar with building xproj need to take a look and figure out why this is happening.

**Comment by gkhanna79** [comment] 2016-06-21 16:28
@barrytang @BillHiebert Based upon details @tarekgh shared above, can you please look into CoreResGen task/xProj infrastructure?

**Comment by BillHiebert** [comment] 2016-06-21 16:38
@gkhanna79 @tarekgh. This all has to work from the command line so the CoreResGen task does not come into play and is purposely not run by Xproj. dotnet build needs to handle this scenario.

**Comment by gkhanna79** [comment] 2016-06-21 16:45
> dotnet build needs to handle this scenario.

I do not have context on build. @BillHiebert Have you chatted with @piotrpMSFT with regards to feature parity expected between CSProj build and dotnet build that you are alluding to?

**Comment by gkhanna79** [comment] 2016-06-21 17:22
Just for context, resgen support for each language is delivered by the language compiler. For example C# work is tracked at https://github.com/dotnet/cli/issues/819.

**Comment by DamianEdwards** [comment] 2016-06-21 18:23
Some extra background here, this was never supported in DNX or .NET Core in the previous preview releases. The RESX file designer in Visual Studio for xproj projects should **not** be allowing the addition of non-string resources (as the .NET Core `ResourceManager` APIs don't support retrieving anything but embedded strings, this is how it behaved in Silverlight & PCL class library projects). This is complicated slightly by xproj's facility to cross-compile to multiple target frameworks which was never really addressed (i.e. the designer would have to support different embedded resource types depending on the target frameworks).

**Comment by tarekgh** [comment] 2016-06-21 19:15
> The RESX file designer in Visual Studio for xproj projects should not be allowing the addition of non-string resources (as the .NET Core  ResourceManager  APIs don't support retrieving anything but embedded strings, this is how it behaved in Silverlight & PCL class library projects). 

To clarify the case here still a string resources. when referencing the text file in the resx file, it is similar as getting the text file content as a string and use it in the resources. 

```
<value>textfile.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
```

note that it is saying ```System.String```

**Comment by DamianEdwards** [comment] 2016-06-21 19:37
@tarekgh yeah the consumption API is the same I see, however the behavior of extracting the text of the file and embedding that was a behavior of ResGen in .NET Framework which was never replicated for the Roslyn-based compile in DNX or .NET CLI.

**Comment by joshfree** [comment] 2016-06-24 20:19
Moving this bug to the CLI repo @ https://github.com/dotnet/cli/issues/3695

**Closed by joshfree** 2016-06-24 20:19 UTC
Labels: System.Resources, tracking-external-issue
