### ISSUE TITLE
All corefx Ubuntu and OS X builds failing with OOMs and aborts

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5943] opened 2016-02-06 15:17 UTC
A recent change in coreclr is causing all of these builds to fail non-deterministically with OOMs and/or aborts.  @jkotas is investigating...

**Comment by jkotas** [comment] 2016-02-06 15:49
These failures were triggered by turning on NGen on Unix. The attempt to load NGen image fails with OOM intermittently on some machines/OSes. It never repros under debugger. I am adding temporary instrumentation to help us to trace this down #3062

cc @gkhanna79 @JohnChen0 @piotrpMSFT

**Comment by stephentoub** [comment] 2016-02-06 16:22
Thanks, @jkotas. In the meantime, can we disable NGen on unix, at least for our CI builds?

**Comment by jkotas** [comment] 2016-02-06 16:33
Yes, it would make sense. I am not able to figure out how it is turned on corefx - as far as I can tell the script to copy over coreclr is excluding native images for some reason already: https://github.com/dotnet/corefx/blob/master/netci.groovy#L250.

**Comment by gkhanna79** [comment] 2016-02-06 16:41
@weshaggard @stephentoub Is CoreFX consuming CoreCLR from ProjectKRel instead of ProjectK? If so, @ellismg can you please confirm that the PR (https://github.com/dotnet/coreclr/pull/2901) had its changes merged into ProjectKRel?

**Comment by gkhanna79** [comment] 2016-02-06 16:41
CC @davidfowl

**Comment by stephentoub** [comment] 2016-02-06 17:00
> excluding native images for some reason already

@ellismg, do you remember why we do this?

> as far as I can tell the script to copy over coreclr is excluding native images

It's using ``**/*.ni.dll```, and if I remember correctly that ``**`` syntax requires turning on the globstar setting in the shell... @mmitche, is it possible that setting (i.e. ```shopt -s globstar```) isn't enabled for Ubuntu and OS X in the lab?

**Comment by stephentoub** [comment] 2016-02-06 17:22
>  Is CoreFX consuming CoreCLR from ProjectKRel instead of ProjectK?

For Unix, neither... we pull the latest successful release build from the Jenkins build of the coreclr repo.

**Comment by ellismg** [comment] 2016-02-06 20:15
We excluded native images because before we had NIs on Linux we'd sometimes pick the Windows version (this was common when we'd start with the Windows runtime from packages and then stomp over it with Linux versions, we needed to either delete mscorlib.ni.dll or never copy it over).

There is probably similar logic in run-test.sh that we should clean up.

**Comment by ellismg** [comment] 2016-02-06 20:35
> Yes, it would make sense. I am not able to figure out how it is turned on corefx - as far as I can tell the script to copy over coreclr is excluding native images for some reason already:

Also, [we delete mscorlib.ni.dll before running the tests](https://github.com/dotnet/corefx/blob/master/run-test.sh#L169) with run-test.sh, so even if it was getting copied over, it should be removed?

**Comment by jkotas** [comment] 2016-02-07 00:37
It turns out that the corefx failures have different root cause, not related to native images....

**Comment by jkotas** [comment] 2016-02-07 00:41
@stephentoub Does the corefx CI run fine with live coreclr builds now?

**Comment by stephentoub** [comment] 2016-02-07 00:54
Earlier today I locked our PR builds to use an older coreclr. Let me undo it and see if things continue to work (but I'm hopeful they will, as I didn't touch the main builds and those seem to be working, too.)

**Comment by stephentoub** [comment] 2016-02-07 20:34
> Does the corefx CI run fine with live coreclr builds now?

Seems to be mostly fixed.  We are still seeing a sporadic failure on OS X in the PLINQ tests that we didn't previously see:
```
03:33:12 ./run-test.sh: line 130: 57376 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
03:33:12 error: One or more tests failed while running tests from 'System.Linq.Parallel.Tests'.  Exit code 134.
```
May be unrelated.  I've not reproed it locally yet.

**Comment by jkotas** [comment] 2016-02-07 20:52
Thanks for checking ... let's open a new issue on the PLinq test failure if necessary.

**Closed** 2016-02-07 20:52 UTC
Labels: bug
