### ISSUE TITLE
WebProxy uses pascal case for parameter names 

### ISSUE THREAD

**Issue by coolcsh** [dotnet/corefx#29506] opened 2018-05-04 02:59 UTC
I am using version 4.3.3 of System.Net.Http package. When I tried to setup proxy for HttpClient I noticed that WebProxy class uses pascal case for constructor parameter names. For example see line:
corefx/src/System.Net.WebProxy/src/System/Net/WebProxy.cs
Line 22 in 8cb7675
public WebProxy(Uri Address, bool BypassOnLocal) : this(Address, BypassOnLocal, null, null) { }
This is against .NET coding conventions which states that parameter names should be written in camel case. It would be great to fix this, but of course I am aware that this is a breaking change and may cause code to stop compiling when someone used explicit parameter names in their code like:
var proxyHttpClientHandler = new HttpClientHandler {
// notice explicit parameter name 'BypassOnLocal'
Proxy = new WebProxy(new Uri("http://localhost:5555/"), BypassOnLocal: false),
UseProxy = true,
};
Still I believe that this should be fixes ASAP even if it causes inconveniences for some people, it would be a better decision in the long run

**Comment by davidsh** [comment] 2018-05-04 03:41
Duplicate of #29476

**Closed by davidsh** 2018-05-04 03:41 UTC
Labels: area-System.Net
