### ISSUE TITLE
Improve layout of bin\tests directory

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#1598] opened 2015-04-30 19:48 UTC
Building and running all CoreFx tests creates bin\tests directory with an insane amount of files (14493 files of total size 1.4GB). The problem is that every CoreFx library deploys its own copy of DNX and XUnit (175 files) to its test directory. Instead all tests should be deployed into a single directory with a single copy of DNX.

**Comment by Maxwe11** [comment] 2015-04-30 21:01
:+1:

**Comment by eatdrinksleepcode** [comment] 2015-04-30 21:35
I don't think the solution is quite that simple, but I do believe we should make an effort to improve this situation.

**Comment by krwq** [comment] 2015-05-01 06:33
I 100% agree although heard different opinions on that. cc: @weshaggard

**Comment by weshaggard** [comment] 2015-05-01 06:43
I do think we should look at options to improve this but we cannot run all the tests from the same directory as there are too many conflicting dependencies between the different tests. Not all tests projects depend on the latest version of all the libraries, which is by design as we plan to be able to ship each library independently.

**Comment by tmat** [comment] 2015-05-01 15:17
Hard-linking sounds like a hack. Why doe the tests and their deps need to be in the same directory as DNX anyways? Couldn't the test driver run from one directory and load tests and their deps from a different one?

**Comment by krwq** [comment] 2015-05-01 23:09
Why can't we just publish a package(s) with all version of the contracts and build against them and then run against the bits from the local repo. This way we can reference lower version but run against whatever we build in the repo. All contracts in all versions are probably at most few megabytes which is still gonna be a lot less than what we already have.

**Comment by weshaggard** [comment] 2015-05-02 00:25
Both very good questions. 

@tmat first DNX isn't actually being used to run our tests we are using our own corerun host and the dependent xunit libraries. Regardless the issue is that the host and xunit use various versions of our libraries themselves but we need the versions that the test depend on and not the versions that our test infrastructure depends on. There are definitely conflicts that happen between the two which was the biggest reason we started isolating the tests and ensuring we copy the test versions over top of the infrastructure versions.

@krwq for libraries that declare a dependency on a specific version of a package we want to make sure that they are actually running on that version as well and not the latest versions from the repo. Otherwise we cannot guarantee that they actually work on the potentially different older versions of the dependent packages. There are times were we will want to run the tests against all the latest versions but that should not be the default case in a world where we want to ship our libraries with specific versions of dependencies.

**Comment by tmat** [comment] 2015-05-02 00:40
@weshaggard Other than System.Runtime, is it not possible to use LKG of xunit dependencies for the host and then load the dependencies of the library being tested in a separate load context?

**Comment by weshaggard** [comment] 2015-05-02 00:45
@tmat It might be possible but at a minimal it would require a custom host with a custom load context. I actually don't know how custom load contexts work when exchanging types across different context from different versions of the same assemblies. @jkota is it even possible to load the same assemblies with different versions in different assembly load contexts and then communicate across the different contexts?

**Comment by tmat** [comment] 2015-05-02 00:47
@weshaggard The communication would probably need to be done via primitive types.

**Comment by jkotas** [comment] 2015-05-02 01:01
It should be definitely possible to load different versions of assemblies into different contexts. As @tmat suggested, the communication between different contexts has to be done via shared types - they do not have to necessarily be primitive.

**Comment by weshaggard** [comment] 2017-01-27 22:12
After the recent engineering changes we now use a shared runtime folder for our tests so closing this.

**Closed by weshaggard** 2017-01-27 22:12 UTC
Labels: area-Meta, enhancement, up for grabs
