### ISSUE TITLE
Seg faults on OSX in CI

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7224] opened 2016-03-24 19:04 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_prtest/2884/

```
./run-test.sh: line 135: 85272 Segmentation fault: 11  ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing $OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
error: One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests'.  Exit code 139.
```

**Comment by stephentoub** [comment] 2016-03-24 19:14
We've been seeing these seg faults frequently but inconsistently on OSX in the FileSystemWatcher, PLINQ, and Collections tests.  @sergiy-k and @janvorli are investigating.  It's likely a GC issue.

**Comment by stephentoub** [comment] 2016-03-24 21:05
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2387/console

**Comment by stephentoub** [comment] 2016-03-24 22:53
System.Runtime.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2302/console

**Comment by stephentoub** [comment] 2016-03-25 13:39
System.IO.FileSystem.Watcher.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2412/console

**Comment by stephentoub** [comment] 2016-03-25 22:32
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2428/console

**Comment by stephentoub** [comment] 2016-03-27 21:03
System.Linq.Parallel:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug/1152/

**Comment by stephentoub** [comment] 2016-03-28 03:11
System.Linq.Expressions.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst/946/console

**Comment by stephentoub** [comment] 2016-03-28 03:53
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2472/console

**Comment by stephentoub** [comment] 2016-03-29 04:13
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2489/console

**Comment by stephentoub** [comment] 2016-03-29 15:33
System.Text.Encodings.Web.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2503/console

**Comment by stephentoub** [comment] 2016-03-30 19:30
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2448/console

**Comment by stephentoub** [comment] 2016-03-31 12:23
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2509/console

**Comment by stephentoub** [comment] 2016-04-03 16:26
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2696/console

**Comment by stephentoub** [comment] 2016-04-05 02:36
System.Security.Cryptography.X509Certificates.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst/1048/console

**Comment by stephentoub** [comment] 2016-04-05 02:58
This one is on Ubuntu...
System.Linq.Expressions.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/3659/console

**Comment by stephentoub** [comment] 2016-04-06 11:02
System.Linq.Parallel.Tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2701/console

**Comment by stephentoub** [comment] 2016-04-06 11:39
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2785/console

**Comment by janvorli** [comment] 2016-04-11 19:36
We have discovered that the problem is caused by the brick table corruption. The brick table is an array of short, and the corruption was overwriting the lower byte of an entry by 0xFF. @sergiy-k has then found the culprit. 
There is a loop setting entries in in the`gc_heap::adjust_limit_clr to -1 this way:
```C++
short* x = &brick_table [b];
short* end_x = &brick_table [brick_of (align_on_brick (start + limit_size))];

for (;x < end_x;x++)
    *x = -1;
```
It is expected to write by shorts, but the clang compiler replaces this by memset. On OSX, the memset implementation writes by bytes in some cases (if the size of the block is larger than 32kB - it uses stosb or if the block size is less than 64 bytes and it is setting the remaining number of bytes not divisible by 8 - then it uses byte mov).
On Linux though, the memset implementation never stores by bytes when the size of the block is divisible by 2, which is the case here. When the block size is less than 64 bytes, it first stores by qwords, then the remaining dwords, then the remaining words and finally the remaining byte only if the size was not divisible by 2.
That explains why we have seen the problem on OSX, but not on Linux.
The fix would be to make sure that the loop is not replaced by memset.

**Comment by janvorli** [comment] 2016-04-11 22:45
I have forgotten to add an importand details that this corruption happens when two threads are trying to write to the same brick table entry, one using the clearing loop above and the other using set_brick to set the hint in the brick to a positive value.

**Comment by janvorli** [comment] 2016-04-11 22:46
Fixed by https://github.com/dotnet/coreclr/issues/4266

**Closed by janvorli** 2016-04-11 22:46 UTC
Labels: System.IO
