### ISSUE TITLE
Some System.Memory tests need disabling for UAPAOT

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26256] opened 2018-01-10 18:09 UTC
Seems to be related to overlap.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20180110.02/workItem/System.Memory.Tests

eg 
```
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace :
   at System.SpanTests.ReadOnlySpanTests.Overlap(Int32 x1, Int32 y1, Int32 x2, Int32 y2, Boolean expected) in E:\A\_work\815\s\corefx\src\System.Memory\tests\ReadOnlySpan\Overlaps.cs:line 989
```

@ahsonkhan

**Comment by ahsonkhan** [comment] 2018-01-10 18:46
This looks like a duplicate of https://github.com/dotnet/corefx/issues/25712

Closing. Please re-open if you feel differently.

cc @AtsushiKan, @ektrah, @jkotas

**Closed by ahsonkhan** 2018-01-10 18:46 UTC
Labels: area-System.Memory

**Comment by danmosemsft** [comment] 2018-01-10 19:51
Your call but this is PlatformNotSupportedException and that is ArgumentException ?

**Comment by AtsushiKan** [comment] 2018-01-10 19:56
This is blocking the other one. The toolchain is suddenly not filling in the intrisic for `Unsafe.ByteOffset()`

**Comment by danmosemsft** [comment] 2018-01-10 20:37
OK
