### ISSUE TITLE
SqlClient returns columns with UNIQUE index even if not selected

### ISSUE THREAD

**Issue by bazzilic** [dotnet/corefx#29714] opened 2018-05-15 10:25 UTC
### Steps to Reproduce
1. Create table `T` with columns `a` and `b`
3. Create a `UNIQUE` index on column `a`
2. Run a query `SELECT b FROM T` using `ExecuteReader` from `System.Data.SqlClient`

### Expected Results
Returned `SqlDataReader` only has one column, which is `b`

### Actual Results
Returned `SqlDataReader` has 2 columns: `b` and `a`

### Remarks
The issue is present on both .NET Core 1.1 and 2.0. The code below should illustrate what is happening:

```csharp
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;

class Program
{
    static SqlConnection _sqlConnection;

    static void Main(string[] args)
    {
        var svsb = new SqlConnectionStringBuilder()
        {
            UserID = "sa",
            Password = "Som3pwd",
            DataSource = "localhost",
            InitialCatalog = "master",    // do not run against production SQL Server
            IntegratedSecurity = false
        };

        _sqlConnection = new SqlConnection(svsb.ToString());
        _sqlConnection.Open();

        ExecuteNonQuery("DROP TABLE IF EXISTS T");
        ExecuteNonQuery("CREATE TABLE T ( a INT NOT NULL, b INT )");
        ExecuteNonQuery("INSERT INTO T VALUES (1,2),(3,4)");

        var rd = ExecuteReader("SELECT b FROM T");
        Log(rd);

        ExecuteNonQuery("CREATE UNIQUE INDEX aaa ON T (a)");

        rd = ExecuteReader("SELECT b FROM T");
        Log(rd);
    }

    private static void Log(DbDataReader rd)
    {
        var s = $"DataReader contains {rd.FieldCount} columns: ";
        var names = new List<string>();
        for (var i = 0; i < rd.FieldCount; i++)
            names.Add(rd.GetName(i));
        s += String.Join(", ", names);
        Console.WriteLine(s);
        rd.Close();
    }

    static DbDataReader ExecuteReader(string cmd)
    {
        using (var sqlcmd = new SqlCommand(cmd) { Connection = _sqlConnection })
            return sqlcmd.ExecuteReader(CommandBehavior.KeyInfo);
    }

    static int ExecuteNonQuery(string cmd)
    {
        using (var sqlcmd = new SqlCommand(cmd) { Connection = _sqlConnection })
            return sqlcmd.ExecuteNonQuery();
    }
}
```

Output:
```
DataReader contains 1 columns: b
DataReader contains 2 columns: b, a
```

**Comment by bgribaudo** [comment] 2018-05-16 20:30
This sounds like expected behavior. There are times when hidden columns are expected to be returned when a query is executed. When this occurs, FieldCount is the total field count, including hidden columns. If you're only interested in visible fields (probably the case), try using VisibleFieldCount.

From [DbDataReader.VisibleFieldCount's docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.visiblefieldcount?view=netcore-2.0#remarks):

> This value is used to determine how many fields in the DbDataReader are visible. For example, a SELECT on a partial primary key returns the remaining parts of the key as hidden fields. The hidden fields are always appended behind the visible fields. 

Is VisibleFieldCount returning 1 in both of your example cases?

**Comment by bgribaudo** [comment] 2018-05-17 11:55
That's a great question. I'm assuming you do not have browse mode enabled. With it disabled, I'm not sure the purpose returning the columns.

When browse mode is enabled, the hidden key columns are needed to make client-side functionality work. (If you're curious, [Security Concern: Hidden Resultset Columns](https://bengribaudo.com/blog/2017/10/05/3846/security-concern-hidden-resultset-columns) explains a little more about this behavior.)

**Comment by keeratsingh** [comment] 2018-05-18 20:33
@bazzilic 
Thank you for providing the detailed information, I was able to successfully repro and observe the same behavior as you in both `.Net Core 2.1` and `.Net Framework v4.7.1`
I will investigate further as to if this is expected behavior or not and will update here once I have further comments or questions.

**Comment by keeratsingh** [comment] 2018-06-01 20:51
@bazzilic You are getting the extra information because you are are calling the `SqlCommand.ExecuteReader` method with `CommandBehavior.KeyInfo` argument. The same behavior can be seen with both `Primary Key` and `Unique` constraints as well.

From [CommandBehavior Documentation](https://msdn.microsoft.com/en-us/library/system.data.commandbehavior.aspx)
> KeyInfo | The query returns column and primary key information.


We see from the `GetSchemaTable` output below that `IsKey = True` for column `a`, which makes sense since we defined a `Unique Index` on Column `a`.
 
From [GetSchemaTable documentation](https://msdn.microsoft.com/en-us/library/system.data.datatablereader.getschematable(v=vs.110).aspx):
>  IsKey | true: The column is one of a set of columns that, taken together, uniquely identify the row in the DataTable. The set of columns with IsKey set to true must uniquely identify a row in the DataTable. There is no requirement that this set of columns is a minimal set of columns. This set of columns may be generated from a DataTable **primary key, a unique constraint or a unique index**. 

We can also observe from the `GetSchemaTable` output below `IsHidden = True` for Column `a`, and since you are iterating over [FieldCount](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.fieldcount?view=netcore-2.0) which is the total field count, including hidden columns as correctly pointed out by @bgribaudo above, therefore you see Column `a` in the output as well 

### GetSchemaTable Output
<pre><code>==============================================
ColumnName = b
ColumnOrdinal = 0
ColumnSize = 4
NumericPrecision = 10
NumericScale = 255
IsUnique = False
IsKey = False
BaseServerName =
BaseCatalogName =
BaseColumnName = b
BaseSchemaName =
BaseTableName = T
DataType = System.Int32
AllowDBNull = True
ProviderType = 8
IsAliased = False
IsExpression = False
IsIdentity = False
IsAutoIncrement = False
IsRowVersion = False
IsHidden = False
IsLong = False
IsReadOnly = False
ProviderSpecificDataType = System.Data.SqlTypes.SqlInt32
DataTypeName = int
XmlSchemaCollectionDatabase =
XmlSchemaCollectionOwningSchema =
XmlSchemaCollectionName =
UdtAssemblyQualifiedName =
NonVersionedProviderType = 8
IsColumnSet = False
==============================================
<b>ColumnName = a</b>
ColumnOrdinal = 1
ColumnSize = 4
NumericPrecision = 10
NumericScale = 255
IsUnique = False
<b>IsKey = True</b>
BaseServerName =
BaseCatalogName =
BaseColumnName = a
BaseSchemaName =
BaseTableName = T
DataType = System.Int32
AllowDBNull = False
ProviderType = 8
IsAliased = False
IsExpression = False
IsIdentity = False
IsAutoIncrement = False
IsRowVersion = False
<b>IsHidden = True</b>
IsLong = False
IsReadOnly = False
ProviderSpecificDataType = System.Data.SqlTypes.SqlInt32
DataTypeName = int
XmlSchemaCollectionDatabase =
XmlSchemaCollectionOwningSchema =
XmlSchemaCollectionName =
UdtAssemblyQualifiedName =
NonVersionedProviderType = 8
IsColumnSet = False
==============================================
DataReader contains 2 columns: b, a
Press any key to continue . . .
</pre></code>

### Suggestions
- Call `ExecuteReader` without `CommandBehavior.KeyInfo` argument, as it will not return the Primary Key information.

OR

- Iterate over [VisibleFieldCount](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.visiblefieldcount?view=netcore-2.0#remarks) Property instead of `FieldCount` property, as it always returns the number of fields that are not hidden and since the hidden fields are always appended behind the visible fields you can be assured that you will not see any hidden fields in your output.

To conclude this is not a bug and is expected behavior for the reasons explained above, let me know if you have any further questions, if not I will go ahead and close this issue.

**Comment by keeratsingh** [comment] 2018-06-06 20:58
Closing issue as this is expected behavior for reasons explained above.

**Closed by keeratsingh** 2018-06-06 20:58 UTC
Labels: area-System.Data.SqlClient
