### ISSUE TITLE
Vector3GetHashCodeTest AV'ing on Windows release

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15713] opened 2017-02-02 04:44 UTC
With the latest CoreCLR update, this test is consistently AV'ing on Windows.
```
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.Numerics.Tests.Vector3Tests.Vector3GetHashCodeTest() in D:\j\workspace\windows_nt_re---37265eab\src\System.Numerics.Vectors\tests\Vector3Tests.cs:line 51
```
cc: @mellinoe, @CarolEidt

**Comment by CarolEidt** [comment] 2017-02-02 23:10
@stephentoub - when I run the tests, this test doesn't seem to run. Has it been disabled? If so, how does one enable it to run the test?

**Comment by stephentoub** [comment] 2017-02-02 23:12
> Has it been disabled? If so, how does one enable it to run the test?

Yes, I disabled it so that we could update CoreCLR.  There's an [ActiveIssue] attribute on the test; just remove it, and it'll start running again.

**Comment by danmosemsft** [comment] 2017-02-08 17:53
@CarolEidt did you have luck getting this to run?

**Comment by CarolEidt** [comment] 2017-02-08 18:18
@danmosemsft Yes,but I haven't got much farther than that.

**Comment by danmosemsft** [comment] 2017-02-08 18:19
OK! let us know if you need anything on our side.

**Comment by CarolEidt** [comment] 2017-02-09 16:52
I have duplicated this on an earlier version and have a potential fix, but with the latest sources it doesn't seem to repro. I'm tracking down whether this is by design (i.e. actually fixed by some intervening change), or by accident (i.e. something else changed).

**Comment by CarolEidt** [comment] 2017-02-09 19:30
I was able to repro it and had a possible fix, but after merging with the latest coreclr, it seems to be failing before it hits the previously failing test. I'm continuing to work on it, but may have to pass it to someone else.

**Comment by danmosemsft** [comment] 2017-02-09 21:44
If it helps -- you can run tests just in one folder by going to the `tests` folder and doing `msbuild /t:buildandtest` or `/t:test`. You can also add [ActiveIssue(1)] on individual tests temporarily but obviously it's probably easier to just comment them out or remove them from the project.

**Comment by CarolEidt** [comment] 2017-02-10 19:13
I have a fix for this issue, and the other problem I was running into, which affects only Checked and Debug versions of the JIT.

**Comment by danmosemsft** [comment] 2017-02-10 19:30
It's great the numeric tests catch these. Do you think https://github.com/dotnet/corefx/issues/15913 is related?

**Comment by danmosemsft** [comment] 2017-02-10 19:32
#15913 can't be related since if I interpret the link in there corectly, it's failing on retail too.

**Comment by CarolEidt** [comment] 2017-02-10 20:02
@danmosemsft - I am fixing two issues with https://github.com/dotnet/coreclr/pull/9496. The real issue behind this GetHashCode failure is an issue which causes an AV in retail, and an assert in Checked - though in Checked, if you ran the full set of tests, you would run into the other (Checked/Debug only) AV. So it's possible that #15913 is due to the same issue as this.

**Closed** 2017-02-17 18:51 UTC
Labels: area-System.Numerics, test-run-core
