### ISSUE TITLE
OS X error System.DllNotFoundException: Unable to load DLL 'ntdll.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by 00101010b** [dotnet/corefx#4762] opened 2015-12-01 21:59 UTC
I receive the following error when attempting to use PingSendAsync on OS X.

```
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to load DLL 'ntdll.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
      System.DllNotFoundException: Unable to load DLL 'ntdll.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
         at System.Net.UnsafeCommonNativeMethods.RtlIpv4StringToAddressExW(String s, Boolean strict, Byte[] address, UInt16& port)
         at System.Net.IPAddressParser.Parse(String ipString, Boolean tryParse)
         at System.Net.NetworkInformation.Ping.SendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options, Object userToken)
         at System.Net.NetworkInformation.Ping.<>c__DisplayClass59_0.<SendPingAsync>b__0(TaskCompletionSource`1 tcs)
         at System.Net.NetworkInformation.Ping.SendPingAsyncCore(Action`1 sendAsync)
         at PingTest1.Controllers.HomeController.<>c.<Index>b__0_0(String host)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at PingTest1.Controllers.HomeController.<Index>d__0.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

Source code available here on GitHub: (https://github.com/00101010b/PingTest1/blob/master/Controllers/HomeController.cs)

**Comment by stephentoub** [comment] 2015-12-01 22:24
What build are you using / where did you get the System.Net.Utilities.dll you're using? Ping was only recently implemented on Unix: https://github.com/dotnet/corefx/pull/4484

**Comment by 00101010b** [comment] 2015-12-01 23:42
Currently using the following version of DNX:

```
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

The following is my project.json:

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "PingTest1"
  },

  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "System.Net.NetworkInformation": "4.1.0-beta-23516",
    "System.Net.Utilities": "4.0.0-beta-23516",
    "System.Net.NameResolution": "4.0.0-beta-23516"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnxcore50": {}
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [
      "npm install",
      "bower install",
      "gulp clean",
      "gulp min"
    ]
  }
}
```

As you can see, I obtained System.Net.Utilities.dll via the `dnu restore` command.

**Comment by stephentoub** [comment] 2015-12-02 00:32
@mellinoe / @chcosta, was packaging work done for System.Net.Utilities around cross-platform support?  The System.Net.Utilities.nupkg on both the dotnet-core and dotnet-core-rel feeds appears to contain a System.Net.Utilities.dll that's the full facade for Windows.

**Comment by chcosta** [comment] 2015-12-02 00:35
There was no packaging work done for System.Net.Utilities x-plat support.

**Comment by stephentoub** [comment] 2015-12-02 00:47
Which i believe explains why this is failing. @mellinoe, could you do the packaging work?

**Comment by mellinoe** [comment] 2015-12-02 00:53
@CIPop You had mentioned doing the packaging work as part of phasing out System.Private.Networking, did you finish that part yet?

**Comment by 00101010b** [comment] 2015-12-02 05:44
Just a quick update, I tested my code on Windows using Visual Studio 2015 Community Edition Update 1 (with some modifications) and it appears to work as it should.

**Comment by mellinoe** [comment] 2015-12-02 06:08
@00101010b That's to be expected right now, sorry about the confusion. We need to update our internal NuGet package projects to correctly produce cross-platform NuGet packages, not just a Windows version like right now. Once that is finished the next day's build should automatically publish to Myget and you can test it out at that point.

Right now you could try building the library from source for the other platforms if you are keen on trying it sooner.

**Comment by 00101010b** [comment] 2015-12-02 06:18
Thanks @mellinoe I think I will wait. I'm a bit noob.

**Comment by CIPop** [comment] 2015-12-02 18:19
> @CIPop You had mentioned doing the packaging work as part of phasing out System.Private.Networking, did you finish that part yet?

All code is ready for check-in but I'm still hitting some compiler and testing issues on NetNative. Once those are done, I'll check everything in. It's an all or nothing check-in for System.Private.Networking. If NIX to be fixed now, I can share the changeset and you can extract and modify the package definitions for NIX only.

**Comment by 00101010b** [comment] 2015-12-03 03:04
Just a quick question... 

What library version was this supposed to be corrected in? I just installed System.Net.NetworkInformation 4.1.0-beta-23516 (was using 4.0.0-beta-23516 when original error occurred) and received the following error when attempting to run my code through `dnx web` and connecting to the site in Chrome:

```
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to load DLL 'ntdll.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
      System.DllNotFoundException: Unable to load DLL 'ntdll.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
         at System.Net.UnsafeCommonNativeMethods.RtlIpv4StringToAddressExW(String s, Boolean strict, Byte[] address, UInt16& port)
         at System.Net.IPAddressParser.Parse(String ipString, Boolean tryParse)
         at System.Net.NetworkInformation.Ping.SendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options, Object userToken)
         at System.Net.NetworkInformation.Ping.<>c__DisplayClass59_0.<SendPingAsync>b__0(TaskCompletionSource`1 tcs)
         at System.Net.NetworkInformation.Ping.SendPingAsyncCore(Action`1 sendAsync)
         at PingTest1.Controllers.HomeController.<>c.<Index>b__0_0(String host)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at PingTest1.Controllers.HomeController.<Index>d__0.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

If this hasn't been corrected yet, I apologise for bringing it up again.

Scott.

**Comment by stephentoub** [comment] 2015-12-03 03:14
> What library version was this supposed to be corrected in

The implementation in the repo is correct (you can build it yourself if you'd like). The problem is the packaging, such that the packages available and that you're pulling down only contain the Windows build. That hasn't been fixed yet.

**Comment by 00101010b** [comment] 2015-12-03 04:02
@stephentoub ok that explains it. Sorry about posting that last post, I thought I broke something or did something wrong.

**Comment by mellinoe** [comment] 2015-12-09 19:05
@00101010b Sorry about the delay. We did finish the work on our end for this recently, and the latest versions of System.Net.Utilities on our feed should support Unix now.

**Comment by stephentoub** [comment] 2015-12-09 20:50
As we believe the issue has been resolved, I'm going to close this.  If you find otherwise, please reopen.  Thanks!

**Closed by stephentoub** 2015-12-09 20:50 UTC
Labels: packaging, X-Plat
