### ISSUE TITLE
Regression: Cookies are not sent in System.Net.Http 4.3.1 if set through headers

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/corefx#16464] opened 2017-02-25 13:37 UTC
In 4.3.0 everything worked as expected.

Repro:
Run following code in .NET Framework 4.6
```c#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http;
using System.Threading.Tasks;

namespace BrokenHttpClient
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = new WebHostBuilder().UseWebListener().Configure(app => app.Run(ctx =>
            {
                if (ctx.Request.Headers["Cookie"].Count == 0)
                    ctx.Response.StatusCode = 400;
                return Task.FromResult(0);
            })).UseUrls("http://localhost:3002").Build();
            using (var client = new HttpClient())
            {
                host.Start();
                var req = new HttpRequestMessage(HttpMethod.Post, "http://localhost:3002");
                req.Headers.TryAddWithoutValidation("Cookie", "mykey=myvalue");
                var res = client.SendAsync(req).Result;
                res.EnsureSuccessStatusCode();
            }
        }
    }
}
```
Nuget packages:
- Microsoft.AspNetCore.Hosting 1.1.0
- Microsoft.AspNetCore.Server.WebListener 1.1.0
- System.Net.Http 4.3.0 and 4.3.1

On 4.3.0 works as expected, on 4.3.1 cookie is not sent (400 is returned).

**Comment by karelz** [comment] 2017-02-25 17:50
@mkosieradzki do you know what is the behavior on .NET Framework (or in System.Net.Http 4.0.0.0)?
If it is the same, then this is by design - we intentionally rolled back all changes from System.Net.Http 4.1.0.0 and 4.3.0.0 - see #11100.

cc: @davidsh

**Comment by mkosieradzki** [comment] 2017-02-25 18:16
@karelz Thank you for explanation.
AFAIR It was not working at 4.0.0 as well. What is the workaround for this behavior? What is the working alternative?

**Comment by karelz** [comment] 2017-02-25 18:34
@mkosieradzki check the top post in #11100 (I know, it is long) - there's 'Breaking changes' section - it suggests to target System.Net.Http.WinHttpHandler NuGet package instead.

**Comment by mkosieradzki** [comment] 2017-02-25 18:47
@karelz Thanks. Unfortunately, I can't use WinHttpHandler, because I need it for aspnet/Proxy which is xplat.

**Comment by mkosieradzki** [comment] 2017-02-25 19:04
Btw. I have scanned through the referenced topic and I see how difficult the current situation is. However it does not make this bug any less painful :-(. However I do really appreciate lack of manual binding redirects requirement which was painful in 4.3.0.

**Comment by karelz** [comment] 2017-02-25 19:17
The binding redirects pain is still there with System.Net.Http 4.3.1 - only targeting .NET Standard 2.0 will be able to fully get rid of them.
BTW: I plan to explore the option of shipping 4.3.2 which does nothing, but I don't know yet how feasible/impactful that will be.

You have 3 options:
1. Use the old 4.3.0 NuGet package and avoid upgrading to 4.3.1 -- you should be warned as it will bring issues mentioned in #11100 
2. Wait for a bug fix in future version of .NET Framework -- that may take a long time and it is not guaranteed it will be fixable in .NET Framework (it has high compat bar)
3. Use .NET Core -- it has all latest and greatest bug fixes

**Comment by mkosieradzki** [comment] 2017-02-25 19:37
I think I will try to conditionally use WinHttpHandler on full .net and keep as is in .net core.

**Comment by karelz** [comment] 2017-02-25 19:41
OK, closing for now.
@davidsh might have additional insights and suggestions.

**Closed by karelz** 2017-02-25 19:41 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
