### ISSUE TITLE
[NetFX compat]: ISet_Generic_Tests.ISet_Generic_IntersectWith_Itself throws InvalidOperationException in netfx

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16796] opened 2017-03-06 23:48 UTC
Currently ISet_Generic_IntersectWith_Itself test fails with error: 

```
System.Collections.Tests.SortedSet_TreeSubset_Int_Tests.ISet_Generic_IntersectWith_Itself(setLength: 1) [FAIL]
      System.Collections.Tests.SortedSet_TreeSubset_Int_Tests.ISet_Generic_IntersectWith_Itself(setLength: 75) [FAIL]
        System.InvalidOperationException : Collection was modified after the enumerator was instantiated.
        Stack Trace:
             at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
             at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
             at System.Collections.Generic.SortedSet`1.TreeSubSet.IntersectWithEnumerable(IEnumerable`1 other)
             at System.Collections.Generic.SortedSet`1.IntersectWith(IEnumerable`1 other)
          D:\repos\corefx\src\Common\tests\System\Collections\ISet.Generic.Tests.cs(145,0): at System.Collections.Tests.ISet_Generic_Tests`1.Validate_IntersectWith(ISet`1 set, IEnumerable`1 enumerable)
          D:\repos\corefx\src\Common\tests\System\Collections\ISet.Generic.Tests.cs(426,0): at System.Collections.Tests.ISet_Generic_Tests`1.ISet_Generic_IntersectWith_Itself(Int32 setLength
```

When targeting framework netfx.

cc: @tarekgh

**Comment by tarekgh** [comment] 2017-03-07 00:06
thanks @safern. maybe you can set some keyword in the issue title so later we can filter and see all issues that have behavior difference with the desktop.

**Comment by safern** [comment] 2017-03-07 00:09
Will add it in both issues I've had opened and in future issues. What do you think about [Netfx test]?

**Comment by tarekgh** [comment] 2017-03-07 00:12
maybe you can make it [NetFX compat] or so

**Comment by safern** [comment] 2017-03-07 00:13
Ok sounds good! Thanks.

**Comment by karelz** [comment] 2017-03-07 01:55
@tarekgh @safern do we want to tackle these compat issues in 2.0 or defer them to Future (current status)?
cc @danmosemsft

**Comment by tarekgh** [comment] 2017-03-07 02:15
We'll keep those for the future except if run into issue we think it has to be in 2.0.0.0. Like a new issue in code didn't ship before and not a desktop issue

**Comment by karelz** [comment] 2017-03-07 02:25
I think that changing .NET Core after we ship 2.0 will be even harder - the argument will be, we shipped it in 3 releases and it was ok.
Do we believe tracking compat for Future is valuable?

**Comment by tarekgh** [comment] 2017-03-07 02:37
You already mentioned the argument :-) why we need to put pressure on fixing these before the release? IMHO Fixing them in the future should still have a value to reduce the behavior gap with the desktop but it is not urgent.

**Comment by safern** [comment] 2017-03-07 03:38
I would leave it as future as well as it is a bug in desktop where it is throwing an InvalidOperationException when using ISet.IntersectWith.

**Comment by danmosemsft** [comment] 2017-04-01 23:56
I don't see why we have this issue? We aren't tracking ports to desktop generally now, someone should have just marked the test and closed this issue. I will do this now.

**Comment by danmosemsft** [comment] 2017-04-02 03:27
@safern @tarekgh we should get the desktop run clean either by disabling the test temporarily (eg against this issue) or permanently (if by design). I am confident this one is by design.

**Closed** 2017-04-02 16:48 UTC
Labels: area-System.Collections, bug, tenet-compatibility, test-run-desktop
