### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents failed in CI with "System.ComponentModel.Win32Exception"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17545] opened 2017-03-27 09:05 UTC
Failed test: System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents

Configuration: OuterLoop_Fedora23_release (build#147)

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/147/consoleText

~~~
System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents(enable: True) [FAIL]
        System.ComponentModel.Win32Exception : No such process
        Stack Trace:
  command exited with ExitCode: 0
  /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.IO.MemoryMappedFiles/tests/Performance
  Finished running tests. End time=18:56:36. Return value was 0
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(58,0): at System.Diagnostics.Process.Kill()
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.Diagnostics.Process/tests/ProcessTestBase.cs(76,0): at System.Diagnostics.Tests.ProcessTestBase.StartSleepKillWait(Process p)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora23_release/src/System.Diagnostics.Process/tests/ProcessTests.cs(117,0): at System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents(Nullable`1 enable)
~~~

**Comment by Priya91** [comment] 2017-03-27 19:03
It looks like the process exited before it can be killed.

**Comment by Priya91** [comment] 2017-03-27 19:04
@Jiayili1 Is this consistently failing?

**Comment by danmosemsft** [comment] 2017-03-27 21:52
@sokket can we get this data out of your system?

**Comment by sokket** [comment] 2017-03-27 22:15
@danmosemsft looking...

**Comment by sokket** [comment] 2017-03-27 22:47
Looks like this is a regression and hasn't failed recently (past 3 runs)

**Comment by danmosemsft** [comment] 2017-03-27 22:52
Thanks @sokket .. this proves the value

**Comment by sokket** [comment] 2017-03-27 22:52
No problem :) glad I could help

**Comment by Jiayili1** [comment] 2017-03-28 01:01
@Priya91 this failing the first time, and I will check this issue on today's build.

**Comment by sepidehMS** [comment] 2017-04-19 22:17
Did this ever happen again? Where can we check?

**Comment by sokket** [comment] 2017-04-19 22:30
Here are the latest failures for this test case:
https://mc.int-dot.net/#/testResultHistory/corefx/System.Diagnostics.Tests.ProcessTests/TestEnableRaiseEvents?onlyPullRequests=false&timeFrame=OneWeek

**Comment by Priya91** [comment] 2017-04-20 22:15
This test hasn't failed since from the link @sokket has provided. @sokket Does that test history include test results from both Jenkins and helix runs?

**Comment by sokket** [comment] 2017-04-21 00:01
@Priya91 yes, however the data only goes back 7 days as of right now

**Comment by Priya91** [comment] 2017-04-21 00:43
Thanks @sokket. Closing this issue as no-repro.

**Closed by Priya91** 2017-04-21 00:43 UTC
Labels: area-System.Diagnostics.Process, blocking-clean-ci, test-run-core
