### ISSUE TITLE
AppContext.TargetFrameworkName is null

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#31081] opened 2018-07-15 05:25 UTC
I created a netcoreapp2.1 console app and checked the value of this property. It was null. I was expecting "netcoreapp2.1" or some variant of that.

Here are the docs: https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.targetframeworkname?view=netcore-2.1

**Comment by danmosemsft** [comment] 2018-07-15 06:57
Try latest bits from master 
https://github.com/dotnet/corefx/pull/30885/files#diff-508407e51bf1346c7da0cf453cb52c1c
@anipik what does it give now for a console app?

**Comment by jkotas** [comment] 2018-07-16 11:35
Duplicate of #23063. Fixed for .NET Core 3.0.

**Closed by jkotas** 2018-07-16 11:35 UTC
