### ISSUE TITLE
HttpWebRequest use HttpClient(not Singleton) to send message

### ISSUE THREAD

**Issue by zlzforever** [dotnet/corefx#31383] opened 2018-07-26 08:29 UTC
Hi,
the method GetResponse in HttpWebRequest

        private async Task<WebResponse> SendRequest()
        {
            if (RequestSubmitted)
            {
                throw new InvalidOperationException(SR.net_reqsubmitted);
            }

            var handler = new HttpClientHandler();
            var request = new HttpRequestMessage(new HttpMethod(_originVerb), _requestUri);

            using (var client = new HttpClient(handler))

Some persons suggest use HttpClient as a singleton to skip cost too many ports. HttpWebRequest will cause issue if it send request use HttpClient like:

        using (var client = new HttpClient(handler))
        {
        }

**Comment by zlzforever** [comment] 2018-07-26 09:05
Let's have a test:

        static void Main(string[] args)
        {
            Parallel.For(0, 10, (i) =>
            {
                while (true)
                {
                    var webRequest = (HttpWebRequest)WebRequest.CreateHttp("http://");
                    var response = webRequest.GetResponse();
                    response.Dispose();
                    Console.WriteLine($"Process: {i}.");
                    Thread.Sleep(5);
                }
            });
            Console.Read();
        }

-------------------------------------------------------------------------------------------------------
|   nfx                                |                  core on windows               |           core on linux              |
-------------------------------------------------------------------------------------------------------
|  cost 2 port                    |    very quickly cost more than 1000+ |           same as windows       |
------------------------------------------------------------------------------------------------------

**Comment by davidsh** [comment] 2018-07-26 14:09
This is a duplicate of #15460.  HttpWebRequest is considered a legacy API and is currently a simple wrapper on top of HttpClient.  For best performance, use HttpClient directly.

**Closed by davidsh** 2018-07-26 14:09 UTC
Labels: area-System.Net
