### ISSUE TITLE
 NetworkInterface.GetAllNetworkInterfaces() throws exception in cloud9 docker container.

### ISSUE THREAD

**Issue by xplicit** [dotnet/corefx#12969] opened 2016-10-24 20:57 UTC
`NetworkInterface.GetAllNetworkInterfaces()` always throws exception if try to run it in cloud9 docker container.

Steps to reproduce: create new workspace at www.c9.io, then install .net core v1.0.1 and type `dotnet new`. Then add following line in the `Main` method 

```
   NetworkInterface.GetAllNetworkInterfaces();
```

and type `dotnet run` (you're possible need to add necessary references to `project.json`). It throws exception:

``````
 Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/sys/class/net/lo/operstate' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOperationalStatus(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at ConsoleApplication.Program.Main(String[] args)```
``````

The bad thing that this exception cannot be catched by `catch (UnauthorizedAccessException)` nor `catch` block without type. What is weird, if try replace 

```
NetworkInterface.GetAllNetworkInterfaces(); 
```

with 

```
File.ReadAllText("/sys/class/net/lo/operstate").Trim();
```

Which is the cause of exception, then the exception can be handled by `catch (UnauthorizedAccessException)` block. So here is two issues: one of about access permissions to `/sys/class/net/lo/operstate` and second that the same exception sometimes can be handled sometimes can not.

**Comment by davidsh** [comment] 2016-10-24 21:01
cc: @stephentoub

**Comment by stephentoub** [comment] 2016-10-24 21:02
@mellinoe, could you take a look?

**Comment by mellinoe** [comment] 2016-10-24 21:17
@xplicit Could you give some more details about this environment? I would like to repro it but the site wants me to put payment information in. Do you have a more straightforward repro environment?

I'm not sure why you're not able to catch the exception; that does seem like a strange problem. If there are systems in which we can't access these files, I will need to augment our current checks. Right now we only try to detect if the file is missing entirely (which happens in some environments). Unfortunately it seems like we will now need to handle the case where the files are not accessible.

**Comment by xplicit** [comment] 2016-10-24 21:26
@mellinoe To create account at this site I made virtual credit card and put the info from virtual credit card. I don't know more details about how they create docker instances and which docker version they used, because I just saw this site at first time an hour ago.

I created the workspace with environment, it should be public, but I don't know can somebody else use it without creating account.  Here is workspace https://c9.io/quantumcalc

**Comment by mellinoe** [comment] 2016-10-24 21:40
From reading around a bit, it sounds like c9.io might be using SELinux or AppArmor or something like that to block access to those folders. We most likely just need to protect against this case.

I think these need to be upgraded to `catch (IOException)`:

https://github.com/dotnet/corefx/blob/master/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L176
https://github.com/dotnet/corefx/blob/master/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L110

**Comment by xplicit** [comment] 2016-10-24 21:46
@mellinoe it also can be permissions which are used in ReadAllText(). This file is located on docker read-only file system, so may be trying to apply additional permissions on read cause this exception. I can `cat /sys/class/net/lo/operstate` under the same user without problem

**Comment by mellinoe** [comment] 2016-10-24 22:08
Hm, that is sort of interesting in and of itself, but I'm not familiar enough with Unix file permissions to know if it is expected. @stephentoub , @JeremyKuhne , does it make sense that you would be able to `cat` a file, but not necessarily do `File.ReadAllText` on it? It looks like the source code for this was refactored so I'm having trouble tracing all of the system calls we make in `File.ReadAllText`.

(Regardless, we should most likely still do what I mentioned above and handle file permission failures here)

**Comment by xplicit** [comment] 2016-10-24 22:55
When fix please don't forget to not hide the error with exception handling. If general exception can not be handled in some cases and crashes the process it's a critical error.

**Comment by mellinoe** [comment] 2016-10-24 23:00
@xplicit A lot of information exposed in the `NetworkInformation` library is not available on Linux, even aside from this particular problem. There are many places that the library already throws a `PlatformNotSupportedException` where information cannot be reasonably obtained. In this case, we will most likely be throwing `PlatformNotSupportedException` if we cannot read the files. `OperationalStatus` does have an `Unknown` value which we use if we don't have any better information, but the other properties will throw an exception.

**Comment by xplicit** [comment] 2016-10-24 23:15
@mellinoe we use this method to get IP addresses and their subnet masks for network interfaces, we do not use any other properties include `OperationalStatus`. So this is fine, that some properties will throw `NotSupportedException`. But currently we cannot use it safely because `NetworkInterface.GetAllNetworkInterfaces()` crashes the process on the call and I do not see a workaround how to prevent it.

**Comment by mellinoe** [comment] 2016-10-24 23:42
Aside from some other strange bug, I don't see why you shouldn't be able to catch the exception that is being thrown there. Could you post the code you've tried?

**Comment by svick** [comment] 2016-10-24 23:56
@mellinoe I can reproduce that strange behavior on c9.io too.

When I run this code using `dotnet run`:

```c#
using System;
using System.Net.NetworkInformation;

public class Program
{
    public static void Main()
    {
        try
        {
            NetworkInterface.GetAllNetworkInterfaces();
        }
        catch
        {
            Console.WriteLine("caught");
        }
    }
}
```

The output is:

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/sys/class/net/lo/operstate' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOperationalStatus(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at ConsoleApplication.Program.Main()
```

And not `caught` as I would expect.

**Comment by stephentoub** [comment] 2016-10-25 00:47
cc: @janvorli, as this sounds like am exception handling bug

**Comment by xplicit** [comment] 2016-10-25 04:49
@mellinoe the code is the same which @svick posted. Also

```csharp
        try
        {
            NetworkInterface.GetAllNetworkInterfaces();
        }
        catch (System.UnauthorizedAccessException)
        {
            Console.WriteLine("caught");
        }
```
does not catch exception. While

```csharp
        try
        {
            File.ReadAllText("/sys/class/net/lo/operstate");
        }
        catch (System.UnauthorizedAccessException)
        {
            Console.WriteLine("caught");
        }
```

catches exception as expected.

**Comment by xplicit** [comment] 2016-10-25 05:18
By the way, shouldn't it be `System.Security.SecurityException` instead of  `System.UnauthorizedAccessException`? For .NET MSDN states that FileStream constructor throws `SecurityException` when there is not enough permissions to the file. 

https://msdn.microsoft.com/ru-ru/library/47ek66wy(v=vs.110).aspx

but 

    new FileStream("/sys/devices/virtual/net/lo/operstate", FileMode.Open, FileAccess.Read, FileShare.Read);

throws `UnauthorizedAccessException`

**Comment by xplicit** [comment] 2016-10-25 05:24
And some more info. If run following in mono (I tried in 3.2.8) it returns string "unknown" without throwing exception as expected: 
 
    File.ReadAllText("/sys/devices/virtual/net/lo/operstate");

**Comment by mattjcowan** [comment] 2016-10-25 15:25
nodejs also returns "unknown" on cloud9 without any errors (using both sync and async calls)
```
$ node
> new String(require('fs').readFileSync("/sys/devices/virtual/net/lo/operstate"))
[String: 'unknown\n']
```

**Comment by stephentoub** [comment] 2016-10-25 15:33
I suspect I may know what the problem is (for the File.ReadAllText failure, not for the inability to catch the exception).

Can you try compiling and running this small C program:
```C
#include <stdio.h>
#include <errno.h>
#include <sys/file.h>
#include <fcntl.h>

int main(int argc, char** argv)
{
    int fd = open("/sys/devices/virtual/net/lo/operstate", O_RDONLY);
    printf("%d\n", fd);

    errno = 0;
    int rv = flock(fd, LOCK_SH | LOCK_NB);
    printf("%d\n", rv);
    printf("%d\n", errno);
}
```
and share the output?  I suspect we're going to see output like:
```
3
-1
66
```
or for that last line something else non-zero.

**Comment by mattjcowan** [comment] 2016-10-25 16:19
i get:

```
3
-1
13
```

**Comment by stephentoub** [comment] 2016-10-25 16:29
Thanks, @mattjcowan.  Yeah, so the problem is that the flock call is failing when asking for a shared lock on the file, resulting in an EACCESS (which, interestingly, isn't listed in any of the man pages for flock I've looked at).  Since this is advisory locking only anyway, we should probably change the call such that rather than failing for any error, we only fail in the case of EWOULDBLOCK (meaning the file is currently locked by someone else), or alternatively special case EACCESS to ignore it.

**Comment by janvorli** [comment] 2016-10-25 16:55
@xplicit - regarding the exception not being caught - did you mean that you get the same exception reported as unhandled or do you get some other exception?

**Comment by xplicit** [comment] 2016-10-25 17:04
@janvorli I meant that the behavior is exactly the same like @svick shows in the comment https://github.com/dotnet/corefx/issues/12969#issuecomment-255898895 

Exception is thrown and process exited with "Unhandled exception" message.

**Comment by stephentoub** [comment] 2016-10-25 17:06
@xplicit, does the exception get caught with this slight variation?
```
try
{
    NetworkInterface.GetAllNetworkInterfaces();
}
catch
{
    Console.WriteLine("caught");
}
```

**Comment by stephentoub** [comment] 2016-10-25 17:07
(Nevermind, I see you already answered that earlier, and the answer was essentially it does not get caught.)

**Comment by xplicit** [comment] 2016-10-25 17:08
@stephentoub yes, it is not caught with `catch` without type specification.

**Comment by janvorli** [comment] 2016-10-25 17:31
@xplicit ah, sorry for not reading through the whole issue before asking. So it is an exception handling issue. I'll look into it.

**Comment by janvorli** [comment] 2016-10-26 00:37
I have looked into that. The exception handling is actually working correctly. The problem is that the `System.Net.NetworkInformation.dll!System.Net.NetworkInformation.LinuxNetworkInterface+<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(System.String, LinkLayerAddressInfo*)` is called from native code as a reverse pinvoke from `System.Native.so` (`SystemNative_EnumerateInterfaceAddresses` function) and CoreCLR doesn't support propagation of exceptions over the unmanaged / managed boundaries. 
That means that the above mentioned callback should catch exceptions and return a status to the native caller. The managed caller of the `SystemNative_EnumerateInterfaceAddresses`, the `LinuxNetworkInterface.GetLinuxNetworkInterfaces` then need to get the status when the `SystemNative_EnumerateInterfaceAddresses` returns and throw an appropriate exception.

**Comment by janvorli** [comment] 2016-10-26 20:53
@mellinoe - would you be the right person to look into fixing the issue with exception handling over the managed - native - managed boundary in the GetLinuxNetworkInterfaces I have identified?

**Comment by mellinoe** [comment] 2016-10-26 22:27
@janvorli I'm working on it.

**Comment by mellinoe** [comment] 2016-10-26 22:30
Note that the bug described in this issue is resolved with the fix to `File.ReadAllText`. I'll provide extra checks in `GetAllNetworkInterfaces()` to ensure that exceptions aren't propogated out of the reverse PInvoke, but it shouldn't have any direct effect on this scenario after the `ReadAllText` fix.

**Comment by janvorli** [comment] 2016-10-26 22:30
@mellinoe ok, makes sense.

**Comment by mellinoe** [comment] 2016-11-07 22:41
This should be fixed in the latest versions of the packages.

**Closed by mellinoe** 2016-11-07 22:41 UTC
Labels: area-System.Net, X-Plat
