### ISSUE TITLE
The StackOverflow exception is raised if C# code contains a generic object that nests a hierarchy of generic types

### ISSUE THREAD

**Issue by maxerokh** [dotnet/corefx#23706] opened 2017-08-31 15:09 UTC
I created the following simple console application where the problem is reproduced:

```c#
class Program {
	static void Main(string[] args) {
		dynamic arg = 5;
		new Builder<object>().SomeMethod(arg);
	}
}


public class Builder<TItem> : BuilderBaseEx<Builder<TItem>> {
	public Builder<TItem> SomeMethod(object arg) {
		return this;
	}
}
public class BuilderBaseEx<T> : BuilderBase<T> where T : BuilderBaseEx<T> { }
public class BuilderBase<T> where T : BuilderBase<T> { }
```

After running the program, I got the StackOverflowException. The exception occurs only when I send a dynamic type object to the SomeMethod. If I send a non-dynamic type object, no error occurs.

[EDIT] Add C# syntax highlight by @karelz

**Comment by JonHanna** [comment] 2017-08-31 15:11
This looks like it might be a duplicate of #7527, or at least have a similar cause.

**Comment by svick** [comment] 2017-08-31 16:17
Previously reported at https://github.com/dotnet/roslyn/issues/21843.

**Comment by karelz** [comment] 2017-08-31 16:46
Yes, it looks like variant of #7527 - closing as dupe.

BTW: The only difference is in the constraint on `Second<T>`=`BuilderBaseEx<T>` here it is `where T : Second<T>`, while in #7527 it is `where T : First<T>`.
I don't think it is significant different.


@maxerokh please in future, do not file identical issues in multiple repos (here and in Roslyn) - it makes multiple teams/people look at the issues, basically wasting their time. And if you do so, for some good reason, please link them, so that people are aware of the multi-repo dupes. Again with the goal to avoid wasted time in duplicate reading/investigations.

BTW: Thanks a lot @svick for catching the filed dupe! And thanks @JonHanna for catching the pre-existing report.

**Closed by karelz** 2017-08-31 16:46 UTC
Labels: area-Microsoft.CSharp, bug

**Comment by JonHanna** [comment] 2017-08-31 21:16
Thank me once I fix it. (It seems to be one of those tasks where every time I try to make a start at it, something comes up).

**Comment by JonHanna** [comment] 2017-11-11 15:58
Confirmed as having duplicate cause as #7527. #25196 includes a test confirming it fixes this.
