### ISSUE TITLE
[RC2] update nuget packaging to include mscorlib.ni.dll on Linux/Mac

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4305] opened 2015-11-03 18:41 UTC
After the official build is updated to produce mscorlib.ni.dll (https://github.com/dotnet/coreclr/issues/1934) the package generation script also needs to be updated to ship the new binaries.

/cc @JohnChen0 @gkhanna79

**Comment by ericstj** [comment] 2015-11-24 18:34
Blocked on crossgen work.

**Comment by gkhanna79** [comment] 2015-11-24 22:20
@ericstj Why is this blocked against crossgen? mscorlib.ni.dll can be generated today with crossgen. The only difference is that mscorlib.ni.dll cannot be generated as part of the Ubuntu/Mac build since mscorlib.dll is built on Windows. Once Msbuild support is enabled that will enable mscorlib.dll to be built on Ubuntu/Mac, CoreCLR repo build will be able to generate the NI.

For now, is there a reason why the package generation script not generate the NI?

**Comment by gkhanna79** [comment] 2015-11-24 22:20
CC @JohnChen0

**Comment by ericstj** [comment] 2015-11-24 22:33
Just meant it's blocked on actually getting https://github.com/dotnet/coreclr/issues/1934 resolved.  If you've fixed https://github.com/dotnet/coreclr/issues/1934 then we can update the packages.

Packaging doesn't generate the NI, nor does it run on Ubuntu/Mac. I don't suppose we can run crossgen on windows to produce the NI for Ubuntu/OSX, right?

**Comment by gkhanna79** [comment] 2015-11-24 22:47
As I mentioned, dotnet/coreclr#1934  cannot be fixed until mscorlib.dll is built on Ubuntu/Mac, which is blocked on Msbuild.

Where are the nuget packages being built? On Windows for all platforms?

> I don't suppose we can run crossgen on windows to produce the NI for Ubuntu/OSX, right?
Correct.

**Comment by ericstj** [comment] 2016-03-16 16:49
It looks like this is fixed now.  @gkhanna79 @chcosta can you confirm and close?

**Comment by gkhanna79** [comment] 2016-03-16 16:54
Yes, this is complete. I am not aware of anything outstanding. @chcosta If there is nothing else you are aware of, please feel free to close this.

**Comment by chcosta** [comment] 2016-03-16 16:55
I confirmed that mscorlib.ni.dll is in today's Linux / OSX packages.

**Closed by chcosta** 2016-03-16 16:55 UTC
Labels: packaging
