### ISSUE TITLE
Debug native build on OSX fails with link error - missing symbols

### ISSUE THREAD

**Issue by 4creators** [dotnet/corefx#20666] opened 2017-06-03 13:47 UTC
Tried to build latest corefx repo master branch commit fd7cc973ae66e1523fabd2c432a8333ddfecd8e6 on OSX following current [instructions](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md). Release build was succesfull while Debug build failed with the following errors:

```
[100%] Linking CXX shared library System.Security.Cryptography.Native.OpenSsl.dylib
Undefined symbols for architecture x86_64:
  "_EC_KEY_set_public_key_affine_coordinates", referenced from:
      _CryptoNative_EcKeyCreateByKeyParameters in pal_ecc_import_export.cpp.o
      _CryptoNative_EcKeyCreateByExplicitParameters in pal_ecc_import_export.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [System.Security.Cryptography.Native/System.Security.Cryptography.Native.OpenSsl.dylib] Error 1
make[1]: *** [System.Security.Cryptography.Native/CMakeFiles/System.Security.Cryptography.Native.OpenSsl.dir/all] Error 2
make: *** [all] Error 2
Failed to build corefx native components.
Command execution failed with exit code 1.
```
System:
```
  System Version:	macOS 10.12.5 (16F73)
  Kernel Version:	Darwin 16.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	        Normal
  Computer Name:	MacBook Air
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	21:56
  Xcode    Version 8.3.2 (8E2002)
```
Corefx build was done after successful build of coreclr for all configurations. Complete build output and earlier cmake configuration error output are attached in file.

[osx_corefx_debug_build_error.txt](https://github.com/dotnet/corefx/files/1049627/osx_corefx_debug_build_error.txt)

**Comment by karelz** [comment] 2017-06-03 17:05
cc @wfurt

**Comment by wfurt** [comment] 2017-06-05 17:12
run 'pkg-config --libs openssl' @4creators 

I was able to reproduce same failure and it is probably because of missing pkg-config. 
If that is the case run:
brew install pkg-config
./clean.sh
./build.sh

I also updated building instructions https://github.com/wfurt/coreclr/blob/master/Documentation/building/osx-instructions.md

**Comment by 4creators** [comment] 2017-06-05 18:28
@wfurt  I don't think it was due to missing pkg-config as I have it installed it earlier for other builds, however, I can be wrong. I will try to clean machine and repro the error and try your fix

**Comment by wfurt** [comment] 2017-06-05 18:32
ok, let me know. Check pkg-config --libs openssl
The error is definitely caused by linking against wrong (system) version of openssl.

**Comment by 4creators** [comment] 2017-06-05 18:56
@wfurt Check my command output above. I edited my message at the same time you posted

**Comment by wfurt** [comment] 2017-06-05 19:26
ok. Can you than send me output of CMakeOutput.log and CMakeError.log?
(bin/obj/OSX.x64.Debug/native/CMakeFiles) 

Your original post shows 
CMake Error at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindOpenSSL.cmake:387 (find_package_handle_standard_args)
  System.Security.Cryptography.Native/CMakeLists.txt:15 (find_package)


and the error is definitely caused by linking wrong version of openssl.

**Comment by 4creators** [comment] 2017-06-05 19:48
Pls find logs attached
[Archive.zip](https://github.com/dotnet/corefx/files/1053007/Archive.zip)

**Comment by 4creators** [comment] 2017-06-05 20:18
Pls find release logs attached - I have built in release mode immediately after debug build failed
[Archive_CmakeLogs_Release.zip](https://github.com/dotnet/corefx/files/1053087/Archive_CmakeLogs_Release.zip)

**Comment by bartonjs** [comment] 2017-06-05 22:26
@4creators Your log shows that the build is trying to link against OpenSSL 0.9.8:

> /Library/Developer/CommandLineTools/usr/bin/clang  -std=c11 -DCHECK_FUNCTION_EXISTS=EC_GF2m_simple_method -Werror -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_42665.dir/CheckFunctionExists.c.o  -o cmTC_42665 /usr/lib/libcrypto.dylib

On my machine the dylib in the log is /usr/local/Cellar/openssl/1.0.2k/lib/libcrypto.dylib.  The only times I've ever seen it be wrong are when pkg-config isn't present, or when the pkgconfig files weren't added to /usr/local/lib/pkgconfig.

Running `pkg-config --libs openssl` usually returns an error of some sort in that scenario.  But your output for that matches mine.

The only other case that I know of is not wiping out the `bin` directory of the repository after CMake has cached the wrong answer (and you've since fixed things).  If `./clean.sh` didn't do the trick, `git clean -xdf` from the repository root should take care of it.

There may also the possibility that you don't have any files under `/usr/local/Cellar/openssl/1.0.2k/lib` anymore... I'm not sure what happens when pkg-config says the library should be there, but it isn't.

**Comment by wfurt** [comment] 2017-06-05 22:37
Cached entry could explain why release works but debug does not. 

After cleaning, you can also try:
cd src/Native
./build-native.sh  verbose cmakeargs '--debug-output --trace'

That produces more details but I still did not find details how proper version is located. 

In your debug output there is at least attempt to use proper version

/Library/Developer/CommandLineTools/usr/bin/clang  -I/usr/local/Cellar/openssl/1.0.2k/include  -std=c11 -DCHECK_FUNCTION_EXISTS=EC_GF2m_simple_method -Werror   -o CMakeFiles/cmTC_42665.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CheckFunctionExists.c

**Comment by 4creators** [comment] 2017-06-06 16:45
After repo cleanup debug build was OK. However I have encountered another problem for which I will open separate issue - download of dependencies with LTE network connections.

**Comment by wfurt** [comment] 2017-06-06 17:43
OK @4creators . I'm closing it for now. It would be interesting to know how did you get to that state. 
For cleanup, did you use the clenup script or did you use git method suggested by @bartonjs ???

**Closed by wfurt** 2017-06-06 17:43 UTC
Labels: area-Infrastructure, bug
