### ISSUE TITLE
JsonSerializer does not support EOL added by some text editors

### ISSUE THREAD

**Issue by vova-lantsov-dev** [dotnet/corefx#38370] opened 2019-06-08 16:36 UTC
I've had an exception with next stacktrace:
```
System.Text.Json.JsonReaderException: The provided data of length 1493 has remaining bytes 1.
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at System.Text.Json.Serialization.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken canc
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at MaximEmmBots.Extensions.SettingsExtensions.YieldRestaurantsAsync()+MoveNext() in /home/kiss/projects/MaximEmmBots/Extensions/SettingsExtensions.cs:line
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at MaximEmmBots.Extensions.SettingsExtensions.YieldRestaurantsAsync()+MoveNext() in /home/kiss/projects/MaximEmmBots/Extensions/SettingsExtensions.cs:line
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at MaximEmmBots.Program.Main(String[] args) in /home/kiss/projects/MaximEmmBots/Program.cs:line 20
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at MaximEmmBots.Program.Main(String[] args) in /home/kiss/projects/MaximEmmBots/Program.cs:line 20
Jun 08 14:24:05 zabbix MaximEmmBots[29507]:    at MaximEmmBots.Program.<Main>(String[] args)
```

Problem was caused by a new line symbol, that is added by default by a lot of existing text editors (such as nano, vim). There are [some options](https://askubuntu.com/a/13324) how to disable EOL insertion but it'd be better to add support into the new JSON library.

**Comment by ahsonkhan** [comment] 2019-06-08 21:32
What is the EOL character value (in hex)? The `Utf8JsonReader` explicitly only allows whitespace according to the JSON RFC https://tools.ietf.org/html/rfc8259#section-2

```text
   Insignificant whitespace is allowed before or after any of the six
   structural characters.

      ws = *(
              %x20 /              ; Space
              %x09 /              ; Horizontal tab
              %x0A /              ; Line feed or New line
              %x0D )              ; Carriage return
```

I would like to know if the character at the end of the JSON file is outside that range. If so, maybe the stream overload on the serializer can special case it, but I wouldn't modify the default "allow" list on the reader (unless we are talking about just `\n`, `\r`, which yes the reader should ignore).

cc @steveharter, @GrabYourPitchforks

**Comment by vova-lantsov-dev** [comment] 2019-06-09 07:12
@ahsonkhan this character is [Line feed](https://www.fileformat.info/info/unicode/char/000a/index.htm). According to info from you, it should be supported, but when this symbol presents as the last byte of the file, code is broken

**Comment by ahsonkhan** [comment] 2019-06-11 00:11
Thanks @vova-lantsov-dev. This was fixed in the synchronous APIs by @watfordgnf, and I couldn't repro it for the async APIs either (since the underlying logic/workhorse method is shared between them): https://github.com/dotnet/corefx/issues/37500 / https://github.com/dotnet/corefx/pull/37549.

What version of the SDK are you on (please share the output of `dotnet.exe --info`)?

Can you try with the latest bits and see if the issue is still reproducible?
https://github.com/dotnet/core-setup#daily-builds

If it is still failing on latest, can you share more details on the repro (like the JSON payload you are trying to read and the .NET object definition deserializing into)?

**Comment by joshfree** [comment] 2019-06-11 19:40
Closing as this is fixed in the latest daily builds

**Closed by joshfree** 2019-06-11 19:40 UTC
Labels: area-System.Text.Json, bug
