### ISSUE TITLE
Extrem Slow Http Client

### ISSUE THREAD

**Issue by BoasE** [dotnet/corefx#35230] opened 2019-02-11 13:21 UTC
In a netcore 2.2 apiproject I'm querying a api.

The responses are horrible slow.

Most of the requests take  about 20 -30 seconds.

When I use PostMan from same machine the api always respons within 50 ms.

Code looks like this:

```
 
 [HttpGet]
 public async Task<IActionResult> Get()
 {
    HttpClient http = new HttpClient();
    http.DefaultRequestHeaders.Clear();
    http.DefaultRequestHeaders.Add("Authorization",myBearer );
    string result = await http.GetStringAsync(myUrl);
}
```

When I put the samecode in a ConsoleLibrary it has same performance as it has in postman.
Only when the code runs inside a Api Controller it gets horrible slow.

So there must be a relation to some asp core web api defaults?

**Comment by khellang** [comment] 2019-02-11 13:25
Is this on the first request or do you have to do a couple of requests before you can see that behavior?

**Comment by BoasE** [comment] 2019-02-11 13:58
All calls starting from the first.
PS For testing in my example i also tried to make HttpClient and them make multiple calls. Each call is slow

like this
```
[HttpGet]
 public async Task<IActionResult> Get()
 {
    HttpClient http = new HttpClient();
    http.DefaultRequestHeaders.Clear();
    http.DefaultRequestHeaders.Add("Authorization",myBearer );
    string result = await http.GetStringAsync(myUrl");
    string result = await http.GetStringAsync(myUrl");
    string result = await http.GetStringAsync(myUrl");
}
```

**Comment by khellang** [comment] 2019-02-11 14:12
> But it seems to be depending on the target url.

I think you need to provide a few more details. There's not really much to work off here.

Are these internet URLs? Or are they on your local network?
Have you tested DNS lookups outside .NET? Could it be related to https://github.com/dotnet/corefx/issues/33037? Maybe try to measure calls to `Dns.GetHostAddressesAsync` for the different URLs?
What OS are you running?

**Comment by BoasE** [comment] 2019-02-11 14:22
I'm running windows. 

The Target URL is in internet in the Google Kubernetes cloud behind cloudflare.
First I assumed it may be related to cloudflare but as my requests form postman are going through  i don't believe this anymore.

Dns.GetHostAddressesAsync works extremly fast and returns same results as nslookup in commandline.

**Comment by davidsh** [comment] 2019-02-11 16:20
>When I put the samecode in a ConsoleLibrary it has same performance as it has in postman.
Only when the code runs inside a Api Controller it gets horrible slow.

This suggests the issue is related to ASP.NET and not the client-side HTTP stack (HttpClient).  It might be best to follow up with the ASP.NET team.  This issue should potentially be moved to that repo. @Tratcher Can you comment on this?

**Comment by Tratcher** [comment] 2019-02-11 16:34
@davidsh there's no reason using HttpClient in an ApiController should have any effect on its performance aside from the common issue of creating many short lived clients. WebApi cannot change any HttpClient defaults.

@BoasE is it any better if you make HttpClient a static member?

Are you testing this under load or just with a single request from a browser or similar?

My other guess would be an issue with automatic proxy detection.

**Comment by BoasE** [comment] 2019-02-11 17:49
With a single request from local developer machine. making itstatic doesn't change anything

**Comment by BoasE** [comment] 2019-02-12 07:38
Furthermore when I run it on a other machine with same windows version i don't have this hangs. So I assume it is related to local configurations not adopted in the webapi

**Comment by khellang** [comment] 2019-02-12 07:52
At this point, it would be very hard for anyone else to debug this, no? 😄

**Comment by BoasE** [comment] 2019-02-12 07:53
Yes it seems like this. I try to isolate it by adotping the settinsg from one pc to another. I assume it has to do with some non default proxys.

**Comment by davidsh** [comment] 2019-02-13 21:54
Based on this discussion and information this issue doesn't seem actionable right now as an bug in CoreFx.  So, I'm going to close this for now.  Let us know if you isolate a repro that would point to a bug in the CoreFx HTTP/networking stack. Thx.

**Closed by davidsh** 2019-02-13 21:54 UTC
Labels: area-System.Net.Http
