### ISSUE TITLE
Weird issue with httpClient

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/corefx#25520] opened 2017-11-27 13:07 UTC
I am testing my code in my win10 dev machine and works fine.

```
//mycode
HttpResponseMessage response = await client.GetAsync(uri);
```

When i try it in a winServer2012 r2 
I get 

```
System.Net.Http.WinHttpException (0x80072F8F): A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NextcloudClient.NextCloudPublicSharesClient.<_getLoginRequestToken>d__15.MoveNext() in C:\Projects\httpIssues\httpIssues\NextcloudClient\NextCloudPublicClient.cs:line 396
...
```

My pc with is in the same network with the devServer in the same AD
My code was working before upgrading to .net core 2.0.3

**Comment by xrkolovos** [comment] 2017-11-27 13:10
This httpRequest is happening in a public https website that uses Let's Encrypt Certificate

**Comment by xrkolovos** [comment] 2017-11-27 13:18
It also worth's pointing out that this never gets triggered. 

```
handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => {
                return true;
            };
```

this also doesn't helps
`handler.SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls;`

And in security tab in chome i get this info

> The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_RSA with P-256 (a strong key exchange), and AES_128_GCM (a strong cipher).

**Comment by SoEnLion** [comment] 2017-11-27 16:04
Hello,

Are you logged in with the same account on bot machines?

`at NextcloudClient.NextCloudPublicSharesClient.<_getLoginRequestToken>d__15.MoveNext() in C:\Projects\httpIssues\httpIssues\NextcloudClient\NextCloudPublicClient.cs:line 396`

**Comment by davidsh** [comment] 2017-11-27 16:51
Please attach a WireShark trace.

**Comment by davidsh** [comment] 2017-11-27 17:47
>This httpRequest is happening in a public https website that uses Let's Encrypt Certificate

Also, please post information about what website this is.

**Comment by LadislavBohm** [comment] 2017-12-05 00:55
I am having the same issue using WebSocketClient in Azure WebJob. Because this happens only in Azure I cant provide WireShark trace (or can I?).
WSS uri I am calling is: wss://sc-02.coinigy.com/socketcluster/

**Comment by xrkolovos** [comment] 2017-12-05 16:50
Hello, i uploaded my wireshark capture.

[wiresharkPackages.zip](https://github.com/dotnet/corefx/files/1532070/wiresharkPackages.zip)

**Comment by xrkolovos** [comment] 2017-12-05 16:53
Some more info on this issue.
I try to navigate in this page from this server with Chrome and Firefox and everything works fine. When i try to navigate from IE i get an error 

> This page can’t be displayed

This is a windows issue definitely.

**Comment by davidsh** [comment] 2017-12-07 04:48
It seems the problem is due to that server allowing only TLS 1.2.

See:
https://www.ssllabs.com/ssltest/analyze.html?d=sc-02.coinigy.com

>Protocols
TLS 1.3	No
TLS 1.2	Yes
TLS 1.1	No
TLS 1.0	No
SSL 3	No
SSL 2	No
For TLS 1.3 tests, we currently support draft version 18.

Windows Server 2012 R2 might require additional settings to use TLS 1.2.

The HTTP stack in .NET Core for Windows uses native WinHTTP layer.
See:
https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

Can you check your machine for those settings and make adjustments if necessary and let us know if you're able to connect with TLS 1.2 on the Windows Server 2012 R2 machine?

**Comment by davidsh** [comment] 2017-12-07 04:51
And in terms of the IE browser not working correctly, that is also interesting.  Internet Explorer uses native WinINet (not native WinHTTP).  It seems like both native Windows HTTP stacks use the registry to determine whether TLS 1.2 is enabled or not.

See:
https://technet.microsoft.com/en-us/library/dn786418(v=ws.11).aspx

**Comment by LadislavBohm** [comment] 2017-12-10 17:05
@davidsh Thanks for the analysis and suggestion. Since I am deploying my app to Azure as WebJob, I am not able to install anything there. However I made a test where I changed from .NET Core 2.0 to .NET 4.6.1 and set:
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
and it works. So from what I understand there is no way yet to set (force) ClientWebSocket to use specific security protocol?

**Comment by davidsh** [comment] 2017-12-10 19:26
>So from what I understand there is no way yet to set (force) ClientWebSocket to use specific security protocol?

This issue is about HttpClient.  Why are we talking about ClientWebSocket now?

**Comment by LadislavBohm** [comment] 2017-12-10 19:36
Same problem described by OP seems to be affecting ClientWebSocket class, but if you want me to create new Issue I will.

**Comment by xrkolovos** [comment] 2017-12-12 12:25
For the IE browser, in ssllabs I get this message in Handshake Simulation

```
|  IE 11 / Win 8.1  R  
Client does not support DH parameters > 4096 bitsRSA 4096 (SHA256)   
|  TLS 1.2> http/1.1    
|  TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 
|  DH 8192

```

**Comment by xrkolovos** [comment] 2017-12-12 12:40
my server enables this protocols

```
Protocols
--
TLS 1.3 | No
TLS 1.2 | Yes
TLS 1.1 | Yes
TLS 1.0 | Yes
SSL 3 | No
SSL 2 | No
For TLS 1.3 tests, we currently support draft version 18.

```

I am trying to find, what i should do. This url 
https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in
doesn't apply for windows server 2012r2

**Comment by davidsh** [comment] 2018-01-08 22:11
@xrkolovos 

Please review this article to make sure that TLS 1.2 is enabled on your Windows Server 2012 R2 machine:
https://technet.microsoft.com/en-us/library/dn786418(v=ws.11).aspx

**Comment by davidsh** [comment] 2018-04-08 22:48
This issue is being caused by a bug/limitation in the the TLS/SSL low-level protocol stack (SCHANNEL) in Windows Server 2012 R2 (a.ka. Windows 8.1 "server").

The analysis by ssllabs.com is correct about this:

```
|  IE 11 / Win 8.1  R  
Client does not support DH parameters > 4096 bitsRSA 4096 (SHA256)   
```

Due to the cipher suite problem (DH parameters > 4096 bitsRSA), the connection can't be completed. And failure to negotiate the cipher suites will prevent further processing of the TLS/SSL handshake. That is why your custom callback is not being called.

 ```
handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => {
                return true;
            };
```

This problem can only be fixed by using a later version Windows OS. You indicated that this scenario works on Windows 10.  It should also work on Windows Server 2016 as well.

Since there is nothing further that can be done, we'll close this issue now.

**Closed by davidsh** 2018-04-08 22:48 UTC
Labels: area-System.Net.Http, os-windows
