### ISSUE TITLE
MS.Internal.FontCache.DWriteFactory type initializer exception

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#37956] opened 2019-05-26 09:04 UTC
This only starts to happen in Preview 6 (3.0.100-preview6-012085) but not in Preview 5 and lower. One of my WPF applications crashes at start on App().Run(). Sadly its a larger application and the stacktrace shows a lot internal stuff so it's hard for me to find the line that's causing it.

Exception:
```
System.TypeInitializationException: 'The type initializer for 'System.Windows.Media.FontFamily' threw an exception.'
TypeInitializationException: The type initializer for 'MS.Internal.FontCache.DWriteFactory' threw an exception.
InvalidCastException: Specified cast is not valid.
```

Stacktrace:
```
 at System.Windows.Media.Typeface..ctor(FontFamily fontFamily, FontStyle style, FontWeight weight, FontStretch stretch)
   at MS.Internal.Text.DynamicPropertyReader.GetTypeface(DependencyObject element)
   at MS.Internal.Text.TextProperties.InitCommon(DependencyObject target)
   at MS.Internal.Text.TextProperties..ctor(FrameworkElement target, Boolean isTypographyDefaultValue)
   at System.Windows.Controls.TextBlock.GetLineProperties()
   at System.Windows.Controls.TextBlock.EnsureTextBlockCache()
   at System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
```

**Comment by mikedn** [comment] 2019-05-28 05:46
This looks like a duplicate of https://github.com/dotnet/coreclr/issues/24705

**Comment by Symbai** [comment] 2019-05-28 09:59
Looks like, except the issue you linked is closed and said its fixed in 3.0.100-preview6-012016 but in my case in happens in 3.0.100-preview6-012085 which is newer.

So it's not fixed?

**Comment by albahari** [comment] 2019-05-28 10:46
I can confirm that it's not fixed as of preview6-19270

**Comment by rprouse** [comment] 2019-05-28 14:40
I can reproduce this issue on two of my machines using @albahari's beta if you need any help tracking down the problem.

**Comment by karelz** [comment] 2019-05-29 22:53
@safern can you please help route it to the appropriate area?

**Comment by safern** [comment] 2019-05-30 23:30
Based on the conversation here: https://github.com/dotnet/wpf/issues/771#issuecomment-496608283 this is a duplicate of: https://github.com/dotnet/coreclr/issues/24705 -- which started flowing up the stack as of 2 days ago, so it is just a matter that it flows up to the SDK and then we produce a new daily build with this change. 

Is there a simple way to repro? If there is a simple repro we could validate by using a daily built runtime (rather than the SDK) since potentially the runtime already has this fix.

Will close and if @albahari or @Symbai could share simple steps to repro I can help validating that.

**Closed by safern** 2019-05-30 23:30 UTC
Labels: area-System.Drawing
