### ISSUE TITLE
EventListener tests for Events are not enabled because we haven't shipped that API yet

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#4865] opened 2015-12-07 20:45 UTC
We are in the process of putting a new API to consume EventSource events through EventListeners without having to subclass an EventListener. The tests for these changes are disabled until the feature ships.

**Comment by danmosemsft** [comment] 2017-03-01 22:55
@davmason this is a very old issue. is it still relevant? if so where are the tests? they should have [ActiveIssue(4865)] on them.

**Comment by danmosemsft** [comment] 2017-03-01 22:55
if not relevant - please close now.

**Comment by karelz** [comment] 2017-03-02 21:32
@davmason do you have the tests anywhere internally? @brianrob said he might be able to do it with his EventSource work + it seems to be cheap.

**Comment by davmason** [comment] 2017-03-02 21:44
All the tests are wired up, and currently running they just don't test the codepath because it wasn't available at the time. In Listeners.cs in the tests directory I have the relevant code commented out with an ifdef. See https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs#L300-L374

Once those ifdefs are removed the tests should light up. For example, this is one such test https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsWriteEvent.cs#L55-L58

**Comment by ViktorHofer** [comment] 2017-04-13 19:25
Working on enabling the tests. Already talked with David. What I noticed, some new members in coreclr don't yet have a mapping here. Need to add that.

```
EventSourceCreatedEventArgs
EventSourceCreated
EventWritten
```

**Comment by karelz** [comment] 2017-04-13 20:48
cc @brianrob @vancem

**Comment by brianrob** [comment] 2017-04-13 20:57
@ViktorHofer, thanks for doing this!  Can you tell me what you mean that some of the members don't have mappings here?

**Comment by ViktorHofer** [comment] 2017-04-14 10:23
The package System.Diagnostics.Tracing is currently target netstandard. Unfortunately these types which I posted above aren't yet in netstandard. I'm not sure if this is intentionally or just left out? @weshaggard Therefore I can't activate the tests as long as they are not coming into netstandard or we change the package targeting.

**Comment by vancem** [comment] 2017-04-14 15:02
The types 
```
EventSourceCreatedEventArgs
EventSourceCreated
EventWritten
```
are exactly the types that were added that David was trying to test.   I have not confirmed but given that David wrote about this in 12/2015 and  V4.6.1 shipped in 11/2015, I would say that these APIs probably were added for V4.6.2.   This means that they are NOT part of netstandard 2.0 (which wants to work on Desktop runtimes back to V4.6.1).    

It can however be a part of NetStandard 1.5 (which requires V4.6.2 on the desktop).   

I think we need @weshaggard  or @ericstj  to comment on what the right approach would be here.   Basically we have some APIs that we would like to expose (and in fact features like EventCounters use), that only got into the desktop framework in V4.6.2.    How should the versioning work from a NetStandard perspective?

**Comment by ViktorHofer** [comment] 2017-04-14 15:04
> It can however be a part of NetStandard 1.5 (which requires V4.6.2 on the desktop).

Wasn't that changed? See here: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

**Comment by karelz** [comment] 2017-04-14 15:11
At minimum we should be able to enable the tests on .NET Core and on Desktop 4.6.2+ then, right?

**Comment by vancem** [comment] 2017-04-14 15:20
> At minimum we should be able to enable the tests on .NET Core and on Desktop 4.6.2+ then, right?
Yes. 
> We might keep the tests disabled till .NET Standard 2.1? Then I guess we will target a higher netfx version?
You could do that, but that means are testing is always at the mercy of how fast the desktop moves.   
It seems like we should have a mechanism for testing new things IMMEDIATELY that were added to .NET Core (as this was done), and then as NetStandard enfolds it, we can test it as part of NetStandard.   I am looking for guidance on how best to do that.

**Comment by karelz** [comment] 2017-04-14 15:47
I think we run Desktop tests only on latest Desktop version. So maybe you don't need to do anything special. Otherwise, there should be way to tell which test supports which Runtime via attributes.

@weshaggard @mellinoe @joperezr should be able to guide us here ... (my quick search didn't find it, but I have seen it)

**Comment by weshaggard** [comment] 2017-04-14 16:41
Assuming these are in netcoreapp I would add a netcoreapp configuration to the test project and add the tests under that configuration.

Currently our desktop test runs are targeting 4.6.1 (i.e. netfx == net461). Ideally we would target the latest .NET Framework but we decided for this release we would map to 4.6.1 to better enable our NS2.0 verification.

**Comment by ViktorHofer** [comment] 2017-04-15 11:15
Thanks @weshaggard. That means I currently can't enable the tests for netfx. Nevertheless I will enable them for netcoreapp.

**Comment by danmosemsft** [comment] 2017-04-30 21:51
these are the members that aren't exposed:
```
    public abstract class EventListener : IDisposable {
        public event EventHandler<EventSourceCreatedEventArgs> EventSourceCreated;
        public event EventHandler<EventWrittenEventArgs> EventWritten;
    }
    public class EventSourceCreatedEventArgs : EventArgs {
        public EventSourceCreatedEventArgs();
        public EventSource EventSource { get; }
    }
```

**Comment by vancem** [comment] 2017-05-02 17:35
Set to milestone 2, can be pushed out if there is a problem

**Comment by joperezr** [comment] 2017-05-02 18:00
Although it's fine to add the new netcoreapp configuration for 2.0, I think that as discussed in the thread we won't be adding these members back since they are not in netstandard2.0 by design, so I'm not sure if setting milestone to 2.0 is right, but I will let the area owners decide.

**Comment by ViktorHofer** [comment] 2017-05-06 14:44
@danmosemsft I just read that @Petermarcu approved this late api change. I could do that

**Comment by karelz** [comment] 2017-05-06 15:00
@valenis yesterday suggested to push it out ... however, I always prefer to have at least minimal test coverage for APIs, so go for it, assuming there is nothing higher priority you can tackle ;-)

**Comment by ViktorHofer** [comment] 2017-05-06 15:08
I don't think this is something low priority as it involves enlarging the API surface of netcoreapp20 and improving compat with netfx which is definitely welcomed by our customers (even if it's not in netstandard20).

There is one very high issue I'm still investigating, everything else is likely done (awaiting PR feedback).

**Comment by karelz** [comment] 2017-05-06 16:50
EventSource is somewhat special ... it is one of the fastest-evolving parts of .NET Framework. We have even out-of-box Microsoft.DIagnostics.Tracing package to churn even faster for .NET Framework users.
Compat is corner cases can be adjusted, it has a bit lower bar than the rest of .NET Framework.

Please consult with @vancem on the best action for each (potential) bug fix. Either in the form of PR, issue, or offline email/IM - whatever works for you best.

**Comment by ViktorHofer** [comment] 2017-05-09 21:22
As it isn't clear when looking on this issue: PR is finished and ready to sign-off. No further action required.

**Closed** 2017-05-10 22:54 UTC
Labels: api-to-expose-from-coreclr, area-System.Diagnostics.Tracing, test enhancement
