### ISSUE TITLE
`dotnet publish -r win-x64` not publish right version of `System.Data.SqlClient` for `netcoreapp3.0` and get `PlatformNotSupportedException`

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/corefx#37608] opened 2019-05-12 08:17 UTC
```
dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18895
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23
```

Step: 
1. Create two csproj
Main:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>
  
</Project>
```
ClassLibrary1:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview5.19224.8" />
  </ItemGroup>
</Project>
```
Main.cs
```cs
using System;
using System.Data.SqlClient;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            new SqlConnection();
            Console.WriteLine("Hello World!");
        }
    }
}
```
2. `dotnet publish -r win-x64`
3. Run the output file, and see PlatformNotSupportedException

**Comment by karinazhou** [comment] 2019-05-15 00:55
Hi @yyjdelete , thank you for reporting this. I will see whether I can reproduce this on my side.

**Comment by karinazhou** [comment] 2019-05-16 22:20
@yyjdelete  We are able to reproduce this issue locally by following your steps. After some investigation, the problem is due to the wrong `System.Data.SqlClient.dll` in the publish folder. 

The nuget package contains a bunch of `System.Data.SqlClient.dll`s for various platforms. When using `dotnet publish` on your application, it failed to find the correct dll for netcoreapp3.0 so it copied the general one which was in `lib\netcoreapp2.1` as a result. The actual working `System.Data.SqlClient.dll` is in `runtimes\win\lib\netcoreapp2.1` which should be picked up with the executable. 

We have tested **netcoreapp2.1** and `dotnet publish` can work fine without `PlatformNotSupportedException`. However, since we haven't add **netcoreapp3.0** yet and the `System.Data.SqlClient` nuget package uses strong-named assembly, `dotnet publish` is not able to work properly. 

One possible workaround for now is to manually copy the dll file from `runtimes\win\lib\netcoreapp2.1` to the publish folder and this can eliminate the exception. Or you may need to wait for the support of netcoreapp3.0 in the future.

**Comment by lefig** [comment] 2019-05-19 22:05
Hi @karinazhou,

We happen to have the same problem too. It would be sure good to hear that the publish command does indeed get fixed in the next release.

Best

**Comment by cheenamalhotra** [comment] 2019-07-15 23:46
Hi @yyjdelete @lefig 

Have you tried with **.NET Core SDK Version: 3.0.100-preview6-012264**.
This issue seems to occur with older SDKs (preview5) but not with the newer one. Maybe it was fixed with some other changes in SDK.

Please confirm so we will close the issue.

**Comment by yyjdelete** [comment] 2019-07-16 02:03
@cheenamalhotra
Verified this is not happen with preview6 for me.

**Closed** 2019-07-16 02:17 UTC
Labels: area-System.Data.SqlClient
