### ISSUE TITLE
System.Globalization.Extensions and System.IO.FileStream fail

### ISSUE THREAD

**Issue by robbchar** [dotnet/corefx#1089] opened 2015-03-05 06:20 UTC
So, after the fix for #1044 I still can't build. The fails happen in the tests for the above dlls when using corerun.exe. 

The FileStream exception message is
System.UnauthorizedAccessException : Access to the path 'C:\dd\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.IO.FileSystem.Tests\aspnetcore50\FileStream_ctor_str_fm_fa_fs_buffer_fo\FileModeCreate_44' is denied.

The Globalization exception message is:
System.ArgumentException : Decoded string is not a valid IDN name.

Lemme know if any other info would help.

**Comment by leppie** [comment] 2015-03-05 06:33
Getting the same here too. I think this is related to culture issues. My OS setting is `en-ZA`. 

Also getting similar test failures for:
- `System.Numerics.Tests.ToStringTest.RunStandardFormatToStringTests`
- `System.Numerics.Tests.ToStringTest.RunCustomFormatThousandsSeparator`

**Comment by ellismg** [comment] 2015-03-05 07:06
@leppie If you are on Windows 7, The normalization issue is likely #579.  Sounds like there could be some IDN issues on Windows 7 as well (I believe that the  implementation is different).  @robbchar are you on Windows 7? 

The en-ZA locale likely is the cause of the Numerics tests.

We should just do a run off run on Windows 7 and disable all of these tests against bugs until #1058 is addressed.

**Comment by robbchar** [comment] 2015-03-05 07:11
Yep win7 en-US.

**Comment by leppie** [comment] 2015-03-05 07:13
@ellismg You are correct. Win 7 64-bit.

**Comment by eatdrinksleepcode** [comment] 2015-03-25 04:58
Is there any update on this?

**Comment by venkat-raman251** [comment] 2015-03-30 20:53
I haven't been able look at it yet. Will do so later this week.

**Comment by venkat-raman251** [comment] 2015-06-09 23:02
I am sorry that I haven't got the time to look at it yet, will do so as soon as I can.

**Comment by joshfree** [comment] 2015-10-09 20:14
Closing as we now have Windows7 rolling test runs for corefx.

**Closed by joshfree** 2015-10-09 20:14 UTC
Labels: bug, grabbed by assignee
