### ISSUE TITLE
StartsWith/EndsWith not giving expected results on Linux

### ISSUE THREAD

**Issue by asthana86** [dotnet/corefx#29503] opened 2018-05-04 02:31 UTC
Both of these are passing on Windows but failing on Linux (Ubuntu 16.04 over WSL). Also fails if I use the invariant comparison.

Debug.Assert("\r\n".EndsWith("\n"));
Debug.Assert("\r\n".StartsWith("\r"));

**Comment by jkotas** [comment] 2018-05-04 03:44
Duplicate of #29474

**Closed by jkotas** 2018-05-04 03:44 UTC
Labels: area-System.Diagnostics
