### ISSUE TITLE
[Uri] Uri.IsWellFormedUriString() different behaviour from net461

### ISSUE THREAD

**Issue by nickbom** [dotnet/corefx#34032] opened 2018-12-12 20:16 UTC
The following unit test for `Uri.IsWellFormedUriString("lime://teste_it%C3%A1vel%3Axx@teste.net/8dd3a58vgv", UriKind.Absolute)`

return true on TargetFramework=net461

return false on TargetFramework=netcoreapp2.1

Is this different behaviour expected?

**Comment by karelz** [comment] 2018-12-12 22:54
Duplicate of #19630

**Closed by karelz** 2018-12-12 22:54 UTC
Labels: area-System.Net
