### ISSUE TITLE
JsonSerializer.Parse<T>() throws if object has an collection property with a default array value

### ISSUE THREAD

**Issue by martincostello** [dotnet/corefx#38640] opened 2019-06-18 13:21 UTC
Using 3.0.100-preview6-012264 of the .NET Core 3.0 SDK, if a type which sets a collection property to a default value which is an array, then the deserialization fails with the following exception:

```
System.NotSupportedException: Collection was of a fixed size.
   at System.Array.System.Collections.IList.Add(Object value)
   at System.Text.Json.Serialization.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Utf8JsonReader& reader, Boolean setPropertyDirectly)
   at System.Text.Json.Serialization.JsonSerializer.HandleEndObject(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)
```

It would appear that the serializer assumes the non-null default collection can be written to, and then fails to add the item as the backing implementation is an array. The unit test below demonstrates the difference in behaviour with System.Text.Json for the two objects, as well as the same behaviour using JSON .NET to perform the same operation.

Ideally the implementation would do something like check the value of the `IsReadOnly` property of the collection/list, and if it is `true` create a new list to append the items to and assign that value to the property.

```csharp
using System;
using System.Collections.Generic;
using Xunit;
using JsonConvert = Newtonsoft.Json.JsonConvert;
using JsonSerializer = System.Text.Json.Serialization.JsonSerializer;

namespace JsonSerializerNotSupportedException
{
    public static class Repro
    {
        [Fact]
        public static void Can_Deserialize_Object_With_Default_Array_SystemTextJson()
        {
            // Arrange
            string json = @"{""Messages"":[""Hello"",""World""]}";

            // Act (fails in preview 6, throws: System.NotSupportedException : Collection was of a fixed size.)
            var actual = JsonSerializer.Parse<MessageWithDefaultArray>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Messages);
            Assert.Equal(new[] { "Hello", "World" }, actual.Messages);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_Default_List_SystemTextJson()
        {
            // Arrange
            string json = @"{""Messages"":[""Hello"",""World""]}";

            // Act
            var actual = JsonSerializer.Parse<MessageWithDefaultList>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Messages);
            Assert.Equal(new[] { "Hello", "World" }, actual.Messages);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_Default_Array_NewtonsoftJson()
        {
            // Arrange
            string json = @"{""Messages"":[""Hello"",""World""]}";

            // Act (fails in preview 6, throws: System.NotSupportedException : Collection was of a fixed size.)
            var actual = JsonConvert.DeserializeObject<MessageWithDefaultArray>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Messages);
            Assert.Equal(new[] { "Hello", "World" }, actual.Messages);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_Default_List_NewtonsoftJson()
        {
            // Arrange
            string json = @"{""Messages"":[""Hello"",""World""]}";

            // Act
            var actual = JsonConvert.DeserializeObject<MessageWithDefaultList>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Messages);
            Assert.Equal(new[] { "Hello", "World" }, actual.Messages);
        }

        private sealed class MessageWithDefaultArray
        {
            public IList<string> Messages { get; set; } = Array.Empty<string>();
        }

        private sealed class MessageWithDefaultList
        {
            public IList<string> Messages { get; set; } = new List<string>();
        }
    }
}
```

**Comment by ahsonkhan** [comment] 2019-06-18 21:31
This is a duplicate of https://github.com/dotnet/corefx/issues/38435

**Closed by ahsonkhan** 2019-06-18 21:31 UTC
Labels: area-System.Text.Json
