### ISSUE TITLE
mutable structs as readonly field should be a warning

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/corefx#34918] opened 2019-01-29 04:47 UTC
for beginners this behavior can be unexpected. (yes it happened to me before). especially if you are using a library and you are not sure if struct is safe to be readonly or not. for example SpinLock must not be readonly.

```c#
readonly MutableStruct x; // make this a warning
```

If struct is immutable (via c# 7.2 readonly keyword) its ok to have it as readonly field.

**Comment by tannergooding** [comment] 2019-01-29 04:55
This should likely be in the dotnet/csharplang repo. It is worth noting that this can't be done currently because it would be a breaking change (without some other feature like warning waves). There are also several similar proposals around this and true immutability in the csharplang repo already.

Writing an analyzer that looks for this pattern and flags it would be your next best option.

**Comment by benaadams** [comment] 2019-01-29 05:04
Is an issue in roslyn for it https://github.com/dotnet/roslyn/issues/17310

**Comment by benaadams** [comment] 2019-01-29 05:05
Is an issue in roslyn for it dotnet/roslyn#17310 (also is about spinlock)

**Comment by karelz** [comment] 2019-02-22 01:43
Duplicate of https://github.com/dotnet/roslyn/issues/17310

**Closed by karelz** 2019-02-22 01:43 UTC
