### ISSUE TITLE
Feature request: Support for Unix-style environment variables

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/corefx#31274] opened 2018-07-23 17:09 UTC
(I copied this from [my closed Mono issue](https://github.com/mono/mono/issues/9679#event-1747560652) so it's still using that template/format)

## Steps to Reproduce

My test code originally looked like this, and I was confused to why it didn't work on Linux:

    if(os == 2) { // Windows
        finalPath = (System.Environment.ExpandEnvironmentVariables("%HOMEDRIVE%%HOMEPATH%") + "blahblah");
    }

    if(os == 4) { // Linux
        finalPath = (System.Environment.ExpandEnvironmentVariables("$HOME") + "blahblah");
    }

### Current Behavior

Environment variables written in the Unix style (`$HOME` etc) instead of the Windows style (`%HOME%` etc) are not resolved by this function. Windows style does work for Unix variables.

### Expected Behavior

I expected Mono to support both types of environment variables, so I originally used `$HOME`. I believe Mono should detect this, so treat all text following dollar signs as an environment variable just as it treats all text in-between percent signs as one.

The work-around is to write environment variables in the Windows style, even on Unix-like platforms. `%HOME%` resolves to what `$HOME` would in a Unix terminal.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**: 5.12

This might be a C# language or .NET issue, I'm not sure who handles the code inside of `System`.

**Comment by danmosemsft** [comment] 2018-07-23 17:17
This is a dupe of https://github.com/dotnet/corefx/issues/28890 where there were concerns about compat. Feel free to add comments there.

**Closed by danmosemsft** 2018-07-23 17:17 UTC
