### ISSUE TITLE
DangerousCreate throws NullReferenceException if obj is null

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#26124] opened 2018-01-03 12:45 UTC
Was using System.Memory (4.5.0-preview1-26025-02) on .NET Core 2.0 (not using the portable span).

```C#
byte x = 10;
Span<byte>.DangerousCreate(null, ref x, 1);
```

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Span`1.DangerousCreate(Object obj, T& objectData, Int32 length)
   at ConsoleApp41.Program.<Main>d__0.MoveNext() in C:\Users\dfowler\documents\visual studio 2017\Projects\ConsoleApp41\ConsoleApp41\Program.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ConsoleApp41.Program.<Main>(String[] args)
```
  
/cc @ahsonkhan

**Comment by jkotas** [comment] 2018-01-03 15:56
DangerousCreate expects `o` to be non-null. You should not be using this method if there is no wrapping object. Use constructor that takes `void*, int` instead.

**Comment by jkotas** [comment] 2018-01-03 15:57
DangerousCreate expects `o` to be non-null. You should not be using this method if there is no wrapping object. Use constructor that takes `void*, int` instead.

**Comment by Joe4evr** [comment] 2018-01-03 19:44
`Dangerous` methods are dangerous, who'd have thunk it? 🙃

**Comment by danmosemsft** [comment] 2018-01-03 21:31
Shouldn't it be ArgumentNullException? Or is this so hot a path that we don't even want to check.

**Comment by jkotas** [comment] 2018-01-03 21:53
Yes, this method was not meant to have argument checks (because of proper argument checks would make it a lot slower - it is not just about checking for null).

**Comment by davidfowl** [comment] 2018-01-03 22:07
I see. Well I believe that code “works” with built in span (doesn’t blow up) and fails with portable span.

**Comment by ahsonkhan** [comment] 2018-01-05 21:51
> Well I believe that code “works” with built in span (doesn’t blow up) and fails with portable span.

The built in span does nothing with the first argument (unlike the portable one):
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/ReadOnlySpan.cs#L110
```C#
public static ReadOnlySpan<T> DangerousCreate(object obj, ref T objectData, int length) => new ReadOnlySpan<T>(ref objectData, length);
```

The argument validation was removed in https://github.com/dotnet/coreclr/commit/7e5aef990eb4c8d7b34fc5f8a9a1fd5ed326410d (from https://github.com/dotnet/coreclr/pull/10462)

**Comment by tarekgh** [comment] 2018-01-09 17:04
@jkotas The portable implementation depends on the object 

https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/ReadOnlySpan.cs#L105

do you think this implementation can be changed to avoid dependency on the object? or we just close this issue as by design and we know we'll have some behavior difference between the portable and built-in implementation?

**Comment by jkotas** [comment] 2018-01-09 17:06
> do you think this implementation can be changed to avoid dependency on the object?

No. It is not possible.

> or we just close this issue as by design

Yes, I think this issue should be closed as by design.

**Comment by tarekgh** [comment] 2018-01-09 17:10
closing it per @jkotas comment.

**Closed by tarekgh** 2018-01-09 17:10 UTC
Labels: area-System.Memory, bug
