### ISSUE TITLE
Some fields of RSAParameters are marked as NotSerialized

### ISSUE THREAD

**Issue by ForkBug** [dotnet/corefx#23847] opened 2017-09-07 08:49 UTC
When RSAParameters is serialized by json.net, The private key is not included.
It due to some fields of RSAParameters(D, Q, etc) are marked as NotSerialized.

NotSerialized should means "This field is meaningless for serialization", not "This field is too important so we couldn't do serialize for it"

**Comment by ViktorHofer** [comment] 2017-09-07 11:08
Hi ForkBug, thanks for the report. I need more info for that as I don't fully understand why this is happening.

In .NET Framework those members are marked as [NotSerialized]: https://source.dot.net/#System.Security.Cryptography.Algorithms/System/Security/Cryptography/RSAParameters.cs,dfd6cfff509b13df

In .NET Core 1.1 those members aren't marked as [NotSerialized] because we hadn't binary serialization support at all: https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAParameters.cs

In .NET Core 2.0 those members are now marked as [NotSerialized] because we brought back binary serialization: https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAParameters.cs

And to complicate it even more, I removed those parameters in master because the type isn't serializable anymore (by binaryformatter): https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAParameters.cs

These types were not meant to be serialized to begin with (to mimic .NET Frameworks behavior). So I guess the 1.1 behavior is the wrong one. I need to talk to the team about that and will get back to this thread later.

cc @stephentoub

**Comment by ViktorHofer** [comment] 2017-09-07 11:53
After talking to Stephen, it seems that Json.NET isn't following the guidelines here. The `NotSerializedAttribute` is only intended to be used in conjunction with the runtime serialization feature which means it should be ignored if the type itself is not serializable (`Type.IsSerializable` returns false).

In this case `RSAParameters` isn't marked as serializable anymore (because we removed serialization support for it) in .NET Core 2.0. Therefore serialization engines should also ignore the [NotSerialized] attributes on the types members. That's the reason why I removed the attributes from it a few weeks ago: https://github.com/dotnet/corefx/commit/7eed79faf47e8e8dbe1645fb002e52c306867347

cc @JamesNK

**Comment by ForkBug** [comment] 2017-09-07 14:52
These fields are marked as NotSerialized by the dev team because the private key is sensitive data.
If I misunderstand this behavior,  please tell me.

The main purpose of NonSerializedAttribute could be:
1. For data not suitable for serialization. For example, object creating timestamp.
2. Sensitive data.
Serializing a field with NonSerializedAttribute is dirty work. We have to write extra, ugly code to do this.

The point is,  who could judge whether a piece of data is sensitive or not? The app or the framework/lib? 
An app may generate many many RSAParameters to try to find out Q's pattern. In this case D,Q... are not sensitive obviously.

Some fields are marked as NonSerializedAttribute, actually disable part of functionality of RSA module. We couldn't store it in a simple step, no matter how secure the app is.

IMHO, NonSerializedAttribute  for sensitive data, is a usage for app, not for framework/lib.

**Comment by ViktorHofer** [comment] 2017-09-07 15:01
> These fields are marked as NotSerialized by the dev team because the private key is sensitive data in release 2.0.

Not true. I am part of the dev team and the cleanup of `NotSerializedAttribute` on non-serialized types was just something we hadn't time before 2.0, that's why it is changed in master but not in release/2.0.0.

**Comment by stephentoub** [comment] 2017-09-07 15:04
@ForkBug, is your question specific to .NET Core?  It seems like you're asking more generally about why these fields are marked as [NotSerialized] in the .NET Framework?

**Comment by ForkBug** [comment] 2017-09-07 15:17
@stephentoub Yes. But I think RSAParameters in https://github.com/dotnet/corefx is the only active implement, no matter .NET Core or .NET Framework, since .net standard 1.0 was created. Is it right?

**Comment by stephentoub** [comment] 2017-09-07 15:20
> Is it right?

No, they are two separate implementations, it's just that .NET Core is open source and .NET Framework is not.   Both provide an implementation of the .NET Standard.

**Comment by ForkBug** [comment] 2017-09-07 15:34
Two different active implement of one .NET Standard class, which could be referenced freely by any .NET Framework or  .NET Core apps, may bring some bugs hardly to fix for users.

**Comment by joperezr** [comment] 2017-10-04 17:45
@ViktorHofer can this issue be closed now? Wanted to make sure before I do it.

**Comment by ViktorHofer** [comment] 2017-10-04 17:51
Yes. The issue needs to be fixed by @jamesnk.

**Closed by ViktorHofer** 2017-10-04 17:51 UTC
Labels: area-System.Runtime.Extensions

**Comment by ekarimi** [comment] 2017-10-16 11:11
@stephentoub
Why these fields are marked as [NotSerialized] in the .NET Framework?

You didn't answer it and I can't find the reason. It's just a general question and it's not related to this issue I think.

**Comment by stephentoub** [comment] 2017-10-16 12:20
> Why these fields are marked as [NotSerialized] in the .NET Framework?

I don't know the history here.

**Comment by TingluoHuang** [comment] 2018-04-27 15:45
@ViktorHofer the same issue also reported in Newtonsoft but got closed as by design. https://github.com/JamesNK/Newtonsoft.Json/issues/1517

**Comment by DemoBytom** [comment] 2018-05-08 11:14
We're currently using this class, since `RSAParameters` is not serializable in _Core 2.0_:
```csharp
public class RSAParametersSerializable : ISerializable
{
    private RSAParameters _rsaParams;
    public RSAParameters RSAParameters => _rsaParams;

    public RSAParametersSerializable()
    {
    }

    public RSAParametersSerializable(RSAParameters rsaParameters)
    {
        _rsaParams = rsaParameters;
    }

    public RSAParametersSerializable(SerializationInfo info, StreamingContext context)
    {
        _rsaParams = new RSAParameters()
        {
            D = (byte[])info.GetValue(nameof(RSAParameters.D), typeof(byte[])),
            DP = (byte[])info.GetValue(nameof(RSAParameters.DP), typeof(byte[])),
            DQ = (byte[])info.GetValue(nameof(RSAParameters.DQ), typeof(byte[])),
            Exponent = (byte[])info.GetValue(nameof(RSAParameters.Exponent), typeof(byte[])),
            InverseQ = (byte[])info.GetValue(nameof(RSAParameters.InverseQ), typeof(byte[])),
            Modulus = (byte[])info.GetValue(nameof(RSAParameters.Modulus), typeof(byte[])),
            P = (byte[])info.GetValue(nameof(RSAParameters.P), typeof(byte[])),
            Q = (byte[])info.GetValue(nameof(RSAParameters.Q), typeof(byte[])),
        };
    }

    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue(nameof(RSAParameters.D), _rsaParams.D);
        info.AddValue(nameof(RSAParameters.DP), _rsaParams.DP);
        info.AddValue(nameof(RSAParameters.DQ), _rsaParams.DQ);
        info.AddValue(nameof(RSAParameters.Exponent), _rsaParams.Exponent);
        info.AddValue(nameof(RSAParameters.InverseQ), _rsaParams.InverseQ);
        info.AddValue(nameof(RSAParameters.Modulus), _rsaParams.Modulus);
        info.AddValue(nameof(RSAParameters.P), _rsaParams.P);
        info.AddValue(nameof(RSAParameters.Q), _rsaParams.Q);
    }

    //
    // Summary:
    //     Represents the D parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] D { get => _rsaParams.D; set => _rsaParams.D = value; }

    //
    // Summary:
    //     Represents the DP parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] DP { get => _rsaParams.DP; set => _rsaParams.DP = value; }

    //
    // Summary:
    //     Represents the DQ parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] DQ { get => _rsaParams.DQ; set => _rsaParams.DQ = value; }

    //
    // Summary:
    //     Represents the Exponent parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] Exponent { get => _rsaParams.Exponent; set => _rsaParams.Exponent = value; }

    //
    // Summary:
    //     Represents the InverseQ parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] InverseQ { get => _rsaParams.InverseQ; set => _rsaParams.InverseQ = value; }

    //
    // Summary:
    //     Represents the Modulus parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] Modulus { get => _rsaParams.Modulus; set => _rsaParams.Modulus = value; }

    //
    // Summary:
    //     Represents the P parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] P { get => _rsaParams.P; set => _rsaParams.P = value; }

    //
    // Summary:
    //     Represents the Q parameter for the System.Security.Cryptography.RSA algorithm.
    public byte[] Q { get => _rsaParams.Q; set => _rsaParams.Q = value; }
}
```
To get around the serialization and deserialization of the `RSAParameters`

```csharp
var serialized = JsonConvert.SerializeObject(new RSAParametersSerializable(rsaParameters));
var deserialized = JsonConvert.DeserializeObject<RSAParametersSerializable>(serialized ).RSAParameters;
```
