### ISSUE TITLE
System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24807] opened 2017-10-23 06:35 UTC
Failed test: System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release/3401/testReport/System.Net.Mail.Tests/LoggingTest/EventSource_EventsRaisedAsExpected/

Configuration: osx10.12_release

MESSAGE:
~~~
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() 
in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 189
~~~

**Comment by danmosemsft** [comment] 2017-10-23 15:54
@vancem ...
```
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018: The "ConvertPortablePdbsToWindowsPdbs" task failed unexpectedly. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DiaSymReader.Converter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:  [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018: File name: 'Microsoft.DiaSymReader.Converter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:    at Microsoft.DotNet.Build.Tasks.ConvertPortablePdbsToWindowsPdbs.Execute() [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:  [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/Tools/CodeCoverage.targets(73,5): warning MSB4018:  [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release/src/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
  Replacing Portable PDB with Windows Pdb in place!
```

**Comment by vancem** [comment] 2017-10-26 18:38
I will have  fix for the failure of the portable->windows conversion mentioned above (it should not be run at all on non-windows platforms).  However I would be surprised my fix will change the outcome of the test (it will simply clean up the log).

**Comment by Sunny-pu** [comment] 2017-12-01 08:10
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/260/testReport/System.Net.Mail.Tests/LoggingTest/EventSource_EventsRaisedAsExpected/

**Comment by vancem** [comment] 2017-12-01 16:45
I am assuming that this is a non-deterministic (and rare) error.  Please correct me if I am wrong. 

Looking at the error detail
```
2:14:30   xUnit.net console test runner (64-bit .NET Core)
12:14:30   Copyright (C) 2014 Outercurve Foundation.
12:14:30   
12:14:30   Discovering: System.Net.Mail.Functional.Tests
12:14:31   Discovered:  System.Net.Mail.Functional.Tests
12:14:31   Starting:    System.Net.Mail.Functional.Tests
12:14:32 
  A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/
12:14:33 
     System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
12:14:33         Exit code was 131 but it should have been 42
12:14:33         Expected: True
12:14:33         Actual:   False
12:14:33         Stack Trace:
12:14:33            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(203,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
12:14:35   Finished:    System.Net.Mail.Functional.Tests
```
This seems to be some sort loader issue with libhostfxr.dylib  which I am guessing is something to do with the test host.   

We probably need to bring in some expertise with this DLL and how it is deployed.   It seems to have little to do with the actual code being tested.

**Comment by karelz** [comment] 2017-12-29 01:15
Duplicate of #26042

**Closed by karelz** 2017-12-29 01:15 UTC
Labels: area-System.Net, os-mac-os-x, test-run-core
