### ISSUE TITLE
Update firewall settings on Fedora and Redhat images to allow network testing.

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#13323] opened 2016-11-03 18:27 UTC
Since October 25th, the outerloop runs for Fedora 23 have been timing out. The same is occurring in Fedora 24, although those have just been enabled. In both cases, the inner loop runs are completing successfully.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/

Nothing is jumping out at me other than the fact that there is a large gap in timestamps before the build times out.

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_debug/47/console
```
20:25:56   Finished running tests. End time=20:26:09. Return value was 0
21:35:10 
Build timed out (after 120 minutes). Marking the build as aborted.
```

**Comment by karelz** [comment] 2016-11-04 00:11
Who has any expertise how to debug it?

cc: @danmosemsft, @weshaggard

**Comment by stephentoub** [comment] 2016-11-04 03:25
It looks like the System.Net.Sockets.Tests tests are hanging.

**Comment by stephentoub** [comment] 2016-11-04 03:38
I found one of the machines that currently hanging.  It's the System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds test.

**Comment by mellinoe** [comment] 2016-11-16 20:32
I debugged this and found that the test is hanging at this call:
https://github.com/dotnet/corefx/blob/a7a3d8b1dd428bd449c7b90d29a729bc19184364/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs#L153

There is a thread waiting at this line in `SocketAsyncEngine.EventLoop`:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L266

Does anyone have any ideas as to why this would be hanging on Fedora only?

**Comment by mellinoe** [comment] 2016-11-21 19:22
@karelz This doesn't seem to be an infrastructure bug to me anymore. I put it into the "System.Net" area, but I'm not sure who is the best person to investigate this.

**Comment by tmds** [comment] 2016-11-22 10:30
@mellinoe if I turn this into a Console app and run it on Fedora 24 with .NET Core 1.1, it doesn't hang.

Console app: https://gist.github.com/tmds/0684ad0f3e858879bd59913095240f15

**Comment by mellinoe** [comment] 2016-11-22 10:42
@tmds Hm, interesting. Perhaps it has something to do with XUnit's custom SynchronizationContext?

**Comment by tmds** [comment] 2016-11-22 10:51
@mellinoe the test is trying to receive an udp message which was sent 10 times (for redundancy) on the "default network interface". The issue may be related to the network settings on the test machine. If that is the case, the console app should also fail on the test machine.

**Comment by stephentoub** [comment] 2016-11-22 12:57
> if I turn this into a Console app and run it on Fedora 24 with .NET Core 1.1, it doesn't hang.

@tmds, so it hangs for you when you run it as a test, but it doesn't when run in a console app, on the same machine?

**Comment by tmds** [comment] 2016-11-22 13:46
> @tmds, so it hangs for you when you run it as a test, but it doesn't when run in a console app, on the same machine?

Haven't tried to reproduce the hanging test. Will give it a try.

**Comment by tmds** [comment] 2016-11-22 16:22
This isn't going well...
```
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/coveralls.io/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/coveralls.io/index.json' has timed out after 100000ms.
strace: Process 14222 attached
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/coveralls.io/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/coveralls.io/index.json' has timed out after 100000ms.
info : An error was encountered when fetching 'GET https://www.nuget.org/api/v2/FindPackagesById()?id='coveralls.io''. The request will now be retried.
info : The HTTP request to 'GET https://www.nuget.org/api/v2/FindPackagesById()?id='coveralls.io'' has timed out after 100000ms.
```

**Comment by karelz** [comment] 2016-11-22 16:43
That's unrelated problem - you are unable to sync. Maybe a firewall?

**Comment by tmds** [comment] 2016-11-22 16:55
> That's unrelated problem - you are unable to sync. Maybe a firewall?

Don't think that's it. I can wget those urls. When I run the same thing in my ubuntu vm, it works fine. Going to give it a try in Fedora 23.

**Comment by mellinoe** [comment] 2016-11-22 17:45
>This isn't going well...

Can you try upgrading your "nss" package with `dnf`? We were hitting similar problems in our CI runs before we did that. On Fedora 24 primarily.

**Comment by tmds** [comment] 2016-11-23 09:53
Tests run fine on my machine:
```
  === TEST EXECUTION SUMMARY ===
     System.Net.Sockets.Tests  Total: 502, Errors: 0, Failed: 0, Skipped: 0, Time: 3.870s
```
This test has the [Outerloop] attribute. Am I sure it gets executed?

Off topic:
I ran the ./build.sh script to get everything built and the test executed. This off course took a long time. Was there a shorter way?
Suppose I now want to go and make some changes to the managed&native part and verify those with a specific test suite. What commands could I use for that?

@mellinoe any idea why the nss upgrade fixes the 'dotnet restore'?

**Comment by mellinoe** [comment] 2016-11-23 10:10
> @mellinoe any idea why the nss upgrade fixes the 'dotnet restore'?

Not specifically. On Fedora, libcurl uses NSS for SSL handling, so presumably it has some effect on the code that handles downloading stuff in NuGet. Beyond that we didn't really understand what exactly was going wrong.

>This test has the [Outerloop] attribute. Does it get executed?

Not by default, no (using `/t:rebuildandtest`). It's probably easiest to just navigate to the test runtime directory and run `./corerun xunit.console.netcore.exe System.Net.Sockets.Tests.dll -method System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds`. That's how I was repro'ing it.

**Comment by mellinoe** [comment] 2016-11-23 10:15
> Off topic:
I ran the ./build.sh script to get everything built and the test executed. This off course took a long time. Was there a shorter way?
Suppose I now want to go and make some changes to the managed&native part and verify those with a specific test suite. What commands could I use for that?

The easiest way to run tests for a single project is to run `Tools/msbuild.sh /t:rebuildandtest <test-project-file>`. Thanks to a recent change, it will now automatically detect the runtime you are on and run the tests for you.

When tests are built, a private runtime is copied into some test subdirectory, and this includes all of the runtime dependencies needed for the test, including the test assembly, it's dependencies, CoreCLR, etc. The location of this is printed out when you run msbuild. After that is built for the first time, you can copy stuff into that directory, and then re-run the tests by directly invoking the test runner. There's a bit more information here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

**Comment by tmds** [comment] 2016-11-23 10:45
Thanks @mellinoe 

The test succeeds:
```
$ ./corerun xunit.console.netcore.exe System.Net.Sockets.Tests.dll -method System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.Sockets.Tests
Discovered:  System.Net.Sockets.Tests
Starting:    System.Net.Sockets.Tests
Finished:    System.Net.Sockets.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.318s
```

**Comment by stephentoub** [comment] 2016-11-23 11:17
(fyi, you can also add /p:Outerloop=true to the msbuild command to include outerloop tests)

**Comment by Priya91** [comment] 2017-02-14 23:56
Debugged through this on a machine where the test is hanging on redhat. When setting the network interface index to 1 (lo) the test passes, and setting index to 2 (eth0) the test hangs, index 2 corresponds to eth0 network interface.. On machine where the test passed, the socket is able to receive on both network interface indexes 1,2. It only makes sense to conclude that the default network interface eth0 is not configured correctly on failing machine, am not sure what to look for.

cc @tmds Do you have any ideas? This happens only on some redhat and fedora machines.

**Comment by tmds** [comment] 2017-02-15 05:37
@Priya91 can you try this on the CI machine.
1. run `/sbin/ifconfig`
verify the interface has flags like this:
```
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
```
2. run `route -n`, the output will tell you what linux thinks is the default interface for multicast traffic
3. Compile and strace [Program.cs](https://gist.githubusercontent.com/tmds/0684ad0f3e858879bd59913095240f15/raw/f15e647cbc58b05fb460a67cf43b746a476f0a01/gistfile1.txt): `strace -f -e socket,setsockopt,sendmsg,recvmsg dotnet bin/Debug/netcoreapp1.1/<name>.dll`
On my machine the output is:
```
strace: Process 4113 attached
[pid  4113] socket(PF_LOCAL, SOCK_STREAM, 0) = 5
strace: Process 4114 attached
[pid  4114] socket(PF_LOCAL, SOCK_STREAM, 0) = 6
strace: Process 4115 attached
strace: Process 4116 attached
strace: Process 4117 attached
strace: Process 4118 attached
Hello World!
[pid  4112] socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 31
[pid  4112] sendmsg(31, {msg_name(16)={sa_family=AF_INET, sin_port=htons(54320), sin_addr=inet_addr("239.1.1.1")}, msg_iov(1)=[{"dummy message", 13}], msg_controllen=0, msg_flags=0}, 0) = 13
[pid  4112] socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 32
[pid  4112] setsockopt(31, SOL_SOCKET, SO_RCVTIMEO, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  4112] setsockopt(31, SOL_IP, IP_ADD_MEMBERSHIP, {imr_multiaddr=inet_addr("239.1.2.3"), imr_interface=inet_addr("0.0.0.0")}, 12) = 0
[pid  4112] setsockopt(32, SOL_IP, IP_MULTICAST_IF, "\0\0\0\0\0\0\0\0\0\0\0\0", 12) = 0
[pid  4112] recvmsg(31, 0x7ffd81e25fc8, 0) = -1 EAGAIN (Resource temporarily unavailable)
strace: Process 4119 attached
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid  4112] sendmsg(32, {msg_name(16)={sa_family=AF_INET, sin_port=htons(38210), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Await receive
[pid  4119] recvmsg(31, {msg_name(0)=NULL, msg_iov(1)=[{"hello", 1024}], msg_controllen=0, msg_flags=0}, 0) = 5
strace: Process 4120 attached
strace: Process 4121 attached
strace: Process 4122 attached
Finished await receive
[pid  4118] +++ exited with 0 +++
[pid  4120] +++ exited with 0 +++
[pid  4119] +++ exited with 0 +++
[pid  4117] +++ exited with 0 +++
[pid  4116] +++ exited with 0 +++
[pid  4122] +++ exited with 0 +++
[pid  4115] +++ exited with 0 +++
[pid  4114] +++ exited with 0 +++
[pid  4113] +++ exited with 0 +++
[pid  4121] +++ exited with 0 +++
+++ exited with 0 +++
```

**Comment by Priya91** [comment] 2017-02-15 21:10
@tmds 

ifconfig has the following output:

```
[helixbot@dnbrh07020001HX ~]$ ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
```

and strace has this output, it's waiting for recvmsg,

```
[helixbot@dnbrh07020001HX netcoreapp1.0]$ strace -f -e socket,setsockopt,sendmsg,recvmsg ./corerun testsocket.dll
Process 52730 attached
Process 52731 attached
Process 52732 attached
Process 52733 attached
Hello World!
[pid 52729] socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 47
[pid 52729] sendmsg(47, {msg_name(16)={sa_family=AF_INET, sin_port=htons(54320), sin_addr=inet_addr("239.1.1.1")}, msg_iov(1)=[{"dummy message", 13}], msg_controllen=0, msg_flags=0}, 0) = 13
[pid 52729] socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 49
[pid 52729] setsockopt(47, SOL_SOCKET, SO_RCVTIMEO, "\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid 52729] setsockopt(47, SOL_IP, IP_ADD_MEMBERSHIP, "\357\1\2\3\0\0\0\0\0\0\0\0", 12) = 0
[pid 52729] setsockopt(49, SOL_IP, IP_MULTICAST_IF, "\0\0\0\0\0\0\0\0\0\0\0\0", 12) = 0
[pid 52729] recvmsg(47, 0x7fff1abf3d18, 0) = -1 EAGAIN (Resource temporarily unavailable)
Process 52735 attached
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Send msg
[pid 52729] sendmsg(49, {msg_name(16)={sa_family=AF_INET, sin_port=htons(58150), sin_addr=inet_addr("239.1.2.3")}, msg_iov(1)=[{"hello", 5}], msg_controllen=0, msg_flags=0}, 0) = 5
Sent msg
Await receive

```

**Comment by tmds** [comment] 2017-02-16 09:16
@Priya91 that looks fine. Perhaps packets are blocked by the firewall? Try `systemctl stop firewalld` and then run the Program. If that doesn't help, try disabling the service (`systemctl disable firewalld`) and a reboot and then run the program.

**Comment by Priya91** [comment] 2017-02-16 19:04
@tmds after stopping firewall the app worked, although how do i just disable for this app like on windows, instead of entirely disabling firewall. I tried this,

```
[helixbot@dnbrh07020001HX netcoreapp1.0]$ sudo firewall-cmd --zone=public --add-service=udp
Error: INVALID_SERVICE: udp
```

**Comment by tmds** [comment] 2017-02-16 20:09
@Priya91 
you can find the local port range by executing `sysctl net.ipv4.ip_local_port_range`
to allow a udp port range do something like this: `firewall-cmd --zone=public --add-port=4990-4999/udp`
adding the `--permanent` flag will make this persistent. You need to restart the firewall to make it use the permanent rule.

**Comment by Priya91** [comment] 2017-02-16 21:33
@tmds The tests uses ports that are out of 4990-4999 range for udp.. how did you get this range of ports?

**Comment by Priya91** [comment] 2017-02-17 01:33
Adding area-infrastructure tag to pop the issue in their query.

**Comment by mellinoe** [comment] 2017-02-17 01:38
If we know what the exact fix is, feel free to update the machine images. Have we seen this outside of the Fedora 23/24 runs in Jenkins here (e.g. Helix or elsewhere)?

**Comment by Priya91** [comment] 2017-02-17 02:50
These are the changes required to be done in the following images:

1.	Redhat image on Helix builds
2.	Fedora23 and Fedora24 images on Jenkins builds

Change to be made:

-	Figure out the ipv4 range of ports using,
sysctl net.ipv4.ip_local_port_range

-	Set firewall policy to allow udp packets on that range,
sudo  firewall-cmd --permanent --zone=public  --add-port=*startport*-*endport*/udp

**Comment by karelz** [comment] 2017-02-17 05:03
@Priya91 please use only [1 area path](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). Feel free to change the area path if you think it is more infra issue (creating a new one with better title might be better IMO). Or just add folks based on [area owners/experts](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas).

**Comment by Priya91** [comment] 2017-02-17 19:31
Marking it as infra, since the work left here is to change the build image.

**Comment by karelz** [comment] 2017-02-22 21:35
@Priya91 can you please update the title to capture what the issue is now tracking?

**Comment by Priya91** [comment] 2017-02-22 22:43
Changed the title.

**Comment by tmds** [comment] 2017-02-23 08:10
@Priya91 when do you want to re-enable the tests?

**Comment by Priya91** [comment] 2017-02-23 21:50
>@Priya91 when do you want to re-enable the tests?

Once we've updated the machines. @MattGal is tracking it, Matt, can you please provide the link to corresponding tracking workitem.

**Comment by MattGal** [comment] 2017-02-23 22:23
I should have this down by end-of-week.  Tracking item is https://github.com/dotnet/core-eng/issues/478.

**Closed** 2017-02-25 00:13 UTC
Labels: area-Infrastructure, os-linux, test bug

**Comment by karelz** [comment] 2017-02-25 00:42
@Priya91 how was the PR #16450 related to this issue? I thought this one is tracking the infra problem ...

**Comment by Priya91** [comment] 2017-02-25 00:45
@karelz Yes, @MattGal informed offline, that he had patched up the machines, hence re-enabled the test.
