### ISSUE TITLE
Inconsistent build via build.cmd vs. individual projects

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/corefx#34505] opened 2019-01-10 19:16 UTC
Build behavior is different whether you build the entire repo via `build.cmd` or directly invoke `msbuild` on an individual project, such as System.Threading.csproj.

When building via build.cmd on Windows the output directory for System.Threading is `netcoreapp-Windows_NT`. When building the .csproj individually it is `netcoreapp-Windows_NT-Debug`. 

Build should be consistent for various reasons, such as incrementality etc. Additionally this breaks tool support such as https://github.com/dotnet/source-indexer that is used to populate https://source.dot.net.

The reason is that global build passes the `Configuration` property as global property and it is set to `netcoreapp-Windows_NT` when building on Windows. The default for the Configuration property should be calculated uniformly for all projects.

As far as I can see the relevant files are generated under `artifacts\toolset\Common\configuration`:
```
        artifacts\toolset\Common
            configuration
                configuration.props
                setConfiguration.netcoreapp-Windows_NT.props
                setConfiguration.props
```

**Comment by stephentoub** [comment] 2019-01-10 19:51
cc: @safern, @ViktorHofer, @ericstj

**Comment by ericstj** [comment] 2019-01-10 19:52
I was already tracking this with https://github.com/dotnet/corefx/issues/33465.  I attempted a fix once but had to undo it.

**Comment by safern** [comment] 2019-01-10 19:54
I think we can close this as a dupe of: #33465 as @ericstj pointed out.

**Closed by safern** 2019-01-10 19:54 UTC
Labels: area-Infrastructure
