### ISSUE TITLE
[A]System.AppDomain cannot be cast to [B]System.AppDomain

### ISSUE THREAD

**Issue by TonyHenrique** [dotnet/corefx#29730] opened 2018-05-15 23:25 UTC
I am having this, this time I am using a simple F# type and tried to return it as JsonResult in C# Azure Functions (V2) in C#

> System.InvalidCastException: '[A]System.AppDomain cannot be cast to [B]System.AppDomain. Type A originates from 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.7\System.Private.CoreLib.dll'. Type B originates from 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.7\System.Runtime.Extensions.dll'.'

This issue also happened when trying to 

```
public static async Task<IEnumerable<string>> PegaPessoa(string email)
{
    // ... gets the json
    string json = "{}";
    return JsonConvert.DeserializeObject<dynamic>(json);
}
```

https://stackoverflow.com/questions/50330860/exception-when-using-dynamic

**Comment by karelz** [comment] 2018-05-16 16:06
@weshaggard @joperezr it sounds weird that the type is defined in 2 assemblies, both in shared framework. Any thoughts?

**Comment by jkotas** [comment] 2018-05-16 16:25
The CoreLib type is internal, but it is not hard to get to it via private reflection. Related to:

https://github.com/dotnet/corefx/issues/16229
https://github.com/dotnet/corefx/issues/25968#issuecomment-352402058

**Comment by karelz** [comment] 2018-05-16 16:41
Private reflection is not something we would support I assume. That would make it won't fix, unless there is other way we expose the type.
@TonyHenrique can you check where the type is coming from? Can you remove the dependency on the library? (to rule out bugs there) Making it a local repro would also help.

**Comment by jkotas** [comment] 2018-05-16 16:58
> Private reflection is not something we would support I assume.

You are right that private reflection on framework internals is not something we support. The linked issues make it easy to use it by accident, especially when porting code from .NET Framework. Consider this:

```
class Test {
    static void Main() {
        Console.WriteLine(Type.GetType("System.AppDomain").IsPublic);
    }
}
```

Result on .NET Framework: `True` All good, I am using public AppDomain type.
Result on .NET Core: `False` Oops, I got private AppDomain type that I am not supposed to use.

**Comment by karelz** [comment] 2018-05-16 17:49
I see, thanks for explanation. That is sad state.
Should we close some of the issues as dupes, or is there value in tracking multiple of them?

**Comment by bartonjs** [comment] 2019-02-26 16:26
This issue seems to be (effectively) a duplicate of others; closing as no specific action required.

**Closed by bartonjs** 2019-02-26 16:26 UTC
Labels: area-System.Runtime, bug
