### ISSUE TITLE
System.Text.Json crash on deserializing invalid json 

### ISSUE THREAD

**Issue by Firefly74940** [dotnet/corefx#41459] opened 2019-10-01 10:19 UTC
with the following structure deserializing invalid json ( see end of issue ) crash instead of using appropriate exeption 
```
class ArticleTypesData
    {
        public IList<ArticleType> ItemTypes { get; set; }
    }
    class ArticleType
    {
        public string Name { get; set; }
    }
```

logic used : 
```
var options = new JsonSerializerOptions
 {
    AllowTrailingCommas = true
};

var ArticleTypesDatas = JsonSerializer.Deserialize<ArticleTypesData>(file, options);

```

Actual result : Null ptr exeption : 

Expeted result : 
use of System.Text.Json.JsonException . with message like 
`System.Text.Json.JsonException : ''"' is an invalid start of an object Array. Expected a '{'. Path: $.ItemTypes[0] | LineNumber: 4 | BytePositionInLine: .'`

valid json : 

```
{
    "ItemTypes": [
    
        {
			"Name": "Where to Stay",
		},
		{
			"Name": "Where to Stay",
		},
    
	]
}
```

invalid json : 
```
{
    "ItemTypes": [

			"Name": "Where to Stay",

			"Name": "Where to Stay",

	]
}

```

**Comment by steveharter** [comment] 2019-10-01 19:52
Thanks for creating the issue.  This is a duplicate of https://github.com/dotnet/corefx/issues/40449

**Closed by steveharter** 2019-10-01 19:52 UTC
Labels: area-System.Text.Json
