### ISSUE TITLE
RemoteCertificateNameMismatch on OSX SSLStream.ClientAuthenticate to SQL Azure

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#5768] opened 2016-01-29 03:14 UTC
In Mac OS when using SSLStream to AuthenticateAsClient to SQL Azure, we get RemoteCertificateNameMismatch Policy error during validation.

Here is how we init the stream
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L151

When we authenticate as Client 
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L177

It give us policy error : RemoteCertificateNameMismatch
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L221

This issue is the root cause of https://github.com/dotnet/corefx/issues/5173

**Comment by kkurni** [comment] 2016-01-29 03:18
@bartonjs I notice that you mentioned to add this 
```
X509Store(StoreName.Root, StoreLocation.CurrentUser).
```
Where can I set this in the client ?


```
Alternatively, you could fix it at the system level in a manner such as http://andatche.com/blog/2012/02/fixing-ssl-ca-certificates-with-openssl-from-macports/
```

I don't think we can force any client to fix by installing macports.
as most of OpenSSL was not installed from Macports.

Is this a general problem in SSLStream on MacOS ?

Thanks

**Comment by kkurni** [comment] 2016-01-29 03:18
CC @bartonjs @saurabh500

**Comment by bartonjs** [comment] 2016-01-29 03:26
@kkurni Yes, this is a known problem with OS X, the OpenSSL installation on Mac doesn't seem to come with a CA certs bundle.  Currently a user has to register CA certs themselves as a pre-requisite to using X509 trust.

Closing this as duplicate of #5173.

**Closed by bartonjs** 2016-01-29 03:26 UTC
Labels: System.Data, System.Net
