### ISSUE TITLE
Occasionally CPR codes appear in cloudshell

### ISSUE THREAD

**Issue by jianyunt** [dotnet/corefx#31433] opened 2018-07-27 19:38 UTC
PowerShell in Azure CloudShell uses PowerShell core (pwsh) on Linux based container running in Kubernetes clusters. Our usability has improved significantly in recent releases. Millions thanks to .net folks!

Occasionally we are seeing CPR code in the cloudshell at the very beginning when launch the cloudshell. Are there any ways to get rid of it?  [Can it be configurable](https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L338)?
![image](https://user-images.githubusercontent.com/10171679/43343085-c6bc8af0-9199-11e8-9991-d1334a0cda25.png)

**Comment by danmosemsft** [comment] 2018-07-28 03:34
@wtgodbe

**Comment by wtgodbe** [comment] 2018-07-30 19:02
I personally don't see any reason not to allow `s_everReceivedCursorPositionResponse` to be configurable. @jkotas @ericstj is there anything stopping us from allowing users to set a value for this? https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Runtime/CompilerServices/DisablePrivateReflectionAttribute.cs#L7

**Comment by ericstj** [comment] 2018-07-30 19:25
@wtgodbe can you explain more about why this is the best method to handle this?  What's the root cause of us showing those codes?

**Comment by wtgodbe** [comment] 2018-07-30 19:35
My understanding is as follows: On Unix we don't have a great way of getting cursor position, so we use Cursor Position Requests - this involves blocking until we get a specifically-formatted response from the terminal, and interpreting it as a cursor position. However, if a client is connecting to CloudShell over a slow network connection, the response may be delayed long enough such that it comes in after our timeout, and is therefore treated/displayed as user input (as in the screenshot above). Our fix for this was to elongate the timeout, if and only if we've received a successful Cursor Position Response - as that would indicate that the terminal supports CPR (this comment also explains the same thing in different words: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L366-L373). In the case of CloudShell, it would seem to be benificial to them to be able to default `s_everReceivedCursorPositionResponse` to `true`, as that would avoid the still present issue where the first CPR request may spew output to the console, as in above. @jianyunt please correct me if any of this is incorrct

**Comment by ericstj** [comment] 2018-07-30 19:43
I see, so they are trying to "opt-in" to the longer timeout from the start, because they know better than us that their console will be slow?  I'd feel better if they could call some public API to force this to be "primed" without writing to the console as opposed to using private reflection.  Perhaps it could even be a side-effect of some existing API where blocking for a longer timeout isn't so bad.

**Comment by wtgodbe** [comment] 2018-07-30 20:01
I'd be alright with changing `s_everReceivedCursorPositionResponse` to something like `s_delayForCursorPositionResponse`, and adding a `set` function for it. Does that sound like a good soluton @ericstj @jianyunt ?

**Comment by jianyunt** [comment] 2018-07-30 20:29
@wtgodbe you summarized our scenario very well. Thanks. 
@ericstj, the cloudshell does not know the speed of network connection either. With the fix from @wtgodbe and @stephentoub, our user experience improved a lot already. Currently users hit this issue occasionally when launching the cloudshell. We are thinking if s_everReceivedCursorPositionResponse is, true, minchars =1, we can potentially get rid of the problem entirely.

Here is more info about the cloudshell: Our backend is running on Linux containers hosted in Azure. We use xterm.js running in browsers as our frontend. The terminal CPR code gets sent by the xterm. Every user key stoke is back and forth between xterm and notepty running on containers. They can be expensive. During [the last investigation](https://github.com/dotnet/corefx/pull/30789), we found if minchars=1, the cloudshell does not seem to hit the .net timeout. 

@wtgodbe,  yes sounds good to us if s_everReceivedCursorPositionResponse is publicly settable. Thanks.

cc @edyoung @SteveL-MSFT

**Comment by stephentoub** [comment] 2018-07-30 20:38
> yes sounds good to us if s_everReceivedCursorPositionResponse is publicly settable.

We should not add any public surface area for this. It's an implementation detail on a subset of platforms.

**Comment by ericstj** [comment] 2018-07-30 20:53
Agree with Steven, think about how you can have cloudshell naturally communicate this to the Console implementation.  If you can ask yourself "why did I need to make the first timeout smaller?" and find a case where that's not as important perhaps that's an opportunity to absorb a longer blocking call.

**Comment by SteveL-MSFT** [comment] 2018-07-30 21:43
It seems sufficient for CloudShell to use reflection to set this member as I agree this (currently) is an exceptional case and not mainstream.

**Comment by jianyunt** [comment] 2018-07-30 21:58
It looks like private members contained in the .net assemblies are not available to reflection.  It has [DisablePrivateReflectionAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.disableprivatereflectionattribute(v=vs.110).aspx) in corefx.

**Comment by ericstj** [comment] 2018-07-30 22:00
We should avoid private reflection, that's worse than public API as it is an undocumented thing that we cannot break.  If we absolutely cannot think of a way to accommodate this (I don't think we are there yet) then I think we should consider an AppContext switch over private reflection.

**Comment by danmosemsft** [comment] 2018-07-31 00:17
In this scenerio you know for sure the customer will always be on a console they will support CPR?

**Comment by jianyunt** [comment] 2018-07-31 16:51
Yes. We support CPR. In our cloudshell scenario, we are using xterm.js as our terminal running browsers which supports CPR.

**Comment by wtgodbe** [comment] 2018-08-01 20:02
In speaking with Eric, we came up with a possible new scheme - for the first call, keep `minChar=0`, but extend the timeout. Then, if we don't successfully receive a CPR response, keep `minChar=0` with the smaller timeout. If we do receive a response, go to `minChar=1` with the longer timeout. This should allow us to correclty receive the first CPR response (if it's coming). @jianyunt what would be the best way for me to test this against your CloudShell environment?

**Comment by jianyunt** [comment] 2018-08-01 21:26
The new scheme seems to cover our majority cases.  As the network connections are unpredictable , users may still hit the issue though - hopefully a lot less.

What number would you like to set as an extended timeout? 

I cannot think of good ways to test it in CloudShell env because by the time CloudShell is ready for inputs, the minchars may always set to 1. How about you fork from your service branch, make the changes, give me your System.Console.dll, and I will deploy it to CloudShell (public). We can contact our MVPs for the experience?

**Comment by wtgodbe** [comment] 2018-08-01 22:07
We use 10 when minChar=1, so perhaps 15?

I'll make changes locally. do you need a .dll built out of 2.1 or master?

**Comment by jianyunt** [comment] 2018-08-01 22:29
How about 15s?

Let's use 2.1 because the current release is 2.1, right? Otherwise I won't be able to just replace one system.console.dll and expect the pwsh to work. Thank you Will.

**Comment by wtgodbe** [comment] 2018-08-02 19:32
@jianyunt I've just emailed you an updated System.Console.dll.

**Comment by jianyunt** [comment] 2018-08-02 20:49
@wtgodbe, I cannot replace your dll to the current release of PowerShell core engine folder. It looks like the Powershell core is using [.Net 2.1.2](https://github.com/PowerShell/PowerShell/commit/b15709f444a1501bac962fea50ca05f5fb7c03a1#diff-5c322f29d2ecbafc45ba24adf80823f8).
``` PowerShell
Exception details:
System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Interop.Kernel32.GetStdHandle(Int32 nStdHandle)
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_BackgroundColor()
object file: No such file or directory
…
```

**Comment by ericstj** [comment] 2018-08-02 21:53
> Unable to load shared library 'kernel32.dll'

Looks like it's the windows build of System.Console.

**Comment by wtgodbe** [comment] 2018-08-02 22:54
@jianyunt I am out of the office until Monday - here is a branch with my changes against 2.1.2, try building this locally to get System.Console.dll: https://github.com/wtgodbe/corefx/tree/Timer212

**Comment by jianyunt** [comment] 2018-08-10 16:33
@wtgodbe any updates?

**Comment by danmosemsft** [comment] 2018-09-25 18:09
@wtgodbe 	@karelz 	are we still tracking work here for servicing? Per milestone.

**Comment by wtgodbe** [comment] 2018-09-25 18:10
Any change here will most likely be for 3.0.

**Comment by danmosemsft** [comment] 2019-03-11 04:07
@wtgodbe is this part of @tmds recent work?

**Comment by wtgodbe** [comment] 2019-03-11 17:30
This is something that may be improved by that PR, @bradygaster @jianyunt  did you get a chance to test out your scenario with the changes in https://github.com/dotnet/corefx/pull/35621 ?

**Comment by edyoung** [comment] 2019-03-11 18:06
We'll need a version of powershell compiled with that corefx build before we can test. We can't do that immediately I am afraid.

**Comment by bradygaster** [comment] 2019-03-20 18:00
I believe @vijayrkn and/or @mlorbetske were able to test this out. Adding them here for confirmation

**Comment by SteveL-MSFT** [comment] 2019-03-24 18:00
We have a [PR](https://github.com/PowerShell/PowerShell/pull/8370) where we're doing the port to 3.0 work for PSCore6.  However, each new preview of 3.0 has brought new issues.  Some have already been fixed, but at this point, I'm waiting on preview4 before trying again.

**Comment by stephentoub** [comment] 2019-03-24 20:01
> each new preview of 3.0 has brought new issues. Some have already been fixed, but at this point, I'm waiting on preview4 before trying again

What are the new issues that haven't been addressed?

**Comment by SteveL-MSFT** [comment] 2019-03-24 21:31
@stephentoub With Preview.3, Add-Type is broken:

> add-type : error CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.

Haven't had time to investigate as we're focused on getting 6.2 to GA.  I'll have more resources looking at the 3.0 port in April.

**Comment by tmds** [comment] 2019-03-26 14:11
For my education, how do you go about creating a version of powershell that include the changes from that PR?

It would be great if you can try this out. The change relies on changing terminal settings based on child processes. Powershell usage involves creating child processes, so it is a good test-case.

**Comment by wtgodbe** [comment] 2019-05-02 20:21
@SteveL-MSFT @mlorbetske @vijayrkn were you able to try this scenario again with the preview4 bits?

**Comment by SteveL-MSFT** [comment] 2019-05-02 21:30
ping @jianyunt

**Comment by wtgodbe** [comment] 2019-05-09 20:26
Closing this for lack of traction, and given the metrics in Tom's PR with should likely have addressed this. Please re-open if you're still experiencing the issue with the latest 3.0 bits.

**Closed by wtgodbe** 2019-05-09 20:26 UTC
Labels: area-System.Console, bug
