### ISSUE TITLE
Unix HttpClient does not do CRL checking on the connection

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#4120] opened 2015-10-24 00:42 UTC
The libcurl+openssl default is to not check CRLs, since they have to be manually provided.

The work done by #4101 isn't going to change the revocation check status, because currently the Unix X509Chain implementation doesn't support opportunistic revocation, and self-signed certs require opportunistic revocation.

#2204 is the issue tracking opportunistic revocation.

**Comment by bartonjs** [comment] 2015-11-10 19:59
@CIPop @davidsh: https://msdn.microsoft.com/en-us/library/system.net.http.winhttphandler.checkcertificaterevocationlist%28v=vs.105%29.aspx says that WinHttpHandler doesn't by default do revocation checks.  Does that mean you would prefer the Unix HttpClient to not check?

**Comment by davidsh** [comment] 2015-11-10 20:03
cc: @SidharthNabar 

We should have the same defaults in the handlers.  So, if the Windows one, by default, has revocation-checking=off, then CurlHandler sould be similar.

**Comment by stephentoub** [comment] 2015-11-10 20:07
This seems sufficiently importantly that it would drive exposing CurlHandler publically so it could be configured, no?

**Comment by davidsh** [comment] 2015-11-10 20:11
Perhaps, but it makes more sense to consider rev'ing HttpClient to add the boolean directly as a property.  Then it could be x-plat.  The issue of course is the difficult in rev'ing HttpClient contract since it is inbox on .NET Desktop.

We could also consider having the default be the other way around, i.e. ON by default.  In the .NET Desktop, this was originally handled via the ServicePointManager class (which doesn't exist in CoreFx). Perhaps, we should consider what it means to turn it on by default.  But the problem is there is no way, then, to turn it off since HttpClientHandler doesn't have the API surface area for it.

**Comment by bartonjs** [comment] 2015-11-10 21:25
I agree that the right place for it is on the base class.  Right now it looks to me like the required Windows-only code is:
```C#
HttpMessageHandler handler = new WinHttpHandler
{
    CheckCertificateRevocationList = true,
};

HttpClient client = new HttpClient(handler);
...
```

I'd hate to see CurlHandler have to pop into that, and then be behind \#if, or some other target-control scope.

It also seems weird to have CurlHandler do it (by always/default) and WinHttpHandler not (by default).

@davidsh what would you guys like me to do here? Write the equivalent code behind a \#if compile wall? "Fix" the issue with a comment in code saying why we do NoCheck? Something else?

**Comment by SidharthNabar** [comment] 2015-11-10 21:38
My 2 cents - Having CRL checking ON always/by default is not a good idea since it has been unreliable in the past and a lot of times the CRL servers are offline and we get back no answer from the server. So, we should have it off and need to have API surface to allow developers to turn it on. 

Now, the callback for developers to implement custom validation of the server SSL certificate (ServerCertificateValidationCallback) is on WinHttpHandler, so I would argue that this property, which is closely related to that one, should also be on the WinHttpHandler type (and thus, on the CurlHandler type in x-plat).

I agree with @davidsh that in the long term, all the properties that are not platform-specific should be "promoted" to HttpClientHandler, but I wouldn't do this for just this single property since it would be inconsistent with several other properties at this time.

**Comment by bartonjs** [comment] 2015-11-13 17:21
I self-assigned this when I thought it was "the Unix version isn't doing what the Windows version is".  Since that's not the case, and this is now a design discussion, I'm reassigning this to one of the library owners to decide how to proceed (or to decide to not proceed).

**Comment by davidsh** [comment] 2015-12-08 23:26
Will require API change to System.Net.Http contract for HttpClientHandler to add CRL on/off property (similar to `WinHttpHandler.CheckCertificateRevocationList' property.

**Comment by davidsh** [comment] 2016-04-09 23:19
Will be part of #7623

**Comment by stephentoub** [comment] 2016-04-15 15:14
Closing this issue, as the implementation was done for CurlHandler in https://github.com/dotnet/corefx/pull/7060, and #7623 is tracking exposing this functionality for both Windows and Unix from HttpClientHandler.

**Closed by stephentoub** 2016-04-15 15:14 UTC
Labels: System.Net, X-Plat
