### ISSUE TITLE
SqlClient.SqlClientFactory doesn't implement DbProviderFactory.CreateDataAdapter()

### ISSUE THREAD

**Issue by FransBouma** [dotnet/corefx#19673] opened 2017-05-11 21:40 UTC
Hi.

In netstandard 2.0, the method DbProviderFactory.CreateDataAdapter() is present, however this method isn't implemented in SqlClient.SqlClientFactory, leading to a null being returned. This is likely an oversight caused by the fact that the factory was ported over way before DataTable and friends were ported over. I think this should be corrected before 2.0 RTM, as it's an important method for code using datatables and dataadapters. 

ref: DbProviderFactory.CreateDataAdapter docs: https://apisof.net/catalog/System.Data.Common.DbProviderFactory.CreateDataAdapter()

thanks!

**Comment by justinvp** [comment] 2017-05-11 21:44
Looks like a dupe of #19651

**Comment by ViktorHofer** [comment] 2017-05-12 01:28
Closing because dupe of https://github.com/dotnet/corefx/issues/19651

**Closed by ViktorHofer** 2017-05-12 01:28 UTC
Labels: area-System.Data.SqlClient

**Comment by FransBouma** [comment] 2017-05-12 06:03
Yep, sorry about this. I searched for the issue but I totally overlooked the issue already filed. My bad.
