### ISSUE TITLE
# in file directory name causes System.Configuration.ConfigurationManager not to discover appsetings for .net core 2.0 app

### ISSUE THREAD

**Issue by TrevorFradsham** [dotnet/corefx#29126] opened 2018-04-15 18:41 UTC
The path to my project files has a hashtag # in it and I spent many hours trying to find out why my .net core 2.0 console app was not able to access the System.Configuration.ConfigurationManager.AppSettings. I thought it was a misspelling of the strings but when I moved the project folder out of the sub-directory with the hashtag, everything worked find.

\code\c#\projectfolder
\code\projectfolder

I figured out the issue when I wrote a piece of code to see if I could add a setting key value pair, when the project was in the folder with the # (\code\c#\projectfolder). It resulted in a .config file being created in \code\c.config. I did not given any name to the config file. The setting  should have appeared in the following file.
\code\c#\projectname\bin\Debug\netcoreapp2.0\projectname.dll.config

Here is the code I had tested:

        private static void _setConfigurationSettings()
        {
            string key = "MyCustomSettings2";
            try
            {
                var configFile = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
                var settings = configFile.AppSettings.Settings;
                if (settings[key] == null)
                {
                    settings.Add("MyCustomSettings2", "Hi This is my setting");
                }
                else
                {
                    settings[key].Value = "My Setting hasChanged";
                }
                configFile.Save(ConfigurationSaveMode.Modified);
                ConfigurationManager.RefreshSection(configFile.AppSettings.SectionInformation.Name);
            }
            catch (ConfigurationErrorsException ex)
            {
                Console.WriteLine($"ERROR: {ex.ToString()}\n");
            }
        }

**Comment by danmosemsft** [comment] 2018-04-15 23:32
@anipik can you localize this? I wonder whether it's URI related.

**Comment by Anipik** [comment] 2018-04-16 22:25
@danmosemsft I am able to repro the bug on 2.0 Still checking if its repro on 2.1 too

**Comment by maryamariyan** [comment] 2018-04-26 17:57
@TrevorFradsham have you tried using the latest version of System.Configuration.ConfigurationManager nuget package. The problem is reproducible in version 4.4.1 but not anymore in 4.5.0-preview2-26406-04

**Comment by TrevorFradsham** [comment] 2018-04-27 09:09
‎Will give it a try

Thanks
Trevor
From: Maryam Ariyan
Sent: Thursday, April 26, 2018 3:27 PM
To: dotnet/corefx
Reply To: dotnet/corefx
Cc: Fradsham, Trevor; Mention
Subject: Re: [dotnet/corefx] # in file directory name causes System.Configuration.ConfigurationManager not to discover appsetings for .net core 2.0 app (#29126)



@TrevorFradsham<https://github.com/TrevorFradsham> have you tried using the latest version of System.Configuration.ConfigurationManager nuget package. The problem is reproducible in version 4.4.1 but not anymore in 4.5.0-preview2-26406-04

**Comment by maryamariyan** [comment] 2018-05-01 00:37
Closing this issue as it is fixed on the newer version. @TrevorFradsham you can reopen if you still find an issue.

**Closed by maryamariyan** 2018-05-01 00:37 UTC
Labels: area-System.Configuration, bug
