### ISSUE TITLE
Port System.Messaging

### ISSUE THREAD

**Issue by valeriob** [dotnet/corefx#25470] opened 2017-11-23 19:39 UTC

**Comment by danmosemsft** [comment] 2017-11-24 09:10
@karelz who owns System.Messaging.dll...

**Comment by danmosemsft** [comment] 2017-11-25 03:26
@zhenlan ?

**Comment by zhenlan** [comment] 2017-11-25 07:08
We should understand how significant the demand is. This is Windows only.

@jimcarley thoughts?

**Comment by valeriob** [comment] 2017-11-25 09:03
For us this is the last stopper to migrate to .net core almost all application actively developed, this means being able to keep up to date with donet core and all the benefit it brings.

This will enable nservicebus msmq transport to target netcore : Particular/NServiceBus.Transport.Msmq#58 

To mee it looks like very much inline with this plan : 
![image](https://user-images.githubusercontent.com/1522516/33229020-db1a40b6-d1c6-11e7-88eb-0d1a39859350.png)

**Comment by bording** [comment] 2017-11-27 16:55
FYI, I believe this request is already being tracked here: https://github.com/dotnet/corefx/issues/6204

**Comment by karelz** [comment] 2017-11-27 17:30
Closing as duplicate of #6204

**Closed by karelz** 2017-11-27 17:30 UTC

**Comment by spragchris** [comment] 2018-05-23 07:59
I'm not sure the proprietary nature of MSMQ as a server is a compelling reason to disregard a port of this functionality into core.  Haven't there been recent compromises in other areas such as Active Directory? It might be that a port isn't possible, but surely this can't be the reasons why.

**Comment by karelz** [comment] 2018-05-23 16:13
@sparraguerra I think you misread the reason for closing - it was closed as duplicate, not disregarded.

I would suggest to vote on the primary issue (upvote the top post / add comment). So far the interest is smaller, compared to other libraries (like Active Directory).
