### ISSUE TITLE
http call using WebClient.UploadData gives HttpRequestException but the exact same code works in .net framework

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31429] opened 2018-07-27 18:28 UTC
_From @gronlund013 on July 26, 2018 14:4_

# https call using WebClient.UploadData gives HttpRequestException but the exact same code works in .net framework

# General
Application is a web api (.net core 2.1) application that uses a call to
```
using (WebClient client = new WebClient())
{
    var response = client.UploadData(serverUrl, capabilityRequestData.ToArray());
}
```
to fetch information from external site.

I am trying to get licensing information from a licensing vendor and their code-sample works (.net framework 3.5) but my .net core code that does the exact same thing gives me the following exception

{System.Net.WebException: The requested name is valid, but no data of the requested type was found The requested name is valid, but no data of the requested type was found ---> System.Net.Http.HttpRequestException: The requested name is valid, but no data of the requested type was found ---> System.Net.Sockets.SocketException: The requested name is valid, but no data of the requested type was found
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, Byte[] data)

_Copied from original issue: dotnet/core#1819_

**Comment by davidsh** [comment] 2018-07-27 18:51
@gronlund013

This error:

~"The requested name is valid, but no data of the requested type was found The requested name is valid, but no data of the requested type was found"~

is basically the same as "Host not found".   So, the networking APIs can't resolve your host name that you are passing in.

Can you provide the actual 'serverUrl' you are using in the code sample above?

```c#
var response = client.UploadData(serverUrl, capabilityRequestData.ToArray());
```

**Comment by gronlund013** [comment] 2018-07-27 19:11
Yeah, I can provide it on monday when I'm back at work..
But.. I had 2 instances of Visual studio 2017 running, one with the netcore2.1 project and one with the .net framework project..

The exact same code worked on the .net framework project but gave me this exception on the netcore2.1 app.

Be back on monday :)

**Comment by gronlund013** [comment] 2018-07-29 09:21
I created a test repository @ https://github.com/gronlund013/WebClientTest

The result I get is shown in the image
![netcorevsnetframeworkrest](https://user-images.githubusercontent.com/26566661/43364782-55259466-9321-11e8-939e-f560347dcc79.png)

I should probably let you know that I'm sitting at a huge company with very complicated proxy settings

**Comment by davidsh** [comment] 2018-07-29 22:00
Thank you for posting the sample applications.

I was not able to reproduce the problem with the NET Core 2.1 app:
![image](https://user-images.githubusercontent.com/7684835/43371092-bf0b21d4-933f-11e8-87c9-bfeae9f3355a.png)

I suspect that the problem might have to do with your environment and the proxy at your work.  We have several different bugs with .NET Core 2.1 and proxies.   Can you post more information about your environment?  What OS and version are you using?  How is the proxy set up on your machine?  If this is Windows, can you post a screenshot of your IE proxy settings?  It would look similar to this:

![image](https://user-images.githubusercontent.com/7684835/43371119-227f2792-9340-11e8-95c9-b554851b4b0f.png)

**Comment by davidsh** [comment] 2018-07-29 22:02
In addition, can you take PerfView ETW traces?  Please collect the "*Microsoft-System-Net-Http" traces.

See these instructions:
https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md

**Comment by gronlund013** [comment] 2018-07-30 05:17
OS: Windows 10 v1709
Proxy is set to use automatic configuration script, its pointing to a pac.pac file
![image](https://user-images.githubusercontent.com/26566661/43377792-15841164-93c3-11e8-968d-c7db02789921.png)

Not sure I got the etl file correctly but here it is
[net_000001.zip](https://github.com/dotnet/corefx/files/2239708/net_000001.zip)

Can confirm proxy is the problem

1. Disconnect from corporate network
2. Disable all proxy settings
3. Connect using phone as personal hotspot
4. It works

**Comment by davidsh** [comment] 2018-07-30 16:56
Thank you for the added information and the traces!

Looking at the ETL traces, I see this:

```
<Event MSec=  "8390.0505" PID="5564" PName="Process(5564)" TID="12700" EventName="ErrorMessage"
  TimeStamp="07/29/18 21:45:52.843937" ID="5" Version="0" Keywords="0x0000F00000000001" TimeStampQPC="889,335,668,499"
  Level="Warning" ProviderName="Microsoft-System-Net-Http" ProviderGuid="bdd9a83e-1929-5482-0d73-2fe5e1c0e16d" ClassicProvider="False"
  Opcode="0" Task="65529" Channel="0" PointerSize="8"
  CPU="4" EventIndex="29" TemplateType="DynamicTraceEventData">
  <PrettyPrint>
    <Event MSec=  "8390.0505" PID="5564" PName="Process(5564)" TID="12700" EventName="ErrorMessage" ProviderName="Microsoft-System-Net-Http" thisOrContextObject="HttpConnectionPoolManager#15368010" memberName="SendAsync" message="Exception from IWebProxy.GetProxy(https://reqres.in/api/users?page=2): System.PlatformNotSupportedException: Operation is not supported on this platform.
       at System.Net.SystemWebProxy.IsBypassed(Uri host)
       at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)"/>
  </PrettyPrint>
```

It looks like this bug is a duplicate of #31100.  Your code is using System.Net.HttpWebRequest calls (which call into HttpClient).  There is a bug causing an incorrect PlatformNotSupportedException to be raised. That exception is not surfacing but instead you're getting the ""The requested name is valid, but no data of the requested type was found The requested name is valid, but no data of the requested type was found" error.

#31100 has been fixed.  The fix will be available in a servicing update of .NET Core 2.1 sometime in the next month or so.

cc: @danmosemsft

**Comment by gronlund013** [comment] 2018-07-31 09:28
@davidsh Thank you for your help, I really thought it was a unique problem cause I couldn't find anyone else reported the same exception.

Do I just monitor #31100 and when it closes I grab the latest update and if it works I close this issue ?

**Comment by gronlund013** [comment] 2018-08-01 08:00
Okey, thank you, will monitor :)

**Comment by davidsh** [comment] 2018-08-01 16:50
Closing this issue as duplicate of #31122

**Closed by davidsh** 2018-08-01 16:50 UTC
Labels: area-System.Net, bug
