### ISSUE TITLE
[ManagedHandler] Add request retry logic on IO failures

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26495] opened 2018-01-21 09:15 UTC
We should support request retry logic for scenarios when sending a request fails due to server connection timeout or other issues.

See my comments on #26453 for more details.

**Comment by stephentoub** [comment] 2018-01-21 15:03
From https://github.com/dotnet/corefx/issues/26453#issuecomment-359218932:

>(1) IO error writing the request header. No problems here, I think.
(2) EOF on result of read ahead, assuming there's no request body. No problems here, I think.
(3) EOF on initial connection read, assuming there's no request body. This is a weird one, but could happen, say, if the server shuts down right after we connect. So on net it's probably worth doing.
(4) EOF (initial or read ahead) when waiting for 100 Continue. (So, there's a request body, but it hasn't been sent yet.) Seems like it's safe to start over here, too.
(5) IO error writing request body. This seems dangerous. Probably we should not restart. If the request body is streamed, we can't restart anyway.
(6) EOF on first read after sending request body. Again, probably doesn't make sense to restart here.

I'm not following why we need to consider (2), (4), (5), or (6).  In general, we don't want to do retries; they can be done at a higher-level and shouldn't be the responsibility of the HTTP stack, which should accurately reflect a failure if the server tore down the connection. What complicates manners is connection pooling; if it weren't for that, we should never retry.  With connection pooling, the only situation we should be concerned about retrying for is if the connection becomes invalid unrelated to the request being made, namely if the server closes the connection associated with the previous request.

There is an inherent race condition here, in that when we reuse the connection, we don't know whether the server is closing it based on the previous request or this one.  If it's closing it based on this request, that failure should be reflected; if it's closing it based on the previous request, we would want to ignore it and retry.  If we detect the connection has been closed, and we detect it before we initiate the second request, then we obviously know it was associated with the first; the issue is if we detect it after we've already initiated the second request, where a timing issue could have the server close the connection based on not having seen anything to do with the second request.

That's why in #26453 I suggested the simple approach of just validating the read ahead task, which represents the first read for a connection taken from the pool.  If that read succeeds with a non-zero result, then any subsequent failures are for this request, not the previous one.  If that read returns 0, then the server closed the connection, and while it's possible it closed it based on what was sent for this request, we can't know either way for sure and can just assume it closed it based on the previous request and retry.  I believe this is your (2).

We could additionally say that if the first send on the connection taken from the pool fails due to ConnectionAborted, we retry.  I believe this is your (1).

I'm not sure why we'd do anything beyond that.

As for number of retries, every time we retry we're either creating a new connection from scratch or taking one from the pool.  If we create a new one from scratch, we won't retry because it's a new connection that was never pooled, so we'll retry at most once.  If we take a connection from the pool and we retry, we won't return that connection to the pool, so we'll be inherently limited in the number of retries by the number of connections in the pool, eliminating them as we go through them.  Given that, I don't think we need to put a hardcoded limit on number of retries, and just let things work themselves out naturally; if we find some degenerate case from that, we can address it down the road.

**Comment by stephentoub** [comment] 2018-01-21 15:04
(That said, it'd be good to look into what other stacks do here: the existing implementation in .NET Framework, WinHttp, wininet, curl, etc.  This is likely already well-trodden ground.)

**Comment by PeterSmithRedmond** [comment] 2018-01-22 18:43
This scenario, BTW, is the exact reason that the HttpClient front end is separate from from the back end handlers: the developer can simply add in a "chain" of HTTP filters for retry, auth, specialized caching and more. The best way to handle this request is by making a sample retry filter.

The UWP HttpClient includes a set of 
[sample filters](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/HttpClient/HttpFilters) for common scenarios.

**Comment by geoffkizer** [comment] 2018-01-22 18:47
Wow, managed C++, I'm impressed :)

The managed handler is largely built in terms of chained HTTP handlers for auth, redirect, cookies, etc.

**Comment by PeterSmithRedmond** [comment] 2018-01-22 19:00
Lots of stuff is appropriate for the manged handler -- cookies, for example, IMHO absolutely belong to the handler, as does some form of redirect and some auth. Other auth gets more complex. 

An example of auth that the managed handler shouldn't handle is OAUTH and OAUTH2. One of the UWP samples is for OAUTH and OAUTH2 authentication; the "filter" looks at each outgoing request and if there's alreay an OAUTH or OAUTH2 token, adds in the token based on some smarts about how different servers require the token. If the token doesn't exist, then an whole auth flow happens and the user gets to do a sign-in. This sort of specialized auth is not appropriate for the managed handler because most people don't need it, and many people will have to fiddle with the flows to make them work for other servers.

**Comment by stephentoub** [comment] 2018-01-22 19:36
> I do think we should do restart for (4); this seems to me to be just another case of "retry on EOF from read ahead task." What's your concern here?

First, (4) says "initial or read ahead"; as noted, I don't think we should be doing any retries for an initial rather than pooled connection.

Second, I don't know why we'd treat 100 Continue specially here. What makes this case functionally different from (2)? i.e. would we need any code to handle this case specifically, and if so, what? I may just not be understanding why it was called it separately.

**Comment by stephentoub** [comment] 2018-01-22 19:39
> The best way to handle this request is by making a sample retry filter.

The best way to handle what request? How would a higher-level filter plug into the connection pooling mechanism? And why would we rely on a sample to address an actual bug in the pooling implementation?

**Comment by geoffkizer** [comment] 2018-01-25 18:53
@stephentoub Re 100-continue -- at the very least, we should have a test for this.

Regardless, I think we are in agreement here and should just proceed to implementation.

**Comment by stephentoub** [comment] 2018-01-25 21:16
> Re 100-continue -- at the very least, we should have a test for this

Sounds good.

**Closed** 2018-02-01 04:24 UTC
Labels: area-System.Net.Http.ManagedHandler, enhancement
