### ISSUE TITLE
System.Buffers ref doesn't match inbox

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#32984] opened 2018-10-23 18:27 UTC
System.Buffers ref is building as 4.0.4.0:
https://github.com/dotnet/corefx/blob/27db480b1d57f05fde422d3208d7351f3e6af369/src/System.Buffers/Directory.Build.props#L5

However, 4.0.3.0 was inbox in netcoreapp2.1
https://github.com/dotnet/corefx/blob/cfe107037f1269ae46dd3165eb18007a11a366b5/src/System.Buffers/dir.props#L5-L7

And before that, 4.0.2.0 was inbox on netcoreapp2.0 and the ref was pinned in 2.1:
https://github.com/dotnet/corefx/blob/cfe107037f1269ae46dd3165eb18007a11a366b5/src/System.Buffers/ref/System.Buffers.csproj#L8

This was broken when this was removed:
https://github.com/dotnet/corefx/commit/b09c098f2e0c7934dac8a4c7e38a5bf249a5b955#diff-2205f80ba40246edf2098e04523def5aL4

Package validation would have normally caught this, but the package was deleted in the same commit.

We should investigate why package testing of upstack consumers (Pipelines) didn't catch this.  I would have expected VerifyClosure to see the mismatch.

**Comment by GSPP** [comment] 2018-10-24 09:36
Is this the cause for https://github.com/dotnet/corefx/issues/30642?

I personally have also experienced a need to add the `System.Buffers` package when it should not have been required.

**Comment by safern** [comment] 2018-12-10 22:44
This was fixed in: https://github.com/dotnet/corefx/pull/32992

**Closed by safern** 2018-12-10 22:44 UTC
Labels: area-System.Buffers
