### ISSUE TITLE
Detect Keep-Alive failures

### ISSUE THREAD

**Issue by smbecker** [dotnet/corefx#5484] opened 2016-01-16 03:48 UTC
In desktop CLR, it is fairly straightforward to detect a keep-alive failure using `WebExceptionStatus.KeepAliveFailure`. I have yet to find any equivalent in CoreCLR. It seems that even the PAL in System.Net.Requests only detects name resolution failures. I have specific processing for keep-alive failures in an application that I am porting to CoreCLR and I am not seeing how I can do that on CoreCLR. Is there a way? Or will there be a way?

**Comment by davidsh** [comment] 2016-01-16 04:01
cc: @SidharthNabar @CIPop @stephentoub 

The System.Net.Requests contract is built on top of the System.Net.Http contract (HttpClient APIs). Underneath that, the HTTP stack is completely different compared with .NET Framework (Desktop).

There is currently no architecture in the CoreCLR HTTP stack to support those `WebExceptionStatus` errors in being returned.  There are no plans to support this in CoreCLR.

**Comment by smbecker** [comment] 2016-12-01 00:47
Is there any other way to detect keep-alive failures or more specific request failures? WebExceptionStatus was pretty useful and it would be a shame if there were no similar functionality to replace it.

**Comment by davidsh** [comment] 2016-12-01 17:44
FWIW, We have thought about the `WebExceptionStatus` enum and bringing it forward in some way into .NET Core.  We did this already but it is more of an app-compat thing for legacy code to compile for System.Net.Requests contract.

But see https://github.com/dotnet/corefx/issues/2384 as we have been thinking about ways to re-use or create a new enum to help error logic.

**Comment by smbecker** [comment] 2016-12-01 20:12
Thanks for the link, I was subscribed to that as well and perhaps this should be closed and tracked there instead. Unfortunately, both this issue and #2384 have been stale for about a year. Is there any plans around this for netstandard 2.0?

**Comment by karelz** [comment] 2016-12-14 19:03
Dupe of #13773.

**Closed by karelz** 2016-12-14 19:03 UTC
Labels: area-System.Net
