### ISSUE TITLE
Creating custom TimeZoneInfo from existing TimeZoneInfo in Ubuntu fails

### ISSUE THREAD

**Issue by stkash** [dotnet/corefx#41649] opened 2019-10-08 19:49 UTC
I was trying to create custom time zones from the time zones returned by `TimeZoneInfo.GetSystemTimeZones()` in Ubuntu. I got "System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap." exception.

This is the simplified version of my code:
```csharp
IList<TimeZoneInfo> customТimeZones = new List<TimeZoneInfo>();
foreach (var timezone in TimeZoneInfo.GetSystemTimeZones())
{
	customТimeZones.Add(
		TimeZoneInfo.CreateCustomTimeZone(
			timezone.Id,
			timezone.BaseUtcOffset,
			timezone.DisplayName,
			timezone.DisplayName,
			timezone.DaylightName,
			timezone.GetAdjustmentRules()));
}
```

I see two potential problems:
1. In Windows `AdjustmentRule.DateStart` of the next rule is always one day after `AdjustmentRule.DateEnd` of the last rule. In Ubuntu they are the same.
Windows:
![Mountain Standard Time Windows](https://user-images.githubusercontent.com/7841361/66427552-373aec80-e9e2-11e9-8d1f-8d95fc4fe824.jpg)

Ubuntu:
![Mountain Standard Time Ubuntu1](https://user-images.githubusercontent.com/7841361/66427562-3bffa080-e9e2-11e9-8a44-0dc2647031c5.jpg)

2. Some of the rules in Ubuntu are messy. For example, "America/Phoenix" has 12 adjustment rules, but there is no continuity after zone with DateEnd = {1/1/1944 12:00:00 AM}. Next zones overlap each other:
![Mountain Standard Time Ubuntu](https://user-images.githubusercontent.com/7841361/66427589-4e79da00-e9e2-11e9-94b7-c7b28d970253.jpg)

**Comment by tarekgh** [comment] 2019-10-08 20:58
This is duplicate of https://github.com/dotnet/corefx/issues/17120 so closing this one. If you adding more comments related to this issue, please added it to the linked issue instead. Thanks for reporting the issue.

**Closed by tarekgh** 2019-10-08 20:58 UTC
Labels: area-System.Runtime, bug
