### ISSUE TITLE
API addition: System.Net.Http.HttpMethod.Patch method/verb

### ISSUE THREAD

**Issue by moljac** [dotnet/corefx#21131] opened 2017-06-16 10:10 UTC
System.Net.Http.HttpMethod.Patch method/verb (RFC5789) is a extension to HTTP 1.1 protocol and method definitions defined in (RFC2616 Section 9). 

Suggestion: add API (static method HttpMethod.Patch that returns new HttpMethod("PATCH")) which is current workaround for this issue.

Pros:
 
*   consistent API with other HTTP methods.

Cons: 

*   none, since this is new API, there should not be any breaking changes.

Code changes can be viewed in the commit referenced below (no PR issued yet).
Preliminary builds on MacOSX passed.

References:

*   https://tools.ietf.org/html/rfc5789
*   https://tools.ietf.org/html/rfc2616#section-9
*   https://github.com/moljac/corefx/commit/457e528a2e5641643a50a438a356d0c7308cd84e

**Comment by davidsh** [comment] 2017-06-16 13:19
Thank you for your suggestion.  This is a dupe of #17299.  Please review that issue and associated process for API additions.

**Closed by davidsh** 2017-06-16 13:19 UTC

**Comment by moljac** [comment] 2017-06-16 14:44
@davidsh 

My bad. Long night. Sorry I did not search good enough.

I will comment on the other issue.
