### ISSUE TITLE
Ignoring default values during serialization using System.Text.Json

### ISSUE THREAD

**Issue by judeleander** [dotnet/corefx#42635] opened 2019-11-19 04:39 UTC
Currently there is no support for Ignoring Default Values while Serialization in `System.Text.Json`, which is required for ignoring default value for value types (Data type), the same support is available in [Json.NET](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm), this can be achieved by adding an API **`IgnoreDefaultValues`** to the Json Serializer Options and then validating a condition to check if the IgnoreDefaultValues API is set true and the value is default value before serializing only for the value types since it cannot be provided for reference types.

### Proposed API

`IgnoreDefaultValues` API is proposed similar to existing API `IgnoreNullValues`

```csharp

/// <summary>
/// Determines whether default values are ignored during serialization and deserialization.
/// The default value is false.
/// </summary>
/// <exception cref="InvalidOperationException">
/// Thrown if this property is set after serialization or deserialization has occurred.
/// </exception>
public bool IgnoreDefaultValues
{
     get
     {
          return _ignoreDefaultValues;
     }
     set
     {
          VerifyMutable();
          _ignoreDefaultValues = value;
     }
}

```

```csharp
bool includeProperty = true;

// Check default value property.
if (options.IgnoreDefaultValues)
{
    DefaultValueAttribute defaultValueAttribute = JsonPropertyInfo.GetAttribute<DefaultValueAttribute>(jsonPropertyInfo.PropertyInfo);
    currentValue = jsonPropertyInfo.GetValueAsObject(state.Current.CurrentValue);
    includeProperty = (defaultValueAttribute != null && object.Equals(currentValue, defaultValueAttribute.Value)) == false;
}

if (includeProperty)
{
    jsonPropertyInfo.Write(ref state, writer);
}
```

### Details
* Added API `IgnoreDefaultValues` for getting input from user if default values are to be ignored while JSON serialization using JsonSerializerOptions in System.Text.Json.
* Implemented the same by validating if IgnoreDefaultValues API is set to true by user and the value to be serialized is a default value and if so the same is ignored and move to next property while serialization.

### Pull Request

A PR with the proposed changes is available: [#42288](https://github.com/dotnet/corefx/pull/42288)

**Comment by layomia** [comment] 2019-11-20 22:57
This might overlap with https://github.com/dotnet/corefx/issues/40600 which discusses conditional ignoring per property.

**Comment by layomia** [comment] 2019-11-23 12:09
Closing - duplicate of https://github.com/dotnet/corefx/issues/38878.

**Closed by layomia** 2019-11-23 12:09 UTC
Labels: api-suggestion, area-System.Text.Json
