### ISSUE TITLE
SendToV4IPEndPointToDualHost_Success timeout on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6516] opened 2016-02-29 13:59 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1458/console
```
05:22:47    System.Net.Sockets.Tests.DualMode.SendToV4IPEndPointToDualHost_Success [FAIL]
05:22:47       System.TimeoutException : The operation has timed out.
05:22:47       Stack Trace:
05:22:47             at System.Net.Sockets.Tests.DualMode.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)
05:22:47             at System.Net.Sockets.Tests.DualMode.SendToV4IPEndPointToDualHost_Success()
```

**Comment by ericeil** [comment] 2016-03-01 21:36
My best guess is that this is due to the inherent unreliability of UDP.  The test sends a single packet, and demands receipt of it.  

@stephentoub, @CIPop, do we see similar failures on Windows ever?  I wonder if UDP delivery to loopback is more reliable on Windows...

**Comment by CIPop** [comment] 2016-03-01 22:36
@ericeil We see a different kind of failure for UDP: #5234 but we see these for TCP quite often #5185.
For Windows, I've never seen this happening on my Dev box.

**Comment by ericeil** [comment] 2016-03-01 23:15
Thanks, @CIPop.

> We see a different kind of failure for UDP: #5234 

#5234 looks like something different; I think I've identified the problem, and I'll submit a PR.

**Comment by ericeil** [comment] 2016-03-01 23:31
> but we see these for TCP quite often #5185

Looking through #5185, it looks like the failures are for UDP, not TCP.  So it seems plausible that this is the same issue.

**Comment by ericeil** [comment] 2016-03-01 23:40
Closing this as a duplicate of #5185.

**Closed by ericeil** 2016-03-01 23:40 UTC
Labels: System.Net, test bug, X-Plat
