### ISSUE TITLE
JsonString node doesn't round-trip DateTimeOffset correctly

### ISSUE THREAD

**Issue by msmolka** [dotnet/corefx#41706] opened 2019-10-10 12:18 UTC
in System.Text.Json serializing and deserializing datetimeoffset looses precision and most important part the offset part.

There is no different between datetime and datetimeoffset after serialization. In multi time environments it cases serious issues since all times are treated as UTC,

JsonString uses "s" format

```c#
 public JsonString(DateTimeOffset value) => Value = value.ToString("s", CultureInfo.InvariantCulture);
```

Which is not producing right value. It totally ignores offset.

**Comment by ahsonkhan** [comment] 2019-10-11 00:55
@msmolka - for the benefit of readers, can you explain what was your reasoning for closing the issue? Why is it invalid?

**Comment by msmolka** [comment] 2019-10-11 06:18
@ahsonkhan Hello
I was looking why my json deserialization is not accepting `+1000`. as time offset in string.

But indeed above issue is valid. `JsonString` definatelly has wring fromat when producing or reading DateTimeOffset. Is should support exactly the same rules as `Serializer`

**Comment by ahsonkhan** [comment] 2019-10-14 02:55
To clarify (and correct me if I am mistaken), but the issue you have isn't about the serialization/deserialization of JSON strings (using [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.0))? It's specifically about the [`JsonString`](https://github.com/dotnet/corefx/blob/437d9bc76489ff18bd9ce04f287e07591f6bc38c/src/System.Text.Json/src/System/Text/Json/Node/JsonString.cs#L12) node only, correct?

Can you provide a sample repro with your expected output/behavior of processing DateTimeOffset compared to what actually happens?

Thanks.

**Comment by msmolka** [comment] 2019-10-14 07:56
@ahsonkhan The issue is related to code I found in latest `JsonString` class. Which is not released yet. So I cannot easily create repo for that. If you look into
 `public DateTimeOffset GetDateTimeOffset() => DateTimeOffset.ParseExact(_value, "s", CultureInfo.InvariantCulture);` 
and 
`public JsonString(DateTimeOffset value) => Value = value.ToString("s", CultureInfo.InvariantCulture);`

you will notice "s" formatter which is not right for `DateTimeOffset`. It is only suiatable for `DateTime`.

**Comment by ahsonkhan** [comment] 2019-10-14 10:29
> The issue is related to code I found in latest `JsonString` class. Which is not released yet. So I cannot easily create repo for that.

You could try using the nightly build/NuGet package that is being built out of master:
Add the following NuGet feed and use the `System.Text.Json` package, version `5.0.0-alpha1.19513.1`
https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

https://github.com/dotnet/corefx/#daily-builds

**Comment by ahsonkhan** [comment] 2019-10-14 10:30
Updated the title since the issue is not related to serialization/deserialization.

**Comment by khellang** [comment] 2019-10-14 10:38
From [The Sortable ("s") Format Specifier docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-sortable-s-format-specifier):

> The purpose of the "s" format specifier is to produce result strings that sort consistently in ascending or descending order based on date and time values. As a result, although the "s" standard format specifier represents a date and time value in a consistent format, the formatting operation does not modify the value of the date and time object that is being formatted to reflect its `DateTime.Kind` property or its `DateTimeOffset.Offset` value. For example, **the result strings produced by formatting the date and time values `2014-11-15T18:32:17+00:00` and `2014-11-15T18:32:17+08:00` are identical.**

IMO, that's problematic for `DateTimeOffset` (since it doesn't preserve the offset), but could it also be problematic for `DateTime` (since it doesn't consider its `DateTime.Kind`?

**Comment by watfordgnf** [comment] 2019-10-14 14:59
`JsonString` should use the `O` format specifier used by Utf8JsonWriter.

https://github.com/dotnet/corefx/blob/7b90f41828abea1d9db6d55403a849c2613d996d/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.DateTime.cs#L109

**Comment by watfordgnf** [comment] 2019-10-14 15:16
Tests missed this because they did not include times or offsets for DateTimeOffset:
https://github.com/dotnet/corefx/blob/37b37395481b635c15eaa3454e52b72ab91de4ef/src/System.Text.Json/tests/JsonStringTests.cs#L88-L95

**Comment by watfordgnf** [comment] 2019-10-14 15:24
It looks like GUID's are correctly using `D` which matches [`Utf8Formatter.TryFormat`](https://github.com/dotnet/corefx/blob/7b90f41828abea1d9db6d55403a849c2613d996d/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Guid.cs) used by `Utf8JsonWriter`.

**Comment by msmolka** [comment] 2019-10-14 15:28
@watfordgnf Be carefull with `"O"` format for parsing. It is very strict. JsonReader is parsing datetimeoffset  in different way.

**Comment by watfordgnf** [comment] 2019-10-14 15:31
Fair point, but more correct than `"s"`.

**Comment by Clockwork-Muse** [comment] 2019-10-15 16:12
@khellang 
> IMO, that's problematic for DateTimeOffset (since it doesn't preserve the offset), but could it also be problematic for DateTime (since it doesn't consider its DateTime.Kind)?

`DateTime.Kind` is mostly worthless.   
 - `DateTimeKind.Local` is almost certainly not going to match whatever the local timezone of the other party is.  So you have to at least send a timezone id and/or an offset anyways (or at least specify it in API documentation).  And if the other party is a server, the local timezone is almost always irrelevant (in preference for the zone of some configured entity).
 - `DateTimeKind.Unspecified` is shorthand for "nobody knows the status without more information", so you're in the same boat.  That's ignoring issues converting from it.
 - `DateTimeKind.Utc` is at least unambiguous, but only covers logged (past) events, given that most people schedule things based on a local _timezone_ (note, not the offset).

**Closed** 2019-11-01 20:10 UTC
Labels: area-System.Text.Json
