### ISSUE TITLE
[Release/1.0.0]HttpClientHandlerTest.PostAsync_CallMethod_StreamContent failed on fedora debug

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#9270] opened 2016-06-09 00:18 UTC
This test is failing intermittently between builds, filing it under RTM for investigation.

```
MESSAGE:
System.Threading.Tasks.TaskCanceledException : A task was canceled.
+++++++++++++++++++
STACK TRACE:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_CallMethod_StreamContent>d__55.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/fedora23_debug/3/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/fedora23_debug/5/

**Comment by davidsh** [comment] 2016-06-09 03:39
cc: @stephentoub

**Comment by ericeil** [comment] 2016-06-09 17:15
At first glance, this would appear to be a simple timeout.  Probably the remote server was slow to respond.

**Comment by ericeil** [comment] 2016-06-09 18:20
Looks like the timeout is the default: 100 seconds.  That's long enough that it's probably worth looking into other possible causes.

**Comment by joshfree** [comment] 2016-06-11 22:20
Moving to 1.1

**Comment by ericeil** [comment] 2016-07-13 21:05
I was able to reproduce this on my machine a couple of times yesterday, but today I have run the test all day long without seeing any of these failures.  This lends some credence to the theory that this is due to unreliability of the remote service these tests use (perhaps today that service is under less load than yesterday).

@davidsh, @CIPop, does your team own the test servers in Azure?  Is there anything we might do to improve reliability there?

**Comment by davidsh** [comment] 2016-07-14 16:42
@ericeil Yes, we own the Azure test server endpoints, i.e. corefx-net.cloudapp.net.

These problems are not caused by the test servers themselves.  The test servers are running as cloud services (Web Roles) with multiple cores and multiple fault-tolerant instances. The issue appears to be an Azure front-end/load-balancer latency issue causing us to see "timeouts".  We are looking into mitigations for this at least for the CI system (i.e. reduce network latency by using "closer"  test server endpoints and/or moving some more tests (but not all) to loopback.

**Comment by CIPop** [comment] 2016-07-14 17:45
> does your team own the test servers in Azure? Is there anything we might do to improve reliability there?

@ericeil See #9048. I have submitted a PR that would allow anyone to install their own IIS-based service locally, enable additional enterprise-level tests (Kerberos, NTLM). The locality of the environment should help us differentiate better between a product and a server-side issue.

**Comment by ericeil** [comment] 2016-07-14 21:14
@davidsh thanks!  Please close this as duplicate of whatever issue(s) you have tracking the reliability work.

@CIPop yes, that does sound very helpful!

**Comment by davidsh** [comment] 2016-09-01 22:22
Mitigated with PR #11341 and future work part of issue #11345

**Closed by davidsh** 2016-09-01 22:22 UTC
Labels: System.Net, X-Plat
