### ISSUE TITLE
no System.Text.Json package produced like other corefx libraries

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/corefx#37043] opened 2019-04-19 21:14 UTC
There is no System.Text.Json package produced, which makes it impossible to add a dependency to it via darc and consume it in a dotnet repo.

**Comment by ahsonkhan** [comment] 2019-04-19 21:26
The current POR is the source package consumption model for netstandard2.0.
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/source_package/README.md
https://www.nuget.org/packages/Microsoft.Bcl.Json.Sources/4.6.0-preview4.19212.13

aspnet consumes it via auto-dependency update just fine (as far as darc is concerned):
https://github.com/aspnet/AspNetCore/blob/9212f4a3df81ed28707d56e1b339f334fa48eb36/eng/Version.Details.xml#L288-L291
https://github.com/aspnet/AspNetCore/search?q=Microsoft.Bcl.Json.Sources&unscoped_q=Microsoft.Bcl.Json.Sources

**Comment by ahsonkhan** [comment] 2019-04-24 03:31
cc @joperezr (to close once completed in https://github.com/dotnet/corefx/pull/37129)

**Comment by joperezr** [comment] 2019-04-24 16:51
Duplicate of #37126.

Closing

**Closed by joperezr** 2019-04-24 16:51 UTC
Labels: area-System.Text.Json, packaging
