### ISSUE TITLE
Soap encoded serialization fails on a netstandard library when running on Desktop.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#18964] opened 2017-04-26 04:12 UTC
When using soap encoded serialization on a netstandard library and running on Desktop it fails as Desktop has a difference in behavior where it looks for System types (e.g System.Enum, System.Object) in mscorlib.dll but since it was built against netstandard the types it is loading are from netstandard.dll so costumers would hit an InvalidOperationException like this one:

```
System.InvalidOperationException : Unable to generate a temporary class (result=1).
        error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. 
       You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

There needs to be a solution here for 2.0 as costumers could be hitting this when using soap encoded serialization on a netstandard library and trying to run it on Desktop. 

For more information see: https://github.com/dotnet/corefx/pull/18743#issuecomment-296306832

cc: @weshaggard @shmao

**Comment by shmao** [comment] 2017-04-28 18:44
The root cause of the issue is explained by https://github.com/dotnet/corefx/pull/18743#issuecomment-296306832.

It seem to me that we need to make changes on full framework to fix the issue. Is there anything we can do to address the issue in NetCore?

@weshaggard @zhenlan

**Comment by danmosemsft** [comment] 2017-05-08 17:18
@weshaggard @zhenlan

**Comment by zhenlan** [comment] 2017-05-09 02:31
I discussed this with @weshaggard and @shmao separately. There is no good solution or workaround.

For 2.0, probably all we can do is to document this. For the long run, maybe CodeDom provider (compiler) on desktop should be updated to be netstarnd aware to solve the issue system wide.

**Comment by weshaggard** [comment] 2017-05-09 16:05
In that case I tagged as netfx-port-consider so a netfx bug is created to try and fix this there.

**Comment by shmao** [comment] 2017-11-09 19:41
We'd like to add this into the known issue list for .NetStandard 2.0 release notes.

**Comment by Carq** [comment] 2017-12-15 09:45
@shmao @weshaggard @zhenlan 
Hi guys, any progress with resolving this issue? Currently in my project correctly we are struggling with this problem. Can you provide some estimation when this issue will be resolved?

**Comment by zhenlan** [comment] 2017-12-18 19:31
No progress on this. We don't have a good solution at this point.

**Comment by shmao** [comment] 2018-01-11 19:24
@carq Can you please share a repro app with us so that we can understand your scenario better? Thanks!

**Comment by huanwu** [comment] 2018-01-30 22:49
It is not only repro for soap encoded serialization, it actually repro for all serialization using c# codegen (set UseLegacySerializerGeneration=true in config). It failed when to compile the code [here](http://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/Compilation.cs,407) For soap type, it will always use c# generation, that's why we see the error. It doesn't repro using IL gen. For non-soap serialization, we can workaround it if we want to use c# codegen by using pre-generated serializer.  But this is not applicable for soap since the serializer won't try to load pregenerated assembly if passing a mapping instead of type when initialize the XmlSerializer [reference code](http://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/XmlSerializer.cs,169)

**Comment by PeterHag** [comment] 2018-04-15 06:51
Hi Guys, I'm also hitting this issue in my project and it is blocking further development. I've created a .NET Standard library and reference this from a .NET Framework 4.7.1 console application. Inside the library I use XmlSerialization but it does not work due to the thread error:

System.InvalidOperationException: 'Unable to generate a temporary class (result=1).
error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

I'm considering  to re-target .NET Standard library back to .NET Framework until the issue is solved.
I'd like to know if this is the best workaround for now or do I have alternatives?

**Comment by PeterHag** [comment] 2018-04-18 03:35
Hi Lukasz,

Thanks for the suggestion. I'll try it as soon as possible, probably in
week-end and I will let you know if it solved my problem.

Kr,
Peter

2018-04-16 15:58 GMT+02:00 Lukasz C. <notifications@github.com>:

**Comment by zhenlan** [comment] 2018-04-18 07:09
The issue eventually needs to be addressed in full framework to make xmlserializer code-gen be aware of netstandard.dll and add it in references for compiler.

**Comment by PeterHag** [comment] 2018-04-22 11:59
@Carq 
Tried your suggestion and indeed it works because it now creates 2 versions.
I agree with Zhenlan that there is still a lot of work to be done. But at least now I can target .NET Standard 2.0 to ensure my API stays clean.
Thanks for the help guys, really appreciate it!

**Comment by huanwu** [comment] 2018-05-10 18:45
Need open a bug on desktop.

**Comment by safern** [comment] 2018-05-10 18:47
It should already be opened. The netfx-port-consider tag should cause it to be opened automatically.

**Comment by huanwu** [comment] 2018-09-13 18:38
To fix this, we need load netstandard reference assembly in runtime. This is impossible at runtime. Close it as Won't Fix. Multi-targeting is a solution.

**Closed by huanwu** 2018-09-13 18:38 UTC
Labels: area-Serialization, documentation, netfx-port-consider

**Comment by wexman** [comment] 2019-09-03 09:47
I have now also run into this problem, however there's no soap involved?!? I have a piece of xml here that I'm trying to deserialize from and am getting the same exception as mentioned above.

However, that XML *is* transported via soap, but as a string.

I would like to ask how the XmlSerializer determines when to use soap encoding and when not to? Can anyone explain?

**Comment by wexman** [comment] 2019-09-03 13:26
Had a little debugging fun stepping through the internals of the XmlSerializer with DnSpy. It seems in my case, IL gen is tried first but throws an exception, and then (as a fallback?) the code gen way is tried which does not work for netstandard...

**Comment by wexman** [comment] 2019-09-03 13:44
I now have a code to reproduce the problem if anyone's interested. I have created a small library assembly targeting netstandard 2.0 and a console app targeting framework 462 (behaves the same for 472).

Library code:

`using System.Collections.Generic;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace SomeLibrary
{
    public class Class1
    {
        [XmlArrayItem(Type = typeof(SomeConcreteClass))]
        public List<SomeAbstractClass> SomeList { get; set; }
    }

    public abstract class SomeAbstractClass
    {
    }

    public class SomeConcreteClass : SomeAbstractClass, IXmlSerializable
    {
        public XmlSchema GetSchema()
        {
            return null;
        }

        public void ReadXml(XmlReader reader)
        {
            return;
        }

        public void WriteXml(XmlWriter writer)
        {
            return;
        }
    }
}
`

Console app:
`using SomeLibrary;
using System;
using System.Xml.Serialization;

namespace SomeApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var someSerializer = new XmlSerializer(typeof(Class1));

            Console.WriteLine("XmlSerializer successfully created!");
            Console.ReadKey();
        }
    }
}
`

The constructor of the XmlSerializer will throw an exception.

**Comment by wexman** [comment] 2019-09-03 14:09
The exception happens in System.Xml.Serialization.SourceInfo.InternalLoad when trying to convert an IXmlSerializable to SomeAbstract class, which doesn't seem right. My guess is that this also failes when the library targets .net framework, but there the fallback will jump in an use the code generation approach.

**Comment by tamlin-mike** [comment] 2019-11-17 15:29
Having spent hundreds of hours trying to bring one of our applications to use SDK-style projects and netstandard2.0 assemblies, we have also hit this. To add insult to injury we (somehow) managed to get everything else "working" in some patchwork way by mixing in old or even outdated nuget packages and possibly a portion of just sheer luck (which is obviously not an acceptable state since **you** could again break **our** software without warning), but finally having gotten it to a state we should be able to do runtime testing, it turns out we're being slammed hard, head-first, into a solid concrete wall.

In our case no soap, vaseline, or any kind of chemicals are included, just runtime generation of XML serialization, and it looks like this is going to be _the_ show-stopper for the project.
No amount of "workarounds" will be accepted. If it doesn't work, it's broken. Period.

@huanwu I question the validity of the following claim
> To fix this, we need load netstandard reference assembly in runtime.

In our case, the (correct version) netstandard dll is already loaded into the running application. Surely the more than rich type/identifier/runtime-query-and-generation system of .NET can use the "real deal" instead of a stripped down interface DLL.

I do thank you for showing Microsoft's true colors, with the following perl:
> Close it as Won't Fix

With partners like that, who needs enemies?

Since it is broken (we frankly don't care what you _think_; this used to work, now it doesn't, and it's due to your changes), and you actively and intentionally _refuse_ to fix it, would you advice us taking the hit of moving to a more reliable and dependable platform, or do you think we should continue to bleed money waiting for Microsoft to never fix this?

What a bug-ridden worm-infested mess you have created. What a mess...
