### ISSUE TITLE
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#28051] opened 2018-03-14 09:49 UTC
tests failed on Ubuntu16.04 when COMPlus_GCStress=3:

```
<test name="System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName" type="System.Net.NameResolution.Tests.GetHostByNameTest" method="DnsObsoleteGetHostByName_EmptyString_ReturnsHostName" time="0.2165148" result="Fail">
        <failure exception-type="System.Net.Internals.SocketExceptionFactory+ExtendedSocketException">
          <message><![CDATA[System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address]]></message>
          <stack-trace><![CDATA[   at System.Net.Dns.InternalGetHostByName(String hostName) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 65
   at System.Net.Dns.GetHostByName(String hostName) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 32
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /home/gcsuser/corefx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 108]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName" type="System.Net.NameResolution.Tests.GetHostByNameTest" method="DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName" time="0.1970667" result="Fail">
        <failure exception-type="System.Net.Internals.SocketExceptionFactory+ExtendedSocketException">
          <message><![CDATA[System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address]]></message>
          <stack-trace><![CDATA[   at System.Net.Dns.InternalGetHostByName(String hostName) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 65
   at System.Net.Dns.ResolveCallback(Object context) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 358
   at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult) in /home/gcsuser/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 383
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName() in /home/gcsuser/corefx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 117]]></stack-trace>
        </failure>
      </test>
```

**Comment by karelz** [comment] 2018-03-14 16:05
Duplicate of #24355

**Closed by karelz** 2018-03-14 16:05 UTC
Labels: os-linux
