### ISSUE TITLE
BitConverter - Select Endianness 

### ISSUE THREAD

**Issue by deinok** [dotnet/corefx#28548] opened 2018-03-28 14:21 UTC
Add a way to set the Endianness of the methods. Something like:
```csharp
public static ushort ToUInt16(byte[] value, int startIndex, Endianness endianness=Endianness.BigEndian);
```

Where the default parameter points to the system default endianness

**Comment by karelz** [comment] 2018-03-28 15:42
Duplicate of #22405
See https://github.com/dotnet/corefx/issues/22405#issuecomment-334282741 - it was superseded by #22355.

**Closed by karelz** 2018-03-28 15:42 UTC
