### ISSUE TITLE
sign.targets error during development (-release) workflow

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#29495] opened 2018-05-03 21:15 UTC
When rebuilding w/o a `git clean -x -d -f` 
```
./build-managed.sh -release
./build-managed.sh -release
```
The second build issues may errors of the form.
```
Tools/sign.targets(113,5): error : 
bin/obj/ref/System.Security.Principal.Windows/4.1.1.0/netstandard/System.Security.Principal.Windows.dll
: PE file is already strong-name signed.
```

Similar errors occur with this workflow.
```
./build-managed.sh -release
./build-tests.sh -release -SkipTests -- /p:WithoutCategories=IgnoreForCI
./build-tests.sh -release -SkipTests -- /p:WithoutCategories=IgnoreForCI
```

**Comment by hughbe** [comment] 2018-05-10 10:03
I can reproduce this and its really annoying for contributions:

```sh
git clone https://github.com/hughbe/corefx.git
cd corefx
./build.sh
cd src/System.Drawing.Common/tests
../.../../tools/msbuild.sh /T:BuildAndTest
```

```
/Users/hugh/Documents/GitHub/corefx/Tools/sign.targets(113,5): error : /Users/hugh/Documents/GitHub/corefx/bin/obj/AnyOS.AnyCPU.Debug/RemoteExecutorConsoleApp/netstandard/RemoteExecutorConsoleApp.exe: PE file is already strong-name signed. [/Users/hugh/Documents/GitHub/corefx/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.csproj]
```

**Comment by joperezr** [comment] 2018-05-10 19:06
sure, taking a look now.

**Comment by joperezr** [comment] 2018-05-10 22:14
just tried it on my high sierra machine and couldn't get a repro either. I have definitely seen this problem in the past, but it seems like we still haven't found a consistent repro yet. @hughbe if you are able to find one, please do let us know. Also, getting a binlog of a repro would be even better 😄

**Comment by danmosemsft** [comment] 2018-05-10 22:47
In https://github.com/dotnet/coreclr/issues/17950 it seems it requires a rebuild.

**Comment by adiaaida** [comment] 2018-05-11 20:39
We're seeing this in the dotnet/optimization repo, where we collect PGO data for coreclr, as well. We build coreclr twice, once with pgo instrumentation and once without as a workaround for an llvm limitation, and on the second build, we see the same issue as in dotnet/coreclr#17950.

**Comment by sdmaclea** [comment] 2018-05-11 21:01
When I looked briefly at the issue, it seemed the problem was that it was signing in place.  That is signing was not creating a signed file in a different place.  This seems like it breaks normal build workflow.

**Comment by danmosemsft** [comment] 2018-05-12 00:31
@sdmaclea you are right. The OpenSourceSign task modifies the file in place. It also has a test when it runs that the file has not been already signed. Its execution is gated by comparing the assembly timestamp against a fake file with the extension ".oss_signed" which is written after the task executes.

Modifying a file in place is not good practice for builds because it is hard to fail atomically. Eg., if the build is interrupted between the signing and the writing of the ".oss_signed" file then the next build will attempt to sign again and get the error. There are likely other failure modes.

Options to fix include (1) signing to a new location (note - signiing to a temporary location then renaming back does not count. If this is too impactful then another possibility is (2) stop erroring when file is already signed, just re-sign it

**Comment by danmosemsft** [comment] 2018-05-15 05:37
See PR for discussion of better solution

**Comment by wtgodbe** [comment] 2019-02-19 21:00
Closing as dup of https://github.com/dotnet/corefx/issues/29331

**Closed by wtgodbe** 2019-02-19 21:00 UTC
Labels: area-Infrastructure, bug
