### ISSUE TITLE
Please add extension method Dictionary.TryGetValue return nullable

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#16254] opened 2017-02-17 04:39 UTC
I think this extension method would be useful

```C#
public static V? TryGetValue<K,V>(this IDictionary<K,V> dict,K key) where V : struct
{
	V v;
	return dict != null && dict.TryGetValue(key,out v) ? v : (V?)null;
}

public static V Get<K,V>(this IDictionary<K,V> dict,K key,V defaultValue) where V : struct
{
	return dict?.TryGetValue(key) ?? defaultValue;
}

public static V Get<K,V>(this IDictionary<K,V> dict,K key) where V : class
{
	V v;
	return dict != null && dict.TryGetValue(key,out v) ? v : null;
}
```

**Comment by ViIvanov** [comment] 2017-02-17 05:39
Looks like names `GetValueOrNull` and `GetValueOrDefault` will be more convenient. `TryGet...` is well known pattern for methods that returns bool and with last `out` parameter.

**Comment by Thaina** [comment] 2017-02-17 05:49
Thanks for suggestion. I don't mind any naming just want this functionality

But for compaction could the latter be `GetDefault` ?

**Comment by karelz** [comment] 2017-02-17 08:39
Looks like dupe of #3482

**Closed by karelz** 2017-02-17 08:39 UTC
