### ISSUE TITLE
[Porting][HttpListener] HttpListenerContext.AcceptWebSocketContextAsync throws PNSE for authentication

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20389] opened 2017-05-27 02:00 UTC
The following test passes on desktop, but fails with netcoreapp:
```
[ConditionalFact(nameof(IsNotWindows7OrUapCore))]
[ActiveIssue(123, TargetFrameworkMonikers.Netcoreapp)]
public async Task AcceptWebSocketAsync_AuthorizationInHeaders_ThrowsNotImplementedException()
{
    Socket.Options.SetRequestHeader("Authorization", "Basic " + Convert.ToBase64String(Encoding.ASCII.GetBytes("user:password")));
    Factory.GetListener().AuthenticationSchemes = AuthenticationSchemes.Basic;

    HttpListenerContext context = await GetWebSocketContext();
    Assert.Equal("user", context.User.Identity.Name);

    HttpListenerWebSocketContext webSocketContext = await context.AcceptWebSocketAsync(null);
    IPrincipal user = webSocketContext.User;

    // Should be copied as User gets disposed when HttpListenerContext is closed.
    Assert.NotSame(context.User, webSocketContext.User);

    Assert.Equal("user", webSocketContext.User.Identity.Name);
    Assert.Equal("Basic", webSocketContext.User.Identity.AuthenticationType);
}
```

A NotImplementedException is also thrown for NTLM/Negotiate/Digest authentication but I can't submit tests for this as these authentication schemes are completely broken (they throw an NRE or hang)

**Comment by hughbe** [comment] 2017-05-29 02:16
This issue now tracks a PNSE thrown for NTLM, Negotiate and Digest authentication. This is because the netcoreapp implementation of these authentication types is already entirely broken (#20096)

**Comment by stephentoub** [comment] 2017-05-29 23:46
> they throw an NRE or hang

@cipop fixed the NRE.  The hang is in the test, not the product.  The product is failing the auth request, and if the test were written to notice the failing client side, it wouldn't hang.

**Comment by stephentoub** [comment] 2017-05-29 23:48
> is already entirely broken (#20096)

Let's be careful throwing around terminology like "entirely broken".  How do you know it's "entirely broken"?  Just because the test being written doesn't pass, that doesn't mean it's entirely broken.  It could be something more subtle about the test.

**Comment by CIPop** [comment] 2017-06-01 23:40
No stack so I'll have to repro this locally. Repro isn't as easy as copy/paste in WebSocketTest.cs so I need to spend some time to figure out what's missing (or which file to paste it in to have all dependencies).

This could be one of two things:

1. Related to unimplemented portions of WebSocket tracked by #5120.
2. Something that was cut (or missed) during the port from .Net Framework.

Either way it looks like something by design but I'd like to confirm

**Comment by CIPop** [comment] 2017-06-01 23:49
I found the exact test checked in and without the ActiveIssue:

https://github.com/dotnet/corefx/blob/00f9b291f8e842b87a77c1b6d2cd33b124e4a33b/src/System.Net.HttpListener/tests/HttpListenerContextTests.cs#L100

@hughbe @stephentoub I'm confused now:
1. The test is saying "ThrowsNIE" but the code doesn't assert that it throws.
2. The test seems to run (no ActiveIssue).

If this is still an issue, please reopen the bug.

**Closed by CIPop** 2017-06-01 23:49 UTC
Labels: area-System.Net.Http, bug, os-windows, tenet-compatibility
