### ISSUE TITLE
JsonSerializer outputs Unicode codes instead of characters

### ISSUE THREAD

**Issue by JohnyL** [dotnet/corefx#38576] opened 2019-06-15 17:12 UTC
I have the following code:
```c#
public class Point
{
    public string Value { get; set; }
}
var json = JsonSerializer.ToString(new Point { Value = "This is \"first\" point." });
```
Now `json` contains the following:

> {"Value":"This is \u0022first\u0022 point."}

**Comment by vcsjones** [comment] 2019-06-16 05:18
What is the output you expected? The quotes need to be escaped in some fashion.

Also this appears to be related to or duplicate of #38543 and #38354.

**Comment by ahsonkhan** [comment] 2019-06-18 05:49
This is a duplicate of existing issues:
https://github.com/dotnet/corefx/issues/35385
https://github.com/dotnet/corefx/issues/34958

We plan to add the ability for the caller to modify the default behavior by passing in a custom `JavaScriptEncoder` to `JsonWriterOptions`, `JsonSerializerOptions`, and `JsonEncodedText`.
https://github.com/dotnet/corefx/issues/37192

**Comment by ufcpp** [comment] 2019-06-18 06:11
I never want to use a serializer which escape non-ASCII characters. It's too ugly and slow.

```cs
using System;
using System.Text.Json.Serialization;

class X { public string Value { get; set; } }

class Program
{
    static void Main()
    {
        var s = JsonSerializer.ToString(new X { Value = "あいうえお" });
        Console.WriteLine(s); // {"Value":"\u3042\u3044\u3046\u3048\u304a"}
    }
}
```

👍 to a custom encoder/options.

**Comment by scalablecory** [comment] 2019-06-18 19:57
json is utf-8, this seems like a bug if it's escaping *all* non-ascii codepoints.

**Comment by ahsonkhan** [comment] 2019-06-18 21:46
Closing as duplicate.

**Closed by ahsonkhan** 2019-06-18 21:46 UTC
Labels: area-System.Text.Json
