### ISSUE TITLE
[HttpClient] [Serializer] HttpClient.GetJsonAsync returns an empty tuple

### ISSUE THREAD

**Issue by MaurizioVerde** [dotnet/corefx#39911] opened 2019-07-31 07:51 UTC
In version SDK 3.0.100-preview7-012821 the GetJsonAsync extension method returns an empty tuple
To Reproduce

Run this code
var retValue = await Http.GetJsonAsync<(bool Success, string ErrorMessage, MyClass MyClass)>("api/MyClass/GetMyClass");
the APIController returns (true, null, MyClass)
The returned tuple from GetJsonAsync is empty (false, null, null)
In preview 5 before version '3.0.0-preview6.19307.2' the tuple was successfully deserialized

Additional Info
worked around this way
@using Newtonsoft.Json
@using Newtonsoft.Json.Serialization
@using System.Text.Json.Serialization
var message = await Http.GetAsync("api/Seminar/GetFirstAvailable");
string content = await message.Content.ReadAsStringAsync();
(bool Success, string ErrorMessage, Seminar Seminar) retValue = JsonConvert.DeserializeObject<(bool Success, string ErrorMessage, Seminar Seminar)>(content);
(I had to go back to Newtonsoft.Json due to "options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore" missing in System.Text.Json)

**Comment by eiriktsarpalis** [comment] 2019-07-31 11:07
Would you be able to provide a minimal reproducing that includes the definition of `MyClass` and the value of `content`?

**Comment by MaurizioVerde** [comment] 2019-07-31 12:14
> Would you be able to provide a minimal reproduction that includes the definition of MyClass and the value of content?

@eiriktsarpalis here the definition of the class: it's a model on EF codefirst. all the involved entity properties are string or bool or date

    public class Seminar : ListableEntityBase
    {
        public string Name { get; set; }

        public DateTime? EventDate { get; set; }

        public DateTime? EventStartTime { get; set; }

        public DateTime? EventEndTime { get; set; }

        public  ICollection<SpeakerOnSeminar> SpeakersOnSeminar { get; set; }

        [NotMapped]
        public List<Speaker> Speakers { get => SpeakersOnSeminar.Select(x => x.Speaker).ToList(); }


        [NotMapped]
        public override string FullTextSearchableString { get => ($"{Name}|{string.Join("|", Speakers.Select(x => x.FullTextSearchableString))}|{(EventDate.HasValue ? $"|{EventDate.Value.ToString("dd/MM/yyyy")}" : string.Empty)}{(EventStartTime.HasValue ? $"|{EventStartTime.Value.ToString("HH:mm")}" : string.Empty)}{(EventEndTime.HasValue ? $"|{EventEndTime.Value.ToString("HH:mm")}" : string.Empty)}"); }

        public int? SeminarCategoryID { get; set; }
        public  SeminarCategory SeminarCategory { get; set; }
    }


    public class SpeakerOnSeminar : ListableEntityBase
    {

        public int? SeminarID { get; set; }
        public  Seminar Seminar { get; set; }

        public int? SpeakerID { get; set; }
        public  Speaker Speaker { get; set; }

        [NotMapped]
        public override string FullTextSearchableString { get => $"{Speaker?.FullTextSearchableString}|{Seminar?.FullTextSearchableString}"; }
    }

    public class Speaker : ListableEntityBase
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public string EMailAddress { get; set; }

        public string ProfileImageName { get; set; }

        [NotMapped]
        public string ProfileImagePath { get => ($"/Resources/Images/Models/Speakers/{(string.IsNullOrWhiteSpace(ProfileImageName) ? "NoImage.png" : ProfileImageName)}"); }

        [NotMapped]
        public override string FullTextSearchableString { get => $"{Name}|{EMailAddress}"; }
    }

Even though nullable, the properties was filled in the sample

Thanks
Maurizio

**Comment by MaurizioVerde** [comment] 2019-07-31 12:39
If i try to serialize through System.Text.Json manually i get this error

![image](https://user-images.githubusercontent.com/37407135/62212048-3cefd280-b3a0-11e9-992f-e2b1b980a315.png)

and this is the content
![image](https://user-images.githubusercontent.com/37407135/62212354-d4552580-b3a0-11e9-8220-a03f975e1e21.png)

**Comment by ahsonkhan** [comment] 2019-07-31 20:04
Looks like your class model contains a loop.

Circular references (equivalent to an option for Newtonsoft Json's `ReferenceLoopHandling`) is not yet supported in `System.Text.Json`, v1 as part of .NET Core 3.0.

This looks like a duplicate of https://github.com/dotnet/corefx/issues/38579.

However, we **should** fix the error message to return something more meaningful so it is clear what went wrong.

**Comment by steveharter** [comment] 2019-08-07 18:16
I'll keep this issue open until we change the error message.

**Comment by steveharter** [comment] 2019-08-07 22:37
FWIW the `JsonException` being thrown has a `Path` property which can be inspected to see what the cycle is.

**Comment by steveharter** [comment] 2019-08-08 18:52
Closing. The original issue is caused by a cycle which is currently not supported.

The exception message was improved (master and [3.0](https://github.com/dotnet/corefx/pull/40158)).

**Closed by steveharter** 2019-08-08 18:52 UTC
Labels: area-System.Text.Json
