### ISSUE TITLE
.net core 3.0 system.text.json option for ignoring property at runtime like newstonsoft DefaultContractResolver

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/corefx#42043] opened 2019-10-23 17:23 UTC
I am migrating my .net core 2.1 application to .net core 3.0 and getting rid of newtonsoft
I am using following code

```
public class PropertyRenameAndIgnoreSerializerContractResolver : DefaultContractResolver
    {
        private readonly Dictionary<Type, HashSet<string>> _ignores;

        public PropertyRenameAndIgnoreSerializerContractResolver()
        {
            _ignores = new Dictionary<Type, HashSet<string>>();
        }

        public void IgnoreProperty(Type type, params string[] jsonPropertyNames)
        {
            if (!_ignores.ContainsKey(type))
                _ignores[type] = new HashSet<string>();

            foreach (var prop in jsonPropertyNames)
                _ignores[type].Add(prop);
        }
    }
	
	then in calling program i have some thing like
	if(condition)
	{
				var jsonResolver = new PropertyRenameAndIgnoreSerializerContractResolver();
                jsonResolver.IgnoreProperty(typeof(ResponseJson), "Log_id");
                jsonResolver.IgnoreProperty(typeof(ResponseJson), "Log_status");
                var json = JsonConvert.SerializeObject(response, Formatting.None,
                    new JsonSerializerSettings { ContractResolver = jsonResolver });
...					
					}
					else
					{
	var json = JsonConvert.SerializeObject(response, Formatting.None);
...	
					}
```
what should i do to achieve same without newtonsoft

**Comment by xsoheilalizadeh** [comment] 2019-10-24 05:50
It's related to #42001, any idea about this issue?
@stephentoub

**Comment by layomia** [comment] 2019-11-23 04:14
Duplicate of https://github.com/dotnet/corefx/issues/42001.

**Closed by layomia** 2019-11-23 04:14 UTC
Labels: area-System.Text.Json
