### ISSUE TITLE
Remove sources from our symbol packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#19781] opened 2017-05-15 16:46 UTC
We've gone to a lot of effort to preserve building symbols packages including source in those packages.

Certainly we need to flow symbols to core-setup in our transport packages so that we can produce symbols zips for shared framework, that is not in question.

The things that are in question are the following:
1. Do we need symbols.nupkgs at all?
2. If we do produce them, do they need to contain source files?

@dagood added this infrastructure in 1.0 and we've done work to keep it working in 2.0 with the flattened packages.

/cc @dagood @weshaggard @gkhanna79 @chcosta

**Comment by dagood** [comment] 2017-05-15 17:10
> Do we need symbols.nupkgs at all?

I think we need a symbol package for any package that anyone will consume DLLs from. Maybe that means fewer CoreFX packages need symbol packages than what we have today, but I believe there are some CoreFX packages that aren't part of the shared framework that will still need symbol packages.

> If we do produce them, do they need to contain source files?

@markwilkie, you mentioned https://github.com/dotnet/roslyn/issues/12759 as a way to source link our PDBs going forwards. Do you think we should stop using MyGet for this and switch to sourcelinking to GitHub instead? Should we continue publishing sources to MyGet until we switch over?

**Comment by markwilkie** [comment] 2017-05-16 20:21
There may be a way in the future to source-link symbols without including the source in the nupkgs, but my understanding for now is that the myget symbol server is what we're placing our bet on - and this includes our released symbols once symbol signing gets sorted.

@ericstj - Perhaps there are some things we can do to reduce the overhead moving forward?

@noahfalk might have additional opinions on this matter.

cc/ @crummel

**Comment by ericstj** [comment] 2017-05-16 20:43
I thought folks are looking to source-index the PDBs directly to github URLs which would mean we don't need source in the nupkgs nor would we require myget to rewrite them.

> Perhaps there are some things we can do to reduce the overhead moving forward?

The overhead I'm discussing here is actually flowing the source, so you can't really reduce that without dropping the requirement.  I'm trying to understand if its a real requirement.  AFAIK no one is testing or consuming the source-indexing of our symbols on myget, and @dagood let me know that we don't even publish the RTM symbol packages to nuget.org, which is what made me raise this issue.

**Comment by weshaggard** [comment] 2017-05-23 18:44
I don't think there is anything we are going to do for 2.0 here so moving to 2.1

**Comment by ericstj** [comment] 2017-05-23 19:01
Agreed, I filed against 2.0 because I was going to rip all this out if we didn't need it.

**Comment by weshaggard** [comment] 2017-12-11 19:20
@vancem @mikem8361 what is your guys take on using symbol packages at all? With the new symbol publishing work can we just stop producing symbol packages now are do we still want them as a transport mechanism?

**Comment by mikem8361** [comment] 2017-12-11 19:47
I still want them as a transport method.  My new uploader tools take a symbol nupkg as its input.  We can eventually stop publishing the packages though.

**Comment by vancem** [comment] 2017-12-13 22:50
As @mikem8361  indicates we need SOMETHING that builds produce that include the symbols (so we can upload them).  We MAY decide to put the PDBs in the main package and not have a separate symbol package, but that seems too costly at least in the native code case (maybe for managed).   

Also, we really can't contemplate dropping them until the replacement (the cool symbol server), works EVERYWHERE and has proven RELIABLE.  

I think we need to support them for quite a while yet...

**Comment by weshaggard** [comment] 2017-12-15 23:12
OK so it sounds like we will keep symbol packages. However the second question in the issue is around including source files in them? With SourceLink I assume we don't need to do that any longer is that your guys assumption as well?

**Comment by mikem8361** [comment] 2017-12-15 23:20
Yes, we do not need to include the source files anymore.  SourceLink should be enabled now in all of our coreclr/corefx projects.

We also should not include the reference assemblies and the reference assembly pdbs in the symbol packages.  The uploader build task will blindly upload all the files in any package named “*.symbols.nupkg”.  I have observed that are a lot of dlls/pdbs under the “ref/netcoreapp2.1” directory in the packages we are publishing.

**Comment by weshaggard** [comment] 2018-03-06 00:35
I've updated to title to reflect the work then which is to keep the symbol packages for transportation and indexing of the symbols but remove the source code from them as SourceLink will be the way to get the source code.

**Comment by ViktorHofer** [comment] 2019-07-24 21:51
@wtgodbe is this still todo?

**Comment by wtgodbe** [comment] 2019-07-24 21:58
No, this can be closed

**Closed by wtgodbe** 2019-07-24 21:58 UTC
Labels: area-Infrastructure
