### ISSUE TITLE
VS 2015 CTP 6 compile error

### ISSUE THREAD

**Issue by talebi** [dotnet/corefx#1238] opened 2015-03-25 03:03 UTC
I've already added a comment to this thread:
https://github.com/dotnet/corefx/issues/1001#issuecomment-84494151

Simply cannot compile a project having a reference to Revit API 2013. It says:
Metadata file 'E:\dev\cadtools_revit\Source\Lib\RevitAPI\RevitAPI_x64_2013.dll' could not be opened -- Row ID or heap offset is too large. The same project compiles in previous VS versions.

**Comment by ellismg** [comment] 2015-03-25 07:19
This is a better fit for the roslyn repo.  I will move this there.

**Comment by nguerrera** [comment] 2015-04-17 20:11
@talebi Is that Revit API publicly available?

**Comment by nguerrera** [comment] 2015-04-17 20:19
@talebi Nevermind, found it here: http://usa.autodesk.com/adsk/servlet/index?siteID=123112&id=2484975

**Comment by nguerrera** [comment] 2015-04-17 20:32
@talebi I found a download here: http://usa.autodesk.com/adsk/servlet/index?siteID=123112&id=2484975, but seems it has only docs and templates and that I need the full Revit product.

**Comment by nguerrera** [comment] 2015-04-17 20:33
I'm checking with some folks internally about contacting Autodesk so that we can work with them on this.

**Comment by talebi** [comment] 2015-04-18 02:58
@nguerrera Revit api dlls are part of the actual Revit installation so no, it's not part of the api download.

**Comment by talebi** [comment] 2015-04-18 03:00
But if you install Revit you can find it alongside Revit.exe (called RevitAPI.dll)

**Comment by jbevain** [comment] 2015-04-21 14:38
@nguerrera this is not related to uints :)

The issue is that the assembly is so big that you can find a string heap index that uses more than 24 bits.

Currently PeekReference and StringHandle assume that heap indexes won't be that big.

**Comment by nguerrera** [comment] 2015-04-23 20:58
@jbevain Thanks.

@tmat Ideas? This is actually a pretty fundamental architectural assumption -- that we have enough room in 32 bits to encode references to heap values like metadata tokens.

I'm looking at the bit twiddling around handle types and so forth, and I think I can squeeze more than 24 bits, but the full 32-bit range is just not possible without making Handle and StringHandle wider or allocating some sort of table on the side.

**Comment by tmat** [comment] 2015-04-23 21:47
I see. Oops. #US heap indices have to be < 24 bit. The spec is not clear but it seems that #Blob, #String and #GUID streams are allowed to be indexed by 32-bit index. Not sure if it has to be 29-bit actually, since greater numbers don't fit to compressed integer.

**Comment by tmat** [comment] 2015-04-23 21:52
Seems like we need to introduce HeapHandle that is 40 bits.

**Comment by tmat** [comment] 2015-04-24 00:50
The library is compiled by C++/CLI, which seem to produce a lot of very long identifiers (encoding templates and such).

So I think we would be fine with limiting the index to 2^29. 2^29 distinct string values occupy at least 2^31 bytes on the #String heap: each string needs to be at least 3 bytes long + 1 byte for size and 2^29 * 4 = 2^31, since there is only (2^8)^3 = 2^24 strings of size 3. Likely the strings will be much longer, so it easily hits 2^32 (2GB), which is a limit on PE size we support.

**Comment by tmat** [comment] 2015-04-24 01:13
That leaves us 2 bits for string kind, which is just what we need (we need 3 string kinds). Close but we can keep 4B heap handles.

**Comment by tmat** [comment] 2015-04-24 07:50
After giving it more thought, I think we have 3 options:
1) Keep string, blob and guid handles 32-bit and virtualize handles with indices greater than 2^24.
If we are about to create a new handle with an index grater than 2^24 we assign it a new virtual handle and add an entry to a map {real index <-> virtual index}. We return a virtual string/blob/guid handle (highest bit set). When retrieving a string or byte[] for such handle we look up the map.

2) Disallow conversion to and from Handle. 
This conversion is not that useful anyways. I don't think there is a case in type system metadata where there is a need to return an union of these handles and other handles. 
We have two sub-options:
a) Keep the handles 32bit, allow index up to 2^29, use 1 bit for virtual flag and 2 bits for kind. 2 bits are good enough since we have only 3 internal representations of string handle and 2 of namespace handles. I think limitation to 2^29 is reasonable since it's the max compressed integer. But one can in theory construct an assembly with one a very large string and one small string that starts at offset 2^30 or so, which we won't be able to represent. I don't think that's a real-world scenario though. Usually there will be many medium sized strings. Consider all possible named metadata entities. To exhaust 2^29 bytes there needs to be something like 2^16 * 8 of entities (typedefs, typerefs, memberrefs, methoddefs, etc.), each with 2^9 long unique name, with no prefixing. That's quite a lot even for C++.
b) Make the handles 40bit, allow index up to 2^32. More memory usage - often 4B more due to alignment.

I propose we go with [2a] and amend the ECMA spec to limit the index size to 2^29 (0.5 GB). That would also be beneficial for Portable PDBs where we often use compressed integers to encode heap blobs. If in future we hit the 2^29 limit for some reason, we could use [1] to deal with larger indices and extend compressed integers to handle greater numbers than 2^29. Loosing convertibility to Handle is likely not gonna be an issue. 

[1] makes things complicated. [2b] is less memory efficient for no practical benefit.

**Comment by jbevain** [comment] 2015-04-24 08:11
Agreed. There's no semantic reason to allow conversion between a table handle and a string handle.

**Comment by tmat** [comment] 2015-04-25 02:11
@jbevain We use compressed heap indices in Portable PDB.

I started implementing [2a] and realized that sometimes it is very useful to have Handle that can represent any handle (table or heap) to avoid code bloat. 

I figured there is another approach, which I'm currently pursuing:
3) Change Handle to be 40bit (int + byte). Such handle can store any heap index or table row id. 
Introduce EntityHandle struct that only has 32bit. All handles that represent entities (type ref, spec, def, method def, etc.), but not values (string, blob, guid, user string) are implicitly convertible to EntityHandle. This is what we'd recommend to use for storing entity handles and saving space.

We can also introduce ValueHandle (or LiteralHandle) for symmetry, but it's not really necessary. Heap handles are simply stored as Handles or strongly typed StringHandle, NamespaceDefHandle, etc.

**Comment by tmat** [comment] 2015-04-27 06:48
I think I'm gonna stick with the limitation of 29 bits for index into blob and string heaps to keep StringHandle and BlobHandle 32 bit. 
I don't believe anyone is seriously creating metadata files that are larger than 0.5GB. If we find such scenario in future we can make the handles larger to encode additional bits. But it seems highly unlikely.

The spec says exactly:
"If bit 0 is set, indexes into the “#String” heap are 4 bytes wide; if bit 1 is set, indexes into the “#GUID” heap are 4 bytes wide; if bit 2 is set, indexes into the “#Blob” heap are 4 bytes wide. Conversely, if the HeapSize bit for a particular heap is not set, indexes into that heap are 2 bytes wide.
"

One might infer that this means that the heaps might be up to 4GB large. But I don't think that's what's the spec really means here. First of all the metadata blob as a whole can't be larger than 2GB. Second, on multiple places the spec is unclear on upper bounds. "4 bytes wide" just means the number is encoded in 4 bytes when used in tables (the corresponding column is 4B wide). 

Some other similar quotes from the spec:
1) Row field of #~ stream header: "Array of n 4-byte unsigned integers indicating the number of rows for each present table."

Clearly there can't be more than 2^24 rows in any table. The encoding is 4B integer.

2) 
The physical representation of a row cell e at a column with type C is defined as follows:
- If e is an index into the GUID heap, 'blob', or String heap, it is stored using the number of bytes as defined in the HeapSizes field.
- If e is a simple index into a table with index i, it is stored using 2 bytes if table i has less than 2^16 rows, otherwise it is stored using 4 bytes.

**Comment by nguerrera** [comment] 2015-05-05 20:22
Fixed by #1557

**Closed by nguerrera** 2015-05-05 20:22 UTC
