### ISSUE TITLE
[HttpListener] No test result generated under "System.Net.HttpListener.Tests"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#19466] opened 2017-05-08 09:14 UTC
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170508.01/workItem/System.Net.HttpListener.Tests/wilogs

No test result generated under "System.Net.HttpListener.Tests", no exception in the result.

**Comment by stephentoub** [comment] 2017-05-08 15:04
The log is missing all information after the tests started:
```
2017-05-07 18:35:51,389: INFO: proc(54): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2017-05-07 18:35:51,389: INFO: proc(54): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2017-05-07 18:35:51,390: INFO: proc(54): run_and_log_output: Output: 
2017-05-07 18:35:51,478: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.HttpListener.Tests
2017-05-07 18:35:51,627: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.HttpListener.Tests
2017-05-07 18:35:51,702: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.HttpListener.Tests
```
That suggests that either a) the tests hung, b) the tests crashed and Helix didn't capture the relevant output, or c) something else is wrong with the infrastructure.  It's difficult to diagnose the actual problem from the lack of info.

**Comment by danmosemsft** [comment] 2017-05-08 19:44
@stephentoub if you look at the .py file on the same page, it indicates it hung:
`2017-05-07 18:55:51,050: ERROR: executor(325): _execute_command: Executor timed out after 1200 seconds and was killed.`

We do not get dumplings in such cases apparently. All we could do is attempt to repro possibly with the Helix repro tool.

**Comment by davidsh** [comment] 2017-05-08 21:36
Is this failing on Windows or *Nix ?  It wasn't clear from the labels on this bug.

**Comment by safern** [comment] 2017-05-09 03:48
This is happening on Desktop also for System.Net.Requests.Tests

```
2017-05-09 01:26:36,957: INFO: proc(54): run_and_log_output: Output: xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
2017-05-09 01:26:37,625: INFO: proc(54): run_and_log_output: Output:   Discovering: System.Net.Requests.Tests
2017-05-09 01:26:38,035: INFO: proc(54): run_and_log_output: Output:   Discovered:  System.Net.Requests.Tests
2017-05-09 01:26:38,042: INFO: proc(54): run_and_log_output: Output:   Starting:    System.Net.Requests.Tests
2017-05-09 01:28:19,484: INFO: proc(54): run_and_log_output: Output:     System.Net.Tests.HttpWebRequestTest.ContentLength_SetAfterRequestSubmitted_ThrowsInvalidOperationException(remoteServer: http://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
2017-05-09 01:28:19,484: INFO: proc(54): run_and_log_output: Output:       System.Net.WebException : The operation has timed out
2017-05-09 01:28:19,484: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-09 01:28:19,484: INFO: proc(54): run_and_log_output: Output:            at System.Net.HttpWebRequest.GetResponse()
2017-05-09 01:28:19,484: INFO: proc(54): run_and_log_output: Output:         E:\A\_work\135\s\corefx\src\System.Net.Requests\tests\HttpWebRequestTest.cs(143,0): at System.Net.Tests.HttpWebRequestTest.ContentLength_SetAfterRequestSubmitted_ThrowsInvalidOperationException(Uri remoteServer)
```

See: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170509.01/workItem/System.Net.Requests.Tests/wilogs

**Comment by stephentoub** [comment] 2017-05-10 16:40
I'm going to close this proactively under the assumption that it's a duplicate of one of the other recently opened issues for HttpListener that have now had tests disabled against them.

**Comment by Jiayili1** [comment] 2017-05-15 02:45
This issue is still repro on Portable core tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170515.01/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by stephentoub** [comment] 2017-05-15 03:01
@Jiayili1, did the build mentioned above https://github.com/dotnet/corefx/issues/19466#issuecomment-301363433 include the fix in https://github.com/dotnet/corefx/pull/19755?

**Comment by Jiayili1** [comment] 2017-05-15 06:04
@stephentoub The log is missing all information after the tests started:
~~~
2017-05-14 17:47:43,115: INFO: proc(54): run_and_log_output: Output: xUnit.net console test runner (64-bit .NET Core)
2017-05-14 17:47:43,115: INFO: proc(54): run_and_log_output: Output: Copyright (C) 2014 Outercurve Foundation.
2017-05-14 17:47:43,116: INFO: proc(54): run_and_log_output: Output: 
2017-05-14 17:47:43,204: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.HttpListener.Tests
2017-05-14 17:47:43,361: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.HttpListener.Tests
2017-05-14 17:47:43,448: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.HttpListener.Tests
~~~

And in .py file, it indicates it hung:
~~~
2017-05-14 18:07:42,788: ERROR: executor(325): _execute_command: Executor timed out after 1200 seconds and was killed.
~~~

**Comment by stephentoub** [comment] 2017-05-15 14:11
@Jiayili1, understood, I was asking about the build that was used, though, and wondering when it was built / from what sources so that I could know whether the hang was potentially caused by the test bug fixed in https://github.com/dotnet/corefx/pull/19755.

**Comment by Jiayili1** [comment] 2017-05-16 01:46
@stephentoub the build is 20170515.01, but in build 20170516.01, test result are generated, but all are fire item, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170516.01/workItem/System.Net.HttpListener.Tests

**Comment by CIPop** [comment] 2017-05-17 01:35
@Jiayili1 from the links above, this fails only on OSX. Is that correct? Have you seen this failing in any other OS types / SKUs?

@safern Have you seen this particular failure for Windows? Unless we're suspecting an infrastructure issue, would it be safe to assume that there are no results because the test process crashed?
If that's the case, we should keep the discussions separate (please open a different bug for Requests having no results).

**Comment by safern** [comment] 2017-05-17 03:08
@CIPop the Windows/desktop issue on System.Net.Requests was because some tests where hanging but that was solved a week ago. So about the failure I pointed out we shouldn't worry anymore :). 

Deleted my comment so that it doesn't confuse people as it  is fixed.

**Comment by CIPop** [comment] 2017-05-17 17:56
> because some tests where hanging 

This is good info: this is likely why this is happening on OSX too. 
Marking as such - please remove the tag if this repros on any other OS.

**Comment by karelz** [comment] 2017-05-18 18:18
Triage: 2 failures in 24h, then nothing. Moving to Future as it is likely test issue and Mac lab is now down. If it has higher frequency, we can revisit the decision.

**Comment by Jiayili1** [comment] 2017-05-19 06:14
the test result shows following on build 20170519.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170519.01/workItem/System.Net.HttpListener.Tests/wilogs

~~~
2017-05-18 17:33:45,774: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.HttpListener.Tests
2017-05-18 17:33:45,937: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.HttpListener.Tests
2017-05-18 17:33:46,030: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.HttpListener.Tests
2017-05-18 17:33:48,772: INFO: proc(54): run_and_log_output: Output:    System.Net.Tests.HttpListenerContextTests.AcceptWebSocketAsync_InvalidHeaders_ThrowsWebSocketException(headers: \"Connection: Upgrade\\r\\nUpgrade: Test2\") [FAIL]
2017-05-18 17:33:48,774: INFO: proc(54): run_and_log_output: Output:       System.Net.HttpListenerException : Address already in use
2017-05-18 17:33:48,779: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-18 17:33:48,916: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(160,0): at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure, Boolean& alreadyExists)
2017-05-18 17:33:48,916: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(213,0): at System.Net.HttpEndPointManager.RemovePrefixInternal(String prefix, HttpListener listener)
2017-05-18 17:33:48,917: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs(187,0): at System.Net.HttpEndPointManager.RemoveListener(HttpListener listener)
2017-05-18 17:33:48,917: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs(161,0): at System.Net.HttpListener.Close(Boolean force)
2017-05-18 17:33:48,917: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs(147,0): at System.Net.HttpListener.Dispose()
2017-05-18 17:33:48,917: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/src/System/Net/HttpListener.cs(305,0): at System.Net.HttpListener.Close()
2017-05-18 17:33:48,917: INFO: proc(54): run_and_log_output: Output:          /Users/buildagent/agent/_work/24/s/corefx/src/System.Net.HttpListener/tests/HttpListenerContextTests.cs(28,0): at System.Net.Tests.HttpListenerContextTests.Dispose()
2017-05-18 17:33:48,918: INFO: proc(54): run_and_log_output: Output:             at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
~~~

**Comment by Jiayili1** [comment] 2017-05-22 07:16
Failed again: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170522.01/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by Jiayili1** [comment] 2017-05-23 06:35
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170523.02/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by karelz** [comment] 2017-05-23 08:15
All 3 last failures are on OSX

**Comment by Jiayili1** [comment] 2017-05-24 06:43
This issue is repro on Portable Core Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170524.01/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by karelz** [comment] 2017-05-24 14:34
This failure is now rather more common than we would like. Moving to 2.0.
@hughbe @stephentoub can you please take a look if you get a chance? Thanks!

**Comment by danmosemsft** [comment] 2017-05-24 15:29
Again, on OSX and Debian. Nothing useful can be gotten from the Helix logs - we either need to repro locally, or experiment.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170524.02/workItem/System.Net.HttpListener.Tests/wilogs

**Comment by karelz** [comment] 2017-05-24 22:10
Is it dupe of #20246? cc @mellinoe

**Comment by mellinoe** [comment] 2017-05-24 23:36
It does look like a dupe, although it's hard to say without knowing which test cases are hanging, exactly.

**Comment by mellinoe** [comment] 2017-05-24 23:48
If we see this actively hung in any CI jobs, please let me know and I will try to debug it. Bonus points to anyone who logs into a machine and attaches a debugger before the process terminates :smile:

**Comment by stephentoub** [comment] 2017-05-25 22:16
I believe this is a dup.  Closing under that assumption.

**Closed by stephentoub** 2017-05-25 22:16 UTC
Labels: area-System.Net.Http, os-linux, os-mac-os-x, test bug, test-run-portable
