### ISSUE TITLE
Add Encoding.GetBytes(string, offset, count)

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#14255] opened 2016-12-07 00:37 UTC
The Encoding class has methods for encoding the middle of a `char[]`, but not for the middle of a `string`.  A caller is forced to switch to unsafe (char*)  or to re-allocate as `char[]`.

```diff
    public abstract partial class Encoding : System.ICloneable
    {
...
        public unsafe virtual int GetByteCount(char* chars, int count) { throw null; }
        public virtual int GetByteCount(char[] chars) { throw null; }
        public abstract int GetByteCount(char[] chars, int index, int count);
        public virtual int GetByteCount(string s) { throw null; }
+       public int GetByteCount(string s, int index, int count) { throw null; }
...
        public unsafe virtual int GetBytes(char* chars, int charCount, byte* bytes, int byteCount) { throw null; }
        public virtual byte[] GetBytes(char[] chars) { throw null; }
        public virtual byte[] GetBytes(char[] chars, int index, int count) { throw null; }
        public abstract int GetBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex);
        public virtual byte[] GetBytes(string s) { throw null; }
+       public byte[] GetBytes(string s, int index, int count) { throw null; }
        public virtual int GetBytes(string s, int charIndex, int charCount, byte[] bytes, int byteIndex) { throw null; }
...
}
```

The `GetBytes(string, int, int)` method would allow for the typical "just give me a big enough array" while the `GetByteCount(string, int, int)` method would allow for ensuring that an existing buffer is sufficiently big to call the existing `GetBytes(string, int, int, byte[], int)` method.

**Comment by tarekgh** [comment] 2016-12-07 00:47
@bartonjs 
we already have 

        public virtual int GetBytes(String s, int charIndex, int charCount,byte[] bytes, int byteIndex)

I think this address your request here

**Comment by bartonjs** [comment] 2016-12-07 06:13
No, because you don't know how big the buffer needs to be without GetByteCount.  And the version that just returns a `byte[]` makes the `char[]` and `string` versions have the same shapes.

**Comment by svick** [comment] 2016-12-07 12:10
Should this wait for `Span<T>` (https://github.com/dotnet/corefx/issues/13892)? With that, the API would look something like:

```c#
public virtual byte[] GetBytes(ReadOnlySpan<char> span);
```

And it would cover the existing use cases of `string`, `char[]`, `char[], int, int`, `char*, int` as well as the use case in question here: `string, int, int`.

**Comment by tarekgh** [comment] 2016-12-07 16:53
@svick that make sense to wait for Span<T>.

**Comment by karelz** [comment] 2016-12-07 17:43
Chatted with @bartonjs - this one is higher priority as there is not good safe alternative. If there's plan to have `Span` for 1.2, we could wait, otherwise we might add this API.
Let's discuss the `Span` timeline and our plans in API review meeting next week (keeping 'api-ready-for-review').

**Comment by tarekgh** [comment] 2016-12-07 17:59
I am not seeing this one is urgent to have so I believe we can just wait for Span. why we are seeing this high priority. for me it is still nice to have feature as there is different ways achieve same results.

**Comment by bartonjs** [comment] 2016-12-07 18:05
If there's a concrete plan that adds Span to Encoding, this is closable.

If there's no concrete plan, this will allow already existing over-allocating code to be cleaned up.

**Comment by tarekgh** [comment] 2016-12-07 18:13
@bartonjs right, then we can wait to figure the Span in general. my point is we don't have to rush this as I am not seeing any urgency for it. cleaning up the code is nice but it is not urgent. 

@svick any idea who is looking at Span<T> in general or who is following up?

**Comment by tarekgh** [comment] 2016-12-07 18:23
talked offline with @bartonjs and I am fine if we can take this and discuss it with the design reviewers.

**Comment by terrajobst** [comment] 2016-12-14 19:41
We shouldn't block API additions on `Span<T>`. For one, we don't know when it will ship stable. Secondly, we don't know which assembly it's in, and thirdly, even if had `Span<T>` today, we might still want to add the `string` version because it represents what the customer actually wants to do, i.e. encode a substring. If anything, we could talk about a `StringSegment` type :-)

We think API looks fine as proposed.

**Comment by AlexRadch** [comment] 2016-12-15 15:33
@karelz I am working on this issue.

**Comment by tarekgh** [comment] 2016-12-15 17:17
thanks @AlexRadch 

please include me in your PR.

**Comment by AlexRadch** [comment] 2016-12-15 17:56
@bartonjs  methods should be virtual or not?

**Comment by AlexRadch** [comment] 2016-12-16 07:00
@karelz Can you answer, methods should be virtual or not? Both reviewers @jkotas, @tarekgh are thinking that methods should NOT be virtual and I do not not see any disadvantage to make them non virtual.

**Comment by karelz** [comment] 2016-12-16 18:08
The answer is driven in the PR: https://github.com/dotnet/coreclr/pull/8651#issuecomment-267618392

**Comment by karelz** [comment] 2016-12-18 02:38
For the record: The API proposal was updated by @tarekgh - see https://github.com/dotnet/coreclr/pull/8651#issuecomment-267710949.

**Comment by bartonjs** [comment] 2016-12-19 19:41
Reopening the issue since it needs a `ref` change and new tests in corefx.

**Comment by tarekgh** [comment] 2017-01-04 01:33
@AlexRadch , did you have a chance to work on exposing the APIs in the corefx side? thanks.

**Comment by karelz** [comment] 2017-01-29 06:10
No activity for 1.5 months, unassigning - the issue is back "up for grabs", for anyone to pick it up.
Next steps: Exposed the API in CoreFX and add tests.

**Comment by hughbe** [comment] 2017-03-05 04:57
Looks like this is already implemented in coreclr/corert. I'll grab exposing and testing this

**Comment by tarekgh** [comment] 2017-03-05 18:52
@hughbe this is greater

**Comment by karelz** [comment] 2017-03-06 19:37
Assigning to @hughbe ...

**Comment by hughbe** [comment] 2017-03-07 13:56
This is technically source breaking right?
```
var encoding = new UTF8Encoding();
encoding.GetByteCount(null, 0, 0)
```
String and char[] can both be assigned from null, so this is now ambiguous and fails to compile

**Comment by JonHanna** [comment] 2017-03-07 14:36
It's only ambiguous with a literal null, and it throws ANE when null is passed to it, so the only code that will be broken is code that would always throw. Source-breaking that code is doing the author a favour.

**Comment by hughbe** [comment] 2017-03-07 16:33
Yup as I thought - it's unlikely

**Comment by tarekgh** [comment] 2017-03-07 16:57
we already has the same case before so this is not really something new. for example we have Encoding.GetBytes(char[]) and Encoding.GetBytes(string). I am not really worried about the null case (without casts).

**Closed** 2017-03-09 18:31 UTC
Labels: api-approved, area-System.Text.Encoding, netfx-port-consider, up for grabs, wishlist
