### ISSUE TITLE
IsoStore: Packaging for libraries that only support a single platform

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5406] opened 2016-01-14 01:12 UTC
Today if a package only targets a single platform our packaging 
infrastructure still requires a `dotnetX.Y` reference assembly.

We should relax this requirement since it doesn't make sense,
packages should only use `dotnetX.Y` if they need to be portable
to more than one platform.

Sample packages:
System.IO.IsolatedStorage
System.Runtime.Loader

An alternate solution here would be to tweak these implementations
to work on more than one platform and package them as dotnet
implementations.

**Comment by ericstj** [comment] 2016-01-14 21:37
I'd like to persue the alternate solution here which would be to come up with a dotnet/netstandard implementation of these libraries.

**Comment by ericstj** [comment] 2016-04-23 16:47
Work here is to implement a generic IsolatedStorage contract.  I don't think that meets the bar for RC3 or perhaps even RTM.  Moving out for now.

**Comment by ianhays** [comment] 2016-05-25 20:05
On Win32 we can mimic the WinRT behavior and toss the isostore base folder into AppData or whatever. On Unix we can put it into `~/.local/share`. 

We would have to make some custom logic to mimic how WinRT creates directories on a per-application basis within the appdata folder. That'd be the only real work item though.

My only concern is that I don't get the impression that anyone really uses IsoStore so I'm not certain it would be worth the effort to add it and support it in netstandard. It seems to me like a FileSystem variable pointing to AppData would provide the same functionality from a non-UWP application where we don't need to sandbox files to a certain location.

**Comment by ianhays** [comment] 2016-09-09 17:17
closing this as a functional duplicate of #9842

**Closed by ianhays** 2016-09-09 17:17 UTC
Labels: packaging, System.IO
