### ISSUE TITLE
Behavior of arraySegment.ToArray() has changed

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#19799] opened 2017-05-15 21:06 UTC
_From @jodavis on May 15, 2017 20:25_

I was using `Enumerable.ToArray(this IEnumerable)` on an ArraySegment, which calls `ArraySegment.GetEnumerator()`. This did not throw any exception when the underlying array is null, so `ToArray()` would return an empty array.

Now that ArraySegment has its own `ToArray()` function, my code is calling that one (with no code change on my part). `ArraySegment.ToArray()` throws an exception when called with a null underlying array.

I can work around this, but is this considered a breaking change?

_Copied from original issue: dotnet/corert#3619_

**Comment by jkotas** [comment] 2017-05-15 21:13
@jodavis Similar source code breaking changes when upgrading to newer profile with more APIs are by design, unfortunately. Otherwise, we would not be ever able to add any new APIs.

There is decent chance that people may hit similar collisions when upgrading to .NET Core 2.0 because of the .NET Standard 2.0 API added back will take precedence over the workarounds for missing APIs. Perhaps we may want to mention it in the documentation?

**Comment by karelz** [comment] 2017-05-16 16:04
This is natural impact of evolution -- whenever we add new API (e.g. `Dictionary.GetValueOrDefault), which devs already did their own extension methods for, we will cause either ambiguity (compiler errors), or our implementation will win. There is nothing that can be done about that short of "don't add new APIs", which is obviously undesirable.
Similar thing happened in this case -- the code used some general method and now it uses more specific one, which behaves slightly differently. In this case the new null behavior is in line with other classes, so by design.

Closing ... let me know if you disagree.

**Closed by karelz** 2017-05-16 16:04 UTC
Labels: area-System.Runtime
