### ISSUE TITLE
DateTime.UtcNow is not good enough for high precision durations in DiagnosticSource.Activity

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/corefx#16405] opened 2017-02-23 12:40 UTC
/cc @lmolkova @vancem 

The new Activity class uses `DateTime.UtcNow` to [calculate the duration of an activity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L293). However depending on the system, [the precision of DateTime might be at ~ 15ms](https://blogs.msdn.microsoft.com/ericlippert/2010/04/08/precision-and-accuracy-of-datetime/). 

I don't think this is precise enough for server scenarios.

In my OpenTracing instrumentation, I'm currently using a [combination of DateTime + Stopwatch](https://github.com/cwe1ss/opentracing-contrib-dotnet/blob/master/src/OpenTracing.Tracer.Abstractions/HighResClock.cs) to overcome this issue. My code isn't in production yet though, so I'm not sure if this has any drawbacks.

**Comment by stephentoub** [comment] 2017-02-23 12:44
https://github.com/dotnet/coreclr/issues/5061

**Comment by cwe1ss** [comment] 2017-02-23 13:12
I've just seen that this behavior is already documented in the [ActivityUserGuide](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md). However I still think that the precision should be better by default. It's very hard to discover this behavior and writing a more precise DateTime+Stopwatch combination is quite complex/error-prone ([Stopwatch runs out of sync](http://stackoverflow.com/questions/1416139/how-to-get-timestamp-of-tick-precision-in-net-c), etc.)

@stephentoub thx for the link! Looking forward to see how this will be resolved.

**Comment by karelz** [comment] 2017-02-23 16:54
Closing as dupe of https://github.com/dotnet/coreclr/issues/5061

**Closed by karelz** 2017-02-23 16:54 UTC

**Comment by cwe1ss** [comment] 2017-02-23 17:54
I don't think that's a duplicate. If there won't be a change to UtcNow this problem will still exist.

**Comment by karelz** [comment] 2017-02-23 17:58
That's exactly what https://github.com/dotnet/coreclr/pull/9736 does.

**Comment by cwe1ss** [comment] 2017-02-23 18:02
great, thank you!
