### ISSUE TITLE
API Proposal - Stream to Pipe Wrapper

### ISSUE THREAD

**Issue by Drawaes** [dotnet/corefx#30791] opened 2018-07-02 20:15 UTC
## Rationale
Currently pipelines has no "endpoints" to speak of. There is a vast array of endpoints and "middleware" available in streams. In order to bridge the gap a class should be provided to wrap a stream and provide a pipe on top of it. This would provide access to the rich tapestry of streams to the new world of pipelines.

I believe that both myself @mgravell  and aspnetcore have implemented these a number of times so it is worth this being a type provided by the BCL

## API Shape
The following API is proposed.

``` csharp
namespace System.IO.Pipelines
{
    public class StreamPipe : IDuplexPipe, IDisposable
    {
        public StreamPipe(Stream stream, PipeOptions pipeOptions)
            : this(stream, pipeOptions, true) { }

        public StreamPipe(Stream stream, PipeOptions pipeOptions, bool ownsStream) { }
        
        public PipeReader Input => throw new NotImplementedException();
        public PipeWriter Output => throw new NotImplementedException();
        public void Dispose() => throw new NotImplementedException();
    }
}
```
## Open questions
1. Should the stream be available as a property on the wrapper?
1. Should there be a read only write only version (single pipe not a duplex pipe?)

/cc @geoffkizer @stephentoub @mgravell @davidfowl @benaadams 

Related #27246 
Related #30777

**Comment by mgravell** [comment] 2018-07-02 20:58
Observation:

not all `Stream`s are duplex. There's also read-only streams that can be meaningfully and gainfully exposed as a `PipeReader`, and write-only streams blah blah `PipeWriter`.

suggestion: it should be very clear which is being supported; "create a `StreamPipe` but only use the `.Input` is ugly.

for my pre-existing implementation, I ended up using factory methods: `CreateReader`, `CreateWriter`, `CreateDuplex` etc. I'm not saying it is perfect, but the reality is that `Stream` is **hugely** ambiguous. Even testing `.CanRead` / `.CanWrite` doesn't tell you whether it is duplex (see: `FileStream`, `MemoryStream`, etc).

**Comment by Drawaes** [comment] 2018-07-02 21:05
I would be happy with a StreamPipeWriter and StreamPipeReader and have this as well but I think they could be separate unless there is a drive for both. This should throw if the pipe isn't writable and readable in my opinion.

**Comment by benaadams** [comment] 2018-07-02 21:12
> re your 2 - indeed, not all Streams are duplex. 

 https://github.com/dotnet/corefx/issues/27268 "Add IPipeReader and IPipeWriter and have IDuplexPipe inherit from them" 😢

**Comment by mgravell** [comment] 2018-07-02 21:13
@benaadams I'm just going to point out the other missed opportunity here... `IDuplexPipe : IDisposable`. It probably should have been. But that ship has sailed, so...

**Comment by Drawaes** [comment] 2018-07-02 21:43
In saying all that..... There aren't any endpoints so maybe it's a blessing rather than a curse?

**Comment by mgravell** [comment] 2018-07-03 15:47
In support of why we need *at least* a `Stream` wrapper, please see [Pipe Dreams, part 2](https://blog.marcgravell.com/2018/07/pipe-dreams-part-2.html) - note [part 1](https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html) is *also* relevant as a discussion of the problems that plague the `Stream` API, as further support for the "pipelines > stream" camp :)

**Comment by davidfowl** [comment] 2018-10-17 18:49
Dupe of https://github.com/dotnet/corefx/issues/27246

**Closed by davidfowl** 2018-10-17 18:49 UTC
Labels: api-suggestion, area-System.IO.Pipelines
