### ISSUE TITLE
No test result generated under "System.Xml.RW.XmlWriterApi.Tests"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#21850] opened 2017-07-04 07:03 UTC
No test result generated under "System.Xml.RW.XmlWriterApi.Tests"
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170704.01/workItem/System.Xml.RW.XmlWriterApi.Tests/wilogs

Configuration:
Windows.10.Amd64.ClientRS3-x86
Windows.10.Arm64-arm

~~~
2017-07-03 19:42:18,296: INFO: proc(54): run_and_log_output: Output: Got manifest file appxmanifest.xml
2017-07-03 19:42:18,391: INFO: proc(54): run_and_log_output: Output: Removing any previous installation...
2017-07-03 19:42:18,391: INFO: proc(54): run_and_log_output: Output: Installing the application...
2017-07-03 19:42:19,578: INFO: proc(54): run_and_log_output: Output: Package ID is 5cd54353-3ed7-4a6e-a72f-db349f28867c_1.0.0.0_arm__v52bfwc2c21ha
2017-07-03 19:42:19,609: INFO: proc(54): run_and_log_output: Output: Starting the application...
2017-07-03 19:42:19,609: INFO: proc(54): run_and_log_output: Output: Resolved Folder Path: C:\Users\DotNetTestRunner\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\
2017-07-03 19:42:20,203: INFO: proc(54): run_and_log_output: Output: Waiting for the application to exit...
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: Process has just exited with return code 255.
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: Disabling the debugger...
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: STDOUT & STDERR from imersive process:
2017-07-03 19:42:31,871: INFO: proc(54): run_and_log_output: Output: ==================================================================================
2017-07-03 19:42:31,887: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:31,887: INFO: proc(54): run_and_log_output: Output: ==================================================================================
2017-07-03 19:42:31,887: INFO: proc(54): run_and_log_output: Output: Removing the application...
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: SUCCESS
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: ExitCode 255
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\074ab7a5-2eef-42da-8843-793c057a4837\Work\141c2691-75ba-443e-99a1-c81258f7bb52\Unzip>move C:\Users\DotNetTestRunner\Documents\TestResults\System.Xml.RW.XmlWriterApi.Tests.dll.xml .\testResults.xml 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: The system cannot find the file specified.
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\074ab7a5-2eef-42da-8843-793c057a4837\Work\141c2691-75ba-443e-99a1-c81258f7bb52\Unzip>move C:\Users\DotNetTestRunner\Documents\TestResults\System.Xml.RW.XmlWriterApi.Tests.dll.txt .\logs.txt 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: The system cannot find the file specified.
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: C:\dotnetbuild\work\074ab7a5-2eef-42da-8843-793c057a4837\Work\141c2691-75ba-443e-99a1-c81258f7bb52\Unzip>type logs.txt 
2017-07-03 19:42:33,437: INFO: proc(54): run_and_log_output: Output: The system cannot find the file specified.
2017-07-03 19:42:33,453: INFO: proc(54): run_and_log_output: Output: Finished running tests.  End time=19:42:33.45, Exit code = 1
2017-07-03 19:42:33,453: INFO: proc(58): run_and_log_output: Exit Code: 1
2017-07-03 19:42:33,467: ERROR: scriptrunner(82): _main: Error: No exception thrown, but XUnit results not created
2017-07-03 19:42:33,467: ERROR: helix_test_execution(83): report_error: Error running xunit None
~~~

**Comment by safern** [comment] 2017-07-05 16:58
@krwq could you take a look please?

**Comment by krwq** [comment] 2017-07-05 20:13
Talked with Santi offline, will check this again since helix seems to be running outerloop

**Comment by safern** [comment] 2017-07-05 20:15
> Talked with Santi offline, will check this again since helix seems to be running outerloop

Thanks @krwq let me know if I can help.

**Comment by krwq** [comment] 2017-07-07 23:06
This is not reproing for me at all since I synced today (running for more than an hour in a loop already). Will leave over the weekend

**Comment by krwq** [comment] 2017-07-10 16:53
This has been running whole weekend in a loop, closing as no repro. Please reopen if you see it in any new log

**Comment by safern** [comment] 2017-07-10 17:20
It just reproed today :(

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170710.02

**Comment by krwq** [comment] 2017-07-10 18:25
I just talked with @joperezr and it seems that this is reproing only on x86 and probably the issue I saw before was unrelated. This seems to be strongly related to resources - this test is frequently changing current culture but for some reason it fails only on x86. @tarekgh could you help investigating this? @joperezr can share the repro

**Comment by tarekgh** [comment] 2017-07-10 18:33
I'll take a look

**Comment by joperezr** [comment] 2017-07-10 19:08
I just logged #22042 which has a bit more info about the failure. Feel free to close that one in favor of this one, but do keep in mind that I have a PR open that has this is the issue that is associated to it.

**Comment by krwq** [comment] 2017-07-10 20:16
Closing this issue as a duplicate of https://github.com/dotnet/corefx/issues/22042 which has a stack trace

**Closed by krwq** 2017-07-10 20:16 UTC
Labels: area-Infrastructure, os-windows-uwp, test-run-uwp-coreclr

**Comment by tarekgh** [comment] 2017-07-10 22:39
just more info as I already submitted PR:

the Windows Runtime failure stack is 

``` 
 # ChildEBP RetAddr  
00 0f40f7e0 0fc67e73 combase!RoOriginateLanguageException [onecore\com\combase\winrt\error\error.cpp @ 1401] 
01 0f40fb18 0fd08768 CoreCLR!SetupErrorInfo+0x280 [e:\a\_work\391\s\src\vm\interoputil.cpp @ 778] 
02 0f40fb88 0f1944a6 CoreCLR!MarshalNative::GetHRForException_WinRT+0x48 [e:\a\_work\391\s\src\vm\marshalnative.cpp @ 920] 
*** WARNING: Unable to verify checksum for F:\OSS\corefx\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlWriterApi.Tests\uap\WinMetadata\Windows.winmd
*** ERROR: Module load completed but symbols could not be loaded for F:\OSS\corefx\bin\Windows_NT.AnyCPU.Debug\System.Xml.RW.XmlWriterApi.Tests\uap\WinMetadata\Windows.winmd
03 0f40fc7c 0fb76094 Windows!DomainBoundILStubClass.IL_STUB_WinRTtoCLR(IntPtr, IntPtr)+0x4e
04 0f40fca0 0fb17e92 CoreCLR!COMToCLRDispatchHelper+0x6b [E:\A\_work\391\s\src\vm\i386\asmhelpers.asm @ 1548] 
05 0f40fcc8 0fb17e29 CoreCLR!InvokeStub+0x39 [e:\a\_work\391\s\src\vm\comtoclrcall.cpp @ 218] 
06 (Inline) -------- CoreCLR!COMToCLRInvokeTarget+0x26 [e:\a\_work\391\s\src\vm\comtoclrcall.cpp @ 425] 
07 (Inline) -------- CoreCLR!COMToCLRWorkerBody+0xa0 [e:\a\_work\391\s\src\vm\comtoclrcall.cpp @ 602] 
08 0f40fd10 00c5d060 CoreCLR!COMToCLRWorker+0xe9 [e:\a\_work\391\s\src\vm\comtoclrcall.cpp @ 853] 
09 0f40fd3c 0f28159b CLRStub[StubLinkStub]@83d0a4500c5d060
0a 0f40fd74 0f2814f1 MrmCoreR!Windows::Internal::Details::GitInvokeHelper<Windows::Foundation::Collections::MapChangedEventHandler<HSTRING__ *,HSTRING__ *>,Windows::Internal::GitPtr,2>::Invoke+0x4b [internal\sdk\inc\winrt\gitevent.h @ 105] 
0b (Inline) -------- MrmCoreR!Microsoft::WRL::EventSource<Windows::Foundation::Collections::MapChangedEventHandler<HSTRING__ *,HSTRING__ *>,Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll::__l2::<lambda_2f59c8e0174f3f0add0e956291eae3f5>::operator()+0x18 [sdk\inc\wrl\event.h @ 977] 
0c 0f40fdb4 0f281a5a MrmCoreR!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<<lambda_2f59c8e0174f3f0add0e956291eae3f5>,Windows::Foundation::Collections::MapChangedEventHandler<HSTRING__ *,HSTRING__ *> >+0x4c [internal\sdk\inc\wrl\internalevent.h @ 119] 
0d 0f40fdd4 0f283271 MrmCoreR!Microsoft::WRL::EventSource<Windows::Foundation::Collections::MapChangedEventHandler<HSTRING__ *,HSTRING__ *>,Microsoft::WRL::InvokeModeOptions<-2> >::DoInvoke<<lambda_2f59c8e0174f3f0add0e956291eae3f5> >+0x46 [sdk\inc\wrl\event.h @ 957] 
0e (Inline) -------- MrmCoreR!Microsoft::WRL::EventSource<Windows::Foundation::Collections::MapChangedEventHandler<HSTRING__ *,HSTRING__ *>,Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll+0xc [sdk\inc\wrl\event.h @ 976] 
0f 0f40fe10 0f283160 MrmCoreR!<lambda_d614cfa549da6f447ddc988b2f36adec>::operator()+0x57 [onecoreuap\base\mrt\runtime\com\winrt\core\lib\winrtresourcecontext.cpp @ 1445] 
10 0f40fe18 0f282354 MrmCoreR!Windows::Internal::ComTaskPool::CTaskWrapper<<lambda_d614cfa549da6f447ddc988b2f36adec> >::Run+0x10 [internal\sdk\inc\winrt\comtaskpool.h @ 416] 
11 0f40fe78 0f281931 MrmCoreR!Windows::Internal::ComTaskPool::CThread::_ThreadProc+0x246 [internal\sdk\inc\winrt\comtaskpool.h @ 1202] 
12 0f40fea0 0f28190d MrmCoreR!Windows::Internal::ComTaskPool::CThread::s_ExecuteThreadProc+0x1a [internal\sdk\inc\winrt\comtaskpool.h @ 997] 
13 0f40fea8 776e8744 MrmCoreR!Windows::Internal::ComTaskPool::CThread::s_ThreadProc+0xd [internal\sdk\inc\winrt\comtaskpool.h @ 1050] 
14 0f40febc 778c587d KERNEL32!BaseThreadInitThunk+0x24 [base\win32\client\thread.c @ 64] 
15 0f40ff04 778c584d ntdll!__RtlUserThreadStart+0x2f [minkernel\ntdll\rtlstrt.c @ 997] 
16 0f40ff14 00000000 ntdll!_RtlUserThreadStart+0x1b [minkernel\ntdll\rtlstrt.c @ 914] 
```

and the parameters we are getting during the failure is:

```
            error = 0x80070057
          message = 0x0bd5efb0 "System.ArgumentException: Value does not fall within the expected range.
   at Windows.ApplicationModel.Resources.Core.ResourceContext.get_Languages()
   at System.Resources.WindowsRuntimeResourceManager.GlobalResourceContextChanged(Object sender, IMapChangedEventArgs`1 e)"
languageException = 0x0e2b440c
```
