### ISSUE TITLE
Introduce Http over arbitrary streams

### ISSUE THREAD

**Issue by simonferquel** [dotnet/corefx#41402] opened 2019-02-14 09:20 UTC
# Summary

This issue is about contributing back support for HTTP over arbitrary streams (named pipe, unix socket, ...) that we use internally for Docker Desktop to .net core libraries.

# Context

I am part of the team building Docker Desktop, and we are in the process of refactoring it to share as much code as possible between Mac and Windows. To align with the company practices, we are using golang for all shared components, and use HTTP over Unix sockets (on Mac) or Named Pipes (on Windows) for IPC. We have extensive experience with Golang for this development model, and so far it has been a success: as an example, Docker Engine API is an HTTP/REST API that can be exposed to clients trough TCP/TLS, Unix sockets, Named pipes (and in the context of Docker Desktop, even trough v-socks or Hyper-V Sockets).

As part of this ongoing Docker Desktop refactoring, I wrote both an HttpClient MessageHandler (for the client side) and a ASP.Net core host (for server side) to support this architecture in C#. You can see an early version of that work here: https://github.com/simonferquel/HttpOverStream/tree/master/src

# What I want to do with it ?

I think support for this kind of architecture directly in the .net Core library would make for a great addition. 
- Users could use it easily for local IPC
- Could also be used for speeding up Unit Tests in large projects (with http clients/server using Http over an in-process Pipe)
- By having access to .net core internal classes, these components will have an improved behavior consistency compared to traditional HTTP/TCP case (if you have a look at https://github.com/simonferquel/HttpOverStream/tree/master/src/HttpOverStream, you'll see much code duplication coming from .net core and CoreFX internal classes, that is not easy to keep in sync with upstream versions).

As an interesting side effect, it would make things easier to build a .net Docker Client library, working with every kind of transport we support.

From the Docker Point of view, it would also be very interesting in term of maintenance costs: every time a bug fix or performance improvement is introduced in internal components shared with the current TCP-focused implementation (mainly the whole HTTP grammar handling), the arbitrary-stream handlers would get it for free (compared to the current model where we have to constantly watch for changes in this part of the code base - which we honestly don't do). Exposure to a broader developer audience and set of use cases would also help us making it more robust (both for us, and other developers).

# Questions to resolve

Where to write PRs:
- I suppose the client side should go there: https://github.com/dotnet/corefx/tree/master/src/System.Net.Http/src/System/Net/Http
- Server side support, I am not completely sure. We could ever make it as a separate server, or make it a new Kestrel feature
- I'd like also to have end-to-end tests, and validate things with cross-language tests: testing client interaction with a golang http server and testing the server with a golang client. Those end-to-end tests could easily be implemented using docker (so we don't require contributors to install a golang toolchain locally), but I have no idea were it could live in the .net core code base.

ping @karelz

**Comment by scalablecory** [comment] 2019-09-27 22:19
This is a bit of a dupe of #35404, so I'm going to close this -- lets continue discussion over there.

**Closed by scalablecory** 2019-09-27 22:19 UTC
Labels: area-System.Net.Http

**Comment by karelz** [comment] 2019-09-30 16:31
@scalablecory unlike the dupe, this issue has clear title explaining easily what is the issue about. Can we change the dupe to have similar thing?
