### ISSUE TITLE
The throw keyword shows the wrong thrown exception line

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/corefx#23470] opened 2017-08-22 14:56 UTC
Using .NETCore2.0, Win10, it seems the `throw` keywor

Using the `throw` keyword loose all the initial stacktrace information. 
You can workaround with `ExceptionDispatchInfo.Capture(ex).Throw();`, but this seems like a bug to me.

```
using System;

namespace ConsoleApp3
{
	class Program
	{
		static void Main(string[] args)
		{
			try
			{
				DoStuff();
			}
			catch(Exception ex)
			{
				Console.WriteLine(ex.StackTrace);
			}
			
		}

		private static void DoStuff()
		{
			try
			{
				throw new Exception("Boom!");
			}
			catch(Exception ex)
			{
				throw;
			}
		}
	}
}
```
Actual output: (Exception line 28)

```
   at ConsoleApp3.Program.DoStuff() in c:\users\nicolasdorier\documents\visual studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 28
   at ConsoleApp3.Program.Main(String[] args) in c:\users\nicolasdorier\documents\visual studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 11
```

Expected output: (Exception line 24)

```
   at ConsoleApp3.Program.DoStuff() in c:\users\nicolasdorier\documents\visual studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 24
   at ConsoleApp3.Program.Main(String[] args) in c:\users\nicolasdorier\documents\visual studio 2017\Projects\ConsoleApp3\ConsoleApp3\Program.cs:line 11
```

Workaround using `ExceptionDispatchInfo.Capture(ex).Throw();`:

```
using System;
using System.Runtime.ExceptionServices;

namespace ConsoleApp3
{
	class Program
	{
		static void Main(string[] args)
		{
			try
			{
				DoStuff();
			}
			catch(Exception ex)
			{
				Console.WriteLine(ex.StackTrace);
			}
			
		}

		private static void DoStuff()
		{
			try
			{
				throw new Exception("Boom!");
			}
			catch(Exception ex)
			{
				ExceptionDispatchInfo.Capture(ex).Throw();
				throw;
			}
		}
	}
}

```

**Comment by Clockwork-Muse** [comment] 2017-08-22 16:01
... this is the behavior of the standard framework, too, though (And I'm on Win7 at the moment).  I'd consider this (mostly) expected behavior.  

It might be better to restate this as a request along the lines of:

> Consider making the re-`throw` shortcut contain the original trace information.

**Comment by danmosemsft** [comment] 2017-08-22 16:08
I see the same behavior in desktop back to 2.0. Which isn't to say ideally it would be improved.

**Comment by danmosemsft** [comment] 2017-08-23 00:10
In fact I remember logging this as a bug many years ago. @jkotas is this (reset of line number of frame in which `throw;` statement is) feasible to ever fix?

**Comment by jkotas** [comment] 2017-08-23 01:16
I do not see a fundamental problem with fixing it in .NET Core. The usual due-diligence with figuring out the breaking potential of the change would apply.

Do you happen to have the bug number that you have filled years ago?

Note that C# let's you write exception filters that solve the problem of catching exception conditionally as well. The filters give you even better diagnostic experience because of the crash dump will have the stacktrace of the original throw site preserved.

```
        try
        {
...
        }
        catch (Exception e) when (....)
        {
...
        }
```

**Comment by NicolasDorier** [comment] 2017-08-23 01:59
Really it is expected behavior? I am coding in .NET since 2007 or something... it turns out I only noticed out now...

```
Note that C# let's you write exception filters that solve the problem of catching exception conditionally as well. The filters give you even better diagnostic experience because of the crash dump will have the stacktrace of the original throw site preserved.
```

You solved another big mystery for me: I had no idea why Exception filter were useful.

**Comment by NicolasDorier** [comment] 2017-08-23 02:01
@jkotas  Ha, you are right, I thought it was specific to .NET Core, but it turns out it does not, it has always been that way.

https://www.thomaslevesque.com/2015/06/21/exception-filters-in-c-6/

**Comment by NicolasDorier** [comment] 2017-08-23 02:01
You may close this issue or keep it open if you think improving it in .NET core in the future.

**Comment by joperezr** [comment] 2017-09-14 22:44
Closing for now given the above discussion. Feel free to reopen if needed.

**Comment by danmosemsft** [comment] 2017-12-06 23:35
I don't think anyone wants the line number on the `throw;`, it is a bug, we would accept a fix for it, I think it is clearest to reopen this. The fix would be in CoreCLR.

**Comment by jkotas** [comment] 2018-01-08 05:12
This issue was moved to dotnet/coreclr#15780

**Closed by jkotas** 2018-01-08 05:12 UTC
Labels: area-System.Diagnostics
