### ISSUE TITLE
Improve code coverage for System.Numerics.Vectors

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#930] opened 2015-02-19 13:55 UTC
According to the current code coverage report, this library is only at 72%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by mellinoe** [comment] 2015-02-19 18:39
For what it's worth, I looked at the numbers for this library when we first start Code Coverage, and saw that a lot of the missed coverage was due to the unique structure of the code. In Vector<T>, for example, there are two code paths for almost every method, one which assumes hardware acceleration, and one which does not. Other types have similar duplication, but it's most evident in Vector<T>. Unless we do two runs, one of which is properly configured to use RyuJit, with the proper environment variables set, etc. then we will probably only see about 50% coverage on that class. When I looked, the coverage was about 52% for Vector<T>, which makes sense given the above. I think that number is probably driving the overall number down quite a bit, because it is an extremely large file.

That said, we should still look and see if there are any particular areas that have been neglected.

**Comment by joshfree** [comment] 2015-02-19 18:43
It would make sense to execute the tests in both scenarios (RyuJIT SIMD registers, and naïve software implementation) that it's an early canary for RyuJIT regressions.  What would the test infra changes entail?

**Comment by mellinoe** [comment] 2015-02-19 19:24
For this case, we'd probably need the ability to set some sort of configuration (environment variables, etc) for the execution of a test run, and then test System.Numerics.Vectors using two different configurations. I don't know how the code coverage tool is working now to be more specific than that, but that's the gist of it.

**Comment by mellinoe** [comment] 2015-02-19 23:04
Actually, this is further complicated by the fact that, in order for SIMD intrinsics to activate, we need to run in a 64-bit process, which doesn't seem to be the case right now. Tests are running 32-bit it seems.

Also, when we do allow 64-bit test process, we'll need to make sure that a good version of RyuJit is being used. This part probably isn't a problem, RyuJit is the standard 64-bit JIT now.

**Comment by joshfree** [comment] 2015-02-19 23:08
do we still have the ee compat mode quirk for simd? if so this sounds pretty straightforward.  compile and run the assembly in 64bit mode; then run it again with the compat quirks flag.

**Comment by mellinoe** [comment] 2015-02-19 23:13
Yes, essentially we just need to run with COMPLUS_Altjit set to * for one run, and then set to nothing for another. This is assuming we can get the test running in a 64-bit process.

**Comment by mellinoe** [comment] 2016-09-26 20:35
This is still something we can consider, but it will probably require setting up some build/CI configurations especially for this, which would be a lot of effort for just a little benefit.

**Comment by mellinoe** [comment] 2016-11-17 23:48
I'm going to close this because I don't think it's worth adding extra test configurations just to get this coverage.

**Closed by mellinoe** 2016-11-17 23:48 UTC
Labels: area-System.Numerics, test enhancement, up for grabs

**Comment by AndyAyersMS** [comment] 2016-11-18 01:07
The lab HW seems to run on AVX2 capable boxes these days, so that's what gets tested by default.

Note we also have SSE2 specific vector codegen bugs at times, eg dotnet/coreclr#7977. This won't show up as a coverage issue in corefx.

So really there are 3 configurations to test: no SIMD, SSE2, and AVX2. We should do some of this sort of testing over in coreclr where we are already set up to run the jit in various creative ways.

@RussKeldorph any thoughts? Can we already do stress mode testing, etc vs corefx?

**Comment by RussKeldorph** [comment] 2016-11-18 10:43
@AndyAyersMS This would be easy to set up on VMs and would acceptably cover the three scenarios as long as a high enough fraction of VMs are AVX2-capable.  Pinning to run on the few real (AVX2) boxes we have would be a bit more work but entirely doable.

@mellinoe Note that we intend to bring SIMD to to 32-bit as well with RyuJIT/x86.
