### ISSUE TITLE
UAP test app not registering on ARM machines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#30399] opened 2018-06-14 17:59 UTC
Almost all our UAP tests on ARM have been failing to start.

eg https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180614.04/workItem/System.Threading.AccessControl.Tests/wilogs

```
2018-06-14 05:38:31,273: INFO: proc(54): run_and_log_output: Output: Installing the application...
2018-06-14 05:38:32,930: INFO: proc(54): run_and_log_output: Output: 
2018-06-14 05:38:32,930: INFO: proc(54): run_and_log_output: Output: FAILED 0x80073CF6 (Package could not be registered.
```

@dotnet/dnceng could you please help me access the Application event log for one of these machines?  That can sometimes have more explanation (eg https://github.com/dotnet/corefx/pull/25208#issuecomment-344320603)

In [this comment](https://github.com/dotnet/corefx/pull/25208#issuecomment-344300108), @dagood fixed such an error code by adding a file `Splashscreen.png` . If I look in the appxmanifest for our test app (you will see it in a path like `C:\git\buildtools\src\xunit.runner.uap\bin\ARM\Debug\Core\AppxManifest.xml` on your machine)  it specifies `        <uap:SplashScreen Image="Assets\SplashScreen.png" />`. However in `buildtools\src\xunit.runner.uap\UpdateScript\buildAndUpdateRunner.bat` we do not copy such a file. I'm guessing that Windows chooses `SplashScreen.scale-200.png` instead and in @dagood 's case it was simply that that was missing too. Also if that was not the case, the app would never work at all, and it does occasionally work. @joperezr any thoughts.

**Comment by joperezr** [comment] 2018-06-14 22:18
mmm not sure what might be going on without debugging further. @dagood how is it that you figured out last time what was missing? Did looking on the Event Log help you at all?

**Comment by dagood** [comment] 2018-06-14 22:31
For the splash screen image being missing, I only got a lucky search result for `Package could not be registered`. I don't remember seeing anything in the event log that was useful to me. (But note that in that issue we gave up on the UWP runner, so I didn't go very deep.) Grabbing the event(s) for the problem happening now might at least show if it's a different issue.

**Comment by dseefeld** [comment] 2018-06-15 19:46
@danmosemsft I took a peek at one of the ARM machines and saw it stopped on this dialog:

![image](https://user-images.githubusercontent.com/6424755/41486573-a9c01404-70aa-11e8-8cf9-caf6e22372ca.png)

**Comment by danmosemsft** [comment] 2018-06-15 20:14
@dseefeld thanks .. this was one of the UAP runs (hitting 0x80073CF6 ), not one of the UAPAOT runs (hitting failures on all architectures - https://github.com/dotnet/corefx/issues/30423) ?

@ViktorHofer how does libc.dll (Windows version of glibc I think) get involved? I thought xunit was 100% managed.

**Comment by danmosemsft** [comment] 2018-06-15 20:41
@tommcdon if you're looking at #30423 is this something you could look at also?

**Comment by danmosemsft** [comment] 2018-06-15 20:41
I can give pointers if needed!

**Comment by MattGal** [comment] 2018-06-15 20:44
> @ViktorHofer Viktor Hofer FTE how does libc.dll (Windows version of glibc I think) get involved? I thought xunit was 100% managed.

It's normally quite managed; in this case it's actually the native executable generated for UAPAOT testing.  I have no idea how it's supposed to get included or who added it,  will check the last time the tests passed in the DB and leave the rest to y'all.

**Comment by ViktorHofer** [comment] 2018-06-15 20:53
Just FYI I will shortly replace the uap Gui App runner with a UWP console app runner where we will never face any splash screen errors again.

**Comment by joperezr** [comment] 2018-06-15 21:00
@dseefeld I see now, that is good. @dagood it is possible that even though we compile an external call to libc, it might be that this code is designed so that it never gets called on Windows, but because of how uapaot works we can't load assemblies during execution so at app startup we would try to load all dependencies (which include libc.dll) and hit this error. The way to fix it is to ifdef the code (Or refactor it) such that the Windows implementation doesn't compile the PInvoke.

**Comment by morganbr** [comment] 2018-06-20 02:38
@luqunl, can you please look into why the libc P/Invoke isn't getting turned into a throw?

**Comment by danmosemsft** [comment] 2018-07-02 23:50
@luqun do you expect to have time to look at this soon? It's relatively high priority as it means the tests are all broken.

**Comment by luqunl** [comment] 2018-07-03 00:09
Let me check with Tom first to avoid duplicate, since The issue is assigned to Tom. 
@tommcdon, are you working on this issue?

cc: @jeffschwMSFT

**Comment by tommcdon** [comment] 2018-07-03 16:29
@chsienki and I were working offline to look at the issue, though we didn't get far.  Since the issue looks interop related, it likely does make more sense for Luqun to take a quick look.

**Comment by luqunl** [comment] 2018-07-03 16:43
> @luqunl, can you please look into why the libc P/Invoke isn't getting turned into a throw?
@morganbr, This is UAP test instead of UAP AOT test.  Mcg isn't used for UAP test..

**Comment by luqunl** [comment] 2018-07-03 16:47
repro-tool currently does not support jobs from the Windows.10.Arm64 queue.
Is there an easy way to repro this?

**Comment by MattGal** [comment] 2018-07-03 17:00
Yes you don't need to be on ARM at all, the libc problem is on AMD64 as well. Just run the test bits locally.

**Comment by luqunl** [comment] 2018-07-03 19:56
@MattGal , I try to build and run the testcase(System.Threading.AccessControl) on my local box and it always run as console.  Do you know how to run it using appx?

>  D:\git\corefx\bin/tests/System.Threading.AccessControl.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd D:\git\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/
  Using D:\git\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\ as the test runtime folder.
  Executing in D:\git\corefx\bin\tests\System.Threading.AccessControl.Tests\netcoreapp-Windows_NT-Debug-x64\
  ----- start 11:48:43.79 ===============  To repro directly: =====================================================
  pushd D:\git\corefx\bin\tests\System.Threading.AccessControl.Tests\netcoreapp-Windows_NT-Debug-x64\
  call D:\git\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\\dotnet.exe xunit.console.netcore.exe System.Threading.AccessControl.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing
  popd

**Comment by MattGal** [comment] 2018-07-03 20:19
I tend to just fetch the prebuilt bits but the relevant bits that make it run this way from the official build fed to build-tests are: -framework=uap /p:RuntimeOS=win10 

This may also require the Optional Tools Source stuff get set as well.  I can help ab it later in the afternoon if needed.

**Comment by luqunl** [comment] 2018-07-03 22:49
These UAP testcases pass on my local machine(Win10 x64).

**Comment by MattGal** [comment] 2018-07-03 23:43
yes, it looks to be fixed there as well (WIndows has been broken for some time and just had a green test build today: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20180703.09 ) with the exception of the ARM run.

**Comment by MattGal** [comment] 2018-07-04 00:47
I agree.  We've only got 6 machines and they hang regularly, but if you're available some time on Thursday we can set something up.  (right now every machine is needed for official runs)

**Comment by ViktorHofer** [comment] 2018-08-12 17:03
@MattGal I can also confirm that this now works locally on AMD64. I would like to see if this still happens on ARM with my recent xunit 2.4 changes. Is a machine available which I can connect to and build buildtools + corefx?

**Comment by MattGal** [comment] 2018-08-20 15:37
Just back from vacation, see me if you still need access to a machine.  We don't have enough to just share them around, but I can work with you and figure something out if needed.

**Comment by cshung** [comment] 2018-08-22 23:49
Can we test if these pull requests fixes the problem?
https://github.com/dotnet/buildtools/pull/2134
https://github.com/dotnet/corefx/pull/31892

**Comment by cshung** [comment] 2018-08-23 18:41
The dotnet/buildtools#2134 maybe replaced by the PR below
https://github.com/dotnet/corefx/pull/31919

**Comment by cshung** [comment] 2018-08-24 04:27
https://github.com/dotnet/corefx/pull/31919 is merged, fingers crossed.

**Comment by ViktorHofer** [comment] 2018-09-25 21:35
Runs are still not working but the reason is something different:

```
2018-09-25 05:23:03,088: INFO: proc(55): run_and_log_output: Output: C:\dotnetbuild\work\52129c76-bc43-4147-b2f6-bc3281f0be0e\Work\014696a9-e96d-4e02-8388-e716a7d77010\Unzip>call C:\dotnetbuild\work\52129c76-bc43-4147-b2f6-bc3281f0be0e\Payload\Launcher\WindowsStoreAppLauncher.exe -install appxmanifest.xml CoreFx.Private.TestUtilities.Tests.dll  -xml testResults.xml -notrait category=nonuaptests -notrait category=nonwindowstests  -notrait category=failing 
2018-09-25 05:23:03,198: INFO: proc(55): run_and_log_output: Output: Got manifest file appxmanifest.xml
2018-09-25 05:23:03,309: INFO: proc(55): run_and_log_output: Output: Removing any previous installation...
2018-09-25 05:23:03,309: INFO: proc(55): run_and_log_output: Output: Installing the application...
2018-09-25 05:23:03,529: INFO: proc(55): run_and_log_output: Output: 
2018-09-25 05:23:03,529: INFO: proc(55): run_and_log_output: Output: FAILED 0x80073D10 (The deployment operation failed because the package targets the wrong processor architecture.
2018-09-25 05:23:03,529: INFO: proc(55): run_and_log_output: Output: )
```

The appx doesn't install successfully because the package either seems to contain wrong assemblies or the target OS is not recent enough.

@MattGal which Win 10 version is installed on the arm machines? The label doesn't tell.

**Comment by MattGal** [comment] 2018-09-25 21:51
Currently it's RS4 RTM ARM64, specifically _17133.rs4_release.180323-1312_ .  I don't think a non-time-bombed RS5 is RTM yet, what do you expect to find?

I'd definitely want to review the manifest and assemblies of this appx for myself too... if an Amd64-specific assembly came along, this is exactly the sort of error I'd expect.

**Comment by ViktorHofer** [comment] 2018-09-25 21:59
> Currently it's RS4 RTM ARM64, specifically 17133.rs4_release.180323-1312 . I don't think a non-time-bombed RS5 is RTM yet, what do you expect to find?

Ok great, I wasn't sure if it isn't using an older version.

> I'd definitely want to review the manifest and assemblies of this appx for myself too... if an Amd64-specific assembly came along, this is exactly the sort of error I'd expect.

I built the runner package for the following ArchGroups: x86, x64 and arm. Shouldn't the arm64 machine just work well with arm(32) package? I thought there is some kind of emulation happening.

**Comment by ViktorHofer** [comment] 2018-09-25 22:29
> Is it possible to get some details to look at this app?

Sure. The runner that fails to be installed lives here: https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.XUnitRunnerUap. The manifest should be fine as it doesn't contain any ArchGroup specifics.

I believe that we need to add configurations for ARM64 to both the launcher and runner and compile it with the ARM64 SDK (if it's already released) as we need the runner to be a true ARM64 non emulated app. I can look at it later.

**Comment by MattGal** [comment] 2018-09-25 22:36
I was looking for a built copy and/or any details of the Helix jobs being sent.  Anyways, you may be correct but I would point out that ARM32 coreclr runs did work in the past.

**Comment by ViktorHofer** [comment] 2018-09-25 22:40
I believe the ARM32 ones should work, this is about the ARM64 ones, right? Are we going to add an official ARM32 leg in the future or for now live with the ARM64 leg?

**Comment by MattGal** [comment] 2018-09-25 23:07
That's up to your team, I'm just saying that as ARM64 machines with Cobalt support I'd expect properly authored content to work as expected for x86, ARM, and ARM64 content.

**Comment by ViktorHofer** [comment] 2018-09-26 15:04
I think I found the reason for the failures. The WindowsStoreAppLauncher which registers and unregisters the UWP app was always compiled with x64 which isn't supported on ARM machines. I updated the Launcher and Runner to correctly support ARM and ARM64: https://github.com/dotnet/arcade/pull/874

**Comment by ViktorHofer** [comment] 2018-12-13 16:51
@MattGal I made some follow-up changes and now both the launcher and the runner are compiled correctly for ARM. Unfortunately that still didn't solve the registration issue. I think I'm out of luck here without access to a repro machine...

**Comment by MattGal** [comment] 2018-12-13 18:31
I am skeptical that you can connect to the intranet KVMs we use from outside corpnet, I'll chat with @ilyas1974 when I get a chance.  I'm always happy to try things out  on a machine.

**Comment by ViktorHofer** [comment] 2019-01-05 13:20
@danmosemsft We need a Windows on ARM machine (there are some notebook on the market with it) to fix this. Unfortunately I don't have one. It would surprise me if nobody in our ORG has one.

**Comment by safern** [comment] 2019-01-07 17:30
> @safern can we get the official builds back for UAP? The x86, x64 runs were working fine and I would also want the ARM runs back to see if they are still failing.

The UAP runs have been running ever since we moved to the new official builds for all of those architectures. 
https://dnceng.visualstudio.com/internal/_build/results?buildId=67384&view=logs

x86 and x64 are clean with no failures, however the ARM runs are failing with: 
```
C:\dotnetbuild\work\32e81b30-c31a-4c80-9b80-bfe1aef40707\Work\6d610423-0801-42b2-ac8c-7ef8008c19a1\Exec>call "C:\dotnetbuild\work\32e81b30-c31a-4c80-9b80-bfe1aef40707\Payload\Launcher\WindowsStoreAppLauncher.exe" -install appxmanifest.xml Microsoft.VisualBasic.Tests.dll 
Got manifest file appxmanifest.xml
Removing any previous installation...
Installing the application...

FAILED 0x80073D10 (The deployment operation failed because the package targets the wrong processor architecture.

)

C:\dotnetbuild\work\32e81b30-c31a-4c80-9b80-bfe1aef40707\Work\6d610423-0801-42b2-ac8c-7ef8008c19a1\Exec>echo.


C:\dotnetbuild\work\32e81b30-c31a-4c80-9b80-bfe1aef40707\Work\6d610423-0801-42b2-ac8c-7ef8008c19a1\Exec>XUnitRunnerUap Microsoft.VisualBasic.Tests.dll -xml testResults.xml -nologo -notrait category=nonuaptests -notrait category=nonwindowstests -notrait category=failing 
'XUnitRunnerUap' is not recognized as an internal or external command,
operable program or batch file.
```

Also I noticed that in helix the test runs are marked as passed even though they failed, I think we're not returning the right exit code at the end of the script when the app fails to register.
https://mc.dot.net/#/user/dotnet-mc-bot-2/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster~2F/test~2Ffunctional~2Fuwp~2Fcli~2F/20190107.1/workItem/Microsoft.VisualBasic.Tests/wilogs

**Comment by ViktorHofer** [comment] 2019-01-22 19:45
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Uap.TestTools/AppxManifest.xml#L10 🤦‍♂️ (ProcessArchitecture=x64). Will try out if that resolves the register issues.

**Comment by ViktorHofer** [comment] 2019-01-24 15:10
This is now fixed with https://github.com/dotnet/corefx/pull/34678

**Closed by ViktorHofer** 2019-01-24 15:10 UTC
Labels: area-Infrastructure, os-windows-uwp, test-run-uwp-coreclr
