### ISSUE TITLE
Environment.ProcessorCount is -1

### ISSUE THREAD

**Issue by Daniel15** [dotnet/corefx#24794] opened 2017-10-22 07:18 UTC
On my Linux system (a VPS running Debian, using the [KVM](https://www.linux-kvm.org/page/Main_Page) virtualization platform), `Environment.ProcessorCount` is returning `-1`. However, the native syscall works fine:

```csharp
using System;
using System.Runtime.InteropServices;

namespace ConcurrentBug
{
    class Program
    {
	    private const int _SC_NPROCESSORS_ONLN = 84;
		[DllImport("libc")]
	    private static extern long sysconf(int name);

		static void Main(string[] args)
        {
            Console.WriteLine($"Processor Count (Managed): {Environment.ProcessorCount}");
	        Console.WriteLine($"Processor Count (Native): {sysconf(_SC_NPROCESSORS_ONLN)}");
		}
    }
}

```
```
0:25 daniel@vps03 /tmp/ConcurrentBug
% /usr/bin/dotnet ConcurrentBug.dll
Processor Count (Managed): -1
Processor Count (Native): 1
```

This breaks the default constructor for `ConcurrentDictionary` - **All** ASP.NET Core sites on this server fail with:
```
Unhandled Exception: System.ArgumentOutOfRangeException: The concurrencyLevel argument must be positive.
Parameter name: concurrencyLevel
   at System.Collections.Concurrent.ConcurrentDictionary`2..ctor(Int32 concurrencyLevel, Int32 capacity, Boolean growLockArray, IEqualityComparer`1 comparer)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher..ctor(String root, FileSystemWatcher fileSystemWatcher, Boolean pollForChanges)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Example.Web.Program.BuildWebHost(String[] args) in C:\src\Example\src\Example.Web\Program.cs:line 21
   at Example.Web.Program.Main(String[] args) in C:\src\Example\src\Example.Web\Program.cs:line 17
```

## Environment
```
0:16 daniel@vps03 /tmp/ConcurrentBug
% /usr/bin/dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

0:17 daniel@vps03 /tmp/ConcurrentBug
% cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1
cpu MHz         : 3500.014
cache size      : 8192 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs            :
bogomips        : 7000.02
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

**Comment by Daniel15** [comment] 2017-10-22 07:40
So after a lot of digging, I worked out that this was happening because I had .NET Core 1.1's `System.Native.so` in `/usr/local/lib`. Even though I also had `System.Native.so` in my test app's directory, the one in `/usr/local/lib` seems to override it.

Can you please use a version number in the file name of `System.Native.so` (eg. `System.Native.2.0.0.so`) to avoid conflicts like this?

**Comment by stephentoub** [comment] 2017-10-22 11:15
Related to #24663, https://github.com/dotnet/corefx/pull/24771
cc: @danmosemsft, @janvorli

**Comment by karelz** [comment] 2017-10-28 18:50
#24663 loos like direct dupe, should we close it as such? Or we tracking different kind of problems?

**Comment by stephentoub** [comment] 2017-10-29 22:58
> should we close it as such? 

@karelz, that depends on how you want to respond to the question "Can you please use a version number in the file name of System.Native.so (eg. System.Native.2.0.0.so) to avoid conflicts like this?"

**Comment by karelz** [comment] 2017-10-30 16:12
That is more a solution discussion than problem description - we can have that discussion easily on the main issue.
Closing as duplicate of #24663.

**Closed by karelz** 2017-10-30 16:12 UTC
Labels: area-System.Runtime.Extensions, bug
