### ISSUE TITLE
SocketException in SmtpClient takes down process

### ISSUE THREAD

**Issue by ajryan** [dotnet/corefx#25234] opened 2017-11-14 05:33 UTC
With the following code, the resulting ExtendedSocketException is not caught and the process crashes:

    static void Main(string[] args)
    {
        try
        {
            using (var smtpClient = new SmtpClient())
            {
                smtpClient.Host = "bogusdomainnotreal.com";
                smtpClient.Port = 587;
                smtpClient.EnableSsl = true;
                smtpClient.Timeout = 5;

                smtpClient.SendMailAsync("me@me.com", "test@test.com", "subj", "body").Wait();
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

**Comment by davidsh** [comment] 2017-11-14 05:43
Is this on Windows or Linux?

**Comment by ajryan** [comment] 2017-11-14 05:48
Windows

**Comment by stephentoub** [comment] 2017-11-14 14:34
I'm not able to repro this.  What version of Windows?  What version of .NET Core?  When I run this the exception is thrown and caught on the main thread.

**Comment by ajryan** [comment] 2017-11-14 15:18
Just tried at work, on 2.1.1-preview-007118 as well as 2.0.2, Windows 7 x64, and it hangs, doesn't crash. I'm behind a proxy at work so it could behave differently.

At home I'm on Windows 10. Need to double-check the framework version bit I think it's 2.0.2.

Thanks for looking at this.

**Comment by ajryan** [comment] 2017-11-15 02:30
Just ran at home again - confirmed this is on .NET Core 2.0.2, Windows 10 Fall Creators Update.
Definitely not catching the exception on the main thread.

Here's the stack trace:

```
Unhandled Exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.239.207.44:587
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.LazyAsyncResult.InvokeCallback(Object result)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError socketError)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
Press any key to continue . . .
```

**Comment by davidsh** [comment] 2017-11-15 02:48
Please post your small repro of the problem as a full Visual Studio solution etc.  You can ZIP it and post it here.  It's important to see exactly how your project is set up etc.  This will make it easier to diagnose the problem.  Thx.

**Comment by ajryan** [comment] 2017-11-15 04:01
Attached.
[smtp.zip](https://github.com/dotnet/corefx/files/1473378/smtp.zip)

**Comment by davidsh** [comment] 2017-11-15 18:42
Thanks for posting this.

I was able to reproduce a problem.  It seems that on .NET Framework, this code correctly throws an exception that surfaces to the top-level and is caught by this code:

>System.Net.Mail.SmtpException: The SMTP host was not found. ---> System.Net.WebException: The remote name could not be resolved: 'bogusdomainnotreal.com'

But on .NET Core, the exceptions are still happening, but they are not been propagated correctly.  In fact, this code hangs forever (due to the .Wait()).  It appears that the Task is never notified of the exceptions occurring and stays in the 'Running' state.

cc: @Priya91 @stephentoub

**Comment by davidsh** [comment] 2017-11-15 18:43
This is not just a Windows issue.  The SmtpClient code is common across all platforms for .NET Core.

**Comment by ajryan** [comment] 2017-11-15 22:46
Is this the fix already? https://github.com/dotnet/corefx/pull/24536

**Comment by davidsh** [comment] 2017-11-15 22:51
Yes, looks like this issue was fixed with PR #24536.

**Closed by davidsh** 2017-11-15 22:51 UTC
Labels: area-System.Net, bug

**Comment by stephentoub** [comment] 2017-11-16 03:00
#24536 fixes a hang, but that's not what you're seeing.  I can't repro the behavior you're seeing, and it sounds like @davidsh couldn't either, so I don't know if #24536 actually addresses it or not.

**Comment by ajryan** [comment] 2017-11-16 04:07
The same code hangs on my Win 7 machine and hard crashes on Win 10. Makes me think it may be different symptoms of the same underlying issue.

Have you tried the repro on .NET Core 2.0.2 on Win 10?
