### ISSUE TITLE
Open .dll in new console window on Linux .Net Core

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28182] opened 2018-03-18 16:54 UTC
@maroallegro commented on [Tue Dec 19 2017](https://github.com/dotnet/core/issues/1177)

I am able to run program.dll in same console window by running:

    var process = new Process
    {

        StartInfo = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = "program.dll",
            UseShellExecute = true,
            RedirectStandardOutput = false,
            RedirectStandardError = false,
            CreateNoWindow = false
        }
    };

    process.Start();

How to open program.dll in new console window on Linux using .NET Core 2.0?

Flag `CreateNoWindow = false` do not open new console as on Windows system.

Is it a bug?

**Comment by karelz** [comment] 2018-03-18 18:17
Duplicate of #26337

**Closed by karelz** 2018-03-18 18:17 UTC
Labels: area-System.Diagnostics.Process, os-linux, question
