### ISSUE TITLE
System.IO.FileSystem: Unix SetCurrentDirectory follows symlinks

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#7358] opened 2016-03-30 18:29 UTC
Using ```Directory.SetCurrentDirectory``` on a symlink in Unix follows the symlink and sets the directory to what the symlink links to. This differs from the Windows behavior as well as the behavior one would see on the command line using similar utilities.

Unit test:
```
[ConditionalFact(nameof(CanCreateSymbolicLinks))]
public void SetToPathContainingSymLink()
{
    var path = GetTestFilePath();
    var linkPath = GetTestFilePath();

    Directory.CreateDirectory(path);
    Assert.True(MountHelper.CreateSymbolicLink(linkPath, path, isDirectory: true));

    // Both the symlink and the target exist
    Assert.True(Directory.Exists(path), "path should exist");
    Assert.True(Directory.Exists(linkPath), "linkPath should exist");

    // Set Current Directory to symlink
    string currentDir = Directory.GetCurrentDirectory();
    try
    {
        Console.WriteLine("LINKPATH : " + linkPath);
        Console.WriteLine("PATH : " + path);

        Directory.SetCurrentDirectory(linkPath);
        Assert.Equal(path, Directory.GetCurrentDirectory());
    }
    finally
    {
        Directory.SetCurrentDirectory(currentDir);
    }
    Assert.Equal(currentDir, Directory.GetCurrentDirectory());
}
```

On Windows the current directory is set to LinkPath; on Unix it is path.

Ubuntu command line behavior using ```cd``` and ```pwd```:
```
mkdir cat
touch cat/fluffy
sudo ln -s cat fat
cd fat
pwd
```
prints ```/home/ianha/test/fat```. 

Ubuntu c program behavior using ```getcwd``` and ```chdir``` (what we interop to in System.IO.FileSystem) follows the link as expected:
```
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

int main(char args[])
{
        char* currentPath = malloc(300);
        char linkPath[] = "fat";
        chdir(linkPath);
        getcwd(currentPath, 299);
        printf("%s\n", currentPath);
        free(currentPath);
}

```

Though the current behavior aligns with the c behavior on Unix, it is different from Windows so I decided to open this issue for Future visibility.

@stephentoub

**Comment by stephentoub** [comment] 2016-03-31 13:54
As you highlight, this is by design.  We should ensure this is codified in tests and close the issue.

**Comment by ianhays** [comment] 2016-03-31 17:26
I've got a PR ready to submit after merging #7308 that will add tests for this.

**Closed** 2016-04-06 03:09 UTC
Labels: 2 - In Progress, System.IO
