### ISSUE TITLE
Add Enumerable.Repeat overlode

### ISSUE THREAD

**Issue by aobatact** [dotnet/corefx#26112] opened 2018-01-02 05:36 UTC
Currently Enumerable.Repeat<T> method create an IEnumerable<T> which values are same instance but sometimes I want an IEnumerable<T> with same value but different instance.

``` csharp
public static partial class Enumerable
{
    public static IEnumerable<TResult> Repeat<TResult>(Func<TResult> factory, int count);
}
```
And for Array.Fill too.
``` csharp
public abstract class Array
{
    public static void Fill<T>(T[] array, Func<T> factory);
    public static void Fill<T>(T[] array, Func<T> factory, int startIndex, int count);
}
```

**Comment by gfoidl** [comment] 2018-01-02 12:04
Is this then still the meaning of __Repeat__? In a sense of "repeat the (exactely) same value count times". I mean no. 

In your proposal the factory should also take the current index into account -> `Func<int, TResult> factory`. How would you else create instances of different types (i.e. based on what decision)?

So _Repeat_ sounds like a wrong name for the method. It's just a factory for creating a "custom" enumerable, so I would name it depending on the concrete use case, hence wouldn't add it to the Enumerable-API.

Anyway you can code this quite simple, especially when you just need this _sometimes_ :wink:

  ```c#
  public static IEnumerable<TResult> Repeat<TResult>(Func<int, TResult> factory, int count)
  {
      if (factory == null) throw new ArgumentNullException(nameof(factory));
      if (count < 0) throw new ArgumentOutOfRangeException(nameof(count));

      return Impl();

      IEnumerable<TResult> Impl()
      {
          for (int i = 0; i < count; ++i)
              yield return factory(i);
      }
  }
  ```
  or just delegate to `Enumerable.Repeat` and a `Select`.

**Comment by aobatact** [comment] 2018-01-02 12:51
What I wanted to have is like
``` csharp
Enumerable.Repeat(()=>new A());
```
I know there is a way like `Enumerable.Range(0,count).Selcet(x=>new A()); ` but I thought it would be useful and faster to have a direct way.

**Comment by JonHanna** [comment] 2018-01-02 14:12
The `Enumerable` part of this is a duplicate of #13909

**Comment by karelz** [comment] 2018-01-02 17:06
Let's first make the Linq extension, then we can consider the Array methods.
Duplicate of #13909.

**Closed by karelz** 2018-01-02 17:06 UTC
