### ISSUE TITLE
HttpClient performance issue compare to the full framework

### ISSUE THREAD

**Issue by caserzer** [dotnet/corefx#11392] opened 2016-09-03 03:11 UTC
I'm trying to wrapper a backend REST API to Frontend. The backend API RPS can archive about 50K  (using AB), I use the HttpClient to invoke the API , get the result and return to then client.
I can only get 1k RPS. (AB is on the same frontend machine )
Code is very simple

```
 [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        private static HttpClient client;// = new HttpClient();

        static ValuesController()
        {

        client = new HttpClient(new HttpClientHandler { UseProxy = false, UseCookies= false, UseDefaultCredentials=false  });
        client.DefaultRequestHeaders.Add("Connection", "Keep-Alive");
        client.BaseAddress = new Uri("http://backendserver/");
        }

        [HttpGet]
        public async Task<string> Wrapper()
        {


            var response =  await client.GetAsync("API");
            var result =  await response.Content.ReadAsStringAsync();
            response.Dispose();

            return result;
        }


        [HttpGet]
        public string Baseline()
        {
            return "value";
        }

```

| Test | RPS Result |
| --- | --- |
| Direct to Backend API | 50K |
| Baseline (.net core) | 5K |
| Baseline (.net full framework) | 5K |
| Wrapper (.net core ) | 1K |
| Wrapper (.net full framework) | 2.3K |

**Comment by davidsh** [comment] 2016-09-03 03:36
We are aware of performance differences between .NET Framework and .NET Core.

See #8809 for example.

**Comment by davidsh** [comment] 2016-09-17 03:54
cc: @CIPop

**Comment by CIPop** [comment] 2016-09-19 17:24
@caserzer In order to further isolate the issue, would it be simple for you to set up a Console application to perform the HttpClient requests instead of an ASP.Net app (for the .Net Core case)?

**Comment by CIPop** [comment] 2016-09-30 01:11
At least part of the perf issues could be caused by #12217.

**Comment by CIPop** [comment] 2016-12-08 23:03
@caserzer One more thing to consider: do you have console-logging active for your ASP.Net application? 

Closing for now: please reopen pointing us to the code used for the comparative test case including the three modes you've tested:

* Direct
* Baseline (.Net Framework / Core)
* Wrapper (.Net Framework / Core)

**Closed by CIPop** 2016-12-08 23:03 UTC
Labels: area-System.Net, tenet-performance
