### ISSUE TITLE
Sockets test failures SendToAsyncV4IPEndPointToV6Host_NotReceived & BeginSendToV4IPEndPointToV6Host_NotReceived

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9017] opened 2016-06-01 02:02 UTC
```
Test Result (2 failures / +2)
```

System.Net.Sockets.Tests.DualMode.SendToAsyncV4IPEndPointToV6Host_NotReceived
System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToV6Host_NotReceived
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/osx_debug_prtest/58/testReport/

Regression

System.Net.Sockets.Tests.DualMode.SendToAsyncV4IPEndPointToV6Host_NotReceived (from (empty))

Failing for the past 1 build (Since Failed#58 )
Took 0.31 sec.
Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(Xunit.Sdk.EqualException): Assert.Equal() Failure\nExpected: 1\nActual: 0
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.DualMode.DualModeSendToAsync_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1359 at System.Net.Sockets.Tests.DualMode.<SendToAsyncV4IPEndPointToV6Host_NotReceived>b__119_0() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1311

Regression

System.Net.Sockets.Tests.DualMode.BeginSendToV4IPEndPointToV6Host_NotReceived (from (empty))

Failing for the past 1 build (Since Failed#58 )
Took 7 ms.
Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(System.Net.Sockets.SocketException): Connection refused
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3004 at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2942 at System.Net.Sockets.SocketTaskExtensions.<>c.<SendToAsync>b__12_0(ArraySegment`1 targetBuffer, SocketFlags flags, EndPoint endPoint, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs:line 235 at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) at System.Net.Sockets.SocketTaskExtensions.SendToAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, EndPoint remoteEndPoint) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs:line 234 at System.Net.Sockets.SocketAPMExtensions.BeginSendTo(Socket socket, Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs:line 565 at System.Net.Sockets.Tests.DualMode.DualModeBeginSendTo_EndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1234 at System.Net.Sockets.Tests.DualMode.<BeginSendToV4IPEndPointToV6Host_NotReceived>b__110_0() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_1.0.0/osx_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1200

**Comment by ellismg** [comment] 2016-06-01 02:05
Dupe of #8636?

**Comment by ericeil** [comment] 2016-06-01 02:30
Should be fixed with #9002.

**Comment by steveharter** [comment] 2017-02-18 01:30
To prevent creating another issue, opening this one again.

We have another failure:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release/1132/

```
System.Net.Sockets.Tests.DualModeConnectionlessSendToAsync.SendToAsyncV4IPEndPointToV6Host_NotReceived (from (empty)) 
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: (No exception was thrown)
```

We connect to a V4 port and then listen on V6 of the same port (or vice-versa in SendToAsyncV6IPEndPointToV4Host_NotReceived) . However, I don't believe there is any guarantee that the V6 listening port isn't already being used by someone else since we didn't actually request that port (as V4 vs V6 have a different address). 

We encountered similar issue with Unix UDP and resolved it by a re-try (which so far has not resulted in additional failures) - https://github.com/dotnet/corefx/pull/15887. 

So if we send to someone else's port then that other test will fail (assuming it is a test on the other side), like what happens to this test as someone else apparently sent to this port (probably the mirror test SendToAsyncV6IPEndPointToV4Host_NotReceived).

The fix here can not the same as https://github.com/dotnet/corefx/pull/15887 because that test was connectionless and didn't actually send, while this is connected and sends. I believe we have to change the test to send to unused port, or remove the test altogether. We should also look for other cases where SocketException is expected and ensure the tests don't send to a port that may be in use.

I will work on a repro and proposed fix.

**Comment by steveharter** [comment] 2017-03-01 22:00
Fix is to disable such tests on non-Windows. Loopback IPV4 and Loopback IPV6 considered separate addresses and on Linux it is easy to get both to exist as separate connections with same port.

**Closed by steveharter** 2017-03-01 22:00 UTC
Labels: area-System.Net.Sockets, os-mac-os-x, tenet-reliability
