### ISSUE TITLE
Incremental build does not work outside Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#6220] opened 2016-02-18 20:38 UTC
RIght now if you build a project twice in a row, the second build re-runs some targets that should be up-to-date already. When I build System.Private.Uri twice on Windows, almost all of the targets are skipped on the second try. On Linux, some targets are re-run. Namely, the CoreResGen and CoreCompile targets are both run again, and those are probably two of the most expensive targets, relatively speaking. 

This may be due to some difference in the x-plat MSBuild we are using. I have tried to use the CoreCLR version of MSBuild on Windows to see if this would reproduce, but there seems to be an issue with csc in that case (something about a COM interface cast failing). Notably, though, it DOES try to rerun the CoreResGen and CoreCompile steps like it does on Linux, and skips the same targets that it does on Linux. So I strongly suspect this is a bug in the CoreCLR-MSBuild we are using.

@joperezr

**Comment by mellinoe** [comment] 2016-02-18 20:40
I am also curious if this is having an effect on build times in our x-plat builds. If things are not being built incrementally, it could have a pretty big effect on overall time.

**Comment by joperezr** [comment] 2016-02-18 21:44
@rainersigwald I'm seeing this as well in both Linux and OSX. Are you guys aware of this?

**Comment by rainersigwald** [comment] 2016-02-18 21:59
Not a problem I'm aware of. @cdmihai have you noticed anything like this?

**Comment by mellinoe** [comment] 2016-02-18 22:54
Another point of interest: Incremental build seems to work on our "ref" projects, for whatever reason. The ref projects are much simpler in general and don't get hooked into as much as our library builds from our custom targets. I'm also able to reproduce this all on Windows if I just pass `/p:DebugType=none` to MSBuild (to work around that csc issue above).

**Comment by cdmihai** [comment] 2016-02-19 17:43
I haven't noticed this issue so far, but I was also not paying special attention to incrementality when perusing the msbuild logs. I'll keep an eye for it.

@mellinoe Can you please open an issue in the msbuild repository with some small repro steps?

**Comment by joperezr** [comment] 2016-02-22 17:07
@mellinoe Should we close the issue in corefx since looks like the problem is MSBuild and you already logged an issue in their repo for it?

**Comment by mellinoe** [comment] 2016-02-22 18:41
@joperezr I'm going to leave it for now, at least until we know the real root cause. Perhaps there is some issue in our targets files that we will eventually need to fix which is only breaking CoreCLR MSBuild. It looks unlikely, but still possible. And the issue can serve as a marker for others who hit this.

**Comment by joperezr** [comment] 2016-11-02 23:33
@mellinoe any updates on this or  has it just gone stale? if so, perhaps we should just close it and reopen later if we see this again

**Comment by mellinoe** [comment] 2016-11-02 23:51
I dunno, I haven't paid enough attention lately to see if it still happens. It's possible that the problem has just gone away in the meantime.

**Comment by joperezr** [comment] 2016-11-03 22:34
Ok, in that case I'll close this but feel free to re-open if you see it again.

**Closed by joperezr** 2016-11-03 22:34 UTC
Labels: Infrastructure, os-linux, os-mac-os-x
