### ISSUE TITLE
[arm32/Windows] System.Runtime.Extensions.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34039] opened 2018-12-12 22:02 UTC
Running the arm32 tests on windows for System.Runtime.Extensions.Tests produced the following results: passed 6479/6481 tests.

System.Tests.EnvironmentTests.GetFolderPath_Windows theory has 2 failing cases (folder= AdminTools and CommonAdminTools). The callstack is:
```
Assert.NotEmpty() Failure
   at System.Tests.EnvironmentTests.GetFolderPath_Windows(SpecialFolder folder) in F:\git\corefx\src\System.Runtime.Extensions\tests\System\EnvironmentTests.cs:line 493
```

[testResults.zip](https://github.com/dotnet/corefx/files/2673697/testResults.zip)

**Comment by danmosemsft** [comment] 2018-12-12 22:33
Dupe of https://github.com/dotnet/corefx/issues/33986

**Closed by danmosemsft** 2018-12-12 22:33 UTC
Labels: arch-arm32, area-System.Runtime.Extensions, os-windows-iot, test-run-core
