### ISSUE TITLE
NETStandard2.0 libraries referencing types absorbed into NETStandard2.1 cannot be used in NS2.1

### ISSUE THREAD

**Issue by sgjsakura** [dotnet/corefx#36719] opened 2019-04-09 03:10 UTC
## How to reproduce
In Visual Studio 2019 RTM, create a new .NET Standard library, and set the target framework to ".NET Standard 2.1". Then add a reference to `System.IO.Pipelines` (either the lastest stable version `4.5.3` or beta version `4.6.0-preview3-191128.7`).

## Error message
The type `System.ReadOnlySpan<T>` (or other types defined in `System.Memory` assembly) is defined in both `System.Memory, version=4.0.1.0` and `netstandard, version=2.1.0.0`.

## Comments
Maybe the reference list of `System.IO.Pipelines` assembly under netstd 2.1 should be updated in order to fix this problem, and many thanks~

**Comment by ahsonkhan** [comment] 2019-04-09 03:28
cc @davidfowl, @pakrym, @ericstj, @terrajobst - presumably this won't be a one-off issue given what's in netstandard2.1.

**Comment by ericstj** [comment] 2019-04-09 04:33
Yep, expected given the current POR not to absorb the assembly past assembly identities into netstandard2.1.  2 options:
1. Have System.Memory ship a new version that has a facade for ns2.1.  People still need to upgrade the package reference to get this.
2. Include a System.Memory facade in netstandard2.1.

2 is the expectation of our users, since that's what we did for 2.0.

/cc @wtgodbe

**Comment by ericstj** [comment] 2019-04-13 14:55
@terrajobst we need to do something here.  Either we ship a new version of System.Memory and all other packages absorbed into netstandard, targeting netstandard2.1, and tell folks they need to upgrade, or we add the facades to the NETStandard 2.1 targeting pack like we did for 2.0.

As mentioned above I think the expectation of users is that we do the latter.  I also think that practically speaking all our frameworks supporting ns2.1 will also want to support the 2.0 libs that were previously using these types, so they will include the old facades as well.  So putting them in netstandard2.1 isn't really added burden.

**Comment by ericstj** [comment] 2019-04-15 19:18
This is now being caught in our package testing once we pick up a new SDK with NuGet mapping for NS2.1: https://github.com/dotnet/corefx/pull/36859

Here's the type overlap our tests are catching:

Type | Assembly
-- | --
System.Buffers.ArrayPool`1 | System.Buffers.dll
System.Buffers.Binary.BinaryPrimitives | System.Memory.dll
System.Buffers.BuffersExtensions | System.Memory.dll
System.Buffers.IBufferWriter`1 | System.Memory.dll
System.Buffers.IMemoryOwner`1 | System.Memory.dll
System.Buffers.IPinnable | System.Memory.dll
System.Buffers.MemoryHandle | System.Memory.dll
System.Buffers.MemoryManager`1 | System.Memory.dll
System.Buffers.MemoryPool`1 | System.Memory.dll
System.Buffers.OperationStatus | System.Memory.dll
System.Buffers.ReadOnlySequence`1 | System.Memory.dll
System.Buffers.ReadOnlySequence`1/Enumerator | System.Memory.dll
System.Buffers.ReadOnlySequenceSegment`1 | System.Memory.dll
System.Buffers.StandardFormat | System.Memory.dll
System.Buffers.Text.Base64 | System.Memory.dll
System.Buffers.Text.Utf8Formatter | System.Memory.dll
System.Buffers.Text.Utf8Parser | System.Memory.dll
System.Memory`1 | System.Memory.dll
System.MemoryExtensions | System.Memory.dll
System.ReadOnlyMemory`1 | System.Memory.dll
System.ReadOnlySpan`1 | System.Memory.dll
System.ReadOnlySpan`1/Enumerator | System.Memory.dll
System.Runtime.InteropServices.MemoryMarshal | System.Memory.dll
System.Runtime.InteropServices.SequenceMarshal | System.Memory.dll
System.SequencePosition | System.Memory.dll
System.Span`1 | System.Memory.dll
System.Span`1/Enumerator | System.Memory.dll
System.Numerics.Matrix3x2 | System.Numerics.Vectors.dll
System.Numerics.Matrix4x4 | System.Numerics.Vectors.dll
System.Numerics.Plane | System.Numerics.Vectors.dll
System.Numerics.Quaternion | System.Numerics.Vectors.dll
System.Numerics.Vector | System.Numerics.Vectors.dll
System.Numerics.Vector`1 | System.Numerics.Vectors.dll
System.Numerics.Vector2 | System.Numerics.Vectors.dll
System.Numerics.Vector3 | System.Numerics.Vectors.dll
System.Numerics.Vector4 | System.Numerics.Vectors.dll
System.Reflection.DispatchProxy | System.Reflection.DispatchProxy.dll
System.Reflection.Emit.AssemblyBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.AssemblyBuilderAccess | System.Reflection.Emit.dll
System.Reflection.Emit.ConstructorBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.EnumBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.EventBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.FieldBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.GenericTypeParameterBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.MethodBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.ModuleBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.PropertyBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.TypeBuilder | System.Reflection.Emit.dll
System.Reflection.Emit.CustomAttributeBuilder | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.ILGenerator | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Label | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.LocalBuilder | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.ParameterBuilder | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.SignatureHelper | System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.DynamicMethod | System.Reflection.Emit.Lightweight.dll
System.Runtime.CompilerServices.AsyncMethodBuilderAttribute | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1 | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable/ConfiguredValueTaskAwaiter | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1 | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1/ConfiguredValueTaskAwaiter | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ValueTaskAwaiter | System.Threading.Tasks.Extensions.dll
System.Runtime.CompilerServices.ValueTaskAwaiter`1 | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Sources.IValueTaskSource | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Sources.IValueTaskSource`1 | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Sources.ValueTaskSourceOnCompletedFlags | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Sources.ValueTaskSourceStatus | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.ValueTask | System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.ValueTask`1 | System.Threading.Tasks.Extensions.dll

**Comment by terrajobst** [comment] 2019-04-20 04:09
As discussed, we should include all those facades with .NET Standard 2.1.

Is this issue related to .NET Core at all? If not, let's move it to dotnet/standard.

**Comment by PinpointTownes** [comment] 2019-04-29 19:17
I can confirm I'm seeing the same issue when using `ValueTask` in a .NET Standard 2.1 class library referencing a .NET Standard 2.0 library that relies on the `System.Threading.Tasks.Extensions` package (with the preview4 tooling):

```
The type 'ValueTask<TResult>' exists in both 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

Good to hear it's something you'll be able to fix in 3.0 RTM.

**Comment by Fabi** [comment] 2019-05-14 10:44
Referencing any System.IO.Pipelines version into a netstandard2.1 project and usage of ReadOnlySpan<T> results in `error CS0433: The type 'ReadOnlySpan<T>' exists in both 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

This happens in dotnet sdk version `3.0.100-preview6-011865`

**Comment by ahsonkhan** [comment] 2019-05-16 03:23
Re-opening until https://github.com/dotnet/corefx/pull/37532 is done.

**Comment by wtgodbe** [comment] 2019-05-16 16:54
@ahsonkhan good call, looks like github closed the issue automatically because I said "Resolved" in that PR 😄 . I just merged the second PR, so now we can actually close this.

**Closed by wtgodbe** 2019-05-16 16:54 UTC
Labels: area-System.Memory, blocking-release

**Comment by davidfowl** [comment] 2019-05-16 16:57
@wtgodbe Can you let me know when we can very this in a core-sdk build?

**Comment by wtgodbe** [comment] 2019-05-16 17:00
The change in Standard has already been absorbed by core-sdk, with https://github.com/dotnet/core-sdk/commit/ebd193f9afcb1c3f37adedd32bbe6858bd8294c2#diff-5c6a1c77fe216efcfbbdccb11b863063. I believe you should be able to try validation now.

**Comment by Fabi** [comment] 2019-05-16 17:47
> The change in Standard has already been absorbed by core-sdk, with [dotnet/core-sdk@ebd193f#diff-5c6a1c77fe216efcfbbdccb11b863063](https://github.com/dotnet/core-sdk/commit/ebd193f9afcb1c3f37adedd32bbe6858bd8294c2#diff-5c6a1c77fe216efcfbbdccb11b863063). I believe you should be able to try validation now.

Works good ty!

**Comment by ahsonkhan** [comment] 2019-05-16 23:20
@sgjsakura and @PinpointTownes, can you verify as well, please?

**Comment by PinpointTownes** [comment] 2019-05-16 23:23
Sure. What’s needed for that? Do I have to install a nightly build of the SDK?

**Comment by wtgodbe** [comment] 2019-05-20 16:41
@PinpointTownes yes, a nightly build of the SDK should work for validation. You can grab the installer from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe. The repro steps in the original post for this issue should be sufficient.

**Comment by PinpointTownes** [comment] 2019-05-20 17:12
Oddly I'm now getting a different error with 3.0.100-preview6-012016 :

> error CS0012: The type 'ValueTask<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Are there additional things you need to do to make that work?
I'll make a tiny repro to ensure it's not a bug on my side.

**Comment by PinpointTownes** [comment] 2019-05-20 17:33
I get the same error (with a different assembly version) with this simple repro:

```
error CS0012: The type 'ValueTask<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

![image](https://user-images.githubusercontent.com/6998306/58040483-e9f2d700-7b35-11e9-8a3f-0fee1d2e178c.png)


### NetStandard20Library.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.2" />
  </ItemGroup>

</Project>
```

### Class1.cs

```cs
using System.Threading.Tasks;

namespace NetStandard20Library
{
    public class Class1
    {
        public static ValueTask<int> Value => new ValueTask<int>(42);
    }
}
```

### NetStandard21Library.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetStandard20Library\NetStandard20Library.csproj" />
  </ItemGroup>

</Project>
```

### Class2.cs

```cs
using System.Threading.Tasks;
using NetStandard20Library;

namespace NetStandard21Library
{
    public class Class2
    {
        public async Task TestAsync()
        {
            var value = await Class1.Value;
        }
    }
}
```

I'm probably missing something obvious, but not sure what 😕

**Comment by ericstj** [comment] 2019-05-21 17:56
Should be fixed with https://github.com/dotnet/standard/pull/1203.

**Comment by ericstj** [comment] 2019-05-22 16:53
https://github.com/dotnet/corefx/pull/37847 ingested this to CoreFX

**Comment by PinpointTownes** [comment] 2019-05-27 13:51
I can confirm everything works like a charm with the latest SDK. Great job 👍
