### ISSUE TITLE
System.Text.Json - TypeLoadException

### ISSUE THREAD

**Issue by dhindrik** [dotnet/corefx#38671] opened 2019-06-19 07:16 UTC
I try to use System.Text.Json in my Xamarin.iOS app. I have added the NuGet package to my .NET Standard 2.0 project where I have my shared code. 

```csharp
var tasks = JsonSerializer.Parse<List<UserTask>> (itemAsString);
```

When I running that line of code I got the following Exception:

> Could not load type of field 'System.Text.Json.JsonWriterHelper:s_hexStandardFormat' (1) due to: Could not resolve type with token 01000050 from typeref (expected class 'System.Buffers.StandardFormat' in assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Buffers.StandardFormat member:(null)

=== Visual Studio Enterprise 2019 (Preview) for Mac ===

Version 8.2 Preview (8.2 build 732)
Installation UUID: 05aabb23-140a-4af9-9c07-b62b81b9fc3c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.83 (d16-2 / f08d4e3e)

	Package version: 600000296

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.296 (2019-02/1e9f3bfbc5a) (64-bit)
	Package version: 600000296

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview3-27503-5
	2.2.4
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.6
	2.1.2
	2.1.1
	2.0.7
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.500
	2.1.302
	2.1.301
	2.1.200
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.3.0.22 (Visual Studio Enterprise)
Commit: HEAD/8e7764fdf
Android SDK: /Users/dhindrik/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08@3cb36842fc4
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/dhindrik/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.56
Hash: a883204
Branch: remotes/origin/d16-2
Build date: 2019-05-30 09:42:42 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.153 (Visual Studio Enterprise)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin.iOS ===

Version: 12.10.0.153 (Visual Studio Enterprise)
Hash: 750a8798
Branch: d16-1-artifacts
Build date: 2019-04-30 15:17:54-0400

=== Xamarin Designer ===

Version: 16.2.0.298
Hash: b09805d48
Branch: remotes/origin/d16-2
Build date: 2019-06-11 00:32:38 UTC

=== Build Information ===

Release ID: 802000732
Git revision: f61490add155ef258c433759f4720f7f8b30abbf
Build date: 2019-06-13 13:49:11+00
Build branch: release-8.2-preview1
Xamarin extensions: c32b720b4e8cdb552962d8cbfa76ea4245b495e0

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.50

**Comment by ahsonkhan** [comment] 2019-06-20 05:15
> Runtime Versions:
3.0.0-preview3-27503-5

It looks like you don't have the latest dotnet sdk version on your machine. That's probably OK since you are referencing the netstandard2.0 compatible NuGet package (rather than using the built-in library as part of .NET Core 3.0).

Can you tell me which version of the package you are referencing? Is it `4.6.0-preview6.19303.8`?https://www.nuget.org/packages/System.Text.Json/4.6.0-preview6.19303.8

If you have a small repro of your app that you can share, that would help us reproduce the issue to figure out the root cause. Are you referencing an older version of System.Memory NuGet package somewhere?

cc @joperezr

**Comment by dhindrik** [comment] 2019-06-20 05:45
> Can you tell me which version of the package you are referencing? Is it `4.6.0-preview6.19303.8`?https://www.nuget.org/packages/System.Text.Json/4.6.0-preview6.19303.8
> 
> If you have a small repro of your app that you can share, that would help us reproduce the issue to figure out the root cause. Are you referencing an older version of System.Memory NuGet package somewhere?

I am referencing '4.6.0-preview6.19303.8'. I'm not able to share this repo, it is for an app that I am building for a customer. But I can try to recreate it in a new solution. I can't see any references to the System.Memory package. Maybe if some other packages have it like a dependency.

**Comment by joperezr** [comment] 2019-06-20 20:18
Can you provide a build binlog of your project? This will not contain the code you are writing, but only the information about the build itself. That way we might be able to repro the issue you are seeing. in order to generate a binlog, run the following in a development command prompt: `msbuild yourProject.csproj /t:rebuild /bl:msbuild.binlog` which would generate a msbuild.binlog file in the current working directory.

**Comment by ahsonkhan** [comment] 2019-06-24 17:46
@dhindrik, were you able to grab the requested info?

**Comment by dhindrik** [comment] 2019-06-25 10:30
[msbuild.binlog.zip](https://github.com/dotnet/corefx/files/3324786/msbuild.binlog.zip)

**Comment by joperezr** [comment] 2019-06-26 16:54
The problem here seems to be that the System.Memory Facade that is inbox in Xamarin don't have the required typeforward in order for things to work properly. This seems to have been fixed in Xamarin already, by this PR: https://github.com/mono/mono/pull/14344 
This means that in theory this will be fixed in the future versions of Xamarin. I would ask @marek-safar to get more info into which versions of Xamarin have this fix. I'm closing this issue given that this isn't a problem with corefx or the System.Text.Json package. @dhindrik feel free to reopen if you think otherwise.

**Closed by joperezr** 2019-06-26 16:54 UTC
Labels: area-System.Text.Json, needs more info, packaging

**Comment by vikramtamboli** [comment] 2019-08-12 05:26
Hi Team,

We are trying to compile source from **https://github.com/SteveSandersonMS/presentation-2019-06-NDCOslo/tree/master/demos/MissionControl**

When we run below command we get exception
**D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server>dotnet build**

Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
  Restore completed in 108.36 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
  Restore completed in 505.88 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj.
  Restore completed in 1.03 sec for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\PinMapLibrary.csproj.
  Restore completed in 35.97 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\MissionControl.Shared.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
  MissionControl.Shared -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\bin\Debug\netstandard2.0\MissionControl.Shared.dll
  PinMapLibrary -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\bin\Debug\netstandard2.0\PinMapLibrary.dll
  MissionControl.Client -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\bin\Debug\netstandard2.0\MissionControl.Client.dll
_EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
     at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.GetBootJsonContent(String assemblyFileName, String entryPoint, String[] assemblyReferences, IEnumerable`1 embeddedContent, Boolean linkerEnabled)
     at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.WriteFile(String assemblyPath, String[] assemblyReferences, String[] embeddedResourcesSources, Boolean linkerEnabled, String outputPath)
     at Microsoft.AspNetCore.Blazor.Build.DevServer.Commands.WriteBootJsonCommand.<>c__DisplayClass0_0.<Command>b__0()
C:\Users\349185\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]_

Build FAILED.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
C:\Users\349185\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
    4 Warning(s)
    2 Error(s)

Time Elapsed 00:00:13.34
