### ISSUE TITLE
Process.WaitForExit does not always return, even if process has exited [macOS/Linux]

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#29699] opened 2018-05-14 20:11 UTC
It appears Process.WaitForExit does not actually complete if called from certain threads, even if the process it waits on has exited. I've only been able to reproduce this on macOS and Linux, not Windows.

**Repro**
This issue was originally reported as a bug in dotnet-watch (see https://github.com/aspnet/DotNetTools/issues/410)

I created a minimal repro here: https://gist.github.com/natemcmaster/b6229d8c923f9305f2f71ffa1686ac8b.

To run it,
```
$ dotnet build
$ dotnet bin/Debug/netcoreapp2.1/App.dll
(Wait for a few seconds and press CTRL + C)
```

The actual code that has encounters the issue is here: https://github.com/aspnet/Common/blob/2.1.0-rc1-final/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L48

**Expected**
1. dotnet App.dll starts child process A ("sleep 60")
2. CTRL+C event fires
3. The app invokes `Process.Start("pgrep", $"-P {processA.Id}")` and reads the output of pgrep to find any child processes
4. The app reads the output of p kills child process A and its entire process tree
5. App exists

**Actual**
1. dotnet App.dll starts child process A ("sleep 60")
2. CTRL+C event fires
3. The app invokes `Process.Start("pgrep", $"-P {processA.Id}")`, but the WaitForExit call on the process object never returns, even after pgrep has exited.

**Details**
I investigated a little. From what I can tell, the indefinite hang appears to happen when Process.WaitForExit is invoked on certain threads. The hang consistently appears if called when Thread.CurrentThread.IsThreadPoolThread == false.

If I dispatch the cancelling the cancellation token via ThreadPool.QueueUserWorkItem, Process.WaitForExit works as expected.

**Comment by stephentoub** [comment] 2018-05-15 03:00
Does this repro on 2.0?

I have a suspicion that this is due to changes @tmds made in 2.1.  In 2.1, WaitForExit is going to depend on handling SIGCHLD, but your code is effectively creating a deadlock due to that.  The ctrl-C handler will be invoked from the signal handling thread, it synchronously cancels the token which synchronously completes the exited task which synchronously runs the continuation of the exited task which synchronously calls WaitForExit, which will end up blocking waiting for the associated SIGCHLD to be processed, which won't happen because that thread is blocked processing the callback... and deadlock.  

That would explain why changing the code to use `ThreadPool.QueueUserWorkItem(() => cts.Cancel())` instead of just `cts.Cancel()` made the issue go away, as that would end up freeing up the signal handling thread to process the subsequent SIGCHLD.  I expect you'd similarly see the problem go away if you changed `private readonly TaskCompletionSource<int> _exited = new TaskCompletionSource<int>();` to instead be `private readonly TaskCompletionSource<int> _exited = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);` or if you added an `await Task.Yield();` after the `await _exited.Task;` in your repro.

@tmds, does that sound right?  If so this is an unfortunate side effect of that change.
cc: @danmosemsft, @ViktorHofer

**Comment by Teeeeew** [comment] 2018-05-15 03:02
On May 14, 2018 11:01 PM, "Stephen Toub" <notifications@github.com> wrote:

Does this repro on 2.0?

I have a suspicion that this is due to changes @tmds
<https://github.com/tmds> made in 2.1. In 2.1, WaitForExit is going to
depend on handling SIGCHLD, but your code is effectively creating a
deadlock due to that. The ctrl-C handler will be invoked from the signal
handling thread, it synchronously cancels the token which synchronously
completes the exited task which synchronously runs the continuation of the
exited task which synchronously calls WaitForExit, which will end up
blocking waiting for the associated SIGCHLD to be processed, which won't
happen because that thread is blocked processing the callback... and
deadlock.

That would explain why changing the code to use ThreadPool.QueueUserWorkItem(()
=> cts.Cancel()) instead of just cts.Cancel() made the issue go away, as
that would end up freeing up the signal handling thread to process the
subsequent SIGCHLD. I expect you'd similarly see the problem go away if you
changed private readonly TaskCompletionSource<int> _exited = new
TaskCompletionSource<int>(); to instead be private readonly
TaskCompletionSource<int> _exited = new
TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
or if you added an await Task.Yield(); after the await _exited.Task; in
your repro.

@tmds <https://github.com/tmds>, does that sound right? If so this is an
unfortunate side effect of that change.
cc: @danmosemsft <https://github.com/danmosemsft>, @ViktorHofer
<https://github.com/ViktorHofer>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/corefx/issues/29699#issuecomment-389027683>, or mute
the thread

**Comment by natemcmaster** [comment] 2018-05-15 03:44
No, it doesn't repro on netcoreapp2.0. And yes, using TaskCreationOptions.RunContinuationsAsynchronously appears to be another way to solve the issue.

**Comment by tmds** [comment] 2018-05-15 06:50
> @tmds, does that sound right? If so this is an unfortunate side effect of that change.

That is indeed the root cause. I did not see that one coming :disappointed: 
WaitForExit can't complete if OnCancelKeyPress is blocked.

```C#
        private static void OnCancelKeyPress(object sender, ConsoleCancelEventArgs e)
        {
            using (var process = Process.Start("sleep", "1"))
            {
                process.WaitForExit();
            }
        }
```

**Comment by danmosemsft** [comment] 2018-05-15 17:16
@stephentoub so this only reproes when handling a signal. What potentially interesting scenarios might lead to someone calling WaitForExit on our signal handling thread?

If it's just Ctrl-C I suspect you're correct that this would not quite meet the bar.

**Comment by danmosemsft** [comment] 2018-05-15 17:30
Looks like just these.
```
    InstallSignalHandler(SIGINT , /* skipWhenSigIgn */ true);
    InstallSignalHandler(SIGQUIT, /* skipWhenSigIgn */ true);
    InstallSignalHandler(SIGCONT, /* skipWhenSigIgn */ false);
    InstallSignalHandler(SIGCHLD, /* skipWhenSigIgn */ false);
```
SIGCHLD - it seems to me user code will not run; this is just our waitpid plumbing.
SIGQUIT would have the same issue as SIGINT, I expect.
SIGCONT seems to only set up the terminal again, seems user code will not run.

**Comment by tmds** [comment] 2018-05-15 17:33
> What potentially interesting scenarios might lead to someone calling WaitForExit on our signal handling thread?

If the user closes the app by Ctrl-C, then the app may want to kill some children and WaitForExit. I guess this is how @natemcmaster ran into this.

> SIGQUIT would have the same issue as SIGINT, I expect.

Correct, that one also triggers CancelKeyPress.

**Comment by natemcmaster** [comment] 2018-05-15 17:50
This was the cause of a 30 seconds hang when dotnet-watch exited. The code that hangs calls `Process.WaitForExit(30_000)` (see [this file](https://github.com/aspnet/Common/blob/2.1.0-rc1-final/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L48)). 

This code path also exists in [MSBuild](https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Utilities/ProcessExtensions.cs), but I haven't looked to see this could be called on the CTRL+C thread.

**Comment by natemcmaster** [comment] 2018-05-16 20:48
Awesome, thanks for fixing so quickly.

**Comment by danmosemsft** [comment] 2018-05-29 23:52
fixed

**Closed by danmosemsft** 2018-05-29 23:52 UTC
Labels: Servicing-Approved-2.1.1, area-System.Diagnostics.Process, bug, os-linux
