### ISSUE TITLE
[System.Text.Json] Serialization type inference 

### ISSUE THREAD

**Issue by rducom** [dotnet/corefx#37613] opened 2019-05-12 19:19 UTC
Given 2 classes :
``` csharp
public class SomeType { }
public class DerivedType : SomeType { }
```
and a list of `DerivedType` created with covariance
``` csharp
IEnumerable<SomeType> list = new List<DerivedType>();
var json = JsonSerializer.ToString(list);
```
When serializing, the only properties visible in the result json, are the properties visible on `SomeType`.
Actually, type is inferred from declared instance type, and not real instance type. 
IMO, this is not the expected behavior, and it differs from the behavior of handling `object` type. (and differs from Json.Net).

Actual workaround is to force the type explicitly with overloads. (but `JsonSerializer.ToString(list,list.GetType())` is annoying to write each time)

Fix seems obvious : replacing `typeof(TValue)` with `value.GetType()` on all the methods like [WriteAsync](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L24), [ToString](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L21) or [ToBytes](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.ByteArray.cs#L17)

**Comment by ahsonkhan** [comment] 2019-05-14 04:26
cc @steveharter

**Comment by steveharter** [comment] 2019-06-07 19:17
Closing this as duplicate of https://github.com/dotnet/corefx/issues/37787.

In summary, the 3.0 release depends on static typing by default for secure-by-default scenarios. This is somewhat loosened for properties of type `object` where we do call `GetType` on serialization. In addition for 3.0 we plan to have an opt-in model for polymorphic serialization, and the custom converter feature will enable polymorphic deserialization.

**Closed by steveharter** 2019-06-07 19:17 UTC
Labels: area-System.Text.Json
