### ISSUE TITLE
[Ubuntu18.04] Test failed: System.Drawing.Imaging.Tests.EncoderParameterTests / Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#27021] opened 2018-02-10 20:27 UTC
Failed on newly added distro Ubuntu 18.04. Related to #24274 (failing in the past)

Failure:
```
Assert.Throws() Failure
Expected: typeof(System.OutOfMemoryException)
Actual:   (No exception was thrown)

at System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(Int32 numberOfValues) in /root/corefx-1371172/src/System.Drawing.Common/tests/Imaging/EncoderParameterTests.cs:line 327
```

## History of failure

Day | Build | Details
-- | -- | --
2/10 | 20180210.01 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180210.01/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Imaging.Tests.EncoderParameterTests~2FCtor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues:%20-1))
2/10 | 20180210.03 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180210.03/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Imaging.Tests.EncoderParameterTests~2FCtor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues:%20-1))
2/12 | 20180212.01 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180212.01/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Imaging.Tests.EncoderParameterTests~2FCtor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues:%20-1))
2/12 | 20180212.01 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180212.05/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Imaging.Tests.EncoderParameterTests~2FCtor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues:%20-1))

**Comment by karelz** [comment] 2018-02-10 20:27
Fails on newly added distro: @ianhays cc @danmosemsft @joshfree

**Comment by danmosemsft** [comment] 2018-02-10 22:30
Dupe of https://github.com/dotnet/corefx/issues/24274. @maryamariyan could you please disable this test for Ubuntu 1804. It is already dsiabled for 1710 as you will see.

**Comment by joshfree** [comment] 2018-02-12 18:30
[Link to today's 20180212.05 failure / log](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180212.05/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Imaging.Tests.EncoderParameterTests~2FCtor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues:%20-1))

**Comment by danmosemsft** [comment] 2018-02-12 20:15
Disable was merged

**Closed by danmosemsft** 2018-02-12 20:15 UTC
Labels: area-System.Drawing, os-linux, test bug
