### ISSUE TITLE
CoreRun.exe not being copied to test directory when the script is run

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8749] opened 2016-05-21 03:46 UTC
Hi, I've recently rebased against the latest changes you guys have made to the repo. When I do a clean build of the repo via

```cmd
build /p:ConfigurationGroup=Release /p:SkipTests=true
```

and then cd to an individual `bin/tests/OS.CPU.Release/Assembly.Tests`, then run the `RunTests` script with `path\to\corefx\packages` as the argument, I get the following output:

```
Using C:\Users\James\Code\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\Users\James\Code\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Reflection.Tests\dnxcore50\ 
Hard linking dependent files... 
Finished linking needed files, moving to running tests.
Running tests... Start time: 23:42:38.95
Command(s):
CoreRun.exe xunit.console.netcore.exe System.Reflection.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
'CoreRun.exe' is not recognized as an internal or external command,
operable program or batch file.
Finished running tests.  End time=23:42:38.97, Exit code = 1
```

Looking into the code of the script, it appears the `CoreRun` executable isn't being copied into the test directory, even though it's still being used. [Here's](https://gist.github.com/jamesqo/66617b7ae005de8e6019cc9de146691e) a gist I made of the script (this particular one is for `System.Runtime.Tests`); if you do a Ctrl + F and search for "corerun", you'll notice it's not in one of the dependent files linked in.

**Comment by ellismg** [comment] 2016-05-21 07:43
Are you seeing this with no local changes as well?

**Comment by jamesqo** [comment] 2016-05-21 14:29
@ellismg No, it works fine without local changes; I just did another clone of the repo and re-followed the instructions I listed above, and it seems to be listed in the batch file. Going to look into this further.

**Comment by jamesqo** [comment] 2016-05-21 15:43
Strangely, when I go to master in my old clone/rebase/do a clean build it's still not listed...

**Comment by ellismg** [comment] 2016-05-22 00:26
@jamesqo You might try git cleanin'g and deleting untracked files (to force both packages to be downloaded again and for project.lock.json's to be regenerated).

**Comment by MattGal** [comment] 2016-05-31 17:32
@jamesqo apologies the notifications for this went to Outlook's "Clutter" folder.  As @ellismg  points out, it's clearly from the Runtests.cmd that CoreRun.exe is not part of the files from the PrereleaseResolveNugetPackageAssets tasks (or it'd be in the copy commands).   

Can you give me instructions starting from a clean repo to get this to happen?  Since it happens in master evidently, this should be just the command you're running.

**Comment by MattGal** [comment] 2016-07-19 17:08
Closing as this has not reproduced and no updates since 5/22

**Closed by MattGal** 2016-07-19 17:08 UTC
Labels: Infrastructure
