### ISSUE TITLE
[WebSocket] ManagedWebSocket.ReceiveAsyncPrivate does not use the CancellationToken received as parameter

### ISSUE THREAD

**Issue by florinciubotariu** [dotnet/corefx#33038] opened 2018-10-25 09:14 UTC
Source code can be found [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs).

The `ReceiveAsync` method inside `ManagedWebSocket` class accepts two objects: `ArraySegment` and a `CancellationToken`.

Inside `ReceiveAsync`, another method is called: `ReceiveAsyncPrivate`. This method receives as parameter the passed `CancellationToken`.

`ReceiveAsyncPrivate` does only one thing with the passed `CancellationToken`: registers a callback.

Combined with https://github.com/aspnet/AspNetCore/issues/3128 issue, the ReceiveAsync method will never return and can not be cancelled.

**Comment by karelz** [comment] 2018-10-25 16:20
cc @stephentoub

**Comment by davidsh** [comment] 2018-10-25 19:33
Actually, the existing code is correct.

The registration of the callback is where the cancellation actually can occur:

```c#
CancellationTokenRegistration registration = cancellationToken.Register(s => ((ManagedWebSocket)s).Abort(), this);
```

This code registers the callback.  And that means that if a caller calls `Cancel()` on the cancellation token source, then this callback registration will automatically call the .Abort() method of the websocket.

So, the logic is using the cancellation token and will cancel the operation.

**Comment by davidsh** [comment] 2018-10-25 19:34
>Combined with aspnet/AspNetCore#3128 issue, the ReceiveAsync method will never return and can not be cancelled.

Do you have a repro that shows that cancellation is not working?  Please attach a small repro that would demonstrate that.

Otherwise, the code appears to be functioning correctly.

**Comment by janusznoszczynski** [comment] 2018-11-30 11:01
I have the same issue when using WebSocket with ngrok tunelling

**Comment by janusznoszczynski** [comment] 2018-11-30 11:04
@karelz Any workarounds?

**Comment by karelz** [comment] 2018-11-30 16:19
I don't think we fully understand the root cause yet, so no workarounds ...

**Comment by stephentoub** [comment] 2019-01-11 15:39
Fixed by https://github.com/dotnet/corefx/pull/33196.

**Closed by stephentoub** 2019-01-11 15:39 UTC
Labels: area-System.Net, bug
