### ISSUE TITLE
Add API to create file system links

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#29978] opened 2018-05-30 13:18 UTC
## Rationale ##

On Windows links are rarely used. On Unix links are used more often and in PowerShell repo we have to implement the API by means of P/Invokes. On Unix this requires creating a native library. In PowerShell repo we would be happy to get rid of the P/Invokes.

Currently PowerShell use path strings and static methods to process file system. I believe we'll review this and move to using FileSystemInfo types to exclude extra path parsings and normalizations. So the proposal contains both static and non-static methods.

PowerShell add magic property `Target` in FileInfo and DirectoryInfo. The method is [here](https://github.com/PowerShell/PowerShell/blob/4c925f58b80893690532c26788a913fdd35fdb70/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7979)
Below the method you can find other methods that implement PowerShell Core work with links.

PowerShell implement [GetLinkType()](https://github.com/PowerShell/PowerShell/blob/4c925f58b80893690532c26788a913fdd35fdb70/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L8007) method for FileSystemInfo. It returns a string. In the proposal we could consider that the method will returns an enum value.

## Proposed API ##

```c#
namespace System.IO
{
    public static class File
    {
        public static FileInfo CreateFileSymbolicLink(string symlinkName, string targetPath);
        public static DirectoryInfo CreateDirectorySymbolicLink(string symlinkName, string targetPath);

        public static FileInfo CreateHardLink(string newFileName, string targetExistingFileName);

        public static bool IsSymbolicLink(string path);
        public static bool IsHardLink(string path);

        public static FileSystemInfo GetTarget(string path);
    }

    public class FileSystemInfo
    {
        public bool IsSymbolicLink { get; }
        public bool IsHardLink { get; }

        // The string value of the target for symbolic links otherwise null
        public string Target { get; }

        public void CreateSymbolicLink(string linkPath);
        public void CreateHardLink(string linkPath);
    }
}
```

/cc @JeremyKuhne 

Related #26310, #25569

**Comment by jnm2** [comment] 2018-05-30 14:20
> In PowerShell repo we would be happy to get rid of the P/Invokes.

Would this happen, though? You'd have to drop support for .NET Core earlier than 2.2.

**Comment by kasper3** [comment] 2018-05-30 16:14
> Related #26310, #25569

Why can't those existing issues, both are still opened?

**Comment by iSazonov** [comment] 2018-05-31 05:02
@kasper3 Those APIs is only for symlinks and looks as "theory". @JeremyKuhne ask me to reference PowerShell implementation and I opened the issue. The proposal is for symbolic and hard links.  It is from real PowerShell code - modern MSFT shell which we actively use and should improve. Anybody can download, install and tests how PowerShell works with links. I guess we have still many issues there.

**Comment by carlossanlop** [comment] 2020-01-23 22:54
Triage:
Let's focus the discussion in #25569 , which is the older issue. Let's make sure we discuss the hard link scenario in the other issue.

**Comment by carlossanlop** [comment] 2020-01-23 22:54
Duplicate of #25569

**Closed by carlossanlop** 2020-01-23 22:54 UTC
Labels: api-suggestion, area-System.IO
