### ISSUE TITLE
PlatformNotSupportedException using ConfigurationManager in ASP.NET 4.6.2

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/corefx#21197] opened 2017-06-19 03:31 UTC
I'm upgrading an existing and complex ASP.NET 4.6.2 application to use .NET Standard across the board. `ConfigurationManager` is not included in the standard by default, so I added `System.Configuration.ConfigurationManager 4.4.0-preview1-25305-02` to the .NET standard project that houses all my `ConfigurationSection`-based classes.

When I did, my previously-working ASP.NET app threw a `PlatformNotSupported` exception from `ConfigurationManager`. That didn't really make any sense, seeing as how the package is _specifically designed_ to be able to run in that environment.

I traced the error down to [here](https://github.com/dotnet/corefx/blob/master/src/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationErrorsException.cs#L106) in which every constructor permutation throws the `PlatformNotSupportedException`. The problem is, `ConfigurationManager` will currently (and legitimately) throw a `ConfigurationErrorsException` in 3 different cases. So you get a very unhelpful exception in a library that should be redirecting you to System.Configuration.dll on .NET 4.6.1+ ANYWAY.

Severity: BLOCKING.

**Comment by danmosemsft** [comment] 2017-06-19 03:39
@robertmclaws can you clarify -- your suggestion is that this exception should suggest using System.Configuration if it finds it's running on desktop?

@jeremykuhne

**Comment by robertmclaws** [comment] 2017-06-19 04:04
@danmosemsft No, sorry... what I am suggesting is that the code should either be functional on Desktop (probably by removing the PlatformNotSupportedException, or the NuGet package should be fixed redirect to System.Configuration when installed on Desktop. Right now the package is targeting .NET Standard 2.0 but doesn't actually work when you use it.

If the package is going to be fixed, it should probably be named System.Configuration, like the assembly it replaces.

Thanks!

**Comment by danmosemsft** [comment] 2017-06-19 04:18
@weshaggard thoughts? this package is never going to be as functional as the desktop version - should it seamlessly be ignored when on desktop?

**Comment by weshaggard** [comment] 2017-06-19 16:19
This nuget package should already be redirecting to System.Configuration on .NET 4.6.1+, see https://github.com/dotnet/corefx/pull/19224. However it doesn't look like that change made it into preview1 builds. @robertmclaws can you try using the our candidate for preview2 from our myget feed. https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Configuration.ConfigurationManager/4.4.0-preview2-25405-01.  I think that will have what you are looking for.

**Comment by danmosemsft** [comment] 2017-08-21 21:57
@robertmclaws is this resolved for you in final bits? if so we should be able to close this.

**Comment by maryamariyan** [comment] 2018-03-19 22:40
@robertmclaws were you able to get unblocked using the newer versions of the ```System.Configuration.ConfigurationManager``` package? 

Otherwise, I was wondering if you have a code snippet from the exception you hit to help with reproducing the bug?

**Comment by Treit** [comment] 2018-08-28 19:27
This issue does not seem to be resolved, or there is a variation on it that is exposed when attempting to consume a .NET Standard library from a unit test project. I see PlatformNotSupportedException if the unit test exercises code in a .NET Standard library that attempts to access ConfigurationManager.AppSettings.

I have created a simple demonstration project that reproduces the issue:

https://github.com/Treit/misc/tree/master/NetStandardUnitTestProblem

**Comment by eric-raes** [comment] 2019-01-04 11:21
Is this fixed in the meanwhile?

We are moving a lot of library projects away from Full .NET to .NET standard. 
One helper project is shared accross some old ASP.Net web services and a .NET Core REST service. 

We keep getting PlatformNotSupported exception when trying to read the web.config file for connectionstrings in the .NET Standard helper project when used under an ASP.net webservice. Is `System.Configuration.ConfigurationManager.ConnectionStrings[name].ConnectionString;` the correct way to read from web.config, or is there another (better) solution?

I thought this cannot be such an issue, but it is currently blocking our progress.

Thanks in advance for any help!

**Comment by ericstj** [comment] 2019-03-06 17:32
@eric-raes / @Treit you're running the netstandard implemenation of this package in a netframework application.  This is happeneing because you haven't referenced the ConfigurationManager package in the netframework application and it's using Package.config (which doesn't flow transitive package dependencies).  The only reason you aren't seeing a FileNotFoundException here is because the library made a setting to copy its dependencies to the output folder: https://github.com/Treit/misc/blob/3f311393e8f36d4458c913690366cc67c54722a5/NetStandardUnitTestProblem/NetStandardTest/NetStandardTest.csproj#L5, and MSBuild of the desktop project desperately is trying to find any copy of ConfigurationManager.dll so it uses the one from the netstandard library's output folder.  This is incorrect since the package provides a "better" one for .NETFramework.

Do one of the following
1. Add a reference to the System.Configuration.ConfigurationManager package in your desktop projects.
2. Convert those desktop projects from packages.config to PackageReference, so they automatically get the nuget packages of their transitive references.

**Comment by ericstj** [comment] 2019-03-06 18:56
Also, make sure you haven't explicitly disabled the flow of PackageReferences by marking them with PrivateAssets or ExcludeAssets.

**Comment by ericstj** [comment] 2019-03-13 18:04
Closing this out per my above comments.  Please reopen if you have some more information or my explanation didn't help.

**Closed by ericstj** 2019-03-13 18:04 UTC
Labels: area-System.Configuration
