### ISSUE TITLE
StartsWith/EndsWith not giving expected results on Linux

### ISSUE THREAD

**Issue by slozier** [dotnet/corefx#29474] opened 2018-05-03 11:48 UTC
Both of these are passing on Windows but failing on Linux (Ubuntu 16.04 over WSL). Also fails if I use the invariant comparison.
```C#
Debug.Assert("\r\n".EndsWith("\n"));
Debug.Assert("\r\n".StartsWith("\r"));
```

**Comment by stephentoub** [comment] 2018-05-05 17:38
Dup of https://github.com/dotnet/corefx/issues/4587, and specifically see https://github.com/dotnet/corefx/issues/4587#issuecomment-219087701.

**Comment by karelz** [comment] 2018-05-05 18:43
Closing as duplicate of #4587

**Closed by karelz** 2018-05-05 18:43 UTC
Labels: area-System.Runtime, os-linux
