### ISSUE TITLE
PostEmptyContentUsingChunkedEncoding_Success failed on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5485] opened 2016-01-16 18:17 UTC
"The server returned an invalid or unrecognized response"... I assume this is just some sort of intermittent infrastructure issue, but opening an issue just in case.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1092/consoleFull

```
09:59:40      System.Net.Http.Functional.Tests.PostScenarioTest.PostEmptyContentUsingChunkedEncoding_Success(serverUri: http://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
09:59:40 
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
09:59:40         ---- System.IO.IOException : The write operation failed, see inner exception.
09:59:41         -------- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
09:59:41         Stack Trace:
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
09:59:41            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(152,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostHelper>d__21.MoveNext()
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
09:59:41            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(62,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostEmptyContentUsingChunkedEncoding_Success>d__11.MoveNext()
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41            ----- Inner Stack Trace -----
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
09:59:41            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpRequestStream.cs(160,0): at System.Net.Http.WinHttpRequestStream.<EndUploadAsync>d__25.MoveNext()
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
09:59:41            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1324,0): at System.Net.Http.WinHttpHandler.<InternalSendRequestBodyAsync>d__126.MoveNext()
09:59:41            --- End of stack trace from previous location where exception was thrown ---
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
09:59:41               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
09:59:41               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
09:59:41            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(835,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
```

**Comment by mellinoe** [comment] 2016-01-20 23:29
Hit this again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1211/

**Comment by stephentoub** [comment] 2016-01-21 20:14
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug/330/consoleFull

**Comment by davidsh** [comment] 2016-01-22 04:47
Added:http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1290/

**Comment by CIPop** [comment] 2016-06-16 18:03
Duplicate of #4171.

**Comment by steveharter** [comment] 2017-04-15 23:42
Reopening as #4171 did not disable this test. This failure is still occurring in CI, and can be repro'd in Windows 2008 under stress

**Comment by steveharter** [comment] 2017-04-15 23:52
Pulled these occurrances from PR #13298 which had the incorrect test info:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/133/testReport/System.Net.Http.Functional.Tests/PostScenarioTest/PostEmptyContentUsingChunkedEncoding_Success_serverUri__https___corefx_net_cloudapp_net_Echo_ashx_/
and
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/122/testReport/System.Net.Http.Functional.Tests/PostScenarioTest/PostEmptyContentUsingChunkedEncoding_Success_serverUri__https___corefx_net_cloudapp_net_Echo_ashx_/

jdash failures:
dotnet_corefx/master/outerloop_win7_release 67 win2008-f5ad80 01/15 07:52 AM  0 
dotnet_corefx/master/outerloop_win7_debug 122 win2008-205c60 03/06 08:25 PM  0 

CI machine repro:
```   System.Net.Http.Functional.Tests.PostScenarioTest.PostEmptyContentUsingChunkedEncoding_Success(serverUri: http://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
      Stack Trace:
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Http.Functional.Tests.PostScenarioTest.<PostHelper>d__22.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Net.Http.Functional.Tests.PostScenarioTest.<PostEmptyContentUsingChunkedEncoding_Success>d__11.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         ----- Inner Stack Trace -----
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
            at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by karelz** [comment] 2017-04-17 18:39
Cadence ~1/month, moving to Future.

**Comment by Jiayili1** [comment] 2017-05-02 08:38
Failed again in CI, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/32/testReport/System.Net.Http.Functional.Tests/PostScenarioTest/PostEmptyContentUsingChunkedEncoding_Success_serverUri__http___corefx_net_cloudapp_net_Echo_ashx_/

**Comment by Jiayili1** [comment] 2017-05-03 06:42
This issue is repro on Core Tests in build 20170503.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170503.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PostScenarioTest~2FPostEmptyContentUsingChunkedEncoding_Success(serverUri:%20http:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by steveharter** [comment] 2017-05-03 14:33
Closing this as likely dupe of https://github.com/dotnet/corefx/issues/18869 which was just fixed.

Same scenario: chunked encoding + empty string + win7 (2008)

**Closed by steveharter** 2017-05-03 14:33 UTC
Labels: area-System.Net.Http, blocking-clean-ci, os-windows, test-run-core
