### ISSUE TITLE
 When calling web service in parallel: "The server returned an invalid or unrecognized response"

### ISSUE THREAD

**Issue by SCKlausZ** [dotnet/corefx#24954] opened 2017-10-30 12:23 UTC
Visual Studio 15.3.4
.net core 2.0.0
dotnet-svcutil 0.5.0.0
System.ServiceModel.Http NuGet package 4.4.0

I have created a console app calling a 3rd party web service, using dotnet-svcutil to generate the client.

When I call the server asynchronously in parallel I sometimes get an  
    HttpRequestException: An error occurred while sending the request.
with an inner exception:
    WinHttpException (0x80072F78): The server returned an invalid or unrecognized response
        (NativeErrorCode: 12152)

I can see that it's the HEAD call that fails. Using WireShark I can see that the server returns an HTTP 405 Method Not Allowed, with a body containing a soap envelope with a fault.

If I create a client app in .net framework 4.7, I don't get the error.

I think the server is a self-hosted wcf service - but I'm not sure.

(If I look in System.ServiceModel.Channels.HttpChannelFactory.cs line 996, an exception during the head pre-auth request, should be ignored (but maybe I'm looking in the wrong place).)

**Comment by davidsh** [comment] 2017-10-30 17:07
>I can see that it's the HEAD call that fails. Using WireShark I can see that the server returns an HTTP 405 Method Not Allowed, with a body containing a soap envelope with a fault.

A HEAD request should return an HTTP response that has headers but no body.  If you are getting a response body in the HEAD request, as you indicated above, then the server is violating the RFC.  That is probably why you are getting the exception.

**Comment by SCKlausZ** [comment] 2017-10-30 17:44
@davidsh Thanks for the swift reply. I'll pass the message along to the vendor of the web service, and see if they will change the way they handle the HEAD request.
For now I'll switch to using .net framework instead of .net core.

**Comment by davidsh** [comment] 2017-10-30 17:47
https://tools.ietf.org/html/rfc7231#section-4.3.2

>The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section)....

**Comment by davidsh** [comment] 2017-10-30 17:48
cc: @stephentoub @geoffkizer @karelz

**Comment by davidsh** [comment] 2017-10-30 18:09
>@davidsh Thanks for the swift reply. I'll pass the message along to the vendor of the web service, and see if they will change the way they handle the HEAD request.
For now I'll switch to using .net framework instead of .net core.

From your comment, this appears to be a behavior differences compared w/ .NET Framework.

In .NET Framework, it appears that the response body (which is incorrectly sent by the server) is ignored.  But then that leaves the open, idle, connection unusable for re-use.  .NET Framework routines tests idle connections to make sure they can be re-used for the next request.  Most likely, testing this connection will detect the unread bytes of the response body still left in the TCP channel.  So, at that point, the connection would be closed and a new one opened up for a subsequent request.

WinHttpHandler (via Windows native WinHTTP) appears to be stricter about RFC compliance in this manner. Which is why it is returning an error for this scenario.

**Comment by karelz** [comment] 2017-10-30 19:06
This is something we should have opportunity to relax in ManagedHandler to be compatible with .NET Framework even for "non-compliant servers".

From WinHttpHandler point of view it seems to be by design and there's nothing we can do.

**Comment by davidsh** [comment] 2018-03-22 20:24
Most likely this issue is resolved in .NET Core 2.1 since it uses the new SocketHttpHandler HTTP stack by default.

Please try out the latest .NET Core 2.1 to use the new HTTP stack.  Thx.

**Closed by davidsh** 2018-03-22 20:24 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility

**Comment by SCKlausZ** [comment] 2018-06-15 08:03
I have tested it in 2.1.300 and it's working. Awesome :-)
