### ISSUE TITLE
System.IO.Compression tests need to remove a workaround for not understood DST issue

### ISSUE THREAD

**Issue by FiveTimesTheFun** [dotnet/corefx#1326] opened 2015-04-04 00:49 UTC
The System.IO.Comprssion tests verify the last modified metadata of zip file entries.  There is currently a workaround where the check will succeed if the entry is 1 hour earlier than expected.  This is to work around a not understood DST issue either in the test, or in the library.  I need to understand if the issue is a test or product issue, and fix.

**Comment by Clockwork-Muse** [comment] 2015-04-04 15:38
Ouch.
This has the potential to become a Heisenbug, given DST can change.

**Comment by ianhays** [comment] 2015-11-18 17:19
Heisenbug is putting it lightly. This has been a nightmare to track down. As best as I can discern, the issue is around the way the tests calculate expected LastModifiedTime when adding a file to an archive.

The tests make use of a class "FileData" that explicitly specifies LastModifiedTime using the long constructor. A few of these numbers were incorrect compared to the actual file values, but fixing that issue did not resolve the bug in the OP.

I've got more debugging to go to figure out where the issue is sourced. Marking as "in progress".

**Closed** 2015-12-22 23:50 UTC
Labels: 2 - In Progress, bug, System.IO.Compression
