### ISSUE TITLE
string.Compare function does not work when deployed to linux (.Net Version 2.0)

### ISSUE THREAD

**Issue by ZackTech** [dotnet/corefx#41351] opened 2019-09-26 11:22 UTC
Issue moved from here: https://github.com/aspnet/AspNetCore/issues/14461#event-2664828155
on advice of javiercn 

If you create a .Net Api project on a windows pc then use the following commands:

dotnet restore -r ubuntu.16.04-x64
dotnet build -r ubuntu.16.04-x64
dotnet publish -f netcoreapp2.0 -c Release -r ubuntu.16.04-x64

Then publish onto Ubuntu

Then do:
string myValue = "False";
var resultA = string.Compare(myValue , "false", false);
var resultB = string.Compare(myValue , "false", true);
Both resultA and resultB are equal to -1

I have a work around so this is for information only, so close the bug whenever you want to.
I have not yet got round to upgrading to ,Net Version 3, so I don't know if it is still an issue.

**Comment by stephentoub** [comment] 2019-09-26 13:52
What is the value returned by CultureInfo.CurrentCulture?
What's the value of your LANG environment variable?

**Comment by stephentoub** [comment] 2019-09-26 13:55
> Then publish onto Ubuntu

Are you saying this doesn't happen if you build/publish/run on Ubuntu, only if you build/publish for Ubuntu on Windows and then run on Ubuntu?

**Comment by ZackTech** [comment] 2019-09-26 14:56
On Windows:
 string.Compare(myValue , "false", true) == 0 //Correct
On Ubuntu Linux:
 string.Compare(myValue , "false", true) == 1 //Incorrect

**Comment by ZackTech** [comment] 2019-09-26 14:57
>>
What's the value of your LANG environment variable?
<<

I would love it to be the Queen's English, and would also love to stop waiting time fighting DateTime

**Comment by stephentoub** [comment] 2019-09-26 15:13
> I would love it to be the Queen's English, and would also love to stop waiting time fighting DateTime

I'm not sure how to interpret that.

> On Windows
> On Linux

What about my question, though? When you say On Linux, if you do the build/publish on Linux and then run on Linux, rather than the build/publish on Windows and then run on Linux (as your initial description cites), you still see the "incorrect" behavior, right?

**Comment by ZackTech** [comment] 2019-09-26 15:35
I develop and build the product on Windows. I then publish it to various destinations including our live system which is on a Ubuntu VPS.

I have no idea if creating the project on Linux Machine and publishing to linux makes any difference.
I don't have a Linux dev environment, and don't really want one.

Everything else seems to work, except the string.Compare function.

Having the ability to develop the product on Windows (using visual studio) and deploy to Linux is fantastic, and I would be horrified if things ever started going backwards. The .Net Core is platform independent so it should not care where it is developed or deployed (which certainly seems to be the case for versions 2.0, 2.1, 2.2).

**Comment by stephentoub** [comment] 2019-09-26 18:19
What is the value returned by CultureInfo.CurrentCulture?

What's the value of your LANG environment variable?

**Comment by ZackTech** [comment] 2019-09-26 19:17
CultureInfo.CurrentCulture = en-GB

What's the value of your LANG environment variable? <-- how would I find that out?

Why has the CurrentCulture or LANG environment variable got anything to do with comparing two strings and coming up with the wrong answer?

**Comment by danmosemsft** [comment] 2019-09-26 22:42
> Why has the CurrentCulture or LANG environment variable got anything to do with comparing two strings and coming up with the wrong answer?

@ZackTech when you compare strings with `Compare(String, String, Boolean)` you are getting a culture-sensitive comparison. We are trying to find out what culture it is using when it's on the Ubuntu machine where it's giving the unexpected results. Can you please modify your test app to log the value of `CultureInfo.CurrentCulture` , and also dump the value of the `LANG` environment variable when running on the machine where you are getting the unexpected results?

Or, perhaps you want a culture-independent comparison? If so, you should pass  @`StringCompare.OrdinalIgnoreCase` eg `string.Compare(myValue, "true", StringCompare.OrdinalIgnoreCase)`

**Comment by ZackTech** [comment] 2019-09-27 06:14
So I wrote this test API Function:

[Route("StringComparisonTest")]
        [HttpGet]
        public IEnumerable<string> StringComparisonTest()
        {
            List<string> retVal = new List<string>();
            try
            {
                var current = CultureInfo.CurrentCulture;
                retVal.Add($"Culture = {current}");

                string test = "False";
                int result = string.Compare(test, "false", true);
                retVal.Add($"Test1 = {result.ToString()}");
                result = string.Compare(test, "false", StringComparison.OrdinalIgnoreCase);
                retVal.Add($"Test2 = {result.ToString()}");


            }
            catch (Exception ex)
            {
                retVal.Add(ex.Message);
                return retVal.ToArray();
            }

            return retVal.ToArray();
        }

When I run the API locally on my local windows PC I get:

[
    "Culture = en-GB",
    "Test1 = 0",
    "Test2 = 0"
]

Which is what I would expect

When I run it on the Ubuntu VPS I get:

[
    "Culture = en-US-POSIX",
    "Test1 = -1",
    "Test2 = 0"
]

I am guessing that is what you are expecting?

So is there anything I can add to the Startup.cs so I don't fall into this hole so that when I do:
string.Compare(myValue , "false", true) I get the result I would expect, and dates are in the format of 
day/month/year and not in the bizarre US format of month/day/year.

If there isn't please can you guys create something?

**Comment by Zenexer** [comment] 2019-09-27 17:09
The easiest and perhaps most correct way is to [change the locale on your VPS](https://askubuntu.com/questions/89976/how-do-i-change-the-default-locale-in-ubuntu-server).  Currently you have it set to en-US, but it sounds like you want en-GB.  That won't fix the comparison bug, but it'll fix dates and most other US vs. UK differences you might encounter.

**Comment by Zenexer** [comment] 2019-09-27 17:16
Repro:

``` csharp
using System;
using System.Globalization;
using System.Linq;

namespace Sandbox
{
    public class Program
    {
        public static void Main()
        {
            var cultures = new[]
            {
                "en-GB",
                "en-US-POSIX",
            }.Select(CultureInfo.GetCultureInfoByIetfLanguageTag);

            foreach (var culture in cultures)
            {
                Console.WriteLine("{0}: {1}", culture, string.Compare("Test", "test", true, culture));
            }
        }
    }
}
```

Output:

```
en-GB: 0
en-US-POSIX: -1
```

**Comment by Zenexer** [comment] 2019-09-27 17:19
Of note: https://github.com/dotnet/corefx/blob/61c5e96b70fd14621ec71aee356b1b520696a3c9/src/System.Globalization/tests/System/Globalization/TextInfoTests.cs#L239-L245

Sounds like `en-US-POSIX` isn't capable of ignoring case.  Since `en-US-POSIX` appears to be the default when LANG is en-US, that's probably unexpected behavior.

**Comment by danmosemsft** [comment] 2019-09-27 23:31
@ZackTech what happens if you set your VPS locale to en-GB as suggested above (see https://help.ubuntu.com/community/Locale). Your test program then should emit "en-GB" instead of "en-US-POSIX" and you should get the results you want.

You may have to also set it as the default culture in your site - I am not familiar with how this is done but [this link looks helpful](https://dotnetcoretutorials.com/2017/06/22/request-culture-asp-net-core/)

@tarekgh anything to add?

**Comment by danmosemsft** [comment] 2019-09-27 23:33
> dotnet publish -f netcoreapp2.0 -c Release -r ubuntu.16.04-x64

@ZackTech note that 2.0 is out of support. You can choose 2.1, 2.2, or 3.0 if you want to deploy on a supported version. See https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by tarekgh** [comment] 2019-09-27 23:57
@@ZackTech 

Yes, properly VPS is running with LANG=C.UTF-8 which is translated to en_us_POSIX and that culture doesn't support case insensitive comparison. You need to change the default language either by setting the LANG environment variable to something like en_GB.UTF-8 or you can set CurrentCulture to en-GB in your app. This is the behavior on net core 2.0 and 2.1. We have changed this behavior in 3.0 so C locale is mapped to Invariant culture instead. I recommend you migrate to 3.0. 

Per this information I am closing the issue but feel free to respond back with any question or request. We'll be happy to help more here.

**Closed by tarekgh** 2019-09-27 23:57 UTC
