### ISSUE TITLE
Directory.Move and Directory.Delete ignore the trailing space

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/corefx#26618] opened 2018-01-28 06:20 UTC
```csharp
Directory.Move(@"T:\Temp\aaa", @"T:\Temp\aaa ");
```

Throws an exception:

```
Unhandled Exception: System.IO.IOException: Source and destination path must be different.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at ConsoleApp3.Program.Main(String[] args) in T:\Temp\ConsoleApp3\ConsoleApp3\Program.cs:line 12
```

Also, if I manually create `"T:\Temp\aaa "` (with space), I can't rename it with `Directory.Move` or delete with `Directory.Delete`. It ignores the space, tries to find `"T:\Temp\aaa"` (without space) and throws `System.IO.DirectoryNotFoundException`.

It seems that the core reason lies in `Path.GetFullPath`:

```csharp
Path.GetFullPath(@"T:\Temp\aaa ") // returns "T:\Temp\aaa" (without space)
```

I'm not sure if we could ever fix `Path.GetFullPath` in a backwards-compatible way, but could we at least do something with `Directory.Move` and `Directory.Delete`?

```console
$ dotnet --info
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by ForNeVeR** [comment] 2018-01-28 06:33
Alright, it doesn't seem like it's a .NET bug.

Workaround is to use UNC path:

```csharp
Directory.Move(@"\\?\T:\Temp\aaa", @"\\?\T:\Temp\aaa ");
```

**Comment by danmosemsft** [comment] 2018-01-29 17:59
@JeremyKuhne why do we do GetFullPath here -- it is sprinkled all over Directory.cs for example. What does it do that the OS can't do itself? Seems like another case where we should not be owning normalization?

**Comment by tannergooding** [comment] 2018-01-29 22:26
FYI. @wli3

**Comment by JeremyKuhne** [comment] 2018-01-29 22:28
This is by design. Win32 APIs trim trailing spaces. It's not a good idea to introduce them as many applications will fail to handle the trailing space. You can, of course do so, with device paths `\\?\` (these are _not_ UNCs btw, a UNC in this format is `\\?\UNC\server\share`).

I've written a few blog posts on Windows path formats and how normalization works if you want the nitty-gritty details. Here is one of them: https://blogs.msdn.microsoft.com/jeremykuhne/2016/04/21/path-normalization/

I'm going to close this out, but if you have any questions, don't hesitate to ask.

@danmosemsft We need to normalize in some cases to get resolved paths to do logic like "are these the same path". Even if we didn't, Windows will normalize the path anyway when we call the Win32 layer. The question mark device syntax tells Windows to skip normalization- which we honor as well.

**Closed by JeremyKuhne** 2018-01-29 22:28 UTC
Labels: area-System.IO
