### ISSUE TITLE
Segmentation fault on dotnet [name-of-app].dll on Debian

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#27951] opened 2018-03-11 16:17 UTC
@ChristianHaase commented on [Sun Feb 11 2018](https://github.com/dotnet/core/issues/1266)

Getting segmentation fault when running the application. Only on HTTP client request sending to external API. The app start fine and I can navigate fine, but whenever I try to login _(calling external API)_, I'm getting the segfault. Same goes for creating a new user, when calling the external API from my MVC backend.

Running the app locally, everything works as expected, and I can login fine, as well as creating a new user.

I have a try/catch around the enitre method, but I'm never hitting the catch. The segfault happens instead of the catch.

# Technical details
dotnet --info

    .NET Command Line Tools (1.0.4)
    
    Product Information
      Version: 1.0.4
      Commit SHA-1 hash: afefd

    Runtime Environment
      OS Name: debian
      OS Version: 9
      OS Platform: Linux
      RID: debian.8-x64
      Base Path: /opt/dotnet/sdk/1..4

Is there any fancy way for me te debug, or get some kind of log about what's happenening?

---

@Petermarcu commented on [Tue Feb 20 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367186826)

@leecow is Debian 9 supported by 1.0?

---

@leecow commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367401765)

No, Debian 9 is 2.0. https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md. 

---

@ChristianHaase commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367422860)

I suppose that would explain some issues, but the application runs fine on the server. It's only remote HTTP request that causes the segfault?

---

@wfurt commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367425295)

What version of curl and openssl do you have? This may be same as #24891 and #24552
You can try container with supported OS. That should get you around linkage problems. 

---

@ChristianHaase commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367429887)

@wfurt 

OpenSSL version:
`OpenSSL 1.10f 25 May 2017`

curl version:
`curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3`

I don't know what issues you are referring to (#24891 and #24552)?

---

@wfurt commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367433750)

oh, the link did not work ;( 
https://github.com/dotnet/corefx/issues/24552 and https://github.com/dotnet/corefx/issues/24891 

---

@ChristianHaase commented on [Wed Feb 21 2018](https://github.com/dotnet/core/issues/1266#issuecomment-367448529)

I'm trying to convert my project to .NET core 2.0, and updating the installed version on my server. I will update my progress here once done. Thanks for the inputs.

---

@ChristianHaase commented on [Sat Feb 24 2018](https://github.com/dotnet/core/issues/1266#issuecomment-368251675)

I updated the project to 2.0, but it's still a problem. I'll take a look at the links you provided @wfurt 

---

@ChristianHaase commented on [Sat Feb 24 2018](https://github.com/dotnet/core/issues/1266#issuecomment-368252318)

I looked at the installed version of libcurl, and this is what I could find: 
![libcurl](https://user-images.githubusercontent.com/7237574/36634093-b2b8545c-199f-11e8-93b9-1b161627d681.PNG)

Anything I can do here?

---

@Petermarcu commented on [Sun Mar 11 2018](https://github.com/dotnet/core/issues/1266#issuecomment-372127397)

I'm going to move this to the corefx repo where it will be tracked better.

**Comment by karelz** [comment] 2018-03-12 05:50
Were you able to create minimal repro?
What exactly do you mean by "calling external API"? Are you doing any PInvokes?

**Comment by karelz** [comment] 2018-03-12 05:51
cc @tmds

**Comment by ChristianHaase** [comment] 2018-03-12 08:20
I haven't created a repro no. Bt it should be easy enough.

Basically it's just an HttpClient request, like this:

	var httpClient = new HttpClient();
	var response = await httpClient.GetAsync("some-uri");

I've trying just calling an `HttpGet` to `https.//google.com`. locally on my machine it works fine, but on my remote AWS test server, this throws the segfault.

**Comment by danmosemsft** [comment] 2018-03-13 04:37
Can you run the app under gdb and get a stack trace?

**Comment by ChristianHaase** [comment] 2018-03-13 20:47
That's where my knowledge of linux fails me. GDB is installed on the server, but I'm not sure how to run the application with GDB to get the stacktrace. I managed to create a coredump, but again, no knowledge about how to actually read it.

If you have time to write a short step-by-step guide, I'd be happy to get it done. My apologies :/

**Comment by karelz** [comment] 2018-03-13 21:23
It might be easiest to create a standalone repro we can try locally.
[Quick search](http://web.mit.edu/gnu/doc/html/gdb_8.html) on internet shows `bt` as the right gdb command for stacktraces.

**Comment by leecow** [comment] 2018-03-13 21:47
1.x is not yet supported on Debian 9 and is a part of the effort to get caught up on overall Distro support. I believe the schedule has us all caught up by June / July.

**Comment by ChristianHaase** [comment] 2018-03-14 11:13
I created a repro, but I want to test it myself first. I've installed a local machine with debian 9, if it fails there, I'll send you the repro. If not, I'll test on the AWS debian server, and send you the repro if it fails. I'll get back to you once I've tested myself.

**Comment by ChristianHaase** [comment] 2018-03-14 16:34
[test.zip](https://github.com/dotnet/corefx/files/1812040/test.zip)
Here's an attachment with a simple repro. To make the request, simple press the "Make call" link on the front page, to the left. This is a very simple repro, but basically that's what's causing the segfault (a simple `HttpClient` request). I haven't tested this myself yet, but I might as well dump this here.

**Comment by karelz** [comment] 2018-03-14 17:48
@ChristianHaase can you try to reproduce it outside of ASP.NET? Or is the ASP.NET somehow important for it to repro? Console application with minimal dependencies would be best.
What do you mean by "_I haven't tested this myself yet_"? ... It would be best to wait for a repro you can confirm you can reliably reproduce to avoid wasting time by chasing things which may or may not reproduce.

**Comment by ChristianHaase** [comment] 2018-03-23 14:50
No of course not. I apologize. I'm waiting for my server technician to boot up our test environment so I can test the project. I'll get back to you once I've tested it.

**Comment by karelz** [comment] 2018-05-06 18:59
No repro yet. Closing. If you have a repro, or more details leading to root-cause, feel free to reopen. Thanks!

**Comment by ChristianHaase** [comment] 2018-05-07 12:14
I'm so sorry, we've had problems with our test server. We just got it rebooted yesterday, and I'm working on a repro. I'll make sure to upload the repro, once I've tested it. My apologies.

**Comment by ChristianHaase** [comment] 2018-05-07 17:54
I'm sorry it took so long. I've attached a simple repro that should causes the segmentation fault on my test server. I've attached the project as a .rar to this comment.

[NETCORE_Debian9_Repro.zip](https://github.com/dotnet/corefx/files/1980901/NETCORE_Debian9_Repro.zip)

**Comment by tmds** [comment] 2018-05-07 18:33
@ChristianHaase please try running this on your AWS machine with gdb.

```
$ gdb dotnet
(gdb) r bin/Release/netcoreapp2.0/NETCORE_Debian9_Repro.dll
```

gdb will break when you get a segfault.
Then use the `bt` command to get a stacktrace.

**Comment by ChristianHaase** [comment] 2018-05-07 18:45
Not really giving me anything readable
![image](https://user-images.githubusercontent.com/7237574/39718768-961c1fec-5237-11e8-9c71-5412c176c19e.png)

**Comment by tmds** [comment] 2018-05-07 19:01
@ChristianHaase maybe this gets you further: https://github.com/dotnet/core/issues/973#issuecomment-331416157

**Comment by karelz** [comment] 2018-05-08 07:00
@ChristianHaase try to get symbols. Please post text instead of pictures (they are not searchable)

Just to confirm, your repro seems to contain just this:
```c#
class Program
{
    static void Main()
    {
        using (var client = new System.Net.Http.HttpClient())
        {
            var response = client.GetAsync("https://google.dk");
            var content = response.Result.Content.ReadAsStringAsync();
        }

        System.Console.WriteLine("Hello World!");
    }
}
```

Is that what fails for you? Did you try it on more than 1 machine/VM? Does it fail for you also on latest .NET Core 2.1 RC?
@tmds @wfurt can you please check if it segfaults for you as well?

**Comment by ChristianHaase** [comment] 2018-05-08 07:10
Yes this is the only code the project contains. Every remote http request caused the segfault. What exactly do you mean by "try to get symbols"?

**Comment by tmds** [comment] 2018-05-08 07:17
@karelz the code runs fine on my system. The referenced issue has a similar stacktrace. That issue is solved by uninstalling ssl 1.0.

**Comment by ChristianHaase** [comment] 2018-05-08 15:07
I can confirm that removing the openssl version 1.0.0 does solve the problem, as 1.0.2 already was installed. Many thanks for the support, and I apologize it took so long.

**Comment by shanselman** [comment] 2018-05-17 19:45
`sudo apt-get remove libssl1.0.0` works for me

**Comment by wfurt** [comment] 2018-05-24 22:11
https://github.com/dotnet/corefx/pull/27208

Should we close it now?

**Comment by ChristianHaase** [comment] 2018-05-28 10:10
You may close this

**Comment by karelz** [comment] 2018-05-28 19:15
Thanks for confirmation @ChristianHaase, closing.

**Closed by karelz** 2018-05-28 19:15 UTC
Labels: area-System.Net.Http, needs more info, os-linux, question
