### ISSUE TITLE
Console.ReadLine backspace issue on Linux

### ISSUE THREAD

**Issue by laceous** [dotnet/corefx#37056] opened 2019-04-20 09:12 UTC
.Net Core 2.2

Code:
```
Console.WriteLine("Enter some text.");
string text = Console.ReadLine();
Console.WriteLine(text);
```

Using Konsole, I typed until the text dropped down to a 2nd line (e.g. wordwrap). Then I hit backspace which erased the text on the 2nd line, but then it got stuck at the first column of the 2nd line and never visually erased anything from the 1st line. From the output, it was clearly internally keeping up with my backspace presses, but it wasn't showing it visually which is confusing.

Output:
```
$ dotnet Test.dll 
Enter some text.
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

jjjjjjjjjjjjjjjjjjjj
```

* The Linux terminal doesn't seem to have this issue outside of dotnet
* Running the code via Windows cmd doesn't exhibit this behavior

**Comment by laceous** [comment] 2019-04-21 23:53
The behavior I'm noticing seems equivalent to this:
```
#!/bin/bash
echo Enter some text.
read text
echo $text
```

And here's the behavior I would expect:
```
#!/bin/bash
echo Enter some text.
read -e text
echo $text
```
https://www.gnu.org/software/bash/manual/bashref.html#index-read

**Comment by danmosemsft** [comment] 2019-04-22 00:18
Can you please try 3.0 preview 4? It should be fixed there 

Cc @tmds

**Comment by laceous** [comment] 2019-04-22 00:40
I'm not seeing any difference in behavior with 3.0 preview 4.

I used Visual Studio 2019 to publish a self-contained app, and copied over to Linux. I'm assuming that should hit the test case successfully.

**Comment by danmosemsft** [comment] 2019-04-22 03:11
Maybe I spoke too soon. I was thinking of https://github.com/dotnet/corefx/issues/36761#issuecomment-482810434

**Comment by tmds** [comment] 2019-04-22 07:05
The behavior should be the same before and after recent console changes. How does this behave on Windows?

**Comment by stephentoub** [comment] 2019-04-22 07:41
I've not tried to repro, but I'm assuming the issue is based on this approach to implementing backspace:
https://github.com/dotnet/corefx/blob/b96247e76506e81ff6eb28dd2a14914a59e2a257/src/System.Console/src/System/IO/StdInReader.cs#L144

**Comment by laceous** [comment] 2019-04-23 03:13
Windows:
![windows](https://user-images.githubusercontent.com/2517907/56550614-f2f28780-653a-11e9-8d2d-628906199886.gif)

Linux:
![linux](https://user-images.githubusercontent.com/2517907/56550623-fbe35900-653a-11e9-95ca-cb973181e862.gif)

**Comment by tmds** [comment] 2019-04-23 07:05
@laceous thanks for the screenshots.

> I've not tried to repro, but I'm assuming the issue is based on this approach to implementing backspace:

I think we could maybe replace this with an escape sequence that erases the entire line and rewrites it completely. I haven't tried it yet.

You can assign the issue to me.

**Comment by stephentoub** [comment] 2019-04-23 13:44
Thanks, Tom.

**Comment by laceous** [comment] 2019-04-30 00:27
Follow-up question: Would the fix here handle the following? Or would there be an exposed way to handle this on Linux (if the user drops down to a 2nd line)?
```c#
private static string MaskedReadLine()
{
    StringBuilder sb = new StringBuilder();
    while (true)
    {
        ConsoleKeyInfo cki = Console.ReadKey(true);
        if (cki.Key == ConsoleKey.Enter)
        {
            Console.WriteLine();
            break;
        }
        else if (cki.Key == ConsoleKey.Backspace)
        {
            if (sb.Length > 0)
            {
                sb.Length--;
                Console.Write("\b \b"); //////// this
            }
        }
        else if (!char.IsControl(cki.KeyChar))
        {
            sb.Append(cki.KeyChar);
            Console.Write("*");
        }
    }
    return sb.ToString();
}
```

**Comment by tmds** [comment] 2019-04-30 07:26
> Console.Write("\b \b"); //////// this

When writing `\b` to the terminal, it doesn't move across rows. The fix doesn't change this. It detects when backspace occurs at the start and handles that differently:

https://github.com/dotnet/corefx/blob/12db0eaedeabaf19a77c3432d2918f499f0b2d9e/src/System.Console/src/System/IO/StdInReader.cs#L145-L158

**Comment by laceous** [comment] 2019-05-01 05:57
It looks like if the console changes size then this fix can cause issues. I took a stab at a proposed fix here:

https://gist.github.com/laceous/7f265e1affaef81df06b31a1300bf67d

I used the public APIs, but I believe the logic should be similar.

**Comment by tmds** [comment] 2019-05-01 16:02
> It looks like if the console changes size then this fix can cause issues.

Can you be more specific in what way it can cause issues?

**Comment by laceous** [comment] 2019-05-02 01:35
It's possible that my use of the public APIs is creating different behavior... but here's some things I've seen happen:

![prefix1](https://user-images.githubusercontent.com/2517907/57052494-692e7280-6c3c-11e9-8367-4cd78f316f49.gif)

![prefix2](https://user-images.githubusercontent.com/2517907/57052505-88c59b00-6c3c-11e9-9c51-1210ae4655bf.gif)

My "fix" involves clearing the current lines, and re-writing the string into the new space.

![postfix1](https://user-images.githubusercontent.com/2517907/57052533-b90d3980-6c3c-11e9-8bc5-5b06d0bebf04.gif)

However, it doesn't seem perfect. I've found this one case where a character can get behind the cursor:

![postfix2](https://user-images.githubusercontent.com/2517907/57052542-d9d58f00-6c3c-11e9-8845-07a9ad2abeae.gif)

I also tweaked the code so that if `Console.CursorTop == 0` then we still reset the cursor to the end of the line (when backspace is pressed). This seems to be the behavior of bash's `read -e`

![read_e](https://user-images.githubusercontent.com/2517907/57052596-3afd6280-6c3d-11e9-89ed-72ed36bb492f.gif)

**Comment by tmds** [comment] 2019-05-03 09:05
> but here's some things I've seen happen:

I don't see this when using 'gnome terminal' or 'terminator'. I wonder if it is 'Konsole' specific.

**Comment by laceous** [comment] 2019-05-08 03:19
Yeah, Gnome and Xfce4 terminal seem to behave "correctly".

I think it's related to this Konsole bug: https://bugs.kde.org/show_bug.cgi?id=196998

**Closed** 2019-05-15 16:13 UTC
Labels: area-System.Console
