### ISSUE TITLE
Add IsolatedStorage types

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9842] opened 2016-07-04 23:28 UTC
Bring back System.IO.IsolatedStorage, comprising these types

```
T:System.IO.IsolatedStorage.INormalizeForIsolatedStorage
T:System.IO.IsolatedStorage.IsolatedStorage
T:System.IO.IsolatedStorage.IsolatedStorageException
T:System.IO.IsolatedStorage.IsolatedStorageFile
T:System.IO.IsolatedStorage.IsolatedStorageFileStream
T:System.IO.IsolatedStorage.IsolatedStorageScope
T:System.IO.IsolatedStorage.IsolatedStorageSecurityOptions
T:System.IO.IsolatedStorage.IsolatedStorageSecurityState
```

The most used types are

```
T:System.IO.IsolatedStorage.IsolatedStorageFile
T:System.IO.IsolatedStorage.IsolatedStorageFileStream
```

and members in descending order

```
M:System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(System.String)
M:System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication
M:System.IO.IsolatedStorage.IsolatedStorageFile.DirectoryExists(System.String)
M:System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(System.String)
M:System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
M:System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(System.String,System.IO.FileMode,System.IO.FileAccess)M:System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(System.String)
M:System.IO.IsolatedStorage.IsolatedStorageFileStream.#ctor(System.String,System.IO.FileMode,System.IO.FileAccess,System.IO.IsolatedStorage.IsolatedStorageFile)
M:System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(System.String)
M:System.IO.IsolatedStorage.IsolatedStorageFile.DeleteDirectory(System.String)M:System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForAssembly
```

**Comment by danmosemsft** [comment] 2016-07-04 23:30
@stephentoub, @JeremyKuhne  -- someone was mentioning that IsolatedStorage was likely to be significant work. Can you comment?

I'm guessing the implementation will need specific work for .net native, also, as it has its own concept of isolated storage. Any context?

**Comment by stephentoub** [comment] 2016-07-04 23:48
I could be wrong, but I wouldn't expect it to be *significant*.  At a high level, I expect it would just be reading/writing files on disk, with the main work being the mapping between the selected scope and where on disk we maintain the relevant "isolated" area.  There would likely be features that remain unsupported, but such an implementation should work for both Unix and .NET Native, albeit using different locations for each.  I believe Mono follows a similar approach, and potentially that implementation could be used with some tweaking for .NET Core.

**Comment by ianhays** [comment] 2016-07-06 17:16
We've got an [IsolatedStorage implementation](https://github.com/dotnet/corefx/tree/master/src/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage) in CoreFX but we only build it for netcore50. There's some discussion on adding it to all platforms in https://github.com/dotnet/corefx/issues/5406 (which this is essentially a duplicate of).

In short, I agree with Steve. We can fairly easily provide most of the API xplat, but there isn't going to be the notion of sandboxing that you get on UWP.

**Closed** 2016-09-23 01:36 UTC
Labels: area-System.IO, netstandard2.0

**Comment by niemyjski** [comment] 2016-09-23 01:38
Any reason this was closed

**Comment by stephentoub** [comment] 2016-09-23 01:40
> Any reason this was closed

I expect because @JeremyKuhne merged these:
https://github.com/dotnet/corefx/pull/11080
https://github.com/dotnet/corefx/pull/11868

**Comment by JeremyKuhne** [comment] 2016-09-23 01:42
> Any reason this was closed


>> I expect because @JeremyKuhne merged these:
#11080
#11868

Yes, and we've got separate issues for the remaining work.
