### ISSUE TITLE
System.String.Equals(string value, StringComparison comparisonType) returns false when call with "True".Equals("true", StringComparison.CurrentCultureIgnoreCase) for Fedora 28

### ISSUE THREAD

**Issue by Xambey** [dotnet/corefx#32038] opened 2018-08-30 20:28 UTC
System.String.Equals(string value, StringComparison comparisonType) 

Net Core 2.1.401
x64

section.Value = "True"

Hi, I think I found a bug in this method. Call this method for section.Value = "True", with the value parameter equal to "true" and comparisonType to StringComparison.CurrentCultureIgnoreCase on Fedora 28 (from uname -a Linux localhost.localdomain 4.17.18-200.fc28.x86_64 # 1 SMP Wed Aug 22 19:08:07 UTC 2018 x86_64 x86_64 x86_64 GNU / Linux) returns false (asp net core). Also, I can add that with OriginalIgnoreCase and InvariantCultureIgnoreCase, the method returns true. If you believe the information from my friends, on Ubuntu 16.04 LTS, Windows 7 and 10 the method returns true

![image](https://user-images.githubusercontent.com/17352479/44877150-b15f5480-acab-11e8-893c-3272fd6a5a25.png)

![image](https://user-images.githubusercontent.com/17352479/44877172-ca680580-acab-11e8-997b-d85cdb915089.png)

![image](https://user-images.githubusercontent.com/17352479/44877130-a6a4bf80-acab-11e8-8b1c-9dd6fc8154e2.png)

![image](https://user-images.githubusercontent.com/17352479/44883783-ffcb1e00-acc0-11e8-83d0-c6791a8d52e0.png)

**Environment variables:**

[Text File.txt](https://github.com/dotnet/corefx/files/2337815/Text.File.txt)

**Comment by danmosemsft** [comment] 2018-08-30 22:31
@tarekgh

**Comment by Xambey** [comment] 2018-08-30 22:51
@filipnavara 
![image](https://user-images.githubusercontent.com/17352479/44883569-3a808680-acc0-11e8-8702-dc40ce2237ae.png)

Does the comparison succeed if you use StringComparison.OrdinalIgnoreCase instead? - Yes, with OrdinalIgnoreCase all good (true)

**Comment by Xambey** [comment] 2018-08-30 22:54
![image](https://user-images.githubusercontent.com/17352479/44883727-cabecb80-acc0-11e8-8521-2b6c34e3a16c.png)

**Comment by tarekgh** [comment] 2018-09-05 20:30
@Xambey looks your culture is en_us_posix which is by design (from ICU library) not supporting the casing. you need to change your default locale either on the machine by setting the LANG environment variable or in your app by setting CultureInfo.CurrentCulture. 

you may look at https://github.com/dotnet/corefx/issues/28611 for more info too. 

I am closing this issue but feel free to reply back if you still have any question.

**Closed by tarekgh** 2018-09-05 20:30 UTC
Labels: area-System.Runtime
