### ISSUE TITLE
typeof(RuntimeArgumentHandle) works with .NET Framework, throws with .NET Core

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#33233] opened 2018-11-03 18:21 UTC
Code:

```cs
typeof(RuntimeArgumentHandle).MakeArrayType();
```

Expected:

passes, matching .NET Framework

Actual:
```
      System.Tests.TypeTests.MakeArrayType_Parameterless_ReturnsExpected(type: typeof(System.RuntimeArgumentHandle), expectedType: null) [FAIL]
        System.TypeLoadException : Could not create array type 'System.RuntimeArgumentHandle[]' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
        Stack Trace:
             at System.RuntimeTypeHandle.MakeSZArray(RuntimeTypeHandle handle, ObjectHandleOnStack type)
          /Users/buildagent/agent/_work/147/s/src/System.Private.CoreLib/src/System/RtType.cs(3806,0): at System.RuntimeType.MakeArrayType()
          /Users/hugh/Documents/GitHub/corefx/src/System.Runtime/tests/System/Type/TypeTests.cs(200,0): at System.Tests.TypeTests.MakeArrayType_Parameterless_ReturnsExpected(Type type, Type expectedType)
```

**Comment by svick** [comment] 2018-11-03 18:29
[`RuntimeArgumentHandle` is a `ref struct` on .Net Core](https://github.com/dotnet/coreclr/blob/a81d910/src/System.Private.CoreLib/src/System/RuntimeArgumentHandle.cs) since https://github.com/dotnet/coreclr/pull/15846, so I think this is the expected behavior. (Unless you think `RuntimeArgumentHandle` was marked as `ref struct` incorrectly?)

**Comment by jkotas** [comment] 2018-11-03 20:42
Yes, this is expected. The error message is not very good though. I have submitted PR to fix the error message.

**Closed** 2018-11-03 23:14 UTC
Labels: area-System.Reflection, question
