### ISSUE TITLE
Allow reflection to identify substituted generic types

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#5744] opened 2016-01-27 23:22 UTC
For overload resolution tie breakers Roslyn needs a way to differentiate between a substituted generic and actual type, e.g:

``` C#
class Foo<T>
{
    void Bar(T v);
    void Bar(int v);
}
```

Consider this code:

``` C#
dynamic foo = new Foo<int>();
foo.Bar(2);
```

Notice the use of `dynamic`. This forces the overload resolution to happen at runtime, with reflection being the provider for the type information the C# binder uses.

The goal is to have overload resolution pick the second method, instead of failing. They currently use `MetadataToken` to compare the original definitions. Given this API throws in certain cases now (e.g. CoreRT), it would be better if we could introduce a new APIs.
### Repro

``` C#
class Program
{
    static void Main(string[] args)
    {
        dynamic foo = new Foo<int>();
        foo.Bar(2);
    }

    class Foo<T>
    {
        public void Bar(T v)
        {
            System.Console.WriteLine("generic");
        }

        public void Bar(int v)
        {
            System.Console.WriteLine("not generic");
        }
    }
}
```
- Works on .NET Framework and prints "not generic",
- On .NET Core the behavior is not guaranteed. The late binder will try to get to `MetadataToken` through private reflection and use that, but if that fails - it is not there or throws -- it will will just pick one of the overloads at random.

@VSadov @weshaggard @pallavit

**Comment by pallavit** [comment] 2016-01-28 00:21
@terrajobst As discussed in the review, I don't think this can be done as part of the API convergence (and as you mentioned will require API addition). Assigning it to Ati for future course of action.

**Comment by terrajobst** [comment] 2016-01-28 19:49
Agreed. Wasn't thinking it should be part of it -- just assigned to you :smile:

**Comment by VSadov** [comment] 2016-01-28 20:09
@terrajobst -  the "foo" must be declared as ```dynamic foo = new Foo<int>();```  in the sample.
Static case obviously works fine :-) , but when we come around and need to do similar resolution at run time, there is no API to tell the difference between two Bar methods.

**Comment by VSadov** [comment] 2016-01-28 20:17
repro 
works on desktop and prints "not generic",
on Core the behavior is not guaranteed. We will try to get to MetadataToken through private reflection and use that, but if that fails - it is not there or throws, we will just pick one of the overloads at random.

```
    class Program
    {
        static void Main(string[] args)
        {
            dynamic foo = new Foo<int>();
            foo.Bar(2);
        }

        class Foo<T>
        {
            public void Bar(T v)
            {
                System.Console.WriteLine("generic");
            }

            public void Bar(int v)
            {
                System.Console.WriteLine("not generic");
            }
        }
    }
```

**Comment by terrajobst** [comment] 2016-01-29 02:50
@VSadov 

> the "foo" must be declared as dynamic foo = new Foo<int>(); in the sample.
Static case obviously works fine :-)

Fair point :-) I've updated the sample.

**Comment by karelz** [comment] 2017-02-28 23:54
Dupe of #5884

**Closed by karelz** 2017-02-28 23:54 UTC
Labels: api-needs-work, area-System.Reflection
