### ISSUE TITLE
Sockets ReceiveMessageFrom.Success test failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4172] opened 2015-10-27 14:52 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5657/console
```
System.Net.Sockets.Tests.ReceiveMessageFrom.Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs(100,0): at System.Net.Sockets.Socket.WSARecvMsgBlocking(IntPtr socketHandle, IntPtr msg, Int32& bytesTransferred, IntPtr overlapped, IntPtr completionRoutine)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs(315,0): at System.Net.Sockets.SocketPal.ReceiveMessageFrom(Socket socket, SafeCloseSocket handle, Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, SocketAddress socketAddress, SocketAddress& receiveAddress, IPPacketInformation& ipPacketInformation, Int32& bytesTransferred)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1714,0): at System.Net.Sockets.Socket.ReceiveMessageFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, EndPoint& remoteEP, IPPacketInformation& ipPacketInformation)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\ReceiveMessageFrom.cs(29,0): at System.Net.Sockets.Tests.ReceiveMessageFrom.Success()
```

**Comment by stephentoub** [comment] 2015-10-29 14:52
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5759/console
```
System.Net.Sockets.Tests.ReceiveMessageFrom.Success [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs(100,0): at System.Net.Sockets.Socket.WSARecvMsgBlocking(IntPtr socketHandle, IntPtr msg, Int32& bytesTransferred, IntPtr overlapped, IntPtr completionRoutine)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs(315,0): at System.Net.Sockets.SocketPal.ReceiveMessageFrom(Socket socket, SafeCloseSocket handle, Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, SocketAddress socketAddress, SocketAddress& receiveAddress, IPPacketInformation& ipPacketInformation, Int32& bytesTransferred)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1714,0): at System.Net.Sockets.Socket.ReceiveMessageFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, EndPoint& remoteEP, IPPacketInformation& ipPacketInformation)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\ReceiveMessageFrom.cs(29,0): at 
```

**Comment by CIPop** [comment] 2015-10-30 02:46
This seems to be caused by code diverging from the Desktop original implementation:
The issue appears to be the unification in a single `EnsureDynamicWinsockMethods()` call as well as no check for null before calling the delegate `recvMsg_Blocking`.

See http://referencesource.microsoft.com/#System/net/System/Net/Sockets/_DynamicWinsockMethods.cs,206 for comparison.

@pgavlin PTAL

As decided in the System.Net SCRUM: moving to RC1 since this is a production-code issue.

**Comment by pgavlin** [comment] 2015-11-03 19:56
@CIPop I'm missing the difference between the linked code and the checked-in code. The [code in Socket.Windows.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs#L95) is the same as the original definition of `Socket.WSARecvMsg_Blocking` ([here](http://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,5803)). The same goes for the technique used by `EnsureDynamicWinsockMethods`, which is identical between the code you've linked and the [checked-in code](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/_DynamicWinsockMethods.cs#L173). Is it possible that the call to `LoadDynamicFunctionPointer` is returning `IntPtr.Zero`?

**Comment by pgavlin** [comment] 2015-11-03 20:50
I think that I have a fix for this. In all of the linked code there is an initialization race due to the misordered writes to `_recvMsg` and `_recvMsgBlocking` (along with the lack of appropriate barriers). I'll be sending a PR out soon.

**Comment by SidharthNabar** [comment] 2015-11-03 20:59
Moving to rc2 since the impact is not RC1-blocking

**Comment by CIPop** [comment] 2015-11-03 21:24
> @CIPop I'm missing the difference between the linked code and the checked-in code. 

My apologizes, you're right: I'm not sure why but I thought that `EnsureDynamicWinsockMethods` was somehow replacing `EnsureWSARecvMsg` entirely.

**Closed** 2015-11-03 23:42 UTC
Labels: 2 - In Progress, System.Net
