### ISSUE TITLE
Issue with System.Net.WebClient.Proxy.GetProxy

### ISSUE THREAD

**Issue by MysticRyuujin** [dotnet/corefx#16695] opened 2017-03-04 00:22 UTC
I noticed this bug while working with a Proxy Auto-Config PAC file. Basically, when using GetProxy, if I pass a relative URI (which generates an exception, which can be caught) and then continue on to pass an absolute URI, it stops processing the PAC file.

More details can be found [HERE](https://github.com/PowerShell/PowerShell/issues/3040) which is where I filed the original bug with the PowerShell team, and also [HERE](https://github.com/dotnet/coreclr/issues/9854) as the PowerShell team directed me to CoreCRL, who have since directed me here to CoreFX... I'm hoping this is the right place...

This is assuming the use of a system PAC file such as:
```c#
function FindProxyForURL(url, host) {
    if ( host == "www.msn.com" ) {
        return "PROXY 10.10.10.10";
    }
    else {
        return  "DIRECT";
    }
}
```

Problem code:

```c#
void Main()
{
	System.Net.WebClient client = new System.Net.WebClient();
	Uri uri_absolute = new Uri("http://www.msn.com", System.UriKind.RelativeOrAbsolute);
	Uri uri_relative = new Uri("www.msn.com", System.UriKind.RelativeOrAbsolute);
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
	
	try { client.Proxy.GetProxy(uri_relative); }
	catch { Console.WriteLine("Exception"); }
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
}
```
And the output is:
```
10.10.10.10
Exception
www.msn.com
```

It should be:
```
10.10.10.10
Exception
10.10.10.10
```

**Comment by davidsh** [comment] 2017-03-04 00:48
Copying my response from the original issue filed in CoreCLR:

On Windows, .NET Core and the HTTP stack does not process PAC files itself. The proxy detection and evaluation logic of a PAC file is handled by the operating system (WinHTTP AutoProxy Discover Service). For the default system proxy, we do not know how to map a URI and find it's proxy. That information is hidden in the OS HTTP stack. While we can select the system proxy and use it, it will use the proper proxy for a URI. But we can't retrieve that information.

That means that methods like Proxy.GetProxy(host) don't work when using the system proxy on Windows. The methods do work if you use a custom proxy. But for the system proxy, we "fake" the methods and only use a shim.

**Comment by karelz** [comment] 2017-03-04 03:40
Closing per explanation above. Feel free to reopen if you disagree.

**Comment by MysticRyuujin** [comment] 2017-03-04 19:04
@davidsh @karelz @daxian-dbw - Can someone tell me where I should open the bug report then? I don't understand why "we 'fake it" is an acceptable answer/explanation to a clearly reproducible issue? If it's an issue in the underlying OS (Windows), how would I even go about reporting that?

**Comment by geoffkizer** [comment] 2017-03-04 20:16
Unless I'm missing something , this seems like a regression.

Why can't we port the code from desktop?

It's fine for HttpClient to fake it, but HttpClient is not the only user of this.

**Comment by davidsh** [comment] 2017-03-04 23:09
>Unless I'm missing something , this seems like a regression.

Yes, it is a "regression" from .NET Framework.  The code to handle proxy detection, calculation, evaluation was part of the older managed sockets based HTTP stack from .NET Framework.  We did not port that code.  We use a different HTTP stack per platform based on OS APIs.

>Why can't we port the code from desktop?

We could extract the code, refactor it and get something to work on Windows.  Not sure how it works on Linux without running some APIs that run JavaScript interpretation on the PAC file after it is detected and downloaded.

It is technical work that was not done.  I estimate it is a 4w to 6w work item if we want to have WebProxy able to detect/evaluate "system" proxy settings from the OS.

**Comment by karelz** [comment] 2017-03-05 02:19
OK, based on the comments above, reopening and marking as enhancement.

Next step: Take the Desktop code (e.g. from ReferenceSource: https://github.com/Microsoft/referencesource/tree/master/System/net/System/Net) and port it to CoreFX.

**Comment by karelz** [comment] 2018-03-30 16:43
Duplicate of #26494

**Closed by karelz** 2018-03-30 16:43 UTC
Labels: area-System.Net, enhancement, up-for-grabs
