### ISSUE TITLE
Console app uses 100% cpu when is ran by Process.Start with redirecting input/output

### ISSUE THREAD

**Issue by XiaoFaye** [dotnet/corefx#15709] opened 2017-02-02 01:44 UTC
dotnet core version: 1.0.2
OS: Windows 10 or Ubuntu 16.04 x64

How to replicate the issue:

1. Create a Console app A, which will accept any input and print the length of the input.
2. Publish app A to a folder.
3. Create a Console app B, which uses Process.Start to start app A with RedirectStandardInput and RedirectStandardOutput set to true, In startinfo, filename is dotnet, argument is the main dll name in the app A publish folder. Do not use WaitForExit in app B.
4. App B will exit after starting the app A, app A will still be running in the background and uses 100% of cpu.
5. With RedirectStandardInput and RedirectStandardOutput set to false, it will be all good.

any ideas?

**Comment by karelz** [comment] 2017-02-02 07:01
Can you please provide sample code - it is much easier to reproduce it that way than to follow steps :)

**Comment by XiaoFaye** [comment] 2017-02-02 10:00
Sure,

**Console app A:**

```
    public class Program
    {
        public static void Main(string[] args)
        {
            string result;

            Console.WriteLine("input something...");
            do
            {
                result = Console.ReadLine();
                if (string.IsNullOrEmpty(result))
                    Console.WriteLine("Empty input");
                else
                    Console.WriteLine("Input length: " + result.Length.ToString());
            } while (result != "qqq");
        }
    }
```

**Console app B:**
```
public class Program
    {
        static StreamWriter input;
        public static void Main(string[] args)
        {
            Thread t = new Thread(RunConsole);
            t.IsBackground = true;
            t.Start();

            string result = Console.ReadLine();        
            
            while(result != "qqq")
            {
                input.WriteLine(result);

                result = Console.ReadLine();
            }

            Console.WriteLine("done");
        }

        static void RunConsole()
        {
            var startInfo = new ProcessStartInfo();
            startInfo.RedirectStandardInput = true;
            startInfo.RedirectStandardOutput = true;
            startInfo.FileName = "dotnet";
            startInfo.Arguments = "/home/james/console/ConsoleApp1.dll";
            startInfo.UseShellExecute = false;
            startInfo.CreateNoWindow = true;

            Process process = new Process();
            process.StartInfo = startInfo;

            process.OutputDataReceived += (sender, e) =>
                               {
                                    Console.WriteLine(e.Data);
                               };
            process.Start();
            process.BeginOutputReadLine();
            input = process.StandardInput;

            //process.WaitForExit();
        }
    }
```

**PS:** with or without process.WaitForExit() doesn't make any difference.

While running the **Console app B**, everything works fine, it can send input to **Console app A** and receive output. Once I type "**qqq**" and exit the **Console app B**, the **Console app A** will keep running on the background and use 100% of cpu as below:

![image](https://cloud.githubusercontent.com/assets/6334728/22544648/9bbf13d4-e99a-11e6-9a51-88da5a186bba.png)

**Comment by mellinoe** [comment] 2017-03-02 19:20
As a sanity check since I'm not very familiar with this part of the Linux world (and I expect others might feel the same): is this actually indicative of extreme CPU usage, or could it be a false flag of some sort? I vaguely recall a similar issue, and I thought we determined that the CPU usage meter was not entirely accurate in some scenarios.

**Comment by XiaoFaye** [comment] 2017-03-07 00:49
@mellinoe I can feel the machine becomes very slow, so this is definitely happening.

**Comment by richardhallett** [comment] 2017-03-29 18:39
Unless I'm misunderstanding, I think the actual problem here is the example code just doesn't ever quit the process you start.
In Program B, your while loop is just going to get the input for "qqq", finish the loop and never send that to Program A, so the Program A process will continue running.

The logic could be fixed in various ways, but if you just make sure you send a `input.WriteLine("qqq");` in Program B for example, then Program A does quit and all is well.

If we are to consider why it shoots up CPU usage without fixing the logic, it's probably because the sub process was trying to read from a input pipe that no longer exists, I don't know enough about internals to tell you what happens, but I wouldn't be surprised if it's throwing errors and just not coping.

Side note, you can see this behaviour Windows or Linux, Linux just noticeably the load pops to 100% but again depends on how the internals of the OS handles this.

**Comment by stephentoub** [comment] 2017-04-05 14:42
@richardhallett's analysis looks right to me.  I'm going to close this.  If you continue to have issues here after fixing the bugs in the repro, feel free to reopen. Thanks.

**Closed by stephentoub** 2017-04-05 14:42 UTC
Labels: area-System.Diagnostics.Process, bug
