### ISSUE TITLE
HttpClient unpredictable IDisposable pattern

### ISSUE THREAD

**Issue by joeyj-msft** [dotnet/corefx#37653] opened 2019-05-14 17:26 UTC
HttpClient seems to have a unpredictable IDisposable pattern. When should a consumer dispose of it? When shouldn't they? Why is HttpClient IDisposable when it's not always expected to be "Disposed"? This non-standard usage of IDisposable creates confusion for new users of our tooling/frameworks.

Some more context here: https://github.com/aspnet/Extensions/issues/1710

**Comment by stephentoub** [comment] 2019-05-14 18:55
It should be Dispose'd of when you're done with it, as with any other disposable.

It's also meant to be reused. So if you cache it to use again, don't Dispose of it until you're actually done with it, as above.

**Comment by MikelThief** [comment] 2019-05-14 19:37
There is no unpredictable pattern. By design, pattern is predictable. The scenario of using HttpClient depends on the situation.
If something implements IDisposable this means it may be disposed, not must because there are some reasons against keeping it alive. Stay pragmatic and don't fall to dogmatic side.

**Comment by wfurt** [comment] 2019-05-20 19:52
Is your question answered @joeyj-msft? Should we close this?

**Closed** 2019-05-21 01:19 UTC
Labels: area-System.Net.Http, question
