### ISSUE TITLE
Kestrel throws OutOfMemory exception after listening HTTPS for several hours

### ISSUE THREAD

**Issue by rui-ktei** [dotnet/corefx#30711] opened 2018-06-27 23:50 UTC
Hello, we observe a problem that we suspect it's kestrel's bug. We run asp.net core in containers using AWS ECS.

We use dotnet sdk 2.1.301 to build DLLs and use docker to build image. The Dockerfile looks like this:
```
FROM microsoft/dotnet:2.1.1-runtime-alpine
COPY ./src/My.Service.Api/bin/Release/netcoreapp2.1/publish/ /app
WORKDIR app
EXPOSE 5000
ENTRYPOINT ["dotnet", "My.Service.Apidll"]
```
During the build, we also use `dotnet dev-certs` command to generate a certificate for kestrel to use for HTTPS binding:
```
dotnet dev-certs https -p $TLS_CERT_PASS -ep src/My.Service.Api/bin/Release/netcoreapp2.1/publish/tls-certificate.pfx
```
And in our codebase, we use this file like this:
```
var pfxFilePath = Path.Combine(Directory.GetCurrentDirectory(), "tls-certificate.pfx");
var pfxPassword = GetCertificatePassword().Result;
Console.WriteLine($"Listening on https://*:{portNumber} using certificate {pfxFilePath}");
options.Listen(IPAddress.Any, portNumber, listenOptions =>
{
    listenOptions.UseHttps(pfxFilePath, pfxPassword);
});
```

Now, after we deployed this application and let it run for a night, the container died after a few hours and this is the stack trace we got from CloudWatch. We're using Microsoft.AspNetCore.Server.Kestrel.Https 2.1.1 and all the other aspnet core packages are 2.1.1 as well.
I wonder if this is a bug in kestrel or something we didn't do right?

```


21:20:21
[21:20:21 ERR] Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.

21:20:21
System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.ClosedAdaptedConnection..ctor()

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter..cctor()

21:20:21
--- End of inner exception stack trace ---

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ApplyConnectionAdaptersAsync()

21:20:21
Unhandled Exception: System.AggregateException: One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.) ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.CloseUninitializedConnection()

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.Abort(Exception ex)

21:20:21
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.<>c.<OnConnectionAsync>b__6_1(Exception error, Object state)

21:20:21
at System.IO.Pipelines.PipeCompletionCallbacks.Execute()

21:20:21
--- End of inner exception stack trace ---

21:20:21
at System.IO.Pipelines.PipeCompletionCallbacks.Execute()

21:20:21
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

21:20:21
--- End of stack trace from previous location where exception was thrown ---

21:20:21
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by jkotas** [comment] 2018-06-28 00:20
This is duplicate of https://github.com/dotnet/corefx/issues/30652.

2.1.1-runtime-alpine has bad memory leak. We are close to finding the root caused. 

Please stay on 2.1.0-runtime-alpine in the meantime to workaround it.

**Closed by jkotas** 2018-06-28 00:20 UTC
