### ISSUE TITLE
SendReceive_PartialMessage_Success failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6255] opened 2016-02-19 22:36 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/2534/consoleFull
```
13:13:19      System.Net.WebSockets.Client.Tests.ClientWebSocketTest.SendReceive_PartialMessage_Success(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
13:13:19         System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
13:13:19         Stack Trace:
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:13:19               at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
13:13:19            d:\j\workspace\windows_nt_de---06b7984d\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(475,0): at System.Net.WebSockets.WinHttpWebSocket.<CloseAsync>d__32.MoveNext()
13:13:19            --- End of stack trace from previous location where exception was thrown ---
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
13:13:19            d:\j\workspace\windows_nt_de---06b7984d\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(195,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<SendReceive_PartialMessage_Success>d__16.MoveNext()
13:13:19            --- End of stack trace from previous location where exception was thrown ---
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:13:19            --- End of stack trace from previous location where exception was thrown ---
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:13:19            --- End of stack trace from previous location where exception was thrown ---
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:13:19               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:13:19   Finished:    System.Net.WebSockets.Client.Tests
```

**Comment by davidsh** [comment] 2016-02-19 22:42
`System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response`

Looks like a transient Azure error

**Comment by stephentoub** [comment] 2016-03-25 19:52
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/4014/consoleFull
```
12:39:29      System.Net.WebSockets.Client.Tests.ClientWebSocketTest.SendReceive_PartialMessage_Success(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
12:39:29         System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
12:39:29         Stack Trace:
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:39:29            D:\j\workspace\windows_nt_re---5067c899\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WinHttpWebSocket.cs(458,0): at System.Net.WebSockets.WinHttpWebSocket.<CloseAsync>d__30.MoveNext()
12:39:29            --- End of stack trace from previous location where exception was thrown ---
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:39:29            D:\j\workspace\windows_nt_re---5067c899\src\System.Net.WebSockets.Client\tests\ClientWebSocketTest.cs(195,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTest.<SendReceive_PartialMessage_Success>d__16.MoveNext()
12:39:29            --- End of stack trace from previous location where exception was thrown ---
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:39:29            --- End of stack trace from previous location where exception was thrown ---
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:39:29            --- End of stack trace from previous location where exception was thrown ---
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:39:29               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ericstj** [comment] 2016-04-20 19:05
Failed again here: 
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/221/testReport/junit/System.Net.WebSockets.Client.Tests/ClientWebSocketTest/SendReceive_PartialMessage_Success_server__wss___corefx_net_cloudapp_net_WebSocket_EchoWebSocket_ashx_/

**Comment by CIPop** [comment] 2016-06-16 18:03
Duplicate of #4171.

**Closed by CIPop** 2016-06-16 18:04 UTC
Labels: System.Net
