### ISSUE TITLE
System.IO.Compression.ZipArchiveEntry: Add Crc32 Property

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/corefx#22292] opened 2017-07-15 07:57 UTC
ZipArchiveEntry should get a "Crc" Propery. 

# Rationale and Usage 
ZIP Files are frequently used as a Backup Medium. To rapidly check the ZIP Contents against other File-Copies it would be most efficient to expose the already existing _crc32 Field as a Read-Only Property. 
This would save having to extract and compare File Contents Byte-wise when checking whether a File has different Content. 

# Proposed API-Addition and Implementation: 
```c#
class ZipArchiveEntry
{
    public uint Crc { get }  // return _crc32;
}
```

EDIT: Added code formatting + added class to the API proposal by @karelz

**Comment by danmosemsft** [comment] 2017-08-22 04:27
@ianhays you may have been out when tihs came in. Thoughts? can you give feedback or flip to ready for review, as appropriate

**Comment by ianhays** [comment] 2017-08-22 20:43
This is effectively a duplicate of https://github.com/dotnet/corefx/issues/8610
Here's a request to expose the actual crc32 function (not the zip header property): https://github.com/dotnet/corefx/issues/7745
Here are some requests to expose other header properties: #15599, #12066 and #10223.

Here's my previous comment on exposing extra header fields:
>There are many fields in the ZipArchive header that I would like to see exposed in some manner eventually. I'm a bit hesitant to start exposing them one-by-one as we may end up with a messy API that we wish we could change but can't because of compat. I'd rather we look at the entire Zip header and decide what to expose - and how - all at once. #14853 is one possible way of doing this.

However, I think that crc is something of an exception to that philosophy since we [don't verify it on decompression](https://github.com/dotnet/corefx/issues/8610) and there is otherwise no good way to verify that data loss didn't occur. 

Exposing crc from ZipArchiveEntry wouldn't conflict with #14853 (should we decide to go that route) or any similar major changes since it's a simple field.

So yeah, I'm good with this. The only question is whether the property name should be `Crc` or `Crc32`. I like the latter, personally.

**Comment by danmosemsft** [comment] 2017-08-22 22:13
OK ready for review then

**Comment by karelz** [comment] 2017-09-05 17:50
Approved with name changed to `Crc32` to match the algorithm name (checked on wikipedia :))
```c#
class ZipArchiveEntry
{
    public uint Crc32 { get }
}
```

Note: As noted in #8610, we should not add validation by default (it's a breaking change).

**Comment by danmosemsft** [comment] 2017-09-22 18:28
@SpocWeb any interest in putting up a PR?

**Closed** 2017-12-24 01:55 UTC
Labels: api-approved, area-System.IO.Compression
