### ISSUE TITLE
Weird behavior of C# TcpClient/TcpListener - not read full input prevents sending before connection is closed

### ISSUE THREAD

**Issue by wapac** [dotnet/corefx#13114] opened 2016-10-28 07:57 UTC
I have described the issue I'm having here:
[http://stackoverflow.com/questions/40258230/explain-weird-behavior-of-c-sharp-tcpclient-tcplistener-on-netcore](http://stackoverflow.com/questions/40258230/explain-weird-behavior-of-c-sharp-tcpclient-tcplistener-on-netcore)

I am not sure if this is actually a bug or if it is meant to behave like this, but it is highly unexpected behavior and probably worth looking for someone with greater insight.

**Comment by davidsh** [comment] 2017-02-26 20:51
This is basically by-design.

The stackoverflow link doesn't show the complete repro...it only shows the individual methods for doing writing and reading.  But this exception is being caused by you closing down the writer while the reader still have a pending I/O to read more data.

**Comment by wapac** [comment] 2017-03-01 07:23
I can provide a full code if it is not clear. 

The server side program entry point looks like this:
`    public static void Main(string[] args)
    {
      StartServerAsync().Wait();
    }
`

and similarly, the client looks like this:

`    public static void Main(string[] args)
    {
      StartClientAsync().Wait();
    }

`

But is there really nothing weird in that that running the client for the first time produces no exception and running the second one does? Also it seems that the exception is thrown to the client when it finished the writing operation and it is reading.

In any case, is there any way to avoid that problem? I.e. how to make sure the client will get the message when server wants to end the conversation with a sequence of "send message and close connection".
Thanks!

**Comment by davidsh** [comment] 2017-03-04 04:23
We would need to see the entire Visual Studio solution in order to make any recommendations.

But looking at the code above,  the use of .Wait() in a Main() method can cause deadlocks as well.

cc: @stephentoub who can also provide some guidance around best practices when writing async networking code.

**Comment by stephentoub** [comment] 2017-03-04 05:06
This is a normal entrypoint in a c# app? Using Wait there is fine; you need to block Main from exiting or else the program will end.

**Comment by wapac** [comment] 2017-03-04 08:44
OK, sorry, I thought it is clear on how to reproduce this. So I send the full solution. Once you compile it with MSVS (I used 2015 community edition update 3), you will have ConsoleApp1 and ConsoleApp2 executables. So you run ConsoleApp1 in one shell (I use Windows 10 command line) and then you run ConsoleApp2 in another shell and then you run ConsoleApp2 for the second time.

My questions are:
1) Is this really expected behavior (to me it seems hugely counter-intuitive)?
2) Is there any workaround to make sure the server is able to write a message to a socket, complete that write and then closing it without any other arbitrary waits (like adding await Task.Delay(100) after WriteAsync will solve the problem, but it is probably not what you want). So any workaround that will not include arbitrary delays before closing the socket?

[corefx-issues-13114.zip](https://github.com/dotnet/corefx/files/818492/corefx-issues-13114.zip)

**Comment by wapac** [comment] 2017-03-08 08:41
@davidsh sorry, not sure how this works if the issue is marked as closed, so just in case, I'm pinging you to let you know there is an update

**Comment by stephentoub** [comment] 2017-03-08 12:23
Reopening as a repro was provided...

**Comment by schen381** [comment] 2017-03-30 21:45
@wapac  The short answer is: the behavior is expected, and is by-design.

>But is there really nothing weird in that that running the client for the first time produces no exception and running the second one does?

It has nothing to do with running clients many times. The exception happens because server closes the connection with a RST. This causes the previous sent data from server to client to get aborted as per TCP/IP protocol rules..  The server closes the connection with a RST and not a FIN which is why the client is unable to read the data.  The reason for the server using a RST is explained below.

>In any case, is there any way to avoid that problem? I.e. how to make sure the client will get the message when server wants to end the conversation with a sequence of "send message and close connection".

Yes, make sure the server reads the all data sent by client before closing the socket (i.e. dispose/end of ‘using’ statement).

>Is this really expected behavior (to me it seems hugely counter-intuitive)?

Yes. As per design rules of System.Net.Sockets and TCP/IP protocol, we can only use FIN to close socket if and only if all data has been received first on the socket. Normally, sending a FIN to close the socket will allow data sent by server to client to arrive ok. However, since server chose not to read all available data from client, the server must close the socket with a RST and not a FIN. This causes all kernel buffers to be flushed and the client will most likely not receive all the data previously sent by the server.

In general, there are two ways to close socket connections. One is a “gentle: way, and one is a “rude” way. The gentle way is using FIN packet, and wait for the other host to ACK it to shutdown connection in both directions. The rude way is using RST packet to reset connection and abandon all data, then close the connection. In your case, server choose the rude way to close connection. 

Please see this source code in System.Net.Sockets:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L4657

>Is there any workaround to make sure the server is able to write a message to a socket, complete that write and then closing it without any other arbitrary waits (like adding await Task.Delay(100) after WriteAsync will solve the problem, but it is probably not what you want). So any workaround that will not include arbitrary delays before closing the socket?

Answered above

**Closed by schen381** 2017-03-30 21:45 UTC
Labels: area-System.Net.Sockets, bug
