### ISSUE TITLE
HttpClient error on dnx-coreclr-linux-x64.1.0.0-beta8-15653

### ISSUE THREAD

**Issue by loqix** [dotnet/corefx#3394] opened 2015-09-23 04:11 UTC
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'libcurl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.HttpInitializer.EnsureCurlIsInitialized()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.libcurl..cctor()
   --- End of inner exception stack trace ---
   at Interop.libcurl.curl_version_info(Int32 curlVersionStamp)
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at ConsoleApp1.Program.<Test>d__7.MoveNext()

**Comment by davidsh** [comment] 2015-09-23 04:47
This is a dupe of #2155.

*Nix binaries are NOT yet in NuGet packages so they only contain Windows binaries.  This is planned to be fixed sometime within the next few weeks.

**Comment by kapilash** [comment] 2015-09-23 07:46
Some how, it seems ```System.Net.Http.Native.so``` got missed in the dnx package. Perhaps a temporary issue at the package repo?   

For me (on OSX) it is available at

    $HOME/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta8-15653/bin/System.Net.Http.Native.dylib
    $HOME/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta8-15653/bin/lib/Microsoft.Dnx.Tooling/System.Net.Http.Native.dylib


I could not repro the original problem. The following code works with ```dnx run```

	       using (var handler = new HttpClientHandler())
	       {
		        var client = new HttpClient(handler);
		        HttpResponseMessage response = client.GetAsync("http://httpbin.org/get").Result;
		        string responseText = response.Content.ReadAsStringAsync().Result;
		        Console.WriteLine(responseText);
	       }

where Project.json is

    {
        "version": "1.0.0-*",
        "dependencies": {
        },

          "frameworks" : {
            "dnx451" : { },
            "dnxcore50" : {
                "dependencies": {
                    "System.Console": "4.0.0-beta-*",
		    "System.Net.Http": "4.0.0-beta-*",
		    "System.Collections": "4.0.11-beta-*",
		    "System.IO": "4.0.11-beta-*",
		    "System.IO.UnmanagedMemoryStream": "4.0.1-beta-*",
                }
            }
        }
   }

**Comment by loqix** [comment] 2015-09-24 01:42
This problem is System.Net.Http.Native.so  too old in package, can update it?

**Closed** 2015-10-03 00:32 UTC
Labels: System.Net
