### ISSUE TITLE
System.Runtime.InteropServices.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException failed with 

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21651] opened 2017-06-28 06:30 UTC
This [test](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/GCHandleTests.cs#L85) is failing with: 
```
 System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(value: Object
   { }) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   (No exception was thrown)
```

Note that this only fails for when the parameter is `new object()` ([source code](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/GCHandleTests.cs#L69))

The thing here is that [GCHandleValidatePinnedObject](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/GCHandle.cs#L271) is checking if the type is a valid pinned object, if not it should throw `ArgumentException`

The only explanation here is that [eeType.MightBeBlittable()](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/GCHandle.cs#L286) should return false for object so that it throws but seems to be returning true (not sure this is the case yet). 

Note that for the test input of `object[]` throws correctly, which makes it more weird that if it is an array of object it detects that is not valid pinned object and it throws, contrary to when the value is just a simple object instance it doesn't throw.

cc: @danmosemsft @AtsushiKan

**Comment by hughbe** [comment] 2017-06-28 06:54
Apparently [this is known](https://github.com/dotnet/corert/blob/3004f6d4fdb9cde9c3b57f06f22f8cd89a3c5277/src/System.Private.CoreLib/src/System/Runtime/InteropServices/InteropExtensions.cs#L80-L90)

```
internal static bool MightBeBlittable(this EETypePtr eeType)
{
    //
    // @todo: B#754744 This is used as the Project N equivalent of MethodTable::IsBlittable(). The current implementation is rather... approximate. This
    //     version will err in the direction of declaring things blittable. This is used for the pinned GCHandle validation code where false positives
    //     are the lesser evil (on the grounds that for V1, at least, app developers will almost always be testing IL versions of their apps and will notice
    //     any failures on that platform.)
    //
    return eeType.IsPrimitive ||
            !eeType.HasPointers;
}

```

**Comment by tijoytom** [comment] 2017-06-28 16:54
object returns are blittable  in N , we have other instances of this issues , mostly around argument validation. Moving out of UWP6.0

**Comment by jkotas** [comment] 2017-06-28 18:59
@tijoytom Since this difference by design, shouldn't this test be disabled for uapaot and this issue closed?

**Comment by safern** [comment] 2017-06-28 19:01
I've disabled the test but against this issue. I can update it to be with `[SkipOnTargetFramework]` and close this issue if that is the case.

**Comment by tijoytom** [comment] 2017-06-28 19:02
@safern Please do SkipOnTargetFramework and close the bug

**Comment by safern** [comment] 2017-06-28 19:04
Ok sounds good. Doing now

**Comment by jkotas** [comment] 2017-06-28 19:05
Note that the test is still valid on uapaot for the most port; it is just the object corner case that needs to be disabled.

**Comment by safern** [comment] 2017-06-28 19:05
> Note that the test is still valid on uapaot for the most port; it is just the object corner case that needs to be disabled.

Yes, I will update and split the test.

**Comment by jkotas** [comment] 2017-06-28 19:06
Or maybe just delete it - and declare it as undefined behavior that's not worth testing.

**Comment by MichalStrehovsky** [comment] 2017-06-28 21:00
> Since this difference is by design

Is this really by design? We have failing CoreCLR tests in the CoreRT repo because of this and there are bugs open to get it fixed.

If this is an uninteresting corner case, we should delete the tests (from CoreCLR also).

If not, this test should be marked as blocked on a bug. If we keep disabling tests that are due to bugs without marking them as such, nobody is ever going to find out we need to re-enable something and we just end up with shoddy test coveraget for the AOT platform.

**Comment by tijoytom** [comment] 2017-06-28 21:07
> there are bugs open to get it fixed.
Do you happen to know the bug number?

**Comment by MichalStrehovsky** [comment] 2017-06-28 21:11
> Do you happen to know the bug number?

See comment from @hughbe above: dotnet/corert#2355. There's also a TFS bug I opened some time ago (number in the CoreRT issue).

**Comment by jkotas** [comment] 2017-06-28 22:00
> Since this difference is by design

See my comment https://github.com/dotnet/corefx/pull/21673#discussion_r124659822. @safern is going to delete the test instead.

**Closed** 2017-06-29 04:53 UTC
Labels: area-System.Runtime.InteropServices, test-run-uwp-ilc
