### ISSUE TITLE
InvalidOperationException: Unknown error '3' from string.Normalize

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#9253] opened 2016-06-08 17:22 UTC
CentOS 7
https://github.com/aspnet/Home/issues/1536
```
Unhandled Exception: System.InvalidOperationException: Unknown error '3'.
   at System.StringNormalizationExtensions.IsNormalized(String value, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Server.Kestrel.Http.PathNormalizer.NormalizeToNFC(String path)
```
Windows Docker:
```
System.InvalidOperationException: Unknown error '3'.
   at System.StringNormalizationExtensions.Normalize(String value, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)
```

**Comment by tarekgh** [comment] 2016-06-08 20:05
@joshfree looks the linked issue has some info. I'll take a look.

**Comment by tarekgh** [comment] 2016-06-08 22:16
@Tratcher I have tried running the code you had in the other issue 

```
            var test = "http://0.0.0.0:5001";
            if (!test.IsNormalized(NormalizationForm.FormC))
            {
                test = test.Normalize(NormalizationForm.FormC);
            }
``` 

but I couldn't repro it. I am running on Centos 7.

Could you please provide a code or repro steps?

**Comment by Tratcher** [comment] 2016-06-08 22:29
@nsankaranarayanan? I have not reproduced this myself. How about `string.Empty` or `"/"`?

**Comment by nsankaranarayanan** [comment] 2016-06-08 22:34
I have not tried this with String.Empty or "/" but have reproduced this consistently in Windows Server 2016 Technical Preview 5 and its containers. It works just fine in CentOS 7. I can try later today on the String.Empty.

**Comment by tarekgh** [comment] 2016-06-08 22:39
@nsankaranarayanan could you explain more what exactly you are seeing when producing the issue? are you getting the following exception?

```
Unhandled Exception: System.InvalidOperationException: Unknown error '3'.
   at System.StringNormalizationExtensions.IsNormalized(String value, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Server.Kestrel.Http.PathNormalizer.NormalizeToNFC(String path)
```

I cannot reproduce the issue on Windows either but I am not running on Server 2016. 

it'll be good if you can provide a full repro steps so I can help with this issue.

**Comment by nsankaranarayanan** [comment] 2016-06-08 23:20
I just went and retraced all my steps for you @tarekgh. Here are the steps at a high level.

1. Yank the code from the git repository.
2. Copy the code to a temporary folder C:\Temp\Apps\DockerTest1
3. Create a docker container using the following command 
        `docker run --rm -it -p 5001:5001 -v C:\Temp:C:\Temp microsoft/iis:windowsservercore cmd`
4. Within the docker container, navigate to my folder "cd temp\Apps\DockerTest1"
5. Within the docker container, restore the packages
6. Within the docker container, run using the dotnet.exe to call the entry point.

Please see attached output.txt for all the steps. The one step that is missing in the output is the actual docker command and here it is. Keep in mind that I have already yanked the .net SDK preview 1 and the docker image microsoft/iis in the past and they are not part of the output.

Hope this helps.

`docker run --rm -it -p 5001:5001 -v C:\Temp:C:\Temp microsoft/iis:windowsservercore cmd`

[output.txt](https://github.com/dotnet/corefx/files/305870/output.txt)

**Comment by Tratcher** [comment] 2016-06-08 23:33
Ah, containers have a known issue for this in TFS (5681693) that has already been fixed.

**Comment by tarekgh** [comment] 2016-06-08 23:40
@Tratcher does this means we can close this issue?

**Comment by tarekgh** [comment] 2016-06-09 15:51
@Tratcher could you please advise if this issue is already fixed or I need to look more?

**Closed** 2016-06-09 17:31 UTC
Labels: bug, os-centos, System.Globalization

**Comment by timdows** [comment] 2016-09-06 15:27
@tarekgh 
Got it a couple of days ago as well, I was able to reproduce it (See attached document for the steps) on Windows Server 2016 Technical Preview 5

Note that the project is netcoreapp1.0, I could not reproduce this with the net461 framework

The error is the same:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unknown error '3'.
System.InvalidOperationException: Unknown error '3'.
   at System.StringNormalizationExtensions.IsNormalized(String strInput, NormalizationForm normalizationForm)
   at WebApplication17.Controllers.HomeController.About() in C:\Dev\Test\WebApplication17\Controllers\HomeController.cs:line 20
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Docker version

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64
```

Docker info
```
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 40
Server Version: 1.12.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1021 MiB
Name: CIPJDocker001
ID: QR7B:D3HU:GUO7:2Y32:ZHQ7:S2SQ:NS2K:ACJK:47YI:7S5W:KKYW:UL4N
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

[repro9253.docx](https://github.com/dotnet/corefx/files/457044/repro9253.docx)

**Comment by PatrickLang** [comment] 2016-09-06 15:55
The Windows issue is fixed in builds after Windows Server 2016 TP5. If you reboot the host, the code should work again. I would consider it solved and close this unless the Centos issue still exists

**Comment by tarekgh** [comment] 2016-09-06 16:11
I'll ignore this issue till someone confirm if still there still any problem.

**Comment by timdows** [comment] 2016-09-06 19:38
This issue could indeed be solved by updating Windows 2016 TP5 via sconfig and rebooting
![2016-09-06 20_11_34](https://cloud.githubusercontent.com/assets/9577532/18287440/73909632-7477-11e6-8c7a-347c0216ebec.png)
