### ISSUE TITLE
System.Diagnostics.Tests.ProcessWaitingTests.WaitForPeerProcess failed in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17220] opened 2017-03-17 06:05 UTC
Configuration: OuterLoop_Fedora24_debug ([build#119](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/119/testReport/))

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora24_debug/119/testReport/System.Diagnostics.Tests/ProcessWaitingTests/WaitForPeerProcess/

~~~
MESSAGE:
Assert.Equal() Failure\nExpected: Signal\nActual: (null)
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Tests.ProcessWaitingTests.WaitForPeerProcess() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_fedora24_debug/src/System.Diagnostics.Process/tests/ProcessWaitingTests.cs:line 157
~~~

**Comment by krwq** [comment] 2017-04-12 22:28
I tried this on Mint, bash for windows and it is not reproing. I'm doing some stress testing on this right now (multiple threads, running in a loop) - if it doesn't fail I'll close as no repro and we can reopen if new data comes in.

**Comment by krwq** [comment] 2017-04-12 23:22
I was not able to get this particular issue. I've run this around 15k times and seeing to types of failures:
- timeout - expected considering amount of resource this test is producing
- This one is suspicious though:
```
        ---- Assert.Equal() Failure
        Expected: 42
        Actual:   137
```

I believe this is coming from: `Assert.Equal(SuccessExitCode, child2.ExitCode);`

**Comment by stephentoub** [comment] 2017-04-12 23:48
> This one is suspicious though

Exit code 137 is almost certainly a seg fault.  Do you see any output earlier in the run that would confirm that the child process is crashing?

**Comment by krwq** [comment] 2017-04-13 01:44
@stephentoub I'll try to collect the output tomorrow, I do not recall seeing it but that could be caused by the fact that I've run the test in the thread.

I do not believe threads are needed to repro so I'll either get the output or will add some diagnostics.

Will also verify if this Linux specific or any platform.

**Comment by stephentoub** [comment] 2017-04-13 02:19
Oops, I was thinking of 139. 137 is most likely SIGKILL, meaning something terminated the process.

**Comment by krwq** [comment] 2017-04-13 17:53
@stephentoub:
- there is no output,
- linux specific (for sure repros on Mint, on Windows I kept looping it for a while and no repro)
- threads are not necessary for repro - running around 3k times repros every time for me

I do not have much expertise debugging .NET from the command line or with S.D.Process.

**Comment by krwq** [comment] 2017-04-13 23:09
Ok, I will stop working on this right now since I have spent too much on this and not getting too much progress.

One of the suspects was that constant used in the lambda which is run on the remote thread was not propagated correctly (WaitInMS) - after hardcoding value in all of the places it was still failing.

My current suspect is that WaitForExit is not working correctly and prematurely kills the process from time to time. (possibly not waiting at all)

Few things I've noted:
- every time the failure happens the process ids of both child processes have Ids with really close values (in each case I checked diff was 1)
- average single test execution time on my box was 330+- 20 ms on my box - just before the failure it was 240ms
- child2.WaitForExit(WaitInMS) just before failure returns pretty much immediately (< 0.05ms) - in any other case it takes at least 120ms - that means the process is already killed
- there is no StdErr or StdOut on child2 (I've added additional logic to verify that)

There is too many pieces here and repro feedback is super slow (waiting usually at least 10min after each change) - would be better if someone who knows PAL for S.D.Process debugs this. I'll prioritize simpler issues over this, I find this issue interesting so I can come back to it later if needed.

It would be likely useful to figure out which Kill kills the thread

**Comment by Jiayili1** [comment] 2017-04-20 09:18
This issue is repro on innerloop_netcoreapp_fedora24_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/fedora24_debug/2020/testReport/System.Diagnostics.Tests/ProcessWaitingTests/WaitForPeerProcess/

**Comment by krwq** [comment] 2017-04-20 17:06
```
     System.Diagnostics.Tests.ProcessWaitingTests.WaitForPeerProcess [FAIL]
        Assert.Equal() Failure
        Expected: Signal
        Actual:   (null)
...
/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/Tools/tests.targets(326,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/bin/Unix.AnyCPU.Debug/System.Diagnostics.Process.Tests/netstandard/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
```

dumpling seems to has failed to download
```
  Traceback (most recent call last):
    File "dumpling.py", line 18, in <module>
      import requests
  ImportError: No module named requests
  python: can't open file '/mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/tempHome/.dumpling/dumpling.py': [Errno 2] No such file or directory
  executing ulimit -c unlimited
  command exited with ExitCode: 1
  command failed, trying to collect dumps
  corefile:
  no coredump file was found
  /mnt/resource/j/workspace/dotnet_corefx/master/fedora24_debug/src/System.Diagnostics.Process/tests
  Finished running tests. End time=23:03:27. Return value was 1
```

**Comment by mellinoe** [comment] 2017-04-20 18:08
It looks like the Fedora images are missing one of the python prerequisites. It doesn't seem related to the test failure here. I will fix the image, though.

**Comment by krwq** [comment] 2017-04-20 18:28
@mellinoe what about the multiple "Dumpling not found, installing..."? Are we trying to install dumpling per test?

**Comment by mellinoe** [comment] 2017-04-20 18:34
Every installation is failing (because one of the pre-reqs is missing), so that's why the message shows up over and over.

**Comment by danmosemsft** [comment] 2017-05-08 17:06
@mellinoe did you fix the prereq?
@krwq do you have cycles to pick this up before Wed? If so please assign to yourself.

**Comment by krwq** [comment] 2017-05-08 17:38
@danmosemsft - I can't 100% sure say I'll have cycles before Wed

**Comment by danmosemsft** [comment] 2017-05-09 17:59
@Priya91 do you have time to take this one?

**Comment by Priya91** [comment] 2017-05-09 18:26
@danmosemsft Yes, i'm looking at this next

**Comment by Priya91** [comment] 2017-05-10 23:01
I was able to repro this locally when i ran the tests in parallel for 1000 counts for a long time, at which point the processes were being killed due to resource constraint. Was not able to repro without OOM, and it's difficult to understand why only on fedora. Could it be the case that the standardoutput gets a \n or a \r first and then the "signal" console output, so when using readline, we get the first line.

**Comment by Priya91** [comment] 2017-05-10 23:10
Although when i just ran this test in loop, there were no failures, but when run with the other tests in the lib, the repro is available. Looks like some other test is interfering.

**Comment by krwq** [comment] 2017-05-10 23:11
@Priya91 did you get the stack in the original report or the one which I got locally? My repro was the same test in multiple threads

**Comment by Priya91** [comment] 2017-05-11 00:16
I got the initial stack of expected signal, actual null.

**Closed** 2017-05-11 03:06 UTC
Labels: area-System.Diagnostics.Process, blocking-clean-ci, test-run-core
