### ISSUE TITLE
The name 'fontFamily' and 'fontSize' do not exist in the current context

### ISSUE THREAD

**Issue by RussKie** [dotnet/corefx#38130] opened 2019-05-31 06:51 UTC
* .NET Core Version: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**

I speculate, but it looks like a debugger visualiser for `Font` may be broken - it expect `familyFont` and `fontSize` which are absent.
I don't believe it is a WinForms issue per se, but I was unable to trace the source of the issue.

**Actual behavior:** 

While testing dotnet/winforms#656 I observed the following:
![image](https://user-images.githubusercontent.com/4403806/58685493-48824580-83bf-11e9-8acd-273552e7f372.png)

Calling `ToString()` produces the expected result:
![image](https://user-images.githubusercontent.com/4403806/58686837-4ae69e80-83c3-11e9-94b2-d3ff19849d44.png)

**Expected behavior:**

The debugger should correct display the font name.

**Minimal repro:**

1. Set a breakpoint in `Font_SetWithHandler_CallsFontChanged` 
2. Debug the test
3. Check the value of `SystemFonts.MenuFont`

**Comment by danmosemsft** [comment] 2019-06-01 01:27
This is a puzzle. I don't see a debugger visualizer. It's not quite the output of `Font.ToString()`. It's not quite the output of `FontConverter.ConvertTo(...typeof(string))` ...

**Comment by danmosemsft** [comment] 2019-06-01 01:28
```c#
Font f = SystemFonts.CaptionFont;
FontConverter fc = new FontConverter();
((FontConverter)fc).ConvertTo(null, System.Globalization.CultureInfo.CurrentCulture, f, typeof(string))
```
`"Segoe UI, 9pt"`

**Comment by danmosemsft** [comment] 2019-06-01 01:29
@ericstj any idea? Some special IDE magic?

**Comment by RussKie** [comment] 2019-06-01 01:30
There must be something else, visualisers can be applied at various levels

**Comment by RussKie** [comment] 2019-06-05 10:59
Looks like the `Brush` object is suffering from the similar symptom:
![image](https://user-images.githubusercontent.com/4403806/58951565-c8038080-87d4-11e9-84b0-cc779686b38c.png)

**Comment by ericstj** [comment] 2019-06-05 13:23
Sorry for delay. Let me see if I can find it.

**Comment by ericstj** [comment] 2019-06-05 15:37
Looks like these are coming from autoexp.dll in VS.  @r-ramesh it looks like you may be the current owner, can you take a look here?  That file should be updated to not rely on private fields.
https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fcsharp%2Fautoexp%2Fautoexp.cs&version=GBmaster&_a=contents&line=28&lineStyle=plain&lineEnd=29&lineStartColumn=18&lineEndColumn=99

I also see some other issues with attributes defined here relying on private fields.

**Comment by danmosemsft** [comment] 2019-06-05 15:41
Whoa. That's an interesting file. Why doesn't it defer to debugger attributes on the type itself? Those will be maintained and issues like this wouldn't occur.

**Comment by ericstj** [comment] 2019-06-05 15:44
Yeah, I'm filing an issue i VS repo and we can hopefully get some clarity on this.  I also see many public copies of this file.  It looks like VS may have redistributed it at some point.

**Comment by ericstj** [comment] 2019-06-05 15:57
@danmosemsft we can test to see what the debugger prefers, not sure anyone has done that yet.  Perhaps if it prefers an attribute on the type we could add one to fix this.

**Comment by r-ramesh** [comment] 2019-06-05 16:35
@ericstj Can the expression be written using public properties/fields (and will such an expression work for previous versions?) If so, feel free to go ahead and edit the autoexp.cs.
The DebuggerDisplay can be defined inline above the type or in a separate assembly (such as autoexp), but looking through the debugger code it looks like the precedence is autoexp > what is defined inline (which makes sense if one wants to override and provide a custom display for a type?).

**Comment by danmosemsft** [comment] 2019-06-05 18:36
@r-ramesh do you feel like that order of precedence is appropriate for types in the platform itself? I would like to improve our types to have better DebuggerDisplay attributes but if I understand right, that would have no effect.

Presumably we need them in this file for .NET Framework, even if they existed on .NET Core versions of the types.

**Comment by r-ramesh** [comment] 2019-06-05 20:41
@danmosemsft That would be a design change that impacts much more than just this Font scenario. Is there a backward compatible way to write the debugger display using public fields/properties?

**Comment by danmosemsft** [comment] 2019-06-05 23:09
@r-ramesh this should do it. Several changed.
```
[assembly: DebuggerDisplay(@"\{Name = {Name} Size={Size}}", Target = typeof(Font))]
[assembly: DebuggerDisplay(@"\{Name = {Name}}", Target = typeof(FontFamily))]
[assembly: DebuggerDisplay(@"\{Color = {Color}}", Target = typeof(Pen))]
[assembly: DebuggerDisplay(@"\{X = {X} Y = {Y}}", Target = typeof(Point))]
[assembly: DebuggerDisplay(@"\{X = {X} Y = {Y}}", Target = typeof(PointF))]
[assembly: DebuggerDisplay(@"\{X = {X} Y = {Y} Width = {Width} Height = {Height}}", Target = typeof(Rectangle))]
[assembly: DebuggerDisplay(@"\{X = {X} Y = {Y} Width = {Width} Height = {height}}", Target = typeof(RectangleF))]
[assembly: DebuggerDisplay(@"\{Width = {Width} Height = {Height}}", Target = typeof(Size))]
[assembly: DebuggerDisplay(@"\{Width = {Width} Height = {Height}}", Target = typeof(SizeF))]
[assembly: DebuggerDisplay(@"\{Color = {Color}}", Target = typeof(SolidBrush))]
```

**Comment by ericstj** [comment] 2019-06-05 23:50
@RussKie you or someone else from WinFroms may want to look at the other values in this file.  I see plenty of visualizers for WinForms types that rely on private fields here too.
https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fcsharp%2Fautoexp%2Fautoexp.cs&version=GBmaster&line=58&lineStyle=plain&lineEnd=91&lineStartColumn=1&lineEndColumn=122

**Comment by RussKie** [comment] 2019-06-06 01:20
We'll do a review, thank you

**Comment by weltkante** [comment] 2019-06-06 07:52
I wonder what takes priority if visualizers are defined both in .NET Core assemblies and in the VS extension. If the defining assembly takes precedence then you could just add the corrected attributes in .NET Core and leave the VS extension in place for Desktop Framework.

**Comment by r-ramesh** [comment] 2019-06-06 15:26
@danmosemsft 
You can make the changes here (you can do it in the web UI itself) and create a PR against the same branch:
https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fcsharp%2Fautoexp%2Fautoexp.cs&version=GBteam%2Fdebugger%2Fd16.2stg

**Comment by ericstj** [comment] 2019-06-06 16:07
@weltkante see https://github.com/dotnet/corefx/issues/38130#issuecomment-499160228.  I confirmed the behavior described by @r-ramesh in the debugger after changing System.Drawing.Common so we do require changes to VS to fix this.

**Comment by danmosemsft** [comment] 2019-06-07 18:25
@r-ramesh done https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/185456?_a=overview

**Comment by RussKie** [comment] 2019-06-08 02:19
Thank you.
Is it reasonable to expect changes that would allow us decorate types the visualiser attributes in containing assemblies, and those decoration would take precedence over those declared in VS assemblies?

**Comment by ericstj** [comment] 2019-06-08 15:16
No.  You need to update the VS assembly.  Debugger is **not changing** precedence.

**Comment by danmosemsft** [comment] 2019-06-11 19:54
This was fixed in VS.

**Closed by danmosemsft** 2019-06-11 19:54 UTC
Labels: area-System.Drawing, bug
