### ISSUE TITLE
Tests that block and use TaskScheduler.Current can cause a deadlock

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#387] opened 2015-01-09 23:04 UTC
See #308 for some discussion around a particular instance of this issue.

It seems that in the particular test execution environment we are using currently, there can be a deadlock on single-core machines when using heavily-threaded code using TaskCreationOptions.LongRunning, and also probably when explicitly creating Thread objects. There may be an issue in the CLR test host, the xUnit test runner, some part of the library code, or some specific interaction between those components.

Given that the current root cause is unclear at this point, I'm simply creating this issue in order to track and compile information / repro's of this bug.

**Comment by stephentoub** [comment] 2015-01-15 17:40
We now believe we understand the problem here, and it actually isn't to do with LongRunning.

The issue is related to how the tests are written in combination with xunit's usage of a TaskScheduler or SynchronizationContext to limit the concurrency level.  xunit schedules the invocation of the tests to a scheduler/context it sets up with a fixed number of workers in it (based on the set concurrency level).  If a test running on that scheduler itself queues some work to run on the same scheduler and then blocks in some manner waiting for that work to complete, a deadlock can occur, and almost certainly will occur if there's only one worker in the scheduler (it can still happen with more workers, it's just less likely).  So, for example, if a test running on a scheduler with one worker does Task.Factory.StartNew(() => { ... }) and then subsequently Wait()'s for that task to complete, synchronously blocking, the test will likely deadlock... this is because Task.Factory.StartNew schedules to TaskScheduler.Current unless a scheduler is provided to override that.(see [this](http://blogs.msdn.com/b/pfxteam/archive/2011/10/24/10229468.aspx) and [this](http://blogs.msdn.com/b/pfxteam/archive/2012/09/22/new-taskcreationoptions-and-taskcontinuationoptions-in-net-4-5.aspx) for some more background).

As such, especially if a test is going to synchronously block, tests should try to schedule tasks to TaskScheduler.Default rather than TaskScheduler.Current.  This can be done, for example, by using Task.Run instead of Task.Factory.StartNew (if none of the extra configuration available through StartNew is needed), by explicitly passing TaskScheduler.Default to methods like StartNew or ContinueWith, to use .ConfigureAwait(false) when awaiting tasks in async helper methods used by synchronous test methods, etc.

**Comment by stephentoub** [comment] 2015-01-31 15:22
As of #563, this should be fixed in all of the tests.  A change made to xunit (https://github.com/xunit/xunit/commit/2f2efc5be1be468a3efe72ff5faa858b9f99926a) will also help to ensure such issues don't manifest in the future, should any additional usages sneak in.

**Closed by stephentoub** 2015-01-31 15:22 UTC
Labels: test bug
