### ISSUE TITLE
Enhance SqlClientDiagnosticListener to support SqlTransaction 

### ISSUE THREAD

**Issue by fitzchak** [dotnet/corefx#13034] opened 2016-10-26 09:30 UTC
It will be great if SqlTransaction will output tracing info about Commit, Rollback and Dispose as SqlConnection and SqlCommand have tracing info about connection open/close and command executing/executed.

**Comment by karelz** [comment] 2016-10-26 15:40
Do you have suggestion how to do that?
cc: @saurabh500

**Comment by saurabh500** [comment] 2016-10-26 18:13
@fitzchak 
>> SqlConnection and SqlCommand have tracing info about connection open/close

For SqlCommand which APIs are you talking about, w.r.t. tracing ?

**Comment by saurabh500** [comment] 2016-10-26 18:14
@karelz  this is an enhancement request.

**Comment by karelz** [comment] 2016-10-26 18:23
@saurabh500 mark it so :)

**Comment by saurabh500** [comment] 2016-10-26 18:25
@fitzchak I just realized that you are talking about `SqlClientDiagnosticListener` which was added to .Net core by @tstringer 
We can look into this when we work on SqlTransaction support for .Net core.

**Comment by fitzchak** [comment] 2016-10-27 08:06
@karelz I'll add the trace statements where we need them and will show you.
For now, I'm not able to compile the (solution)[https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/System.Data.SqlClient.sln]. 
Can you point me to the guide how to do that?

**Comment by karelz** [comment] 2016-10-27 16:09
> We can look into this when we work on SqlTransaction support for .Net core. 

@saurabh500 does it mean the code is not there today?
If the bug is about code which does not exist yet, I think we should close it for now (or make it dependend on "bring the code in" bug).
If the issue is about existing code, and it is reasonable for contributors to tackle it (i.e. it does not require deep internal knowledge), please mark it as "up for grabs" with brief guidance on what is needed where -- @fitzchak might want to grab it :).

**Comment by saurabh500** [comment] 2016-10-27 16:57
@fitzchak I can mark this as up for grabs and I would be glad to see the changes come in for the SqlTransaction type.

**Comment by saurabh500** [comment] 2016-10-27 16:59
@fitzchak 
>>For now, I'm not able to compile the solution. 

You should first compile the .Net core  completely and then you can compile each project iteratively by doing an msbuild from the folder that has the csproj file.

More building instructions at https://github.com/dotnet/corefx/tree/master/Documentation/building

**Comment by karelz** [comment] 2016-10-27 18:33
@fitzchak can you please confirm you are working on the issue? We should assign it to you in such case ...

**Comment by fitzchak** [comment] 2016-10-30 11:53
@saurabh500 I opened an issue about the error I'm getting: https://github.com/dotnet/corefx/issues/13159

@karelz Sure, I'm working on it.

**Closed** 2016-11-07 21:36 UTC
Labels: area-System.Data.SqlClient, enhancement, up for grabs

**Comment by karelz** [comment] 2016-11-07 22:36
Thanks for helping out @fitzchak!
