### ISSUE TITLE
Directory.EnumerateFiles and Directory.GetFiles recursive ignores folders starting with period

### ISSUE THREAD

**Issue by JasonJShuler** [dotnet/corefx#31612] opened 2018-08-06 15:05 UTC
In .NET Core 2.1, Directory.EnumerateFiles and Directory.GetFiles when run with the EnumerationOptions.RecurseSubdirectories = true does not look in folders that start with a period.

To repeat, run at command line: 
```batch
mkdir c:\test
echo "" > c:\test\file1.txt
mkdir c:\test\.foo
echo "" > c:\test\.foo\file2.txt
```

Then in c# do the following:

```csharp
var files = Directory.GetFiles("c:\\test", "*", new EnumerationOptions() { RecurseSubdirectories = true });
```

files should contain both file1 and file2, but only file1 is returned.

**Comment by JasonJShuler** [comment] 2018-08-06 15:30
Here is my workaround

`        public static IEnumerable<string> EnumerateFilesRecursive(string path)
        {
            foreach (var file in Directory.EnumerateFiles(path))
            {
                yield return file;
            }

            foreach (var subDir in Directory.EnumerateDirectories(path))
            {
                foreach (var subFile in EnumerateFilesRecursive(subDir))
                {
                    yield return subFile;
                }
            }
        }`

**Comment by vcsjones** [comment] 2018-08-07 14:19
>In .NET Core 2.1, Directory.EnumerateFiles and Directory.GetFiles when run with the EnumerationOptions.RecurseSubdirectories = true does not look in folders that start with a period.

Did this behavior change from 2.0?

**Comment by JasonJShuler** [comment] 2018-08-07 16:16
Unsure, I have not tested it in prior versions

**Comment by vcsjones** [comment] 2018-08-07 19:59
Looking more carefully at your example:

>mkdir c:\test
>mkdir c:\test.foo

Did you mean "C:\test\\.foo" in your second example? I looks like GitHub might have eaten your directory separator there.

**Comment by vcsjones** [comment] 2018-08-08 20:33
@JasonJShuler 

I'm not observing this behavior. Given this program:

```csharp
using System;
using System.IO;

namespace scratch {
    public class Scratch {
        static void Main() {
            var files = Directory.EnumerateFiles(@"C:\test", "*", new EnumerationOptions { RecurseSubdirectories = true });
            foreach(var file in files) {
                Console.WriteLine(file);
            }
        }
    }
}
```

I get the following output:

![image](https://user-images.githubusercontent.com/361677/43862718-7a82f776-9b28-11e8-8322-51dedeeae32e.png)

Can you describe more about your environment? The version and name of your operation system and the output of `dotnet --info` from the command prompt?

**Comment by JasonJShuler** [comment] 2018-08-08 22:07
... so I'm not sure what happened, but I'm getting the same result as you now.

Specifically I'm having an issue with the .git folder in a local git repository. The folder shows up gray in windows explorer, but when you check the properties Hidden is not checked. However attrib shows it as hidden...

So it seems I was wrong - it is ignoring hidden folders. Is this the expected behavior? (I did try using the include special folders to no avail)

**Comment by danmosemsft** [comment] 2018-08-10 09:39
@jeremykuhne

**Comment by JeremyKuhne** [comment] 2018-08-10 17:54
It is by design that we skip hidden and system if you don't specify otherwise when creating `EnumerationOptions`: https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/EnumerationOptions.cs#L30

We had a fair amount of discussion around it. It was decided that the new options would give you "normal" files and that you would have to explicitly ask for "special" files. Very few people want to get the recycle bin back in their results, for example. Hidden is a bit grayer, but consistency helped push it in.

I'm going to close the issue, but I'll still happily answer any questions.

**Closed by JeremyKuhne** 2018-08-10 17:54 UTC
Labels: area-System.IO
