### ISSUE TITLE
System.Net.Sockets.Socket.DoConnect failed with Operation timed out in the CI

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#26810] opened 2018-02-03 02:04 UTC
https://mc.dot.net/#/user/tarekgh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/f5e2e814d3f584d8578937fe41a907c507742f7e/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendPacketsAsync~2FSendPacketsElement_FileZeroCount_Success(type:%20APM)

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Operation timed out [::1]:50296

at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4376
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 824
   at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SocketImplementationType type, SendPacketsElement[] elements, SocketError expectedResut, Int32 bytesExpected) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 452
   at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SocketImplementationType type, SendPacketsElement element, Int32 bytesExpected) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 433
   at System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FileZeroCount_Success(SocketImplementationType type) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs:line 343
```

**Comment by karelz** [comment] 2018-02-04 01:27
Duplicate of #21037

**Closed by karelz** 2018-02-04 01:27 UTC
Labels: area-System.Net.Sockets, os-mac-os-x
