### ISSUE TITLE
SQL Client: Unable to load sni.dll (DllNotFoundException)

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/corefx#5252] opened 2016-01-08 18:08 UTC
Several customers have reported errors loading sni.dll. 

This is not the same as https://github.com/dotnet/corefx/issues/3760 because installing the Microsoft Visual C++ 2012 Redistributable does not resolve the issue.

Examples of the customer reports are on https://github.com/aspnet/EntityFramework/issues/4162. Many of those are seeing the error when using EF7 but have confirmed that the error reproduces when using SQL Client directly.

Several people have reported that the error occurs under the following environment

> coreclr-x64-rc1-update1 with IIS 7.5 on Windows Server 2008 R2 with C++ redistributable installed (x64 & x86).

Full details of the exception...

```
The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.Exception caught: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.Exception caught: Unable to load DLL 'C:\Users\ddragan\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23616\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)Exception thrown: 'System.TypeInitializationException' in Platform.Authentication
Exception thrown: 'System.TypeInitializationException' in mscorlib.ni.dll
Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware:Error: An unhandled exception has occurred: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'C:\Users\ddragan\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23616\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.TdsParser..cctor()
   --- End of inner exception stack trace ---
   at ExternalDataAccessor.GetFirm(String firmName)
```

**Comment by rowanmiller** [comment] 2016-01-08 18:11
cc'ing several customers who have reported this issue so that they can track the issue here and provide more details if needed

@dan-dragan @JohnBicknell @juswes

**Comment by taufiqueahmad** [comment] 2016-01-11 08:34
any progress regarding SQL Client: Unable to load sni.dll (DllNotFoundException) issue?

**Comment by Aequoris** [comment] 2016-01-11 16:30
I too am getting this issue, on both RC1-update1 and on the RC2 nightly builds.

**Comment by kkurni** [comment] 2016-01-12 02:41
@rowanmiller Do you mind to check whether you have that SNI.dll in this folder (as per error message) ?
C:\Users\ddragan\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23616\runtimes\win7-x64\native\

Do you have instruction to repro this ?

**Comment by matthieugd** [comment] 2016-01-12 14:48
I got the same exception even if the app was working a few weeks ago. And the SNI.dll is present in the folder. 

"System.DllNotFoundException: Unable to load DLL 'C:\Users\xxxx\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
"

**Comment by dlebedynskyi** [comment] 2016-01-12 16:10
having same issue. 
```{"Unable to load DLL 'C...\\packages\\runtime.win7-x86.System.Data.SqlClient.sni\\4.0.0-beta-23516\\runtimes\\win7-x86\\native\\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}
```
Any news on when fix is expected?

**Comment by airomero** [comment] 2016-01-12 16:22
Same here!

![image](https://cloud.githubusercontent.com/assets/1215578/12269247/40237804-b92f-11e5-82e5-719799679723.png)

**Comment by kkurni** [comment] 2016-01-12 16:45
I still trying to repro this. And try to find a clue what may cause this.

Please provide us with more information variation as possible to get this fix quickly.
---
how you repro this?
Are you using dnx or corefx?
What windows version?
When this start happening? Did you recently pull the latest version,
Did you get error on different version as well?
Do you mind to share your snippet of code? are you calling EF or sqlclient?
--

**Comment by kkurni** [comment] 2016-01-12 16:48
@joshfree @stephentoub This could potentially be packaging issue. Do you have packaging to look into this issue as well?

**Comment by airomero** [comment] 2016-01-12 17:11
Heres is an example, it only happens using netcore x86 and x64 (1.0.0-rc1-update1)

![image](https://cloud.githubusercontent.com/assets/1215578/12270705/233b18d0-b936-11e5-85f8-5489040166d2.png)

In my case os : win7x64 ultimate (in win 10 it works fine)

**Comment by JohnBicknell** [comment] 2016-01-12 17:24
@kturni

how you repro this?
Make a simple sql query using sqlclient and CoreClr x86 or x64 RC1 or (so far) nightly build. For most setups the work-around fix of installing Microsoft Visual C++ 2012 Redistributable worked. Where I'm stuck is deployment on IIS, which is via HttpPlatformHandler Module of IIS. On a windows 2008 R2 server (with C++ Redistributable installed) the application will run and query sql server fine from the command line using dnx web. Running via IIS, same dnx, SNI error returns, app starts up fine, just errors with SNI when you hit code that has a SQLClient query. 

Are you using dnx or corefx?
1.0.0-rc1-update1 coreclr x64          win             core64

What windows version?
For me Windows 7 or Windows Server 2008 R2 (Works fine OSX)

When this start happening? Did you recently pull the latest version,
Only started trying to get it working on windows last week.

Did you get error on different version as well?
See above

Do you mind to share your snippet of code? are you calling EF or sqlclient?
Just the simplest query using SQLConnection and SQLCommand will trigger it, no EF required.

**Comment by kkurni** [comment] 2016-01-12 17:57
Thanks @JohnBicknell & @airomero.

So if I can summarize this issue, This issue only exist if you run this SQLClient code inside ***IIS & Win2008R2/Win7***

***Does anyone has the same error if your run this Outside IIS ?

@airomero does this work fine when you run it inside Windows 10 IIS ?

FYI, OSX/ unix will works as it will use managed SNI. only windows we use native SNI at this moment.

**Comment by matthieugd** [comment] 2016-01-12 18:07
I have the same problem on Windows 10 on IIS Express with coreclr-1.0.0-rc1-update1 x64
using EF 

`_dbContext.MyEntity.FirstOrDefault(x => x.Id == Guid.Empty);`

System.DllNotFoundException: Unable to load DLL 'C:\Users\zzzz\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_1`1.<CompileQuery>b__1(QueryContext qc)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

**Comment by JohnBicknell** [comment] 2016-01-12 18:13
@kkurni 
Does anyone has the same error if your run this Outside IIS ?
Just to be clear, I was getting it on Windows 7 and Windows Server 2008 R2, until installing Microsoft Visual C++ 2012 Redistributable.

**Comment by kkurni** [comment] 2016-01-12 18:26
Thanks @JohnBicknell for your clarification.

It seems installing C++2012 will solve this https://github.com/dotnet/corefx/issues/3760.

Did you get the same error before you installed C++2012 outside IIS ?

**Comment by taufiqueahmad** [comment] 2016-01-12 18:48
For me it is Working on windows 10 development machine but when i published on win server 2012 R2 it is not working, I installed Microsoft Visual C++ 2012 Redistributable as well but still getting same error.

System.DllNotFoundException: Unable to load DLL 'C:\Users\xxxxxx.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
at

**Comment by taufiqueahmad** [comment] 2016-01-12 19:00
Sorry i want to correct one thing,
After published on Windows Server 2008 R2 is not working.

**Comment by kkurni** [comment] 2016-01-12 19:11
@taufiqueahmad did you published to IIS ?

**Comment by airomero** [comment] 2016-01-12 19:12
In win7x64 not working even debugging in VS. Visual C++ 2012 Redistributable x86 and x64 are both installed.

**Comment by kkurni** [comment] 2016-01-12 19:24
@airomero do you use ASPNET Web project ? Did you try with console application ?
In windows 10, you mentioned that this is worked fine. Does it work when you deployed to IIS windows 10 ?

**Comment by airomero** [comment] 2016-01-12 19:44
The example i showed you is a console app. I haven´t deployed anything to IIS yet, so i can't answer that.

**Comment by taufiqueahmad** [comment] 2016-01-12 20:16
Yes i published on iis.

**Comment by JohnBicknell** [comment] 2016-01-13 09:23
@kturni

Did you get the same error before you installed C++2012 outside IIS ?

Inner Exceptions looks the same.
(both CoreClr x64 RC1)

Exception from IIS Logs (With and without C++ Redistributable installed)
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[3]
      Request finished in 0.0624ms 500
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'D:\Websites\rnli-launch-api\bin\output\approot\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
         at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
         at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
         at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
         at System.Data.SqlClient.SNILoadHandle..ctor()
         at System.Data.SqlClient.SNILoadHandle..cctor()
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.TdsParser..cctor()
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
         at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
         at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at LaunchApi.Models.StationRepo.GetStationsPage(String query, Int32 page, Int32 size, String baseURL, String latitude, String longitude, Int32 radius)
         at LaunchApi.Shouts.StationsController.Get(String query, Int32 page, Int32 size, String latitude, String longitude, Int32 radius)
      --- End of stack trace from previous location where exception was thrown ---
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


Exception from running directly in console (without C++ Redistributable installed) with 'DNX web'
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an except
ion. ---> System.DllNotFoundException: Unable to load DLL 'C:\Users\geckotec.support\.dnx\packages\runtime.win7-x64.System.Data.SqlClient.sni\4.0.0-beta-23516\runtimes\win7-x64\native\sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
         at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
         at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
         at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
         at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
         at System.Data.SqlClient.SNILoadHandle..ctor()
         at System.Data.SqlClient.SNILoadHandle..cctor()
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.TdsParser..cctor()
         --- End of inner exception stack trace ---
         at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
         at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
         at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
         at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionStringconnectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
         at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool,DbConnection owningConnection, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
         at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultiple
ObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1
 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternaloldConnection, DbConnectionInternal& connection)
         at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
         at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
         at System.Data.SqlClient.SqlConnection.Open()
         at LaunchApi.Models.StationRepo.GetStationsPage(String query, Int32 page, Int32 size, String baseURL, String latitude, String longitude, Int32 radius)
         at LaunchApi.Shouts.StationsController.Get(String query, Int32 page, Int32 size, String latitude, String longitude, Int32 radius)
      --- End of stack trace from previous location where exception was thrown ---

**Comment by jamesgibbs100** [comment] 2016-01-13 11:33
Simple Testing Results

Using a simple test console application which references System.Data.SqlClient. This Console application makes a connection to a remote database and queries the contents of a table.

Using 1.0.0-rc1-final, coreclr, x86 (or x64)

Running this from the command line works with either x64 or x86 runtimes.
Running this from Visual Studio (F5 Debug) then it fails with the SNI not found errors above.

Monitoring the process through Process Monitor reveals that "api-ms-win-core-stringansi-l1-1-0.dll" is not being loaded [for what ever reason]. Whereas from the commandline it is successfully located. 

Placing api-ms-win-core-stringansi-l1-1-0.dll into the same directory as the project allows Visual Studio to launch the console application and run normally

1) Failure

![1](https://cloud.githubusercontent.com/assets/4983720/12293031/b891525c-b9e8-11e5-9ce0-93703997b46a.png)

2) Monitoring

![2](https://cloud.githubusercontent.com/assets/4983720/12293057/e043b092-b9e8-11e5-91c7-f7db9c62f6b5.png)

3) After copying in the file

From : C:\Users\jgibbs\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-final\bin
To : Project Root

Console application works as expected

**Comment by kkurni** [comment] 2016-01-13 19:23
Thanks @JohnBicknell for clarification.

Thanks @jamesgibbs100 for debuging this. api-ms-win-core-stringansi-l1-1-0.dll looks interesting. This could be packaging bug.

**Comment by chcosta** [comment] 2016-01-13 20:01
Why does this work from the command-line?  Where does it find the exports it is looking for in api-ms-win-core-stringansi-l1-1-0.dll? Does it find them in the api set dll or in user32.dll?  

> [Same hack can be achieved by adding the runtime bin folder to the path environment variable prior to opening VS]

@jamesgibbs100, are you saying the api set dll present in your runtime bin folder?

**Comment by kkurni** [comment] 2016-01-13 20:52
Why does it work from command line ?

Because they installed VC2012++ redistributable which contains MSVCR10.dll
This issue is related this https://github.com/dotnet/corefx/issues/3760

So the current work around is to install VC2012++ redistributable. But unfortunately this issue will not fix if they run the application inside IIS + Sql Server 2008 R2.
This could probably related with how the permission is handled.

I still not sure about api-ms-win-core-stringansi yet. And why it was placed on different folder.

**Comment by jamesgibbs100** [comment] 2016-01-13 21:12
I placed the dll into the same folder as the project.json. If you can read the Process Monitor events on the above screen shot you can just read the paths it is trying to resolve through, which is what led me to try doing this.

Note : the console app has no reference to IIS or web at all. Just the sqlclient.

**Comment by kkurni** [comment] 2016-01-14 03:12
@jamesgibbs100 How did you install your DNVM ?

I installed dnvm manually but has VS 2015 installed, and for command line it works fine.

![image](https://cloud.githubusercontent.com/assets/698547/12314851/847b2cd6-ba29-11e5-94c3-a57056797b1f.png)

**Comment by kkurni** [comment] 2016-01-15 02:43
I can repro this only if I published it to IIS.

IIS Express and Krestel are working fine.

VC2012++ redis is installed with OS.

I used 
- Server 2008 R2
- VS2015 
- IIS 7.5

**Comment by jamesgibbs100** [comment] 2016-01-15 11:05
__Executing from the command Line (Working)__
In order to execute from the command line I use DNVM USE to select the version of the runtime I want
This in turn inserts the path to the runtime bin folder to the PATH statement
As a result, dll resolution works. stringansi dll is located and the application works as expected

__Executing from Visual Studio (NOT Working)__
Whilst I set the global.json to point to the correct SDK/runtime which it locates, no path changes occur as above. Consequently, dll resolution does NOT work, SNI.DLL cannot load *stringansi* dll and reports the failure of SNI.
Even though the stringansi dll is located in the runtime/bin folder - as this is not part of the path - it will be skipped and sni.dll fails to load


* This might be a corrupt environment but I have been using it successfully for months across multiple versions. 
* The console application I used was one which was originally work without glitch so is this something that has been introduced recently.
* stringansi dll is NOT located in any windows directory, only the runtime/bin folder
* I am using Win 7, x86|x64, coreclr
* I have VS 2012 and VS 2015 installed

Is this expected behaviour or should the dll location be resolved regardless of PATH variables being set. So, in the VS (which doesn't set the PATH) , as it locates the correct runtime folder should I also expect that to be sufficient for it to load all managed and unmanaged assemblies ?

**Comment by kkurni** [comment] 2016-01-16 01:15
Here is what I found for IIS case.

When you publish your web project, you will get AppRoot/web.cmd
This AppRoot/web.cmd will get executed on IIS and fire DNX.exe.

Unfortunately this web.cmd doesn't register your runtime (which should be on your current publish package)

In IIS, because you run your application pool on different user, DNX runtime hasn't been installed there or it could be different version, that's why you get that exception because sni.dll depend on stringansi.dll which located inside the runtime.

In other cases, you will get BadImageException because your runtime that you set on your current user profile are different than your runtime that you should use in your published application.

For workaround, you can modify web.cmd to add your runtime into your path.
***SET "PATH=%PATH%;%~dp0runtimes\%DNX_FOLDER%\bin\;" ***

It should look like this.
```
@echo off
SET DNX_FOLDER=dnx-coreclr-win-x64.1.0.0-rc1-update1
SET "LOCAL_DNX=%~dp0runtimes\%DNX_FOLDER%\bin\dnx.exe"
***SET "PATH=%PATH%;%~dp0runtimes\%DNX_FOLDER%\bin\;" ***
```

Restart your IIS, it should fix your problem at this moment.

I will raise this issue with DNX team and also CLI team to make sure that it won't be a problem in RC2 release.

**Comment by kkurni** [comment] 2016-01-16 03:05
@jamesgibbs100, I guess in your case, why you can not find api-ms-win-core-stringansi-l1-1-0.dll, because you set your dnx into different version when you run it.

If i check this from your screenshot, 
I guess you build and run this project againts : RC1 update
![image](https://cloud.githubusercontent.com/assets/698547/12370085/0816d8f6-bbba-11e5-879e-c07286fdd474.png)


But in some reason your runtime was set to RC1 Final, in your environment path.
![image](https://cloud.githubusercontent.com/assets/698547/12370095/3b54d56a-bbba-11e5-9867-5275b382e235.png)

Try to update your package again use the same version when you build and your environment setup.

check your project compilation are compiled against the same version
![image](https://cloud.githubusercontent.com/assets/698547/12370132/f83cd290-bbba-11e5-9820-433d6d2c3cf2.png)

![image](https://cloud.githubusercontent.com/assets/698547/12370108/8cc48094-bbba-11e5-9a30-3e51fcdfc24e.png)

![image](https://cloud.githubusercontent.com/assets/698547/12370109/946db48c-bbba-11e5-841c-04a99d437c5a.png)

Make sure the active env are the same
![image](https://cloud.githubusercontent.com/assets/698547/12370128/d918b0f0-bbba-11e5-9696-8edcd359d761.png)

**Comment by JohnBicknell** [comment] 2016-01-16 16:22
@kkurni 
>>>>>>>>>>>>>>>>>>>>>>>>>>>
For workaround, you can modify web.cmd to add your runtime into your path.
SET "PATH=%PATH%;%~dp0runtimes\%DNX_FOLDER%\bin\;"
<<<<<<<<<<<<<<<<<<<<<<<<<<<

Thanks! that works for me.

**Comment by sady4850** [comment] 2016-01-18 07:57
Any workaround for the issue to enable debugging in VS ?

**Comment by kkurni** [comment] 2016-01-19 19:08
@sady4850, this issue more related to IIS, I still cannot replicate the issue when debugging in VS.
But this will be similar root cause. Would you mind to raise another issue which just has VS debugging details about how you replicate and the version you are using ?

**Comment by kkurni** [comment] 2016-01-19 19:08
I am closing this issue, as this is more related to DNX and CLI.

It will be tracked on 

https://github.com/aspnet/dnx/issues/3316
https://github.com/dotnet/cli/issues/881

**Closed** 2016-01-19 19:08 UTC
Labels: blocking-partner, packaging, System.Data, Windows

**Comment by sady4850** [comment] 2016-01-19 20:01
@kkurni here you go #5521

**Comment by foxjazz** [comment] 2017-10-11 17:58
After published on Windows Server 2008 R2 is not working.
sni.dll not found when connecting to the database.

**Comment by phillijw** [comment] 2017-10-11 22:03
Oddly enough, I ran into this problem today... just a couple hours after foxjazz did. I'm assuming there is a regression issue?
