### ISSUE TITLE
HttpWebRequest with default SocketsHttpHandler hangs for certain endpoints

### ISSUE THREAD

**Issue by hognevevle** [dotnet/corefx#35376] opened 2019-01-29 14:08 UTC
Hello,

I'm trying to consume a third party API via .NET Core 2.2. I'm experiencing that the request will simply hang, using both .NET Core 2.2 and 2.1. The hang appears to be indefinite, and I have not yet reached any timeout.

Attempting the same in .NET Framework or .NET Core 2.0 works as intended. 

Also, by issuing the code below prior to executing the request, my request will also work in .NET Core 2.2 and 2.1. 
`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`

This leads me to believe there is a bug in the SocketsHttpHandler introduced in .NET Core 2.1.

In its simplest form, the following console app replicates the issue. 

```c#
using System;
using System.IO;
using System.Net;

namespace SampleRequest
{
    class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Hello World!");
                
                //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
                
                string html = string.Empty;
                string url = @"https://sso.ote-godaddy.com/v1/secure/api/partner/foo/account/1";
    
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
    
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream))
                {
                    html = reader.ReadToEnd();
                    Console.WriteLine(html);
                }

                Console.WriteLine("Request ended.");    
                Console.ReadLine();
            }
        }
}
```

**Expected behaviour**
As this endpoint requires a client certificate for authentication, an exception should be thrown. 

**Actual behaviour**
With `UseSocketsHttpHandler` set to true (being the default in 2.1/2.2), the request will simply hang. I'm seeing this behaviour regardless of whether a certificate is provided or not.

With `UseSocketsHttpHandler` set to false, or using .NET Core 2.0/netfx, an exception is thrown as expected. 

Issue has been verified on three different machines (Windows).

**Comment by davidsh** [comment] 2019-02-17 19:36
@hognevevle I tried the repro and got this exception.  The behavior was same regardless of turning on/off SocketsHttpHandler:

```
davidsh@davidsh2:~/dotnet/SampleRequest$ dotnet run
Hello World!

Unhandled Exception: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at SampleRequest.Program.Main(String[] args) in /home/davidsh/dotnet/SampleRequest/Program.cs:line 20
```

I'm using the latest .NET Core 2.2.

**Comment by hognevevle** [comment] 2019-02-17 21:58
It appears some changes has been made on the endpoint side (GoDaddy), and I can no longer reproduce this either. It definitely wasn't returning a 403 before, instead it was failing on a SSL/TLS level. 

Closing for now. Will see if I can reproduce with a different endpoint, in which case I'll reopen the issue.

**Comment by hognevevle** [comment] 2019-02-17 22:04
@pwiens To me your issue sounds related to your environment, rather than a .NET issue. Will a simple `curl https://pypi.org/pypi/flake8/json` work from the build server?

**Comment by hognevevle** [comment] 2019-02-18 07:58
@davidsh Looks like I can still reproduce with the same endpoint under sso.ote-godaddy.com. I've edited the initial code sample.

Could you please try again?

**Comment by davidsh** [comment] 2019-02-18 18:00
Thanks for redoing the repro sample.  I am able to reproduce the hang in .NET Core when you use the default SocketsHttpHandler.  If you use the AppContext switch and turn off SocketsHttpHandler, then I see that an exception being generated (due to missing the proper client TLS certificate).  I also see the proper exception when I run the sample in .NET Framework.

The problem is a bug in .NET Core dealing with TLS renegotiation when it requests client certificates and we don't have one.  We should route the error up the stack to the HttpClient/HttpWebRequest API caller.  Instead the exception is being lost.

From .NET Core  / .NET Framework traces and WireShark traces, I see the server sending back a TLS alert due to the missing client certificate:

![image](https://user-images.githubusercontent.com/7684835/52969056-e21f6d00-3363-11e9-8673-b1127e3d00b6.png)

The TLS alert is "IllegalMessage" probably due to not having the TLS client certificate sent to the server.
>System.Net Information: 0 : [4968] InitializeSecurityContext(In-Buffers count=2, Out-Buffer length=0, returned code=IllegalMessage).
    ProcessId=16608
    DateTime=2019-02-18T17:48:55.9103456Z

**Comment by davidsh** [comment] 2019-02-18 18:00
@geoffkizer @karelz

**Comment by davidsh** [comment] 2019-02-18 18:58
I've reduced the repro for this endpoint:

```c#
var client = new TcpClient();
client.Connect("sso.ote-godaddy.com", 443);
NetworkStream s = client.GetStream();

var s2 = new SslStream(s);
s2.AuthenticateAsClient("sso.ote-godaddy.com");

var builder = new StringBuilder();
builder.AppendLine("GET /v1/secure/api/partner/foo/account/1 HTTP/1.1");
builder.AppendLine("Host: sso.ote-godaddy.com");
builder.AppendLine();

byte[] bytes = Encoding.UTF8.GetBytes(builder.ToString());

s2.Write(bytes);

byte[] readBuffer = new byte[1024];
s2.Read(readBuffer, 0, readBuffer.Length);
Console.WriteLine(Encoding.UTF8.GetString(readBuffer));
```

This code will throw an exception when it gets to this line:

```c#
s2.Read(readBuffer, 0, readBuffer.Length);
```

The exception is:
```
System.IO.IOException
  HResult=0x80131620
  Message=The read operation failed, see inner exception.
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStreamInternal.<ReadAsyncInternal>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at System.Net.Security.SslStreamInternal.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SampleRequest.Program.Test2() in D:\dotnet\SampleRequest\Program.cs:line 32
   at SampleRequest.Program.Main(String[] args) in D:\dotnet\SampleRequest\Program.cs:line 48

Inner Exception 1:
AuthenticationException: Authentication failed, see inner exception.

Inner Exception 2:
Win32Exception: The message received was unexpected or badly formatted
```

The "Win32Exception: The message received was unexpected or badly formatted" is coming from the SslStream object.  Basically, this confirms the receipt of the TLS alert "IllegalMessage" caused by the lack of the client certificate.

So, the bug is probably in SocketsHttpHandler not handling these kind of exceptions from SslStream.

**Comment by davidsh** [comment] 2019-02-18 21:32
Another interesting thing with this endpoint is that it behaves differently than other endpoints that request TLS renegotiation with client certificates.  When I test this against an IIS server where a subfolder needs client certificates, I don't get a TLS alert.  I simply get back a 403 HTTP response because I didn't send a client certificate.

And browsing to that URL (https://sso.ote-godaddy.com/v1/secure/api/partner/foo/account/1) in chrome gives this:
![image](https://user-images.githubusercontent.com/7684835/52977228-587e9800-3381-11e9-83c8-1d0e7c719f2f.png)

This is interesting because usually when a website requests a client certificate, a browser will display a dialog and ask me to pick a client certificate from some that I already have installed on the machine.  However, I suspect that this server is usually a restricted 'TrustedIssuers' list so even a normal browser won't have any client certificates to pick from.

**Comment by davidsh** [comment] 2019-02-18 23:26
Looks like these 2 AuthenticationExceptions get thrown during the SSL renegotiation phase.  But then those exceptions aren't transferred from the Socket threadpool I/O completion callback to SslStream and the rest of the upstack HTTP layers.

>1. System.Security.Authentication.AuthenticationException
System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Net.Security.dll!System.Net.Security.SslState.StartSendAuthResetSignal(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest, System.Runtime.ExceptionServices.ExceptionDispatchInfo exception)
System.Net.Security.dll!System.Net.Security.SslState.CheckCompletionBeforeNextReceive(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.Security.SslState.StartSendBlob(byte[] incoming, int count, System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.Security.SslState.ProcessReceivedBlob(byte[] buffer, int count, System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.Security.SslState.StartReadFrame(byte[] buffer, int readBytes, System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.Security.SslState.PartialFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.AsyncProtocolRequest.CompleteRequest(int result)
System.Net.Security.dll!System.Net.FixedSizeReader.ReadPacketAsync(System.IO.Stream transport, System.Net.AsyncProtocolRequest request)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<System.Net.FixedSizeReader.<ReadPacketAsync>d__1>.MoveNext()
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(System.Action<object> continuation, object state, bool forceAsync)
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs _)
System.Net.Sockets.dll!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(int bytesTransferred, System.Net.Sockets.SocketFlags flags)
System.Net.Sockets.dll!System.Net.Sockets.SocketAsyncEventArgs..cctor.AnonymousMethod__177_0(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)
System.Private.CoreLib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)

continuing and then

>2. System.Security.Authentication.AuthenticationException
System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Net.Security.dll!System.Net.Security.SslState.ThrowIfExceptional()
System.Net.Security.dll!System.Net.Security.SslState.CheckThrow(bool authSuccessCheck, bool shutdownCheck)
System.Net.Security.dll!System.Net.Security.SslState.CheckOldKeyDecryptedData(System.Memory<byte> buffer)
System.Net.Security.dll!System.Net.Security.SslState.HandleQueuedCallback(ref object queuedStateRequest)
System.Net.Security.dll!System.Net.Security.SslState.FinishHandshakeRead(int newState)
System.Net.Security.dll!System.Net.Security.SslState.FinishHandshake(System.Exception e, System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.Security.SslState.PartialFrameCallback(System.Net.AsyncProtocolRequest asyncRequest)
System.Net.Security.dll!System.Net.AsyncProtocolRequest.CompleteRequest(int result)
System.Net.Security.dll!System.Net.FixedSizeReader.ReadPacketAsync(System.IO.Stream transport, System.Net.AsyncProtocolRequest request)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<System.Net.FixedSizeReader.<ReadPacketAsync>d__1>.MoveNext()
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(System.Action<object> continuation, object state, bool forceAsync)
System.Net.Sockets.dll!System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs _)
System.Net.Sockets.dll!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(int bytesTransferred, System.Net.Sockets.SocketFlags flags)
System.Net.Sockets.dll!System.Net.Sockets.SocketAsyncEventArgs..cctor.AnonymousMethod__177_0(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)
System.Private.CoreLib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)

**Comment by davidsh** [comment] 2019-04-23 21:13
This is no longer hanging .NET Core 3.0 master branch.  This is probably due to recent refactoring changes in SslStream.  There was a similar bug that only exhibited hangs but now properly returns an exception.

I now get an exception returned from the original repro code:

<details>
<summary>Repro code</summary>

```c#
using System;
using System.IO;
using System.Net;

namespace SampleRequest
{
    class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Hello World!");
                
                //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
                
                string html = string.Empty;
                string url = @"https://sso.ote-godaddy.com/v1/secure/api/partner/foo/account/1";
    
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
    
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream))
                {
                    html = reader.ReadToEnd();
                    Console.WriteLine(html);
                }

                Console.WriteLine("Request ended.");    
                Console.ReadLine();
            }
        }
}
```

</details>

**Closed** 2019-04-23 21:16 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, bug, tenet-reliability
