### ISSUE TITLE
Enabling the incremental build for Native projects as well

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#38082] opened 2019-05-30 23:53 UTC
Currently if we make a change in the native proj, we have to  build from the root in order to get the changes.
We should enable incremental build for the native projects as well.

cc @ericstj

**Comment by ericstj** [comment] 2019-05-31 05:56
Agree this would be nice to have, moved to future since these CMake scripts have had this behavior since 1.0 and nothing should be forcing us to do this now.  I'm not sure how incremental CMake is, but others who are familiar are free to pick this up. /cc @ViktorHofer @safern

**Comment by ViktorHofer** [comment] 2019-05-31 06:32
Duplicate of https://github.com/dotnet/corefx/issues/29778

**Closed by ViktorHofer** 2019-05-31 06:32 UTC
Labels: area-Infrastructure
