### ISSUE TITLE
[CI Failure] System.Net.Sockets.Performance.Tests failure on code coverage run

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#16584] opened 2017-03-01 23:15 UTC
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows_prtest/34/consoleFull#-141271452579fe3b83-f408-404c-b9e7-9207d232e5fc

```
System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync [FAIL]
13:53:36         System.AggregateException : One or more errors occurred. (No connection could be made because the target machine actively refused it) (No connection could be made because the target machine actively refused it) (No connection could be made because the target machine actively refused it) (No connection could be made because the target machine actively refused it)
13:53:36         ---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
13:53:36         ---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
13:53:36         ---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
13:53:36         ---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
13:53:36         Stack Trace:
13:53:36               at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
13:53:36               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
13:53:36               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
13:53:36               at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketPerformanceTests.cs(131,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.RunClient(SocketImplementationType testType, EndPoint endpoint, Int32 iterations, Int32 bufferSize, Int32 socketInstances)
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketPerformanceTests.cs(51,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(Int32 port, SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds)
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketPerformanceTests.cs(76,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceTests.ClientServerTest(SocketImplementationType serverType, SocketImplementationType clientType, Int32 iterations, Int32 bufferSize, Int32 socketInstances, Int64 expectedMilliseconds)
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\System.Net.Sockets\tests\PerformanceTests\SocketPerformanceAsyncTests.cs(45,0): at System.Net.Sockets.Performance.Tests.SocketPerformanceAsyncTests.SocketPerformance_MultipleSocketClientAsync_LocalHostServerAsync()
13:53:36            ----- Inner Stack Trace #1 (System.Net.Sockets.SocketException) -----
13:53:36               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketTestClient.cs(138,0): at System.Net.Sockets.Performance.Tests.SocketTestClient.<RunTest>d__22.MoveNext()
13:53:36            ----- Inner Stack Trace #2 (System.Net.Sockets.SocketException) -----
13:53:36               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketTestClient.cs(138,0): at System.Net.Sockets.Performance.Tests.SocketTestClient.<RunTest>d__22.MoveNext()
13:53:36            ----- Inner Stack Trace #3 (System.Net.Sockets.SocketException) -----
13:53:36               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketTestClient.cs(138,0): at System.Net.Sockets.Performance.Tests.SocketTestClient.<RunTest>d__22.MoveNext()
13:53:36            ----- Inner Stack Trace #4 (System.Net.Sockets.SocketException) -----
13:53:36               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
13:53:36               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
13:53:36            D:\j\workspace\code_coverage---d5838fef\src\Common\tests\System\Net\Sockets\Performance\SocketTestClient.cs(138,0): at System.Net.Sockets.Performance.Tests.SocketTestClient.<RunTest>d__22.MoveNext()
```

**Comment by steveharter** [comment] 2017-03-07 20:24
Dupe of https://github.com/dotnet/corefx/issues/13349

**Closed by steveharter** 2017-03-07 20:24 UTC
Labels: area-System.Net.Sockets, os-windows, test-run-core

**Comment by steveharter** [comment] 2017-04-28 19:47
Note this is marked as a dupe of #13349 but may have other root cause as the exceptions are different (ObjectDisposedException vs. SocketException). Unable to repro on offline Unix and Windows CI machines running repeatedly. Keeping closed until we have another occurrence.
