### ISSUE TITLE
System.Text.Json double quotes

### ISSUE THREAD

**Issue by mfow** [dotnet/corefx#39554] opened 2019-07-16 22:17 UTC
System.Text.Json serializes strings that contain quotes using `\u0022` notation, rather than double quotes.

System.Text.Json: `{"foo":"this string has a \u0022 quote in the middle."}`
Double quotes: `{"foo": "this string has a "" quote in the middle."}`
Escaped quote: `{"foo": "this string has a \" quote in the middle."}`

`            using (var strm = new MemoryStream())
            {
                using (var writer = new Utf8JsonWriter(strm))
                {
                    writer.WriteStartObject();
                    writer.WriteString("foo", @"this string has a "" quote in the middle.");
                    writer.WriteEndObject();
                }

                strm.Seek(0, SeekOrigin.Begin);
                var r = new StreamReader(strm);
                string str = r.ReadToEnd();
                Console.WriteLine(str);
            }`

Even though I believe all three are valid json, the first breaks some existing services. It also takes up more space, and IMO is less readable.

Suggestion:
- Add an option to serialize a quoted string using double quotes.

**Comment by vcsjones** [comment] 2019-07-17 00:13
Hello, this looks like a duplicate of https://github.com/dotnet/corefx/issues/38576#issuecomment-502957010, which was addressed by #39524.

**Comment by ahsonkhan** [comment] 2019-07-17 01:27
> Even though I believe all three are valid json, the first breaks some existing services. 

How so? I would be interested to see how such default escaping policies causes breaks in existing code, primarily for my education.

Closing as duplicate. The default behavior will remain as is. However, as @vcsjones mentioned, there is a workaround where the user can pass in a custom `JavascriptEncoder` to the serializer (and writer) to control the escaping behavior of certain character.

Also, we added a `JavascriptEncoder.UnsafeRelaxedJsonEscaping` that would escape quotes as \" rather than \u0022, but using it is discouraged unless you have high confidence up/down the stack that you can do this safely (https://github.com/dotnet/corefx/issues/39410 / https://github.com/dotnet/corefx/pull/39550), since it comes with certain risks. It shouldn't be used flippantly particularly when the generated JSON is being sent over the wire (or in some web api/service).

**Closed by ahsonkhan** 2019-07-17 01:27 UTC
Labels: area-System.Text.Json

**Comment by ahsonkhan** [comment] 2019-07-17 02:34
cc @steveharter, @GrabYourPitchforks - fyi
