### ISSUE TITLE
Opening SqlConnection results in DllNotFoundException (Unable to load sni.dll) in case of executing from Visual Studio

### ISSUE THREAD

**Issue by sady4850** [dotnet/corefx#5521] opened 2016-01-19 19:59 UTC
works fine from command line

code

```
            var connection = new SqlConnection("valid connection string");
            connection.Open();
```

project.json:
```
{
  "version": "1.0.0-*",
  "description": "ConsoleApp10 Console Application",
  "authors": [ "sady4850" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "System.Data.SqlClient": "4.0.0-beta-23516"
  },

  "commands": {
    "ConsoleApp10": "ConsoleApp10"
  },

  "frameworks": {
     "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}
```

exception:
```

   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedLibraryFromPath(String path)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.LoaderContainer.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadUnmanagedLibrary(String name)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadUnmanagedDll(String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()

SQL Client: Unable to load sni.dll (DllNotFoundException)
```

**Comment by sady4850** [comment] 2016-01-19 20:02
see also #5252

**Comment by dan-dragan** [comment] 2016-01-19 20:19
Erm. Isn't this  a duplicate of the issue I opened at https://github.com/aspnet/EntityFramework/issues/4162 that got merged into https://github.com/dotnet/corefx/issues/5252 that got closed but got  tracked into aspnet/dnx#3316  and dotnet/cli#881 ?

**Comment by NickCraver** [comment] 2016-01-22 02:54
Is this the main tracking issue? The few libs hitting this (runtime bindings?) are the biggest pain in RC1, I'd consider this high-priority for RC2.

**Comment by danroth27** [comment] 2016-01-26 16:58
Please note that DNX is getting replaced by the new .NET CLI (https://github.com/dotnet/cli), so we should verify if this is still an issue when running on the .NET CLI. We are not fixing DNX specific issues at this point.

**Comment by airomero** [comment] 2016-01-26 18:14
Is there any post explaining the hole thing about dnx and cli. I'm a little confused about what will survive, what will die and what will be modified. How do we test if this problem exists in net cli?

**Comment by danroth27** [comment] 2016-01-26 21:00
You can get the latest .NET CLI build from http://dotnet.github.io.

**Comment by kkurni** [comment] 2016-01-29 02:34
I just verified that .NET CLI won't have this issue any more because the runtime will be set as local.

https://github.com/dotnet/cli/issues/881

**Comment by airomero** [comment] 2016-01-29 11:19
What do you mean with "the runtime will be set as local"? Local to the application??

**Comment by sady4850** [comment] 2016-01-29 11:42
@kkurni Why are linking IIS publishing issue here ? This issue is not related to the IIS at all.

**Comment by kkurni** [comment] 2016-01-29 16:23
@airomero in Dotnet CLI, the runtime is published the same folder (local) as the compiled application.
this will make sure that the published runtime is used instead of installed runtime

In DNX, the runtime is published on different folder which need something to register this path to enviroment variables to use that runtime. (this can potentially conflict with the installed runtime.

**Comment by kkurni** [comment] 2016-01-29 17:01
@sady4850 this could be the same issue as DNX always assume to use installed runtime which registered in your "path" environment variables.

I cannot repro this issue while debugging console app in visual studio.
![image](https://cloud.githubusercontent.com/assets/698547/12681390/442f3dac-c663-11e5-93eb-65c277a4516c.png)

Here is my project.json
![image](https://cloud.githubusercontent.com/assets/698547/12681698/b9af3716-c664-11e5-9687-de2f8346878c.png)


Couple things you can do to troubleshoot this.
* Open Process Monitor to your console application.

* Check which DNX runtime that visual studio open. (is it using the correct runtime ?)
![image](https://cloud.githubusercontent.com/assets/698547/12681751/fdcd1d64-c664-11e5-9702-e180a065cd83.png)


* Search for SNI.dll (Where Sni.dll is loaded ? Success /Fail ?)
![image](https://cloud.githubusercontent.com/assets/698547/12681852/7556006c-c665-11e5-9e75-c955f99d49ad.png)

* Search for stringansi-l1
(Check whether api-ms-win-core-stringansi-l1-1-0.dll is loaded ?)


* if it is failed to load stringansi-l1, check your environment variables. 
It should register dnx runtime path there.
![image](https://cloud.githubusercontent.com/assets/698547/12682147/db775e08-c666-11e5-8b8f-1ccfc9f125f5.png)

**Comment by sady4850** [comment] 2016-01-29 18:59
@kkurni ye, there wasn't dnx path in PATH. Still an open question why it is disappeared from there (because it worked and obviously I didn't remove it manually)

**Comment by kkurni** [comment] 2016-01-29 19:54
To find out why it works on console app (without VS Debugger), you can attach process monitor as well on console application without using VS debugger. (check where sni.dll and stringansi.dll is loaded).

it will be hard to answer why this path is disappeared. It probably some other installation of other frameworks / version which override / remove this runtime path.

I will close this as we have the root cause why we get SNI.dll error. 
And The DNX is being retired in favor of the new dotent CLI command line tools

**Closed by kkurni** 2016-01-29 19:54 UTC
Labels: bug, System.Data
