### ISSUE TITLE
Socket remote transfer file problem under CentOS #34618

### ISSUE THREAD

**Issue by eatage** [dotnet/corefx#34618] opened 2019-01-16 08:59 UTC
**测试环境：**
操作系统：CentOS 7 x64
.NET Core版本：2.2.1
**问题描述**
在特定文件条件下触发，当FileStream.Read读到一定长度的内容时，Socket.Send发送成功，
但是在远程端收到的内容为空，导致传送中端，最终引发SocketException Socket超时。
且都是读到同样的长度发生错误，表现为传送进度到此位置时发生Socket超时错误。
如果该文件触发了这个错误，则将该文件拷到其他同环境的服务器也一定触发该错误。
发送至远程客户端，同同步方法或异步方法都触发这个Bug。
可用此项目进行测试：[FtpServer](https://github.com/ZhaobangChina/FtpServer)
可向我索取触发Bug的文件：[346414491@qq.com](mailto:346414491@qq.com)

**Comment by danmosemsft** [comment] 2019-01-16 17:11
bing translated:

test environment:
Operating system: CentOS 7 x64
.NET Core version: 2.2.1
Problem Description
Triggered under certain file conditions, when FileStream.Read reads a certain length of content, Socket.Send is sent successfully.
However, the content received at the remote end is empty, causing the middle end to be transmitted, eventually causing a SocketException Socket timeout.
Both of them read the same length and an error occurs, which is caused by a Socket timeout error when the transfer progresses to this position.
If the file triggers this error, copying the file to another server in the same environment must also trigger the error.
Sending to a remote client triggers the bug with either a synchronous method or an asynchronous method.
Can be tested with this project: FtpServer
Ask me for a file that triggers a bug: 346414491@qq.com

**Comment by caesar1995** [comment] 2019-01-16 21:46
@eatage Have you tested on Windows?

> when FileStream.Read reads a certain length of content

What's the length? Does it repro with any files which exceed that size?

> 导致传送中端

Typo?

> Ask me for a file that triggers a bug

Can you attach the file here?

**Comment by karelz** [comment] 2019-02-21 04:39
Not actionable, closing.
Let us know if you have additional info which makes the report actionable, we can reopen.

**Closed by karelz** 2019-02-21 04:39 UTC
Labels: area-System.Net.Sockets, needs more info
