### ISSUE TITLE
Enable packages and building for MEF.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#9440] opened 2016-06-15 17:18 UTC
Right now, we're in a situation we're shipping packages based on checked in binaries but aren't able to build new binaries (and thus fix bugs) in the MEF code.

**Comment by mellinoe** [comment] 2016-06-15 17:40
Is this a dupe of https://github.com/dotnet/corefx/issues/6598?

What do you mean by "we're shipping packages based on checked in binaries"? We dont have any nuget packages being produced for System.Composition. And the code checked in here should build fine, it's just not being packaged.

I have a branch here that adds packages for all of the System.Composition libs, but it's not complete or bug tested yet.
https://github.com/mellinoe/corefx/tree/system.composition.nupkg

**Comment by AtsushiKan** [comment] 2016-06-15 17:56
Looks like a dupe.

I opened it because I keep getting assigned the MEF bugs but if you’re already on 6598, I’m not demanding to poach it ☺

Feel free to close 9440.

**Closed** 2016-06-15 17:58 UTC
Labels: System.Composition

**Comment by mellinoe** [comment] 2016-06-15 17:59
> I’m not demanding to poach it ☺

Bummer :laughing: . I worked on this briefly earlier in the week, but am working on some more urgent stuff now. It shouldn't take much more work to finish up my branch when I have time.
