### ISSUE TITLE
dotnet core 3 on macOS Catalina: NetworkInterface causes high CPU

### ISSUE THREAD

**Issue by aspcompiler** [dotnet/corefx#42634] opened 2019-11-18 21:53 UTC
You can find our code at https://github.com/awslabs/kinesis-agent-windows/blob/master/Amazon.KinesisTap.Shared/NetworkStatus.cs. It runs fine on Windows and macOS before Catalina, but causes high CPU on macOS Catalina.

High CPU is only caused by NetworkAddressChanged or NetworkAvailabilityChanged event handler. This occurs when we turn on/off VPN. This is to give you a heads up; we will do more work to narrow down the exact line of the code that cause high CPU later.

**Comment by scalablecory** [comment] 2019-11-19 06:42
@wfurt @aik-jahoda

**Comment by wfurt** [comment] 2019-11-19 06:48
It seems like there are still digging. It would be nice to get small runable repro. The linked fragment will register for notifications as well as it will get all info from all interfaces. It would be interesting to know which parts is causing the troubles.

**Comment by aspcompiler** [comment] 2019-11-19 15:19
Thank you for superfast response! I will try to provide more information. The problem only occurs sporadically. We are experimenting with [dotnet-trace](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace) to capture information. If you are willing to take a look of the trace, I can upload some.

**Comment by wfurt** [comment] 2019-11-19 19:43
Good to know this is not deterministic. dotnet-trace does not capture native parts but that may be ok for this case. Knowing where we spent cycles when issue happens would be good.
If you get reasonable repro, you can also make body of the callback empty - either only log or update counters. One speculation I have is race condition in getting all network info when system is transitional state.

**Comment by rharpavat** [comment] 2019-11-27 22:52
Apologies for the delay in responding, I have created a small program that should reliably reproduce the issue which can be found at [https://github.com/rharpavat/dotnet-macos-cpuusage](https://github.com/rharpavat/dotnet-macos-cpuusage). Instructions to run the program are in the README.

Please let me know if there's any more information I can provide that might be helpful. Thanks!

**Comment by wfurt** [comment] 2019-11-27 22:56
thanks. I'll give it try.

**Comment by wfurt** [comment] 2019-12-04 22:35
I don't have wifi on my Catalina machine so I used ifconfig up/down but that did not repro cpu load. 
I have another machine I may be able to upgrade.
I'll let you know if I get repro.

**Comment by wfurt** [comment] 2019-12-05 19:54
I was able to get repro. It seems like we get stuck in endless loop in native code while trying to process routing table. From that point no further notifications are dispatched and the watching thread just eats CPU forever.

**Comment by sahilmaggu08** [comment] 2019-12-05 20:44
Thanks for the quick reply @wfurt 
Do you think its a quick fix or you need any more info from our side?

**Comment by wfurt** [comment] 2019-12-07 03:19
reopening to consider servicing

**Comment by zekuny** [comment] 2019-12-09 19:08
Thanks for the quick fix. Is this in fix in the latest Master (5.0.x Runtime)? Can I download the installer (5.0.100-alpha1-015914) to test the fix now? Do you have an ETA for the 3.1 servicing pack?

**Comment by rharpavat** [comment] 2019-12-09 23:42
@wfurt : I was still able to reproduce the issue with the repro project linked above after updating to use the .NET Core 5.0.1 SDK from https://github.com/dotnet/core-sdk. I also tried updating just the runtime using the latest version from https://github.com/dotnet/runtime but the issue has persisted. 

Do you know if these builds contain the fix and/or when we will be able to download a 5.x build containing the fix? Additionally, is there a rough ETA of when we will see this fix in a 3.1 build? Thanks!

**Comment by wfurt** [comment] 2019-12-10 00:53
With recent infrastructure changes I don't know answer for your questions. But I should be able to find it eventually. For testing, what exact version of runtime do you have and what is your methodology for testing? (e.g. are you sure you test with correct assemblies)

**Comment by rharpavat** [comment] 2019-12-10 18:23
.NET runtime version: **5.0.100-alpha1-015914** (output from running `dotnet --version`)

I tested with the same test project above (https://github.com/rharpavat/dotnet-macos-cpuusage), changed the `TargetFramework` in the .csproj file to `netcoreapp5.0` from `netcoreapp3.0`.

Here's the output from running the test project using `dotnet run Program.cs`:

```
Welcome to .NET Core 5.0!
---------------------
SDK Version: 5.0.100-alpha1-015914

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
App started!
```

after which we see the `Console.WriteLine()` statements indicating network switches. Was able to see sustained high CPU usage again after running for ~5 mins.

Please let me know if I'm testing with incorrect assemblies/not referencing them properly/have some other issue! Appreciate the help and quick reply.

**Comment by wfurt** [comment] 2019-12-10 19:08
```
strings shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Native.dylib | grep Commit
@(#)Version 5.0.19.56306 @Commit: 5cee7c97d602f294e27c582d4dab81ec388f1d7b
```

It seems like this still has runtime from old corefx repo. That is also true for the runtime link from runtime repo ;(

Publishing to Azure is still behind repo reorg.  I was told this should be fixed by end of the week if everything goes according to plan.

**Comment by rharpavat** [comment] 2019-12-10 19:11
Ah gotcha, thanks for the update! Is there a good way for us to check whether or not a certain version of the runtime has the updated code?

**Comment by wfurt** [comment] 2019-12-10 19:15
not really. I use the command above to find commit hash. And then I look in one or the other repo for that hash. And then you can check if given fix was submitted before or after that change.

**Comment by rharpavat** [comment] 2019-12-18 18:02
I downloaded the latest version of the runtime (5.0.0-alpha.1.19564.1) and it seems to contain the fixed code. Ran the test program above and was not able to reproduce the issue again, so it seems to have been fixed. Do you know when we might see this bugfix incorporated into a release of .NET Core 3.1?

**Comment by rharpavat** [comment] 2019-12-30 19:24
Do you know when we might be able to see this fix in a release of .NET Core 3.1? Would appreciate even a rough ETA - thanks!

**Comment by danmosemsft** [comment] 2019-12-31 21:06
> Would appreciate even a rough ETA - thanks!

@rharpavat, @wfurt will have to comment and go through servicing process. But we generally release servicing updates on the 2nd Tuesday of the month, and the one for Jan is already finalized. I think there is a window open for the Feb one.

**Comment by rharpavat** [comment] 2020-01-06 16:50
@wfurt Would it be possible to include this in the Feb servicing release? Appreciate the support. Thanks!

**Comment by karelz** [comment] 2020-01-14 21:51
Fixed in 3.1.2 in PR #42800 and in 5.0 in PR https://github.com/dotnet/runtime/pull/591

**Closed by karelz** 2020-01-14 21:51 UTC
Labels: area-System.Net, bug, os-mac-os-x

**Comment by rharpavat** [comment] 2020-01-20 17:57
Would it be possible to get a dev build of 3.1.2 so we can verify this fix? We're depending on this fix for a product release so would like to verify it prior to release. Thanks!

**Comment by karelz** [comment] 2020-01-21 16:54
Did you try to grab daily build? https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries

**Comment by rharpavat** [comment] 2020-01-23 20:14
Hi, I tried installing the latest daily build from the 3.1.2 release branch (`3.1.200-preview-014935`). I'm running into these `dotnet build` errors:

```
error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.osx-x64 with version (= 3.1.2)
proj.csproj : error NU1102:   - Found 1331 version(s) in dotnet-core [ Nearest version: 5.0.0-alpha.1.19528.5 ]
proj.csproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 3.1.1 ]
proj.csproj : error NU1102:   - Found 0 version(s) in aspnet-aspnetcore-tooling
proj.csproj : error NU1102:   - Found 0 version(s) in aspnet-aspnetcore
proj.csproj : error NU1102:   - Found 0 version(s) in aspnet-entityframeworkcore
proj.csproj : error NU1102:   - Found 0 version(s) in aspnet-extensions
proj.csproj : error NU1102:   - Found 0 version(s) in dotnet-windowsdesktop
proj.csproj : error NU1102:   - Found 0 version(s) in gRPC repository
```

I updated my NuGet.Config file as directed on [this page](https://github.com/dotnet/core-sdk) with the following lines:
```
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-windowsdesktop" value="https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json" />
    <add key="aspnet-aspnetcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json" />
    <add key="aspnet-aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
    <add key="aspnet-entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
    <add key="aspnet-extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
    <add key="gRPC repository" value="https://grpc.jfrog.io/grpc/api/nuget/v3/grpc-nuget-dev" />
  </packageSources>
</configuration>
```

I know 3.1.2 is installed as running the `dotnet --list-sdks` and `dotnet --list-runtimes` commands give the following output:
```
dotnet --list-sdks
2.1.803 [/usr/local/share/dotnet/sdk]
3.0.102 [/usr/local/share/dotnet/sdk]
3.1.200-preview-014935 [/usr/local/share/dotnet/sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

This is what my .csproj file looks like, for reference:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyVersion>1.1.200.1</AssemblyVersion>
    <FileVersion>1.1.200.1</FileVersion>
    <Version>1.1.200.1</Version>
    <RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>
    <AssemblyName>myapp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.0" />
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
  </ItemGroup>

</Project>
```

Is there a config I'm missing and need to include in order to build successfully? Thanks!

**Comment by karelz** [comment] 2020-01-23 20:45
@nguerrera @dsplaisted could you help route this problem of using daily build of servicing branch? Are any steps missing?
