### ISSUE TITLE
HTTP client - API error c# (A task was canceled.)

### ISSUE THREAD

**Issue by rajurh** [dotnet/corefx#27702] opened 2018-03-04 06:51 UTC
We are calling multiple API's in foreach loop and all API are of Async call. Now in the foreach loop due to some reason 1 API call has returned internal error and we are skipping that record and progressing with other requests in for loop. When the next loop continues the first API call we are getting error with "System.Threading.Tasks.TaskCanceledException: A task was canceled" and "Aggregation exception".

Code Snippet:
We are making Httpclient initialization per loop and object used multiple times in the loop.
using (var httpClientHelper = new HttpClientHelper(tokenService)) 

API call snippet:
var response = await httpClientHelper.GetAsync("http://xyz"); 

Help or thoughts on this will be much appreciated.

**Comment by davidsh** [comment] 2018-03-04 15:55
>We are making Httpclient initialization per loop

You should try to reuse a single HttpClient as much as possible for multiple requests.  Without seeing the rest of your code, my guess is that your tasks are being canceled because they are timing out.  It's possible that you have a deadlock situation etc. in your code.

cc: @stephentoub

**Comment by rajurh** [comment] 2018-03-04 21:00
Below is the sample code for the above issue. Where you can see I am using single httpclient and in the foreach loop if the API call is not success i.e. when error is returned I am continuing with for loop. 

In the scenario where the status code is returned Internal error for one of the API and if I continue with forloop then I facing the issue "Task canceled". 

Hope this helps and have sufficient information.

**Sample code:**
  Public void Test()
  {
  
  using (var httpClientHelper = new HttpClientHelper())
                {
                    httpClientHelper.SetupInitial(default(string), "XXX"); //Setting up custom header values
					 foreach (var req in Requests)
						{
							 var response = httpClientHelper.GetAsync("endpointurl").Result; 
								if (response.IsSuccessStatusCode)
								{
									//custom logic
								}
								else
								{
									continue;
								}
								
								 var result = httpClientHelper.GetAsync("diff endpoint url").Result;
								if (result.IsSuccessStatusCode)
								{
								
								}
								else
								{
									continue;
								}
						}
                }
  }

**Comment by karelz** [comment] 2018-03-05 17:07
Which internal error do you get?
Can you provide a full (minimal) repro? Something you can reproduce on another machine and we will be able to reproduce inhouse for further investigation?

**Comment by karelz** [comment] 2018-03-12 21:25
@rajurh any chance to get a standalone minimal repro?

**Comment by davidsh** [comment] 2018-04-13 20:41
@rajurh We're not able to proceed with any debugging investigation without a small complete repro of the problem. We'll close this issue for now.  If you're able to repro the problem and attach a solution of it, we can re-open the issue.

Also, please try out .NET Core 2.1 Preview 2 to see if your problem reproduces with that latest release.  Thx!

https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

**Closed** 2018-04-13 20:41 UTC
Labels: area-System.Net.Http, needs more info, question

**Comment by PhilAtWysdom** [comment] 2018-11-27 16:04
I experienced this - it was triggered for me by setting the Timeout property to ```new TimeSpan(6000L)```

Changing it to ```new TimeSpan(0, 0, 10)``` resolved the issue for me.

**Comment by stephentoub** [comment] 2018-11-27 16:09
> I experienced this - it was triggered for me by setting the Timeout property to new TimeSpan(6000L)

The `TimeSpan(long ticks)` ctor takes a number of ticks, of which there are 10,000,000/second, so setting the timeout to `new TimeSpan(6000L)` is asking for the operation to timeout after less than a millisecond.

**Comment by PhilAtWysdom** [comment] 2018-11-27 16:11
Indeed, I had skim-read the tooltip and assumed milliseconds.
