### ISSUE TITLE
System.Composition.AttributedModel is released with mixed assembly versions.

### ISSUE THREAD

**Issue by tom-englert** [dotnet/corefx#41913] opened 2019-10-19 11:20 UTC
Starting with v1.3.0, the NuGet package of System.Composition.AttributedModel contains mixed versions!
For netstandard1.0 and portable it contains version 1.0.33, but for netstandard2.0 it is 1.0.34.

This leads to the conflict that if you reference two assemblies, one build for net4x and one build for netstandard2x, and all using System.Composition 1.3.0, you get a runtime error that System.Composition.AttributedModel 1.0.33 could not be loaded, because 1.0.34 is in the bin folder,
but the net4x assembly has a reference to the 1.0.33 assembly.

How to reproduce:
- Get https://github.com/tom-englert/TomsToolbox
- Upgrade System.Composition to 1.3.0
- Build
- Run tests
Now one test fails with an exception that System.Composition.AttributedModel 1.0.33 could not be loaded

Might be related to #41393

**Comment by safern** [comment] 2019-10-21 21:45
cc: @joperezr @ericstj might have some insights here.

**Comment by ericstj** [comment] 2019-10-21 23:10
This was introduced with https://github.com/dotnet/corefx/commit/955f028171040c66afc19394ddc332b9cda52c88.  @ViktorHofer 

Have you enabled bindingRedirects on your .NET4x project?

**Comment by tom-englert** [comment] 2019-10-22 07:05
@ericstj The test project is net462, so generating binding redirects should be on by default.
However according to @jcchalte in #41393 also the public key tokens have changed, so redirects can't work.

Looking at 955f028 - if you no longer build/support e.g. netstandard1.0, why then does the nuget package contain a binary for netstandard1.0? Does it pack stale binanries?

IMO such interface projects are very critical, and you should not change them by chance, forcing the DLL-hell mor than neccesary.

**Comment by tom-englert** [comment] 2019-10-30 10:16
@ericstj any update on this?

**Comment by ericstj** [comment] 2019-10-30 19:04
> why then does the nuget package contain a binary for netstandard1.0? Does it pack stale binanries?

Yeah, it redistributes the old build for these.

Public key tokens should not have changed, if they did, that's a bug that should be fixed.  I can confirm that's the problem here. 

From package 1.3.0
> System.Composition.AttributedModel, Version=1.0.34.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> System.Composition.AttributedModel, Version=1.0.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

From package 1.2.0 (all same)
> System.Composition.AttributedModel, Version=1.0.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

This needs to be fixed in 3.1, and likely 3.0 as well.  @maryamariyan @ViktorHofer.

Looks like this was regressed with https://github.com/dotnet/corefx/commit/cf52405ee7aacaf2a5ee7ce04153320f243d951c#diff-7385611035c749a335f16a7b108e7166L3-R4 which removed the public key and didn't add it to the [shared file](https://github.com/dotnet/corefx/blob/cf52405ee7aacaf2a5ee7ce04153320f243d951c/src/System.Composition/dir.props#L4-L7).  /cc @weshaggard 

Fix here is to add 
```
    <StrongNameKeyId>Microsoft</StrongNameKeyId>
```

To System.Composition\directory.build.props.

**Comment by safern** [comment] 2019-10-30 19:12
I can take this. It seems like a simple fix as @ViktorHofer and @maryamariyan are busy with other immediate stuff.

**Comment by ericstj** [comment] 2019-10-30 19:13
I already have the fix.

**Comment by safern** [comment] 2019-10-30 19:13
> I already have the fix.

Sounds good. Thanks.

**Comment by ericstj** [comment] 2019-10-31 20:16
Fixed in https://github.com/dotnet/corefx/pull/42235

**Closed by ericstj** 2019-10-31 20:16 UTC
Labels: area-System.Composition
