### ISSUE TITLE
SendRecvPollSync_TcpListener_Socket outerloop test is flaky

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#14673] opened 2016-12-21 23:51 UTC
When running this test in System.Net.Socket.Test.dll, I occasionally get the following exception:
```
     System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBefore
  Operation: False) [FAIL]
        System.AggregateException : One or more errors occurred. (An existing connection was forcibly closed
  by the remote host)
        ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote ho
  st
        Stack Trace:
              at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationTok
  en cancellationToken)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
           C:\github\geoffkizer\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(1184,0): a
  t System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean poll
  BeforeOperation)
           ----- Inner Stack Trace -----
           C:\github\geoffkizer\corefx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1436,0): at Sy
  stem.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
           C:\github\geoffkizer\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(1138,0): a
  t System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass27_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.M
  oveNext()

Looks like a timing issue somewhere.
```

**Comment by karelz** [comment] 2016-12-21 23:59
cc @steveharter

**Comment by steveharter** [comment] 2017-03-01 22:29
FYI last failure was 1/7/2017

Official build failures since 12\1\2016:
```
Test Case: System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: True)
Failed Jenkins Jobs
Build Number 	Machine Name 	Date
dotnet_corefx/master/outerloop_win10_debug 50 	win2016-9b32d0 	12/30 01:30 PM
dotnet_corefx/master/outerloop_win10_debug 53 	win2016-c4e0c0 	01/03 01:31 PM
dotnet_corefx/master/outerloop_windows_nt_release 61 	win2012-a995a0 	01/07 11:12 AM
```

```
Test Case: System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: True)
Failed Jenkins Jobs
Build Number 	Machine Name 	Date
dotnet_corefx/master/outerloop_win10_debug 47 	win2016-c006c0 	12/26 01:30 PM
dotnet_corefx/master/outerloop_win7_debug 57 	win2008-ebb680 	01/05 08:30 PM
```

**Comment by geoffkizer** [comment] 2017-03-01 23:26
I have not seen this recently either.

**Comment by stephentoub** [comment] 2017-04-12 22:36
Let's close it out and re-open if it shows up again.  It's possible it's been addressed by the various sockets fixes we've made over the last few months.

**Comment by steveharter** [comment] 2017-04-15 23:29
I can repro this on both Windows 2008 and Windows 10 CI machines when running in stress.

Exception same in both cases
```
   System.Net.Sockets.Tests.SendReceiveEap.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: False) [FAIL]
      System.AggregateException : One or more errors occurred. (Read poll after completion should have succeeded
      Expected: True
      Actual:   False)
      ---- Read poll after completion should have succeeded
      Expected: True
      Actual:   False
      Stack Trace:
            at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
            at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
            at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
            at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
         ----- Inner Stack Trace -----
            at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass22_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext()
```

**Comment by karelz** [comment] 2017-04-16 00:18
@steveharter how often does it repro in official CI? (milestone 2.0 vs. Future)
How often does it reproduce in your stress run? Is it the run-in-a-loop run or real GCStress run?

**Comment by steveharter** [comment] 2017-04-16 00:35
jdash results are sparse and localized to January and earlier:
```
dotnet_corefx/master/outerloop_win10_debug 53 win2016-c4e0c0 01/03 01:31 PM  0 
dotnet_corefx/master/outerloop_windows_nt_release 61 win2012-a995a0 01/07 11:12 AM  0 
dotnet_corefx/master/outerloop_win7_debug 57 win2008-ebb680 01/05 08:30 PM  0 
```

On Win10, it was a repeated loop (not GCStress) and occurred 5 times out of ~200 runs. Win 2008 was similar (~2% of tests failed because of this).

I have not been able to repro locally on Win10 (only on the CI machines)

**Comment by karelz** [comment] 2017-04-16 01:19
Did you mean January and later? -- I hope we have some recent data to look at in general ...

**Comment by steveharter** [comment] 2017-04-16 01:21
No, I meant earlier. There were some 'known' failures in 2016 (based on previous replies in this issue) that I did not report as the jdash query times become too long.

**Comment by karelz** [comment] 2017-04-16 01:22
So we have no history in jdash form 2017 February-April?

**Comment by steveharter** [comment] 2017-04-16 01:24
For this test, yes. Meaning it didn't fail since then or there were some gaps in jdash data.

**Comment by karelz** [comment] 2017-04-16 04:29
I still don't quite understand, sorry - jdash saves only failures, right? So if there is no failure since Feb, either it means it didn't fail since, or that some hiccup in jdash didn't record the new failure data. Is that correct?
Is there any general reason to believe that jdash lost some data since Feb?

**Comment by steveharter** [comment] 2017-04-17 14:24
Correct it hasn't failed since then or when it did fail, it failed during an outage. There hasn't been any jdash data loss AFAIK, only a couple gaps that I'm aware of, each lasting a few days at a time.

Given a 2-3% failure rate when running under a loop, that would fall into the bucket of fairly rare  (1\month or thereabouts) so in the range of moving to future.

**Comment by steveharter** [comment] 2017-04-17 15:21
Moving to future since does not meet current threshold, and because it is very similar to other existing issues which are already tracked.

**Comment by Jiayili1** [comment] 2017-04-24 09:41
This issue is repro on build 20170424.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170424.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveSync~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20127.0.0.1,%20pollBeforeOperation:%20False)

**Comment by Jiayili1** [comment] 2017-04-27 03:03
This issue is repro on Core Tests in build 20170427.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170427.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveApm~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20::1,%20pollBeforeOperation:%20True)

**Comment by Jiayili1** [comment] 2017-05-02 08:36
This issue is repro on outerloop_win7_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/32/testReport/System.Net.Sockets.Tests/SendReceiveApm/SendRecvPollSync_TcpListener_Socket_listenAt____1__pollBeforeOperation__True_/

**Comment by karelz** [comment] 2017-05-02 14:58
It seems to be now failing roughly 1/week

**Comment by danmosemsft** [comment] 2017-05-20 02:51
Again https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170520.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveApm~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20::1,%20pollBeforeOperation:%20True)

**Comment by karelz** [comment] 2017-05-21 05:34
This has higher frequency - @DavidGoll we should prioritize it in 2.1 schedule.

**Comment by v-haren** [comment] 2017-06-02 05:33
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_debug/62/testReport/System.Net.Sockets.Tests/SendReceiveSync/SendRecvPollSync_TcpListener_Socket_listenAt____1__pollBeforeOperation__True_/

**Comment by v-haren** [comment] 2017-07-05 05:55
failed again: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/109/testReport/System.Net.Sockets.Tests/SendReceiveSync/SendRecvPollSync_TcpListener_Socket_listenAt__127_0_0_1__pollBeforeOperation__True_/

**Comment by Jiayili1** [comment] 2017-07-14 07:18
This issue is repro on Core Tests (2.0.0), detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170714.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveApm~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20::1,%20pollBeforeOperation:%20True)

**Comment by Jiayili1** [comment] 2017-08-04 07:39
Failed again in CI: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/148/testReport/System.Net.Sockets.Tests/SendReceiveSyncForceNonBlocking/SendRecvPollSync_TcpListener_Socket_listenAt____1__pollBeforeOperation__False_/

**Comment by Jiayili1** [comment] 2017-08-22 06:39
it is now failing:
The test `System.Net.Sockets.Tests.SendReceiveSync/SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: False)` has failed.

System.AggregateException : One or more errors occurred. (Read poll after completion should have succeeded\r
    Expected: True\r
    Actual:   False)\r
    ---- Read poll after completion should have succeeded\r
    Expected: True\r
    Actual:   False

        Stack Trace:

           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 4676
       at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 4489
       at System.Net.Sockets.Tests.SendReceive$1<System.__Canon>.SendRecvPollSync_TcpListener_Socket($IPAddress listenAt, Boolean pollBeforeOperation) in E:\A\_work\390\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 625
       at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetVII<System.__Canon, System.Boolean>(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
       at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
       at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in CallDynamicInvokeMethod:line 16707566
    
    ----- Inner Stack Trace -----
       at System.Net.Sockets.Tests.SendReceive$1<System.__Canon>.<>c__DisplayClass7_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext() in E:\A\_work\390\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 582
    
Build : Master - 20170822.01 (UWP ILC Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x64
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170822.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveSync~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20127.0.0.1,%20pollBeforeOperation:%20False)

**Comment by Jiayili1** [comment] 2017-09-15 02:46
failed again: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170914.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveApm~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20127.0.0.1,%20pollBeforeOperation:%20True)

The test `System.Net.Sockets.Tests.SendReceiveApm/SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: True)` has failed.

System.AggregateException : One or more errors occurred. (An existing connection was forcibly closed by the remote host)\r
    ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host

        Stack Trace:

           at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
       at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
    ----- Inner Stack Trace -----
       at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass25_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext()
Build : 2.0.0 - 20170914.01 (Core Tests)
Failing configurations:
- windows.10.nanolatest.amd64-x64
  - Release

**Comment by Jiayili1** [comment] 2017-09-18 03:07
Now it failed with: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/250/testReport/System.Net.Sockets.Tests/SendReceiveTask/SendRecvPollSync_TcpListener_Socket_listenAt____1__pollBeforeOperation__True_/

MESSAGE:
Wait timed out\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in D:\j\workspace\outerloop_net---15cfbbd5\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 627

**Comment by wfurt** [comment] 2017-10-20 20:23
it failed times in september

**Comment by Jiayili1** [comment] 2017-10-23 02:33
This issue is repro in UWP F5 Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20171023.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveSync~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20::1,%20pollBeforeOperation:%20False)

The test `System.Net.Sockets.Tests.SendReceiveSync/SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: False)` has failed.

System.AggregateException : One or more errors occurred. (Read poll after completion should have succeeded\r
    Expected: True\r
    Actual:   False)\r
    ---- Read poll after completion should have succeeded\r
    Expected: True\r
    Actual:   False

        Stack Trace:

           at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
       at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in E:\A\_work\1345\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 625
    ----- Inner Stack Trace -----
       at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass7_1.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext() in E:\A\_work\1345\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 582
Build : Master - 20171023.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Amd64.ClientRS3-x64
  - Release

**Comment by Sunny-pu** [comment] 2017-11-15 08:16
failed again:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20171115.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveTask~2FSendRecvPollSync_TcpListener_Socket(listenAt:%20::1,%20pollBeforeOperation:%20False)

**Closed** 2017-12-05 15:27 UTC
Labels: area-System.Net.Sockets, bug, os-windows, test-run-core, test-run-uwp-coreclr, wishlist
