### ISSUE TITLE
System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeAndQuoteMime should allow quotes

### ISSUE THREAD

**Issue by uber5001** [dotnet/corefx#20816] opened 2017-06-08 15:51 UTC
If `System.Net.Http.Headers.ContentDispositionHeaderValue.FileName` is set to a value with quotes, [this](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs#L441) throws an error:

```c#
        private string EncodeAndQuoteMime(string input)
        {
            ...
            if (result.IndexOf("\"", 0, StringComparison.Ordinal) >= 0) // Only bounding quotes are allowed.
            {
                throw new ArgumentException(string.Format(CultureInfo.InvariantCulture,
                    SR.net_http_headers_invalid_value, input));
            }
            ...
        }
```

As far as I can tell, `quoted-string` should be allowed, as per [RFC 2616](https://tools.ietf.org/html/rfc2616#section-2.2). 

It seems strange that this error can be thrown at all, considering that you can even give it non-ASCII and it will encode it properly.

[EDIT] Add C# syntax highlighting by @karelz

**Comment by davidsh** [comment] 2017-06-08 16:11
Have you tried this on .NET Framework?  In general, we've keep the behaviors to match for app-compat reasons.

I'll review RFC2616 but that RFC is now obsoleted in favor of RFC7230+.

**Comment by uber5001** [comment] 2017-06-08 16:25
I'm using .NET Framework 4.7

**Comment by DavidGoll** [comment] 2017-06-17 00:23
Passing a string with *bounding* quotes is supported. The code referenced above is meant to detect embedded quotes after (temporarily) stripping the bounding quotes. Embedded quotes would be illegal per the RFC. The code may not be smart enough when stripping the bounding quotes. For example, if there are any other characters preceding the first quote or trailing the terminating quote, one or both of the quotes would remain and you'd get that exception. If this is the case, a workaround would be to sanitize the input before setting the FileName property.

**Comment by davidsh** [comment] 2017-07-13 18:29
What is the behavior on .NET Core?  This repo tracks issues for .NET Core.  Bug/issues for .NET Framework are tracked elsewhere.

**Comment by karelz** [comment] 2017-12-29 03:52
Seems that the behavior is by design and according to the RFC.
Closing.

**Closed by karelz** 2017-12-29 03:52 UTC
Labels: area-System.Net.Http, os-windows, question
