### ISSUE TITLE
RequestUri case modification while being used in HttpClient causes problem inside docker

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/corefx#36247] opened 2019-03-22 22:33 UTC
**What is wrong**
Making connection to http://ttt.CP.com fails inside docker with aliases, although at the same time all Linux tools woks fine with that address.

**Details**
I noticed that case is changed when sending requests and (although it seems cases should not matter for domain names) it will cause problem in Windows using dockers.

Program.cs
```
using System;

namespace ConsoleApp16
{
    class Program
    {
        static void Main(string[] args)
        {
            var client_ = new System.Net.Http.HttpClient();
            using (var request_ = new System.Net.Http.HttpRequestMessage())
            {
                request_.Method = new System.Net.Http.HttpMethod("GET");
                request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                request_.RequestUri = new System.Uri("http://ttt.CP.com", System.UriKind.RelativeOrAbsolute);

                var response_ = client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead).GetAwaiter().GetResult();
            }
        }
    }
}
```

my docker-compose.yml
```
version: '2.4'
services:
  nginx:
    image: nginx
    expose:
     - "80"
    networks: 
      mynetwork2:
        aliases:
          - ttt.CP.com

  myapi:
    build: .
    networks: 
      mynetwork2:
        aliases:
          - aaa.CP.com
           
   
networks:
  mynetwork2:
    driver: bridge
```

Dockerfile
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build
WORKDIR /src
COPY TestProgram/ TestProgram/
WORKDIR /src/TestProgram
ENTRYPOINT ["dotnet","run"]
#ENTRYPOINT ["/bin/bash"]
```

TestProgram.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

</Project>
```

docker version
```
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

Now if you run `docker-compose up` you will get
```
myapi_1  |
myapi_1  | Unhandled Exception: System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
myapi_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
myapi_1  |    --- End of inner exception stack trace ---
myapi_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
myapi_1  |    at System.Threading.Tasks.ValueTask`1.get_Result()
myapi_1  |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
myapi_1  |    at System.Threading.Tasks.ValueTask`1.get_Result()
myapi_1  |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
myapi_1  |    at System.Threading.Tasks.ValueTask`1.get_Result()
myapi_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
myapi_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
myapi_1  |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
myapi_1  |    at ConsoleApp16.Program.Main(String[] args) in /src/TestProgram/Program.cs:line 16
```

But if you get into docker (`docker-compose run --entrypoint /bin/bash myapi`)
```
root@6a612eff59c3:/src/TestProgram# ping ttt.CP.com
PING ttt.CP.com (172.20.0.3) 56(84) bytes of data.
64 bytes from dtest_nginx_1.dtest_mynetwork2 (172.20.0.3): icmp_seq=1 ttl=64 time=0.128 ms

root@6a612eff59c3:/src/TestProgram# nslookup ttt.CP.com
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   ttt.CP.com
Address: 172.20.0.3

root@6a612eff59c3:/src/TestProgram# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.20.0.2      6a612eff59c3

root@6a612eff59c3:/src/TestProgram# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

root@6a612eff59c3:/src/TestProgram# dig 127.0.0.11 ttt.CP.com

; <<>> DiG 9.10.3-P4-Debian <<>> 127.0.0.11 ttt.CP.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35646
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;127.0.0.11.                    IN      A

;; Query time: 49 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Fri Mar 22 22:30:53 UTC 2019
;; MSG SIZE  rcvd: 28

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9856
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ttt.CP.com.                    IN      A

;; ANSWER SECTION:
ttt.CP.com.             600     IN      A       172.20.0.3

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Fri Mar 22 22:30:53 UTC 2019
;; MSG SIZE  rcvd: 54


root@6a612eff59c3:/src/TestProgram# curl ttt.CP.com
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Workarounds:
- change `ttt.CP.com` to `ttt.cp.com` in .net console program.
- adding a new aliases in `docker-compose.yml`
```
        aliases:
          - ttt.CP.com
          - ttt.cp.com
```

But while all tools work fine in OS,I assume net core application should not lower case the domain name!

**Comment by roozbehid-ic** [comment] 2019-03-22 22:41
Tested with `mcr.microsoft.com/dotnet/core/sdk:2.2` and `<TargetFramework>netcoreapp2.2</TargetFramework>`, still same error!

**Comment by wfurt** [comment] 2019-03-27 18:00
The ' No such device or address' is definitely name lookup failure. .Net depends on OS functions there and I'm not aware of any trickery inside PAL layer. You can try to get packet capture either using tcpdump or Wireshark. Use filter "port 53 and host 127.0.0.11" When you run the HTTP fragment it should do lookup and we may see more info. 

BTW could you try same container and code running on Linux host? It seems like ttt.CP.com does not resolve from outside of your network.

**Comment by roozbehid-ic** [comment] 2019-03-29 16:45
@wfurt I think I did not explain the issue correctly.

The problem clearly to me is that .Net is making a conversion from "ttt.CP.com" to "ttt.cp.com" (lower casing it) and then uses OS functions.
Because adding a new alias of "ttt.cp.com" inside my docker-compose will resolve the issue.

And clearly all OS tools such as ping, dig, curl somehow manage to use "ttt.CP.com" and not "ttt.cp.com" as they do work fine. Also they wont work if I do "curl ttt.cp.com".

ttt.CP.com does not resolve from outside of my network. it is some fake domain name inside docker bridges.

**Comment by davidsh** [comment] 2019-03-29 16:54
>The problem clearly to me is that .Net is making a conversion from "ttt.CP.com" to "ttt.cp.com" (lower casing it) and then uses OS functions.

Why is this a problem?  DNS names in general are case insensitive.  It should matter what the networking stack does in terms of lower-case canonicalization.

**Comment by wfurt** [comment] 2019-03-29 17:49
I agree with @davidsh. Name lookup is case insensitive. (you can try that with ping or dig) 
The problem lives somewhere else. 

I just noticed 127.0.0.X as your resolver. Could you try to start your container with --dns=x.x.x.x and pass real name-server address? (or edit /etc/resolv.conf and give it same content as your host configuration)

**Comment by roozbehid-ic** [comment] 2019-03-29 21:45
> Why is this a problem?
Because it caused an exception and testing with OS tools none of them reported a problem. So this tells me it is generally not a problem with OS tools! Anyway why .Net goes into more work and lowercases dns names when it can preserve my formating?


> I agree with @davidsh. Name lookup is case insensitive. (you can try that with ping or dig)
> The problem lives somewhere else.
Well I tried with ping and dig as you can see in the first post and all of them returned result to me. so ping and dig tools while passing those information to OS stack do not change or lowercase dns name, they let the OS decide what to do. Why not do the same in .Net?

> I just noticed 127.0.0.X as your resolver. Could you try to start your container with --dns=x.x.x.x and pass real name-server address? (or edit /etc/resolv.conf and give it same content as your host configuration)
So you mean add an entry in /etc/resolv.conf with ttt.CP.com ? I'll try that this afternoon, I have to figure out how that works....

**Comment by wfurt** [comment] 2019-03-29 21:54
no, you should not put name to /etc/resolv.conf . What I want is avoiding use of dnsmasq or docker involvement. It is not clear what the problem actually is and answering our questions would help. 
Since we cannot reproduce it, this is not actionable otherwise.

**Comment by roozbehid-ic** [comment] 2019-03-29 21:55
I also found this https://github.com/moby/moby/issues/21169
So it seems it's been an issue with docker from 2016 and still an issue. 

So in short, while using dockers, host names created in networks are case sensitive.
So what is the workaround here?

**Comment by wfurt** [comment] 2019-03-29 22:02
what server/process serves your CP.com zone?  Without knowing more about your topology, it is hard to give specific answers. Can you make everything lowercase? Even if the specification says  comparison and lookup should be case insensitive, using lowercase seems to be most common.
You can of course put explicit entry to /etc/hosts. That may or may not work depending how often that changes e.g. is ttt somewhat static or is it on random dhcp?

**Comment by davidsh** [comment] 2019-04-01 18:08
>So in short, while using dockers, host names created in networks are case sensitive.
So what is the workaround here?

The comment [here](https://github.com/moby/moby/issues/21169#issuecomment-299840402) summarizes why the .NET networking stack lowercases hostnames.  It is part of the normal canonalication process for the Uri.

The issue here is due to a bug in the Docker component.

According to [this](https://github.com/moby/moby/issues/21169#issuecomment-343960114) comment, , the problem can be worked around as follows:

```
You can disable this by putting options randomize-case:0 in the /etc/resolve.conf
```

**Comment by davidsh** [comment] 2019-04-01 18:10
The root cause is a problem with [Docker](https://github.com/moby/moby/issues/21169) and not an issue with CoreFx.  We will close this issue then.

**Closed by davidsh** 2019-04-01 18:10 UTC
Labels: area-System.Net.Http
