### ISSUE TITLE
WMI support in NetStandard 1.5

### ISSUE THREAD

**Issue by jmroyb** [dotnet/corefx#18932] opened 2017-04-25 16:46 UTC
Folks,

can you tell if WMi is supported in NetStandard 1.5? I cannot find System.Management namespace ....

If not supported, do you plan to supported it and when?

Thanks a million

**Comment by ViktorHofer** [comment] 2017-04-25 17:09
I doubt it will ever be added to netstandard as WMI is Windows specific. Netstandard (minus a few exceptions) only contains APIs which are cross-platform in nature.

**Comment by karelz** [comment] 2017-04-26 01:02
Looks like dupe of #14762 to add it into .NET Core.

**Closed by karelz** 2017-04-26 01:02 UTC
Labels: question

**Comment by jmroyb** [comment] 2017-04-26 10:19
Thanks karelz for your update
