### ISSUE TITLE
WinHttpResponseStream.CopyToAsyncCore sporadically throws IOException

### ISSUE THREAD

**Issue by avtc** [dotnet/corefx#23504] opened 2017-08-23 15:38 UTC
I have an self-hosted (kestrel) asp net web api site, based on net core.
On application startup i am using single instance of `HttpClient` (with "Connection: keep-alive") to touch `/post` endpoint (with different payloads) of that site, and after that mark it as healthy (so called warm up).
`/post` endpoint uses its own `HttpClient` to send dto, serialized as string, to third party endpoint.
During warm up, instead of third party endpoint, i use same site endpoint, like `http://localhost:80/fake-third-party-response/`, where i return sample string that is expected from third party.

And there comes an Issue - during integration tests (i am using nunit, inside test self hosted kestrel site is started), `WarmupService` produce errors, not always, but in about 20% cases test is failed.
Errors are caught inside `/post` endpoint, when it tries to do:
`PostAsync(new StringContent(someText, System.Text.Encoding.UTF8, "text/xml")` with "Connection: close" headers, using `HttpClient`.
`HttpClient` in `/post` endpoint is created each time new, and disposed.
`HttpResponseMessage` as a result of `PostAsync` call is also disposed.
Test itself making about 50 calls to `/post` endpoint (so overall calls could be 100).

Issue appears on Windows OS, i tried with netcoreapp1.1 and netcoreapp2.0, System.Net.Http 4.3.0 and 4.3.2.

Stack trace:
```csharp
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The operation completed successfully
   --- End of inner exception stack trace ---
   at System.Net.Http.WinHttpResponseStream.<CopyToAsyncCore>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
```

**Comment by karelz** [comment] 2017-08-23 17:18
Do you have isolated repro? (ideally without any unnecessary components like nunit, Kestrel, etc.)

**Comment by avtc** [comment] 2017-09-11 16:26
Repo: https://github.com/avtc/HttpClient-CopyToAsyncCore-Ex
To reproduce: Ctrl+F5 to run SampleApp as self-hosted web app.
Errors will be printed to console output (to pause console - left click on console window).

Issue is reproduced when conditions are met:
1) Kestrel self-hosted web app as a server.
    - "System.Net.Http.HttpRequestException: Error while copying content to a stream." is reproduced, only in case server is running as self-host.
   - "System.Net.Http.WinHttpException: Not enough storage is available to process this command" is reproduced for self-host and IIS Express also.
2) Http client is used for "Post" inside Task.Run
3) Windows OS.
4) Reproduced when 150-1000 requests are issued in short term.

**Comment by karelz** [comment] 2017-09-11 17:48
Is it reproducible outside of Kestrel? (trying to narrow it down to fewer technologies and moving parts involved)

**Comment by avtc** [comment] 2017-09-11 21:47
"System.Net.Http.HttpRequestException: Error while copying content to a stream."
- is not reproduced on [HTTP.sys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys) self-host.
- is reproduced on Kestrel.

"System.Net.Http.WinHttpException: Not enough storage is available to process this command"
- is not reproduced on another PC (with Windows 10 Pro), checked with 50_000 sequential posts.

**Comment by davidsh** [comment] 2017-09-27 21:59
I tried the repro here:
https://github.com/avtc/HttpClient-CopyToAsyncCore-Ex

But I got this error:
>Severity	Code	Description	Project	File	Line	Suppression State
Error		Visual Studio Container Tools requires Docker CE for Windows.  To get it, see https://go.microsoft.com/fwlink/?linkid=847268
For more info, please see: http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	163	

Do you have a repro that doesn't require Docker?

**Comment by karelz** [comment] 2018-01-17 23:03
Triage: Next step - verify we can reproduce.

**Comment by rmkerr** [comment] 2018-01-24 23:11
Thanks for the great repro @avtc, that was very easy to set up. I'm able to reproduce the issue and I'll be looking into what is going on here over the next few days.

**Comment by rmkerr** [comment] 2018-01-25 23:51
I've looked into what is going on with the repro, and think I've got some idea of what is happening. Here's a network capture of a "POST" that threw an exception. The values are listed in the order they are sent.

The client begins sending the POST, but notice how it doesn't send the data yet:
```
POST /api/values/fake/50 HTTP/1.1
Connection: close
Content-Type: application/json; charset=utf-8
Content-Length: 41
Host: localhost:50614
```
The server responds as soon as it has received the headers, and does not wait for the request body:
```
HTTP/1.1 200 OK
Connection: close
Date: Thu, 25 Jan 2018 19:37:02 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

7
fake-50
0
```
The client finishes sending the request body:
```
http://localhost:50614/api/values/fake/50
```  
Notice how the server responds _before the client has even finished sending the message_. For more detail we can look at the TCP stream:

![image](https://user-images.githubusercontent.com/4656175/35418034-e4766808-01e4-11e8-84fa-cc1f9f0dcde5.png)


Notice how the server closes the connection with a [FIN, ACK] once it has replied to the message. It does this despite not having received all of the original request. The client ACKs the FIN, but still sends the rest of the request. When the rest of the request arrives (Packet No. 15668 above) the server has already closed the connection and so responds with a RST which I believe causes the exception you are seeing.

This whole process raises several questions for me. I'm not sure why it takes HttpClient nine seconds from when it sends the headers to when it sends the data. I'm also not sure why we see the particular exception that is being thrown, and why our implementation seems to be sending the rest of the request despite having ACK'd the FIN sent by the server. I'm not an HTTP expert so I'll be looking into whether or not this is a behavior we should support. If it turns out not to be, this is probably an issue to bring up with Kestrel rather than here.

**Comment by halter73** [comment] 2018-01-26 00:56
@rmkerr Good observations. Kestrel will sometimes send a FIN immediately when the response completes without waiting to receive the entire request, but only if a few conditions are met.

1. The request must contain a request body.
2. The server application/middleware did not consume the entire request body itself.
3. The request was made over a non-keep-live connection. One case this happens is when there's a "Connection: close" request header as is the case here. This behavior was added to work around [an issue](https://github.com/aspnet/KestrelHttpServer/issues/418) with running Kestrel behind nginx proxy with a default configuration.

So as you can imagine, there's probably a few workarounds to the issue you're experiencing. The simplest might be to add some middleware that does something like the following:

```c#
app.Use(async (context, next) =>
{
    await next();
    await context.Request.Body.CopyToAsync(Stream.Null);
});
```

I filed aspnet/KestrelHttpServer#2276 with the suggestion of basically doing what the above middleware does be default even for non-keep-alive connections.

I still think that this is an issue that should also be fixed in WinHttpResponseStream. If a complete response was received, you should be able to read it even if there's a subsequent connection reset for the still-ongoing request body upload.

**Comment by davidsh** [comment] 2018-01-26 01:01
>I still think that this is an issue that should also be fixed in WinHttpResponseStream. If a complete response was received, you should be able to read it even if there's a subsequent connection reset for the still-ongoing request body upload.

That is not going to be possible to fix in WinHttpHandler since it is built on native WinHttp.  Despite the fact that the HTTP protocol allows for response headers to arrive around the same time as the request body is being uploaded, WinHttp does not process the response headers until the request body is done uploading.  The sequence of calls to the WinHttp APIs are pretty rigid regarding this.

If there is an I/O error in the uploading of a request body, then this will kill the response processing.  And thus there is no HttpResponseMessage returned from the handler's SendAsync() method.  There will simply be an exception wrapped in an HttpRequestException for the HttpClient.PostAsync() method etc.

**Comment by rmkerr** [comment] 2018-01-26 18:53
After doing a bit more research and talking to other members of the team, I'm going to go ahead and close this issue. I think that fundamentally it doesn't make sense for us to accept the response to a message that has technically failed to send. That appears the be the behavior of native WinHttp, so there is some precedent. Thank you both for the help on understanding what was happening here, and for providing a workaround.

**Closed by rmkerr** 2018-01-26 18:53 UTC
Labels: area-System.Net.Http, bug, os-windows
