### ISSUE TITLE
JsonElement cannot write scientific number with decimal point

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#39325] opened 2019-07-09 17:10 UTC
```csharp
[Fact]
public static void WriteScientificNumber()
{
    var buffer = new ArrayBufferWriter<byte>(1024);
    using (JsonDocument doc = JsonDocument.Parse($" [ 1.2e-3 ]", s_options))
    {
        JsonElement target = doc.RootElement[0];
        var writer = new Utf8JsonWriter(buffer);
        target.WriteValue(writer);
    }
}

System.ArgumentException : 'e' is an invalid end of a number. Expected a delimiter. (Parameter 'utf8FormattedNumber')
Stack Trace:
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Writer\JsonWriterHelper.cs(224,0): at System.Text.Json.JsonWriterHelper.ValidateNumber(ReadOnlySpan`1 utf8FormattedNumber)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Writer\Utf8JsonWriter.WriteValues.FormattedNumber.cs(28,0): at System.Text.Json.Utf8JsonWriter.WriteNumberValue(ReadOnlySpan`1 utf8FormattedNumber)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Document\JsonDocument.cs(903,0): at System.Text.Json.JsonDocument.WriteElementTo(Int32 index, Utf8JsonWriter writer)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Document\JsonElement.cs(1355,0): at System.Text.Json.JsonElement.WriteValue(Utf8JsonWriter writer)
D:\dotnet\corefx\src\System.Text.Json\tests\JsonElementWriteTests.cs(56,0): at System.Text.Json.Tests.JsonElementWriteTests.WriteEmptyArray()
```

**Comment by ericstj** [comment] 2019-07-10 16:28
This is a duplicate of https://github.com/dotnet/corefx/issues/39139

**Closed by ericstj** 2019-07-10 16:28 UTC
Labels: area-System.Text.Json, bug
