### ISSUE TITLE
BinaryFormatter deserializes items in generic list as nulls

### ISSUE THREAD

**Issue by mderoy** [dotnet/corefx#31105] opened 2018-07-16 21:24 UTC
I have a simple example, which fails
```c#
        static void AssertAreEqual(Item a, Item b)
        {
            if(a.value != b.value)
                throw new Exception("Not Equal");
        }

        static void Main(string[] args)
        {
            var a = new ContainerOfItems();
            a.AddItem(1);
            a.AddItem(2);
            a.AddItem(3);
            a.AddItem(4);
            var b = Deserialize<T>(Serialize(a));

            AssertAreEqual(a.GetItem(0), b.GetItem(0));
            AssertAreEqual(a.GetItem(1), b.GetItem(1));
            AssertAreEqual(a.GetItem(2), b.GetItem(2));
            AssertAreEqual(a.GetItem(3), b.GetItem(3));
        }
```

ContainerOfItems is a class, which contains a List<Item> which implements ISerializable, and Item is a class wrapping an int, which implements ISerializable (both are marked with the serializable attribute as well)

In the given example, I find that when b is deserialized, I get a list of the correct size, but all values are null.

If I serialize an additional field

```
            //UCOMMENT THE BELOW LINE AND IT WORKS?!!?!?!
			//Serialize last item
			//info.AddValue("lastItem", lastItem, typeof(Item));
```

Then the values in the List are no longer null, and my asserts all pass.

I've uploaded an example that exhibits this behavior in VS2017 with .net core 2.1
[ReproDeserializationBug.zip](https://github.com/dotnet/corefx/files/2199334/ReproDeserializationBug.zip)

To make it easier to look at the bug, here is the serialize and deserialize functions

```
        private static MemoryStream Serialize<T>(T o)
        {
            MemoryStream stream = new MemoryStream();
            IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(stream, o);
            return stream;
        }

        private static T Deserialize<T>(MemoryStream stream)
        {
            IFormatter formatter = new BinaryFormatter();
            stream.Seek(0, SeekOrigin.Begin);
            object obj = formatter.Deserialize(stream);
            return (T)obj;
        }
```

**Comment by karelz** [comment] 2018-07-17 00:38
cc @ViktorHofer 
Is it a regression against .NET Core 2.0 or against .NET Framework?

**Comment by ViktorHofer** [comment] 2018-07-17 09:52
Thanks for the repro, I quickly ran through it and probably found the reason for it:

```csharp
var itemsToDeserialize = (List<Item>)info.GetValue("items", typeof(List<Item>));
items = new List<Item>();
foreach (Item item in itemsToDeserialize)
{
    items.Add(item);
}
```

If you change this to

```csharp
items = (List<Item>)info.GetValue("items", typeof(List<Item>));
```

The reason why the former doesn't work is that at the time you get back the container and store it in `itemsToDeserialize`, the items haven't yet been deserialized. This is because you are still inside the deserialization ctor of `ContainerOfItems`. If you want to manipulate data you should do this when deserialization is done, either when the object construction is finished or inside a method attributed with `OnDeserializedAttribute`: https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ondeserializedattribute(v=vs.110).aspx or with `DeserializationCallback.OnDeserialization`: https://msdn.microsoft.com/en-us/library/system.runtime.serialization.ideserializationcallback(v=vs.110).aspx.

Will close this for now. Feel free to reopen if you have more questions. Thanks.

**Closed by ViktorHofer** 2018-07-17 09:52 UTC
Labels: area-System.Runtime, bug
