### ISSUE TITLE
Net Platform Standard Question

### ISSUE THREAD

**Issue by seesharper** [dotnet/corefx#8828] opened 2016-05-24 21:45 UTC
I am the author of the LightInject DI framework and I am trying to get things out the door based on the new RC2 bits

This means moving from the old TFM's (DNX451 and DNXCORE50) to the new (and hopefully final) NETSTANDARDx.x TFM´s.

Okay, so let's start with what I used to do prior to this. 

The Nuget Package used to contain a version of lightinject.dll for each platform. These platforms were net45, net46, dnx451, dnxcore50 and PCL Profile 111 (to be used with xamarin). 

Moving to the new TFM's I have replaced DNX451 with NetStandard1.1 and DNXCORE50 with NetStandard1.3. 

This is where things start to get a little wierd. 

If I try to install into a plain NET46 class library, NuGet still wants to install the dependencies declared for NetStandard1.3 even though it (correctly) picks the assembly in the net46 folder in the nuget package. I solved this by creating an empty entry in the nuspec file that explicitly states that net46 has no dependencies to any of the new RC2 net standard packages.

```
      <dependencies>
        <group targetFramework=".NETFramework4.5" />
        <group targetFramework=".NETFramework4.6" />
```

Okay, so that is solved (God knows why), moving on to my PCL version.

The PCL is profile 111 and installing into a Xamarin.iOS project, it picks the netstandard1.3 which is sort of correct according to https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md , but I really need it to pick the PCL version when on aot (ahead of time) platforms. The .Net platform standard document states that given netstandard1.3 it should run on iOS so in that sense it is understandable that it picks the "closest" match. Problem is that netstandard1.3 basically means net46 and there is a lot of stuff there that does not work on iOS such as reflection.emit and many other things. 

I really don't understand how this is supposed to work. I have an assembly that is "netstandard1.3" but why does it get prioritized for an iOS project over the PCL version? 

I perfectly understand the motivation behind the platform standard being open ended and all, but I simply don't understand how to distinguish between runtimes.

**Comment by ericstj** [comment] 2016-05-26 17:57
Thanks for a good write up of this situation.

> Okay, so that is solved (God knows why)

NuGet selects each asset group independently.  So it chooses the best dependency group, the best ref, the best lib, etc.  You would have had the same problem before if you had dependencies specific to your PCL library (since that PCL moniker would have also applied to desktop).

@joelverhagen / @emgarten / @davidfowl what are the precedence rules for Xamarin platforms?  In the past I thought portable-a+b+c would win over NETStandard, but that doesn't seem to be what's happening here.

Also, this issue should probably be opened in the http://github.com/nuget/home repo as that is where all the code lives and where this needs to be documented.  FWIW, this [issue](https://github.com/NuGet/Home/issues/358) is supposed to be tracking better documentation of NuGet's fallback algorithm.

**Comment by davidfowl** [comment] 2016-05-30 07:33
I believe PCL does win over netstandard (last time I verified that) but I haven't tried it with Xamarin (though it shouldn't be any different).

**Comment by ericstj** [comment] 2016-05-31 18:23
I've confirmed @seesharper's report.  NuGet is picking `netstandard1.3` over `portable-net45+netcore45+wpa81` for `Xamarin.iOS`.  Oddly though, it picks `portable-net45+netcore45+wpa81` over `netstandard1.1` for `WindowsPhoneApp`.  We really need clarity on how this is supposed to behave.  I'm closing this and ref-counting the NuGet issue.

**Closed by ericstj** 2016-05-31 18:23 UTC
Labels: documentation, question
