### ISSUE TITLE
Regression  System.Net.Sockets.Tests.DualMode.SendToV4IPEndPointToV6Host_NotReceived (from (empty))

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8868] opened 2016-05-25 23:35 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/osx_release_prtest/24/testReport/junit/System.Net.Sockets.Tests/DualMode/SendToV4IPEndPointToV6Host_NotReceived/

Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(System.Net.Sockets.SocketException): Connection refused
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP) at System.Net.Sockets.Tests.DualMode.DualModeSendTo_IPEndPointToHost_Helper(IPAddress connectTo, IPAddress listenOn, Boolean dualModeServer, Boolean expectedToTimeout)

Test failure in PR https://github.com/dotnet/corefx/pull/8863

**Comment by ericeil** [comment] 2016-05-25 23:44
Duplicate of #8636.

**Closed by ericeil** 2016-05-25 23:44 UTC
Labels: Mac OS X, System.Net
