### ISSUE TITLE
Web requests abnormally slow

### ISSUE THREAD

**Issue by ssougnez** [dotnet/corefx#23919] opened 2017-09-09 23:17 UTC
Hi,

in my current project, I'm trying to make a web request in C# by using the following code (a bit modified for the sake of this post):

```c#
private static void WithWebRequest()
{
    Stopwatch sw = new Stopwatch();

    sw.Start();

    var request = WebRequest.Create("http://www.dot.net");

    using (WebResponse response = request.GetResponse())
    {
        using (StreamReader sr = new StreamReader(response.GetResponseStream()))
        {
            string content = sr.ReadToEnd();

            sw.Stop();

            Console.WriteLine(content);

            Console.WriteLine($"Response got in {sw.ElapsedMilliseconds / 1000}");
        }
    }
}
```

I'm pretty sure it used to work pretty well when I was using ASP.NET Core 2.0 but since I upgraded to ASP.NET Core 2.1 (2.1.0-preview1-26907) (because I need it to use SignalR Core), it seems that requests take for ages to execute. As you can see, I used `Stopwatch` to measure the duration of the call and it is generally about 45 seconds, give or take. I usually have the time to open a new browser instance and navigate to the URL by myself while the request is called.

I also tried with `HttpClient`:

```c#
private static void WithHttpClient()
{
    Stopwatch sw = new Stopwatch();

    sw.Start();

    using (var client = new HttpClient())
    {

        client.BaseAddress = new Uri("http://www.dot.net");

        var content = client.GetStringAsync(string.Empty).Result;

        sw.Stop();

        Console.WriteLine(content);

        Console.WriteLine($"Response got in {sw.ElapsedMilliseconds / 1000}");
    }
}
```

And I obtain approximately the same result. I also tried to use "async" execution and it didn't solve it.

[EDIT] Added C# syntax highlight by @karelz

**Comment by karelz** [comment] 2017-09-10 10:11
Can you reproduce the same on latest (daily) build of .NET Core 2.1?

**Comment by ssougnez** [comment] 2017-09-10 11:03
Hello, I just installed the version 2.1.0.7186 (I think it's the latest one) of .NET Core and the problem remains. Just to be sure, here is what's installed on my machine:

- Microsoft .NET Core SDK 2.1.0 - Preview (x64) - 2.1.0.7186
- Microsoft .NET Core SDK - 2.0.0 (x64) - 2.0.0
- Microsoft Core SDK 1.1.0 (x64) - 1.1.0

The example above has been developed with Visual Studio Community 15.3.3 (not that it really matters). It's a freshly created console application with the following csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

Note that I also have the same behavior coming from an ASP.NET Core Web API controller.

Cheers

**Comment by karelz** [comment] 2017-09-10 20:23
That is concerning serious regression between 2.0 and 2.1/master - @geoffkizer @Priya91 @wfurt any idea what might introduce it?

**Comment by davidsh** [comment] 2017-09-10 23:28
cc: @stephentoub 

My thoughts on this:

It is really difficult to track down these kind of reports without having the exact repro as well as some "good" vs. "bad" timings.  The code above doesn't use any async practice patterns.  Perhaps there is some UI thread deadlocking happening which is slowing down the networking responses.  Hard to tell from the code snippet.

The best way to research this type of thing is as follows:

1. We need a complete repro which means a ZIP file of a Visual Studio solution.  This will show the exact client source code being used, as well as what package dependencies are being loaded.  And if the server being accessed in not on the Internet, then we need a copy of the server code, i.e. perhaps it is some localhost ASP.NET server as noted above.

2. We need to see a printout of the observed "good" vs. "bad" timings. This will give us an idea of what is going on for the user reporting the bug.

There are references to ASP.NET Core in this report.  Perhaps that is actually part of the problem that needs to be investigated. It seems the server being used (in the repro above) is "www.dot.net" That simply redirects to "www.microsoft.com".  I'm not sure if that particular server is the one that is being measured against, or whether that is just a placeholder for some other server defined by ASP.NET implementations.

**Comment by ssougnez** [comment] 2017-09-11 06:27
Hello,

I just tried my code on a different laptop and I don't have the issue on it... Maybe a configuration issue on the other one, I'll check that later that day and come back to you.

Regards

**Comment by karelz** [comment] 2017-09-11 13:29
OK, closing until it is proven more-than-one-machine problem.

**Closed by karelz** 2017-09-11 13:29 UTC
Labels: area-System.Net.Http, bug, tenet-performance

**Comment by liaowubinf** [comment] 2018-10-20 07:48
I have the same problem, it run good on my develop machine, but when i publish it to the windows server, it goes extremely  slow, more than ten seconds, it run good when i did not install v2.1.5 Runtime, but i can't slove it even if i uninstal the v2.1.4 or v2.1.5

**Comment by ssougnez** [comment] 2018-10-20 09:31
Hi, if I remember well, my problem was actually external at .Net. Indeed I had create an inbound rule in my firewall and I guess I did it wrong. When I removed this rule, requests went fast again.

**Comment by karelz** [comment] 2018-10-20 16:49
@liaowubinf it is likely some network configuration problem on your network.
The easiest way to double-check that is to collect network capture traces and analyze them - e.g. Wireshark.

**Comment by logic01** [comment] 2019-03-12 14:26
Hello, we saw similar issues with upgrading from core 2.0 to core 2.1. We rolled back to 2.0 because our spike in network calls was 100x and our enterprise application slowed to a crawl. We have been working with Microsoft Reps thinking it was the server but in the end the 'rollback' resolved all speed issues. 

We where only seeing the slowdown in our Development and Test domains (about 4 servers in each) while we did not see the slowdown in our UAT, Stage, Production servers. It is possible that we have different networking rules in each.

That said, is there a set of network rules we should be investigating? What changed between core 2.0 and 2.1 that would suddenly trigger firewalls or other network configurations to slow down requests? Any direction would be useful.

**Comment by wfurt** [comment] 2019-03-12 17:28
You can try to set DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=false environment @logic01 to see if that makes any different. If you have lot of parallelism or IO, you may try to increase thread-pool size. New handler introduced in 2.1 uses it quite a bit more.

**Comment by wfurt** [comment] 2019-03-12 17:30
What was it set to before @liaowubinf ? The handler will get default proxy setting from environment on Unix or system setting on Windows. In second case the default is usually "auto" and that will perform network discovery.
