### ISSUE TITLE
[WinHttpHandler] Digest authentication resubmit differences between WinHttpHandler & SocketsHttpHandler

### ISSUE THREAD

**Issue by rmkerr** [dotnet/corefx#28522] opened 2018-03-27 22:23 UTC
This behavior difference causes a hang in the HTTP authentication tests. I'll summarize the issue here, with my thoughts at the bottom. I've been wrong about this particular failure before, so I'll try to stick to just the facts :)

In two of the `WWW-Authenticate` header test cases, an invalid `Digest` scheme will cause `WinHttpHandler` to resubmit the original request. `SocketsHttpHandler` will instead close the connection and return the 401 response immediately. The Wireshark traces below demonstrate both cases, with `SocketsHttpHandler` on the left.

Digest with an unsupported algorithm:
![image](https://user-images.githubusercontent.com/4656175/37983480-7575dd50-31a8-11e8-9850-6a7ae55de978.png)
Digest with no realm or nonce:
![image](https://user-images.githubusercontent.com/4656175/37983564-a798ffce-31a8-11e8-971b-0df28f1a1baf.png)
The extra newline in the SocketsHttpHandler case is added by wireshark and is not a part of the actual message. Note that I modified the test slightly while getting these screenshots -- I stopped the loopback server from closing the connection immediately after the 401, which was causing a hang in `WinHttpHandler` when it sent the second get request and got no response. The test case is still the same for both handlers.

The re submission happening in WinHttpHandler is primarily caused by WinHttp. We make the following call to query supported auth schemes:
https://github.com/dotnet/corefx/blob/b458c89b34ba2a84858312a487066bdc2ba350e3/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpAuthHelper.cs#L90-L95
In both cases WinHttp returns the value `WINHTTP_AUTH_SCHEME_DIGEST`, indicating that digest authentication is the only supported scheme. We then set the credentials, but when the request is sent WinHttp has not included them.

**Opinions below:**
I think that the `SocketsHttpHandler` behavior is correct, and that the `WinHttpHandler` behavior should be considered a (minor) bug. Since we rely on WinHttp to determine what auth schemes are available, I would tentatively call this a WinHttp bug. For the time being, I'd like to modify the test to support both cases. I'd like to hear what others think though.

**Comment by davidsh** [comment] 2018-05-08 16:15
>Since we rely on WinHttp to determine what auth schemes are available, I would tentatively call this a WinHttp bug.

This is not really a bug in WinHttp.  In both SocketsHttpHandler and WinHttpHandler, the net result is that the request will end up authenticated and final 401 is returned by the HttpClient APIs.

The only difference between the two handlers is that WinHttpHandler ends up with an extra 401 round-trip. But in general, this is unavoidable due to the architecture of WinHTTP APIs.  WinHttp is not validating the Digest scheme parameters until we try to do the second roundtrip.  There are no other WinHttp APIs to call to validate the schemes presented by the server other than to call 'WinHttpQueryAuthSchemes` which enumerates them.  But it doesn't really validate all the parameters on them until our second round trip.  We could try to optimize this by doing our own validation of the Authorization headers. Or you could call this a "bug" in WinHTTP since maybe `WinHttpQueryAuthSchemes` should return an error right away.  But then, doing so might mask other valid schemes that the server presented.

This limitation in WinHTTP is just for the Digest scheme.  There are probably other schemes that could have parameter validation errors.  But those wouldn't be parsed until we try to process a scheme we (HttpClient) picks and then do the second round-trip to have WinHttp do authentication.

Our test (a negative test for validating failures to authenticate) shouldn't be counting the number of round trips to the server.  It should simply validate that a final 401 is received by the client.  It's good that SocketsHttpHandler is more optimal (i.e. doesn't waste a round-trip).

**Comment by caesar1995** [comment] 2018-05-08 17:40
I think this might be the root cause for  #26722.

**Comment by davidsh** [comment] 2018-05-08 17:43
>I think this might be the root cause for #26722.

#26722 has a different root cause as I described in that issue. Fixing that would require a change in WinHttpHandler to inspect 401 responses and make cookies are parsed from them and placed into the CookieContainer in the handler.

**Comment by rmkerr** [comment] 2018-05-08 17:57
@davidsh thanks for explaining what's happening here. I agree that we should just fix the loopback server in this case.

**Comment by davidsh** [comment] 2019-08-08 18:23
We've made some Digest auth fixes in .NET Core 3.0.

Closing this issue. We can revisit additional Digest auth improvements if we get customer feedback.

**Closed by davidsh** 2019-08-08 18:23 UTC
Labels: area-System.Net.Http, test enhancement
