### ISSUE TITLE
The Environment class is missing method GetCommandLineArgs

### ISSUE THREAD

**Issue by puzzl3r** [dotnet/corefx#3003] opened 2015-08-28 06:42 UTC
The `Environment` class in `System.Runtime.Extensions.dll` is missing the [`GetCommandLineArgs` method](https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs(v=vs.110).aspx), while it is available in the full CLR.

Here's a sample project.json that when targeting `dotnet`, the above mentioned
method is not found. When switched to `dnx451`, it then works fine.

```
{
  "version": "1.1.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
  },

  "frameworks": {
    "dotnet": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23019",
        "System.Linq": "4.0.0-beta-23019",
        "System.Threading": "4.0.10-beta-23019",
        "System.Runtime": "4.0.10-beta-23019",
        "Microsoft.CSharp": "4.0.0-beta-23019",
        "System.Console": "4.0.0-beta-23123",
        "System.Runtime.Extensions": "4.0.0-beta-23019"
      }
    },
    "dnx451": { }
  }
}
```

**Comment by akoeplinger** [comment] 2015-08-28 13:42
This was already reported at https://github.com/dotnet/corefx/issues/2413

**Comment by weshaggard** [comment] 2015-08-29 03:24
Yes closing as this is a duplicate of #2413 which @pallavit is investigating.

**Closed by weshaggard** 2015-08-29 03:24 UTC
