### ISSUE TITLE
System.Net.Http.WinHttpException ("The option is invalid") in System.Net.Http when ClientCertificates are used.

### ISSUE THREAD

**Issue by dperschonok** [dotnet/corefx#9796] opened 2016-07-01 17:03 UTC
I am trying to call a soap based webservice that requires client certs for authentication and the following exception occurs:

```
Exception: Exception thrown: 'System.Net.Http.WinHttpException' in System.Net.Http.dll ("The option is invalid"). Exception thrown: 'System.Net.Http.WinHttpException' in System.Net.Http.dll ("The option is invalid")
```

I've tried making these calls using the HttpClientHandler class directly as well as WCF client libraries, and the outcome is the same for both. Here is the code I am using the make these calls. 

```c#
using (var httpHandler = new HttpClientHandler())
                {
                    string certFilePath = @"C:\share\Certificates\mytestcert.cer";
                    X509Certificate2 cert2 = new X509Certificate2(certFilePath);

                    httpHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
                    httpHandler.ClientCertificates.Add(cert2);

                    using (var client = new HttpClient(httpHandler))
                    {
                        client.DefaultRequestHeaders.Add("SOAPAction", soapAction);
                        client.DefaultRequestHeaders.Add("Expect", "100-continue");
                        client.DefaultRequestHeaders.Add("Accept-Encoding", "gzip, deflate");
                        client.DefaultRequestHeaders.Add("Connection", "Keep-Alive");


                        StringContent stringContent = new StringContent(soapTemplate, null, "text/xml");

                        using (HttpResponseMessage response = await client.PostAsync(sUrl, stringContent))
                        using (HttpContent content = response.Content)
                        {
                            result = await content.ReadAsStringAsync();
                        }
                    }
```

If there is additional information I can provide, please let me know.

**Comment by davidsh** [comment] 2016-07-02 14:06
What version of Windows are you using?  Windows 7? Windows 8? Windows 10?

Please open a CMD.EXE window and type "ver" and let me know the result.  Thx.

**Comment by dperschonok** [comment] 2016-07-02 18:19
Windows 7. Microsoft Windows [Version 6.1.7601]

Would you like me to try it from another version of Windows if I can?

**Comment by davidsh** [comment] 2016-07-03 00:07
One thing I noticed about your code:

```c#
string certFilePath = @"C:\share\Certificates\mytestcert.cer";
                    X509Certificate2 cert2 = new X509Certificate2(certFilePath);
```

This code implies that the client certificate contains only the public key portion.  You must only use a client certificate that also includes the private key.  Usually that is only in a PFX type of file. So, you will get an error from trying to use this certificate since it is missing the private key.

I don't think you should be getting "Option is invalid" error though.  That is probably a bug.

Can you also try a newer version of Windows, i.e. 8 or 10? I would like to see if the error is different.

**Comment by davidsh** [comment] 2016-07-03 00:07
cc: @stephentoub

**Comment by dperschonok** [comment] 2016-07-05 16:14
Switching it to use the PFX file ends up giving me the expected result and I am able to get the token back. The same exception is still being thrown, but doesn't seem to have any impact on my application from what I can tell.

I can try it on Windows 8 a little bit later today. Only one of my developers has Windows 8 installed, so once I get their machine updated I will see if the exception happens on that OS as well.

Just for my own knowledge, I am guessing the underlying way that certificates are handled has changed? In our old 4.5.x code base, we used to reference the .cer file which we exported after installing the .pfx into our local certificate stores. My assumption is the .cer file was used to pull the private key from the certificate store? I realize this doesn't matter for the new framework, I'm just curious how it differs.

**Comment by davidsh** [comment] 2016-07-05 16:21
cc: @CIPop @bartonjs 

>I am guessing the underlying way that certificates are handled has changed? In our old 4.5.x code base, we used to reference the .cer file which we exported after installing the .pfx into our local certificate stores. My assumption is the .cer file was used to pull the private key from the certificate store? I realize this doesn't matter for the new framework, I'm just curious how it differs.

You are correct in that the orignal .NET Framework (Desktop) 4.x did support that feature where a public-key only client certificate could be used. Internally, if the private key wasn't part of the certificate `X509Certificate` object, then the stack would try to look up the certificate in the MY/Personal store to find the complete (public/private) object and then use the private key from that.

The Http stack in .NET Core doesn't support that feature and requires the full public/private key `X509Certificate`.

**Comment by dperschonok** [comment] 2016-07-06 04:33
The exception does not occur on my Windows 10 machine. I can try Windows 8 tomorrow.

**Comment by davidsh** [comment] 2017-03-04 04:09
This is probably a Windows 7 specific bug with WinHTTP.  It is likely that our WinHttpHandler code is calling a WinHTTP API that isn't implemented on the Windows 7 version of WinHTTP.  That is why the error, "The option is invalid" is being returned.

This is a bug we should fix once we root cause the specific WinHTTP API call that is failing.  The repro scenario suggests it is limited some client certificate related API.

On a separate note, this comment:

>Just for my own knowledge, I am guessing the underlying way that certificates are handled has changed? In our old 4.5.x code base, we used to reference the .cer file which we exported after installing the .pfx into our local certificate stores. My assumption is the .cer file was used to pull the private key from the certificate store? I realize this doesn't matter for the new framework, I'm just curious how it differs.

describes a behavior difference between .NET Framework and .NET Core. If there is a strong desire to fix this, then a separate issue should be opened up for that.

**Comment by davidsh** [comment] 2017-04-27 16:43
@dperschonok Is this problem still occurring for you?  I have been unable to repro it on Windows 7 given the repro sample code you posted.

If you are still having this problem, can you post a complete Visual Studio solution that repros the problem? Thx.

**Comment by dperschonok** [comment] 2017-04-27 18:40
@davidsh We haven't had the issue anymore. As you originally pointed out, we weren't using the certificates properly in our code. Once we used the correct certificate type, all of our issues went away. So the bug I posted was probably a red herring. My apologies. I should have posted back here sometime ago. Our certificate is running successfully in production (on Linux).

**Comment by davidsh** [comment] 2017-04-27 20:45
Thx for the response. I will close this issue now.

**Closed by davidsh** 2017-04-27 20:45 UTC
Labels: area-System.Net.Http, bug, os-windows
