### ISSUE TITLE
[arm\windows] Hundreds of  tests failed with "The work item failed to produce any test results." without Stack trace

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#34423] opened 2019-01-08 09:01 UTC
**Job name:**
uap-Windows_NT-Release-arm-Windows.10.Arm64

Error message:
```
The work item failed to produce any test results.
```

Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=67997&view=ms.vss-test-web.test-result-details

**Comment by safern** [comment] 2019-01-08 18:57
Closing as dupe of: #30399

**Closed by safern** 2019-01-08 18:57 UTC
Labels: test-run-core
