### ISSUE TITLE
Installing System.Collections.Immutable on .NET 4.5 brings unnecessary packages

### ISSUE THREAD

**Issue by jakubka** [dotnet/corefx#2984] opened 2015-08-26 22:49 UTC
When System.Collections.Immutable nuget package is installed to project targeting .NET 4.5, some unnecessary dependencies are brought in:

```
  <package id="System.Collections" version="4.0.0" targetFramework="net45" />
  <package id="System.Diagnostics.Debug" version="4.0.0" targetFramework="net45" />
  <package id="System.Globalization" version="4.0.0" targetFramework="net45" />
  <package id="System.Linq" version="4.0.0" targetFramework="net45" />
  <package id="System.Resources.ResourceManager" version="4.0.0" targetFramework="net45" />
  <package id="System.Runtime" version="4.0.0" targetFramework="net45" />
  <package id="System.Runtime.Extensions" version="4.0.0" targetFramework="net45" />
  <package id="System.Threading" version="4.0.0" targetFramework="net45" />
```

NuGet is apparently smart enough to not add those packages as references as they are only meant for .NET Core, but I still feel they should not even be added to packages.config and downloaded.

[System.Collections.Immutable nuget package](https://www.nuget.org/packages/System.Collections.Immutable/) only specifies dependencies for .NET Core (DotNET 5.0). I believe that adding empty dependencies group for .NET 4.5 as can be seen in [AutoMapper nuget package](https://www.nuget.org/packages/AutoMapper/) (for example) would fix the issue and those dependencies would not be downloaded.

Have not adding other dependency groups been done on purpose or is it an oversight? Thanks!

**Comment by ericstj** [comment] 2015-11-04 23:54
In order to fix this we need to take into account our inbox framework lists when generating package dependencies.

Today the package dependencies are simply harvested from the assembly refs and assumed to match 1:1 with the target framework of the assembly.

We need to do this for "dotnet*" "dnxcore50" and "netcore50", but for frameworks with targeting packs we can do a little better. To reduce the noise.  I talk about this a bit here: https://github.com/ericstj/NuGetDocs/blob/ericstj/nuget3samples/NuGet.Docs/Create/nuget3-packages-walkthrough.md

In our packaging infrastructure we can do the following:
1. Start by generating the dependency group for dotnet.
2. For each concrete TFM that supports that dotnet generation, if it has any of the dependencies inbox (it will: at least system.runtime) create a copy of the dependencies and remove each dependency that is supported inbox.

**Comment by davidfowl** [comment] 2015-11-06 15:24
Maybe be can do something in nuget instead? This will become more of a problem with the standard platform

**Comment by ericstj** [comment] 2015-11-06 16:15
Perhaps, though the problem here is nuget v2 / packages.config where all these dependencies get burned into packages.config.  On nuget v3 the dependencies are a no-op since the only place they show up is the lock file and they are just validating that the specific dependencies are supported by the platform.

**Comment by chcosta** [comment] 2015-11-30 19:36
A fix for this has been submitted and will be present in the next package push.

**Closed by chcosta** 2015-11-30 19:36 UTC
Labels: packaging, System.Collections

**Comment by samholder** [comment] 2016-04-26 11:35
What is the fix for this? We have just upgraded to VS2015 and we are seeing this issue when we try and update packages for any solution that contains a dependency on System.Collections.Immutable regardless of whether we have updated to Update 2 of VS or not. I'm not sure what else we should be upgrading to fix this...

**Comment by chcosta** [comment] 2016-04-26 16:27
The fix was this was in how we define our dependencies in the package per target framework.  We made a change to better take into account inbox dependencies and not list them as package dependencies.  In the case of System.Collections.Immutable, we have an empty dependency group for net45 in the package starting with 1.1.38-rc2-23601.

**Comment by danrozenberg** [comment] 2016-11-30 18:45
It seems like adding ``System.Collections.Immutable": "1.3.0`` to my project.json is fixing my ``System.Runtime`` reference to version 4.0.20, even though other references specify a higher version of ``System.Runtime``.

The following project.json, for example, leaves me with ``System.Runtime 4.0.20``:

```
{
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    //"SomeLibrary": "1.0.0-*"
  },
  "frameworks": {
    "net462": {
      "dependencies": {
        "System.Runtime": "4.1.0",
        "System.Collections.Immutable": "1.3.0"
      }
    }
  },
  "version": "1.0.0-*"
```

The following project.json gets me  the desired ``System.Runtime 4.1.0``:

```
{
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    //"SomeLibrary": "1.0.0-*"
  },
  "frameworks": {
    "net462": {
      "dependencies": {
        "System.Runtime": "4.1.0"        
      }
    }
  },
  "version": "1.0.0-*"
}
```

Is this the expected behavior? I thought Nuget was supposed to get me the smallest version greater than 4.1....  Is this a bug in Nuget? In Collections.Immutable? 

Thanks!

**Comment by ericstj** [comment] 2016-11-30 19:00
@danrozenberg both project.json files when restored select the exact same System.Runtime.dll in project.lock.json.  If you're seeing different results the problem may exist further down in the build process.  

> leaves me with  `System.Runtime 4.0.20`

How are you determining that, and what are you using to build? /cc @piotrpMSFT @davidfowl

**Comment by danrozenberg** [comment] 2016-11-30 19:21
Hello, @ericstj . Thanks for the quick response.

I am using Visual Studio

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
```

and ``Microsoft .NET Core Tools (Preview 2)   14.1.20907.0``

I haven't changed any build options, so I assume the default being used is MSBuild?

To determine the version that I end up with, I am looking at the solution explorer, under references. There I can see the System.Runtime version being used.  Also, running my sample project described in this issue (https://github.com/dotnet/coreclr/issues/8352) raises the "Could not load file or assembly" whenever VS informs me that ``4.0.20`` was loaded, so I believe VS's information to be accurate.

Interestingly, my project.lock also shows a dependency on ``System.Runtime/4.1.0``, but VS shows me that what I got is "4.0.20"

Sometimes (but not always), I'll get the warning:  ``Dependency specified was System.Runtime >= 4.1.0, but ended up with System.Runtime 4.0.20"``

Can you confirm through VS that you do get version 4.1.0 when you also have a dependency on ``Collections.Immutable 1.3.0``?

**Comment by danrozenberg** [comment] 2016-11-30 19:26
My project.lock.json, in case that helps

```
{
  "locked": false,
  "version": 2,
  "targets": {
    ".NETFramework,Version=v4.6.2": {
      "System.Collections.Immutable/1.3.0": {
        "type": "package",
        "compile": {
          "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll": {}
        },
        "runtime": {
          "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll": {}
        }
      },
      "System.Runtime/4.1.0": {
        "type": "package",
        "frameworkAssemblies": [
          "System",
          "System.ComponentModel.Composition",
          "System.Core",
          "mscorlib"
        ],
        "compile": {
          "ref/net462/System.Runtime.dll": {}
        },
        "runtime": {
          "lib/net462/System.Runtime.dll": {}
        }
      }
    }
  },
  "libraries": {
    "System.Collections.Immutable/1.3.0": {
      "sha512": "zukBRPUuNxwy9m4TGWLxKAnoiMc9+B+8VXeXVyPiBPvOd7yLgAlZ1DlsRWJjMx4VsvhhF2+6q6kO2GRbPja6hA==",
      "type": "package",
      "path": "System.Collections.Immutable/1.3.0",
      "files": [
        "System.Collections.Immutable.1.3.0.nupkg.sha512",
        "System.Collections.Immutable.nuspec",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/netstandard1.0/System.Collections.Immutable.dll",
        "lib/netstandard1.0/System.Collections.Immutable.xml",
        "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll",
        "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.xml"
      ]
    },
    "System.Runtime/4.1.0": {
      "sha512": "v6c/4Yaa9uWsq+JMhnOFewrYkgdNHNG2eMKuNqRn8P733rNXeRCGvV5FkkjBXn2dbVkPXOsO0xjsEeM1q2zC0g==",
      "type": "package",
      "path": "System.Runtime/4.1.0",
      "files": [
        "System.Runtime.4.1.0.nupkg.sha512",
        "System.Runtime.nuspec",
        "ThirdPartyNotices.txt",
        "dotnet_library_license.txt",
        "lib/MonoAndroid10/_._",
        "lib/MonoTouch10/_._",
        "lib/net45/_._",
        "lib/net462/System.Runtime.dll",
        "lib/portable-net45+win8+wp80+wpa81/_._",
        "lib/win8/_._",
        "lib/wp80/_._",
        "lib/wpa81/_._",
        "lib/xamarinios10/_._",
        "lib/xamarinmac20/_._",
        "lib/xamarintvos10/_._",
        "lib/xamarinwatchos10/_._",
        "ref/MonoAndroid10/_._",
        "ref/MonoTouch10/_._",
        "ref/net45/_._",
        "ref/net462/System.Runtime.dll",
        "ref/netcore50/System.Runtime.dll",
        "ref/netcore50/System.Runtime.xml",
        "ref/netcore50/de/System.Runtime.xml",
        "ref/netcore50/es/System.Runtime.xml",
        "ref/netcore50/fr/System.Runtime.xml",
        "ref/netcore50/it/System.Runtime.xml",
        "ref/netcore50/ja/System.Runtime.xml",
        "ref/netcore50/ko/System.Runtime.xml",
        "ref/netcore50/ru/System.Runtime.xml",
        "ref/netcore50/zh-hans/System.Runtime.xml",
        "ref/netcore50/zh-hant/System.Runtime.xml",
        "ref/netstandard1.0/System.Runtime.dll",
        "ref/netstandard1.0/System.Runtime.xml",
        "ref/netstandard1.0/de/System.Runtime.xml",
        "ref/netstandard1.0/es/System.Runtime.xml",
        "ref/netstandard1.0/fr/System.Runtime.xml",
        "ref/netstandard1.0/it/System.Runtime.xml",
        "ref/netstandard1.0/ja/System.Runtime.xml",
        "ref/netstandard1.0/ko/System.Runtime.xml",
        "ref/netstandard1.0/ru/System.Runtime.xml",
        "ref/netstandard1.0/zh-hans/System.Runtime.xml",
        "ref/netstandard1.0/zh-hant/System.Runtime.xml",
        "ref/netstandard1.2/System.Runtime.dll",
        "ref/netstandard1.2/System.Runtime.xml",
        "ref/netstandard1.2/de/System.Runtime.xml",
        "ref/netstandard1.2/es/System.Runtime.xml",
        "ref/netstandard1.2/fr/System.Runtime.xml",
        "ref/netstandard1.2/it/System.Runtime.xml",
        "ref/netstandard1.2/ja/System.Runtime.xml",
        "ref/netstandard1.2/ko/System.Runtime.xml",
        "ref/netstandard1.2/ru/System.Runtime.xml",
        "ref/netstandard1.2/zh-hans/System.Runtime.xml",
        "ref/netstandard1.2/zh-hant/System.Runtime.xml",
        "ref/netstandard1.3/System.Runtime.dll",
        "ref/netstandard1.3/System.Runtime.xml",
        "ref/netstandard1.3/de/System.Runtime.xml",
        "ref/netstandard1.3/es/System.Runtime.xml",
        "ref/netstandard1.3/fr/System.Runtime.xml",
        "ref/netstandard1.3/it/System.Runtime.xml",
        "ref/netstandard1.3/ja/System.Runtime.xml",
        "ref/netstandard1.3/ko/System.Runtime.xml",
        "ref/netstandard1.3/ru/System.Runtime.xml",
        "ref/netstandard1.3/zh-hans/System.Runtime.xml",
        "ref/netstandard1.3/zh-hant/System.Runtime.xml",
        "ref/netstandard1.5/System.Runtime.dll",
        "ref/netstandard1.5/System.Runtime.xml",
        "ref/netstandard1.5/de/System.Runtime.xml",
        "ref/netstandard1.5/es/System.Runtime.xml",
        "ref/netstandard1.5/fr/System.Runtime.xml",
        "ref/netstandard1.5/it/System.Runtime.xml",
        "ref/netstandard1.5/ja/System.Runtime.xml",
        "ref/netstandard1.5/ko/System.Runtime.xml",
        "ref/netstandard1.5/ru/System.Runtime.xml",
        "ref/netstandard1.5/zh-hans/System.Runtime.xml",
        "ref/netstandard1.5/zh-hant/System.Runtime.xml",
        "ref/portable-net45+win8+wp80+wpa81/_._",
        "ref/win8/_._",
        "ref/wp80/_._",
        "ref/wpa81/_._",
        "ref/xamarinios10/_._",
        "ref/xamarinmac20/_._",
        "ref/xamarintvos10/_._",
        "ref/xamarinwatchos10/_._"
      ]
    }
  },
  "projectFileDependencyGroups": {
    "": [],
    ".NETFramework,Version=v4.6.2": [
      "System.Collections.Immutable >= 1.3.0",
      "System.Runtime >= 4.1.0"
    ]
  },
  "tools": {},
  "projectFileToolGroups": {}
}
```

**Comment by danrozenberg** [comment] 2016-12-02 18:03
It seems like the problem is happening during build and not restore. I see that running ``dotnet build`` on the project root creates the bin folder with all necessary .dlls, except ``System.Runtime.dll``. 
If I remove the dependency to System.Collections.Immutable, then ``dotnet build`` will put ``System.Runtime.dll`` in my bin folder. Inspecting it with ILSpy confirms that dll is indeed ``System.Runtime.dll``, which is what I need if I need to reference a ``netstandard1.5`` library.

I will open a new issue on the corecli repo for 2 reasons:

1 - I think its the most appropriate place
2 - Have it as an open issue as opposed to posting all this on a closed issue.

Thanks!

**Comment by ericstj** [comment] 2016-12-05 17:49
@danrozenberg you got it!  Indeed I think this is a problem with the CLI's build.

**Comment by danrozenberg** [comment] 2016-12-05 19:03
Thanks for looking into this, @ericstj and @karelz
