### ISSUE TITLE
Enumerable.ToArray() fails on the results of some uses of Enumerable.Cast()

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#2241] opened 2015-07-03 18:23 UTC
Generally any implementation of `IEnumerable<T>` should be able to produce a `T[]` with a call to `ToArray()`.

However, in some cases the `IEnumerable<T>` produced by a call to `Cast()` will in fact be an array of another type that can be converted on the fly by the implementation of `GetEnumerator()`. This works well in many cases and is a valuable optimisation (rather than going through `CastIterator`) but if `ToArray()` is called on it, the result is an `ArrayTypeMismatchException` that would not be expected by the user, especially since code might call `ToArray()` without knowing that `Cast()` had been used, or pass the result of `Cast()` to a method, not knowing that `ToArray()` would be used.

In particular this happens if you `Cast()` an array of one `enum` type to another `enum` type.

**Comment by leppie** [comment] 2015-07-03 18:25
A test case would be nice.

**Comment by hackcraft** [comment] 2015-07-03 18:26
private enum Enum0
        {
            First,
            Second,
            Third
        }

        private enum Enum1
        {
            First,
            Second,
            Third
        }

        [Fact]
        public void ToArray_Cast()
        {
            var source = new[] { Enum0.First, Enum0.Second, Enum0.Third };
            Assert.Equal(new[] { Enum1.First, Enum1.Second, Enum1.Third }, source.Cast<Enum1>().ToArray());
        }

**Comment by leppie** [comment] 2015-07-03 18:28
But even the simple case does not work in the presence of generics.

    static X Cast<X, Y>(Y y)
    {
      return (X)y;
    }

**Comment by hackcraft** [comment] 2015-07-03 18:32
I don't follow, leppie. Generally `source.Cast<Enum1>()` produces a perfectly fine `IEnumerable<Enum1>` generally `someSequence.ToArray()` where `someSequence` is an `IEnumerable<Enum1>` produces a perfectly find `Enum1[]`. It's surprising behaviour that `source.Cast<Enum1>().ToArray()` fails, especially since the code using `Cast` and the code using `ToArray` could be quite far apart.

**Comment by hackcraft** [comment] 2015-07-03 18:36
Ah, I get you now. As a rule `Enumerable<Cast>()` does do pretty much the same thing as `return (X)(object)y`. (To be precise, it does `foreach (object obj in source) yield return (TResult)obj`). The problem is with the optimisation of:

    IEnumerable<TResult> typedSource = source as IEnumerable<TResult>;
    if (typedSource != null) return typedSource;

Which can cause problems if `ToArray()` then in turn tries to optimise for `ICollection<TElement> collection = source as ICollection<TElement>`.

But those to optimisations are hit by more code than is affected by this bug, so the key is to fix the bug without removing the optimisations.

**Comment by leppie** [comment] 2015-07-03 18:42
@hackcraft : In that case, the issue is legit :D Good catch.

**Comment by mikedn** [comment] 2015-07-04 07:23
This really is a bug in the `Array.CopyTo` implementation. On one hand the runtime allows you to freely cast enum arrays with the same underlying type and to unbox enums with the same underlying type but different actual type. On the other hand `Array.CopyTo` claims that you can't copy to an enum array with the same underlying type. That doesn't make sense no matter how you look at it.

**Comment by stephentoub** [comment] 2015-07-04 12:14
I agree with @mikedn, and I'd rather this be addressed at the source than at every possible place this pattern is employed. @jkotas, who should look at this?

**Comment by jkotas** [comment] 2015-07-04 19:47
This looks like enhancement request for `Array.Copy` that is called by `Array.CopyTo`. The following does not work today:

            var source = new Enum0[3];
            var dest = new Enum1[3];
            Array.Copy(source, dest, 3);

I do not see a fundamental problem with making this work. It should be a simple fix: change `GetSignatureCorElementType` to `GetVerifierCorElementType` throughout the implementation of `Array.Copy`. It should not be a breaking change because of it is changing throwing behavior to non-throwing behavior.

However, such change should be reviewed by the FX design group for consistency issues. I believe that we generally disallow implicit enum conversions, e.g. `Array.SetValue` or reflection APIs won't perform enum conversions. Is it a good to allow them for `Array.Copy` and keep everything else as is?

**Comment by stephentoub** [comment] 2015-07-04 19:58
Either that request, or that in this code:

object source = new Enum0[3];
bool b = source is IEnumerable<Enum1>;

b would be false instead of true (it's true today), just as it's false today in this code:

var source = new Enum0[3];
bool b = source is IEnumerable<Enum1>;

But that would be a breaking change. It'd be better if the rest of Array could be made consistent with the current type checking behavior.

cc: @terrajobst

**Comment by jkotas** [comment] 2015-07-04 20:30
`b` should really be true in this code:

    var source = new Enum0[3];
    bool b = source is IEnumerable<Enum1>;

This looks like an invalid optimization performed by C# compiler. I have opened https://github.com/dotnet/roslyn/issues/3830

**Comment by mikedn** [comment] 2015-07-05 08:29
> Is it a good idea to allow them for  Array.Copy  and keep everything else as is?

Hmm, I'm tempted to say that this should be done only for `CopyTo` and only for that `CopyTo` that's accessible via a `ICollection<T>`. The Array's own `Copy` and `CopyTo` should not be changed.

Consider the following code:
```C#
class Program {
    enum X {
        Foo
    }
    enum Y {
        Foo
    }
    static void Main() {
        X x = (X)(object)Y.Foo; // works, this why the proposed Cast/ToArray fix works

        X[] a = new X[1];
        a.SetValue(Y.Foo, 0); // doesn't work and I don't think that it should work
        a.CopyTo(new Y[1], 0); // same as above
        Array.Copy(a, new Y[1], 1); // same as above

        IList<Y> l = ((object)a) as IList<Y>;
        l[0] = Y.Foo; // works
        Y y = l[0]; // works
        l.CopyTo(new Y[1], 0); // doesn't work
    }
}
```
I think that last `CopyTo` in the above example should work. As is now the runtime allows the cast to `IList<Y>` but the resulting interface is only partially functional.

**Comment by hackcraft** [comment] 2015-07-05 13:31
I suspect this ultimately goes back to pre-generics .NET broken-but-intractable copying of pre-generics Java's broken-but-intractable array covariance.

To consider it another way. If this issue had been found in initial testing of `Cast` and it wasn't deemed too minor to care about, the conclusion could well have been that either the optimisation in `Cast` was too risky, or the optimisation in `ToArray` was too risky, and one or both of them should be removed.This would have stopped the problem hitting in this point that was introduced with .NET 3.5, but left any issues at 3.0 or earlier as is.

But coming in now with that would cause a performance hit on code that benefits from the optimisation, which is likely quite a lot. As such a change like that in this PR has the advantage of being relatively low-impact, and it could be diked out if a deeper change made it unnecessary.

**Comment by stephentoub** [comment] 2015-07-05 18:21
> As such a change like that in this PR has the advantage of being relatively low-impact

While that may be true, the fix proposed in #2242 only fixes one particular case of this issue:
```C#
var source = new Enum0[] { Enum0.First };
var results = source.Cast<Enum1>().ToArray();
```

It doesn't fix using ```ToList```:
```C#
var results = source.Cast<Enum1>().ToList();
```
nor using ```List<T>```'s ctor directly:
```C#
var results = new List<Enum1>(source.Cast<Enum1>());
```
nor without ```Cast<TResult>```:
```C#
var results = new List<Enum1>(source as object as IEnumerable<Enum1>);
```
nor using some other ```IList<T>.CopyTo``` wrapper:
```C#
new ReadOnlyCollection<Enum1>(source as object as Enum1[]).CopyTo(new Enum1[0], 0);
```
nor any number of other occurrences of this pattern in the framework itself, in 3rd-party libraries, or in application code.

**Comment by hackcraft** [comment] 2015-07-06 16:15
As updated, the PR now tries to fix `Cast` specifically, taking this combination from the other side, and potentially fixing other uses of `Cast` rather than potentially fixing other uses of `ToArray`. There is likely stuff in this discussion that it ignores that are still worth considering generally though.

**Comment by nguerrera** [comment] 2015-07-06 17:04
@mikedn wrote:
> Hmm, I'm tempted to say that this should be done only for CopyTo and only for that CopyTo that's accessible via a `ICollection<T>`. The Array's own Copy and CopyTo  should not be changed.

I don't think this should be limited to calls through the interface. Ideally, all of the following would work too IMHO:

``` C#
int[] ints = new int[] { 1, 2, 3 };
uint[] uints = (uint[])(object)ints;

uints.CopyTo(new uint[3], 0); // today throws ArrayTypeMismatchException
uints.SetValue(1u, 0); // today throws ArgumentException
Array.Copy(uints, new uint[3], 3); // today throws ArrayTypeMismatchException
```

If those uints were passed to me rather than schemed right above, I'd have no reason to suspect that any of those calls would fail.

So, really, the same argument applies to U[] as `ICollection<U>`: If the runtime type system allows me to treat T[] as U[], then the U[] should work like any other to the full extent possible. (One well known case where it's not possible is for array covariance due to the lack of safety, but that doesn't apply here.)

So I would fix Array.SetValue too and anything else where the same logic applies. 

I'd have to dig in to relaxing the reflection issues that @jkotas alluded to. Ideally, we'd fix them too, but I'm inclined to think it is less bad to have gaps in reflection than static use of U[], `ICollection<U>`, or `IList<U>` that blows up.

**Comment by hackcraft** [comment] 2015-07-06 17:19
@nguerrera those have been known issues since 1.0, when they were copied as known issues from Java. I think it's too late to resolve that now, what can be fixed is (at least sometimes) when corefx code causes the issue to be raised.

**Comment by nguerrera** [comment] 2015-07-06 17:21
@hackcraft I don't see why this cannot be fixed. We generally tolerate turning exception throwing paths in to working paths. I highly doubt there are applications that will break without the ArrayTypeMismatchException.

**Comment by mikedn** [comment] 2015-07-06 18:33
@nguerrera wrote:

>I don't think this should be limited to calls through the interface. Ideally, all of the following would work too IMHO:

Well, I was looking for a way out that doesn't relax the safety too much. The problem with `Array`'s own `CopyTo` is that the destination array parameter is of type `Array`, not `T[]`. If you relax `Array.CopyTo` then you end up with this:

```C#
int[] x = new int[42];
uint[] y = new uint[42];
x.CopyTo(y, 0); // yay, this would work and there's no explicit cast in sight
```

Same thing happens with `Array.Copy(Array, Array, int)` & co. The interface only solution doesn't suffer from this problem, you have a `ICollection<T>` source and a `T[]` destination, copying should work.

You'd need to add generic `Copy` and `CopyTo` overloads that ensure that the source and destination static type is the same. In turn that would ensure that the objects are either what they claim to be or have been obtained via allowed conversions. Such generic overloads would implement the new behavior while the non-generic overloads would remain unchanged.

**Comment by nguerrera** [comment] 2015-07-06 18:35
@mikedn I see. Yes, we could add the generic overloads and enforce the same constraint on anything taking Array. I think that would indeed be best. Good point.

**Comment by VSadov** [comment] 2016-11-18 21:18
It seems the right solution here is to make new or existing CopyTo  to work with everything assignment-compatible.
I have entered https://github.com/dotnet/corefx/issues/13816 to track that.

**Comment by VSadov** [comment] 2016-11-18 21:18
I think we should close this for now until   #13816 is fixed.

**Comment by karelz** [comment] 2016-11-18 22:12
Let's keep it open to not loose track.

**Comment by karelz** [comment] 2016-11-18 22:15
Blocked on #13816

**Closed** 2017-07-07 15:31 UTC
Labels: area-System.Linq, blocked, bug, up-for-grabs
