### ISSUE TITLE
[Perf][Windows_NT] Investigate the regression on some System/IO/Tests benchmarks due to OS upgrade

### ISSUE THREAD

**Issue by jorive** [dotnet/corefx#27495] opened 2018-02-27 03:14 UTC
It looks like changing the OS on the perf machines, from Windows Server 2012 to Windows Server 2016 (https://github.com/dotnet/corefx/pull/23714) caused a regression of:
- System/IO/Tests/[Perf_File & Perf_FileStream]
  - ~400% on Perf_File.Delete
  - ~24% on Perf_File.Exist
  - ~15% on Perf_FileStream
- System/IO/Tests/Perf_Path/GetTempPath ~32% regression

**Comment by danmosemsft** [comment] 2018-03-22 20:55
@jorive do we have ETL traces from before and after? Manually setting up machines and reproing to get traces would take a long time.

**Comment by jorive** [comment] 2018-03-22 21:00
@danmosemsft I doubt we still have Etl traces.

**Comment by danmosemsft** [comment] 2018-03-22 21:02
@jorive is there a way to get them without manually setting up machines? Since we presumably can't use VM's that could take all day. Is there a way to set up 2 perf machines, one with each OS, taht we can use?

**Comment by jorive** [comment] 2018-03-22 21:03
Yes, we can reserve two of the machines in the lab for each OS, and start private runs.

**Comment by danmosemsft** [comment] 2018-03-22 21:03
Can we go ahead and do this please

**Comment by jorive** [comment] 2018-03-22 21:04
OK

**Comment by danmosemsft** [comment] 2018-03-26 23:53
Looked briefly at this with @JeremyKuhne . You see the same regression in eg GetTempPath -- which regressed ~50% and presumably does little or no work on disk (lack of noise in it is consistent with this). Our theory is that it is because Server 2016 upgraded many of these API's to support long paths. So something that previously did very little work like GetTempPath now has to check whether the path is "long".

Traces will prove this.

**Comment by danmosemsft** [comment] 2018-03-28 22:00
@jorive is working to get ETL with stacks that we can diff. Won't be analyzed by EOW

**Comment by danmosemsft** [comment] 2018-04-14 05:45
@jorive can your please give status.

**Comment by jorive** [comment] 2018-04-16 15:26
@danmosemsft I am waiting on https://github.com/dotnet/buildtools/pull/2008. This change will enable two runs capturing different profile data.

**Comment by jorive** [comment] 2018-04-19 23:01
Waiting on CI legs to finish for https://github.com/dotnet/corefx/pull/29203

**Comment by danmosemsft** [comment] 2018-04-28 00:49
@jorive (or maybe @adamsitnik if Jose is out) are traces now available, with stacks, for us to compare?

**Comment by jorive** [comment] 2018-05-09 17:18
@danmosemsft I enabled Etl traces on CoreFx repo few weeks ago. I will request the lab to reimage one machine back to the old OS, so you can do the testing.

**Comment by jorive** [comment] 2019-02-13 08:41
@adamsitnik @danmosemsft I think this is a place where we could use dotnet/performance to do the investigations, and using the machines in the lab.

**Comment by JeremyKuhne** [comment] 2020-01-22 23:33
Triage: closing due to lack of traces to investigate.

**Closed by JeremyKuhne** 2020-01-22 23:33 UTC
Labels: area-System.IO, tenet-performance-benchmarks
