### ISSUE TITLE
.NET Core 2.1 HttpClient can't established of Https URL in Docker ENV.

### ISSUE THREAD

**Issue by idoop** [dotnet/corefx#30313] opened 2018-06-12 06:46 UTC
code:
``` c#
public class Tests 
{
    private readonly HttpClient _client = new HttpClient();
...
   private async Task<bool> TestOrderPay(string chargeId)
   {
            var url = "https://api.google.com/xxx/xxx/?livemode=false";
            string strResult = await _client.GetStringAsync(url);
            return strResult == "success";
   }
}
```
When i build it on Win and Ubuntu18 platform is ok, but build it in **docker env (microsoft/dotnet:2.1-sdk)** is error:
```
...
---- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
-------- System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
...
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
...
----- Inner Stack Trace -----
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
...
```

It's look like not found root cert files.But use `curl` commond in docker to connect  https url, it's established.

**Comment by karelz** [comment] 2018-06-12 17:35
@wfurt @bartonjs do you have suggestion how to troubleshoot that?
@idoop can you post a repro we can run internally? (HelloWorld-style app with real URL)

**Comment by davidsh** [comment] 2018-06-12 19:42
I tried to repro this myself and I did not get an exception.

On my Windows 10 machine I have Docker for Windows.

I created the Linux container and ran a simple test (shown below).  I simply got a valid 404 HTTP response code and didn't see any exception thrown.  While my repro only used the root https://api.google.com URI, it shouldn't matter because TLS/SSL is first done by connecting just to the host over port 443 before doing any HTTP GET operations on the path.

```
docker run -it microsoft/dotnet:2.1-sdk
root@25d3de085828:/home/usr/corefx/ssltest# dotnet run -f netcoreapp2.1
(Framework: /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.0)
Doing GET for https://api.google.com/
404 Not Found
Referrer-Policy: no-referrer
Date: Tue, 12 Jun 2018 19:37:12 GMT
Alt-Svc: quic=":443"; ma=2592000; v="43,42,41,39,35"
Content-Type: text/html; charset=UTF-8
Content-Length: 1561

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
```

```c#
internal class Program
{
    static void DumpResponse(HttpResponseMessage response)
    {
        try
        {
            Console.WriteLine($"{(int)response.StatusCode} {response.ReasonPhrase}");
            Console.Write(response.Headers);
            Console.WriteLine(response.Content.Headers);
            string responseBody = response.Content.ReadAsStringAsync().Result;
            Console.WriteLine(responseBody);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }

    static void Main()
    {
        Console.WriteLine($"(Framework: {Path.GetDirectoryName(typeof(object).Assembly.Location)})");

        try
        {
            var serverUri = new Uri("https://api.google.com/");

            var handler = new HttpClientHandler();
            using (var client = new HttpClient(handler))
            {

                Console.WriteLine($"Doing GET for {serverUri}");
                HttpResponseMessage response = client.GetAsync(serverUri).GetAwaiter().GetResult();
                DumpResponse(response);
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}
```

**Comment by wfurt** [comment] 2018-06-12 19:48
I did quick try with setting up microsoft/dotnet:2.1-sdk image on Linux and I cannot reproduce it e.g. everything works as expected. 
You can try to create x500 store and iterate through to see what certificates you get. 
I would also suggest to check that local time is valid. 
You can also do packet capture to see SSL transaction.
Make sure there is direct connectivity and there is no upstream proxy of firewall messing up with the handshake.

**Comment by karelz** [comment] 2018-06-12 20:37
2x no repro, closing for now.
If you find a way to reproduce it reliable on other machines, please let us know and we can reopen.

**Closed by karelz** 2018-06-12 20:37 UTC
Labels: area-System.Net.Http, bug, needs more info
