### ISSUE TITLE
UdpClient Send overload methods not having an offset

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18106] opened 2017-04-08 06:09 UTC
@txdv commented on [Fri Apr 07 2017](https://github.com/dotnet/coreclr/issues/10790)

[I was looking at the API of UdpClient](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L904-L928) and I wondered, why is it that there is no offset for the byte buffer provided?

It just provides the offset as the 0 default to the underlying Socket SendTo call:
```csharp
return Client.SendTo(dgram, 0, bytes, SocketFlags.None, endPoint);
````
Shouldn't the API be typed like Send(byte[] buffer, int offset, int count) like all the other APIs? (Stream::Write, Socket::SendTo)

Is that a change that might get accepted? 

---

@jkotas commented on [Fri Apr 07 2017](https://github.com/dotnet/coreclr/issues/10790#issuecomment-292553643)

@txdv You should ask this question in corefx repo since the relevant code lives there.

**Comment by txdv** [comment] 2017-04-08 12:30
O thanks! I would have moved the issue myself ... but thanks anyways ;)

**Comment by davidsh** [comment] 2017-04-08 14:50
>Shouldn't the API be typed like Send(byte[] buffer, int offset, int count) like all the other APIs? (Stream::Write, Socket::SendTo)

This sounds like an API change request.

**Comment by karelz** [comment] 2019-10-02 19:31
Duplicate of #28131

**Closed by karelz** 2019-10-02 19:31 UTC
Labels: area-System.Net, enhancement
