### ISSUE TITLE
Update NamedPipe tests to inject \LOCAL\ in the paths for UAP so they can be reenabled for UAP

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21392] opened 2017-06-22 23:44 UTC
Uap has some access restrictions when creating a NamedPipe, we are still figuring out with the Windows guys how should we do this and through which Win Api. So we need to tweak this tests to pass for uap as they apparently can only create local named pipes to within the app container package location. 

I will disable this tests against this issue.

cc: @danmosemsft @JeremyKuhne

**Comment by danmosemsft** [comment] 2017-07-03 20:50
Needs some owner, don't care who but Jeremy has a bunch already. @joperezr talk to @JeremyKuhne /@safern for context.

**Comment by danmosemsft** [comment] 2017-07-05 20:40
Plan here is to inject \LOCAL\ into the paths the tests use when in appcontainer, and we'd be requiring app code to do the same: unless Windows can improve things.

**Comment by danmosemsft** [comment] 2017-07-05 21:46
We discussed this please go ahead and have our tests inject \LOCAL\ into the paths when `IsUap` is true, so the tests pass. Customer code will have to do the same, we will document that.

**Comment by joperezr** [comment] 2017-07-05 23:49
will do.

**Comment by joperezr** [comment] 2017-07-07 22:41
I'm trying to fix this, but after doing so and re-enabling the tests, a bunch of IO.Pipes tests are hanging waiting forever to connect to a namedPipe. I'm trying to investigate this now, but I might need to grab some help from @JeremyKuhne

**Comment by joperezr** [comment] 2017-07-12 23:42
Looks like the reason why the tests are now hanging is because there was a regression on one of the PInvokes that we call to create the namedPipeServer after RS1. There is a bug open and tracked by Windows, but once they fix it we will need to re-enable these tests.

**Comment by AlexGhiondea** [comment] 2017-07-14 19:50
Marking this as post-zbb since we depend on a fix from Windows.

**Closed** 2017-07-17 15:42 UTC
Labels: area-System.IO, test-run-uwp-coreclr
