### ISSUE TITLE
ValueTuple's xml file is not valid xml

### ISSUE THREAD

**Issue by bentheiii** [dotnet/corefx#26263] opened 2018-01-10 22:51 UTC
Version Used:
ValueTuple version 4.4.0

Steps to Reproduce:

Have any project with target framework 4.6.2 at the most.
Install the ValueTuple nuget package into the project.
Build the project and find System.ValueTuple.xml near the output file.
Open System.ValueTuple.xml with any XML viewer (i.e. Chrome).
Expected Behavior:
System.ValueTuple.xml should open normally.

Actual Behavior:
Opening the file fails with the following error:

error on line 1241 at column 95: Opening and ending tag mismatch: p line 0 and th

**Comment by svick** [comment] 2018-01-10 22:55
Reposting my comment from https://github.com/dotnet/roslyn/issues/24157, where this was originally reported:

The XML file in the NuGet package is already invalid, the code around line 1241 is:

```xml
    <member name="M:System.ValueTuple`1.CompareTo(System.ValueTuple{`0})">

      <summary>Compares the current <see cref="T:System.ValueTuple`1"></see> instance to a specified <see cref="T:System.ValueTuple`1"></see> instance.</summary>

      <param name="other">The tuple to compare with this instance.</param>

      <returns><p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="1" sourceendlinenumber="2"><p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="1" sourceendlinenumber="1">A signed integer that indicates the relative position of this instance and                      <code data-dev-comment-type="paramref">other</code> in the sort order, as shown in the following able.  </p>
 <table><thead><tr><th> Vaue  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="4" sourceendlinenumber="4"> </th><th> Description  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="6" sourceendlinenumber="6"> </th></tr></thead><tbody><tr><td> A negative integer  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="8" sourceendlinenumber="8"> </td><td> This instance precedes                                      <code data-dev-comment-type="paramref">other</code>.  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="10" sourceendlinenumber="10"> </td></tr><tr><td> Zero  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="12" sourceendlinenumber="12"> </td><td> This instance and                                      <code data-dev-comment-type="paramref">other</code> have the same position in the sort order.  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="14" sourceendlinenumber="14"> </td></tr><tr><td> A positive integer  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="16" sourceendlinenumber="16"> </td><td> This instance follows                                      <code data-dev-comment-type="paramref">other</code>.  <p>
<p sourcefile="System.ValueTuple.yml" sourcestartlinenumber="18" sourceendlinenumber="18"> </td></tr></tbody></table></p>
</returns>

    </member>
```

**Comment by karelz** [comment] 2018-01-11 18:40
@jcouv can you please comment?

**Comment by jcouv** [comment] 2018-01-11 18:44
I'll take a look.
It's the first time I see this file (it's not part of the source), so something must be generating it. I'll check with Wes and Eric.

**Comment by danmosemsft** [comment] 2018-01-11 18:45
@svick isn't this file written by Roslyn? eg with
`/doc:C:\git\corefx\bin/AnyOS.AnyCPU.Debug/System.ValueTuple/netcoreapp/System.ValueTuple.xml`

Other quirkiness; https://github.com/dotnet/corefx/issues/25764

**Comment by svick** [comment] 2018-01-11 20:52
@danmosemsft I don't know.

There are XML files for `ref` assemblies, whose source code doesn't have documentation comments. The wording is different than the source ([source](https://github.com/dotnet/corefx/blob/cc4cc40/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L363): "A signed number", XML: "A signed integer"). And I don't think Roslyn uses YAML. To me, all of this indicates that's it's not just `/doc`, but I haven't actually looked into it.

Also, if it turns out to be a bug in Roslyn, I think this repo is still the right place for the initial analysis and for producing a good repro for Roslyn.

**Comment by danmosemsft** [comment] 2018-01-11 21:53
@mairaw can you explain where the xml files come from like the one above? I see them in bin\docs but I don't see the strings in them in our sources. What generates them?

**Comment by mairaw** [comment] 2018-01-11 22:00
Unfortunately, I don't know where this xml comes from @danmosemsft. That API is not even in our docs yet. Maybe @weshaggard knows?

**Comment by mairaw** [comment] 2018-01-11 22:03
Scratch what I said about not having that API. When I clicked on the source link, it took me to ValueTuple, instead of ValueTuple<T>. Let me dig more. /cc @rpetrusha

**Comment by mairaw** [comment] 2018-01-11 22:48
Ron and I looked at the shipped files before and this was a bug in the previous version of our IntelliSense generator which included that broken content. The current version of our tooling is not generating IntelliSense like that anymore. 

But thinking long-term and not only about this specific issue, I wonder if it would be better to change the return value to a simple description like shown in the code vs. our docs. The table looks good online but it doesn't translate well to IntelliSense.

For this specific issue though, the tool no longer generates a System.ValueTuple.xml for .NET Core 2.0 as it used to, given that the API is defined in System.Runtime.dll. So I'm wondering how we wanna fix this. We have an upcoming discussion with @dend to document some of our NuGet packages (which in turn gives us the IntelliSense files).

**Comment by danieldemus** [comment] 2018-02-02 11:41
The invalid xml also prevents sandcastle (and I presume any other documentation tool that automatically looks for dependency documentation) from working. So the issue is quite visible.

**Comment by satano** [comment] 2018-02-08 07:44
We have the same problem - SHFB is not able to build our documentation because of this invalid XML file. The workaround we use is to delete the file (or whole ValueTuple package) before building documentation.

**Comment by joperezr** [comment] 2018-02-27 00:18
@mairaw any comments on how to fix this? I believe this should be fixed before 2.1.

**Comment by mairaw** [comment] 2018-02-27 20:45
I believe @rpetrusha was working with @weshaggard to get this fixed. They should confirm.

**Comment by weshaggard** [comment] 2018-02-27 21:11
I've recently updated the intellisense files https://github.com/dotnet/corefx/pull/27005 so the xml file itself should no longer have this issue. However I'm not sure that the xml file as all the necessary API docs yet because there is still work to support documenting our nuget packages.

**Closed by weshaggard** 2018-02-27 21:11 UTC
Labels: area-System.Runtime, bug, tracking-external-issue
