### ISSUE TITLE
Character encoding errors with .NET Core on Linux

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#31278] opened 2018-07-23 18:36 UTC
Original issue https://github.com/dotnet/core/issues/1791 

**_@shaulbehr commented 7 days ago_**

This has been driving me batty for days, and I've finally got it down to a simple, reproducible issue.

I have a NUnit test project, which is .NET Core 2.1. It references a library (let's call it "Core") which is .NET Standard 2.0.

In my test project:
```
	[TestCase(true, false)]
	[TestCase(false, false)]
	[TestCase(false, true)]
	public void ShouldStartWith(bool useInternal, bool passStartsWith)
	{
		var result = useInternal ? StartsWithQ("¿Que?") : StringUtilities.StartsWithQ("¿Que?", passStartsWith ? "¿" : null);
		result.ShouldBeTrue();
	}

	public static bool StartsWithQ(string s)
	{
		return _q.Any(q => s.StartsWith(q, StringComparison.InvariantCultureIgnoreCase));
	}
```
and in the `Core` project in the `StringUtilities` class:
```
	public static bool StartsWithQ(string s, string startsWith = null)
	{
		return startsWith == null
			? _q.Any(q => s.StartsWith(q, StringComparison.InvariantCultureIgnoreCase))
			: s.StartsWith(startsWith, StringComparison.InvariantCultureIgnoreCase);
	}
```
Both classes have defined a list of special characters:
```
	private static readonly List<string> _q = new List<string>
	{
		"¡",
		"¿"
	};
```
In a Windows environment, all test cases pass. But when the same tests run in the Linux environment, the test case `ShouldStartWith(False,False)` fails!

That means that when everything is running in the test project, the string comparison works correctly, and even if you pass the special characters to the `StringUtilities` method, the comparison works. But when you compare to a string that was compiled in the Core project, the special characters are no longer equivalent!

Is this a .NET bug? How to work around it?

P.S. I have also asked this question on [StackOverflow](https://stackoverflow.com/q/51364469/7850), in case you want to answer it there, too.

**Comment by svick** [comment] 2018-07-23 20:31
I can't reproduce this. When I follow your instructions and then run `dotnet test` on .Net Core 2.1 on Ubuntu, all tests pass. Can you provide a complete example that demonstrates the issue? The best option is probably a zip archive that contains a tiny solution with all the relevant code.

**Comment by shaulbehr** [comment] 2018-07-24 13:07
OK, I'm working on setting up a Linux VM locally now. Having some trouble, so it might be a couple of days before I can follow up on this...

**Comment by tarekgh** [comment] 2018-08-15 18:27
@shaulbehr I am going to close this issue but feel free to respond back when you have a repro and we can re-open the issue and investigate. Thanks.

**Comment by shaulbehr** [comment] 2018-10-11 09:01
Ok, I got a repro now. It happens when I build the test project for Docker and run it in the Docker container.

**Comment by tarekgh** [comment] 2018-10-11 16:12
@shaulbehr could you please share more information about the docker container you are using?  are you using Alpine image? I am asking because I guess this could be because you are running in globalization invariant mode  https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md

**Comment by tarekgh** [comment] 2018-10-11 16:52
@shaulbehr thanks for your reply. Could you please check if ICU packages is installed on these images and used when running your test? also, could you please send me the pointer to the exact docker image you are using from https://hub.docker.com/?

**Comment by shaulbehr** [comment] 2018-10-11 17:59
@tarekgh I don't know what ICU packages are (I'm a bit of a Docker newbie).
The Microsoft images can be found [here](https://hub.docker.com/r/microsoft/dotnet/).

**Comment by tarekgh** [comment] 2018-10-11 18:19
sorry it looks I was not clear in my question regarding the pointer of the docker image. which specific image you choose from https://hub.docker.com/r/microsoft/dotnet/? for example, did you choose 2.1/sdk/stretch/arm32v7/Dockerfile?

**Comment by joperezr** [comment] 2018-10-11 19:15
We tried this on the microsoft/dotnet:2.1-sdk docker container with your tests and it works fine for us. Here is the output we get from your test run:
```
Test run for /home/joe/repro/bin/Debug/netcoreapp2.1/repro.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 4. Passed: 4. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0.8965 Seconds
```

**Comment by tarekgh** [comment] 2018-10-16 16:55
@shaulbehr do you have any update?

**Comment by shaulbehr** [comment] 2018-10-16 20:40
I wish I could say that I do, but I'm not in control of my own time, and I've been moved on to something more urgent for the time being. If you want to close this ticket in the meantime, that's fine, and I'll update you when I get another chance to look at this. Sorry...

**Comment by tarekgh** [comment] 2018-10-16 20:49
thanks @shaulbehr. I'll close the issue for now but feel free to reply back and we can re-open it.

**Closed by tarekgh** 2018-10-16 20:49 UTC
Labels: area-System.Globalization, os-linux, question

**Comment by danilobreda** [comment] 2019-05-02 23:00
Im having the same issues, [https://github.com/JeremySkinner/FluentValidation/issues/1105](Here)
The problem is occorring only on linux, On my build server (Ubuntu 18.04) and on production docker microsoft/dotnet:2.2-aspnetcore-runtime (old repo).
The Tests is getting some fails and when published the rest calls is returning the json with REPLACEMENT CHARACTER (�) when ã, é, ç... #1105

**Comment by danilobreda** [comment] 2019-05-02 23:11
The problem can be the [ICU](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md)? 
I think this is not installed on my linux build machine, and probably on the docker image, @tarekgh can you help me with that?

**Comment by tarekgh** [comment] 2019-05-02 23:18
@danilobreda  for ```microsoft/dotnet:2.2-aspnetcore-runtime``` I think you are running into the issue https://github.com/Microsoft/Oryx/issues/68 which is the image is enabling the Globalization Invariant mode. They are working to fix the image. 

For ```server (Ubuntu 18.04)``` could you check if you have the same issue as you indicated? Could you double check if the ICU is installed on that server? and if there is environment variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT defined there?

**Comment by danilobreda** [comment] 2019-05-03 19:05
On ubuntu 18.04 (Build Machine)
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.603 [/usr/share/dotnet/sdk]
  2.2.203 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

> dpkg -l | grep libicu
> ii  libicu60:amd64                                              60.2-3ubuntu3                                               amd64        International Components for Unicode

And no DOTNET_SYSTEM_GLOBALIZATION_INVARIANT on env command.
The Problem on this build machine is when  i execute a test(mstest) with Azure Devops Agent OR manually (dotnet test example.csproj)
```
 Failed   ComErro_Plano_Obrigatorio
Error Message:
 Expected resultInsert.Errors to contain only items matching (x.ErrorMessage == value(Bredas.OverallContrato.Tests.Validations.Entities.ContratoValidationTest+<>c__DisplayClass8_0).erroRequerido), but {Bredas.SharedKernel.Domain.Validators.DomainValidatorError
   {
      ErrorMessage = "Plano � obrigat�rio"
      Field = "Plano"
      Value = ""
   }} do(es) not match.
Stack Trace:
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\LateBoundTestFramework.cs:line 16
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.OnlyContain(Expression`1 predicate, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 511
   at Bredas.OverallContrato.Tests.Validations.Entities.ContratoValidationTest.ComErro_Plano_Obrigatorio() in /opt/vstsagent/_work/17/s/Bredas.OverallContrato.Tests/Validations/Entities/ContratoValidationTest.cs:line 146
```
The test code of the .cs file in this machine is ok with the correct accent when i execute a "cat"

 cat Validations/Entities/ContratoValidationTest.cs

```
[TestMethod]
        public void ComErro_Plano_Obrigatorio()
        {
            string erroRequerido = "Plano é obrigatório";
            long idEmpresa = 1;
            long idGrupo = 1;
            var aplicacao = AplicacaoFactory.GetAplicacao();

            var contrato = ContratoFactory.GetContrato(idEmpresa, idGrupo, aplicacao, null);

            var resultInsert = _domainValidator.ValidateEntity(contrato, DomainValidationRuleTypes.INSERT_VALIDATIONS);
            var resultUpdate = _domainValidator.ValidateEntity(contrato, DomainValidationRuleTypes.UPDATE_VALIDATIONS);
            resultInsert.Errors.Should().OnlyContain(x => x.ErrorMessage == erroRequerido);
            resultUpdate.Errors.Should().OnlyContain(x => x.ErrorMessage == erroRequerido);
        }
```
On my windows local machine, on visual studio 2019 community, the test pass, (the code is the same branch!)
if i replace all the accents of the the words, the project test pass too, thats how im using right know.
The language is pt-BR

**Comment by danilobreda** [comment] 2019-05-03 19:53
I changed the dockerfile:
microsoft/dotnet:2.2-aspnetcore-runtime -> mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
microsoft/dotnet:2.2-sdk -> mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

The problem persist.
the strangest thing is that the problem occurs only when it goes through validation (fluentValidation package).
{"errors":[{"errorMessage":"Nome � obrigat�rio","field":"Nome","value":""}]} (translates to "name is required")

**Comment by tarekgh** [comment] 2019-05-03 22:36
@danilobreda what exactly is failing? I mean what is the call to .NET that cause the failure in your test? could you please create a simple repro so we can help? 

> the strangest thing is that the problem occurs only when it goes through validation (fluentValidation package).

Is it possible for any reason the text get encoding to something different during this call?

**Comment by danilobreda** [comment] 2019-05-07 03:01
Found some issues with [FluentValidator Here](https://github.com/JeremySkinner/FluentValidation/issues/1105#issuecomment-489887538).
Probably the problem is not from .net initially.
Thanks for your time 👍

**Comment by danilobreda** [comment] 2019-05-07 15:09
Problem was file encoding, need to be UTF8 (without BOM).
