### ISSUE TITLE
RegularExpression validation does not handle \p{L} properly

### ISSUE THREAD

**Issue by jasonleenaylor** [dotnet/corefx#42487] opened 2019-11-08 19:30 UTC
I filed this bug against ASP.Net Core (https://github.com/aspnet/AspNetCore/issues/16904) and they seemed to think the problem was here in corefx.

### Description
We are using the RegularExpressionAttribute to validate a Name field and want to handle more than ASCII characters. Using the regular expression @"[\p{L}\s-'\.]+" works to match the strings we need. Example: "François O'Brian-McKay Jr."

This works fine in a C# unit test but when deployed on the server it only validates the 'L' character and the punctuation.

### To Reproduce

``` C#
public class TestModel : PageModel
{
        [RegularExpression(@"^[\p{L}\s-'\.]+$", ErrorMessage = "Invalid characters in name.")]
        public string Name { get; set; }
}
```

### Further technical details
- ASP.NET Core 2.1

.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Unit test and work done in Microsoft Visual Studio Community 2017 Version 15.8.1

**Comment by GrabYourPitchforks** [comment] 2019-11-08 19:38
To clarify, you're observing that this regex matches only four characters: the literal 'L', the hyphen, the apostrophe, and the period? So if I were to pass the string "Hello", it'd fail?

**Comment by danmosemsft** [comment] 2019-11-08 19:45
@GrabYourPitchforks it's not a literal L, `\p{L}` should match anything in the Unicode letter category, right?

**Comment by danmosemsft** [comment] 2019-11-08 19:46
Also anything after the hyphen should be subtracted from the character group. It's not a literal hyphen.

**Comment by danmosemsft** [comment] 2019-11-08 20:34
@jasonleenaylor what do you mean by "it only validates the L character"? What string is it failing to match?

**Comment by jasonleenaylor** [comment] 2019-11-13 16:07
@GrabYourPitchforks Yes, that is what I'm observing.

**Comment by jasonleenaylor** [comment] 2019-11-13 16:09
@danmosemsft What I am seeing is what GrabYourPitchForks clarified. It would not match "Hello" but it would Match "L'-."

**Comment by danmosemsft** [comment] 2019-11-13 18:48
I'm missing something 😃 this prints 'true' on latest bits from master, and on 2.1 for me:
```c#
            bool result = Regex.IsMatch("Hello", @"^[\p{L}\s-'\.]+$");
            Console.WriteLine($"IsMatch: {result}");
```

**Comment by jasonleenaylor** [comment] 2019-11-14 20:14
@danmosemsft Yes, as I mentioned in my report it works fine if I use it in a C# unit test but as soon as I try to use the RegularExpressionAttribute in ASP.Net Core I get the bad behavior. It is acting as if the ECMAScript option is set.

**Comment by danmosemsft** [comment] 2019-11-14 20:28
@anurse do you know whether the ASP.NET attribute above implicitly passes `RegexOptions.ECMAScript` ? That would not be unreasonable for it to do.

**Comment by danmosemsft** [comment] 2019-11-14 20:32
I'm looking here https://source.dot.net/#System.ComponentModel.Annotations/System/ComponentModel/DataAnnotations/RegularExpressionAttribute.cs,104 .. if that's the right place, then apparently it's not.

**Comment by anurse** [comment] 2019-11-14 20:46
I don't believe it does (after [searching the code](https://github.com/aspnet/AspNetCore/search?l=C%23&q=ECMAScript)). There is no ASP.NET attribute, it's just the DataAnnotations attribute that is used by MVC model binding.

I tried using the attribute directly and couldn't repro either. I don't see anywhere that ASP.NET is setting ECMAScript options.

> This works fine in a C# unit test but when deployed on the server it only validates the 'L' character and the punctuation.

@jasonleenaylor Can you clarify *where* you're seeing this error? Is it in the client-side validation that MVC generates to run in the browser? If so, that would definitely be using ECMAScript-style Regexes since it is implemented in JavaScript. Perhaps a complete repro sample that describes where the error is observed would help us understand this better.

**Comment by jasonleenaylor** [comment] 2019-11-14 21:10
@anurse Yes, sorry I wasn't specific enough. Probably I didn't understand all that I should have.

In TestModel.cshtml.cs we have:
```
public class TestModel : PageModel
{
       [BindProperty]
        [Required(ErrorMessage = "Name missing"]
        [RegularExpression(@"^[\p{L}\s-'\.]+$", ErrorMessage = "Invalid characters in name.")]
        public string Name { get; set; }

}
```

In TestModel.cshtml we have:
```
...
<div asp-validation-summary="All" class="required"></div>
    <form method="POST" asp-antiforgery="false">
        <div class="field-container">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Name">
                <label class="mdl-textfield__label" for="Name">
                    What's your name and last name? <span class="required">*</span>
                </label>
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        ...
    </form>
...
```
When typing content in this form in the browser I'm seeing the unexpected behavior. So from the comments I gather that this validation attribute ends up becoming javascript regex which then loses the ability to do what I need.

**Comment by anurse** [comment] 2019-11-14 21:20
Yes, that's correct. In order to do client side validation we have to push the regex down to the browser and us JavaScript to evaluate it. That's not really something we can avoid here :(.

**Comment by danmosemsft** [comment] 2019-11-14 21:31
Ah, then I think this is by design. 

@anurse if @jasonleenaylor is willing to offer a PR for the docs, which would be the right doc? https://github.com/aspnet/ApiDocs/blob/master/aspnet-mvc/xml/System.Web.Mvc/RegularExpressionAttributeAdapter.xml ?

**Comment by anurse** [comment] 2019-11-14 22:43
Unfortunately for this one, there isn't a good API doc. The only API the user interacts with is [`RegularExpressionAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.regularexpressionattribute?view=netcore-3.0) which isn't web specific. The best we could do in an API is say "when used for ASP.NET model binding, [blah blah blah]", which is a little awkward.

A PR to the narrative doc may be useful since that is describing validation specifically in the web context: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation

**Comment by danmosemsft** [comment] 2019-11-15 00:20
OK. I'll close this one then as I believe this is resolved. We'd welcome a doc tweak PR @jasonleenaylor  or an issue for it. Thanks for the report.

**Closed by danmosemsft** 2019-11-15 00:20 UTC
Labels: area-System.Text.RegularExpressions

**Comment by GrabYourPitchforks** [comment] 2019-11-15 06:12
Maybe a good candidate for static analysis? I don't know how easy it would be to detect that a particular attribute might end up being emitted as client-side validation, but assuming that's detectable it should be straightforward to detect regex patterns that lose fidelity client-side.

**Comment by jasonleenaylor** [comment] 2019-11-21 17:02
@danmosemsft I'm happy to provide a documentation tweak PR, but I couldn't figure out where the source for https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation came from.

**Comment by danmosemsft** [comment] 2019-11-21 17:11
@anurse can you help find it? I was thinking somewhere in https://github.com/aspnet/AspNetDocs ?

**Comment by anurse** [comment] 2019-11-21 17:29
The Edit button on any doc should take you straight to the GitHub path to the source.

![image](https://user-images.githubusercontent.com/7574/69361354-2caa7e80-0c41-11ea-8ec9-f7d8291d359a.png)

In this case: https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md

A PR to update the doc would be awesome @jasonleenaylor !

**Comment by danmosemsft** [comment] 2019-11-21 17:47
Oh! I didn't realize that. Thank you, that's useful knowledge.

**Comment by jasonleenaylor** [comment] 2019-12-12 16:07
@anurse @danmosemsft I did make a PR for the docs with my best effort to help devs like me. :-)
