### ISSUE TITLE
math.round return different results with same decimal part

### ISSUE THREAD

**Issue by hotlhg** [dotnet/corefx#36953] opened 2019-04-17 07:25 UTC
is this a known issue?

![image](https://user-images.githubusercontent.com/4005904/56268589-4e300e80-6124-11e9-83b9-2e39866e8f61.png)

**Comment by Gnbrkm41** [comment] 2019-04-18 00:46
511.92500000000001 => 511.93
512.92499999999995 => 512.92

654.92499999999995 => 654.92
655.92499999999995 => 655.93

Try checking these values with `i.ToString("G17")`

**Comment by danmosemsft** [comment] 2019-04-18 00:50
@tannergooding

**Comment by Gnbrkm41** [comment] 2019-04-18 01:50
related: #36982

**Comment by tannergooding** [comment] 2019-04-18 01:53
Yes, I've logged https://github.com/dotnet/corefx/issues/36982 to track the work.

Ultimately, the current code is wrong and is not IEEE compliant. It wasn't something that was on my radar for 3.0; and so will need to be fixed in some future release.

**Comment by danmosemsft** [comment] 2019-04-18 15:45
Sounds like this is a dupe of that now?

**Comment by tannergooding** [comment] 2019-04-18 16:09
Yes. Will close this in favor of it.

**Closed by tannergooding** 2019-04-18 16:09 UTC
