### ISSUE TITLE
New modifier with different type is not hiding base property

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#38154] opened 2019-06-03 02:33 UTC
New modifier with different type is not hiding base property, throwing `System.InvalidOperationException: The JSON property name for 'System.Text.Json.Serialization.Tests.FooBar1.foo' collides with another property.` 
It is workign as expected when base derived property types are same.
This issue is edge case, with very low priority. 
```csharp
[Fact]
public void DerivedClassHidingBasePropertySerializesAsExpected()
{
    var original = new FooBar1 { foo = "value" };  //System.InvalidOperationException : The JSON property name for 'System.Text.Json.Serialization.Tests.FooBar1.foo' collides with another property.
    var json = JsonSerializer.ToString(original);
    var expectedJson = @"{""foo"":""value""}}";
    Assert.Equal(expectedJson, json);
}
[Fact]
public void DerivedClassHidingBasePropertyDeserializesAsExpected()
{
    var json = @"{""foo""/:""value""}";
    var deserialized = JsonSerializer.Parse<FooBar1>(json); // System.InvalidOperationException : The JSON property name for 'System.Text.Json.Serialization.Tests.FooBar1.foo' collides with another property.
    Assert.NotNull(deserialized.foo);
    Assert.Equal("value", deserialized.foo);
}
		
public class FooBar1 : Foo1
{
    public new string foo { get; set; }
}
public class Foo1
{
    public object foo { get; set; }
}

**Comment by layomia** [comment] 2019-11-23 08:33
Duplicate of https://github.com/dotnet/corefx/issues/41338.

**Closed by layomia** 2019-11-23 08:33 UTC
Labels: area-System.Text.Json, json-functionality-doc
