### ISSUE TITLE
Re add netcore50 test runs for some System.Xml test projects once System.Private.Xml builds for netcore50

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#11726] opened 2016-09-14 22:31 UTC
PR #11717 removed netcore50 test runs for a few projects in System.Private.Xml in order to unblock the PipeBuild given that those projects depended on System.Private.Xml which didn't run in all supported netcore50 platforms. Once it does, then we should add those configurations back.

cc: @sepidehMS

**Comment by krwq** [comment] 2016-10-25 18:57
As this is UWP specific, we can defer it for now @danmosemsft

**Comment by danmosemsft** [comment] 2017-02-27 22:52
@joperezr can this be closed as a dupe of https://github.com/dotnet/corefx/issues/14935

**Closed** 2017-06-06 20:31 UTC
Labels: area-System.Xml, test bug
