### ISSUE TITLE
Convenience extension methods for Span<T> for interop with IEnumerable<T> et al?

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/corefx#17093] opened 2017-03-14 12:59 UTC
There doesn't seem to exist a method that allows the creation of an `IEnumerable<T>` from a `Span<T>`.

Useful extension methods would include:

* `ToEnumerable()`

  Useful for passing a `Span<T>` to a function accepting `IEnumerable<T>` (e.g. for LINQ)

* `GetEnumerator()`

  Should save one allocation when compared to `ToEnumerable()`

* `AsReadOnlyList()`

  For indexed access in code indicating that:

    1. Read-only access
    2. Indexed access
    3. Avoid multiple re-enumeration when used in multiple places

* `AsList()` where `IsReadOnly` returns `true`

    For APIs that don't know about `IReadOnlyList<T>` and companions.

**Comment by svick** [comment] 2017-03-14 18:52
I don't think that would work, since `Span<T>` is stack-only and so you can't have for example a method that returns `IEnumerable<T>`, where the returned object contains the `Span<T>`.

On the other hand, I think this should work `Memory<T>`, which is basically a version of `Span<T>` with less limitations, but one that is also less efficient. `Memory<T>` could likely even implement `IEnumerable<T>` and `IReadOnlyList<T>` itself.

See also: "Remove IEnumerable<T> from Spans" https://github.com/dotnet/corefxlab/issues/838.

**Comment by KrzysztofCwalina** [comment] 2017-03-14 20:23
As @svick explained, there is no way to do it without making a copy of the data. Span\<T\>.ToArray() copies the data and can directly or indirectly do what @fubar-coder described above.

**Comment by fubar-coder** [comment] 2017-03-14 22:23
There's absolutely no way to enumerate over the elements covered by a span without a for loop? Is it impossible to box (copy) a Span<T>?

**Comment by benaadams** [comment] 2017-03-14 22:26
Boxing moves it from stack to heap and span is a stack only type, so you can't box it (which is why it implements no interfaces)

**Comment by KrzysztofCwalina** [comment] 2017-03-15 01:06
@svick, you might want to look at type called Memory<T>. It might be better suited to what you want to do.

**Comment by ahsonkhan** [comment] 2017-03-17 02:56
@svick, can you close this issue and possibly open one for `Memory<T>` in https://github.com/dotnet/corefxlab/issues if it is relevant?

You can find `Memory<T>` here:
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/Memory.cs#L15

**Comment by ahsonkhan** [comment] 2017-03-25 02:21
@karelz @KrzysztofCwalina, close this issue?

**Comment by karelz** [comment] 2017-03-25 02:49
Your call. I don't follow details which parts of `Span<T>` is in CoreFX and which is still in CoreFXLab

**Comment by ahsonkhan** [comment] 2017-03-25 03:06
This isn't about repos. The issue is invalid for `Span<T>`. @svick, consider opening an issue for `Memory<T>`

> I don't think that would work, since `Span<T>` is stack-only and so you can't have for example a method that returns `IEnumerable<T>`, where the returned object contains the `Span<T>`.

> Boxing moves it from stack to heap and span is a stack only type, so you can't box it (which is why it implements no interfaces).

**Closed by ahsonkhan** 2017-03-25 03:06 UTC
Labels: api-needs-work, area-System.Memory

**Comment by karelz** [comment] 2017-03-25 03:28
OK, I didn't get that part from a quick skim. Either way, if you think it is invalid, close it. If you're unsure, consult your area co-owners (@KrzysztofCwalina @shiftylogic).

I can help with general community discussions (incl. the controversial ones), escalations and general guidance on bugs & API process, triage rules, docs routing, etc. I won't scale to become expert on every area though ;-)
