### ISSUE TITLE
Cannot open resource editor in VS on corefx projects

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#10200] opened 2016-07-20 21:41 UTC
Opening src\System.Reflection.Metadata\src\Resources\Strings.resx in VS, I get the following:

```
Could not resolve mscorlib for target framework '.NETPortable,Version=v4.5,Profile=Profile7'.  
Thiscan happen if the  target framework is not installed or if the framework moniker is 
incorrectly formatted.
```

C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7 is installed so I assume this has something to do with the build customization in corefx. Not necessarily related, but should we even be referencing portable profiles anywhere anymore?

**Comment by mellinoe** [comment] 2016-07-20 22:16
It most likely has to do with this stuff: https://github.com/dotnet/buildtools/blob/42f2315bdeb7e6d671f9ac8ffb1b3c0f800dbb22/src/Microsoft.DotNet.Build.Tasks/PackageFiles/FrameworkTargeting.targets#L31

We can most likely do another round of cleanup of some of this hacky stuff.

**Comment by joperezr** [comment] 2016-08-02 21:31
This is a dupe of #4883

**Comment by joperezr** [comment] 2016-08-02 21:31
Closing as a dupe.

**Closed by joperezr** 2016-08-02 21:31 UTC
Labels: Infrastructure
