### ISSUE TITLE
A small suggestion for making the VS experience in corefx more idiot-proof.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#7973] opened 2016-04-21 21:41 UTC
Know all these lines that show up in various .csproj files?

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Windows_Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Windows_Release|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Unix_Debug|AnyCPU'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Unix_Release|AnyCPU'" />
```

Well heck, these are just NOP's - might as well get rid of them, right? Or at least, not worry if they don't line up with the Configurations actually supported by the project (is this library "Debug" or "Windows_Debug"?)

**Wrong**. I just found out, the hard way, that the VS IDE looks for these conditionals as a sign that a .csproj "supports" a certain configuration. And if the .sln file specifies a certain configuration for your .csproj file and your .csproj file doesn't have this magic line, VS "helpfully" "fixes" your .sln to use a configuration that the .csproj appears to support (how does it know it picked a good one? Beats me.) And unless you're like me and keep files read-only as long as possible, you'll get no notice that "Hey! We just applied a fix to _your_ file without knowing what we're doing. But I guess you didn't need to know that."

In the mean time, hitting F6 now yields broken or misleading results and you wonder why you have to commit an .sln file change that you have no understanding of.

This seems like boilerplate that could go into dir.props so everyone doesn't have to deal with this. It's fine by me if the boilerplate includes every $(Configuration) name we use repo-wide - I see no value in the VS IDE insisting that the $(Configuration)/Project pairup be approved on both sides like that.

**Comment by mellinoe** [comment] 2016-04-21 23:48
On the one hand, those blocks can be a bit confusing, and in a lot of projects are out-of-sync, out-dated, or worse, just wrong. On the other hand, I think it would not be better to have every single option listed in the solution in VS. There will be no way to figure out if I should select from "net45, net451, net46, net461, net462, net47, etc." without either 1) looking at the .builds file or 2) scouring over the csproj to see all valid TargetGroup's. I think there's way too many configurations to just leave them all in the list.

Even aside from this, we need to figure out how we can clean up and keep our solution files in sync. I would be in support of an effort to:

1. Add all the configurations to dir.props (or somewhere top-level).
2. Auto-generate all solution files in the repo, and enforce valid configurations by parsing the .builds files. We should include this as a target somewhere so we can re-run it if something goes wrong or gets out of sync.
3. Delete all of these configuration blocks from all individual projects.

On the other hand, I actually have found that having these configuration blocks in the project to be helpful, provided that I already know they are correct (i.e. I just added them myself, or I just fixed them myself). It makes it easier when modifying conditions in the project to be sure that you are condition'ing on a valid property set. Technically this can also be achieved by looking into the .builds file, however.

**Comment by bartonjs** [comment] 2016-06-18 17:10
Since we do have the builds files now, maybe it's worth making a tool which does, approximately:
* Find a builds file
* Ensure it only talks about a .csproj in the same directory
* Clear out the configurations
* Regenerate Debug/Release configurations for everything in the .builds file

Though I guess really it might want to be done as a library/.sln thing; since then you can regen the .sln after all of the libraries it references are done.

**Comment by karelz** [comment] 2016-11-14 19:38
Dupe of #4919.

**Closed by karelz** 2016-11-14 19:38 UTC
Labels: enhancement, Infrastructure, up for grabs
