### ISSUE TITLE
Memory growth of WinHttpRequestState objects

### ISSUE THREAD

**Issue by shortspider** [dotnet/corefx#11674] opened 2016-09-13 15:54 UTC
I have a web server that accepts an http request and then makes a post request to a bunch of other servers using `HttpClient`. To speed this up we make a `Task` for each request and call `HttpClient.PostAsync` inside each task. These tasks are synchronously waited on with `Task.WaitAny` in order to check the results as they come in. All the code inside the tasks uses async/await. Finally, each task get's a new `HttpClient` but they all use a shared static `HttpClientHandler` which is not disposed when the client is disposed.

I have been having issues where out of the blue all of the memory on the server is used up and the number of handles goes through the roof. This happens suddenly over the course of a 10-15 min. Looking at the dumps I have been able to get I can see that most of the handles are rooted in `WinHttpRequestState`.

While I am still unsure of the root cause I was looking at  `WinHttpHandler` and `WinHttpRequestCallback` and noticed that `WinHttpRequestCallback.RequestCallback` is surrounded in a try/catch, however if any exception is thrown `WinHttpHandler` is not signaled by `WinHttpRequestCallback.RequestCallback` because none of it's `TaskCompletionSource`s are given the exception.

Is this correct? If an exception does happen in `WinHttpRequestCallback.RequestCallback` will the task created by `WinHttpHandler.SendAsync` just sit forever? Please let me know if I have missed something.

Thanks!

**Comment by davidsh** [comment] 2016-09-13 16:04
>Finally, each task get's a new HttpClient but they all use a shared static HttpClientHandler which is not disposed when the client is disposed.

This is not a recommended pattern.  There is no advantage to using a separate instance of HttpClient but a static shared instance of HttpClientHandler. I would recommend you either reuse a single HttpCLient w/ HttpClientHandler instance or new instances if you cannot share them.

In regards to memory increases due to `WinHttpRequestState` objects hanging around, we are aware of some cases where this occurs.

In regards to your questions about exception handling in `WinHttpRequestCallback`, those TCS's are not passed the exception directly except to store that exception in the savedException field for later use.

It sounds like your real observation in this issue is about perceived memory growth of `WinHttpRequestState` objects. That is issue #8819

**Comment by shortspider** [comment] 2016-09-13 16:26
>I would recommend you either reuse a single HttpCLient w/ HttpClientHandler instance

So it's safe to call `HttpClient.PostAsync` from multiple threads on the same object? The MDSN docs are a little vague on this.

>In regards to your questions about exception handling in WinHttpRequestCallback, those TCS's are not passed the exception directly except to store that exception in the savedException field for later use.

I'm sorry if this is really stupid but how does the `WinHttpHandler` get signaled that there was an exception in `WinHttpRequestCallback` if all that happens is `WinHttpRequestState.SavedException` is set?

I do have a few instances of exceptions from `WinHttpRequestCallback` but the call-stack does not provide much detail:

```
ThrowLevel: 0 >>>>>>
Exception: System.NullReferenceException EXB7F25E50
Message: Object reference not set to an instance of an object.
 at System.Net.Http.WinHttpRequestCallback.RequestCallback(...)
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
//My application code
```

**Comment by benaadams** [comment] 2016-09-13 18:01
There was that article recently that may be related: [You're using HttpClient wrong and it is destabilizing your software ](http://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)

**Comment by shortspider** [comment] 2016-09-13 18:25
@benaadams I actually was doing exactly that in the beginning and ran into the issues described there (I really wish that article had been written in July :stuck_out_tongue:). However making the handler static seemed to resolve those issues.

What I see now is that the application runs and seems to be running fine, memory is good as is throughput and socket usage. However all of a sudden the memory and number of handles spikes through the roof and the application crashes. This seems to happen randomly, it happening once a day for three days and then didn't happen for over a week before happening again a few more times.

**Comment by mconnew** [comment] 2016-09-14 04:05
@davidsh, there is one scenario where there's an advantage to maintaining a static HttpClientHandler but creating and disposing HttpClient instances. The scope of a connection pool is the HttpClientHandler, so all requests using the same handler will pool together. By instantiating an HttpClient specifying not to dispose of the handler, this allows you to group related requests together using a single HttpClient and clean up any lingering requests just by calling Dispose() on the HttpClient. This does look to be a supported scenario, otherwise why would HttpClient have a constructor overload allowing you to specify not to dispose the handler? Although I'll admit this is definitely a very narrow specific use case and shouldn't be the normal way to do things.

**Comment by karelz** [comment] 2017-02-23 19:23
Looks like dupe of #8819.

**Closed by karelz** 2017-02-23 19:23 UTC
Labels: area-System.Net, untriaged
