### ISSUE TITLE
Marshal.SizeOf<T>() under Ubuntu 16.04 LTS throws an exception for structs when there is a field of a reference type.

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#20442] opened 2017-05-30 04:45 UTC
_From @marek86 on May 29, 2017 12:0_

public struct A
	{
		public double X;
		public object Obj;
	}

System.Runtime.InteropServices.Marshal.SizeOf<A>() works on Windows but throws ArgumentException on Ubuntu.

_Copied from original issue: dotnet/sdk#1263_

**Comment by danmosemsft** [comment] 2017-05-30 04:59
@yizhang82

**Comment by yizhang82** [comment] 2017-05-30 05:33
@marek86 Passing object in fields would marshal them as IUnknown and that is not supported on non-Windows. If you want to pass arbitrary objects around, you might want to try using GCHandle.

**Comment by stephentoub** [comment] 2017-05-30 16:15
Closing as by design.

**Closed by stephentoub** 2017-05-30 16:15 UTC
