### ISSUE TITLE
The type 'Assembly' exists in both 'System.Reflection' and 'System.Runtime'

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#14600] opened 2016-12-17 08:35 UTC
I try to use System.Json in .net core and it cause that error

This is my project.json

```JSON
{
  "name":"TTTT",
  "version": "1.0.0-*",
  "dependencies": {},
  "resource": [
    "*.json"
  ],
  "resourceExclude": [
    "project.json",
    "project.lock.json"
  ],
  "frameworks": {
    "netcoreapp1.1": {
      "imports": "dnxcore50",
      "dependencies": {
        "System.Json":"4.4.0-beta-24721-02",
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "Newtonsoft.Json": "9.0.1",
        "AWSSDK.Lambda":"3.3.*",
        "Amazon.Lambda.Core": "1.0.0*",
        "Amazon.Lambda.Serialization.Json": "1.0.0",
        "Amazon.Lambda.Tools": {
          "type": "build",
          "version": "1.0.0-preview1"
        }
      },
      "tools": {
        "Amazon.Lambda.Tools": "1.0.0-preview1"
      }
    }
  }
}
```

**Comment by karelz** [comment] 2016-12-17 20:00
It looks like you have a mix up of reference assemblies (System.Reflection, the 'right one') and implementation assemblies (System.Runtime, the 'bad one').
Can you find out where the latter comes from? (Trying minimal repro usually helps -- either starting with HelloWorld project, or by removing all unnecessary references)

**Comment by Thaina** [comment] 2016-12-17 21:09
@karelz It came from `System.Json 4.4.0-beta-24721-02`. I don't know why it use `System.Runtime` instead of `System.Reflection`

I can let it work by remove `System.Json` package from my project. But I want to use it

**Comment by karelz** [comment] 2016-12-17 22:49
Where did you get System.Json from? I can't find it on NuGet.
cc: @mellinoe @ericstj @weshaggard

**Comment by Thaina** [comment] 2016-12-18 06:18
There are on nuget but that is version 4.0

Version 4.3 which compatible with dotnetcore is hosted in dotnet.myget

**Comment by karelz** [comment] 2016-12-18 06:51
Is it possible that you are by accident referencing the implementation assembly instead of reference assembly? Can you somehow figure out the path it resolves from? (should be in build log or rsp file)

**Comment by Thaina** [comment] 2016-12-18 06:55
@karelz I was just using that version of System.Json and it was include System.Runtime as its dependencies by itself. I don't like to say it is accidental because it was process of dependencies. The point is, why System.Json in dotnet.myget say it compatible with dotnetcore while it use System.Runtime

**Comment by karelz** [comment] 2016-12-18 07:04
Did you check the package manually? Does the ref assembly truly reference System.Runtime?

**Comment by Thaina** [comment] 2016-12-18 07:17
@karelz https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Json

**Comment by karelz** [comment] 2016-12-18 07:39
I don't see ref for netstandard or netcore, only xamarin and mono. Probably packaging problem (or I don't understand NuGet at all) -- cc: @ericstj @mellinoe
Did you try to compare the ref directory list with last official System.JSon release?

**Comment by Thaina** [comment] 2016-12-18 07:42
This is what I see

![image](https://cloud.githubusercontent.com/assets/1042507/21292235/1da3106a-c530-11e6-9cb2-1936ab20cb21.png)

**Comment by karelz** [comment] 2016-12-18 07:51
The package System.JSon is not on nuget.org. Maybe you are not supposed to directly reference this package. Let's wait for experts to chime, you have reached the limits of my knowledge in this space ...

**Comment by Thaina** [comment] 2016-12-18 07:55
Well, I have already told you

> There are on nuget but that is version 4.0
> Version 4.3 which compatible with dotnetcore is hosted in dotnet.myget

And the thing is dotnet.myget is also owned by .net foundation. Which I conclude that it came from this repo

**Comment by davidfowl** [comment] 2016-12-18 21:20
This is a known issue, the latest CoreFX packages aren't usable without the latest nuget (which doesn't exist for anyone yet). That's currently being worked on AFAIK.

/cc @ericstj

**Comment by ericstj** [comment] 2016-12-19 14:33
Actually they work with the latest msbuild based CLI @davidfowl.  

Indeed the error here is caused by our reuse of netstandard1.7/netcoreapp1.1 in master which will be fixed with the rename that @alexperovich is doing.  Once that's in place you can target netcoreapp1.1 with the latest packages from CoreFx without an updated NuGet.  

That said you still won't get any of the netcoreapp2.0/netstandard2.0 API and that will still require private NuGet bits.

**Comment by karelz** [comment] 2016-12-19 16:42
OK, closing as by design then -- myget requires new NuGet.

BTW: I already have it on my todo list to properly document how to dogfood daily builds.
I also plan to schedule the version bump of netcoreapp in master right after we fork for release (2.0 or any future). That should also make things simpler.

**Closed by karelz** 2016-12-19 16:42 UTC
Labels: area-Infrastructure, question
