### ISSUE TITLE
Assembly.Load doesn't work for ASP.NET Core Web Application assembly targeting at net461

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#25591] opened 2017-11-30 01:43 UTC
Repro Step:
1. Create a ASP.NET Core Web Application targeting at net461. 
2. Create a console app targeting netcoreapp2.0. 
3. Use Assembly.Load to load the asp.net core app assembly created in step#1. I will get the FileLoadException "Could not load file or assembly ...". Is it expected?

**Comment by ViktorHofer** [comment] 2017-11-30 04:38
I believe you should be able to reference net461 assemblies from netcoreapp2.0. The other way around it definitely wouldn't work. Can you please provide some more details? Full error message, .NET Core Shared Framework and Host version (dotnet --info).

**Comment by huanwu** [comment] 2017-12-01 00:40
@ViktorHofer 
The error information is:
System.IO.FileLoadException
  HResult=0x80131621
  Message=Could not load file or assembly 'WebApplication5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

The output from dotnet --info is:
.NET Command Line Tools (2.1.1-preview-007165)

Product Information:
 Version:            2.1.1-preview-007165
 Commit SHA-1 hash:  a4d1a8e0bb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1-preview-007165\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by DnlHarvey** [comment] 2018-02-20 22:07
@huanwu I must be missing something from your steps, because I can't even load something targeting netcoreapp2.0 that way. Can you expand your steps or post a solution somewhere?

**Comment by joshfree** [comment] 2018-03-19 21:10
Moving to the future milestone as the issue is 'needs more info'.

@DnlHarvey I think the meta question is 'what is the expected behavior?'.  Perhaps you could help improve the docs for this @ https://github.com/dotnet/docs ?

**Comment by huanwu** [comment] 2018-03-19 22:56
@DnlHarvey The repro steps are exactly what I mentioned above.

**Comment by DnlHarvey** [comment] 2018-03-19 23:08
Ok the behavior I observed while following your steps seems expected. Given I'm observing different behavior from what you've described, that statement is likely not relevant to your question, but I can't offer a better answer without a way to reproduce what you've described.

**Closed by DnlHarvey** 2018-03-19 23:08 UTC
Labels: area-System.Reflection, needs more info, question
