### ISSUE TITLE
Collectible AssemblyLoadContext

### ISSUE THREAD

**Issue by Rohansi** [dotnet/corefx#3779] opened 2015-10-12 15:14 UTC
Collectible assemblies can be used for many different things but it usually comes down to some form of hot swapping code. Updating a plugin or compiling a new version of a Razor view, without restarting the process or leaking memory.

.NET Core currently has no way to unload assemblies from memory if they are no longer required. In the full .NET Framework you could load the assemblies into a separate AppDomain so they can be unloaded later.
## Proposed API

`AssemblyLoadContext` can be extended to enable developers to load normal assemblies, from the filesystem or any stream, as collectible assemblies.

``` csharp
public abstract class AssemblyLoadContext
{
    // ...
    protected AssemblyLoadContext(bool isCollectible) { }
    // ...
}
```

Collectible assemblies loaded by `AssemblyLoadContext` would have the same [lifetime and limitations as those generated by `System.Reflection.Emit`](https://msdn.microsoft.com/en-us/library/vstudio/dd554932%28v=vs.100%29.aspx), except the lifetime extends to all assemblies loaded by the `AssemblyLoadContext`. This means the `AssemblyLoadContext` will not unload until there are no references to any of the assemblies it loaded.

I am working on the implementation for this in CoreCLR: https://github.com/dotnet/coreclr/pull/1684

**Comment by nguerrera** [comment] 2015-10-12 17:55
cc @gkhanna79 @jkotas

**Comment by nguerrera** [comment] 2015-10-12 17:57
I am fine with the proposed API change. If the implementation PR is approved, we can update the contract in corefx to match.

**Comment by mellinoe** [comment] 2015-10-12 18:37
A minor nit since this is a protected constructor, but I think our guidelines say something like "prefer a single flag parameter over multiple booleans". Would it make sense in this case to provide something like AssemblyLoadContextOptions? It would probably make the most sense if we expected there to be more combinable options in the future, but I think our guidelines suggest that it should always be used regardless.

**Comment by mellinoe** [comment] 2016-08-22 03:46
@gkhanna79 Is anything like this supported right now? I'm working on a project in which I'd really like to have something like this available. Do we have any support for unloading/reloading assemblies right now? This is for hot-swapping code and/or a plugin system which can be reloaded.

**Comment by gkhanna79** [comment] 2016-08-22 15:43
@mellinoe No, we do not have any notion of collectible assemblies. This is a pretty non-trivial amount of feature work, in addition to simply exposing an API off the contract, to ensure it works correctly. This is something we will look into future but not necessarily targeted in the short/medium term.

**Comment by jcansdale** [comment] 2016-08-22 17:47
If the main thing someone wanted to do was reload assemblies and they didn't mind bleeding a bit of memory, would creating a new `AssemblyLoadContext` and using `LoadFromStream(Stream assembly)` be a reasonable option?

**Comment by gkhanna79** [comment] 2016-08-22 17:55
> would creating a new AssemblyLoadContext and using LoadFromStream(Stream assembly) be a reasonable option

Yes, it would work.

**Comment by jcansdale** [comment] 2016-08-22 18:03
I guess this trick would be creating an `AssemblyLoadContext` that uses `LoadFromStream` and understands `.deps.json` files.

**Comment by gkhanna79** [comment] 2016-08-22 18:05
Can you elaborate on your scenario? ALC deals with Assemblies; deps.json is an appmodel (and not ALC) artifact.

**Comment by jcansdale** [comment] 2016-08-22 18:48
Say I wanted to load a .NET Core application into an already loaded .NET Core process. Wouldn't the loader need to understand the `.deps.json` file of the target application? The scenario would be for testing without the expense of spinning up a new process.

**Comment by gkhanna79** [comment] 2016-08-22 20:15
If you know the assembly to be loaded and invoked, is there any reason why Reflection cannot be used? Or, is your goal to invoke XUnit test from within your app (in which, any reason why XUnit cannot be loaded to invoke your test)?

**Comment by AlexGhiondea** [comment] 2016-11-21 18:34
It sounds like collectible assemblies are not something we can easily support and there is a workaround (that does leak some memory) for re-loading assemblies from disk.

@gkhanna79 are there plans to support collectible assemblies in the long run?

**Comment by gkhanna79** [comment] 2016-11-21 19:16
Yes, we will be in future. @rahku will be looking into it.

**Comment by karelz** [comment] 2017-03-04 00:11
Looks like dupe of #14724

**Closed by karelz** 2017-03-04 00:11 UTC
Labels: api-needs-work, area-System.Runtime
