### ISSUE TITLE
EventLog is not supported in .Net Core? When is it going to be avaiable next?

### ISSUE THREAD

**Issue by vksohpaul** [dotnet/corefx#25440] opened 2017-11-22 17:23 UTC
I have trying hard to see if EventLog works in .Net Core but it doesn't.  Is it going to be also shipped with dot net core version 2.1 ?

**Comment by danmosemsft** [comment] 2017-11-22 20:00
@vksohpaul it is available in 2.0 but you have to install the compatibility pack
https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/
Note this pack is marked preview on Nuget. We don't have a date for marking it stable (ie whether it will be when we ship 2.1, or earlier)

**Comment by karelz** [comment] 2017-11-27 16:44
Closing as duplicate of #6913

**Closed by karelz** 2017-11-27 16:44 UTC
