### ISSUE TITLE
DbCommand boolean property SupportsNamedParameters

### ISSUE THREAD

**Issue by rgarrison12345** [dotnet/corefx#41863] opened 2019-10-17 00:52 UTC
I think it would be great if the DbCommand object in System.Data.Common had a read only boolean property that indicates whether or not the ADO.Net provider implementation that inherits from that object supports named parameters.  Or in some cases some providers support both like Oracle/Postgres.  In the case of Postgres named parameters were not always possible so the inheriting provider could based on the server version property of the DbConnection object know if named parameters are supported.

There are several ORM frameworks out there that build out SQL by taking in a class object as a generic parameter.  Using the public properties as columns and associated values.  Using this property a correctly parameterized SQL statement could be generated based on whether or not the ADO.NET implementer supports named or positional parameters.

Looking in Oracle.Managed.Client.OracleCommand, that object has a property that is a boolean flag that specifies the binding method in the parameters collection

https://docs.oracle.com/cd/B19306_01/win.102/b14307/OracleCommandClass.htm#i997666

**Comment by roji** [comment] 2019-10-17 17:40
See #27075 for a discussion on this.

Some points:

* Simply knowing that a DbCommand supports named parameters is insufficient, since it doesn't tell the consumer *how* to generate a placeholder (e.g. which prefix, etc.). This is why #27075 is about providing a more complete placeholder generation mechanism, rather than just a flag.
* ADO.NET providers already expose some information via [the DataSourceInformation schema collection](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/common-schema-collections), specifically the ParameterMarkerFormat value. By inspecting that, consumers can more or less determine how to generate placeholders (but the mechanism isn't perfect).
* See https://github.com/dotnet/corefx/issues/27075#issuecomment-463200860 for why named vs. positional is insufficient (there's `@p`, `$1` and `?` which are three different cases).
* Your example with OracleCommand is a (rare) example of a provider which supports *both* binding methods (named and positional). It is not read-only.
* Assuming you're using Npgsql with PostgreSQL, only named parameter are supported, although PostgreSQL itself does natively support only positional parameters (with Npgsql doing the placeholder rewriting). https://github.com/npgsql/npgsql/issues/1042 is about a mode where that won't be necessary anymore, and users will be able to specify positional $1, $2 directly in the CommandText. However, that would probably be a connection mode, rather than something specified on a command-by-command basis like in the Oracle case.

Could you please tell us more about what you're doing and why you think you need this property?

**Comment by roji** [comment] 2019-10-24 09:53
I'll go ahead and close this for now as a duplicate of #27075, but please feel free to provide more details either on that issue or here (if you feel like there's value in a separate issue).

**Closed by roji** 2019-10-24 09:53 UTC
Labels: area-System.Data
