### ISSUE TITLE
EmailAddressAttribute.IsValid Method (Object) cannot validate hyphen at the beginning of domain name

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#27346] opened 2018-02-22 00:40 UTC
_From @ahmetbombaci-united on February 21, 2018 22:25_

Domain names cannot start with hyphen (ref: https://tools.ietf.org/html/rfc952)

However; IsValid method does not respect to this rule

Test case:

var checkMail = new System.ComponentModel.DataAnnotations.EmailAddressAttribute().IsValid("ahmet.bombaci@yahoo.-united.COM"); 

_Copied from original issue: aspnet/Home#2893_

**Comment by Eilon** [comment] 2018-02-22 00:41
Tagging @divega / @ajcvickers / @lajones - DataAnnotations issue

**Comment by divega** [comment] 2018-02-22 07:46
@Eilon it seems this is by design and another duplicate of https://github.com/dotnet/corefx/issues/17873. Do you agree?

**Comment by ahmetbombaci-united** [comment] 2018-02-22 16:13
@divega it looks similar to #17873 but in this case I am not quite sure if this really complicates the regex.

Is there any chance for me to see the implementation?

**Comment by Eilon** [comment] 2018-02-22 17:24
@divega I think it's the same fundamental issue, though not the exact same issue. I do think that the current behavior is fine - it just checks if there's an `@` somewhere in the text. We figured that having a 1,000-character long regex is useless because that isn't the point of the attribute.

@ahmetbombaci-united you can see the implementation here: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs#L31-L46

I'm in favor of closing this as by design. If someone wants a more strict validator, it's easy to use the existing RegEx validator with your own 1,000-character long regex.

**Comment by ahmetbombaci-united** [comment] 2018-02-22 18:48
Thank you for the explanation. I got the point. We can close the issue

**Comment by divega** [comment] 2018-02-23 01:07
Thanks @ahmetbombaci-united and @Eilon. Closing.

**Closed by divega** 2018-02-23 01:07 UTC
Labels: area-System.ComponentModel.DataAnnotations
