### ISSUE TITLE
Support controlling the order of properties for JSON Serialization / Deserialization

### ISSUE THREAD

**Issue by Praveen-Rai** [dotnet/corefx#38669] opened 2019-06-19 06:48 UTC
An attribute similar to [JsonPropertyAttribute](https://www.newtonsoft.com/json/help/html/JsonPropertyOrder.htm) in JSON.Net or [DataMemberAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datamemberattribute?view=netframework-4.8) in System.Runtime.Serialization.

**Comment by ahsonkhan** [comment] 2019-06-20 05:22
This is an interesting feature request which we will consider for the future.

@steveharter, is it feasible for us to extend our existing attribute to enable this scenario in the future? We should make sure our current design allows for it.

**Comment by layomia** [comment] 2019-12-21 08:44
Closing as duplicate of https://github.com/dotnet/runtime/issues/1085.

**Closed by layomia** 2019-12-21 08:44 UTC
Labels: area-System.Text.Json, enhancement
