### ISSUE TITLE
System.Text.Json Deserialization - ISet<> cannot be used within a object

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#40097] opened 2019-08-07 14:24 UTC
Use .NET Core 3.0 preview 7:
```csharp
using System.Collections.Generic;
using System.Text.Json;

namespace ISetTest
{
    class Test
    {
        public string A { get; set; } = "123";
        public ISet<string> B { get; set; } = new HashSet<string>{ "test" };
    }
    class Program
    {
        static void Main(string[] args)
        {
            var x = new Test();
            var json = JsonSerializer.Serialize(x);
            var result = JsonSerializer.Deserialize<Test>(json);
            return;
        }
    }
}
```

Got exception:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.Generic.IList`1[System.String]'.
   at System.Text.Json.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)     
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)   
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)        
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

However this is ok:
```csharp
using System.Collections.Generic;
using System.Text.Json;

namespace ISetTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = new HashSet<string>{ "test" };
            var json = JsonSerializer.Serialize(x);
            var result = JsonSerializer.Deserialize<ISet<string>>(json);
            return;
        }
    }
}
```

**Comment by steveharter** [comment] 2019-08-07 17:08
I was not able to reproduce with the latest code in master - the `B` property contains a `HastSet<string>` with the single "test" value.

@layomia can you find the duplicate (?) issue for PR for this? Thanks

**Comment by layomia** [comment] 2019-08-07 17:58
This was fixed in https://github.com/dotnet/corefx/pull/38319 and will be in preview 8. You can try it now in the [daily build](https://github.com/dotnet/corefx/pull/38319). Please feel free to reopen if you still have issues with this.

**Closed by layomia** 2019-08-07 17:58 UTC
Labels: area-System.Text.Json
