### ISSUE TITLE
Possibility of hang in ReaderWriterLockSlim in case of ThreadAbortExceptions

### ISSUE THREAD

**Issue by erik-kallen** [dotnet/corefx#12646] opened 2016-10-14 12:14 UTC
I just finished investigating an issue that I am pretty sure boils down to ReaderWriterLockSlim not being resistant to ThreadAbortExceptions.

If an asynchronous exception (eg. a ThreadAbortException) is thrown eg. on https://github.com/dotnet/corefx/blob/master/src/System.Threading/src/System/Threading/ReaderWriterLockSlim.cs#L300, the ExitMyLock() method will never be called and the next attempt to spin for the ```_myLock``` field (eg. if trying to exit the lock as part of a finally clause, or the next attempt to acquire the lock) will hang indefinitely.

Perhaps it could also be meaningful to store the managed thread id instead of just 1 in the ```_myLock``` field while the lock is being held because it would have made this issue much easier to find.

**Comment by stephentoub** [comment] 2016-10-14 12:21
Thanks for the issue @erik-kallen.

> I just finished investigating an issue that I am pretty sure boils down to ReaderWriterLockSlim not being resistant to ThreadAbortExceptions.

Are you using the .NET Framework (aka "desktop") or .NET Core?  This repo contains the code for the latter, but thread aborts are not exposed/available in .NET Core.

**Comment by erik-kallen** [comment] 2016-10-14 12:24
I am using .net framework.

I did not know that .net Core does not have ThreadAbortExceptions, you learn something new every day, in that case I gues it is not an issue with Core but I would appreciate if you could forward the issue to the team that handles .net framework.

**Comment by erik-kallen** [comment] 2016-10-14 12:29
@stephentoub I am using .net framework.

I did not know that .net Core does not have ThreadAbortExceptions, you learn something new every day, in that case I gues it is not an issue with Core but I would appreciate if you could forward the issue to the team that handles .net framework.

**Comment by stephentoub** [comment] 2016-10-14 13:16
cc: @kouvel

**Comment by karelz** [comment] 2016-10-14 18:48
Closing as it does not affect .NET Core.
Reporting bugs for Desktop .NET Framework can be done via Microsoft Support or Microsoft Connect. However, be warned that the bar for .NET Framework bugs is pretty high - the bug would have to have significant impact on non-trivial number of customers without easy workaround to get a chance to be fixed (it's a policy to mitigate risk of introducing new unintended regressions).

**Closed by karelz** 2016-10-14 18:48 UTC
Labels: area-System.Threading
