### ISSUE TITLE
SignatureDecoder does not support ELEMENT_TYPE_INTERNAL (0x21)

### ISSUE THREAD

**Issue by nitroxis** [dotnet/corefx#30823] opened 2018-07-03 23:03 UTC
The System.Reflection.Metadata.Ecma335.SignatureDecoder structure currently throws an exception when it encounters ELEMENT_TYPE_INTERNAL in a signature. It seems to be mostly used with DynamicMethods and the like and probably is not included in the official specs, but (optional, e.g. via a flag) support for this would be nice to have.

The C++ sigparser in the CLR implements it: https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/utilcode/sigparser.cpp#L105

It would make sense to have the SignatureDecoder support things the runtime outputs so one can parse signatures created by the runtime (e.g. the local variable signature of a DynamicMethod), which currently is not possible, at least with this library.

**Comment by tmat** [comment] 2019-02-18 04:26
There are many cases of invalid metadata (invalid according to the ECMA spec) that the CLR runtime metadata reader is able to read. In general, System.Reflection.Metadata is strict about following the specification. There are some exceptions, mostly in cases where the specification is contradicting itself or too vague, or if there is a important scenario that needs to be supported in practice.
 
What is the scenario for reading CLR dynamic method signatures using System.Reflection.Metadata APIs?

**Comment by tmat** [comment] 2019-02-18 04:28
Removing "bug" label. The current behavior is by design as the source of truth for SRM is not the CLR metadata reader but the ECMA specification.

**Comment by tmat** [comment] 2019-02-18 04:40
> `ELEMENT_TYPE_INTERNAL` 0x21 Implemented within the CLI 

The ECMA spec mentions the value but doesn't specify meaning or whether the code is followed by any other bytes, so that's not at all useful.

Another question that we need to ask is how stable is the meaning of this element type? Does the CLR guarantee that it's not gonna be changed in the next version. I don't think that's the case. Unless such a guarantee is given, System.Reflection.Metadata APIs can't support this as they are independent of the CLR version.

**Comment by jkotas** [comment] 2019-02-18 04:46
> it's not gonna be changed in the next version?

In fact, the encoding of `ELEMENT_TYPE_INTERNAL` did change at least once in the history of .NET Framework.

**Comment by tmat** [comment] 2019-02-18 05:11
@jkotas Thanks for info. Closing as "by design".

**Closed by tmat** 2019-02-18 05:11 UTC
Labels: area-System.Reflection.Metadata, needs more info
