### ISSUE TITLE
Web Calls failing with error - An error occurred while sending the request.  System.Net.Http.CurlException: Failure when receiving data from the peer at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)

### ISSUE THREAD

**Issue by arpit-nagar** [dotnet/corefx#27970] opened 2018-03-12 17:09 UTC
Getting failures when making web call-
```
System.Net.WebException: An error occurred while sending the request. Failure when receiving data from the peer ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at Company.Platform.Common.WebRequestConnector.<GetHttpResponseAsync>d__5.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/submodule/productsCommon/platform-common/Company.Platform.Common/WebCaller/WebRequestConnector.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Platform.Common.WebRequestConnector.<SendAsync>d__4.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/submodule/productsCommon/platform-common/Company.Platform.Common/WebCaller/WebRequestConnector.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Platform.Common.HttpConnectorFilter.<ApplyAsync>d__2.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/submodule/productsCommon/platform-common/Company.Platform.Common/WebCaller/Internal/HttpConnectorFilter.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Platform.Common.HttpFilter.<ApplyAsync>d__2.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/submodule/productsCommon/platform-common/Company.Platform.Common/WebCaller/Internal/HttpFilter.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Connector.products.subsystem.Common.WebCaller.ResponseDataExtractorHttpFilter`2.<ApplyAsync>d__2.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/Company.Connector.products.subsystem/Common/WebCaller/ResponseDataExtractorHttpFilter.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Platform.Common.HttpFilter.<ApplyAsync>d__2.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/submodule/productsCommon/platform-common/Company.Platform.Common/WebCaller/Internal/HttpFilter.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Company.Connector.products.subsystem.Common.WebCaller.LoggingHttpFilter.<ApplyAsync>d__4.MoveNext() in /var/lib/jenkins/workspace/mycompany-product-connector-subsystem/code/subsystem/Company.Connector.products.subsystem/Common/WebCaller/LoggingHttpFilter.cs:line 39
```
We are using following code -

```csharp
public class WebRequestConnector : IHttpConnector
{
	private readonly IMemoryStreamPool _memoryStreamPool;
	private static byte[] EmptyPayload = new byte[0];

	public WebRequestConnector(IMemoryStreamPool memoryStreamPool = null)
	{
		_memoryStreamPool = memoryStreamPool ?? HttpSettings.Default.MemoryPool;
	}

	private HttpWebRequest CreateBasicWebRequest(HttpRequest request)
	{
		var webRequest = WebRequest.Create(request.Uri) as HttpWebRequest;
		if (webRequest == null)
			return null;

		webRequest.Headers = new WebHeaderCollection();
		webRequest.Method = request.Method;
		webRequest.ContentType = request.ContentType;
		// webRequest.ProtocolVersion = new Version(request.ProtocolVersion);
		// webRequest.ServicePoint.Expect100Continue = false;
		// webRequest.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
		// webRequest.Timeout = (int)request?.TimeOut.Value.TotalMilliseconds;
		foreach (var header in request.Headers)
			webRequest.Headers[header.Key] = header.Value;
		return webRequest;
	}

	public async Task<HttpResponse> SendAsync(HttpRequest request, CancellationToken cancellationToken = default(CancellationToken))
	{
		var webRequest = CreateBasicWebRequest(request);

		if (request.SendRequestBody == true)
		{
			Stream compressionStream = null;
			request.Payload = request.Payload ?? EmptyPayload;
			using (var requestStream = await webRequest.GetRequestStreamAsync())
			{
				if (request.IsCompressionEnabled == false)
					await requestStream.WriteAsync(request.Payload, 0, request.Payload.Length, cancellationToken);
				else
				{
					webRequest.Headers[HeaderNames.ContentEncoding] = request.CompressionType.ToString().ToLower();
					if (request.CompressionType == CompressionType.Gzip)
						compressionStream = new GZipStream(requestStream, CompressionMode.Compress, false);
					else
						compressionStream = new DeflateStream(requestStream, CompressionMode.Compress, false);
					using (compressionStream)
					{
						await compressionStream.WriteAsync(request.Payload, 0, request.Payload.Length, cancellationToken);
					}
				}
			}
		}

		var timeOut = request.TimeOut.Value;
		var cts = new CancellationTokenSource(timeOut);
		var token = cts.Token;
		var responseTask = GetHttpResponseAsync(request, webRequest, token);
		await Task.WhenAny(responseTask, Task.Delay(timeOut, token));

		if (!responseTask.IsCompleted)
			throw new CommunicationException("32", "A timeout exception occured", HttpStatusCode.GatewayTimeout);

		return await responseTask;
	}

	private async Task<HttpResponse> GetHttpResponseAsync(HttpRequest request, HttpWebRequest webRequest, CancellationToken cancellationToken = default(CancellationToken))
	{
		HttpWebResponse webResponse;
		try
		{

			webResponse = await webRequest.GetResponseAsync() as HttpWebResponse;
		}
		catch (WebException webException)
		{
			webResponse = webException.Response as HttpWebResponse;
			if (webResponse == null)
			{
				throw webException;
			}
		}

		using (var responseStream = webResponse.GetResponseStream())
		{
			Stream streamToCopy = responseStream;
			using (var memoryStream = await CreateStreamAsync())
			{
				var contentEncodingKey = webResponse.Headers.AllKeys.ToList().FirstOrDefault(h => h.ToLower().Equals("content-encoding"));
				if (!string.IsNullOrEmpty(contentEncodingKey))
				{
					Stream decompressStream = null;
					if (webResponse.Headers[contentEncodingKey].Contains("gzip"))
						decompressStream = new GZipStream(responseStream, CompressionMode.Decompress, false);
					else if (webResponse.Headers[contentEncodingKey].Contains("deflate"))
						decompressStream = new DeflateStream(responseStream, CompressionMode.Decompress, false);
					using (decompressStream)
					{
						if (decompressStream != null)
							await decompressStream.CopyToAsync(memoryStream);
						else
							await responseStream.CopyToAsync(memoryStream);
					}
				}
				else
					await responseStream.CopyToAsync(memoryStream);
				var payload = memoryStream.ToArray();
				var response = new HttpResponse(webResponse.StatusCode, payload, request.Settings);
				WriteHeaders(webResponse?.Headers, response);
				return response;
			}
		}
	}

	private void SetTimeOut(CancellationTokenSource cancellationTokenSource, TimeSpan? timeOut)
	{
		if (timeOut != null)
		{
			cancellationTokenSource.CancelAfter(timeOut.Value);
		}
	}

	private async Task<MemoryStream> CreateStreamAsync()
	{
		if (_memoryStreamPool == null)
			return new MemoryStream();
		else return await _memoryStreamPool.GetMemoryStream();
	}

	private void WriteHeaders(WebHeaderCollection headers, HttpResponse response)
	{
		if (headers != null)
		{
			foreach (var header in headers.AllKeys)
				response.Headers[header] = headers[header];
		}
	}
}
```

Following are the server configuration -

OS - Linux 14.02
Framework - dotnet 2.0

Can someone please help me to fix this issue.

**Comment by rmkerr** [comment] 2018-03-12 18:18
Hey @arpit-nagar, thanks for reporting this. Is it possible to get a full repro that we can run? Network traces would be useful too. Also, approximately how long does it take from sending the request to getting that failure? This reminds me of some unusual behavior with `Content-Length` in Curl, where sending less data than Curl expects causes a hang and eventually throws the exception you're seeing.

**Comment by arpit-nagar** [comment] 2018-03-12 18:52
Thanks, @rmkerr for looking into this.
Sorry, I can't share repro as well as working trace. Although I can share a sample non-working trace with you on your personal Id. 
This is a random behavior around 5% to 10% calls were failing with this error and I have following observations on this.
- Calls generally took < 10ms. In a normal scenario, it varies from 200ms to 5000ms
- It happens on load around 5rps
- In all calls `Content-Length` : 1200+

**Comment by arpit-nagar** [comment] 2018-03-13 06:02
@rmkerr @karelz Please let us know if you need more details.

**Comment by karelz** [comment] 2018-03-13 16:08
@arpit-nagar we need a repro - can you try to isolate it from your application? Create something similar to your workload that you can share publicly?

**Comment by karelz** [comment] 2018-05-06 18:57
It is not actionable without repro. Closing. Feel free to reopen if there is repro, or deeper analysis pointing to a specific problem.

**Closed by karelz** 2018-05-06 18:57 UTC
Labels: area-System.Net.Http, bug, needs more info, os-linux

**Comment by smudge202** [comment] 2018-05-18 09:45
I appreciate this issue has been closed but we're experiencing what I believe to be the exact same behaviour. Would you prefer another issue be opened?

We have a public endpoint that I can provide an repro for, though as @arpit-nagar mentioned, it is intermittent (14/46 requests fail looking at our recent logs).

Is a simple snippet of `HttpClient` code calling a specific endpoint sufficient or do you need something else?

**Comment by karelz** [comment] 2018-05-18 17:53
Please open new issue - there is no value to continue on this one as it might or might not be the same problem.
We will need isolated minimal repro.
It is ok if it runs a loop and it takes a while to hit the failure, or if it needs to be executed multiple times to hit the problem - just make sure you can reproduce it on more than 1 machine yourself.

**Comment by Ramnath24** [comment] 2018-06-08 07:06
I'm Getting same issue. Does anyone have solution 

p0071983@D-113109264:~$ dotnet run --project /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.Api
Using launch settings from /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.Api/Properties/launchSettings.json...
	[INFO]Running interactively, press enter to stop.
	[INFO]Initializing the application
	[INFO]Polling started on the cobas e-library interface with RCL
	[ERROR]An error occurred while sending the request.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roche.cobaselibrary.RclConnector.RclInterfaceConnector.<GetResourcesAsync>d__34.MoveNext() in /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.RCLConnector/RclInterfaceConnector.cs:line 537
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roche.cobaselibrary.RclConnector.RclInterfaceConnector.<GetAndExecuteResources>d__24.MoveNext() in /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.RCLConnector/RclInterfaceConnector.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roche.cobaselibrary.Logger.LoggerWrapper.AppLogger.<LogProcessTime0Params>d__25.MoveNext() in /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.Logger/LoggerWrapper/AppLogger.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roche.cobaselibrary.Logger.LoggerWrapper.AppLogger.<LogDebugAsync>d__5.MoveNext() in /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.Logger/LoggerWrapper/AppLogger.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roche.cobaselibrary.RclConnector.RclInterfaceConnector.<PollingLoopAsync>d__23.MoveNext() in /home/p0071983/Documents/HRD_RAMNATh/cobas-e-library-backend/Roche.cobaselibrary.RCLConnector/RclInterfaceConnector.cs:line 258
Running interactively, press enter to stop.

**Comment by karelz** [comment] 2018-06-08 17:45
@Ramnath24 can you try .NET Core 2.1 - it does not use curl anymore.
If you can still repro on 2.1, please check network traces (Fiddler/Wireshark) and if it looks like .NET Core problem, please try to isolate the problem into a repro we can look at. File a new issue in such case - see https://github.com/dotnet/corefx/issues/27970#issuecomment-390283753

**Comment by AbhiAgarwal192** [comment] 2019-03-19 06:17
even .net core 2.1 has the same issue.

**Comment by karelz** [comment] 2019-03-19 14:37
@AbhiAgarwal192 did you get chance to collect network traces and see if it is problem in .NET Core?
