### ISSUE TITLE
[System.Text.Json]: Recursive property in collection type results in stackoverflow

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37313] opened 2019-04-30 22:14 UTC
```C#
static void Main(string[] args)
{
    var node = new Node();
    Console.WriteLine(JsonSerializer.ToString(node));
}

class Node
{
    public List<Node> Children { get; set; }
}
```

Environment: Microsoft.NETCore.App 3.0.0-preview6-27629-07

**Comment by pranavkm** [comment] 2019-04-30 22:15
cc @steveharter \ @ahsonkhan

**Comment by steveharter** [comment] 2019-05-01 14:58
Duplicate of https://github.com/dotnet/corefx/issues/36510

**Comment by pranavkm** [comment] 2019-05-01 16:12
@steveharter the other issue is for a cycle in the serialization graph. However, in this case, there isn't an actual cyle in fact, Children` node is entirely empty and has no back reference to the parent. I would expect this to serialize just normally.

**Comment by pranavkm** [comment] 2019-05-10 17:34
Can we prioritize fixing this issue? There is really no good way to workaround this and it's a fairly recurring theme in our tests.

**Comment by rynowak** [comment] 2019-05-12 00:09
To put some emphasis on this - this is blocking us using S.T.J for Blazor. https://github.com/aspnet/AspNetCore/pull/10171/files#diff-5fd50c61f956f92c8ba798028bb6cce7R41

**Comment by rynowak** [comment] 2019-05-12 00:21
I'm guessing that the call stack for this is something like:

```txt
JsonSerializerOptions.GetOrAddClass()
JsonPropertyInfo.ctor()
..Activator..
JsonClassInfo.CreateProperty()
JsonClassInfo.AddProperty()
JsonClassInfo.ctor()
```
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfo.cs#L66

It looks like the case of "`T` has a property of type `IEnumerable<T>`" will recursively try to construct the class info for itself. The infinite recursion could be broken by make this lazy or keeping track of the work "on the stack" using a local `HashSet<>` in `GetOrAddClass()`.

**Comment by ahsonkhan** [comment] 2019-05-14 04:03
From @oskardudycz in https://github.com/dotnet/corefx/issues/37610
> As in title: Serializing class that has array of children of the same class throws StackOverflowException.

> Simplest repro steps:

```
public class TestClass
{
    public TestClass[] Children { get; set; }
}

var document = new TestClass();
var str = JsonSerializer.ToString(document);
```
> I create repository that reproduces this issue: https://github.com/oskardudycz/System.Text.Json.Fail

**Closed** 2019-05-21 18:50 UTC
Labels: area-System.Text.Json, blocking-partner, bug
