### ISSUE TITLE
how can i use DESCryptoServiceProvider in dotnet core?

### ISSUE THREAD

**Issue by vincentshow** [dotnet/corefx#12477] opened 2016-10-08 12:54 UTC
I'm migrating a old library to dotnet core. There is a decrypt_encrypt helper class that using DESCryptoServiceProvider of .net framework4.0 as its algorithm. But I cannot find this class in dotnet core. Does anyone know how to find it? Thanks

**Comment by svick** [comment] 2016-10-08 13:32
`DESCryptoServiceProvider` is not currently part of .Net Core. See https://github.com/dotnet/corefx/issues/11116 for an issue about adding it.

**Comment by Petermarcu** [comment] 2016-10-08 22:03
Going to close this one as a duplicate of #11116 where we're tracking the work to add it.

**Closed by Petermarcu** 2016-10-08 22:03 UTC
