### ISSUE TITLE
Marshal.QueryInterface for IDispatch for int/string etc. returns error not success

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#31079] opened 2018-07-14 21:34 UTC
No errors with netfx

```
  ===========================================================================================================
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Runtime.InteropServices.Tests
  Discovered:  System.Runtime.InteropServices.Tests
  Starting:    System.Runtime.InteropServices.Tests
     System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_ValidInterface_Success(o: 10, guid: \"0002
  0400-0000-0000-C000-000000000046\") [FAIL]
  Finished:    System.Runtime.InteropServices.Tests

  === TEST EXECUTION SUMMARY ===
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning :    System.Runtime.InteropServices.Tests  T
otal: 1150, Errors: 0, Failed: 4, Skipped: 0, Time: 4.227s [C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.I
nteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  ----- end 22:33:31.11 ----- exit code 1 ----------------------------------------------------------
        Assert.Equal() Failure
        Expected: 0
        Actual:   -2147467262
        Stack Trace:
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\QueryInterfaceTests.cs(76,0): at System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_V
  alidInterface_Success(Object o, String guid)
     System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_ValidInterface_Success(o: \"string\", guid
  : \"00020400-0000-0000-C000-000000000046\") [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   -2147467262
        Stack Trace:
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\QueryInterfaceTests.cs(76,0): at System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_V
  alidInterface_Success(Object o, String guid)
     System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_ValidInterface_Success(o: System.Runtime.I
  nteropServices.Tests.Common.NonGenericStruct, guid: \"00020400-0000-0000-C000-000000000046\") [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   -2146233079
        Stack Trace:
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\QueryInterfaceTests.cs(76,0): at System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_V
  alidInterface_Success(Object o, String guid)
     System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_ValidInterface_Success(o: Value1, guid: \"
  00020400-0000-0000-C000-000000000046\") [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   -2146233079
        Stack Trace:
           C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServic
  es\Marshal\QueryInterfaceTests.cs(76,0): at System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_V
  alidInterface_Success(Object o, String guid)
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(514,5): warning MSB3073: The command "C:\Users\hughb\Documen
ts\GitHub\corefx\bin/tests/System.Runtime.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64//RunTests.cmd C:\Users\
hughb\Documents\GitHub\corefx\bin/testhost/netcoreapp-Windows_NT-Debug-x64/" exited with code 1. [C:\Users\hughb\Docume
nts\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
C:\Users\hughb\Documents\GitHub\corefx\Tools\tests.targets(522,5): error : One or more tests failed while running tests
 from 'System.Runtime.InteropServices.Tests' please check C:\Users\hughb\Documents\GitHub\corefx\bin/tests/System.Runti
me.InteropServices.Tests/netcoreapp-Windows_NT-Debug-x64/testResults.xml for details! [C:\Users\hughb\Documents\GitHub\
corefx\src\System.Runtime.InteropServices\tests\System.Runtime.InteropServices.Tests.csproj]
Done Building Project "C:\Users\hughb\Documents\GitHub\corefx\src\System.Runtime.InteropServices\tests\System.Runtime.I
nteropServices.Tests.csproj" (BuildAndTest target(s)) -- FAILED.


Build FAILED.
```

**Comment by danmosemsft** [comment] 2018-07-15 18:46
0x80131509 | -2146233079 | COR_E_INVALIDOPERATION | "An   operation is not legal in the current state."
-- | -- | -- | --

**Comment by jkotas** [comment] 2018-07-16 11:39
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment] 2019-10-23 22:02
Closing as duplicate of https://github.com/dotnet/corefx/issues/31077

**Closed by AaronRobinsonMSFT** 2019-10-23 22:02 UTC
Labels: area-System.Runtime.InteropServices
