### ISSUE TITLE
Installing build tools is quite slow

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#30435] opened 2018-06-15 20:54 UTC
Given these output:

```sh
>>> Installing dotnet cli...
>>> Restoring BuildTools version 2.2.0-preview1-02912-01...
Using RID linux-x64 for BuildTools native tools
>>> Initializing BuildTools...
Making all .sh files executable under Tools.
>>>  Restoring packages for /corefx/Tools/crossgen/crossgen.csproj...
>>>  Installing Microsoft.NETCore.App 2.1.0-rc1.
>>>  Installing runtime.linux-x64.Microsoft.NETCore.App 2.1.0-rc1.
  Generating MSBuild file /corefx/Tools/crossgen/obj/crossgen.csproj.nuget.g.props.
  Generating MSBuild file /corefx/Tools/crossgen/obj/crossgen.csproj.nuget.g.targets.
  Restore completed in 6.06 min for /corefx/Tools/crossgen/crossgen.csproj.
>>> Running crossgen on all assemblies in /corefx/Tools.
```

the highlighted (`>>>`) steps take a lot of time to execute on Unix. Is there anything that can be done to optimize them?

Also, if we only run `./build-native.sh` in a fresh clone, why does it install the full build-tools?

**Comment by karelz** [comment] 2018-06-15 21:19
What's a lot of time? Did you try Windows on the same network / same machine settings?
Were you able to identify the bottleneck? (network / something else)

**Comment by kasper3** [comment] 2018-06-15 21:27
@karelz, i am in process of converting PAL C++ code to C, for which i needed to switch lots of operating systems. I have noticed that some of these steps are taking order of minutes. The downloading of initial zip doesn't take more than few seconds, the rest of unzipping stuff and crossgen'ing takes most of the time. However, subsequent builds are faster because if we don't clean the repo directory, subsequent builds reuse the Tools.

**Comment by kasper3** [comment] 2018-06-15 21:28
At least for `build-native` case, perhaps it is possible to exempt some of these steps.

**Comment by danmosemsft** [comment] 2018-06-16 14:20
You are sharing the same repo between Unix and windows? I find that too painful for this reason, tools must switch. Have you considered two clones, that pull from each other? They can do that directly or via github if http is easier.

**Comment by kasper3** [comment] 2018-06-16 14:27
Nope, i have different clones. They are different VMs. I think there are some low hanging fruits:

* use CDN URLs (as dotnet/cli is using in dotnet-install script etc.)
* if applicable, DRY the subcomponents that get downloaded twice and extracted twice (one from dotnet-cli one from buildtools)
* when user only invokes ./build-native, do not run all the steps: `{download,restore,initialize} buildtools`, `crossgen assemblies`, `restore packages` etc. I think it kinda goes against the purpose of having `build-native.sh` separate than `build.sh`?

**Comment by karelz** [comment] 2018-06-18 19:59
I wonder if this is dupe of #30479.
sync took hours and didn't finish over the weekend for me. I just tried and it finished in 2:38, which is ok.
Can you please give it another try?

**Comment by wfurt** [comment] 2018-09-20 22:21
You can run build-native.sh from src/Native. That one will not install build-tools

**Closed by wfurt** 2018-09-20 22:21 UTC
Labels: area-Infrastructure, enhancement, tenet-performance
