### ISSUE TITLE
Audit Repos for old zlib / AccessViolationException - Interop.zlib.deflate(Byte* stream, Int32 flush)

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9339] opened 2016-06-11 00:25 UTC
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win7-x86.runtime.native.System.IO.Compression/4.0.1-rc3-24210-00

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. 
at Interop.zlib.deflate(Byte* stream, Int32 flush) 
at Interop.zlib.Deflate(ZStream& stream, FlushCode flush) 
at System.IO.Compression.Deflater.Deflate(FlushCode flushCode) 
at System.IO.Compression.Deflater.ReadDeflateOutput(Byte[] outputBuffer, FlushCode flushCode, Int32& bytesRead) 
at System.IO.Compression.Deflater.GetDeflateOutput(Byte[] outputBuffer) 
at System.IO.Compression.DeflateStream.WriteDeflaterOutput() 
at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count) 
at System.IO.Compression.CheckSumAndSizeWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count) 
at System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(Byte[] buffer, Int32 offset, Int32 count) 
at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)

**Comment by ellismg** [comment] 2016-06-11 01:01
Did we get a dump internally or a scenario we can stress locally?

**Comment by ellismg** [comment] 2016-06-11 04:23
We think this is a dupe of the previously known issue (the zlib was an older version coming from build tools which did not have the rollback to fix the issue we were seeing)

**Comment by joshfree** [comment] 2016-06-11 05:36
It was discovered by the reporter that they were actually running against a much older version of the library than reported.  Updating title; the ask is to audit buildtools and other repos for references to the older zlib with known issues

**Comment by ianhays** [comment] 2016-06-11 15:30
[WCF](https://github.com/dotnet/wcf/blob/release/1.0.0/BuildToolsVersion.txt) and [coreclr](https://github.com/dotnet/coreclr/blob/release/1.0.0/BuildToolsVersion.txt) are using the BuildTools with the broken clrcompression.

**Comment by ianhays** [comment] 2016-06-27 20:03
Looks like we're in the clear. Master on WCF/coreclr are using fine buildtools versions.  No new versioning issues in a while. Closing.

**Closed by ianhays** 2016-06-27 20:03 UTC
Labels: tenet-reliability
