### ISSUE TITLE
[Perf][Windows_NT] Investigate System/Runtime/Serialization/Json/Tests/Performance/DcjsPerformanceTest Improvement/Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by jorive** [dotnet/corefx#27512] opened 2018-02-27 18:22 UTC
There are multiple improvement/regressions across this noisy suite +/-4%.

**Comment by huanwu** [comment] 2018-03-22 17:48
@jorive Could you provide more context/details about this issue

**Comment by danmosemsft** [comment] 2018-03-29 21:08
https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61647,61602,61698]&jobid=94550&

should show this

![image](https://user-images.githubusercontent.com/6385855/38113692-8f589e3e-335a-11e8-8394-4c557bc78c75.png)

Note it is possible to drill in, see code changes occurring at point of regression etc.

cc @mconnew

**Comment by danmosemsft** [comment] 2018-03-29 21:08
Based on the graph it seems Windows matches 2.0 and Linux is improved. If that is not worth understanding further you can close this issue right now.

**Comment by danmosemsft** [comment] 2018-04-18 20:44
Note if you install https://userstyles.org/styles/108591/github-wide you see the graphs more easily.

**Comment by huanwu** [comment] 2018-06-21 18:31
We can consider it as noisy since it is less than 5%.

**Closed by huanwu** 2018-06-21 18:31 UTC
Labels: area-Serialization, tenet-performance-benchmarks
