### ISSUE TITLE
double value in appsettings can't be read

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#19175] opened 2017-05-01 03:06 UTC
@juliengomes commented on [Sun Apr 30 2017](https://github.com/dotnet/core/issues/608)

Not sure where to put this issue so I just put it here.

In my appsetting.json file, I have a double value in dictionnary, something like 
```
{
    "A": {
        "B": {
            "EUR": 0.5,
            "USD": 0.5
        }
   }
}
```

This is the code I have in my Startup.cs file 

```
services.Configure<MyOptions>(options => Configuration.GetSection("A").Bind(options));
```

And this is MyOptions
```
namespace Options
{
    public class MyOptions
    {
        public Dictionary<string,double> B { get; set; }
    }
}
```

When I try to run this, I get the following error
```
Unhandled Exception: System.InvalidOperationException: Failed to convert '0,5' to type 'System.Double'. ---> System.Exception: 0,5 is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary(Object dictionary, Type dictionaryType, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at LOL.Startup.<ConfigureServices>b__5_0(MyOptions options) in /Users/LOL/Startup.cs:line 41
```

This is my dotnet version `1.0.0-preview2-1-003177` and I run it on a french macbook pro. I say french because in french "0,5" is the right string conversion for 0.5, so it might be the cause, but it's still a bug because I need double there, even if I go through casting.

---

@Petermarcu commented on [Sun Apr 30 2017](https://github.com/dotnet/core/issues/608#issuecomment-298240850)

@gkhanna79

**Comment by gkhanna79** [comment] 2017-05-01 03:06
CC @danmosemsft @karelz

**Comment by karelz** [comment] 2017-05-01 04:47
Where does `Microsoft.Extensions.Configuration` live? I don't think in CoreFX ... @JeremyKuhne any idea?

**Comment by danmosemsft** [comment] 2017-05-01 04:48
I believe the relevant line is likely here - although it's inlined. This is owned by asp.net, and they're using invariant culture which won't parse fr-fr number format. 

https://github.com/aspnet/Configuration/blob/e1b7960f22b7c508645fedb8a50f0e873d7407d5/src/Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs#L316

**Comment by danmosemsft** [comment] 2017-05-01 04:50
@haok you made the last change to this file. Is this a bug, and if so should it go to your configuration repo?

**Comment by svick** [comment] 2017-05-01 10:53
I think the issue is that `JsonConfigurationFileParser` incorrectly converts the `double` to `string` using the current culture [here](https://github.com/aspnet/Configuration/blob/9b633a4/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationFileParser.cs#L98), but `ConfigurationBinder` correctly expects invariant culture.

This certainly belongs to aspnet/Configuration.

**Comment by svick** [comment] 2017-05-01 11:14
And I think it's actually a duplicate of https://github.com/aspnet/Configuration/issues/470.

**Comment by stephentoub** [comment] 2017-05-01 11:25
Thanks, @svick.  Closing as dup of aspnet/Configuration#470.

**Closed by stephentoub** 2017-05-01 11:25 UTC
Labels: bug
