### ISSUE TITLE
[arm32/Windows] System.Xml.Xsl.XslCompiledTransformApi.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#34052] opened 2018-12-12 23:05 UTC
Running the arm32 tests on windows for System.Xml.Xsl.XslCompiledTransformApi.Tests produced the following results: passed 1267/1268 tests.

The test that failed was System.Xml.Tests.CTransformRegressionTest.RegressionTest1(xslInputType: URI, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument) with:
```
System.IO.FileNotFoundException : Could not find file 'C:\\Data\\Users\\Administrator\\Documents\\tests\\System.Xml.Xsl.XslCompiledTransformApi.Tests\\netcoreapp-Windows_NT-Release-arm\\TestFiles\\TestData\\XsltApiV2\\Straße.xml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in E:\A\_work\48\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Windows.cs:line 1640
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in E:\A\_work\48\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Win32.cs:line 46
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in E:\A\_work\48\s\src\System.Private.CoreLib\shared\System\IO\FileStream.cs:line 243
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in E:\A\_work\48\s\src\System.Private.CoreLib\shared\System\IO\FileStream.cs:line 171
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share) in F:\git\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 157
   at System.IO.File.Open(String path, FileMode mode) in F:\git\corefx\src\System.IO.FileSystem\src\System\IO\File.cs:line 147
   at System.Xml.Tests.CTransformRegressionTest.RegressionTest1(XslInputType xslInputType, ReaderType readerType, OutputType outputType, NavType navType) in F:\git\corefx\src\System.Private.Xml\tests\Xslt\XslCompiledTransformApi\XslCompiledTransform.cs:line 3379
```
[testResults.zip](https://github.com/dotnet/corefx/files/2673901/testResults.zip)

**Comment by danmosemsft** [comment] 2018-12-12 23:46
This is odd, nothing to do with XSL, it's just writing and reading a file. No idea, but perhaps related to the \u00DF somehow. Need to run code below on the machine and look on the disk.
```
            string testFile = Path.Combine("TestFiles", FilePathUtil.GetTestDataPath(), "XsltApiV2", "Stra\u00DFe.xml");

            // Create the file.
            using (FileStream fs = File.Open(testFile, FileMode.Open))
```

**Comment by joshfree** [comment] 2018-12-12 23:53
@krwq could you take a look at this after your current feature is finished?

**Comment by krwq** [comment] 2019-01-14 22:45
Me and @buyaa-n tried to run the sample @danmosemsft gave on Win IoT Core (Raspberry PI) and we think the problem is with pscp.exe (which AFAIK @joperezr was using when copying the tests over) which replaces the special characters with `�` which causes to file in fact not to exist. Here is the full thing we ran:

```csharp
            Console.WriteLine(Environment.CurrentDirectory);

            foreach (var file in Directory.EnumerateFiles(Environment.CurrentDirectory, "Str*.xml"))
            {
                Console.WriteLine(file);
                using (FileStream fs = File.Open(file, FileMode.Open))
                {
                }
            }

            Console.WriteLine("END OF LIST");

            string testFile = "Stra\u00DFe.xml";
            using (FileStream fs = File.Open(testFile, FileMode.Open))
            {
                using (StreamReader sr = new StreamReader (fs))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
```

and the output was following:

```
C:\Data\Users\administrator\Documents\bin\Debug\netcoreapp3.0\win-arm\publish
C:\Data\Users\administrator\Documents\bin\Debug\netcoreapp3.0\win-arm\publish\Stra�e.xml
END OF LIST

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Data\Users\administrator\Documents\bin\Debug\netcoreapp3.0\win-arm\publish\Straße.xml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at win_iot_core_repro.Program.Main(String[] args) in F:\mess\win-iot-core-repro\Program.cs:line 23
```

@joperezr could you confirm you used pscp.exe? If so I think we can close the issue since it's not related to .NET

**Comment by joperezr** [comment] 2019-01-14 22:53
Yes, I did use pscp.exe. Does that mean that without pscp the test passes? If so, then I'm fine with closing the issue.

**Comment by danmosemsft** [comment] 2019-01-14 23:12
We shoukd fix the problem (at minimum by disabling the test for ARM) so it never fails again for this reason and we don't have to do this analysis again. The goal is that future ARM runs pass100%

**Comment by joperezr** [comment] 2019-01-15 00:17
pscp was only used for the sample run, once we get this in CI files would be distributed by Helix so if this was caused by pscp I don't expect it to repro in CI.

**Comment by danmosemsft** [comment] 2019-06-26 02:54
If pscp was the problem, we can close this.

**Closed by danmosemsft** 2019-06-26 02:54 UTC
Labels: arch-arm32, area-System.Xml, os-windows-iot, test-run-core
