### ISSUE TITLE
Add tests for new String.Join overloads

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#12655] opened 2016-10-14 16:39 UTC
Once dotnet/coreclr/pull/7621 makes its way over to CoreFx, we need to add tests for the new APIs.

**Comment by hughbe** [comment] 2016-10-14 19:54
I'll take this once we update the core CLR dependencies here

**Comment by AlexGhiondea** [comment] 2016-10-14 21:53
@hughbe that is great! I assigned the issue to you!

**Comment by AlexGhiondea** [comment] 2016-11-21 17:57
@hughbe, it looks like @jamesqo has taken over that work and filed https://github.com/dotnet/coreclr/pull/7942 for it.

**Comment by AlexGhiondea** [comment] 2016-11-21 17:59
@jamesqo, @hughbe  let me know if any of you are planning to add tests in CoreFx side for this.

**Comment by hughbe** [comment] 2016-11-21 19:14
Yeah I agreed with James he'd implement and test

**Comment by AlexGhiondea** [comment] 2016-11-21 19:15
@hughbe and @jamesqo  thank you! :)

**Comment by AlexRadch** [comment] 2016-12-20 17:35
I am working on this PR

**Comment by karelz** [comment] 2016-12-21 00:17
@AlexGhiondea isn't it tracking same thing as #5552?

**Comment by AlexRadch** [comment] 2016-12-21 02:24
@karelz Yes. It is the same thing

**Comment by karelz** [comment] 2016-12-21 23:42
Closing as dupe of #5552.

**Closed by karelz** 2016-12-21 23:42 UTC
Labels: area-System.Runtime, test enhancement, up for grabs
