### ISSUE TITLE
TimeZoneInfo Now functionality

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#26400] opened 2018-01-18 00:08 UTC
@TimCurwick commented on [Fri Sep 15 2017](https://github.com/dotnet/coreclr/issues/14019)

TimeZoneInfo objects should have functionality to provide the current time in the time zone defined in the object. This would be similar to the DateTime and DateTimeOffset Now and UTCNow static properties, though of course not static. For consistency, this could be a property named Now.
Something like:
`public readonly DateTime Now {
    get {
        return ConvertTime( DateTime.UtcNow, this);
        }
    }`

**Comment by tarekgh** [comment] 2018-01-18 02:19
@mj1856 already proposed this before and we decided to hold this proposal because we are thinking in doing more TZ work which can include such functionality. 

This is a duplicate of #25089

**Comment by joshfree** [comment] 2018-02-22 19:25
Closing as this is tracked with #25089

**Closed** 2018-02-22 19:25 UTC
Labels: api-suggestion, area-System.Runtime

**Comment by TimCurwick** [comment] 2018-02-22 20:48
So because someone might someday do something else related to this and might do something then, it was decided not to add one line of code that would definitely make an improvement today?

**Comment by tarekgh** [comment] 2018-02-22 21:26
what is the issue if you have the following extension method in your code? 

```C#
        public static DateTime Now(this TimeZoneInfo zone)
        {
            return TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, zone);
        }
```

We are not saying we'll not add this API. what we are saying we need some little more time to figure out the whole story of the time zones plan.

**Comment by TimCurwick** [comment] 2018-02-23 15:51
I'm not a C# developer; I'm a PowerShell consultant and trainer. For me personally, the difference is that if it's in your code, it's not in my code. For the wider PowerShell community, the difference is between using an existing object property, which any Windows admin can do and understand, and modifying object definitions, which puts it beyond the comfort level of most PowerShell scripters. (Here's my article on doing it the hard way - http://www.madwithpowershell.com/2017/09/its-always-5-oclock-somewhere-using-net.html )

It's a little thing, but that's why I'm a little puzzled. Instead of taking the time to put the code in your question asking why I'd like you to add this enhancement now, you could have put the code in the source code, and added this enhancement now.
