### ISSUE TITLE
hi i have some problem about cpu100% in .net core

### ISSUE THREAD

**Issue by pigwing** [dotnet/corefx#31087] opened 2018-07-16 03:05 UTC
in libcoreclr.so some times will let my cpu 100%, in CorUnix::PROCRemoveThread
and check cat /proc/id/status threads count is 32
system is linux arm 32
https://github.com/AirleaderChina/Airleader-Open/blob/master/errorPho1.png
https://github.com/AirleaderChina/Airleader-Open/blob/master/errorPho.png

**Comment by karelz** [comment] 2018-07-16 18:20
@pigwing can you please try to narrow it down to small repro?
Or profile your app to identify the bottleneck.

You can try to use: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md (not sure if it works for arm32 - cc @brianrob @vancem)

**Comment by brianrob** [comment] 2018-07-16 18:39
Yes, this strategy does work on arm32 as long as the distro has perf and LTTng.

**Comment by pigwing** [comment] 2018-07-17 08:51
@karelz OK,i am waiting for the raspberry pi system Raspbian to let the cpu 100% tha i can upload the tracing
today i change the core clr to 2.0,i found that .net core 2.0 small consumption look at two picture
.net core 2.0  this two clr has same code  same os  same  hardware all the same,only use .net core 2.0 or .net core 2.1
https://github.com/AirleaderChina/Airleader-Open/blob/master/core2.0.png
.net core 2.1
https://github.com/AirleaderChina/Airleader-Open/blob/master/core2.1.png

i think tomorrow i can dump the .net core 2.1 clr tracing ,now the cpu is well not use 100%.

**Comment by pigwing** [comment] 2018-07-18 06:04
@karelz the tracing https://github.com/AirleaderChina/Airleader-Open/blob/master/sampleTrace.trace.zip
@brianrob

**Comment by pigwing** [comment] 2018-07-18 06:12
is about irqbalance problem?

**Comment by pigwing** [comment] 2018-07-18 06:15
my app is ECO.Gateway

**Comment by karelz** [comment] 2018-07-18 09:09
Did you get chance to analyze the traces? Where does it point to and why?

**Comment by pigwing** [comment] 2018-07-18 13:45
all cpu use in libcorelir.so and i can not found any information

**Comment by pigwing** [comment] 2018-07-19 14:36
i am use .net core 2.0,cpu avg use 10%-15% these 3 days not longer this problem

**Comment by wfurt** [comment] 2018-09-20 20:59
can you provide some simplified repro? Also note, that you can connect to the precess with Visual Studio and do normal debugging. 

cc: @janvorli

**Comment by janvorli** [comment] 2018-09-20 21:10
My guess is that it could be related to a spinlock bug that was fixed in https://github.com/dotnet/coreclr/pull/19606. The fix should go out in 2.1.5.

**Comment by pigwing** [comment] 2018-09-21 08:34
@janvorli well

**Comment by joperezr** [comment] 2018-10-22 20:20
@pigwing v.2.1.5 was released a couple of weeks ago, do you mind validating if that was the cause of the problem? If so, we can just go ahead and close this issue.

**Comment by wfurt** [comment] 2018-12-20 22:17
2.1.6 is out. Do you have any updates @pigwing ???

**Comment by pigwing** [comment] 2018-12-21 02:57
@wfurt yeah,2.1.6 is ok.thx

**Comment by pigwing** [comment] 2018-12-21 02:58
@joperezr yes,i upgrade to 2.2 that is well

**Comment by joperezr** [comment] 2019-01-04 19:44
I see, so I believe that this issue can probably be closed now. Feel free to reopen if you feel otherwise.

**Closed by joperezr** 2019-01-04 19:44 UTC
Labels: arch-arm32, area-Meta, os-linux, tenet-performance
