### ISSUE TITLE
EventLogTests.DeleteLogTest failed on Win7 in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24690] opened 2017-10-17 15:35 UTC
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/0105300fc3ca40d98db157cea91b097c68de6627/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTests~2FDeleteLogTest
```
Windows.7.Amd64.Open-Debug-x64
Unhandled Exception of Type System.ComponentModel.Win32Exception
Message :
System.ComponentModel.Win32Exception : Access is denied
Stack Trace :
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.EventLog.Delete(String logName)
   at System.Diagnostics.Tests.EventLogTests.DeleteLogTest()
```

**Comment by stephentoub** [comment] 2017-10-24 15:24
Another access denied failure on a different test, WriteEntryWithTypeIdCategoryAndData:
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/4c5a4efb652236a41ee701f1ee268e361b793489/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogWriteEntryTests~2FWriteEntryWithTypeIdCategoryAndData(sourceFlag:%20False)
```
Unhandled Exception of Type System.ComponentModel.Win32Exception
Message :
System.ComponentModel.Win32Exception : Access is denied
Stack Trace :
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at System.Diagnostics.EventLog.WriteEvent(String source, EventInstance instance, Object[] values)
   at System.Diagnostics.Tests.EventLogWriteEntryTests.WriteLogEntryWithSource(String source, Boolean type, Boolean instance, Boolean category, Boolean data)
   at System.Diagnostics.Tests.EventLogWriteEntryTests.WriteEntryWithTypeIdCategoryAndData(Boolean sourceFlag)
```

**Comment by ViktorHofer** [comment] 2017-10-24 15:46
cc @Anipik

**Comment by danmosemsft** [comment] 2017-10-24 15:52
It's not that we're not elevated, as we check for that, plus all the other tests pass. There is no issue on other OS. It seems something flaky inside the OS.

All I can think of is either to make just about every test do retries on Windows 7 -- or, update ClearEventLog and InternalWriteEvent to do a retry on access denied. I would lean towards the latter as it makes the product more robust.

**Comment by danmosemsft** [comment] 2017-10-24 19:48
@Anipik is going to disable for now

**Comment by Anipik** [comment] 2017-11-01 22:16
@danmosemsft should I close this issue now ?

**Comment by stephentoub** [comment] 2017-11-02 14:29
> should I close this issue now ?

Is the problem fixed, or the test just disabled? If the problem is fixed, you can close the issue. If the test is just disabled, the issue should remain open to track providing a real fix.

**Comment by Anipik** [comment] 2017-11-02 16:05
no the problem is fixed and tests are enabled again

**Closed** 2017-11-02 16:20 UTC
Labels: area-System.Diagnostics.Tracing
