### ISSUE TITLE
Test failure: System.ComponentModel.Tests.DateTimeOffsetConverterTests.ConvertTo_DestinationType_Success

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#40134] opened 2019-08-08 06:34 UTC
Test `System.ComponentModel.Tests.DateTimeOffsetConverterTests.ConvertTo_DestinationType_Success` has failed.

Error message:
```
Assert.All() Failure: 4 out of 13 items in the collection did not pass.\r\n[5]: 
Item: Source='12/5/1998 10:30:30 PM +00:00', Type='System.String', Culture='', RemoteCulture='pl-PL'\r\n 
Xunit.Sdk.TrueException: Exit code was -1073740940 but it should have been 42\r\n 
Expected: True\r\n 
Actual: False\r\n 
at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 96\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 143\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55\r\n 
at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 73\r\n 
at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\r\n[4]: 
Item: Source='12/5/1998 10:30:30 PM +00:00', Type='System.String', Culture='(null)', RemoteCulture='pl-PL'\r\n 
Xunit.Sdk.TrueException: Exit code was -1073740940 but it should have been 42\r\n 
Expected: True\r\n Actual: False\r\n at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 96\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 143\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55\r\n at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 73\r\n 
at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\r\n[2]: Item: Source='12/5/1998 12:00:00 AM +00:00', Type='System.String', Culture='', RemoteCulture='pl-PL'\r\n 
Xunit.Sdk.TrueException: Exit code was -1073740940 but it should have been 42\r\n 
Expected: True\r\n 
Actual: False\r\n 
at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 96\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 143\r\n 
at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55\r\n 
at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__13_0(ConvertTest convertTest) in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 73\r\n 
at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\r\n[1]: 
Item: Source='12/5/1998 12:00:00 AM +00:00', Type='System.String', Culture='(null)', RemoteCulture='pl-PL'\r\n 
Xunit.Sdk.TrueException: Exit code was -1073740940 but it should have been 42\r\n 
Expected: True\r\n 
Actual: False\r\n 
at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 96\r\n 
at Microsoft.DotNet.RemoteExecutor.Rem
```
Stack trace:
```
   at System.ComponentModel.Tests.TypeConverterTestBase.ConvertTo_DestinationType_Success() in /_/src/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 74
```
Build: -[20190807.51](https://dnceng.visualstudio.com/public/_build/results?buildId=299775&view=ms.vss-test-web.build-test-results-tab&runId=8523276&resultId=114109&paneView=debug)(Master)

Failing configuration:

- netcoreapp-Windows_NT-Release-x64-windows.10.amd64.serverrs4.open

Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=299775&view=ms.vss-test-web.build-test-results-tab&runId=8523276&resultId=114109&paneView=debug

**Comment by safern** [comment] 2019-08-08 21:32
This a dupe of: https://github.com/dotnet/corefx/issues/38858

RemoteExecutor crashing in Nano 1803, which seems to be fixed in 1809, should be taken care of in: https://github.com/dotnet/corefx/pull/39734

**Closed by safern** 2019-08-08 21:32 UTC
Labels: area-System.ComponentModel, test-run-core
