### ISSUE TITLE
PlatformApis.IsWindows is evaluating true on macOS 10.12/mono 4.6.1

### ISSUE THREAD

**Issue by zgramana** [dotnet/corefx#12203] opened 2016-09-29 19:55 UTC
### Given

Had a functioning Kestrel app. Upgraded to macOS 10.12 and mono 4.6.1. Executed `dotnet restore` and then executed `dotnet run` as usual.
### Expected

Nominal app startup
### Observed

Unhandled Exception: `System.DllNotFoundException: WS2_32.dll` (full stack trace below)
### Notes

One doesn't expect `WS2_32.dll` to be present on non-Windows systems, and there is [a guard against attempting to P/Invoking into it on non-Windows platforms](https://github.com/aspnet/KestrelHttpServer/blob/1a273f5a34cae8ea39d99bd5e7ff64eb6057d142/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs#L202-L205), but it appears that the guard now returns `true` after updating to 10.12.

---

Full stack trace:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: WS2_32.dll
  at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods:WSAIoctl (intptr,int,int*,uint,int*,int,uint&,intptr,intptr)
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind_windows_extras (Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle handle) [0x0001f] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind (Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle handle, Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.SockAddr& addr, System.Int32 flags) [0x00023] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind (Microsoft.AspNetCore.Server.Kestrel.ServerAddress address) [0x0004a] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket () [0x00040] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener+<>c.<StartAsync>b__6_0 (System.Object state) [0x00012] in <7fa2145c3191420fad86bd0c6af65de7>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary+<StartAsync>d__11.MoveNext () [0x000f5] in <7fa2145c3191420fad86bd0c6af65de7>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189 
  at System.Threading.Tasks.Task.Wait () [0x00000] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3054 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer (Microsoft.AspNetCore.Server.Kestrel.ServerAddress address) [0x000e1] in <7fa2145c3191420fad86bd0c6af65de7>:0 
---> (Inner Exception #0) System.DllNotFoundException: WS2_32.dll
  at (wrapper managed-to-native) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods:WSAIoctl (intptr,int,int*,uint,int*,int,uint&,intptr,intptr)
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind_windows_extras (Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle handle) [0x0001f] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind (Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle handle, Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.SockAddr& addr, System.Int32 flags) [0x00023] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind (Microsoft.AspNetCore.Server.Kestrel.ServerAddress address) [0x0004a] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket () [0x00040] in <7fa2145c3191420fad86bd0c6af65de7>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener+<>c.<StartAsync>b__6_0 (System.Object state) [0x00012] in <7fa2145c3191420fad86bd0c6af65de7>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary+<StartAsync>d__11.MoveNext () [0x000f5] in <7fa2145c3191420fad86bd0c6af65de7>:0 <---
```

**Comment by stephentoub** [comment] 2016-09-29 20:31
@zgramana, this issue is about using Kestrel on macOS with mono (rather than with corefx/coreclr)?  It'd be better over in the https://github.com/aspnet/kestrelhttpserver repo.

**Comment by zgramana** [comment] 2016-09-29 20:46
It is, but after digging around, I realized that seems to be coincidence.

I found this line in both `dotnet-compile.rsp` and `dotnet-compile-csc.rsp`, which raised some hairs since I'm targeting 4.5.1 and all the references point to paths like `lib/net4[051]+/`:
```
--reference:/Users/zgramana/.nuget/packages/System.Runtime.InteropServices.RuntimeInformation/4.0.0/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
```
Intrigued, I wrote a little test. Using this assembly, I ran this 1-line program on OS X 10.12:     ```Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX));```
which output:
```
False
```
Not sure if kestrelhttpserver is still the right repo for this.

**Comment by stephentoub** [comment] 2016-09-29 21:00
> Intrigued, I wrote a little test

This assembly has different implementation builds for Windows and Unix.  It sounds like somehow you're using the Windows build rather than the Unix one.  I assume if you modify your test to do IsOSPlatform(OSPlatform.Windows) it returns true?

**Comment by zgramana** [comment] 2016-09-29 21:03
It does not, nor does it return true for Linux FWIW.

Something in the tooling added this reference, presumably the CLI during restore, but I'm just guessing.

**Comment by stephentoub** [comment] 2016-09-29 21:10
Hmm, I wonder if you're using the reference assembly at a run time (the reference assembly has default implementations of all member bodies, so anything that returned a bool would return false).  What's the output of typeof(RuntimeInformation).GetTypeInfo().Assembly.Location?  And if you open that path in ildasm or reflector or some other disassembler, what do member bodies look like?

**Comment by zgramana** [comment] 2016-09-29 21:15
FWIW, the OS version string was `Unix 16.0.0.0`. When I'm back at my machine I'll give it a try.

**Comment by zgramana** [comment] 2016-09-29 21:17
It did run `monodis` and the bodies didn't look like no-ops.

**Comment by stephentoub** [comment] 2016-09-29 21:22
> the bodies didn't look like no-ops

Does the implementation of IsOSPlatform mention Interop.Sys.GetUnixName?  If so, can you try doing:
```
using System.Runtime.InteropServices;
...
[DllImport("System.Native")]
private static extern IntPtr SystemNative_GetUnixName();
...
Console.WriteLine(Marshal.PtrToStringAnsi(SystemNative_GetUnixName()));
```
and share the output?

**Comment by zgramana** [comment] 2016-09-29 22:11
Okay, finally back at a terminal, and indeed the library was a reference assembly with a bunch of `ldnull`s were staring me in the face. 😮

I ran this block of code in my actual app's `Main`:
```
Console.WriteLine("OSX: " + RuntimeInformation.IsOSPlatform(OSPlatform.OSX));
Console.WriteLine("Windows: "+ RuntimeInformation.IsOSPlatform(OSPlatform.Windows));
Console.WriteLine("Linux: " + RuntimeInformation.IsOSPlatform(OSPlatform.Linux));
Console.WriteLine(typeof(RuntimeInformation).Assembly.Location);
Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.OSArchitecture);
```
With the output:
```
OSX: False
Windows: True
Linux: False
/Users/the/path/to/my/programs/bin/Debug/net451/osx.10.12-x64/System.Runtime.InteropServices.RuntimeInformation.dll
Unhandled Exception:
System.DllNotFoundException: api-ms-win-core-sysinfo-l1-2-0.dll
  at (wrapper managed-to-native) Interop+mincore:GetNativeSystemInfo (Interop/mincore/SYSTEM_INFO&)
  at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture () [0x0001c] in <f13660f89d0d419fba4e315693dd26ea>:0 
  at aspnetcoreapp.Program.Main (System.String[] args) [0x00081] in /Users/the/path/to/my/programs/Program.cs:15 
```

However, I did look through the disassembly in the actual assembly copied into `bin/Debug/net451/osx.10.12-x64/` and it's definitely a Windows build, and appears identical to `~/.nuget/packages/System.Runtime.InteropServices.RuntimeInformation/4.0.0/lib/net45/System.Runtime.InteropServices.RuntimeInformation.dll`
```
.module extern 'ntdll.dll'
.module extern 'api-ms-win-core-sysinfo-l1-2-0.dll'
.module extern 'api-ms-win-core-sysinfo-l1-1-0.dll'

[[ ...snip...snip.... ]]

    // method line 10
    .method public static hidebysig 
           default bool IsOSPlatform (valuetype System.Runtime.InteropServices.OSPlatform osPlatform)  cil managed 
    {
        // Method begins at RVA 0x21aa
        // Code size 12 (0xc)
        .maxstack 8
        IL_0000:  call valuetype System.Runtime.InteropServices.OSPlatform valuetype System.Runtime.InteropServices.OSPlatform::get_Windows()
        IL_0005:  ldarg.0 
        IL_0006:  call bool valuetype System.Runtime.InteropServices.OSPlatform::op_Equality(valuetype System.Runtime.InteropServices.OSPlatform, valuetype System.Runtime.InteropServices.OSPlatform)
        IL_000b:  ret 
    } // end of method RuntimeInformation::IsOSPlatform
```
For fun, I looked at the `monodis` for `bin/Debug/net451/osx.10.11-x64/System.Runtime.InteropServices.RuntimeInformation.dll`, and this one *is* correct:
```
.module System.Runtime.InteropServices.RuntimeInformation.dll // GUID = {862459BD-8869-4743-8B3F-CF70C862F252}

.module extern 'System.Native'

[[ ...snip...snip.... ]]
    // method line 29
    .method private static hidebysig pinvokeimpl ("System.Native" as "SystemNative_GetUnixName" winapi )
           default native int GetUnixNamePrivate ()  cil managed preservesig 

```

**Comment by stephentoub** [comment] 2016-09-29 22:18
@zgramana, thanks for the follow-up.

@ericstj, is this an issue with NuGet not being able to differentiate Mono from desktop?  Or something to do with it not understanding macOS Sierra?

**Comment by zgramana** [comment] 2016-09-29 22:19
Confirmed the workaround does indeed work around the issue

#### Confirm status quo doesn't work
```
> mono bin/Debug/net451/osx.10.12-x64/program.exe
Unhandled Exception:
System.DllNotFoundException: api-ms-win-core-sysinfo-l1-2-0.dll
...
```
#### Confirm workaround does work
```
> cp bin/Debug/net451/osx.10.11-x64/System.Runtime.InteropServices.RuntimeInformation.dll bin/Debug/net451/osx.10.12-x64/System.Runtime.InteropServices.RuntimeInformation.dll
> mono bin/Debug/net451/osx.10.12-x64/program.exe
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

**Comment by zgramana** [comment] 2016-09-29 22:31
I did a run with `COREHOST_TRACE=1 MONO_LOG_LEVEL=debug dotnet run` and it appears that the error happens when `dotnet` builds the `csc` response file, which it then passes in:
```
Launch host: /usr/local/share/dotnet/dotnet, app: /usr/local/share/dotnet/sdk/1.0.0-preview2-003121/csc.dll, argc: 2, args: -noconfig,@/Users/the/path/to/my/programs/obj/Debug/net451/dotnet-compile-csc.rsp
```

**Comment by tarekgh** [comment] 2017-03-02 19:54
CC @zgramana is this still happening? 

@akoeplinger did you run into similar issue before? 

@ericstj is this can be Nuget issue?

**Comment by ericstj** [comment] 2017-03-02 20:57
I suspect the app is using the desktop implementation of RuntimeInformation that got copied to the app's output directory and mono isn't overriding.  That desktop implementation [hardcodes](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L19) windows.  There's been discussion before about making the desktop implementation of this library handle mono better but I don't think that work has been done /cc @Priya91.  So the only way mono will get a better implementation (today) is if it implements it itself and prefer's that over the one in the desktop app.

**Comment by Priya91** [comment] 2017-03-02 23:42
Mono has already implemented RuntimeInformation.IsOSPlatform [here](https://github.com/mono/mono/blob/ff7a2a5114d6da678a5a75c5eebf0731db4f3aed/mcs/class/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices/RuntimeInformation.cs#L47). Not sure how to control Nuget to pick this version though.

**Comment by ericstj** [comment] 2017-03-02 23:44
It's not about NuGet.  Mono apps and desktop apps are identical at build time.  Mono has to decide at runtime to reject the copy in the app.  We're having a discussion about this here: https://github.com/dotnet/corefx/issues/15112

**Comment by Priya91** [comment] 2017-03-02 23:54
Thanks @ericstj , the solution from #15112 should fix this issue?

**Comment by ericstj** [comment] 2017-03-03 00:02
Sure in the long term it will.

**Comment by karelz** [comment] 2017-03-03 08:07
OK, marking as dupe of #15112. Please shout out if it is wrong.

**Closed by karelz** 2017-03-03 08:07 UTC
Labels: area-System.Runtime.InteropServices, bug
