### ISSUE TITLE
Should we allow multiply TimeSpan with number?

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#24165] opened 2017-09-20 10:52 UTC
Instead of

```C#
var day = TimeSpan.FromDay(1)
var twoDay = TimeSpan.FromDay(2);
var halfDay = TimeSpan.FromDay(0.5f);
var eDay = TimeSpan.FromDay(Math.E);
var goldenDay = TimeSpan.FromDay((1 + Math.Sqrt(5)) / 2);
```

If we could multiply TimeSpan with number it would be easier

```C#
var day = TimeSpan.FromDay(1);
var twoDay = 2 * day;
var halfDay = day / 2;
var eDay = day * Math.E;
var goldenDay = day * (1 + Math.Sqrt(5)) / 2;
```

**Comment by JonHanna** [comment] 2017-09-20 11:44
.NET Core already has this. #16475
(I like the idea that a day, 14 hours, 49 minutes and 58.137 seconds is a *golden day* 😄).

**Comment by JonHanna** [comment] 2017-09-20 11:48
Incidentally, one can also now divide `TimeSpan`s by `TimeSpan`s. `TimeSpan.FromDays(1) / TimeSpan.FromHours(1)` returns 24.0, and so on.

**Comment by karelz** [comment] 2017-09-20 15:44
Duplicate of #7175

**Closed by karelz** 2017-09-20 15:44 UTC
