### ISSUE TITLE
Missing Release Notes for NuGet Packages

### ISSUE THREAD

**Issue by compilenix** [dotnet/corefx#31935] opened 2018-08-24 08:28 UTC
I cannot find any release notes about [System.Threading.Tasks.Dataflow release 4.9.0](https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/4.9.0).

The link to https://go.microsoft.com/fwlink/?LinkID=799421 works but i'm not able to find any release notes about any recent version of System.Threading.Tasks.Dataflow.

Possible solutions:
1. Update the release notes section of the Nuget package to embed or link to the specific release notes for this version.
2. Create release notes which summarize notable changes from the previous NUget packet version to the new version.

**Comment by tarekgh** [comment] 2018-08-25 00:36
@compilenix you can navigate the release note link https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/4.9.0 and then browse to the desired release note. here is some example link listing or commits done in 2.1.3 release  https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3-commits.md

you can do the same with any other release. I don't think we include in every library package a release note specific to the library, instead, we point to the release notes for the whole net core.

**Comment by compilenix** [comment] 2018-08-26 20:00
I've seen that there are release notes for the whole net core and it's components, which System.Threading.Tasks.Dataflow is part of.

There are things which makes this really difficult:

1. I cannot see which version of the package (4.9.0 in this case) coresponses to which net core version and therefore which release notes i have to read.
2. in the example link for net core 2.1.3 i can't see anything about changes to System.Threading.Tasks.Dataflow or to which NUget package version this belogs.
3. as far as i can see this, this os not specific to System.Threading.Tasks.Dataflow but also aplies to many other parts / components of net core, i've found multiple places where release notes with slightly varying content are held. I.e.:

- https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3.md
- https://blogs.msdn.microsoft.com/dotnet/2018/08/21/net-core-august-2018-update/
- https://github.com/aspnet/Home/releases/tag/2.1.3

None of the links above go into detail about what parts have changed in which way, without reading the commit messages and assosiated issues myself which would be really timeconsuming considering i might be interested in the changes about a single NUget package.

Sorry for the slightly broken language, i'm not a native english speaker^^

**Comment by tarekgh** [comment] 2018-09-05 19:51
@terrajobst @ericstj do you know if we support adding the release notes for every library we support? or we just share the release notes for the whole release?

**Comment by tarekgh** [comment] 2018-09-06 19:09
CC @joperezr

**Comment by joperezr** [comment] 2018-09-06 20:26
I don't believe we have a good way today to provide release notes to the library granularity.

**Comment by compilenix** [comment] 2018-11-06 09:44
So there is no reasonable way no know what changed between nuget package releases (i.e. from 4.8.0 to 4.9.0), when they are'nt mentioned in the release notes of dotnet core?

**Comment by sillyousu** [comment] 2019-03-27 07:26
any update?

**Comment by tarekgh** [comment] 2019-03-27 14:58
CC @karelz @danmosemsft 

@compilenix I don't think anything changed since last reply you received from @joperezr. We are not including the release notes per package and instead we have release notes for the whole release. We may look at that in the future but don't expect this will change for 2.1 release.

**Comment by compilenix** [comment] 2019-04-01 16:24
OK, thanks for the response @tarekgh :)

**Comment by ViktorHofer** [comment] 2019-06-23 19:25
Closing as dupe of https://github.com/dotnet/corefx/issues/26014

**Closed by ViktorHofer** 2019-06-23 19:25 UTC
Labels: area-Infrastructure, documentation
