### ISSUE TITLE
Exception when return type contains SqlConnection

### ISSUE THREAD

**Issue by Kation** [dotnet/corefx#13032] opened 2016-10-26 03:52 UTC
If a method or property that return type contains SqlConnection like **SqlConnection**, **Task&lt;SqlConnection&gt;** or **List&lt;SqlConnection&gt;**, there is an exception when we are trying to list this object in **Watch Window**.

```
public class A
{
    public A()
    {
        //breakpoint in the class codes, type 'this' in the Watch window
        //throw exception 'Internal error in the expression evaluator'
    }

    public SqlConnection Test() { return null; }
}
```

**Comment by svick** [comment] 2016-10-26 11:28
What is the exception?

**Comment by Kation** [comment] 2016-10-26 15:30
When breakpoint in the class that has the member I said, type **this** will show **Internal error in the expression evaluator**.

**Comment by saurabh500** [comment] 2016-11-10 03:15
@Kation 
Does this happen when you try to print the value of object on Console ? `Console.WriteLine(offendingObject)` 

Does it repro in any other language as well apart from ZH-CN ? 

I want to understand if this is a tooling issue or an issue with SqlConnection?

@karelz Can you get someone from VS tooling to look into this as well?

**Comment by Kation** [comment] 2016-11-10 03:57
@saurabh500 
It can print the class name in the Console. 
There is no error to do all things in the codes but use in the **Visual Studio Window** like **Watch Window** etc.

I have no English environment right now. I will test it later.

**Comment by karelz** [comment] 2016-11-10 05:19
@noahfalk @cshung @FrankPeschel-Gallee do you know how to reach folks in VS Debugger who know about expression evaluator?
@Kation you can use VS feedback channel - menu: Help -> Send Feedback -> Report a Problem...

Given that the issue is likely in VS, not in .NET Core / System.Data.SqlClient, I would suggest to close this issue.

**Comment by Kation** [comment] 2016-11-10 08:53
@karelz 
Maybe this is an issue with .Net Core Tools For Visual Studio?

**Comment by saurabh500** [comment] 2017-03-20 23:13
Closing as this is not a .Net Core SqlClient issue

**Closed by saurabh500** 2017-03-20 23:13 UTC
Labels: area-System.Data.SqlClient, needs more info

**Comment by karelz** [comment] 2017-03-20 23:16
@saurabh500 so where is the problem? In the app?
If it is another .NET Core component or VS, we need to route it, not close it ...

**Comment by saurabh500** [comment] 2017-03-20 23:18
@karelz you had already provided a path forward to report this in comments above

**Comment by karelz** [comment] 2017-03-20 23:29
Ooops, missed/misread my own comment, embarrassing :( ... Thanks @saurabh500!
