### ISSUE TITLE
Will SqlCommandBuilder.DeriveParameters be in .net core

### ISSUE THREAD

**Issue by nhathongly** [dotnet/corefx#20560] opened 2017-06-01 10:04 UTC
We're porting some of our libraries to .net core. In our code, we use SqlCommandBuilder.DeriveParameters to retrieve parameters of a stored procedure, so that we can check if there is any of parameters added in the SqlCommand.Parameters is invalid or not ('invalid' means not defined in the stored procedure).

My question is: do you have any plan to bring SqlCommandBuilder to CoreFx?
Thanks

**Comment by danmosemsft** [comment] 2017-06-01 17:01
dupe of #5501 and tracked in https://github.com/dotnet/corefx/issues/17126. Thanks for the feedback. @saurabh500 for the question ...

**Comment by saurabh500** [comment] 2017-06-01 17:15
Yes we are bringing back SqlCommandBuilder to core. The reason it is not available right now is because of the dependency on query notofication.  We will be bring in query notifications which will unblock the path forward for SqlCommandBuilder

**Comment by saurabh500** [comment] 2017-06-01 17:18
The issue tracking SqlCommandBuilder specifically is at https://github.com/dotnet/corefx/issues/5501 
Closing this issue.
cc @corivera

**Closed by saurabh500** 2017-06-01 17:18 UTC
