### ISSUE TITLE
Test failure: System.Tests.GetCommandLineArgs/GetCommandLineArgs_Invoke_ReturnsExpected(args: [\"arg1\", \"\\\\\\\\\\\\\\\\\\\\\\\"alpha\", \"\\\\\\\"arg3\"]) 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38872] opened 2019-06-25 09:39 UTC
Test `System.Tests.GetCommandLineArgs/GetCommandLineArgs_Invoke_ReturnsExpected(args: [\"arg1\", \"\\\\\\\\\\\\\\\\\\\\\\\"alpha\", \"\\\\\\\"arg3\"]) ` has failed.

Message :
```
Exit code was -1073740940 but it should have been 42
Expected: True
Actual:   False
```
Stack Trace :
```
  at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 143
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55
   at System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(String[] args) in /_/src/System.Runtime.Extensions/tests/System/Environment.GetCommandLineArgs.cs:line 49
```
Build: -[20190624.84](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.84)(Master)

Failing configurations:

- Windows.Nano.1803.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.84/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.GetCommandLineArgs~2FGetCommandLineArgs_Invoke_ReturnsExpected(args:%20%5B%5C%22arg1%5C%22,%20%5C%22%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%5C%22alpha%5C%22,%20%5C%22%5C%5C%5C%5C%5C%5C%5C%22arg3%5C%22%5D)

**Comment by vcsjones** [comment] 2019-06-25 17:09
Duplicate of #38858.

**Closed** 2019-06-26 17:41 UTC
Labels: area-System.Runtime.Extensions, test-run-core
