### ISSUE TITLE
System.Text.Json ExpandoObject not supported

### ISSUE THREAD

**Issue by MickeyReznikov** [dotnet/corefx#41156] opened 2019-09-17 13:19 UTC
When i try to return ExpandoObject as a return, looks like its not supported yet

`
ExpandoObject e = new ExpandoObject();
            ((IDictionary<string, object>)e).Add("key", "value");

            var results = System.Text.Json.JsonSerializer.Serialize(e);`

Unable to cast object of type '\<GetExpandoEnumerator\>d__51' to type 'System.Collections.IDictionaryEnumerator'.

planned for version 3?

**Comment by ahsonkhan** [comment] 2019-09-18 00:00
No. We do not have support for dynamic types like `ExpandoObject`. This is a duplicate of https://github.com/dotnet/corefx/issues/38007

Feel free to add your scenario/use case to that issue.

**Closed by ahsonkhan** 2019-09-18 00:00 UTC
Labels: area-System.Text.Json, enhancement
