### ISSUE TITLE
How to develop in corefx for UWP

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#20326] opened 2017-05-25 19:38 UTC
Opening on behalf of @CIPop from https://github.com/dotnet/corefx/pull/20322#issuecomment-304102737

>@ericstj @weshaggard /cc @karelz @DavidGoll Could you please help with the following:

>1. How to get Visual Studio debugging to work for UWP.
>2. How to get Visual Studio build to work correctly for UWP.
>3. How to test UWP APIs that are not part of netstandard20 (e.g. APIs that exist in .Net 4.7 / netcoreapp such as TLS Alerts or TLS SystemDefault version).

**Comment by weshaggard** [comment] 2017-05-25 19:43
If you want to build and debug UWP configurations you need to have a uap configuration in your project configuration.props file. If you are only targeting netstandard in your configuration you will only see netstandard APIs, you need to target specific TFM if you want to be able to use APIs that are only in that target.

**Comment by CIPop** [comment] 2017-05-25 21:21
@weshaggard : in certain cases (most cases) we won't have a specific build for `uap` - is it still OK to add the configuration just for the Visual Studio editor to work? (Would that interfere somehow with the build system unnecessarily?)

**Comment by weshaggard** [comment] 2017-05-30 20:01
For test projects I think it is probably OK to add a configuration. It will be the only way you can actually successfully build and run it from VS. 

The only difference that would happen is that your test binary would be built against the uap set of reference assemblies instead of netstandard which isn't the end of the world.

**Comment by ViktorHofer** [comment] 2018-08-26 20:01
As the issue is already more than a year old let me ask - do we still want to invest in the debugging scenario for UWP inside corefx? I believe with _some_ work it would be possible. This will definitely come up again when a) we have VS Test Explorer support enabled and b) VS supports multi-configuration testing.

**Comment by wtgodbe** [comment] 2018-12-28 22:03
Closing for now with lack of traction. We can re-open if this comes up again in the future.

**Closed by wtgodbe** 2018-12-28 22:03 UTC
Labels: area-Infrastructure, question
