### ISSUE TITLE
No Database connection from Ubuntu 14.04 LTS to SQL Server 2008 R2

### ISSUE THREAD

**Issue by MontyGvMC** [dotnet/corefx#12987] opened 2016-10-25 12:48 UTC
I am facing problems connecting from an ASP.NET Core Web API using Entity Framework Core running on Ubuntu 14.04 LTS to a Windows Server 2008 R2 running a SQL Server 2008 R2.

the Window Server 2008 R2 is unpatched.
I installed SQL Server Service Pack 3,
have TCP/IP enabled,
have named pipes enabled.

The app gets running and everything seems fine (swagger ui shows up shows the rest api)
when I try to make an request from swagger it throws an System.Data.SqlClient exception in the background.

I was adviced to this board [from here](https://github.com/aspnet/EntityFramework/issues/6830)
Here I also show that I already used different versions of the connection string (WITHOUT named instances) all without success.

I also seeked help on [Stackoverflow](http://stackoverflow.com/questions/40150357/asp-net-core-web-api-on-ubuntu-14-04-lts-doesnt-get-sql-connection-to-mssql-200?noredirect=1#comment67578524_40150357)

Hopefully, someone here can point me to the error or can confirm that this is an issue.
....
System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.RequestTrackingMiddleware.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.d__2.MoveNext()
.....

**Comment by karelz** [comment] 2016-10-25 15:41
@saurabh500 can you please advise here?

**Comment by saurabh500** [comment] 2016-10-25 17:04
@MontyGvMC  Do you have SP3 installed on the server 2008 R2 ?

**Comment by MontyGvMC** [comment] 2016-10-26 09:46
I installed SQL Server 2008 R2 Service Pack 3.

For Windows Server 2008 R2 the highest I could find was Service Pack 1 and so far we decided not to patch  the Windows Server itself (who knows what doesnt run afterwards).

I am preparing a fresh Windows Server 2008 R2 (fully patched via internet updates) and a fresh SQL Server 2008 R2 to test the project and this issue. 

Maybe tomorrow I can say more if it works with patches.

**Comment by saurabh500** [comment] 2016-10-26 18:10
@MontyGvMC 
>> I am preparing a fresh Windows Server 2008 R2 (fully patched via internet updates) and a fresh SQL Server 2008 R2 to test the project and this issue.

I am assuming that you will update the Sql Server 2008 R2 with SP3 in the new installation.

**Comment by MontyGvMC** [comment] 2016-10-27 05:52
I will.
But as mentioned the SQL Server is already patched in the currrnt setup and I am still getting the exception.
So Service Pack 3 for the SQL Server 2008 R2 alone seems not to fix the problem.

**Comment by MontyGvMC** [comment] 2016-10-28 10:29
@saurabh500 I installed service pack 3

Well ladies and guys, i am back reporting my progress.

You can't imagine how much fun I had the last days.

I installed a fresh new Windows Server 2008 R2 including the latest service pack.
Then I started the always beloved game of checking for Windows Updates, Install them, reboot,
check for windows updates again, install them, reboot,...... over a slow internet connection. 

Then I installed Windows SQL Server 2008 R2, installed Service Pack 3, checked for Windows Updates, installed them, rebooted, checked for Windows Updates, installed them, rebooted, ..... same slow internet connection,....

Interestingly it mentioned it also wants Dot Net Core installed. Can't imagine this is installed on the old server runnig a couple of time (years?)

Well, after a few days playing windows updates and rebooting I ended up with a fully patched Windows Server 2008 R2, Windows SQL Server 2008 R2, dotnet runtime 1.01, Visual Studio 2015 c++ redistributable,... and whatever it asked me to install

A day later I managed to migrate our database to the new server (long life database first approach).

And guess what: I still get SqlClient Exception
From Windows 7 development environment I also get a System.Data.SqlClient.Exception: A connection was successfully established with the server, but than an error occured during the pre-login handshake
each first time the web api starts (works on the second request on all requests afertwards).

Then I had the idea: eah, lets thes the latest packages (including previews of 1.1.0) and leave the latest stable versions (1.0.0 or 1.0.1)
bad idea, now nothing works on ubunutu now 
(it looks for the ProjectName.xml but on /var/www/[ABSOLUTE PATH TO THE DIRECTORY OF THE DEV ENVIRONMENT].ProjectName.xml).

I also have to rename the NLog.config to nlog.config each time since it allways keeps the CamelCase typing although i renamed it in each config file/source file i found to all lower case typing.
Ubuntu can't find them if they are named nlog.config in code but the file on the system is name NLog.config.

Well, the resume:
With all updates and patches and fixes available over windows update the exception remains on Ubuntu within the latest stable version available.
I have an pre-login Handshake error new in the task list.

And I got my own development server (so I am not tied to an unpatched windows server 2008 and a ubuntu for deployment).
Will either get rid of Linux or Windows and stick on the same tech for development. Till release where I am will be tied to good old Windows Server 2008 R2 again :-)

Keep you updated once errors /changed disappeared on my side.
Recomendations what I should check on Windows side or Ubuntu side still warmly welcome.

Thanks for your patience so far.

**Comment by MontyGvMC** [comment] 2016-10-28 10:55
Whatever update (to newest versions including previews) broke the build causing the problem searching the ProjectName.xml on /var/www/[ABSOLUTE PATH TO WINDOWS DEV ENVIRONMENT] was not in the project.json. It remains after reverting project.json to last working copy from the repository.

Now I can not build for Ubuntu anymore. Yeah.

Resume: do not try preview versions
reevaluating my/our project technologies

**Comment by saurabh500** [comment] 2016-10-28 17:43
cc @corivera 
@MontyGvMC The first error that you have posted points to a failure in DNS resolution from Ubuntu to the Server machine 
`System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address`

Can you provide the full stack trace for the new failure with .Net core 1.0 and Sql Server 2008 R2 with SP3? 

We have recognized that Sql Server 2008 R2 with SP3 will help fix the issues for connectivity from Ubuntu. 
Based on your notes, your environment seems to be setup correctly and it should allow connectivity from SqlClient on Ubuntu.

**Comment by MontyGvMC** [comment] 2016-10-29 20:01
I will give it a try on wednesday (weekend and national holiday).

**Comment by saurabh500** [comment] 2016-10-31 17:52
@MontyGvMC For Sql Server 2008 R2 with SP3 on Windows Server 2008 you may need to update the TLS 1.2 by changing the registry key.
https://technet.microsoft.com/en-us/library/dn786418(v=ws.11).aspx#BKMK_SchannelTR_TLS12

TLS 1.2
This subkey controls the use of TLS 1.2.
Note: For TLS 1.2 to be enabled and negotiated on servers that run Windows Server 2008 R2, you MUST create the "DisabledByDefault" entry in the appropriate subkey (Client, Server) and set it to "0". The entry will not be seen in the registry and it is set to "1" by default.

**Comment by saurabh500** [comment] 2016-11-03 19:07
@MontyGvMC Any updates on this issue?

**Comment by MontyGvMC** [comment] 2016-11-04 06:26
@saurabh500 Hi. Unfortunatly not yet. 

Before one of the last posts I updated all packages including a part of Visual Studio. It asked me to do so from the NuGet Packet Manager to install a newer version of some used Packet. I haven't found a way to revert this installation.

With this installation it looks for a Project.xml instead of a Project.json. That would'nt be a problem but on my builds for Ubuntu it looks for that Project.xml in a wrong path so I currently can't start my application on Ubuntu to do further tests.

The pattern for the path where it searches for the xml is:
[DeploymentDirectory]/[AbsolutePathOnTheDevelopmentMachine]/Project.xml
or namely
/var/www/E:/Repositories/Project/src/Project/Project.xml.

This is blocking my further investigations at the moment.

Thanks for your patience. I will keep you updated as soon as possible.

**Comment by saurabh500** [comment] 2016-11-04 17:10
@MontyGvMC On the client machine (Ubuntu in this case) can you create a new project using `dotnet new` and initialize a Sql Connection to the server? This way we can eliminate the changes that Visual Studio pulled in for your project.
The `dotnet` CLI tool will help create and run a new project without any dependencies on VS. 

It's only a recommendation to isolate the Sql Server connectivity problem from the project setup problem. I will let you decide your path for investigating this :) 

Let me know when you have more results.

**Comment by MontyGvMC** [comment] 2016-11-07 09:54
@saurabh500 
Managed to get my setup running. The problem with the xml file was a problem in my configuration file *grml*

Here is the information for the new error ("A connection was successfully established with the server, but then an error occurred during the pre-login handshake.") as requested:

Setup:
Client runs on my fully updated Win7 development machine (started locally from Visual Studio 2015)
The database is running on a fully updated Windows Server 2008 R2 with a fully updated SQL Server 2008 R2.
The project.json (for package versions) is pasted below.

The stacktrace as copied from VS2015 to the clipboard

`System.Data.SqlClient.SqlException was unhandled by user code
  Class=20
  HResult=-2146232060
  LineNumber=0
  Message=A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - Der Wartevorgang wurde abgebrochen.)
  Number=258
  Server=myserver
  Source=Core .Net SqlClient Data Provider
  State=0
  StackTrace:
       at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
       at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
       at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
       at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
       at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
       at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
       at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
       at lambda_method(Closure , QueryContext )
       at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
       at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
       at MediaServer.Controllers.StatisticsController.Get()
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: 
       HResult=-2147467259
       Message=Der Wartevorgang wurde abgebrochen
       NativeErrorCode=258
       InnerException: 
`

The project.json

`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Swashbuckle": "6.0.0-beta902",
    "NLog.Extensions.Logging": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1"

  },

  "runtimes": {
    "win7-x64": {},
    "win10-x64": {},
    "ubuntu.14.04-x64": {}
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config",
      "nlog.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

d

**Comment by MontyGvMC** [comment] 2016-11-07 10:57
Changed the TSL 1.2 registry key DisabledByDefault 0x00000001 for Client only and Client and Server.

Still no connection.

Anything I should check on the Ubuntu machine? 

Thank you for your patience and support.

**Comment by halter73** [comment] 2016-11-07 19:35
I find it interesting that the the exception is being thrown from `System.Net.Dns.HostResolutionEndHelper` given that the connection string is specified by IP ("Server=xxx.xxx.xxx.xxx;Database=DatabaseName;user id=*****;password=*****").

@saurabh500 Why do you think it's a TLS issue?

**Comment by saurabh500** [comment] 2016-11-07 22:05
@MontyGvMC  
I see two different errors in this case

1. 

>System.Data.SqlClient.SqlException was unhandled by user code Class=20 HResult=-2146232060 LineNumber=0 Message=A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - Der Wartevorgang wurde abgebrochen.) Number=258 

You mentioned that you get this error while trying to connect from Windows 7 machine. Is that right?

2.

> Connection id "0HL06TURUPCSV": An unhandled exception was thrown by the application. System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address at 

This seems to be the error message from Ubuntu. 

In case of error 1, there is a TCP timeout in play here. (error 258) 
Do you have any other clients/apps installed on the same Windows machine which can successfully connect? e.g. SSMS / or can you write code in .Net framework using SqlConnection to verify this?

In case of error 2, the error message indicates that the client is not able to find a route to your Sql Server. If your server is running on port 1433 can you use netcat to verify if a TCP connection can be established ? 
`netcat -v -z sqlserverHost 1433`

**Comment by saurabh500** [comment] 2016-11-07 22:33
I have a setup where I have my server on the domain joint machine. 

When I try to connect from Ubuntu to Sql Server on Windows Server 2008 R2, I got the same error as you received.

I changed my Sql Server hostname from `hostname` to `hostname.domain.company.com` and the sql server could then be resolved.

I verified this using `netcat -v -z hostname 1433` 
`The error I received was `netcat: getaddrinfo: Name or service not known`

Then I tried `netcat -v -z hostname.domain.company.com 1433` 
I received a success `Connection to hostname.domain.company.com 1433 port [tcp/ms-sql-s] succeeded!`

**Comment by MontyGvMC** [comment] 2016-11-08 10:47
@saurabh500 
#1: yes, this is from my Win 7 development machine
It actually works from Win 7, this error only occurs on the first try (request). All the following requests are working fine. So this is no problem for me.
No, there are no other things running on it except the database (and the not working deployment of my rest api).

#2: yes, this is from ubuntu.


It's time for me to ask a different question:
is there some recommended setup (windows server, database) for .NET Core?

I have 2 windows server 2008 R2 (one unpatched, one fully patched) and a Ubuntu 14.04 LTS but I don't manage to get a setup up and running to test our development on other places than locally on my machine.

I can't get a connection from Ubuntu to Server 2008 R2.
I can't deploy to or get the app running on Server 2008 R2 (which would get rid of Ubuntu).
It seems I can't use MySQL (so far) with Entity Framework Core (which would get rid of Windows/MSSQL and bring all to one Ubuntu server).
Windows Server 2016 seems to be too experimental for the moment?

Is it worth trying to get all (DB & App) set up on one Windows Server 2012? Any experiences if that (or any other setup) will work?

**Comment by saurabh500** [comment] 2016-11-08 15:55
@MontyGvMC The scenario you are trying, i.e. a .Net core app on Ubuntu 14.04 LTS connecting to Sql Server 2008 on Windows Server 2008 R2 is a valid scenario.
Connectivity from .Net core to any supported SQL server on a supported Windows OS is a valid scenario.

You can get your DB and app running on Windows Server 2012 as well. 
I have tried both scenarios that you have mentioned, a .Net core app on Ubuntu, connecting to Sql server 2008 on Windows Server 2008 
App on .Net core Ubuntu connnecting to Sql Server 2008 R2 on Windows server 2012 R2
App and server on Windows Server 2012 R2. 

The pre-req for connecting to Sql server from Ubuntu is that the Sql server should have TLS 1.2 enabled.

I still think that you should diagnose the network connectivity issue from Ubuntu to Sql server on Windows. Based on the error message. The error message that you are receiving, hints at the server host not being reachable from the Ubunut Client.

Can you provide the results from the `netcat` tool ?

**Comment by MontyGvMC** [comment] 2016-11-10 08:38
tried netcat -v -z ip port (I am not sure if we have server/domain names in our internal development network)

results:
`me@ubuntu:~$ netcat -v -z 192.168.101.42 1433
Connection to 192.168.101.42 1433 port [tcp/ms-sql-s] succeeded!`

Is that what you meant with the results from the netcat tool?

**Comment by saurabh500** [comment] 2016-11-10 15:24
The `netcat` tool suggests that there is a TCP connection path from the client to server. This is good. 

Can you also share your connection string without the sensitive information like credentials?

**Comment by MontyGvMC** [comment] 2016-11-10 19:02
Well, here I had a list with all my approaches
https://github.com/aspnet/EntityFramework/issues/6830

Well, versions I tried so far:
Data Source=[IP],1433;Database=DatabaseName;user id=usr;password=pwd;
Data Source=[IP],1433;Database=DatabaseName;user id=usr;password=pwd;Encryption=False;
Data Source=[IP],1433;Initial Catalog=DatabaseName;user id=usr;password=pwd;
Data Source=[IP],1433;Initial Catalog=DatabaseName;user id=usr;password=pwd;Encryption=False;

Data Source=[IP];Database=DatabaseName;user id=usr;password=pwd;
Data Source=[IP];Database=DatabaseName;user id=usr;password=pwd;Encryption=False;
Data Source=[IP];Initial Catalog=DatabaseName;user id=usr;password=pwd;
Data Source=[IP];Initial Catalog=DatabaseName;user id=usr;password=pwd;Encryption=False;

Server=[IP],1433;Database=DatabaseName;user id=usr;password=pwd;
Server=[IP],1433;Database=DatabaseName;user id=usr;password=pwd;Encryption=False;
Server=[IP],1433;Initial Catalog=DatabaseName;user id=usr;password=pwd;
Server=[IP],1433;Initial Catalog=DatabaseName;user id=usr;password=pwd;Encryption=False;

Server=[IP];Database=DatabaseName;user id=usr;password=pwd;
Server=[IP];Database=DatabaseName;user id=usr;password=pwd;Encryption=False;
Server=[IP];Initial Catalog=DatabaseName;user id=usr;password=pwd;
Server=[IP];Initial Catalog=DatabaseName;user id=usr;password=pwd;Encryption=False;

Currently I am at:
Server=IP;Database=DbName;user id=dbu;password=dbpw;

**Comment by saurabh500** [comment] 2016-11-10 20:03
@CIPop @stephentoub Can you folks help with this issue or direct us to someone from Xplat networking? 

My understanding is that SqlClient is failing to open a TCP connection

Connection id "0HL06TURUPCSV": An unhandled exception was thrown by the application. System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. **(No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) at** System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult) at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult) 


Any ideas what could be causing the part in **bold**

Looks like the TCP connections to the server can be established using `netcat` 
The client is using the IP address to connect to the server. 

I have tried similar scenario using Ubuntu and MacOS and it works.

**Comment by CIPop** [comment] 2016-11-10 23:14
> I have tried similar scenario using .Net core 1.0 from Ubuntu and MacOS to SqlServer and it works.

@saurabh500 I'm not sure I understand the issue. Please summarize what works and what doesn't. 
Also, does it work if you use System.Net.Sockets instead of SqlClient?

**Comment by saurabh500** [comment] 2016-11-10 23:36
@CIPop We haven't tried the an isolated System.Net.Sockets sample. 
Do you have any sample code for opening a Tcp Connection from a Client to server that @MontyGvMC could try for us? If not, I could create one and ask @MontyGvMC to try it.

The issue is that when SqlClient on Ubuntu tries to connect to Sql Server on Windows, we get an error during DNS resolution. 
@MontyGvMC is providing the IP address of the SqlServer to the SqlClient. The `netcat` results for opening the TCP connection to Sql Server port is succeeding.

Do you know the possible scenarios in which the above errors can be thrown while resolving the DNS?

**Comment by CIPop** [comment] 2016-11-11 00:10
> Do you know the possible scenarios in which the above errors can be thrown while resolving the DNS?

@stephentoub may know more about the non-Windows implementation for Dns. (Sounds like "host not found" to me).

**Comment by MontyGvMC** [comment] 2016-11-11 11:37
I am experiencing a strange behavior of the Database connections (for the first time today).

Is there a way to log (within startup.cs or on some controller)
the actual used connection settings (aka the connection string) 
and not the value from the config file?

` services.AddDbContext<MyDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));`

Are connection strings somewhere stored outside of the appsettings.json (in some autogenerated config file or somewhere else)?

**Comment by MontyGvMC** [comment] 2016-11-11 12:30
@saurabh500 

Oh dear, the connection from Ubuntu to the fully patched Windows Server 2008 R2 works now.

And the solution in short: was a auto-generated and hardcoded connection string in the auto generated DbContext class.

A bit more detail:
It seems the last time I scaffolded the db context (database first approach) i missed replacing the OnConfigure method with the Constructor taking the DbContextOptions.
Therefore it ignored the connection string from the appsettings.json (and appsettings.Development.json i created today to test a local database).

The new strange behaviour I mentioned in the previous comment was that I had
appsettings.json connection string pointing to the IP ending with .42
appsettings.Development.json connection string pointing to a local db
but the database which got populated was pointed from the hardcoded DbContext connection string (ending with .10 which is the old 2008 R2 without all the new patches and updates).

This was the reason why it never worked.
Throwing DNS erros when using IP addresses made me curious too. The solution for that is that the hardcoded connection string did not use the ip address but: 
`Server=ourDBserver;Database=ourDB;`

Adding hard coded connection strings in auto-generated files seems to be dangerous. *smile*

Without it I published to Ubuntu and tada, it works.

Thank you all for the patience.
TSL registry settings and updates work to get the connection running.

**Comment by saurabh500** [comment] 2016-11-11 17:19
Thanks for the confirmation @MontyGvMC

**Closed by saurabh500** 2016-11-11 17:19 UTC
Labels: area-System.Data.SqlClient

**Comment by CIPop** [comment] 2016-11-11 17:54
Glad that this got sorted out! Thanks @MontyGvMC !

**Comment by bmart102** [comment] 2019-12-03 19:10
I had a similar issue and I was able to fix just by adding "Connect Timeout=60" in the connection string.
