### ISSUE TITLE
S.T.J.JsonSerializer does not serialize value tuples

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/corefx#36240] opened 2019-03-22 18:26 UTC
Using latest nightly build of .NET Core 3.0 and write:

```c#
string s = JsonSerializer.ToString((a: 1, b: 2));
Console.WriteLine(s);
```
You will get a string representing an empty object `{}`. I think the right behavior is to have `{ "Item1": 1, "Item2": 2 }` and I expect it should also work for deserialization.

**Comment by YohDeadfall** [comment] 2019-03-29 08:00
@ahsonkhan @karelz I would like to take it.

**Comment by karelz** [comment] 2019-03-29 11:04
Great @YohDeadfall. I sent you collaborator invite to CoreFX repo. We recommend to swtich the repo to Not Watching, otherwise you will receive 500+ notifications per day (may be a bit overwhelming). The Not Watching setting will send you notifications for issues where you are mentioned, you are assigned or where you explicitly subscribed.
Once you accept the collaborator invite, please ping me, I will assign the issue to you then (GH limitation, assigning to myself for now).

**Comment by YohDeadfall** [comment] 2019-03-29 14:46
By the way, can you replace "value tuples" in the title by "structures"?

**Comment by karelz** [comment] 2019-03-29 15:03
Well, the original issue was for "value tuples". Do you mean it could / should be generalized? If yes, I let @ahsonkhan comment on that.

**Comment by mazhou-msft** [comment] 2019-03-29 17:06
It does work for some of the primitive structures such as `DateTime`, however it does not work for `DateTimeOffset`. They could be different issues to track.

**Comment by YohDeadfall** [comment] 2019-03-29 17:23
@mazhou-msft `DateTimeOffset` is a different kind of structures which should be serialized as a single value. Such kind of types should be handled by value converters. I'm talking about value types which have serializable public properties and fields.

@karelz Take a look at the expected output. There are `Item1` and `Item2` properties which corresponds to fields of `ValueTuple<,>`. So the issue isn't about serialization of value tuples with their field aliases which are `a` and `b` in the example.

**Comment by mazhou-msft** [comment] 2019-03-29 17:38
Make sense. 

For the expected result, I would say `a` and `b` may be more natural, but it makes things harder (for those runtime `TupleElementName` checks etc.) back one step, `Item1` and `Item2` are still acceptable results as they are identitical to what Json.NET returns for value tuples.

**Comment by steveharter** [comment] 2019-03-29 18:00
`DateTimeOffset` support was just added.

There is no converter yet for `ValueTuple`, so using this issue to track that.

**Comment by mazhou-msft** [comment] 2019-03-29 20:02
Thanks for the info, sounds good.

**Comment by ahsonkhan** [comment] 2019-04-01 21:10
Is this issue about providing struct support (i.e. value types), or is it about supporting **ValueTuples** specifically (which just happen to be a value type)?

**Comment by ahsonkhan** [comment] 2019-05-20 01:29
Re-opening since it isn't fully fixed yet.

**Comment by buyaa-n** [comment] 2019-05-27 19:03
Adding a test case:
```csharp
    [Fact]
    public void SerializeValueTuple()
    {
        ValueTuple<int, int, string> t = ValueTuple.Create(1, 2, "string");
        string json = JsonSerializer.ToString(t);
        Assert.Equal(@"{""Item1"": 1,""Item2"": 2,""Item3"": ""string""}", json);
        ValueTuple<int, int, string> t2 = JsonSerializer.Parse<ValueTuple<int, int, string>>(json);

        Assert.Equal(1, t2.Item1);
        Assert.Equal(2, t2.Item2);
        Assert.Equal("string", t2.Item3);
        }
```

**Comment by pranavkm** [comment] 2019-05-28 22:46
I tried this out earlier today using `3.0.0-preview6-27728-02` and things are essentially the same as the original reported issue. Could we consider throwing if the serializer encounters a `ValueTuple` for 3.0 if there isn't enough runway to support the feature in this release? The experience is a bit frustrating since it seems like serialization succeeded, but all you have is empty objects.

**Comment by YohDeadfall** [comment] 2019-05-29 19:06
`ValueTuple` has fields, not properties, and the current implementation doesn't support them. There is #36505 to track progress (am working on it and will try to open a PR on this weekend).

**Comment by karelz** [comment] 2019-05-29 23:21
Duplicate of #36505

**Closed by karelz** 2019-05-29 23:21 UTC
Labels: area-System.Text.Json, enhancement

**Comment by ahsonkhan** [comment] 2020-01-09 20:59
I mention a workaround for `ValueTuples` (up to 3) based on custom converters if folks need it.
https://github.com/dotnet/runtime/issues/1519#issuecomment-572751931
