### ISSUE TITLE
HttpConnection.cs::FillAsync() - "System.IO.IOException": The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by naftasantos** [dotnet/corefx#34600] opened 2019-01-15 13:02 UTC
I am using a library developed for .NET Framework inside my dotnetcore2.1 application. This library uses System.Net classes to make Http requests.

When using this library with a .NET Framework console app, everything works fine. However, when moving to dotnetcore2.1 an exception is raised inside FillAsync method of the HttpConnection class. At first I believed that this issue was related to #31423 but, after some analysis, I realized that actually no real response was received from the server (different from what @Jeff-Lewis experienced).

Here is the Stack Trace for this exception:

```
"System.IO.IOException"
The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```

The only part of the code that I found inside this method that raises this exception is the below snippet:

```c#
int bytesRead = await _stream.ReadAsync(new Memory<byte>(_readBuffer, _readLength, _readBuffer.Length - _readLength)).ConfigureAwait(false);

if (NetEventSource.IsEnabled) Trace($"Received {bytesRead} bytes.");
if (bytesRead == 0)
{
  throw new IOException(SR.net_http_invalid_response);
}
```

Which indicates that the server is returning no data at all. So I decided to analyze the network flow using Wireshark and here's what I found (address 51 is my system and 35 is the server):

**.NET**
![image](https://user-images.githubusercontent.com/1520189/51180233-fed10c80-18ae-11e9-8b4e-70c7b5d4903b.png)

The fourth line is the client sending the header after the handshake, followed by the fifth line which is the server returning an ACK and then, finally, the sixth line is the actual POST of the data.

**.NET Core**
![image](https://user-images.githubusercontent.com/1520189/51180643-06dd7c00-18b0-11e9-8b88-c00aee99048a.png)

Again, the fourth line is the client sending the header however, this time, after the ACK is returned from the server, the server sends a FIN packet (due to the difference in the No. between this and the previous packet it seems that the server waited some time), which starts the close handshake (removed from the screenshot). This explains the `if (bytesRead == 0)` part. I'm guessing there is something wrong with the header in dotnetcore, or the implementation is not sending the POST after the ACK triggering a timeout in the server, but I cannot really be sure.

The HTTP header difference is as follows:

**.NET Framework**

```
POST /wsman HTTP/1.1
Content-Type: application/soap+xml;charset=UTF-8
Host: <ip>:<port>
Content-Length: 959
Expect: 100-continue
Connection: Keep-Alive

```

**.NET Core**

```
POST /wsman HTTP/1.1
Connection: Keep-Alive
Content-Type: application/soap+xml; charset=UTF-8
Content-Length: 959
Host: <ip>:<port>

```

And this is the ACK response difference from the server:

**.NET**
![image](https://user-images.githubusercontent.com/1520189/51181308-fcbc7d00-18b1-11e9-84b7-9d38070c1fdb.png)

**.NET Core**
![image](https://user-images.githubusercontent.com/1520189/51181335-0cd45c80-18b2-11e9-91bd-f2a5206b33f5.png)

**Constraints:**

1. I cannot change the server code and/or environment.

Is this info enough for understanding the problem, or do you need something else?

**Comment by naftasantos** [comment] 2019-01-15 16:10
Also, here is the PerfView of the Microsoft-System-Net-Http traces: [HttpConnectionPerfView.xlsx](https://github.com/dotnet/corefx/files/2760414/HttpConnectionPerfView.xlsx)

**Comment by davidsh** [comment] 2019-01-15 17:06
What version of .NET Core 2.1 are you using?  Please show "dotnet --info" output.

>At first I believed that this issue was related to #31423 but, after some analysis, I realized that actually no real response was received from the server (different from what @Jeff-Lewis experienced).

I still suspect your problem is related to #31423.  In order to rule that out, please install .NET Core [2.1.7](https://dotnet.microsoft.com/download/dotnet-core/2.1) which contains the fix for #31423.

**Comment by naftasantos** [comment] 2019-01-15 17:53
Here is the info. My SDK is 2.1.5, but the host is 2.1.7. I'll try to install the SDK 2.1.7.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davidsh** [comment] 2019-01-15 18:35
>.NET Core runtimes installed:
Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Although you didn't have the updated SDK, you were already running against 2.1.7 runtime.

>I updated to the latest installer available here (2.2) and the problem still occurs. Here is my current info:

That would install the 2.2 runtime as well.  But since your application is probably still targeting 2.1, it wouldn't use the 2.2 runtime.

Looking at your PerfView traces, it shows that you did receive an HTTP response from the server.  But processing that response resulted in an exception being thrown:

```
ThreadID="4.076"   thisOrContextObject="HttpClient#33675143"   memberName="HandleFinishSendAsyncError"   message="System.Net.Http.HttpRequestException: An error occurred while   sending the request. ---> System.IO.IOException: The server returned an   invalid or unrecognized response. at   System.Net.Http.HttpConnection.FillAsync() at
 System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean   foldedHeadersAllowed) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage   request, CancellationToken cancellationToken) --- End of inner exception   stack trace --- at   System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request,   CancellationToken cancellationToken) at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage   request, Uri authUri, ICredentials credentials, Boolean isProxyAuth,   HttpConnection connection, HttpConnectionPool connectionPool,   CancellationToken cancellationToken) at   System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection   connection, HttpRequestMessage request, Boolean doRequestAuth,   CancellationToken cancellationToken) at   System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage   request, Boolean doRequestAuth, CancellationToken cancellationToken) at   System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage   request, Uri authUri, ICredentials credentials, Boolean preAuthenticate,   Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken   cancellationToken) at   System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request,   CancellationToken cancellationToken) at   System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask,   HttpRequestMessage request, CancellationTokenSource cts, Boolean   disposeCts)"   ActivityID="00000008-0001-0000-7832-0000ffdcd7b5"
--
```

I suspect that something in the HTTP response headers is causing the parser to fail and that is why an exception is being thrown.

**Comment by davidsh** [comment] 2019-01-15 18:39
@geoffkizer

**Comment by naftasantos** [comment] 2019-01-15 19:24
When reviewing the .NET Framework communication, the first response (there are several others) that arrive is a 401 with the following content:

```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Digest realm="Digest:<32 numbers removed>", nonce="<32 characters removed>",stale="false",qop="auth"
Content-Type: text/html
Server: Intel(R) Active Management Technology 11.8.60.3561
Content-Length: 690
Connection: close

<html content removed>
```

I was unable to see the response header when analyzing the .NET Core communication.

**Comment by davidsh** [comment] 2019-01-16 18:47
>Great. Please let me know if there is something else that I can provide.

We are not going to be able to diagnose further unless we can either reproduce this ourselves or we can look at the detailed WireShark traces. 

For a repro, it seems the "server" is an embedded system (Intel(R) Active Management Technology) using Digest auth.  That might be difficult for us to repro without the hardware.  It's possible we have a bug with parsing Digest auth response headers.

You can send us WireShark traces so we can look at all the details.  But if they contain sensitive information you should not post them here. Instead, you would need to send them to us via our Microsoft Product Support channel.  So, that would require you to open up a support case.

**Comment by geoffkizer** [comment] 2019-01-16 19:50
We're throwing an exception because the server is closing the connection (sending a FIN) without sending a response. The interesting question is, why is the server doing this?

**Comment by naftasantos** [comment] 2019-01-16 20:11
> You can send us WireShark traces so we can look at all the details. But if they contain sensitive information you should not post them here. Instead, you would need to send them to us via our Microsoft Product Support channel. So, that would require you to open up a support case.

Will do that, thank you.

> We're throwing an exception because the server is closing the connection (sending a FIN) without sending a response. The interesting question is, why is the server doing this?

From what I understood about this flow, what is happening is the following:

1. The client sends the HTTP header through TCP;
2. The server responds with ACK and waits for the POST with the data mentioned by the header;
3. No data is sent by the client;
4. The connection times out in the server then a FIN packet is sent.

I realized this because the FIN packet No. is 541, while the ACK is 169, which indicates that a long time (for the computer) has passed between the two packets. Whilst in the .NET stack, the POST packet (966) occurs right after the ACK (957) from the server.

**Comment by karelz** [comment] 2019-01-16 21:00
@naftasantos if you need to share sensitive files, you can use [VS Developer Community](https://developercommunity.visualstudio.com/spaces/61/index.html) (.NET). There is option to attach files privately (just for MS employees to see).
If you do that just link your report from here, so that we know where to find it. Thanks!

**Comment by naftasantos** [comment] 2019-01-17 12:15
Hi @karelz, I tried to create the issue there, but I found no option for private upload (the upload seemed public, so I removed the issue):

![image](https://user-images.githubusercontent.com/1520189/51318161-b21d3b00-1a40-11e9-9b2b-6893f1d18dc7.png)
![image](https://user-images.githubusercontent.com/1520189/51318186-c19c8400-1a40-11e9-87e1-c9e15fb5c45f.png)

None of these screens showed a private upload option.

**Comment by karelz** [comment] 2019-01-17 15:50
Did you try it on a reply to the issue?
I have option to select who will view my replies - public vs. customer & MS employees. I expect you will see something similar from your end.

**Comment by naftasantos** [comment] 2019-01-17 15:58
Great, thank you!

[Here](https://developercommunity.visualstudio.com/content/problem/430064/httpconnectioncsfillasync-systemioioexception-the-1.html) is the issue.

I'm also working on a step-by-step on how to create the environment for testing (it's not that hard).

**Comment by naftasantos** [comment] 2019-01-17 16:12
# How to reproduce the problem

## What you'll need

1. A system with Intel vPro processor;
2. Enable Intel AMT in the system (this will be the server): https://www.intel.com.br/content/www/br/pt/support/articles/000026592/technologies.html
3. Download Intel's SDK: https://software.intel.com/en-us/amt-sdk/download

## How to reproduce
When you unzip the SDK, there will be a folder with the compiled .NET libraries under Bin.

Create a .NET Core 2.1 console app and add the HLAPI.dll as reference.

Paste the sample code below:

```c#
using Intel.Manageability;
using System;

  class Program
  {
    static void Main(string[] args)
    {
      ConnectionInfoEX connectionInfo = new ConnectionInfoEX(
        "IP Address",
        "admin", // user
        "password",
        false,
        string.Empty,
        ConnectionInfoEX.AuthMethod.Digest,
        null,
        null,
        null);

      IAMTInstance AmtInstance = AMTInstanceFactory.CreateEX(connectionInfo);

      Console.WriteLine($"{AmtInstance.StorageAdmin.Statistics.BytesCapacity}");
      Console.ReadKey();
    }
  }
```

In the systems that I tested, the exception will occur at the line 

```c#
      IAMTInstance AmtInstance = AMTInstanceFactory.CreateEX(connectionInfo);
```

Hope this helps.

**Comment by davidsh** [comment] 2019-01-17 17:57
@naftasantos Thank you for uploading the WireShark traces.  I took a look at them.

The .NET Framework traces look normal with POST requests going to the server.  The server requires HTTP Digest authentication.  So, it sends back 401 and then the client retries and attaches the credentials and 200 is returned.  Those traces look normal.

The .NET Core traces are not normal. It seems that the client is only sending the first POST request and includes a 'Content-Length: 959' but then never sends any body.  The server waits about 15 seconds and then sends back a FIN.  Presumably, the server has a timeout of some sort and then closes the connection if the promised request body (which is a SOAP message) doesn't show up.

Could you try an experiment with your code?  Can you add the following line to your client application?  Add it before it does any networking operations.

```c#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

This will cause the older HTTP stack (WinHttpHandler) to be used instead of the newer (SocketsHttpHandler) stack. I'd like to see if the problems happens or not.

In the meantime, we'll try to get an Intel vPro machine set up to mimic the repro you have.

**Comment by davidsh** [comment] 2019-01-17 18:08
@naftasantos 

I have another question about your repro application.

>Create a .NET Core 2.1 console app and add the HLAPI.dll as reference.

According to the Intel web site, the AMT SDK doesn't say anything about .NET Core support.  It only talks about .NET Framework support.  

Ref: https://software.intel.com/en-us/amt-sdk/documentation#release-notes

```
Latest Release Notes
New features included with the Intel AMT SDK, release 12.0:

Files: The .MOF and XSL files in the \DOCS\WS-Management directory and the class reference in the documentation are updated to version 12.0.0.1065.
.NET Version: Samples and code libraries have been upgraded from .NET version 3.5 to version 4.6.1.
```

So, is this a supported scenario to use the HLAPI.DLL in this manner?

**Comment by naftasantos** [comment] 2019-01-17 18:21
I believe that this is a scenario where the library was not really tested yet, so there might be a problem with that as well.

**Comment by naftasantos** [comment] 2019-01-17 18:40
> Could you try an experiment with your code? Can you add the following line to your client application? Add it before it does any networking operations.

It also crashes, the exception is similar:
```
Unhandled Exception: Intel.Manageability.Exceptions.ManageabilityException: UnknownError ---> Intel.Management.Wsman.WsmanConnectionException: UnknownError ---> System.Net.WebException: An error occurred while sending the request. Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server returned an invalid or unrecognized response'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server returned an invalid or unrecognized response'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Intel.Management.Wsman.WsmanConnection.SendWebRequest(String msgId, XmlDocument reqDoc, IManagedReference refObj, IManagedInstance input)
   --- End of inner exception stack trace ---
   at Intel.Management.Wsman.WsmanConnection.SendWebRequest(String msgId, XmlDocument reqDoc, IManagedReference refObj, IManagedInstance input)
   at Intel.Management.Wsman.WsmanConnection.SubmitRequest(XmlDocument reqDoc, IManagedReference refObj, IManagedInstance input)
   at Intel.Management.Wsman.ManagedReference.Get()
   at Intel.Manageability.Impl.AMTInstanceManager.GetVersionWSMan()
   at Intel.Manageability.Impl.AMTInstanceManager.SetVersionInfo()
   at Intel.Manageability.Impl.AMTInstanceManager.InitAMTInstanceMNG(ConnectionInfoEX infoEx, Boolean isHBP, ConnectionInfo info)
   at Intel.Manageability.Impl.AMTInstanceManager..ctor(ConnectionInfoEX info, Boolean isHBP)
   at Intel.Manageability.AMTInstanceFactory.CreateEX(ConnectionInfoEX info)
   --- End of inner exception stack trace ---
   at Intel.Manageability.AMTInstanceFactory.CreateEX(ConnectionInfoEX info)
   at AMTTest.Program.Main(String[] args) in c:\Temp\AMTTest\Program.cs:line 23

```

**Comment by davidsh** [comment] 2019-01-17 18:47
>It also crashes, the exception is similar:

Since it fails with both HTTP stacks on .NET Core, this tells me that the AMT SDK isn't really supported on .NET Core.  You might want to follow with Intel to see if they are thinking of officially adding .NET Core support to this SDK.

**Comment by naftasantos** [comment] 2019-01-17 18:55
Will do that, thank you ;)

**Comment by davidsh** [comment] 2019-01-17 22:19
>Will do that, thank you ;)

In the meantime, since Intel AMT SDK does not officially support .NET Core, the scenario you have (manually copying the HLAPI.DLL and referencing it) is not actionable by us to resolve your issue.

I'll close this issue for now.  If you get new information, please let us know.  Thanks!

**Closed by davidsh** 2019-01-17 22:19 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
