### ISSUE TITLE
IPGlobalProperties.GetActiveTcpListeners() throws System.OverflowException on WSL

### ISSUE THREAD

**Issue by iftahbe** [dotnet/corefx#30909] opened 2018-07-09 12:11 UTC
Running on Ubuntu WSL (Windows Subsystem for Linux):
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
With dotnet (installed via apt-get install dotnet-sdk-2.1):
```
# dotnet --version
2.1.301
```
When I run the following console app:
```
using System;
using System.Net.NetworkInformation;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            var ipProperties = IPGlobalProperties.GetIPGlobalProperties();
            var activeTcpListeners = ipProperties.GetActiveTcpListeners();
        }
    }
}
```

I get an exception:
```
System.OverflowException: Array dimensions exceeded supported range.
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile)
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpListeners()
   at ConsoleApp3.Program.Main(String[] args) in /home/iftah/test/Program.cs:line 13
```

**Comment by stephentoub** [comment] 2018-07-09 13:33
This appears to be an issue with WSL: both `/proc/net/tcp` and `/proc/net/tcp6` are empty.  We should have a better failure mode from `GetActiveTcpListeners` in that case, but as `GetActiveTcpListeners` depends on those for the data, if the data isn't available, it probably still needs to throw, but just throw something more informative, like `NetworkInformationException`.

**Comment by wfurt** [comment] 2019-08-20 08:25
we should check if this is still issue.

**Comment by ManickaP** [comment] 2019-09-05 14:36
I'll look into it.

**Comment by ManickaP** [comment] 2019-09-13 11:31
This does not happen on WSL2, mentioned files are not empty anymore and contain at least the expected header (e.g.: [`// First line is header in each file.`](https://github.com/dotnet/corefx/blob/fdb13cc7ee134a17fb36a038b57795b7e2225274/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L46)).

I was able to reproduce the issue on WSL1 and the stated method is not the only one having problems.

I'll fix this since the fix is pretty easy.

**Comment by ManickaP** [comment] 2019-09-13 14:49
@stephentoub You suggested throwing [`NetworkInformationException`](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/NetworkInformation/NetworkInformationException.cs) but it inherits from `Win32Exception` so it might not be the best candidate (as it is right now).

I see 3 options right now:
- split the `NetworkInformationException` into Win and Linux implementations
- create a new, completely different exception
- use another existing exception, e.g. `PlatformNotSupportedException` which is already used for when the file doesn't exist

**Comment by stephentoub** [comment] 2019-09-13 14:56
> it inherits from Win32Exception

We've had to accept the fact that "Win32Exception" is simply poorly named, and it's really "OSException".  It works fine on Unix, and is thrown in many other places.  It'd be a breaking change to change NetworkInformationException's base type, and NetworkInformationException similarly works fine on Unix.

**Comment by ManickaP** [comment] 2019-09-20 10:32
Won't fix as this is only observed only on WSL1 and nowhere else.

**Closed by ManickaP** 2019-09-20 10:32 UTC
Labels: area-System.Net, bug, os-windows-wsl, up-for-grabs
