### ISSUE TITLE
CancellationTokenSource Cannot Cancel ReceiveAsync via SocketTaskExtensions

### ISSUE THREAD

**Issue by garethwarry** [dotnet/corefx#31415] opened 2018-07-27 05:58 UTC
**System**
.NET Core version: netcoreapp2.1
OS version: Windows 10 Build 1803

**Summary**
A first task, the main task, spawns a second task and passes a CancellationToken from the main tasks's CancellationTokenSource. The second tasks enters a loop and passes the CancellationToken to ReceiveAsync (as shown below). The first task then calls Cancel on the CancellationTokenSource. This does not cancel the ReceiveAsync Socket method. Even passing a token from the same context doesn't work.

**Expected Behavior**
The cancellation token parameter works.

**Actual Behavior**
Cannot get the cancellation token to cancel the ReceiveAsync task.

**Example**
```csharp
namespace SocketBug
{
    using System;
    using System.Net;
    using System.Net.Sockets;
    using System.Threading;
    using System.Threading.Tasks;

    class Program
    {
        static void Main(string[] args)
        {
            // Start the server socket
            var sock = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            sock.Bind(new IPEndPoint(IPAddress.Any, 9958));
            sock.Listen(100);

            // Accept a client and run tests
            Task.Run(async () => 
            {
                // Accept the client
                var cancellation = new CancellationTokenSource(TimeSpan.FromSeconds(5));
                var clientSock = await sock.AcceptAsync();
                var buffer = new Memory<byte>(new byte[2048]);
                while (clientSock.Connected && !cancellation.IsCancellationRequested)
                {
                    try
                    {
                        // Receive data while connected and not cancelled
                        var bytes = await clientSock.ReceiveAsync(buffer, SocketFlags.None, cancellation.Token);
                        Console.WriteLine("Received {0} bytes", bytes);
                    }
                    catch (Exception e)
                    {
                        // Hoping cancellation was called.
                        Console.WriteLine(e);
                        break;
                    }
                }

                Console.WriteLine("Client task is terminating");
            });

            Console.ReadKey(true);
        }
    }
}
```
Perhaps it's something I'm doing wrong?
Thanks!

**Comment by garethwarry** [comment] 2018-07-27 06:09
Second example: This also fails.
```
var task = clientSock.ReceiveAsync(buffer, SocketFlags.None, cancellation.Token);
cancellation.CancelAfter(TimeSpan.FromSeconds(5));
var bytes = await task;
```

**Comment by davidsh** [comment] 2018-07-27 15:43
Duplicate of #24430

**Closed by davidsh** 2018-07-27 15:43 UTC
Labels: area-System.Net.Sockets
