### ISSUE TITLE
[Uri] System.Uri escaped result is incorrect

### ISSUE THREAD

**Issue by experdot** [dotnet/corefx#38714] opened 2019-06-20 09:57 UTC
### Overview

`System.Uri` escapes the constructor parameter by default. If the raw string contains **%20** and **Unicode symbols** together, the escaped result is incorrect.

### Steps
1. Execute `Console.WriteLine(new Uri("C:\\%20hello world中文字符.txt", UriKind.Absolute).AbsolutePath);`
2. The expected value is `C:/%2520hello%20world%E4%B8%AD%E6%96%87%E5%AD%97%E7%AC%A6.txt`, 
3. The actual value is `C:/%20hello%20world%E4%B8%AD%E6%96%87%E5%AD%97%E7%AC%A6.txt`
4. The "%20" between "C:/" and "hello" should be escaped.

**Comment by Gnbrkm41** [comment] 2019-06-20 11:50
Sounds like a duplicate of https://github.com/dotnet/corefx/issues/32301?

**Comment by Gnbrkm41** [comment] 2019-06-20 11:51
Also, could you tell which runtime ( & version) you're using?

**Comment by davidsh** [comment] 2019-06-20 14:16
@wfurt

**Comment by davidsh** [comment] 2019-06-20 14:17
@wtgodbe

**Comment by experdot** [comment] 2019-06-20 16:43
> Sounds like a duplicate of #32301?

Yes, it's duplicate. I reproduced it in the following platforns.
- .NET Framwork 4.7.2
- .NET Core 2.1
- .NET Core 3.0 Preview 6

**Comment by davidsh** [comment] 2019-06-20 16:56
Duplicate of #32301

**Closed** 2019-06-20 16:56 UTC
Labels: area-System.Net
