### ISSUE TITLE
CurlHandler exception on resource constraint environment

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/corefx#17010] opened 2017-03-11 14:21 UTC
The following exception happens on .NET Core runtime 1.1.1 on Ubuntu 14.04, when resources are constrained.

```
Uncatched exception in BroadcasterJob: System.IO.IOException: The read operation failed, see inner exception. ---> System.ObjectDisposedException: Cannot access a closed Stream.
         at System.IO.__Error.StreamIsClosed()
         at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
         at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
I am using `CopyToAsync` on a stream from a `WebResponse.GetResponseStream()` to a `MemoryStream`. I imagine something is garbage collected at the wrong time.

The `MemoryStream` at the top of the exception stack does not seems to be the same as the one passed to `CopyToAsync`. I experienced the same problem with simple `Read()`, same stacktrace, on the WebResponse stream.

Another example:

```
System.ObjectDisposedException: Cannot access a closed Stream.
         at System.IO.__Error.StreamIsClosed()
         at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
         at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at System.Net.Http.CurlHandler.CurlResponseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
```

I am investigating it,

**Comment by karelz** [comment] 2017-03-13 16:59
@Priya91 any thoughts?

**Comment by Priya91** [comment] 2017-03-13 21:18
@NicolasDorier Can you please provide a repro..

**Comment by NicolasDorier** [comment] 2017-03-14 02:08
I will try. This come from a customer running the same code as me on the same ubuntu, the only different we spotted is that he is low on memory. This problem is transient. (one call fail, and 3 will succeed)

Will try to repro, but how to repo GC activity?

**Comment by karelz** [comment] 2017-03-14 02:59
You don't repro GC activity. You stress the code path (hit it over and over again). Sometimes you need to set the right conditions (low memory by allocating a lot first).

**Comment by NicolasDorier** [comment] 2017-03-14 03:59
thanks a lot I will try.

**Comment by NicolasDorier** [comment] 2017-03-14 10:33
I did not manage to reproduce on the microsoft docker image. 
A customer of mine have this error. I tried to reproduce with this code:

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using  Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            int i = 0;
            new Thread(() =>
            {
                List<byte[]> bytes = new List<byte[]>();
                while(i < 760430)
                {
                    bytes.Add(new Byte[10000]);
                    i++;
                }
            }).Start();

        new Thread(() =>
                    {
                    new WebHostBuilder()
                    .UseKestrel()
                    .Configure(a => a.Run(async c => 
                    {
                        await c.Response.WriteAsync("Hi!"); 
                        System.Console.WriteLine("hey"); 
                        Thread.Sleep(1000); 
                    }))
                    .Build()
                    .Run();
        }).Start();
            while(true)
            {
                DoRequest().Wait();
                Thread.Sleep(1000);
                System.Console.WriteLine(i);
            }
        }

        private static async Task DoRequest()
        {
            try
            {
                var req = System.Net.HttpWebRequest.Create("http://127.0.0.1:5000/");
                req.Method = "POST";
                var stream = await req.GetRequestStreamAsync().ConfigureAwait(false);
                await stream.WriteAsync(new byte[] { 0 }, 0, 1).ConfigureAwait(false);
                await stream.FlushAsync().ConfigureAwait(false);
                stream.Dispose();
                var webResponse = await req.GetResponseAsync().ConfigureAwait(false);
                MemoryStream ms = new MemoryStream();
                await webResponse.GetResponseStream().CopyToAsync(ms).ConfigureAwait(false);
            }
            catch(Exception ex)
            {
                System.Console.WriteLine(ex);
            }
        }
    }
}
```
To no success...

**Comment by NicolasDorier** [comment] 2017-03-14 10:40
here is a repro:
```
using System;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using  Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
             int i = 0;
            // new Thread(() =>
            // {
            //     List<byte[]> bytes = new List<byte[]>();
            //     while(i < 760430)
            //     {
            //         bytes.Add(new Byte[10000]);
            //         i++;
            //     }
            // }).Start();

        new Thread(() =>
                    {
                    new WebHostBuilder()
                    .UseKestrel()
                    .Configure(a => a.Run(async c => 
                    {
                        await c.Response.WriteAsync(String.Join("-", System.Linq.Enumerable.Range(0, 1024).Select(o => "hey").ToArray())); 
                        System.Console.WriteLine("hey"); 
                        Thread.Sleep(1000); 
                    }))
                    .Build()
                    .Run();
        }).Start();
            while(true)
            {
                DoRequest().Wait();
                Thread.Sleep(1000);
                System.Console.WriteLine(i);
            }
        }

        private static async Task DoRequest()
        {
            try
            {
                var req = System.Net.HttpWebRequest.Create("http://127.0.0.1:5000/");
                req.Method = "POST";
                var stream = await req.GetRequestStreamAsync().ConfigureAwait(false);
                await stream.WriteAsync(new byte[1024 * 1024], 0, 1).ConfigureAwait(false);
                await stream.FlushAsync().ConfigureAwait(false);
                stream.Dispose();
                var webResponse = await req.GetResponseAsync().ConfigureAwait(false);
                MemoryStream ms = new MemoryStream();
                await webResponse.GetResponseStream().CopyToAsync(ms).ConfigureAwait(false);
            }
            catch(Exception ex)
            {
                System.Console.WriteLine(ex);
            }
        }
    }
}
```

Running the latest docker:

```
root@c9f9f65913f7:/# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
root@c9f9f65913f7:/# dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

Running docker image microsoft/dotnet:latest (id 0abf88e1ef29)

**Comment by NicolasDorier** [comment] 2017-03-16 08:31
@Priya91 does the repro works for you ?

**Comment by NicolasDorier** [comment] 2017-03-27 02:27
@karelz @Priya91 please let me know if you could repro. This make my project unadvisable to run in production on Linux environment, so I would do anything for reproducing it better if it does not work on your machine.

**Comment by Priya91** [comment] 2017-03-27 20:25
@NicolasDorier sorry for the delay, will try this today.

**Comment by Priya91** [comment] 2017-03-27 21:23
@NicolasDorier I tried your repro today on Ubuntu 14.04 LTS. I am getting "Couldn't connect to Server" errors.
```
System.Net.WebException: An error occurred while sending the request. Couldn't connect to server ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.HttpWebRequest.<SendRequest>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ConsoleApplication.Program.<DoRequest>d__1.MoveNext() in /media/lasekar/Enlistments/apps/curl_gc/Program.cs:line 47
Hosting environment: Production
Content root path: /media/lasekar/Enlistments/apps/curl_gc/bin/Debug/netcoreapp1.1
Now listening on: http://localhost:5000

```

**Comment by NicolasDorier** [comment] 2017-03-28 02:37
@Priya91 please wait a bit. The first request is sent before the server is connected. You will then see "hey".

**Comment by Priya91** [comment] 2017-03-29 16:42
@NicolasDorier I get the cannot connect to server error one time, and let it ran for 30 mins, i didn't hit your issue.

**Comment by NicolasDorier** [comment] 2017-03-30 03:35
@Priya91 My apologies, the VM id is `af1675435d14`.
The first exception is normal, then it should keep printing "hey". 
Then the error should come up, in around 1min. I tried  with `af1675435d14`.

```
docker run -ti af1675435d14
apt-get update
apt-get install vim
dotnet new console -n Repro
cd Repro
vim Program.cs
# Edit Program.cs
dotnet add package Microsoft.AspNetCore.Server.Kestrel
dotnet restore
dotnet run
```

Output:

```
hey
hey
hey
hey
hey
System.IO.IOException: The read operation failed, see inner exception. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
   at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ConsoleApplication.Program.<DoRequest>d__1.MoveNext() in /Repro/Program.cs:line 49
hey
hey
```

I tried on image `0abf88e1ef29` as well. (1.0.0-preview2-003131)
**1.0.0-preview2-003131 of image `0abf88e1ef29` does not seems to exhibit this bug, I let it run for 1 minute without issue**

If you want to try on 1.0.0-preview2-003131:
```
docker run -ti 0abf88e1ef29
apt-get update
apt-get install vim
mkdir Repro
cd Repro
dotnet new
vim project.json
# adding dependency Microsoft.AspNetCore.Server.Kestrel
vim Program.cs
# Edit Program.cs
dotnet restore
dotnet run
```

I apologize for giving you the wrong image.

**Comment by Priya91** [comment] 2017-03-31 00:45
@nicholasdorier The version 1.0.0-preview2-003131 is .net core 1.1? It's latest compared to .net 1.0.. Are you saying the bug doesn't repro on the latest version? If so, can you upgrade to the latest?

**Comment by karelz** [comment] 2017-03-31 00:52
FYI: The version 1.0.0-preview2-003131 is for .NET Core 1.0 (see [release notes](https://github.com/dotnet/core/tree/master/release-notes))

**Comment by Priya91** [comment] 2017-03-31 00:52
@NicolasDorier I tried your repro with ```1.1 with SDK Preview 2.1 build 3177``` and the bug didn't repro. Can you update to 1.1?

**Comment by NicolasDorier** [comment] 2017-04-01 06:05
Same problem with latest microsoft image, very consistently reproduce the error above.
```
root@cd33ee32ac2e:/Repro# dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

Using the latest microsoft/dotnet  image id `82ba68a32f38`.
@Priya91 after reproducing the bug above I downloaded `1.1 with SDK Preview 2.1 build 3177` and gave it a try with the following `project.json`

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "NETStandard.Library": "1.6.0",
        "System.Net.Requests" : "*"
      },
      "imports": "dnxcore50"
    }
  }
}
```

```
root@cd33ee32ac2e:/Repro# dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

It is worth noting that it takes more time to reproduce on `1.0.0-preview2-1-003177` than on `1.0.1`.

**Comment by NicolasDorier** [comment] 2017-04-01 06:17
Please, try yourself, my environment is very easy reproductible thanks to docker.  @Priya91 I think you were not using the right dotnet core version.  Try to use the  docker image latest microsoft/dotnet image id 82ba68a32f38.

**Comment by NicolasDorier** [comment] 2017-04-01 06:19
You can also use https://docs.docker.com/engine/admin/resource_constraints/ for restraining memory of your container, even though you should not need that.

**Comment by PavelStefanov** [comment] 2017-04-02 11:09
+1
I have same issue. I'm using .Net core 1.1 on Ubuntu 14.04. So also I am using CopyToAsync on WebResponse.GetResponseStream() stream to a MemoryStream.

`System.IO.IOException: The read operation failed, see inner exception. ---> System.ObjectDisposedExce         ption: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken can         cellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length         , EasyRequest easy)
   at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitem         s, IntPtr context)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Http.CurlHandler.CurlResponseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)`

@Priya91 Can you try to reproduce the issue? Can you provide a workaround?

**Comment by Priya91** [comment] 2017-04-04 00:03
I was able to repro this by using the linux docker container from windows, whereas using the same container from my linux box I was not successful, that is weird.

From looking at the callstack it seems like the request stream is disposed of, when the curl invokes send callback to read the request data. Will follow up.

**Comment by NicolasDorier** [comment] 2017-04-04 06:03
> I was able to repro this by using the linux docker container from windows, whereas using the same container from my linux box I was not successful, that is weird.

This is really weird. My only guess is that default of memory setting for containers on Windows is different from linux.  You might give a try to  https://docs.docker.com/engine/admin/resource_constraints/ .

**Comment by NicolasDorier** [comment] 2017-04-19 04:11
@karelz can you remove the "need more info" tag ?

**Comment by karelz** [comment] 2017-04-19 05:57
Done, thanks for reminder @NicolasDorier. BTW: We did triage & costing today - @Priya91 mentioned this is likely dupe of #9006.

**Comment by stephentoub** [comment] 2017-05-01 18:21
A few for https://github.com/dotnet/corefx/issues/9006 was merged a few days ago in https://github.com/dotnet/corefx/issues/19082.  Does this still repro with the latest bits from master?

**Comment by karelz** [comment] 2017-05-01 18:25
I will opportunistically close it as Fixed. If there's evidence otherwise, please shout out ASAP, and we can reopen, thanks!

**Closed by karelz** 2017-05-01 18:25 UTC
Labels: area-System.Net.Http, bug, os-linux

**Comment by NicolasDorier** [comment] 2017-05-01 19:41
@stephentoub is there any easy to use container somewhere so I can give it a try ?

**Comment by karelz** [comment] 2017-05-01 20:34
Here are dogfooding docs: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md
Hope it helps.

**Comment by karelz** [comment] 2017-05-01 20:34
cc @danmosemsft @mellinoe @weshaggard regarding the container idea ...

**Comment by NicolasDorier** [comment] 2017-08-08 06:12
I confirm this issue is fixed in .NET Core 2.0 preview 2.
A production machine hit the same issue on .NET Core 1.1, changing to .NET Core 2.0 instantly solved the issue.
