### ISSUE TITLE
System.Threading.Barrier will fail if current execution context is not preallocated default

### ISSUE THREAD

**Issue by Alexx999** [dotnet/corefx#2072] opened 2015-06-17 01:22 UTC
This occurs due to FinishPhase calling ExecutionContext.Run(). It will always succeed for the first time, but during first call it will set isNewCapture to false if ExecutionContext is not a PreallocatedDefault so any subsequent calls will fail in this case.
I encountered this when running System.Threading tests on top of .NET Framework 2.0 where is no PreallocatedDefault context.
Solution is making _ownerThreadContext.CreateCopy() call before calling ExecutionContext.Run()

**Comment by stephentoub** [comment] 2015-06-17 02:57
Thanks, @Alexx999.  Just to make sure I understand, you're not able to repro this on .NET Core or on any recent version of the .NET Framework on the desktop, only on an older version of .NET?

**Comment by stephentoub** [comment] 2015-06-17 03:20
And could you post a repro?  I'm unable to reproduce a failure on the current corefx src/tests on GitHub.

**Comment by Alexx999** [comment] 2015-06-17 03:37
it reproduces on 2.0, but it will reproduce on new runtimes too if you switch ExecutionContext to non-default. The failing test was RunBarrierTest8_PostPhaseException because it used Barrier twice

**Comment by stephentoub** [comment] 2015-06-17 03:40
Can you share repro code for how you're switching to a non-default context such that it fails on .NET Core?  I just tried it, confirmed it captured a non-default context, and it still ran successfully, so I'm obviously doing something different than you are if it's failing for you. Thanks!

**Comment by Alexx999** [comment] 2015-06-17 04:32
Hmmm... When using desktop runtime it fails even in simplest cases like:
```
        public static void Main()
        {
            var b = new Barrier(1, barrier => {});
            Task.Run(() => b.SignalAndWait()).Wait();
            Task.Run(() => b.SignalAndWait()).Wait();
        }
```
But I just checked the CoreCLR's ExecutionContext and it turns out that it's fine as-is.

**Comment by stephentoub** [comment] 2015-06-17 10:46
Thanks, @Alexx999.  What version are you using?  I just ran that on the desktop a million times, and it succeeded every time.

**Comment by stephentoub** [comment] 2015-06-17 11:58
Oh, wait, are you using the corefx implementation of Barrier on the desktop, rather than using the desktop's implementation of Barrier on the desktop?  If so, yes, this is by design.

**Comment by stephentoub** [comment] 2015-06-17 15:35
@Alexx999, I'm going to go ahead and close this.  As far as I can tell, it works in all environments as long as you use the right version for that environment.  I'm going to close this out for now; feel free to reopen if you still believe there's an issue here.

**Closed by stephentoub** 2015-06-17 15:35 UTC
