### ISSUE TITLE
WebException: update WebException.GetStatusFromException after System.Net.Http API changes

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#2384] opened 2015-07-16 17:45 UTC
For now, we use the .HResult of the exception to help us map to a suitable
WebExceptionStatus enum value.  The .HResult is set into this exception by
the underlying .NET Core and .NET Native versions of the System.Net.Http stack.
In the future, the HttpRequestException will have its own .Status property that is
an enum type that is more compatible directly with the WebExceptionStatus enum.

**Comment by karelz** [comment] 2016-12-14 18:21
Dupe of #13773

**Closed by karelz** 2016-12-14 18:21 UTC
Labels: api-needs-work, area-System.Net
