### ISSUE TITLE
WaitForPeerProcess test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5780] opened 2016-01-29 16:42 UTC
MESSAGE:
Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx\ubuntu_release_bld_prtest\src\System.Diagnostics.Process\tests\ProcessWaitingTests.cs. Line: 146\n---- Assert.Equal() Failure\nExpected: 42\nActual: 139
+++++++++++++++++++
STACK TRACE:
at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber) at Assert.Equal[T](T expected, T actual, String path, Int32 line) at System.Diagnostics.Tests.ProcessWaitingTests.WaitForPeerProcess() ----- Inner Stack Trace ----- at Assert.Equal[T](T expected, T actual, String path, Int32 line)

**Comment by stephentoub** [comment] 2016-01-31 21:25
I just saw this happen again. Looks like some kind of seg fault in the peer process.

**Comment by stephentoub** [comment] 2016-02-02 16:38
@LLITCHEV, @janvorli, @ramarag, this failure started happening randomly in our tests a few days ago, though the test has been stable for a long time before that.  The failure occurs when we fork and execve another process, which then seg faults.  Every time I've been able to capture a core dump locally, I see this:
```
Core was generated by `corerun RemoteExecutorConsoleApp.exe System.Diagnostics.Process.Tests, Version='.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efd9df4faec in ETW::MethodLog::MethodJitted(MethodDesc*, SString*, SString*, SString*, unsigned long, unsigned long) ()
   from /home/stoub/netcore/libcoreclr.so
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00007efd9df4faec in ETW::MethodLog::MethodJitted(MethodDesc*, SString*, SString*, SString*, unsigned long, unsigned long) ()
   from /home/stoub/netcore/libcoreclr.so
#1  0x00007efd9e059953 in MethodDesc::MakeJitWorker(COR_ILMETHOD_DECODER*, unsigned int, unsigned int) () from /home/stoub/netcore/libcoreclr.so
#2  0x00007efd9e05af33 in MethodDesc::DoPrestub(MethodTable*) () from /home/stoub/netcore/libcoreclr.so
#3  0x00007efd9e05a823 in PreStubWorker () from /home/stoub/netcore/libcoreclr.so
#4  0x00007efd9df68324 in ThePreStub () from /home/stoub/netcore/libcoreclr.so
#5  0x00007efd24490bf4 in ?? ()
#6  0x00007efd8a7915b0 in ?? ()
#7  0x0000000000000000 in ?? ()
```
Any ideas?

**Comment by janvorli** [comment] 2016-02-02 17:49
@stephentoub let me try to reproduce it locally so that I can see what is the exact spot of failure

**Comment by janvorli** [comment] 2016-02-02 17:50
I have accidentally closed it and I am unable to reopen it - I reopen and the dotnet-bot closes it right away.

**Comment by stephentoub** [comment] 2016-02-02 18:16
Looks like you managed to get it reopened :smile:

Since it only repros sporadically, I changed the test locally to be:
```C#
public static IEnumerable<object[]> Iterations { get { for (int i = 0; i < 1000; i++) yield return new object[] { i }; } }

[Theory]
[MemberData("Iterations")]
public void WaitForPeerProcess(int iteration)
```
so that running the unit tests would run this particular test a thousand times.  The peer process usually crashes within the first 100 iterations for me.  I used ```ulimit -c unlimited``` to ensure that when it did, a core dump was captured.

**Comment by janvorli** [comment] 2016-02-04 14:29
@stephentoub I have modified the test as you've suggested, but I was unable to reproduce the issue. I've tried it first with the coreclr binaries that were placed to the test's binary folder and later with debug coreclr binaries that I've built from the latest coreclr.
I was running just the single test selectively, so I was wondering if there is something you were doing differently.
Also, I have used native Ubuntu box for my testing.

**Comment by stephentoub** [comment] 2016-02-04 14:32
> I was wondering if there is something you were doing differently

No, that's basically what I've done.  Is there some information I can gather for you on my machine to help?  Would a core dump help?

**Comment by janvorli** [comment] 2016-02-04 14:37
Yes, a dump with libcoreclr.so would help me to find out the instruction causing the fault. Or even simpler, a disass of the function that crashed and the register values would probably be sufficient.

**Comment by stephentoub** [comment] 2016-02-11 15:41
Looks like this is https://github.com/dotnet/coreclr/issues/3101.  @brianrob, when that's fixed, can you please re-enable this test as well? Thanks.

**Comment by brianrob** [comment] 2016-02-11 17:29
#3110 should mitigate the crash and has already been merged, so you should be good to enable this test.  #3101 is still open so that we can implement the proper fix.

**Closed** 2016-02-12 15:35 UTC
Labels: 2 - In Progress, X-Plat
