### ISSUE TITLE
INumber or INumeric interface for base number types

### ISSUE THREAD

**Issue by MovGP0** [dotnet/corefx#2064] opened 2015-06-16 13:23 UTC
I often run into the problem that I want to handle numeric base types in a common way. 

Unfortunately, they are missing a common interface to express their similarities. Therefore I propose to create an `INumber` or `INumeric` interface on the following numeric base types: 
- `System.Decimal`
- `System.Double`
- `System.Single`
- `System.Int32`
- `System.UInt32`
- `System.Int64`
- `System.UInt64`

This interface should define common functionality, like `+`, `-`, `*`, `/`, etc.

**Comment by ellismg** [comment] 2015-06-16 14:27
We've explored designs like this internally in the past.  One of the sticking points has been you can't define operators on interfaces today, requiring us to use methods like `Add`, `Subtract`, etc.  Would you imagine `BigInteger` would also become INumeric?

**Comment by KrzysztofCwalina** [comment] 2015-06-16 16:23
cc: @CarolEidt
Carol might want to correct me if I am wrong, but I don't think the issue is in syntactical differences between operators and Add/Sub/etc methods. I think additional problem was perf. Operators are non-virtual and don't use the this pointer. We could devirtualized INumber calls but it would require work and might not ever get to the performance level of operators.

**Comment by CarolEidt** [comment] 2015-06-16 17:03
You are both right. The issue was defining operators on interfaces, and it is a non-syntactic issue. Operators are static methods (not instance) and interfaces cannot specify a static method. Thus, one can't specify the natural constraints for INumeric that one would like (i.e. that it have the expected operators). Other designs have added Add, Sub, etc. as instance methods, but that requires changing the definition of all the primitive types. I had proposed adding static interface methods some time ago for this very purpose, but it was considered to be too high cost and cross-cutting (language and runtime).

**Comment by grokys** [comment] 2015-06-16 17:23
This would indeed be incredibly useful, but I can understand the difficulties.

I wonder if it would be easier to add support for a `where T : numeric` to the compiler somehow? Or would this also require runtime changes?

**Comment by CarolEidt** [comment] 2015-06-16 17:47
There was some discussion about having operator constraints, e.g. where T: op_Addition (not necessarily this exact syntax). But even this requires runtime support, and doesn't address static properties (e.g. Zero) which would be desirable. It does address the issue of allowing subsets of operators, for different mathematical classes (e.g. Group, Ring, Field), though one could envision hierarchical interfaces for that purpose.

**Comment by mikedn** [comment] 2015-06-16 17:48
There are ways to use interfaces, operators and get good performance (to a certain limit depending on JIT's mood) but the solution suffers from at least one usability issue:

```C#
interface ICalculator<T> {
    T Add(T x, T y);
}

struct Int32Calculator : ICalculator<int> {
    public int Add(int x, int y) { return x + y; }
}

struct Number<T, TCalc> where TCalc : struct, ICalculator<T> {
    T value;
    public static implicit operator Number<T, TCalc>(T value) {
        return new Number<T, TCalc> { value = value };
    }
    public static implicit operator T(Number<T, TCalc> number) {
        return number.value;
    }
    static TCalc Calc {
        get { return default(TCalc); }
    }
    public static Number<T, TCalc> operator +(Number<T, TCalc> x, Number<T, TCalc> y) {
        return Calc.Add(x, y);
    }
}

static T Sum<T, TCalc>(T[] values) where TCalc : struct, ICalculator<T> {
    var sum = default(Number<T, TCalc>);
    foreach (var value in values)
        sum += value;
    return sum;
}

static void Main() {
    Console.WriteLine(Sum<int, Int32Calculator>(new[] { 1, 2, 3 }));
}
```
The code generated for Sum is identical to the code generated for a non-generic Sum(int[]) method (well, almost - there is a bug in JIT that needs a workaround that's not included in this code). 

The issue is that to use Sum you have to specify the calculator type as a generic argument. Not exactly pretty and not easy to avoid. Maybe it would work if some kind of default generic arguments are added to the language but that's probably just as complicated as adding `T : numeric`.

**Comment by whoisj** [comment] 2015-06-16 18:23
Similar discussion happening over in [Rosyln Issues](https://github.com/dotnet/roslyn/issues/3391)

**Comment by mikedn** [comment] 2015-06-16 18:51
@MaleDong's last example gives me an idea:

```C#
struct Number<T> {
    T value;
    public static implicit operator Number<T>(T value) {
        return new Number<T> { value = value };
    }
    public static implicit operator T(Number<T> number) {
        return number.value;
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Number<T> operator +(Number<T> x, Number<T> y) {
        if (typeof(T) == typeof(int)) {
            return (T)(object)((int)(object)x.value + (int)(object)y.value);
        }
        else {
            NotSupported();
            return default(Number<T>);
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void NotSupported() {
        throw new NotSupportedException();
    }
}

static T Sum<T>(T[] values) {
    var sum = default(Number<T>);
    foreach (var value in values)
        sum += value;
    return sum;
}

static void Main() {
    Console.WriteLine(Sum(new[] { 1, 2, 3 }));
}
```
On x86 (yet to check RyuJIT) the code generated for Sum is almost OK:
```
006404AD 33 F6                xor         esi,esi  
006404AF 33 D2                xor         edx,edx  
006404B1 83 79 04 00          cmp         dword ptr [ecx+4],0  
006404B5 7E 10                jle         006404C7  
006404B7 8B 7C 91 08          mov         edi,dword ptr [ecx+edx*4+8]  
006404BB 03 F7                add         esi,edi  
006404BD 8B C6                mov         eax,esi  
006404BF 8B F0                mov         esi,eax  
006404C1 42                   inc         edx  
006404C2 39 51 04             cmp         dword ptr [ecx+4],edx  
006404C5 7F F0                jg          006404B7  
006404C7 8B C6                mov         eax,esi  
```
There are some warts like esi->eax->esi but it's possible that these no longer exist in RyuJIT. In any case, the code doesn't contains interface calls, boxing or other expensive operations.

However, this will likely "fail" as soon as you add more numeric types to operator+ as the code size will likely exceed the maximum code size the JIT is willing to inline.

**Comment by mellinoe** [comment] 2015-06-16 19:57
> ```return (T)(object)((int)(object)x.value + (int)(object)y.value);```

FWIW, this is the general pattern we use for the IL implementation of Vector<T> (in System.Numerics.Vectors). You're right in that we can avoid boxing/interface calls, etc, but also correct in that we probably can't get inlining to work well. For Vector<T> we just rely on the compiler intrinsics to take over, anyways, so it has a special-case solution.

**Comment by mikedn** [comment] 2015-06-17 20:16
> but also correct in that we probably can't get inlining to work well

I did a test with RyuJIT and inlining works well even if all the types requested by @MovGP0 are added to `operator+`. Unfortunately, the code generated for float and double is kablooey. I suppose that's fixable.

What I really don't like about this kind of implementation is that it is limited to certain numeric types, if the code wasn't written to work with BigInteger then it won't work and there's nothing a user can do about it except creating a different `Number<T>` struct. It's also a bit ugly that you can't block people from attempting to use `Number<T>` with unsupported `Ts` unless you add an interface to the supported numeric types so you have something to constrain `T` to.

**Comment by MovGP0** [comment] 2015-06-17 21:14
while static interfaces or code generation might be helpful, i think it might be much simpler to define methods like `T Add(T left, T right)` on a base interface. additional types could then be supported using generic extension methods on those base interfaces.

**Comment by karelz** [comment] 2016-11-18 18:10
We don't think using `Add`, etc. will be that helpful. Ideally we would like operators on interfaces, which requires language + library + runtime support.
Closing here - we should move this to User Voice per our [issue guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#when-we-close-issues).

**Closed by karelz** 2016-11-18 18:10 UTC
Labels: api-needs-work, area-System.Runtime
