### ISSUE TITLE
HttpClient GET methods does not call virtual SendAsync method

### ISSUE THREAD

**Issue by dombrovsky** [dotnet/corefx#25242] opened 2017-11-14 16:47 UTC
I want to decorate all requests to `System.Net.Http.HttpClient` in some generic way, e.g. log request uri.
I create a subclass of `HttpClient` and override method `SendAsync(HttpRequestMessage, CancellationToken)`.
It turns out that overridden method is executed for `PostAsync`, `DeleteAsync`, `PutAsync`, but not executed for `GetAsync`.

```
using System.Net.Http;

class HttClientEx : HttpClient
{
    public override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        Console.WriteLine("{0} {1}", request.Method, request.RequestUri);
        return base.SendAsync(request, cancellationToken);
    }
}
```
Adding some generic request decorators would be much easier if 
`SendAsync(HttpRequestMessage, HttpCompletionOption, CancellationToken)` 
would be virtual, but 
`SendAsync(HttpRequestMessage, CancellationToken)` 
sealed.

**Comment by stephentoub** [comment] 2017-11-14 16:49
https://github.com/dotnet/corefx/issues/23812
cc: @davidsh

**Comment by davidsh** [comment] 2017-11-14 16:51
This is a dupe of #23812.

If you want to do custom pre and post processing of requests, the design pattern is to create a new handler based on HttpMessageHandler, DelegatingHandler.  Then pass that into the constructor or HttpClient.

The helper methods of HttpClient: GetAsync, PostAsync, etc. are not meant to be "subclassed".

Also, if you want to create a new set of helper methods, you can only create a subclass of HttpMessageInvoker which is the base class of HttpClient.

**Closed** 2017-11-14 16:52 UTC
Labels: area-System.Net.Http, question
