### ISSUE TITLE
Add overloads on TcpClient and TcpListener that take a CancellationToken

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#42106] opened 2019-10-25 06:12 UTC
This adds cancellation support to TcpClient and TcpListener

```c#
class TcpClient
{
   // public System.Threading.Tasks.Task ConnectAsync (string host, int port);
   public ValueTask ConnectAsync (string host, int port, CancellationToken cancellationToken);

   // public System.Threading.Tasks.Task ConnectAsync (IPAddress address, int port);
   public ValueTask ConnectAsync (IPAddress address, int port, CancellationToken cancellationToken);

   // public Task ConnectAsync (IPAddress[] addresses, int port);
   public ValueTask ConnectAsync (IPAddress[] addresses, int port, CancellationToken cancellationToken);
}

class TcpListener
{
   // public Task<Socket> AcceptSocketAsync ();
   public ValueTask<Socket> AcceptSocketAsync (CancellationToken cancellationToken);

   // public Task<TcpClient> AcceptTcpClientAsync ();
   public ValueTask<TcpClient> AcceptTcpClientAsync (CancellationToken cancellationToken);
}
```

related: #37118

**Comment by scalablecory** [comment] 2019-11-19 08:25
Duplicate of https://github.com/dotnet/corefx/issues/37118

**Closed by scalablecory** 2019-11-19 08:25 UTC
Labels: api-suggestion, area-System.Net
