### ISSUE TITLE
Regression in System.Data.SqlClient >= 4.7.0-preview7 on Docker

### ISSUE THREAD

**Issue by rmja** [dotnet/corefx#40476] opened 2019-08-21 07:04 UTC
The newest versions of `System.Data.SqlClient` throws when connecting to SQL Azure when running inside a Docker linux container.

* `4.7.0-preview6.19303.8` does not throw
* `4.7.0-preview7.19362.9` and `4.7.0-preview8.19405.3` throws when run in Docker

I have tried both the debian and alpine images and both seems to produce the exception. The code works fine on Windows.
I have also not seen any issues when connecting to a "real" SQL Server, but I have not investigated this thoroughly.

![image](https://user-images.githubusercontent.com/2112306/63409421-6e811a00-c3f1-11e9-8a3e-4aa7f4d91f28.png)

The reproducing code is the following:

```
using System.Data.SqlClient;

namespace Repro145
{
    class Program
    {
        static void Main()
        {
            using (var connection = new SqlConnection(ConnectionString))
            {
                connection.Open();

                var command = new SqlCommand("SELECT * FROM Catalog.Device", connection);

                // System.Data.SqlClient 4.7.0-preview7.19362.9 and later throws when run in Docker
                // System.Data.SqlClient 4.7.0-preview6.19303.8 does not throw
                var reader = command.ExecuteReader();

                while (reader.Read()) ;

                connection.Close();
            }
        }

        private const string ConnectionString = "Server=tcp:xxx.database.windows.net,1433;Initial Catalog=xxx;Persist Security Info=False;User ID=xxx;Password=xxx;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
    }
}

```

<details>
<summary>.csproj file</summary>

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.2" />
    
    <!-- Does not throw -->
    <!--<PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview6.19303.8" />-->
    
    <!-- Throws -->
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview7.19362.9" />
    
  </ItemGroup>

</Project>
```

</details>

<details>
<summary>Dockerfile</summary>

```
FROM mcr.microsoft.com/dotnet/core/runtime:3.0.0-preview8-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0.0-preview8-buster AS build
WORKDIR /src
COPY ["Repro145/Repro145.csproj", "Repro145/"]
RUN dotnet restore "Repro145/Repro145.csproj"
COPY . .
WORKDIR "/src/Repro145"
RUN dotnet build "Repro145.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Repro145.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Repro145.dll"]
```

</details>

<details>
<summary>Full stacktrace</summary>

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at Repro145.Program.Main() in C:\Source\repro145\Repro145\Program.cs:line 17

Inner Exception 1:
IOException: The decryption operation failed, see inner exception.

Inner Exception 2:
SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL.

Inner Exception 3:
OpenSslCryptographicException: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

</details>

This issue is related to https://github.com/dotnet/SqlClient/issues/145 for the Microsoft.Data.SqlClient equivalent.

**Comment by roji** [comment] 2019-08-21 10:16
/cc @David-Engel @cheenamalhotra @Wraith2

As there haven't been many actual changes to System.Data.SqlClient recently, are we thinking this is possibly a lower-level issue?

**Comment by Wraith2** [comment] 2019-08-21 10:35
Looks like an ssl issue. All the changes I've made to the managed implementation are well above transport level and I don't think there was much else done in there. I know there have been changes to the managed SslStream for 3.0 for kestrel performance though so it might be related to those, or it might be environmental (ssl version differences?)

**Comment by davidsh** [comment] 2019-08-22 11:21
@wfurt 

@bartonjs Can you help here?  This might be an OpenSsl related change/bug.

**Comment by bartonjs** [comment] 2019-08-22 15:20
It means the server responded with something that wasn't TLS.  Looks like the dockerfile used is from Debian, which tends to have some configuration to alter the default enabled ciphersuites; it's possible that this is a bad gateway reporting that there's no mutual ciphersuite.

Really someone needs to capture a network trace.  It might even be enough to try from a similar environment to run `openssl s_client -connect $HOST:$PORT -msg -servername $HOST` with `$HOST` being the name of an AzureSql server and `$PORT` being whatever port SQL talks on.  If that doesn't also fail with "ssl3_get_record:wrong version number" then the network capture is required.  (If it does, then at least we can say what gibberish the server sent :smile:)

**Comment by rmja** [comment] 2019-08-22 17:38
@bartonjs Here is the output from the openssl client connect:

![image](https://user-images.githubusercontent.com/2112306/63536518-10992300-c514-11e9-9cdf-45bcefc77f07.png)

It all seems fine. Please note that `4.7.0-preview6.19303.8` (and its dependencies) does not produce this issue - even though the debian image is the same.

**Comment by bartonjs** [comment] 2019-08-22 17:44
That command output doesn't show any response from the server, and the cipher is (NONE), meaning it isn't actually established. Weird.  So looks like it'll require a tcpdump capture of failing to talk to SQL.  (Ideally a success with the preview6 package and a failure with preview7 package)

**Comment by Wraith2** [comment] 2019-08-22 18:26
Azure SQL requires ssl for all connections. Standard SQL requires ssl for login but not after that point unless you request it. The stack trace indicates that the error occurs during a read operation not a login so it looks as if the login (and thus ssl connection) was possible but that it is now failing while being used.

tcpdump seems like the best way to see what's different as suggested.

**Comment by rmja** [comment] 2019-08-28 12:43
@Wraith2 year, I am not competent enough to provide such dumps, sorry.

**Comment by rmja** [comment] 2019-08-28 18:15
@wfurt can you mail me at my-github-username@laesoe.org. Please include your IP/range so that I can open the firewall appropriately.

I use the versions `mcr.microsoft.com/dotnet/core/runtime:3.0.0-preview8-buster-slim`and `mcr.microsoft.com/dotnet/core/runtime:3.0.0-preview8-alpine`.

**Comment by wfurt** [comment] 2019-08-28 22:42
I think there is regression between preview6 and preview7. I did not get to running in container yet but I can easily reproduce the linked issue.

I published example as self-contained app on Ubuntu 18.04 and than:
```
git checkout XXX
git clean -dfx
./build.sh
cp artifacts/bin/System.Data.SqlClient/netcoreapp-Unix-Debug/System.Data.SqlClient.dll XXXX
```

With that, tip of master fails, https://github.com/dotnet/corefx/commit/88c5a3e317dd2edadc95adedc764c1acad5e3541 works fine and https://github.com/dotnet/corefx/commit/2469a91c2aa68f9cb6b0f18f75dffc673a1f7895 fails. 

That points to https://github.com/dotnet/corefx/pull/35363 as culprit of this. 

I did not change anything in self-contained app besides System.Data.SqlClient.dll and that points to the assembly it self.

I also have packet captures but since everything is wrapped in TDS, it is hard to decode the actual TLS messages. 

cc: @saurabh500 @Gary-Zh @cheenamalhotra

**Comment by Wraith2** [comment] 2019-08-28 22:58
That'll be me then. So the repro is unix client and azure server instance and then query any table and it'll blow up?

**Comment by wfurt** [comment] 2019-08-28 23:01
yes, it seems like. However I did not try OSX or Windows. It would be easy to do if that helps.

**Comment by Wraith2** [comment] 2019-08-28 23:12
Windows would use the native implementation and that wouldn't be affected by the changes in the PR you linked to. OSX would be affected. If you're bored and want to try it confirmation would be interesting but don't waste time you don't have on it.

I probably won't be able to look at this until the weekend but I'll see if I can repro and track it down.

**Comment by wfurt** [comment] 2019-08-28 23:36
It was quick and windows do work. On OSX I get 
```
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: One or more parameters passed to a function were not valid.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Data.SqlClient.SNI.SNIPacket.ReadFromStream(Stream stream)
   at System.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
```

I try to eyeball the packets but it looks similar enough. I did not see any obvious  size mismatch.

**Comment by wfurt** [comment] 2019-08-28 23:45
Also one more note that this works as well
```
<PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19239.1" />
```

**Comment by Wraith2** [comment] 2019-08-28 23:47
Yes, it will do because it's effectively a copy of the corefx code from ~6 months ago.

**Comment by rmja** [comment] 2019-08-29 03:56
@wfurt Are you sure? I am having issues with:

```
<PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19221.1-Preview" />
```

Note that the issue does not have the same symtoms. Instead the symtom is partially corrupted data on read, see https://github.com/dotnet/SqlClient/issues/145

**Comment by wfurt** [comment] 2019-08-29 04:41
I did not do any data transfer. Just trying if it would connect. Also I did not try in container. Just base test ob my dev machine.

**Comment by Wraith2** [comment] 2019-08-29 20:01
It's reproducible on windows if you force the use of the managed network interface (which you can only do in debug builds) and enable encryption on the connection string. It's nothing to do with azure because I can point it at my local sql server and get the same result . It isn't caused by openssl it is caused by SslStream. 

exceptions are:

> A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
>> The decryption operation failed, see inner exception.
>>> The supplied message is incomplete. The signature was not verified.

```
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__214`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Data.SqlClient.SNI.SNIPacket.ReadFromStream(Stream stream) in E:\Programming\csharp7\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNIPacket.cs:line 175
   at System.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds) in E:\Programming\csharp7\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SNI\SNITcpHandle.cs:line 474
```

and as you can see all [ReadFromStream](https://github.com/dotnet/corefx/blob/777dbdec193fcbe49b3f18614348ac96f77d57c3/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIPacket.cs#L175) all it does is request data from the slsstream instance it's using. The data is incoming from the sql server so it isn't an incorrectly formed outgoing packet.

Anyone got any ideas on how to proceed from here?

**Comment by wfurt** [comment] 2019-08-29 20:25
How did that work before the change @Wraith2? 
It it possible somehow we mangle the buffer or we override old data before consuming it? 

It was discussed on the other issue that Azure forces you to do ssl but local SQL may not.

**Comment by Wraith2** [comment] 2019-08-30 00:21
The packet read worked the same way. The problem is in SslOverTDSStream which gets sandwitched between the SslStream and the underlying NetworkStream. The PR you pointed out made some changes to try and avoid extra buffer allocations and separate out some peculiar async stuff more cleanly. The async related changes are the cause of the problem. I can back them off and implement the array pooling of the temporary buffer from the original code and have it work with encryption now. 

I have to be at work in 5 hours so I've run out of time now but tomorrow evening I'll be able to run the manual sql tests and then open a PR. Given that this blocks all non-windows encrypted connections it might be something that hits the 3.0 fix bar. I'm pretty astounded it hasn't shown up until now. It certainly shows we need some manual tests which force encryption on instead of relying on the connection string provided.

@cheenamalhotra, @david-engel the change which causes this problem didn't make it into M.D.SqlClient so this bug isn't in the 1.0 and can be avoided in porting now it's known. The tests did completely miss it though so I think it needs some tests to force encryption scenarios.

**Comment by stephentoub** [comment] 2019-08-30 00:52
Sounds like the best thing to do for 3.0 is revert the offending PR.

cc: @ericstj

**Comment by Wraith2** [comment] 2019-08-30 06:55
Reverting the specifc change to SslOverTdsStream i could agree with, the whole PR is overkill.

**Comment by rmja** [comment] 2019-08-30 09:49
@Wraith2 please see my observations over in https://github.com/dotnet/SqlClient/issues/145#issuecomment-526538760. Are we absolutely sure that the two issues are not related?

**Comment by stephentoub** [comment] 2019-08-30 11:52
> Reverting the specifc change to SslOverTdsStream i could agree with, the whole PR is overkill.

I think this demonstrates that we lack sufficient test coverage to be making such broad sweeping changes. You said yourself "I'm pretty astounded it hasn't shown up until now."

**Comment by Wraith2** [comment] 2019-08-30 17:28
If you're decided on rollback do you need me to do anything? I don't know how that process works.

**Comment by stephentoub** [comment] 2019-08-30 17:29
> If you're decided on rollback

There's no decision here; I'm just making a recommendation.

**Comment by Wraith2** [comment] 2019-08-30 17:45
Ok, as long as no-one is waiting for me to do something that's fine. Just let me know if I do need to take some action. I don't want to be holding things up.

**Comment by wfurt** [comment] 2019-08-30 18:13
I can give it try. If there are no follow-up changes depending on this it is pretty easy. Unless we think we can quickly come up with good and safe fix.

**Comment by Wraith2** [comment] 2019-08-30 18:57
Option 1 is to revert the changes to SslOverTdsStream.ReadInternal that I made back to the [original](https://github.com/dotnet/corefx/blob/68cfddeac516d7552124ca5028275e884bccbeb5/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SslOverTdsStream.cs#L89-L127)

Option 2 is to do 1 and then then move forward with a [conservatively altered version](https://github.com/Wraith2/corefx/blob/c9fb311e1e8bc94fc3b624b1c3485152f30356f4/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SslOverTdsStream.cs#L90-L133) that keeps the memory benefit but doesn't attempt to split apart the async. 

Option 3 is a full revert of the entire PR.

I favour 2 and that's where I'd got to yesterday and had it connecting and reading a table of date from Northwind successfully with and without encryption.

**Comment by bartonjs** [comment] 2019-08-30 21:18
Since we're really really locking down for 3.0 I think the release drivers will want only "option 3", or like a 2 line surgical fix to the current state.  And they probably really wanted it to have been in master yesterday and release/3.0 a couple hours ago so the fix could be verified in preview9, which is (IIRC) the last preview before the release.

Since there's no more runway to fix a fix, they'll want "the simplest" solution (either logically (revert a PR) or LoC).  Half-reverting a PR probably will sound too scary.

But I'm just speculating, I don't actually attend those meetings, or control them :smile:.

**Comment by Wraith2** [comment] 2019-08-30 21:25
I'd say option 1 is the smallest and safest change, no new code just the previous version.

**Comment by wfurt** [comment] 2019-08-30 21:28
Revert from github does not work as there are conflicting changes. Can you please work out PR to revert the change @Wraith2 ?

**Comment by Wraith2** [comment] 2019-08-30 21:33
the full PR or just the small block?

**Comment by wfurt** [comment] 2019-08-30 22:08
I'm not database person so I don't know what is smallest risk. As @bartonjs mentioned 3.0 is closing and risk is important. We can always improve and iterate on new package as that can be shipped out of band.

**Comment by danmosemsft** [comment] 2019-09-03 17:38
@cheenamalhotra as the owner of SqlClient can you please help make sure the right thing happens here? Note, we are close to cutting the final 3.0 release build

**Comment by cheenamalhotra** [comment] 2019-09-03 18:02
Hi @danmosemsft 

I'm reviewing and testing Wraith's PR to fix this issue and will update soon!

**Comment by cheenamalhotra** [comment] 2019-09-03 18:05
Hi @wfurt 

Would request you to also test changes from PR #40732 over the bugged PR to confirm from your repro environment.

**Comment by danmosemsft** [comment] 2019-09-03 18:11
@cheenamalhotra perfect, once there is a change merged into master, please ping myself and @ericstj and we can help get it to tactics for 3.0 consideration.

**Comment by johnsimons** [comment] 2019-09-04 05:11
I am not sure if it helps or not but we ran into this issue (same version) and we manage to work around it by explicitly setting the `Packet Size` in the connection string to `4096`, from my reading it is 8000 by default.

**Comment by cheenamalhotra** [comment] 2019-09-04 23:56
@danmosemsft @ericstj 
The regression issue has been fixed and PR #40732 merged.

@wfurt @rmja 
The latest master branch source code fixes the problem now, please test and let us know for any other concerns. We are also considering to port over the performance improvements in Microsoft.Data.SqlClient (NetCore) with dotnet/sqlclient#173 soon.

**Comment by Wraith2** [comment] 2019-09-04 23:58
@danmosemsft @ericstj, @cheenamalhotra just validated and merged the fix

**Comment by wfurt** [comment] 2019-09-05 00:00
I only have setup @rmja provided and I used the very simple repro script.

**Comment by divega** [comment] 2019-09-05 00:49
@danmosemsft, @ericstj just wanted to confirm that you plan to take this to tactics. Does it help to keep the issue open in 3.0 for tracking purposes?

**Comment by danmosemsft** [comment] 2019-09-05 02:11
@cheenamalhotra could you please prep a PR against 3.0 if it needs to be ported? Please include the usual template and let us know.

**Comment by danmosemsft** [comment] 2019-09-05 02:13
Example of the filled out PR template : https://github.com/dotnet/corefx/pull/40820
After this is done we can send mail asking for OK to merge it. I think since your team owns this component we will mostly be relying on your recommendation.

**Comment by cheenamalhotra** [comment] 2019-09-05 04:59
Done 👍

**Comment by marchy** [comment] 2019-09-06 07:59
Confirmed the nightly build 4.7.0-rc2.19455.22 now works on MacOS!  😁
Great work all

**Comment by divega** [comment] 2019-09-10 00:10
@danmosemsft, @cheenamalhotra should this issue be closed now or is it still used to track something?

**Comment by danmosemsft** [comment] 2019-09-10 00:11
It's fixed I believe. @cheenamalhotra feel free to close

**Closed** 2019-09-10 00:34 UTC
Labels: area-System.Data.SqlClient, os-linux, os-mac-os-x
