### ISSUE TITLE
Publish is broken with “Error: The underlying compression routine could not be load correctly

### ISSUE THREAD

**Issue by muratg** [dotnet/corefx#5380] opened 2016-01-13 18:09 UTC
Seems related to `System.IO.Compression.ZipFile` package.

@joshfree @troydai

**Comment by ianhays** [comment] 2016-01-13 18:11
Looking into this now.

**Comment by pranavkm** [comment] 2016-01-13 18:21
Here's the stack trace:

```
C#
Error: Full Exception: System.IO.Compression.ZLibException: The underlying compression routine could not be loaded corre
ctly. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, Co
mpressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.ZipArchiveEntry.GetDataCompressor(Stream backingStream, Boolean leaveBackingStreamOpen, EventHandler onClose)
   at System.IO.Compression.ZipArchiveEntry.OpenInWriteMode()
   at NuGet.PackageBuilder.WriteOpcManifestRelationship(ZipArchive package, String path)
   at NuGet.PackageBuilder.WriteManifest(ZipArchive package, Int32 minimumManifestVersion)
   at NuGet.PackageBuilder.Save(Stream stream)
```

**Comment by ianhays** [comment] 2016-01-13 19:04
There is a bug in the app-container clrcompression.dll in the most recent package that is causing this error. Working on the solution now.

**Comment by ianhays** [comment] 2016-01-13 19:52
I was unable to repro this. Could you provide some more details (or some repro code) of the failure so I can be sure I'm resolving it completely?

My config:
```
PS D:\git\dnx\test\Microsoft.Dnx.Tooling.tests> dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc2-16386
 Type:         CoreClr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0.10586
 Runtime Id:   win10-x86

PS D:\git\dnx\test\Microsoft.Dnx.Tooling.tests> cmd /C dnx test
xUnit.net DNX Runner (32-bit DNXCore 5.0)
  Discovering: Microsoft.Dnx.Tooling.tests
  Discovered:  Microsoft.Dnx.Tooling.tests
  Starting:    Microsoft.Dnx.Tooling.tests
...
  Finished:    Microsoft.Dnx.Tooling.tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Dnx.Tooling.tests  Total: 35, Errors: 0, Failed: 0, Skipped: 0, Time: 20.656s
```

**Comment by ianhays** [comment] 2016-01-14 02:10
I got the repro working and was able to find the root cause: the exports being used to build the app-container clrcompression.dll were being loaded incorrectly. I resolved that issue on the TFS side in changeset 1564308.

**Closed by ianhays** 2016-01-14 02:10 UTC
Labels: blocking-partner

**Comment by joshfree** [comment] 2016-01-14 02:15
Thanks @ianhays

**Comment by troydai** [comment] 2016-01-14 06:44
Thank you @ianhays
