### ISSUE TITLE
Should sockets performance tests be inner loop?

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3542] opened 2015-09-29 20:45 UTC
These tests have failed to meet the baseline a few times, but they pass on re-run.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4407/testReport/junit/System.Net.Sockets.Performance.Tests/SocketPerformanceAPMTests/SocketPerformance_SingleSocketClientAsync_LocalHostServerAPM/

When the CI System runs jobs, it can run multiple jobs on the same machine at the same time, could that be causing problems or are there real problems here that we should be investigating?

It seems like the long term plan is that we move to @ianhays's [Performance] stuff.  Can we just adopt these changes for that instead of having yet another perf testing thing that also runs inner loop?

/cc @CIPop @davidsh @pgavlin @bartonjs.

**Comment by pgavlin** [comment] 2015-09-29 20:49
I think that there's already been some discussion re: moving these tests to the outer loop and finding a better success metric.

**Comment by CIPop** [comment] 2015-09-29 22:06
Yes, this is a duplicate of #3495.

I still think it's generally a bad idea to ever consider Perf tests as CI. (These are already marked as perf.)

**Comment by pgavlin** [comment] 2015-09-29 22:08
I'll submit a PR today to move these into outer loop/benchmark

**Comment by pgavlin** [comment] 2015-10-02 17:20
These tests were moved into [OuterLoop]  by #3548.

**Closed by pgavlin** 2015-10-02 17:20 UTC
Labels: bug, System.Net

**Comment by stephentoub** [comment] 2015-10-05 15:28
> I still think it's generally a bad idea to ever consider Perf tests as CI

Certainly if the tests weren't written to be run as part of a normal CI job then we shouldn't be doing so.

More generally, however, eventually I do believe we'll want perf legs as part of CI jobs, so that we can verify that core performance isn't regressed by a change in addition to functionality not being regressed.  I'm not sure whether this would apply to networking or not.

**Comment by bartonjs** [comment] 2015-10-05 16:09
> eventually I do believe we'll want perf legs as part of CI jobs, so that we can verify that core performance isn't regressed

Right now one potential problem with that is that we allow multiple PR jobs to run on the same machines, in parallel.  So wall-clock based performance metrics can be impacted by process switching.

**Comment by stephentoub** [comment] 2015-10-05 16:13
I'm less interested in wall clock measurements for such things than I am in instructions retired and GC allocations.
