### ISSUE TITLE
System.Linq.Expressions.Expression.GetType() returns Expression1`1 instead of Expression`1

### ISSUE THREAD

**Issue by amkherad** [dotnet/corefx#36720] opened 2019-04-08 23:02 UTC
### Issue

I have a class in my project which is responsible for simple object mapping operations, each member is a pure+static method to return an expression so I can use it in EF
```
public static Expression<Func<Image, UploadDescriptorModel>> ImageToDescriptorModel()
{
    return image => new UploadDescriptorModel
    {
        Id = image.Id,
        Name = image.Name,
        FileName = image.FileName,
        Order = image.Order
    };
}
```
I was trying to add a dynamic method to find the member with desired type signature and compile it to Func so the mapping is available outside of the EF
But first I cached all of the members in an static field called `AdapterCache` defined as `IDictionary<Type, Expression> AdapterCache`
```
AdapterCache = typeof(Adapters).GetMethods(BindingFlags.Static | BindingFlags.Public)
      .Select(method => (Expression) method.Invoke(null, new object[0]))
      .ToDictionary(expression => expression.GetType());
```
Here's the `GetAdapter` code:
```
public static Func<TEntity, TModel> GetAdapter<TEntity, TModel>()
{
    if (AdapterFuncCache.TryGetValue(typeof(Func<TEntity, TModel>), out var func))
    {
        return (Func<TEntity, TModel>) func;
    }

    if (AdapterCache.TryGetValue(typeof(Expression<Func<TEntity, TModel>>), out var value))
    {
        var compiledFunc = ((Expression<Func<TEntity, TModel>>) value).Compile();
        AdapterFuncCache.Add(typeof(Func<TEntity, TModel>), compiledFunc);
        return compiledFunc;
    }

    throw new InvalidOperationException();
}
```
The function kept failing despite that I was sure that it was correct, when I checked the cache I noticed that types are showing as Expression1'1 instead of Expression'1

### I created some tests:
```
Expression<Func<Product, ProductResponseModel>> exp = Adapters.ProductToProductResponseModel();
Debug.Assert(typeof(Expression<Func<Product, ProductResponseModel>>) == exp.GetType(), "FAIL");
// >>>>> it's failing
```
```
Debug.Write("typeof(Expression<Func<Product, ProductResponseModel>>).Name.GetHashCode():");
Debug.WriteLine(typeof(Expression<Func<Product, ProductResponseModel>>).Name.GetHashCode());

Debug.Write("exp.GetType().Name.GetHashCode():");
Debug.WriteLine(exp.GetType().Name.GetHashCode());
//typeof(Expression<Func<Product, ProductResponseModel>>).Name.GetHashCode():-182679955
//exp.GetType().Name.GetHashCode():-547687512
```

I'm on ArchLinux so I don't have the latest version of dotnet and I'm not sure that it got fixed or not but with the search I've done I found nothing about this bug.

### My Stats
Linux version 4.19.29-1-lts
dotnet-host 2.2.3+105-1                                                               
dotnet-runtime 2.2.3+105-1
dotnet-sdk 2.2.3+105-1

**Comment by cston** [comment] 2019-06-28 04:44
@amkherad, thanks for reporting this issue. Sorry for not responding sooner.

It looks like the behavior is by design: `exp` is an instance of a derived type of the declared type.

The following assert should succeed:
```C#
Debug.Assert(typeof(Expression<Func<Product, ProductResponseModel>>).IsInstanceOf(exp));
```

**Comment by cston** [comment] 2019-06-28 04:44
Closing as by design.

**Closed by cston** 2019-06-28 04:44 UTC
Labels: area-System.Linq.Expressions
