### ISSUE TITLE
UdpClient: Cancellation support for Async methods

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#9848] opened 2016-07-05 13:12 UTC
In the current UdpClient methods, the `SendAsync` and `ReceiveAsync` method have no support for cancellation. A method could be in an `await RecieveAsync()`, which effectively never returns in a "clean" way.

Instead, you have to call `Dispose()`/`Close()` on the `UdpClient` instance and catch `ObjectDisposedException` and `NullReferenceException`'s coming from that await.

There's a race condition here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L397

That that triggers the NRE -- the `FreeResources()` call could be called as part of a dispose while another thread hit's that `EndRecieve()`

Rather than handling exceptions to end things, having a `CancellationToken` available in the async calls would enable a clean shutdown.

**Comment by karelz** [comment] 2017-02-23 19:58
Dupe of #9698 (potential solution of it)

**Closed by karelz** 2017-02-23 19:58 UTC
Labels: area-System.Net, enhancement, untriaged
