### ISSUE TITLE
[DataAnnotations] resx localization not work on RC1

### ISSUE THREAD

**Issue by kazuk** [dotnet/corefx#4682] opened 2015-11-26 03:50 UTC
### environment 

- Windows 10 Enterprize N + japanese lang pack
- Visual Studio 2015 Enterprize (ja-jp localized)

### repro steps

1. create new ASP.NET Web Application project
2. add Resource.resx
3. define `Password` resource 
4. edit `ViewModels/Account/LoginViewModel.cs`
```
        [Required]
        [DataType(DataType.Password)]
        [Display( ResourceType = typeof(Resource), Name ="Password")]
        public string Password { get; set; }
```

 run application and go to login page

### expected result

 Login form field label shown as resource defined text.

### actual result

```
An unhandled exception occurred while processing the request.

InvalidOperationException: ローカライズに失敗したため、プロパティ 'Name' を取得できません。型 'WebApplication1.Resource' がパブリックでないか、'Password' という名前のパブリックで静的な文字列プロパティが含まれていません。

場所 System.ComponentModel.DataAnnotations.LocalizableString.<>c__DisplayClass0.<GetLocalizableValue>b__3()
```

 error was reports WebApplication1.Resource is not `public` or 'Password' is not `public static`.

in generated Resources.Designer.cs

```
    internal class Resource {

 snip

        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
   }
```

- Resource class generated with `internal`
- Password property generated with `internal static`

**Comment by gkhanna79** [comment] 2015-12-03 18:54
This sounds like a VS designer issue rather than a runtime/resourcemanager infrastructure issue.

**Comment by gkhanna79** [comment] 2015-12-03 18:59
@Pilchie Can you please help route this to the appropriate designer dev? I am not sure who is the right person and if they are on GH.

**Comment by davkean** [comment] 2015-12-04 01:27
This is a DataAnnotations bug/design issue, in particular the code starting here: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/LocalizableString.cs#L132.

**Comment by lajones** [comment] 2016-01-22 18:17
@kazuk I don't think we want to change this. The code has required the resources to be public since the beginning. But there's an easy workaround. Double-click the .resx file. At the top of the editor you'll see a dropbox labeled "Access Modifier". Change that from "internal" to "public" and you should be good to go. Closing as By Design.

**Closed by lajones** 2016-01-22 18:17 UTC
Labels: System.ComponentModel
