### ISSUE TITLE
Intermittent System.Numerics.Tests.divremTest.RunDivRemTests failed in CI on CentOS, Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7806] opened 2016-04-17 12:27 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug_tst/3/consoleFull

```
00:29:07    System.Numerics.Tests.divremTest.RunDivRemTests [FAIL]
00:29:07       Assert.Throws() Failure
00:29:07       Expected: typeof(System.DivideByZeroException)
00:29:07       Actual:   typeof(Xunit.Sdk.TrueException): Out parameters not matching
00:29:07       Expected: True
00:29:07       Actual:   False
00:29:07       Stack Trace:
00:29:07             at System.Numerics.Tests.StackCalc.VerifyOutParameter()
00:29:07             at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
00:29:07             at System.Numerics.Tests.divremTest.<>c__DisplayClass8_0.<RunDivRemTests>b__0()
```

**Comment by mellinoe** [comment] 2016-06-08 19:11
I'm not able to reproduce this, unfortunately. I initially assumed it must have something to do with the random numbers being generated in the test. The test class uses a predictable seed value, but the Random instance is static and shared across the test cases. Technically, I think xUnit is free to run tests in whatever order it wants, which could result in unpredictable values being used in different test cases. In practice, though, I'm only seeing it run the tests in the same order, so the test cases should be using the same test values in every run.

**Comment by stephentoub** [comment] 2016-06-14 11:17
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/64/consoleText
```
System.Numerics.Tests.divremTest.RunDivRemTests [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   -4966759395308350
```

**Comment by stephentoub** [comment] 2016-10-23 12:36
Failed again here, this time on Fedora:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/44/consoleText
```
     System.Numerics.Tests.divremTest.RunDivRemTests [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.DivideByZeroException)
        Actual:   typeof(Xunit.Sdk.EqualException): Assert.Equal() Failure
        Expected: 0
        Actual:   -4966759395308350
```

**Comment by stephentoub** [comment] 2016-10-23 12:38
> Technically, I think xUnit is free to run tests in whatever order it wants, which could result in unpredictable values being used in different test cases. In practice, though, I'm only seeing it run the tests in the same order, so the test cases should be using the same test values in every run.

Tests do not always run in the same order.  If the tests are expecting to be run in a particular order, we need to fix the tests.

**Comment by Clockwork-Muse** [comment] 2016-10-24 05:29
Even besides the test ordering problem, `Random` [isn't threadsafe](https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx#ThreadSafety).  Tests are run in parallel.
So part of what we're seeing is possibly due to its internal state being corrupted.  The remarks claim that concurrent access results in a 0 being returned, but the current code doesn't seem to do anything to ensure that (...and if the code isn't threadsafe, detection strikes me as unlikely anyways).  Also, such a 0 strikes me as problematic anyways, since 0 may be valid or invalid input, depending on method and parameters used.

**Comment by stephentoub** [comment] 2016-11-03 20:00
Not sure if it's the same underlying cause, but another divremTest test failed here:
http://dotnet-ci1.westus.cloudapp.azure.com/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_release/1/consoleText
```
System.Numerics.Tests.divremTest.RunDivRem_OneSmallOne0BI [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   31122745322556859589923417330907291586
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_release/src/System.Runtime.Numerics/tests/BigInteger/stackcalculator.cs(252,0): at System.Numerics.Tests.StackCalc.VerifyOutParameter()
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_release/src/System.Runtime.Numerics/tests/BigInteger/divrem.cs(185,0): at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
           /mnt/j/workspace/dotnet_corefx/master/outerloop_ubuntu16.04_release/src/System.Runtime.Numerics/tests/BigInteger/divrem.cs(96,0): at System.Numerics.Tests.divremTest.RunDivRem_OneSmallOne0BI()
```

**Comment by stephentoub** [comment] 2016-11-04 18:51
Also here on macOS:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_osx_debug/15/consoleText
```
     System.Numerics.Tests.divremTest.RunDivRem_OneLargeOne0BI [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.DivideByZeroException)
        Actual:   typeof(Xunit.Sdk.EqualException): Assert.Equal() Failure
        Expected: 0
        Actual:   -4966759395308350
        Stack Trace:
              at System.Numerics.Tests.StackCalc.VerifyOutParameter()
              at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
              at System.Numerics.Tests.divremTest.<>c__DisplayClass5_0.<RunDivRem_OneLargeOne0BI>b__0()
```

**Comment by danmosemsft** [comment] 2016-11-07 17:00
@mellinoe could you please try again to repro locally?

Note if you can't repro then @Clockwork-Muse's comment above that Random isn't threadsafe may be the key to making them reliably repro.

**Comment by danmosemsft** [comment] 2016-11-28 21:39
@jiangzeng how often are we seeing this?

**Comment by jiangzeng** [comment] 2016-11-29 00:50
@danmosemsft I checked the history results from MissionControl in the last month, it looks like it does not happen.

**Comment by Clockwork-Muse** [comment] 2016-11-29 02:43
@danmosemsft - while it's true that `Random` isn't threadsafe, on further review it's unlikely that's happening here.  Tests **are** multi-threaded, but this is usually only in independent units (test classes), probably specifically to avoid something like this.

**Comment by JonHanna** [comment] 2016-11-29 02:57
If you really need to run tests in a particular order you can force it with the attribute at https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/TestExtensions/TestOrderAttribute.cs and the orderer at https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/TestExtensions/TestOrderer.cs though its best avoided since it breaks isolation (the expressions tests use those to check something before and after a one-way change in static state, so the ordering requirement is unavoidable)

**Comment by danmosemsft** [comment] 2016-11-29 05:38
@Clockwork-Muse also it doesn't appear that these tests rely on any particular random numbers (not that you were suggesting they were). I will add logging of the random numbers used, perhaps that will allow us to repro it locally.

**Comment by danmosemsft** [comment] 2016-11-29 17:49
@jiangzeng I added some logging to help us when this fails again. Please next time you see this fail, grab as much of the log as you can and put it in this issue. In particular look for text like this

```
 System.Numerics.Tests.divremTest.RunDivRem_OneSmallOne0BI [FAIL]
        System.Exception : VerifyDivRemString failed: make 197 24 endmake make 0 endmake bDivRem Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 0
        Actual:   2
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 35
           at Xunit.Assert.Equal[T](T expected, T actual) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:line 20
           at System.Numerics.Tests.StackCalc.VerifyOutParameter() in C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\stackcalculator.cs:line 250
           at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 190
        ---- Assert.Equal() Failure
        Expected: 0
        Actual:   2
        Stack Trace:
           C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs(196,0): at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
           C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs(94,0): at System.Numerics.Tests.divremTest.RunDivRem_OneSmallOne0BI()
           ----- Inner Stack Trace -----
           C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\stackcalculator.cs(250,0): at System.Numerics.Tests.StackCalc.VerifyOutParameter()
           C:\git\corefx.dan\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs(190,0): at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
```

**Comment by jiangzeng** [comment] 2016-11-30 00:52
@danmosemsft Sure

**Comment by danmosemsft** [comment] 2016-12-27 21:44
@jiangzeng have we seen this recently? any log for it?

**Comment by jiangzeng** [comment] 2016-12-28 00:43
@danmosemsft I did not see it in recent runs.
@Jiayili1 Please help to double check.

**Comment by danmosemsft** [comment] 2016-12-28 07:32
I am going to close this on the shaky assumption that some other change has fixed it in the last 2 months. @jiangzeng please reopen with the relevant log (similar to mine above) if this does fail.

**Closed by danmosemsft** 2016-12-28 07:32 UTC
Labels: area-System.Numerics, test bug, test-run-core
