### ISSUE TITLE
StringComparer.InvariantCultureIgnoreCase gives different results in Windows and Linux

### ISSUE THREAD

**Issue by abelykh0** [dotnet/corefx#39623] opened 2019-07-19 18:03 UTC
`StringComparer.InvariantCultureIgnoreCase` gives different results in Windows and Linux.

The example below returns 2 distinct values under Windows, and 3 under Linux. Using 3.0.100-preview6-012264.

```csharp
using System;
using System.Linq;
namespace ConsoleApp30
{
    class Program
    {
        static void Main(string[] args)
        {
            string[] tags = new[] { "Bærum", "Baerum", "abc", "abc" };
            var distinctTags = tags.Distinct(StringComparer.InvariantCultureIgnoreCase);
            foreach(string tag in distinctTags)
            {
                Console.WriteLine(tag);
            }
        }
    }
}
```

**Comment by Clockwork-Muse** [comment] 2019-07-19 18:14
See #29930 (and specifically [@tarekgh 's comment](https://github.com/dotnet/corefx/issues/29330#issuecomment-384718448)).  This is going to be "by design".

**Comment by abelykh0** [comment] 2019-07-19 18:20
Should be 29330, not 29930, please edit

**Comment by tarekgh** [comment] 2019-07-19 18:26
@Clockwork-Muse is correct. we depend on the underlying OS collation behavior as the comment https://github.com/dotnet/corefx/issues/29330#issuecomment-384718448 explain. 

And yes it is duplicate of the issue #29330.

**Closed by tarekgh** 2019-07-19 18:26 UTC
Labels: area-System.Globalization
