### ISSUE TITLE
CoreCLR publishing on Server no libraries are generated

### ISSUE THREAD

**Issue by Devmates** [dotnet/corefx#4937] opened 2015-12-11 12:10 UTC
I would like to publish my .NET Core console application on a server and I noticed the source code remains as it is and is not compiled into a library. Is it possible to choose for which platform you want to publish e.g. windows and compile the needed source code into a dll without having the complete source code?
In the old .NET I could build my application and get the exe file with the source code as dlls and I could execute it as a standalone application.
How can I achieve the same with a .NET Core console application?

**Comment by weshaggard** [comment] 2015-12-11 17:01
Yes with .NET Core that is definitely possible. From the sounds of it you are using dnx, and if so it is probably best you ask your question over in that repo.

**Comment by GuardRex** [comment] 2015-12-11 17:07
@Devmates Yes, ask questions over in https://github.com/aspnet/home/issues

... but ... Check the docs at https://docs.asp.net/en/latest/ and search the issues first.

You're specifically searching for everything dealing with "`dnu pack`" ... the command that produces NuGet package libraries. https://github.com/aspnet/Home/wiki/DNX-utility

**Comment by stephentoub** [comment] 2016-01-04 17:11
Closing as the issue is moving to a different repo.

**Closed by stephentoub** 2016-01-04 17:11 UTC
