### ISSUE TITLE
Performance issue with HttpClient on Ubuntu 16.04

### ISSUE THREAD

**Issue by EvgenyKhaliper** [dotnet/corefx#29597] opened 2018-05-09 08:47 UTC
Having singleton HttpClient as suggested impacts the performance.
Just toggle comment on New and Same client to reproduce.

Seems like a mystery to me as everyone everywhere suggests using singleton. Moreover just looking into HttpClientFactory which will be introduced in dotnet core 2.1 doesn't seem to solve the issue.

Someone has ideas ?

thanks

```c#
    class Program
    {
        private static string URL = "URL";
        
        static void Main(string[] args)
        {
            var options = new ParallelOptions
            {
                MaxDegreeOfParallelism = 100
            };
            
            SameClient(0, 400, options);
            
//            NewClient(0, 400, options);
        }

        private static void NewClient(int start, int end, ParallelOptions options)
        {
            var startNew = Stopwatch.StartNew();

            Parallel.For(start, end, options, i =>
            {
                using (var httpClient = new HttpClient())
                {
                    var res = httpClient
                        .SendAsync(new HttpRequestMessage(HttpMethod.Get, URL))
                        .GetAwaiter().GetResult();


                    res.EnsureSuccessStatusCode();
                }
            });
            startNew.Stop();
            Console.WriteLine($"new client each time took: {startNew.Elapsed.TotalSeconds}");
        }
        
        private static void SameClient(int start, int end, ParallelOptions options)
        {
            var httpClient = new HttpClient();
            var startNew = Stopwatch.StartNew();
            Parallel.For(start, end, options, i =>
            {
                var res = httpClient
                    .SendAsync(new HttpRequestMessage(HttpMethod.Get, URL))
                    .GetAwaiter().GetResult();

                res.EnsureSuccessStatusCode();
            });
            startNew.Stop();
            Console.WriteLine($"same client each time took: {startNew.Elapsed.TotalSeconds}");
        }
    }
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by rmkerr** [comment] 2018-05-09 15:52
Hey @EvgenyKhaliper, thanks for reporting this. What version of .NET Core are you targeting?

**Comment by stephentoub** [comment] 2018-05-09 15:59
I just tried your code on 2.1, using "http://bing.com" as URL, and I got:
```
same client each time took: 8.0957795
 new client each time took: 30.786809
```

**Comment by guy-lud** [comment] 2018-05-10 12:13
Hey @rmkerr, Thanks for your answer.
We targeted .NET Core 2.0.

We've also tried 2.1 with SocketHttpHandler and got ~37 sec for both calls

**Comment by karelz** [comment] 2018-05-10 16:47
@guy-lud did you try 2.1 RC? (release earlier this week)
Are you able to reproduce it on more than one machine? Are you from the same company/project as @EvgenyKhaliper? (or do we have 2 independent reports?)

Given that we cannot reproduce it & it goes against our expectations, it is suspicious and we will need more info.

**Comment by kasper3** [comment] 2018-05-10 16:59
I am seeing totally opposite result in `ubuntu:xenial` docker with `2.1.0-rc1` (added `<RuntimeFrameworkVersion>2.1.0-rc1</RuntimeFrameworkVersion>` in csproj with latest sdk):

```
same client each time took: 38.8719781
new client each time took: 14.3202461
```

**Comment by rmkerr** [comment] 2018-05-10 17:02
I'd definitely expect you to see improved performance in most situations when using the new handler in 2.1. @guy-lud is it possible that the bottleneck you're seeing is on the server side?

**Comment by rmkerr** [comment] 2018-05-10 17:30
@kasper3 that's definitely not the expected behavior. What server are you connecting to when you measure that?

**Comment by kasper3** [comment] 2018-05-10 17:45
I used `URL = "http://bing.com"` and `<RuntimeFrameworkVersion>2.1.0-rc1</RuntimeFrameworkVersion>` in csproj.

**Comment by EvgenyKhaliper** [comment] 2018-05-10 18:54
@karelz and @rmkerr 
Sorry it took some time to get here again.   

As @guy-lud said we are targeting 2.0 for now and we are from the same project.

Moreover, we are running Ubuntu 16.04 as OS not as VM or docker container.

**Comment by karelz** [comment] 2018-05-10 20:47
We have very different numbers from various people (all testing on Ubuntu 16.04).
How stable are the numbers? Can someone try to dump per-request statistics and dig into those? (to avoid one XXL long request to skew the numbers)

@wfurt can you please help here?

**Comment by kasper3** [comment] 2018-05-10 20:56
@karelz, the test case given in first comment is not stable as `NewClient` method intermittently thwos TaskCanceledException, therefore I wasn't able to successfully reproduce the results consecutively. That said, running in docker, running in VM, running in WSL and running on bare metal, all using Ubuntu 16.04 may have slight differences as well, but not a huge gap if we are all testing with `http://bing.com` from different geo-locations.

**Comment by EvgenyKhaliper** [comment] 2018-05-10 21:32
number of iterations: 100
same client: 23s
new client: 14s

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by stephentoub** [comment] 2018-05-10 21:48
> now to bing.com

What url were you using before? Have you tried against some server that's opened by you and stable in response performance (which a public server with many different endpoints and traffic loads won't be)?

What results do you get with 2.1?

What results do you get if you make all requests serially rather than in parallel? i.e. stop using Parallel.For?

**Comment by EvgenyKhaliper** [comment] 2018-05-11 19:10
@stephentoub 

Thanks for the reply,

- I was using a stable AWS instance with the API i'm building.
- Exactly same results with  "sdk": { "version": "2.1.300-rc1-008673" }
- Whole point is that it ( HttpClient ) did not perform well under pressure in our product, this is where all the 'check HttpClient performance' has started. So do you think I should test in sync ?
-  HTTP
- Did not see any difference, can you point to something more specific in the response to look for ?

**Comment by wfurt** [comment] 2018-05-14 06:45
I also try to reproduce the results and same client is little bit faster than new client.
I try that with my local system as well as AWS instance.
can you please get packet captures @EvgenyKhaliper.

**Comment by wfurt** [comment] 2018-05-14 20:56
I did another round of testing agains my local server - to avoid external servers and still get similar results as before. This time, the same client is almost 3x faster. 
With new HttpClient, every request is new TCP connection - and that will cost you some when going to internet (or doing SSL one day). With reusing single HttpClient, I see 16 connections and all requests are multiplexed via that connection pool. 

I also add some timing information for each request. 
```c#
            Parallel.For(start, end, options, i =>
            {
                var started = startNew.ElapsedMilliseconds;
                var res = httpClient
                    .SendAsync(new HttpRequestMessage(HttpMethod.Get, URL))
                    .GetAwaiter().GetResult();
                var ended = startNew.ElapsedMilliseconds;
                Console.WriteLine("finished in {0}", ended-started);
                res.EnsureSuccessStatusCode();
            });
```
I see large variation between requests, even for local server.
But you can give it try @EvgenyKhaliper to see if whole result is skewed by few very long requests.

**Comment by karelz** [comment] 2018-05-19 00:33
Unable to reproduce, closing. If you have more details / evidence what is happening, please let us know and we can reopen.

**Closed by karelz** 2018-05-19 00:33 UTC
Labels: area-System.Net.Http, needs more info, os-linux, question
