### ISSUE TITLE
Process.VirtualMemorySize64 (at least) is giving corrupt values

### ISSUE THREAD

**Issue by mshobohm** [dotnet/corefx#20812] opened 2017-06-08 10:56 UTC
System.Diagnostics.Process.VirtualMemorySize64 has an unexpected High Value (Windows 10 x64)

Example:
```c#
using System;
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("VirtualMemorySize:{0:#,0.}", System.Diagnostics.Process.GetCurrentProcess().VirtualMemorySize64);
        Console.ReadKey();
    }
}
```

Output:
VirtualMemorySize:2.199.520.038.912
Expected output : <= 150 MB as with .NET Classic

**Comment by danmosemsft** [comment] 2017-06-08 15:53
I repro this. A regression from 1.1 (and desktop)

**Comment by danmosemsft** [comment] 2017-06-08 16:07
Seems like an alignment thing but it's not obvious from a quick diff of sources. @karelz is someone available to have a quick look in @Priya91 's absence?

**Comment by stephentoub** [comment] 2017-06-08 23:39
I don't think this is a regression in Process; if anything, it appears to be a change in the runtime.
@janvorli, @jkotas, has something changed for 2.0 with regards to how the runtime handles memory that would impact the value returned from VirtualMemorySize?

The reason I don't think it's a Process regression is if I use a .NET 4.7 or .NET Core 1.1 app to get the VirtualMemorySize64 for a .NET Core 2.0 process, I see similarly large values.

**Comment by karelz** [comment] 2017-06-08 23:43
It is not regression, moving it to 2.1 then.

**Comment by stephentoub** [comment] 2017-06-08 23:49
> It is not regression, moving it to 2.1 then.

@karelz, I didn't say it's not a regression, I said I don't think it's a regression in Process.  There could still be a runtime issue.  Let's wait to hear back to my question before moving this around.

**Comment by jkotas** [comment] 2017-06-09 00:17
It does not repro for me:

```
C:\repro>dotnet run
VirtualMemorySize:492,863,488

C:\repro>dotnet run -c Release
VirtualMemorySize:492,929,024

C:\repro>dotnet --version
2.0.0-preview1-005977
```

**Comment by jkotas** [comment] 2017-06-09 00:18
> has something changed for 2.0 with regards to how the runtime handles memory that would impact the value returned from VirtualMemorySize?

Nothing I am aware of.

**Comment by stephentoub** [comment] 2017-06-09 00:38
> dotnet --version

That's the version of dotnet/SDK, or the runtime the test is running against? (or both)

**Comment by jkotas** [comment] 2017-06-09 01:09
The runtime version is 2.0.0-preview1-002111-00 (the shared runtime that comes with the preview1 build).

What I have done: [Download preview1](https://www.microsoft.com/net/core/preview), `dotnet new console`, copy&paste your snipped to program.cs, `dotnet run`.

Could you please share the runtime versions that it repros on for you?

**Comment by stephentoub** [comment] 2017-06-09 02:19
When I repeat what you did, @jkotas, I get the same basic output as you.

It looks like this might be caused by the host somehow?  If I do a `dotnet publish -r win10-x64` to get a standalone directory (after modifying the csproj to include `<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>`, and in there I do `.\tmpapp.exe` or `dotnet tmpapp.dll`, I get output like `526,970,880`.  If I instead copy `corerun` to that folder and do `corerun tmpapp.dll`, I get output like `2,199,548,268,544`.

But if I add a test like:
```C#
        [Fact]
        public void PrintVirtualMem()
        {
            Console.WriteLine("VirtualMemorySize:{0:#,0.}", System.Diagnostics.Process.GetCurrentProcess().VirtualMemorySize64);
        }
```
I also get the absurdly large output number, yet the tests are executed using dotnet (though the one in the repo)... so I'm not sure exactly what's happening.

**Comment by stephentoub** [comment] 2017-06-09 03:08
Looks like this may have something to do with Control Flow Guard...

**Comment by stephentoub** [comment] 2017-06-09 03:33
Yeah, definitely seems to be related to Control Flow Guard.  The `dotnet` in preview1 doesn't have it enabled:
```
8160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   Terminal Server Aware
```
whereas the one in corefx (which is newer) does:
```
C160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   Control Flow Guard
                   Terminal Server Aware
```
as does corerun.exe
```
C160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible
                   Control Flow Guard
                   Terminal Server Aware 
```
And looking in procexp.exe, if I add columns for CFG and Virtual Size, almost all of the processes on the machine with CFG enabled have sizes like 2,147,586,904K.  So it looks like this is just behavior enacted by Windows, rather than an issue with the runtime or libraries.

cc: @ellismg

**Closed** 2017-06-09 03:34 UTC
Labels: area-System.Diagnostics.Process

**Comment by jkotas** [comment] 2017-06-09 03:47
The size of the CFG bitmap (that is huge) is accounted for in the VirtualSize by Windows. It is technically correct because the CFG bitmap does occupy process address space, but it certainly takes people by surprise when they see the number for the first time...

**Comment by stephentoub** [comment] 2017-06-09 03:50
Thanks, @jkotas.

**Comment by OrbintSoft** [comment] 2018-11-01 13:48
ok the runtime read the correct value, but that value has no useful meaning.

How can I get the real virtual memory available for the process?

**Comment by janvorli** [comment] 2018-11-01 14:35
@OrbintSoft the Process.VirtualMemorySize64 doesn't return the amount of available VM for the process, but rather the amount of virtual memory currently used by the process. The total VM space available for a process is a fixed value (depending on the processor architecture and Windows version and it is described here: https://docs.microsoft.com/en-us/windows/desktop/Memory/memory-limits-for-windows-releases
Can you please share what you really want to get and what you are planning to use it for?

**Comment by OrbintSoft** [comment] 2018-11-01 20:18
I was porting a Java library to .NET, in the original library gets the available memory by JVM to determine how much cache to allocate.  In .NET I dunno how to reproduce this functionality, except to set a fixed amount of cache.

The  library is a .NET standard library so can work on many different platforms.
I remember for example that on UWP for windows mobile you have a limited amount of memory usable by apps depending on the model and that value can be get with MemoryManager.AppMemoryUsageLimit

**Comment by OrbintSoft** [comment] 2018-11-01 20:43
@jkotas

`Runtime runtime = Runtime.getRuntime();`

the original library uses these APIs:

```
runtime.totalMemory() 
runtime.maxMemory()
runtime.freeMemory() 
```


I was thinking to use WorkingSet64 for total memory and VirtualMemorySize64 for max size, but they have completely different meaning.

I am rethinking logic to adapt to the new environment, I dont need really to get equivalent values of Java API, but arguing how much cache I can allocate it's a big deal.

I  would like to have MemoryManager.AppMemoryUsageLimit API in .netstandard :(

**Comment by jkotas** [comment] 2018-11-01 20:49
There are no APIs like this today. https://github.com/dotnet/corefx/issues/25617 was start of a proposal to add them, but it did not get too much traction so far.

**Comment by mshobohm** [comment] 2018-11-02 10:45
I Think Microsoft should add a seperate new class for all performance values, which the user needs. Most wanted for me is the "commit" value. These values should be clearly defined and kept stable, even if new feutures are added. A good example for performance analysis is the vmmap.exe frome the sysinternals suite. You should be able to get exact performance analysis value from inside a .NET Core Application.
