### ISSUE TITLE
System.Text.Json fails to serialize Dictionary with int keys

### ISSUE THREAD

**Issue by israellot** [dotnet/corefx#41345] opened 2019-09-26 07:12 UTC
```
var dictionary = new Dictionary<int, int>()
            {
                [0] = 1
            };

 var serialized = System.Text.Json.JsonSerializer.Serialize(dictionary);
```

This simple serialization is handled well by the former default Newtonsoft json library by serializing the int key as string. On System.Text.Json is throws a not supported exception.

**Comment by ahsonkhan** [comment] 2019-09-26 07:58
This is a known issue and is a duplicate of https://github.com/dotnet/corefx/issues/40120

**Closed by ahsonkhan** 2019-09-26 07:58 UTC
Labels: area-System.Text.Json
