### ISSUE TITLE
System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream failed in CI

### ISSUE THREAD

**Issue by v-haren** [dotnet/corefx#24600] opened 2017-10-12 09:38 UTC
Failed test: System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream 

Configuration: osx10.12_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3296/testReport/System.Diagnostics.Tests/ProcessStreamReadTests/TestAsyncErrorStream/

MESSAGE:
~~~
Assert.Equal() Failure\n ↓ (pos 0)\nExpected: System.Diagnostics.Process.Tests started ···\nActual: A fatal error occurred, the required libr···\n ↑ (pos 0)
~~~

STACK TRACE:
~~~
at System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Diagnostics.Process/tests/ProcessStreamReadTests.cs:line 50
~~~

**Comment by Jiayili1** [comment] 2017-10-20 01:34
failed tests:
 System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentOfChildProcess
 System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream
 System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncOutputStream
 System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncOutputStream
 System.Diagnostics.Tests.ProcessStreamReadTests.TestManyOutputLines
 System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncHalfCharacterAtATime
 System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream

**Comment by karelz** [comment] 2017-12-07 21:27
Duplicate of #24601

**Closed by karelz** 2017-12-07 21:27 UTC
Labels: area-System.Diagnostics.Process, test bug, test-run-core
