### ISSUE TITLE
Make System.Net tests reliable

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#14519] opened 2016-12-14 18:47 UTC
We have lots of test failures. It is not efficient to track them in individual issues. This one tracks them all, until we are near-clean.

**Comment by ianhays** [comment] 2017-01-13 18:05
The **NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success** test is failing intermittently on Outerloop runs of RHEL7.2 Debug and Release. In the past 3 weeks it has failed 5 times with the following errors:
```
RHEL Debug53, Release55, Release63, Debug65
11:39:32      System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success [FAIL]
11:39:32         System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
11:39:32         ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
11:39:32         -------- System.ComponentModel.Win32Exception : GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument).
11:39:32         Stack Trace:
11:39:32               at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
11:39:32               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
11:39:32               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
11:39:32            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_debug/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs(284,0): at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success()
11:39:32            ----- Inner Stack Trace -----
11:39:32               at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
11:39:32               at System.Net.Security.NegotiateStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
11:39:32               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
11:39:32            ----- Inner Stack Trace -----

RHEL Release59
System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success [FAIL]
00:21:10         System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
00:21:10         ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
00:21:10         -------- System.ComponentModel.Win32Exception : GSSAPI operation failed with error - An invalid status code was supplied (No Kerberos credentials available).
00:21:10         Stack Trace:
00:21:10               at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
00:21:10               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
00:21:10            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_release/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs(285,0): at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_StreamToStream_KerberosAuthDefaultCredentials_Success()
00:21:10            ----- Inner Stack Trace -----
00:21:10               at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
00:21:10               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
00:21:10            ----- Inner Stack Trace -----
```

It is the only NegotiateStream test to fail consistently with these errors which suggests to me that the issue is with either the test or the code, and not [the testing infra](https://github.com/dotnet/corefx/issues/14519)

**Comment by ianhays** [comment] 2017-01-13 18:06
related: [NegotiateStream_StreamToStream_AuthToHttpTarget_Success test failing on RHEL ](https://github.com/dotnet/corefx/issues/7707)

**Comment by ianhays** [comment] 2017-01-13 18:10
**NegotiateStream_EchoServer_ClientWriteRead_Successive_Sync_Success** appears to also be failing very seldom (twice since December 1st) on RHEL Release Outerloop with the Success error:

```
RHEL Release63
00:21:54      System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Sync_Success [FAIL]
00:21:54         System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
00:21:54         ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
00:21:54         -------- System.ComponentModel.Win32Exception : GSSAPI operation failed with error - An invalid status code was supplied (Success).
00:21:54         Stack Trace:
00:21:54               at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
00:21:54               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
00:21:54            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_rhel7.2_release/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs(320,0): at System.Net.Security.Tests.NegotiateStreamTest.NegotiateStream_EchoServer_ClientWriteRead_Successive_Sync_Success()
00:21:54            ----- Inner Stack Trace -----
00:21:54               at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
00:21:54               at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
00:21:54            ----- Inner Stack Trace -----
```

The only other test to fail with this same inner exception is **NegotiateStream_StreamToStream_AuthToHttpTarget_Success** which failed in a different run.

**Comment by ianhays** [comment] 2017-01-13 18:13
Those are the only three NegotiateStream tests that are failing consistently enough for me to get console output for them. If we disable any tests for stability on RHEL, it should be these three and no others.

**Comment by Jiayili1** [comment] 2017-01-22 02:51
This issue occur on OuterLoop_Windows10_release (build#76), failed test: System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_StreamToStream_Write_ReadByte_Success

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_release/lastFailedBuild/consoleText

Message:
~~~
System.AggregateException : One or more errors occurred. (VirtualNetwork: Timeout reading the next frame.) (The credentials supplied to the package were not recognized)
        ---- System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
        ---- System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
~~~

Stack Trace:
~~~
at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(401,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.DoHandshake(SslStream clientSslStream, SslStream serverSslStream)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\tests\FunctionalTests\SslStreamStreamToStreamTest.cs(248,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Write_ReadByte_Success()
           ----- Inner Stack Trace #1 (System.TimeoutException) -----
           D:\j\workspace\outerloop_win---6835b088\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs(39,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
           D:\j\workspace\outerloop_win---6835b088\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(119,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
              at System.Threading.Tasks.Task`1.InnerInvoke()
              at System.Threading.Tasks.Task.Execute()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           D:\j\workspace\outerloop_win---6835b088\src\Common\src\System\Threading\Tasks\TaskToApm.cs(116,0): at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\FixedSizeReader.cs(143,0): at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslState.cs(731,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           ----- Inner Stack Trace #2 (System.ComponentModel.Win32Exception) -----
           D:\j\workspace\outerloop_win---6835b088\src\Common\src\Interop\Windows\sspicli\SSPIWrapper.cs(167,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(407,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslStreamPal.Windows.cs(131,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(676,0): at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(783,0): at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SecureChannel.cs(706,0): at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslState.cs(767,0): at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslState.cs(983,0): at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslState.cs(1145,0): at System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           D:\j\workspace\outerloop_win---6835b088\src\System.Net.Security\src\System\Net\Security\SslState.cs(731,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
~~~

**Comment by steveharter** [comment] 2017-01-23 20:19
Please don't comment on new traces etc unless they contain some information to help find the cause, such as patterns or related issues. If the issue is not intermittent\random (i.e. it is a test blocking CI issue), it should have its own bug. I deleted some of the traces here because this issue was getting unwieldy.

We already know the test failures from the jdash site. Here's a sample query - http://jdash.azurewebsites.net/builds/test?viewName=dotnet_corefx&startDate=2017-01-15&limit=10. Note that results this will include master as well as release branches.

**Comment by ianhays** [comment] 2017-03-21 18:13
This test issue is no longer providing any value now that we've created issues for each bug since we have far fewer System.Net test failures now. There aren't any tests marked with ActiveIssue with this bug, so I'm closing it.

**Closed by ianhays** 2017-03-21 18:13 UTC
Labels: area-System.Net, test enhancement, test-run-core
