### ISSUE TITLE
String containing UTF-8 pairs gets mutated when passed to a custom Attribute

### ISSUE THREAD

**Issue by TheSatoshiChiba** [dotnet/corefx#31583] opened 2018-08-03 15:06 UTC
This issue started out here: https://github.com/nunit/nunit3-vs-adapter/issues/534
The link contains some more information and tests I did. At first I thought this was an issue with the `NUnit` adapter but I could reproduce it without it.

-----
## The Observation

A string given to a simple custom `Attribute` is being mutated when accessed via reflection. Consider the following string `"xx\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51"` which contains some [Unicode pairs](https://www.fileformat.info/info/unicode/char/10151/index.htm). In hex this value is: `7807800D851DD0D851DD0D851DD0D851DD`. When being accessed via reflection the resulting value is: `78078000FDFF0D851DD0D851DD0D851DD`.  This seems to only happen on Ubuntu. I couldn't reproduce this issue on Windows or OSX. Also older runtime versions seem to be working fine. .NET Core 2.0 didn't have this bug.

## The Test Case

```csharp
using System;
using System.Text;
using System.Reflection;

namespace Test {
    class SomeAttribute : Attribute {
        public string Value { get; }

        public SomeAttribute( string value ) {
            Value = value;
        }
    }

    class SomeType {
        [SomeAttribute( "xx\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51" )]
        public void SomeMethod() {
        }
    }

    class Program {
        static void Main( string[] args ) {
            // What is expected:
            var attribute = new SomeAttribute( "xx\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51" );
            foreach ( var b in Encoding.Unicode.GetBytes( attribute.Value ) ) {
                Console.Write( "{0:X} ", b );
            }
            Console.WriteLine();

            // What it actually is:
            var assembly = Assembly.GetCallingAssembly();
            foreach ( var types in assembly.GetTypes() ) {
                foreach ( var method in types.GetMethods() ) {
                    attribute = method.GetCustomAttribute<SomeAttribute>();
                    if ( attribute != null ) {
                        foreach ( var b in Encoding.Unicode.GetBytes( attribute.Value ) ) {
                            Console.Write( "{0:X} ", b );
                        }
                        Console.WriteLine();
                        return;
                    }
                }
            }
        }
    }
}

```

The output as hex is just for clarification of what is actually different. Even when just printed to the console the string has an invalid character question mark when accessed via reflection.

## The Environment

The output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by 0xd4d** [comment] 2018-08-03 23:56
The string in the custom attribute is stored as a UTF8 encoded string but the string in the method body is stored as UTF16 (it's in the #US heap). So it seems to be some problem with the UTF8 encoder and/or decoder. What happens when you try to UTF8 encode the string in the method body?

```C#
var expectedString = "xx\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51";
var d = Encoding.UTF8.GetBytes(expectedString);
var decodedString = Encoding.UTF8.GetString(d);
Console.WriteLine(expectedString == decodedString);
```

**Comment by TheSatoshiChiba** [comment] 2018-08-05 12:41
I don't think it is a proiblem with the endcoder/decoder as the problem persists even when not using the encoder. Simply print the string as-is to the console and you'll aready see the difference. I can do the test on Monday when I am back at work but my suspicion (based on previous tests) is that it will just work as expected.

**Comment by TheSatoshiChiba** [comment] 2018-08-06 08:17
I verified your example and it works perfectly fine. Which means it is not a problem with the Encoder. This issue is quite serious tbh as it affects certain unit tests in our product.

Some more information copied from the other issues I opened:
`\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51` works fine when passed to the attribute.
`x\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51` doesn't work and will be mutated.
`xx\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51` doesn't work and will be mutated.
`\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51x` works fine.
`\ud800\udd51\ud800\udd51\ud800\udd51\ud800\udd51xx` doesn't work and will be mutated.

So it seems to me that it has something to do with the length of the string that I pass in. Specifically if `\ud800\udd51` is within a string of `>= 14` (?) characters.

**Comment by jkotas** [comment] 2018-08-06 14:15
This looks like https://github.com/dotnet/coreclr/issues/18269 . The fix will be included in Microsoft.NETCore.App 2.1.3.

**Comment by svick** [comment] 2018-08-06 20:14
As far as I can tell, this is an issue with UTF-8 decoding done by the CLR. It was fixed in https://github.com/dotnet/coreclr/pull/18294/https://github.com/dotnet/coreclr/pull/18309, which should be included in the next servicing release of .Net Core 2.1.

**Comment by karelz** [comment] 2018-08-15 02:02
Closing as duplicate of https://github.com/dotnet/coreclr/issues/18269

**Closed by karelz** 2018-08-15 02:02 UTC
