### ISSUE TITLE
AccessViolationException in System.Data.SqlClient when a second copy is loaded at application shutdown

### ISSUE THREAD

**Issue by muratg** [dotnet/corefx#4110] opened 2015-10-23 20:31 UTC
We are seeing the following error [on one of the EF tests](https://github.com/aspnet/EntityFramework/blob/de4f73e9517ba75f69064e45ff30d2755a3981d3/test/EntityFramework.CrossStore.FunctionalTests/EndToEndTest.cs#L21).  

Not sure if it’s SqlClient or CoreCLR issue.  

```
[12:16:22]Step 6/6: Run tests (Command Line) (3m:53s)
[12:17:56][Step 6/6] xunit-test (2m:19s)
[12:19:42][xunit-test] Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[12:19:42][xunit-test]    at System.Data.SqlClient.SNINativeMethodWrapper.SNITerminate()
[12:19:42][xunit-test]    at System.Data.SqlClient.SNILoadHandle.ReleaseHandle()
[12:19:42][xunit-test]    at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
[12:19:42][xunit-test]    at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
[12:19:42][xunit-test]    at System.Runtime.InteropServices.SafeHandle.Finalize()
[12:20:15][xunit-test] Step Run tests (Command Line) failed
```

**Comment by divega** [comment] 2015-10-24 01:37
Note that this issue makes a very simple test fail and may be blocking for RC1.

**Comment by saurabh500** [comment] 2015-10-26 17:33
@muratg I am assuming this is a Windows Test failure based on the classes being loaded. 

The SNITerminate calls the native code from sni.dll 
There were no changes that were made to any of this code in many months. 

We are looking to find more information on why this could be happening. Is this a consistent test failure or an intermittent failure ?

**Comment by muratg** [comment] 2015-10-26 18:45
@divega can point you to the right direction.  A very simple test is failing while I believe it was passing before.

**Comment by divega** [comment] 2015-10-26 18:52
@smitpatel will work on a simplified repro for this.

**Comment by saurabh500** [comment] 2015-10-26 19:55
Can you confirm if this was a windows run?

**Comment by smitpatel** [comment] 2015-10-26 20:34
Program.cs
```
using System.Data.SqlClient;
using Microsoft.Data.Entity;

namespace SqlClientError
{
    public class Program
    {
        public void Main(string[] args)
        {

            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                ctx.Blogs.Add(new Blog());

                ctx.SaveChanges();
            }
        }
    }


    public class Blog
    {
        public int Id { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; } 

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = "(localdb)\\MSSQLLocalDB", InitialCatalog = "sqlerror", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }
}
```
Project.json
```
{
  "version": "1.0.0-*",
  "description": "SqlClientError Console Application",
  "authors": [ "smpatel" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-*",
    "EntityFramework.Commands": "7.0.0-rc1-*"
  },

  "commands": {
    "SqlClientError": "SqlClientError"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23109",
        "System.Console": "4.0.0-beta-23109",
        "System.Linq": "4.0.0-beta-23109",
        "System.Threading": "4.0.10-beta-23109",
        "Microsoft.CSharp": "4.0.0-beta-23109"
      }
    }
  }
}
```
Console output
```
PM> dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-15996
 Type:         CoreClr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86

PM> dnx run
dnx : 
At line:1 char:1
+ dnx run
+ ~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Unhandled Exception:
 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Data.SqlClient.SNINativeMethodWrapper.SNITerminate()
   at System.Data.SqlClient.SNILoadHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

**Comment by saurabh500** [comment] 2015-10-27 01:32
Based on the repro I did the following: 
I installed coreclr x86 and x64 and replaced the sni.dll in the dnx runtime with sni.dll built from dev environment. 

I ran the above code for repro and following is the test matrix.

On x86 Arch installation
x64 chk -- Pass
x64 ret -- Pass
x86 chk -- Fail
x86 ret -- fail

On x64 runtime installation
x64 chk -- Fail
x64 ret -- Fail
x86 chk -- Pass
x86 ret -- Pass

For reasons unknown currently, the installation architecture has inverse pairing with the sni.dll success.

**Comment by saurabh500** [comment] 2015-10-27 18:08
This is not a packaging issue.
I tested the code in the Beta8 build and the Repro is not breaking. 
This should be a CoreCLR issue.

**Comment by divega** [comment] 2015-10-27 22:05
@moozzyk this may be a long shot, but is it possible that this has to do with the new native loading code in DNX? Incidentally we had another report that seemed to indicate we attempt to load the wrong native library in https://github.com/aspnet/EntityFramework/issues/3573.

cc @muratg

**Comment by saurabh500** [comment] 2015-10-27 22:21
@divega 
I checked the test run against a SqlServer. I ran into the same problem as above.

Few observations: 
1. The native code seems to be loading fine. The test completes the run and the results of the repro posted above are as expected. I put some Console Statements which show that all executions were good till the last line of the test. I verified that the Database on the SqlServer has the Blog table in the Database that I provided.
2. The AV occurs during application shutdown/unloading. Before that all calls to the Native code seems to be executing fine.

**Comment by divega** [comment] 2015-10-27 23:38
@saurabh500 thanks for clarifying that. I misinterpreted what you said before about the installation architecture having inverse pairing with the success of sni.dll.

**Comment by saurabh500** [comment] 2015-10-27 23:53
@divega That's still a bit of a mystery. With inverse pairing, the tests succeed. So a sni.dll for x64 if dropped in x86 installation of the CoreClr, leads to test pass without any exception and vice versa. I noticed it and I put it in the notes here.

I looked at the headers of sni.dll which is installed by default with x86 coreclr. (dumpbin /headers sni.dll) The default sni.dll installed is x86 as expected. However when replaced with a x64 sni.dll built from the source, the AV starts occurring.

**Comment by divega** [comment] 2015-10-28 00:33
Another observation: Currently there is a copy of sni.dll directly located in the dnx runtime folder. Before native assembly loading was implemented, that copy of sni.dll helped us because it get picked up seamlessly. 

However @smitpatel and I just verified that removing that copy from the runtime folder makes the repro and the tests pass.

If I understand things correctly if anything is wrong with the native library on the runtime folder, that could explain the inverse pairing you are seeing, e.g. it seems that native assembly loading is actually working correctly but the presence of the sni.dll is taking precedence over the one in the package for a given architecture. 

We cannot explain why the sni.dll on that folder could be stale or incorrect though. We have code that extracts the sni.dll from a package every time we pull CoreCLR. Maybe the package where we take it from is stale?

**Comment by saurabh500** [comment] 2015-10-28 01:16
This is interesting. 

I verified this behavior at my end as well. If I delete the Sni.dll, the test succeeds.

I am not sure about how native image compilation is working. 
Based on what I observed, everytime i install a CoreCLR runtime, the native assemblies are compiled.
The console shows the following output 

    Adding C:\Users\sausing\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-16031\bin to process PATH
    Compiling native images for dnx-coreclr-win-x86.1.0.0-rc1-16031 to improve start up performance...

This process results in a System.Data.SqlClient.ni.dll 
If this *.ni.dll is self sufficient (and doesn't need sni.dll to operate) then it would need the native information from somewhere for its creation. The source of that information should be the native SNI.dll downloaded with the CoreCLR. If this is the case, then the sni.dll should be the correct dll.
Let me know if this is an incorrect assumption. I am not aware of the changes in this area. 

cc @chcosta do you have insights into this? 

With the Native assembly generation, I wonder if we need the sni.dll at all in the bin folder?

**Comment by divega** [comment] 2015-10-28 05:24
I don't think this is related to the generation of native images. I think the native images of System.Data.SqlClient are are not self sufficient (at least in Windows, yet) and they still call into sni.dll. The reason sni.dll is no longer needed in the runtime's bin folder is that we now have native assembly loading in dnx that will find it in the right runtime package.

My theory is still that there is something wrong in sni.dll in the runtime bin folder that causes the AV exception. I suspect this implies that there is a stale or corrupt sni.dll in one of the packages produced by the CoreCLR build, but we haven't confirmed this yet.

**Comment by joshfree** [comment] 2015-10-29 06:37
@LLITCHEV could this be the same JIT issue as https://github.com/dotnet/coreclr/issues/1831?

**Comment by LLITCHEV** [comment] 2015-10-29 06:57
This looks like a Windows issue. The Issue 1831 is only related to System V OS-es. The ABI work PR-ed with PR "Implementation of System V ABI struct passing. #1806" is related only to Linux. There are no any differences in the codegen before and after that PR (no any asm diffs). Looking at the call stack it looks like the VM is doing a GC.

**Comment by joshfree** [comment] 2015-10-29 17:23
okay thanks @LLITCHEV for taking a look

**Comment by saurabh500** [comment] 2015-10-29 17:34
I updated the DNX today and the version that I have is 1.0.0-rc1-16048 arch x86 
I cannot reproduce this issue any more.
@divega or @smitpatel Can you verify?

**Comment by smitpatel** [comment] 2015-10-29 17:46
@saurabh500, @divega  The issue is not happening anymore (even EF build works fine.) Interesting thing is sni.dll is no longer present in runtime installation folder for 1.0.0-rc1-16048. I am not aware what changes made it to disappear but as per previous observation without sni.dll in runtime installation, the exception no longer appears.

**Comment by divega** [comment] 2015-10-29 17:53
We removed sni.dll from the runtime's bin directory with https://github.com/aspnet/dnx/commit/44ea661211118f59974c83574e014f3fe1499522 after we confirmed that without it the AV didn't occur. 

It remains unexplained why loading the file from there caused problems. I confirmed that the sni.dll that used to be placed in the runtime directory was a copy of the one in the runtime.win7-x86.System.Data.SqlClient.sni package.

**Comment by divega** [comment] 2015-10-29 18:23
One last observation in case it helps someone: 

I verified using Process Explorer (couldn't see it in the Modules window) on 1.0.0-rc1-16043 coreclr x86 (which still contains sni.dll on the runtime's bin folder) that while the program is running, the copy of sni.dll from the runtime.win7-x86.System.Data.SqlClient.sni package is loaded in memory. When later the AV occurs, both the copy from the package and the one from the runtime are loaded into memory.

I don't have any insights on why a second copy would be loaded at application shutdown but I suspect it is the cause of the AV.

Since the problem no longer occurs after we removed sni.dll from the runtime I am comfortable with closing this.

cc @moozzyk

**Comment by saurabh500** [comment] 2015-10-29 20:41
@joshfree I think we can remove this from the RC1 Blocker list. Let me know what you think.
With the change in DNX, the packaging has been modified to mitigate this issue.

This is still a concern because with the absence of Native images, this issue will exist where System.Data.SqlClient.dll and sni.dll are present in the runtime folder.

**Comment by joshfree** [comment] 2015-10-29 22:13
@saurabh500 I agree this can be removed from the rc1 list.

**Comment by saurabh500** [comment] 2016-01-26 04:01
Not able to reproduce this issue any more. Please reopen if found.

**Closed by saurabh500** 2016-01-26 04:01 UTC
Labels: System.Data
