### ISSUE TITLE
System.IO.fileSystem.Watcher.Tests has a flaky test causing build failures.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#1670] opened 2015-05-08 00:37 UTC
FileSystemWatcher_4000_Tests.FileSystemWatcher_IncludeSubDirectories_Directory [FAIL]
        Didn't observe a created event within 500ms
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\Utility\Utility.cs(94,0): at Utility.ExpectEvent(WaitHandle eventOccured, String eventName, Int32 timeout)
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.IncludeSubDirectories.cs(68,0): at FileSystemWatcher_4000_Tests.FileSystemWatcher_IncludeSubDirectories_Directory()
  Finished:    System.IO.FileSystem.Watcher.Tests

**Comment by akoeplinger** [comment] 2015-05-08 00:38
Dupe of #1657

**Closed** 2015-05-08 00:50 UTC
