### ISSUE TITLE
Add Unsafe.AsRef<T>(in T value) overload

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#26757] opened 2018-02-01 20:44 UTC
Sometimes you really just want to turn a "ref readonly" variable into a standard "ref" variable, perhaps so that it can be passed to `Unsafe.As<TFrom, TTo>` or `Unsafe.ReadUnaligned<T>`. Since we don't want to add overloads to all of our unsafe APIs that take readonly-qualified parameters, we should have a utility method that strips the readonly qualifier from its input.

/cc @KrzysztofCwalina @jkotas @ahsonkhan

**Comment by jkotas** [comment] 2018-02-01 20:47
Duplicate of https://github.com/dotnet/corefx/issues/23916 . Already done.

**Closed by jkotas** 2018-02-01 20:47 UTC

**Comment by GrabYourPitchforks** [comment] 2018-02-01 21:03
Looks like I was pulling the System.Runtime.CompilerServices.Unsafe package from nuget.org, not myget.org. That resulted in using an out-of-date package that didn't have these APIs.

**Comment by ahsonkhan** [comment] 2018-02-01 23:20
For reference: https://github.com/dotnet/corefx/blob/83f35ef9a79b5cd1412aeaad8d2cb84e1bfe73c4/src/System.Runtime.CompilerServices.Unsafe/ref/System.Runtime.CompilerServices.Unsafe.cs#L19
