### ISSUE TITLE
BeginSend_AsyncOperationCompletes_Success failure in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4363] opened 2015-11-06 00:07 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6206/
```
System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success
MESSAGE:
System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2955 at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2900 at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 297 at System.Net.Sockets.UdpClient.<SendAsync>b__4(Byte[] targetDatagram, Int32 targetBytes, IPEndPoint targetEndpoint, AsyncCallback callback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 618 at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 617 at System.Net.Sockets.UdpClientAPMExtensions.BeginSend(UdpClient client, Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\src\System\Net\Sockets\SocketAPMExtensions.cs:line 1184 at System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\UdpClientTest.cs:line 51
```

**Comment by davidsh** [comment] 2015-11-06 00:09
cc: @pgavlin @josguil

**Comment by stephentoub** [comment] 2015-11-09 22:04
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/6090/console

Could someone take a look at fixing the test or disabling it?
```
System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success [FAIL]
        System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2944,0): at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(2889,0): at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs(297,0): at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs(618,0): at System.Net.Sockets.UdpClient.<SendAsync>b__4(Byte[] targetDatagram, Int32 targetBytes, IPEndPoint targetEndpoint, AsyncCallback callback, Object state)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
              at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs(617,0): at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\src\System\Net\Sockets\SocketAPMExtensions.cs(1184,0): at System.Net.Sockets.UdpClientAPMExtensions.BeginSend(UdpClient client, Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\UdpClientTest.cs(51,0): at System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success()
```

**Comment by davidsh** [comment] 2015-11-09 22:09
I will submit a PR now and disable the test.

**Comment by stephentoub** [comment] 2015-11-09 22:10
Thanks, David.  Presumably from the "test bug" label we do believe this is a bug in the test rather than in the Sockets implementation?

**Comment by davidsh** [comment] 2015-11-09 22:15
@stephentoub 

> Presumably from the "test bug" label we do believe this is a bug in the test rather than in the Sockets implementation?

Not sure at this point.

**Comment by CIPop** [comment] 2015-11-09 22:35
Guillermo, could you take a look at this test please? I believe it's a test issue caused by a mismatch in IPv4 vs IPv6 addresses being used.

**Comment by josguil** [comment] 2015-11-10 03:44
I took a look at this. 

I don't think it's a test issue. The error message happens when the address family of client and server are different. But both server and client are initialized to IPv4 in the test. The one for the UdpClient is by default Ipv4 even if it's not passed explicitly to the constructor. 

It looks like something else could be changing one of the addresses, my best bet is CheckCacheRemote method, since it can actually remap an Ipv4 endpoint to be Ipv6. But I couldn't get a repro, and I need it to give a better answer on what path our code is following in this method when it throws the exception.

**Comment by SidharthNabar** [comment] 2016-01-12 00:01
Need to investigate this test - this seems to be a test setup/infra issue, hence moving to RTM milestone.

**Comment by CIPop** [comment] 2016-01-15 00:27
Duplicate to #4071.

**Closed by CIPop** 2016-01-15 00:27 UTC
Labels: System.Net
