### ISSUE TITLE
HTTP POST Request loosing cookies when sent from Linux

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#29894] opened 2018-05-24 16:21 UTC
_From @FasettoAndrew on May 24, 2018 10:51_

We have two ASP NET Core websites running in a Linux environment which communicate using HTTP requests.

On one server we are manually creating the new HTTP request and adding a provided cookie collection to the request like so:

`CookieCollection cookies` is passed to the method

```c#
// Create the request
var request = WebRequest.CreateHttp(OtherServerUrl);
request.Method = "POST";
request.ContentType = "application/json;charset=UTF-8";

// Add cookies if we have specified.
if (cookies != null)
{
    // Create new cookie container if one does not exist.
    if (request.CookieContainer == null)
    request.CookieContainer = new CookieContainer();

    // Add our cookies to the container.
    request.CookieContainer.Add(cookies);
}

if (content != null)
{
    // Serialize the model
    var JSONBody = JsonConvert.SerializeObject(content);

    // Write the json into the request stream
    using (var requestStream = await request.GetRequestStreamAsync())
    using (var sw = new StreamWriter(requestStream))
        await sw.WriteAsync(JSONBody);
}

// Get the request response as a HttpWebResponse
var response = (await request.GetResponseAsync()) as HttpWebResponse;
.....
```

In our use case, currently only a single cookie is being added, but we can see this if we output the request's cookie container; the cookie is in the request before it is sent. But when the request reaches the endpoint on the other server, the cookie container in the request contains 0 cookies.

The exact same code runs fine on Windows with the cookies being passed correctly, it only appears to occur on Linux.

_Copied from original issue: aspnet/Home#3166_

[EDIT] Add syntax highlighting by @karelz

**Comment by karelz** [comment] 2018-05-24 17:13
@FasettoAndrew which version of .NET Core do you use? Did you try 2.1 RC?

> the cookie is in the request before it is sent

Did you look at the network traces? (Fiddler / Wireshark) Is the cookie present there?

Can you please post minimal repro that would allow us to reproduce the failure on our side?

**Comment by FasettoAndrew** [comment] 2018-05-28 10:47
Under further investigation we identified the root cause of the issue.

The first back-end server was setting the domain on the cookies to be the same as what the originated from the front-end request, then performing a HTTP request to second back-end server with "localhost" as domain. Because the cookie domains did not match, they were being dropped.

We only saw this working on Windows as we accessed the site using localhost in the browser, but with Linux we had to use the devices IP.

Please feel free to close this issue.

**Closed** 2018-05-28 13:41 UTC
Labels: area-System.Net.Http, bug, needs more info, os-linux
