### ISSUE TITLE
Please consider Ownership-Heap implementation

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefx#31643] opened 2018-08-08 03:07 UTC
Rust's ownership system is appealing. Considering in coreClr or mono where all reference types could be created within a "ownership-Heap" and gc-ed with its ownership lost, it is possible for us to write system application just like c, and even possible to write clr with C# itself.

Value type is something which makes dotnet great compared with jvm, and that is almost 20 years' idea. Stack is great but with limitations, considerring that valueTask with IValueTaskSource it is possible to do async with nothing allocating and IValueTaskSource is still in need of Heap participating. 

Our dotnetters love and hate heap for gc's conveniency and its inexpectability. Rust's ownership system seems a good solution for this, from which we could introduce a new keyword "owner" just like "unsafe".
`
owner{
  var i=new object();
}
`
In the scope of "owner" any reference objs r created in ownership heap and deleted just out of the scope.

**Comment by krwq** [comment] 2018-08-08 07:11
Thanks for the proposal @juepiezhongren! Any chance you could propose how you would see new APIs or at least list expected features? This doc might be of some help: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by mattwarren** [comment] 2018-08-09 14:43
See https://github.com/dotnet/coreclr/issues/1235 for a similar discussion

**Comment by juepiezhongren** [comment] 2018-08-12 09:36
@ayende nowadays, rust's idea seems perfect for customed-heap control

**Comment by ayende** [comment] 2018-08-12 10:36
I like the idea, although I'm not so sure about the keyword.
Being able to hook into the object creation and provide our own buffer for managed objects would be great.
The problem is, of course, that we need to worry about external references.
Using your own syntax, what would this do:

```
var list = new List<object>(); // allocated on global heap
owner 
{
    list.Add(new object()); // allocated on local heap
}
```

GC will try to follow the pointer from `list` and probably die with access violation.
That is unless we can mark the pointer itself as "do not follow" for GC, and I don't know if that is possible.
On the one hand, we can use a few bits in the pointer, but that would have impact on traversal on normal cases.

**Comment by ayende** [comment] 2018-08-14 06:31
@juepiezhongren Rust does the check in compile time, because it has lifetime annotations.
How do you propose to be able to do that in C#?

Assume that we have 

```
var list = new List<object>(); // allocated on global heap
owner 
{
    // compiler error? 
    list.Add(new object()); // allocated on local heap
}
```

What about?
```
void Add(List<object> a, object b) => a.Add(b);

var list = new List<object>(); // allocated on global heap
owner 
{
    // compiler error? 
    Add(list, new object()); // allocated on local heap
}
```

The second case you are calling a method that has no lifetime specification. How do you handle this?

**Comment by juepiezhongren** [comment] 2018-08-14 11:07
things in oheap just behave in oheap together with stack, that's what i think first, and any call from heap to oheap is simply function without reference passing. Any bcl apis could be implemented for oheap is another thought, but not every one is valid in my opinion.

**Comment by ayende** [comment] 2018-08-14 13:51
I don't follow what you mean here? What is `oheap` ? The `owner`'s heap? What happens if I want to send a object allocate there to a function that may do something to it?

**Comment by juepiezhongren** [comment] 2018-08-14 14:00
oheap means ownership heap, sorry for that. objs in oheap , i.guess, should be untouchable from heap' object' reference

**Comment by ayende** [comment] 2018-08-14 14:11
So how do you enforce that?
You have this method: `void Add(List<object> a, object b) => a.Add(b);`
It gets the list from the normal heap and the object form the owner heap.
But it can also get it the other way around, or both from the same heap, etc.

**Comment by juepiezhongren** [comment] 2018-08-14 14:17
that will cause compiler error only, oheap's objs won't be referenced outside owner scope keyword

**Comment by ayende** [comment] 2018-08-14 14:42
How will the compiler _know_ about this?

**Comment by karelz** [comment] 2018-08-15 02:14
This is larger discussion, not specific to CoreFX - it should start in the Runtime.
Duplicate of https://github.com/dotnet/coreclr/issues/1235

**Closed by karelz** 2018-08-15 02:14 UTC
