### ISSUE TITLE
.NET Core 2.0: ResourceManager ignores Culture, always reads neutral RESX file

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#24786] opened 2017-10-21 01:56 UTC
@hardcodet commented on [Fri Oct 20 2017](https://github.com/dotnet/core/issues/1036)

VS2017, 15.3.5

I have an ASP.NET Core 2.0 app to which I added two resource files - the neutral one and one for German:

* `SiteResources.resx` (English strings)
* `SiteResources.de.resx` (German strings)

Both have their Build Action set to `EmbeddedResource`  and the `ResxFileGenerator` as the Custom Tool. So far so good.

The problem is: The following code returns always the English value from the **neutral** RESX file:

    SiteResources.Culture = new CultureInfo("de");
    string s1 = SiteResources.SomeTestString;

Same would go for this, which is equivalent

    string s1 = SiteResources.ResourceManager.GetString("SomeTestString", new CultureInfo("de"));

This somewhat defeats the whole purpose of having RESX files and the `ResourceManager`. Any idea how to work around this?

### Some additional infos

* My main DLL is called `TaxiLink.Site.dll`
* The compiler creates the following resource file that is put into a culture-specific folder:
   `\bin\Debug\netcoreapp2.0\de\TaxiLink.Site.resources.dll`
* I had my resources in a dedicated folder, and also tried a pair of resource files at the root of the application - both didn't work.

**Comment by danmosemsft** [comment] 2017-10-23 03:59
@krwq

**Comment by hardcodet** [comment] 2017-10-23 07:52
Some updates: I tried reproducing the issue on a vanilla project, and there, the correct resource value was returned. Since I was already refactoring my original controller at that point, I started there from scratch and noticed that moving the snippet above to the top of my controller method also got me the correct value.

Unfortunately, SourceTree was broken for me all weekend (I only just found a link to an upgrade), and I don't have the original state from before my refactoring - something must have messed up those lookups. If I'm getting successful in reproducing the bug again, I'll post back here.

**Comment by danmosemsft** [comment] 2017-10-23 15:57
@hardcodet OK, I'm going to close this then, please reactivate if you can repro.

**Closed by danmosemsft** 2017-10-23 15:57 UTC
Labels: area-System.Resources

**Comment by marcwittke** [comment] 2017-12-24 14:33
I am facing the same issue, see [ConsoleApp3](https://github.com/marcwittke/ConsoleApp3) for a reproduction

**Comment by marcwittke** [comment] 2017-12-24 14:38
Okay, it's definitely a problem with Visual Studio:

```cmd
C:\Users\MarcWittke\source\scratchpad\ConsoleApp3\ConsoleApp3>dotnet build
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 20,23 ms for C:\Users\MarcWittke\source\scratchpad\ConsoleApp3\ConsoleApp3\ConsoleApp3.csproj.
  ConsoleApp3 -> C:\Users\MarcWittke\source\scratchpad\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.0\ConsoleApp3.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.32

C:\Users\MarcWittke\source\scratchpad\ConsoleApp3\ConsoleApp3>dotnet run
Hallo Welt!
Hallo Welt!

C:\Users\MarcWittke\source\scratchpad\ConsoleApp3\ConsoleApp3>
```

**Comment by BredStik** [comment] 2018-03-23 19:16
Anyone noticed that the resourceCulture static private field is always null?  I think this is what leads to always retrieving the default culture resource.

See:

`private static global::System.Globalization.CultureInfo resourceCulture;`

Has this been resolved?  Still observing this as of today.

**Comment by OndrejNepozitek** [comment] 2018-10-05 12:15
I also encountered this problem when adding localization to an existing application. However, when I tried to test it in a new project, everything worked as expected.

Eventually, I was able to fix the problem in the original project. All I had to do was to remove an arbitrary PackageReference from the csproj file, build the app, and then add the reference back. (The motivation behing doing that was to check if it is possible that one of the referenced packages causes the problem.)

That means that no change in code was needed to fix the problem. After adding and removing the package reference, the project was in the same state as before.

**Comment by apspestana** [comment] 2019-03-27 16:29
I also had this problem. After reading the comments above, I cleaned and build my solution and this fixed the problem

**Comment by hardcodet** [comment] 2019-03-27 22:37
@danmosemsft Maybe this is worth reopening and having a look?

**Comment by danmosemsft** [comment] 2019-03-27 23:01
@hardcodet if there is a minimal repro we can look at, sure. It would be best to open a new issue. If the satellite assemblies are not going in the right place, the issue should go in Microsoft/msbuild. If they seem right but ResourceManager does not seem to be loading the right ones, then dotnet/corefx is the place for the issue.
