### ISSUE TITLE
Repeated http requests get stuck and cause client-side timeout

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#23012] opened 2017-08-07 13:57 UTC
_From @myarichuk on August 7, 2017 9:37_

Repeated http calls get stuck and timeout after one or two requests when executed in a 4.6.1 project that references a netstandard 2.0 project.
On my end, I've reproduced it here --> https://github.com/myarichuk/TestWebRequestGettingStuck
(the steps to reproduce are in the readme)
It reproduces each run reliably.

It looks like a bug.

_Copied from original issue: dotnet/coreclr#13247_

**Comment by valeriob** [comment] 2017-09-05 10:14
Hi,
any news on this ?  😄

**Comment by khellang** [comment] 2017-09-05 15:11
This is because you've specified `HttpCompletionOption.ResponseHeadersRead` and you haven't read or disposed the result. This means the connection will hang around (waiting for you to read the content) until it times out.

**Comment by khellang** [comment] 2017-09-05 15:17
Try changing the code to

```diff
diff --git a/TestWebRequestGettingStuck/Program.cs b/TestWebRequestGettingStuck/Program.cs
index 26e700e..29cbf7d 100644
--- a/TestWebRequestGettingStuck/Program.cs
+++ b/TestWebRequestGettingStuck/Program.cs
@@ -11,7 +11,7 @@ namespace TestWebRequestGettingStuck
         {
             for (int i = 1; i < 10001; i++)
             {
-                client.GetAsync("http://localhost:9000/foo",HttpCompletionOption.ResponseHeadersRead).Wait();
+                client.GetAsync("http://localhost:9000/foo",HttpCompletionOption.ResponseHeadersRead).Result.Dispose();
                 Console.WriteLine(i);
             }
         }
```

And see it fly :wink:

I don't think this is related to .NET Standard. It's just how `HttpClient` works. If you don't consume (or dispose) the response content, the connection will be stuck until timeout.

**Comment by valeriob** [comment] 2017-09-05 15:19
Thanks @khellang.
But the same code just changing the project type or referencing an empty net standard library behave differently. I understand what you are saying, but why referencing an empty netstandard project it blocks other way it doesnt ?
And why referencing the netstandard project but using the old project system without your patch it works ?

**Comment by khellang** [comment] 2017-09-05 15:43
Hmm. That's interesting. It's probably due to some of the binding redirect magic that @terrajobst has been talking about in https://github.com/dotnet/standard/issues/481.

I took a look at the fusion logs, and the resolution is indeed redirected once you add the reference to the netstandard assembly.

## Without NETStandard Reference

Without the netstandard reference, it ends up picking `System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` from

> C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll

<details>

```
*** Assembly Binder Log Entry  (05.09.2017 @ 17:32:13) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\TestWebRequestGettingStuck.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/khe1/Code/TestWebRequestGettingStuck/TestWebRequestGettingStuck/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = TestWebRequestGettingStuck.exe
Calling assembly : TestWebRequestGettingStuck, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\TestWebRequestGettingStuck.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Found assembly by looking in the GAC.
LOG: Binding succeeds. Returns assembly from C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll.
LOG: Assembly is loaded in default load context.
```

</details>

## With NETStandard Reference

But when you add the reference, it ends up picking `System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` from

> C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\System.Net.Http.dll

<details>

```
*** Assembly Binder Log Entry  (05.09.2017 @ 17:36:24) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\TestWebRequestGettingStuck.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/khe1/Code/TestWebRequestGettingStuck/TestWebRequestGettingStuck/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = TestWebRequestGettingStuck.exe
Calling assembly : TestWebRequestGettingStuck, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\TestWebRequestGettingStuck.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.2.0.0 redirected to 4.2.0.0.
LOG: Post-policy reference: System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/khe1/Code/TestWebRequestGettingStuck/TestWebRequestGettingStuck/bin/Debug/System.Net.Http.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\System.Net.Http.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Binding succeeds. Returns assembly from C:\Users\khe1\Code\TestWebRequestGettingStuck\TestWebRequestGettingStuck\bin\Debug\System.Net.Http.dll.
LOG: Assembly is loaded in default load context.
```

</details>

I guess there are several questions here; why is it picking different assemblies? why are the two versions of the assemblies behaving differently? is this a bug or an intended break? what can you do to work around it? 🤔

**Comment by valeriob** [comment] 2017-09-05 15:55
wow @khellang  that's awesome 😄

**Comment by valeriob** [comment] 2017-09-06 11:39
removing the reference to System.Net.Http from the project TestWebRequestGettingStuck that references netstandard library fixes the problem.

![image](https://user-images.githubusercontent.com/1522516/30109997-c7f0a93c-9308-11e7-871a-f033f5476c46.png)

**Comment by khellang** [comment] 2017-09-06 11:42
Sounds like the same problem as https://github.com/dotnet/standard/issues/484 then. I see you also have the warning icon on the System.Net.Http reference.

**Comment by khellang** [comment] 2017-09-06 11:42
The behavior change is still pretty weird though 😕

**Comment by valeriob** [comment] 2017-09-06 11:56
yep i used the suggestion in  [dotnet/standard#484](https://github.com/dotnet/standard/issues/484).

**Comment by khellang** [comment] 2017-09-06 21:28
Related to the Solution Explorer warnings: https://github.com/dotnet/sdk/issues/1499

**Comment by davidsh** [comment] 2017-09-28 02:03
>Repeated http calls get stuck and timeout after one or two requests when executed in a 4.6.1 project that references a netstandard 2.0 project.
On my end, I've reproduced it here --> https://github.com/myarichuk/TestWebRequestGettingStuck
(the steps to reproduce are in the readme)
It reproduces each run reliably.

This is a .NET Framework repro.  The default limit for numbers of connections per server is 2 (ServicePointManager.DefaultConnectionLimit and/or HttpClientHandler.MaxConnectionsPerServer).  Since this repro is not reading the response nor disposing of it, it is leaving connections open.  Therefore, trying to run another Http request will end up causing it to be queued and it will wait until the other connections are closed.

On .NET Core, the number of connections per server is different (much higher).  The differences between .NET Core and .NET Framework are due to having a different HTTP stack.

So, the original bug reported here by @jkotas is basically by-design.  So, closing this issue.

**Closed by davidsh** 2017-09-28 02:03 UTC
Labels: area-System.Net.Http
