### ISSUE TITLE
BitArray.CopyTo copies also unused bits ("leaks data")

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#9838] opened 2016-07-04 10:33 UTC
`BitArray.CopyTo(...)` leaks internal data, if the data copied is shorter than the destination type.
For instance, if set via `new BitArray(16, true)` (16 bits long, all on), then copy to an int array, all bits in the int are set (as if the `BitArray` is actually 32 bits long).

[Demonstration tests](https://github.com/Clockwork-Muse/corefx/commit/19a67977e876aaa80eb42f7e04feae1fed1a815c) (although would need to be switched for regression tests).  At the moment I had to verify the tests in a separate project - Something about the System.Collections is borked up when trying to run tests.

I'm assuming that this is _not_ the desired behavior, given the data is automatically cleared when the length is increased.  Granted, it's somewhat on the programmer for this, using a type shorter than there's officially data for...

**Comment by Clockwork-Muse** [comment] 2016-07-07 11:31
Possible reason tests can't be run: Microsoft/xunit-performance#157  
(certainly not helping things any)

**Comment by karelz** [comment] 2016-09-28 22:43
This needs deeper investigation ... anyone, feel free to grab it

**Comment by mareklinka** [comment] 2016-10-12 05:10
I took a look into the issue. The root cause seems to raise from the fact that `BitArray` uses `int`s for its internal data storage. For example, the `BitArray(int, true)` constructor will first allocate a necessary number of `int`s and then do

` m_array[i] = unchecked(((int)0xffffffff));`

So if we do `new BitArray(16, true)`, we internally end up with 32 bits all set to 1. Later in `CopyTo(int[], int)`, we do

`Array.Copy(m_array, 0, array, index, GetArrayLength(m_length, BitsPerInt32));`

For the example above, this will copy all of the 32 bits set to 1, so the resulting array leaks the unused upper 16 bits.

Manually setting `Length` solves this (I guess unintentionally) because it sets the unused bits (the bits above `m_length`) to 0. So the solution should actually be simple here - just before `CopyTo` copies the data, do as `set_Length` does and trim the excessive bits. I'll try to provide a pull request later today.

**Comment by mareklinka** [comment] 2016-10-12 21:12
I seem to have hit a snag with the promised pull request. Apparently there are two different implementations of the `BitArray` class. One in corefx and one in coreclr. I guess that's why my tests, when run locally via MsBuild, also fail - by default, they use the `BitArray` implementation present in `System.Private.CoreLib.ni.dll`.

Since I'm rather new to this project, I'd greatly appreciate if someone could help me figure out the next steps.

**Comment by Clockwork-Muse** [comment] 2016-10-12 22:13
@mareklinka - you should be able to just open a PR for coreclr too (I did that for an earlier change to BitArray).

**Comment by karelz** [comment] 2016-10-12 23:04
@ianhays @Priya91 can you please help here?

**Comment by Priya91** [comment] 2016-10-13 01:11
@mareklinka You can open up a PR to the Coreclr repo and get it merged, once the packages are updated in corefx with your fix, the tests should pass. The right way is to do the coreclr change first.

**Comment by mareklinka** [comment] 2016-10-13 04:51
I thought so, just wanted to make sure. Thanks all for the help, I'll prepare t he coreclr PR later today.

**Comment by danmosemsft** [comment] 2016-10-13 18:46
@weshaggard would this potentially break existing code? what is our compat bar/process?

**Comment by weshaggard** [comment] 2016-10-13 18:52
With every change there is potential to break someone depending on the old behavior, right or wrong, but in this case I don't feel like it will be an issue to fix.

**Comment by karelz** [comment] 2016-10-13 18:54
Agreed. We don't want to be bug-by-bug compatible. That would prevent us from almost any innovation.
However, we have to be compatible in places where there is high risk of breaking existing code and causing headaches to lots of developers. This does not seem to be the case.

**Comment by danmosemsft** [comment] 2016-10-13 18:57
Fine.

**Comment by mareklinka** [comment] 2016-10-15 07:29
I just opened the _coreclr_ PR and updated the _corefx_ pull request according to the discussions.

**Closed** 2016-10-21 16:16 UTC
Labels: area-System.Collections, bug, up for grabs
