### ISSUE TITLE
Can't reliably determine if connection was successful when using HttpClient

### ISSUE THREAD

**Issue by wizofaus** [dotnet/corefx#41192] opened 2019-09-19 03:41 UTC
If an exception is thrown from a call to HttpClient.SendAsync( ) there's no way to be certain that the connection itself failed, vs. e.g., a timeout before trying to read the response.
While there are certain SocketException SocketError values that can only happen if the DNS lookup or connection fails, if there is a) a failure negotiating the SSL handshake or b) a timeout trying to connect, there's no reliable way to programmatically distinguish this from other possible errors.
This is important in many real world applications where if there's any possibility that the remote server did receive all or part of the request, but a network or system failure occurred after this point, it's necessary to attempt to contact that server again to determine whether it did process the request.
If the HttpClient had a way of determine how many bytes had been successfully sent to the remote server before the exception occurred, that would solve it nicely too.

**Comment by davidsh** [comment] 2019-09-19 04:02
This is similar to #4148 and related issues. Basically we need to enhance the top-level HttpRequestException and add a property that would be similar to the [WebException.Status property](https://docs.microsoft.com/en-us/dotnet/api/system.net.webexception.status?view=netframework-4.8). That property was of type [WebExceptionStatus](https://docs.microsoft.com/en-us/dotnet/api/system.net.webexceptionstatus?view=netframework-4.8) enum and made it easy to distinguish various error conditions.

**Comment by eiriktsarpalis** [comment] 2019-09-19 13:04
This feels related to #20296. A solution here should probably also address that issue.

**Comment by wizofaus** [comment] 2019-09-20 02:12
I notice that mentions OperationCanceledException - in the testing I'd done I was getting OperationCanceledException when the connection timed out, but just a regular TaskCanceledException when it timed out trying to read a response.  Not really something I could rely on either way!

**Comment by qjw2bqn** [comment] 2019-09-27 09:49
I have the same error.But I publish the demo on ubuntu across docker.
The base image is microsoft/dotnet:2.2-aspnetcore-runtime.
when i use the httpclient request the remote api,sometimes work right ,but somethimes it get wrong with the error message:
the operation was canceled

but it doesn't occur on window environment！！
somebody have the same question with me?

**Comment by karelz** [comment] 2019-10-04 20:17
Duplicate of #4148

**Closed by karelz** 2019-10-04 20:17 UTC
Labels: area-System.Net.Http, enhancement
