### ISSUE TITLE
Building corefx fails on my machine

### ISSUE THREAD

**Issue by janvorli** [dotnet/corefx#1628] opened 2015-05-04 12:52 UTC
I have tried to build corefx on my machine today and it fails with several error. I've tried both Linux and Windows builds and both behave the same.
For Linux, I've used the following command:
`build.cmd /p:OSGroup=Linux /p:SkipTests=true /t:rebuild`
and for Windows, I've used the following one:
`build.cmd /p:SkipTests=true /t:rebuild`
In both cases, I got the following error at the beginning of the build:
```
CSC : error CS0518: Predefined type 'System.Object' is not defined or imported [D:\git\corefx\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]
```

And later on, bunch of errors like these:
```
  System.IO.FileSystem.Watcher -> D:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.IO.FileSystem.Watcher\System.IO.FileSystem.Watcher.dll
EXEC : GenFacades.exe error : 0 : File does not exist D:\git\corefx\packages\System.Diagnostics.Debug\4.0.10-beta-22816\ref\any\System.Diagnostics.Debug.dll [D:\git\corefx\src\System.Diagnostics.Debug\src\System.Diagnostics.Debug.csproj]
EXEC : GenFacades.exe error : 0 : No assemblies loaded for D:\git\corefx\packages\System.Diagnostics.Debug\4.0.10-beta-22816\ref\any\System.Diagnostics.Debug.dll [D:\git\corefx\src\System.Diagnostics.Debug\src\System.Diagnostics.Debug.csproj]
  System.IO.MemoryMappedFiles -> D:\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.IO.MemoryMappedFiles\System.IO.MemoryMappedFiles.dll
EXEC : GenFacades.exe error : 0 : When partialFacadeAssemblyPath is specified, only exactly one corresponding contract assembly can be specified. 
```
I've tried to use `git clean -xdf` and then `git pull upstream master` to make sure I have the latest bits. Also, @stephentoub has verified that the build works for him and we have the same top of the `git log`

I am running the build command from a fresh regular command prompt (not the visual studio command prompt).

**Comment by janvorli** [comment] 2015-05-04 12:53
@ericstj, Steve has suggested that you will likely be able to help me with this.

**Comment by janvorli** [comment] 2015-05-04 13:09
I have also tried it on my other machine, where there was no corefx checkout before so I have created a brand new one and I've hit exactly the same issue.

**Comment by akoeplinger** [comment] 2015-05-04 13:15
This looks like https://github.com/dotnet/corefx/issues/449

**Comment by bpschoch** [comment] 2015-05-04 14:14
The new Visual Studio 2015 RC will install xamarin if you select all the defaults,  go to add/remove programs and remove the xamarin install and it should work.  I ran into same problem myself

**Comment by stephentoub** [comment] 2015-05-04 14:17
@weshaggard, if installing VS2015 breaks building corefx, we need to fix the corefx build to accommodate.  Who can look at fixing this?  Devs should be able to work on corefx with VS2015 as-is without uninstalling stuff.

**Comment by janvorli** [comment] 2015-05-04 14:41
I don't have VS 2015 installed

**Comment by ericstj** [comment] 2015-05-04 16:22
@janvorli  do you have the PCL targeting pack installed at all?  What is the content in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable?
At least the System.Collections.Immutable failure is not related to package resolution at all.  This project still builds as a normal (legacy) PCL with no nuget package dependencies.  I suspect the problem is that you are missing the targeting pack.
The genfacades errors look like the problem that @mellinoe and @ellismg fixed with nuget.config and restore of partial façade projects.

**Comment by janvorli** [comment] 2015-05-04 21:48
@ericstj I don't have the PCL targetting pack installed and I don't have the `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETPortable` folder at all.

**Comment by janvorli** [comment] 2015-05-04 21:50
Is it somehow required?

**Comment by janvorli** [comment] 2015-05-05 11:28
@ellismg Any idea what can be causing the genfacades errors?

**Comment by janvorli** [comment] 2015-05-05 11:34
Actually, the first warning during the build might shed some light on the issue:
`C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(989,5): warning MSB3644: The reference assemblies for framework ".NETPortable,V
ersion=v4.5,Profile=Profile259" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [D:\git\corefx\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]`

I'm not sure what I am supposed to install though. The developer guide for CoreCLR on the wiki says that the only Prerequisity is VS2013 which I have installed on both of my machines.

**Comment by ellismg** [comment] 2015-05-05 13:58
Do you have the most recent VS 2013 update installed?

**Comment by janvorli** [comment] 2015-05-05 17:05
@ellismg Thanks for the suggestion. I didn't have any updates installed in the VS and now that I have installed the update 4, the build passes ok.

**Comment by janvorli** [comment] 2015-05-05 17:12
Hmm, still not true for Linux build. The first error went away, but the ones related to the facades are still there.

**Comment by janvorli** [comment] 2015-05-05 17:20
Looking at the error message again and at the path of the file it couldn't open:
File does not exist `D:\git\corefx\packages\System.Diagnostics.Debug\4.0.10-beta-22816\ref\any\System.Diagnostics.Debug.dll`
Looking at my folder structure, I can see that under the `D:\git\corefx\packages\System.Diagnostics.Debug\4.0.10-beta-22816` I have no "ref" subfolder at all. I only have `lib` folder there and the following files:
`License.rtf`
`System.Diagnostics.Debug.4.0.10-beta-22816.nupkg`
`System.Diagnostics.Debug.4.0.10-beta-22816.nupkg.sha512`
`System.Diagnostics.Debug.nuspec`

**Comment by ellismg** [comment] 2015-05-05 17:26
Can you do a git clean -dxf and also delete the NuGet and DNU folders in your temp directory and try again?

**Comment by ericstj** [comment] 2015-05-05 17:30
Matts suggestion should work.  These types of problems are caused by dnu's implementation of Nuget.config probing.  I'm hoping to move us off Nuget.config in a couple days because I'm tired of the feed issues.

**Comment by janvorli** [comment] 2015-05-05 19:47
I've deleted NuGet folders in my AppData\Local, Roaming and LocalLow folders and the DNU folder in my AppData\Local. There were no more such folders on my C drive. I've also ran git clean -dxf.
It still doesn't work and I get the same errors.

**Comment by ellismg** [comment] 2015-05-05 21:35
Does the System Diagnostics Debug package that gets pulled down look like it did before you did all the clean stuff (e.g no ref folder?).

**Comment by janvorli** [comment] 2015-05-06 05:35
Yes, exactly the same

**Comment by janvorli** [comment] 2015-05-06 17:36
@ellismg, @ericstj I've just synced the latest corefx and now the issues I was hitting are gone.
Unfortunately, there are new ones. I've deleted all NuGet/DNU folders I've found and ran `git clean -dxf` to make sure they are not caused by that.

From the errors below, do you have any idea what's going on?

`EXEC : error : DownloadPackageAsync: https://www.myget.org/F/dotnet-corefx/api/v2/package/System.Threading.Overlapped/4.0.0-beta-22809 [D:\git\corefx\src\System.IO.FileSystem.Watcher\src\System.IO.FileSystem.Watcher.csproj]
D:\git\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00042\lib\packageresolve.targets(31,5): error MSB3073: The command ""D:\git\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta5-11682/\bin\dnu.cmd" restore --packages "D:\git\corefx\packages" "D:\git\corefx\src\System.IO.FileSystem.Watcher\src/project.json"" exited with code 1. [D:\git\corefx\src\System.IO.FileSystem.Watcher\src\System.IO.FileSystem.Watcher.csproj]`

and a bit further:

`EXEC : error : FindPackagesById: System.Collections.Concurrent [D:\git\corefx\src\System.IO.Pipes\src\System.IO.Pipes.csproj]
D:\git\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00042\lib\packageresolve.targets(31,5): error MSB3073: The command ""D:\git\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta5-11682/\bin\dnu.cmd" restore --packages "D:\git\corefx\packages" "D:\git\corefx\src\System.IO.Pipes\src/project.json"" exited with code 1. [D:\git\corefx\src\System.IO.Pipes\src\System.IO.Pipes.csproj]`

`EXEC : error : FindPackagesById: System.Collections.Immutable [D:\git\corefx\src\System.Reflection.Metadata\src\System.Reflection.Metadata.csproj]`

`EXEC : error : FindPackagesById: System.Collections.Immutable [D:\git\corefx\src\System.Reflection.Metadata\src\System.Reflection.Metadata.csproj]
D:\git\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00042\lib\packageresolve.targets(31,5): error MSB3073: The command ""D:\git\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta5-11682/\bin\dnu.cmd" restore --packages "D:\git\corefx\packages" "D:\git\corefx\src\System.Reflection.Metadata\src/project.json"" exited with code 1. [D:\git\corefx\src\System.Reflection.Metadata\src\System.Reflection.Metadata.csproj]`

**Comment by akoeplinger** [comment] 2015-05-06 17:52
@janvorli Copy and run the command that fails directly in cmd.exe, it should show you some more details about what went wrong.

**Comment by ericstj** [comment] 2015-05-06 18:27
Build.cmd actually writes out a log file: msbuild.log in the same directory.  A lot of the issues we've been facing in DNU have been race conditions so it may not repro on a rerun.  Sharing the log will help me root cause it and ensure we get issues filed on DNU.

**Comment by janvorli** [comment] 2015-05-06 19:12
@ericstj Thanks, rerunning the build fixed the errors. I'll send you the msbuild.log from the failed run via email.

**Comment by ericstj** [comment] 2015-05-06 20:06
Ok, the log had two distinct failure modes:
```
                     System.ArgumentNullException: Value cannot be null. (TaskId:271)
                     Parameter name: stream (TaskId:271)
                        at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) (TaskId:271)
                        at Microsoft.Framework.PackageManager.PackageUtilities.<OpenNuspecStreamFromNupkgAsync>d__1.MoveNext() (TaskId:271)
```
And
```
                     System.Net.Http.HttpRequestException: The requested failed, see inner exception for details. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host (TaskId:334)
                        at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags) (TaskId:334)
                        at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) (TaskId:334)
                        --- End of inner exception stack trace --- (TaskId:334)
                        at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) (TaskId:334)
                        at Microsoft.Net.Http.Client.ApmStreamWrapper.Read(Byte[] buffer, Int32 offset, Int32 count) (TaskId:334)
                        at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count) (TaskId:334)
                        at System.Net.Security._SslStream.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:334)
                        at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:334)
                        at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:334)
                        at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:334)
                        at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count) (TaskId:334)
                        at System.IO.Stream.<>c__DisplayClass0.<BeginReadInternal>b__5(Object ) (TaskId:334)
```

First one looks like a bug in DNX, second looks like a network glitch that resulted in DNX failing.  @pranavkm @davidfowl are these known issues?

**Comment by ericstj** [comment] 2015-05-06 20:08
In general as a workaround to these you can just run build /t:RestoreAllProjectPackages until you get success and that'll give you a good package cache, but we need to work out these issues with DNU so please keep reporting them.

**Comment by ericstj** [comment] 2015-05-06 22:59
@ChengTiang let me know that both of these are network glitches and opened https://github.com/aspnet/dnx/issues/1804 to track this.  For now I will close this issue.  Please reopen if you are still experiencing issues.

**Closed by ericstj** 2015-05-06 22:59 UTC
