### ISSUE TITLE
Package restore failure (unable to locate System.Runtime)

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#1508] opened 2015-04-24 19:05 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug/lastFailedBuild/consoleFull#-1256200281ca1c4203-ea29-47c4-9c51-c32ae427766d

Since http://dotnet-ci.cloudapp.net/job/dotnet_corefx/379/

/cc @ellismg @ericstj @jhendrixMSFT

**Comment by ericstj** [comment] 2015-04-24 19:28
This is in the partial-facades target that @mellinoe added.  It's similar to the other bugs I fixed around nuget.config not being honored.  Since he writes the project.json to intermediate there is no nuget.config in the dir heirarchy above it.  I think a reasonable fix would be to either copy the nuget.config to the intermediate folder next to project.json (or even at the root) or to pass in a -Source switch to dnu.

**Comment by mmitche** [comment] 2015-04-24 19:34
It looks like this somehow got changed without an obvious PR or merge causing the problem.  Any idea how it slipped by?

**Comment by mellinoe** [comment] 2015-04-24 19:35
In what situations does this happen? I've never seen it

**Comment by mmitche** [comment] 2015-04-24 19:36
@mellinoe Every build of the corefx repo is failing currently.

**Comment by ericstj** [comment] 2015-04-24 19:37
Intermediate has to be outside of the source path.  This is the case for CI builds but not local dev builds.  I think you should be able to repro if you specify a different intermediate folder.

**Comment by mmitche** [comment] 2015-04-24 19:38
The intermediates folder is by default within the repo path.

**Comment by ericstj** [comment] 2015-04-24 19:40
But not under src where nuget.config lives.  Also this is a race condition, if any other project under src happens to beat you to restoring the same package you won't see it.

**Comment by mmitche** [comment] 2015-04-24 19:42
oh oh, source = src not repo root in this case.

**Comment by ellismg** [comment] 2015-04-24 19:43
I merged the change that caused the failure in but it was passing in CI there at the time.  The only failure was the in the Linux test job which was aborted.  That must explain why we didn't see it there.

**Comment by mellinoe** [comment] 2015-04-24 20:03
What's the reason the CI machines have a different build process? It's not easy to catch things like this unless there's some property I could set to emulate the other process.

**Comment by mmitche** [comment] 2015-04-24 20:06
They do not have a different build process.  They are directly calling build.cmd from the root of the repo.

d:\j\workspace\dotnet_corefx_mac_debug>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86 && build.cmd /p:OS=OSX /p:Configuration=Debug /p:SkipTests=true

Are you building from TFS?

**Comment by ericstj** [comment] 2015-04-24 20:12
@mellinoe it's also a race that only happens on a fresh build so you might not hit it locally.  To try, delete your bin and packages folder, build from the root on a multi-core machine.  Depending on order projects build you may or may not hit it.  To force it you can delete bin & packages and just build the s.r facade project.

**Comment by mellinoe** [comment] 2015-04-24 20:16
I must be doing something wrong because I'm not able to repro this no matter what I do. Building System.Runtime.CoreCLR.csproj from a clean repo still succeeds for me. Could you clarify what you meant about this, Eric:

> Intermediate has to be outside of the source path. This is the case for CI builds but not local dev builds. I think you should be able to repro if you specify a different intermediate folder.

Is this a difference between local and CI builds that I need to take into account?

**Comment by mmitche** [comment] 2015-04-24 20:17
The only thing that's different between a local and CI build of corefx is that the CI will delete the full repo directory (the whole workspace essentially) clone and then build.  See command above.

**Comment by mellinoe** [comment] 2015-04-24 20:25
Hm, even after a fresh clone I am unable to reproduce this. Are either of you guys actually able to repro this locally?

**Comment by ericstj** [comment] 2015-04-24 20:27
Disable all your machine wide Nuget sources.

**Comment by mellinoe** [comment] 2015-04-24 20:37
No difference. I'm still inclined to believe this is a CI-only issue unless someone is actually able to reproduce this locally? @kwrq and @Priya91 haven't been able to repro this either

**Comment by ericstj** [comment] 2015-04-24 20:44
Did you clean out all the Nuget caches as well?  Check out %localappdata%\nuget

**Comment by mmitche** [comment] 2015-04-24 20:55
@mellinoe I can give you a machine for investigation if you'd like

**Comment by ellismg** [comment] 2015-04-24 21:27
I am testing a fix.

**Comment by mellinoe** [comment] 2015-04-24 22:17
Should be fixed by #1510 . Thanks @ellismg

**Closed** 2015-04-24 22:24 UTC
