### ISSUE TITLE
SendReceive_PartialMessage_Success websockets test failed on Windows in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9463] opened 2016-06-16 11:31 UTC
"The server returned an invalid or unrecognized response"
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/655/consoleText
```
System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_PartialMessage_Success(server: wss://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx) [FAIL]
        System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
              at System.Net.WebSockets.WinHttpWebSocket.<CloseAsync>d__30.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.WebSockets.Client\tests\SendReceiveTest.cs(49,0): at System.Net.WebSockets.Client.Tests.SendReceiveTest.<SendReceive_PartialMessage_Success>d__1.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by aviviadi** [comment] 2016-06-16 15:00
Are you using kestrel's KeepAliveInterval (or using it's default 30 Secs?).
Try to set it to TimeSpan.FromDays(1) (not infinite) and see what happens.

The keep alive ping from kestrel somehow ruins the buffer.  Changing the keep alive interval solved the problem for me in windows.

However in Linux (I have my own version of websocket client), I see the same problem with additional 4 bytes : 1000 0001 , 0111 1110 , 0000 0100 , 0000 0000
Are those linux's socket heartbeats ?   

It seems the program's "RecvAsync" races with the native socket recv... I guessing that because sometimes client receives the sent buffer minus 4 bytes, and sometimes plus these 4 bytes. (and that may happens every few seconds, so I can start receiving a lot of data before it happens).

Another note : AsyncRecv EndOfMessage might be True when this happens.    That's maybe connected to the fact I am using my own unix version of websocket client.

**Comment by aviviadi** [comment] 2016-06-16 15:06
For the KeepAliveInterval run this and wait few seconds : (rc2)

using System;
using System.Net.WebSockets;
using System.Threading;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.WebSockets.Protocol;
using Microsoft.Extensions.Logging;

namespace TestUnexpected
{
    public class ServerStartup
    {
        private const int BufferSize = 30 * 1024 * 1024;

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerfactory)
        {
            app.UseWebSockets(new WebSocketOptions
            {
                KeepAliveInterval = TimeSpan.FromMilliseconds(1),
                ReceiveBufferSize = 4096
            });

            app.Run(async context =>
            {
                using (var ws = await context.WebSockets.AcceptWebSocketAsync())
                {
                    while (true)
                    {
                        try
                        {
                            var bytes = new byte[BufferSize];
                            var buffer = new ArraySegment<byte>(bytes);
                            WebSocketReceiveResult result;
                            do
                            {
                                result = await ws.ReceiveAsync(buffer, CancellationToken.None);
                            } while (result.EndOfMessage == false);
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine(e);
                            Console.ReadKey();
                            Environment.Exit(1);
                        }
                    }
                }
            });
        }
    }
}
`

**Comment by stephentoub** [comment] 2016-06-16 15:08
cc: @Tratcher

**Comment by CIPop** [comment] 2016-06-16 17:18
/cc @davidsh 

Thanks @aviviadi for the ideas! I'll see if they apply in this case. Our test server code is actually using the IIS WebSockets implementation.

**Comment by davidsh** [comment] 2016-06-16 17:21
We have seen this exception before in System.Net.Http/System.Net.Http.WinHttpHandler:

>System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response

It usually occurs when there is some network error and the HTTP response from the server is corrupted. 

I don't think this is a specific problem with WebSocket.

**Comment by CIPop** [comment] 2016-06-16 18:01
Thanks @davidsh. 

Refs: #5485, #9212, #6255, #4171

**Comment by CIPop** [comment] 2016-06-16 18:03
Duplicate of #4171.

**Closed by CIPop** 2016-06-16 18:03 UTC
Labels: System.Net
