### ISSUE TITLE
libcurl maintains stale DNS information

### ISSUE THREAD

**Issue by glennc** [dotnet/corefx#26651] opened 2018-01-29 20:33 UTC
When building a HttpClientFactory in ASP.NET we did some experiments with DNS and HTTPClient. Specifically we are disposing of handlers periodically in order to avoid stale DNS, but re-using them enough to mitigate socket exhaustion problems with keeping a single client forever.

Our issue is that when using libcurl on a mac disposing the handler doesn't appear to impact DNS at all. Suggesting some type of single DNS cache in libcurl itself.

You can see the experiment and results here: https://github.com/aspnet/HttpClientFactory/wiki/Exploring-DNS-issues

Issue on our side is: https://github.com/aspnet/HttpClientFactory/issues/10

Is this a bug in our libcurl usage or is there something we can do at a higher level to work around it?

/cc @karelz

**Comment by stephentoub** [comment] 2018-01-29 20:47
My understanding is that libcurl used to have a per-process / global cache, but that it's been deprecated, and it's no longer the default; you can opt back into it via https://curl.haxx.se/libcurl/c/CURLOPT_DNS_USE_GLOBAL_CACHE.html, which CurlHandler does not do.

According to https://curl.haxx.se/libcurl/c/CURLOPT_DNS_CACHE_TIMEOUT.html, libcurl utilizes a 60 second timeout by default on DNS entries.  CurlHandler doesn't explicitly do anything with DNS timeouts, doesn't change this setting, etc.

**Comment by karelz** [comment] 2018-01-29 22:16
@Priya91 can you please take a look?

**Comment by wfurt** [comment] 2018-01-29 22:28
we should make sure the entries are not cached by OS resolver. It would be handy if you can describe your test methodology @glennc.
BTW /etc/hosts entries do not really have TTL. It may be worth of testing with real name server.
Also note that updates to /etc/resolv.conf and nsswitch.conf typically have different refresh cycle - at least on Unix.

**Comment by Priya91** [comment] 2018-01-29 23:35
>  CurlHandler doesn't explicitly do anything with DNS timeouts, doesn't change this setting, etc.

We do change this setting [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L318)

**Comment by karelz** [comment] 2018-01-29 23:41
@rynowak can you please double check that you didn't see the changes even after the 10 mins? (our timeout)

**Comment by stephentoub** [comment] 2018-01-29 23:58
> We do change this setting here

You're right, @Priya91, and I even added that code (https://github.com/dotnet/corefx/pull/7564). 😦 Sorry for misleading; need to page all this back in.

**Comment by glennc** [comment] 2018-01-30 00:00
When does this https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L317 come into play then? @rynowak in the linked issue seemed to indicate that even if left for a long time, longer than 10 minutes, he still saw old DNS entries.

**Comment by glennc** [comment] 2018-01-30 00:02
@wfurt the test methodology is described in the linked wiki article. It is the same test @rynowak talked about in the linked issue.

**Comment by Priya91** [comment] 2018-01-30 00:03
@stephentoub This dns cache timeout is per easy request right, which means per SendAsync, so this timeout shouldn't affect other easy requests using the ame multi handle (CurlHandler). In your linked PR issue comment you mention the below. I don't understand how the timeout here influences the reported issue.

```
Now that we're allowing the multi handle to live for as long as the CurlHandler, the DNS cache timeout starts to matter much more.
```

**Comment by Priya91** [comment] 2018-01-30 00:07
Also in the libcurl documentation page, they mention, 

```
The name resolve functions of various libc implementations don't re-read name server information unless explicitly told so (for example, by calling res_init(3)). This may cause libcurl to keep using the older server even if DHCP has updated the server info, and this may look like a DNS cache issue to the casual libcurl-app user.
```

so if we repro the issue with a native app similar to .NET Core app environment with multi handle, and easy handles having same settings, we can confirm this bug is not in .net core.

**Comment by stephentoub** [comment] 2018-01-30 12:17
@Priya91, when in doubt, go to the source, e.g.
https://github.com/curl/curl/blob/a5e6d6ebcb8dc00f264c89c3e5376f042c372efb/lib/multi.c#L392-L398
shows that easy handles as we're using them share a DNS cache from the multi handle.

**Comment by Priya91** [comment] 2018-02-02 20:07
I did this test on Linux ubuntu 17.04 and didn't see the issue repro, will report back when I have results on osx.

The test:

```c#
    public class HttpClientHandlerTest_ASPNET_repro
    {
        [Fact]
        [Trait("category", "mytest")]
        public async Task TestMethod()
        {
            var cts = new CancellationTokenSource();
            Console.CancelKeyPress += (sender, e) => cts.Cancel();
            while (!cts.IsCancellationRequested)
            {
                var client = new HttpClient();
                var content = await client.GetStringAsync("http://www.foo.com");
                Console.WriteLine("Content: " + DateTime.Now + ": " + content);
                client = null;

                await Task.Delay(2000);
            }
        }
    }
```

Infrastructure setup:

1. Created a dns server on azure, and mapped www.foo.com to 2 IP addresses, which host kestrel process and returns string like "Hello from Windows Server 1" or "Hello from Windows Server 2".
2. Modify the record in the dns server for www.foo.com to point to either one of the windows servers, and do a rndc reload. 
3. Observe the change from HttpClient app, running on an azure ubuntu 1704 machine.

This is the output:

```
  Content: 2/2/18 8:04:41 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:43 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:45 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:47 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:49 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:51 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:53 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:55 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:57 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:04:59 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:01 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:03 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:05 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:07 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:09 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:11 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:13 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:15 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:17 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:19 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:21 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:23 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:25 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:27 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:29 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:31 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:33 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:35 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:37 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:39 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:41 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 8:05:43 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:45 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:47 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:49 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:51 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:53 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:55 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:57 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:05:59 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:01 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:03 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:05 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:07 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:09 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:11 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 8:06:13 PM: ["Hello from Windows Server 2"]
```

**Comment by Priya91** [comment] 2018-02-02 22:49
I observed the same output with OSX as well, it responds to the DNS update,

```
  Content: 2/2/18 2:43:56 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:43:58 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:00 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:02 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:04 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:06 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:08 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:10 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:12 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:14 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:17 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:19 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:21 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:23 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:25 PM: ["Hello from Windows Server 1"]
  Content: 2/2/18 2:44:28 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:30 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:32 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:34 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:36 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:38 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:40 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:42 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:44 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:46 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:48 PM: ["Hello from Windows Server 2"]
  Content: 2/2/18 2:44:50 PM: ["Hello from Windows Server 2"]
```

This is my OS environment information:

```
mac os 10.12.6

lasekar-osx:FunctionalTests lakshmipriya$ curl -V
curl 7.52.1 (x86_64-apple-darwin14.5.0) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.18.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by Priya91** [comment] 2018-02-02 22:50
@glennc We confirmed with our local repro that this bug doesn't repro. Can you provide more info, about the OS environment, about the curl Version, osx version, and the crypto backend curl uses on your osx?

**Comment by karelz** [comment] 2018-02-03 00:10
@rynowak any idea how is our environment different from yours?

**Comment by rynowak** [comment] 2018-02-03 00:32
I will provide more info about this tonight when I get home.

**Comment by wfurt** [comment] 2018-02-03 01:19
Is that curl from brew @Priya91 I get this on my 10.12.6.

macik:System.Net.Http furt$ curl -V
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 **SecureTransport** zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

There may be differences between stock default vs updated one.

**Comment by rynowak** [comment] 2018-02-05 03:18
Here's my version info:
```
➜  Client2 git:(master) ✗ curl -V
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

The other possible difference here is that my DNS server is running dnsmasq which isn't a production quality DNS server. Also the hosts that I'm using as servers are on my lan. 

That said, only HttpClient has these issues for me. I can see the state update almost immediately using Chrome, Curl, etc.

**Comment by Priya91** [comment] 2018-02-07 18:27
@rynowak We have a special case for LibreSSL in our code, where we use a single multi handler for all requests [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs#L199). So it could be possible that because your crypto backend is not openssl, and the same multi handle is being used you are hitting this issue.

**Comment by rynowak** [comment] 2018-02-07 18:49
OK, I'll see what I can do to change this configuration and see if that fixes the problem. Hopefully this solves the mystery.

**Comment by Priya91** [comment] 2018-02-12 22:18
Closing this issue as resolved. @rynowak feel free to reopen if it didn't fix your scenario.

**Closed by Priya91** 2018-02-12 22:18 UTC
Labels: area-System.Net.Http, needs more info, os-mac-os-x

**Comment by rynowak** [comment] 2018-02-18 00:32
To close the loop on this, I grabbed curl with OpenSSL off of brew and set the load with DYLD_LIBRARY_PATH and that solved the issue. Given that there's no official support for LibreSSL I'm not overly concerned about this. 

For anyone else faced with this issue, read https://spin.atomicobject.com/2017/09/28/net-core-osx-libcurl-openssl/ to understand how to get .NET Core to use a specific libcurl install.
