### ISSUE TITLE
Desktop: Tests under "System.ConfigurationTests.ApplicationSettingsBaseTests" failed with "System.PlatformNotSupportedException"

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#18832] opened 2017-04-24 08:39 UTC
Failed tests:
 System.ConfigurationTests.ApplicationSettingsBaseTests.GetSetIntProperty_SimpleSettings_Ok
 System.ConfigurationTests.ApplicationSettingsBaseTests.Context_SimpleSettings_InNotNull
 System.ConfigurationTests.ApplicationSettingsBaseTests.Reload_SimpleSettings_Ok 
 System.ConfigurationTests.ApplicationSettingsBaseTests.Providers_SimpleSettings_Empty
 System.ConfigurationTests.ApplicationSettingsBaseTests.GetSetStringProperty_SimpleSettings_Ok
 System.ConfigurationTests.ApplicationSettingsBaseTests.SettingsProperty_SettingsWithAttributes_Ok

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/System.ConfigurationTests/ApplicationSettingsBaseTests/GetSetIntProperty_SimpleSettings_Ok_isSynchronized__True_/

MESSAGE:
~~~
System.PlatformNotSupportedException : Operation is not supported on this platform.
~~~
STACK TRACE:
~~~
at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigPaths.cs:line 56 
at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigPaths.cs:line 157 
at System.Configuration.ClientConfigPaths.get_Current() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigPaths.cs:line 125 
at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\ConfigurationManagerInternal.cs:line 20 
at System.Configuration.ApplicationSettingsBase.get_Initializer() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 683 
at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propInfo) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 471 
at System.Configuration.ApplicationSettingsBase.EnsureInitialized() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 588 
at System.Configuration.ApplicationSettingsBase.get_Properties() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 141 
at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\SettingsBase.cs:line 56 
at System.Configuration.SettingsBase.get_Item(String propertyName) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\SettingsBase.cs:line 30 
at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 732 
at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\src\System\Configuration\ApplicationSettingsBase.cs:line 416 
at System.ConfigurationTests.ApplicationSettingsBaseTests.SimpleSettings.get_IntProperty() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\tests\System\Configuration\ApplicationSettingsBaseTests.cs:line 36 
at System.ConfigurationTests.ApplicationSettingsBaseTests.GetSetIntProperty_SimpleSettings_Ok(Boolean isSynchronized) 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Configuration.ConfigurationManager\tests\System\Configuration\ApplicationSettingsBaseTests.cs:line 97
~~~

**Comment by danmosemsft** [comment] 2017-04-25 16:08
Same cause as https://github.com/dotnet/corefx/issues/18711. `Assembly.GetEntryAssembly()` is sometimes returning null on desktop. POssibly we should just skip such tests on desktop

**Comment by safern** [comment] 2017-05-04 17:50
Tests are skipped now (#19348).

Should we close this? @JeremyKuhne @danmosemsft

**Comment by danmosemsft** [comment] 2017-05-05 05:42
@safern No, we never close issues that have tests disabled against them. They remain open to track fixing the problem and reenabling the test. 
This is definitely "future" now though.

**Comment by safern** [comment] 2017-05-05 05:45
I thought that because of the comment above, I didn't know if this was an intended difference in behavior, thanks for clarifying :)

**Comment by maryamariyan** [comment] 2019-03-02 17:15
_From @ericstj on Feb 28, 2019, 8:49 PM PST_

I don’t think this should be failing with NotSupported. I’d expect this to just forward to the desktop implementation. The linked issue looks like it’s lacking a good root cause analysis.

**Comment by safern** [comment] 2019-03-04 23:26
I think the problem is that this tests are actually using the netstandard implementation rather than the netfx implementation, therefore not working correctly. We should add a netfx configuration to the tests and I would expect them to pass.

**Comment by ericstj** [comment] 2019-03-06 18:59
I'm a bit surprised by this, but I agree with your assesment.  A netstandard configuration of the test should have no impact on the binaries used to *execute* the tests.  This should only impact the references used to compile the test.  The vertical being built/tested is what chooses all the runtime assemblies.  /cc @ViktorHofer

**Closed** 2019-09-18 14:31 UTC
Labels: area-System.Configuration, disabled-test, test-run-desktop
