### ISSUE TITLE
TcpListener should use cancel tokens

### ISSUE THREAD

**Issue by jjxtra** [dotnet/corefx#31586] opened 2018-08-03 19:22 UTC
Please provide cancel tokens to the async methods of TcpListener. It's possible to wrap a tcp listener with cancel token methods and call stop but this feels like an unnecessary step, and one that is not easy for all people to understand.

**Comment by GSPP** [comment] 2018-08-12 11:29
This is a duplicate of [Add a clean way to cancel a long-running Socket operation (e.g. accept or connect)]( https://github.com/dotnet/corefx/issues/5749).

**Comment by karelz** [comment] 2018-08-15 02:05
Duplicate of #5749

**Closed by karelz** 2018-08-15 02:05 UTC
Labels: api-suggestion, area-System.Net
