### ISSUE TITLE
WebSocket file descriptor leak when server returns error

### ISSUE THREAD

**Issue by sherlock1982** [dotnet/corefx#27765] opened 2018-03-06 10:30 UTC
**Description:**
WebSocket file descriptor leak when server returns error

**Environment:**
NETCore 2.0.5, 
Linux x64

**How to reproduce:**
Connect to a server which constantly returns errors with Websocket.
You will see that on Linux amount of file descriptors will drastically grow with each connection attempt.

The reason is that [here](https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs) when `sslStream.AuthenticateAsClientAsync` or any other function throws error on connect `stream` will not be disposed.

**Comment by davidsh** [comment] 2018-03-06 15:54
cc: @stephentoub @wfurt

**Comment by karelz** [comment] 2018-03-28 23:32
As pointed out in https://github.com/dotnet/corefx/pull/27767#issuecomment-370768157, the issue is fixed in 2.1 (you can try public [2.1 Preview1](https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/) release).
Servicing fix does not meet the bar - see details here: https://github.com/dotnet/corefx/pull/27767#issuecomment-377070444

**Closed by karelz** 2018-03-28 23:32 UTC
Labels: area-System.Net, bug, os-linux
