### ISSUE TITLE
unable to get cpuid by ManagementObjectSearcher

### ISSUE THREAD

**Issue by zhusheping** [dotnet/corefx#38242] opened 2019-04-24 07:52 UTC
I wan't get cpuid in a console app with core3.0 preview with

```c#
           String processorID = "";
            ManagementObjectSearcher searcher = new ManagementObjectSearcher(
                "Select * FROM WIN32_Processor");
            ManagementObjectCollection mObject = searcher.Get();
            foreach (ManagementObject obj in mObject)
            {
                processorID = obj["ProcessorId"].ToString();
            }
            return processorID;
```
And exception throwed:Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.

**Comment by jkotas** [comment] 2019-06-05 02:49
This is known issue with .NET Core 3.0 and old version of System.Management package.

For .NET Core 3.0, you need to reference latest preview version 4.6.0-preview5.19224.8 of https://www.nuget.org/packages/System.Management/ to workaround it.

cc @jkoritzinsky 

This is duplicate of #38093 and #35694

**Closed by jkotas** 2019-06-05 02:49 UTC
Labels: area-System.Management

**Comment by tqinli** [comment] 2019-10-16 00:29
I am using .net core 3.0, I changed my package reference to System.Management 4.6.0, but I am seeing this error instead: System.Management currently is only supported for Windows desktop applications.
What did I do wrong?
