### ISSUE TITLE
System.Transactions.Tests.AsyncTransactionScopeTests.AsyncTSTest failing in CI

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#13593] opened 2016-11-11 18:40 UTC
See https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/24/consoleFull#192703349679fe3b83-f408-404c-b9e7-9207d232e5fc.

```
10:08:56      System.Transactions.Tests.AsyncTransactionScopeTests.AsyncTSTest [FAIL]
10:08:56         System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
10:08:56         Expected: Transaction { IsolationLevel = (throws ObjectDisposedException), PromoterType = (throws ObjectDisposedException), TransactionInformation = (throws ObjectDisposedException) }
10:08:56         Actual:   (null))
```

**Comment by stephentoub** [comment] 2016-11-11 22:05
Dup of https://github.com/dotnet/corefx/issues/12228?

**Comment by dmetzgar** [comment] 2016-11-14 23:48
Closing as duplicate of #12228

**Closed by dmetzgar** 2016-11-14 23:48 UTC
Labels: area-System.Transactions, test-run-core
