### ISSUE TITLE
ColorTranslator giving Named Color with null Name

### ISSUE THREAD

**Issue by Sebbs128** [dotnet/corefx#29472] opened 2018-05-03 05:44 UTC
I've just come across this issue. So far I have only the one reproducible case, but I can verify this is a break in behaviour from .NET 4.6.2.

Under .NET Core 2.0 using the package System.Drawing.Common v4.5.0-preview2-26406-04, `ColorTranslator.FromWin32(16777215)` returns a `Color` with `IsNamedColor == true`, but `Name == null` instead of `White`

```c#
    class Program
    {
        static void Main(string[] args)
        {
            var c = System.Drawing.ColorTranslator.FromWin32(16777215);
            Console.WriteLine($"Is Named Color? {c.IsNamedColor}");
            Console.WriteLine($"Color Name: {c.Name}");
            Console.WriteLine($"Color Name is null? {c.Name == null}");
            Console.ReadLine();
        }
    }
```

[EDIT] Add C# syntax highlighting by @karelz

**Comment by safern** [comment] 2018-05-11 17:01
Hello @Sebbs128 thanks for reporting the issue. I was able to repro the issue when running on .netcoreapp2.0 but we fixed this in .netcoreapp2.1 -- if you move to use the latest SDK and set the `TargetFramework` in you project to netcoreapp2.1 you will not hit this issue anymore. 

Just FYI this issue is caused by the same reason as: https://github.com/dotnet/corefx/issues/29269 and we decided not to fix it in 2.0 as it is already fixed in 2.1 which is faster and has a lot more benefits than 2.0 :) 

Please feel free to re-open or report another issue if you hit other issues or if you just need help.

**Closed by safern** 2018-05-11 17:01 UTC
Labels: area-System.Drawing, bug, tenet-compatibility
