### ISSUE TITLE
Microsoft.Windows.Compatibility: Problem loading NetStandard 2.0 Library with net462 AppDomain and Assembly.Load

### ISSUE THREAD

**Issue by FlorianRainer** [dotnet/corefx#28861] opened 2018-04-05 17:58 UTC
Project Setup:

1: `netstandard2.0` ClassLibrary used for `netcoreapp2.0` and `net462`
2: `net462` Project, Console App in my case.

The netstandard2.0 class uses the `Microsoft.Windows.Compatibility` Package for Image processing `System.Drawing.Image.FromStream`.

The net462 App loads the `netstandard2.0` Lib at runtime in a separated AppDomain.
This works without problem for `netstandard2.0` but `Microsoft.Windows.Compatibility` returns an exception `System.Drawing is not supported on this platform.`. But normaly it should no problem to use System.Drawing on full framework on windows. If i reference the netstandard2.0 Lib to the net462 Project and call the Method, it works without problems.

To Reproduce:
1: `netstandard2.0` Class:
`TestClass.cs`
```C#
using System;
using System.Drawing;
using System.IO;
using System.Net;

namespace StandardLib
{
    public class TestClass
    {
	    public void DoImageStuff()
	    {
		    using (var webClient = new WebClient())
		    {
			    var data = webClient.DownloadData("https://www.google.de/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png");
			    using (var memoryStream = new MemoryStream(data))
			    {
				    using (var img = Image.FromStream(memoryStream))
				    {
					    var x = img.Height;
					    var y = img.Width;
					    Console.WriteLine($"Image: {x}x{y}");
				    }
			    }
		    }
	    }
    }
}
```

`StandardLib.csproj`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- CopyLocalLockFileAssemblies needed to get `System.Drawing.Common.dll` in bin folder as part of the build output, not needed, but needs dotnet deploy and not works with simple VS build -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="2.0.0-preview1-25914-04" />
  </ItemGroup>

</Project>
```

2: `net462` Console App
```C#
using System;
using System.Reflection;
using System.Security.Policy;

namespace DllLoadingTest
{
	class Program
	{
		static void Main(string[] args)
		{
			//this works if ProjectReference is added
			//new TestClass().DoImageStuff();

			var appDomainSetup = new AppDomainSetup
			{
				ApplicationName = "NAME"
			};

			var appDomain = AppDomain.CreateDomain(appDomainSetup.ApplicationName, new Evidence(), appDomainSetup);

			var wrapper = (AssemblyWrapper)appDomain.CreateInstanceAndUnwrap(typeof(AssemblyWrapper).Assembly.FullName, typeof(AssemblyWrapper).FullName ?? string.Empty);

			wrapper.LoadAssembly(@"..\..\..\..\StandardLib\bin\Debug\netstandard2.0\StandardLib.dll");

			Console.WriteLine("Loading OK!");
			Console.ReadKey();
		}

		public class AssemblyWrapper : MarshalByRefObject
		{
			public override object InitializeLifetimeService()
			{
				return null;
			}

			public void LoadAssembly(string libraryPath)
			{
				var assemblyName = AssemblyName.GetAssemblyName(libraryPath);
				var assembly = Assembly.Load(assemblyName);

				var type = assembly.GetType("StandardLib.TestClass");

				//just a hack to use dynamic, with reflection or common udes interfaces the problem still exists
				dynamic instance = Activator.CreateInstance(type);

				instance.DoImageStuff();
			}
		}
	}
}
```

`DllLoadingTest.csproj`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

**Comment by danmosemsft** [comment] 2018-04-05 20:51
@weshaggard any thoughts about this? Why is it loading the netstandard dummy assembly and not type forwarding to the NETFX implementation?

**Comment by weshaggard** [comment] 2018-04-12 17:58
```
    <!-- CopyLocalLockFileAssemblies needed to get `System.Drawing.Common.dll` in bin folder as part of the build output, not needed, but needs dotnet deploy and not works with simple VS build -->
```

That shouldn't be needed and I suspect might be the source of your problem.

Can you instead try adding a reference the the System.Drawing.Common package in your net462 project?

**Comment by FlorianRainer** [comment] 2018-04-12 18:48
@weshaggard to add the reference is not possible, those 2 projects are normaly separated solutions.
the net462 Project is a Windows Service. this service is dynamicaly loading plugin libraries, this are libraries just implementing a certain interface and compiled to a set of dlls. this can be net4.x full framework or like in my example netstandard. Those libraries are not only used by this windows service, they are used as well als API with asp.net core / mvc.

the used libraries in this projects can vary, it can be a simple pacakge or some hundred. it's impossible to and if possible it would be a bad pattern to reference those packages in our windows host service.

this service must be full framework for AppDomain usage, isolation and many more.
but i have used already much packages with netsatndard in this way even with  `CopyLocalLockFileAssemblies ` the only problem until now was related to `System.Drawing.Common.dll`

**Comment by FlorianRainer** [comment] 2018-04-13 11:15
ok, this explaination makes sense, and i perfectly unserstand why this is happening.
But ist not only related to `CopyLocalLockFileAssemblies` like i described upon.
I've added this only to work with visual studio build output in bin folder.

My normal usecase is the following.
- remove `CopyLocalLockFileAssemblies'  from `StandardLib.csproj`
- use 'dotnet publish .\StandardLib.csproj -c Release -r win'
- use the path to `.\StandardLib\bin\Release\netstandard2.0\win\publish\StandardLib.dll` for `wrapper.LoadAssembly()`

the same problem will appear.

Following points are perfectly fine for me:
- if i compile vs net462 i get the dll with shim to `system.drawing`
- if i compile vs netstandard20 i will get the netstandard implementation
 - i compile my dynamic lib VS netstandard20 so i should get the netstandard implementation, right
 - this library should work on windows, but deliver this error message on non windows systems.

The strange thing about this is, if i don't call `Image.FromStream` and use something else from like `new Rectangle(new Point(1, 2), Size.Empty)` it works (ok, because of no plattform specific differences, but if i take a look at the Process Explorer i see the following:

![grafik](https://user-images.githubusercontent.com/12272092/38731869-5a420fdc-3f1c-11e8-8b25-bf161b6e98d3.png)

It seems to load System.Drawing.dll from GAC, and NOT even loads `System.Drawing.Common.dll` thats realy strange and i dont unserstand why.
- if realy System.Drawing.dll from GAC is loaded, why it makes problems on `Image.FromStream`?

**Comment by glopesdev** [comment] 2020-01-23 03:18
This is a real debugging nightmare: essentially this means that if I'm debugging my netstandard 2.0  class library by launching an external application that loads that library (a very reasonable approach to debugging plugin libraries btw), I am actually prevented from accessing System.Drawing.Common classes.

It's baffling to me that there are different "special cases" when generating .exe and .dll code. I've also been trying everything to get System.Drawing.Common to load correctly on Windows, including copying the "runtimes" folder that is placed there when deploying a netcoreapp target, but it seems like there is a requirement on some ".deps.json" file that specifies the runtimes.

I really don't understanding how the .NET core abstraction is leaking all over the place in a .NET standard project, which is supposed to behave equivalently to a .NET framework library (i.e. it should be possible to load such a DLL on a normal .NET fx app and have it behave as a normal .NET framework assembly), or am I missing something?

**Comment by glopesdev** [comment] 2020-01-23 03:23
Btw, I also figured out you can add this directive to the csproj file and will generate the runtimes folder and everything for your library project:

`<PreserveCompilationContext>true</PreserveCompilationContext>`

Unfortunately, this still doesn't work if the DLL is loaded from an external .NET application, it's as if the runtime has no idea what to do with these files unless .NET core is actually used to start the process.

**Comment by danmosemsft** [comment] 2020-01-23 03:50
Cc @ericstj

**Comment by glopesdev** [comment] 2020-01-23 07:03
Even more strange, if I change the library target to `net472 `(with an explicit reference to `System.Drawing`) but consume a `netstandard2.0` 3rd party library that relies on `System.Drawing.Common`, I still get the same error when creating a `System.Drawing.Bitmap` _in my `net472` code_. That is just incredibly bizarre, because in this case I am letting the tooling do all the work, I am creating a `net472 `library that consumes a `netstandard2.0` library and it just blows up when its loaded by a `net472 `application.

How was this supposed to work anyway? At this point I am completely lost.

**Comment by glopesdev** [comment] 2020-01-23 07:16
I have deleted my previous comment, as I noticed a problem with my debugging settings. I can confirm that building my own library as a `net472` project works, even if it consumes a 3rd party `netstandard2.0` library.

It would still be important to know what is preventing a pure `netstandard2.0` library build to load `System.Drawing` correctly in a .NET framework host on Windows. Exactly as @FlorianRainer explained, this is fundamental for plugin like deployment and the same as him, all other `netstandard` libraries seem to work fine apart from `System.Drawing.Common`.

**Comment by ericstj** [comment] 2020-01-23 16:58
Any library which requires a different .NETFramework implementation will face this issue.  As you mention, not all libraries do, but many do.  This is the case those which are exposing existing .NETFramework API to netstandard libraries but are not part of the standard, like System.Drawing.Comming, System.Configuration.ConfigurationManger, Microsoft.Win32.Registry, etc.  They must provide a different .NETFramework implementation so that they can forward the types rather than define them.  A single assembly cannot both forward and define types so we have to rely on framework specific assemblies.

It's not the case that a plugin must be built for .NETFramework, but it must be restored and published for .NETFramework.  This is so that the plugin recieves it's .NETFramework version of all dependencies.

**Comment by glopesdev** [comment] 2020-01-23 18:36
This is fair enough, but what if the plugin is loaded by a host other than the .net core tooling? Is there a documented way that the host can resolve the specific versions of these assemblies?

I imagine you can hook into AppDomain.AssemblyLoad event (which works even on core) and then when one of these assemblies comes up you have to resolve them to the correct assembly.

Is there an easy way to know which assemblies need to be redirected? Maybe some metadata that can be reflected upon on the default netstandard shim?

**Comment by ericstj** [comment] 2020-01-23 19:09
>  hook into AppDomain.AssemblyLoad event

[AssemblyLoad](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyload?view=netframework-4.8) doesn't let you change the resolution, [AssemblyResolve](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.8) does, but it's only raised when the runtime cannot locate an assembly which is not the case here.

> Is there an easy way to know which assemblies need to be redirected?

A .NETStandard project's output is guaranteed to be runnable.  You need to publish it for a concrete framework, or reference it from a concrete framework project.

Even the .NETCore host doesn't know how to select *framework* specific libs, it can only handle *runtime* specific libs.  Take things like System.Memory, or Microsoft.BCL.AsyncInterfaces, etc.  These will have the same problem in .NETCoreApp: the netstandard version has type-defs, but the .NETCoreApp version needs to forward to the framework.  The same problem can exist in 3rd party packages as well, take something like Newtonsoft.Json: it has a netstandard implementation as well as a net45 implementation.  When referenced in a net45 app it will get the net45 implementation.  These differences in implementation have noticeable side-effects.  It just happens to be *very* noticeable in the case of System.Drawing (intentionally).

**Comment by glopesdev** [comment] 2020-01-23 19:14
All of this makes sense (my mistake about the AssemblyResolve name). What I am trying to understand is what exactly is meant here by “publishing”. When I publish a netcore app, it creates a .deps.json file that points to different runtime assemblies. Is this file handled by .net core when running an app? What about a .net framework application? Does it understand this file?

If I have a host that installs its plugins on demand via NuGet, what precise steps does it need to do to replicate the “publish” functionality?

I guess worst case scenario the install at the moment is done to host specific locations that have to be handled with AssemblyResolve anyway, so the decision process could be done there.

**Comment by glopesdev** [comment] 2020-01-23 19:18
Can we count on these NuGet packages to have a deps.json file? If this is standard we could use this to know a particular assembly needs “publishing” or a specific platform resolution.

**Comment by ericstj** [comment] 2020-01-23 19:25
deps.json is framework-specific.  The only thing that knows how to select from many frameworks is NuGet restore, nothing at runtime does this.  So you would need to restore the package for a specific framework + potentially RID in order to understand which is the best asset to apply.  This gets even more complicated because packages have framework-specific dependencies, so even if you can select which lib to use from a package, you might need to download additional packages for that different framework and select libs from those too.  This is complicated as well, since it's a graph walk to resolve packages and versions, in other words a full restore.

**Comment by glopesdev** [comment] 2020-01-24 01:43
Sure, but again, some API is doing that work, presumably the NuGet core SDK itself. Ultimately one would just let NuGet do the walk, providing a target framework. For me its good enough to know resolution is done at package install time, I will take care of the rest. Thanks.

**Comment by ericstj** [comment] 2020-01-24 05:56
Closing as the original question was answered and there isn’t any actionable bug here.

**Comment by glopesdev** [comment] 2020-01-24 05:56
Actually, after reading [this pos](https://natemcmaster.com/blog/2017/12/21/netcore-primitives/)t and the comments it seems like there are additional mechanisms for runtime resolution of framework-specific assemblies specifically for this scenario of dependencies coming from packages, either by using `.runtimeconfig.json` or via specifying --additional-deps: https://github.com/dotnet/core-setup/issues/1597

**Closed by ericstj** 2020-01-24 05:56 UTC
Labels: area-Infrastructure-libraries, packaging

**Comment by glopesdev** [comment] 2020-01-24 05:59
I'm not sure I agree that there is no bug, as there are clearly two distinct mechanisms of interpreting how to resolve System.Drawing.Common for .NET framework and .NET core; the intended equivalence where .NET standard can act as an equivalent target for either is not fulfilled when loading assemblies through Assembly.Load mechanisms.

**Comment by ericstj** [comment] 2020-01-24 06:31
Netstandard is just API it isn’t a runnable thing.  

NuGet is the only supported mechanism to select framework specific assemblies from packages. You must restore or publish for a concrete framework, eg net*, netcoreapp*. A .NETStandard project’s output is not runnable since it doesn’t select the right target framework assets fRom dependent packages.  We have no mechanism in .NETFramework nor .NETCore that understands/selects target framework specific libraries.

@jeffschwMSFT @vitek-karas can back this up as owners of our host and loader.  Runtimeconfig and deps.json are not solutions to this problem.

You can read more:
https://github.com/dotnet/corefx/issues/18217
https://github.com/dotnet/standard/blob/master/docs/faq.md
https://xunit.net/docs/why-no-netstandard

**Comment by vitek-karas** [comment] 2020-01-24 11:06
I absolutely agree with what @ericstj wrote, maybe just to make some things a bit clearer:

Let's say I have a netstandard2.0 class lib called MyPainting.
* If I include it in an application via either ProjectReference or PackageReference, then during the build of the application NuGet will restore all the dependencies transitively, so it will also restore dependencies for MyPainting. Since the app is built with TFM for a runnable thing (net462 or netcoreapp20, but not netstandard2.0), it will know which runtime assets to restore for the dependencies and will only pick those matching the TFM. For some packages it's possible that there's only netstandard2.0 binary - which means it works exactly the same everywhere, but for other package there will be net462 specific binary and netcoreapp2.0 specific binary - NuGet will then pick the right one.
* If I want to consume MyPainting as a plugin - so load it at runtime, then I need to publish it targetting a runnable TFM. The code inside may be written against netstandard2.0 and may even have the same binary everywhere, but the dependencies of MyPainting may not. So I need to publish it for net462 or netcoreapp2.0 (separately) - during that publish NuGet will again pick the right assets from all the dependencies.

The functionality to pick the right assets for a given TFM is only implemented in NuGet - note that even .NET Core SDK doesn't know how to do this - instead it calls into NuGet. There is an API which one can call to do this (just like SDK does that) - I don't know what it is right now, but if you're interested I can include the right people. That said, it's not something meant to be used at runtime - so in theory possible, but in practice there might be issues with it.

`.runtimeconfig.json` is a file which determines which version of .NET Core will the app use. It is .NET Core specific (.NET Framework doesn't understand this file and doesn't look at it). It basically stores that the app should run on .NET Core 2.1.1 (for example). Plugins loaded via Assembly.Load (and friends) don't need `.runtimeconfig.json` since the host app determines the exact version of the .NET Core. (Side note - components/plugins which are loaded via native hosting APIs do need `.runtimeconfig.json` as they may need to start the runtime - and thus select the correct version of .NET Core).

`.deps.json` is a file which describes runtime assets to be used by the app or plugin. This is a .NET Core specific file (again .NET Framework doesn't understand this file and doesn't look at it). There are several different things `.deps.json` can store, but from the runtime's perspective its main purpose is to determine the correct assets for a given RID. RID is the identification of the platform the app is running on (for example `win-x64`, or `linux-arm32`, ...). If the app/plugin is built as portable app (so there's no RID specified during its build/publish), the app/plugin may carry multiple assets specific to certain RIDs. For example it's possible for MyPainting to have different implementation on Windows versus Linux. Note that this is distinct from TFM which determines which kind/version of the runtime it needs. The `.deps.json` then contains the necessary information to find the correct asset for a given RID. For apps the `.deps.json` is processed by the .NET Core native host (dotnet.exe or app.exe). For plugins, you can consume this via the `AssemblyDependencyResolver`.
