### ISSUE TITLE
Desktop: Tests under "System.Diagnostics.TextWriterTraceListenerTests.DelimiterWriteMethodTests" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#17773] opened 2017-04-01 09:24 UTC
Configuration: outerloop_netfx_windows_nt_debug

Failed tests:
DelimiterWriteMethodTests\TraceEvent_FormatString_Test
DelimiterWriteMethodTests\TraceData_Object_Test
DelimiterWriteMethodTests\TraceEvent_String_Test
DelimiterWriteMethodTests\TraceData_ObjectArray_Test

Message: 
~~~
Assert.Equal() Failure\r\n ↓ (pos 46)\r\nExpected:
 ···ummy message\";;4552;\"8\";\"2017-03-31T23:12:18.3920125Z\";981020···\r\n
Actual:
 ···ummy message\";;4552;;\"8\";\"2017-03-31T23:12:18.3920125Z\";98102···\r\n ↑ (pos 46)
~~~

Stack Trace:
~~~
at System.Diagnostics.TextWriterTraceListenerTests.DelimiterWriteMethodTests.TraceEvent_FormatString_Test(TraceFilter filter, TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args) in D:\j\workspace\outerloop_net---903ddde6\src\System.Diagnostics.TextWriterTraceListener\tests\DelimiterWriteMethodTests.cs:line 58
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/3/testReport/System.Diagnostics.TextWriterTraceListenerTests/DelimiterWriteMethodTests/TraceEvent_FormatString_Test_filter__null__eventCache__TraceEventCache___Callstack________at_System_Environment_GetStackTrace_Exception_e_______DateTime___2017_03_31T23_12_18_3920125Z__LogicalOperationStack_______ProcessId___4552__ThreadId_____8___________source____Co____1984________eventType__Verbose__id__12__format____Dummy_message____args__null_/

**Comment by danmosemsft** [comment] 2017-04-01 22:56
Caused by this in desktop:
https://referencesource.microsoft.com/#System/compmod/system/diagnostics/DelimitedListTraceListener.cs,170

now being this in core:
https://source.dot.net/#System.Diagnostics.TextWriterTraceListener/System/Diagnostics/DelimitedListTraceListener.cs,171

Note this has been removed -- it causes the extra delimiter
```
                if (IsEnabled(TraceOptions.LogicalOperationStack))
                    WriteStackEscaped(eventCache.LogicalOperationStack);
                Write(Delimiter); // Use get_Delimiter
```
The code has been this way since 2015.

@brianrob, @vancem do you own this and if so is this a known and acceptable change?

**Comment by danmosemsft** [comment] 2017-04-04 01:03
@brianrob, @vancem  ?

**Comment by brianrob** [comment] 2017-04-04 04:09
I believe we do own this, but took it over recently, so I do not have context on this change.  We will need to investigate this.  This issue is actually a duplicate of #10880, so I'll close this one.

**Closed by brianrob** 2017-04-04 04:09 UTC
Labels: area-System.Diagnostics, test-run-desktop
