### ISSUE TITLE
System.Diagnostics.Process.GetProcesses and System.Diagnostics.ProcessModule

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25652] opened 2017-12-02 08:53 UTC
_From @diamondes3 on August 11, 2017 18:47_

I'm creating a program that needs to get a list of currently executing processes in memory and take action to kill a given process, if it's a different instance of the same (currently executing program) that has become hung for some reason; where I have a criteria based on start time to declare a given process as being hung.  This logic is being developed on a windows machine using "dotnet" core, then packaged and run on a Ubuntu machine.

If I get a list of processes via "Process.GetProcesses", I can see my currently executing logic in the list as "dotnet".  This isn't real helpful, as what if there are X different "dotnet" programs running on this machine, they all look like they are the same logic due to the "dotnet" name.  Some of them MIGHT be hung instances of the logic I'm after, some of them MIGHT be totally other "dotnet" assemblies.

I figured out, that if I examine the list of modules for a given process (ProcessModule), the ProcessModule.ModuleName is the name of the underlying .dll that the "dotnet" core environment is running.

This works fine on the Windows machine running Visual Studio.  When I compile and package the logic and run it on the Linux machine, I get can get the list of Processes, examine their corresponding modules; however, the underlying .dll that the "dotnet" core is executing is missing from the list of modules that should be in that given process.  In other words, the .dll name shows up as a module in the Windows process, but does NOT show up as a module in the Linux process; even though numerous other modules DO show up in the Linux environment for the given process.

There are no exceptions or any other errors that I'm seeing, just not seeing the underlying .dll listed as a module for a given process on the Linux machine.

Any constructive thoughts on this?

_Copied from original issue: dotnet/coreclr#13340_

**Comment by jkotas** [comment] 2017-12-02 08:53
_From @benaadams on August 11, 2017 21:40_

Maybe add to: https://github.com/dotnet/core-setup/issues/2007

**Comment by jkotas** [comment] 2017-12-02 08:53
_From @diamondes3 on August 11, 2017 22:0_

That'd be fine. It's a bit of an add on to #2007 if you try to solve the
module issue.

If you solve the issue in #2007, I think that would suffice for what I'm
describing, unless you find there is some logic issue within the code that
is exposing the attributes of the modules.

**Comment by jkotas** [comment] 2017-12-02 08:55
Dup of https://github.com/dotnet/corefx/issues/23972 ?

**Comment by joperezr** [comment] 2018-03-26 19:54
I do believe this is a dupe of #23972 as @jkotas suggests, so closing this one for now.

**Closed by joperezr** 2018-03-26 19:54 UTC
Labels: area-System.Diagnostics.Process
