### ISSUE TITLE
ClientWebSocket not using system proxy settings on Windows

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#31242] opened 2018-07-21 18:30 UTC
This appears to be a bug in HttpSystemProxy class used in SocketsHttpHandler.  The problem might not be isolated to just ClientWebSocket.  But the parser in ParseProxyConfig doesn't seem to be able to handle simple "host:port" strings that are in IE settings.

https://github.com/dotnet/corefx/blob/3ea1a8cf78073491f9532e36a738a7b8be44829a/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpSystemProxy.cs#L214

Repro Code:
```c#
//using System;
//using System.IO;
//using System.Net;
//using System.Net.Http;
//using System.Net.WebSockets;
//using System.Threading;

var uri = new Uri("wss://corefx-net.cloudapp.net/websocket/echowebsocket.ashx");
var socket = new ClientWebSocket();
socket.ConnectAsync(uri, CancellationToken.None).GetAwaiter().GetResult();
```

IE Settings example:
![image](https://user-images.githubusercontent.com/7684835/43039035-59c2d6c6-8cd9-11e8-8c84-6005443d727a.png)

I debugged this to the ParseProxyConfig() method.  It is getting a value of "localhost:3128".  But ends up returning null URIs.  So, the proxy is ignored.

**Comment by davidsh** [comment] 2018-07-21 18:30
cc: @wfurt

**Comment by wfurt** [comment] 2018-07-24 22:09
reopening for 2.1 servicing: 

**Description**
When using control panel or IE to configure HTTP proxy, 2.1 HttpClient cannot parse them correctly. 

**Customer Impact**
HTTP Proxy configuration no longer works after upgrading to 2.1 on Windows.

**Regression?**
Yes. This is regression from 2.0 

**Risk**
low.
This change improves parsing of HttpProxy value to cover cases missed in 2.1 release.

**Comment by danmosemsft** [comment] 2018-07-26 19:34
Shiproom asked asked whether we have some test holes around proxies that have led to all these servicing issues, and whether we expect more..

Info from @davidsh :

Yes, we do have test holes in scenarios involving proxies.  @Karel Zikmund is aware of that.  We have been trying to react to these incoming issues.  Some of the holes are due to authentication scenarios and system/machine settings scenarios (especially Windows auth like Negotiate/NTLM) arounds proxies which are not possible to test in CI right now.  We knew these holes existed prior to shipping .NET Core but the decision at the time was to de-prioritize investment in those tests since other things took higher priority.

We are hoping to increase investment in this test area.

I did a sanity test pass (manual testing) and I think that the list below is the bulk of the problem areas for proxies and proxy authentication.

cc @Pilchie fyi

**Comment by Pilchie** [comment] 2018-07-26 19:53
Thanks for the follow-up.  Is this something that we should consider adding to a manual walkthrough script for vendors until we can get better automated coverage here?

**Comment by danmosemsft** [comment] 2018-07-26 20:35
No doubt that's one of the options to look at.

**Comment by vivmishra** [comment] 2018-07-31 18:20
Approved.

**Comment by joshfree** [comment] 2018-08-09 18:39
@wfurt can you please add the 2.1 PR to this issue and close it once you’ve merged the PR? Checkin needs to be completed before Tuesday to make 2.1.4

**Comment by wfurt** [comment] 2018-08-09 18:43
It is #31367 @joshfree . marked as no-merge

**Comment by davidsh** [comment] 2018-08-09 18:48
>It is #31367 @joshfree . marked as no-merge

@wfurt it was marked as "no-merge" at the time to prevent it from being merged since the branch wasn't ready for 2.1.4 fixes.  But @joshfree is now saying it can be merged.

I will remove the "no-merge" flag.

**Comment by wfurt** [comment] 2018-08-09 18:49
thanks for clarification @davidsh .

**Comment by joshfree** [comment] 2018-08-09 19:10
Thanks all!

**Comment by wfurt** [comment] 2018-08-09 23:16
#31367 merged

**Closed by wfurt** 2018-08-09 23:16 UTC
Labels: Servicing-approved-2.1.4, area-System.Net.Http.SocketsHttpHandler, bug, os-windows, tenet-compatibility

**Comment by CIPop** [comment] 2018-08-30 19:57
@wfurt @davidsh @karelz  a few servicing questions:
1. is this going to be available in .NET Core 2.1? If yes, is it sufficient to upgrade to the latest SDK?
2. What are the instructions for 3rd parties that did `dotnet publish` to get the new fix?

/cc @tameraw, @abhipsamisra

**Comment by karelz** [comment] 2018-08-30 20:03
It will be part of 2.1.5 release (cc @danmosemsft for confirmation)

For self-contained apps, you have to republish with 2.1.5.
For apps relying on shared-framework being installed, you need to upgrade to 2.1.5 on the server.
Does it help?
