### ISSUE TITLE
Add Client certificate support to HttpClient API

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#4479] opened 2015-11-12 22:07 UTC
The `HttpClientHandler` API has a `ClientCertificateOptions` enum that lets you pick between `Automatic` and `Manual` client cert option. Choosing `Automatic` lets the system choose the "best" client certificate for the user from among the installed and accessible ones. `Manual` means that the developer can explicitly pass in a client cert.

However, `HttpClientHandler` does not have a `ClientCertificate` property, so you can't assign a certificate for the `Manual` option to use. This issue tracks the fix to address this gap. (`WinHttpHandler` has a `ClientCertificates` property for this purpose, but it is not x-plat and is not supported for all app models (e.g. UWP))

If you have specific requirements around this feature, please enter them here.

**Comment by SidharthNabar** [comment] 2015-11-12 22:08
@davidsh @ericstj @mconnew @terrajobst  - PTAL

**Comment by flint-rocketdesk** [comment] 2016-03-07 12:54
@SidharthNabar This is a blocking issue for ASP.NET Core adoption for many of us, so your team's work here is greatly appreciated.

Our specific requirement combination is HTTP/2 support with client certificates.  This is for our APNS (HTTP/2) application servers.  

As a very-short-term workaround, we are currently running UWP apps inside instances of Windows 10/Server2016 utilizing System.Net.Http.HttpClient and HttpClientHandler -- because we love .NET and see a bright future with .NET Core.  But in reality this creative arrangement is a painful stop-gap until we can move all of our code onto ASP.NET/.NET Core.

Right now we have half a solution with Linux and half a solution with Windows: HTTP/2 is supported for ASP.NET Core on Linux #dotnet/corefx#4756 and HTTP Client Certificates are only supported using WinHttpHandler on Windows #dotnet/wcf#544

If we could move everything onto ASP.NET Core on Linux on Azure, life would be fantastic.

**Comment by SidharthNabar** [comment] 2016-03-08 00:33
@flint-rocketdesk : Thanks for your interest in the HttpClient API. If I correctly understand your requirements, you need two things:
1. Ability to pass in a specific client certificate to HttpClient
2. HTTP/2 support

and you need both of these in a portable API surface (e.g. HttpClient/HttpClientHandler) rather than a platform-specific API (e.g. WinHttpHandler). Am I correct? 

This is actually a part of a larger API direction, where our team is looking at properties of WinHttpHandler that are useful, and make sense cross-platform. We will then "promote" them up to HttpClientHandler, so that you can write portable code using those.

For HTTP/2, the answer is completely separate - whether or not we support HTTP/2 on a particular platform depends on whether the underlying OS supports it. So, in order for ASP.NET Core on Windows (#4870), it needs to be supported in WinHTTP in Windows Server OS (this is work-in-progress).

**Comment by flint-rocketdesk** [comment] 2016-03-08 02:05
@SidharthNabar Yes, exactly.  Thank you for taking the time to learn more about our requirements.  And thanks for helping me understand why specific features are available on the different features.

That path forward: innovating with custom properties per platform and then promoting those features to HttpClientHander is a great strategy.  I like that that also gives us the opportunity to test and give feedback on some of the new functionality before it goes "core".

A bit more feedback on client certificates: right now with UWP we have to run multiple builds of our APNS application "server" simultaneously, one for each iOS/Mac application (app bundle ID).  This is due to limitations in the System.Web.Http.HttpClient class (i.e. we cannot specify a certificate directly...so we just have to import exactly one certificate into our app's certificate store).  

So as a stopgap solution, we now have multiple builds of the same app, each with its own keystore, so that we can serve push notifications to each of our iOS and Mac apps.  One "server" for each iOS/Mac app.

My wish for client certificates: for .NET Core, it would be fantastic if we could specify the certificate to use (using Manual mode, with a .ClientCertificate property on the HttpClientHandler to select the client certificate).  

I've subscribed to this issue and can't wait to see what your team cooks up.  Thanks again for the info.

**Comment by mconnew** [comment] 2016-03-11 17:59
@flint-rocketdesk, you can specify a certificate directly to System.Web.Http.HttpClient. We do this in our [WCF code](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTHttpClientHandler.cs). Here's the [msdn](https://msdn.microsoft.com/en-us/library/windows/apps/windows.web.http.filters.httpbaseprotocolfilter.clientcertificate.aspx) documentation for the HttpBaseProtocolFilter.ClientCertificate property.

**Comment by davidsh** [comment] 2016-03-11 18:01
> you can specify a certificate directly to System.Web.Http.HttpClient

The actual namespace is Windows.Web.Http and not System.Web.Http.

**Comment by davidsh** [comment] 2016-04-09 23:18
Will be part of #7623

**Comment by flint-rocketdesk** [comment] 2016-04-13 21:32
@mconnew -- thanks for the tip on the HttpBaseProtocol filter.  We consolidated our UWP apps down to one and are able to select certificates programmatically now. :)

But that brings me to a strange, seemingly-undiagnosable bug in the UWP implementation of HttpClient...

**Comment by flint-rocketdesk** [comment] 2016-04-13 21:38
@SidharthNabar, @davidsh -- how can we help test the new HttpClient "HTTP/2 + client certificate" support in .NET Core?  The UWP implementation of HttpClient is exhibiting consistent and severe COM-level failures when interacting with Apple's new HTTP/2 APN servers (tested from multiple computers and versions of Windows 10).  We are moving 100% of our servers to ASP.NET Core and so we would really like to make sure that .NET Core performs flawlessly.

More info on the critical issue with UWP's implementation:
http://stackoverflow.com/questions/36592138/reproducible-failures-with-uwp-httpclient-http-2-and-client-certificates

With .NET Core, if we run into problems, we should be able to debug into the core.  [Unfortunately, with UWP and no source debugging access, we could find no way to diagnose the issue since neither Fiddler nor SSLStream fully support analysis when using HTTP/2 + client certificates.]  BTW, we did test against a PHP implementation of HTTP/2 (using mitmproxy) and those work flawlessly (along with Java implementations).

**Comment by davidsh** [comment] 2016-04-13 21:45
SInce you are using `Windows.Web.Http.Filters.HttpBaseProtocolFilter ` APIs directly, those are WinRT APIs and not .NET Core APIs.  So, this issue here in GitHub is not the appropriate place to discuss problems with Windows.Web.Http APIs.  There is no open source code for Window.Web.Http APIs here in GitHub.

Please open up an issue on Connect and/or Product Support to handle your inquiry.

**Comment by flint-rocketdesk** [comment] 2016-04-13 21:50
@davidsh - what's the best way for us to help test the upcoming .NET Core HttpClient revisions to make sure it works great with Apple's HTTP/2 servers (which require client certificates)?

P.S. On the off-topic: thanks for the pointer!  We will open a support issue on the WinRT APIs through Connect/Product Support (in addition to posting on StackOverflow as developer.windows.com suggested).

**Comment by davidsh** [comment] 2016-04-13 22:03
To be clear on HTTP/2 support for CoreFx System.Net.Http APIs:

1) For *Nix platforms, HTTP/2 is supported in System.Net.Http
2) For UWP variant of CoreFx, HTTP/2 is supported in System.Net.Http. That is because System.Net.Http for the netcore50 variant uses WinRT Windows.Web.Http APIs which support HTTP/2 via Wininet.
3) For Windows platforms and non-UWP, CoreFx for System.Net.Http does not yet support HTTP/2. This implementation uses Windows WinHTTP APIs which do not yet support HTTP/2.  Eventually, WinHTTP will support if on Windows in a future Windows 10 release. When that happens, we will activate it in the .NET layer in CoreFx via a dynamic detection mechanism (since other Windows versions won't have that support).

So, at present, there isn't any specific HTTP/2 Windows testing to do yet for non-UWP System.Net.Http.

**Comment by flint-rocketdesk** [comment] 2016-04-13 22:16
Thanks @davidsh.  That's great info with a lot of detail.

On #1...once client certificates are supported on *Nix platforms, we'll dig in an help test this out.  I'll watch for updates on this issue and #7623.  [I tried testing HTTP/2 minus the client certificates, but Apple just returns 403 FORBIDDEN so we'll have to wait a bit to be able to test #1.]

On #2...I have reported the CoreFx System.Net.Http.HttpClient bug (UWP) on MS Connect.

On #3...happy to test there too, once those updates are made.  Especially with Nano Server/IoT Core.

Thanks for the quick responses and all your team's work making .NET Core so awesome :)

**Comment by SidharthNabar** [comment] 2016-04-14 16:14
Thanks @flint-rocketdesk for this report - we are definitely interested in identifying such interop issues with HTTP/2. Since it is a fairly new standard, we do expect some differences between implementations at this point - I am discussing with our internal HTTP teams here and will let you know what the next steps are.

Thanks,
Sid

**Comment by markvincze** [comment] 2016-05-02 11:11
Hey everyone,

I've seen in the discussion multiple different libraries being mentioned, and I'm a bit confused:  
Is there currently any way in .NET Core to manually set a client side certificate with `HttpClient` in a way that I can run the application on Linux.

**Comment by davidsh** [comment] 2016-05-02 13:57
The short answer is yes but we have not officially locked the API. 

We are working on finalizing the System.Net.Http 4.1 API surface. We try to finalize the API by RTM. If you try out the latest packages from the MYGET dev feed You will find a property `HttpClientHandler.ClientCertificates` to set the client certificate on the HttpClientHandler object.

https://dotnet.myget.org/gallery/dotnet-core

**Comment by markvincze** [comment] 2016-05-02 15:43
@davidsh,

That's a lifesaver :)
I'll give it a try, thanks!

**Comment by davidsh** [comment] 2016-05-09 00:49
Closing this issue since it is part of #7623.

**Closed by davidsh** 2016-05-09 00:49 UTC
Labels: enhancement, System.Net

**Comment by flint-rocketdesk** [comment] 2016-08-19 23:01
@SidharthNabar - quick follow-up...

We have tested .NET Core 1.0 + HTTP/2 + SSL Client Certificate + Ubuntu 16.04 LTS.

It mostly works, but there's still one glitchy issue.  At least when trying to connect to Apple's APNS servers.

Scenario:
Establishing HTTP/2 SSL connections are almost instantaneous, as expected.  But when an APNS client certificate is added to the SSL request, .NET Core takes almost ten seconds to connect to the server.  Even worse, sometimes it just blocks asynchronously during the request for a minute or so and then simply throws an exception after timeout.

Follow-up requests (with the HTTP/2 connection already open) seem to work fine under our default test scenario.  We will be doing more intensive testing next week.

We use client certificates extensively for internal servers, and we will be testing HTTP/2 support there in the next week or two as well.  If these issues exist in local scenarios (i.e. NGINX + Kestrel + ASP.NET Core servers), I'll add that to this post.  

But at this point, it looks like it might be HTTP/2 + APNS specific--which is a critical interop target.

Thanks again for all the hard work your team has been putting into this!

**Comment by flint-rocketdesk** [comment] 2016-08-20 08:55
@davidsh and @SidharthNabar - the above issue appears to be a blocking bug in production.  .NET Core 1.0 is actually completely crashing when doing HTTP/2 requests with client certificates on Ubuntu 16.04.

Debug mode: when debugging inside VSCode on Ubuntu 16.04 desktop, the first call either takes 8-10 seconds to complete or completely times out and throws an exception.  Follow-up requests using the same connection execute properly and quickly.

Release mode: when running the same code in release mode on Ubuntu 16.04 server, with the same libcurl (7.47.0) HTTP2 support, .NET Core simply crashes with no exception after about 8-10 seconds.  No requests are successful.

We have tried using both async (await) and non-async (.GetAwaiter().GetResult()) and in both scenarios .NET Core 1.0 RTM just crashes with no chance to catch an exception.

Are there any tools we can run to help provide useful debug information?

**Comment by flint-rocketdesk** [comment] 2016-08-20 09:16
Here is the actual code we are using which causes .NET Core to crash.  If you comment out the line which adds the client certificate, the HTTP request succeeds (returning a "missing client certificate" message from the APNS servers).  If the client certificate is included, .NET Core crashes while attempting the request (after about 8 seconds).

To repro:
1. Install .NET Core 1.0 on Ubuntu 16.04 LTS
2. Compile libcurl from source to include HTTP/2 support
3. Save your APNS development certificate to disk, and reference it and your APNS bundle/deviceToken IDs in code.
4. Drop the code inside Program.cs Main() and run the code.  The HTTP request line of code will run for about 8 seconds and then .NET Core will crash hard without raising an exception.

REPRO CODE FOLLOWS (connecting to Apple APNS servers)

// create our HTTP Client Handler (which will be reused across HTTP/2 requests)
var clientHandler = new HttpClientHandler() { ClientCertificateOptions = ClientCertificateOption.Manual };
X509Certificate2 clientCertificate = new X509Certificate2("/home/ubuntu/apns_devcert.pfx", "password");
// INFO: comment out the following line to see that HTTP/2 is succeeding...APNS will simply return a "please provide a client certificate" message
clientHandler.ClientCertificates.Add(clientCertificate);
//
var myClient = new System.Net.Http.HttpClient(clientHandler);

// we will attempt to send five requests, 60 seconds apart, to ensure that HTTP/2 is working properly.
for (int i = 1; i <= 5; i++)
{
    Console.WriteLine("Starting request #" + i.ToString());

    // create the push notification request
    string deviceToken = "{device token from mac/ios device goes here}";
    string appBundleId = "{app bundle id goes here}";
    string messageUuid = Guid.NewGuid().ToString("D");

    var myRequest = new System.Net.Http.HttpRequestMessage(System.Net.Http.HttpMethod.Post, "https://api.development.push.apple.com:443/3/device/" + deviceToken);
    // upgrade the HTTP request to HTTP/2 (required for .NET Core on Linux)
    myRequest.Version = new System.Version(2, 0);

    myRequest.Headers.Add("apns-id", messageUuid);
    myRequest.Headers.Add("apns-expiration", "0");
    myRequest.Headers.Add("apns-priority", "10");
    myRequest.Headers.Add("apns-topic", appBundleId);

    StringContent content = new StringContent("{ \"aps\" : { \"alert\" : \".NET Core (request #" + i.ToString() + ") -- test message -- \" } }");
    myRequest.Content = content;
    try
    {
        // INFO: .NET Core crashes on the following line
        var response = myClient.SendAsync(myRequest).GetAwaiter().GetResult();

        // print out response to console 
        var responseString = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
        Console.WriteLine("Response: " + responseString);

        // optionally, verify that the response is using HTTP/2
        //Console.WriteLine("Response protocol: HTTP/" + response.Version.ToString());
    }
    catch (System.Net.Http.HttpRequestException ex)
    {
        Console.Write("HttpRequestException: " + ex.Message);
    }
    catch (Exception ex)
    {
        Console.Write("Exception: " + ex.Message);
    }

    // wait 60 seconds between test requests
    Task.Delay(60000).GetAwaiter().GetResult();
}

Console.WriteLine("Done");

**Comment by flint-rocketdesk** [comment] 2016-08-20 09:23
P.S. Here is a quick and dirty method for compiling HTTP/2 support into libcurl on Ubuntu 16.04 LTS:

sudo apt-get update
mkdir curl
cd curl
sudo apt-get build-dep curl
sudo apt-get install libnghttp2-dev
sudo apt-get source curl
cd curl-7.47.0
sudo debian/rules binary
cd ..
sudo dpkg -i *deb

To test for HTTP/2 support, run the following command and watch for "HTTP/2.0 200":
curl --http2 -I nghttp2.org

REFERENCES
How to compile HTTP/2 support for Ubuntu 16.04:
https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1567697

.NET Core Libcurl requirement for HTTP/2 support:
https://github.com/dotnet/corefx/pull/4756

**Comment by davidsh** [comment] 2016-08-20 14:55
@flint-rocketdesk 
This issue was originally about problems with Windows UWP apps and the use of HTTP/2 and/or client certificates.

Now it appears this issue is about Linux apps using HTTP/2 and/or client certificates.  Is that correct?  We want to clarify so that we get the right people looking at it.  Can you open up a new issue for this? Thx.

cc: @stephentoub

**Comment by flint-rocketdesk** [comment] 2016-08-21 14:43
@davidsh 
Wow, thanks for the quickly reply!  

Yes, to confirm: the target here is Ubuntu using HTTP/2 using client certificates.  

I have opened up a new issue as requested: #11036

cc: @stephentoub

**Comment by dluc** [comment] 2017-09-20 21:54
Just here to say that after 2 years there still is no solution for MacOS users, which is a real painful experience for .NET developers, more over since VS for Mac and IntelliJ Rider are becoming popular IDEs for xplatform .NET development. 

In case it's not sufficiently clear, the issue is not about "unit testing" which I noticed mentioned in here or some other linked GitHub issue. The issue is about allowing developers to work using HTTPS endpoints with invalid certs (e.g. self-signed certs), which is pretty common when doing some local development, and even more when working with distributed systems, e.g. microservices, running locally. HTTPS is mandatory when working with services like Azure Active Directory, so downgrading to HTTP is not always an option.

While working on MacOS Sierra I've tried the approaches described above, which apparently used to work for some time, but they don't work anymore, so there is really no solution, without going through other complicated and unsafe options which I haven't tried yet, e.g. installing untrusted CAs locally.

The amount of time lost and documentation to write to explain users what to do is huge, and I don't understand why this is still an unsolved problem when other programming languages had this feature for decades.
