### ISSUE TITLE
Provide ways to parse sections of a string, not an entire string.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/corefx#2254] opened 2015-07-06 20:18 UTC
Right now .Net provides lots of ways to convert strings to other values.  For example `Int32.TryParse`.  This is fine if you are starting with a string, but it's very suboptimal if you have a larger string, and are trying to parse out a piece of it.  You are forced to first create a substring, and then parse that.  This adds GC pressure to the system and can be a large perf impact.

It would be very beneficial to have overloads of these functions that took a start+length.  Alternatively, if there were some sort of struct representing a piece of a string, that could also work as well.  

Right now this impacts TypeScript greatly.  We have to marshal data from JavaScript to .Net.  This comes in as a string to us, which we then need to parse out into actual values (like ints).  We are forced to either send tons of strings over (not ideal), or send one big string over that we then are forced to break into tons of small strings.

Right now we've worked around this by hand-writing our own Int32.Parse that can work on subsections of a string.  But this is non-ideal and would really be served inside the runtime so everyone could benefit.  This is a place where really ony the runtime could implement this thing.  There is so much complexity around string parsing (even just for ints), with things like FormatSpecifiers and whatnot, that trying to duplicate it in another library would be unfeasible.

**Comment by KrzysztofCwalina** [comment] 2015-07-06 20:50
I am working on a prototype of a new formatting and parsing library. See https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Formatting. 
Formatting is more complete at the moment, but I have started working on parsing recently.

**Comment by JohanLarsson** [comment] 2015-07-06 21:30
[here](https://github.com/JohanLarsson/Gu.Units/blob/master/Gu.Units/Utils/DoubleParser.cs) is some code that parses a double from a starting position.

**Comment by danmosemsft** [comment] 2016-10-31 20:57
@KrzysztofCwalina is this issue redundant now - can you dupe it?

**Comment by KrzysztofCwalina** [comment] 2016-10-31 21:29
@danmosemsft, 
Yes, @botaberg is working on such parsing library. I am not sure if he has the exact issue to dup, but I think it would be good to open such issue in corefxlab and assign it to @botaberg.

**Comment by thomaslevesque** [comment] 2016-11-15 19:49
Related: #7593

**Comment by danmosemsft** [comment] 2016-11-15 19:54
@botaberg ?

**Comment by danmosemsft** [comment] 2016-11-15 19:55
Actually this is a dupe of #7593 I believe.

**Closed by danmosemsft** 2016-11-15 19:55 UTC
Labels: api-needs-work, area-System.Runtime
