### ISSUE TITLE
'Fireball' failure in Helix for 2 Socket tests on Redhat.72

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#16060] opened 2017-02-11 00:21 UTC
2x 'fireball' failure for RedHat 7.2 for these two tests:
System.Net.Sockets.Tests.SocketOptionNameTest:
* ReuseUnicastPort_CreateSocketGetOption_SocketsReuseUnicastPortSupport_OptionIsZero
* ReuseUnicastPort_CreateSocketSetOptionToZeroAndGetOption_SocketsReuseUnicastPortSupport_OptionIsZero

Logs:
* [20170209.02](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170209.02/workItem/System.Net.Sockets.Tests/wilogs)
* [20170208.02](https://mc.dot.net/#/product/netcore/110/source/official~2Fcorefx~2Frelease~2F1.1.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170208.02/workItem/System.Net.Sockets.Tests/wilogs)

cc: @MattGal

**Comment by Priya91** [comment] 2017-02-11 01:44
assigning to @MattGal  to confirm it's product issue first.

**Comment by MattGal** [comment] 2017-02-11 01:55
Assigning to @Priya91.   The test fails consistently with the same symptoms on RedHat 7.2 while others do not;  this is not the same issue as the Fedora runs.  If you have any evidence for this being an infra issue I will happily investigate.

**Comment by Priya91** [comment] 2017-02-11 02:13
@MattGal I thought you mentioned the build libs used for redhat may not be the right ones, and you were gonna confirm with Chris. Maybe I misunderstood it.

**Comment by MattGal** [comment] 2017-02-13 17:03
That's Fedora (we're currently build for 24 and running on 23.   Any current issues around that from offical runs should be disregarded until we address that.  Redhat does not have this problem.

**Comment by MattGal** [comment] 2017-02-13 17:38
Took a bit of a look here, something very odd is happening.  
Both of these tests have the same Condition attribte on their facts:
```
[ConditionalFact(nameof(SocketsReuseUnicastPortSupport))]
```

https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs#L46
Looking at the sources, we see that this test was clearly designed to be a conditional fact... 
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs#L17
And the condition is meant to always be false on non-Windows and pre-Windows 10 boxes:
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Net/Capability.Sockets.cs#L28 

The logic is slightly simpler but still the same idea on the 1.1.0 branch:
https://github.com/dotnet/corefx/blob/release/1.1.0/src/Common/tests/System/Net/Capability.Sockets.cs#L28
... namely this Fact should be excluded in any non-Windows-10 OS on the Rel 1.1.0 branch.  

It's almost like RuntimeInformation.IsOSPlatform(OSPlatform.Windows) did not work properly.  Either way, this raises several issues about how XUnit or the IsOsPlatform() method is functioning here.  

@davidsh , can you confirm whether this sort of functionality ought to work on Linux?

**Comment by karelz** [comment] 2017-02-13 17:55
@Priya91 should be able to answer Networking questions on Linux.

**Comment by Priya91** [comment] 2017-02-13 18:40
> It's almost like RuntimeInformation.IsOSPlatform(OSPlatform.Windows) did not work properly.

It could be that the windows version of ```System.Runtime.InteropServices.RuntimeInformation``` lib is copied to the redhat box, as the IsOSPlatform implementation is just a build time constant set according to the OS platform the library will be used at runtime.

**Comment by MattGal** [comment] 2017-02-13 18:55
Checking the assets included with the test (can be found in container "" in dotnetbuilddrops account, ping me if you need help getting to this), the only included copy of that assembly came from:

System.Runtime.InteropServices.RuntimeInformation\4.3.0\runtimes\unix\lib\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll.

Poking at that assembly using ILSpy, I'm unsure how to check whether it's hard coding to return the wrong thing.

**Comment by Priya91** [comment] 2017-02-13 19:17
@MattGal I copied down the helix libs and ran the tests locally on a redhat box with the azure image used by Jenkins CI, This is the output, the tests are correctly skipped.

```
[lasekar@rhel Unzip]$ ./RunTests.sh ../../../Payload/
Using ../../../Payload/ as folder for resolving package dependencies.
Executing in .
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 19:15:38
Commands:
./corerun xunit.console.netcore.exe System.Net.Sockets.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.0tests -notrait category=requireselevation -notrait category=failing -notrait category=nonlinuxtests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.Sockets.Tests
Discovered:  System.Net.Sockets.Tests
Starting:    System.Net.Sockets.Tests
   System.Net.Sockets.Tests.SocketOptionNameTest.ReuseUnicastPort_CreateSocketGetOption_SocketsReuseUnicastPortSupport_OptionIsZero [SKIP]
      Condition(s) not met: "SocketsReuseUnicastPortSupport"
   System.Net.Sockets.Tests.SocketOptionNameTest.ReuseUnicastPort_CreateSocketSetOptionToZeroAndGetOption_SocketsReuseUnicastPortSupport_OptionIsZero [SKIP]
      Condition(s) not met: "SocketsReuseUnicastPortSupport"
Finished:    System.Net.Sockets.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 603, Errors: 0, Failed: 0, Skipped: 2, Time: 6.118s
Finished running tests. End time=19:15:45. Return value was 0

```

**Comment by MattGal** [comment] 2017-02-13 19:39
@Priya91, Which correlation id did you use for this?

**Comment by Priya91** [comment] 2017-02-13 19:47
Used this one: f687c2e8-fb22-4f5e-b77f-ca993e08b191

**Comment by MattGal** [comment] 2017-02-13 20:11
@Priya91 that run shows a timeout for System.Net.Sockets, it could not have been the one resulting in the misplaced conditional facts.

**Comment by MattGal** [comment] 2017-02-13 21:15
Further investigation:  THere's a bug here where mission control is showing "not run" for things that ran and passed if other columns contain skipped tests.  I created https://github.com/dotnet/core-eng/issues/451 to track this and will keep investigating.  

That means the only real issue here is the timeout on RedHat 7.2;  If you're certain that release 1.1.0 bits do not hit this hang on a proper RHEL machine, it can be ignored, but we should definitely understand why this is happening if possible. I can help investigate this further if needed.

**Comment by Priya91** [comment] 2017-02-13 21:57
> That means the only real issue here is the timeout on RedHat 7.2; If you're certain that release 1.1.0 bits do not hit this hang on a proper RHEL machine, it can be ignored

I've reproed the bits from the above jobid on a jenkins CI azure image, and didn't see the hang. Is that a valid test? If not, what would be the correct repro?

**Comment by Priya91** [comment] 2017-02-14 21:44
The hang is happening at test MulticastInterface_Set_AnyInterface_Succeeds, this is a dupe of #13323

**Comment by karelz** [comment] 2017-02-14 22:07
If it is hang, should we close it?

**Comment by Priya91** [comment] 2017-02-14 22:17
Yeah, closing this as dupe of the other one.

**Closed by Priya91** 2017-02-14 22:17 UTC
Labels: area-System.Net.Sockets, bug, os-linux

**Comment by karelz** [comment] 2017-02-14 22:35
@Priya91 how can we best prevent similar fireball fire-drill investigation in future 1.1 servicing releases?

**Comment by Priya91** [comment] 2017-02-15 00:16
> how can we best prevent similar fireball fire-drill investigation in future 1.1 servicing releases?

This bug is not in .NET, as running the test with master bits on the same machine produces the hang, whereas the test passes on Jenkins machines. We need to figure out if it's configuration/firewall/unknown element on the machine that's causing this. 

One way to prevent this will be to use the same image that Jenkins uses on Helix. Or disable this test for helix test runs.

cc @MattGal what is the right way to disable tests only for helix?

**Comment by MattGal** [comment] 2017-02-15 01:47
I don't think it's entirely fair to say the bug is not in .NET simply because no one has found the root cause.  Without understanding of that, it's just guesswork.

Either way, the only way we do test filtering today is via XUnit trait, and that is not helix specific.  It would be fairly simple to add a new trait specific to this, but until you've proven there's something specifically wrong with Helix VMs, I personally oppose this; and if you do find such an issue, why not fix it?

**Comment by Priya91** [comment] 2017-02-15 02:06
@MattGal From the investigation, it looks like it's highly likely that it's machine configuration issue. Syncing with redhat folks to help debug, and temporarily disabling the test for redhat and fedora machines.
