### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.SendFileTest / SendFile_APM

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#25979] opened 2017-12-18 23:44 UTC
### WhenAllOrAnyFailed timed out after 30000

Failure [20171213.05](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171213.05/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%20512)):
```
System.TimeoutException : WhenAllOrAnyFailed timed out after 30000
   at System.Threading.Tasks.TaskTimeoutExtensions.<WhenAllOrAnyFailed>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Tests.SendFileTest.<SendFile_APM>d__7.MoveNext() in E:\A\_work\1400\s\corefx\src\System.Net.Sockets\tests\FunctionalTests\SendFile.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

### Neither client nor server task completed within allowed time

Before `SendFile_APM` test change in https://github.com/dotnet/corefx/commit/779171fea3d9f0b25d4058e281ca05b2b6eec323#diff-479492e701f07787f80f44f18ef076f8 on 2017/11/21

Failures [20171022.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171022.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%20512)):
```
Neither client nor server task completed within allowed time
Expected: True
Actual:   False
   at System.Net.Sockets.Tests.SendFileTest.SendFile_APM(IPAddress listenAt, Boolean sendPreAndPostBuffers, Int32 bytesToSend) in /root/corefx-1079212/src/System.Net.Sockets/tests/FunctionalTests/SendFile.cs:line 233
```

## History of failures

Day | Build | OS | Error message
-- | -- | -- | --
7/11 | 20170711.04 | OSX10.13 | Neither client nor server task completed within allowed time
9/4 | 20170904.01 | OSX10.12 | Neither client nor server task completed within allowed time
10/22 | 20171022.02 | RedHat69 | Neither client nor server task completed within allowed time - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171022.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%20512))
11/21 | N/A | N/A | Assert changed into TimeoutException in https://github.com/dotnet/corefx/commit/779171fea3d9f0b25d4058e281ca05b2b6eec323#diff-479492e701f07787f80f44f18ef076f8
12/1 | 20171201.03 | Win7 | WhenAllOrAnyFailed timed out after 30000
12/8 | 20171208.01 | Win8.1 | WhenAllOrAnyFailed timed out after 30000
12/10 | 20171210.03 | Win8.1 | WhenAllOrAnyFailed timed out after 30000
12/12 | 20171212.03 | Win10 | WhenAllOrAnyFailed timed out after 30000
12/13 | 20171213.05 | Win7 | WhenAllOrAnyFailed timed out after 30000 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171213.05/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%20512))
12/28 | 20171228.01 | Win8.1 | WhenAllOrAnyFailed timed out after 30000 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171228.01/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%2012345678))
12/30 | 20171230.02 | Win7 | WhenAllOrAnyFailed timed out after 30000 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171230.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%2012345678))
1/4 | 20180104.02 | Win10 | WhenAllOrAnyFailed timed out after 30000 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180104.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20False,%20bytesToSend:%2012345678))
1/23 | 20180123.04 | Win7 | WhenAllOrAnyFailed timed out after 30000 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180123.04/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendFileTest~2FSendFile_APM(listenAt:%20127.0.0.1,%20sendPreAndPostBuffers:%20True,%20bytesToSend:%201024))
3/13 | 20180313.03 | Win8.1 | WhenAllOrAnyFailed timed out after 30000
3/16 | 20180316.01 | Win7 | WhenAllOrAnyFailed timed out after 30000
3/22 | 20180322.01 | Win8.1 | WhenAllOrAnyFailed timed out after 30000
3/22 | 20180322.06 | Win10 | WhenAllOrAnyFailed timed out after 30000

Timeout similar to #25894, started around same time. Sometimes correlated failures (12/28, 12/13).

**Comment by wfurt** [comment] 2019-09-11 20:39
I found 4 failures in last 90 days. That can be considered as noice caused by CI environment.
Since this issue is super old, I'm going to close it.
If we see this test failing again, we should collect console.log and testResults.xml and we should start fresh issue.

**Closed by wfurt** 2019-09-11 20:39 UTC
Labels: area-System.Net.Sockets, test bug, test-run-core
