### ISSUE TITLE
System.Diagnostics.PerformanceCounterType enum missing values

### ISSUE THREAD

**Issue by davidbraden** [dotnet/corefx#21829] opened 2017-07-03 16:01 UTC
I think System.Diagnostics.PerformanceCounterType is missing some values. I think it should also include
PrecisionSystemTimer = 541525248;
Precision100NsTimer = 542573824;
PrecisionObjectTimer = 543622400;
to match all the values from the Win32 api. This is based off https://github.com/Microsoft/referencesource/blob/4fe4349175f4c5091d972a7e56ea12012f1e7170/System/compmod/microsoft/win32/NativeMethods.cs#L993

If that makes sense I can create a PR.

**Comment by danmosemsft** [comment] 2017-07-03 16:10
@brianrob ?

**Comment by vancem** [comment] 2017-07-05 15:24
The performance counter API is very Win32 specific, so making it more Win32 specific is not a problem, so this change is 'on the table'.  

However adding these values of course does increase complexity.    Can you describe the end-to-end scenario (is this the only thing needed to unblock it).     

@brianrob owns the final decision but if you can articulate a useful end-to-end scenario that just needs the new values added, it seems reasonable to me...

**Comment by davidbraden** [comment] 2017-07-05 15:40
The issue I've seen is when using the object PerformanceCounter obtained from PerformanceCounterCategory.GetCounters() for the `LogicalDisk` category.
The CounterType property on PerformanceCounter isn't a member of the enum for some counters despite what the method signature indicates. This then causes a problem when using the enum to convert the type to a string.

**Comment by danmosemsft** [comment] 2017-08-22 04:28
@brianrob can you please give feedback? is this an addition would you would support? if so please add api-ready-for-review label.

**Comment by vancem** [comment] 2017-08-22 18:11
Again, I won't speak for Brian, but there are a few issues 

1. This code is NOT (at least currently) in corefx it is only in the desktop .NET Framework.   Thus there is a fundamental structural issue (you can't create a PR).     We may ultimately have a compat library for it, but I don't know of any currently.   

2. There is a issue with simply adding the particular values mentioned above.  The issue is that on the native side this enum is a BITFIELD, but when this was made on the managed side it was made a NORMAL enum.     The example above lists a few of the possible combinations, but there are many other possibilities.     However for compatibility's sake we probably don't want to change the enum to a bitfield (especially since this type is not likely to have a future in .NET Core).     

I suspect that the original design was targeting CREATION of perf-counters (so by making it a normal enum we could restrict ourselves to things we wanted to support).    The goal of this change seems to be to enable nice pretty-printing of the PerformanceCounterType for counters created by the OS.    This is not a primary scenario, and arguably would entail more testing.  

If this code was in the open source codebase, I would suggest that @davidbraden leave this enum alone (it is for generation, not pretty-printing), and make either another [Flags] enum and a pretty-printer, but he cannot even do that since this code is not currently open source.    

My recommendation is to simply close the issue as it really is not relevant to this repository.

**Comment by brianrob** [comment] 2017-08-22 22:53
Agreed with @vancem on this.  This code is not available on core or present in corefx - it is specific to the desktop framework.  The easiest workaround will be to convert the value manually based on the values used by the Win32 API.

**Closed** 2018-01-25 00:19 UTC
Labels: api-needs-work, area-System.Diagnostics.Tracing
