### ISSUE TITLE
[System.Text.Json] Serializing multi-dimensional arrays as properties throws

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37317] opened 2019-04-30 23:18 UTC
```C#
class Container
{
    public int[][] Matrix { get; set; }
}

var json = "{\"Matrix\": [[1, 2], [3, 4]]}";
Console.WriteLine(JsonSerializer.Parse<Container>(json));
```

This seems to work though:

```C#
var json = "[[1, 2], [3, 4]]";
Console.WriteLine(JsonSerializer.Parse<int[][]>(json).Length);
```

**Comment by pranavkm** [comment] 2019-05-01 21:43
cc @ahsonkhan \ @steveharter

**Comment by steveharter** [comment] 2019-05-15 16:44
Multiple dimension arrays are not supported and is special cased in the code to throw. Try to use jagged arrays (arrays within arrays). Supporting multi-dimension arrays is not a trivial feature add.

**Comment by steveharter** [comment] 2019-05-15 16:53
As part of this issue, at least temporarily, I think we should change the exception type thrown from `JsonException` to `NotSupportedException`.

**Comment by steveharter** [comment] 2019-05-15 16:56
The code example is using jagged arrays, not multi-dimensional arrays. So perhaps this issue is a duplicate of https://github.com/dotnet/corefx/issues/36889.

A md array is like `int[,]`

**Comment by ahsonkhan** [comment] 2019-05-17 02:14
Duplicate of https://github.com/dotnet/corefx/issues/36889. Closing.

**Closed by ahsonkhan** 2019-05-17 02:14 UTC
Labels: area-System.Text.Json, blocking-partner, bug, up-for-grabs
