### ISSUE TITLE
Beta 8 blocker: IPAddress.ToString and .Parse fails on OS X with DNX

### ISSUE THREAD

**Issue by muratg** [dotnet/corefx#3625] opened 2015-10-02 20:42 UTC
Example program:

```csharp
using System;
using System.Net;

namespace Test
{
    public class Program
    {
        public void Main(string[] args)
        {
            System.Console.WriteLine("Test!");

            IPAddress.Loopback.ToString();

            // Parse also causes the process to crash
            var ipAddress = IPAddress.Parse("1.1.1.1");
            Console.WriteLine("IP address: {0}", ipAddress);
        }
    }
}
```

Stack Trace:

```
System.Net.Sockets.SocketException: Input/output error
   at System.Net.IPAddressParser.IPv4AddressToString(Byte[] numbers)
   at System.Net.IPAddress.ToString()
   at Test.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

There is no exception or stack trace from “IPAddress.Parse("1.1.1.1")”. The process just crashes.

Use the latest DNX (`dnx-coreclr-darwin-x64.1.0.0-beta8-15794`) from `aspnetrelease` feed.  There's a reference issue that we're fixing that you'll need to workaround. Just copy `runtime.unix.Microsoft.Win32.Primitives/4.0.1-beta-23326/lib/dotnet/Microsoft.Win32.Primitives.dll` over to `~/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta8-15794/bin/`

cc @halter73 @Eilon @davidfowl @brennanconroy

**Comment by muratg** [comment] 2015-10-02 20:43
@pgavlin

**Comment by pgavlin** [comment] 2015-10-02 21:43
Okay. I've reproduced this, but I've also verified that it's fixed in newer builds of CoreFX.

**Comment by pgavlin** [comment] 2015-10-02 22:00
We've decided to keep this open to track backporting the fix for beta8.

**Comment by joshfree** [comment] 2015-10-02 23:17
@chcosta and @ellismg are pulling the fix into the VSO release branch now for a beta8 rebuild.

**Comment by ellismg** [comment] 2015-10-04 04:29
Just so everyone knows what we did, we cherry picked f3191981b3739742e4f728b6a13a880abe12c5a6 into our beta8 release branch (which is on VSO not on GitHub) since @pgavlin said this would address the issue.  New builds should be produced as part of our official build Sunday night, which ASP.NET will then pick up.

**Comment by joshfree** [comment] 2015-10-07 23:17
Closing this bug since the fix has been tested in a beta8 release build.

**Closed by joshfree** 2015-10-07 23:17 UTC
Labels: System.Net, X-Plat
