### ISSUE TITLE
Udp Socket.ReceiveFrom a lot of allocations for IPAdress

### ISSUE THREAD

**Issue by kripergvg** [dotnet/corefx#39317] opened 2019-07-09 09:18 UTC
At production server, I have a simple code 
```
mSocket.ReceiveFrom(mBuffer, SocketFlags.None, ref ep);
```

I call this code every millisecond. Recently I found out that almost 40% of allocations from my application are from this code. And all of the allocations are only 3 primitives: SocketAddress, IPEndPoint, IPAdress. It seems wasteful. Maybe I do something wrong? Can I read data from the UDP socket without this allocations? Can I have managed UDP transport with zero allocations?
Simple reproduction https://github.com/kripergvg/UdpAllocations
dotmemory after 4 minutes 
![image](https://user-images.githubusercontent.com/7288803/60876324-5cce2380-a244-11e9-93ad-72a7b22fc9ee.png)

**Comment by scalablecory** [comment] 2019-08-22 18:38
ReceiveFrom variants have a surprisingly large number of allocations right now. This is likely to have a significant impact on QUIC. Seems worth a look at what we can do to improve things.

**Comment by scalablecory** [comment] 2019-08-22 21:08
What do you think of adding some APIs to use `SocketAddress` directly:

```c#
class Socket
{
    public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
    public ValueTask<int> SendToAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);

    public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
    public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
}
```

As well as some changes to conveniently access the result:

```c#
class SocketAddress
{
    public ReadOnlyMemory<byte> IPAddress { get; }
    public int Port { get; }
}
```

**Comment by kripergvg** [comment] 2019-08-27 05:15
> What do you think of adding some APIs to use `SocketAddress` directly:
> 
> ```cs
> class Socket
> {
>     public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
>     public ValueTask<int> SendToAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
> 
>     public int ReceiveFrom(Span<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
>     public ValueTask<int> ReceiveFromAsync(Memory<byte> buffer, SocketFlags socketFlags, SocketAddress remoteAddress);
> }
> ```
> 
> As well as some changes to conveniently access the result:
> 
> ```cs
> class SocketAddress
> {
>     public ReadOnlyMemory<byte> IPAddress { get; }
>     public int Port { get; }
> }
> ```

Looking amazing. It would solve my problem.

**Comment by karelz** [comment] 2019-09-09 17:53
Duplicate of #40933

**Closed by karelz** 2019-09-09 17:53 UTC
Labels: area-System.Net.Sockets
