### ISSUE TITLE
WinRT WebSocket throws unhandled exception on lost connection

### ISSUE THREAD

**Issue by arturl** [dotnet/corefx#17317] opened 2017-03-21 00:05 UTC
The issues affects UWP implementation of `ClientWebSocket`.

When `ReceiveAsync` call is pending and the connection is lost, `System.Net.WebSockets.WinRTWebSocket.OnMessageReceived` throws an exception with HRESULT 0x80072EFE ("The connection with the server was terminated abnormally") here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinRTWebSocket.cs#L282

The exception is thrown on a background thread, which cannot be handled so it brings down the process.

**Comment by davidsh** [comment] 2017-03-21 03:11
Added information from @arturl 

```
I’m not familiar with .NET Core versioning. I’m using Microsoft.NETCore.UniversalWindowsPlatform 5.2.2 package. I think these are the relevant assemblies:
 
                System.Net.WebSockets.Client.dll          D:\g\azure-iot-sdk-csharp\device\samples\UWPSample\bin\x86\Debug\AppX\System.Net.WebSockets.Client.dll     No          N/A                Symbols loaded. c:\symbols\System.Net.WebSockets.Client.pdb\4d9fc6dcf0c5490c8a7109492ef110e71\System.Net.WebSockets.Client.pdb                27           4.06.24705.1       11/4/2016 21:38               0FF60000-0FF70000         [10104] UWPSample.exe              [1] CoreCLR_UWP_Domain 
                System.Net.WebSockets.dll       D:\g\azure-iot-sdk-csharp\device\samples\UWPSample\bin\x86\Debug\AppX\System.Net.WebSockets.dll  No          N/A        Symbols loaded. c:\symbols\System.Net.WebSockets.pdb\fc82556df289488cbf50c6cf0c092e601\System.Net.WebSockets.pdb                28           4.06.24705.1       11/4/2016 21:38               0FF70000-0FF7A000        [10104] UWPSample.exe              [1] CoreCLR_UWP_Domain 
 
The exception happens in WinRTWebSocket.OnMessageReceived (not my code) on a thread that I cannot control. I cannot redirect it to my own callback.
```

**Comment by arturl** [comment] 2017-03-21 17:21
More info - exception and partial call stack here:

```
                                e             {Windows.UI.Xaml.UnhandledExceptionEventArgs}                Windows.UI.Xaml.UnhandledExceptionEventArgs
-                              Exception            {System.Exception: Exception from HRESULT: 0x80072EFE
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)}   System.Exception
+                             Data       {System.Collections.ListDictionaryInternal}          System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
                                HResult -2147012866       int
                                HelpLink               null         string
-                              InnerException null         System.Exception
+                             Static members                
                                Message              "Exception from HRESULT: 0x80072EFE" string
                                Source  "Windows"         string
                                StackTrace          "   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()\r\n   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)"   string
-                              Non-Public members                     
                                _COMPlusExceptionCode             -532462766         int
                                s_EDILock            {object} object
+                             Non-Public members                     
                                Handled               false      bool
                                Message              "System.Exception: Exception from HRESULT: 0x80072EFE\r\n   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()\r\n   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)"   string

```

**Comment by Trolldemorted** [comment] 2017-03-23 23:29
I can confirm this is happening, same stacktrace:

```
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
```
Is there a workaround for this, or will we have to wait for a new release of System.Net.WebSockets.Client?

**Comment by davidsh** [comment] 2017-03-24 00:20
>Is there a workaround for this, or will we have to wait for a new release of System.Net.WebSockets.Client?

I don't think there is a workaround.  The exception is happening in internal code and is leaking which crashes the process.

**Comment by Trolldemorted** [comment] 2017-03-24 00:37
Are dirty hacks like catching every unhandled exception within the app and ignoring it impossible?

And out of curiosity, why is this only happening on UWP?

**Comment by davidsh** [comment] 2017-03-24 00:48
>Are dirty hacks like catching every unhandled exception within the app and ignoring it impossible?

Unlikely to help.  The exception is leaking out of internal code on a threadpool thread.  It will crash the process.  It might be possible for your app to install a special "unhandled exception" handler.  But I'm not really familiar with that.

>And out of curiosity, why is this only happening on UWP?

The UWP version of System.Net.WebSockets.Client is different from non-UWP.  It uses different source code in the implementation (very different).  Currently it uses the WinRT WebSockets APIs as the underlying implementation.  This is very different from the non-UWP binaries in the System.Net.WebSockets.Client package.

**Comment by Trolldemorted** [comment] 2017-03-24 00:54
Damn.

I suppose it will continue to use WinRT WebSockets until .netstandard2.0 is coming? Can you estimate when a fix for this will be available? Unfortunately System.Net.WebSockets.Client is the only option in .netstandard libraries, leading to every uwp app that uses a netstandard library that uses websockets being killed if a server closes a websocket connection.

**Comment by davidsh** [comment] 2017-03-24 00:57
cc: @karelz 

I have no estimate at this time. Any short-term fix would have to done via the release/servicing branches (such as release/1.1.0 etc.) and then a new updated System.Net.WebSockets.Client nuget package generated (tested and marked as stable).

We will hopefully post an update on schedule expectations within the next week or so.

**Comment by moozzyk** [comment] 2017-05-17 02:22
SignalR is hitting this as well: https://github.com/aspnet/SignalR/issues/412

**Comment by karelz** [comment] 2017-05-17 03:03
@moozzyk this is UWP (client) issue, not .NET Core. How is this affecting SignalR? I thought that is server-side scenario. What is the scenario? How common is it?

**Comment by moozzyk** [comment] 2017-05-17 03:41
SignalR consists of the server and the client. The server runs on .NET core but the C# client targets netstandard1.3 so that it can run all over the place (desktop, .NET Core, xamarin, UWP etc.). WebSockets is the default transport so the bug can be hit easily when running SignalR client in a UWP app.

**Comment by caesar1995** [comment] 2017-06-16 17:53
Should we triage this issues as "System.Net"? Since it's related to WebSockets.

@davidsh @CIPop

**Comment by alekkowalczyk** [comment] 2017-06-23 20:03
Any news on that issue? Some expected timeframe for a new version of the websockets package with a fix?

**Comment by davidsh** [comment] 2017-06-23 20:05
Fixing this is part of our UWP6.0 work (i.e. NETStandard20 for UWP).  That will RTM later this year but a preview in a few months.

**Closed** 2017-06-28 18:47 UTC
Labels: area-System.Net, bug, os-windows-uwp

**Comment by Trolldemorted** [comment] 2017-09-12 16:07
@davidsh will the fix be backported to earlier NETStandard versions? If i understand MS' announcements correctly, NETStandard20 will be a part of the Fall Creators Update, which might not be deployed to all W10M devices.

**Comment by davidsh** [comment] 2017-09-12 16:27
>will the fix be backported to earlier NETStandard versions?

The is only part of .NET Core 2.0 release which implies UWP6.0 release.  The fix is not being backported to earlier .NET Core versions.

**Comment by Trolldemorted** [comment] 2017-10-21 09:11
I am sorry to bother you again, but now that the FCU is out, we know that some W10M devices are not receiving it. Will there be one last `System.Net.WebSockets.Client` nuget release that we can depend on, or will this bug never be fixed on these devices?

**Comment by davidsh** [comment] 2017-10-21 14:51
This UWP specific bug was not backported to any other branches other than UWP6.0. So, it will not appear in any System.Net.WebSockets.Client NuPackage for releases other than UWP6.0.  And UWP6.0 actually uses different packaging models, so the binary is in a larger UWP6.0-style package.

**Comment by davidsh** [comment] 2017-10-21 17:52
This is the current set of stable packages on NuGet.org for System.Net.WebSockets.Client:

https://www.nuget.org/packages/System.Net.WebSockets.Client/
![image](https://user-images.githubusercontent.com/7684835/31854423-ba2ddad2-b64d-11e7-85ba-fc681f0895f9.png)

If you feel you need more discussion on this topic, I recommend you open a new issue (closed issues are not really monitored).  Then the right experts from the servicing/packaging teams can comment on whether it is feasible to service that older package for this UWP specific bug (which is fixed in the newer UWP6.0 release.

cc: @karelz
