### ISSUE TITLE
Implement MEF DirectoryCatalog

### ISSUE THREAD

**Issue by marcusien** [dotnet/corefx#8348] opened 2016-05-06 14:40 UTC
Hi,

Really need to got back the feature of MEF to get all dlls from a directory via DirectoryCatalog. 
Is there something done in that way ?

Thank you

**Comment by AlexGhiondea** [comment] 2016-11-23 22:53
@marcusien is there any workaround you can use for this?

**Comment by bradbart** [comment] 2016-11-28 16:30
I found the following code snippet is functionality equivalent to the usage of directory catalogs: 
```cs 
            // Find and load all the DLLs in the folder 
            var assemblies = Directory.GetFiles(directory, "*.dll")
              .Select(path => AssemblyLoadContext.Default.LoadFromAssemblyPath(path))
              .Where(x => x != null);

            // Add the loaded assemblies to the container 
            var configuration = new ContainerConfiguration()
              .WithAssemblies(assemblies)
              .WithAssembly(this.GetType().GetTypeInfo().Assembly);
            return configuration.CreateContainer(); 
```
I think this approach works well, though it would be nice to have an extension method on the ConfigurationContainer that does this. So instead of WithAssemblies, use WithAssembliesFromDirectory() which loads the assemblies and adds them to them to the configuration.

**Comment by AlexGhiondea** [comment] 2016-11-29 18:24
@bradbart thanks for adding the workaround to the issue.

Since we don't currently have any plans to bring back more APIs for MEF and since we have an acceptable workaround I am closing this.

**Closed by AlexGhiondea** 2016-11-29 18:24 UTC
Labels: area-System.Composition, question

**Comment by AceHack** [comment] 2018-04-24 17:31
@bradbart how do you avoid the dependent assembly issue and System.IO.FileNotFoundException error when calling LoadFromAssemblyPath?

**Comment by bradbart** [comment] 2018-06-12 15:56
Hi @AceHack can elaborate on the nature of the issue you are encountering? I didn't notice any IO Exceptions occur when I ran this in my project.

**Comment by AceHack** [comment] 2018-06-12 16:55
@bradbart load things that have dependencies or themselves in the nuget/package cache instead of the bin folder and you should see the issue.

**Comment by bradbart** [comment] 2018-07-18 21:04
I suspect that this issue is caused by the application not having permissions to the directory outside of its bin. Doing a `ReadFile` from that directory should confirm whether that is the issue. Also, might be worth double checking the path if using a relative reference to the directory.  Outside of that, I'm not sure why that exception would occur.
