### ISSUE TITLE
No release notes for System.Net.Http.HttpClient

### ISSUE THREAD

**Issue by jonathanantoine** [dotnet/corefx#32765] opened 2018-10-11 13:48 UTC
I can't find a release notes for HttpClient and the nuget page target a wrong page : https://www.nuget.org/packages/System.Net.Http/

How can I decide if it's a good thing to update my nuget package without information ? 

Thanks !

**Comment by stephentoub** [comment] 2018-10-12 12:39
cc: @terrajobst

**Comment by karelz** [comment] 2018-10-12 18:17
@weshaggard do we have option to provide custom release notes link for a specific package?

The bottom line is that there are no differences in the package since 4.3.1. Version 4.3.1 threw away all custom code for .NET Framework and replaced it with the code shipping inside .NET Framework.
.NET Core has all the implementation in the platform and does not need the package either.
Ideally we recommend to remove the package dependency from your app/library and use the version in the platform. It may not be possible in certain situation when you have .NET Standard libraries in your dependency graph.

**Comment by weshaggard** [comment] 2018-10-12 22:45
>@weshaggard do we have option to provide custom release notes link for a specific package? 

We don't currently have that infrastructure but we could certainly do that if we wanted but we haven't gotten anyone to drive a design. The main tracking issue is https://github.com/dotnet/corefx/issues/26014.

**Comment by karelz** [comment] 2018-10-12 23:44
Duplicate of #26014

**Comment by karelz** [comment] 2018-10-12 23:44
OK, closing it as dupe in that case. If we have more people asking for it (this is the first question in a long long time), we can bump the priority up.

**Closed by karelz** 2018-10-12 23:44 UTC
Labels: area-System.Net.Http, documentation

**Comment by jonathanantoine** [comment] 2018-10-13 06:43
@karelz thank you for the explanation!
