### ISSUE TITLE
Make BufferPool's Shared property Settable

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#4974] opened 2015-12-14 19:27 UTC
To allow for swapping out the Shared instance of the BufferPool, make the Shared property Settable

**Comment by aevitas** [comment] 2015-12-15 14:53
Just out of curiosity, how would one deal with a situation where two consumers use the shared BufferPool, and somewhere along the line of rent/return operations, the shared buffer gets swapped while there are still consumers renting buffers from the original buffer? 

Do they return it to the new instance, and how would that be handled?

**Comment by sokket** [comment] 2015-12-15 18:39
Since the BufferPool deals in pure arrays today, it has to be resilient to people passing back invalid data. If a custom pool derives from the base class and swaps out the Shared instance with it's own instance, it will need to sanity check all incoming data to be sure it is valid and can be returned

**Comment by stephentoub** [comment] 2016-01-04 17:40
This seems dangerous, as components (including those in corefx) will come to rely on the default behavior provided by the built-in pool.  Why do we want this to be settable?  What scenarios are we trying to enable?

**Comment by aevitas** [comment] 2016-01-04 17:47
@stephentoub It would make sense if the current `BufferPool` consistently fails to hand out buffers due to the requested buffers being too large or the entire pool being rented out to swap the BufferPool with an instance that supports either larger buffers, or more of them. 

I agree though that consistent behaviour between the various pools, if swapping is allowed, should be enforced one way or the other, as well as keeping close track of which instance rented out specific buffers.

**Comment by sokket** [comment] 2016-01-04 19:26
This is just something @KrzysztofCwalina and I are thinking about to allow overriding the default functionality of the Shared pool. There are a lot of potential issues here and this is not POR by any means yet; it is more a thought for how we can light up this scenario.

**Comment by sokket** [comment] 2016-01-04 22:51
This will be discussed via API review here: #5182

**Comment by sokket** [comment] 2016-01-05 22:39
Pushing back to RTM since this is not RC2 specific

**Comment by alexperovich** [comment] 2016-10-21 23:01
Closing as this is a duplicate of #5182

**Closed by alexperovich** 2016-10-21 23:01 UTC
Labels: api-needs-work, area-System.Buffers, up for grabs
