### ISSUE TITLE
AsParallel is significantly slower than in the old .NET

### ISSUE THREAD

**Issue by Paradoxon101** [dotnet/corefx#36691] opened 2019-04-08 07:46 UTC
Here is a very simple example that .net core is much slower than the old .net!

```c#
private List DoCalcInParallel(int numberCount)
{
var numbers = Enumerable.Range(3, numberCount - 3);
var parallelQuery = numbers.AsParallel()
.WithExecutionMode(ParallelExecutionMode.ForceParallelism)
.WithMergeOptions(ParallelMergeOptions.NotBuffered)
.Where(n => Enumerable.Range(2, (int)Math.Sqrt(n))
.All(i => n % i != 0))
.OrderBy(i => i);
return parallelQuery.ToList();
}

var stopwatch = Stopwatch.StartNew();
var primeNumbers = this.DoCalcInParallel(20000000);
stopwatch.Stop();
```

On my machine (release build) with .NET the code runs in 6.2 seconds with .NET Core in 7.6 seconds!

**Comment by gfoidl** [comment] 2019-04-08 09:13
Maybe you got trapped by [Tiered Compilation](https://devblogs.microsoft.com/dotnet/tiered-compilation-preview-in-net-core-2-1/). Try to switch it off, and remeasure.

BTW: be aware that methods need to be JITed, so there should be a "warmup" before measurement.
You can use https://benchmarkdotnet.org, which does this stuff for you.

**Comment by Paradoxon101** [comment] 2019-04-08 14:44
Testhardware: Surface Pro 4 i7

Release Build
.NET Framework 4.7.2 -> 15800 ms
.NET Core 3.0 preview3 -> 19400 ms (<TieredCompilation>false</TieredCompilation>)
.NET Core 2.1 -> 21500 ms (<TieredCompilation>false</TieredCompilation>)

[AsParallelTestProject.zip](https://github.com/dotnet/corefx/files/3054853/AsParallelTestProject.zip)

**Comment by Symbai** [comment] 2019-04-08 15:22
On my end they are about nearly the same:

```
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3362.0
  Core   : .NET Core 3.0.0-preview4-27602-07 (CoreCLR , CoreFX 4.700.19.20203), 64bit RyuJIT
```

| Method |  Job | Runtime |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------- |----- |-------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|-----------:|
|    Run |  Clr |     Clr | 5.605 s | 0.0230 s | 0.0215 s |    2 | 436000.0000 | 3000.0000 | 1000.0000 | 2702.83 MB |
|    Run | Core |    Core | 5.401 s | 0.0245 s | 0.0230 s |    1 | 411000.0000 | 3000.0000 | 1000.0000 |  221.75 MB |

```
[ClrJob]
    [CoreJob]
    [MemoryDiagnoser]
    [RPlotExporter, RankColumn]
    public class AsParallelTest
    {
        static int numberCount = 20000000;

        [Benchmark]
        public List<int> Run()
        {
            var numbers = Enumerable.Range(3, numberCount - 3);
            var parallelQuery = numbers.AsParallel()
            .WithExecutionMode(ParallelExecutionMode.ForceParallelism)
            .WithMergeOptions(ParallelMergeOptions.NotBuffered)
            .Where(n => Enumerable.Range(2, (int)Math.Sqrt(n))
            .All(i => n % i != 0))
            .OrderBy(i => i);
            return parallelQuery.ToList();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<AsParallelTest>();
        }
    }
```

**Comment by stephentoub** [comment] 2019-04-08 15:37
Here's what I get with @Symbai's test:
```
| Method |  Job | Runtime |    Mean |    Error |   StdDev |       Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------- |----- |-------- |--------:|---------:|---------:|------------:|----------:|----------:|-----------:|
|    Run |  Clr |     Clr | 8.769 s | 0.0398 s | 0.0372 s | 654000.0000 | 5000.0000 | 2000.0000 | 2702.63 MB |
|    Run | Core |    Core | 7.123 s | 0.0370 s | 0.0346 s | 616000.0000 | 4000.0000 | 2000.0000 |  327.83 MB |
```

**Comment by Paradoxon101** [comment] 2019-04-08 17:58
Could it be that the CLR is faster because it runs in 32 bit?

Here's what I get with @Symbai's test:

.NET Core SDK=3.0.100-preview3-010431
  [Host] : .NET Core 3.0.0-preview3-27503-5 (CoreCLR 4.6.27422.72, CoreFX 4.7.19.12807), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview3-27503-5 (CoreCLR 4.6.27422.72, CoreFX 4.7.19.12807), 64bit RyuJIT

| Method |  Job | Runtime |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 |   Allocated |
|------- |----- |-------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|------------:|
|    Run | Core |    Core | 7.691 s | 0.0192 s | 0.0180 s |    1 | 615000.0000 | 4000.0000 | 2000.0000 | 337830040 B |

---
  
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3362.0
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3362.0

Job=Clr  Runtime=Clr

| Method |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|----------:|
|    Run | 5.993 s | 0.0246 s | 0.0218 s |    1 | 404000.0000 | 4000.0000 | 2000.0000 |   1.67 GB |

**Comment by yahorsi** [comment] 2019-04-09 19:02
> Could it be that the CLR is faster because it runs in 32 bit?

Try run it on 2.2. to make sure it is not caused by tiered jit

**Comment by Symbai** [comment] 2019-04-09 20:09
On 2.2 I get a performance difference:

```
  Job-FDCFFT : .NET Core 2.2.3 (CoreCLR 4.6.27414.05, CoreFX 4.6.27414.05), 64bit RyuJIT
  Clr        : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3362.0
  Core       : .NET Core 3.0.0-preview4-27602-07 (CoreCLR , CoreFX 4.700.19.20203), 64bit RyuJIT
```

| Method |     Job | Runtime |     Toolchain |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------- |-------- |-------- |-------------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|-----------:|
|    Run | Default |    Core | .NET Core 2.2 | 5.973 s | 0.0171 s | 0.0152 s |    3 | 411000.0000 | 3000.0000 | 1000.0000 |  224.66 MB |
|    Run |     Clr |     Clr |       Default | 5.590 s | 0.0231 s | 0.0216 s |    2 | 436000.0000 | 3000.0000 | 1000.0000 | 2702.61 MB |
|    Run |    Core |    Core | .NET Core 3.0 | 5.391 s | 0.0144 s | 0.0120 s |    1 | 411000.0000 | 3000.0000 | 1000.0000 |   222.7 MB |2702.32 MB |
|    Run | Core |    Core | .NET Core 2.2 | 6.525 s | 0.0284 s | 0.0266 s |    2 | 411000.0000 | 3000.0000 | 1000.0000 |   222.5 MB |

Test:
```
[ClrJob]
    [MemoryDiagnoser]
    [RPlotExporter, RankColumn]
    public class AsParallelTest
    {
        static int numberCount = 20000000;

        [Benchmark]
        public List<int> Run()
        {
            var numbers = Enumerable.Range(3, numberCount - 3);
            var parallelQuery = numbers.AsParallel()
            .WithExecutionMode(ParallelExecutionMode.ForceParallelism)
            .WithMergeOptions(ParallelMergeOptions.NotBuffered)
            .Where(n => Enumerable.Range(2, (int)Math.Sqrt(n))
            .All(i => n % i != 0))
            .OrderBy(i => i);
            return parallelQuery.ToList();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<AsParallelTest>(
        DefaultConfig.Instance.With(
        Job.Default.With(CsProjCoreToolchain.NetCoreApp22),
        Job.Core.With(CsProjCoreToolchain.NetCoreApp30)));
        }
    }
```

**Comment by tarekgh** [comment] 2019-04-10 21:42
Here what I got on my machine:

```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.706 (1803/April2018Update/Redstone4)
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview3-010431
  [Host]     : .NET Core 2.2.4 (CoreCLR 4.6.27521.02, CoreFX 4.6.27521.01), 64bit RyuJIT
  Job-NNLLLW : .NET Core 2.2.4 (CoreCLR 4.6.27521.02, CoreFX 4.6.27521.01), 64bit RyuJIT
  Clr        : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3394.0
  Core       : .NET Core 3.0.0-preview3-27503-5 (CoreCLR 4.6.27422.72, CoreFX 4.7.19.12807), 64bit RyuJIT


| Method |     Job | Runtime |     Toolchain |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------- |-------- |-------- |-------------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|-----------:|
|    Run | Default |    Core | .NET Core 2.2 | 9.339 s | 0.0309 s | 0.0274 s |    2 | 615000.0000 | 4000.0000 | 2000.0000 |  314.67 MB |
|    Run |     Clr |     Clr |       Default | 9.397 s | 0.0348 s | 0.0308 s |    2 | 652000.0000 | 5000.0000 | 2000.0000 | 2700.67 MB |
|    Run |    Core |    Core | .NET Core 3.0 | 8.993 s | 0.4148 s | 0.4259 s |    1 | 615000.0000 | 5000.0000 | 2000.0000 |  315.99 MB |

```

Looks 4.7.2 and core 2.2 close to each others but core 3.0 have some improvements.

**Comment by Paradoxon101** [comment] 2019-04-11 07:39
Why are there so many different results here?

Does anyone have a project with which all three projects can be started with a benchmark?
My results ran off successively in separate projects.

.NET Framework 4.7.2
.NET Core 2.2
.NET Core 3.0

**Comment by gfoidl** [comment] 2019-04-11 07:59
> Looks 4.7.2 and core 2.2 close to each others

Not when also looking at the "Allocated" column. There .NET Core has big improvements.

**Comment by AndyAyersMS** [comment] 2019-04-11 08:18
@Paradoxon101 in your last measurement above you seem to be mixing 64 bit and 32 bit results. At least, It kind of looks that way:

> Core : .NET Core 3.0.0-preview3-27503-5 (CoreCLR 4.6.27422.72, CoreFX 4.7.19.12807), 64bit RyuJIT
> Clr : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3362.0

If so, this is not comparing apples to apples. 32 bit code often has an inherent advantage over 64 bit because of the smaller pointer size.

**Comment by tarekgh** [comment] 2019-04-11 15:28
> Not when also looking at the "Allocated" column. There .NET Core has big improvements.

Yes, I was talking about the speed and not the allocation. you are right, net core has a lot of improvement in the allocations.

@Paradoxon101 per your measurement and @AndyAyersMS comment, your numbers were result of comparing 32-bit Clr against net core 64-bit. And from other measurements done by @Symbai and myself, it is clear there is no real perf regressions between Clr and net core 2.2. Even we see some improvements with net core 3.0. do you still believe there is a regression there?

**Comment by Paradoxon101** [comment] 2019-04-11 17:15
@tarekgh I think the problem is really 32 bit. Can you please give me your project with the BenchmarkRunner so I can run it on me?

When I create a new project and run it with "Any CPU", the CLR always runs in 32bit on my Windows 10 x64.

**Comment by filipnavara** [comment] 2019-04-11 17:17
> When I create a new project and run it with "Any CPU", the CLR always runs in 32bit on my Windows 10 x64.

Uncheck "prefer 32-bit" on the project options.

**Comment by tarekgh** [comment] 2019-04-11 18:08
@Paradoxon101 

@filipnavara is right. just make sure your csproj file not having a line like:

```Xml
    <Prefer32Bit>true</Prefer32Bit>
```

other idea is just use the CLI directly. in my case, I did 

```
dotnet new Console
```

then I have edited the csproj like:

```Xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0;net462</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.11.5" />
  </ItemGroup>
</Project>
```

and then I run with 

```
dotnet run -c Release -f netcoreapp2.2
```

**Comment by tarekgh** [comment] 2019-04-11 18:38
@Paradoxon101 per discussion here I am closing this issue. Feel free to respond with any question or issue we can help with. thanks for your report.

**Closed by tarekgh** 2019-04-11 18:38 UTC
Labels: area-System.Linq.Parallel, question, tenet-performance

**Comment by Paradoxon101** [comment] 2019-04-11 18:58
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.437 (1809/October2018Update/Redstone5)
Intel Core i7-6700K CPU 4.00GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview3-010431
  [Host]     : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT
  Job-KRFOPY : .NET Core 2.1.9 (CoreCLR 4.6.27414.06, CoreFX 4.6.27415.01), 64bit RyuJIT
  Clr        : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3362.0
  Core       : .NET Core 3.0.0-preview3-27503-5 (CoreCLR 4.6.27422.72, CoreFX 4.7.19.12807), 64bit RyuJIT


| Method |     Job | Runtime |     Toolchain |    Mean |    Error |   StdDev | Rank |       Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------- |-------- |-------- |-------------- |--------:|---------:|---------:|-----:|------------:|----------:|----------:|-----------:|
|    Run | Default |    Core | .NET Core 2.1 | 9.082 s | 0.0258 s | 0.0215 s |    3 | 616000.0000 | 4000.0000 | 2000.0000 |  321.17 MB |
|    Run |     Clr |     Clr |       Default | 8.304 s | 0.0873 s | 0.0817 s |    2 | 652000.0000 | 5000.0000 | 2000.0000 | 2701.03 MB |
|    Run |    Core |    Core | .NET Core 3.0 | 7.373 s | 0.0120 s | 0.0106 s |    1 | 615000.0000 | 5000.0000 | 2000.0000 |  319.27 MB |

Thank you very much.
The problem was probably in front of the screen :)
