### ISSUE TITLE
JsonSerializer cant Deserialize dynamic objects

### ISSUE THREAD

**Issue by ghost1372** [dotnet/corefx#41472] opened 2019-09-28 18:55 UTC
hi I hope this is a good place to ask this question
It seems we can't deserialize dynamic objects
i used this code but not worked is there any way to do this?
```
var objList = System.Text.Json.JsonSerializer.Deserialize<List<dynamic>>(json);
```

**Comment by steveharter** [comment] 2019-10-01 19:34
Duplicate of issue https://github.com/dotnet/corefx/issues/38007

**Closed by steveharter** 2019-10-01 19:34 UTC
Labels: area-System.Text.Json
