### ISSUE TITLE
Tests under "System.Collections.Tests" failed with "Exit code was 131 but it should have been 42"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#24763] opened 2017-10-20 01:47 UTC
Failed tests:
 System.Collections.Tests.SortedListTests.Item_Get_DifferentCulture
 System.Collections.Tests.CaseInsensitiveComparerTests.DefaultInvariant_Compare
 System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_Compare_TurkishI
 System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Ctor_Empty_ChangeCurrentCulture_GetHashCodeCompare
 System.Collections.Tests.HashtableTests.Ctor_IDictionary_IEqualityComparer
 System.Collections.Tests.HashtableTests.Ctor_IDictionary_Int_IEqualityComparer
 System.Collections.Tests.HashtableTests.Ctor_IEqualityComparer
 System.Collections.Tests.HashtableTests.Ctor_Int_IEqualityComparer
 System.Collections.Tests.HashtableTests.Ctor_Int_Int_IEqualityComparer
 System.Collections.Tests.ComparerTests.DefaultInvariant_Compare

Configuration: outerloop_netcoreapp_osx10.12_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release/221/testReport/System.Collections.Tests/SortedListTests/Item_Get_DifferentCulture/

MESSAGE:
Exit code was 131 but it should have been 42\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 172

**Comment by danmosemsft** [comment] 2017-10-20 05:19
another ` A fatal error occurred, the required library libhostfxr.dylib could not be found at /Users/dotnet-bot/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_osx_release/bin/testhost/netcoreapp-OSX-Release-x64/shared/Microsoft.NETCore.App/9.9.9/` ... @mmitche is working on it

**Comment by mmitche** [comment] 2017-10-20 16:19
@danmosemsft This looks unrelated to the other outerloop netcoreapp issues.  What was the original?  I don't remember seeing it.

**Comment by danmosemsft** [comment] 2017-10-20 20:08
Ah - you're right. You were looking at "Please install clang". OK, this will need investigation...

**Comment by Sunny-pu** [comment] 2017-12-29 02:39
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/3874/testReport/

**Comment by ianhays** [comment] 2018-02-26 23:02
This might have been caused by the default culture on the machine being set to something unexpected. I pushed some fixes to the Collections-culture relationship last that might have been related to these failures.

Either way, I'm closing this as no-repro locally and since it hasn't failed CI in a few months.

**Closed by ianhays** 2018-02-26 23:02 UTC
Labels: area-System.Collections, test-run-core
