### ISSUE TITLE
Should HttpWebRequest utilize HttpClientFactory

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/corefx#32134] opened 2018-09-06 15:25 UTC
https://github.com/dotnet/corefx/blob/master/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1096-L1106 instantiates a new `HttpClient` for each request which is less then ideal.

**Comment by davidsh** [comment] 2018-09-06 16:32
This is a duplicate of an existing issue. I just can't find the issue number at the moment.

**Comment by karelz** [comment] 2018-09-06 17:44
Duplicate of #15460

**Closed by karelz** 2018-09-06 17:44 UTC
Labels: area-System.Net
