### ISSUE TITLE
HttpWebRequest internally throws 2 exceptions

### ISSUE THREAD

**Issue by joshlang** [dotnet/corefx#12282] opened 2016-10-01 23:13 UTC
Create a .NET Core 1.0.1 console project with this line of code: 
**HttpWebRequest.CreateHttp("https://www.google.ca/").GetResponseAsync().Wait();**

Execute it and examine the output window:
Exception thrown: 'System.PlatformNotSupportedException' in System.Net.Requests.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.ni.dll

**This occurs on every call, which cannot be good for performance.**

The PlatformNotSupportedException can be avoided by setting the HttpWebRequest object .Proxy = null, or setting HttpWebRequest.DefaultWebProxy = null;

I have not yet found a way to avoid the ArgumentNullException (some SafeHandle cannot be null)

Stack trace top 2 items show:
    System.Private.CoreLib.ni.dll!System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle pHandle, ref bool success)
    System.Net.Http.dll!System.Net.Http.WinHttpHandler.StartRequest(object obj)

**Comment by davidsh** [comment] 2016-10-02 00:02
I'm fairly certain this issue is fixed in the .NET Core 1.1 branch as well as current [master].

cc: @stephentoub

**Comment by davidsh** [comment] 2016-10-02 00:03
This is a dupe of #9578

**Comment by joshlang** [comment] 2016-10-02 00:20
Yes, I saw #9578. The Proxy PlatformNotNullException wasn't mentioned in it, and I wasn't 100% sure it was the same ArgumentNullException, so I decided to report it.

**Comment by davidsh** [comment] 2016-10-03 22:40
Can you please confirm the platform you are using?  Windows?  Linux?  Etc.  Please include your current project.json file.  Thx.

**Comment by joshlang** [comment] 2016-10-03 22:57
Windows (win10 x64 pro)
Visual Studio 2015
.NET Core Console app

project.json:
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

Program.cs:
namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            System.Net.HttpWebRequest.CreateHttp("https://www.google.ca/").GetResponseAsync().Wait();
        }
    }
}

**Comment by davidsh** [comment] 2016-11-18 20:49
Closing this as we believe this is fixed in the .NET Core 1.1 RTM release.

Please re-open if you still see this problem.  Thx.

**Closed by davidsh** 2016-11-18 20:49 UTC
Labels: area-System.Net

**Comment by Trolldemorted** [comment] 2017-02-07 15:27
@davidsh i have a similar issue:

This code compiles fine in an UWP project:

```
using System;
using System.Net.Http;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

[...]

HttpClientHandler handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback = new Func<HttpRequestMessage, X509Certificate2, X509Chain, SslPolicyErrors, bool>((HttpRequestMessage a, X509Certificate2 b, X509Chain c, SslPolicyErrors d) => { return true; });
HttpClient connection = new HttpClient(handler);
```

But when executing a PlatformNotSupportedException is thrown:

```
System.PlatformNotSupportedException: The value 'System.Func`5[System.Net.Http.HttpRequestMessage,System.Security.Cryptography.X509Certificates.X509Certificate2,System.Security.Cryptography.X509Certificates.X509Chain,System.Net.Security.SslPolicyErrors,System.Boolean]' is not supported for property 'ServerCertificateCustomValidationCallback'.
   at System.Net.Http.HttpClientHandler.set_ServerCertificateCustomValidationCallback(Func`5 value)
   at Test_Project.MainPage.Button_Click_1(Object sender, RoutedEventArgs e)
```

Is this the right issue and repository for this issue, or should i open a new one?
Are there any workarounds that allow UWP to handle server certificate validation?

Setup information:
- VS 2017 RC, everything up-to-date
- UWP project, target Build 10586
- project.json:
```
{
  "dependencies": {
    "libsignal-service-dotnet": "1.4.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.3.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by davidsh** [comment] 2017-02-07 15:48
This is a known issue.  The functionality is not implemented for UWP apps which is why it throws PlatformNotSupportedException.

The functionality will be working sometime later this year.

**Comment by davidsh** [comment] 2017-02-07 15:49
There is no waorkaround except to use WinRT Windows.Web.Http APIs in your UWP app.  Those WinRT APIs work in C# and support server certificate validation callback

**Comment by Trolldemorted** [comment] 2017-02-07 16:00
Unfortunately, the HTTPS requests are being sent from a .NETStandard1.4 library. Is there a way i can keep this functionality in the library and still use it in UWP and non-UWP projects?

**Comment by davidsh** [comment] 2017-02-07 16:21
Sorry, but the UWP binary in the System.Net.Http package does not currently support this functionality.  You will have to wait until a new version of the package ships (probably in the .NET Core 2.0 timeframe).

**Comment by Trolldemorted** [comment] 2017-02-07 16:35
Thanks for your quick and kind help. I suppose i will have to fall back to a PCL library until .NET Core 2.0 hits.

Is there an official list which functionalities UWP is not yet supporting? And is it intended that there are no compile-time warnings about this, or will these differences disappear forever as soon as 2.0 is there?

**Comment by davidsh** [comment] 2017-02-07 16:37
>Is there an official list which functionalities UWP is not yet supporting? 
Sorry, there is no list but PlatformNotSupportedException is what you will get when it is not yet implemented.

>will these differences disappear forever as soon as 2.0 is there?

The plan is to implement this in the .NET Core 2.0 timeframe.

**Comment by Trolldemorted** [comment] 2017-02-27 11:33
@davidsh the .NET Core 2.0 release has been postponed to [Q3 2017](https://github.com/dotnet/core/blob/master/roadmap.md), does this also apply for a fix in System.Net.Http? Is there another way of saying "just ignore that the certificate is not signed by a trusted ca" until we can pin a certificate properly?

**Comment by davidsh** [comment] 2017-02-27 17:55
>@davidsh the .NET Core 2.0 release has been postponed to Q3 2017, does this also apply for a fix in System.Net.Http? Is there another way of saying "just ignore that the certificate is not signed by a trusted ca" until we can pin a certificate properly?

If this question is about the UWP version of the System.Net.Http binary, then those newer properties in HttpClientHandler (such as `ServerCertificateCustomValidationCallback ` will continue to throw `PlatformNotSupportedException`.   Getting all properties working for UWP is now part of the .NET Core 2.1 milestone.

cc: @karelz

**Comment by Trolldemorted** [comment] 2017-02-28 21:34
2.*1*? Can we somehow get some kind of workaround earlier? Since i guess we cannot expect .NET Core 2.1 before 2018, it would be ridiculous to wait one year just to be able to communicate with a HTTP server that uses a self-signed certificate.

I understand that .netcore/standard is a really huge project and that it is very complicated to keep libraries of that size consistent, but i am sure you can relate to a programmer's perspective, in which waiting one year just to be able to talk to your HTTPS server is not an option.

Sorry for being so rigid about this point, but the prospect of waiting 12+ months just to be able to tell System.Net.HTTP to shut up about self-signed certs is *really* upsetting.

**Comment by davidsh** [comment] 2017-02-28 21:53
>2.1? Can we somehow get some kind of workaround earlier?

If you are developing a C# UWP (Windows Store App), then a workaround would be to use the WinRT Windows.Web.Http APIs.  They are similar to System.Net.Http and support allowing self-signed certificates.

See:

 https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter#Windows_Web_Http_Filters_HttpBaseProtocolFilter_IgnorableServerCertificateErrors

https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter#Windows_Web_Http_Filters_HttpBaseProtocolFilter_ServerCustomValidationRequested

**Comment by Trolldemorted** [comment] 2017-03-01 06:33
As i said, the requests are sent from a .NETStandard library, is there a package that would grant us access to the WinRT HttpClients?

**Comment by davidsh** [comment] 2017-03-04 04:21
>As i said, the requests are sent from a .NETStandard library, is there a package that would grant us access to the WinRT HttpClients?

If you are the author of a library that depends on NETStandard, then it is possible you can have different binary implementations in the NuGet package of your library.  If you want to have UWP implementations that use WinRT APIs, you can do that.  In general, any NuGet package can have multiple binaries in it.  You would need to target 'netcore50' for the moniker which is what NuGet uses when it takes a package (library) and extracts out the assembly needed for a UWP.

**Comment by sandersaares** [comment] 2018-02-15 07:05
`Exception thrown: 'System.PlatformNotSupportedException' in System.Net.Requests.dll` remains on .NET Core 2.0. The workaround to set DefaultWebProxy works - it no longer gets thrown.

**Comment by ByronAP** [comment] 2018-03-27 16:26
this should be re-opened as it is still an issue

**Comment by karelz** [comment] 2018-03-27 19:13
Given the back and forth above, I think we should open a new issue with link to this one and with minimal repro demonstrating the behavior.
Can you please check it repros also on 2.1? Thanks!
