### ISSUE TITLE
Inconsistencies between netfx and netcoreapp in string random hashing

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#26010] opened 2017-12-21 04:48 UTC
While trying to add tests to check if the randomized string hashing is working fine ([issue 24466](https://github.com/dotnet/corefx/issues/24466)), I noticed that netfx is not using random function for GetHashCode. 

The randomized string hashing function is working properly in netcoreapp but not in netfx.
```"abc".GetHashCode()``` should be randomized and be returning a different hashcode in different processes. But apparently instead it is returning the same hash code all the time.

Please refer to the tests added in this pr #24779.

**Comment by jkotas** [comment] 2017-12-21 07:59
> I noticed that netfx is not using random function for GetHashCode.

This is not a bug. It is the expected behavior. Randomized hashing was not in .NET Framework originally. When we have introduced it, it was not turned on by default because of the bug-for-bug .NET Framework compatibility bar.

.NET Framework programs that wish to have randomized hashing have to opt into it using config file: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/userandomizedstringhashalgorithm-element . If you want these tests to pass on .NET Framework, you need to add a config file like this for them.

**Comment by karelz** [comment] 2017-12-22 16:37
I don't think it is worth to add .NET Framework-specific tests into CoreFX. We can stick with just what we have IMO and skip the test on .NET Framework.

**Comment by maryamariyan** [comment] 2017-12-22 21:22
So far, I have noticed the following problems while adding random hashing tests:

1. Dictionary exposes internal type comparer

2. Behavior inconsistencies between netfx and netcoreapp:
a. For Dictionary, netfx uses a randomized comparer by default but netcoreapp uses non-randomized and switches to randomized after reaching collision threshold
b. StringComparer.OrdinalIgnoreCase does not produce randomized hash codes in netcoreapp

**Comment by maryamariyan** [comment] 2017-12-22 21:39
@jkotas, in netcoreapp, StringComparer.OrdinalIgnoreCase is not producing randomized hash codes.

The other StringComparers (Ordinal, CurrentCulture, CurrentCultureIgnoreCase, InvariantCulture, InvariantCultureIgnoreCase) are producing randomized hash codes.

in netfx, all 6 above string comparers are producing non random hash codes.

I added a test reflecting this in #24779

**Comment by jkotas** [comment] 2017-12-22 21:42
> In netcoreapp, StringComparer.OrdinalIgnoreCase is not producing randomized hash codes.

This is .NET Core 1.0 -> .NET Core 2.0 regression. It was producing randomized hash codes in .NET Core 1.0.

**Comment by ViktorHofer** [comment] 2018-03-21 23:30
Closing as by design. PR for tests can be found here: https://github.com/dotnet/corefx/pull/28218

**Closed by ViktorHofer** 2018-03-21 23:30 UTC
Labels: area-System.Runtime, bug
