### ISSUE TITLE
System.IO.FileLoadException in System.Net.Http 4.1.1 (NuGet package 4.3.0) on System.Diagnostics.DiagnosticSource 4.0.1 (NuGet package 4.3.0) 

### ISSUE THREAD

**Issue by baal2000** [dotnet/corefx#15031] opened 2017-01-10 14:40 UTC
System.IO.FileLoadException at System.Net.Http.WinHttpHandler.SendAsync(): 
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Our research has shown that:
* System.Net.Http v 4.3.0 package depends on System.Diagnostics.DiagnosticSource v 4.3.0.
* NuGet package of System.Net.Http v 4.3.0 in fact contains System.Net.Http.dll v 4.1.1 (as of Jan 8 2017). Why? There is NuGet package System.Net.Http v 4.1.1 for that
* System.Net.Http ver 4.1.1.0 references System.Diagnostics.DiagnosticSource v. 4.0.0
* NuGet package of System.Diagnostics.DiagnosticSource v 4.3.0 in fact contains System.Diagnostics.DiagnosticSource v 4.0.1 (as of Jan 8 2017).
* Strongly named assembly System.Diagnostics.DiagnosticSource version mismatch ( v 4.0.1 v.s. v 4.0.0) causes System.IO.FileLoadException in System.Net.Http 4.1.1.
* The binding redirect to System.Diagnostics.DiagnosticSource v 4.0.0 to v 4.0.1 is not automatically generated under our scenario. Even if it was, would that address every build scenario, for example a shared library project later referenced from a 3-rd party project? 

This ticket can also be answered at http://stackoverflow.com/questions/41550563

Thanks!

**Comment by karelz** [comment] 2017-01-10 16:43
cc @ericstj who had some insights.

We believe it will be fixed as a side-effect of fix for #11100.
I would still like to understand the root cause here (it's not clear to me from the bug description).

**Comment by baal2000** [comment] 2017-01-10 17:00
cc @karelz: More details at http://stackoverflow.com/questions/41550563.

Maybe this sequence is clearer:
1. System.Net.Http.dll 4.1.1 has been built while referencing  System.Diagnostics.DiagnosticSource.dll v 4.0.0
2. Nevertheless, System.Diagnostics.DiagnosticSource.dll v 4.0.1 is auto-deployed with System.Net.Http v 4.3.0 package. This package carries System.Net.Http.dll 4.1.1 with itself, as explained in the issue description.
3. Invoking certain System.Net.Http classes methods causes FileLoadException because the runtime can not find exact match (strong name, version) to System.Diagnostics.DiagnosticSource.dll referenced  from System.Net.Http.

The error can be prevented by manually adding the binding redirect section to app.config 
or 
manually  adding System.Diagnostics.DiagnosticSource v 4.0.0 package to the project dependencies when NuGet package of System.Net.Http v 4.3.0 is installed.

**Comment by davidsh** [comment] 2017-01-10 17:21
@karelz @ericstj Any fix for #11100 will not affect this problem unless DiagnosticSource is removed completely from the set of assemblies used for the net46 build of System.Net.Http.dll.  Can you explain why you think the problem would be fixed as a side-affect of fixing #11100?

**Comment by karelz** [comment] 2017-01-10 17:39
I was just quoting @ericstj. These things are mind-blowing (feels like the good old Fusion days with inconsistent versions of participating assemblies on top of that :() - I need to grab @ericstj and understand the problem better.

**Comment by davidsh** [comment] 2017-01-10 20:26
After reviewing the binaries that dependencies of System.Net.Http.dll, I see that once the fix for #11100 is checked in (with PR #15036), the set of depedent assemblies for the NET46 build of System.Net.Http.dll in reduced.  See below:

Current System.Net.Http.dll NET46 build in [master] branch.

```
// Metadata version: v4.0.30319
.module extern crypt32.dll
.module extern kernel32.dll
.module extern winhttp.dll
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Diagnostics.DiagnosticSource
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 4:0:2:0
}
.assembly extern System.Core
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Buffers
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 4:0:2:0
}
```

Pending revised System.Net.Http.dll NET46 build (once PR #15036 is checked in):
```
// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Core
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
```

So, since the hard dependency against System.Diagnostics.DiagnosticSource is removed, the exception "System.IO.FileLoadException" should go away.

**Comment by baal2000** [comment] 2017-01-10 22:01
Agree removing System.Diagnostics.DiagnosticSource dependency should do. 
Thank you all.

**Comment by baal2000** [comment] 2017-01-10 23:08
@davidsh What about WinHttpHandler package dependencies that new version of System.Net.Http.dll requires to support HTTP/2 protocol per [PR 15036](https://github.com/dotnet/corefx/pull/15036)?

**Comment by davidsh** [comment] 2017-01-10 23:16
System.Net.Http.dll doesn't have a dpendency to System.Net.Http.WinHttpHandler.dll.  But it does include the source of WinHttpHandler as the default HttpClientHandler implementation.  That, however, is changing with the PR #15036.

The PR #15036 will end up implicitly removing a dependency where System.Net.Http.dll requires DiagnosticSource.dll because that requirement bubbles up from using WinHttpHandler.

That said, any explicit use of WinHttpHandler (i.e. via the System.Net.Http.WinHttpHandler package) will bring in DiagnosticSource.  And perhaps, there will be a problem surfacing regarding version conflict dependencies with DiagosticSource.dll.

I would suggest we wait until PR #15036 is done. And then you can try a new repro case where you have explicit code referencing WinHttpHandler.  In that case, we might want to close this issue as resolved since it talks about System.Net.Http.dll needing DiagnosticSource.dll.  But perhaps then open up a new issue regarding WinHttpHandler.dll dependencies with DiagnosticSource.

**Comment by baal2000** [comment] 2017-01-11 01:26
Sure may close System.Net.Http case then

**Comment by davidsh** [comment] 2017-01-18 20:23
Now that PR #15036 is checked in, this problem should go away w.r.t. net46.  System.Net.Http.dll no longer use WinHttpHandler internally and thus no longer trys to load System.Diagnostics.DiagnosticSource.dll at runtime.

Please try out the latest packages on the MyGet dev feed.  You'll want to use the latest built System.Net.Http.dll packages which as of today is:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Net.Http

version 4.4.0-beta-24913-02.

You can use dev feed packages via changing your NuGet package source fees either with command line tools or Visual Studio.

Instructions:

Command-Line:
Add the following in nuget.config, under <packagesources> element:

```xml

<add key="myget.org dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```
Visual Studio:
In VS, Tools->Options->Nuget Package Manager->Package Sources -> Add, under Source,  use this url, https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

In either case, make sure you list the MyGet dev feed as the first feed in the list.

**Comment by davidsh** [comment] 2017-01-18 20:24
I'll close this issue for now.  If the problem isn't solved w.r.t. System.Net.Http.dll, please re-open this issue.

If there is a different problem, then please open up a new issue.  Thanks!

**Closed by davidsh** 2017-01-18 20:24 UTC
Labels: area-System.Net.Http, bug

**Comment by Muhammadbilawal** [comment] 2017-02-01 06:48
I have a problem error " 'System.IO.FileLoadException' " how can i get rid of this error .... i am new to programing

**Comment by karelz** [comment] 2017-02-01 08:07
I would recommend to use StackOverflow.com or similar communities for general programming questions. Doing search on bing/google usually leads to helpful things as well.

**Comment by GZidar** [comment] 2017-03-07 22:15
Hi all, I have just installed VS2017 on a brand new computer (nothing but windows 10 - insider build 15048) and tried dotnet ef migrations list and the command crashes with the below message. 

```
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
The project is a netcoreapp1.1 csproj with all packages referencing version 1.1.1 (except tools as there is no 1.1.1 version) as shown below.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>WebAPI.Database</AssemblyName>
    <PackageId>WebAPI.Database</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    </ItemGroup>

    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebAPI.Shared\WebAPI.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
```

**Comment by karelz** [comment] 2017-03-08 01:11
@GZidar I would recommend to not post into closed issues - they may not be monitored.

I am not sure which command crashes for you ... can you specify if it is some migration tool or your app? (note that migration tools are not part of CoreFX - so if that's the case, we will be able to direct you to the right repo)

**Comment by GZidar** [comment] 2017-03-08 02:58
@karelz Sorry for posting here but I did so under direction (in a previous closed issue EF#7742 - linked above). The command that fails is "**dotnet ef migrations list**" this is not a problem with my app code as far as I can tell and it has been an issue that has been reproduced by others. Unfortunately the fix which should have been shipped with dotnet core 1.1.1 does not seem to work (for me at least).

I am at something of a loss. 

There is a workaround that involves changing the target framework of my project to netcoreapp1.0 then running the command and then changing it back afterwards.

**Comment by haraldnagel** [comment] 2017-03-08 23:12
I am seeing this as well. They mentioned in aspnet/EntityFramework#7557 using the `netcoreapp1.0` workaround and routed us over here.

**Comment by karelz** [comment] 2017-03-09 00:08
I admit I don't know what the "dotnet ef ..." command does. I guess it is the CLI exe, dotnet.exe. @piotrpMSFT @eerhardt can you please help route it?

**Comment by haraldnagel** [comment] 2017-03-09 00:27
My guess is that it might have something to do with the Microsoft.EntityFrameworkCore.Tools.DotNet v1.0.0 CLI tooling package but I'm not sure. It might actually belong over in EF.

**Comment by karelz** [comment] 2017-03-09 00:30
If it is in tooling, I assume it is part of CLI repo - we just need to identify which exe it is and that will give us the repo with its source code, which points at where to file a bug (I assume) ...

**Comment by haraldnagel** [comment] 2017-03-09 00:37
Maybe aspnet/EntityFramework.Tools

**Comment by karelz** [comment] 2017-03-09 00:39
I honestly have no idea ... @natemcmaster can you help route it?

**Comment by natemcmaster** [comment] 2017-03-09 03:46
"dotnet ef" lives in https://github.com/aspnet/EntityFramework.Tools. Use https://github.com/aspnet/EntityFramework for issues

**Comment by karelz** [comment] 2017-03-09 06:16
Thanks @natemcmaster! @haraldnagel can you please post your bug there?
Sorry for the ping-pong between repos. I would normally move the bug into another repo via GitHubMover, but we hijacked different (although similar) closed issue with the discussion report, so it is not appropriate in this case ...

**Comment by haraldnagel** [comment] 2017-03-09 16:48
I'll do a little more review to make sure I can't get this to work and then I'll post over there. Thanks @karelz et al. for your help!

**Comment by karelz** [comment] 2017-03-09 16:53
@haraldnagel I would suggest to not wait and file it there right away. It looks pretty bad from scenario perspective, so either it is known issue, or it should get attention ASAP IMO.

**Comment by haraldnagel** [comment] 2017-03-09 18:48
This was user error on my part. I was not specifying the startup project with `-s` as the `dotnet ef` instructions clearly say to. The bit in the stack trace about `Microsoft.Extensions.DependencyInjection` tipped me off. Thanks again @karelz for following up on my questions in an already-closed issue, it's greatly appreciated!

**Comment by karelz** [comment] 2017-03-09 20:03
@haraldnagel I think it is still worth filing there - I don't like experience of exceptions when you do wrong command line. It should be proper error, explaining and leading people to what to do IMO. Of course, if possible.

**Comment by GZidar** [comment] 2017-03-14 08:35
@haraldnagel You are quite correct that specifying the startup project does make the commands work (well spotted), but it is interesting that changing to netcoreapp1.0 also makes it work. Thank you and @karelz for following up despite this being a PEBKAC issue.

**Comment by mejiamanuel57** [comment] 2017-04-30 21:30
I just installed System.Diagnostics.DiagnosticSource and System.Collections.Immutable from the NuGet Package Manager, and everything is working :)
