### ISSUE TITLE
Long running test hang: System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext 

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#37824] opened 2019-05-20 20:37 UTC
`System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext` hangs randomly on `OSX.1013.Amd64.Open-x64:Release`:

```
  Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Mail.Functional.Tests (found 135 of 136 test cases)
  Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 4)
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:02:00
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:04:01
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:06:02
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:08:03
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:10:04
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:12:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:14:07
```

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190518.8/workItem/System.Net.Mail.Functional.Tests/wilogs

@stephentoub maybe `SmtpClient.SendMailAsync` happens before the `TcpListener.AcceptTcpClient` (SmtpServer) blocking call?

**Comment by ViktorHofer** [comment] 2019-05-20 20:38
Closing as dupe of https://github.com/dotnet/corefx/issues/37775

**Comment by ViktorHofer** [comment] 2019-05-20 20:39
Oh sorry, were you trying something out here?

**Closed by ViktorHofer** 2019-05-20 20:38 UTC
Labels: area-System.Net

**Comment by Anipik** [comment] 2019-05-20 20:41
no worries. i was just testing the bot with the changes. Its no longer removing the milestone. :)
