### ISSUE TITLE
System.Text.Json.JsonSerializer doesn't correctly serialize generic super class when nested

### ISSUE THREAD

**Issue by Joelius300** [dotnet/corefx#39903] opened 2019-07-30 22:18 UTC
I'm currently trying to migrate from `Newtonsoft.Json` to `System.Text.Json`. The main reason for that is simply because [`IJSRuntime` has been migrated to `System.Text.Json`](https://github.com/aspnet/Announcements/issues/364) but this doesn't really matter for this bug.  

While testing how things get serialized currently (with `System.Text.Json`) and comparing that to `Newtonsoft.Json`s output I have found what I believe to be a (rather critical) bug.  

## Bug

I have an `InnerContainer` and an `OuterContainer`. The `InnerContainer` has to be generic but I also have to be able to generalize it. This is done via an empty class which is not generic. The classes are defined as follows:

```
// non-generic for generalization
public abstract class InnerContainer { }

// generic for actual use
public class InnerContainer<TValue> : InnerContainer
{
    public TValue Value { get; set; }
}

public class OuterContainer
{
    // use of non-generic class, actual type can of course be generic (derived class)
    public InnerContainer Container { get; set; }
}
```

Now the bug happens when serializing an instance of `OuterContainer`.  
The following is the serialization code:  
```
// note this is declared as the non-generic type, just like in OuterContainer
InnerContainer inner = new InnerContainer<string>   // actual type is generic
{
    Value = "StringValue"
};

OuterContainer outer = new OuterContainer
{
    Container = inner
};

// serialize inner
string innerJsonSystemTextJson = JsonSerializer.Serialize(inner);
string innerJsonNewtonsoft = Newtonsoft.Json.JsonConvert.SerializeObject(inner);

// serialize outer
string outerJsonSystemTextJson = JsonSerializer.Serialize(outer);
string outerJsonNewtonsoft = Newtonsoft.Json.JsonConvert.SerializeObject(outer);
```

Below are the results of the above code:  

#### Newtonsoft.Json (innerJsonNewtonsoft)
`{"Value":"StringValue"}`

#### System.Text.Json (innerJsonSystemTextJson)
`{"Value":"StringValue"}`

#### Newtonsoft.Json (outerJsonNewtonsoft)
`{"Container":{"Value":"StringValue"}}`

#### System.Text.Json (outerJsonSystemTextJson)
`{"Container":{}}`

As you can see if we directly serialize the inner container it works without any issues and produces the same results with both serializers.  
On the other hand if we serialize the outer one (which contains the inner container) only `Newtonsoft.Json` produces the correct result.  

Why does `System.Text.Json` write an empty object instead of the expected value?

## Further examination/information

If I add a property to the non-generic `InnerContainer` like so..
```
public abstract class InnerContainer
{
    public int MyInt { get; set; } = 3;
}
```

.. the output changes like you would expect.

#### Newtonsoft.Json (innerJsonNewtonsoft)
`{"Value":"StringValue","MyInt":3}`

#### System.Text.Json (innerJsonSystemTextJson)
`{"Value":"StringValue","MyInt":3}`

#### Newtonsoft.Json (outerJsonNewtonsoft)
`{"Container":{"Value":"StringValue","MyInt":3}}`

#### System.Text.Json (outerJsonSystemTextJson)
`{"Container":{"MyInt":3}}`

`MyInt` does get serialized but `Value` still doesn't - if nested in `OuterContainer`.  

I believe there must be some bug in the library which chooses the wrong type (declaring type instead of actual type maybe?) for serialization. I'm no expert of course this is just what I suspect :)  

Is this a bug which can be expected to be fixed in upcoming previews?  

Version Information:
- **IDE:** Newest preview of VS 2019 (unrelated I think)
- **SDK:** .Net Core 3.0.100-preview7-012821

**Comment by ahsonkhan** [comment] 2019-07-31 21:26
cc @layomia, @steveharter

**Comment by cadesalaberry** [comment] 2019-08-01 17:08
I am having the same issue, here is the full example:

```cs
public class WebSocketPayload
{
}

public class WSReadFolderPayload : WebSocketPayload
{
    public string files { get; set; }
}

public class WebSocketMessage
{
    public string type { get; set; }
    public string[] files { get; set; }
    public WebSocketPayload payload { get; set; }
}
```

Code:
```cs
var message = new WebSocketMessage
{
    type = "READ_FOLDER_SUCCESS",
    payload = new WebSocketPayload
    {
        files = files,
    },
    files = files,
};

var options = new JsonSerializerOptions
{
    MaxDepth = 1000,
    IgnoreNullValues = true,
};
var serialized = JsonSerializer.Serialize(message, options);

Log(serialized);

```


Leads to:
```js
{"type":"READ_FOLDER_SUCCESS","files":["C:\\Users\\cades\\Downloads\\desktop.ini"],"payload":{}}
```

Where I would expect `files` to also be present in the payload object.

**Comment by steveharter** [comment] 2019-08-06 20:56
I believe these are all polymorphic scenarios which are [not supported yet](https://github.com/dotnet/corefx/issues/38650). Currently, by design, only static serialization is supported unless:
- The type is specified when serializing via the `type` argument when calling Serialize(...). Only that single type is serialized polymorphically (not child objects \ collections).
- The type is declared as `System.Object`. In this case at run-time, object.GetType() is called and that type is serialized.

**Comment by Joelius300** [comment] 2019-08-07 04:50
From looking at the issue you linked I can see that this has been added to future and removed from 3.0. I've also seen the reasons for that and understand them.  

Still I have to ask, isn't this a very critical feature? I think a big portion of people who will use this feature (willingly or forced by e.g. `IJSRuntime`) will need this.  

Is there a workaround?

**Comment by steveharter** [comment] 2019-08-07 17:38
@Joelius I can provide a work-around \ example for serialization but a larger feature is that System.Text.Json does not yet support polymorphic deserialization directly.

Do you need polymorphic serialization and deserialization? Both are achivable by using a custom converter, but just serialization is an easier example to provide.

**Comment by Joelius300** [comment] 2019-08-07 18:03
I know that deserialization is much more expensive and complicated. That's why I'm happy to report I only need serialization.  

I also thought about using a custom converter but I've not tried anything since there isn't yet support for [custom base-class serializer](https://github.com/dotnet/corefx/issues/39905) and I think that might be a bit of an issue. I have found a workaround for that base-class issue so I could probably combine that with your converter right?

**Comment by steveharter** [comment] 2019-08-08 19:33
Here's a [test\sample](https://github.com/dotnet/corefx/blob/fbb8b5c4b9566ba81596aa35f42b71bbda601528/src/System.Text.Json/tests/Serialization/CustomConverterTests.Polymorphic.cs#L159-L218) for polymorphic serialization. Currently the test\sample assumes the base class is abstract.

Closing issue since it is covered by https://github.com/dotnet/corefx/issues/38650

**Closed by steveharter** 2019-08-08 19:33 UTC
Labels: area-System.Text.Json, enhancement

**Comment by steveharter** [comment] 2019-08-08 22:49
@Joelius can you please verify the behavior of this part:

```cs
InnerContainer inner = new InnerContainer<string>   // actual type is generic
{
    Value = "StringValue"
};
...
// serialize inner
string innerJsonSystemTextJson = JsonSerializer.Serialize(inner);
```

> Inner container directly
> System.Text.Json (innerJsonSystemTextJson)
> {"Value":"StringValue"}

Since the declared variable type being serialized is `InnerContainer` not `InnerContainer<string>` you should get `"{}"` back not `{"Value":"StringValue"}` even though the instance is `InnerContainer<string>`

**Comment by Joelius300** [comment] 2019-08-09 19:57
You are right. The reason I got a different behaviour was because I actually declared inner as `object` before serializing, sorry about that. I have created two unit tests which show that this is in fact the current behaviour.  

```
[Fact]
public void InnerContainerNonSupportedPolymorphic()
{
    // arrange
    var options = new JsonSerializerOptions();

    InnerContainer inner = new InnerContainer<string>
    {
        ContainerId = 0,
        Value = "StringValue"
    };

    // act
    string json = JsonSerializer.Serialize(inner, options);

    // assert
    Assert.Contains(@"""ContainerId"":0", json);
    Assert.DoesNotContain(@"""Value"":""StringValue""", json);
}

[Fact]
public void InnerContainerPolymorphic_DeclaredObject()
{
    // arrange
    var options = new JsonSerializerOptions();

    InnerContainer inner = new InnerContainer<string>
    {
        ContainerId = 0,
        Value = "StringValue"
    };

    object objectInner = inner;

    // act
    string jsonExplicit = JsonSerializer.Serialize(inner, inner.GetType(), options);
    string jsonViaObject = JsonSerializer.Serialize(objectInner, /*typeof(object),*/ options);

    // assert
    Assert.Equal(jsonExplicit, jsonViaObject);
}
```

Testclasses:
```
// non-generic for generalization
public abstract class InnerContainer
{
    public int ContainerId { get; set; }
}

// generic for actual use
public class InnerContainer<TValue> : InnerContainer
{
    public TValue Value { get; set; }
}
```

Quick question about this. In [JsonSerializer.Write.String.cs (at line 21)](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L21):
Why is there `typeof(TValue)` instead of `value.GetType()`? If it was `value.GetType()`, this case would be supported.  
What is the reason for this? Does it have anything to do with performance?

**Comment by Joelius300** [comment] 2019-08-09 20:44
## Generic Workaround (write-only)

As a generic, seralize only workaround I use this converter.  

```
class PolymorphicWriteOnlyJsonConverter<T> : JsonConverter<T>
{
    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        throw new NotImplementedException($"Deserializing not supported. Type={typeToConvert}.");
    }

    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value, value.GetType(), options);
    }
}
```

You can either add it to the converters: 
```
// if you want to serialize this, you have to add a PolyphormicConverter for the declaring base-type (here Person)
Person person = new Customer();

var options = new JsonSerializerOptions();
options.Converters.Add(new PolymorphicWriteOnlyJsonConverter<Person>());
```

Or add with an attribute to the base-class. Keep in mind this only works if that is the declaring type of the property or variable you want to serialize. That's also the case if you add it to the converters but there you can directly see what converter to add.
```
[System.Text.Json.Serialization.JsonConverter(typeof(PolymorphicWriteOnlyJsonConverter<Person>))]
class Person
{ ... }
```

@steveharter Do you think this is a good workaround (serialize only ofc) or do you see any issues with this?
