### ISSUE TITLE
Make System.IO.Path.NormalizePath public

### ISSUE THREAD

**Issue by xPaw** [dotnet/corefx#4208] opened 2015-10-28 17:17 UTC
Right now the only way to normalize a path is by calling `GetFullPath`, but this is not always desirable. This could be especially useful since .NET is cross platform now. Thoughts?

**Comment by JeremyKuhne** [comment] 2015-10-29 17:28
@xPaw What specifically are you looking to avoid by not calling GetFullPath?

**Comment by xPaw** [comment] 2015-10-29 17:31
GetFullPath would resolve a path relative to the root directory or working directory. I have multiple cases where I work with relative paths (working with archives and other stuff) where I want to print normalized paths (that are "full" paths in said archive, but not on the system).

**Comment by JeremyKuhne** [comment] 2015-10-29 18:27
What you want is this, right?

```C#
        /// <summary>
        /// Try and remove relative segments from the given path (without combining with a root).
        /// </summary>
        /// <param name="skip">Skip the specified number of characters before evaluating.</param>
        private static string RemoveRelativeSegments(string path, int skip = 0)
        {
```

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/IO/Path.cs#L426

**Comment by xPaw** [comment] 2015-10-29 18:31
What I was thinking was changing '/' and '\' to `DirectorySeparatorChar` (e.g. '/' -> '\' on windows). Didn't think about relative segments, but that could be useful to have too.

**Comment by JeremyKuhne** [comment] 2015-10-29 19:05
This method does that as well. It also collapses runs of directory separators. UNCs and extended paths on Windows are weird so it would need to be altered some to be public (don't want to collapse the first two separators `\\`).

**Comment by xPaw** [comment] 2015-10-29 19:07
Then yes, this method sounds reasonable.

**Comment by wli3** [comment] 2018-06-26 22:57
I have the same problem. And the previous solution is moved to internal at https://github.com/dotnet/corert/pull/5520. Is there any alternative?

**Comment by JeremyKuhne** [comment] 2018-06-26 23:57
https://github.com/dotnet/corefx/blob/66110e6e5b0cdca7d212adb2062602ca4d041cfa/src/Common/src/CoreLib/System/IO/PathInternal.cs#L117

This is useful for a number of scenarios. Reopening so we can track.

@Anipik, this is the follow up I discussed with you. Can you help drive getting a formal API proposal together?

**Comment by Anipik** [comment] 2018-06-27 00:17
@JeremyKuhne I will write a formal Api proposal for it.

**Comment by ahsonkhan** [comment] 2019-05-11 08:14
Since https://github.com/dotnet/corefx/issues/30701 is targeting Future, moving this to Future as well.

**Comment by JeremyKuhne** [comment] 2020-01-14 23:54
Duplicate of #30701

**Closed by JeremyKuhne** 2020-01-14 23:54 UTC
Labels: api-needs-work, area-System.IO
