### ISSUE TITLE
Why we use CompareInfo.Invariant for Ordinal?

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#33047] opened 2018-10-25 15:20 UTC
I am not so familiar with unicode in-depth and I am amazed to see that
[`public int IndexOf(char value, StringComparison comparisonType)`](https://source.dot.net/#System.Private.CoreLib/shared/System/String.Searching.cs,dff9d7f2a57eacd4)
and all `IndexOf` overloads for strings like
[`public int IndexOf(string value, int startIndex, int count, StringComparison comparisonType)
`](https://source.dot.net/#System.Private.CoreLib/shared/System/String.Searching.cs,ef82268cfee756fe)
call CompareInfo.Invariant.IndexOf() for both InvariantCulture (InvariantCultureIgnoreCase) and Ordinal (OrdinalIgnoreCase).

In the same time we have `IndexOf` overloads for chars which use really ordinal comparison from SpanHelpers with SIMD accelerations.
[`public int IndexOf(char value) => SpanHelpers.IndexOf(ref _firstChar, value, Length);`](https://source.dot.net/#System.Private.CoreLib/shared/System/String.Searching.cs,eb06d6d166f6a3d9)

We even have [`public static int CompareOrdinal(string strA, int indexA, string strB, int indexB, int length)
`}(https://source.dot.net/#System.Private.CoreLib/shared/System/String.Comparison.cs,341906879aa2feb9).
(internally SpanHelpers with SIMD accelerations.)

---
_I'd expect the same for strings too if StringComparison is Ordinal or OrdinalIgnoreCase._

---
In the case we could implement very fast SIMD accelerated methods like IndexOf(), LastIndexOf(), Replace() and perhaps some more.

For OrdinalIgnoreCase we could implement unicode _simple case folding_ (#17233). With this enhancement we could to get great wins in RegEx (see [Rust RegEx lib](https://github.com/rust-lang/regex)) and simplify Boyer-Moore implementation (which is also useful in IndexOf() and Replace() - #17233 and https://github.com/dotnet/coreclr/issues/6918).
Some languages (like PowerShell) could get great wins in _identifier comparisons_.

**Comment by jkotas** [comment] 2018-10-25 15:32
This is duplicate of #19672. The `char` case was fixed already.

**Comment by iSazonov** [comment] 2018-10-25 15:38
@jkotas Is the link correct?

**Comment by jkotas** [comment] 2018-10-25 15:52
> @jkotas Is your link correct?

It is correct now.

> And my request is for strings not chars.

The linked issue is for `string.IndexOf(...`. If you would like to submit PRs with more fixes towards this, we will be happy to take them.

**Closed** 2018-10-25 16:03 UTC

**Comment by iSazonov** [comment] 2018-10-25 16:38
Why the fix is not replicated to CoreFX? https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/String.Searching.cs#L55

I am not ready to submit PRs but I will.

**Comment by jkotas** [comment] 2018-10-25 16:48
@anipik The recent changes in String.Searching.cs (and a few other files) were not mirrored correctly to corefx. Could you please take a look?

**Comment by Anipik** [comment] 2018-10-25 17:48
@jkotas there is no missing commit for this change. we will have to manually open the PR to correct it.
i can open PR to correct it in corefx and make sure the commit is not mirrored back to coreclr or corert(i.e mirror didnot get stuck due to merge conflicts)

**Comment by jkotas** [comment] 2018-10-25 17:49
That would be great. Could you please do that?

**Comment by Anipik** [comment] 2018-10-25 17:50
yeah i am on it
