### ISSUE TITLE
[Uri] Incorrect combination of absolute and relative URI in presence of non-ASCII characters

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#34227] opened 2018-12-23 15:00 UTC
```C#
Console.WriteLine(new Uri(new Uri("file:///x/", UriKind.Absolute), new Uri("a", UriKind.Relative)));
Console.WriteLine(new Uri(new Uri("file:///噸/", UriKind.Absolute), new Uri("a", UriKind.Relative)));
```

(the character 噸 is U+1234).

Expected:

```
file:///x/a
file:///噸/a
```

Actual:

```
file:///x/a
file:///%E5%99%B8//%E5%99%B8/a/噸//噸/a
```

Works on Desktop FX, fails on Core (both Windows and Linux).

```
> dotnet --version
3.0.100-preview-009844
```

**Comment by tmat** [comment] 2018-12-23 15:11
Affects Source Link - test disabled due to this issue: https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.Tasks.Git.UnitTests/GitOperationsTests.cs#L299

**Comment by davidsh** [comment] 2018-12-23 15:37
@rmkerr

**Comment by MihaZupan** [comment] 2019-12-19 17:24
Duplicate of dotnet/runtime#1061

**Closed by MihaZupan** 2019-12-19 17:24 UTC
Labels: area-System.Net, bug
