### ISSUE TITLE
System.Text.Json cannot serialize dictionary with deep values

### ISSUE THREAD

**Issue by eliashdezr** [dotnet/corefx#41283] opened 2019-09-24 14:36 UTC
Project to reproduce the error:
[JsonDemo.zip](https://github.com/dotnet/corefx/files/3647718/JsonDemo.zip)

Using `.NET Core 3.0.100`

Error:
```xml
System.NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Int32,JsonDemo.Controllers.Root]' on 'JsonDemo.Controllers.RootTest.Roots' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Using the `Newtonsoft` NuGet package and adding `AddNewtonsoftJson()` in `Startup.cs` worked. This is the expected result from the object that I'm trying to serialize:
```json
{
    "roots": {
        "1": {
            "rootId": 1,
            "rootChildrens": {
                "1": {
                    "rootChildrenId": 1,
                    "childrenDetails": [{
                            "data": "Children One Data"
                        }
                    ]
                },
                "2": {
                    "rootChildrenId": 2,
                    "childrenDetails": [{
                            "data": "Children Two Data"
                        }
                    ]
                }
            }
        },
        "2": {
            "rootId": 2,
            "rootChildrens": {
                "3": {
                    "rootChildrenId": 3,
                    "childrenDetails": [{
                            "data": "Children Three Data"
                        }
                    ]
                }
            }
        }
    }
}
```

**Comment by scalablecory** [comment] 2019-09-24 21:39
Does it work if you change the dictionary's key type to `string`?

**Comment by ahsonkhan** [comment] 2019-09-24 23:20
Only `Dictionary<string, TValue>` is supported. Your object model (Root), contains a `Dictionary<int, TValue>`

This issue is a duplicate of https://github.com/dotnet/corefx/issues/40120. Closing.

**Closed by ahsonkhan** 2019-09-24 23:20 UTC
Labels: area-System.Text.Json
