### ISSUE TITLE
SqlClient Connection Pooling error

### ISSUE THREAD

**Issue by narf37** [dotnet/corefx#23443] opened 2017-08-21 18:14 UTC
Hello , I have an Webapi that connect to different sql servers, we enabled connection pooling for both connections. Recently we need to apply a patch to one server, so we need to restart it. The result was that the connection pool blow the whole application. 

Different ways it fails:
  - When app starts, and you try to do first query to initialized the pool. If the server is not available or cannot connect.
 - After app starts and one of the server is not available, the app will eventually crash.
 - After app starts and you get intermittent connection availability, the app will eventually crash.

I test this on the new core 2.0 , and also on 1.1.2 both on windows and linux , same result.

this is the stack error that I get on core 2.0

System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.AggregateException: One or more errors occurred. (Connection refused 10.40.40.106:1433) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused 10.40.40.106:1433
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.SqlClient.SNI.SNITCPHandle.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.PoolCreateRequest(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted

I wrote a simple console test that helps to reproduced the issue. 
[Test.txt](https://github.com/dotnet/corefx/files/1239779/Test.txt)

The problem is that there is no way to catch the exception since it happens at the framework level, so the entire app crash.  If we removed the Min Pool Size the app wont crash.

**Comment by corivera** [comment] 2017-08-23 20:03
Duplicate issue with connection pool exceptions: https://github.com/dotnet/corefx/issues/14615

**Comment by narf37** [comment] 2017-08-23 20:23
Hi it seams like is related to issue  14615 , the difference is that 14615 is taking about the argument Pooling=true on the connection string , this one is with the Min Pool Size=XX , I get the exact same behavior of the whole app crashing. Please review it.

**Comment by saurabh500** [comment] 2018-02-12 22:44
Dupe of https://github.com/dotnet/corefx/issues/14615

**Closed by saurabh500** 2018-02-12 22:44 UTC
Labels: area-System.Data.SqlClient
