### ISSUE TITLE
Warning building corefx on mac locally

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#33002] opened 2018-10-24 11:26 UTC
```
Downloading 'https://dot.net/v1/dotnet-install.sh'
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-osx-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-osx-x64.tar.gz
dotnet-install: Adding to current process PATH: `/Users/hugh/Documents/GitHub/corefx/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/MSBuild.dll /nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/dotnet.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/Users/hugh/Documents/GitHub/corefx/eng/common/../../artifacts/log/Debug/ToolsetRestore.binlog /clp:Summary /clp:None /nr:true /p:__ToolsetLocationOutputFile=/Users/hugh/Documents/GitHub/corefx/eng/common/../../artifacts/toolset/1.0.0-beta.18522.6.txt /t:__WriteToolsetLocation /Users/hugh/Documents/GitHub/corefx/eng/common/../../artifacts/toolset/restore.proj

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.26
/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/MSBuild.dll /nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/hugh/Documents/GitHub/corefx/.dotnet/sdk/2.1.401/dotnet.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/Users/hugh/Documents/GitHub/corefx/eng/common/../../artifacts/log/Debug/Build.binlog /clp:Summary /nr:true /p:Configuration=Debug /p:Projects=/Users/hugh/Documents/GitHub/corefx/eng/common/../../*.sln /p:RepoRoot=/Users/hugh/Documents/GitHub/corefx/eng/common/../.. /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:ContinuousIntegrationBuild=false /Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18522.6/tools/Build.proj
/Users/hugh/Documents/GitHub/corefx/dependencies.props(80,3): warning MSB4011: "/Users/hugh/Documents/GitHub/corefx/eng/Versions.props" cannot be imported again. It was already imported at "/Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18522.6/tools/DefaultVersions.props (19,3)". This is most likely a build authoring error. This subsequent import will be ignored. [/Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18522.6/tools/Tools.proj]
  Restoring packages for /Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18522.6/tools/Tools.proj...
  Installing System.Xml.XPath 4.3.0.
  Installing System.Text.Encoding.CodePages 4.3.0.
  Installing System.Reflection.Metadata 1.6.0.
  Installing System.Xml.XmlDocument 4.3.0.
  Installing System.Xml.XPath.XDocument 4.3.0.
  Installing System.Collections.Immutable 1.5.0.
  Installing Microsoft.CodeAnalysis.Analyzers 2.6.1.
  Installing System.Diagnostics.FileVersionInfo 4.3.0.
  Installing System.Diagnostics.StackTrace 4.3.0.
  Installing System.ValueTuple 4.3.0.
  Installing Microsoft.CodeAnalysis.CSharp 2.9.0.
  Installing Microsoft.AnalyzerPowerPack 1.0.0.
  Installing MicroBuild.Core 0.2.0.
  Installing MicroBuild.Core.Sentinel 1.0.0.
  Installing vswhere 2.5.2.
  Installing Desktop.Analyzers 1.1.0.
  Installing Microsoft.DotNet.SignTool 1.0.0-beta.18511.3.
  Installing System.Security.Cryptography.Hashing.Algorithms.Analyzers 1.1.0.
  Installing System.Runtime.InteropServices.Analyzers 1.1.0.
  Installing System.Runtime.Analyzers 1.1.0.
  Installing Microsoft.CodeAnalysis.FxCopAnalyzers 1.1.0.
  Installing Microsoft.DotNet.GenAPI 1.0.0-beta.18478.5.
  Installing Microsoft.DotNet.ApiCompat 1.0.0-beta.18478.5.
  Installing Microsoft.DotNet.Build.Tasks.Packaging 1.0.0-beta.18518.2.
  Installing Microsoft.DotNet.CodeAnalysis 1.0.0-beta.18519.7.
  Installing Microsoft.CodeAnalysis.Common 2.9.0.
  Installing Microsoft.SymbolUploader.Build.Task 1.0.0-beta-63412-03.
  Installing Microsoft.DiaSymReader.Pdb2Pdb 1.1.0-beta1-62506-02.
  Installing Microsoft.DotNet.BuildTools 3.0.0-preview1-03322-02.
  Installing Microsoft.DotNet.Build.Tasks.Feed 3.0.0-preview1-03322-02.
  Installing Microsoft.DotNet.GenFacades 1.0.0-beta.18478.5.
  Generating MSBuild file /Users/hugh/Documents/GitHub/corefx/artifacts/toolset/Common/Tools.proj.nuget.g.props.
  Generating MSBuild file /Users/hugh/Documents/GitHub/corefx/artifacts/toolset/Common/Tools.proj.nuget.g.targets.
  Restore completed in 26.21 sec for /Users/hugh/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18522.6/tools/Tools.proj.

```

**Comment by Wraith2** [comment] 2018-10-24 12:00
Same issue on windows https://github.com/dotnet/corefx/issues/32961 , there's a fix in the pipeline somewhere.

**Comment by karelz** [comment] 2018-10-24 16:44
Duplicate of #32961

**Closed by karelz** 2018-10-24 16:44 UTC
