### ISSUE TITLE
Running performance tests requires specifying the OS

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#10567] opened 2016-08-04 16:22 UTC
<h1>UPDATE</h1>

Go further down the chain for the changes to the issue.

<hr/>

Attempting to run performance tests on my machine results in "error: Xunit performance package was not found", even though I have the required options installed in VS:
![image](https://cloud.githubusercontent.com/assets/5569508/17409563/aa21d390-5a24-11e6-9b91-0d48a67e96a9.png)
I've attempted uninstalling/reinstalling the feature, VisualStudio itself, and onto a new machine too.  Are the instructions incomplete or something?  Or what might I be doing wrong?

I do have VS2013 Community installed...

**Comment by weshaggard** [comment] 2016-08-04 21:43
Which instructions are you referring to? Which performance tools package are you looking for?

**Comment by Clockwork-Muse** [comment] 2016-08-05 02:25
@weshaggard - The [performance testing instructions](https://github.com/dotnet/corefx/blob/673e8307ec8811ce85c3f17cc5375a468a2fb152/Documentation/project-docs/performance-tests.md), that at least previously worked for me.

I suspect this is also affecting #10561 , although the exact problem there is unclear.


Buildtools has _something_ going on: dotnet/buildtools#723
And building the test tools package has an egregious version number (Microsoft/xunit-performance#157), but I'm not sure if that's the whole issue.

**Comment by lt72** [comment] 2016-08-05 19:52
@dsgouda 
Deepak: this could be fixed by fixing #157. Please fix #157 first and then move onto this one.

**Comment by dsgouda** [comment] 2016-08-05 20:05
@lt72 I believe https://github.com/Microsoft/xunit-performance/issues/157 was fixed by version 0039 of the xunit perf runner, prehaps we can try restoring that version and see if the issue still persists
The issue described in https://github.com/dotnet/buildtools/issues/723 sounds more relevant though I need to repro this to be sure

**Comment by Clockwork-Muse** [comment] 2016-08-06 18:41
@dsgouda - I actually figured something like that (new version fixes reference) had happened, at least from that end.  The bigger question might be if the fixed version got picked up elsewhere.

**Comment by Clockwork-Muse** [comment] 2016-08-25 01:12
Figured out what's going on: in dotnet/buildtools#730 , an explicit check for target OS was added, as part of the differentiation between Linux/Windows.  This means things run fine if I add `/p:TargetOs=Windows_NT` to the command line; it's just the error otherwise feels opaque.  

So (beside possibly temporarily updating the performance instructions), should I just move the issue to buildtools to supply the system OS for local performance tests?

**Comment by Clockwork-Muse** [comment] 2016-08-25 01:21
Side question: is there any way to build the performance analyzer so it doesn't need admin access?

**Comment by dsgouda** [comment] 2016-08-25 02:13
@Clockwork-Muse I wasn't sure about the scenario where you were trying to use xunit performance but yes you do need to pass the target OS to the msbuild tasks that run the perf tests, we can make changes to build tools to default to Windows_NT but I'm not sure if it is the right thing to do.
@MattGal do you have any thoughts here?

We do have a pending issue to update all performance testing instructions under CoreFX but haven't gotten to it yet ( https://github.com/dotnet/corefx/issues/9257) 

I'm not sure what you mean by building the performance analyzer, can you explain what you are trying to achieve there?

**Comment by Clockwork-Muse** [comment] 2016-08-25 15:59
@dsgouda - I don't want it to default to Windows either, that for sure would be the wrong choice.  I was just wondering about making it default to the current OS (like tests do), since it's not like you can have a different one when run local...

Running the performance analyzer is popping up a UAC prompt for me (`xunit.performance.logger.exe`).  One with an unsigned/unknown publisher, no less.  Mostly just annoying.  I'd prefer it if it no longer popped up a prompt, but would settle for it at least being signed.

**Comment by Clockwork-Muse** [comment] 2016-08-30 15:32
Currently, running the performance tests requires explicitly specifying the target os, such as with `/p:TargetOs=Windows_NT` or `/p:TargetOs=Linux` (actually, those may be the only two that actually work, given the targets file).  It would be better to have the system capture the host OS like the normal test runs do, and thus not require the parameter.

**Comment by dsgouda** [comment] 2016-08-30 16:31
Functional tests too require this flag but I doubt if there is any functionality to automatically determine the machine's OS environment in msbuild. Currently we default the OSGroup param to Windows_NT for functional tests but have to explicitly define it for Linux machines. We can probably emulate the same for perf tests if it helps end users.

**Comment by mellinoe** [comment] 2016-11-11 20:33
I made a recent change that auto-detects a test RID for all platforms. If the perf tests inherit that behavior, then this issue should be fixed. But, I'm not sure how they work. Is this still a problem? @Clockwork-Muse , @brianrob , @dsgouda

**Comment by brianrob** [comment] 2016-11-12 00:26
@DrewScoggins, can you confirm?

**Comment by Clockwork-Muse** [comment] 2016-11-14 16:58
@mellinoe - I don't know, I can't get any performance tests to run right now.  Have the instructions gone out of date again, or is something up with the larger process?  Build output complains that we've got a assembly mismatch:
```
Creating output directory: .
  Discovering tests for c:\Users\xande\repositories\corefx\bin\tests\Windows_NT.AnyCPU.Release\System.Collections.Tests\default.netcoreapp1.1\System.Collections.Tests.dll.
  Exception thrown during test framework discoverer construction: System.TypeLoadException: Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.
     at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
     at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
     at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
     at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
     at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
     at Xunit.Sdk.ReflectionAssemblyInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 63
     at Xunit.Sdk.TestFrameworkProxy.GetTestFrameworkType(IAssemblyInfo testAssembly, IMessageSink diagnosticMessageSink) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFrameworkProxy.cs:line 80
  Error: Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.
     at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
     at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
     at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttributeRecord caRecord)
     at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
     at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAssembly target)
     at Xunit.Sdk.ReflectionAssemblyInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 63
     at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 36
     at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\XunitTestFramework.cs:line 21
     at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 71
     at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 94
     at Xunit.XunitFrontController.CreateInnerController() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 111
     at Xunit.XunitFrontController.get_InnerController() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 81
     at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 135
     at Microsoft.Xunit.Performance.EtwPerformanceMetricLogger..ctor(XunitPerformanceProject project, Program program) in D:\git\xunit-performance-master\src\xunit.performance.run\EtwPerformanceMetricLogger.cs:line 47
     at Microsoft.Xunit.Performance.Program.GetPerformanceMetricLogger(XunitPerformanceProject project) in D:\git\xunit-performance-master\src\xunit.performance.run\ProgramDesktop.cs:line 28
     at Microsoft.Xunit.Performance.ProgramCore.RunTests(XunitPerformanceProject project) in D:\git\xunit-performance-master\src\xunit.performance.run\ProgramCore.cs:line 164
     at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args) in D:\git\xunit-performance-master\src\xunit.performance.run\ProgramCore.cs:line 56
```

... however, leaving off the `OSGroup` option still generates the same error it did previously.

**Comment by MattGal** [comment] 2016-11-14 17:54
I'll try this out shortly myself.  Problems with System.Private.CoreLib are affecting the main functional builds as well so this could simply be a manifestation of that.

**Comment by DrewScoggins** [comment] 2016-11-14 19:00
As far as I know you still need to use the OSGroup flag when you want to run performance tests, and it seems like @Clockwork-Muse has confirmed this.  The assembly loading issue you are seeing we have run into before in the CoreCLR repo, due to work being done for Net Standard 2.0.  This commit https://github.com/dotnet/coreclr/pull/7835/commits/ef60f7921285baef7257b79fa79443ff15205d57 in the coreclr repo shows the work we did to move the tests to netstandrad1.4 so that we could load the tests properly in the runner.  We just need to do this work to the tests in CoreFX as well.

**Comment by MattGal** [comment] 2016-11-14 19:12
Yup, I had the same experience.  The reason TargetOS has to be explicitly set is clear in PerfTesting.targets: https://github.com/dotnet/buildtools/blob/50b800cd9a84da8609c4c59959e1222688a173fa/src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets#L20  since many required properties are only set it TargetOS is also set.   These could switch to use one of the various other properties easily (OS, OSGroup, etc)

**Comment by weshaggard** [comment] 2016-11-15 16:52
>These could switch to use one of the various other properties easily (OS, OSGroup, etc)

We should definitely look at using something that gets a default value setup so it isn't required to be specified at the command line everytime.

> This commit dotnet/coreclr@ef60f79 in the coreclr repo shows the work 

Unfortunately that same fix isn't going to work in corefx. We have started moving a lot of our tests to be .NET Core specific and so we will not be able to make all the test projects we want to run performance benchmarks on .NET Standard based.

**Comment by brianrob** [comment] 2017-03-09 05:10
@DrewScoggins have your recent changes handled this issue?  Can you point @Clockwork-Muse to updated instructions (or update the set referenced above), as it looks like this issue also covered the fact that there were various breaks.

**Comment by DrewScoggins** [comment] 2017-03-09 18:31
Yeah, I will update the instructions referenced above.

**Comment by Clockwork-Muse** [comment] 2017-03-25 22:40
Tests still require OS name, but instructions are out of date generally, see #9257

**Comment by mario-d-s** [comment] 2018-05-23 08:56
@Clockwork-Muse I see #9257 has been fixed since, can you check if it solves your problem here?

**Comment by Clockwork-Muse** [comment] 2018-05-24 04:26
@mario-d-s 
What do you mean?  The instructions have been updated/working for a while, but they still require supplying the OS.

**Comment by ViktorHofer** [comment] 2018-08-17 13:45
@Clockwork-Muse I hit this recently as well and created a PR which should fix this. thanks for bringing this up!

**Closed** 2018-08-21 14:29 UTC
Labels: area-Infrastructure, test bug
