### ISSUE TITLE
VisualStudio 2019 debugger shows incorrect string for System.Numerics.Vector<long>

### ISSUE THREAD

**Issue by Konard** [dotnet/corefx#42112] opened 2019-10-25 12:54 UTC
Using latest .NET Standard 2.1 (.NET Core 3.0) and Visual Studio 2019, executing the code:
```C#
var vector = new System.Numerics.Vector<long>(new long[] { 1, 1, 1, 1 });
```
When vector is hovered in the debugger it shows:
```
{<1, 1, 0, 0>}
```
![2019-10-25_15-52-46](https://user-images.githubusercontent.com/1431904/67572847-ba2ca880-f73f-11e9-9dba-12d1c8a67254.png)

**Comment by 0xd4d** [comment] 2019-10-25 13:36
https://github.com/dotnet/coreclr/issues/10148

**Comment by tannergooding** [comment] 2019-10-25 14:24
This is a duplicate of https://github.com/dotnet/coreclr/issues/16280.

**Closed by tannergooding** 2019-10-25 14:24 UTC
Labels: area-System.Numerics
