### ISSUE TITLE
Test System.Collections.Immutable.Tests.ImmutableDictionaryTest.AddRemoveRandomDataTest failed in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26778] opened 2018-02-02 07:10 UTC
Test System.Collections.Immutable.Tests.ImmutableDictionaryTest.AddRemoveRandomDataTest failed.

Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug/4169/testReport/System.Collections.Immutable.Tests/ImmutableDictionaryTest/AddRemoveRandomDataTest/

Failed configuration: osx10.12_Debug

MESSAGE:
Assert.True() Failure\nExpected: True\nActual: False
~~~
STACK TRACE:
at System.Collections.Immutable.Tests.ImmutableDictionaryTestBase.AddRemoveRandomDataTestHelper(IImmutableDictionary`2 map) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Collections.Immutable/tests/ImmutableDictionaryTestBase.cs:line 410 at System.Collections.Immutable.Tests.ImmutableDictionaryTestBase.AddRemoveRandomDataTest() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug/src/System.Collections.Immutable/tests/ImmutableDictionaryTestBase.cs:line 85
~~~

**Comment by karelz** [comment] 2018-02-05 17:31
Duplicate of #26821

**Comment by ianhays** [comment] 2018-02-26 23:10
This appears to be due to the same root cause as https://github.com/dotnet/corefx/issues/26821 which was resolved. I'm going to close it and if it happens again we can re-examine.

**Closed by ianhays** 2018-02-26 23:10 UTC
Labels: area-System.Collections, test-run-core
