### ISSUE TITLE
Using Dynamic with COM object doesn't work

### ISSUE THREAD

**Issue by dotMorten** [dotnet/corefx#32630] opened 2018-10-05 04:43 UTC
I'm trying to use `dynamic` against COM objects to access the Location API `LocationDisp.LatLongReportFactory` as described here: https://docs.microsoft.com/en-us/windows/desktop/LocationAPI/locationdisp-latlongreportfactory

This works fine on .NET Framework, but fails on .NET Core when trying to access properties and methods on the COM object.

### Repro steps:

```
            Type t = Type.GetTypeFromCLSID(new Guid("9DCC3CC8-8609-4863-BAD4-03601F4C65E8"));
            dynamic handle = Activator.CreateInstance(t);

            //Fails on .NET Core (works on .NET Framework):
            uint accuracy = handle.DesiredAccuracy;
            
            // Using reflection approach instead succeeds:
            var accuracy2 = t.InvokeMember("DesiredAccuracy", 
                Reflection.BindingFlags.Instance | Reflection.BindingFlags.GetProperty | Reflection.BindingFlags.Public,
                null, handle, new object[] { });
```

Exception:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: ''System.__ComObject' does not contain a definition for 'DesiredAccuracy''
StackTrace:
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Device.TestApp.Program.Main(String[] args) in e:\Sources\System.Device.TestApp\Program.cs:line 16
```
![image](https://user-images.githubusercontent.com/1378165/46516369-26c7c300-c81e-11e8-88e0-50c9c6d79b87.png)

I'm seeing this behavior both with 2.1 and 3.0-preview

**Comment by jkotas** [comment] 2018-10-05 13:39
cc @AaronRobinsonMSFT

**Comment by jeffschwMSFT** [comment] 2019-01-30 21:59
Per @richlander "It requires a dependency that we don’t want to take in a lean stack. That said, it would be straightforward for anyone to build a layer on top that did this."

**Comment by jeffschwMSFT** [comment] 2019-01-30 22:36
@dotMorten perhaps we can find a way to enable this without the use of dynamic.  Check out the Excel sample: https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo
You can use native com objects in a statically typed way.

**Comment by dotMorten** [comment] 2019-01-31 01:19
@jeffschwMSFT Yeah I tried that and failed (it doesn't generate any APIs). After your post I tried again, and somehow it now works. That's awesome.

I would however have preferred a way where System.Device.dll didn't have to be completely rewritten, but a straight port "just works"

**Comment by jeffschwMSFT** [comment] 2019-01-31 16:13
@AaronRobinsonMSFT is taking a closer look, but I am happy to see that our recent work enabling COM is at least one path forward.

**Comment by AaronRobinsonMSFT** [comment] 2019-04-25 16:36
Closing this issue as a duplicate of https://github.com/dotnet/coreclr/issues/24246

**Closed by AaronRobinsonMSFT** 2019-04-25 16:36 UTC
Labels: area-System.Runtime.InteropServices
