### ISSUE TITLE
Json Deserialize issue with class has "new modifier" property

### ISSUE THREAD

**Issue by nhuthan** [dotnet/corefx#42692] opened 2019-11-23 01:17 UTC
Here is simple code:
```
public class Program
{
	public static void Main()
	{
		var str = "{\"P1\": 123}";
		var obj = JsonSerializer.Deserialize<B>(str);	//--> throw
		
	}
}

public class A{
	public int P1{get;set;}	
	public int P2{get;set;}
}

public class B: A{
	public new float P1{get;set;}
}
```
And I got an error:
```
Unhandled exception. System.InvalidOperationException: The JSON property name for 'B.P1' collides with another property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(JsonClassInfo jsonClassInfo, JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.Main()
Command terminated by signal 6
```

**Comment by layomia** [comment] 2019-11-23 04:00
Closing - duplicate of https://github.com/dotnet/corefx/issues/41338, but for deserialization.

**Closed by layomia** 2019-11-23 04:00 UTC
Labels: area-System.Text.Json, bug
