### ISSUE TITLE
Duplicate types in System.IO.Packaging.dll and WindowsBase.dll

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#33720] opened 2018-11-27 23:19 UTC
(Filing bugs from my notes after customer visit exploring porting large WPF app to .NET core 3)

# Repro steps
* Install 3.0 SDK
* mkdir repro
* cd repro
* dotnet new wpf
* dotnet add package Microsoft.Windows.Compatibility
* Edit MainWindow.xaml.cs

```diff
        public MainWindow()
        {
            InitializeComponent();
+            var x = typeof(System.IO.Packaging.PackUriHelper);
        }
```

* dotnet build

# Expected result

Builds successfully

# Actual result
```
MainWindow.xaml.cs(26,48): error CS0433: The type 'PackUriHelper' exists in both 'System.IO.Packaging, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [
```

@ericstj

**Comment by ericstj** [comment] 2019-02-27 21:30
Duplicate of https://github.com/dotnet/corefx/issues/29959

**Closed by ericstj** 2019-02-27 21:30 UTC
Labels: area-System.IO, bug
