### ISSUE TITLE
JsonSerializer support for TimeSpan in 3.0?

### ISSUE THREAD

**Issue by martincostello** [dotnet/corefx#38641] opened 2019-06-18 14:13 UTC
_Apologies if this is already answered somewhere else, but if it was my search abilities failed me._

I'm trying out the preview 6 of 3.0 with some existing production application code, and one of the issues that's come out of testing is that some of our existing objects we use in our API contracts use properties which are `TimeSpan` values, which are then represented as strings.

Is support for `TimeSpan` properties planned for 3.0 for the new System.Text.Json APIs?

If it's not going to be that gives us notice to do some refactoring ahead of September to change them to strings so we can use the new serializer, where as if it's planned but just not implemented yet then we just need to wait for a later preview to get this working.

Below is a minimal repro unit test that demonstrates the failure for `TimeSpan` to be handled compared to our existing JSON .NET code.

```csharp
using System;
using System.Text.Json.Serialization;
using Xunit;
using JsonConvert = Newtonsoft.Json.JsonConvert;
using JsonSerializer = System.Text.Json.Serialization.JsonSerializer;

namespace JsonSerializerTimeSpanNotSupportedException
{
    public static class Repro
    {
        [Fact]
        public static void Can_Deserialize_Object_With_SystemTextJson()
        {
            // Arrange
            string json = "{\"child\":{\"value\":\"00:10:00\"}}";

            // Act (fails in preview 6, throws: System.Text.Json.JsonException : The JSON value could not be converted to System.TimeSpan. Path: $.child.value | LineNumber: 0 | BytePositionInLine: 28.)
            var actual = JsonSerializer.Parse<Parent>(json, new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(TimeSpan.FromMinutes(10), actual.Child.Value);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_NewtonsoftJson()
        {
            // Arrange
            string json = "{\"child\":{\"value\":\"00:10:00\"}}";

            var actual = JsonConvert.DeserializeObject<Parent>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(TimeSpan.FromMinutes(10), actual.Child.Value);
        }

        private sealed class Parent
        {
            public Child Child { get; set; }
        }

        private sealed class Child
        {
            public TimeSpan Value { get; set; }
        }
    }
}
```

**Comment by ahsonkhan** [comment] 2019-06-20 05:26
We currently do not have plans to support `TimeSpan` and would be added in the future but I can do some investigation to see how much work is involved.  Alternatively, you could create your own `JsonConverter` to support `TimeSpan` as a workaround. I'll give an update by end of next week. Thanks.

**Comment by martincostello** [comment] 2019-06-20 06:40
Thanks - a custom converter would also be an easy enough way to make it work for our app for 3.0. Are those capabilities planned to ship with preview 7?

**Comment by steveharter** [comment] 2019-06-20 14:55
Yes the custom converter support is now in master and thus will be in preview 7.

However, since TimeSpan is a common BCL type we should still provide a default converter.

**Comment by terrajobst** [comment] 2019-06-26 00:51
We reviewed this today:

* There is an argument in favor of it, because it's a value type. In principle we could optimize parsing to be allocation free (i.e. avoid going through a string).
* It's unclear whether there is an standard encoding for time spans.
* For now, close. This can be reopened if there is enough customer evidence that this needed.

**Closed by terrajobst** 2019-06-26 00:51 UTC
Labels: area-System.Text.Json, up-for-grabs

**Comment by khellang** [comment] 2019-06-27 07:03
> * It's unclear whether there is an standard encoding for time spans.

The standard encoding for time spans would be [ISO8601's "duration"](https://en.wikipedia.org/wiki/ISO_8601#Durations). This is also what [XML use to represent `TimeSpan`](https://www.w3.org/TR/xmlschema-2/#duration) and is already implemented in `XmlConvert` and `XsdDuration`:

https://github.com/dotnet/corefx/blob/6d723b8e5ae3129c0a94252292322fc19673478f/src/System.Private.Xml/src/System/Xml/XmlConvert.cs#L1128-L1146

https://github.com/dotnet/corefx/blob/6d723b8e5ae3129c0a94252292322fc19673478f/src/System.Private.Xml/src/System/Xml/Schema/XsdDuration.cs#L229-L236

Now, arguably, `TimeSpan` itself should support parsing and formatting ISO8601 duration formats. Maybe it would be better, as a first step, to add a new standard `TimeSpan` format string, similar to `DateTime[Offset]`'s round-trip ("O", "o") format specifier? Adding a converter after that would be really simple.

**Comment by yhvicey** [comment] 2019-06-30 16:52
This also changed default behavior of how AspNetCore handing returning `TimeSpan` type in API, see aspnet/AspnetCore#11724. This might be a breaking change.

**Comment by rezabayesteh** [comment] 2019-10-09 21:11
The simplest solution is to create a custom converter:
```
public class TimeSpanConverter : JsonConverter<TimeSpan>
    {
        public override TimeSpan Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return TimeSpan.Parse(reader.GetString());
        }

        public override void Write(Utf8JsonWriter writer, TimeSpan value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString());
        }
    }
```

**Comment by FForthmann** [comment] 2019-10-22 17:41
Talking about customer evidence: for our software-development support for TimeSpan is highly necessary.

**Comment by IGx89** [comment] 2019-10-23 16:52
Ran into this today porting an app to .NET Core 3.0 as well. Because this is closed does that mean Microsoft has no plans to add native support? @khellang's comment seems a pretty convincing argument to me that it should be on a roadmap somewhere...

**Comment by mfeingol** [comment] 2019-10-31 22:20
Just ran into this issue today. The default behavior is worse than previous behavior and was entirely unexpected. We should fix it, either by using ISO8601 or being compatible with Newtonsoft.

**Comment by khellang** [comment] 2019-11-01 07:14
> The default behavior is worse than previous behavior and was entirely unexpected.

@mfeingol What behavior? That it simply fails?

> We should fix it, either by using ISO8601 or being compatible with Newtonsoft.

It's really easy to just add the workaround @rezabayesteh mentioned.

**Comment by mfeingol** [comment] 2019-11-01 15:27
@khellang: what I observed with a relatively vanilla ASP.NET Core project is that it serializes a `Timespan?` as a `HasValue` field, and then each of the properties of the TimeSpan struct.

> It's really easy to just add the workaround

I did, but that shouldn't be necessary for such a commonly used type.

**Comment by bashocz** [comment] 2019-11-11 17:04
I've just found this issue today (reported by my customer) and have to switch back all of my aspnet webapi and apps to use Newtonsoft.Json serializer instead using configuration in Startup.cs:

services.AddControllers()
    .AddNewtonsoftJson(options =>
    {
        options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
    });

In my cases I use a few nullable TimeSpan (TimeSpan?) and System.Text.Json has serialized it as:

{
"hasValue": true,
"value": {
"tick":0,
"days": 0,
"hours": 0,
"milliseconds": 0,
"minutes": 0,
"seconds": 0,
"totalDays": 0,
"totalHours": 0,
"totalMilliseconds": 0,
"totalMinutes": 0,
"totalSeconds": 0
}
}

This causes a little problem for javascript objects in web browsers, as well as for various cross-platform (means various programming languages) deserializers consuming my apis.

I would expect same serialization result as Newtonsoft.Json serializer:

{
"timeSpan": "00:00:00.0000000",
"nullTimeSpan": null
}

**Comment by khellang** [comment] 2019-11-12 15:14
> I've just found this issue today (reported by my customer) and have to switch back all of my aspnet webapi and apps to use Newtonsoft.Json serializer instead

@bashocz Why won't the workaround mentioned in https://github.com/dotnet/corefx/issues/38641#issuecomment-540200476 work for you?

**Comment by bashocz** [comment] 2019-11-12 15:45
> Why won't the workaround mentioned in [#38641 (comment)](https://github.com/dotnet/corefx/issues/38641#issuecomment-540200476) work for you?

@khellang I just want to highlight TimeSpan serialization is an issue for another developers, and give it an attention. I'd very like to switch to System.Text.Json, however there are some obstacles.

I'd investigated new System.Text.Json a few weeks ago and found it is not feature complete. I've raised an issue #41747 and was pointed to other #39031, #41325, #38650 related. Because of that all of our internal microservices still use Newtonsoft.Json.

For unknown reason I forgot to manage devs to fix it on public APIs and webapps as well.

BTW: I try to avoid workarounds as much as possible in production code.. it's hard to maintain and remove it in future.

**Comment by arisewanggithub** [comment] 2019-11-15 22:51
@khellang , it's not that a workaround won't work. It's just such a basic thing shouldn't need developers to add a workaround. As a big feature introduced for .NET core 3, it shouldn't lack such basic implementations.

**Comment by arisewanggithub** [comment] 2019-11-15 23:05
@khellang Also, if our code calls the deserialize and serialize, we can pass the custom converter. But in case for asp.net controllers, how would it work? The model binding calls it. And there is no global default settings to pass the custom converter.

**Comment by martincostello** [comment] 2019-11-16 07:15
@arisewanggithub There are global settings available to controllers. You can configure it via `AddJsonOptions()`, or you can pass a `JsonSerializerOptions` instance to the `Json()` controller method.

**Comment by acclaimuser** [comment] 2019-12-19 14:57
Is this closed cause we are having workaround?!

**Comment by khellang** [comment] 2019-12-19 15:09
> Is this closed cause we are having workaround?!

The issue is still open, pending an API/behavior proposal, review and implementation. In the meantime, it's pretty easy to work around by using the converter mentioned in https://github.com/dotnet/corefx/issues/38641#issuecomment-540200476.

**Comment by CodeBlanch** [comment] 2020-01-26 01:07
For anyone blocked by this, here's a NuGet package with a converter (JsonTimeSpanConverter) we can use ahead of the 5.0 drop: [Macross.Json.Extensions](https://www.nuget.org/packages/Macross.Json.Extensions/)

Supports TimeSpan & Nullable<TimeSpan> types.
