### ISSUE TITLE
HPACK: DynamicTable Resize doesn't handle circular scenarios

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39967] opened 2019-08-01 22:23 UTC
DynamicTable uses a circular buffer, but it's Resize API doesn't account for that. When Resize copies the underlying buffer it can end up inserting that new blank space in the middle of the circular buffer, throwing off the indexes.

We currently disable DynamicTable usage via SETTINGS at startup, so this does not affect us currently. If we ever choose to enable DynamicTable usage, we will need to fix this.

See https://github.com/aspnet/AspNetCore/issues/12784 for more details.

**Comment by scalablecory** [comment] 2019-08-02 03:58
Dupe of #39656, and already fixed.

**Comment by scalablecory** [comment] 2019-08-02 03:58
Misunderstood ticket, not a dupe.

**Closed** 2019-08-07 01:23 UTC
Labels: area-System.Net.Http
