### ISSUE TITLE
Building in Visual Studio stopped working

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#439] opened 2015-01-16 16:00 UTC
While building on the command line via `build.cmd` works just fine, building with Visual Studio doesn't.

It's worth calling out that building on the command line via `devenv` is also broken: 

```
$ devenv .\System.Collections.NonGeneric.sln /build

Microsoft Visual Studio 2013 Version 12.0.31101.0.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Build started: Project: System.Collections.NonGeneric, Configuration: Debug Any CPU ------
1>CSC : error CS0518: Predefined type 'System.Object' is not defined or imported
2>------ Build started: Project: System.Collections.NonGeneric.Tests, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'P:\oss\corefx\bin\Debug\System.Collections.NonGeneric\System.Collections.NonGeneric.dll' could not be found
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

It seems the new build-based package resolution is to blame.

For example, here is the output of building **System.Collections.NonGeneric**:

Type    | #   | Description                                                 | Project
--------|-----|-------------------------------------------------------------|------------------------------------
Error   | 1   | Unable to find nupkg for System.Text.Encoding.              | System.Collections.NonGeneric.Tests
Error   | 2   | Unable to find nupkg for xunit.console.netcore.             | System.Collections.NonGeneric.Tests
Error   | 3   | Unable to find nupkg for xunit.runner.dependencies.netcore. | System.Collections.NonGeneric.Tests
Error   | 4   | Unable to find nupkg for Microsoft.DotNet.TestHost.         | System.Collections.NonGeneric.Tests
Error   | 5   | Unable to find nupkg for System.Collections.Concurrent.     | System.Collections.NonGeneric.Tests
Error   | 6   | Unable to find nupkg for System.Diagnostics.Tracing.        | System.Collections.NonGeneric.Tests
Error   | 7   | Unable to find nupkg for System.IO.FileSystem.              | System.Collections.NonGeneric.Tests
Error   | 8   | Unable to find nupkg for System.IO.FileSystem.Primitives.   | System.Collections.NonGeneric.Tests
Error   | 9   | Unable to find nupkg for System.Linq.                       | System.Collections.NonGeneric.Tests
Error   | 10  | Unable to find nupkg for System.Reflection.Extensions.      | System.Collections.NonGeneric.Tests
Error   | 11  | Unable to find nupkg for System.Runtime.Handles.            | System.Collections.NonGeneric.Tests
Error   | 12  | Unable to find nupkg for System.Runtime.InteropServices.    | System.Collections.NonGeneric.Tests
Error   | 13  | Unable to find nupkg for System.Text.Encoding.Extensions.   | System.Collections.NonGeneric.Tests
Error   | 14  | Unable to find nupkg for System.Text.RegularExpressions.    | System.Collections.NonGeneric.Tests
Error   | 15  | Unable to find nupkg for System.Xml.ReaderWriter.           | System.Collections.NonGeneric.Tests
Error   | 16  | Unable to find nupkg for System.Xml.XDocument.              | System.Collections.NonGeneric.Tests

**Comment by davkean** [comment] 2015-01-16 16:27
This only happens for the test projects? @FiveTimesTheFun is there something special you are doing here for the test projects that would cause this?

**Comment by joshfree** [comment] 2015-01-16 18:27
Are all tests broken currently or just a few specific csproj files?

**Comment by shiftkey** [comment] 2015-01-17 10:39
Stumbled upon this after opening `System.Xml.sln` in VS2015 CTP (the version which just dropped). Here's the default build output:

```
1>------ Build started: Project: XunitTraitsDiscoverers, Configuration: Debug Any CPU ------
1>  XunitTraitsDiscoverers -> C:\Users\brendanforster\Documents\GitHub\corefx\bin\Debug\XunitTraitsDiscoverers\XunitTraitsDiscoverers.dll
2>------ Build started: Project: System.Xml.XmlDocument.Tests, Configuration: Debug Any CPU ------
3>------ Build started: Project: System.Xml.XPath.XDocument.Tests, Configuration: Debug Any CPU ------
2>  System.Xml.XmlDocument.Tests -> C:\Users\brendanforster\Documents\GitHub\corefx\bin\Debug\System.Xml.XmlDocument.Tests\System.Xml.XmlDocument.Tests.dll
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.console.netcore.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.runner.dependencies.netcore.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for Microsoft.DotNet.TestHost.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Collections.Concurrent.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Console.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Diagnostics.Tracing.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.Primitives.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Reflection.Extensions.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.Handles.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.InteropServices.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.Encoding.Extensions.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.RegularExpressions.
2>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Xml.XDocument.
4>------ Build started: Project: System.Xml.XPath.XmlDocument.Tests, Configuration: Debug Any CPU ------
4>  System.Xml.XPath.XmlDocument.Tests -> C:\Users\brendanforster\Documents\GitHub\corefx\bin\Debug\System.Xml.XPath.XmlDocument.Tests\System.Xml.XPath.XmlDocument.Tests.dll
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.console.netcore.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.runner.dependencies.netcore.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for Microsoft.DotNet.TestHost.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Collections.Concurrent.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Console.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Diagnostics.Tracing.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.Primitives.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Reflection.Extensions.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.Handles.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.InteropServices.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.Encoding.Extensions.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.RegularExpressions.
4>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Xml.XDocument.
5>------ Build started: Project: System.Xml.XDocument.Tests, Configuration: Debug Any CPU ------
3>  System.Xml.XPath.XDocument.Tests -> C:\Users\brendanforster\Documents\GitHub\corefx\bin\Debug\System.Xml.XPath.XDocument.Tests\System.Xml.XPath.XDocument.Tests.dll
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.console.netcore.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.runner.dependencies.netcore.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for Microsoft.DotNet.TestHost.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Collections.Concurrent.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Console.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Diagnostics.Tracing.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.Primitives.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Reflection.Extensions.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.Handles.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.InteropServices.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.Encoding.Extensions.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.RegularExpressions.
3>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Xml.XDocument.
5>  System.Xml.XDocument.Tests -> C:\Users\brendanforster\Documents\GitHub\corefx\bin\Debug\System.Xml.XDocument.Tests\System.Xml.XDocument.Tests.dll
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.console.netcore.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for xunit.runner.dependencies.netcore.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for Microsoft.DotNet.TestHost.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Collections.Concurrent.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Console.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Diagnostics.Tracing.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.IO.FileSystem.Primitives.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Reflection.Extensions.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.Handles.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Runtime.InteropServices.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.Encoding.Extensions.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Text.RegularExpressions.
5>C:\Users\brendanforster\Documents\GitHub\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5): error : Unable to find nupkg for System.Xml.XDocument.
========== Build: 1 succeeded, 4 failed, 6 up-to-date, 0 skipped ==========
```

It restores some packages when you build it the first time, but definitely seems to be related to test projects and `Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\publishtest.targets(32,5)`

**Comment by weshaggard** [comment] 2015-01-17 17:37
This issue is particular to all test projects. I know the what the issue is and I'm working on a fix for it.

**Comment by weshaggard** [comment] 2015-01-18 01:52
I've unblocked the building inside VS with #458. The problem was that the test-runtime\packages.config was not being restored during VS restore process, however the CopyTestToTestDirectory tries to resolve the contents of those packages to copy and they don't exist that is where the error occurs. For now to fix this I've added all the package dependencies into our global solution packages.config which will unblock this.

I am working on some other changes to our testing process that will hopefully eliminate the need to maintain this list of packages dependencies in the global solution config. Most likely I will end up restoring test-runtime\packages.config via msbuild before the test copy target. 

Also another thing to note is we cannot use `devenv .\System.Collections.NonGeneric.sln /build` to validate this because in this case VS doesn't do any package restoring and we definitely require that before we can build. If you look at the errors in the output between that and building VS they are difference. DevEnv is complaining about System.Object being missing which is because no packages were restored and the VS UI was just complaining about not finding particular packages which were those in the test-runtime\packages.config list.

For now until I finish my other work I'm going to keep this issue open to ensure that we have some way to keep this working.

**Comment by terrajobst** [comment] 2015-01-18 02:00
Thanks for the details, that all makes sense to.

It seems somewhat weird that our BuildTools NuGet package *contains* a `package.config` that we have to restore when running the tests. It seems that those should be promoted to be dependencies of the test runner package, no? Shouldn't this solve this problem?

**Comment by weshaggard** [comment] 2015-01-18 02:11
@terrajobst I was playing around with that idea but I couldn't get that to work with restore. I think the dependencies of a packages.config are only pulled down during install and not restore. So unless I'm missing something it seems like you still need to list them all out explicitly for restore to work. I'm happy to be wrong here by the way but from my quick testing it didn't seem to work.

**Comment by shiftkey** [comment] 2015-01-18 11:46
:thumbsup: to the fix in #458

**Comment by terrajobst** [comment] 2015-01-19 00:36
@weshaggard 

Generally speaking, the `packages.config` is considered to contain he closure. In other words, `nuget restore` will not download any packages that aren't listed in `packages.config`.

**Comment by mj1856** [comment] 2015-02-01 07:54
FYI - The "Predefined type 'System.Object' is not defined or imported" mentioned in this issue will also show up if Xamarin is installed (see #449).

**Comment by ellismg** [comment] 2015-02-08 08:29
@weshaggard Is this still an issue?

**Comment by weshaggard** [comment] 2015-02-10 04:45
@ellismg Yes this issue is actually fixed I'm still working on some packaging changes but they aren't blocking this issue. The only issue I'm aware of is #449 which is related to Xamarin tools being installed, so I'm closing this one.

**Closed by weshaggard** 2015-02-10 04:45 UTC
Labels: bug, Infrastructure
