### ISSUE TITLE
Flaky test System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected

### ISSUE THREAD

**Issue by shimingsg** [dotnet/corefx#17327] opened 2017-03-21 08:20 UTC
This test fails when a GC stress on Ubuntu 16.04 LTS:
I am not sure if it is a bug or not, open this issue to track it

  <test name="System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected" type="System.Net.Tests.WebProxyTest" method="BypassOnLocal_MatchesExpected" time="0" result="Fail"
>
        <failure exception-type="System.Net.Internals.SocketExceptionFactory+ExtendedSocketException">
          <message><![CDATA[System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address]]></message>
          <stack-trace><![CDATA[   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /home/gcstress/repos/corefx/src/System.Net.NameResolution/src
/System/Net/DNS.cs:line 83
   at System.Net.Dns.ResolveCallback(Object context) in /home/gcstress/repos/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /home/gcstress/repos/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /home/gcstress/repos/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /home/gcstress/repos/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 652
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext() in /home/gcstress/repos/corefx/src/System.Net.WebProxy/tests/WebProxyTest.cs:line 146
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /home/gcstress/repos/corefx/src/System.Linq/src/System/Linq/Select.cs:line 133]]></stack-trace>
        </failure>
      </test>

**Comment by stephentoub** [comment] 2017-03-21 10:30
I suspect this is either the same root cause or a related cause to https://github.com/dotnet/corefx/issues/17177.

**Comment by karelz** [comment] 2017-03-21 18:24
@shimingsg does it repro 100% for you with GCStress enabled, or only sometimes? BTW: Which GCStress?

@danmosemsft I assume we should catch it in our GCStress runs on every CoreFX test ...

**Comment by danmosemsft** [comment] 2017-03-21 18:50
@karelz this was `COMPLUS_GCSress=3`. Of course it's not necessarily triggerd by GCStress. It could be random, or exposed by the slow execution.

Not sure what you mean by your 2nd question. We don't have regular runs and I don't think this is something that should affect just any test.

**Comment by karelz** [comment] 2017-03-21 19:26
Oh, I didn't realize that this issue is a result of our stress run. I thought it is external report ... can you please confirm?

**Comment by Jiayili1** [comment] 2017-03-31 05:56
Test "System.Net.Tests.WebProxyTest/BypassOnLocal_MatchesExpected" failed again on build 20170331.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170331.01/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FBypassOnLocal_MatchesExpected

Message:
~~~
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
~~~

Stack Trace:
~~~
at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 83
   at System.Net.Dns.ResolveCallback(Object context) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /root/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 652
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext() in /root/corefx/src/System.Net.WebProxy/tests/WebProxyTest.cs:line 146
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /root/corefx/src/System.Linq/src/System/Linq/Select.cs:line 133
~~~

So adding "test-run-core" label.

**Comment by danmosemsft** [comment] 2017-03-31 21:23
The run above obviously did not have gcstress applied.

**Comment by stephentoub** [comment] 2017-04-05 18:59
https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/3010/consoleText

**Comment by karelz** [comment] 2017-04-06 09:23
@steveharter did you see the failure in your runs? Looks like it reprod 2x in week.

**Comment by steveharter** [comment] 2017-04-17 16:32
I can repro this locally on Ubuntu16, apparently started failing recently. Will attempt a new run with latest code and report results.

Last jdash occurrence on 4/6 however so looking at whether jdash data is missing, or issue was addressed a few days ago.

**Comment by steveharter** [comment] 2017-04-17 22:17
I was able to repro locally on Ubuntu14 and 16 but it appears my repro was due to #13464 and not "no such device or address"
```
System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected(destination: http://127.0.1.1/, isLocal: True) [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
```

**Comment by karelz** [comment] 2017-04-19 00:06
@steveharter given the low frequency, should we push it out to Future?

**Comment by steveharter** [comment] 2017-04-19 17:49
Yes I think Future is appropriate here. With the exception of 2 failures that occurred in a different branch, the failures only occurred from 4/4-4/6 and there were 19 of them indicating some infrastructure issue other other issue that was fixed.

**Comment by karelz** [comment] 2017-04-19 17:52
That sounds more like "Let's Close it". 4/4-4/6 seems like temporary hiccup.
Do we have any indication that this is real problem in our CI? Shouldn't we just wait for another occurrence? (just thinking aloud, feel free to push back)

**Comment by steveharter** [comment] 2017-04-19 18:53
Changing to close; if it occurs again, let's change it to future.

**Closed by steveharter** 2017-04-19 18:53 UTC
Labels: area-System.Net, os-linux, tenet-reliability, test-run-core
