### ISSUE TITLE
Building individual projects fails

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#5367] opened 2016-01-13 09:54 UTC
PR #5310 introduced a new tools directory, which is built _if_ you run one of the base "build" commands (ie `Build.cmd`).  This is potentially the first time this has been a **required** step; before, clean builds from VisualStudio on a single project worked.
If instead a committer has been working on single projects, and building just that project (via either the command line or VisualStudio), building now fails with an only indirectly-helpful error:
>C:\Users\xande\repositories\corefx\src\System.Threading.Tasks\src\System.Threading.Tasks.csproj : error  : The imported project "C:\Users\xande\repositories\corefx\Tools\Build.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\xande\repositories\corefx\dir.props

>C:\Users\xande\repositories\corefx\src\System.Threading.Tasks\tests\System.Threading.Tasks.Tests.csproj : error  : The imported project "C:\Users\xande\repositories\corefx\Tools\Build.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\xande\repositories\corefx\dir.props

**Comment by Clockwork-Muse** [comment] 2016-01-13 09:56
(Well, presumably it'll work after building - it hasn't finished grabbing stuff for me.  I keep getting 504 Gateway Timeouts, although it appears to be making _some_ progress).

**Comment by stephentoub** [comment] 2016-01-13 16:43
https://github.com/dotnet/corefx/issues/5332

**Comment by weshaggard** [comment] 2016-01-13 17:07
Yes this is a duplicate of #5332, you need to at least call init-tools.cmd to bootstrap the tools before you can load in VS or build individual projects.

@joperezr we need to get this documented soon so we can point folks to it.

**Closed by weshaggard** 2016-01-13 17:07 UTC
