### ISSUE TITLE
QuaternionCreateFromYawPitchRollTest2 failed in CI on OSX

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9409] opened 2016-06-14 11:13 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_release/72/consoleText
```
System.Numerics.Tests.QuaternionTests.QuaternionCreateFromYawPitchRollTest2 [FAIL]
        Yaw:-545 Pitch:155 Roll:365
        Expected: True
        Actual:   False
```
cc: @mellinoe, @RussKeldorph

**Comment by karelz** [comment] 2016-09-26 21:54
Looks like dupe of #4833.

**Closed by karelz** 2016-09-26 21:54 UTC
Labels: area-System.Numerics
