### ISSUE TITLE
Investigate failling test in CLI insertion

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#27588] opened 2018-03-01 01:54 UTC
https://github.com/dotnet/cli/pull/8689 insertion cause a test `GivenAnInstalledPackageUninstallRollsbackWhenTransactionAborts` fails constantly in REHL 7 Jenkins machine. However, when the test is renamed, the problem is gone. There is no local repo. Also after change test directory, a [similar error](https://ci.dot.net/job/dotnet_cli/job/master/job/release_windows_nt_x64_prtest/2384/testReport/(root)/(empty)/Microsoft_DotNet_ToolPackage_Tests_ToolPackageInstallerTests_GivenAnInstalledPackageUninstallRemovesThePackageWhenTransactionCommits_testMockBehaviorIsInSync__True_/) happened at a different part of the code. This time it is on Windows. But there is still no local repo.

Both tests has Directory Enumerator involved. Consider there is change in that area. I believe we need to find the root cause of the issue.

**Comment by karelz** [comment] 2018-03-01 03:04
@JeremyKuhne I think you did changes in the space recently - maybe a regression?

**Comment by JeremyKuhne** [comment] 2018-03-01 04:34
> I think you did changes in the space recently - maybe a regression?

I don't see anything in the linked details that looks like an IO bug (either Path or file enumeration).

**Comment by peterhuene** [comment] 2018-03-01 05:30
@wli3 That Windows failure makes me think there's a race condition in the product or test that's the underlying issue; that Windows failure is when it is using a mock, in-memory "file system".  It does seem to reproduce more consistently on RHEL for some reason.  Really odd about the test name change; perhaps it's affecting the test run ordering and preventing a concurrent run with an interfering test?

I think it may be premature to consider this is a corefx issue until we can track down the underlying cause.

**Comment by peterhuene** [comment] 2018-03-01 05:36
See https://github.com/dotnet/cli/pull/8689#issuecomment-369335953 I think that's worth addressing first.

**Comment by danmosemsft** [comment] 2018-03-01 06:47
Thanks @peterhuene . Please let us know if better evidence emerges of a BCL bug.

**Comment by karelz** [comment] 2018-03-01 07:08
BTW: I thought it is IO related based on this:

> Both tests has Directory Enumerator involved

I might be wrong of course ...

**Comment by karelz** [comment] 2018-03-01 16:55
OK, so it is not clear if there is any .NET Core bug at this moment. Closing.

**Closed by karelz** 2018-03-01 16:55 UTC
Labels: area-System.IO, bug
