### ISSUE TITLE
System.Numerics.BigInteger causes StackOverflowException on calculating an arbitrarily large number #1731 

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/corefx#13588] opened 2016-11-11 17:36 UTC
Hi,

whilst experimenting with F# @arshbunny found an issue with System.Numerics .Biginteger.  Here is a link to his issue:

https://github.com/Microsoft/visualfsharp/issues/1731#issuecomment-259840351

We don't believe this is issue due to F#  but because of a bug in System.Numerics.BigInteger.  Please take a look at it.

Thank you 

Kevin

![Screenshot](http://archive.org/download/Fsharp-StackOverflowException/fsi.png)

The code first defines a custom power function, then tetration function based on it and then two operators so I don't have to type 'I' next to every number I want to work with and hide the superfluous BigInteger members from the console.
It worked fine for 3rd tetration of 4 [4 ^ (4 ^ 4) = 4 ^ 256] and returned over 150 digits, but something went wrong on calculating the 5th tetration of 2, which is supposed to be almost 20,000 digits, btw; the program crashes before bigint value gets close to what float can handle (~310 digits), let alone 20,000 digits. What am I missing?
````
let rec exponentiation (x:bigint) (y:bigint) : bigint =
    match y with
    | y when y.IsZero -> 1I
    | y when y.IsOne -> x
    | y -> x * exponentiation x (y-1I)
let rec tetration (x:bigint) (y:bigint) : bigint =  
    match y with
    | y when y.IsZero -> 1I
    | y when y.IsOne -> x
    | y -> exponentiation x (tetration x (y-1I))
let (^) (x:int) (y:int) = System.Console.WriteLine (exponentiation (bigint x) (bigint y))
let (^^) (x:int) (y:int) = System.Console.WriteLine (tetration (bigint x) (bigint y))
````
I've been dabbling with F# lately, it's the only programming language I am familiar with. I know an unhelpful smattering of JavaScript, and remember a couple of keywords from C# that I tried years ago for a few days on Unity (yeah, absolutely no .NET knowledge)
````
Windows 10 for Education x64
.NET Framework 4.5.1
Visual F# 4.0
Visual Studio Code 1.7 with Ionide suite of extensions
````

**Comment by svick** [comment] 2016-11-11 17:39
This looks like a duplicate of https://github.com/dotnet/corefx/issues/13568.

**Comment by stephentoub** [comment] 2016-11-11 17:53
Dup of https://github.com/dotnet/corefx/issues/13568

**Closed by stephentoub** 2016-11-11 17:53 UTC
