### ISSUE TITLE
Add way to receive RemoteEndPoint from TcpClient

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/corefx#8380] opened 2016-05-08 02:42 UTC
I'm working on porting one of my networking libraries to .NET Core, and some of the changes made to sockets and TcpClient have made some information impossible to get. I was using a derived version of NetworkStream, however with the removal of the Client property, I could not create that anymore. I can work without that, but with neither NetworkStream or TcpClient providing the RemoteEndPoint of the socket, I cannot receive the remote address or remote port of the client. In addition, because of the removal of Async methods from Socket, I can't use raw sockets either. Any chance a way to get RemoteEndPoint data from a TcpClient or NetworkStream, a way to get the raw Socket again from TcpClient, or Task based async methods on raw Sockets?

**Comment by davidsh** [comment] 2016-05-08 03:46
cc: @CIPop @himadrisarkar

**Comment by CIPop** [comment] 2016-05-09 21:20
@ThadHouse Thanks for reporting this. As far as I can tell, this is a duplicate of #6107.

> In addition, because of the removal of Async methods from Socket, I can't use raw sockets either.

None of the Async methods should have been removed from Socket. Can you please add an example of method that you're missing? We've actually added new Task-based (await/async) new methods to Socket.

**Closed by CIPop** 2016-05-09 21:20 UTC
Labels: enhancement, System.Net

**Comment by ThadHouse** [comment] 2016-05-09 21:35
I was previously using BeginConnect and EndConnect to provide timeout functionality during a socket connect. Those methods have been marked as internal, so they cannot be used anymore. Also, in Master, System.Net.Sockets does not have any Task async methods added. Are those in another branch? Also, would those async methods be backported to the old .NET Framework? Without those being added, or Begin and EndConnect being remade public, it will not be possible to make a PCL of my library.

**Comment by CIPop** [comment] 2016-05-09 23:03
@ThadHouse The Begin/End methods have just been added back to the contracts: see #8378. 

The Task based APIs should be available in the latest builds and in the master branch: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/ref/System.Net.Sockets.cs#L392
If your application is using CoreFX and targetting .Net Desktop within project.json you should also be able to reference the Task-based APIs.
Please let us know if that is not working.

We are considering making the Task-based implementation available in .Net Desktop as well.

**Comment by CIPop** [comment] 2016-05-09 23:09
Marked #3895 accordingly.

**Comment by ThadHouse** [comment] 2016-05-09 23:14
Those are the Begin and End methods for streams. Is there a separate PR for the Socket BeginConnect and EndConnect methods?

**Comment by CIPop** [comment] 2016-05-09 23:24
@ThadHouse You're right. See the comments from the same PR: The answer was that all Begin/End APIs will be added back.
I don't think that PR is out yet.
