### ISSUE TITLE
Date formatting discrepancy between Windows and Linux

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#3974] opened 2015-10-19 20:36 UTC
Code:

    CultureInfo.CurrentCulture = new CultureInfo("en-GB");
    sb.AppendFormat(CultureInfo.CurrentCulture, "{0:D}", DateTime.Parse("01/02/2015"));
    Console.WriteLine(sb.ToString());

Windows:

    01 February 2015

Linux:

    Sunday, 1 February 2015

**Comment by akoeplinger** [comment] 2015-10-19 21:10
Likely by design, see https://github.com/dotnet/coreclr/issues/1734 for some background info.

**Comment by muratg** [comment] 2015-10-19 21:35
@cesarbs Windows output is with CoreCLR right?

@akoeplinger Shouldn't the outputs be identical by design?

**Comment by akoeplinger** [comment] 2015-10-19 21:38
@muratg Quoting from https://github.com/dotnet/coreclr/issues/1734#issuecomment-146918606
> In short, until Windows and CLDR are in 100% agreement, there will always be differences between the culture data on Windows and Linux. Which means if you are dependent on this data (like your tests are), then you will have to switch depending on what platform you are running on.

**Comment by muratg** [comment] 2015-10-19 21:41
@akoeplinger how about apps depending on this data? (I know it's bad design to depend on datetime string, but people may still do it.)  For now, we can fiddle with our tests, but over the long term, I think this is bad for customers.

**Comment by akoeplinger** [comment] 2015-10-19 21:46
@muratg I fully agree with you (identical outputs would be great), but I'm just the messenger here :)

/cc @eerhardt @ellismg @tarekgh

**Comment by tarekgh** [comment] 2015-10-19 21:59
@muratg 

> how about apps depending on this data? (I know it's bad design to depend on datetime string, but people may still do it.) For now, we can fiddle with our tests, but over the long term, I think this is bad for customers.

Actually it is better to not having the app take dependency (or assume any) data. this will cause the app to break sooner or later if the data changed for any reason. 
The best practice for apps is use their own pattern if they need consistency. if they want guarantee parsing , they should use the Invariant culture (or the Iso date/time pattern).

**Comment by muratg** [comment] 2015-10-19 22:22
Agreed, though people will still hit these type of issues. I would prefer we fix the issues we know of if it's not too much effort.

**Comment by tarekgh** [comment] 2015-10-19 22:33
what we'll do if the data changed again? the app will be broken and the app will assume the problem is in the framework and not really the app itself.
It is better to have people write their app with the best practices. even when hitting this issue, they will get to understand the issue and fix their app. 
believe me when the app take decency on the data they will break sooner or later regardless.

**Comment by ellismg** [comment] 2015-10-19 22:45
@muratg The logical conclusion for "fix these issues" is CoreCLR ships a complete set of culture data to every platform that we control and version.  This is something we specifically *DO NOT* want to do.  This will lead to CoreCLR applications not behaving like the target platform and will force us to ship out revisions when culture data changes[0].

This would also create a difference between CoreCLR and Full .NET Framework on any recent Windows operating system, which uses the OS provided locale data.

We've been transitioning to using OS provided data in the CLR since Windows Vista.  Since Windows 7 we've picked up this sort of formatting data from the OS and culture data has changed every major windows release since then.  If you need formating data that doesn't change use Invariant.  If you aren't using Invariant then we assume you are trying to format the data for an end user and we do the best to match whatever the platform we are running on thinks that means.  

--
[0]: This happens much more often than you would think.  One fun case is when a locale adopts a new currency symbol.  Now the built in data is "wrong" and applications which format a string to display to the user will do the wrong thing.  This has happened multiple times over the last few years and it's always a pain for full .NET because in addition to patching Windows itself, you had to obtain a patch for .NET.

**Comment by cesarbs** [comment] 2015-10-19 23:02
@muratg Yes, Windows output is on CoreCLR.

**Comment by muratg** [comment] 2015-10-19 23:10
@ellismg Thanks for the explanation, this totally makes sense now.  "Fixing it" wouldn't only be a big upfront effort, but also will need ongoing costly maintenance.  I think this bug is good to close.

@cesarbs We should fix the test case and just expect different results on the OS.

**Comment by ellismg** [comment] 2015-10-19 23:12
@cesarbs @muratg I took a quick look at the test and it may make more sense to just set CurrentCulture to Invariant (the string name for this is "" (the empty string)).  That would let you test the "goes down the current culture code path" but also give you a invariant data which should not change.

**Comment by joshfree** [comment] 2015-10-20 04:09
Closing as by design.  Note that the OS culture data can be different not only Linux vs Mac vs Windows but also between different versions of Windows (7 vs 8 vs 10).

**Closed by joshfree** 2015-10-20 04:09 UTC

**Comment by muratg** [comment] 2015-10-20 05:34
@ellismg :+1:, thanks again!
