### ISSUE TITLE
Executing console application with a file share as working directory fails with ConfigurationErrorsException

### ISSUE THREAD

**Issue by asbjornu** [dotnet/corefx#12581] opened 2016-10-12 08:58 UTC
As reported in https://github.com/dotnet/roslyn-project-system/issues/206#issuecomment-252869071, I've encountered a problem related to working with file shares and .NET: When running a console application in an unelevated `cmd.exe` with a file share (mapped drive) as its working directory, the application blows up with the following exception:

``` c#
System.Configuration.ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section. ---> System.Net.Sockets.SocketException: An invalid argument was supplied
   at System.Net.SafeCloseSocketAndEvent.CreateWSASocketWithEvent(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType, Boolean autoReset, Boolean signaled)
   at System.Net.NetworkAddressChangePolled..ctor()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.get_CurrentAutoDetector()
   at System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   at System.Net.WebProxy.UnsafeUpdateFromRegistry()
   at System.Net.WebProxy..ctor(Boolean enableAutoproxy)
   at System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- End of inner exception stack trace ---
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
   at System.Net.HttpWebRequest..ctor(Uri uri, Boolean returnResponseOnFailureStatusCode, String connectionGroupName, Action`1 resendRequestContent)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pomona.Common.RequestDispatcher.<SendHttpRequestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pomona.Common.RequestDispatcher.<SendRequestInnerAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Pomona.Common.RequestDispatcher.<SendRequestAsync>d__12.MoveNext()
```

An HTTP request is being made by the console application, which seemingly requires loading of proxy settings, which for some reason are out of reach from an application run with unelevated privileges **with a file share as the working directory**.

If I change the working directory with `cd /d C:\Windows` before exeucting the console application, it works. It also works if I open up a `cmd.exe` with administrative privileges. It also works if I run the console application directly from an elevated Visual Studio instance. But the combination of unelevated `cmd.exe` and a file share as a working directory, makes the application fail with the above exception.

As I write in dotnet/roslyn-project-system#206, I've run `caspol` to grant full permissions to both `Y:\*` and `file://Mac/*`, but it still fails.

**Comment by karelz** [comment] 2016-10-12 16:11
Can you provide a minimal repro?
It would help greatly if you can debug the root cause and identify which part of code doesn't handle the situation well.

**Comment by stephentoub** [comment] 2016-10-12 16:14
> It would help greatly if you can debug the root cause and identify which part of code doesn't handle the situation well.

@karelz, it sounds like this is in desktop, not corefx.

**Comment by karelz** [comment] 2016-10-12 16:47
@asbjornu is it on full .NET Framework? If yes, there is not much we can do here in CoreFX ...

**Comment by asbjornu** [comment] 2016-10-12 17:13
@karelz: I reported it here because @davkean asked me to do it in https://github.com/dotnet/roslyn-project-system/issues/206#issuecomment-252981596. This is full .NET framework, version 4.5.2. I can of course try upgrading to .NET Core and see if that improves anything. Will it work flawlessly to have mixed 4.5.2 and .NET Core projects in the same solution?

**Comment by karelz** [comment] 2016-10-17 16:42
You can always try .NET Core. If you have small repro, it should be simple. I don't know what the result will be, but in .NET Core we can try to fix it.

You can file full .NET Framework bug on Microsoft Connect (via official Microsoft Support channel), but it won't get much attention unless it has significant impact without reasonable workaround on significant number of customers (just setting the expectations).
From your description it seems there is a reasonable workaround for full .NET Framework (use local working directory, not a file share).

**Comment by asbjornu** [comment] 2016-10-19 17:37
@karelz: I will try to reproduce this in .NET Core. My question then still applies:

> Will it work flawlessly to have mixed 4.5.2 and .NET Core projects in the same solution?

Also, how do I upgrade a project from 4.5.2 to .NET Core?

> You can file full .NET Framework bug on Microsoft Connect (via official Microsoft Support channel), but it won't get much attention unless it has significant impact without reasonable workaround on significant number of customers (just setting the expectations).

Thanks for the pointer, but my impression is that spending any amount of time on Microsoft Connect is a waste.

> From your description it seems there is a reasonable workaround for full .NET Framework (use local working directory, not a file share).

While I violently disagree that the workaround is reasonable, I understand that this is one way to reason about it.

**Comment by karelz** [comment] 2016-10-19 19:15
> Also, how do I upgrade a project from 4.5.2 to .NET Core?

You can try to flip the VS target framework from to .NET Core 1.0 / 1.1 preview. You may find out that it is missing bunch of APIs your project uses (we are bringing lots of them back in next version 1.2.0). If you hit that, the other best option is to create a small isolated repro and then migrate just that.
@weshaggard do we have any .NET Core migration guide docs?

> Thanks for the pointer, but my impression is that spending any amount of time on Microsoft Connect is a waste.

At the end of the day it is going to come to the same team (incl. myself). Sadly, Connect is not the best tool for back-and-forth. Also the quality of reports is typically pretty low (no repros, or large involved repros, or problems in customer code).

> While I violently disagree that the workaround is reasonable, I understand that this is one way to reason about it.

Totally understood -- whenever I hit an issue myself, it is the center of my life as well.
The other angle is that the problem is there probably forever (10+ years) and this is likely the first (or one of a few) reports we got. So even strictly from customer impact point of view, it doesn't meet the bar. Especially in a product with high compatibility expectations like full .NET Framework. Even if we knew exactly what to fix and even if it would be a super-simple 1-character/1-line change, there is always 10% risk that it will have unanticipated consequences and it will break someone. The 10% risk is just not worth it unless the benefit is high.
We do not have the same problem in .NET Core with taking changes -- it is a product where we do not have such high compat bar, because the product is not force-updated to apps machine-wide (it is app opt-in upgrade), and because the product is agile and can ship fixes more quickly based on feedback.

**Comment by karelz** [comment] 2016-11-07 21:00
@weshaggard ping?

**Comment by weshaggard** [comment] 2016-11-08 23:34
We don't really have a guide, the closest would be https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/ which talks about the APIs available and about out to use apiport.

With that said I don't think the answer for this particular issue is to port code from .NET 4.5.1 to .NET Core as this is an issue on .NET that we should independently look into.

**Comment by tarekgh** [comment] 2017-03-02 18:56
considering this issue is a desktop issue and having a working around, I am closing the issue here. Still can file issue on connect if need to address the issue in the full framework. feel free to reopen the issue if you disagree. thanks.

**Closed by tarekgh** 2017-03-02 18:56 UTC
Labels: area-Meta, bug, needs more info
