### ISSUE TITLE
TargetInvocationException System.Text.Json.Serialization

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#37522] opened 2019-05-08 18:59 UTC
Don't have a repro yet but this threw an exception during serialization.
Running on 3.0.100-preview5

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
   at System.Text.Json.Serialization.JsonPropertyInfoCommon`3..ctor(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type elementType, JsonSerializerOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Text.Json.Serialization.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.Serialization.JsonSerializer.GetRuntimeClassInfo(Object value, JsonClassInfo& jsonClassInfo, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.HandleObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.Write(Utf8JsonWriter writer, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteAsyncCore(Object value, Type type, Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by vcsjones** [comment] 2019-05-08 19:55
Usually this happens when you try to serialize a type that is not supported yet, such as a struct. Is one of the types in the object graph a struct or a Guid?

**Comment by NinoFloris** [comment] 2019-05-08 20:26
It may actually be our usage of Dictionary (would be amazing if the error actually had the offending type in there...) which only got merged 12 days ago, it just missed preview5, bummer. https://github.com/dotnet/corefx/pull/37186

**Comment by ahsonkhan** [comment] 2019-05-09 13:06
> It may actually be our usage of Dictionary

Can you please re-try with a recent nightly build and see if you are still hitting this issue?

**Comment by vcsjones** [comment] 2019-05-09 13:42
@ahsonkhan are there any plans to improve the error output for unsupported types during serialization rather than a fairly esoteric error around delegate type mismatches? If so, is there an issue tracking that?

**Comment by ahsonkhan** [comment] 2019-05-09 13:57
This was brought up here as well: https://github.com/dotnet/corefx/issues/37537#issuecomment-490904530

> are there any plans to improve the error output for unsupported types during serialization rather than a fairly esoteric error around delegate type mismatches?

Since the serializer APIs are fairly new, we do expect a few unsupported cases to be hit. We should definitely work to improve the error messaging for such scenarios, and we do plan to document what isn't supported for the current release. @steveharter, it would be good to enumerate and document all the common cases we know won't work which would be part of the backlog for vNext.

> If so, is there an issue tracking that?

I don't think there is one specific to error messaging. I would appreciate it if you could file an issue for it. That might also provide a centralize issue to log the "unsupported" cases to help with search-ability while we work on docs/better exceptions.

**Comment by ahsonkhan** [comment] 2019-05-09 14:23
> @steveharter, it would be good to enumerate and document all the common cases we know won't work which would be part of the backlog for vNext.

@layomia, this might be something you could help with as part of the effort to improve testing and reliability.

**Comment by steveharter** [comment] 2019-05-09 15:00
Since we are actively fill feature gaps, yes there are some exceptions that are being leaked. Fields, dictionaries and collections are the main areas that are not yet hardened. We are working on throwing the appropriate exceptions there, porting tests from Json.Net, and fuzz-testing approaches for bad JSON.

**Comment by GSPP** [comment] 2019-05-12 12:31
> Since the serializer APIs are fairly new, we do expect a few unsupported cases to be hit. 

If the first version ships with bad errors there is a risk that these bad errors cannot be fixed for compatibility reasons. Likely we need to get this right in v1.

**Comment by danmosemsft** [comment] 2019-05-12 21:21
@GSPP 

> If the first version ships with bad errors there is a risk that these bad errors cannot be fixed for compatibility reasons

Possibly, but we have more freedom than before of course as.NET Core installs SxS and without roll forward

**Comment by layomia** [comment] 2019-05-18 00:02
> @layomia, this might be something you could help with as part of the effort to improve testing and reliability.

Yes, I'll document these cases as part of our testing and reliability effort. cc @buyaa-n

**Comment by MarcoRossignoli** [comment] 2019-05-30 13:03
> Yes, I'll document these cases as part of our testing 

@layomia is there some doc in some branch ready to check? I was working on throw better exception but I'm not sure what is or not supported yet.

**Comment by ahsonkhan** [comment] 2019-05-30 18:49
> is there some doc in some branch ready to check? I was working on throw better exception but I'm not sure what is or not supported yet.

I am working on writing up such a doc and hoping to get it checked in by eod tomorrow. Hopefully, that will help.

**Comment by ahsonkhan** [comment] 2019-06-11 21:25
@NinoFloris, is this issue still reproducible with the latest build (https://github.com/dotnet/core-setup#daily-builds)?

If so, please feel free to re-open and provide additional info on how to reproduce it.

**Closed by ahsonkhan** 2019-06-11 21:25 UTC
Labels: area-System.Text.Json
