### ISSUE TITLE
Add System.Xml.Xsl

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#5593] opened 2016-01-21 20:05 UTC
.NET Core currently doesn't support running XML transforms (XSLT).

**Comment by kwaazaar** [comment] 2016-02-18 07:45
Yes please! I use it a lot to manipulatie OOXML documents (Word). It's much faster than linq to XML. As the OOXML SDK may be ported as well somewhere in the future, my current solution (www.docati.com) requires XslTransform as well.

**Comment by danmosemsft** [comment] 2016-03-04 15:30
Dupe of #2189?

**Comment by SariDev** [comment] 2016-03-24 08:44
I would like to see a port.

Maybe you could even improve it by adding support for XSLT 2.0 or maybe even XSLT 3.0+.
Right now the .NET Framework only supports XSLT 1.0 as far as I know.
XSLT 2.0+ makes it easier to transform non xml (text) files as it offers new xslt functions like unparsed-text() and others.

**Comment by danmosemsft** [comment] 2016-08-24 21:43
This is now in the dev/api branch, so the work is largely done but it's not yet shipped.

**Comment by danmosemsft** [comment] 2016-08-24 21:44
In src\System.Private.Xml\src\System\Xml\Xslt. I"ll leave this open until it's in master.

**Comment by jasongaylord** [comment] 2016-08-25 17:43
Any timeframe for that Dan?

**Comment by jasonwilliams200OK** [comment] 2016-08-26 21:59
@danmosemsft, I get:

error CS0234: The type or namespace name 'Xsl' does not exist in the namespace 'System.Xml'

with `"System.Private.Xml": "4.0.0-*",` when I compile `using System.Xml.Xsl` and `using System.Xml.Xsl.Xslt`.

Is it added to the contract and is it possible to consume it from our our code using dev/api assemblies? 

Note that I have added `<add key="myget.org dotnet-core-dev-api" value="https://dotnet.myget.org/F/dotnet-core-dev-api/api/v3/index.json" />` to my NuGet.config temporarily to consume it.

**Comment by danmosemsft** [comment] 2016-08-26 22:08
@ericstj What's the magic necessary here?

**Comment by danmosemsft** [comment] 2016-09-18 20:58
This is now in master.

**Comment by bradwilson** [comment] 2016-09-18 21:16
Do you have a target version and/date for this?

**Comment by danmosemsft** [comment] 2016-09-18 22:15
@terrajobst are there dates you can share about 1.2/ 1.2 preview?

Note I don't think there are ref assemblies in the meta package yet, so you can't reference it. I've asked @weshaggard what the best way is to get you trying it out.

**Comment by tmsns** [comment] 2016-09-19 10:54
Is it already certain System.Xml.Xsl will be added to .NET Core 1.2?

Also, just wondering @danmosemsft , why was the assembly named System.Private.Xml? Why the private moniker?

**Comment by danmosemsft** [comment] 2016-09-19 23:30
It doesn't have a reference assembly yet. @sepidehMS is working on that (needs issue)

**Comment by sepidehMS** [comment] 2016-09-20 00:05
Here's the related issue: https://github.com/dotnet/corefx/issues/11888

**Comment by brendansaunders** [comment] 2016-09-20 10:31
I am a little confused as i was refered here from issue  #977... Will this support / allow us to get our xUnit test results in the NUnit xml format?

**Comment by mstruppBE** [comment] 2016-09-20 13:18
Is it possible to use the XSLT code that has already been posted, or is that not ready for primetime?

**Comment by bradwilson** [comment] 2016-09-20 15:21
@brendansaunders The xUnit.net runners need this code to perform the transformations that enable support for NUnit XML. You don't need this code yourself; I do. 🙂

**Comment by sepidehMS** [comment] 2016-09-20 16:52
@mstruppBE There is no ref assembly for it yet, but you can technically use it. Please refer to [here](https://github.com/dotnet/corefx/tree/master/src/System.Private.Xml/tests) to see how our tests are currently doing that.

**Comment by mstruppBE** [comment] 2016-09-21 15:13
@sepidehMS Thanks.  I will wait for the ref assembly. We have some projects which utilize XSLT that we're porting to Net Core that I am hoping to test soon.

**Comment by mstruppBE** [comment] 2016-10-05 13:52
@sepidehMS Just checking in here - is the ref assembly yet available for testing XSLT functionality in Net Core?  Thanks!

**Comment by sepidehMS** [comment] 2016-10-07 16:27
@mstruppBE The XSLT functionality is now available in System.Xml.ReaderWriter assembly. Closing this for now.

**Closed by sepidehMS** 2016-10-07 16:27 UTC
Labels: area-System.Xml, port-to-core

**Comment by Tandis5** [comment] 2016-10-07 17:40
@sepidehMS So I'm new to Net Core and Github, but I'm doing a project with Net Core and need the XSLT functionality.  How do I get this latest version with the XSLT functionality?  I downloaded System.Xml.ReaderWriter from NuGet (version 4.0.11) but it doesn't not have the XSL classes.

**Comment by mstruppBE** [comment] 2016-10-07 20:25
@Tandis5 I downloaded the "System.Xml.ReaderWriter": "4.4.0-beta-24607-05 version from myGet (which was last updated today) and it also doesn't have XSL classes. I'm pretty sure I'm missing something here.

**Comment by sepidehMS** [comment] 2016-10-07 20:47
@Tandis5 @mstruppBE Can you tell me how you are looking for XSL classes? I am seeing the namespace System.Xml.Xsl included in netstandard1.7 dll in the latest package (the same version @mstruppBE mentioned)

**Comment by mstruppBE** [comment] 2016-10-07 20:50
@sepidehMS Thank you for your response.  I created a Net Core C# console application, installed the System.Xml.ReaderWriter package I referenced above and then tried to instantiate System.Xml.Xsl classes but nothing happened.  That's all I did, so I may be missing a step or two.

**Comment by Tandis5** [comment] 2016-10-07 23:00
@sepidehMS Mine is an ASP.net core web service...  started with an empty project and downloaded System.Xml.ReaderWriter (version 4.0.11) from NuGet.  I've never used myGet before.  Where can I find it on there?  I tried searching for a bit but was unsuccessful.

**Comment by Tandis5** [comment] 2016-10-07 23:51
@sepidehMS @mstruppBE Ok I got the 4.4.0 beta version from myGet, but I'm still having the same issue.  I'm assuming it has something to do with it referencing the wrong library under the package.  I changed my project.json to have "netstandard1.7" as a framework import, but that didn't change anything.  If I browse to the System.Xml.ReaderWriter in the references it appears as if that library is empty.  If I right-click on the reference and choose "scope to this" I get an empty window.

**Comment by weshaggard** [comment] 2016-10-08 06:24
@Tandis5 what do you mean by adding "netstandard1.7" as a framework import? Can you show a snippet of your project.json? I believe you will actually need to change your framework to "netstandard1.7" and not import it.

**Comment by Tandis5** [comment] 2016-10-09 00:09
@weshaggard So I'm confused by the whole .net core vs .net standard and how this project.json works.  After reading some I realize now that what I was doing was wrong.  Are you saying I need to remove "netcoreapp1.0" from my "frameworks" node in the project.json and replace it with "netstandard1.7"?  When I try that I get an error during package restore that says "Microsoft.NETCORE.App 1.0.1 is not compatible with netstandard1.7".

**Comment by weshaggard** [comment] 2016-10-11 04:41
@Tandis5 yes netstandard1.7 isn't compatible with netcoreapp1.0/Microsoft.NETCore.App1.0.1. Unfortunately we are in the middle of a large set of changes in our master branch right now which isn't going to be easily consumed in isolation. I suspect it would require a update of all the packages as well as the tools because an updated nuget(dotnet restore) is needed to understand the new target frameworks. These XML changes are definitely not in a place to be incrementally consumed with existing applications but if you are interested expermenting I can try and help you get through all the various updates. Otherwise I would suggest you hold off until our 1.2 release which is coming out next spring sometime.

**Comment by Tandis5** [comment] 2016-10-11 10:12
@weshaggard Thanks for the response.  I'm going to take a different route and avoid using XSLT for now.

**Comment by agray** [comment] 2017-01-11 01:10
REALLY need XUnit to emit nunit3 XML. new tools now take nunit 3 xml as input.  Have also raised this ticket: https://issues.jenkins-ci.org/browse/JENKINS-27906 to Critical as it is increasingly redonkulous that Jenkins STILL doesn't handle NUnit 3 XML AFAICS.

**Comment by grahamehorner** [comment] 2017-01-11 13:01
@weshaggard I'm having the same issue; I can't see the Xsl namespace using the following project.json

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "System.Xml.ReaderWriter": "4.3.0",
    "System.Xml.XmlDocument": "4.3.0",
    "System.Xml.XPath": "4.3.0"
  },

  "frameworks": {
    "netstandard1.7": {
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by weshaggard** [comment] 2017-01-11 16:55
Have a look at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md for instructions on how to use our latest packages.

**Comment by eerohele** [comment] 2017-02-22 07:17
Looks like the `<msxsl:script>` element isn't supported at the moment. If you try to use it, you get `System.PlatformNotSupportedException: Compiling JScript/CSharp scripts is not supported`.

Will .NET Core ever get `<msxsl:script>` support?

**Comment by danmosemsft** [comment] 2017-02-24 00:54
We don't have plans to support it right now. As you know it requires out of proc compilation, at least as currently implemented and we don't have that. When we looked at it, it wasn't super commonly encountered. We can use this issue to gauge importance of it. Thumbs up or whatever.

**Comment by Jonathan34** [comment] 2017-03-17 20:06
So this is part of the .net standard 1.7 and will be integrated into .Net Core 2.0?
i am currently trying to migrate a .net framework 451 dll to .net standard 1.6 and it heavily uses xslt...

**Comment by danmosemsft** [comment] 2017-03-17 20:39
@Jonathan34 yes `System.Xml.Xsl` is part of .NET Standard 2.0 and will ship in .NET Core 2.0.  (Just not support for `<msxsl:script>`.)

Do you want to try it out? Here are instructions for using .NET Core 2.0 nightly builds in VS 2017.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md
If you hit any problems please do post back.

**Comment by Jonathan34** [comment] 2017-03-17 20:44
@danmosemsft thanks. What i thought. can we use a .Net standard 2.0 assembly in an asp.Net core 1.1 (mvc)?

**Comment by danmosemsft** [comment] 2017-03-17 20:47
If it runs on .NET Core 2.0. I don't know how to do that upgrade (but obviously it's supported!). @davidfowl where is the "dogfooding guide for ASP.NET Core 2.0"?

**Comment by Jonathan34** [comment] 2017-03-17 20:52
Well the dll will use .Net standard 2.0 but my app will rely on .Net core 1.1 (until 2.0 is out). We can't use the beta version in prod but we may survive if one dll is in beta....

**Comment by danmosemsft** [comment] 2017-03-17 20:55
The assembly must run on .NET Core 2.0 runtime.

**Comment by Jonathan34** [comment] 2017-03-17 21:17
The assembly yes. But what about the ASP.net core app using the 2.0 assembly? Sorry I m trying to see if 1.1 can run a 2.0 assembly or if everything needs to be 2.0.

**Comment by danmosemsft** [comment] 2017-03-17 21:18
Sorry everything from the implementation of XSL downwards needs to be 2.0. Do you use XSL in a limited way? If so perhaps there is a 3rd party library you could use for XSL meantime.

**Comment by busbina** [comment] 2017-05-16 00:08
@danmosemsft Is there a bug\feature started for <msxsl:script> support?

**Comment by krwq** [comment] 2017-05-16 00:14
cc: @sepidehMS

**Comment by sepidehMS** [comment] 2017-05-16 00:48
@busbina Currently there is no plan to add msxsl:script support and it's not being tracked by an issue right now. You could file a bug with your scenario and we will make a decision based on popularity :)

**Comment by busbina** [comment] 2017-05-16 18:47
@sepidehMS Thanks!

**Comment by danmosemsft** [comment] 2017-05-16 20:53
Right, this issue is closed (XSL support in general) but we'd welcome a distinct new issue for msxsl:script.

**Comment by busbina** [comment] 2017-05-22 06:27
@danmosemsft @sepidehMS  I opened an issue for script support a few days ago.
#19837

**Comment by mstaal** [comment] 2019-03-24 19:59
I have made a comment in in #19837 explaining how Microsoft XSLT Extension Objects is (at least in many cases) an alternative to using the <msxsl:script>`-tag. I hope it may help someone!
