### ISSUE TITLE
System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success failed in CI

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#18869] opened 2017-04-24 20:20 UTC
This test has a ~1% failure rate on windows 2008 when running on an offline CI machine repeatedly in a loop, and has recently failed in CI.

In all cases the detail is as follows (including the test arguments of True, "")
```
   System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success(transferEncodingChunked: True, text: \"\") [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
      Stack Trace:
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at System.Net.Tests.HttpRequestStreamTests.<Read_FullLengthSynchronous_Success>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         ----- Inner Stack Trace -----
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
            at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

```

**Comment by hughbe** [comment] 2017-04-25 02:33
Is this a test bug or product bug? I'm not sure why receiving a chunked empty string should fail intermittently?

**Comment by stephentoub** [comment] 2017-04-28 03:12
Failed again here:
https://github.com/dotnet/corefx/pull/19051

**Comment by steveharter** [comment] 2017-04-28 19:09
Since this failed in CI, moving this from Future to 2.0 until we can triage it

**Comment by davidsh** [comment] 2017-04-28 19:11
Removing milestone until we triage it.

**Comment by karelz** [comment] 2017-04-29 06:55
This might be a sign of product bug. Let's keep it in 2.0 for now. In next Networking triage (Thursday meeting) we should go through all test failures and make final call what is in / out of scope for 2.0.

**Comment by davidsh** [comment] 2017-05-01 20:51
>System.Net.Tests.HttpRequestStreamTests.Read_FullLengthSynchronous_Success(transferEncodingChunked: True, text: \"\") [FAIL]
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response

This error is impossible to diagnose with a dump file or a repro.  We need to understand what the "response" was that is considered "invalid or unrecognized".

**Comment by karelz** [comment] 2017-05-01 20:53
How do we collect that?
We can ask @steveharter to get the repro on his CI machine if we give him the right scripts to capture the right stuff ...

**Comment by davidsh** [comment] 2017-05-01 21:02
There are two ways to collect something.  Server-side (HttpListner-side) tracing or Client-side (HttpClient) tracing.

For example, we would do something like this to record all low-level Windows WinHTTP and WinSock logs via something like this:

```
netsh trace start scenario=InternetClient_dbg capture=yes persistent=yes
<repro>
netsh trace stop
Share nettrace.cab
```

That will collect a huge trace, though, if it takes a long time to repro.

**Comment by karelz** [comment] 2017-05-01 21:47
Is there option for circular buffer?
@steveharter mentioned ~1% failure rate ... so we will need something like that, or stop the tracing between runs. Steve, how difficult would it be to try it in your scripts? At least once to see how big the trace is ...

**Comment by davidsh** [comment] 2017-05-01 21:50
>Is there option for circular buffer?
Yes, the syntax for the "netsh trace start" line would need to change accordingly.  I'm not familiar with the exact parameters you'll need for that but one could look it up and use whatever is appropriate.

**Comment by karelz** [comment] 2017-05-01 22:39
@steveharter can you please spend 1h to see if it is feasible? (please time box it)

**Comment by steveharter** [comment] 2017-05-02 14:53
Sure. Will start asap.

**Comment by davidsh** [comment] 2017-05-02 19:41
I was able to get traces and have WinHTTP team help decode them. 

It turns out the test case that causes the test failure is this:

```c#
        [ConditionalTheory(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotOneCoreUAP))]
        [InlineData(true, "")]
        [InlineData(false, "")]
        [InlineData(true, "Non-Empty")]
        [InlineData(false, "Non-Empty")]
        public async Task Read_FullLengthSynchronous_Success(bool transferEncodingChunked, string text)
        {
```

There seems to be a bug in WinHttpHandler dealing with sending zero-length content using chunked encoding. 

So, this test failure is actually an HttpClient product issue even though these tests themselves are testing HttpListener.

I’ll take a closer look at this.  Perhaps I’ll be able to reproduce the problem using an HttpClient unit test.

**Comment by karelz** [comment] 2017-05-02 19:46
Kudos for tracking it down!

How common is the scenario? How impactful is it on customers? Is it P1 for 2.0?

**Comment by steveharter** [comment] 2017-05-02 22:11
Note that a fix here will also likely fix https://github.com/dotnet/corefx/issues/18376

**Comment by karelz** [comment] 2017-05-02 22:13
Should we dupe the other one against this one then?

**Comment by davidsh** [comment] 2017-05-02 22:36
>Should we dupe the other one against this one then?

You can if you want.  I have a PR going now.  When it is merged, we can close both issues.

**Comment by karelz** [comment] 2017-05-02 22:48
OK, your decision ...

**Closed** 2017-05-03 03:12 UTC
Labels: area-System.Net.Http, bug, os-windows, test-run-core
