### ISSUE TITLE
[Uri] Test hole in System.Private.Uri -> UriHelper.EscapeString

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#16513] opened 2017-02-27 22:31 UTC
There is a test hole where we are not testing the case of when we find an unescaped reserved character and we need to grow the destination `char[]` and copy its current values.

Pointer to this case in the source code: https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/UriHelper.cs#L407-L432

Pointer to a comment on a PR where we found this hole: https://github.com/dotnet/corefx/pull/16456#discussion_r103077889

/cc: @stephentoub

**Comment by danmosemsft** [comment] 2017-02-28 01:53
FWIW according to code coverage at least one test is exercising those lines of code somehow.

**Comment by safern** [comment] 2017-03-01 02:42
I don't know how the current test is exercising those lines of code but it seems we are missing to do more testing there because I tried to do locally what @stephentoub described here: https://github.com/dotnet/corefx/pull/16456#discussion_r103077889 and it failed as he said.

**Comment by stephentoub** [comment] 2019-01-11 16:50
> FWIW according to code coverage at least one test is exercising those lines of code somehow.

The issue isn't just those lines.  It's what happens when those lines execute but then the calling code ends up using the incorrect data.  If, for example, `if(pooledArray.IsSameString(pStr, 0, position))` was true at the call site, then we'll end up returning an incorrect string and returning the already-returned array back to the pool.

That said, the test hole is really only applicable when doing the kind of pooling that was being done in that PR.  Without it, there's not really a hole per se.

So I'm going to close this as it's not particularly actionable, e.g. without making src changes, we couldn't get the new test to fail or easily validate that it was testing what we wanted it to test.

**Closed by stephentoub** 2019-01-11 16:50 UTC
Labels: area-System.Net, test enhancement, up-for-grabs
