### ISSUE TITLE
Respond to PR code review comments for ported library System.Diagnostics.StackTrace

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#5017] opened 2015-12-16 17:36 UTC
@noahfalk as the owner of the System.Diagnostics.StackTrace library can you please have a look through the code review comments provided in https://github.com/dotnet/corefx/pull/4972 and address them appropriately.

**Comment by weshaggard** [comment] 2016-01-08 02:48
Duplicate of https://github.com/dotnet/corefx/issues/4976 which has been resolved.

**Closed by weshaggard** 2016-01-08 02:48 UTC
Labels: System.Diagnostics
