### ISSUE TITLE
[arm32/Linux] System.ServiceModel.Syndication.Tests failures on arm32 linux

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#33875] opened 2018-12-06 19:44 UTC
Running the arm32 tests on linux for System.ServiceModel.Syndication.Tests produced the following results: passed 1108/1211 tests.

Most of the failures are caused by PlatformNotSupportedExceptions so I believe that they should all be skipped when running in linux arm32.

**Comment by danmosemsft** [comment] 2018-12-06 21:07
Is it possible to attach the appropriate testResults.xml to these issues? Then they can get fixed without hardware.

**Comment by joperezr** [comment] 2018-12-06 21:35
[testResults.zip](https://github.com/dotnet/corefx/files/2654991/testResults.zip)

**Comment by yujayee** [comment] 2019-03-19 21:45
Closing as duplicate of #33993

**Closed by yujayee** 2019-03-19 21:45 UTC
Labels: arch-arm32, area-System.ServiceModel.Syndication, os-linux, test-run-core
