### ISSUE TITLE
Package downgrades occur when referencing System.ValueTuple from a .NET Core 1.0 project with a RuntimeIdentifier specified

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefx#15826] opened 2017-02-05 19:36 UTC
- Create a new Console App (.NET Core) project (targeting .NET Core 1.0)
- Add the following property to the .csproj file: `<RuntimeIdentifier>win7-x86</RuntimeIdentifier>`
- Reference System.ValueTuple (version 4.3.0)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.3.0" />
  </ItemGroup>

</Project>
```

- Run NuGet restore (e.g. `dotnet restore` from command line)

**EXPECTED:** No warnings on restore
**ACTUAL:** Lots of package downgrade warnings (57 of them to be specific), such as the following

> 11:29:11.493     1>C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning : Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1 \r [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning :  ValueTupleTest (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.0) -> NETStandard.Library (>= 1.6.0) -> System.Console (>= 4.0.0) -> runtime.win.System.Console (>= 4.3.0) -> System.IO.FileSystem.Primitives (>= 4.3.0) \r [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning :  ValueTupleTest (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.0) -> NETStandard.Library (>= 1.6.0) -> System.IO.FileSystem.Primitives (>= 4.0.1) [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]
11:29:11.493     1>C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning : Detected package downgrade: System.Threading from 4.3.0 to 4.0.11 \r [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning :  ValueTupleTest (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.0) -> NETStandard.Library (>= 1.6.0) -> System.Console (>= 4.0.0) -> runtime.win.System.Console (>= 4.3.0) -> System.Threading (>= 4.3.0) \r [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004616\NuGet.targets(97,5): warning :  ValueTupleTest (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.0) -> NETStandard.Library (>= 1.6.0) -> System.Threading (>= 4.0.11) [C:\Users\daplaist\Documents\Visual Studio 2017\Projects\ValueTupleTest\ValueTupleTest\ValueTupleTest.csproj]

Note that due to https://github.com/dotnet/roslyn-project-system/issues/1474, if you don't specify the `RuntimeIdentifier` for the project, you will see the warnings in Visual Studio but not when you do a command-line restore.

It seems like this may be happening due to the combination of NuGet's "nearest wins" version selection logic and the way the rid-specific implementation packages (such as `runtime.win.System.Console`) are brought in.  Possible solutions might include:

- Changing NuGet's version resolution (probably not feasible at this point)
- Updating the System.ValueTuple packages dependencies

@ericstj @weshaggard @rrelyea @emgarten

**Comment by srivatsn** [comment] 2017-02-05 19:42
Tagging @jaredpar @jcouv as well.

**Comment by emgarten** [comment] 2017-02-05 22:29
I'm a little unclear on how this is expected to work.

1. If the intent here is to use System.ValueTuple 4.3.0 on top of NETCore.App 1.1.0 which contains older System packages then I think these downgrade warnings are correct given the current packages.

2. If the expectation is that adding System.ValueTuple 4.3.0 updates half of the dependency graph to 4.3.0 and overrides the runtime assemblies used to be from the new packages instead of the shared framework then the problem might be that the runtime.json files containing these dependencies are coming from high level packages and are not updated by the System.ValueTuple.

**Comment by weshaggard** [comment] 2017-02-06 17:45
@dsplaisted this is a similar case to the NS 1.6.1 issue, where the ValueTuple package is upgrading packages above what we shipped in netcoreapp1.0 and will likely cause issues. 

If we want to support System.ValueTuple package with netcoreapp1.0 then we will need to update the System.ValueTuple package to have matching dependencies. 

cc @jcouv

**Comment by dsplaisted** [comment] 2017-02-06 18:11
@weshaggard It's a similar situation, but the difference with ValueTuple is that it's not actually upgrading all of the packages.  It's upgrading some of the runtime packages (for example runtime.win.System.Console) but not their dependencies (for example System.IO.FileSystem.Primitives).

I'm not sure whether this will work at runtime or not, but even if it does the package downgrade warnings will be confusing.  It won't be clear why they're occurring or what to do to resolve them.

**Comment by AlexGhiondea** [comment] 2017-02-08 18:20
@jcouv what are you thoughts on this? Do we want to update the ValueTuple package references as suggested above?

**Comment by jcouv** [comment] 2017-02-10 00:13
We discussed a few options with @srivatsn and @weshaggard. We'll have a decision Monday and I'll prioritize fixing this before RTM ships.

**Comment by jcouv** [comment] 2017-02-28 18:39
There was a related change above (#893) which makes 1.1 the new default version. At this point, we recommend 1.0 customers who want to use ValueTuple that they should upgrade to 1.1.
So I'll close the issue as by design.

**Closed by jcouv** 2017-02-28 18:39 UTC
Labels: area-System.Runtime, bug
