### ISSUE TITLE
Assert failure in ConcurrentBag's DangerousCount on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#33500] opened 2018-11-14 19:43 UTC
https://mc.dot.net/#/user/bartonjs/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/a27a04349e8d52a75261351271da8910c63ec177/workItem/System.Collections.Concurrent.Tests/wilogs
```
2018-11-14 07:53:11,069: INFO: proc(55): run_and_log_output: Output: Assertion Failed
2018-11-14 07:53:11,069: INFO: proc(55): run_and_log_output: Output: 
2018-11-14 07:53:11,070: INFO: proc(55): run_and_log_output: Output:    at System.Collections.Concurrent.ConcurrentBag`1.WorkStealingQueue.get_DangerousCount() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 1055
2018-11-14 07:53:11,071: INFO: proc(55): run_and_log_output: Output:    at System.Collections.Concurrent.ConcurrentBag`1.get_DangerousCount() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 521
2018-11-14 07:53:11,071: INFO: proc(55): run_and_log_output: Output:    at System.Collections.Concurrent.ConcurrentBag`1.ToArray() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 390
2018-11-14 07:53:11,072: INFO: proc(55): run_and_log_output: Output:    at System.Collections.Concurrent.Tests.ConcurrentBagTests.<>c__DisplayClass18_0.<Clear_ConcurrentUsage_NoExceptions>b__1() in /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Collections.Concurrent/tests/ConcurrentBagTests.netcoreapp.cs:line 85
2018-11-14 07:53:11,076: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-11-14 07:53:11,076: INFO: proc(55): run_and_log_output: Output:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2018-11-14 07:53:11,076: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by safern** [comment] 2019-03-12 20:00
@stephentoub is this still relevant? Have you seen this happen again? If so then to jump in and look at a dump if it was generated.

**Comment by stephentoub** [comment] 2019-03-13 02:11
@safern, I only ever saw it that once.

**Comment by safern** [comment] 2019-03-13 06:26
Ok, will close it and if we hit it again we can reopen and grab the dump.

**Comment by stephentoub** [comment] 2019-05-03 21:32
Just saw it again on Windows:
```
  Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 861 of 868 test cases)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 4)
Assertion Failed

   at System.Collections.Concurrent.ConcurrentBag`1.WorkStealingQueue.get_DangerousCount() in D:\a\1\s\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentBag.cs:line 1056
   at System.Collections.Concurrent.ConcurrentBag`1.get_DangerousCount() in D:\a\1\s\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentBag.cs:line 521
   at System.Collections.Concurrent.ConcurrentBag`1.ToArray() in D:\a\1\s\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentBag.cs:line 390
   at System.Collections.Concurrent.Tests.ConcurrentBagTests.<>c__DisplayClass18_0.<Clear_ConcurrentUsage_NoExceptions>b__1() in D:\a\1\s\src\System.Collections.Concurrent\tests\ConcurrentBagTests.netcoreapp.cs:line 85
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\Tasks\Task.cs:line 2403
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\Threading\ThreadPool.cs:line 664
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37391~2Fmerge/test~2Ffunctional~2Fcli~2F/20190503.16/workItem/System.Collections.Concurrent.Tests/wilogs

**Comment by ViktorHofer** [comment] 2019-05-15 05:15
Just happened again on OSX:

```
~/dotnetbuild/work/2ecf843e-5a48-4576-a83f-6af4b97ed0f1/Work/05b3e20d-17df-4712-b6a4-77b63c622ba7/Exec ~/dotnetbuild/work/2ecf843e-5a48-4576-a83f-6af4b97ed0f1/Work/05b3e20d-17df-4712-b6a4-77b63c622ba7/Exec
  Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 861 of 868 test cases)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 8)
Assertion Failed

   at System.Collections.Concurrent.ConcurrentBag`1.WorkStealingQueue.get_DangerousCount() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 1056
   at System.Collections.Concurrent.ConcurrentBag`1.get_DangerousCount() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 521
   at System.Collections.Concurrent.ConcurrentBag`1.ToArray() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 390
   at System.Collections.Concurrent.Tests.ConcurrentBagTests.<>c__DisplayClass18_0.<Clear_ConcurrentUsage_NoExceptions>b__1() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Collections.Concurrent/tests/ConcurrentBagTests.netcoreapp.cs:line 85
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 288
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2402
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 663
./RunTests.sh: line 175:  3510 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" xunit.console.dll System.Collections.Concurrent.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonosxtests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop $RSP_FILE
~/dotnetbuild/work/2ecf843e-5a48-4576-a83f-6af4b97ed0f1/Work/05b3e20d-17df-4712-b6a4-77b63c622ba7/Exec
----- end 22:01:48 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37512~2Fmerge/test~2Ffunctional~2Fcli~2F/20190514.47/workItem/System.Collections.Concurrent.Tests/wilogs

**Comment by stephentoub** [comment] 2019-05-30 17:46
```
~/dotnetbuild/work/6db7d4a9-0b29-49d4-9344-2bd90bd5f015/Work/f56b3197-0b69-4758-bd32-79cedc3ad501/Exec ~/dotnetbuild/work/6db7d4a9-0b29-49d4-9344-2bd90bd5f015/Work/f56b3197-0b69-4758-bd32-79cedc3ad501/Exec
  Discovering: System.Collections.Concurrent.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Concurrent.Tests (found 861 of 868 test cases)
  Starting:    System.Collections.Concurrent.Tests (parallel test collections = on, max threads = 4)
Assertion Failed
Expected _addTakeCount (-1) >= _stealCount (0).

   at System.Collections.Concurrent.ConcurrentBag`1.WorkStealingQueue.get_DangerousCount() in /_/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 1058
   at System.Collections.Concurrent.ConcurrentBag`1.get_DangerousCount() in /_/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 521
   at System.Collections.Concurrent.ConcurrentBag`1.ToArray() in /_/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs:line 390
   at System.Collections.Concurrent.Tests.ConcurrentBagTests.<>c__DisplayClass18_0.<Clear_ConcurrentUsage_NoExceptions>b__1() in /_/src/System.Collections.Concurrent/tests/ConcurrentBagTests.netcoreapp.cs:line 85
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2406
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 663
```

**Comment by kevingosse** [comment] 2019-06-01 17:36
I can reproduce locally when running the `Clear_ConcurrentUsage_NoExceptions` about 50 times. It's easier to debug by setting `threadsCount` to 2, `itemsPerThread` to 10000, and having one of the two threads do only `TryTake` operations.

Anyway, it seems like a race condition caused by an overflow. 

The race is between `TrySteal` and `TryLocalPop`. The initial condition is that the collection is empty, and `_headIndex` is equal to `int.MaxValue`.
1. In TrySteal, `_headIndex` is incremented optimistically, overflowing the value:

    Interlocked.Exchange(ref _headIndex, unchecked(head + 1));

2. Then the following check fails (as expected, since the collection is empty):

    if (head < _tailIndex)

3. So the steal is cancelled and the original value of `_headIndex` is restored:

    _headIndex = head;

The problem happens if `TryLocalPop` is called between steps 1 and 3. Because `_headIndex` is temporarily equal to int.MinValue (due to the optimistic increment), it becomes lower than `_tailIndex`. The logic unfolds as if the collection wasn't empty, returning an non-existing element and decrementing `_addTakeCount` below 0.

This is my first deep-dive into the logic of ConcurrentBag so I'm not sure what's the best way to fix this. I suspect the issue has been around for a while, but made much more likely by https://github.com/dotnet/corefx/commit/864e82e39b06f7df0acefe822f5c7c48592b53e1, which removed the initial `if (_headIndex < _tailIndex)` check in `TrySteal`. 


Also, I don't think this is related to the issue, but this condition looks fishy: 

https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentBag.cs#L975

According to the comment, the code is supposed to check if there are 2 items or less in the collection, and in that case wait for any pending Add operation. Then I believe the condition should have been something like:

    if (head >= _tailIndex - 2 && _currentOp == (int)Operation.Add)

**Comment by stephentoub** [comment] 2019-06-10 22:07
Thanks, @kevingosse.  Just took a quick look, and your analysis of the issue looks right; more generally, some of the comparisons here aren't accounting for the potential for overflow, so e.g. instead of "a < b", they should be "a - b < 0".  I have a fix locally with which I'm not able to repro the assert.

Regarding your "don't think this is related to the issue, but this condition looks fishy"... that does look wrong.  Fixing that, too.

Thanks!

**Closed** 2019-06-11 15:34 UTC
Labels: area-System.Collections, os-mac-os-x
