### ISSUE TITLE
 Could not load file or assembly System.Net.Http Version=4.0.0.0 in .net core app

### ISSUE THREAD

**Issue by rizwaans** [dotnet/corefx#28267] opened 2018-03-20 21:07 UTC
I've got this issue in .net core 2.0, just to give you more idea about what I'm trying to achieve. I'm trying to connect to VSTS and update the test status "Passed" or "Failed" based on my unit tests
I run of this "Could not load file or assembly System.Net.Http Version=4.0.0.0" issue where the code is trying to open a connection to vsts.
var connection = new VssConnection("https://.visualstudio.com", credentials);

**Comment by karelz** [comment] 2018-03-20 23:12
Does it repro in brand new .NET Core 2.0 console app for you? Or does the repro require some additional dependencies?

**Comment by rizwaans** [comment] 2018-03-20 23:54
I think you can reproduce it with out any additional dependencies. I just tried creating a new .net core console app and execute the below code. 

        try
        {
            var u = new Uri("https://{My Account}.visualstudio.com");
            VssCredentials c = new VssCredentials(new Microsoft.VisualStudio.Services.Common.VssBasicCredential(username, password));
            var connection = new VssConnection(u, c);
            var testClient = connection.GetClient<TestManagementHttpClient>();
            int testpointid = 1;
            string teamProject = "MyProjectName";
            RunCreateModel run = new RunCreateModel(name: "TestCase Name", plan: new Microsoft.TeamFoundation.TestManagement.WebApi.ShallowReference("TestPlan Id"), pointIds: new int[] { testpointid });
            TestRun testrun = testClient.CreateTestRunAsync(run, teamProject).Result;

            TestCaseResult caseResult = new TestCaseResult() { State = "Completed", Outcome = "passed", Id = 100000 };

            var testResults = testClient.UpdateTestResultsAsync(new TestCaseResult[] { caseResult }, teamProject, testrun.Id).Result;
            RunUpdateModel runmodel = new RunUpdateModel(state: "Completed");
            TestRun testRunResult = testClient.UpdateTestRunAsync(runmodel, teamProject, testrun.Id, runmodel).Result;

        }
        catch (AggregateException e)
        {
            Console.WriteLine(e.InnerException.Message);
        }

**Comment by karelz** [comment] 2018-03-21 00:45
Where do you get these types from then?
* Microsoft.VisualStudio.Services.Common.VssBasicCredential
* Microsoft.TeamFoundation.TestManagement.WebApi.ShallowReference
Can you post exact steps how to reproduce it? (start with new Console .NET Core 2.0 app)

Do you need more than the first 3 lines of code to reproduce it?

**Comment by rizwaans** [comment] 2018-03-21 01:16
ok here you go. 
1.create a .net core 2.0 console app
2.add Microsoft.TeamFoundationServer.ExtendedClient (15.112.1) package from Nuget
3.put the sample code from above comment , try and build. 

<thisshouldbeyouraccount>.visualstudio.com 

hope this helps you to recreate the issue. 

incase you're not able to add the extended client package. just add the below code in .csproj

<PropertyGroup>
    <PackageTargetFallback>portable-net451+win8</PackageTargetFallback>
</PropertyGroup>

**Comment by davidsh** [comment] 2018-05-10 22:02
@rizwaans What version of Visual Studio are you using?  Visual Studio 2017?  And what update are you using? We recommend the latest Update 15.7 for Visual Studio 2017.

**Comment by SivakumarShan** [comment] 2018-06-07 11:19
Hi I'm also getting the same error while using the below code.
var vssConnection = new Microsoft.VisualStudio.Services.WebApi.VssConnection(new Uri(tfsCollectionUri), new Microsoft.VisualStudio.Services.Common.VssBasicCredential("", ""));

I'm using .NET Core 2.0 version.

**Comment by karelz** [comment] 2018-06-07 14:59
@SivakumarShan can you answer @davidsh's questions above please? (https://github.com/dotnet/corefx/issues/28267#issuecomment-388199656)

**Comment by SivakumarShan** [comment] 2018-06-07 18:18
@karelz I'm using VS 2017 with 15.5.6 version. Let me update to the above mentioned version and try it out. Thanks :)

**Comment by SivakumarShan** [comment] 2018-06-08 06:56
@karelz I'm using VS 2017 with 15.5.6 version. Let me update to the above mentioned version and try it out. Thanks :)

**Comment by SivakumarShan** [comment] 2018-06-08 09:51
@karelz I've updated to VS Enterprise 2017 to 15.7.3 and still getting the same issue. I'm using netcoreapp2.0. Please help me to resolve this issue. Thanks.

**Comment by karelz** [comment] 2018-06-11 18:59
I am getting slightly different error, which is by design - it seems that the NuGet packages you're using are not compatible with .NET Core and use .NET Framework API surface (from System.Net.Http.WebRequest.dll) which is not available on .NET Core.

Repro steps: (based on https://github.com/dotnet/corefx/issues/28267#issuecomment-374809539)
```c#
using Microsoft.VisualStudio.Services.Common;
using Microsoft.VisualStudio.Services.WebApi;

class Program
{
    static void Main()
    {
        VssCredentials c = new VssCredentials(new Microsoft.VisualStudio.Services.Common.VssBasicCredential("my_name", "abc"));
        var connection = new VssConnection(new System.Uri("https://my_name.visualstudio.com"), c);
    }
}
```

Note build warnings - listing assemblies which target .NET Framework 4.6.1 instead of .NET Core 2.0:
```
warning NU1603: Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.5 depends on System.Net.Http (>= 4.0.1) but System.Net.Http 4.0.1 was not found. An approximate best match of System.Net.Http 4.1.0 was resolved.
warning NU1603: Microsoft.IdentityModel.Clients.ActiveDirectory 3.13.5 depends on System.Text.RegularExpressions (>= 4.0.12) but System.Text.RegularExpressions 4.0.12 was not found. An approximate best match of System.Text.RegularExpressions 4.1.0 was resolved.
warning NU1701: Package 'Microsoft.AspNet.WebApi.Client 5.2.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.TeamFoundationServer.Client 15.112.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.VisualStudio.Services.Client 15.112.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Microsoft.VisualStudio.Services.InteractiveClient 15.112.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'Newtonsoft.Json 8.0.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'System.IdentityModel.Tokens.Jwt 4.0.2.206221351' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
```

At runtime, I get exception explaining System.Net.Http.WebRequest is not available:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Using .NET Framework assets on .NET Core is a bridge which helps to try libraries that didn't start targeting .NET Core / .NET Standard yet. It is not guaranteed to work and in this case, it won't work as the libraries have dependencies which cannot be satisfied on .NET Core.

Closing as by design - the libraries you use need to ship targeting .NET Core, or you can use them only on .NET Framework.

**Closed by karelz** 2018-06-11 18:59 UTC
Labels: area-System.Net.Http, needs more info, question

**Comment by kaaoo** [comment] 2018-09-26 13:19
Hi everybody!
I had the same error. But I've found another [issue](https://github.com/Microsoft/vsts-dotnet-samples/issues/93) which helped me.
I just changed the version of Vsts client to **version 15.126.0-preview**.
Hope it will help you!

**Comment by jrb9249** [comment] 2018-10-30 15:59
I am able to reproduce this issue in .NET Framework 4.6.1.

**Comment by dsun-ge** [comment] 2019-08-12 14:46
I had the same problem. I figured out that I created a wrong type of project. It should be Windows Console application that runs on .NET Framework,, not CoreApp console application that runs on CoreApp2.0. I am new to .NET and hope my experience helps those like me.
