### ISSUE TITLE
System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.PostAsync_RedirectWith302_LargePayload failed with "System.OperationCanceledException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22956] opened 2017-08-04 07:16 UTC
Failed test: System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest.PostAsync_RedirectWith302_LargePayload 
Configuration: OuterLoop_netcoreapp_ubuntu14.04_debug

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/131/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/PostAsync_RedirectWith302_LargePayload/

MESSAGE:
~~~
System.OperationCanceledException : The operation was canceled.
~~~
STACK TRACE:
~~~
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 508 
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 463 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_Redirect_LargePayload_Helper>d__83.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 1582 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_RedirectWith302_LargePayload>d__82.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 1566
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by davidsh** [comment] 2017-08-04 13:48
Another case of timeouts from Azure Internet to the test endpoint.

**Comment by Jiayili1** [comment] 2017-08-14 07:49
This issue is repro on outerloop_netcoreapp_release, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_release/lastCompletedBuild/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/PostAsync_RedirectWith307_LargePayload/

**Comment by Jiayili1** [comment] 2017-08-16 06:54
This issue is still repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170816.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest~2FPostAsync_RedirectWith307_LargePayload

**Comment by davidsh** [comment] 2017-08-16 16:32
There are no logs when I click on the above link.  Please include call stack and errors generated.

**Comment by Jiayili1** [comment] 2017-08-22 09:07
This test failed with same issue: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/148/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/PostAsync_RedirectWith307_LargePayload/

MESSAGE:
~~~
System.OperationCanceledException : The operation was canceled.
~~~
STACK TRACE:
~~~
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 508 
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 463 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_Redirect_LargePayload_Helper>d__85.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 1654 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<PostAsync_RedirectWith307_LargePayload>d__83.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu14.04_debug/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs:line 1631 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by Jiayili1** [comment] 2017-08-28 03:09
failed again in outerloop_netcoreapp_ubuntu14.04_debug, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/154/testReport/System.Net.Http.Functional.Tests/ManagedHandler_HttpClientHandlerTest/PostAsync_RedirectWith307_LargePayload/

**Comment by Jiayili1** [comment] 2017-09-04 02:46
Following test failed with same issue, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_debian8.4_debug/157/testReport/System.Net.Http.Functional.Tests/ManagedHandler_PostScenarioTest/PostEmptyContentUsingChunkedEncoding_Success_serverUri__https___corefx_net_cloudapp_net_Echo_ashx_/
ManagedHandler_PostScenarioTest.PostEmptyContentUsingChunkedEncoding_Success
ManagedHandler_PostScenarioTest.PostRewindableContentUsingAuth_NoPreAuthenticate_Success
ManagedHandler_PostScenarioTest.PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsHttpRequestException

**Comment by Sunny-pu** [comment] 2017-12-11 07:55
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/lastCompletedBuild/testReport/System.Net.Http.Functional.Tests/HttpClientHandler_SslProtocols_Test/GetAsync_SupportedSSLVersion_Succeeds_sslProtocols__Tls__url____https___www_ssllabs_com_10301____/

**Comment by karelz** [comment] 2017-12-24 06:08
Duplicate of #23768 (although this one has ManagedHandler failures)

**Closed by karelz** 2017-12-24 06:08 UTC
Labels: area-System.Net.Http, Azure test infra changes needed, os-linux, test-run-core

**Comment by sagardafle** [comment] 2018-04-02 00:58
Facing the same error when we try to do a stress test on an "GET" API that returns around 10K lines of JSON data.
Any workaround/fixes for this ?

**Comment by stephentoub** [comment] 2018-04-02 01:01
@sagardafle, how long is the request taking?  Is it possible it's just taking a long time and changing the HttpClient.Timeout to something longer or infinite would address it?  The default is that the request will be canceled after 90 seconds, and if you're overloading your client or server or network in a stress test, it's not out of the realm of possibility that you could bump up against that limit.

**Comment by sagardafle** [comment] 2018-04-02 01:19
Hi @stephentoub , 

Thank you for replying. I have set the Timeout and the 'ReadWriteTimeout' to (1000 * 60 * 10) 10 minutes for the HttpWebRequest. 
The request took around 2 minutes to complete and then I got the below error: 
```

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The request was aborted: The request was canceled.
System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()

```

Below are the client settings:
```
[ClassInitialize]
        public static void ClassInit(TestContext context)
        {
            ServicePointManager.UseNagleAlgorithm = false;
            ServicePointManager.Expect100Continue = false;
            ServicePointManager.DefaultConnectionLimit = 1000;
            ServicePointManager.DnsRefreshTimeout = 60 * 60 * 1000; // 1 hour

        }

private static HttpWebRequest CreateRequest(Uri uri)
        {
            var request = HttpWebRequest.CreateHttp(uri);
            request.Method = "GET";
            request.Accept = "application/json";
            request.AllowAutoRedirect = false;
	        request.KeepAlive = false;
	        request.ReadWriteTimeout = 1000 * 60 * 10;
			request.Timeout = 1000 * 60 * 10;
			request.AllowWriteStreamBuffering = false;
            request.AuthenticationLevel = AuthenticationLevel.None;
            request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            request.PreAuthenticate = true;
}
```

**Comment by stephentoub** [comment] 2018-04-02 01:21
> System.Net.ConnectStream.EndRead

This showing up on the call stack means you're running against the .NET Framework rather than .NET Core / corefx.

**Comment by sagardafle** [comment] 2018-04-02 01:27
Ok, thanks for pointing that out. 
Couple of questions(If you don't mind answering) as I am new to the .Net stack:
1. We have recently update our service to use Visual Studio 2017 and ASP.NET Core 2.0 , so not sure if your comment fully hold true. 
2. What fix do you recommend in such case?
Thanks again. 
Really appreciate.

**Comment by stephentoub** [comment] 2018-04-02 01:34
> We have recently update our service to use Visual Studio 2017 and ASP.NET Core 2.0 , so not sure if your comment fully hold true.

That ConnectStream class simply doesn't exist in corefx.  If it's showing up on the stack, you're not running on .NET Core.  In .NET Core, HttpWebRequest is actually layered on top of HttpClient, so these internal types from the .NET Framework aren't there.

> What fix do you recommend in such case?

To start, I'd recommend switching to using HttpClient directly rather than using HttpWebRequest.  You generally want to create a single instance of HttpClient that's then shared for all of your requests.

As for root causing the issue, I would suggest taking a network trace.  My guess is that the server is actually closing the connection after two minutes, but that's just a guess; I'm not very familiar with that implementation.

**Comment by sagardafle** [comment] 2018-04-02 05:30
Hi Stephen, 

I tried replacing HttpWebRequest with HttpClient. I would say , it runs better but I do encounter error sometimes. 

The error looks like: 
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The request was aborted: The request was canceled.
System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)


My HttpClient configuration looks like:


```
 private static readonly HttpClientHandler handler = new HttpClientHandler();
		private static readonly HttpClient HttpClient = new HttpClient(handler,false)
	    {
			DefaultRequestHeaders = {
				Authorization = new AuthenticationHeaderValue("Bearer", AccessToken),
				Accept = { MediaTypeWithQualityHeaderValue.Parse("application/json")},
			},
			Timeout = TimeSpan.FromMinutes(20),
	    };

using (var response = await HttpClient.GetAsync(uri))
			using (var content = response.Content)
			{
				// ... Read the string.
				var totalSize = await content.ReadAsStringAsync();
				Assert.AreNotEqual(0, totalSize.Length);
				Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
			}

```

Am I missing anything in the HttpClient setup? Thank you.

**Comment by stephentoub** [comment] 2018-04-02 05:32
> Am I missing anything in the HttpClient setup?

On .NET Framework, HttpClient is built on top of HttpWebRequest, so you would expect to see the same issue.  On .NET Core, it's inverted, with HttpWebRequest built on top of HttpClient.  Since it sounds like your intention is to be using core, I would see how things run with HttpClient while using .NET Core rather than .NET Framework.
