### ISSUE TITLE
Span<byte> gets corrupted when accessing `Environment.StackTrace` multiple times in xunit test

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#14833] opened 2017-01-03 23:56 UTC
### Repro:
1. Checkout https://github.com/pakrym/r/tree/span-corrupt
2. `dotnet restore `&& `dotnet test` in `src/SpanCorrupt`

### Expected:
Calling Environment.StackTrace does not modify span:
```
BEFORE LOOP 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
1 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
2 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
3 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
4 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
5 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
6 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
7 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
8 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
9 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
10 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
11 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
12 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
13 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
14 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
15 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
16 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
17 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
18 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
19 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
20 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
21 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
22 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
23 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
24 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
25 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
26 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
27 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
28 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
29 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
30 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
31 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
```
### Actual
Calling Environment.StackTrace modifies span:
```
1 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
2 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
3 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
4 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
5 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
6 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
7 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
8 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
9 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
10 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
11 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
12 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
13 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
14 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
15 -- 72 101 97 100 101 114 58 118 97 108 117 101 13 10 13 10
16 -- 186 68 239 255 255 255 255 255 88 252 200 2 13 10 13 10
17 -- 186 68 239 255 255 255 255 255 88 252 200 2 13 10 13 10
18 -- 186 68 239 255 255 255 255 255 88 252 200 2 13 10 13 10
19 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
20 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
21 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
22 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
23 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
24 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
25 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
26 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
27 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
28 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
29 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
30 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
31 -- 121 0 115 0 116 0 101 0 109 0 46 0 80 0 114 0
```

@davidfowl @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment] 2017-01-04 00:00
@AtsushiKan, could you take a look? This is blocking the ASP.NET team.

cc: @joshfree, @jkotas

**Comment by jkotas** [comment] 2017-01-04 00:45
It does not build for me:

```
C:\r-span-corrupt\src\SpanCorrupt\Program.cs(17,15): error CS0433: The type 'Encoding' exists in both 'System.Text.Encoding, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by pakrym** [comment] 2017-01-04 00:46
@jkotas you would need SDK `1.0.0-preview2-1-003180` installed

**Comment by jkotas** [comment] 2017-01-04 01:21
You are using the faster Span implementation built into CoreCLR. It is not fully functional yet. 

https://github.com/dotnet/coreclr/issues/5851 is the uber tracking issue. The problem you are hitting is caused by `JIT - Correctness – proper GC reporting of the special byref field`. @russellhadley or somebody from his team is working on it.

**Comment by pakrym** [comment] 2017-01-04 02:11
@jkotas is there a way to target latest runtime but disable fastspan?

**Comment by jkotas** [comment] 2017-01-04 02:31
I would go to nuget cache and overwrite the netcoreapp1.1 System.Memory with netstandard1.0 copy:

`copy lib\netstandard1.0\System.Memory.dll lib\netcoreapp1.1\System.Memory.dll`

**Comment by davidfowl** [comment] 2017-01-04 08:19
@jkotas does it make sense to disable the fast span in the package until it works? Doesn't make much sense to use it now.

**Comment by jkotas** [comment] 2017-01-04 08:35
You either need to use older corefx before #14262 for now; or if you need to use live corefx for other reasons, I agree it would make sense to disable the fast span in the package.

cc @ahsonkhan

**Comment by KrzysztofCwalina** [comment] 2017-01-04 16:32
@ahsonkhan, could you temporarily disable fast span?

**Comment by davidfowl** [comment] 2017-02-19 07:05
Isn't this fixed now?

**Comment by karelz** [comment] 2017-03-02 18:56
@ahsonkhan says the bugs in GC & JIT got fixed.

**Closed by karelz** 2017-03-02 18:56 UTC
Labels: area-System.Memory, blocking-partner, bug
