### ISSUE TITLE
ImmutableArray list initialiser throws NullReferenceException

### ISSUE THREAD

**Issue by rjmholt** [dotnet/corefx#31217] opened 2018-07-20 05:17 UTC
Using .NET Core 2.1.1, I have a line of code like:
```csharp
var x = new ImmutableArray<int> { 0 };
```

I get an error like this as a result (actual one is a bit bigger):
```
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.Collections.Immutable.ImmutableArray`1.Add(T item)
   at MetadataAnalysis.MetadataAnalyzer..ctor(PEReader peReader) in /home/rob/Documents/Dev/Microsoft/ModuleAnalyzer/MetadataAnalysis/MetadataAnalyzer.cs:line 128
```

Workaround of course is to do
```csharp
var x = new [] { 0 }.ToImmutableArray();
```

(Or I presume something similar? I couldn't find the nice `Create()` and `CreateRange()` methods in my versions even though they're in the code here -- presume they are pending release? Or do I need another assembly reference?))

**Comment by EgorBo** [comment] 2018-07-20 10:05
I guess it's not supposed to be created via the parameterless constructor and the reason why NRE is thrown instead of something meaningful is explained here: https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L168-L173

Have you tried to use `Create` like this:
`var x = ImmutableArray.Create(0);` ?

**Comment by jnm2** [comment] 2018-07-20 12:39
@rjmholt The reason is inherent to C# itself. `var x = new ImmutableArray<int> { 0 };` is by definition identical to:

```cs
var x = new ImmutableArray<int>();
x.Add(0);
```

And you can see how useless this is for immutable types, even besides the NRE, since you can't access the return value of Add. C#'s initializer syntax today is only useful when mutating the same object.

**Comment by danmosemsft** [comment] 2018-07-20 16:53
Closing as by design as explained in the code comment.

**Closed by danmosemsft** 2018-07-20 16:53 UTC

**Comment by rjmholt** [comment] 2018-07-20 18:03
Ok that comment makes it all make sense to me. I admit I didn't actually know how list initialisers worked under the hood until I got this error - I was banking on the newest and most concise syntax being the most appropriate/efficient one.

I'll say that the `NullReferenceException` made this rather unclear and that it took me a fair while longer to debug this than if it had been a different exception. I didn't find that comment until it was pointed out (because of the indirection of the list initialiser syntax). But I suppose if we're trying to coerce the JIT, there's not much that can be done.

@EgorBo I didn't get intellisense for any of the `Create` methods - is there another import I should be using?

**Comment by jnm2** [comment] 2018-07-20 18:09
@rjmholt It's `ImmutableArray.Create<int>` (though the generic parameter can be inferred) but you were probably trying `ImmutableArray<int>.Create`?

**Comment by rjmholt** [comment] 2018-07-20 18:14
Ah! That's probably it. I'll give it a try later. Thanks for the help.
