### ISSUE TITLE
Create the Microsoft.Diagnostics.EventSource.Redist Nuget Package

### ISSUE THREAD

**Issue by brianrob** [dotnet/corefx#24618] opened 2017-10-12 22:15 UTC
The package will be completed once the following is done:

 - [X] Create project and solution file for Microsoft.Diagnostics.Tracing.EventSource.Redist.
 - [x] Copy the code into CoreFX and make it build.
 - [X] Migrate changes required for this nuget package (code changes and missing resource strings) back to CoreCLR.
 - [X] Mirror code from CoreCLR repo.
 - [X] Use SR for resource strings instead of using ResourceManager directly.
 - [X] Produce a nuget package.
 - [X] Enable EventSource tests to run against Microsoft.Diagnostics.Tracing.EventSource.Redist during CI.
 - [x] Add EventCounter source and tests.

**Comment by brianrob** [comment] 2017-10-12 22:15
The first PR: #24405

**Comment by brianrob** [comment] 2017-10-23 10:43
PR out for SR usage: https://github.com/dotnet/corefx/pull/24808.

**Comment by brianrob** [comment] 2017-10-23 14:20
Updated list above now that #24808 has been merged.

**Comment by brianrob** [comment] 2017-10-24 09:58
- https://github.com/dotnet/coreclr/pull/14669 tracks porting the source and string additions back to dotnet/CoreCLR.
 - https://github.com/dotnet/corert/pull/4786 tracks porting the string additions back to dotnet/CoreRT.  The source changes will be automatically ported to dotnet/CoreRT by the mirror.

**Comment by brianrob** [comment] 2017-10-24 09:59
@JamesCrompton-MSFT this is the issue that tracks the work required to produce the EventSource nuget package.

Wanted to make sure you are aware of this issue so that you can track progress.

**Comment by brianrob** [comment] 2017-10-25 09:09
PR for enabling tests: https://github.com/dotnet/corefx/pull/24859

**Comment by brianrob** [comment] 2017-10-25 09:09
PR for enabling tests: https://github.com/dotnet/corefx/pull/24859

**Comment by brianrob** [comment] 2017-10-26 08:30
PR for enabling EventCounter: https://github.com/dotnet/corefx/pull/24893

**Comment by brianrob** [comment] 2017-11-01 21:51
We now have an initial mirror in place, but there are some things that will need to be fixed.  @safern is going to look at this next week.

**Comment by brianrob** [comment] 2017-11-20 22:52
@safern, have you had any time to look into the mirroring issues?  Thanks.

**Comment by safern** [comment] 2017-11-20 23:08
> @safern, have you had any time to look into the mirroring issues? Thanks.

Not yet, I'll take a look this week or next week the latest.

**Comment by brianrob** [comment] 2017-11-20 23:49
Thanks much.  Appreciate it.

**Comment by safern** [comment] 2018-01-13 01:46
@brianrob the issue is fixed and the mirror is now using the updated tool. However there has been a discussion about mirroring the whole coreclr shared folder into corefx. See: https://github.com/dotnet/corefx/issues/25188

So I'm changing the mirror settings to mirror the whole folder to a Common directory in corefx, @tarekgh will work once the first PR is merged to fix the Redist project to build and grab the sources from that folder.

**Comment by brianrob** [comment] 2018-01-24 19:52
@safern sounds good.  Thanks so much for fixing this.  Looks like we can close this issue!

**Closed** 2018-01-24 19:52 UTC
Labels: area-System.Diagnostics.Tracing, enhancement
