### ISSUE TITLE
Tracing diagnostic events not fired in ArrayPool tests 

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#20511] opened 2017-05-31 18:21 UTC
These tests explicitly test for tracing events , tracing API are not tested in UWP . This bug tracks System.Buffer UWP test failures.

public static void RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent()

**Comment by karelz** [comment] 2017-06-02 00:28
@tijoytom we're using exactly 1 area label per issue - see [Triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified). Thanks!

**Comment by brianrob** [comment] 2017-07-12 23:34
@tijoytom, it looks like this is because there is a copy of ArrayPoolEventSource in System.Private.CoreLib that does nothing.  The compiler produces code that calls Object..ctor because it's functionally equivalent to an Object allocation.

It also looks like the ArrayPool implementation has been pulled into System.Private.CoreLib, so it's likely that the EventSource needs to be pulled in as well.

This appears to be tracked by https://github.com/dotnet/corert/issues/2414.  The implementation is present in ProjectN\src\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Buffers\ArrayPoolEventSource.cs.

Can you help route this to the right person?

**Comment by tijoytom** [comment] 2017-07-13 18:54
@danmosemsft @karelz Who owns System.Buffer ?

**Comment by AlexGhiondea** [comment] 2017-07-13 18:59
@tijoytom can you tell me more about why is this related to Buffer?

**Comment by tijoytom** [comment] 2017-07-13 19:03
@AlexGhiondea See @brianrob comment above ..ArrayPoolEventSource is in System.Buffer

**Comment by AlexGhiondea** [comment] 2017-07-13 19:04
@safern it looks like you own System.Buffers. Can you take a look?

**Comment by tijoytom** [comment] 2017-07-13 19:04
@AlexGhiondea  I meant to say ArrayPoolEventSource need to be implemented for UAPAOT..

**Comment by AlexGhiondea** [comment] 2017-07-13 19:08
@tijoytom @brianrob if this is about implementing/porting the EventSource code to UWPAOT then whoever owns EventSource should do that -- is that you @brianrob ?
If there is a bug in System.Buffers that prevents the code from working then @safern can take a look.

**Comment by brianrob** [comment] 2017-07-13 19:11
@AlexGhiondea, the issue is that when System.Buffers was ported to System.Private.CoreLib, its EventSource was not ported.  Thus, the code in CoreFX isn't even being used.

If you want to have an EventSource present in UAPAOT for System.Buffers, then the owner of System.Buffers needs to do that.  This has nothing to do with EventSource functionality.  Put another way, the owners of EventSource don't instrument the runtime and framework.  Instead, we provide EventSource as a common way for components to do logging.

**Comment by tijoytom** [comment] 2017-07-13 19:12
@AlexGhiondea Yes it's about implementing / porting event source provider for Arraypool ..ie ArrayPool want diagnostics information , so it use event source for it ... @brianrob owns event source itself, not libraries that  use it .. So it's up to the library owner to make sure it works on UAPAOT

**Comment by AlexGhiondea** [comment] 2017-07-13 19:13
@tijoytom @brianrob that makes sense. Thanks for clarifying.

@safern can you take a look and see what the work would be?

**Comment by safern** [comment] 2017-07-19 20:46
Taking a look now. Finally unblocked by ResourceManager stuff :)

**Comment by safern** [comment] 2017-07-19 21:14
@brianrob the ArrayPoolEventSource in CoreFX is actually being used: https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System.Buffers.csproj#L24-L30

So I will just go ahead and port that into CoreRT.

**Comment by safern** [comment] 2017-07-21 01:42
Fixed in changeset: 1667201 in TFS. Will update to be ingested and will re-enable the tests.

**Comment by safern** [comment] 2017-07-21 17:58
My change didn't make it to yesterday's official build but it is already in ProjectN. All the disabled tests against this issue pass. So I will wait until we consume that change to enable the tests and close this issue.

**Comment by joshfree** [comment] 2017-07-24 22:10
@safern can you verify the fix on today's build?  Are we safe to resolve/close now?

**Comment by safern** [comment] 2017-07-24 22:12
To close this I need to re-enable the tests for UapAot as they are disabled. I will verify if the fix is on today's build and will throw a PR that closes this issue.

**Closed** 2017-07-25 18:36 UTC
Labels: area-System.Buffers
