### ISSUE TITLE
Extra newline in Linux on console input

### ISSUE THREAD

**Issue by shravan2x** [dotnet/corefx#25809] opened 2017-12-09 06:20 UTC
I have the following code targeted at .NET Core 2.0

```c#
while (true)
{
    Console.WriteLine(DateTime.Now);
    // do some work
    Console.ReadKey();
}
```

When the program is run on Windows, typing `enter` a few times results in output like:

```
12/9/2017 12:14:15 AM
12/9/2017 12:14:16 AM
12/9/2017 12:14:17 AM
```

However, on Ubuntu, the output is
```
12/9/17 6:13:55 AM

12/9/17 6:14:07 AM

12/9/17 6:14:08 AM
```

I believe this is because on Windows, typing the enter key on `Console.ReadKey()` does not actually print the `\n` character, whereas on Linux it does.

Is this something that can be fixed?

**Comment by karelz** [comment] 2017-12-12 00:15
@tmds any idea if it is something we can override on Linux?

**Comment by tmds** [comment] 2017-12-12 05:09
@shravan2x @karelz `ReadKey` has an overload that accepts a bool, when set to `true`, it won't print the read character. That works.
The docs of `ReadKey()` say _The pressed key is displayed in the console window._ So the Linux behavior matches with the docs.
We need to understand why Windows isn't showing the character. Then we can look at changing the Linux implementation.

**Comment by clarkis117** [comment] 2018-03-21 01:20
Hmmm... maybe the issue is similar to this one #11206

**Comment by ViktorHofer** [comment] 2018-03-21 23:18
> I believe this is because on Windows, typing the enter key on Console.ReadKey() does not actually print the \n character, whereas on Linux it does.

In fact the key returned by Console.ReadKey is printed on both Windows and Linux but the difference is that on Windows `ConsoleKeyInfo.KeyChar` is `\r` whereas on Unix it is `\n` when pressing enter (`ConsoleKeyInfo.Key` = `Enter`). That's by design as on Windows a newline consists of two character and because of that there is no newline printed onto the console. Closing.

**Closed by ViktorHofer** 2018-03-21 23:18 UTC
Labels: area-System.Console, enhancement, os-linux, tenet-compatibility

**Comment by tmds** [comment] 2018-03-22 12:04
https://github.com/dotnet/corefx/pull/28362 fixes the issue by making enter return '\r' on Unix.
