### ISSUE TITLE
CoreFx 3.0 20181004.0 (arm64) Build failure: Git clone failing (when VSTS has transient network issue)

### ISSUE THREAD

**Issue by ulisesh** [dotnet/corefx#32774] opened 2018-10-11 22:05 UTC
@dotnet-mc-bot commented on [Thu Oct 04 2018](https://github.com/dotnet/core-eng/issues/4314)

2018-10-04T12:05:45.7830819Z ##[section]Starting: Docker git clone
2018-10-04T12:05:45.7833872Z ==============================================================================
2018-10-04T12:05:45.7834033Z Task         : Command Line
2018-10-04T12:05:45.7834115Z Description  : Run a command line with arguments
2018-10-04T12:05:45.7834227Z Version      : 1.1.3
2018-10-04T12:05:45.7834306Z Author       : Microsoft Corporation
2018-10-04T12:05:45.7834441Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2018-10-04T12:05:45.7834542Z ==============================================================================
2018-10-04T12:05:45.9505598Z [command]/usr/bin/docker run --rm --name corefx-cross-2088038 -v corefx-cross-2088038:/root/corefx-2088038 -w=/root/corefx-2088038 -e PACKAGEVERSIONPROPSURL= -e MSBUILDDEBUGCOMM=1 -e MSBUILDDEBUGPATH=/root/corefx-2088038 microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921 git clone *** /root/corefx-2088038
2018-10-04T12:05:47.1304420Z Cloning into '/root/corefx-2088038'...
2018-10-04T12:05:47.4927662Z fatal: unable to access '***': GnuTLS recv error (-54): Error in the pull function.
2018-10-04T12:05:50.3810187Z ##[error]/usr/bin/docker failed with return code: 128
2018-10-04T12:05:50.3819607Z ##[error]/usr/bin/docker failed with error: /usr/bin/docker failed with return code: 128
2018-10-04T12:05:50.4536353Z ##[section]Finishing: Docker git clone

---

@v-asdhin commented on [Thu Oct 04 2018](https://github.com/dotnet/core-eng/issues/4314#issuecomment-427152553)

@danmosemsft Could you please have a look at this build break issue?

---

@danmosemsft commented on [Thu Oct 04 2018](https://github.com/dotnet/core-eng/issues/4314#issuecomment-427154321)

@dotnet/dnceng this seems like infra.

---

@MattGal commented on [Thu Oct 04 2018](https://github.com/dotnet/core-eng/issues/4314#issuecomment-427155051)

Agreed;  It looks like a transient network error accessing the VSTS trusted Git repo, tagging as First responder to investigate.

---

@MattGal commented on [Thu Oct 11 2018](https://github.com/dotnet/core-eng/issues/4314#issuecomment-429043684)

@ulisesh you've had this assigned to you for three days without any update, can you please provide one?

---

@ulisesh commented on [Thu Oct 11 2018](https://github.com/dotnet/core-eng/issues/4314#issuecomment-429134773)

It's a transient error caused by the Git repository hanging up while trying to clone the repo. The command comes from CoreFX source code and the component that is misbehaving is external to our teams, there's nothing we as .NET Engineering services can actually do here. The correct fix is to detect this case and retry some number of times. Moving to CoreFX for investigation.

**Comment by karelz** [comment] 2018-10-12 18:27
Is it dupe of #32769?
@wtgodbe @weshaggard can you please check priority/urgency?

**Comment by wtgodbe** [comment] 2018-10-12 18:58
Yes, it's a dupe. Closing in favor of https://github.com/dotnet/corefx/issues/32769

**Closed by wtgodbe** 2018-10-12 18:58 UTC
Labels: area-Infrastructure, bug
