### ISSUE TITLE
Dotnet core's sockets don't seem to have access to the SocketAPMExtensions

### ISSUE THREAD

**Issue by johnnymo87** [dotnet/corefx#10566] opened 2016-08-04 15:51 UTC
I've made [a github repo](https://github.com/johnnymo87/socket-apm-extensions) to demo my issue. Copying the readme here ...

According to my understanding of the conversation in [this issue](https://github.com/dotnet/corefx/issues/2936), dotnet core supports APM methods for sockets, such as `BeginConnect` and `EndConnect`. I believe the support for it appears [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs) in the source code. I must be doing something wrong, however, because I am unable to access those methods in my code. This repo has the necessary code to reproduce the issue.

``` bash
docker-compose build
```

I get the following:

``` bash
Building app
Step 1 : FROM microsoft/dotnet:latest
 ---> 3502ab7a3654
Step 2 : COPY . /app
 ---> d129994eb685
Removing intermediate container a6ad53b0061f
Step 3 : RUN dotnet restore /app
 ---> Running in a04726ff78a2
log  : Restoring packages for /app/project.json...
log  : Writing lock file to disk. Path: /app/project.lock.json
log  : /app/project.json
log  : Restore completed in 608ms.
 ---> b3934c2e0aeb
Removing intermediate container a04726ff78a2
Step 4 : RUN dotnet build /app
 ---> Running in 38dfed6ca88a
Project app (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling app for .NETStandard,Version=v1.6
/usr/share/dotnet/dotnet compile-csc @/app/obj/Debug/netstandard1.6/dotnet-compile.rsp returned Exit Code 1
/app/Program.cs(15,35): error CS1061: 'Socket' does not contain a definition for 'BeginConnect' and no extension method 'BeginConnect' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?)
/app/Program.cs(16,56): error CS1061: 'Socket' does not contain a definition for 'EndConnect' and no extension method 'EndConnect' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    2 Error(s)

Time elapsed 00:00:01.2293181
```

**Comment by mellinoe** [comment] 2016-08-04 17:42
@CIPop @davidsh

**Comment by CIPop** [comment] 2016-08-04 18:03
@johnnymo87 This was, at that time, by design: the contracts only expose new Task-based APIs and the high-performance *Async (not Task based) APIs. The thinking was that we needed to create a simple API surface with as little duplication as possible.
I believe that thinking has now changed as we aim to simplify porting existing code to the new platform.

To work-around the issue in the current release, please include the following in your project: https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/Net/Sockets/SocketAPMExtensions.cs

@richlander / @terrajobst may have more information on the new API surface guidance.

**Comment by johnnymo87** [comment] 2016-08-05 13:02
@CIPop Thanks for the quick response from you and your team! The work-around you suggest works for me. For the record, I'll note here that I also had to include the `TaskToApm` code from here: https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/Threading/Tasks/TaskToApm.cs

**Comment by davidsh** [comment] 2016-11-18 20:52
This problem should be gone now in the current code in [master] branch targeted for .NET Core 1.2 release.

The APM methods have been added back to the API surface and don't reside in any extensions class.

Closing this issue for now.  Please try out the current code in [master].  Thx.

**Closed by davidsh** 2016-11-18 20:52 UTC
Labels: area-System.Net
