### ISSUE TITLE
Intermittent: Empty Process stdout

### ISSUE THREAD

**Issue by sirkadirov** [dotnet/corefx#31740] opened 2018-08-13 16:15 UTC
## Story
I don't know why, but sometimes when running same console program with same input data, System.Diagnostics fucntionality returns empty stdout.

It's not a problem with running process. Also I checked my code many times, no errors found.

## Platforms
- Windows (tested)
- Linux (tested)

## I think this non-repro code would be useful for creation of working repro of this problem

I tried to do a minimal repro, but all tests passed and none failed... so maybe something wrong with my code. Or, if someone have same problem, maybe something wrong in .NET Core.

````c#
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Diagnostics;

class EmptyStdOutRepro
{
    
    public static void Main()
    {
        new EmptyStdOutRepro().Run();
    }
    
    public void Run()
    {
        
        while (true)
            Exec();
        
    }
    
    private void Exec()
    {
        
        int lineCount = 0;
        string output = "";
        
        Process process = new Process();
        
        process.StartInfo.FileName = "ipconfig.exe";
        
        process.StartInfo.UseShellExecute = false;
        process.StartInfo.RedirectStandardOutput = true;
        process.StartInfo.CreateNoWindow = true;
        process.StartInfo.ErrorDialog = false;
        
        process.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
        {
            
            if (!String.IsNullOrEmpty(e.Data))
            {
                lineCount++;
                output += ("\n[" + lineCount + "]: " + e.Data);
            }
            
        });

        process.Start();

        process.BeginOutputReadLine();
        process.WaitForExit();

        if (output != "")
            Console.WriteLine("PASSED!" + output.Length);
        else
            Console.WriteLine("FAILED!" + output.Length);

        process.WaitForExit();
        process.Close();
        
    }
    
}

````

## Working repro, needs minimization
Class ProgramExecutor in SimplePM_Server repo: https://github.com/SirkadirovTeam/SimplePM_Server/tree/master/SimplePM_Server/ProgramTesting/SRunner/ProgramExecutor

**Comment by karelz** [comment] 2018-08-15 02:53
Are you able to reproduce it on both Windows and Linux?
Are you able to reproduce it on more than 1 machine?
Is the large repro sensitive to HW configuration?

**Comment by sirkadirov** [comment] 2018-08-15 07:16
Hi, @karelz!
I just moved my project from .NET framework/Mono due to not implremented System.Diagnostics features in second. After that, I noticed this problem.

Yes, this error rep on both OSes, tested on VMs - reproduces...

Maybe this error is mine, so now I'm rewriting that module. If problem returns, I let you know.

No, not sensitive, this must work on all hardware.

**Comment by danmosemsft** [comment] 2018-08-16 17:05
I'll close this meantime, feel free to reopen if you determine it is .NET Core.

**Closed by danmosemsft** 2018-08-16 17:05 UTC
Labels: area-System.Diagnostics.Process, needs more info, question

**Comment by karelz** [comment] 2018-08-16 17:56
OK, let us know if you see it is a real problem in .NET Core.

**Comment by sirkadirov** [comment] 2018-08-16 18:07
OK, I'll stay in touch.

**Comment by sirkadirov** [comment] 2018-08-21 09:29
New info: maybe problem with threading: I use "testing subsystem" as many times separately, aslogical processors on PC. Maybe problem here?

**Comment by sirkadirov** [comment] 2018-08-21 16:29
@danmosemsft @karelz Maybe problem in .NET Core: nothing helped.

Minified repro: https://github.com/SirkadirovTeam/SimplePM_Server/tree/master/SProgramRunner/SRunner

And... as I said before, error found when project moved to .NET Core, on .NET Framework all worked...

**Comment by sirkadirov** [comment] 2018-08-26 08:59
@danmosemsft @karelz Checked many times, with  different ways of stream reading - problem exists...

### Base stream reader used
````c#
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace SProgramRunner
{
    
    public class AdvancedStreamReader
    {
        
        private const int BufferSize = 4096;

        private Stream _source;
        private MemoryStream _outputMemoryStream;

        private CancellationTokenSource _cancellationToken;

        public AdvancedStreamReader(Stream source)
        {
            
            _source = source;
            _outputMemoryStream = new MemoryStream();

        }

        public void Run()
        {
            
            _cancellationToken = new CancellationTokenSource();
            
            Task.Run(async () =>
            {
                
                var buffer = new byte[BufferSize];
                
                while (true)
                {
                    
                    _cancellationToken.Token.ThrowIfCancellationRequested();
                    
                    var count = await _source.ReadAsync(buffer, 0, BufferSize, _cancellationToken.Token);
                    
                    if (count <= 0)
                        break;
                    
                    await _outputMemoryStream.WriteAsync(buffer, 0, count, _cancellationToken.Token);
                    
                    await _outputMemoryStream.FlushAsync(_cancellationToken.Token);
                    
                }
                
            }, _cancellationToken.Token);
            
        }

        public byte[] KillAndGet()
        {
            
            _cancellationToken.Cancel();
            
            return _outputMemoryStream.ToArray();

        }
        
    }
    
}
````
#### Exec this reader
````c#
process.Start();
_outputStreamReader = new AdvancedStreamReader(_process.StandardOutput.BaseStream);
_outputStreamReader.Run();
````
on process exited:
````c#
_programRunningResult.ProgramOutputData = _outputStreamReader.KillAndGet();
````

Error - empty output on small count of tests from 50-100 or more... And this is not my code.

**Hope this can help to identify the problem. Now working on repro.**

**Comment by stephentoub** [comment] 2018-09-27 00:36
> any thoughts come to mind?

Not until we have a repro :)

That said, accessing StreamReader.BaseStream is a bit suspicious.  The StreamReader could have buffered data from the stream, such that it's been consumed from the Stream and is sitting in the StreamReader's buffer.  The shared code isn't doing any manipulation of the reader, so this may not be the issue, but that's why having a repro that actually shows the problem is important.

**Comment by sirkadirov** [comment] 2018-09-27 04:35
@stephentoub I'll re-try to create a working repro.
