### ISSUE TITLE
System.Collections.Immutable reference assembly bugfix

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#31475] opened 2018-07-30 15:14 UTC
System.Collections.Immutable 1.5.0 (used from .NET Framework 4.6.2) demonstrates the same issue as https://github.com/dotnet/corefx/issues/28870:

![image](https://user-images.githubusercontent.com/8040367/43403091-3f52e208-93e2-11e8-9f2e-18ae937501a9.png)

([thisisfine.gif](https://imgur.com/gallery/3dWKFGG))

I spotted this in a coworker's PR today and it makes me very uneasy. @tannergooding pointed out that this has already been fixed in master: https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/ref/System.Collections.Immutable.cs#L98 Would you please publish a release version of System.Collections.Immutable with this fix so that we can compile against it?

**Comment by nguerrera** [comment] 2018-07-30 16:06
This is a compiler issue, not a reference assembly issue. 

See https://github.com/dotnet/roslyn/pull/25886 and the discussion there.

That array field on line 98 (of reference type) is dropped by the compiler when the assembly is imported.

The behavior you are seeing would reproduce if you compiled against the System.Collections.Immutable implementation assembly, or an assembly generated by the compiler's /refout switch. I suspect 1.5.0 already has that field, but even if it does not, adding it won't fix the issue.

We decided not to hack around the issue by putting a dummy int field in these cases because it would create inconsistent behavior between implementation assemblies (or /refout) and the more complex corefx reference assemblies, and therefore be very difficult to reason about. Reference assemblies should preserve enough information to substitute for the implementation assembly at compile time. They should not add information to trick the compiler into different behavior.

Fixing the compiler issue was deemed too breaking precisely because it impacts common types like CancellationToken and ImmutableArray. My hope is that we'll get "diagnostic waves" (commonly called "warning waves", but I want errors for cases like this) as a way to address this.

**Comment by nguerrera** [comment] 2018-07-30 16:06
cc @gafter @agocke @jaredpar @weshaggard

**Comment by gafter** [comment] 2018-07-30 16:54
@nguerrera The compilers do pay attention to these private fields in "strict" more, which some people use, and we intend to support that more widely with the first warning waves in C# 8. Without fields in the reference assembly, that will not work.

**Comment by jnm2** [comment] 2018-07-30 16:57
Workaround for now discovered by @nguerrera: `<Features>Strict</Features>` in the project file. I hadn't actually tried it. Thank you! 🎉

**Comment by nguerrera** [comment] 2018-07-30 17:00
@gafter the surrogate fields of reference type are in the reference assembly.

**Comment by nguerrera** [comment] 2018-07-30 17:01
They were not in old versions but that was already fixed.

**Comment by jnm2** [comment] 2018-07-31 12:45
Heh, I was apparently late to the party. Saw the twitter conversation last night and just now saw https://github.com/dotnet/corefx/issues/31456.

**Closed** 2018-08-01 16:08 UTC
Labels: area-System.Collections, question
