### ISSUE TITLE
GetResponse_UseDefaultCredentials_ExpectSuccess test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16310] opened 2017-02-20 00:32 UTC
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_release/102/

System.Net.Tests.HttpWebRequestHeaderTest.GetResponse_UseDefaultCredentials_ExpectSuccess(remoteServer: https://corefx-net.cloudapp.net/Echo.ashx) [FAIL]
        System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)
        ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
        -------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(989,0): at System.Net.HttpWebRequest.GetResponse()
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/tests/HttpWebRequestHeaderTest.cs(47,0): at System.Net.Tests.HttpWebRequestHeaderTest.GetResponse_UseDefaultCredentials_ExpectSuccess(Uri remoteServer)
           ----- Inner Stack Trace -----
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(487,0): at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1192,0): at System.Net.HttpWebRequest.<SendRequest>d__188.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs(984,0): at System.Net.HttpWebRequest.GetResponse()
           ----- Inner Stack Trace -----
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs(637,0): at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs(864,0): at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)

**Comment by Jiayili1** [comment] 2017-02-21 06:58
This test failed on OuterLoop_Fedora23_release (build#109), detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_fedora23_release/109/testReport/System.Net.Tests/HttpWebRequestHeaderTest/GetResponse_UseDefaultCredentials_ExpectSuccess_remoteServer__https___corefx_net_cloudapp_net_Echo_ashx_/

**Comment by stephentoub** [comment] 2017-02-21 16:15
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_portablelinux_release/20/

**Comment by Priya91** [comment] 2017-02-21 22:28
Dupe of #16201

**Closed by Priya91** 2017-02-21 22:28 UTC
Labels: area-System.Net.Http, blocking-clean-ci, test-run-core
