### ISSUE TITLE
[ManagedHandler] Hit assert during local test run for ResponseStreamTest

### ISSUE THREAD

**Issue by pjanotti** [dotnet/corefx#26903] opened 2018-02-06 21:15 UTC
/cc @karelz @geoffkizer @stephentoub 

This is not happening on every run and prevents the generation of testResults.xml so I may have missed some other occurrences of it. I will try to see if it repros in other boxes and also to capture a dump. 

https://github.com/dotnet/corefx/blob/6f8a600be95671162bd4de3014adafabe0a0e5ed/src/System.Net.Http/src/System/Net/Http/Managed/HttpConnection.cs#L1181

```
  Assertion Failed
  34 != 32
  
     at System.Net.Http.HttpConnection.ReturnConnectionToPoolCore() in C:\s\github\pjanotti\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 1181
     at System.Net.Http.HttpConnection.ReturnConnectionToPool() in C:\s\github\pjanotti\corefx\src\System.Net.Http\src\System\Net\Http\Managed\HttpConnection.cs:line 1143
     at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken) in C:\s\github\pjanotti\corefx\src\System.Net.Http\src\System\Net\Http\Managed\ContentLengthReadStream.cs:line 60
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in E:\A\_work\1024\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 922
     at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken)
     at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\s\github\pjanotti\corefx\src\System.Net.Http\src\System\Net\Http\Managed\ContentLengthReadStream.cs:line 28
     at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count) in E:\A\_work\1024\s\src\mscorlib\src\System\IO\Stream.cs:line 376
     at System.Net.Http.Functional.Tests.ResponseStreamTest.ReadAsStreamHelper(IPEndPoint serverEndPoint) in C:\s\github\pjanotti\corefx\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 253
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1024\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in E:\A\_work\1024\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 546
     at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 75
     at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 107
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1024\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
     at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 89
     at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitWorkerThread.cs:line 37
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1024\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in E:\A\_work\1024\s\src\mscorlib\src\System\Threading\Tasks\Task.cs:line 2440
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\1024\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 166
```

**Comment by stephentoub** [comment] 2018-02-06 21:17
https://github.com/dotnet/corefx/issues/26754

**Comment by karelz** [comment] 2018-02-06 21:24
Duplicate of #26754

**Closed by karelz** 2018-02-06 21:24 UTC
Labels: area-System.Net.Http.ManagedHandler
