### ISSUE TITLE
StringReader.ReadLine does not read last line if it's empty

### ISSUE THREAD

**Issue by tylerl0706** [dotnet/corefx#32990] opened 2018-10-23 20:03 UTC
Consider the following text with 2 lines (one with content, one blank):

```
asdf

```

Load it into a StringReader and do the following:

```csharp
var reader = new System.IO.StringReader(text);
reader.ReadLine(); // gives 'asdf'
reader.ReadLine(); // gives null
```

I would expect that the second ReadLine would give an empty string because there is still an additional line in the text. null would mean that there is no additional lines in this text...

Is this behavior by-design? Seems a bit strange if it is.

**Comment by vexx32** [comment] 2018-10-23 20:10
Does an intermediary line that is blank get read properly?

**Comment by tylerl0706** [comment] 2018-10-23 20:13
Yes it does.

Example:

```
asdf

asdf
```

Gives you:
```
"asdf"
""
"asdf"
null
```

**Comment by tylerl0706** [comment] 2018-10-23 20:14
and one with two newlines at the end behaves strangely:

```
asdf


```

gets you:

```
"asdf"
""
null
```

**Comment by rjmholt** [comment] 2018-10-23 20:58
Here's a fuller description of the various behaviours:

```csharp
using System;
using System.IO;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Text;

namespace readline
{
    class Program
    {
        private static readonly string[] s_testStrings = new []
        {
            "a\nb\nc",
            "a\nb\nc\n",
            "a\r\nb\r\nc",
            "a\r\nb\r\nc\r\n"
        };

        private static readonly IReadOnlyDictionary<string, Func<string, string[]>> s_splitFuncs = new Dictionary<string, Func<string, string[]>>
        {
            { nameof(SplitWithStringReader),  SplitWithStringReader },
            { nameof(SplitWithStringSplit),  ((s) => SplitWithStringSplit(s)) },
            { $"{nameof(SplitWithStringSplit)}_RemoveEmpty", ((s) => SplitWithStringSplit(s, removeEmptyEntries: true)) },
            { nameof(SplitWithRegex), SplitWithRegex },
            { nameof(SplitManually), SplitManually }
        };

        static void Main(string[] args)
        {
            foreach (string str in s_testStrings)
            {
                string escapedStr = CSharpEscapeString(str);
                Console.WriteLine($"==== {escapedStr} ====");

                foreach (KeyValuePair<string, Func<string, string[]>> splitPair in s_splitFuncs)
                {
                    string[] result = splitPair.Value(str);

                    string joinedResult = String.Join('/', result);
                    int lineCount = result.Length;

                    Console.WriteLine($"\t{splitPair.Key}:");
                    Console.WriteLine($"\t\t{joinedResult}");
                    Console.WriteLine($"\t\tCount: {lineCount}");
                }

                Console.WriteLine();
            }
        }

        private static string[] SplitWithStringReader(string s)
        {
            var acc = new List<string>();
            using (var sr = new StringReader(s))
            {
                string curr;
                while ((curr = sr.ReadLine()) != null)
                {
                    acc.Add(curr);
                }
                
            }
            return acc.ToArray();
        }

        private static string[] SplitWithStringSplit(string s, bool removeEmptyEntries = false)
        {
            return s.Split(new [] { "\n", "\r\n" }, removeEmptyEntries ? StringSplitOptions.RemoveEmptyEntries : StringSplitOptions.None);
        }

        private static string[] SplitWithRegex(string s)
        {
            var notNewline = new Regex(@"\r?\n");
            return notNewline.Split(s);
        }

        private static string[] SplitManually(string s)
        {
            var acc = new List<string>();
            var curr = new StringBuilder();
            bool sawCR = false;
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] == '\r')
                {
                    sawCR = true;
                    continue;
                }

                if (s[i] == '\n')
                {
                    acc.Add(curr.ToString());
                    curr.Clear();
                    sawCR = false;
                    continue;
                }

                if (sawCR)
                {
                    curr.Append('\r');
                    sawCR = false;
                }
                curr.Append(s[i]);
            }
            acc.Add(curr.ToString());

            return acc.ToArray();
        }

        private static string CSharpEscapeString(string s)
        {
            var sb = new StringBuilder().Append('"');
            foreach (char c in s)
            {
                sb.Append(CSharpEscapeChar(c));
            }
            sb.Append('"');

            return sb.ToString();
        }

        private static string CSharpEscapeChar(char c)
        {
            switch (c)
            {
                case '\a':
                    return "\\a";

                case '\b':
                    return "\\b";

                case '\f':
                    return "\\f";

                case '\n':
                    return "\\n";

                case '\r':
                    return "\\r";

                case '\t':
                    return "\\t";

                case '\v':
                    return "\\v";

                case '\\':
                    return "\\\\";

                case '\0':
                    return "\\\0";

                case '"':
                    return "\"";

                default:
                    return c.ToString();
            }
        }
    }
}
```

This program will print the following:

```text
==== "a\nb\nc" ====
        SplitWithStringReader:
                a/b/c
                Count: 3
        SplitWithStringSplit:
                a/b/c
                Count: 3
        SplitWithStringSplit_RemoveEmpty:
                a/b/c
                Count: 3
        SplitWithRegex:
                a/b/c
                Count: 3
        SplitManually:
                a/b/c
                Count: 3

==== "a\nb\nc\n" ====
        SplitWithStringReader:
                a/b/c
                Count: 3
        SplitWithStringSplit:
                a/b/c/
                Count: 4
        SplitWithStringSplit_RemoveEmpty:
                a/b/c
                Count: 3
        SplitWithRegex:
                a/b/c/
                Count: 4
        SplitManually:
                a/b/c/
                Count: 4

==== "a\r\nb\r\nc" ====
        SplitWithStringReader:
                a/b/c
                Count: 3
        SplitWithStringSplit:
                a/b/c
                Count: 3
        SplitWithStringSplit_RemoveEmpty:
                a/b/c
                Count: 3
        SplitWithRegex:
                a/b/c
                Count: 3
        SplitManually:
                a/b/c
                Count: 3

==== "a\r\nb\r\nc\r\n" ====
        SplitWithStringReader:
                a/b/c
                Count: 3
        SplitWithStringSplit:
                a/b/c/
                Count: 4
        SplitWithStringSplit_RemoveEmpty:
                a/b/c
                Count: 3
        SplitWithRegex:
                a/b/c/
                Count: 4
        SplitManually:
                a/b/c/
                Count: 4
```

**Comment by karelz** [comment] 2018-10-23 21:13
Seems like the newline is considered part of the current line, it does not mean "there is another line behind".
Does it behave the same way on .NET Framework and .NET Core?
It is likely not something we can change due to compat ...

**Comment by rjmholt** [comment] 2018-10-23 22:06
Confirmed that it's the same in Framework, via Windows PowerShell:

```powershell
PS C:\Users\rob\Documents\Dev\sandbox\readline> Add-type -TypeDefinition @"
>> using System;
>>
>> public class Main2
>> {
>> public static void Run()
>> {
>> string x = "a\nb\nc\n";
>> var sr = new System.IO.StringReader(x);
>> var acc = new System.Collections.Generic.List<string>();
>> int count = 0;
>> string curr = null;
>> while ((curr = sr.ReadLine()) != null)
>> {
>> count++;
>> acc.Add(curr);
>> }
>>
>> Console.WriteLine("Count: " + count.ToString());
>> Console.WriteLine("String: " + String.Join("/", acc.ToArray()));
>> }
>> }
>> "@

PS C:\Users\rob\Documents\Dev\sandbox\readline> [Main2]::Run()
Count: 3
String: a/b/c
```

**Comment by rmkerr** [comment] 2018-10-23 22:40
Echoing what @karelz said - it looks like the logic here is that a line is terminated by either a newline, or the end of the file. 

With the current parsing users don't have to special case the last line. For example:
```
"line1\n" +
"line2\n" +
"line3\n"
```
I think that the intuitive thing to do is to parse that as three lines. 

On the other hand, if you want an empty line at the end of the file, you can make that behavior explicit with an additional newline:
```
"line1\n" +
"line2\n" +
"line3\n" +
"\n"
```

It isn't perfect for all situations, but I think it's a reasonable behavior. Since it's consistent with .NET Framework I think we should probably leave it as-is.

**Comment by Clockwork-Muse** [comment] 2018-10-23 23:11
This is, essentially, [the way Unix views text files](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file): all lines in a file properly end in a new-line character.

It would, essentially, vastly simplify parsing, because you just consider characters until you find the eol, and eof if after the last eol character.

**Comment by rmkerr** [comment] 2018-10-24 17:08
Since this is a known behavior (and is something we probably can't change), I'm going to close this issue. 

Thanks everyone for the info. Even though no changes are likely to come out of it, it was an informative thread.

**Closed by rmkerr** 2018-10-24 17:08 UTC
Labels: area-System.IO, question

**Comment by rjmholt** [comment] 2018-10-24 17:20
@rmkerr "Known behaviour" might be a stretch since this information does not appear in the documentation -- we hit it the hard way. Is there somewhere we can open a PR to add a note in the docs?

**Comment by tylerl0706** [comment] 2018-10-24 17:29
I figured that nothing would change here due to back-compat (makes sense) - How about an issue on the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringreader.readline?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_StringReader_ReadLine) to call out this limitation.

Just so everyone understands what the use-case was... this is for [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the PowerShell extension for VSCode. 

We read in the contents of files and break them down line-by-line. We were seeing crashes when a user had a newline at EOF because the size of the array that stored all the lines would be one off (because the new line at EOF would not be added to the array because it was null)

[Code in reference](https://github.com/PowerShell/PowerShellEditorServices/blob/042f2e0b7f70ddf7316458c54657b8e2ad71d095/src/PowerShellEditorServices/Workspace/ScriptFile.cs#L224-L236)

**Comment by tylerl0706** [comment] 2018-10-24 17:30
oh there were other comments lol

**Comment by tylerl0706** [comment] 2018-10-24 17:39
Opened an issue here so we're good: https://github.com/dotnet/docs/issues/8612
