### ISSUE TITLE
Potential unexpected null in httpclient

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/corefx#26054] opened 2017-12-26 04:50 UTC
This [SO](https://stackoverflow.com/questions/47973590/httpclient-header-getting-nulled-when-using-in-async-methods) question alludes to a potential unexpected header being null.

This [line](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L600) does not check for header value being possibly null, leading to the argument null exception. 

In case the SO thread disappears here is the call stack, not that it is in net 4.6.1 and not core, so I'm 50/50 if this exists here or not.

#### Callstack
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Enter(Object obj)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.AddHeaders(HttpHeaders sourceHeaders)
   at System.Net.Http.Headers.HttpRequestHeaders.AddHeaders(HttpHeaders sourceHeaders)
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PutAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)
   at Attributes.Controllers.AttributesBaseController.<UpdateAttributes>d__6.MoveNext() in D:\Git\PortalSystem\Attributes\Controllers\AttributesBaseController.cs:line 42

**Comment by mqudsi** [comment] 2017-12-26 05:15
Shouldn’t you test it against .NET Core before opening this issue?

**Comment by kevingosse** [comment] 2017-12-26 10:11
The `HeaderStoreItemInfo` wraps the value of the header. So even if the value of the header is null, the `HeaderStoreItemInfo` itself shouldn't ever be. 

When adding a header, `PrepareHeaderInfoForAdd` is called: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L74

Which itself retrieves the existing `HeaderStoreItemInfo` if any, otherwise creates it: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L1037

What happens on the SO question is more likely a race condition from mutating the headers dictionary concurrently.

**Comment by yishaigalatzer** [comment] 2017-12-28 23:05
@mqudsi given a limited amount of available time, I could have chosen to ignore it or to post, these race conditions (as describe in the SO post) are hard to reproduce, and IMHO it is better to raise the awareness that to let things slide so they break customers. If the team doesn't want such bug reports (@karelz ?), I'd be happy not to post again, unless I have a fully reproducible problem.

**Comment by karelz** [comment] 2017-12-29 00:06
IMO it doesn't hurt to have such reports, however, it is good to clarify the background: If repro was attempted, on which platforms and if it was not attempted, then why (e.g. it is extremely rare).
Understanding that if it is not actionable for us, we may close it, also helps :)

Right now it is waiting on code expert to take a look and judge (@davidsh)

**Comment by davidsh** [comment] 2017-12-30 05:52
>What happens on the SO question is more likely a race condition from mutating the headers dictionary concurrently.

Yes, this is probably a bug in both .NET Core and .NET Framework.  The headers dictionary object (HttpHeaders) itself is not thread safe.  Usually those header collections are used only for a single HttpRequestMessage or HttpResponseMessage.  But that header collection object is also used by HttpClient.DefaultRequestHeaders which is being shared in this case. So, there are potential race conditions.

To workaround this, you can avoid use HttpClient.DefaultRequestHeaders.  Instead, just create HttpRequestMessage's yourself and use HttpClient.SendAsync() to send the request.

This particular code has existed in the .NET Framework for a long time (since .NET 4.5 when HttpClient was released). We haven't had many customer issues reported on this.

**Comment by mikedn** [comment] 2017-12-30 09:26
> Yes, this is probably a bug in both .NET Core and .NET Framework. The headers dictionary object (HttpHeaders) itself is not thread safe.

This does not look like a framework bug to me. Even if that dictionary would be thread safe the way `DefaultRequestHeaders` is used in the SQ question is simply incorrect. There will be multiple threads attempting to clear the headers and add a certain header back so it's possible that a request will be sent with no headers (or with the wrong headers if some other code adds something different from `application/json`).

**Comment by davidsh** [comment] 2018-01-08 22:15
Based on the discussions in this thread it does appear that the original issue marked in the SO article is not a bug in the .NET Core code but rather a misuse of the Http APIs.

So, closing this issue.

**Closed by davidsh** 2018-01-08 22:15 UTC
Labels: area-System.Net.Http, bug
