### ISSUE TITLE
System.Configuration.ConfigurationManager uap-aot test fails with cannot load assembly System 

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#21000] opened 2017-06-13 19:06 UTC

**Comment by AtsushiKan** [comment] 2017-08-11 16:08
ClientConfigPaths constructor is attempting a `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);` which is throwing an InvalidOperationException from inside WInRT. I assume this is simply an artifact of ILC "UWP" runs not actually running as an AppX.

https://github.com/dotnet/corefx/blob/2c2171f4098abb6d0285e9a115b0d592121057d4/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs#L112

**Comment by danmosemsft** [comment] 2017-08-11 16:47
Dupe of https://github.com/dotnet/corefx/issues/21000#issuecomment-321854150

**Closed by danmosemsft** 2017-08-11 16:47 UTC
Labels: area-System.Configuration, bug, test-run-uwp-ilc

**Comment by krwq** [comment] 2018-04-04 19:41
@danmosemsft this is closed as a dup of itself. There are 4 testcases releated to this - I'm not sure if they should be reenabled or this is by design:

```
System.Configuration.ConfigurationManager/tests/Mono/ConfigurationSectionGroupTest.cs:49:        [ActiveIssue(21000, TargetFrameworkMonikers.UapAot)]
System.Configuration.ConfigurationManager/tests/System/Configuration/SectionGroupsTests.cs:57:        [ActiveIssue(21000, TargetFrameworkMonikers.UapAot)]
System.Configuration.ConfigurationManager/tests/System/Configuration/UriSectionTests.cs:42:        [ActiveIssue(21000, TargetFrameworkMonikers.UapAot)]
System.Configuration.ConfigurationManager/tests/System/Configuration/UriSectionTests.cs:55:        [ActiveIssue(21000, TargetFrameworkMonikers.UapAot)]
```
