### ISSUE TITLE
Https requests on linux distro fails with SSL error

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#38467] opened 2019-06-11 21:30 UTC
**.NET Core Version:**
2.1.9

**OS version and info:**
Debian GNU/Linux 10 (buster),
and just in case -- OpenSSL 1.1.1b

**Error:**

```
HTTP exception in auth.login request handler: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LiveShare.Tracing.TracingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\238\s\src\Tracing\Tracing\TracingHttpMessageHandler.cs:line 63
   at Microsoft.Cascade.Agent.ForwardResponseMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\A\_work\238\s\src\Agent\ForwardResponseMessageHandler.cs:line 50
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by davidsh** [comment] 2019-06-11 21:35
>OS version and info:
Debian GNU/Linux 10 (buster),
and just in case -- OpenSSL 1.1.1b

@bartonjs

**Comment by bartonjs** [comment] 2019-06-11 22:04
> and just in case -- OpenSSL 1.1.1b

Nah, you're loading 1.0 :).

Dupe of https://github.com/dotnet/corefx/issues/33179.

The three solutions:

1) Comment out the `ssl_conf` value in /etc/ssl/openssl.cnf
2) Uninstall OpenSSL 1.0.x
3) Set CLR_OPENSSL_VERSION_OVERRIDE=1.1 to force OpenSSL 1.1 to be used.  (2.1 prefers binding to OpenSSL 1.0.x because that's what it shipped with... it only uses 1.1 if explicitly told to, or if 1.0 isn't available)

**Closed by bartonjs** 2019-06-11 22:04 UTC
Labels: area-System.Net.Http, os-linux

**Comment by Priya91** [comment] 2019-06-12 16:52
@bartonjs My understanding was that irrespective of the openssl version loaded, .netcore should be compatible with the native implementation used.. Is this the case where .netcore is detecting openssl 1.0, when in fact it is loading 1.1, hence the mismatch? I don't understand why the user needs to do any configuration if he has both versions of openssl..

**Comment by bartonjs** [comment] 2019-06-12 21:54
When OpenSSL 1.0 is loaded it loads the config file (/etc/ssl/openssl.cnf), but Debian's default configuration file now has an option in it that OpenSSL 1.0 says is invalid.

.NET works with OpenSSL 1.0 or 1.1; in this case, Debian's OpenSSL 1.0 doesn't work with Debian's (default) OpenSSL config file.

**Comment by Priya91** [comment] 2019-06-13 21:34
Hmm, which stable version of .NETCore loads OpenSSL 1.1 by default? So that we can upgrade our app to that version, .NET Core 3.0 is still in preview mode, hence we cannot upgrade to that per the release rules.

**Comment by bartonjs** [comment] 2019-06-13 21:53
@Priya91 2.1 and 2.2 are 1.0 preferred, 1.1 possible.  3.0 is 1.1 preferred, 1.0 possible.  So there is no RTM version that prefers 1.1
