### ISSUE TITLE
ConsoleColor.White isn't white on macosx

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#25634] opened 2017-12-01 14:17 UTC
_From @equiman on December 1, 2017 13:25_

I'm working in a console project in dotnet core. 
But white color on mac is represented as lighter gray and not as white color.

Example img: https://ibb.co/kKoXPb
1) is background color in terminal by default.
2) is `Console.BackgroundColor = ConsoleColor.White; ` but is represented as lighter gray. 

I'm using default terminal application on macos.

$> dotnet --version
2.0.0

$> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003

Code using to format with color:
https://github.com/equiman/hardhat/blob/master/dev/tools/Colorify.cs

_Copied from original issue: dotnet/coreclr#15320_

**Comment by tarekgh** [comment] 2018-03-10 18:52
@equiman 

The framework is sending the right escape code to the terminal for the bright white color

```
Esc [107m
```

but the terminal chooses to display the color as of the kind of light gray. you can manually see that when issuing the terminal command 

```
echo -e "\e[107mHello"
```

and you'll see the terminal is displaying the same color.

**Comment by equiman** [comment] 2018-03-11 19:23
It's a terminal problem?

**Comment by wfurt** [comment] 2018-03-11 20:39
You can try iTerm2 for example. Some of it also depends on TERM variable. Different terminals can use different escape sequence to switch colors. That comes from terminfo database. The actual color is handled by terminal. You can also look at #23381 as there was long discussion about colors.

**Comment by wfurt** [comment] 2018-03-11 20:43
BTW You can also try to switch to Bright/Bold mode @equiman. There is another good article here: https://askubuntu.com/questions/558280/changing-colour-of-text-and-background-of-terminal

**Comment by tarekgh** [comment] 2018-03-12 16:36
Closing this one as a duplicate of #23381

@equiman feel free to follow up on #23381 or post any more questions there. 

@wfurt do we have any idea what should be done for #23381? I mean is this will be by design or we'll have to try something else?

**Closed by tarekgh** 2018-03-12 16:36 UTC
Labels: area-System.Console
