### ISSUE TITLE
Regression: After using `less` with PowerShell Core, cursor keys return the VT100 escape sequence to ReadKey()

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#40557] opened 2019-08-24 14:22 UTC
When using PowerShell 7 built on .NET Core 3.0:

```powershell
1 | less
q # to quit
```

Now use the `UpArrow` key to go back in history

Expected:

```powershell
1 | less  #since this was the last command
```

Actual:

```none
nothing, as PSReadLine receives `<ESC>A` (as two key presses) which is the VT100 escape sequence for up arrow
```

This repros on macOS and Linux.  If you use PowerShell Core 6.x (same version of PSReadLine is included) this doesn't repro as it's built on .NET Core 2.1.

Interestingly, if you use:

```powershell
"`e[2J"
```

This is the VT100 escape sequence to clear the screen, then the up arrow returns the correct key to [Console]::ReadKey() again instead of the up arrow escape sequence.
This will block the PowerShell 7 release.  https://github.com/PowerShell/PSReadLine/issues/1007

**Comment by stephentoub** [comment] 2019-08-24 14:29
cc: @tmds

**Comment by tmds** [comment] 2019-08-24 19:06
@SteveL-MSFT can you create a code snippit that uses Console and Process that reproduces the regression?

**Comment by tmds** [comment] 2019-08-24 20:56
I can reproduce the issue using this code:
```
            Console.ReadKey();
            Process p = Process.Start(new ProcessStartInfo { FileName = "less", RedirectStandardInput = true });
            p.StandardInput.Write("hello");
            p.StandardInput.Close();
            p.WaitForExit();
            System.Console.WriteLine(Console.ReadKey().Key);
```
The issue is we're not considering this process to be interactive:
https://github.com/dotnet/corefx/blob/e92b6d57af9b7299f2a6fca2a599f09dce4f672a/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L401-L402
The fix is to change this condition to `||` instead of `&&`.
When I change the code so it matches the current `usesTerminal` condition, the terminal is properly reconfigured when the child terminated:
```
            File.WriteAllText("/tmp/file", "hello");
            Console.ReadKey();
            Process p = Process.Start(new ProcessStartInfo { FileName = "less", Arguments = "/tmp/file" });
            p.WaitForExit();
            System.Console.WriteLine(Console.ReadKey().Key);
```

**Comment by tmds** [comment] 2019-08-24 21:03
While looking at the code in pal_console, I noticed another bug:
https://github.com/dotnet/corefx/blob/e92b6d57af9b7299f2a6fca2a599f09dce4f672a/src/Native/Unix/System.Native/pal_console.c#L192-L198
`VMIN` gets checked twice here. The last line should be checking `VTIME` instead.

**Comment by tmds** [comment] 2019-08-24 21:36
> The fix is to change this condition to || instead of &&.

For background, the reason this was using `&&` is that for cases where we want to make the echoing work, the child process would be using both stdin/stdout.

**Comment by tmds** [comment] 2019-08-26 14:58
> Does that mean something else is going to break as a result of the fix?

No. We'll be re-configuring the terminal for Console usage in more cases.

**Comment by stephentoub** [comment] 2019-08-29 17:42
Fixed by https://github.com/dotnet/corefx/pull/40661

**Closed by stephentoub** 2019-08-29 17:42 UTC
Labels: area-System.Console
