### ISSUE TITLE
BlockReflection attribute inclusion for assemblies that are used on uap

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#16022] opened 2017-02-10 02:04 UTC
Framework assemblies that are used on netcore50 should include `BlockReflectionAttribute=true` in their project file unless there's a good reason not to.

It seems like something happened to framework reflection blocking with e.g. Microsoft.CSharp.dll in the 5.2.2 framework metapackage for UWP apps.

I was helping out troubleshooting a UWP failure where the `dynamic` keyword support goo was trying to reflect on the CSharpGetMemberBinder type (a private type in the assembly), and the customer was getting a MissingMetadataException on 5.2.2 metapackage, while things worked fine with the previous metapackage. The key difference seems to be the absence of the attribute. Removing reflection blocking is a breaking change.

**Comment by MichalStrehovsky** [comment] 2017-02-10 02:05
Cc @weshaggard @morganbr @davidwrighton @zamont

**Comment by jkotas** [comment] 2017-02-10 06:25
Did not we agree to make things well work without it? This stuff is super fragile...

**Comment by tarekgh** [comment] 2017-02-10 16:28
CC @AtsushiKan

**Comment by MichalStrehovsky** [comment] 2017-02-10 17:54
> Did not we agree to make things well work without it? This stuff is super fragile...

Getting this to work all the time would require a change in default RD.XML reflection policy on UWP apps from:

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="*Application*" Dynamic="Required All" />
  </Application>
</Directives>
```

To:

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application Dynamic="All">
    <Assembly Name="*Application*" Dynamic="Required All" />
  </Application>
</Directives>
```

This change in policy comes with size on disk costs and compilation throughput costs. I don't remember an agreement about that.

This would still be breaking to apps that use the old form of the RD.XML (which is why the customer I was helping hit this by merely upgrading the framework metapackage). Upgrading framework metapackage should not be a breaking change.

**Comment by jkotas** [comment] 2017-02-10 18:13
> Upgrading framework metapackage should not be a breaking change.

If this bug is for servicing existing framework package, I agree - servicing upgrades of the framework metapackages should be breaking change. 

If this bug is to get this fixed in live master correctly, the framework package update will require matching toolset upgrade so I do not see a problem.

BlockReflectionAttribute have been used to communicate what types are part of the actual public surface vs. what types are internal implementation detail.

The same information is available in other form: The toolchain knows which assemblies and facades are part of the public surface and which ones are just internal implementation details. It can infer the reflection blocking form that. And the exceptions to this policy should be in rd.xml.

**Comment by morganbr** [comment] 2017-02-13 22:57
@MichalStrehovsky , that's a bit of an over-exaggeration. We've never had metadata for everything public in the framework, so we probably wouldn't add it for everything private in the framework. 

@jkotas , having the toolchain do reflection blocking stuff internally doesn't sound too unreasonable, though it would still need some indication that an assembly should go through the process (some CoreFX assemblies do reflect on their internals).

**Comment by MichalStrehovsky** [comment] 2017-02-13 23:02
> that's a bit of an over-exaggeration

As I wrote in the bug, the reason we hit this is because the DLR is reflecting on `CSharpGetMemberBinder` type in Microsoft.CSharp. That's a private type in Microsoft.CSharp. @jkotas suggested we make things work well without reflection blocking. How do you suggest we would fix it without the "over-exaggeration"?

**Comment by morganbr** [comment] 2017-02-13 23:09
@MichalStrehovsky , we have a few different tools for something like that:
1. Scoped rd.xml in the assembly. If the DLR is supposed to reflect on CSharpGetMemberBinder, we could add something like <Namespace Name="Microsoft.CSharp.RuntimeBinder" Dynamic="Required All" /> to Microsoft.CSharp.dll (Altering that to make actual sense with what the DLR does, of course. Maybe SubTypes is more appropriate or something).
2. Better analysis. Maybe the DLR does something that Project N's analyzer should know about, but doesn't.
3. Worst case -- blanket rd.xml in the assembly. We can at least hold expansion to assemblies that are likely to do lots of reflection crawling as Microsoft.CSharp might without dragging in metadata for the internals of, say, the CoreRT type loader.

Of course, for this case if that type isn't even supposed to be visible for the DLR to function correctly, I'm all for reflection blocking.

**Comment by MichalStrehovsky** [comment] 2017-02-13 23:15
@morganbr Yes, and that will solve this for the exact problem the original problem was about and nothing else.

Let's say that nobody wants to do 1-3 for each private type a random app in the future might reflect on. We're left with either the RD.XML I proposed, or reflection blocking. Let's just stay at "we need to restore reflection blocking, period", seems like we agree on that :).

**Comment by morganbr** [comment] 2017-02-13 23:20
@MichalStrehovsky , that sounds perfectly reasonable. I was assuming there was something DLR-specific here, but I agree we don't want random reflection walks into private code.

**Comment by jkotas** [comment] 2017-02-14 00:37
> If the DLR is supposed to reflect on CSharpGetMemberBinder, we could add something like to Microsoft.CSharp.dll 

Yes, it is what I meant by "the exceptions to this policy should be in rd.xml".

> @jkotas suggested we make things work well without reflection blocking

I meant to make reflection blocking work without corefx build magic that sprinkles BlockReflectionAttributes.

**Comment by tarekgh** [comment] 2017-03-02 17:07
I am moving this issue to corert according the conclusion in this discussion. if there is anything specific to Microsoft.CSharp need to be done we can open a new specific issue for that library.

**Comment by tarekgh** [comment] 2017-03-02 17:07
Issue moved to [dotnet/corert #2869](https://github.com/dotnet/corert/issues/2869) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MichalStrehovsky** [comment] 2017-03-02 17:11
@tarekgh This is a *regression* that is observable when upgrading to the latest framework using old and unpatched compiler. E.g. people using Visual Studio 2015 Update 3 will get a regression in their functionality just by upgrading to metapackage 5.2.2. This needs a framework fix.

Compiler fix that we discussed would be in Project N. We don't track Project N compiler issues on GitHub because nobody working on the Project N compiler is looking at that.

Cc @weshaggard

**Comment by tarekgh** [comment] 2017-03-02 17:38
logged a TFS bug to track this for the compiler https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/390112

**Comment by weshaggard** [comment] 2017-03-02 18:19
I agree with @MichalStrehovsky that we should probably fix Microsoft.CSharp to include the BlockReflection to handle the regression, @tarekgh can you file another issue for that? Once we get the compiler feature we should re-evaluate whether or not to remove that from all the corefx libraries.

**Comment by tarekgh** [comment] 2017-03-02 18:42
I reopened it and changed the area to Microsoft.CSharp as all discussions included here.

**Comment by danmosemsft** [comment] 2017-03-04 01:45
Did this regress because this condition is never true anymore?
https://github.com/dotnet/corefx/blob/master/dir.props#L77

**Comment by tarekgh** [comment] 2017-03-04 01:48
> Did this regress because this condition is never true anymore?

likely, but the proposed solution now is different than what we used to do.

**Comment by morganbr** [comment] 2017-03-04 01:52
@danmosemsft  If the fix is that simple, getting it in would be helpful to efforts to test new versions of CoreFX and ProjectN with each other since we're seeing other possible regressions from unexpected reflectable framework internals.

CC @DnlHarvey @joperezr

**Comment by weshaggard** [comment] 2017-03-04 02:02
>Did this regress because this condition is never true anymore?

Currently the repo has all things without this because of the at condition, but we haven't shipped any of this yet. This issue is about the Microsoft.CSharp regression which was caused by another issue I can talk to you offline if you want to know the details.

**Comment by MattWhilden** [comment] 2017-04-04 18:50
FWIW, this issue was reported by another customer. I'm not sure what the accepted patter here is fur +1.

http://stackoverflow.com/questions/43175500/building-with-net-native-tool-chain-causes-error-with-missing-property-in-dynam/43195100#43175500

**Comment by danmosemsft** [comment] 2017-04-05 06:42
This should be working now I thought

**Comment by weshaggard** [comment] 2017-04-05 19:04
@danmosemsft while this may be fixed in master (although worth verifying), it doesn't help folks today. If we feel this is a big enough issue then we should probably consider servicing this library with the fix.

**Comment by danmosemsft** [comment] 2017-06-22 18:59
@AtsushiKan if I read this right, this is not part of the current release, it's a servicing request. If so you can move out to 2.1.

**Closed** 2018-09-11 21:01 UTC
Labels: area-Microsoft.CSharp, os-windows-uwp
