### ISSUE TITLE
Managed WebSocket implementation on Windows 7?

### ISSUE THREAD

**Issue by JustArchi** [dotnet/corefx#24249] opened 2017-09-26 03:27 UTC
Recently we've stumbled upon particular issue of Windows 7 SP1 not supporting WebSockets natively, as they were introduced in Windows 8 / Server 2012. Check out https://github.com/SteamRE/SteamKit/issues/455 as a reference of original issue.

Since there is managed implementation of websocket that is apparently **[already possible to be used on Windows](https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets.Client/src/System.Net.WebSockets.Client.csproj#L7-L9)**, would it make sense to use it on Windows 7 as a platform that does not support WinSocket Windows stack natively? Or maybe it's already possible?

Thank you in advance.

**Comment by davidsh** [comment] 2017-09-26 03:30
Duplicate of #9503.

**Closed** 2017-09-26 03:30 UTC
Labels: area-System.Net
