### ISSUE TITLE
Got Illegal character error when the file name is encoded in GBK

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/corefx#21701] opened 2017-06-29 07:21 UTC
Hi All,

We just encountered an issue that the enumeration function reports error of illegal character when there's GBK Chinese character in the directory. We found this issue on RedHat 7.3 with $LANG and $LC_ALL set to "zh_CN.GBK". It works well with Chines character with UTF-8 encoding.
The issue can be reproduced by following code: 
```c#
using System;
using System.IO;

namespace netcoretest
{
    class Program
    {
        static void Main(string[] args)
        {
            foreach (var fileItem in Directory.EnumerateFileSystemEntries(".", "*", SearchOption.TopDirectoryOnly))
            {
                Console.WriteLine(fileItem);
            }
        }
    }
}

```
It reports an error as following: 

```
Unhandled Exception: System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.PathInternal.CheckInvalidPathChars(String path)
   at System.IO.Path.Combine(String path1, String path2)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.<Enumerate>d__11.MoveNext()
   at netcoretest.Program.Main(String[] args) in /home/xtest/netcoretest/Program.cs:line 10
Aborted (core dumped)
```

GBK is an encoding standard defined by China. Does .Net Core framework have plan to support other encoding besides Unicode? If so, could you share your schedule?

Thanks
Emma

**Comment by karelz** [comment] 2017-06-29 08:35
Does it work fine without .NET Core involved on RedHat? (trying to rule out OS problems)
@tarekgh are you the right person to take a look?

**Comment by tmds** [comment] 2017-06-29 11:48
The bytes that make up the filename are decoded using `Encoding.Default`, which is documented to return `Gets an encoding for the operating system's current ANSI code page.`

For netcore, the encoding is fixed to UTF8 (from https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/Encoding.cs#L86-L87)
```C#
        // For netcore we use UTF8 as default encoding since ANSI isn't available
        private static readonly UTF8Encoding.UTF8EncodingSealed s_defaultEncoding  = new UTF8Encoding.UTF8EncodingSealed(encoderShouldEmitUTF8Identifier: false);

        // Returns an encoding for the system's current ANSI code page.
        public static Encoding Default => s_defaultEncoding;
```

**Comment by karelz** [comment] 2017-06-29 16:03
@tmds what do you suggest? Change the default? Or some opt-in for customers?

**Comment by tmds** [comment] 2017-06-29 16:13
@karelz the default should reflect the operating systems' current ANSI code page. This isn't implemented, it is always returning UTF8. I guess that is the root cause of the issue.

**Comment by tarekgh** [comment] 2017-06-29 16:35
@tmds 

> the default should reflect the operating systems' current ANSI code page. This isn't implemented, it is always returning UTF8. I guess that is the root cause of the issue

This is not true for net core since day one. UTF8 should be the default as this is the recommended behavior. your scenario will be broken anyway if someone using such file names encoded in such codepage and changed the system codepage to something else. or moved teh file to other machine that don't have this encoding as the default. this is why we are saying always using UTF8 will protect you from running into these broken scenarios.

Also, ansi/asciii encoding are not available by default in net core and you have to opt-in to use such encoding. the link https://msdn.microsoft.com/en-us/library/mt643901(v=vs.110).aspx has the info to opt-in.

I believe this issue should be addressed from System.IO.FileSystem and not really the encoding. when reading the file names from the OS we should either always get it in utf8 or we should throw if we need to have encoding conversion and the encoding is not available. I am going to tag this as System.IO issue. 

@ianhays @JeremyKuhne

**Comment by ianhays** [comment] 2017-06-29 18:03
>I believe this issue should be addressed from System.IO.FileSystem and not really the encoding. when reading the file names from the OS we should either always get it in utf8 or we should throw if we need to have encoding conversion and the encoding is not available. I am going to tag this as System.IO issue.

We do, we use [Marshal.PtrToStringAnsi](https://msdn.microsoft.com/en-us/library/7b620dhe(v=vs.110).aspx) which converts ansi=>unicode. Is that not adequate if we're defaulting the encoding to UTF8 in all cases i.e. does Marshal think the native string is already in unicode since that's the default encoding?

**Comment by tmds** [comment] 2017-06-29 18:46
> We do, we use Marshal.PtrToStringAnsi which converts ansi=>unicode. Is that not adequate if we're defaulting the encoding to UTF8 in all cases i.e. does Marshal think the native string is already in unicode since that's the default encoding?

`Marshal.PtrToStringAnsi` calls [String(sbyte*)](https://github.com/dotnet/coreclr/blob/906f60ce3c55ab0cc41765d9eeea542ec65ff737/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L135)
Which uses [Encoding.Default](https://msdn.microsoft.com/en-us/library/k9s9t975(v=vs.110).aspx).

**Comment by ianhays** [comment] 2017-06-29 18:51
>Which uses Encoding.Default.

Yeah, that'll do it then. It seems like we'll run into issues anywhere that function is used since it's not really doing conversion anymore, regardless of the *actual* system encoding.

**Comment by tarekgh** [comment] 2017-06-29 19:25
> SMarshal.PtrToStringAnsi calls String(sbyte*) Which uses Encoding.Default.

This is not calling Encoding.Default. it is eventually calls 

https://github.com/dotnet/coreclr/blob/a3af468e2f731e2d7b071fb82bd2eeb62cd8db0d/src/pal/src/locale/unicode.cpp#L667

passing CP_ACP

and the CP_ACP is hard coded for Linux to UTF8 

https://github.com/dotnet/coreclr/blob/a3af468e2f731e2d7b071fb82bd2eeb62cd8db0d/src/pal/src/locale/unicode.cpp#L81

@ellismg looks you defaulted that on Linux. any comment about that?

**Comment by ellismg** [comment] 2017-06-29 19:46
I just think we decided to get on the UTF8 plan completely on *nix.  There used to be a bunch of code to deal with doing code page conversions (but it was OSX specific, IIRC from the Silverlight days) and just forcing UTF8 let us delete all that stuff. @jkotas

**Comment by tarekgh** [comment] 2017-06-29 20:13
@karelz I moved this issue to 2.1.0. let me know if you still want keep this for 2.0

**Comment by jkotas** [comment] 2017-06-29 20:25
> the default should reflect the operating systems' current ANSI code page

Current ANSI code page is Windows-specific construct. There has never been anything equivalent that got uniformly supported across Linux ecosystem.

Recent enough Linux distributions are set up such that everything is using UTF-8. .NET Core only supports distributions that are on this plan.

You can a ton of discussions on this topic, e.g. https://unix.stackexchange.com/questions/2089/what-charset-encoding-is-used-for-filenames-and-paths-on-linux

**Comment by karelz** [comment] 2017-06-30 00:57
Is there anything for us left to do at all in 2.1? What should be the next step?

**Comment by tarekgh** [comment] 2017-06-30 00:59
Per Jan's comment I think we can close this issue.

**Comment by karelz** [comment] 2017-06-30 01:08
Then let's do it :)

**Closed by karelz** 2017-06-30 01:08 UTC
Labels: area-System.IO, bug, os-linux

**Comment by tmds** [comment] 2017-06-30 15:31
> Recent enough Linux distributions are set up such that everything is using UTF-8. .NET Core only supports distributions that are on this plan.

@karelz should this be documented?

@jkotas @tarekgh @ellismg fyi, this blog post shows how java handles this: http://happygiraffe.net/blog/2009/09/24/java-platform-encoding/.

**Comment by karelz** [comment] 2017-06-30 15:45
> should this be documented?

Probably ... do you have any idea where? With some APIs? Or maybe in Release notes? (Does not seem to be good fit for CoreFX repo docs)

**Comment by tarekgh** [comment] 2017-06-30 15:47
> fyi, this blog post shows how java handles this: http://happygiraffe.net/blog/2009/09/24/java-platform-encoding/.

from the comments on this article it looks the problem still there with Java too. the file names still displayed as "?" so the encoding is not really correctly handled there.

**Comment by jkotas** [comment] 2017-06-30 15:48
> With some APIs?

The documentation for `Encoding.Default` property would be a good place.

**Comment by tarekgh** [comment] 2017-06-30 16:00
I have created a doc issue and linked it to this issue.

CC @Petrusha

**Comment by tmds** [comment] 2017-06-30 16:14
> from the comments on this article it looks the problem still there with Java too. the file names still displayed as "?" so the encoding is not really correctly handled there.

I wouldn't assume there is a Java problem, I guess his terminal isn't configured for UTF-8 or some else related to that particular setup.

> With some APIs?
The documentation for Encoding.Default property would be a good place.

Would that be a good place that this affects filesystem handling too? Or perhaps a remark on File/Directory class?

**Comment by tarekgh** [comment] 2017-06-30 16:25
> Would that be a good place that this affects filesystem handling too? Or perhaps a remark on File/Directory class?

Feel free to add your comment to the linked doc issue so it can capture all place we may need to edit

**Comment by tmds** [comment] 2017-06-30 16:26
Some more info on the OpenJDK implementation (credits: Andrew Haley)

> OpenJDK on Linux/glibc calls nl_langinfo(CODESET) to get the coding
used for filenames:

> nl_langinfo is POSIX: AFAIK it is the standard way to get the system
encoding on all UNIXy systems.
