### ISSUE TITLE
NullReferenceException in System.Text.Json.Deserialize<IEnumerable<IDictionary<string, object>>>

### ISSUE THREAD

**Issue by mmosca** [dotnet/corefx#41198] opened 2019-09-19 12:32 UTC
System.Text.Json fail with a NullReferenceException trying to deserialized nested objects/arrays to IEnumerable<IDictionary<>> type.

This sample program will trigger this issues on .Net Core 3.0-rc1:

```
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace CustomViewSplit
{
    class Program
    {
        static void Main(string[] args)
        {
            string workingJson = @"[
  {
    ""a"": ""A"",
    ""b"" :  ""B""
  }
]";

            string brokenJson = @"[
  {
    ""a"": ""A"",
    ""b"" :  {} 
  }
]";


            foreach (string json in new[] {workingJson, brokenJson})
            {
                byte[] bytes = System.Text.Encoding.UTF8.GetBytes(json);
                ReadOnlySpan<byte> readonlySpan = new ReadOnlySpan<byte>(bytes);

                // This will throw a NullReferenceException for brokenJson and alsoBroken
                var enumerable = JsonSerializer.Deserialize<IEnumerable<IDictionary<string, object>>>(readonlySpan);
            }
        }
    }
}
```

**Comment by ahsonkhan** [comment] 2019-09-19 22:39
This is a duplicate of https://github.com/dotnet/corefx/issues/41107

**Closed by ahsonkhan** 2019-09-19 22:39 UTC
Labels: area-System.Text.Json
