### ISSUE TITLE
DNS Resolution on IPv6 enabled host causes major slowdown

### ISSUE THREAD

**Issue by AlexTalavari** [dotnet/corefx#37035] opened 2019-04-19 18:06 UTC
DNS.GetHostEntries has a check and tries to resolve IPv6 even when not desirable. 

This behavior causes major slowdowns in High Performance applications especially when connecting to domains with small TTL.

Using other 3rd party libraries ignore the problem with ipv6. Unfortunatelly there is no option to change the DNS client for TCPClient or HttpClient or force to resolve into only IPv4 and cause major bottlenecks in our applications. 

10seconds to resolve a domain with TTL of 60 is reallly bad compared to the <100ms a A query does.

There is a workaround of handling the resolution ourselves before passing it to HttpClient or TcpClient but its not ideal.

Also i was not able to find the source code for System.Net.NameResolutionPal.cs but i am suspecting it does a ANY query to the DNS. ANY is obsolete according to RFC8482 and many providers such as Cloudflare are blocking it as shown below

```
$dig ANY cloudflare.com @ns1.cloudflare.com.

;; QUESTION SECTION:
;cloudflare.com.                        IN      ANY

;; ANSWER SECTION:
cloudflare.com.         3789    IN      HINFO   "RFC8482" ""

;; Query time: 20 msec
;; WHEN: Fri Apr 19 21:00:31 DST 2019
```

Proposed solution: A global setting to disable ipv6 resolution for DNS

**Comment by wfurt** [comment] 2019-04-20 02:11
It checks both address families. If you don't want IPv6 lookups disable IPv6 on our system.
In Linux you can update /etc/gai.conf (there are many HOWTOs on internet)

**Comment by scalablecory** [comment] 2019-09-26 23:15
Closing as by design; this appears to be a system configuration or DNS server issue.

If you have some suggestions on how we might use DNS more effectively without impacting behavior, these would be interesting to know.

**Closed by scalablecory** 2019-09-26 23:15 UTC
Labels: area-System.Net, enhancement
