### ISSUE TITLE
[Regression] Test failure: System.Net.Sockets.Tests.SocketOptionNameTest / MulticastInterface_Set_AnyInterface_Succeeds in CI

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#26775] opened 2018-02-02 02:21 UTC
Outerloop test ```MulticastInterface_Set_AnyInterface_Succeeds``` failing with following stacktrace:
In PR #26731 (both [Release](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_release_prtest/7/testReport/junit/System.Net.Sockets.Tests/SocketOptionNameTest/MulticastInterface_Set_AnyInterface_Succeeds/) and [Debug](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_fedora24_debug_prtest/13/testReport/junit/System.Net.Sockets.Tests/SocketOptionNameTest/MulticastInterface_Set_AnyInterface_Succeeds/))

```
11:32:20   /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.ComponentModel.TypeConverter/tests/Performance
11:32:20   Finished running tests. End time=11:32:20. Return value was 0
11:32:20      System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds [FAIL]
11:32:20         Waiting for received data timed out
11:32:20         Expected: True
11:32:20         Actual:   False
11:32:20         Stack Trace:
11:32:20   Using as the test runtime folder.
11:32:20            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(131,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_Helper(Int32 interfaceIndex)
11:32:20            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(91,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_AnyInterface_Succeeds()
11:32:20            --- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidsh** [comment] 2018-02-02 04:56
Doing multicast tests in the CI system is problematic.

**Comment by wfurt** [comment] 2018-02-02 05:03
generally true but the one I look at has been configuration problems with the machines @davidsh 
It would be great to have link to actual runs so we can investigate failure - at least see of the repro environment would repro it. may be related to #24114

**Comment by karelz** [comment] 2018-02-05 17:42
@wfurt it failed as part of the referenced PR on both Debug and Release build - can you please check with infra team what's going on?

**Comment by caesar1995** [comment] 2018-02-14 20:41
I think this issue will only repro with Fedora CI. Probably related to: #24036.

**Comment by wfurt** [comment] 2018-02-14 22:36
I was not able to reproduce this. Fedora24 is now officially out. However I did see failure for IPv6 multicast tests. This still may need some investigation.

**Comment by karelz** [comment] 2018-03-02 20:24
Fedora24 is officially out, so closing. We can reopen if it happens again on other OSs.

**Closed by karelz** 2018-03-02 20:24 UTC
Labels: area-System.Net.Sockets, os-linux, test bug
