### ISSUE TITLE
Caching EqualityComparer.Default<T> in ValueTuple brings significant performance increase

### ISSUE THREAD

**Issue by azhmur** [dotnet/corefx#18666] opened 2017-04-20 12:17 UTC
I have added caching for EqualityComparer instances inside ValueTuple. E.g.

        internal static readonly EqualityComparer<T1> T1Comparer = EqualityComparer<T1>.Default;
        internal static readonly EqualityComparer<T2> T2Comparer = EqualityComparer<T2>.Default;
        internal static readonly EqualityComparer<T3> T3Comparer = EqualityComparer<T3>.Default;
        internal static readonly EqualityComparer<T4> T4Comparer = EqualityComparer<T4>.Default;

        public bool Equals(ValueTupleCached<T1, T2, T3, T4> other)
        {
            return T1Comparer.Equals(Item1, other.Item1)
                && T2Comparer.Equals(Item2, other.Item2)
                && T3Comparer.Equals(Item3, other.Item3)
                && T4Comparer.Equals(Item4, other.Item4);
        }

And it seems improving performance for both GetHashCode and Equals. I can create pull request if this change supposed to be approved. 

``` ini

BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4770 CPU 3.40GHz, ProcessorCount=8
Frequency=3318387 Hz, Resolution=301.3512 ns, Timer=TSC
  [Host]       : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  LegacyJitX64 : Clr 4.0.30319.42000, 64bit LegacyJIT/clrjit-v4.6.1637.0;compatjit-v4.6.1637.0
  LegacyJitX86 : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  RyuJitX64    : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0

Runtime=Clr  

```
 |            Method |          Job |       Jit | Platform |       Mean |    StdErr |    StdDev |
 |------------------ |------------- |---------- |--------- |----------- |---------- |---------- |
 |            Equals | LegacyJitX64 | LegacyJit |      X64 | 10.4266 ns | 0.0090 ns | 0.0338 ns |
 |       GetHashCode | LegacyJitX64 | LegacyJit |      X64 | 47.9099 ns | 0.0912 ns | 0.3533 ns |
 |      EqualsCached | LegacyJitX64 | LegacyJit |      X64 |  4.2168 ns | 0.0070 ns | 0.0260 ns |
 | GetHashCodeCached | LegacyJitX64 | LegacyJit |      X64 | 25.2044 ns | 0.0407 ns | 0.1576 ns |
 |            Equals | LegacyJitX86 | LegacyJit |      X86 |  9.6312 ns | 0.0323 ns | 0.1252 ns |
 |       GetHashCode | LegacyJitX86 | LegacyJit |      X86 | 46.9868 ns | 0.4833 ns | 2.1065 ns |
 |      EqualsCached | LegacyJitX86 | LegacyJit |      X86 |  3.9719 ns | 0.0330 ns | 0.1279 ns |
 | GetHashCodeCached | LegacyJitX86 | LegacyJit |      X86 | 20.4734 ns | 0.0514 ns | 0.1925 ns |
 |            Equals |    RyuJitX64 |    RyuJit |      X64 |  9.6321 ns | 0.0123 ns | 0.0476 ns |
 |       GetHashCode |    RyuJitX64 |    RyuJit |      X64 | 40.7101 ns | 0.0525 ns | 0.2035 ns |
 |      EqualsCached |    RyuJitX64 |    RyuJit |      X64 |  2.9862 ns | 0.0035 ns | 0.0130 ns |
 | GetHashCodeCached |    RyuJitX64 |    RyuJit |      X64 | 14.9397 ns | 0.1623 ns | 0.7073 ns |

You can check results in my test project
https://github.com/azhmur/TupleBenchmark2/

PS Originally I thought JIT inlining effectively eliminates need of such optimization, but it seems it is not.

**Comment by JonHanna** [comment] 2017-04-20 13:11
Considering that most things don't call `GetHashCode()` directly, but through `EqualityComparer<T>.Default`, I wonder if a specialisation of `EqualityComparer<T>.Default` could give gains here without taking up as much static memory for tuple types that don't have it used.

**Comment by azhmur** [comment] 2017-04-20 15:22
I have update code to use field stored comparer instance instead direct call to Equals and GetHashCode. This is more similar to the usage inside HashSet and Dictionary. And it still shows some improvement.

``` ini

BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4770 CPU 3.40GHz, ProcessorCount=8
Frequency=3318387 Hz, Resolution=301.3512 ns, Timer=TSC
  [Host]       : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  LegacyJitX64 : Clr 4.0.30319.42000, 64bit LegacyJIT/clrjit-v4.6.1637.0;compatjit-v4.6.1637.0
  LegacyJitX86 : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  RyuJitX64    : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0

Runtime=Clr  

```
 |            Method |          Job |       Jit | Platform |       Mean |    StdErr |    StdDev |
 |------------------ |------------- |---------- |--------- |----------- |---------- |---------- |
 |            Equals | LegacyJitX64 | LegacyJit |      X64 | 13.3058 ns | 0.0159 ns | 0.0596 ns |
 |       GetHashCode | LegacyJitX64 | LegacyJit |      X64 | 53.3942 ns | 0.1326 ns | 0.5136 ns |
 |      EqualsCached | LegacyJitX64 | LegacyJit |      X64 |  9.6589 ns | 0.0504 ns | 0.1952 ns |
 | GetHashCodeCached | LegacyJitX64 | LegacyJit |      X64 | 26.9144 ns | 0.0585 ns | 0.2267 ns |
 |            Equals | LegacyJitX86 | LegacyJit |      X86 | 12.3289 ns | 0.0479 ns | 0.1856 ns |
 |       GetHashCode | LegacyJitX86 | LegacyJit |      X86 | 47.6645 ns | 0.1320 ns | 0.5112 ns |
 |      EqualsCached | LegacyJitX86 | LegacyJit |      X86 |  8.4311 ns | 0.1175 ns | 0.4843 ns |
 | GetHashCodeCached | LegacyJitX86 | LegacyJit |      X86 | 27.1333 ns | 0.1024 ns | 0.3966 ns |
 |            Equals |    RyuJitX64 |    RyuJit |      X64 | 11.5519 ns | 0.0509 ns | 0.1970 ns |
 |       GetHashCode |    RyuJitX64 |    RyuJit |      X64 | 46.0448 ns | 0.3826 ns | 1.4817 ns |
 |      EqualsCached |    RyuJitX64 |    RyuJit |      X64 |  5.4152 ns | 0.0092 ns | 0.0358 ns |
 | GetHashCodeCached |    RyuJitX64 |    RyuJit |      X64 | 16.4995 ns | 0.0323 ns | 0.1163 ns |

**Comment by omariom** [comment] 2017-04-20 18:58
It is waiting for[ this optimization](https://github.com/dotnet/coreclr/issues/6688)

**Comment by danmosemsft** [comment] 2017-04-20 21:15
@jcouv

**Comment by jcouv** [comment] 2017-04-28 04:42
This sounds like a good optimization, @omariom. Thanks for the proposal and data points.
I will check with some runtime folks to understand if there might be any negative effects. For instance, with .NET Native.

**Comment by danmosemsft** [comment] 2017-04-28 18:51
@jcouv do you need this for the 2.0 release and it will be done by 5/10? If so please set milestone=2.0.  If not please set milestone=future.

**Comment by jcouv** [comment] 2017-04-29 00:10
@azhmur 
I checked with a few folks (@vsadov, @davidwrighton) and confirmed this seems ok from a runtime perspective, including .NET Native.

There is a window to get this in the .NET Core 2.0 release, if you want to make a PR next week (that'd be great).
Let me know if you won't be able to do it, I'll try to squeeze it in my backlog.

**Comment by AlexGhiondea** [comment] 2017-04-30 04:03
@azhmur @jcouv I have move this out of the 2.0 milestone. If you can get this checked in next week that would be great!

**Comment by stephentoub** [comment] 2017-05-04 11:03
cc: @jkotas

**Comment by jkotas** [comment] 2017-05-04 15:05
@jcouv Isn't this implementation of ValueType effectively dead since it has been moved to CoreLib on all runtimes? Where do you expect to ship it again?

Other than that, the change is working around slow EqualityComparer.Default in shipping .NET Framework that has been much improved in .NET Core.

**Comment by jcouv** [comment] 2017-05-04 17:40
@jkotas I'll stop by to discuss.
I don't know if there is a fixed cadence for all packages from coreFX to be published to nuget, but there are some other fixes (type-forwarding to .NET 4.7) that require such publishing anyways.

Regarding the performance benefits of this fix, see the benchmarks above. If I'm reading it correctly, there are benefits on both legacy JIT and RyuJIT. Those mean desktop and Core runtimes, right?

**Comment by VSadov** [comment] 2017-05-04 17:49
The tests seem to be run on desktop FX, just with different JIT compilers - current and legacy.
Is it possible to run the same on CoreClr?

**Comment by jkotas** [comment] 2017-05-04 17:49
> If I'm reading it correctly, there are benefits on both legacy JIT and RyuJIT. Those mean desktop and Core runtimes, right?

Desktop has much less efficient `EqualityComparer.Default`. This change is working around that inefficiency for the most part. Nothing to do with the JIT.

**Comment by jcouv** [comment] 2017-05-04 18:15
Ah, thanks for the clarification @jkotas . That makes sense.

Based on that, we should only take this optimization in coreFX (which will benefit desktop scenarios before 4.7). I will follow-up to port this optimization into desktop implementation of ValueTuple.

If we can benchmark on coreCLR, then we could discuss a change to coreCLR implementation of ValueTuple. But it sounds like you don't expect similar gains.

**Closed** 2017-05-08 23:41 UTC
Labels: area-System.Runtime, tenet-performance, up-for-grabs
