### ISSUE TITLE
Missing several valuable members of System.Console in contract

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4636] opened 2015-11-23 12:45 UTC

**Comment by DamianEdwards** [comment] 2015-11-30 23:13
:+1: for this

I just ran into a need for `Console.KeyAvailable` trying to make an ASP.NET 5 app support interactivity in the console while the server is running, while preserving graceful shutdown on Ctrl+C. For now I've had to move the [interactivity to a bg thread](https://github.com/aspnet/benchmarks/commit/9d0cc2ab934adaba34ba18bd27a9f21f9ba80666#diff-c1a9f61e9cd451b6c0883f87bdd7c4abR49).

**Comment by khellang** [comment] 2015-12-01 00:19
Didn't #4639 close this?

**Comment by stephentoub** [comment] 2015-12-01 00:20
No, the Windows implementation and updating the contract (and agreeing to update it) remain.

**Comment by stephentoub** [comment] 2015-12-01 00:29
Specifically, we should add at least the following members back:
- Console.Title
- Console.Beep
- Console.Clear
- Console.SetCursorPosition
- Console.WindowWidth / WindowHeight / WindowLeft / WindowTop
- Console.BufferWidth / BufferHeight
- Console.CursorLeft / CursorTop
- Console.KeyAvailable

These have all now been implemented on Unix, so what remains is copying over the Windows implementations and exposing them in the contract.

@terrajobst, can we agree to add these back?  If we need a review meeting, can we do it at the next available?

**Comment by terrajobst** [comment] 2015-12-04 18:15
Looks good, except for `BufferWidth` and `BufferHeight` because they are not meaningful on Linux; they basically have to return `WindowWidth` and `WindowHeight`.

@stephentoub, can you create a list of all the missing APIs in `Console`? We should probably add all except for the ones we don't want/can't support.

**Comment by stephentoub** [comment] 2015-12-07 03:46
> @stephentoub, can you create a list of all missing APIs in Console?

These are the members I mentioned previously and that we agreed to add back:
```
public static string Title { get; set; }
public static void Beep();
public static void Clear();
public static bool KeyAvailable { get; }
public static int CursorLeft { get; set; }
public static int CursorTop { get; set; }
public static void SetCursorPosition(int left, int top);
public static int WindowHeight { get; set; }
public static int WindowWidth { get; set; }
public static int WindowLeft { get; set; }
public static int WindowTop { get; set; }
```
They've already been implemented on Unix in the corefx repo.  @pallavit is going to bring back the Windows implementations and update the contract accordingly.

Of the remaining non-ported methods, these could be implemented on Unix:
```
public static int BufferHeight { get; set; }
public static int BufferWidth { get; set; }
public static int LargestWindowHeight { get; }
public static int LargestWindowWidth { get; }
- (Would just return WindowHeight and WindowWidth)

public static int CursorSize { get; set; }
- (Getter would just return 100 and setter would be a nop.)

public static bool TreatControlCAsInput { get; set; }
- (Would essentially add a ctrl-c handler that would add the appropriate characters to the read buffer.)

public static Stream OpenStandardError(int bufferSize);
public static Stream OpenStandardInput(int bufferSize);
public static Stream OpenStandardOutput(int bufferSize);
public static Encoding InputEncoding { get; set; }
public static Encoding OutputEncoding { get; set; }
public static void Write(string format, object arg0, object arg1, object arg2, object arg3, __arglist)
public static void WriteLine(string format, object arg0, object arg1, object arg2, object arg3, __arglist)
- (These aren't really platform-specific.)
```

Whereas I don't currently know of a good way to implement the following on Unix... if these were added back to the contract, we would likely need to throw PlatformNotSupportedException on Unix:
```
public static void Beep(int frequency, int duration);
public static void MoveBufferArea(int sourceLeft, int sourceTop, int sourceWidth, int sourceHeight, int targetLeft, int targetTop);
public static void MoveBufferArea(int sourceLeft, int sourceTop, int sourceWidth, int sourceHeight, int targetLeft, int targetTop, char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor);
public static void SetBufferSize(int width, int height);
public static void SetWindowPosition(int left, int top);
public static void SetWindowSize(int width, int height);
public static bool CapsLock { get; }
public static bool NumberLock { get; }
```

**Comment by andschwa** [comment] 2015-12-12 01:52
By the way, @stephentoub, we've been testing this internally on Linux for our project (added the API you specified to the reference library, recompiled, and distributed the DLL to our contractors), it's working great for the console. Thanks for the work!

**Comment by stephentoub** [comment] 2015-12-12 02:32
Great! :smile:

**Comment by andschwa** [comment] 2015-12-22 20:21
Is there an ETA for this? It's the last library we're having to patch manually, and it would be oh so nice to stop patching it. :sunny:

**Comment by tenor** [comment] 2015-12-22 20:38
I'd like to point out that `Console.Title` in the .Net Framework bleeds across appdomains because it's implemented via native calls.
Please consider a non-native implementation for .Net Core on Windows or give developers the opportunity to swap in an object to handle the `.Title {get; set;}`.

**Comment by jasonwilliams200OK** [comment] 2015-12-26 13:30
For `void Beep` without frequency/duration, in C: `printf("%c\n",(char)(7));  // requires <stdio.h>` or C++ `cout << '\a';`

For `void Beep` with frequency/duration, there is this cross-platform library called PortAudio (http://www.portaudio.com/), see examples: https://github.com/EddieRingle/portaudio/tree/master/examples. If PortAudio is too large, then the most precise solution is to engage Speaker drivers and ioctl the raw command: [BSD](https://www.freebsd.org/cgi/man.cgi?query=speaker&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html) and [Linux](http://www.linuxquestions.org/questions/linux-kernel-70/kernel-beep-manipulation-605355/) (search for term "frequency").

For cross-platform `bool CapsLock`, see this thread: http://www.qtcentre.org/threads/30180-how-to-determine-if-CapsLock-is-on-crossplatform.

For cross-platform `bool NumLock`, see this answer: http://stackoverflow.com/a/8429021.

**Comment by genlu** [comment] 2016-01-09 00:43
Thanks for addressing this! It'd be great if you can make `BufferWidth` available too, as it might be different from `WindowWidth` on Windows.

**Comment by pallavit** [comment] 2016-01-09 00:46
Thanks @genLu. As you mentioned BufferWidth is not useful on Linux. I am not sure, if we can add it but I will keep it in mind.

**Comment by genlu** [comment] 2016-01-12 18:24
@pallavit Correct me if I was wrong, but we'd need to know BufferWidth/BufferHeight to set cursor position, since arguments to `SetCursorPosition` are based on buffer size, right?

**Comment by andschwa** [comment] 2016-01-12 19:01
@genlu Correct, and my team is currently making due with our own native library to get those sizes. We'd *like* to use .NET's, but it's not totally blocking us.

**Comment by benaadams** [comment] 2016-01-12 19:01
Throwing `PlatformNotSupportedException` would cause x-plat library issues if someone mostly develops and test the library on windows (where it works); but then a user of that library is on linux then it would likely cause runtime crashes?

**Comment by benaadams** [comment] 2016-01-12 19:06
However, If it throws on windows if redirected and there is an api to detect that; maybe say linux always returns that it is redirected? Then could throw?

**Comment by Garciat** [comment] 2016-01-12 19:07
If `Console` were an object, it could be casted to `WindowsConsole`/`UnixConsole` to get access to platform-specific APIs. `Console` would then only expose only cross-platform APIs. But, it is not an object.

**Comment by jasonwilliams200OK** [comment] 2016-01-12 19:08
@benaadams, that would be a very normal scenario in almost every library repo on GitHub: that the developer of library must have CI configured for all supported operating system testing all path of their code base (100% code coverage). If something is still breaking on certain platform, the consumers of lib will request the library developer to fix/implement that part. Case in hand, this very issue. :smile:

**Comment by andschwa** [comment] 2016-01-12 19:14
@genlu I just switched out our use of faked `BufferHeight` and `BufferWidth` with `WindowHeight` and `WindowWidth`, which for a readline-esque Linux shell is working just fine as far as I can tell.

My only explanation is that our use of it is really simple.

**Comment by andschwa** [comment] 2016-01-12 19:25
Just to reference here, the following APIs:

``` c#
public static string Title { get; set; }
public static void Beep();
public static void Clear();
public static bool KeyAvailable { get; }
public static void SetCursorPosition(int left, int top);
public static int WindowHeight { get; set; }
public static int WindowWidth { get; set; }
public static int WindowLeft { get; set; }
public static int WindowTop { get; set; }
```

Were added in #5254.

And the remaining,
``` c#
public static int CursorTop { get { return default(int); } set { } }
public static int CursorLeft { get { return default(int); } set { } }
```

In #5201.

These are now all available least in build (at least, maybe before) 23712 (confirmed working in our scenario).

Thank you a million @pallavit! (And @stephentoub for earlier implementation). :smile: 

Unless I missed something, I believe we can close this issue now.

**Comment by jasonwilliams200OK** [comment] 2016-01-12 19:29
@andschwa, we can get BufferWidth from `TIOCGWINSZ` ioctl call. 
I googled and got this: http://stackoverflow.com/a/23369919, then locate that in neovim (C99 implementation of vim; which -- due to vim's age and maturity -- is undoubtedly one of the best reference source to get inspiration for any shell related code in POSIX): https://github.com/neovim/neovim/blob/959f2601f982bb911c83cc6e948f06abd2e9c140/src/nvim/tui/tui.c#L698 (with fallbacks and proper checks).

**Comment by genlu** [comment] 2016-01-12 19:54
@andschwa Thanks for your replies. But IMHO, `BufferWidth` and `BufferHeight` are necessary (especially if methods like `SetCursorPosition` are provided), otherwise you can't write x-platform code using .NET to handle console.

Also for this issue, I believe corefx team will still be using it to keep track the work of adding those APIs to contract. (and thanks a lot to @pavv and @stephentoub for implementing them!)

**Comment by genlu** [comment] 2016-01-12 20:02
@andschwa And missing `BufferWidth` and `BufferHeight` wouldn't not be a problem on Linux (assuming they simply return `WindowWidth` and `WindowHeight` as @terrajobst mentioned, then you should be able to use them instead), the problem is when you want to work with console on Windows using corefx, where buffer and windows might be different.

**Comment by stephentoub** [comment] 2016-01-12 20:09
> we can get BufferWidth from TIOCGWINSZ ioctl call. 

@jasonwilliams200OK, that's already done in WindowWidth/WindowHeight:
https://github.com/dotnet/corefx/blob/e0a215f3f959407be801c9e7837c9bb4d9df9fb6/src/Native/System.Native/pal_console.cpp#L24

**Comment by terrajobst** [comment] 2016-01-13 01:32
We've approved the API with feedback. Details in the [notes](https://github.com/dotnet/apireviews/pull/23).

**Comment by andschwa** [comment] 2016-02-12 23:23
@genlu Indeed that turned out to be an issue on Windows for us :smile:

**Comment by Konard** [comment] 2016-02-18 19:54
Any news on Console.KeyAvailable ?

**Comment by stephentoub** [comment] 2016-02-18 19:58
> Any news on Console.KeyAvailable ?

It's available.
https://github.com/dotnet/corefx/blob/master/src/System.Console/ref/System.Console.cs#L30

**Comment by Konard** [comment] 2016-02-20 06:49
> It's available.
> https://github.com/dotnet/corefx/blob/master/src/System.Console/ref/System.Console.cs#L30

Ok.. But when it will be published as a nuget package?

**Comment by stephentoub** [comment] 2016-02-20 12:14
https://dotnet.myget.org/gallery/dotnet-core

**Comment by palladia** [comment] 2016-03-03 19:37
Is there plan to implement Console.TreatControlCAsInput?  

In light of news that upcoming changes could cause non-blocking Console.ReadKey (achieved with Console.KeyAvailable) to possibly lose keystrokes, I need either that be fixed, or that TreatControlCAsInput be implemented.

**Comment by stephentoub** [comment] 2016-03-03 20:17
> In light of news that upcoming changes could cause non-blocking Console.ReadKey (achieved with Console.KeyAvailable) to possibly lose keystrokes

It won't lose keystrokes.  Not sure where that news is coming from.  You may be thinking of the fact that we now only disable echo during a ReadKey(intercept: true) call, so in a race between the user typing and you calling ReadKey(intercept: true), the key might be echo'd even when you were hoping it wouldn't be, but you won't lose the keystroke.

**Comment by palladia** [comment] 2016-03-03 23:49
I was told that's the side effect of some recent changes.  But apparently that's now fixed by #6619.

So there's no plan to implement Console.TreatControlCAsInput, because it's too hard?

**Comment by stephentoub** [comment] 2016-03-03 23:54
> So there's no plan to implement Console.TreatControlCAsInput, because it's too hard?

We do plan to. Just hasn't been done yet.

**Comment by palladia** [comment] 2016-03-03 23:57
Any estimate on when this may happen?  I have a work-around, just trying to justify the effort.

**Comment by stephentoub** [comment] 2016-03-04 20:28
> Any estimate on when this may happen?

https://github.com/dotnet/corefx/pull/6669

**Closed** 2016-03-07 20:36 UTC
Labels: 2 - In Progress, api-approved
