### ISSUE TITLE
String.EndsWith on CoreCLR \ Linux does not work correctly for line feeds

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#4587] opened 2015-11-19 20:27 UTC
Here's the repro example:

```C#
using System;

public class Program
{
    public static void Main (string[] args)
    {
        var text = "Hello\r\n";
        
        Console.WriteLine(text.EndsWith("\n"));
        Console.WriteLine(text.LastIndexOf('\n') == text.Length -  1);
    }
}
```
**Expected**: True True
**Actual**: False True

I used DNX v1.0.0-rc2-16216 to run this application. The version of `System.Console` I used was `4.0.0-beta-23516`. Running it with DNX Mono or running this on Windows produces the right results.

**Comment by stephentoub** [comment] 2015-11-19 20:34
Related to https://github.com/dotnet/corefx/issues/3467 and https://github.com/dotnet/coreclr/issues/2051.

**Comment by ellismg** [comment] 2015-11-19 21:41
In this specific case, using StringComparision.Ordinal (to force Ordinal comparison) should address the issue until the code is fixed.  It also turns out that doing so will give you better performance as Ordinal comparisions (which is what you want here) are faster than linguistic comparisions.

**Comment by pranavkm** [comment] 2015-11-19 22:30
:+1: We switched to looking at the underlying chars in our code since we were needlessly creating the string from a `StringBuilder`

**Comment by ellismg** [comment] 2015-11-19 22:31
@pranavkm Event better!

**Comment by pranavkm** [comment] 2015-11-19 23:11
Feel free to close this bug if the issue is independently tracked.

**Comment by stephentoub** [comment] 2016-04-30 12:31
@ellismg, @joshfree, this is marked as 1.1.0... should it be moved back to 1.0.0-rtm?

**Comment by tarekgh** [comment] 2016-05-04 19:42
@pranavkm I cannot reproduce this issue. could you please try it and let me know if you still see the problem?

**Comment by tarekgh** [comment] 2016-05-13 16:07
To conclude this issue and clarify the expected behavior:

- When doing linguistic collation operations, it is expected you'll see different behavior when running on Linux than Windows. the reason is net core is just calling the OS for such operations.

- For this specific case when search for "\n" in a string has "\r\n", this one of the differences between Windows and Linux. ICU collation will treat "\r\n" differently and not as 2 separate characters '\r' and '\n'. so searching linguistically for \n will fail to find it on Linux. If you remove \r from the original source and search for \n, that will succeed. 

- In general if you are search for \n, \r or similar character categories, I tis recommended to use ordinal search and not linguistic search.

- We had an issue which is we were trying to optimize the search when having Ascii strings and that was causing a problem of having different behavior when using non-ascii string. we have fixed this problem through the linked PR. 

Please let me know if you have any question. Thanks.

**Closed by tarekgh** 2016-05-13 16:07 UTC
Labels: System.Globalization
