### ISSUE TITLE
Disposing Socket during Socket.Receive behaves badly on *nix

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#24677] opened 2017-10-17 00:33 UTC
### Repro app:

```C#
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;

namespace SocketInvalidArg
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var serverSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
            {
                serverSocket.Bind(new IPEndPoint(IPAddress.Loopback, 5000));
                serverSocket.Listen(512);

                var i = 0;
                try
                {
                    for (;; i++)
                    {
                        using (var clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
                        {
                            clientSocket.Connect(IPAddress.Loopback, 5000);

                            var acceptSocket = serverSocket.Accept();

                            Task.WaitAll(Task.Run(() => ReadInput(acceptSocket)), Task.Run(() => acceptSocket.Dispose()));
                        }
                    }
                }
                catch
                {
                    Console.Write("Failed after #{0} iterations", i);
                    throw;
                }
            }
        }

        static void ReadInput(Socket socket)
        {
            try
            {
                Console.WriteLine("Calling socket.Receive");
                var count = socket.Receive(new byte[256]);
                Console.WriteLine("Called socket.Receive with count = {0}", count);
            }
            catch (ObjectDisposedException)
            {
                Console.WriteLine("Socket.Receive threw ODE");
            }
            catch (SocketException ex) when (ex.SocketErrorCode != SocketError.InvalidArgument)
            {
                Console.WriteLine(ex + Environment.NewLine + ex.SocketErrorCode);
            }
        }
    }
}
```

### Actual Behavior (macOS 10.12 and Ubuntu 16.04)

On macOS and Linux, Socket.Recieve() either throws an "Invalid argument" SocketException:

```$ dotnet run
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Failed after #12 iterations
Unhandled Exception: System.AggregateException: One or more errors occurred. (Invalid argument) ---> System.Net.Sockets.SocketException: Invalid argument
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at SocketInvalidArg.Program.ReadInput(Socket socket) in /Users/shalter/source/halter73/SocketInvalidArg/Program.cs:line 45
   at SocketInvalidArg.Program.<>c__DisplayClass0_0.<Main>b__0() in /Users/shalter/source/halter73/SocketInvalidArg/Program.cs:line 28
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at SocketInvalidArg.Program.Main(String[] args) in /Users/shalter/source/halter73/SocketInvalidArg/Program.cs:line 35
```

Or hangs indefinitely on the call to Socket.Receive:
```
$ dotnet run
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
```

### Expected Behavior (Current Behavior on Windows)

Socket.Receive always completes. If the Socket is Disposed after the call to Socket.Receive, it throws a "ConnectionAborted" SocketException instead of an "InvalidArgument" SocketException.

```
...
Calling socket.Receive
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at SocketInvalidArg.Program.ReadInput(Socket socket) in C:\Users\shalter\source\halter73\SocketInvalidArg\Program.cs:line 45
ConnectionAborted
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
Socket.Receive threw ODE
Calling socket.Receive
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at SocketInvalidArg.Program.ReadInput(Socket socket) in C:\Users\shalter\source\halter73\SocketInvalidArg\Program.cs:line 45
ConnectionAborted
Calling socket.Receive
Socket.Receive threw ODE
...
(and so it goes forever)
```

**Comment by stephentoub** [comment] 2017-10-17 02:22
> Expected Behavior 

Closing a BSD socket during a synchronous send/receive operation is explicitly undefined behavior.  Different OSes provide different behaviors, including various errors, hangs, etc., and not always consistently even on the same OS.

Do you have a suggestion for what we should be doing differently in the .NET layer?

**Comment by tmds** [comment] 2017-10-17 08:53
It's worth knowing that Dispose will block as long as there are on-going operations.
So in your example, if you Dispose before calling Receive, Receive will throw ODE.
If you Receive before Dispose, both will block indefinitely (if nothing is received).
To avoid blocking indefinitely, you can set ReceiveTimeout/SendTimeout.

Going async is the simplest solution. Then Dispose will cause pending operations to complete.

**Comment by halter73** [comment] 2017-10-17 17:33
@tmds Good tip about it being only sync Receive that blocks indefinitely. Even though it doesn't hang, ReceiveAsync will throw a "SocketError.InvalidArgument" SocketException if it's called before Dispose. I believe this behavior is still wrong. It should throw a "SocketError.ConnectionAborted" SocketException instead like it does on Windows.

**Comment by stephentoub** [comment] 2017-10-17 17:57
>  I believe this behavior is still wrong
> It should throw a "SocketError.ConnectionAborted" SocketException instead like it does on Windows.

This is the error the OS is giving us.  You're suggesting the .NET layer should somehow detect this condition and change the error supplied by the OS to match Windows?  Why is Windows correct?

**Comment by halter73** [comment] 2017-10-17 18:09
> You're suggesting the .NET layer should somehow detect this condition and change the error supplied by the OS to match Windows?

Yes.

>Why is Windows correct?

In this situation, none of the arguments to Receive(Async) are invalid at the time of the call. When the Socket is already disposed, an ODE makes sense, but that's not the situation here. Instead the Receive call was aborted by closing the connection. Copying the Windows behavior also makes the code for aborting a connection from the server consistent across OS's.

---

I think I was too quick to accept Receive/Dispose blocking. I don't plan on using the synchronous Receive method in any real apps, but I still think this is probably bad behavior on *nix.

Does calling Receive before Dispose cause both to block indefinitely on Windows? That was not my observation when running the repro app. Instead on Windows, Receive throws a ConnectionAborted SocketException. I think this should also be the behavior on *nix for compatibility with existing apps.

**Comment by stephentoub** [comment] 2017-10-17 18:24
> I think I was too quick to accept Receive/Dispose blocking.

I'm not clear on what you suggest be done instead.  We call send or recv.  It blocks.  If the handle is then closed on another thread, what are you proposing be done with regards to the other thread that's currently blocked in a send/recv native call?  The only option I'm aware of here is to use only non-blocking behavior, and rely on our synchronous emulation layer that builds synchronous operations on top of async/non-blocking ones, and that's a significant perf problem if folks actually want the blocking behavior.

> Yes

I don't think this is a good idea.  The OS says "this is the problem", and I don't believe we want to be in the business of saying "well, we disagree, we're going to pretend the problem was something else".  I also don't know how we can do so accurately; there's a race condition between the file descriptor getting closed by someone and the call being made, and I believe you're suggesting we somehow detect the difference between whether it was closed and then the call made vs the call made and then it closed, and converting the errno value only in one of those cases.

**Comment by tmds** [comment] 2017-10-26 13:06
@stephentoub @halter73 
I went and looked a bit deeper into this. I think you are getting 'Invalid Value' because the syscall return EBADF when passed an invalid file descriptor. corefx maps that to SocketError.InvalidArgument.

https://github.com/dotnet/corefx/blob/9dafd441dc905ccbe614dfa8c3d9bac6b09a9ccb/src/Common/src/System/Net/Sockets/SocketErrorPal.Unix.cs#L43

The mapping could be changed to ConnectionAborted.

**Comment by stephentoub** [comment] 2017-10-26 13:22
> The mapping could be changed to ConnectionAborted.

But it is an invalid argument. This is the race condition I referred to earlier.

**Comment by tmds** [comment] 2017-10-26 13:57
> But it is an invalid argument. This is the race condition I referred to earlier.

I agree. EBADF is an invalid argument for a file descriptor.
I think in Socket context, EBADF will be a disposed Socket (almost always), mapping it to ConnectionAborted may be more informative. 'Invalid Argument' makes me look at the arguments I'm passing.

**Comment by Priya91** [comment] 2017-12-07 19:18
@tmds what are the other scenarios while using sockets for which ebadf wouldn't mean connection aborted?

**Comment by tmds** [comment] 2017-12-11 09:06
@Priya91 in corefx, `sendfile` is the only socket system call that accepts a file descriptor that isn't a socket. The managed implementation only passes valid file descriptors for this, so it won't generate EBADF. All other cases for EBADF reflect the socket handle.
After having another look at the available socket errors, I think `OperationAborted` _(The overlapped operation was aborted due to the closure of the Socket._) may be a better mapping than `ConnectionAborted` (_The connection was aborted by the .NET Framework or the underlying socket provider._): EBADF will also happen for connectionless sockets (e.g. UDP).

I find the current mapping to `InvalidArgument` (_An invalid argument was supplied to a Socket member._) a bit counterintuitive since the problem is not with the arguments, so I am suggesting alternatives. I'm fine if things stay as-is too.

**Comment by Priya91** [comment] 2017-12-11 21:22
In sockets perspective it makes sense with mapping ebdaf to operationaborted, given that there is no other case in this scenario where ebdaf could actually mean invalid arguments rather than the socket being closed. Although if that was the case, I am not sure why the OS would give an ebdaf instead of a more informative appropriate error. It is also a safe option to not be smarter than the OS, in case in future the OS design assigns this error to more scenarios and we are now blocked with our mapping, and having to deal with compat issues.

Closing this as by design.

**Closed by Priya91** 2017-12-11 21:22 UTC
Labels: area-System.Net.Sockets, os-linux

**Comment by tmds** [comment] 2017-12-11 22:14
> In sockets perspective it makes sense with mapping ebdaf to operationaborted, given that there is no other case in this scenario where ebdaf could actually mean invalid arguments rather than the socket being closed. 

This is about socket errors.

> Although if that was the case, I am not sure why the OS would give an ebdaf instead of a more informative appropriate error.

Because the Socket was Disposed, the file descriptor is closed and has become invalid.

**Comment by ward0093** [comment] 2018-01-24 20:45
ok... we are having this issue now... after we send data out via our API, the connection gets severed.

How do we solve or trap around this?

[19:52:35 DBG] Connection id "0HLB3BR492N7L" completed keep alive response.
[19:52:35 INF] Request finished in 7.6281ms 200 application/json; charset=utf-8
[19:52:35 INF] Connection id "0HLB3BR492N7L" communication error.
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -9 EBADF bad file descriptor
[19:52:35 DBG] Connection id "0HLB3BR492N7L" disconnecting.
[19:52:35 DBG] Connection id "0HLB3BR492N7L" sending FIN.
[19:52:35 INF] Connection id "0HLB3BR492N7L" request processing ended abnormally.
System.IO.IOException: Error -9 EBADF bad file descriptor ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -9 EBADF bad file descriptor
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer.<WriteOutputAsync>d__6.MoveNext()

We are struggling getting our ASPNETCORE API to run inside a docker container

**Comment by stephentoub** [comment] 2018-04-13 04:46
> System.IO.IOException: Error -9 EBADF bad file descriptor --->
> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -9 EBADF bad file descriptor

That's coming from Kestrel and its usage of libuv; I suggest you open an issue for it in the https://github.com/aspnet/kestrelhttpserver repo if there isn't already such an issue.
cc: @davidfowl
