### ISSUE TITLE
Error showing Metadata file \corefx\bin\Windows_NT.AnyCPU.Debug\XunitTraitsDiscoverers\XunitTraitsDiscoverers.dll could not be found.

### ISSUE THREAD

**Issue by mafiya69** [dotnet/corefx#965] opened 2015-02-20 02:10 UTC
I opened \src\System.Console.sln and build it.
System.Console builded successfully, but System.Console.Text failed showing an Error Showing "Metadata file \corefx\bin\Windows_NT.AnyCPU.Debug\XunitTraitsDiscoverers\XunitTraitsDiscoverers.dll' could not be found." Anyone can help?

**Comment by akoeplinger** [comment] 2015-02-20 02:12
Looks like https://github.com/dotnet/corefx/issues/745

**Comment by weshaggard** [comment] 2015-02-20 03:07
Yes this is a duplicate of #745. We haven't figured out how we want to address it yet but for now you can workaround it by building at least once from the command line (either this project or the entire build.cmd in the root).

**Closed by weshaggard** 2015-02-20 03:07 UTC
