### ISSUE TITLE
Test failure in System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_NoneIPAddress_Fail and 

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#15930] opened 2017-02-07 23:13 UTC
The test is currently disabled with label [ActiveIssue(10345)](https://github.com/dotnet/corefx/issues/10345), although the issue has been closed. If you enable the test, it would still fail on Linux.

 ```
System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_NoneIPAddress_Fail(address: 255.255.255.255) [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.Sockets.SocketException)
        Actual:   typeof(System.Net.Internals.SocketExceptionFactory+ExtendedSocketException): No such device or address
        Stack Trace:
           /home/sekho/Desktop/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs(422,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
           /home/sekho/Desktop/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs(561,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
           /home/sekho/Desktop/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs(641,0): at System.Net.Dns.<>c.<GetHostEntryAsync>b__26_1(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by karelz** [comment] 2017-02-07 23:23
cc @steveharter @Priya91 @ianhays

**Comment by Priya91** [comment] 2017-02-28 23:41
Closing bug as dupe of #10345

**Closed by Priya91** 2017-02-28 23:41 UTC
Labels: area-System.Net, os-linux, test bug, test-run-core, untriaged
