### ISSUE TITLE
MatchingRefApiCompat issues with System.Data.SqlClient

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#27974] opened 2018-03-12 17:27 UTC
See baseline file
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/MatchingRefApiCompatBaseline.txt

We should do one of the following:
1. Expose the APIs publicly in the reference assembly
2. Make the APIs in the implementation internal
3. Add a comment to the baseline file why you cannot do either (1) or (2) and keep them baselined.

See PR https://github.com/dotnet/corefx/pull/27881/ for extra context.

**Comment by geleems** [comment] 2018-03-21 21:36
In the MatchingRefApiCompatBaseline.txt,
It says the constructor `Microsoft.SqlServer.Server.SqlMetaData(System.String, System.Data.SqlDbType, System.Type)` does not exist in implementation, but does exist in the contract.
https://github.com/dotnet/corefx/blob/2169709020cb51c95aedf66f3db7c41d7d54a725/src/System.Data.SqlClient/src/MatchingRefApiCompatBaseline.txt#L2

But actually the constructor does not exist in the contract
https://github.com/dotnet/corefx/blob/2169709020cb51c95aedf66f3db7c41d7d54a725/src/System.Data.SqlClient/ref/System.Data.SqlClient.cs#L147-L162

And it does exist in implementation.
https://github.com/dotnet/corefx/blob/2169709020cb51c95aedf66f3db7c41d7d54a725/src/System.Data.SqlClient/src/System/Data/Sql/SqlMetaData.cs#L87-L92

**Comment by weshaggard** [comment] 2018-03-21 21:55
Yes the wording in the baseline file is confusing, as this is a reverse apicompat check "implementation" in baseline is really the ref and "contract" in the baseline is really the src.

**Comment by geleems** [comment] 2018-03-21 22:26
@weshaggard Thanks for the info.
What is the command line to update the baseline?

**Comment by geleems** [comment] 2018-03-22 18:07
@saurabh500 
I talked to Wes about the command for updating the baseline, and found out there doesn't exist such a command. I have to manually remove the violations in the MatchingRefApiCompatBaseline.txt. Build will complain if anything is not fixed properly in MatchingRefApiCompatBaseline.txt.

**Comment by saurabh500** [comment] 2018-03-22 18:14
@weshaggard What is the build target to check if the MatchingRegApiCompatBaseline is in sync with the compat issue?

**Comment by geleems** [comment] 2018-03-22 20:22
@weshaggard 
My PR for fixing this issue (https://github.com/dotnet/corefx/pull/28369) failed with `Packaging All Configurations x64 Debug Build` test.
```
> .\build.cmd -allConfigurations -buildArch=x64 -Debug -- /p:RuntimeOS=win10

Build FAILED.

System.Data.SqlClient.cs(644,114): error CS0234: The type or namespace name 'IDbColumnSchemaGenerator' does not exist in the namespace 'System.Data.Common' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Data.SqlClient\ref\System.Data.SqlClient.csproj]
System.Data.SqlClient.cs(661,85): error CS0234: The type or namespace name 'DbColumn' does not exist in the namespace 'System.Data.Common' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Data.SqlClient\ref\System.Data.SqlClient.csproj]
    0 Warning(s)
    2 Error(s)
```
Because there is no `IDbColumnSchemaGenerator` and `DbColumn` interface in NETFramework.v4.6.1.
How can I fix this?

**Comment by weshaggard** [comment] 2018-03-22 21:05
You cannot expose those APIs in the netstandard ref's if they don't exist on .NET Framework. So you have to decide if these APIs are import to be exposed for other scenarios like .NET Core then you will need to add a netcoreapp specific configuration for those APIs or decide that they aren't needed any you remove them or make them private in the implementation.

**Comment by geleems** [comment] 2018-03-22 22:11
@weshaggard `GetColumnSchema` method is for netcoreapp API, but the problem is we don't have build configuration for netcoreapp in System.Data.SqlClient. Should we create build configuration for System.Data.SqlClient? Is this right way to do?

**Comment by weshaggard** [comment] 2018-03-22 22:18
Currently that API isn't exposed to the customers and is only the implementation and cannot be exposed as netstandard, so if this API is needed then yes you will need to create a netcoreapp configuration in both the ref and the src projects.

**Comment by geleems** [comment] 2018-03-30 18:53
The fix https://github.com/dotnet/corefx/pull/28369 for this issue has been merged to master.
Closing the issue.

**Closed by geleems** 2018-03-30 18:53 UTC
Labels: area-System.Data.SqlClient
