### ISSUE TITLE
Strange behavior with Process creation and termination

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#18408] opened 2017-04-14 23:03 UTC
@livarcocc commented on [Thu Mar 16 2017](https://github.com/dotnet/core-setup/issues/1762)

_From @mellinoe on April 29, 2016 21:36_

## Steps to reproduce

Consider this program:

``` CSharp
public static void Main(string[] args)
{
    ProcessStartInfo psi = new ProcessStartInfo("ping", "github.com");
    psi.RedirectStandardOutput = true;
    Process.Start(psi);
    Console.WriteLine("Process started.");
}
```

NOTE: This is just an easy example, my use case is slightly different (using xdg-open to launch a browser). Ping works here because it usually takes a while to exit.
## Expected  behavior

The program starts a process, prints out "Process started", and terminates.
## Actual behavior

When executed via `dotnet run`, the program does not terminate until the "ping" process terminates. Executing `killall ping` causes the `dotnet` process to terminate, as well, once `ping` has been killed.

When I run the same program using corerun or coreconsole, the above behavior is not exhibited. A ping process is started, but the program immediately terminates. Ping continues in the background.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.04
 OS Platform: Linux
 RID:         ubuntu.15.04-x64
```

_Copied from original issue: dotnet/cli#2776_

---

@livarcocc commented on [Thu Mar 16 2017](https://github.com/dotnet/core-setup/issues/1762#issuecomment-287265358)

_From @mellinoe on April 29, 2016 21:43_

Another point of data: If I execute `dotnet <test.dll>`, then the correct behavior is exhibited.

This repros on both Ubuntu and Windows (all I've tried).

---

@livarcocc commented on [Thu Mar 16 2017](https://github.com/dotnet/core-setup/issues/1762#issuecomment-287265362)

_From @brthor on May 2, 2016 18:53_

It seems like we should be a little more robust in how we manage child processes in `dotnet run` here, it sounds like we are waiting for the entire process tree instead of the immediate child.

I don't think this is a blocker for RC2 though, comment if you feel otherwise.

---

@livarcocc commented on [Thu Mar 16 2017](https://github.com/dotnet/core-setup/issues/1762#issuecomment-287265367)

@mellinoe I just tried this in 1.0.1 and I hit the same thing, except that when I published the app and run it using dotnet <dll> it exhibited the same delay there. So, wondering if that's an issue with dotnet.exe, since that's also what we use during dotnet run.

I will move this issue to core-setup. 

---

@gkhanna79 commented on [Fri Mar 17 2017](https://github.com/dotnet/core-setup/issues/1762#issuecomment-287443578)

Dotnet.exe is not launching processes @livarcocc. It simply calls into the managed entrypoint. 

> I hit the same thing, except that when I published the app and run it using dotnet it exhibited the same delay there

How did you repro this? What delay did you see?

---

@gkhanna79 commented on [Fri Apr 14 2017](https://github.com/dotnet/core-setup/issues/1762#issuecomment-294252653)

The host does not do anything to block/wait against the application aside from invoking its entrypoint. Someone in CoreFX should take a stab.

**Comment by gkhanna79** [comment] 2017-04-14 23:03
CC @danmosemsft

**Comment by karelz** [comment] 2017-04-15 00:10
Based on the steps from @mellinoe it seems that CLI is best tracking place, as it repros only with `dotnet` -- @livarcocc why did you move it out?

**Comment by gkhanna79** [comment] 2017-04-15 00:13
I dont see anything CLI or host specific in this @karelz. It maybe best for someone to look into why Process creation is hanging in certain scenarios and not in the others.

**Comment by karelz** [comment] 2017-04-15 00:30
Well, if it happens under one host and not the other, it naively looks host-specific to me ... either way, I don't mind if Process owners take a first look ;)

**Comment by gkhanna79** [comment] 2017-04-15 00:36
It is the same host being used for both scenarios.

**Comment by karelz** [comment] 2017-04-15 00:37
Interesting, what is the difference between corerun/coreconsole vs. dotnet?

**Comment by jkotas** [comment] 2017-04-15 16:14
It does not repro for me. Tried on all netcoreapp1.0/1.1/2.0. Latest servicing releases of netcoreapp1.0/1.1, Ubuntu 16.04 LTS, build using .NET CLI 2.0.0-preview1-005797.

This needs precise repro steps, with versions of all parts involved.

**Comment by karelz** [comment] 2017-11-30 21:41
Looks like we couldn't reproduce the issue. Closing for now. Feel free to reopen with additional info.

**Closed by karelz** 2017-11-30 21:41 UTC
Labels: area-System.Diagnostics.Process, bug
