### ISSUE TITLE
[Perf] Investigate Xml/XmlSerializer benchmarks regressions in 2.1 (part I)

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#27483] opened 2018-02-26 23:19 UTC
[Perf] Investigate Xml/XmlSerializer benchmark regressions in 2.1 (part I)

Regression across multiple tests in Xml/XmlSerializer of ~10% from this range of commits:

https://github.com/dotnet/corefx/compare/6ded3992a29c48ec3c9e641589b9805a1dbc50a3...dotnet:697e2b910e6cccbc1f3d58be111e309db4823ab7

**Comment by danmosemsft** [comment] 2018-03-30 21:34
This shows the Jan 9 regression

https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61761,61768,61770,61771,61769,61777,61762,61775,61767,61779,61776,61766,61778,61773,61772,61765,61764,61774,61763,61786,61788,61789,61787,61795,61780,61793,61785,61797,61794,61784,61796,61791,61790,61783,61782,61792,61781]&jobid=94550&

![image](https://user-images.githubusercontent.com/6385855/38154566-75762810-3427-11e8-9203-c549aa9a33a2.png)

**Comment by danmosemsft** [comment] 2018-03-30 21:36
@mconnew 

I don't believe @valenis has the right bracket above. This regressoin is caused by 
https://github.com/dotnet/corefx/compare/b542758a665b74398ba3448b8039800f3bc139f1...dotnet:697e2b910e6cccbc1f3d58be111e309db4823ab7

which brackets only one change, this one:

 @krwq
Harden hashing in Xml NameTable (#26241)
697e2b9

**Comment by danmosemsft** [comment] 2018-03-30 21:39
Regression size is 10-30% across several XML deserialization scenarios. Not all (depends on type?) and does not show up in serialization.

**Comment by danmosemsft** [comment] 2018-03-30 21:41
https://github.com/dotnet/corefx/issues/27636 ? @adamsitnik

**Comment by krwq** [comment] 2018-03-30 21:47
A little perf regression is expected because of better hashing used but 30% is slightly more than I'd have expected. @adamsitnik do you remember in what cases did you see regression and in which improvement?
I'm not sure how much further we would be able to optimize Marvin hashing.

**Comment by Lxiamail** [comment] 2018-04-02 22:39
Need further investigation, but no resource to finish before ZBB. Keep it in 2.1, but have to work on it in Post-ZBB.

**Comment by adamsitnik** [comment] 2018-04-03 15:48
I have investigated the perf regression for Windows here https://github.com/dotnet/corefx/issues/27636

To tell the long story short: we had a regression on Windows in the preview1 of 2.1 due to Marvin regression which was fixed by https://github.com/dotnet/coreclr/pull/16654 . Moreover https://github.com/dotnet/coreclr/pull/16659 have actually improved the perf.

However, we still have a big regression (100%) for Linux https://github.com/dotnet/corefx/issues/27786

I am closing this issue since the remaining regression is now tracked in #27786

**Closed by adamsitnik** 2018-04-03 15:48 UTC
Labels: Post-ZBB, area-Serialization, tenet-performance-benchmarks

**Comment by krwq** [comment] 2018-04-03 17:27
cc: @mconnew
