### ISSUE TITLE
System.IO.FileAttributes are Windows specific

### ISSUE THREAD

**Issue by polarapfel** [dotnet/corefx#15201] opened 2017-01-15 07:22 UTC
There is no way to retrieve POSIX file attributes on Linux via anything in System.IO. System.IO.FileAttributes only has enumerations for Windows specific file attributes.

**Comment by karelz** [comment] 2017-01-17 16:47
Looks like dupe of #312.

**Closed by karelz** 2017-01-17 16:47 UTC
Labels: area-System.IO
