### ISSUE TITLE
X-plat Performance Counters

### ISSUE THREAD

**Issue by KodrAus** [dotnet/corefx#4577] opened 2015-11-19 06:47 UTC
Hi all, is there any way I can get machine-specs with .NET Core that are cross-platform friendly? Like mono's PerformanceCounters?

Specifically I'm trying to get the physical RAM available for a machine in .NET Core. I notice mono has a native function `mono_determine_physical_ram_size` that is cross-platform. Are there any plans to incorporate something similar with .NET Core PerformanceCounters?

Thanks :)

**Comment by vancem** [comment] 2016-03-07 22:35
I have assigned this to the Future milestone.    At the moment we are driving to complete the V1.0 release and want to prioritize that above any features that look like they can be deferred (like this one).   You can ping this issue again sometime after the V1.0 release.

**Comment by foragerr** [comment] 2016-09-13 14:37
Ping! We're now post 1.0 release, wanted to check if there are any further thoughts about perf counters.

**Comment by KodrAus** [comment] 2016-09-13 21:06
Sorry I haven't kept up with for a while. Are cross platform perf counters a thing now in 1.0?

**Comment by vancem** [comment] 2016-09-13 22:04
There is an initiative to incorporate Mono's API into the .NET API.   This may simply fall out of that.   

I will get someone to comment on that.

**Comment by karelz** [comment] 2017-02-09 00:16
@vancem do you have API shape in mind for OS counters (CPU, memory, etc.)? Should we explore Mono (cc @marek-safar if he has advice here)

@galvesribeiro expressed interest on gitter to have something like that for Orleans (on Linux), potentially contributing the work to CoreFX code base.

**Comment by akoeplinger** [comment] 2017-02-09 00:33
Mono has implementations for reading a few of the performance counters like getting free/total memory, cpu usage etc that could be reused. I'm not sure however whether the PerformanceCounter API is the best approach xplat (though it'd probably help porting existing code).

**Comment by karelz** [comment] 2017-02-09 00:34
@akoeplinger Does Mono have any API for the tasks? Can you point us to it?

**Comment by vancem** [comment] 2017-02-09 00:36
First I note that some of this data (e.g. CPU Time, working set, etc), already exists on the System.Diagnostics.Process class. I think in general if there is a 'obvious' class where metrics 'belong' it should go on that (e.g. GC information on the GC class). If that would 'pollute' the API too much with this 'rare' case, we should make a helper class with a standard suffix (e.g. PerfMetrics),
Note that as a second step, these raw numbers could be passed to EventCounters (thus allowing all things that use EventSources to get at the information without needing to be 'in' the process. But that is
a second step.
@terrajobst @weshaggard

**Comment by akoeplinger** [comment] 2017-02-09 00:41
@karelz nothing special, just regular PerformanceCounter:

```bash
$ csharp -e 'new System.Diagnostics.PerformanceCounter ("Mono Memory", "Available Physical Memory").RawValue'
352276480
```

**Comment by karelz** [comment] 2017-02-09 00:46
@vancem given that we will introduce Performance Counters consumers for Windows, would it make sense to provide the same API also on Linux? It may not be the most beautiful, but it will be easy to use (samples everywhere), while we figure out the "right way". Thoughts?

**Comment by karelz** [comment] 2017-03-02 21:27
Triage: We decided it is dupe of #3906.

@brianrob can you please create new issue to expose GC, JIT events on NET Core via EventCounters or something like that.

**Closed by karelz** 2017-03-02 21:27 UTC
Labels: api-needs-work, area-System.Diagnostics.Tracing
