### ISSUE TITLE
Network build failures in 'prodcon/corefx/release/2.2/' - '20180831.01'

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#32053] opened 2018-08-31 17:57 UTC
@dotnet-mc-bot commented on [Thu Aug 30 2018](https://github.com/dotnet/core-eng/issues/4138)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1993890
  - **Agent:** DDVSOWINAGE079
  - **Error log:** fatal: unable to access '***': Failed to connect to devdiv.visualstudio.com port 443: Timed out...

@jcagme, @markwilkie

---

@MattGal commented on [Fri Aug 31 2018](https://github.com/dotnet/core-eng/issues/4138#issuecomment-417734716)

Not much actionable here, but I sent email to the VC Expert asking about any outages around 2018-08-31T01:46:28.7904247Z

---

@MattGal commented on [Fri Aug 31 2018](https://github.com/dotnet/core-eng/issues/4138#issuecomment-417743632)

From VSTS Experts:

> Sorry Matt, nothing really actionable on our side and no outages to report. There were >13k fetches in the hour period between 1 and 2am UTC, and only 3 failed so looking at that metric alone that’s 99.97% availability over the hour, notwithstanding the fact that the 3 failures look like network issues. I suspect it was a transient network issue somewhere between the agent and the VSTS application tier. In our experience with these cases, the issue is usually closer to the client (machine, network, etc)
>
> Sorry I couldn’t be more helpful – retry logic sounds reasonable.

As the changes to that would be in CoreFX, and we're likely to not want to invest in fixing the old behavior this close to YAML migration, I'm going to move this one to CoreFX to get triaged there (i.e. : Give your git clone some retry)

**Comment by wtgodbe** [comment] 2018-10-19 20:34
Closing as dupe of https://github.com/dotnet/corefx/issues/32769

**Comment by karelz** [comment] 2018-10-19 20:35
Duplicate of #32769

**Closed by wtgodbe** 2018-10-19 20:34 UTC
Labels: area-Infrastructure, bug

**Comment by MattGal** [comment] 2018-10-19 20:35
Thanks Will, and sorry that we do periodically make dupes.
