### ISSUE TITLE
[backport request] IOException during "File.WriteAllText" to the file under NFS on Linux with corefx 1.0.3

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/corefx#16256] opened 2017-02-17 06:56 UTC
At first, I'd like to confirm can I request backport here? If not, I'll turn down my PR.

I'm facing below IOException with this simple code when ``/mnt/volume`` is a NFS shared directory even if the user of process has a valid access to ``/mnt/volume`` and it exists.
```cs
File.WriteAllText(@"/mnt/volume/test.txt", "TextToWrite");
```

```
System.UnauthorizedAccessException: Access to the path '/mnt/volume/output.txt' is denied. ---> System.IO.IOException: Bad file descriptor
   --- End of inner exception stack trace ---
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents)
   at ConsoleApplication.Startup.<>c.<<Configure>b__1_0>d.MoveNext()
```

This error only occurs on .NET Core 1.0. If I updated  .NET Core to 1.1 (update project.json and use the .NET Core 1.1 runtime), this doesn't occur. From the stacktrace, I suspect this commit fixed the problem.
https://github.com/dotnet/corefx/commit/60d1b3d22eca28ca3dfe375d0cefd2bd16059261

I think .NET Core 1.0 is still LTS phase, so is there any possibility to backport this commit to 1.0.x to fix the issue?

Here is the dotnet info where I reproduce this issue.
```
# dotnet --info
.NET Command Line Tools (1.0.0-preview2-003156)

Product Information:
 Version:            1.0.0-preview2-003156
 Commit SHA-1 hash:  33dabee5d8

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.3
 OS Platform: Linux
 RID:         rhel.7.2-x64
```

The dotnet info I confirmed .NET Core 1.1 fixes the isseu (on the same machine).
```
# dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003175)

Product Information:
 Version:            1.0.0-preview2-1-003175
 Commit SHA-1 hash:  bb053ed000

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.3
 OS Platform: Linux
 RID:         rhel.7.2-x64
```

**Comment by karelz** [comment] 2017-02-17 08:37
@leecow what is our backporting policy for LTS?

**Comment by leecow** [comment] 2017-02-17 17:30
@karelz - case by case basis. If the issue is broadly impacting then we can review and decide.

**Comment by tanaka-takayoshi** [comment] 2017-02-20 08:16
@leecow @karelz Thank you for comments. How about in this case? How do you or your team decide this is broadly impacting or not?

**Comment by leecow** [comment] 2017-02-21 17:33
@tanaka-takayoshi - I have added this issue to the review list for the next LTS updates.

**Comment by karelz** [comment] 2017-02-22 21:15
@tanaka-takayoshi also number of reports/asks is usually helpful.

**Comment by omajid** [comment] 2017-03-14 13:55
Is there some way community can provide input on the review list? For example an individual or an organization may strongly desire a fix and would be willing to help with the review/testing workload.

In terms of reports and requests for a fix, is any consideration applied to "hey, I am user running into bug foobar, please fix!" vs "hey, i am running into bug foobar, fix is baz and here's how I tested and unit tested this. I am willing to help with getting this released"?

**Comment by danmosemsft** [comment] 2017-08-09 18:11
@JeremyKuhne @ianhays please comment on whether this should go into 1.x.

@omajid we don't have a formal process beyond noting that an issue has a lot of traffic/thumbs up.

**Comment by danmosemsft** [comment] 2017-08-14 23:15
@JeremyKuhne @stephentoub please comment on value/risk of backporting.

**Comment by JeremyKuhne** [comment] 2017-08-14 23:39
It seems pretty low risk to me and reasonably valuable.

**Comment by danmosemsft** [comment] 2017-08-17 20:49
this was merged into release and if all goes well will go out in next servicing

**Closed by danmosemsft** 2017-08-17 20:49 UTC
Labels: area-System.IO, bug

**Comment by omajid** [comment] 2017-08-17 21:39
Thanks! We have been carrying this fix in our 1.x builds for a few months now and haven't seen any issues. @tanaka-takayoshi was kind enough to verify that this fix does fix the original issue.

**Comment by danmosemsft** [comment] 2017-08-17 21:44
great! PS maybe try 2.0 too?
