### ISSUE TITLE
System.Text.Json Deserialize Not Ignoring Property

### ISSUE THREAD

**Issue by realdevhl** [dotnet/corefx#39373] opened 2019-07-11 01:43 UTC
Take the following class:

```
public class MyObject
{
    [JsonIgnore]
    public List<object> MyAttribute { get; set; }

    [JsonPropertyName("MyAttribute")]
    public int MyAttributeCount { get; set; }
}
```

And then try to parse some JSON

```
json = $"{{\"MyAttribute\": 0}}";

MyObject myObject = JsonSerializer.Parse<MyObject>(json);
```

Results in the following error.

'The JSON property name for 'MyObject.MyAttributeCount' collides with another property.'

If I remove the property decorated with JSONIgnore then it works.

I am using System.Text.Json v4.6.0-preview6.19303.8

**Comment by ericstj** [comment] 2019-07-12 15:28
@layomia can you have a look?

**Comment by steveharter** [comment] 2019-07-15 18:58
This is a duplicate of #38668

This was fixed in https://github.com/dotnet/corefx/pull/38935

**Closed by steveharter** 2019-07-15 18:58 UTC
Labels: area-System.Text.Json
