### ISSUE TITLE
Enable Validation of entire graph

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#23460] opened 2017-08-22 04:36 UTC
Please implement a way to validate an entire graph of object, so validating the root object will walk throughout the entire object graph and validate all subsequent children and their properties:

```
public class Company
{
  [Required]
  public string Name { get; set; } 
  public ICollection<Contact> Contacts { get; set; }  
}

public class Contact
{
  [Required]
  public string Name { get; set; }    
  public string Address { get; set; }
}

public class Address
{
  [Required]
  public string Street { get; set; }
}
```

Usage:
   
    Validator.TryValidateObject(company, ...);

The validation should walk thru the whole graph and validate both `Name` properties and the `Street` property.

**Comment by divega** [comment] 2017-08-24 21:57
**DataAnnotations Triage:** We believe that this is something that would be better addressed in an opinionated manner by an external component instead of trying to solve it in a general way in DataAnnotations. 

Some of the challenges that need to be sorted out in an implementation are:

- Deal with cycles
- Whether to look at private, internal, protected, fields vs. only public properties
- How to prevent traversing into graphs of system types
- More generally, when to stop traversing the graph.

**Closed by divega** 2017-08-24 21:57 UTC
Labels: area-System.ComponentModel.DataAnnotations

**Comment by weitzhandler** [comment] 2017-08-24 22:31
@divega 
I'm sorry to see this closed, I was merely asking for a few additional overloads in the `Validator` class.

As the concerns you pointed out:

- Deal with cycles
-- We can have a visitor that validates object wasn't visited
- Whether to look at private, internal, protected, fields vs. only public properties
-- Why should we? public properties only. Alternatively, we can instead introduce a different validation attribute to explicitly opt-in properties by annotating them with it, for instance, let's say we have a `ValidateObjectAttribute` attribute, so given the example [above](https://github.com/dotnet/corefx/issues/23460#issue-251835720), the `Company.Contacts` and the `Contact.Address` properties will be decorated by it. When the `Validator` walks through the validation properties of the type and discovers a `ValidateObject` attribute, it will walk in and validate it too.
- How to prevent traversing into graphs of system types
-- I think that makes explicit opt-in a better choice indeed
- More generally, when to stop traversing the graph
-- That should also be like it currently works with the `Validator` class, be determined by the `validateAllProperties` flag.

I'm hereby changing my suggestion and re-opening it for future consideration, so that instead of having additional overloads in the `Validator` class, a new `ValidateObjectAttribute : ValidationAttribute` should be introduced, to be able to add graph properties to the validation tree on demand.

**Comment by weitzhandler** [comment] 2017-08-24 22:37
@divega 
I'm sorry to see this closed, I was merely asking for a few additional overloads in the `Validator` class.

As the concerns you pointed out:

- Deal with cycles
  - We can have a visitor that validates object wasn't visited
- Whether to look at private, internal, protected, fields vs. only public properties
  - Why should we? public properties only. Alternatively, we can instead introduce a different validation attribute to explicitly opt-in properties by annotating them with it, for instance, let's say we have a `ValidateObjectAttribute` attribute, so given the example [above](https://github.com/dotnet/corefx/issues/23460#issue-251835720), the `Company.Contacts` and the `Contact.Address` properties will be decorated by it. When the `Validator` walks through the validation properties of the type and discovers a `ValidateObject` attribute, it will walk in and validate it too.
- How to prevent traversing into graphs of system types
  - I think that makes explicit opt-in a better choice indeed
- More generally, when to stop traversing the graph
  - That should also be like it currently works with the `Validator` class, be determined by the `validateAllProperties` flag.

I'm hereby changing my suggestion and would like to have it reopened for future consideration, so that instead of having additional overloads in the `Validator` class, a new `ValidateObjectAttribute : ValidationAttribute` should be introduced, to be able to add graph properties to the validation tree on demand. Should I open a new issue with the new suggestion?

**Comment by weitzhandler** [comment] 2017-08-24 22:48
@divega 
I'm sorry to see this closed, initially I was merely asking for a few additional overloads in the `Validator` class, but as for the concerns you pointed out, I think we should instead introduce a new `ValidateObjectAttribute : ValidationAttribute` attribute, to explicitly annotate properties we want to be walked in by the validation process, after that is implemented, let's address the issues:

- Deal with cycles
  - We can have a visitor that validates object wasn't visited
- Whether to look at private, internal, protected, fields vs. only public properties
  - As per the new suggestion, developer decides what fields we look into by annotating them explicitly. So given the example in my [original post](https://github.com/dotnet/corefx/issues/23460#issue-251835720), should the `Company.Contacts` and the `Contact.Address` properties will be decorated with the `ValidateObject` attribute, and the `Validator` or any other validation tool, shall walk through the requested properties' instances, and validate them as well.
- How to prevent traversing into graphs of system types
  - This will be solved too be having to opt in explicitly
- More generally, when to stop traversing the graph
  - That should also be like it currently works with the `Validator` class, be determined by the `validateAllProperties` flag.

Now since my suggestion changed in its essence, I'd like to request you to either re-open it or give me the permission to post a fresh one.

**Comment by divega** [comment] 2017-08-25 00:28
> I'd like to request you to either re-open it or give me the permission to post a fresh one.

@weitzhandler you don't really need our permission, but I would like you to understand that the reason we closed this is that we don't think this belongs in the DataAnnotations library that is part of .NET, not necessarily that we don't agree it is a good idea. I would like to encourage you to consider that this is a as potential contribution someone could make to the .NET ecosystem by extending it with new libraries rather than trying to address all the possible scenarios in the base class libraries. Look at the most successful NuGet packages for examples of this.

**Comment by weitzhandler** [comment] 2017-08-25 00:34
@divega thanks for your kind response, with permission I meant to whether you might reconsider this suggestion in the sufferer new opt-in suggestion.
The validator is a static class pretty hard to extend, I'd be more glad to extend extend the existing validation rather than adding external hackey workaround and patches to something that can easily fit in. Will you guys accept a PR addressing this?

**Comment by NiekGr** [comment] 2018-09-14 14:45
@karelz since you have added this issue to the 2.1.0 milestone, was this issue ment to be addressed with new features? If so, the issue was closed before you added it to the milestone.

**Comment by karelz** [comment] 2018-09-14 17:33
@NiekGr if you look at the timeline, you can see that the issue was closed 2 months before I set the milestone.
The milestone just reflects during which timeframe it was closed (super useful for fixed issues and not-so-useful-but-harmless for Won't Fix/By Design resolutions like this one -- I do bulk edits, so I don't distinguish between reasons for closure).

**Comment by NiekGr** [comment] 2018-09-15 21:13
> 
> 
> @NiekGr if you look at the timeline, you can see that the issue was closed 2 months before I set the milestone.
> The milestone just reflects during which timeframe it was closed (super useful for fixed issues and not-so-useful-but-harmless for Won't Fix/By Design resolutions like this one -- I do bulk edits, so I don't distinguish between reasons for closure).

Oké, thank you very much for the fast reply.
