### ISSUE TITLE
tests periodically fail with "too many open files" on macOS machines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21892] opened 2017-07-05 18:32 UTC
We periodically have tests fail on our macOS machines with `System.IO.IOException : Too many open files`

eg 
https://github.com/dotnet/corefx/issues/20226 
https://github.com/dotnet/corefx/issues/21813
https://github.com/dotnet/corefx/issues/12503
https://github.com/dotnet/corefx/issues/18462

According to @MattGal " For our OSX machines (which were basically set up once then cloned, as they are not VMs) ulimit -a shows 256 open files and 8 MB stack size, which is lower than the init-tools setting " (this may be just because init tools wasn't run in that tab)

We set `ulimit -n` (ie file descriptors) to 2048 in init-tools.sh on macOS  only https://github.com/dotnet/corefx/blob/master/init-tools.sh#L27 . This is supposed to set both hard and soft limit - although I'm not sure this script is run as sudo. On my Ubuntu machine, `ulimit -n` shows 1024.

This may not have actually applied until April (fixed in https://github.com/dotnet/corefx/pull/19363)

We should either modify init-tools.sh to increase this limit and/or run `lsof` to try to figure out what the files are that are getting held open.

@pjanotti perhaps you could try lsof a few times during a test run on macOS, see what number we typically get up to, and whether a leak stands out?

**Comment by danmosemsft** [comment] 2017-07-05 20:11
@MattGal tells me that the OSX machines that run tests have not had init-tools.sh run on, so they're using 256.

**Comment by pjanotti** [comment] 2017-07-05 22:31
Hi @MattGal just to be sure that we are talking about the same thing: the ulimit inside a script only has effect for the duration of the script, that's why measuring it outside the scripts doesn't show 2048. For now I am going to try to pursue the route mentioned by Dan: get a repro and more info about what is holding the files.

**Comment by danmosemsft** [comment] 2017-07-06 00:33
@pjanotti what I/we were trying to say is: the tests can run on machines on which init-tools.sh has never run: so if we do need a higher ulimit for tests, it can't be set there.

**Comment by MattGal** [comment] 2017-07-06 01:16
@pjanotti Ah, I did not realize this, that's useful to know.  I have a suggestion then.

We could, if detecting the right combination of stuff, declare an item group on the test project and include one or more "TestCommandLines" ITaskItems as seen here:
https://github.com/dotnet/buildtools/blob/3162466ab961d8bc851a60d24c3a80649ddc631c/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L279

When RunTests.sh is created, we basically just take all off the TestCommandLines items we generated and stick them into the script (among other stuff).  You can test this locally too, it's not specific to official run execution or anything.   If this solves the problem, it's a super cheap fix.  That said, if the customer will have a limit of 256, it may be more correct to stick to that limit, if at all possible.

**Comment by pjanotti** [comment] 2017-07-12 19:10
@MattGal I did validate that and it works as expected. I have the list of tests that Dan added at the top but it will be good if we have some way to check all tests hitting such issue, is that possible?

**Comment by MattGal** [comment] 2017-07-12 20:26
@pjanotti  unfortunately while it's possible to fetch all the logs for a run I think this sort of failure can manifest in multiple ways, so it's difficult to say exactly which tests hit it.  @Priya91  has a PR doing a really similar thing right now, she may have greater context as to which other tests need this. 

Since the Helix VMs always have ulimit set to 256, anything that reliably fails there on OSX is a candidate.

**Comment by pjanotti** [comment] 2017-07-12 20:48
@MattGal @danmosemsft the fix itself is very simple (see #22124 mentioned above) and I confirmed the setting taking effect inside the test code (via getrlimit API on a macOS). The hard part now is finding which tests we want to apply that and the respective value for the limit. I am a bit hesitant of applying it without the owners of each area first checking the tests and the respective limit, while the risk of hiding bugs due to increased limit may be small the impact of such bugs can be high.

**Comment by danmosemsft** [comment] 2017-07-19 17:15
@pjanotti do we have any evidence that some tests are misbehaving? Is it apparently as simple as over stressing the machine?

**Comment by MattGal** [comment] 2017-07-19 17:43
Setting the limit to whatever CI does (I think it's 2000 because tests are run in the same context as the init-tools call?) should be tolerable since that's how CI tests were run for a very long time without people's objection.  I do agree the choice to up the limit should be on the area owners as well, as well as logged in some way that Dan could audit.

**Comment by danmosemsft** [comment] 2017-07-19 18:25
@pjanotti I would recommend seeing what we actually use (apparently `lsof` is the way)

**Comment by pjanotti** [comment] 2017-07-19 18:32
@danmosemsft the issue is that we need to run in the same context as the test code since the limit is per session. Let's do the following: I will add the setting for the tests that hit this recently and then I will look into getting this information inside the test process (in case of hitting the issue). If that is feasible we can consider the investment as a more long term and robust option.

**Comment by danmosemsft** [comment] 2017-07-19 18:36
good point. sounds good.

**Comment by pjanotti** [comment] 2017-07-20 18:51
@danmosemsft @MattGal I just added it to the console perf test, the only other issue listed here already got its `ulimit` updated for macOS.

**Comment by pjanotti** [comment] 2017-07-20 22:18
@danmosemsft @MattGal for now let's keep this issue open and see if we hit it on other tests. If that happens we can look at capturing information about opened files to give better information to the tests owners to decide if they just want to increase the limit or something else.

**Comment by pjanotti** [comment] 2017-08-07 15:21
@danmosemsft @MattGal if we are not seeing this error anymore I think it is time to close this issue.

**Closed** 2017-08-07 16:55 UTC
Labels: area-Infrastructure, enhancement, os-mac-os-x
