### ISSUE TITLE
Unable to load DLL 'System.Native' during System.Diagnostics.Process.Start

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#16687] opened 2017-03-03 20:18 UTC
# Repro

1. dotnet new
2. `project.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001651-00</RuntimeFrameworkVersion>
  </PropertyGroup>

</Project>
```

3. `dotnet restore`
4. `Program.cs`
```
using System;

namespace a8
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Diagnostics.Process.Start("cmd.exe");
            Console.WriteLine("Hello World!");
        }
    }
}
```
5. `dotnet run`

# Expected
Process runs

# Actual
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'System.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.Sys.GetPid()
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at a8.Program.Main(String[] args) in D:\temp\a8\Program.cs:line 9
```
# Env
```
D:\temp\a8> dotnet --version
2.0.0-alpha-005165
D:\temp\a8> dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-beta-001651-00
  Build    : 85f2ec09e9147af4c1f5e5fc04bc0fb366419703
```

**Comment by mellinoe** [comment] 2017-03-03 22:05
I think this is most likely a duplicate of https://github.com/dotnet/corefx/issues/16621, which should be fixed in the latest builds.

@ericstj

**Comment by weshaggard** [comment] 2017-03-03 22:11
Yes this is a duplicate of https://github.com/dotnet/corefx/issues/16621 which should be fixed with today's packages.

**Closed by weshaggard** 2017-03-03 22:11 UTC
