### ISSUE TITLE
NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds failed with System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#19964] opened 2017-05-19 00:09 UTC
again https://mc.dot.net/#/user/mmitche/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fportable~2Fcli~2F//workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test~2FNoCallback_RevokedCertificate_NoRevocationChecking_Succeeds

```
nhandled Exception of Type System.Net.Http.HttpRequestException
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.\n---- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?)
Stack Trace :
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/GenPRTest/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 462
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__9.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/GenPRTest/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error) in /mnt/j/workspace/dotnet_corefx/master/GenPRTest/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.cs:line 644
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult) in /mnt/j/workspace/dotnet_corefx/master/GenPRTest/portable-linux-Config_Debug+OuterLoop_false_prtest/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandl
```

https://github.com/dotnet/corefx/issues/19701 simlar

**Comment by danmosemsft** [comment] 2017-05-22 16:31
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170522.02/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.SyncWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

also
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170522.02/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadString_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

```
   at System.Net.HttpWebRequest.GetResponse() in /root/corefx/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1012
   at System.Net.WebClient.GetWebResponse(WebRequest request) in /root/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 249
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream) in /root/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 851
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer) in /root/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 983
   at System.Net.WebClient.UploadFile(Uri address, String method, String fileName) in /root/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 566
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Tests.WebClientTestBase.<UploadFile_Success>d__23.MoveNext() in /root/corefx/src/System.Net.WebClient/tests/WebClientTest.cs:line 678
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by Jiayili1** [comment] 2017-05-23 06:33
also: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170523.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test~2FGetAsync_SupportedSSLVersion_Succeeds(sslProtocols:%20Tls,%20url:%20%5C%22https:~2F~2Fwww.ssllabs.com:10301~2F%5C%22)

**Comment by v-haren** [comment] 2017-05-25 08:29
Failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/57/testReport/System.Net.Http.Functional.Tests/HttpClientHandler_ServerCertificates_Test/NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds/

**Comment by Jiayili1** [comment] 2017-06-01 07:29
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170601.05/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test~2FNoCallback_RevokedCertificate_NoRevocationChecking_Succeeds

**Comment by Jiayili1** [comment] 2017-06-15 06:40
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170615.01/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test~2FNoCallback_RevokedCertificate_NoRevocationChecking_Succeeds

**Comment by v-haren** [comment] 2017-06-15 08:12
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_portablelinux_debug/79/testReport/System.Net.Http.Functional.Tests/HttpClientHandler_ServerCertificates_Test/NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds/

**Comment by karelz** [comment] 2017-12-22 20:18
Duplicate of #19701

**Closed by karelz** 2017-12-22 20:18 UTC
Labels: area-System.Net.Http, os-linux, test-run-core
