### ISSUE TITLE
HTTP2: Support responses with trailers

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#31979] opened 2018-08-27 19:11 UTC
HTTP2 allows sending trailers. It does this in HEADERS/CONTINUATION frames that follow the response body, similar to HTTP/1.1 with chunked encoding.

We need to read and ignore these trailers, just as we do for HTTP/1.1 currently.

**Comment by karelz** [comment] 2019-02-27 19:43
Duplicate of #34912

**Closed by karelz** 2019-02-27 19:43 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, enhancement
