### ISSUE TITLE
KDCSetup failing on multiple Unix OSes in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#12715] opened 2016-10-17 15:21 UTC
```
--> Running transaction check
  ---> Package krb5-libs.x86_64 0:1.12.2-14.el7 will be updated
  --> Processing Dependency: krb5-libs(x86-64) = 1.12.2-14.el7 for package: krb5-devel-1.12.2-14.el7.x86_64
  --> Processing Dependency: libkdb5.so.7()(64bit) for package: krb5-devel-1.12.2-14.el7.x86_64
  ---> Package krb5-libs.x86_64 0:1.13.2-12.el7_2 will be an update
  ---> Package krb5-server.x86_64 0:1.13.2-12.el7_2 will be installed
  System.Runtime.Serialization.Xml.Performance.Tests -> /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/bin/AnyOS.AnyCPU.Release/System.Runtime.Serialization.Xml.Performance.Tests/System.Runtime.Serialization.Xml.Performance.Tests.dll
  http://olcentgbl.trafficmanager.net/centos/7/extras/x86_64/repodata/a7c44548f84080446edd33e17e9c37274a1f195f797088cb4153254478d9881a-filelists.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
  Trying other mirror.
  
  
   One of the configured repositories failed (CentOS-7 - Extras),
   and yum doesn't have enough cached data to continue. At this point the only
   safe thing yum can do is fail. There are a few ways to work "fix" this:
  
       1. Contact the upstream for the repository and get them to fix the problem.
  
       2. Reconfigure the baseurl/etc. for the repository, to point to a working
          upstream. This is most often useful if you are using a newer
          distribution release than is supported by the repository (and the
          packages for the previous distribution release still work).
  
       3. Disable the repository, so yum won't use it by default. Yum will then
          just ignore the repository until you permanently enable it again or use
          --enablerepo for temporary usage:
  
              yum-config-manager --disable extras
  
       4. Configure the failing repository to be skipped, if it is unavailable.
          Note that yum will try to contact the repo. when it runs most commands,
          so will have to try and fail each time (and thus. yum will be be much
          slower). If it is a very temporary problem though, this is often a nice
          compromise:
  
              yum-config-manager --save --setopt=extras.skip_if_unavailable=true
  
  failure: repodata/a7c44548f84080446edd33e17e9c37274a1f195f797088cb4153254478d9881a-filelists.sqlite.bz2 from extras: [Errno 256] No more mirrors to try.
  http://olcentgbl.trafficmanager.net/centos/7/extras/x86_64/repodata/a7c44548f84080446edd33e17e9c37274a1f195f797088cb4153254478d9881a-filelists.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
  Error occurred during installation, aborting
  Operating System: centos
  
  Stopping KDC..
  Removing config files
  Removing KDC database
  Removing NTLM credentials file
  Cleanup completed
```

**Comment by stephentoub** [comment] 2016-10-17 15:25
Similar result with slightly different error on Ubuntu:
```
The following additional packages will be installed:
    krb5-config krb5-user libverto-libevent1 libverto1
  Suggested packages:
    krb5-kpropd krb5-kdc-ldap
  The following NEW packages will be installed:
    krb5-admin-server krb5-config krb5-kdc krb5-user libverto-libevent1
    libverto1
  0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
  Need to get 408 kB of archives.
  After this operation, 1,455 kB of additional disk space will be used.
  Get:1 http://azure.archive.ubuntu.com/ubuntu yakkety/main amd64 libverto-libevent1 amd64 0.2.4-2.1ubuntu2 [5,742 B]
  Get:2 http://azure.archive.ubuntu.com/ubuntu yakkety/main amd64 libverto1 amd64 0.2.4-2.1ubuntu2 [9,132 B]
  Get:3 http://azure.archive.ubuntu.com/ubuntu yakkety/main amd64 krb5-config all 2.3 [23.4 kB]
  Err:4 http://azure.archive.ubuntu.com/ubuntu yakkety/universe amd64 krb5-user amd64 1.14.3+dfsg-1ubuntu1
    404  Not Found
  Err:5 http://azure.archive.ubuntu.com/ubuntu yakkety/universe amd64 krb5-kdc amd64 1.14.3+dfsg-1ubuntu1
    404  Not Found
  Err:6 http://azure.archive.ubuntu.com/ubuntu yakkety/universe amd64 krb5-admin-server amd64 1.14.3+dfsg-1ubuntu1
    404  Not Found
  Fetched 38.3 kB in 0s (109 kB/s)
  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/k/krb5/krb5-user_1.14.3+dfsg-1ubuntu1_amd64.deb  404  Not Found
  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/k/krb5/krb5-kdc_1.14.3+dfsg-1ubuntu1_amd64.deb  404  Not Found
  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/k/krb5/krb5-admin-server_1.14.3+dfsg-1ubuntu1_amd64.deb  404  Not Found
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  Error occurred during installation, aborting
```

**Comment by stephentoub** [comment] 2016-10-17 15:27
@karelz, @mmitche, looking back through the logs from the past week or two, this appears to be causing intermitten failures in outerloop runs on at least CentOS and RHEL.  I'm not sure what's changed in these environments, nor why it's not consistent on every run.

Examples:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_debug/29/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.10_release/25/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_release/35/consoleText

**Comment by karelz** [comment] 2016-10-17 15:39
@mmitche who's the right person to look at it as a high pri?

**Comment by karelz** [comment] 2016-10-17 15:40
@stephentoub why System.Net? Isn't it general infra?

**Comment by stephentoub** [comment] 2016-10-17 15:43
> why System.Net? Isn't it general infra?

No, this is from the script that runs as part of the System.Net.Security tests to configure a kerberos environment for the NegotiateStream tests to use on Unix.

**Comment by mmitche** [comment] 2016-10-17 15:45
@karelz @stephentoub Nothing has changed for those runs for infra in the last week.  I don't have the bandwidth to investigate this.

**Comment by karelz** [comment] 2016-10-17 16:05
@ericeil could you please help take a look?
In the worst case we should move the tests from CI to Outter loop and make it part of our Networking tests stability push planned for after netstandard2.0 work.

**Comment by stephentoub** [comment] 2016-10-17 16:10
> In the worst case we should move the tests from CI to Outter loop

They are outer loop.

**Comment by mellinoe** [comment] 2016-10-17 17:24
Related: https://github.com/dotnet/corefx/issues/12107

Ubuntu 16.10 has always had trouble with this script, it fails very often there. My only guess is that the package feed used by Ubuntu 16.10 is not as reliable as the other Ubuntu feeds we happen to be using.

An obvious fix is to have the packages pre-installed on our CI images so the script isn't trying to download and install stuff from the package manager... That's a ton of work, though. If we were using docker or something like we are in a couple of other repos, I could see that option being easier and making a bit more sense.

**Comment by karelz** [comment] 2016-10-17 17:39
@mellinoe aren't those dupes of each other? Can we close one of them? (this one probably)

**Comment by ericeil** [comment] 2016-10-17 22:15
Closing this as duplicate of #12107.

**Closed by ericeil** 2016-10-17 22:15 UTC
Labels: area-System.Net, blocking-clean-ci, test bug, X-Plat
