### ISSUE TITLE
Q: TaskStatus.Canceled for non-matching OperationCanceledException

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#41186] opened 2019-09-18 21:10 UTC
When I run:
```cs
        static void Main(string[] args)
        {
            Task fooTask = Foo();
            System.Console.WriteLine(fooTask.Status);
            Task tokenTask = Task.Run(() => throw new OperationCanceledException(), new CancellationTokenSource().Token);
            tokenTask.ContinueWith(t => System.Console.WriteLine(t.Status)).Wait();
        }

        static async Task Foo()
        {
            throw new OperationCanceledException();
        }
```
it outputs:
```
Canceled
Canceled
```
I expected the Tasks to be in the `Faulted` state because the `OperationCanceledException` isn't associated with the Task token.

Why are these Tasks `Canceled`?

**Comment by davidsh** [comment] 2019-09-19 04:04
@stephentoub

**Comment by stephentoub** [comment] 2019-09-19 12:55
This is by design.

For all `async` methods, `OperationCanceledException` is special-cased to complete the returned `Task` as `Canceled` rather than `Faulted`.  It pays zero attention to cancellation tokens, because the C# language / compiler for `async` methods has zero knowledge of cancellation tokens.  As such, rather than having all exceptions (even if for cancellation) be `Faulted`, we chose to special-case all `OperationCanceledExceptions`.

The `Task.Run` case is just an extension of that.  There are multiple `Task.Run` overloads that differ only by delegate return type, and since your lambda always throws and doesn't have any return statements that would indicate would delegate type to map to and thus which overload to map to, the C# betterness rules are selecting the `Func<Task>` overload.  That overload (as well as the `Func<Task<TResult>>` overload) are primarily intended to be used with `async` methods, as they "unwrap" the returned task in order to marshal it to the task returned from the `Run` call.  In order to not have a subtle difference in behavior based on whether the delegate synchronously or asynchronously throws an `OperationCanceledException`, this overload similarly treats all `OperationCanceledException`s as cancellation.

**Comment by tarekgh** [comment] 2019-09-19 16:06
@tmds I am closing this issue per @stephentoub answer. Feel free to respond back with any more questions if there is anything unclear. Thanks.

**Closed by tarekgh** 2019-09-19 16:06 UTC
Labels: area-System.Threading.Tasks, question

**Comment by tmds** [comment] 2019-09-19 17:51
Yes, question answered. Thanks @stephentoub .
