### ISSUE TITLE
WebRequest.DefaultWebProxy in .net core for corss platform

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28642] opened 2018-03-30 06:31 UTC
@nQuantPlatforms commented on [Sat Mar 24 2018](https://github.com/dotnet/core/issues/1381)

# Issue Title

WebRequest.DefaultWebProxy in .net core for corss platform

# General
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
<PropertyGroup>
    <RuntimeIdentifiers>win10-x64;osx-x64;linux-x64;</RuntimeIdentifiers>
</PropertyGroup>

Using above RID and running on Win 10 gives me platform not supported exception.
My app need to read proxy from Win, OSX and Linux platform. Whats the best way to get proxy in Core app without having to create separate platform specific library ?

**Comment by davidsh** [comment] 2018-03-30 15:08
This is basically a duplicate of https://github.com/dotnet/corefx/issues/16695

**Comment by karelz** [comment] 2018-03-30 15:41
@davidsh how is it different from #26494? Is that a duplicate too?

**Comment by karelz** [comment] 2018-03-30 15:41
Duplicate of #16695

**Closed by karelz** 2018-03-30 15:41 UTC
Labels: area-System.Net

**Comment by davidsh** [comment] 2018-03-30 15:47
>@davidsh how is it different from #26494? Is that a duplicate too?

Yes I would say it is essentially a duplicate of the same problem of exposing the calculated proxy for a given input destination Uri.

Most apps don't really need that directly since the HTTP stacks themselves know how to detect proxy settings and then calculate the proxy based on destination Uri (which might involve PAC file processing). But some custom apps like to know the proxy Uri separately in case they aren't using the HTTP stack directly.  This is why there have been several requests for this to expose this information in the public APIs we have (which are PNSE in .NET Core).

cc: @stephentoub @geoffkizer

**Comment by karelz** [comment] 2018-03-30 16:46
OK, closed the other one as dupe as well. We should come up with unified strategy for proxies.
