### ISSUE TITLE
Uri constructor with UriKind.RelativeOrAbsolute incorrectly calls macOS path relative when it's absolute

### ISSUE THREAD

**Issue by TylerLeonhardt** [dotnet/corefx#40428] opened 2019-08-19 23:25 UTC
Here's a simple PowerShell example:

```pwsh
[Uri]::new("/Users/tyler/").IsAbsoluteUri

# gives you

true

# and 

[Uri]::new("/Users/tyler/", [System.UriKind]::RelativeOrAbsolute).IsAbsoluteUri

#gives you

false
```

I can repro this in .NET Core 3.0 and .NET Core 2.1.

Is this behavior expected? It's causing [Newtonsoft to do the wrong thing](https://github.com/JamesNK/Newtonsoft.Json/issues/2128#issuecomment-522261724) when serializing and deserializing `Uri`s.

**Comment by TylerLeonhardt** [comment] 2019-08-19 23:31
Note, based on https://github.com/JamesNK/Newtonsoft.Json/issues/2128 this issue also happens with UNC paths.

**Comment by davidsh** [comment] 2019-08-19 23:56
@wtgodbe

**Comment by wtgodbe** [comment] 2019-08-20 00:03
This is a duplicate of https://github.com/dotnet/corefx/issues/22098 and is by-design - see https://github.com/dotnet/corefx/issues/22098#issuecomment-315296271 for the reccomended workaround (cc @tmds)

**Closed by wtgodbe** 2019-08-20 00:03 UTC
Labels: area-System.Net
