### ISSUE TITLE
CustomAttribute implementation missing in MetadataLoadContext for dynamic loading of Razor Components (DLLs) and relative MVC rounting support

### ISSUE THREAD

**Issue by DanielS4n** [dotnet/corefx#35755] opened 2019-03-04 18:43 UTC
It is important to be able to dynamically load razor component libraries to make modular asp applications. I've managed to use MetadataLoadContext to load multiple DLLs but the MVC service can not function without the GetCustomAttributes implementation.

**When will it be possible to use them?**

see :
...
// Operations that are invalid for ReflectionOnly objects.
        public sealed override object[] GetCustomAttributes(bool inherit) => **throw new InvalidOperationException(SR.Arg_ReflectionOnlyCA);**
        public sealed override object[] GetCustomAttributes(Type attributeType, bool inherit) => **throw new InvalidOperationException(SR.Arg_ReflectionOnlyCA);**

**Comment by jkotas** [comment] 2019-03-05 22:29
MetadataLoadContext is for inspecting metadata. It does not allow running the code from the assemblies being inspected. GetCustomAttributes methods throw exception because of they run code.

Are you actually trying to run the razor components? If yes, you may be want to look at the plugin samples at https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin

**Comment by steveharter** [comment] 2019-06-13 14:19
Closing this as by design.

**Closed by steveharter** 2019-06-13 14:19 UTC
Labels: area-System.Reflection, question
