### ISSUE TITLE
System.Net.Sockets tests crashed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4204] opened 2015-10-28 15:48 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5725/console
```
Discovering: System.Net.Sockets.Tests
  Discovered:  System.Net.Sockets.Tests
  Starting:    System.Net.Sockets.Tests
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00111\lib\tests.targets(129,5): warning MSB3073: The command "CoreRun.exe xunit.console.netcore.exe System.Net.Sockets.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -1073741819. [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\tests\FunctionalTests\System.Net.Sockets.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00111\lib\tests.targets(136,5): error : One or more tests failed while running tests from 'System.Net.Sockets.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\tests\FunctionalTests\System.Net.Sockets.Tests.csproj]
```

**Comment by CIPop** [comment] 2015-10-28 18:22
Can someone help getting the log that the message is referring to:

> d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00111\lib\tests.targets(136,5): error : One or more tests failed while running tests from 'System.Net.Sockets.Tests' please check log for details!

**Comment by weshaggard** [comment] 2015-10-28 18:26
The log it is referring to is http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/5725/console

**Comment by CIPop** [comment] 2015-10-28 18:31
Thanks @weshaggard but that's the log that @stephentoub attached as well. 

This seems to be the only relevant portion from the log and it's not telling me why the tests failed:
```
     System.Net.Sockets.AsyncServer.Tests  Total: 354, Errors: 0, Failed: 0, Skipped: 0, Time: 66.825s
  System.Net.Sockets.APM.Performance.Tests -> d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Net.Sockets.APM.Performance.Tests\System.Net.Sockets.APM.Performance.Tests.dll
  System.Net.Sockets.Tests -> d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Net.Sockets.Tests\System.Net.Sockets.Tests.dll
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Net.Sockets.APM.Performance.Tests
  Discovered:  System.Net.Sockets.APM.Performance.Tests
  Info:        System.Net.Sockets.APM.Performance.Tests has no tests to run
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Net.Sockets.Tests
  Discovered:  System.Net.Sockets.Tests
  Starting:    System.Net.Sockets.Tests
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00111\lib\tests.targets(129,5): warning MSB3073: The command "CoreRun.exe xunit.console.netcore.exe System.Net.Sockets.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -1073741819. [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\tests\FunctionalTests\System.Net.Sockets.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_release_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00111\lib\tests.targets(136,5): error : One or more tests failed while running tests from 'System.Net.Sockets.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\tests\FunctionalTests\System.Net.Sockets.Tests.csproj]
  System.Net.Sockets.Async.Performance.Tests -> d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Net.Sockets.Async.Performance.Tests\System.Net.Sockets.Async.Performance.Tests.dll
  System.Reflection.Metadata.Tests -> d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\Windows_NT.AnyCPU.Release\System.Reflection.Metadata.Tests\System.Reflection.Metadata.Tests.dll
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
```

This issue seems to be a duplicate of #4037.
The investigation is currently (partially) _blocked_ by #4152.

Thanks @weshaggard for suggesting offline that this could be caused by an Assert. Given that the issue is most likely timing, I'll try to repro on a low-resource machine until we can get at least part of #4152 ready.

**Comment by CIPop** [comment] 2015-10-29 01:59
I was able to set up a 1 CPU (with a 50% VM limit) / 1GB VM continuously running 8 parallel processes of the System.Net.Sockets.Tests. I've installed WinDBG as debugger. So far the only error I see is a race condition within the test execution harness:

```
(240.5d0): CLR exception - code e0434352 (!!! second chance !!!)
CLR exception type: System.IO.IOException
    "The process cannot access the file 'C:\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Net.Sockets.Tests\dnxcore50\testResults.xml' because it is being used by another process."
```

This is most likely caused by the fact that I'm using the same repo. I'm running the tests with the following command:
```
cd C:\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Net.Sockets.Tests\dnxcore50
C:\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Net.Sockets.Tests\dnxcore50\CoreRun.exe xunit.console.netcore.exe   System.Net.Sockets.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing
```

The other issues that I've seen are occasional timeout exceptions which are expected under these conditions.

**Comment by CIPop** [comment] 2015-10-29 02:13
Updated the scripts to use a different test output file. This should work-around the previous issue.

**Comment by CIPop** [comment] 2015-10-29 17:55
Machine ran over-night and found no issues. I'll continue the investigation using 2 CPU cores but at this time I think the issue is most likely CI infrastructure.

**Comment by CIPop** [comment] 2015-10-30 03:10
I was able to repro after running with 2 CPUs!
@weshaggard : You were actually correct - this is a Debug.Assert. The stack shows that FailFast was triggered which crashed the process (on the CI no dump collection was made given #4152).

The assert is `SafeCloseSocket.Release after inner socket disposed.` Given the exception below (`NullReferenceException`) we know that `_innerSocket == null`.

```
0:011> !CLRStack
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.6.23419.0
SOS Version: 4.6.23428.1
OS Thread Id: 0xc84 (11)
        Child SP               IP Call Site
000000a4b3efc848 00007ffc04edc01f [GCFrame: 000000a4b3efc848] 
000000a4b3efc8d8 00007ffc04edc01f [HelperMethodFrame_1OBJ: 000000a4b3efc8d8] System.Environment.FailFast(System.String)
000000a4b3efc9e0 00007ffba5806c82 System.Net.Sockets.SafeCloseSocket.Release() [C:\corefx\src\Common\src\System\Net\SafeCloseSocket.cs @ 78]
000000a4b3efe8b0 00007ffc04f170b0 [FaultingExceptionFrame: 000000a4b3efe8b0] 
000000a4b3efedb0 00007ffba5806c20 System.Net.Sockets.SafeCloseSocket.Release() [C:\corefx\src\Common\src\System\Net\SafeCloseSocket.cs @ 73]
000000a4b3efee20 00007ffba5806292 System.Net.Sockets.SafeNativeOverlapped.FreeNativeOverlapped() [C:\corefx\src\Common\src\Interop\Windows\Winsock\SafeNativeOverlapped.cs @ 88]
000000a4b3efeeb0 00007ffba57f0d1e System.Net.Sockets.SafeNativeOverlapped.Dispose(Boolean) [C:\corefx\src\Common\src\Interop\Windows\Winsock\SafeNativeOverlapped.cs @ 49]
000000a4b3efef10 00007ffba57e27d7 System.Net.Sockets.SocketAsyncEventArgs.CompleteIOCPOperation() [C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs @ 168]
000000a4b3efef50 00007ffba57e275c System.Net.Sockets.SocketAsyncEventArgs.InnerComplete() [C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs @ 120]
000000a4b3efef80 00007ffba57e26ed System.Net.Sockets.SocketAsyncEventArgs.Complete() [C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs @ 335]
000000a4b3efefc0 00007ffba5802ff6 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags) [C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.cs @ 867]
000000a4b3eff1a0 00007ffba5800889 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*) [C:\corefx\src\System.Net.Sockets\src\System\Net\Sockets\SocketAsyncEventArgs.Windows.cs @ 1219]
000000a4b3eff2c0 00007ffbf6d5d006 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
000000a4b3eff430 00007ffc05211ec3 [GCFrame: 000000a4b3eff430] 
000000a4b3eff630 00007ffc05211ec3 [DebuggerU2MCatchHandlerFrame: 000000a4b3eff630]

0:011> !pe
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.6.23419.0
SOS Version: 4.6.23428.1
Exception object: 000001b6ca6211e0
Exception type:   System.ExecutionEngineException
Message:          <none>
InnerException:   System.NullReferenceException, Use !PrintException 000001b6ca6f36a0 to see more.
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131506
0:011> !PrintException /d 000001b6ca6f36a0
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.6.23419.0
SOS Version: 4.6.23428.1
Exception object: 000001b6ca6f36a0
Exception type:   System.NullReferenceException
Message:          Object reference not set to an instance of an object.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    000000A4B3EFEDB0 00007FFBA5806C20 system_net_sockets!System.Net.Sockets.SafeCloseSocket.Release()+0x60

StackTraceString: <none>
HResult: 80004003
```

**Comment by CIPop** [comment] 2015-10-30 03:12
@joshfree Per our last team's SCRUM, we're going to attempt to get production code fixes ready for RC1. If that is not going to get approved please let us know by switching the milestone back to RC2.

**Comment by CIPop** [comment] 2015-11-02 22:04
Moving this back to RC2 since it's a `DEBUG` code issue and shouldn't happen in `RET` builds.

**Closed** 2015-11-03 00:08 UTC
Labels: bug, System.Net
