### ISSUE TITLE
Add Single.TryFormat span-based method

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#25374] opened 2017-11-20 16:01 UTC
Separated out of https://github.com/dotnet/corefx/issues/22403 and https://github.com/dotnet/corefx/issues/22616

Add:
```C#
public bool TryFormat(Span<char> destination, out int charsWritten, string format = null, IFormatProvider provider = null);
```
and use it in `StringBuilder.Append(float)`.

**Comment by jkotas** [comment] 2017-11-20 16:08
We should track single and double together. It is same piece of code.
Duplicate of https://github.com/dotnet/corefx/issues/25373

**Closed by jkotas** 2017-11-20 16:08 UTC
Labels: api-approved

**Comment by stephentoub** [comment] 2017-11-20 16:11
Ok. Thanks.
