### ISSUE TITLE
CLA Labels

### ISSUE THREAD

**Issue by sgtfrankieboy** [dotnet/corefx#423] opened 2015-01-14 12:14 UTC
I've been following the project for a while now and noticed that recently there is a bot in place that adds `cla-required`, `cla-signed` and `cla-not-required`. I personally think that these labels clutter up a lot. Wouldn't it be easier to only add `cla-required` when they haven't signed it yet and remove it when signed? Leaving out the other two labels.

Also, when signing up for the CLA you require to enter the company you work for, not everyone has work and some are still studying.

**Comment by joshfree** [comment] 2015-01-14 23:50
:+1: 

@dmahugh @BethMassi -- Can we make the dot net foundation bot not be so loud?  Specifically I'd like it to not post anything when the issue is a no-op for contributors.  Over time most people submitting PRs will have already signed the CLA; so these bot-posts are going to be mostly noise that people have to ignore.  What do you think?

Also as @sgtfrankieboy wrote above, can we also reduce the amount of labels applied?

**Comment by stephentoub** [comment] 2015-01-14 23:55
:+1: 

I agree; these bots are causing way too much noise, both in unnecessary comments and unnecessary labeling.

**Comment by justinvp** [comment] 2015-01-15 00:35
:+1:

**Comment by nguerrera** [comment] 2015-01-15 01:12
:+1:

**Comment by terrajobst** [comment] 2015-01-16 03:21
I fully agree. I'll raise this the owners of the bot. (What does it mean to 'own' a bot? Is it the same as 'parenting' or more like 'maintaining'? Or is morally wrong to own a bot? :thought_balloon:)

**Comment by citizenmatt** [comment] 2015-01-16 09:16
I like the way [CLAHub](https://www.clahub.com) do it, using GitHub's [status API](https://github.com/blog/1227-commit-status-api) to show that the PR can't be merged due to the contributor not having signed the CLA. You can see it in the pictures on their site.

**Comment by terrajobst** [comment] 2015-01-16 14:37
@citizenmatt yep, that's in the backlog of the team that owns the CLA process for the .NET Foundation.

**Comment by joshfree** [comment] 2015-10-13 13:55
I'm closing out this old issue as the cla-bot noise level was reduced several months ago (though the number of unique labels it uses remains high).

**Closed by joshfree** 2015-10-13 13:55 UTC
Labels: Meta
