### ISSUE TITLE
HttpClient DiagnosticSource reporting does not notify about exceptions

### ISSUE THREAD

**Issue by lmolkova** [dotnet/corefx#14331] opened 2016-12-08 21:16 UTC
See `[System.Net.Http.HttpHandlerToFilter](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/netcore50/System/Net/HttpHandlerToFilter.cs)`
```
        protected internal override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancel)
        {
           ....
           Guid loggingRequestId = s_diagnosticListener.LogHttpRequest(request);

            RTHttpRequestMessage rtRequest = await ConvertRequestAsync(request).ConfigureAwait(false);
            RTHttpResponseMessage rtResponse = await _next.SendRequestAsync(rtRequest).AsTask(cancel).ConfigureAwait(false);

           ...
            s_diagnosticListener.LogHttpResponse(response, loggingRequestId);
            return response;
        }
```

If exception is thrown while sending the request (DNS issues, timeout), nothing will be sent to diagnostic source.

**Comment by davidsh** [comment] 2016-12-08 21:22
This is really a dupe of https://github.com/dotnet/corefx/issues/13172

**Closed** 2016-12-08 21:50 UTC
Labels: area-System.Net, enhancement
