### ISSUE TITLE
Doc comment on ValueTuple.Item1 displays incorrectly

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#35009] opened 2019-02-01 00:11 UTC
![image](https://user-images.githubusercontent.com/12466233/52094135-cef25c00-2572-11e9-99e0-74f090e6b310.png)

Same problem in `Tuple`:
![image](https://user-images.githubusercontent.com/12466233/52102303-a67b5980-2594-11e9-8ff2-05df1c7b73d2.png)

**Comment by danmosemsft** [comment] 2019-02-02 01:45
@dendeli-msft I've seen other reports of this -- is it a known issue, and if so where? Seems the XML doc comment is simply using a regular apostrophe.

**Comment by karelz** [comment] 2019-02-22 01:50
@dendeli-msft @mairaw any thoughts?

**Comment by sharwell** [comment] 2019-02-22 02:26
I've been trying to reproduce this, but I need to know the *exact* reference for `ValueTuple<T1, T2>` used in the example. My suspicion is the associated XML documentation file contains `instance&amp;#39;s` instead of `instance&#39;s`.

**Comment by danmosemsft** [comment] 2019-02-22 03:41
These don't come from the code itself. I guess from
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ValueTuple%601.xml#L359 ?

**Comment by mairaw** [comment] 2019-04-09 18:29
This might have been fixed with the issues I logged for the .NET Framework IntelliSense release since I don't see this issue on our :
![image](https://user-images.githubusercontent.com/12971179/55825129-37514280-5aba-11e9-869e-3fde29ef54e7.png)

So we need to make sure the IntelliSense files get updated for .NET Core to reflect that.

/cc @safern

**Comment by safern** [comment] 2019-04-09 22:45
This is fixed in the latest .NET Core version. I just validated with `Microsoft.NETCore.App (3.0.0-preview4-27609-07)`

![image](https://user-images.githubusercontent.com/22899328/55839917-742f3080-5ade-11e9-8e33-f6b6e74b4da8.png)

Should be fixed in the latest SDK.

**Closed by safern** 2019-04-09 22:45 UTC
Labels: area-Infrastructure, documentation
