### ISSUE TITLE
ResourceManager not reading from textual file

### ISSUE THREAD

**Issue by atuzovic** [dotnet/corefx#10366] opened 2016-07-27 13:08 UTC
## Steps to reproduce

1. Create new .NET Console Application
2. Create new Resources File for .NET Core. (i.e. EmailTemplates.resx)
3. Go to Add Resource => Add New Text File and create textual file (i.e. Registration.txt)
4. Add some sample text to file (i.e. "Hello World")
5. Type Console.WriteLine(EmailTemplates.Registration) in Program.cs
6. Run

## Expected  behavior

Should be: "Hello world" on console window.

## Actual behavior

Console window is showing: 
`Registration.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;Windows-1252`

## Environment data

.NET Command Line Tools (1.0.0-preview3-003215)

Product Information:
 Version:            1.0.0-preview3-003215
 Commit SHA-1 hash:  eaa771edca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by tuespetre** [comment] 2016-07-27 14:44
@atuzovic I had been relying on this functionality as well. The problem is that the 'read text file as string' functionality is supplied by [the `ResXResourceReader` class](https://msdn.microsoft.com/en-us/library/system.resources.resxresourcereader(v=vs.110).aspx), which exists in the `System.Windows.Forms.dll` assembly. Seems like a bad design/placement choice made a while back.

**Comment by stephentoub** [comment] 2016-07-27 15:00
cc: @danmosemsft, @tarekgh, @KrzysztofCwalina

**Comment by tarekgh** [comment] 2016-08-16 00:02
This looks similar to the issue 

https://github.com/dotnet/corefx/issues/8200#event-699283914

**Comment by barrytang** [comment] 2016-08-16 01:29
dupe of https://github.com/dotnet/cli/issues/3695.

**Closed by barrytang** 2016-08-16 01:29 UTC
Labels: System.Resources
