### ISSUE TITLE
Inconsistent System.IO.IOExceptions for requests where the URI is too long in .net core 2.1.1

### ISSUE THREAD

**Issue by mckenzielee** [dotnet/corefx#30951] opened 2018-07-10 17:24 UTC
With the upgrade from .net core 2.0 to .net core 2.1.1, we are receiving different responses to /get requests where the URI is too long. The first response is consistently 414 - URI Too Long. Most of the subsequent responses to the same request are the following exception:

System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
-------- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.WriteByteSlowAsync(Byte b)
   at System.Net.Http.HttpConnection.WriteStringAsyncSlow(String s)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
----- Inner Stack Trace -----

We are using a Kestrel web server to host our .net core 2.1.1 application. It may be similar to this issue: #23504

 Let me know what else you need.

**Comment by mckenzielee** [comment] 2018-07-11 15:54
I do not have a small repro to share. I can get you one within a week.

**Comment by karelz** [comment] 2018-07-11 23:03
@mckenzielee ok, we will wait for it.

**Comment by mckenzielee** [comment] 2018-07-17 23:24
Here it is: https://github.com/mckenzielee/HttpClient-URITooLong-Exception

**Comment by davidsh** [comment] 2018-07-18 01:49
>That doesn't explain the issue with subsequent requests, you should always get the same response. Is HttpClient trying to re-use a connection that's being closed?

Probably.  And that looks like a bug with HttpClient, specifically SocketsHttpHandler.  Kestrel is also sending "Connection: close" as well (which is good).  So, SocketsHttpHandler should be able to remove that connection from its pool and use a new connection.

We'll investigate the bug on the HttpClient side.

cc: @geoffkizer @stephentoub

**Comment by mckenzielee** [comment] 2018-07-18 02:05
To clarify, we are expecting a 414 response to this request. In .NET core 2.0 and ASP.NET core 2.0.1, we were consistently getting the 414 response to requests of this size.

**Comment by geoffkizer** [comment] 2018-07-18 04:35
We should be detecting that the connection is closed and not reusing it. Not sure why that isn't happening here.

**Comment by karelz** [comment] 2018-07-18 09:32
We may consider it for servicing ...

**Comment by mckenzielee** [comment] 2018-07-31 19:35
Any update on this?

**Comment by mckenzielee** [comment] 2018-08-28 21:52
Yes, that workaround is straightforward. The main concern is this situation of the HttpClient re-using closed connections is not only isolated to the long URIs. Can you confirm that this is case?

**Comment by karelz** [comment] 2018-08-29 00:58
> The main concern is this situation of the HttpClient re-using closed connections is not only isolated to the long URIs. Can you confirm that this is an isolated case?

I am not aware of any other similar bugs. This is the only report we got in the area of reusing closed connections, so it is safe to assume it is isolated case. Although there may be more scenarios that can hit the underlying problem (we won't know for sure until we fully understand the fix).
Does it help?

**Comment by mckenzielee** [comment] 2018-09-04 18:19
Yep, thank you.

**Comment by wfurt** [comment] 2018-09-12 22:45
I did look at this issue and I don't see any remaining problems beyond what was discussed. 
I used link to repro provided and here is what I see:

- client will start sending request. 
- server sends 414 before sending is done. 
- client keeps sending request
- server sends RST as it probably give up on reading. 

on next rounds, client uses NEW connection and scenario repeats. 

<img width="1303" alt="capture" src="https://user-images.githubusercontent.com/14356188/45457156-9248c580-b6a2-11e8-9e96-3bcc4d35e157.png">

I also modify the repro so it sends one large URL and than sequence of "normal" requests.

```
Request URI Length: 30009
REQUEST 1 - Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.WriteByteSlowAsync(Byte b)
   at System.Net.Http.HttpConnection.WriteStringAsyncSlow(String s)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ClientExceptionReproApp.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in /home/furt/github/HttpClient-URITooLong-Exception/ClientExceptionReproApp/Program.cs:line 39
REQUEST 2 - Response: 404 Not Found
REQUEST 3 - Response: 404 Not Found
REQUEST 4 - Response: 404 Not Found
REQUEST 5 - Response: 404 Not Found
REQUEST 6 - Response: 404 Not Found
REQUEST 7 - Response: 404 Not Found
REQUEST 8 - Response: 404 Not Found
REQUEST 9 - Response: 404 Not Found
REQUEST 10 - Response: 404 Not Found
```

first request fails as expected but rest succeeds without any IO errors. 

unless somebody objects, I think we should close this.

**Comment by davidsh** [comment] 2018-09-12 23:34
It's possible this doesn't repro now because of the fix to #30327 as a side-affect.

**Comment by karelz** [comment] 2018-09-13 00:08
@wfurt can you please double-check the test case on 2.1.1 public release vs. 2.1.5 (current 2.1.x branch)?
If it is fixed as side-effect, we can close it as dupe.

**Comment by wfurt** [comment] 2018-09-13 03:59
I get same results with 2.1.302 (running on Ubuntu16) 
Since server resets the connection while sending request, there is really no response processing.

**Comment by wfurt** [comment] 2018-09-13 18:59
I also went to 2.1.1 as that it is version where it was originally reported. 
I could not reproduce inconsistent behavior described above regardless of .Net version I used. 

However in process of changing version I made discovery that after server part is restarted, the very first request returns 417 and than it consistently fails with IO exception as server sends RST. 
When I look at packet capture, in the very first request, sever sends 414 response after receiving complete request.  

So observed behavior is expected. I think we should close this, unless somebody disagrees. 

<img width="1556" alt="capture2" src="https://user-images.githubusercontent.com/14356188/45509440-726ddc00-b74c-11e8-828c-673ae996f6e1.png">

**Comment by karelz** [comment] 2018-09-13 20:51
To sum it up: If the server sends respond before we finish sending the request and closes the connection (via RST) before we finish sending the request, it is by design that we may throw the exception above -- `System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine` as it captures the reality. It's by design timing which could happen with any HTTP server and any HTTP client.

Closing as resolved. Let us know if you have further questions.

**Closed by karelz** 2018-09-13 20:51 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, bug, tenet-compatibility
