### ISSUE TITLE
Getting MSB3027 (access denied) in MSDEV during compilation after dotnet.exe crash

### ISSUE THREAD

**Issue by viking84** [dotnet/corefx#25313] opened 2017-11-17 10:15 UTC
Hey there,

I'm devolping a dotnet core console application with Visual Studio Pro 2017 (15.4.0).

Sometimes I'm starting my console app from the Powershell, sometimes directly hitting F5 from the Visual Studio. It occurs from time to time, that when I start the Project from Powershell, that dotnet.exe crashes in case of an unhandled application exception. 

From that Point on, I can't compile my Project anymore getting:
  Error	MSB3027	Could not copy "obj\Debug\netcoreapp2.0\projectname.dll" to "bin\Debug\netcoreapp2.0\projectname.dll". 
Exceeded retry count of 10. Failed.	

In the taskmanager, there is no dotnet process open, closing all MSDEV instances doesn't help. At the Moment I'm forced to do a reboot.

Any guesses?

**Comment by karelz** [comment] 2017-11-17 19:15
It almost looks like OS keeps some handles opened, forcing you to restart. It typically doesn't happen for normal apps, so I guess PowerShell is using something special tricks which can result in that situation.
I would suggest to ask PowerShell if they have a clue. I don't think it is anything specific to .NET or VS as it doesn't happen until PowerShell comes into the game.

**Comment by viking84** [comment] 2017-11-17 19:39
Hi Karel,
It is not a powershell Problem. I also tried it with cmd.exe.
Same behavior. Also tested with different Projects and different exceptions.
Greetings

**Comment by karelz** [comment] 2017-11-17 19:49
OK, that was not clear.
Are you able to reproduce it with small app? (HelloWorld)
Are you able to reproduce it on more than 1 machine?

**Comment by danmosemsft** [comment] 2017-11-17 22:10
Can you find which process is holding the handle to this file?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by tarekgh** [comment] 2017-11-17 22:20
would be either to just reboot the machine and try again.

**Comment by tarekgh** [comment] 2017-11-17 22:27
@viking84 you have mentioned MSDEV, did you mean devenv.exe? or you mean something else? please update us if you reboot and still seeing the issue.

**Comment by danmosemsft** [comment] 2017-11-18 02:21
msdev.exe is what VS used to be called until 2002. 😃

**Comment by tarekgh** [comment] 2017-11-20 17:15
@danmosemsft I know that. I am trying to understand how old VS conflicting with the dotnet compilation at all. I don't think can compile net core app with old VS at all as the templates are not there.

**Comment by danmosemsft** [comment] 2017-11-20 17:49
I meant it's what old timers like me sometimes call VS ...

**Comment by tarekgh** [comment] 2017-11-21 17:38
@viking84 I am closing the issue. If you still experience the problem, please respond back with more info and we'll be happy to help and re-activate the issue. Thanks.

**Closed by tarekgh** 2017-11-21 17:38 UTC
Labels: area-Meta, question
