### ISSUE TITLE
Add TimeSpan.Infinite

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#40693] opened 2019-08-29 23:42 UTC
We already have [`System.Threading.Timeout.InfiniteTimeSpan`](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Threading/Timeout.cs#L12), which uses `-1` for milliseconds.

@KrzysztofCwalina proposed to add an alias under `TimeSpan` which would be more discoverable:

> I think it would be useful. The `Timeout` type is in `Threading` namespace and we don’t want to use it as timing out has nothing to do with threading.

### Proposed API

```C#
namespace System
{
    public partial struct TimeSpan
    {
        public static readonly TimeSpan Infinite = System.Threading.Timeout.InfiniteTimeSpan;
    }
}
```

**Comment by omariom** [comment] 2019-08-29 23:57
`Infinite` has such meaning in the context of timeouts so the property should be called `InfiniteTimeout`.
But then why have domain specific properties in a generic type?

**Comment by KrzysztofCwalina** [comment] 2019-08-30 00:38
I agree we cannot keep using -1 in this case. I was thinking we could use TimeSpan.FromSeconds(double.NaN), but I just looked in the code (TimeSpan.Interval method) and even this might not be possible. Although NaN is currently "reserved" (the Interval method throws), we would still need to find a way to represent it as a long, and it's possible that all its range is already used (e.g. through FromTicks factory method).

**Comment by stephentoub** [comment] 2019-08-30 00:55
> I agree we cannot keep using -1 in this case

I don't see how such a new property could have a value different from Timeout.InfiniteTimeSpan. It's not just about a new property and new methods, but every existing method that takes a TimeSpan and special-cases this one value.

**Comment by terrajobst** [comment] 2019-08-30 01:12
I agree. Creating an alias under `TimeSpan` feels OK, but using a different value would break too much code. `Timeout.InfiniteTimeSpan` and `TimeSpan.Infinite` must have the same values.

**Comment by svick** [comment] 2019-08-30 10:07
I think that it would be very confusing if `TimeSpan.Infinite.TotalMilliseconds` returned -1. `Timeout.InfiniteTimeSpan` can get away with that, because it does not look like a first-class support for infinity in `TimeSpan`. But `TimeSpan.Infinite` does, and I think that would make it problematic.

As long as `TimeSpan` does not properly support infinity, it should not pretend that it does.

Or, put another ways, if `TimeSpan.Infinite` being -1 ms is acceptable, would it also be acceptable to have `int.Infinite`, which is -1?

**Comment by stephentoub** [comment] 2019-08-30 14:28
> But TimeSpan.Infinite does, and I think that would make it problematic.

I agree. It has to be -1, and it can't be -1. Seems it shouldn't exist.

**Comment by KrzysztofCwalina** [comment] 2019-08-30 16:44
We are all in agreement that we cannot use -1.
Using a different value has some negatives, but I don't think would be objectively bad. It's a trade off. 

BTW, TimeSpan.FromTicks(long.MaxValue); is 30K years. Pretty close to infinite timeout as far as computer programs are concerned.

**Comment by stephentoub** [comment] 2019-08-30 16:48
> I don't think would be objectively bad

I think it would be very bad.  Every API that currently special-cases Timeout.InfiniteTimeSpan would be wrong.  That "wrong" may not manifest as correctness; it could easily manifest as a performance issue.  For example, if HttpClient.Timeout is Timeout.InfiniteTimeSpan, then the implementation avoids creating a bunch of things, including a Timer, for each request; using this mythical TimeSpan.Infinite instead of Timeout.InfiniteTimeSpan would make everything more expensive.

**Comment by KrzysztofCwalina** [comment] 2019-08-30 16:59
It's not only that it leaves in System.Threading. The problem is that nobody knows about the Timeout class. When a users sees TimeSpan parameter, they might try to see if there is a singleton property in TimeSpan (just like there are singleton properties on all our primitive types), but it will never cross their mind to go look into some other type in a different namespace.

As to the performance issue, I agree that it's a problem, but I think it would be reasonable to not waste time creating timers when the calling code passes 30K years timespan.

**Comment by stephentoub** [comment] 2019-08-30 17:06
> When a users sees TimeSpan parameter, they might try to see if there is a singleton property in TimeSpan (just like there are singleton properties on all our primitive types), but it will never cross their mind to go look into some other type in a different namespace.

So let's update the documentation for TimeSpan to highlight Timeout.InfiniteTimeSpan.  Let's augment IntelliCode to suggest Timeout.InfiniteTimeSpan when IntelliSense pops up to offer options for TimeSpan arguments.  Let's have an analyzer that flags use of -1 for timeout arguments and suggest using a TimeSpan overload with Timeout.InfiniteTimeSpan instead.  Etc.  There are other ways to address such concerns than adding a new such property which I continue to maintain is the wrong thing to do.

**Comment by KrzysztofCwalina** [comment] 2019-08-30 17:19
> What cut-off is reasonable? 

Just this one sentinel value.

As to doc updates: they are better than nothing, but a property on TimeSpan would be better. 

Anyway, you guys decide if it's worth more discussion or not. If you don't think it's worth it, let's close the issue.

**Comment by terrajobst** [comment] 2019-08-30 17:48
What if we were to follow @omariom's suggestion

> `Infinite` has such meaning in the context of timeouts so the property should be called `InfiniteTimeout`.

and did that:

```C#
namespace System
{
    public partial struct TimeSpan
    {
        /// <summary>
        /// Represents an infinite timeout. Note that this is different from a generalized
        /// concept of infinity in that <c>InfiniteTimeout</c> is just <c>-1</c> milliseconds.
        /// </summary>
        public static readonly TimeSpan InfiniteTimeout = System.Threading.Timeout.InfiniteTimeSpan;
    }
}
```

**Comment by akoeplinger** [comment] 2019-09-01 16:22
I agree that -1 as the value for Infinite would be counterintuitive but having a timeout-specific property on the generic TimeSpan type feels wrong to me too.

Doesn't sound worth it tbh.

**Comment by terrajobst** [comment] 2019-09-03 20:28
@KrzysztofCwalina @stephentoub what are your thoughts on my proposal above? If we can't get consensus, we should close.

**Comment by KrzysztofCwalina** [comment] 2019-09-03 20:45
I assume you are asking about the InfiniteTimeout property on TimeSpan. I agree that it's not ideal, but it seems to be the next best thing and weighing pros and cons, I think we should do it.

**Comment by scalablecory** [comment] 2019-09-03 21:07
Is this a layering issue?

An infinite `TimeSpan` isn't a thing. It is a special sentinel value for timeouts, not a general property of `TimeSpan`. It doesn't belong there.

I prefer @stephentoub's idea to update docs & Intellisense.

**Comment by terrajobst** [comment] 2019-09-04 01:01
@scalablecory 

> An infinite `TimeSpan` isn't a thing.

Hence the suggestion to expose it as `TimeSpan.Infinite**Timeout**`.

> Is this a layering issue?

No, it's discoverability issue. Here is the scenario:

1. You use the Azure SDK
2. You use a type called `StorageClient` from the namespace `Microsoft.Azure.Storage`.
3. Its `ConnectAsync()` method takes an argument `TimeSpan timeout`.

How does a user know that 'infinite' is provided by `System.Threading.Timeout.InfiniteSpan`? `System.Threading` isn't imported by default and not required to use the SDK. The most logical choice for a developer is trying to:

1. Access statics on `TimeSpan`
2. Constructing a `TimeSpan`

@stephentoub, are you opposed to expose this?

> ```cs
> namespace System
> {
>     public partial struct TimeSpan
>     {
>         /// <summary>
>         /// Represents an infinite timeout. Note that this is different from a generalized
>         /// concept of infinity in that <c>InfiniteTimeout</c> is just <c>-1</c> milliseconds.
>         /// </summary>
>         public static readonly TimeSpan InfiniteTimeout = System.Threading.Timeout.InfiniteTimeSpan;
>     }
> }
> ```

**Comment by stephentoub** [comment] 2019-09-04 01:43
I don't love it or think it's necessary, but to quote from myself above:

> If I'm outvoted and we decide to add such a property, I maintain it must be the equivalent of InfiniteTimeSpan, and have a name that makes it clear it's a synonym, e.g. InfiniteTimeout, with the docs and IntelliSense being super clear about the association.

**Comment by GSPP** [comment] 2019-09-05 08:43
There is no such things as an infinite `TimeSpan`. `TimeSpan` does not support that notional at all.

The fact, that `-1` means "infinite" in *some* APIs is a concept specific to those APIs. Putting that concept on `TimeSpan` itself is a layering violation.

**Comment by terrajobst** [comment] 2019-09-05 17:40
It's a common enough sentinel value that it doesn't feel outrageous to put this on `TimeSpan`, but I agree that it *feels* a bit over the top. Not a clear cut line.

**Comment by GrabYourPitchforks** [comment] 2020-01-14 18:25
API review - this sentinel value would only be special-cased by specific APIs, and in some contexts -1 is a perfectly valid value for `TimeSpan` parameters. This really should be a doc issue demonstrating correct use of the existing `Timeout` API rather than a public API being added to `TimeSpan`.

**Closed** 2020-01-14 18:25 UTC
Labels: area-System.Runtime
