### ISSUE TITLE
On OSX, launching a non existent process looks for Windows specific DllImport

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4282] opened 2015-11-02 11:29 UTC
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-errorhandling-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.SetErrorMode(UInt32 newMode)
   at System.IO.Win32FileSystem.FillAttributeInfo(String path, WIN32_FILE_ATTRIBUTE_DATA& data, Boolean tryagain, Boolean returnErrorOnNotFound)
   at System.IO.Win32FileSystem.FileExists(String fullPath)
   at System.IO.File.Exists(String path)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Program.Main()
```

/cc @stephentoub

**Comment by stephentoub** [comment] 2015-11-02 14:11
@davidfowl, thanks. From the stack, it looks like you're using a System.IO.FileSystem.dll for Windows....  Win32FileSystem doesn't exist in the System.IO.FileSystem.dll on Unix.  Maybe there's a packaging problem?

**Comment by joshfree** [comment] 2015-11-02 15:41
@chcosta @ericstj PTAL

**Comment by ericstj** [comment] 2015-11-02 17:23
What version of the packages is this?  If I trace the 23430 version of the package I see a `ref/dotnet5.4` in system.io.filesystem package, no lib, runtime.json includes runtime.osx.10.10.System.IO.FileSystem, which contains `runtimes/osx.10.10/lib/dotnet5.4`.  The behavior you are observing is what I'd expect if you were using the pre-x-plat packages.

I noticed some unusual packaging in DNX where it was picking up older versions of the packages for its bin folder.  I expect that to be fixed by the lineup change that went in over the weekend.  If you see that DNX is getting old bits you probably want to wait to get that change in today's build.

**Comment by joshfree** [comment] 2015-11-02 17:35
today's rc1 build is 23502.00 and is on http://myget.org/gallery/dotnet-core-rel.

**Comment by ericstj** [comment] 2015-11-02 19:04
For DNX to see this they'll actually need to package a new version of DNX since this binary is included in their bin folder.

**Comment by davidfowl** [comment] 2015-11-03 08:21
@ericstj This isn't using DNX it's using corerun. I think the package is busted. I can launch a process fine but when it fails, it fails this way.

**Comment by chcosta** [comment] 2015-11-03 17:39
@davidfowl, do you have more specific repro instructions?  I'm working on setting up a repro machine now.

**Comment by chcosta** [comment] 2015-11-04 00:03
@davidfowl , do you have a binary I can use to pass to corerun and repro this?  Do you have more information I can use to try to repro this?

So far I've been unsuccessful at repro'ing this, and I don't see any issue with the packages which would lead to importing a Windows implementation assembly on OSX.  The assemblies appear to be built / packaged correctly.  I'm not certain how corerun would get a Windows implementation assembly.

**Comment by ericstj** [comment] 2015-11-04 00:49
The package isn't busted.  The problem is you are getting an old version of FileSystem that didn't have the x-plat factoring.  Process is latest so that works, but FileSystem is old so it only has a windows implementation.  We just made a change to centrailize the lineup information that should help this.  What happens when you reference the latest Microsoft.NETCore.Platforms in your project?

**Comment by davidfowl** [comment] 2015-11-04 12:34
I added this:

```JSON
{
   "dependencies": {
   "Microsoft.NETCore.Platforms": "1.0.1-beta-23502",
}   
}
```

And I'll still seeing the same thing

**Comment by davidfowl** [comment] 2015-11-04 12:34
Too old?

**Comment by davidfowl** [comment] 2015-11-04 12:36
Put in a * and got this:

```
Restore failed
A circular reference to 'System.Private.DataContractSerialization' was detected
```

**Comment by ericstj** [comment] 2015-11-04 14:31
Not seeing that in DNX.  Do you have a log of the restore and the source project.json?

**Comment by ericstj** [comment] 2015-11-04 15:30
Now seeing this on the official build.  I'll have a look.

**Comment by ericstj** [comment] 2015-11-04 16:04
Ok, build should be fixed.  Can you delete the local copy of System.Private.DCS and try again?

**Closed** 2015-11-06 19:04 UTC
Labels: Mac OSX, packaging, System.Diagnostics.Process, System.IO

**Comment by davidfowl** [comment] 2015-11-06 19:29
Works now
