### ISSUE TITLE
ImmutableHashSet<>.HashBucket needs to implement an Equals()/GetHashCode()/IEquatable<HashBucket> for perf reasons

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#19044] opened 2017-04-27 14:45 UTC
ActiveIssued two tests on System.Collections.Immutable.Tests:

```
System.Collections.Immutable.Tests.ImmutableHashSetTest.EnumeratorWithHashCollisionsTest
System.Collections.Immutable.Tests.ImmutableHashSetTest.RemoveValuesFromCollidedHashCode 

```
Before the panic sets in any further, the fix is simple:

<a href="https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.HashBucket.cs#L33">ImmutableHashSet&lt;&gt;.HashBucket<a> needs to implement an Equals()/GetHashCode() pair. I strongly recommend that it also implement IEquatable&lt;HashBucket&gt; to remove the boxing penalty.

Right now, comparison of HashBuckets falls back to the last-resort Equals() method implemented by System.ValueType.

Which uses _Reflection_ to compare the fields of the HashBucket.

So even on non-AoT platforms, you're taking a horrendous perf hit.

On AoT platforms, the private fields get hidden from Reflection, thus causing Equals() to return true unconditionally. This is causing two tests to fail on AoT, and it's amazing that it's only two.

   ImmutableHashSetTest.EnumeratorWithHashCollisionsTest
   ImmutableHashSetTest.RemoveValuesFromCollidedHashCode

@morganbr: I'll open a separate TFS item for the toolchain. There's a discoverable call to EqualityComparer&lt;HashBucket&gt;.Default in the code so if that doesn't kick the toolchain into emitting the auto-Equals method for HashBucket, it probably should.

Regardless, this issue should also be fixed in System.Collections.Immutable because of the perf hit alone.

**Comment by AtsushiKan** [comment] 2017-04-27 14:55
cc @ianhays

**Comment by danmosemsft** [comment] 2017-04-27 17:35
@AtsushiKan aot/UWP stuff goes in 2.1. It doesn't seem cirtical enough for 2.0 but feel free to correct me.

**Comment by morganbr** [comment] 2017-04-27 20:51
@AtsushiKan , the toolchain is indeed supposed to have noticed that HashBucket is reflection blocked and generated a non-reflection Equals/GetHashCode. Thanks for filing the TFS bug on that.

**Comment by stephentoub** [comment] 2017-04-28 03:16
cc: @AArnott

**Comment by AArnott** [comment] 2017-04-28 04:09
Which branch should a fix for this (the ImmutableHashSet one) be targeted to?

**Comment by AArnott** [comment] 2017-04-28 04:22
Hmmm... I guess it's been too long since I've built this code. I can't figure out how to get it to build in VS2017 so I can run tests, and fix this issue. This is what I'm seeing in VS. I see a similar error from MSBuild.exe at the command line, and dotnet build also fails but with a different error.

```
1>------ Build started: Project: System.Collections.Immutable, Configuration: netcoreapp-Debug Any CPU ------
1>  fatal: invalid --pretty format: cd
1>c:\git\corefx\Tools\versioning.targets(323,5): error MSB4062: The "GenerateCurrentVersion" task could not be loaded from the assembly c:\git\corefx\Tools/Microsoft.DotNet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
2>------ Build started: Project: System.Collections.Immutable.Tests, Configuration: netcoreapp-Debug Any CPU ------
2>  fatal: invalid --pretty format: cd
2>c:\git\corefx\Tools\versioning.targets(323,5): error MSB4062: The "GenerateCurrentVersion" task could not be loaded from the assembly c:\git\corefx\Tools/Microsoft.DotNet.Build.Tasks.dll. Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

That said, In looking over the code I'm very curious what the callstack would be on these calls to `HashBucket.Equals(object)`. So far I haven't found the code that would have done that.

**Comment by stephentoub** [comment] 2017-04-28 15:30
> Which branch should a fix for this (the ImmutableHashSet one) be targeted to?

master is fine

> I guess it's been too long since I've built this code.

Try sync'ing to the latest, doing a git clean, and then doing build.cmd from the root of the repo.  Then you should be able to build and test the individual project.

> That said, In looking over the code I'm very curious what the callstack would be on these calls to HashBucket.Equals(object). So far I haven't found the code that would have done that.

```
        Stack Trace:
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.HashBucket.cs(62,0): at System.Collections.Immutable.ImmutableHashSet`1.HashBucket.Equals(Object obj)
              at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\SortedInt32KeyNode.cs(431,0): at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEquali
  tyComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\SortedInt32KeyNode.cs(185,0): at System.Collections.Immutable.SortedInt32KeyNode`1.SetItem(Int32 key, TValue value, IEqualit
  yComparer`1 valueComparer, Boolean& replacedExistingValue, Boolean& mutated)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(791,0): at System.Collections.Immutable.ImmutableHashSet`1.UpdateRoot(SortedInt32KeyNode`1 root, Int32
   hashCode, HashBucket newBucket)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(658,0): at System.Collections.Immutable.ImmutableHashSet`1.Add(T item, MutationInput origin)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(195,0): at System.Collections.Immutable.ImmutableHashSet`1.Add(T item)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(383,0): at System.Collections.Immutable.ImmutableHashSet`1.System.Collections.Immutable.IImmutableSet<
  T>.Add(T item)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\tests\ImmutableSetTest.cs(473,0): at System.Collections.Immutable.Tests.ImmutableSetTest.EnumeratorTestHelper[T](IImmutableSet`1 emptySet, IComparer`1 compar
  er, T[] values)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\tests\ImmutableHashSetTest.cs(70,0): at System.Collections.Immutable.Tests.ImmutableHashSetTest.EnumeratorWithHashCollisionsTest()
     System.Collections.Immutable.Tests.ImmutableHashSetTest.RemoveValuesFromCollidedHashCode [FAIL]
        System.Exception : Exception of type 'System.Exception' was thrown.
        Stack Trace:
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.HashBucket.cs(62,0): at System.Collections.Immutable.ImmutableHashSet`1.HashBucket.Equals(Object obj)
              at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\SortedInt32KeyNode.cs(431,0): at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEquali
  tyComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\SortedInt32KeyNode.cs(185,0): at System.Collections.Immutable.SortedInt32KeyNode`1.SetItem(Int32 key, TValue value, IEqualit
  yComparer`1 valueComparer, Boolean& replacedExistingValue, Boolean& mutated)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(791,0): at System.Collections.Immutable.ImmutableHashSet`1.UpdateRoot(SortedInt32KeyNode`1 root, Int32
   hashCode, HashBucket newBucket)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(720,0): at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput or
  igin)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(1039,0): at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWi
  thComparer)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet_1.cs(248,0): at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableHashSet.cs(112,0): at System.Collections.Immutable.ImmutableHashSet.Create[T](IEqualityComparer`1 equalityComparer,
   T[] items)
           C:\Users\stoub\Source\Repos\corefx\src\System.Collections.Immutable\tests\ImmutableHashSetTest.cs(146,0): at System.Collections.Immutable.Tests.ImmutableHashSetTest.RemoveValuesFromCollidedHashCode()
```

**Comment by AArnott** [comment] 2017-04-29 15:17
Thanks, @stephentoub. The build is now working. But tests still aren't showing up in Test Explorer. Should I be expecting them to? Otherwise what is the recommended way to step through tests? Add a Debugger.Launch somewhere?

**Comment by AtsushiKan** [comment] 2017-05-02 15:00
You should just be able to hit F5 in VS - the repo .sln for these projects are supposed to populate the debug parameters correctly. I never use Test Explorer so I don't know if that's even supported in CoreFx.

**Comment by danmosemsft** [comment] 2017-06-15 05:25
@AArnott is this something you're still looking at? do you need any pointers?

**Comment by AArnott** [comment] 2017-06-16 00:30
I haven't spent more time on it yet. My interest was primarily on learning who was calling the base methods of `HashBucket`. I didn't realize folks were waiting for me to fix it. :) I'm willing to, but it may not happen this week as I've been OOF for a week ending today and I have a lot to catch up on, plus Connect discussion to have with my team.

**Comment by danmosemsft** [comment] 2017-06-16 02:54
No obligation Andrew just let us know if you don't...

**Comment by AtsushiKan** [comment] 2017-06-19 17:31
@morganbr, @danmosemsft 

Just as a reminder, the "Must fix by UWP 6.0" part of this can also be satisifed by fixing the toolchain so it knows to generate the the Equals/GetHashCode() methods for Hashbucket. (It's also supposed to be doing that based on the code pattern.) Let me know if you'd rather have a separate TFS bug for that as that bug fix should happen regardless of whether we fix the S.C.Immutable code.

If we get the toolchain fix, we can move the milestone out as this no longer a correctness issue but a perf issue (for CoreCLR.)

**Comment by AtsushiKan** [comment] 2017-06-19 17:33
I just realized I already had opened a TFS bug: 426550

**Comment by tijoytom** [comment] 2017-06-21 05:14
@AArnott The TFS bug is assigned to @morganbr . I am closing this one

**Comment by stephentoub** [comment] 2017-06-21 10:05
@tijoytom, why did you close this? Isn't there still a perf issue on coreclr?

**Comment by tijoytom** [comment] 2017-06-21 16:10
@stephentoub If there is a perf issue please open a seperate bug , this is tagged under UWP6.0 and there is a corresponding  TFS bug.

**Comment by tijoytom** [comment] 2017-06-21 16:12
On non-AOT platform the issue is

ImmutableHashSet<>.HashBucket needs to implement an Equals()/GetHashCode() pair. I strongly recommend that it also implement IEquatable<HashBucket> to remove the boxing penalty.

and the reflection use on AOT is tracked by TFS bug.

**Comment by stephentoub** [comment] 2017-06-21 16:15
> If there is a perf issue please open a seperate bug

No.  This issue as originally opened was covering both.  If it no longer needs to cover one piece of it, then we can just do as Ati says and change the milestone.  We shouldn't just close bugs and lose the relevant work.

Further, this issue number is still referred to in multiple ActiveIssues, e.g.
https://github.com/dotnet/corefx/blob/b3a7e25c630a1fb4a4631db0c763abaf04b409dd/src/System.Collections.Immutable/tests/ImmutableHashSetTest.cs#L67
https://github.com/dotnet/corefx/blob/b3a7e25c630a1fb4a4631db0c763abaf04b409dd/src/System.Collections.Immutable/tests/ImmutableHashSetTest.cs#L151
We should not be closing issues that are still referenced by code.

**Comment by tijoytom** [comment] 2017-06-21 16:20
This issue as originally opened was covering both
   That's a problem , if it's two different issues , they should be not be covered by one active bug. The UWP6.0 bugs need to be fixed by 7/14 , if this do not fall under UWP anymore please move it out of UWP then.

**Comment by danmosemsft** [comment] 2017-06-21 16:37
Oops, our title edits crossed. fine.

**Comment by morganbr** [comment] 2017-06-21 20:07
The ProjectN fix might not make it into UWP6.0, so fixing ImmutableHashSet might be a good idea for that just in case.

**Comment by AtsushiKan** [comment] 2017-06-21 20:09
One way or the other, this needs to be fixed for UWP6.0. Without this, these two types will experience weird, sporadic and undiagnosable corruptions.

**Comment by AArnott** [comment] 2017-06-26 19:52
@AtsushiKan Hitting F5 in the sln opens a console window briefly then exits. The Debug output window contains only this:

```
The program '[10244] dotnet.exe' has exited with code -2147450741 (0x8000808b).
The program '[10244] dotnet.exe: Program Trace' has exited with code 0 (0x0).
```

**Comment by AtsushiKan** [comment] 2017-06-26 20:01
Have you tried hitting Ctrl-F5 (the "hey VS, do you mind if I read the console before you take it down?" hotkey.)

**Comment by AArnott** [comment] 2017-06-26 21:05
Ctrl+F5 flashes the console window for an even shorter time. I know what you're talking about though, @AtsushiKan  where VS will usually keep the window open till I hit a key, but that doesn't happen here.

So I copied the command line from the Debug panel to my own developer prompt. Here is the output I see:

```
Error initializing the dependency resolver: A fatal error was encountered, missing dependencies manifest at: C:\git\corefx\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\Microsoft.NETCore.App.deps.json
```

The directory that is named above is present, and lots of files are in it. But not a single `*.json` file.

**Comment by AtsushiKan** [comment] 2017-06-26 21:14
That file is something built in the overall build that's a prequisite for doing anything in corefx.

Here's my morning routine (which creates that file.)

cd <repo-root>
git clean -xdf  
.\sync.cmd -p   // retrieve thousands of packages... (~5 min)
.\build.cmd      // build the test-host and whatever else that script builds... (~10 min)

After that, that file you mentioned is there and tests are ready to build and debug.

**Comment by AArnott** [comment] 2017-06-26 21:49
I thought build.cmd worked for me previously, but today it fails with:

```
CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.
Failed to generate native component build project!
Command execution failed with exit code 1.
```

I don't remember CMake being a dependency. Do I really need to find and install that just to build and test this immutable collections library?

**Comment by AtsushiKan** [comment] 2017-06-26 21:57
Yeah, the prereqs (including CMake) are documented here: https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

I believe it's used to build some native support needed by some libaries - may be a x-plat thing though. You could try to trick the build into ignoring that requirement but I haven't ever tried that so can't say what success you would have.

**Comment by AArnott** [comment] 2017-06-26 23:38
I ran `.\build-managed.cmd` and that avoided the CMake dependency and I still ended up with the .json file I needed. I'm running tests now. 😀

**Comment by AArnott** [comment] 2017-06-27 00:09
I have the naive fix here: https://github.com/AArnott/corefx/commit/2bdf03dc7d25fae8fbee1868bbc130fd34807ce8

But I'm not sure it's what we need. The `HashBucket` doesn't really know how to equate `T _firstValue`. Comparing `_additionalElements` is easier because that's a ref type. 
The owning `ImmutableHashSet<T>` knows which comparer to use for `T`, but that needs to propagate to the `HashBucket.Equals` and `GetHashCode` methods. I'm working on how we can do that without bloating memory a bunch with more fields.

I'm also trying to convince myself one way or another regarding whether we need exactly the same `T` in the case of reference types or if it's OK to call `Equals` on a reference type and have the HashBucket decide it's Equal.

**Comment by AtsushiKan** [comment] 2017-06-27 13:59
The status quo is that they're being compared using their Object.Equals() override (which means I guess this is actually a correctness bug on CoreCLR too - not just a perf bug?)

The fix is probably then not to use EqualityComparer&lt;HashBucket&gtl.Default to compare hash buckets in the first place (disclaimer: I don't know if that one instance I found is the only site that compares hash buckets.) There should be a HashBucket-specific compare method that takes the comparer instance as an argument. (It'd be also nice for HashBucket to override Equals() and GetHashCode() with a "Hey - don't call me - call that other guy" stub.)

**Comment by AArnott** [comment] 2017-06-27 14:33
Ya, that's what I was coming to as well. Thanks for confirming.

**Comment by AArnott** [comment] 2017-06-29 19:45
As an update, I have the code changes done in what I believe is a reasonable way. The test coverage is inadequate so I'll be adding tests later today. I expect to send a PR by tomorrow.

**Closed** 2017-07-01 15:38 UTC
Labels: area-System.Collections, bug, tenet-performance, test-run-uwp-ilc
