### ISSUE TITLE
New span-based overload Encoding.GetBytes() is slow

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#30382] opened 2018-06-14 07:06 UTC
The following benchmark compares 3 ways of encoding a UTF8 string to binary:

1. Array: `Encoding.GetBytes()` on a `byte[]`
2. SpanLegacy: getting a pointer to a `Span<byte>` and calling `Encoding.GetBytes()` on that. This method allows using Span on pre-netcoreapp2.1 targets.
3. Span21: using the new `Encoding.GetBytes()` overload introduced in netcoreapp2.1 which accepts spans directly.

Results show that the new overload is surprisingly slow:

``` ini

BenchmarkDotNet=v0.10.14, OS=ubuntu 18.04
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 65525 physical cores
.NET Core SDK=2.1.300
  [Host]     : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT


```
|     Method |      Mean |     Error |    StdDev | Scaled |
|----------- |----------:|----------:|----------:|-------:|
|      Array |  99.47 ns | 0.6631 ns | 0.6203 ns |   1.00 |
| SpanLegacy |  97.85 ns | 0.4903 ns | 0.4347 ns |   0.98 |
|     Span21 | 110.77 ns | 0.5877 ns | 0.5210 ns |   1.11 |

The benchmark code:

```c#
public class WriteString
{
    const int StringSize = 256;
    string Data = new string('x', StringSize);
    byte[] Buffer = new byte[1024];

    readonly Encoding Encoding = Encoding.UTF8;

    [Benchmark(Baseline = true)]
    public void Array() => Encoding.GetBytes(Data, 0, 256, Buffer, 0);

    [Benchmark]
    public unsafe void SpanLegacy()
    {
        var span = new Span<byte>(Buffer);
        fixed (char* chars = Data)
        fixed (byte* bytes = &span.GetPinnableReference())
        {
            Encoding.GetBytes(chars, StringSize, bytes, 1024);
        }
    }

    [Benchmark]
    public void Span21()
    {
        var span = new Span<byte>(Buffer);
        Encoding.GetBytes(Data, span);
    }
}
```

When decoding, the new overload is also the slowest, although the gap is smaller:

``` ini

BenchmarkDotNet=v0.10.14, OS=ubuntu 18.04
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical cores and 1 physical core
.NET Core SDK=2.1.300
  [Host]     : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT


```
|     Method |     Mean |     Error |    StdDev | Scaled |
|----------- |---------:|----------:|----------:|-------:|
|      Array | 164.4 ns | 0.6337 ns | 0.5618 ns |   1.00 |
| SpanLegacy | 164.8 ns | 0.5748 ns | 0.5096 ns |   1.00 |
|     Span21 | 167.5 ns | 0.9230 ns | 0.7708 ns |   1.02 |

Code:

```c#
public class ReadString
{
    const int StringSize = 256;
    byte[] Buffer = new byte[StringSize];
    readonly Encoding Encoding = Encoding.UTF8;

    public ReadString()
    {
        var data = new string('x', StringSize);
        Encoding.GetBytes(data, 0, StringSize, Buffer, 0);
    }

    [Benchmark(Baseline = true)]
    public string Array() => Encoding.GetString(Buffer, 0, StringSize);

    [Benchmark]
    public unsafe string SpanLegacy()
    {
        var span = new Span<byte>(Buffer);
        fixed (byte* bytes = &span.GetPinnableReference())
        {
            return Encoding.GetString(bytes, StringSize);
        }
    }

    [Benchmark]
    public string Span21()
    {
        var span = new Span<byte>(Buffer);
        return Encoding.GetString(span);
    }
}
```

I'm guessing that other related overloads should also be investigated, especially chunked encoding/decoding (`TextEncoder/TextDecoder`).

**Comment by tarekgh** [comment] 2018-06-14 19:03
CC @stephentoub

**Comment by ViktorHofer** [comment] 2018-06-15 12:04
@stephentoub I see that with your change https://github.com/dotnet/coreclr/pull/13269 you added Span overloads in System.Encoding by pinning the Span. Maybe we can avoid the Span pinning and also reduce allocating by using stackalloc / ArrayPool for the char and byte array allocations. If you agree I would take this one and try to optimize.

**Comment by jkotas** [comment] 2018-06-15 12:34
@ViktorHofer The first step on this issue should be the profile the two cases using perfview and see where the problem is.

I doubt that pinning or stackalloc is a problem in this case. My guess is that it will be https://github.com/dotnet/coreclr/pull/13269#discussion_r131971645

**Comment by jkotas** [comment] 2018-06-15 12:40
https://github.com/dotnet/coreclr/issues/9668 is related to this.

**Comment by ViktorHofer** [comment] 2018-06-15 13:06
Thanks Jan, I looked through the links and it seems we are currently in a depressing state. We want to switch to a faster implementation but our coverage is to low to make a confident change: https://github.com/dotnet/corefx/issues/16334

Someone probably needs to spend some time writing up tests to cover most cases and corner cases and after that we can switch to a faster implementation (corefxlab).

**Comment by stephentoub** [comment] 2018-06-15 18:35
I'm not convinced the issue with the repro is with Encoding.GetBytes, at least not the primary issue: a large part of it appears to be in the repro code itself, or specifically the issues we're already aware of around zero-init.  For example, I tweaked the benchmark to allow me to specify a number of iterations within each call:
```C#
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes.Jobs;

[MemoryDiagnoser]
[InProcess]
public class Benchmarks
{
    private static void Main() => BenchmarkRunner.Run<Benchmarks>();

    const int InnerIters = 1;
    const int StringSize = 256;
    string Data = new string('x', StringSize);
    byte[] Buffer = new byte[1024];

    readonly Encoding Encoding = Encoding.UTF8;

    [Benchmark(Baseline = true)]
    public void Array()
    {
        for (int i = 0; i < InnerIters; i++) Encoding.GetBytes(Data, 0, Data.Length, Buffer, 0);
    }

    [Benchmark]
    public unsafe void SpanLegacy()
    {
        var span = new Span<byte>(Buffer);
        fixed (char* chars = Data)
        fixed (byte* bytes = &span.GetPinnableReference())
        {
            for (int i = 0; i < InnerIters; i++) Encoding.GetBytes(chars, Data.Length, bytes, span.Length);
        }
    }

    [Benchmark]
    public void Span21()
    {
        var dst = new Span<byte>(Buffer);
        var src = Data.AsSpan();
        for (int i = 0; i < InnerIters; i++) Encoding.GetBytes(src, dst);
    }
}
```
With InnerIters == 1 (matching the original repro), I get numbers like:

|     Method |     Mean |     Error |    StdDev | Scaled | Allocated |
|----------- |---------:|----------:|----------:|-------:|----------:|
|      Array | 89.15 ns | 0.4122 ns | 0.3654 ns |   1.00 |       0 B |
| SpanLegacy | 87.99 ns | 0.3675 ns | 0.3437 ns |   0.99 |       0 B |
|     Span21 | 95.28 ns | 0.3786 ns | 0.3541 ns |   1.07 |       0 B |

but change InnerIters to be 1000, and I get numbers like:

|     Method |     Mean |     Error |    StdDev | Scaled | Allocated |
|----------- |---------:|----------:|----------:|-------:|----------:|
|      Array | 86.66 us | 0.5805 us | 0.5430 us |   1.00 |       0 B |
| SpanLegacy | 84.45 us | 0.4751 us | 0.4444 us |   0.97 |       0 B |
|     Span21 | 87.06 us | 0.4580 us | 0.4060 us |   1.00 |       0 B |

From looking at the disasm, it seems like this is primarily the same issue highlighted in https://github.com/dotnet/coreclr/issues/13827, using `rep stosd` for the initialization instead of `mov`s.  @jkotas, does that seem right to you?

There's still some small room for improvement as @jkotas alluded to with regards to virtual calls.  If I add this to UTF8Encoding:
```C#
public override unsafe int GetBytes(ReadOnlySpan<char> chars, Span<byte> bytes)
{
    fixed (char* charsPtr = &MemoryMarshal.GetNonNullPinnableReference(chars))
    fixed (byte* bytesPtr = &MemoryMarshal.GetNonNullPinnableReference(bytes))
    {
        return GetBytes(charsPtr, chars.Length, bytesPtr, bytes.Length, baseEncoder: null);
    }
}
```
then still with InnerIters == 1000, I get results like:

|     Method |     Mean |     Error |    StdDev | Scaled | Allocated |
|----------- |---------:|----------:|----------:|-------:|----------:|
|      Array | 86.71 us | 0.4385 us | 0.4101 us |   1.00 |       0 B |
| SpanLegacy | 86.80 us | 1.0304 us | 0.9638 us |   1.00 |       0 B |
|     Span21 | 85.49 us | 0.5023 us | 0.4453 us |   0.99 |       0 B |

So, I can submit a PR to do that, but there's still the zero-init issue at the call site.

**Comment by jkotas** [comment] 2018-06-15 19:16
> `rep stosd` for the initialization instead of `movs`  @jkotas, does that seem right to you?

Yes, it sounds plausible. The string in the benchmark is not very long, so this can make a measurable difference.

**Comment by stephentoub** [comment] 2018-06-15 22:18
https://github.com/dotnet/coreclr/pull/18487 was merged, so I'm going to close this.

**Closed by stephentoub** 2018-06-15 22:18 UTC
Labels: area-System.Text.Encoding, bug, tenet-performance
