### ISSUE TITLE
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate is failing

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#16202] opened 2017-02-15 21:40 UTC
These are failing

Logs at https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/

`System.Net.Http.HttpRequestException : An error occurred while sending the request.\r\n---- System.Net.Http.WinHttpException : The data is invalid`

```
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"\", expectedFragment: \"#origFragment\", useRelativeRedirect: False)	14 ms	6
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: False)	4 ms	6
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: True)	5 ms	6
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: False)	6 ms	6
 System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_AllowAutoRedirectTrue_RetainsOriginalFragmentIfAppropriate(origFragment: \"#origFragment\", redirFragment: \"#redirFragment\", expectedFragment: \"#redirFragment\", useRelativeRedirect: True)	5 ms	6
All Tests
```

@Priya91 @steveharter please fix or (presumably) disable today so we can get a green badge.
Click in  to see the logs.

**Comment by Priya91** [comment] 2017-02-15 22:02
@danmosemsft This is a dupe of #16133.. And it's from the same run #97. Can you please avoid filing duplicate bugs when there are no newer runs.

**Closed by Priya91** 2017-02-15 22:02 UTC
Labels: area-System.Net.Http, blocking-clean-ci, test-run-core
