### ISSUE TITLE
Blocking Task.Result design flaw leads to deadlock when called from ThreadPool thread

### ISSUE THREAD

**Issue by AqlaSolutions** [dotnet/corefx#11463] opened 2016-09-06 07:57 UTC
Run this application:

https://gist.github.com/AqlaSolutions/f8c993bfad32dc9be11703fea4e01422

It simulates network engine receiving requests and calling synchronously `IConnection.OnRequestReceived`. This method calls async method and then synchronously processes the result retrieved with Task.Result. The async method may take up to 700 ms.

Assume I can't use await, because external network engine provides synchronous interface and I need to check async call result before returning.

During run the simulation will decrease time between requests until deadlock occurs - after that point currently awaiting requests will never be completed.

I set TP to low threads number to show the problem. It will also happen on 200 and 1000 threads but it will just take more time and will require modifying the simulation code for more requests. In a real app you will never want to set max threads to big numbers because it will make your app very slow (context switching thing) and also each thread takes 1 MB RAM.

This example proves that absolutely any blocking call to `Task.Result` or `Task.Wait` from `ThreadPool` thread will work for some time but will eventually deadlock your application in truly high load scenario. Using these methods from `ThreadPool` thread for waiting is always a mistake and should be disallowed (but I understand that it will not happen for compatibility reasons).

Yes, we all know from docs that mixing async and blocking "may cause deadlocks" but previously I thought about this only in a way "do not block with `.Result` thread which synchronization context may be required to complete the waited task itself". TP deadlock is not obvious and many people will "just use `.Result`" without ever encountering it during testing.

What do you think? May be some workarounds inside .NET TP? Prioritize continuations over new tasks?

**Comment by svick** [comment] 2016-09-06 10:54
I don't see how this is a flaw in `Task.Result` or how could it be fixed by the framework.

If *your code* is going to block all the available `ThreadPool` threads and continuing those threads also requires some code to run on the `ThreadPool`, then of course you're going to get a deadlock.

The solution is to not block (probably by using `await`), or, if you really can't, increase the number of max threads. And if this actually causes performance issues (not sure how, 1 GB is not that much memory, and hundreds of *blocked* threads won't cause much context switching), then some possible workarounds for you are:

* Asynchronously limit the max number of concurrent requests.
* Use a custom thread pool `TaskScheduler`, which uses threads with smaller stacks. (This will only help with memory consumption and is only available on .Net Framwork, not .Net Core.)

**Comment by AqlaSolutions** [comment] 2016-09-06 11:41
@svick, again, people usually think that blocking with `.Result` is just not recommended but it won't break an app. Recently I saw a comment on SO:

>You don't have to make the calling methods async - they can just do the call to the async method as var result = SomeAsyncMethod().Result. In this way, you can break the "async chain" until you are ready to refactor further up the call tree.

But the reality is that you should never wait with `.Result` from TP threads - if one request can do it - there is a chance to have 100 requests waiting like this at same time (but may be in different code places). This problem is not obvious and not documented enough.

On the `TaskScheduler` - I thought it affects only `ContinueWith` behavior. Can you describe more how using custom `TaskScheduler` should be done?

**Comment by stephentoub** [comment] 2016-09-06 13:32
> I don't see how this is a flaw in Task.Result or how could it be fixed by the framework.

+1

> But the reality is that you should never wait with .Result from TP threads

This has little to do with .Result... it's simply about blocking in general.  You're right that one should avoid blocking as much as possible, especially on thread pool threads, but that doesn't mean that it's a design flaw to having APIs that block, rather it means one should try to minimize the usage of APIs that block.  For example, it's not a design flaw that ManualResetEventSlim.Wait() blocks, but it may be a design flaw of an app if it uses that method too much, in places it shouldn't, etc.

Task.Result/Wait already do try to do a bit of additional smarts to alleviate some of the issue here: if you wait on a task backed by a delegate (e.g. Task.Run(someDelegate)), and that task hasn't started executing yet, then the wait operation will ask the scheduler if it's ok for the wait to "inline" the execution, i.e. rather than simply blocking and waiting for some other thread to come along and execute the task, since this thread is going to be blocked anyway, it may as well run the task rather than blocking waiting for it.  But that only helps in some situations, and it doesn't help if there's nothing to actually run, e.g. the task returned from an async method is just a promise... there's nothing associated with it to actually "run", so waiting on it will block.  We explicitly chose not to pump arbitrary work items in this case, in part as doing so could cause the wait to take much longer than it otherwise would have (the pumped work item may be completely unrelated).

**Comment by AqlaSolutions** [comment] 2016-09-06 19:53
Developer expects blocking to perform slower but not to disable the whole app. The different is between "will be not efficient" and "block app from doing anything until restart". The first is acceptable and expected but the second is what can actually happen. It's not about choice between fast and slow but instead between working and hanging. 

If you have a method which can't be used because each time it's called it has a chance to block the whole app - it's a design flaw.

**Comment by stephentoub** [comment] 2016-09-06 20:08
@AqlaSolutions, I don't understand the response.

Your comment suggests that ManualResetEventSlim.Wait() is a design flaw, because I can write code that does:
```C#
ThreadPool.QueueUserWorkItem(() => new ManualResetEventSlim().Wait());
```
and block a thread pool thread forever.  The flaw here isn't in MRES.Wait(), though, it's in how I'm using it.

**Comment by AqlaSolutions** [comment] 2016-09-06 20:14
@stephentoub, `ManualResetEventSlim.Wait` has it's specific application area and in your example it's applied incorrectly. But blocking calls to `Task.Result` are expected to be applicable in usual situations. Now considering the deadlock they are *not applicable* in area where they are expected to work (not efficiently, but stable!).

**Comment by stephentoub** [comment] 2016-09-06 21:12
I can't tell if we're talking past each other or if we're going to need to agree to disagree.

The purpose of Task.Wait() is to not return until the task has completed; that may involve blocking.  The purpose of Task.Result is to give you back the result of the task, which may involve waiting for the task to complete (otherwise there is no result).  If you're in a situation where you don't want to block, then don't use blocking operations.

**Comment by terrajobst** [comment] 2016-09-06 22:43
I think the argument that @AqlaSolutions is trying to make is that `await` and `async` have changed the systems enough that deadlocks happen more frequently. VS has similar problems which is why they are pumping messages when doings waits...

**Comment by stephentoub** [comment] 2016-09-06 22:50
> VS has similar problems which is why they are pumping messages when doings waits

VS has other issues, such as needing to deal with multiple UI models and COM, and a single UI thread.

> await and async have changed the systems enough that deadlocks happen more frequently

Ok. And, what is the desired change here?  My response is the same: don't use blocking APIs if you don't want to block.  I've already outlined some reasons why general pumping during Task.Wait()/Result would be a bad thing to do.  Unless there's a concrete proposal here for something to change, I'm not seeing the action item.

**Comment by benaadams** [comment] 2016-09-07 07:04
For context the author was having issues with NHibernate

> NHibernate authors already stated that they are not going to support async and that it shouldn't affect performance when compared to app logic. This is an example how "good" people usually understand TP. Do you still think they won't use .Result in TP threads?

> Anyway NHibernate is a very big project and I don't believe that it can be easily migrated to async.

> So for my project I will create async wrappers for the most blocking thing in NHibernate - getting connection from pool - which will move blocking calls to a separate custom TP and free the main TP for continuations.

@AqlaSolutions a non-blocking use of `.Result` (or `.GetAwaiter().GetResult()` which is similar but doesn't give aggregate exceptions for single tasks) would be:

```csharp
if (task.IsCompleted)
{
    if (task.RanToCompletion)
    {
         var result = task.GetAwaiter().GetResult();
    }
    else 
    {
         // error or cancelled
    }
}
else
{
    // not finished yet
}
```

**Comment by alexperovich** [comment] 2016-10-14 22:17
Closing because there is nothing actionable here. #8949 could help with the problem. You could also inspect the Task state without blocking with either @benaadams suggestion or #8931.

Feel free to reopen if you have a specific proposal.

**Closed by alexperovich** 2016-10-14 22:17 UTC
Labels: area-System.Threading

**Comment by tedekeroth** [comment] 2019-10-08 20:24
I know this is some 3 years later, and this is closed, but: AqlaSolutions is completely correct. It is very error-prone these days when trying to adopt the TPL. Using .Result is for most people OK to use, not understanding that it will eventually break your application.

That this design passed through the .NET team is beyond me...

**Comment by AqlaSolutions** [comment] 2019-10-08 21:19
@alexperovich @tedekeroth actually my specific proposal is prioritizing Task continuations to be executed before others queued in ThreadPool. Because async code is usually waited by someone it's better to continue instead of using resources on other tasks. Or it may be even better to detect Tasks which are blocking other code (calls to .Result or .Wait) and prioritize only such tasks in ThreadPool.

**Comment by AqlaSolutions** [comment] 2019-10-08 21:29
It seems that I was misunderstand what this issue is about. 

Let me explain it now again: 
1. assume there is a call to `.Result` in a synchronous code that calls wants to wait for async method
2. request processing library calls this synchronous code using ThreadPool many times
3. this leads to a case when *all* of ThreadPool threads are waiting in `.Result` and there are no free threads to actually execute those async methods which are waited for.

**Comment by Clockwork-Muse** [comment] 2019-10-08 22:49
@AqlaSolutions - 
[Async tasks don't (necessarily) have a thread associated with them you could raise the priority on](https://blog.stephencleary.com/2013/11/there-is-no-thread.html).  If you consider things like network I/O, _even if the app is otherwise behaving_ you could run into deadlocks simply by having too many requests outstanding to a slow service - and there's nothing your code could do to "speed up" or otherwise prioritize those requests.

**Comment by AqlaSolutions** [comment] 2019-10-09 08:04
@Clockwork-Muse , 
1. deadlock and slowing down are different things.
2. I'm not asking to raise thread priority, I'm asking to raise action priority in ThreadPool queue. IO tasks callback through ThreadPool too.

**Comment by tedekeroth** [comment] 2019-10-09 08:13
Yes, too many requests are not at all the same thing as a deadlock.

I find it hard to understand how anyone can defend the hugely error prone situation that we have today, where using constructs, like .Wait() and .Result, that is readily available, when in fact that will lead to a deadlock. A deadlock by design.
