### ISSUE TITLE
Rethink System.Linq.Expressions.Tests.csproj

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#31665] opened 2018-08-08 23:10 UTC
I don't know what's the historical reason why we disable the default test references `<IncludeDefaultReferences>false</IncludeDefaultReferences>` and add them manually. The git history doesn't really tell either. Is this a left-over or still here for a reason?

https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj

cc @danmosemsft @joperezr

**Comment by joperezr** [comment] 2018-08-13 16:48
Usually, we did this whenever we wanted to reference the implementation directly, or if we wanted to compile de implementation as part of the test project. Test projects automatically get a reference to the whole targeting pack (for example, on the netcoreapp vertical they will get a reference to everything under bin/ref/netcoreapp) so if we wanted to test a class that only exists in the implementation of a library but not exposed in the contract, we weren't able to. For cases like this, we decided to reference the implementation directly and disable all of the references to the targeting pack, and instead ensamble the references ourselves. 

If you see this piece of code on that project you'll see how we add manually a reference to the implementation directly since we want to test a class that is only exposed there:
https://github.com/dotnet/corefx/blob/9301706972eb90757f335d8ad2601b54d1f56c67/src/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj#L14-L17

I can't fully remember what this class is, but if you want to know, simply comment out all of the `ReferenceFromRuntime` items and also comment out the `<IncludeDefaultReferences>false</IncludeDefaultReferences>` and try to build. You should see an error of a missing class, which would be the reason why we did it like this.

**Comment by ViktorHofer** [comment] 2018-08-13 16:57
Ok thanks, so can we now use this instead? https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Tests.csproj#L9

**Comment by joperezr** [comment] 2018-08-13 17:46
No, in fact that line could be deleted. That would be enough if System.Linq.Expressions didn't depend on the runtime directly, but it does, which means that we have to reference all of the runtime manually.

**Comment by ViktorHofer** [comment] 2018-08-13 17:49
Ah sorry, I meant the line below: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Composition/tests/System.ComponentModel.Composition.Tests.csproj#L10

**Comment by ViktorHofer** [comment] 2018-08-13 17:49
Ah ok I think I misunderstood something. I will re-read what you wrote and respond later.

**Comment by joperezr** [comment] 2018-08-13 18:05
Closing the issue since this was discussed offline and decided that this is by design.

**Closed by joperezr** 2018-08-13 18:05 UTC
Labels: Design Discussion, area-System.Linq.Expressions, question
