### ISSUE TITLE
Please support S.R.IS.RI (and System.Native.so) seperately from corefx as well

### ISSUE THREAD

**Issue by borgdylan** [dotnet/corefx#9754] opened 2016-06-29 13:26 UTC
Currently mono does not ship an API that implements ```System.Runtime.InteropServices.RuntimeInformation``` in the box. The NuGet package shipped as part of the .NET Standard Library indicates this API as being compatible with ```netstandard1.1``` which implies Mono compatibility. I have managed to compile ```libSystem.Native.so``` (System.Native.so won't work without a dll-map) for 32 and 64 bit Linux and used them with this API on Mono. The process was hacky at best when targeting x86, and longer than it should be for x64. I consider this API as being very useful for cross platform programming and for supporting special behaviors on specific OS/Architecture combinations. This is why it would be wonderful if the native library ```System.Native``` was compilable separately or maybe distributed separately as a runtime for this API.

**Comment by ericstj** [comment] 2016-06-29 16:22
Duplicate of https://github.com/dotnet/corefx/issues/9012

**Closed by ericstj** 2016-06-29 16:22 UTC
