### ISSUE TITLE
Beginning in version 4.5.0, System.Reflection.TypeExtensions fails at runtime for ns1.3–ns1.5

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#30506] opened 2018-06-19 12:47 UTC
If I use System.Reflection.TypeExtensions 4.4.0 in a netstandard1.4 library which then runs with netcoreapp1.1, it runs fine. If I upgrade to System.Reflection.TypeExtensions 4.5.0, the project builds but it fails to load at runtime with "System.Reflection.TypeExtensions is not supported on NET Standard 1.3 or 1.5."
The 4.5.0 package still targets netstandard1.3 and netstandard1.5 which indicates that it's intended to work there. Is this error somehow a misconfiguration on my end, or maybe a packaging error?

I looked for a discussion issue or release notes mentioning it and didn't find any. If this is an intentional change to drop support for netstandard1.3–1.5, would you please consider supporting them again, for us library authors who use netstandard1.4 to support folks on `uap10.0`? Are there gotchas we should know about if we stick with 4.4.0 which seems to run fine when referenced from netstandard1.4 projects?

**Comment by karelz** [comment] 2018-06-19 18:56
cc @AtsushiKan @joshfree @weshaggard

**Comment by weshaggard** [comment] 2018-06-19 21:16
@ericstj looks like this issue is caused by your change (https://github.com/dotnet/corefx/commit/72002dbb7e3e657adaeb002feca0399d9667a54b) to harvest the netstandard asset which throws PNSE and include it for netcoreapp1.0 
https://github.com/dotnet/corefx/blame/release/2.1/src/System.Reflection.TypeExtensions/pkg/System.Reflection.TypeExtensions.pkgproj#L15.

I don't think we intentionally wanted to break this, @ericstj is there any reason we don't harvest the netcoreapp1.0 asset?

**Comment by ericstj** [comment] 2018-06-19 21:52
Actually that change was correct when it was first shipped, it was only after we versioned that the remapping started picking up the wrong assembly.  We should look at all cases where we were moving assemblies via harvest remapping and make sure those are doing the correct thing if we changed the package version they were harvesting from.

**Comment by mwpowellhtx** [comment] 2018-06-20 20:15
Somewhere along the way I'd received feedback that we should "forget about" *[ns1.6)* and just run with *(ns2.0]*? (note, version ranges...) Is this aligned with tooling dependencies on *[ns1.6)*?

**Comment by ericstj** [comment] 2018-06-22 16:27
Not sure what advice you're talking about @mwpowellhtx.  There aren't many platforms that support ns1.6 and not ns2.0, really that's only .NETCore 1.x.  Perhaps you should open a question issue in the dotnet/standard repo and tag @terrajobst?

@jnm2 we put a fix in master for this.  Could you try it out and let us know if it fixes the issue for you?  If so we'll try to get a fix through servicing (if it meets the bar).

**Comment by ericstj** [comment] 2018-06-22 16:50
Also, with respect to your comments about UAP: the package contains a specific asset for uap10 (using netcore50 TFM) so that shouldn't be broken in the 4.5.0 package, just netcoreapp1.x was broken.

**Comment by jnm2** [comment] 2018-06-22 17:10
Sure. I have just verified that `4.6.0-preview1-26622-01` resolves the problem on .NET Core 1.1, and thanks for the confirmation about UWP.

**Comment by karelz** [comment] 2018-07-08 20:35
@ericstj was it fully or just partially fixed by your 2.1.x PR #30609?

**Comment by ericstj** [comment] 2018-07-09 15:30
Yep, should be fixed starting in https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Reflection.TypeExtensions/4.5.1-servicing-26703-08.

**Closed by ericstj** 2018-07-09 15:30 UTC
Labels: area-System.Reflection, bug
