### ISSUE TITLE
System.Net test intermittent failures

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#10702] opened 2016-08-10 23:20 UTC
few test cases are marked with `[ActiveIssue(10702)]`
(pending work - i need to have an issue number to mark it  :smile:)

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_release_prtest/324/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_debug_prtest/329/

Happened in here: https://github.com/dotnet/corefx/pull/10693

**Comment by krwq** [comment] 2016-08-10 23:33
Hey @ericeil could you take a look? It happened when merging xml PR but it doesn't seem like any of those have anything to do with XML.

**Comment by davidsh** [comment] 2016-11-22 16:54
Closing this issue since the repro logs are no longer available.

**Comment by Jiayili1** [comment] 2017-02-24 06:48
Disabled test, reopen it.

**Comment by Priya91** [comment] 2017-02-28 19:18
The disabled test is a dupe of issue #9296.

**Closed** 2017-02-28 19:18 UTC
Labels: area-System.Net, disabled-test, test-run-core

**Comment by karelz** [comment] 2017-02-28 20:02
@Priya91 can you please update the code to refer to the active issue? We do not want ActiveIssue on closed bugs in code.

**Comment by Priya91** [comment] 2017-02-28 20:03
@karelz Yes I have a couple of other changes to go in as well, will consolidate and open a PR soon.

**Comment by karelz** [comment] 2017-02-28 20:04
Perfect, thanks!
