### ISSUE TITLE
Desktop: DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings failed with "Xunit.Sdk.TrueException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18802] opened 2017-04-24 02:47 UTC
Failed test: DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/29/testReport/(root)/DataContractJsonSerializerTests/DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings/

Configuration: outerloop_netfx_windows_nt_debug

MESSAGE:
~~~
Assert.True() Failure
   Expected: True
   Actual: False
~~~
STACK TRACE:
at DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings() 
in D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs:line 2547

**Comment by Jiayili1** [comment] 2017-04-25 02:52
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/30/testReport/(root)/DataContractJsonSerializerTests/DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings/

**Comment by danmosemsft** [comment] 2017-04-25 04:27
@shmao you were making some other change recently to datetime serialization?

```
        var graph = new DateTimeOffset(2008, 5, 1, 8, 6, 32, new TimeSpan(1, 0, 0));
        dcjsSettings = new DataContractJsonSerializerSettings() { DateTimeFormat = jsonTypes.DTF_DMMMM };
        var actual3 = SerializeAndDeserialize(graph, "{\"DateTime\":\"1, mayo\",\"OffsetMinutes\":60}", dcjsSettings);
        Assert.NotNull(actual3);
        Assert.True(actual3 == new DateTimeOffset(2017, 5, 1, 1, 0, 0, new TimeSpan(1, 0, 0)));
```

**Comment by shmao** [comment] 2017-04-25 06:22
@stone-li just to confirm, PR https://github.com/dotnet/corefx/pull/18833 would fix this issue as well, right?

**Comment by shmao** [comment] 2017-04-25 06:27
This is a duplicate of #18539.

**Comment by shmao** [comment] 2017-04-25 22:22
The test is still failing on netfx.

**Comment by Jiayili1** [comment] 2017-04-26 06:31
This issue is repro on full framework tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170426.01/workItem/System.Runtime.Serialization.Json.ReflectionOnly.Tests/analysis/xunit/DataContractJsonSerializerTests~2FDCJS_VerifyDateTimeForFormatStringDCJsonSerSettings

**Closed** 2017-04-27 02:25 UTC
Labels: area-Serialization, bug, test-run-desktop
