### ISSUE TITLE
Migrate to 3.0 misleading message to reference System.Data.SqlClient

### ISSUE THREAD

**Issue by zehavibarak** [dotnet/corefx#41902] opened 2019-10-16 01:29 UTC
# General

Migrating to core 3.0 from 2.2 issues a message over SqlParameter `SqlParameter is now in System.Data.SqlClient`. Adding the package yield a runtime message `System.InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects`.

# Resolution

Adding a reference to Microsoft.Data.SqlClient, as does the underlaying Microsoft.EntityFrameworkCore, rather than to System.Data.SqlClient - works.

**Comment by scalablecory** [comment] 2019-10-18 18:28
Can you give some sample code that demonstrates this?

**Comment by roji** [comment] 2019-10-21 11:13
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/16812 (and https://github.com/aspnet/EntityFramework.Docs/issues/1815).

As you've found out, when using EF Core 3.0 you must depend on the new Microsoft.Data.SqlClient, and not on System.Data.SqlClient. We'll be updating the documentation to make this clearer (https://github.com/aspnet/EntityFramework.Docs/issues/1815).

**Closed by roji** 2019-10-21 11:13 UTC
Labels: area-System.Data.SqlClient, needs more info
