### ISSUE TITLE
Login failed for user  'NT AUTHORITY\ANONYMOUS LOGON'

### ISSUE THREAD

**Issue by TechWatching** [dotnet/corefx#21824] opened 2017-07-03 08:05 UTC
While using the mssql extension for vscode (which uses SqlClient implementation for .Net Core), I am having an issue for querying linked servers.
See [link](https://github.com/Microsoft/vscode-mssql/issues/909)

Steps to Reproduce:

Connect to a SQL Server with "authenticationType": "Integrated"
Do a select request with a join on the table of a linked server
The following error appears : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'
Other requests work correctly.
This works correctly on SSMS so I guess it is not an issue linked to a bad configuration.

**Comment by karelz** [comment] 2017-07-03 08:46
Can you reproduce it without VSCode extension? We need to isolate which part of the stack the bug is in.

**Comment by TechWatching** [comment] 2017-07-03 09:12
No in SSMS requests on linked servers work correctly without error. The vs code team told me that vs code extension is just relaying messages sent by SqlClient.

**Comment by karelz** [comment] 2017-07-03 09:40
Can you please create repro outside of VS Code then?

**Comment by TechWatching** [comment] 2017-07-03 09:44
How can I do that ?

**Comment by kevcunnane** [comment] 2017-07-03 16:56
@TechWatching if you can provide the T-SQL query you used this is likely the best way to provide a repro. I tried some basic versions but with no luck (see samples below). So if you can provide a better sample this will help get this addressed.

@karelz  - The MSSQL extension is simply executing this and hooking the `InfoMessage` and `StatementCompleted` events and this is a SqlClient message, hence why we're routing it here. One helpful example is in a duplicate bug report - see https://github.com/Microsoft/vscode-mssql/issues/778. In this case the error shown in SSMS was
> XML data type not supported in Distributed Queries
but in our case we got the login failed error

In my attempts to repro, I executed the following queries but got a different message back. It looks like the server I'm using to test on isn't set up correctly, but I am getting a clearer error message so this doesn't look like the right repro:
```
select * from sys.servers
GO
select * from [SQLTOOLS2014].master.sys.databases
```
Returned error (which looks like a correct one, mustn't have the servers setup correctly):
```
OLE DB provider "SQLNCLI11" for linked server "SQLTOOLS2014" returned message "Invalid authorization specification". 
	Msg 7399, Level 16, State 1, Line 2
The OLE DB provider "SQLNCLI11" for linked server "SQLTOOLS2014" reported an error. Authentication failed. 
```

**Comment by karelz** [comment] 2017-07-04 08:13
I am not sure if the above is sufficient for SqlClient team (@saurabh500?)
I would personally ask for isolated repro which does not involve VSCode. It is pain to debug large repros, it costs extra hours / days.

Typical tricks to create isolated repro is to debug through the large repro and take out the pieces which are important & sufficient to reproduce the problem. Incl. initial setup, etc. Then play with the repro and cut out even more things, until it is smallest possible.

**Comment by TechWatching** [comment] 2017-07-06 11:33
I have a 2 servers A with and B. B is in the linked Servers list of A. 
My request is the following :
`select top 100 * from B.B1.dbo.b with (nolock)`
where B1 is a database on server B and b is the name name

It returns the following : 
`Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. `

I first thought it was a configuration issue but the exact same request works correctly on SSMS.
I don't have any xml column in my table.

**Comment by TechWatching** [comment] 2017-07-13 07:36
Partially solved so I will close it as there is a way around the issue. If I already have a connection opened with SSMS, requests from vs code work correctly. Issue probably due to a configuration specific to my company.

**Comment by rars** [comment] 2018-01-04 10:28
Hi, I have also encountered this issue. I’m using Dapper 1.50.2 and System.Data.SqlClient.SqlConnection 4.2.0.0 in a netcoreapp2.0 console application.

The call that is failing is making a stored procedure call that calls through to a linked sql server.

When run on windows it works fine, but running from Linux results in the anonymous logon error. If a manual call is made via ssms using the same service account then that makes the issue disappear from the Linux process until the process restarts, which sounds like the same workaround described above.

Any help/advice would be greatly appreciated. Thanks!

**Comment by rars** [comment] 2018-01-07 11:30
After more investigation I suspect the issue I described above may be an issue with the SqlClient. This describes a simple setup to reproduce the error. I have two SQL servers: SQLSERVERA, SQLSERVERB.

On SQLSERVERB:
```
USE MyDatabase;
GO
CREATE PROCEDURE usp_MySelectProc @Date DATE
AS
BEGIN
 SELECT ColA, ColB FROM dbo.MyTable WHERE Date = @Date;
END;
GO
```
On SQLSERVERA:
```
USE MyOtherDatabase;
GO
CREATE PROCEDURE usp_MyOtherProc @Date DATE
AS
BEGIN
  EXEC SQLSERVERB.MyDatabase.dbo.usp_MySelectProc @Date = @Date;
END;
GO
```

I have a netcoreapp2.0 console application that executes this proc using the Dapper library: `SQLSERVERA.MyOtherDatabase.dbo.usp_MyOtherProc`. That execution fails with the ANONYMOUS LOGON error when run on a RHEL flavour of Linux but does not error when run on Windows.

This netcoreapp2.0 is running as a user account X. If I create a Python script to use pyodbc from the same Linux box to execute the same procedure and run it as user X, then the procedure succeeds and returns data as expected. So it does not seem to be an issue with the SQL server setup or Kerberos setup on the Linux box. The issue seems to be in the way the library used by the netcoreapp2.0 app is making the request to execute the procedure.

I've encountered the exact same behaviour as described by @TechWatching in that making the call to SSMS in Windows using user account X while the Linux process is still running seems to cause some credential or connection to be cached/reused so that the next request made by the Linux process will succeed without the ANONYMOUS LOGON error.

This only affects executing stored procedures that go across linked servers. The Linux process can execute sprocs that only interact with databases on SQLSERVERA fine without error. So it seems to be some problem with delegation.

Please can you let me know if this issue will be looked at in the near future as this is a blocker for us going further with this?

**Comment by ah-** [comment] 2018-01-09 13:25
Had a quick look and it seems to be caused by a missing Delegate flag. The following fixes it, although I'm not 100% sure if this is the right place to set that flag:

```
diff --git a/src/Common/src/System/Net/ContextFlagsAdapterPal.Unix.cs b/src/Common/src/System/Net/ContextFlagsAdapterPal.Unix.cs
index 7e2f7a1..599bd4a 100644
--- a/src/Common/src/System/Net/ContextFlagsAdapterPal.Unix.cs
+++ b/src/Common/src/System/Net/ContextFlagsAdapterPal.Unix.cs
@@ -26,7 +26,8 @@ namespace System.Net
             new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_IDENTIFY_FLAG, ContextFlagsPal.InitIdentify),
             new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_MUTUAL_FLAG, ContextFlagsPal.MutualAuth),
             new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_REPLAY_FLAG, ContextFlagsPal.ReplayDetect),
-            new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_SEQUENCE_FLAG, ContextFlagsPal.SequenceDetect)
+            new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_SEQUENCE_FLAG, ContextFlagsPal.SequenceDetect),
+            new ContextFlagMapping(Interop.NetSecurityNative.GssFlags.GSS_C_DELEG_FLAG, ContextFlagsPal.Delegate)
         };


diff --git a/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs b/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs
index 64d832c..a93ff8a 100644
--- a/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs
+++ b/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs
@@ -105,6 +105,7 @@ namespace System.Data.SqlClient.SNI

             ContextFlagsPal requestedContextFlags = ContextFlagsPal.Connection
                 | ContextFlagsPal.Confidentiality
+                | ContextFlagsPal.Delegate
                 | ContextFlagsPal.MutualAuth;

             string serverSPN = System.Text.Encoding.UTF8.GetString(serverName);
```

**Comment by saurabh500** [comment] 2018-01-09 14:51
Cc @geleems please take a look at the recommendation.
Thanks @ah-

**Comment by saurabh500** [comment] 2018-01-09 18:44
cc @LotharOfTheHillPeople can you help with this issue as well? 
Can we have a sweep of the GSS flags that ODBC driver on unix uses for integrated auth and have similar parity in SqlClient? It will be good to have a list of these flags from MSSQL-ODBC driver.

**Comment by LotharOfTheHillPeople** [comment] 2018-01-10 20:03
From a brief scan of ODBC, it looks like it uses both GSS_C_MUTUAL_FLAG and GSS_C_DELEG_FLAG.

**Comment by saurabh500** [comment] 2018-01-10 20:05
Thanks @LotharOfTheHillPeople 
@ah- Do you want to send a PR with the change?

**Comment by ah-** [comment] 2018-01-10 20:07
Yes, will do tomorrow morning.

**Comment by saurabh500** [comment] 2018-01-10 20:08
Thanks

**Comment by roederja2** [comment] 2018-01-11 09:08
I wonder though why linked servers work from a Windows client even without the change to SNIProxy.cs - does the Windows implementation implicitly add the delegate flag?

**Comment by saurabh500** [comment] 2018-01-11 21:44
@roederja2 The windows version of sqlclient uses sni.dll whose implementation is not on Github. 
Its a component which handle the networking nuances of Sql Server. The same networking module has been reimplemented using Managed code for Linux.

**Comment by geleems** [comment] 2018-01-16 22:08
@ah- thanks for the fix.
The fix has just been merged to main branch.

**Closed** 2018-01-16 22:13 UTC
Labels: area-System.Data.SqlClient, question
