### ISSUE TITLE
MathTests.Pow test failing after recent coreclr change

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9053] opened 2016-06-02 03:44 UTC
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst/558/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/fedora23_debug_tst/167/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu16.04_debug_tst/347/consoleText
```
System.Tests.MathTests.Pow [FAIL]
      Assert+WrapperXunitException : File path: D:\j\workspace\fedora23_debu---1725fa63\src\System.Runtime.Extensions\tests\System\Math.cs. Line: 266
      ---- Assert.Equal() Failure
      Expected: 1
      Actual:   NaN
      Stack Trace:
            at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
            at Assert.Equal[T](T expected, T actual, String path, Int32 line)
            at System.Tests.MathTests.Pow()
         ----- Inner Stack Trace -----
            at Assert.Equal[T](T expected, T actual, String path, Int32 line)
```
I believe this was caused by https://github.com/dotnet/coreclr/pull/4847
cc: @tannergooding, @janvorli, @jkotas 

https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Runtime.Extensions/tests/System/Math.cs#L266

**Comment by tannergooding** [comment] 2016-06-02 04:32
@stephentoub, I understand the cause of failure.

`COMDouble::Pow` had a line removed which did roughly `if (IS_INFINITY(y) && (x == 1.0)) { return x; }`. The line was removed because MSVC is now producing the correct result.

However, `PAL_pow` was not updated accordingly. So it still has code that says roughly `if(IS_INFINITY(y) && (abs(x) == 1.0)) { return NAN; }`. This is causing non windows platforms to produce an incorrect result.

I am working on a fix and should have something up shortly.

**Comment by tannergooding** [comment] 2016-06-02 14:42
@stephentoub, I have a PR here: https://github.com/dotnet/corefx/pull/9065, which adds test coverage for areas which have custom handling in PAL but did not have tests covering them in the managed layer.

**Comment by tannergooding** [comment] 2016-06-02 18:32
@stephentoub, this should probably stay open until #9069 is merged (after CoreFX is consuming a CoreCLR build that includes https://github.com/dotnet/coreclr/pull/5399). That way the `[ActiveIssue]` attribute gets removed and the new tests covering the currently failing scenario are in.

**Closed** 2016-06-03 22:48 UTC
Labels: System.Runtime
