### ISSUE TITLE
[Request] Missing TryParse Method for System.Net.NetworkInformation.PhysicalAddress

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/corefx#31605] opened 2018-08-06 05:23 UTC
`System.Net.NetworkInformation.PhysicalAddress` currently only implement a `Parse` method. Many other classes and structs implement a `Parse `and a `TryParse` method. So it would be nice, when `PhysicalAddress` implement a `TryParse` method.

### Usage
```csharp

// usage for the currently supported formats
var parseOkayFormat1 = PhysicalAddress.TryParse("008041AEFD7E",      out var physicalAddress1);
var parseOkayFormat2 = PhysicalAddress.TryParse("00-80-41-AE-FD-7E", out var physicalAddress2);

// possible usage, when value formats are supported
var parseOkayFormat3 = PhysicalAddress.TryParse("008041-AEFD7E",     out var physicalAddress3);
var parseOkayFormat4 = PhysicalAddress.TryParse("0080.41AE.FD7E",    out var physicalAddress4);
var parseOkayFormat5 = PhysicalAddress.TryParse("00:80:41:AE:FD:7E", out var physicalAddress5);
```

### Proposed API
```csharp
namespace System.Net.NetworkInformation
{
    public class PhysicalAddress
    {
        public static bool TryParse(string addressToParse, out PhysicalAddress physicalAddress);
    }
}
```

### Things to notice
- Only two value formats are currently supported by the `Parse` method
- Only upper case values are currently supported by the `Parse` method
- Only full format values are currently supported by the `Parse` method

### Other Tickets for PhysicalAddress
#29740

**Comment by danmosemsft** [comment] 2018-08-06 07:43
Hello, please take a look at the API proposal and review process described in the documentation in this repo, and edit this issue to be in the format requested there.

**Comment by karelz** [comment] 2018-08-15 02:07
Duplicate of #29740

**Closed by karelz** 2018-08-15 02:07 UTC
Labels: api-suggestion, area-System.Net
