### ISSUE TITLE
JsonSerializer does not serialize fields

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/corefx#37936] opened 2019-05-24 19:23 UTC
So far JsonSerializer only supports serialization of properties. Practically every other serializer can also serialize fields. Is this feature on the roadmap?

**Comment by Anipik** [comment] 2019-05-24 20:04
cc @steveharter @ahsonkhan

**Comment by ahsonkhan** [comment] 2019-05-24 22:07
Duplicate of https://github.com/dotnet/corefx/issues/36505

>  Is this feature on the roadmap?

Yes it is, but for vNext.

**Closed by ahsonkhan** 2019-05-24 22:07 UTC
Labels: area-System.Text.Json
