### ISSUE TITLE
Make immutable collections serializable.

### ISSUE THREAD

**Issue by Scythen** [dotnet/corefx#23844] opened 2017-09-07 05:07 UTC
All of the Immutable collections should support serialization. In particular they should support Data Contract Serialization so that they can be used with Service Fabric and other systems that require serialization.

Hope this isn't a duplicate but I didn't see any other similar requests.

**Comment by ViktorHofer** [comment] 2017-09-07 11:30
@shmao @zhenlan to fulfill this request would these types needed to be marked with SerializableAttribute (https://msdn.microsoft.com/de-de/library/system.serializableattribute(v=vs.110).aspx) similar to what binary formatter requires?

cc @danmosemsft @stephentoub

**Comment by sharwell** [comment] 2017-09-07 11:59
This appears to be a duplicate of #1272.

**Comment by jkotas** [comment] 2017-09-07 12:06
Duplicate of #1272

**Closed by jkotas** 2017-09-07 12:06 UTC
Labels: area-Serialization
