### ISSUE TITLE
Timeout_SetTo60AndGetResponseFromServerWhichTakes40_Success failed on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8061] opened 2016-04-25 18:15 UTC
"The handle is invalid"
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/12/consoleText
```
System.Net.Http.Functional.Tests.HttpClientTest.Timeout_SetTo60AndGetResponseFromServerWhichTakes40_Success [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.Http.WinHttpException : The handle is invalid
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           d:\j\workspace\outerloop_win---097a300f\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           d:\j\workspace\outerloop_win---097a300f\src\System.Net.Http\tests\FunctionalTests\HttpClientTest.cs(389,0): at System.Net.Http.Functional.Tests.HttpClientTest.Timeout_SetTo60AndGetResponseFromServerWhichTakes40_Success()
           ----- Inner Stack Trace -----
           d:\j\workspace\outerloop_win---097a300f\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1360,0): at System.Net.Http.WinHttpHandler.InternalReceiveResponseHeadersAsync(WinHttpRequestState state)
           d:\j\workspace\outerloop_win---097a300f\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(850,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__102.MoveNext()
```

**Comment by stephentoub** [comment] 2016-04-25 20:25
Same "The handle is invalid" error, but for a different test:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/438
``` System.Net.Http.Functional.Tests.ResponseStreamTest.ReadAsStreamAsync_ValidServerResponse_Success(transferType: None, transferError: None) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.Http.WinHttpException : The handle is invalid
        Stack Trace:
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs(130,0): at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamHelper>d__8.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs(121,0): at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_ValidServerResponse_Success>d__7.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(1360,0): at System.Net.Http.WinHttpHandler.InternalReceiveResponseHeadersAsync(WinHttpRequestState state)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs(850,0): at System.Net.Http.WinHttpHandler.<StartRequest>d__102.MoveNext()
```

**Comment by davidsh** [comment] 2016-05-26 19:25
Moving post RTM.

**Comment by davidsh** [comment] 2016-06-17 16:38
Closing this since it is a dupe of the root issue in #9228

**Closed by davidsh** 2016-06-17 16:38 UTC
Labels: System.Net
