### ISSUE TITLE
ReaderWriterLockSlim.AcquireWriterLock timing out does not wake up waiting readers in uapaot

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#21585] opened 2017-06-26 22:30 UTC
related issue: #3364

cc: @kouvel 

corefx test ReleaseReadersWhenWaitingWriterTimesOut is hanging in uapaot test runs causing our ARM machines (which are physical machines) to hang forever. It's very possible that this issue is simply some change that was made to coreclr that fixed this and needs to be mirrored to corert. This issue is to track the work of fixing and enabling that test once its fixed.

**Comment by danmosemsft** [comment] 2017-06-26 23:03
@kouvel @AntonLapounov can one of you please tke a look?

I thought of https://github.com/dotnet/corert/commit/78fae17f5434839a8720603973ff53f27e27f916 but that is already in corert, obviously.

**Comment by kouvel** [comment] 2017-06-27 03:41
Yes I had made that change, there may be a duplicate of the code in corert that is not fixed. I'll take a look.

**Closed** 2017-06-29 20:12 UTC
Labels: area-System.Threading, os-windows-uwp, test-run-uwp-ilc
