### ISSUE TITLE
SmtpClient.Send crashes with Segmentation fault

### ISSUE THREAD

**Issue by abelykh0** [dotnet/corefx#39732] opened 2019-07-24 16:08 UTC
The example below crashes with Segmentation fault on Linux. The same code works fine (i.e. throws `System.Net.Mail.SmtpException`) in 2.2 or preview 6.

```csharp
using System.Net.Mail;
namespace ConsoleApp31
{
    class Program
    {
        static void Main(string[] args)
        {
            MailMessage message = new MailMessage(new MailAddress("a@example.com"), new MailAddress("a@example.com"));
            SmtpClient client = new SmtpClient("smtp.example.com");
            client.Send(message);
        }
    }
}
```

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     opensuse-leap
 OS Version:  15.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.2.301 [/usr/share/dotnet/sdk]
  3.0.100-preview7-012821 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]```

**Comment by danmosemsft** [comment] 2019-07-24 17:39
@abelykh0 is it possible for you to get a stack backtrace?

**Comment by abelykh0** [comment] 2019-07-24 18:49
Please let me know how to do it, I will provide it.

**Comment by abelykh0** [comment] 2019-07-24 19:12
I tried to run the .exe file and surprisingly, it runs correctly, only `dotnet` command fails.

```
> ./ConsoleApp31.exe
Unhandled exception. System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at ConsoleApp31.Program.Main(String[] args) in C:\Users\andreyb\source\repos\ConsoleApp31\ConsoleApp31\Program.cs:lin
e 10
> dotnet exec ConsoleApp31.dll
Segmentation fault (core dumped)
```

**Comment by scalablecory** [comment] 2019-07-24 19:23
Is "smtp.example.com" a valid smtp server?

**Comment by abelykh0** [comment] 2019-07-24 19:39
No

**Comment by abelykh0** [comment] 2019-07-24 19:40
I tried this on Red Hat Linux, it works fine. Maybe it is because openSUSE is on WSL. However, 2.2 or preview 6 works fine on it.

**Comment by abelykh0** [comment] 2019-07-24 19:44
This is what I get on Red Hat:
```
>dotnet exec ConsoleApp31.dll
Unhandled exception. System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at ConsoleApp31.Program.Main(String[] args) in C:\Users\andreyb\source\repos\ConsoleApp31\ConsoleApp31\Program.cs:line 11
Aborted (core dumped)
```

This is what I get on openSUSE:
```
>./ConsoleApp31
Segmentation fault (core dumped)
```

**Comment by karelz** [comment] 2019-07-26 18:05
@scalablecory can you please dig deeper into it?

**Comment by wfurt** [comment] 2019-07-26 18:22
I did quick try and I'm not able to reproduce it using OpenSuse container. 

```
9cfb460ed314:/tmp/aa # /p7/dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     opensuse-leap
 OS Version:  15.1
 OS Platform: Linux

9cfb460ed314:/tmp/aa # /p7/dotnet run
Unhandled exception. System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at ConsoleApp31.Program.Main(String[] args) in /tmp/aa/Program.cs:line 10
```

**Comment by abelykh0** [comment] 2019-07-26 19:09
What about WSL?

**Comment by abelykh0** [comment] 2019-07-29 17:16
I updated to Windows 10 Enterprise, version 1903 and the issue went away. Feel free to close it, it is no longer relevant to me.

**Comment by scalablecory** [comment] 2019-07-31 00:57
Thanks for the report @abelykh0. I'm reproing this on Ubuntu WSL.

```
cory@conelso1:~/39732-smtp-segfault$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
cory@conelso1:~/39732-smtp-segfault$ ./bin/Debug/netcoreapp3.0/39732-smtp-segfault
sending.
Segmentation fault (core dumped)
cory@conelso1:~/39732-smtp-segfault$ dotnet ./bin/Debug/netcoreapp3.0/39732-smtp-segfault.dll
sending.
Segmentation fault (core dumped)
```

**Comment by scalablecory** [comment] 2019-07-31 01:39
Here's the bug:

https://github.com/dotnet/corefx/blob/175c4b7467f4da173c732f9aaf95882b3c426665/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs#L100-L104

If `_tcpClient.Connect()` fails, `_networkStream` is never assigned. Then, during `Abort()`, we attempt to `_networkStream.Dispose()` which throws a `NullReferenceException`.

https://github.com/dotnet/corefx/blob/175c4b7467f4da173c732f9aaf95882b3c426665/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs#L172-L187

Except there seems to be an issue in CLR re: SIGSEGV -&gt; `NullReferenceException` handling that ends with a segfault. Tracking that issue in https://github.com/dotnet/coreclr/issues/25945.

**Comment by karelz** [comment] 2019-07-31 17:28
Duplicate https://github.com/dotnet/coreclr/issues/25945

**Comment by karelz** [comment] 2019-07-31 17:29
The SegFault is dupe of the above.
@scalablecory please file new issue for the remaining unnecessary NullRefException in SmtpClient.

**Closed by karelz** 2019-07-31 17:28 UTC
Labels: area-System.Net, os-linux
