### ISSUE TITLE
AV from GenFacades on Windows outer loop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5508] opened 2016-01-19 00:04 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_release/61/consoleFull
```
11:32:56   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
11:32:56      at Microsoft.Cci.ISymUnmanagedWriter2.Close()
11:32:56      at Microsoft.Cci.PdbWriter.Dispose()
11:32:56      at GenFacades.Program.OutputFacadeToFile(String facadePath, HostEnvironment seedHost, Assembly facade, IAssembly contract, String pdbLocation)
11:32:56      at GenFacades.Program.Main(String[] args)
```

**Comment by weshaggard** [comment] 2016-01-19 05:04
I would not be surprised if this is because of a race condition. I've got changes I'm working on that should eliminate most if not all of the race conditions caused by projects being build with different global properties. It is at https://github.com/weshaggard/corefx/tree/ScriptToFindConflictingProjectConfigurations, however I need an update to BuildTools (https://github.com/dotnet/buildtools/pull/400) before I can submit the PR to corefx. I will try to do that tomorrow.

**Comment by stephentoub** [comment] 2016-01-23 13:09
Another GenFacades AV:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_bld_prtest/1316/console

**Comment by mellinoe** [comment] 2016-04-18 22:04
I'm going to close this because it was most likely due to a race condition at the time of these runs. The PdbWriter was probably trying to write to a file that something else was also using, or something of that nature. We made various fixes for races in the build and have a logger now.

**Closed by mellinoe** 2016-04-18 22:04 UTC
Labels: Infrastructure
