### ISSUE TITLE
Rollforward from .NET Core 2.0 to 2.1 throws with MissingMethodException when System.Memory package is referenced

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#29298] opened 2018-04-24 04:59 UTC
**Conditions**

An application that is:
 - compiled against netcoreapp2.0
 - has a package reference to System.Memory (v4.5.0-rc1-26423-06)
 - runs on a machine **without** Microsoft.NETCore.App 2.0.x installed, but has a Microsoft.NETCore.App 2.1.0 version... 

**Result**
The application
 - rolls to execute on Microsoft.NETCore.App 2.1 ✅ , but
 - some System.IO apis throw MissingMethodException :x:

```
System.MissingMethodException: Method not found: '!!0 ByRef System.Runtime.InteropServices.MemoryMarshal.GetReference(System.Span`1<!!0>)'.
   at Interop.Sys.LStat(ReadOnlySpan`1 path, FileStatus& output)
   at System.IO.FileStatus.Refresh(ReadOnlySpan`1 path)
   at System.IO.FileStatus.EnsureStatInitialized(ReadOnlySpan`1 path, Boolean continueOnError)
   at System.IO.FileStatus.GetAttributes(ReadOnlySpan`1 path, ReadOnlySpan`1 fileName)
   at System.IO.FileSystemInfo.get_Attributes()
   at System.IO.FileInfo.get_Length()
```

**Repro**
In a directory, create 3 files, `Dockerfile`, `program.cs`, and `test.csproj` and run `docker build .`:

```Dockerfile
FROM microsoft/dotnet:2.0-sdk as builder
WORKDIR /code
COPY Program.cs .
COPY test.csproj .
RUN dotnet publish -o pub/

FROM microsoft/dotnet-nightly:2.1-runtime
WORKDIR /app
COPY --from=builder /code/pub .
RUN dotnet test.dll
```
```xml
<!-- test.csproj-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>7.1</LangVersion>
    <RestoreSources>
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json;
      https://api.nuget.org/v3/index.json;
    </RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.0-rc1-26423-06" />
  </ItemGroup>

</Project>
```
```csharp
// Program.cs
using System;
using System.IO;

class Program
{
    public static int Main(string[] args)
    {
        try
        {
            var path = Path.Combine(AppContext.BaseDirectory, "test.txt");
            File.WriteAllText(path, "hello");
            var fileinfo = new FileInfo(path);
            Console.WriteLine("System.IO.File.Exists = " + File.Exists(path));
            Console.WriteLine("System.IO.FileInfo.Exists = " + fileinfo.Exists);
            Console.WriteLine("System.IO.FileInfo.FullName = " + fileinfo.FullName);
            Console.WriteLine("System.IO.FileInfo.Length = " + fileinfo.Length);
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.ToString());
            return 1;
        }
    }
}
```

**Details**
Inside the container:
```
dotnet --info

Host (useful for support):
  Version: 2.1.0-rc1-26419-02
  Commit:  515f580aa0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.0-rc1-26419-02 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by natemcmaster** [comment] 2018-04-24 05:09
cc @Petermarcu @ahsonkhan @stephentoub

**Comment by ahsonkhan** [comment] 2018-04-24 09:42
I believe the root cause of this issue is the same as #29032. 

We are waiting for an SDK build with this change: https://github.com/dotnet/sdk/pull/2118 and a fix for this: https://github.com/dotnet/corefx/issues/29218 (specifically for master).

cc @ericstj, @steveharter

**Comment by natemcmaster** [comment] 2018-04-24 14:10
So, if I understand right, the fix requires that the deps.json file specify assembly versions. Does this means users will need to recompile with a new SDK? Or that just the shared framework needs to be compiled with this new SDK? If it is the former or both, what happens if someone doesn’t recompile (or can’t recompile) their app? I’m thinking about applications running on shared servers or hosting environments, where rollforward may start happening months after the application was created.

**Comment by ericstj** [comment] 2018-04-24 15:43
The shared framework needs the versions, so core-setup needs to have the SDK change.  I believe @dsplaisted and @steveharter we’re trying to get that in.  You can mock up the changes in the shared framework deps to test this.

App doesn’t need to be rebuilt, only if you want app to win does it need to rebuild.

**Comment by ericstj** [comment] 2018-04-24 17:29
Duping this to https://github.com/dotnet/corefx/issues/29032 as we don't need two issues. https://github.com/dotnet/corefx/issues/29032 remains open for verification purposes.

**Closed by ericstj** 2018-04-24 17:29 UTC
Labels: area-System.Memory, blocking-release, packaging
