### ISSUE TITLE
Testing of .NET Core final output

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#18083] opened 2017-04-07 18:18 UTC
Today we have a gap around what we test.  We test individual output from a single machine but never really test the final thing we're shipping after we bring all the stuff together.  Folks upstack do this but not to the level that we would.

We should at a minimum test the following things on a final MS.NETCore.App + shared framework out of core-setup.
1. API Compat between MS.NC.A and shared framework - all rids. 
[djm: runtime assets that are included in the CLI ... similar to apicompat does in the build at leaf level, but for non-Windows, and strictly limited to MS.NC.A]
2. API Compat between MS.NC.A and runtime packages - all rids. 
[djm: runtime assets that you get when publishing]
3. API Compat between Netstandard.Library and MS.NC.A.
[djm: similar to what we do in the shims\apicompat.proj, but strictly limited to MS.NC.A]
4. API Compat between MS.NC.A and last stable version of the same. - ref assys (eg: 2.0 vs 1.1)
[djm: this may not have been done before]
5. API Compat between shared framework and last stable version of the same - all rids.
[djm: as above but for runtime -- this may not be easy to interpret, or relevant (?)]
6. API Compat between runtime packages and last stable version of the same - all rids.
[djm: as for 5 but runtime packages - what you get when publishing]
7. CoreFx test compilation against MS.NC.A (and other stable packages) and execution against shared framework (and runtime packages) - all rids.
[djm: will show any tests that depend on random binaries built by corefx that aren't in shared framework; also a sanity check of the real product]
8. Check that necessary baselines built by shims\apicompat.proj are clean. (This does not build by default.)
[djm: sanity check]

In all cases "all rids" mean all platforms we support and care to test, regardless of the granularity of our actual assets.

In all cases MS.NC.A and runtime packages indicate the final packages which we publish.

In all cases shared framework indicates the final installer/zip that we publish.

/cc @weshaggard

**Comment by karelz** [comment] 2017-04-07 19:07
Should we track it for 2.0?

cc @danmosemsft (should we add it to your list for 2.0 shipping?)

**Comment by danmosemsft** [comment] 2017-04-07 20:27
I put it on our list. @ericstj is this something you have cycles to do?

**Comment by ericstj** [comment] 2017-04-07 23:27
Not at the moment.  I don't even know where this would go, but its something we need to do.

At the very least we should do it manually for the release.  Ideally this becomes some test infrastructure that runs regularly.

I'm imagining that its at least a week of work, maybe more.

**Comment by danmosemsft** [comment] 2017-04-17 20:30
@weshaggard are you planning to do any of this?

**Comment by weshaggard** [comment] 2017-04-17 23:15
I will be doing some diffs between NS and NETCore and some diffs between NETCore1.1 and NETCore2.0 but I wasn't planning to run all the tests I'm primarily looking at API and assembly differences to make sure they are understood and expected.

**Comment by karelz** [comment] 2017-04-18 00:43
What would be best way to do such one off run? Does anyone have required knowledge in infra? (e.g. Jose, EricM.)

**Comment by weshaggard** [comment] 2017-04-18 16:36
We don't have the specific infra to do such a run it will require some deeper knowledge of the system to do some tweaks and make it work in this manor. I think both @mellinoe and @joperezr would be able to do it.

**Comment by karelz** [comment] 2017-04-18 16:43
@mellinoe I think you're pretty booked for next 3 weeks (infra area + perf), aren't you? @joperezr do you have free cycles to help here (assuming @danmosemsft is fine with that).

**Comment by danmosemsft** [comment] 2017-04-18 16:45
I think it makes sense for @joperezr to grab this when he's back May 1st.

**Comment by joperezr** [comment] 2017-05-01 23:35
after chatting offline with @ericstj looks like a roughly costing for this would be around 2 days of work in case we decide to do it as a one off thing, and probably around a week if we want to automate some parts of it or all of it and have official builds that check this. If we decide to do the one-off approach, @ericstj and I agreed that it would be better if we do it closer to release as opposed to doing it now. @weshaggard @danmosemsft @ericstj what are your thoughts around which way to go?

**Comment by weshaggard** [comment] 2017-05-01 23:58
I would love to see this actually automated in some way as it would help us catch regressions sooner, but I understand it is not trivial and requires a higher level repo build to attempt so I'm OK with the status quo of doing it manually closer to release.

**Comment by danmosemsft** [comment] 2017-05-02 00:05
@joperezr If yo'ure confident it's about a week then I'm fine with automating it.

**Comment by karelz** [comment] 2017-05-25 22:51
Reopening to track port to rel/2.0.0

**Comment by joperezr** [comment] 2017-05-25 23:30
Actually, I discussed this with @weshaggard offline, and given that you can pass in the version of the shared framework that you want to test, then we said that if this doesn't make it to rel/2.0.0 it's not the end of the world, since we could still do the validation by simply passing in a rel/2.0.0 shared framework version. That is why I thought that closing this would be fine, but if we want to keep pushing into getting it to rel branch, I'm fine with that too

**Comment by weshaggard** [comment] 2017-05-26 00:07
I think we should at least keep it open until we do a manual run against the 2.0.0 builds. This is kind of a final testing verification step.

**Comment by karelz** [comment] 2017-05-26 00:46
I reopened it, because the milestone said 2.0, yet it was not ported to rel/2.0.0 branch. If that's ok, just change the milestone and close it.
For manual verification feel free to open another tracking 2.0 issue in such case.

Did you guys think about 2.0.x servicing branches? If we will need similar things there, won't this change be useful?
If it will be useful, we can get it in post-RTM, but we want it in rel/2.0.0 branch eventually.
Also note that 2.0.x servicing may be more active than 1.x servicing branches based on the high-pri feedback we may start getting (e.g. System.DirectoryServices and System.Drawing was promised to ship in summer).

**Comment by danmosemsft** [comment] 2017-06-30 16:41
@ericstj I guess now is a good time to re-run @joperezr analysis (ie., it's final bits) or should we wait a little longer?

**Comment by ericstj** [comment] 2017-06-30 17:01
Do it now and once we have a stable build.

**Comment by joperezr** [comment] 2017-06-30 17:05
Sounds good, I'll do this later today and report back with the results.

**Comment by joperezr** [comment] 2017-06-30 18:47
just ran the validation against the following versions:
```
Microsoft.NETCore.App -> 2.0.0-preview3-25428-01
CoreFx OOB packages -> 4.4.0-preview3-25426-02
```
All ApiCompat checks are passing, and except  for one System.Diagnostics.DiagnosticSource test all of the corefx tests are passing which is good news. I'll take a closer look at that test and figure out why is it failing.

**Comment by danmosemsft** [comment] 2017-07-20 23:55
@joperezr any update on this or remaining concerns?

**Comment by joperezr** [comment] 2017-07-21 16:27
last time I checked, everything was looking fine, but I'm happy to trigger a new validation run. In fact, Now that I have some spare time I'll try to set this up as part of an official build leg and have it running daily.

**Comment by weshaggard** [comment] 2017-07-24 16:45
@joperezr can you do a final validation based on our stable packages?

**Comment by joperezr** [comment] 2017-07-24 17:46
Sure I'll do that

**Comment by joperezr** [comment] 2017-07-27 16:22
Results of this run are here: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170726.42

Closing this issue as I feel it has served its purpose.

**Closed by joperezr** 2017-07-27 16:22 UTC
Labels: area-Infrastructure, blocking-release, enhancement

**Comment by weshaggard** [comment] 2017-07-27 17:24
Thanks @joperezr
