### ISSUE TITLE
Regression: HTTPS defaults to older TLS version for Win7

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#28733] opened 2018-04-02 21:08 UTC
On Win7/2008R2 the new SocketsHttpHandler uses older defaults for TLS versions than the WinHttpHandler it's replacing. SocketsHttpHandler defaults to TLS 1.0 while WinHttpHandler supports TLS 1.2, 1.1, and 1.0. This is a regression for updating apps.

ASP.NET Core's Kestrel server defaults to TLS 1.1 and 1.2 so the new client can't connect to it using the default settings.

Example: Github.com as removed TLS 1.0 support
```            Environment.SetEnvironmentVariable("DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER", "true");
            var handler = new HttpClientHandler();
            // handler.SslProtocols = SslProtocols.Tls12; // Workaround
            var client = new HttpClient(handler);
            var response = await client.GetAsync("https://github.com/");
            Console.WriteLine(response);
```

Workaround: Override the protocol versions on the client.

Found in ASP.NET Core's WebSocket Autobahn tests

@geoffkizer @karelz

**Comment by davidsh** [comment] 2018-04-02 21:38
This is interesting.  The default for any TLS/SSL protocol in .NET Core should be this [`SecurityProtocolType.SystemDefault`](https://msdn.microsoft.com/en-us/library/system.net.securityprotocoltype(v=vs.110).aspx)

which means to use OS defaults.

**Comment by davidsh** [comment] 2018-04-02 21:41
And according to this:
https://support.microsoft.com/en-us/help/3154520/support-for-tls-system-default-versions-included-in-the-net-framework

The OS default would not include TLS 1.1 nor 1.2 for Windows 7 SP1 and Windows Server 2008 R2 SP1.

**Comment by davidsh** [comment] 2018-04-02 21:44
So, while our best-practice coding pattern is not to hard-code any TLS version, it seems like the use of 'SystemDefault' on Windows 7/Windows Server 2008 R2 is resulting is only TLS 1.0 being part of the set and  excluding TLS 1.1, 1.2.

cc: @morganbr

**Comment by karelz** [comment] 2018-04-02 22:19
Hmm, does it mean that WinHttp on Win7 has different defaults than Schannel which we use? I assume we just tell OS APIs "use your default", right?

**Comment by Tratcher** [comment] 2018-04-02 22:33
https://github.com/dotnet/corefx/blob/3cc6fda0c6abe76eea222c165ebdf816e83df564/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L928-L929

https://github.com/dotnet/corefx/blob/3cc6fda0c6abe76eea222c165ebdf816e83df564/src/Common/src/System/Net/SecurityProtocol.cs#L11

**Comment by davidsh** [comment] 2018-04-02 22:40
@Tratcher correct.  WinHTTP doesn't have any concept of using 'SystemDefault' TLS versions.

@karelz and I discussed offline.  We think the right fix for this app-compat regression in handler behavior is to do something like in SocketsHttpHandler:

```c#
if (RunningOnWin7OrWindowsServer2008R2 && _sslProtocols == SslProtocols.None)
{
    _sslProtocols = SecurityProtocol.DefaultSecurityProtocols; // this is TLS1.0, 1.1, 1.2
}
```

**Comment by stephentoub** [comment] 2018-04-03 20:11
Do we know why the default is Off for 1.1 and 1.2 on Win7/2008R2?

I'm wondering if rather than doing this in SocketsHttpHandler, we should do it in SslStream.

**Comment by davidsh** [comment] 2018-04-03 20:15
>Do we know why the default is Off for 1.1 and 1.2 on Win7/2008R2?

At the time of release of Win7/Win2K8R2, TLS 1.1 and 1.2 weren't supported.  Servicing updates of these OS versions added the support.  But the use of the 'SystemDefaultTlsVersions' setting didn't include them as default since many older apps might break if the defaults were changed like that. We can follow-up with the SCHANNEL team internally if you need more info.

>I'm wondering if rather than doing this in SocketsHttpHandler, we should do it in SslStream.

That is another option.  We could use the same logic and essentially "override" SystemDefaultTlsVersions setting for SslStream if SslProtocols.None is used on Win7/Win2K8R2.

**Closed** 2018-04-04 16:59 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, bug, tenet-compatibility
