### ISSUE TITLE
HttpWebResponse.Close acts differently from traditional framework

### ISSUE THREAD

**Issue by LukasBendikas** [dotnet/corefx#30605] opened 2018-06-22 14:30 UTC
Apologies if I'm in the wrong place.

I have an old project which uses HttpWebRequest/HttpWebResponse quite a lot and am targeting classic .NET v4.6.1 and .NET core v2.0.

During code migration to Net Core I'm seeing code break which uses HttpWebResponse after Close() was called since apparently Close == Dispose in Net Core. In traditional .NET this is not the case and my code relies on HttpWebResponse data after calling Close - for stuff like response logging, manual redirect logic, etc.

Technically I could delay Close until after I'm done with accessing the object's properties but that would require some refactoring as I'm passing the object to quite a bit modules in my code. Also some of my code relies on Close to be called for the next request to work properly.

Is this a bug or intended to be different? What is the recommended approach here to have code working for both net core and classic .net?

**Comment by karelz** [comment] 2018-06-23 01:31
In general, we conside HttpWebRequest legacy API and we recommend people to consider using HttpClient instead.
That said, we introduced HttpWebRequest for compat with Desktop, so we may look into it to see if there is easy way to fix it. If there are more customers affected, we will prioritize it even higher.

**Comment by karelz** [comment] 2018-07-03 01:32
@LukasBendikas any luck?

**Comment by LukasBendikas** [comment] 2018-07-03 12:20
@karelz same thing with Core 2.1

I created this repo to illustrate the issue: https://github.com/LukasBendikas/core-vs-classic-http-test

**Comment by davidsh** [comment] 2018-07-11 22:40
>Is this a bug or intended to be different? What is the recommended approach here to have code working for both net core and classic .net?

Related issue: #18851.

This is a difference between .NET Framework and .NET Core.

**Comment by wfurt** [comment] 2018-09-20 22:16
should we close this since refereed #18851 was closed as well? 
It seems like we decided that HttpWebResponse should not be used after it is closed.

**Comment by karelz** [comment] 2018-09-20 23:32
Agreed

Duplicate of #18851

**Closed by karelz** 2018-09-20 23:32 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
