### ISSUE TITLE
Fix ApiCompat issues for System.Appcontext

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#6936] opened 2016-03-15 23:21 UTC
Remove ApiCompatBaseline.net462.txt once errors mentioned in it are resolved.

**Comment by venkat-raman251** [comment] 2016-03-28 08:57
MembersMustExist : Member 'System.AppContext.TargetFrameworkName.get()' does not exist in the implementation but it does exist in the contract.

The above types do not match between the contracts and the impl.

**Comment by venkat-raman251** [comment] 2016-03-28 09:06
@weshaggard : Who is the owner of system.appcontext that i can assign this bug to?

**Comment by weshaggard** [comment] 2016-05-13 19:33
We have the following compat issues after the recent run I did https://github.com/dotnet/corefx/pull/8513

```
MembersMustExist : Member 'System.AppContext.TargetFrameworkName.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.AppContext.GetData(System.String)' does not exist in the implementation but it does exist in the contract.
```

@AlexGhiondea Are these in net462? If so we should get the targeting pack we are using to validate these updated. If not then we need to move this to a later net463 or so version in the package.

**Comment by AlexGhiondea** [comment] 2016-05-13 19:36
These are in 4.6.2. I will update the targeting pack for 4.6.2

**Comment by joshfree** [comment] 2016-05-25 00:43
@tarekgh could you please move this to a .NET 4.6x bug?

**Comment by AlexGhiondea** [comment] 2016-05-25 01:08
They are actually not in 4.6.2. I updated the AppContext library to support 1.6 with the new contract.

I think we can close this issue.

**Comment by tarekgh** [comment] 2016-05-25 01:09
@joshfree I believe we should have some change (at least updating the baseline of the tool). I'll follow up with @AlexGhiondea to see if we can just close this issue and track it on TFS

**Comment by tarekgh** [comment] 2016-05-25 01:16
@AlexGhiondea do we need to update the tool baseline file?

**Comment by AlexGhiondea** [comment] 2016-05-25 01:17
@tarekgh I can't remember if my change updates the baseline file. If it does not, then I will do that against this issue.

**Comment by joshfree** [comment] 2016-05-25 01:19
Thanks.  @tarekgh and @AlexGhiondea

**Comment by AlexGhiondea** [comment] 2016-05-25 03:17
@joshfree @tarekgh -- it looks like we cannot yet remove the baseline file. The 2 APIs currently in the baseline were introduced in 4.6.3 and we don't yet have a targeting pack for 4.6.3. Once we have it, we can remove the baseline file.

**Comment by karelz** [comment] 2016-11-16 21:38
Dupe of #8515

**Closed by karelz** 2016-11-16 21:38 UTC
Labels: area-System.AppContext, test bug
