### ISSUE TITLE
Uri.Authority does not follow RFC 3986

### ISSUE THREAD

**Issue by Xeeynamo** [dotnet/corefx#34472] opened 2019-01-09 17:33 UTC
According to RFC 3986 (https://tools.ietf.org/html/rfc3986) paragraph 3.2, the Authority of a URI is composed by 

> [ userinfo "@" ] host [ ":" port ]

. But both .Net Framework and .Net Core returns only 

> host [ ":" port ]

ignoring the userinfo. I don't think that's the expected behaviour, unless it was intentional. 

`        [Theory]`
`        [InlineData("", "scheme:path")]`
`        [InlineData("host", "scheme://host")]`
`        [InlineData("host:12345", "scheme://host:12345")]`
`        [InlineData("userinfo@host:12345", "scheme://userinfo@host:12345")] // FAILS!`
`        public void AuthorityTest(string expected, string strUri)`
`        {`
`            Assert.Equal(expected, new Uri(strUri).Authority);`
`        }`

**Comment by davidsh** [comment] 2019-01-09 17:55
@rmkerr

**Comment by davidsh** [comment] 2019-01-09 17:56
>. But both .Net Framework and .Net Core returns only host [ ":" port ]
ignoring the userinfo. I don't think that's the expected behaviour, unless it was intentional.

Yes, it was intentional.  System.Uri in general doesn't support the username/password information because it is considered an insecure way of passing credential information.

**Comment by rmkerr** [comment] 2019-01-09 18:23
What David said is accurate. This is by-design, and the behavior is described in our documentation:

>Gets the Domain Name System (DNS) host name or IP address and the port number for a server.

While `Authority` as described in the spec does contain userinfo, it's much more common for users to need just the host and port. If you do need to include userinfo, the best approach is probably to use [GetComponents](https://docs.microsoft.com/en-us/dotnet/api/system.uri.getcomponents?view=netcore-2.1)

I'm going to close this, but feel free to comment if you have questions, or re-open if you feel strongly that this is an issue that should be revisited.

**Closed by rmkerr** 2019-01-09 18:23 UTC
Labels: area-System.Net
