### ISSUE TITLE
HttpClient with unencrypted HTTP/2

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#36462] opened 2019-03-28 20:47 UTC
I am not able to get HttpClient to work with HTTP/2 without encryption.

https://http2.github.io/faq/#does-http2-require-encryption

Does HttpClient support this scenario? Will it support this scenario in .NET Core 3.0?

**Comment by davidsh** [comment] 2019-03-28 20:50
Duplicate of #31338.

It is unlikely for .NET Core 3.0.

**Closed** 2019-03-28 20:53 UTC
Labels: area-System.Net.Http
