### ISSUE TITLE
no way to use proxy for connected service

### ISSUE THREAD

**Issue by dmnk** [dotnet/corefx#34255] opened 2018-12-27 08:59 UTC
Environment: 
- .net Core SDK 2.2.101
- IIS 10.0 on Win 2016 Server
- VS Studio 2019 16.0.0 Preview 1.1

I've tried pretty everything mentioned on github / stack-overflow, and more through connected debugging, but still failed to make dot net core use a proxy for an outbound connection to a connected service.

altered version of: https://stackoverflow.com/questions/17968307/how-to-set-proxy-credentials-to-specific-wcf-client
```C#
void SetProxySettings<TChannel>(ClientBase<TChannel> client,
            bool useProxy, string address, int port, string login, string password)
            where TChannel : class
        {
            if (!useProxy) return;
            var b = client.Endpoint.Binding as BasicHttpBinding;

            var b_core = client.Endpoint.Binding as System.ServiceModel.Channels.CustomBinding;
            if (b_core != null)
            {
                var element = b_core.Elements[1] as System.ServiceModel.Channels.HttpsTransportBindingElement; //
                element.ProxyAddress = new Uri(string.Format("http://{0}:{1}", address, port));
                return;
            }

            // further non modified stuff from SO solution
        }
```
But the customBindings proxyAddress doesn't seem to do anything.

I've further tried to deploy the api project to an IIS, i guess in "in-process-hosting-mode", but essentially just followed the guide at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2 and deployed from VS 2019 beta via "file-system-deployment" and "framework-dependent deployment" (which i guess - means in-process hosting).

The applications web.config has a section which should set the proxy, but it seems that this part is ignored as well:
```xml
    <system.net>
        <defaultProxy>
            <proxy proxyaddress="http://proxy.mydomain.org:8080" usesystemdefault="false" />
        </defaultProxy>
    </system.net>
</configuration>
```

Is there any - ideally platform-independent - way, to tell the framework which proxy to use for a connected service?

**Comment by davidsh** [comment] 2018-12-27 15:56
If you're using .NET Core, it doesn't use app.config/web.config settings. 

You can specify a proxy with HttpClient like this:

```c#
var handler = new HttpClientHandler();
handler.Proxy = new WebProxy("http://proxy.mydomain.org:8080");
var client = new HttpClient(handler);

// Send requests.
HttpResponseMessage response = await client.GetAsync("http://www.example.com");

// ...
```

The example above assume you are using HttpClient directly.  The example above also only works for non-authenticating proxies.  You will need additional code to pass credentials for the proxy.

**Comment by dmnk** [comment] 2018-12-27 18:10
I'm using a connected service as explained at https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide

No way to define a HttpClientHandler, as thats part of the generated proxy class. The problem is that it utilizes the CustomBinding, which doesn't seem to offer a way to inject a proxy.

**Comment by karelz** [comment] 2018-12-27 21:41
@dmnk can you please check in WCF repo that there is indeed no way around it?
It may be another +1 on the ask to provide API to set proxy globally in .NET Core process. It is something we're tracking for 3.0.

**Comment by dmnk** [comment] 2018-12-28 07:32
@karelz thanks for the hint.
i've found various similar reports, and joined a active one, as the proposed solution throws an exception ;-)

i haven't got as much +1's as a unified central proxy configuration would deserve, especially as .NET Core got some traction on multiple platforms.

**Comment by caesar1995** [comment] 2019-01-08 23:36
Dupe of: https://github.com/dotnet/corefx/issues/31036#issuecomment-435469812

We can track the issue there - it currently targets 3.0 as well.

**Closed by caesar1995** 2019-01-08 23:36 UTC
Labels: area-System.Net.Http

**Comment by karelz** [comment] 2019-01-09 01:01
Duplicate of https://github.com/dotnet/corefx/issues/31036
