### ISSUE TITLE
Value of Environment.CommandLine is different with the actual input

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/corefx#29014] opened 2018-04-11 05:26 UTC
Hi,
We are porting a .Net application to .Net Core. The application will run on Windows and we'd want it to have the same behavior with the origin one. In the application, we implemented a command line parser which reads command line from `Environment.CommandLine`. We'd want to reuse the code, while found `Environment.CommandLine` returns different value with .Net. In .Net, it can return exactly the same string I input on console. In .Net Core, it uses `\` to escape double quote marks, which is different from the string I input from console. 
For example:
When the input is `""" 1234`, `Environment.CommandLine` returns `"\" 1234"`, when input is `"\" 1234 "`, it also returns `"\" 1234"`.  
In this condition, I have no way to know what the actual input is.

Could you please help to take a look?

Emma

**Comment by stephentoub** [comment] 2018-04-11 13:01
cc: @AtsushiKan

**Comment by AtsushiKan** [comment] 2018-04-11 15:01
"Getting the exactly same input as typed on console" is something you can only do on Windows (on Unix, the "command line" is actually a string array) - given that .NETCore is cross-platform, `Environment.CommandLine` simply ensures a string that will roundtrip back to the output of `Environment.GetCommandLineArgs()`.

Since your application is specific to Windows, I would recommend P/Invoking to the Windows api directory:

https://www.pinvoke.net/default.aspx/kernel32/GetCommandLine.html

**Comment by AtsushiKan** [comment] 2018-04-11 15:15
Also, if your parser parsing command lines using the same rules that the C runtime does (http://www.windowsinspired.com/how-a-windows-programs-splits-its-command-line-into-individual-arguments/), it should be safe to pass the .NETCore output of `Environment.CommandLine` to it. It should parse to the same result.

**Comment by wfurt** [comment] 2018-09-25 00:52
is there anything left to do? This was opened as a question.

**Comment by EmmaZhu** [comment] 2018-09-25 00:58
Thanks for your help. The native method works just fine for our scenario.

**Comment by jkotas** [comment] 2018-09-25 13:11
We may want to consider fixing this for .NET Core 3.0 to ease migration from .NET Framework.

We plan to produce .exe for number by default in number of cases in .NET Core 3.0. The original arguments that we need to be able to be parse the command line and that it has to work the same way as on Unix no longer apply.

**Comment by jkotas** [comment] 2018-09-25 13:12
cc @danmosemsft

**Comment by danmosemsft** [comment] 2018-09-26 18:51
Putting in Winforms project although it's not directly related

**Comment by danmosemsft** [comment] 2018-09-26 18:56
@jeffschwMSFT do you own the "exe" story?

**Comment by jeffschwMSFT** [comment] 2018-09-26 19:00
My team owns a good portion of the host to the point of exe activation.

**Comment by danmosemsft** [comment] 2018-09-26 19:19
.NET Framework just pulled ::GetCommandLineW(). Any reason that wouldn't give the result we expect for these .NET Core based exe's?

It looks like on Unix you look in `/proc/<pid>/cmdline`

**Comment by jeffschwMSFT** [comment] 2018-09-26 19:51
In the case of the apphost it should.

**Comment by danmosemsft** [comment] 2018-09-26 20:05
The tricky part is deciding when we want to use that, and when we want Environment.CommandLine to return only the arguments (as it always does currently). 

The magic that currently eliminates "dotnet.exe" from the command line seems to be this stack - the CLR itself calls Environment.SetCommandLineArgs very early:
```
02 00000096`1df7de80 00007ffb`9c00ca93 coreclr!SetCommandLineArgs+0x29 [e:\a\_work\164\s\src\vm\corhost.cpp @ 379] 
03 00000096`1df7dfd0 00007ffb`9c00c936 coreclr!CorHost2::ExecuteAssembly+0x103 [e:\a\_work\164\s\src\vm\corhost.cpp @ 474] 
04 00000096`1df7e0e0 00007ffb`ab27fa50 coreclr!coreclr_execute_assembly+0xd6 [e:\a\_work\164\s\src\dlls\mscoree\unixinterface.cpp @ 407] 
```

In Environment.CommandLine it will prefer that
```
        public static string[] GetCommandLineArgs()
        {
            /*
             * There are multiple entry points to a hosted app.
             * The host could use ::ExecuteAssembly() or ::CreateDelegate option
             * ::ExecuteAssembly() -> In this particular case, the runtime invokes the main 
               method based on the arguments set by the host, and we return those arguments
             *
             * ::CreateDelegate() -> In this particular case, the host is asked to create a 
             * delegate based on the appDomain, assembly and methodDesc passed to it.
             * which the caller uses to invoke the method. In this particular case we do not have
             * any information on what arguments would be passed to the delegate.
             * So our best bet is to simply use the commandLine that was used to invoke the process.
             * in case it is present.
             */
            if (s_CommandLineArgs != null)
                return (string[])s_CommandLineArgs.Clone();

            return GetCommandLineArgsNative();
```

[Note to self. When not supplied, Environment.CommandLine uses GetCommandLineArgs() but runs it through PasteArguments.Paste to reconstruct it. GetCommandLineArgs() comes from coreclr\src\classlibnative\bcltype\system.cpp which does GetCommandLineW then runs it through [SegmentCommandLine](https://github.com/dotnet/coreclr/blob/a1404cafbe1cd15a5c0cfbd4995ad97694b708bd/src/utilcode/util.cpp#L2821) which does something similar to PasteArguments but in reverse. Seems some simplification is possible here]

Given the above I think the work is in the host, it needs to indicate to the CLR through coreclr_execute_assembly whether it should overwrite the actual command line or not. Does that sound right @jeffschwMSFT ?

**Comment by jkotas** [comment] 2018-09-26 21:02
> It looks like on Unix you look in `/proc/<pid>/cmdline`

I do not think there is any advantage in doing this on Unix compared to what we are doing today - it should return the same result. The issue described here is Windows specific.

**Comment by wfurt** [comment] 2018-09-26 21:07
```
furt@Ubuntu:~/git/wfurt-corefx$ cat /proc/630/cmdline | hexdump -C
00000000  2f 75 73 72 2f 62 69 6e  2f 64 62 75 73 2d 64 61  |/usr/bin/dbus-da|
00000010  65 6d 6f 6e 00 2d 2d 73  79 73 74 65 6d 00 2d 2d  |emon.--system.--|
00000020  61 64 64 72 65 73 73 3d  73 79 73 74 65 6d 64 3a  |address=systemd:|
00000030  00 2d 2d 6e 6f 66 6f 72  6b 00 2d 2d 6e 6f 70 69  |.--nofork.--nopi|
00000040  64 66 69 6c 65 00 2d 2d  73 79 73 74 65 6d 64 2d  |dfile.--systemd-|
00000050  61 63 74 69 76 61 74 69  6f 6e 00                 |activation.|
0000005b
```

That is essentially list of tokens equivalent of argv. (notice '\0' chars)

As far as I know there is no way to get the actually text user typed. 
Certainly not for commands from shell as shell will process quoting, escaping and variable expansion before calling exec()

**Comment by wfurt** [comment] 2018-09-26 21:10
one more note, that there are tricks to manipulate process name (and arguments) visible via ps. 
(At least on Linux)

**Comment by jeffschwMSFT** [comment] 2018-09-26 22:19
@danmosemsft I may have missed something, but why would Environment.CommandLine return any other than what was passed to the entry point?  The cases where create delegate, etc. seem nice to have but not required.  Based on your comment it looks like commandlines are not round tripable through PasteArguments.Paste.

**Comment by jkotas** [comment] 2018-09-26 22:28
> commandlines are not round tripable through `PasteArguments.Paste`

Yes, that's correct. It is by design.

`Environment.CommandLine` for Windows .NET Framework .exes returns the verbatim command line, before any round-tripping.

**Comment by danmosemsft** [comment] 2018-10-09 21:53
> Environment.CommandLine for Windows .NET Framework .exes returns the verbatim command line, before any round-tripping. Should we consider restoring this behavior?

Still stripping off args[0] ie `dotnet`, `dotnet.exe` etc. I assume?

**Comment by jkotas** [comment] 2018-10-09 22:16
> Still stripping off args[0] ie dotnet, dotnet.exe etc. I assume?

I think the behavior should stay as is for apps without apphost .exe that are launched via `dotnet.exe`.

**Comment by danmosemsft** [comment] 2019-04-26 20:45
@jeffschwMSFT @jkotas I have not heard much feedback on this since our discussion last fall. I suggest to move to Future. Let me know if you prefer we do something here now.

**Comment by jkotas** [comment] 2019-04-26 20:56
This is duplicate of https://github.com/dotnet/coreclr/issues/20562. CoreCLR repo is better place to track this.

>  I suggest to move to Future. Let me know if you prefer we do something here now.

It is fine with me. It is not hard work around if somebody really needs to native command line on Windows or native .exe name.

cc @sdmaclea

**Closed by jkotas** 2019-04-26 20:56 UTC
Labels: area-System.Runtime.Extensions, bug, tenet-compatibility

**Comment by danmosemsft** [comment] 2019-04-26 21:36
OK thanks.
