### ISSUE TITLE
XmlSerializer.Serialize performance issues on linux

### ISSUE THREAD

**Issue by deppe** [dotnet/corefx#16636] opened 2017-03-02 23:15 UTC
I recently profiled some asp.net core code that uses XmlSerializer and noticed some differing performance results when comparing Windows and Linux execution. I have a test program https://github.com/deppe/XmlSerializerPerf that runs XmlSerializer.Deserialize 1000 times, then runs XmlSerialize.Serialize 1000 times and prints the total time for each.

On windows, Serialize and Deserialize take a similar amount of time. For example:
```
Deserialize time 1351 ms
Serialize time 1210 ms
Serialize took 47.25% of total time
```

On linux, Serialize is much slower relative to Deserialize:
```
Deserialize time 1239 ms
Serialize time 4432 ms
Serialize took 78.15% of total time
```

I tried both dotnet version 1.0.0-preview2-1-003177 and 1.0.0-preview2-003131 and got similar results.

Is this expected? Are there any plans to improve the performance of XmlSerializer.Serialize on linux?

**Comment by danmosemsft** [comment] 2017-03-03 04:53
@stephentoub what's the best practice for investigating a Unix specific perf issue?

**Comment by stephentoub** [comment] 2017-03-03 12:16
> what's the best practice for investigating a Unix specific perf issue?

Profiling is generally a good place to start. You can collect profiling data with the perfcollect tool and view it in PerfView:
https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/Documentation/project-docs/linux-performance-tracing.md

**Comment by danmosemsft** [comment] 2017-03-03 21:55
@deppe any interest in grabbing a trace on Linux as above? With such a big difference the problem area might jump out.

**Comment by deppe** [comment] 2017-03-06 15:43
I ran perfcollect, but the output was too large to attach to this issue. Instead i pushed it to my test repo here: https://github.com/deppe/XmlSerializerPerf/blob/master/xmlperf.trace.zip

Let me know if you need anything else.

**Comment by stephentoub** [comment] 2017-03-06 15:54
@vancem, @brianrob, I tried opening this in perfview, but I get an error when I try to open the CPU stacks view:
```
Started: Opening CPU Stacks
Completed: Opening CPU Stacks   (Elapsed Time: 7.032 sec)
Exception Occurred: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__29.MoveNext() in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptEventParser.cs:line 326
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext() in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptEventParser.cs:line 85
   at Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_0.<DoInterning>b__0(Object givenArrayIndex) in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 63
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.DoInterning() in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 80
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptStackSource.InternAllLinuxEvents(Stream stream) in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 351
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptStackSource..ctor(String path, Boolean doThreadTime) in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 266
   at Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource..ctor(String path, Boolean doThreadTime) in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 20
   at PerfView.LinuxPerfViewData.OpenStackSourceImpl(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate) in C:\Users\stoub\Source\repos\perfview\src\PerfView\PerfViewData.cs:line 6090
   at PerfView.PerfViewStackSource.OpenStackSource(String streamName, TextWriter log, Double startRelativeMSec, Double endRelativeMSec, Predicate`1 predicate) in C:\Users\stoub\Source\repos\perfview\src\PerfView\PerfViewData.cs:line 2382
   at PerfView.PerfViewStackSource.<>c__DisplayClass23_0.<Open>b__0() in C:\Users\stoub\Source\repos\perfview\src\PerfView\PerfViewData.cs:line 2400
   at PerfView.StatusBar.<>c__DisplayClass19_0.<StartWork>b__0(Object <state>) in C:\Users\stoub\Source\repos\perfview\src\PerfView\GuiUtilities\StatusBar\StatusBar.xaml.cs:line 216
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__29.MoveNext() in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptEventParser.cs:line 326
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext() in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptEventParser.cs:line 85
   at Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_0.<DoInterning>b__0(Object givenArrayIndex) in C:\Users\stoub\Source\repos\perfview\src\PerfView\OtherSources\Linux\LinuxPerfScriptStackSource.cs:line 63
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

An exceptional condition occurred, see log for details.
```
Known issue in perfview?  And/or potentially something incorrect about the trace was captured?

**Comment by stephentoub** [comment] 2017-03-06 16:11
I hacked PerfView to work around the issue.  I believe this serialization performance problem is the same as https://github.com/dotnet/coreclr/issues/5558, and in particular https://github.com/dotnet/corefx/issues/3815, as 30% of the time in the trace is being spent in native code serializing doubles.

**Comment by vancem** [comment] 2017-03-06 17:36
I have reproed the issue with PerfView and created the following issue for it.  
https://github.com/Microsoft/perfview/issues/166 go there for any followup on that. 
I will give a triage look see later today.

**Comment by karelz** [comment] 2017-03-22 15:40
This is blocking .NET Core adoption for a particular customer who contacted us offline.
@zhenlan @shmao can you please drive the end-to-end resolution in 2.0? I'll say the same in the bugs @stephentoub identified, but we will need verification after they are fixed that this end-to-end scenario improved.

**Comment by mellinoe** [comment] 2017-03-23 00:17
@deppe Are you able to run the same tests on .NET Core 1.1 and compare the results?

**Comment by deppe** [comment] 2017-03-23 13:44
Looks similar using .NET Core 1.1:

```
Deserialize time 1028 ms
Serialize time 4264 ms
Serialize took 80.57% of total time
```

This was run using dotnet CLI version 1.0.1 and the following csproj. Let me know if i need to tweak anything in my setup.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>TestXml</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>TestXml</PackageId>
    <RuntimeFrameworkVersion>1.1.0</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>

</Project>
```

**Comment by mellinoe** [comment] 2017-03-27 22:46
Thanks for the additional data @deppe . I forked the repo and made a version that can be run against the latest .NET Core 2.0 bits.

https://github.com/mellinoe/XmlSerializerPerf

From my brief experimentation, the `Serialize` step takes about 80% of the time in .NET Core 2.0 when compared to .NET Core 1.1, and the `Deserialize` step takes about 105% off the time, if there's a difference at all.

We should re-run the analysis when https://github.com/dotnet/coreclr/issues/10390 and https://github.com/dotnet/coreclr/issues/5716 are fixed.

**Comment by karelz** [comment] 2017-03-27 22:53
@mellinoe just curious if you compared 1.1 vs. 2.0 on Windows or Linux or both?

**Comment by mellinoe** [comment] 2017-03-27 22:59
Relative differences are about the same for Windows and Linux by my testing.

Windows .NET Core 1.1:
```
iterations: 1000
Deserialize time 897 ms
Serialize time 1104 ms
Serialize took 55.17% of total time
```

Windows .NET Core 2.0:
```
iterations: 1000
Deserialize time 775 ms
Serialize time 1187 ms
Serialize took 60.5% of total time
```

**Comment by karelz** [comment] 2017-03-27 23:04
That would mean the difference originally reported is gone, unless I am mistaken, right?

**Comment by mellinoe** [comment] 2017-03-27 23:09
@karelz No... the problem is still there, it's just in slightly different proportions. And those differences could easily be explained by me having different hardware than @deppe . On my Ubuntu 16.04 machine, the `Serialize` step takes 85% of the time in .NET Core 2.0.

**Comment by mellinoe** [comment] 2017-03-27 23:13
Ubuntu 16.04 .NET Core 1.1:
```
iterations: 1000
Deserialize time 944 ms
Serialize time 3849 ms
Serialize took 80.3% of total time
```

Ubuntu 16.04 .NET Core 2.0:
```
iterations: 1000
Deserialize time 778 ms
Serialize time 3936 ms
Serialize took 83.5% of total time
```

**Comment by karelz** [comment] 2017-03-27 23:13
ok, makes sense. If you can reproduce, it's a great start for deeper investigations and experiments, thanks!

**Comment by eerhardt** [comment] 2017-04-18 19:12
FYI - I have merged two pretty major DateTime/TimeZoneInfo perf changes: https://github.com/dotnet/coreclr/pull/10507 and https://github.com/dotnet/coreclr/pull/10948.  From my perf investigations, running `DateTime.Now` 9,000 times went from ~340ms to ~28ms.

Please try the scenario again on the latest builds to ensure DateTime and TimeZoneInfo are no longer perf bottlenecks.

**Comment by karelz** [comment] 2017-04-19 07:55
Thanks @eerhardt @mellinoe for your help here.
I will opportunistically close the issue and reach out to CSS to make sure the validation happens. If there's still significantly blocking difference we can reopen / file a new tracking issue. Thanks!

**Closed by karelz** 2017-04-19 07:55 UTC
Labels: area-Serialization, os-linux, tenet-performance, up-for-grabs

**Comment by deppe** [comment] 2017-04-20 15:57
Which build version can i install to test this out? 2.0.0-preview1-002028-00?

**Comment by eerhardt** [comment] 2017-04-20 22:17
@deppe - I verified that all my fixes are in `2.0.0-preview1-002053-00`.  You can install it from https://github.com/dotnet/core-setup#daily-builds

**Comment by deppe** [comment] 2017-04-21 14:42
I downloaded the rhel build from https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-rhel-x64.latest.tar.gz, but when i run dotnet --version on it, i get 1.0.1. I assume this should be showing `2.0.0-preview1-002053-00` or something similar?

**Comment by karelz** [comment] 2017-04-21 15:07
I believe the --version prints version of the tooling. That is IMO ok to be 1.0.1. The version story is confusing :( -- we are working on de-confusion in the space (see [early doc](https://github.com/bleroy/core-docs/blob/d1c03ad6a86226a882c885bc422202548a8b09df/docs/core/versions/index.md))

**Comment by eerhardt** [comment] 2017-04-21 15:59
@karelz is correct.  `dotnet --info` only prints the SDK version, which is something we are addressing in 2.0.

@deppe - you'll want to read through https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#advanced-scenario---using-a-nightly-build-of-microsoftnetcoreapp (and the section above it) for how to get up and running with 2.0.

You may also run into https://github.com/dotnet/cli/issues/5896 if you have both a released SDK version `1.0.1` installed along with a pre-release `2.0.0-preview1-xxx` version.  To workaround it, you need to make a global.json file pointing to the `2.0.0-preview1-xxx` version of the SDK.  We are also making improvements in this area in 2.0.

**Comment by deppe** [comment] 2017-04-21 16:47
Ok, I'm still getting some errors on restore. Note that my 2.0.0-preview1-002057-00 dotnet installation is in `../dotnet` for all these examples.
```
12:16 $ ../dotnet restore                                                                                                
  Restoring packages for /home/adeppe/XmlSerializerPerf/TestXml/TestXml.csproj...
/opt/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview1-002057-00)' for '.NETCoreApp,Version=v2.0'. [/home/adeppe/XmlSerializerPerf/TestXml/TestXml.csproj]
  Lock file has not changed. Skipping lock file write. Path: /home/adeppe/XmlSerializerPerf/TestXml/obj/project.assets.json
  Restore failed in 208.8 ms for /home/adeppe/XmlSerializerPerf/TestXml/TestXml.csproj.
  
  Errors in /home/adeppe/XmlSerializerPerf/TestXml/TestXml.csproj
      Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview1-002057-00)' for '.NETCoreApp,Version=v2.0'
```

With global.json
```
12:16 $ cat ../global.json 
{
    "sdk": {
        "version": "2.0.0-preview1-002057-00"
    }
}
```

and csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>TestXml</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>TestXml</PackageId>
    <RuntimeFrameworkVersion>2.0.0-preview1-002057-00</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>

</Project>
```

And here's dotnet info.
```
12:17 $ ../dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.3
 OS Platform: Linux
 RID:         rhel.7.2-x64
 Base Path:   /opt/dotnet/sdk/1.0.1

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002057-00
  Build    : 67f26bc9f0b9c155b982869a671ed449512eba14
```

Any idea what I'm missing?

**Comment by eerhardt** [comment] 2017-04-21 16:54
You are missing the NuGet.config file that gets laid down when you say `dotnet new` using a 2.0 SDK.  Add a file next to your .csproj named `NuGet.config` that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

The pre-release packages aren't on nuget.org, so you need to point nuget to our myget feed to get them.

**Comment by deppe** [comment] 2017-04-21 17:18
Thanks, that fixed it. And the performance definitely improved :+1: 

New build:
```
iterations: 1000
Deserialize time 1024 ms
Serialize time 2842 ms
Serialize took 73.51% of total time
```

1.0.1:
```
iterations: 1000
Deserialize time 1317 ms
Serialize time 5093 ms
Serialize took 79.45% of total time
```

The one remaining issue (and this was the original reason i opened this ticket) is the fact that Serialize still takes almost 3x the amount of time as Deserialize. This wouldn't necessarily be an issue on its own, but the reason this stuck out to me is that on Windows, Serialize actually takes less time than Deserialize. If this performance difference between Windows/Linux is expected, then feel free to ignore, but might be something you want to look into further.

**Comment by deppe** [comment] 2017-04-21 17:19
Actually, I think the major cause of this performance discrepancy is https://github.com/dotnet/coreclr/issues/10651, so I can just follow that issue for future updates.

**Comment by karelz** [comment] 2017-04-21 17:31
@deppe can you please check you measure steady state perf properly? (e.g. discarding warm up phase, doing proper data statistics, etc.)
Could you create a test in https://github.com/dotnet/BenchmarkDotNet?
