### ISSUE TITLE
Port xsd.exe to .NET Core

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#12525] opened 2016-10-10 21:39 UTC
Currently, xsd.exe is a command line tool that runs against .NET Framework. We don't have a .NET Core and thus no cross-platform version of this tool.

**Comment by danmosemsft** [comment] 2016-10-10 22:00
dupe of https://github.com/dotnet/corefx/issues/8647

**Closed** 2016-10-10 22:47 UTC
Labels: area-System.Xml, port-to-core
