### ISSUE TITLE
Reconsider Socket Timeout Api

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#4880] opened 2015-12-08 12:51 UTC
Timeout settings for Socket Send/Recv operations only work for blocking API's. 
It's too easy to shoot yourself in the foot thinking these setting will come into effect for non-blocking network operations, especially nowadays given the simplicity of issuing async calls using async/await.

I suggest either:
- Implement timeout support for async send/recv operations into the Socket class (Preferred)
  - Why windows doesn't support timeouts for non-blocking socket calls is quite a mystery. 
- Remove blocking timeout properties (force explicit use of socket options)

For reference, all these properties are no-up with respect to async calls

Socket Class:
ReceiveTimeout
SendTimeout

NetworkStream:
CanTimeout (fixed to True)
ReadTimeout
WriteTimeout

TcpClient:
ReceiveTimeout
SendTimeout

**Comment by stephentoub** [comment] 2015-12-08 14:11
cc: @cipop, @SidharthNabar, @davidsh

**Comment by SidharthNabar** [comment] 2015-12-08 22:23
Thanks for pointing this out - I agree that developers would expect these timeouts to work with the async methods as well (through cancellation). I think the right fix for this should be to make these properties work for the async methods as well. That would be consistent with async methods in other APIs such as HttpClient. 

@davidsh @CIPop @pgavlin  - Do you agree?

**Comment by CIPop** [comment] 2015-12-09 00:08
I agree that we're missing cancellation on async Sockets APIs and that we need to add the functionality (most likely by introducing new APIs) in a future iteration. We were already thinking of adding CancellationToken support for TPL Socket APIs. We should also consider adding cancellation APIs for the Socket.*Async APIs without disposing the Socket object.

I don't agree changing any of the documented behaviors for the above APIs. Synchronous APIs are strongly discouraged and have been added mainly to support the `select` BSD async pattern.

**Comment by clrjunky** [comment] 2015-12-09 09:19
>We should also consider adding cancellation APIs for the Socket.*Async APIs without disposing the Socket object.

Key requirement.

**Comment by SidharthNabar** [comment] 2016-01-22 17:03
Adding CancellationToken overloads to Socket and Security APIs is tracked by #5211

**Comment by CIPop** [comment] 2016-12-12 23:21
@clrjunkie I'm tentatively closing this as a duplicate of 5211. Please reopen if I've missed anything.

**Comment by clrjunkie** [comment] 2016-12-13 11:26
I have no problem with having a single open issue on this topic, but a cursory read of #5211 suggests to me that this is not the right issue to replace this issue as it's title and the first few messages that follow suggest that the scope of the problem is limited to System.Net.Security. 

I would argue that this issue is better suited to represent the problem than #5211 because it highlights the general problem, details which socket api’s are affected and does not specifically advocate for any one solution.

Saying that, I have no problem with this issue being closed as long as the issue that replaces it carries a title having the word “Sockets” and a least mentions the Socket API’s which are affected, explicitly.

For some reason I do not have the option to reopen this issue. So please do so and feel free to close it again after designating an alternate issue (or update the existing designated one) with text that better conveys the general problem.

**Comment by CIPop** [comment] 2016-12-13 20:30
> but a cursory read of #5211 suggests to me that this is not the right issue to replace this issue as it's title and the first few messages that follow suggest that the scope of the problem is limited to System.Net.Security.

Sorry about that. You're right: I've ended up splitting these per contract but didn't change the ref here. 

The issue tracking this work now is #14308.

**Closed** 2016-12-13 20:31 UTC
Labels: api-needs-work, area-System.Net

**Comment by clrjunkie** [comment] 2016-12-13 20:34
Thanks.
