### ISSUE TITLE
Diacritics test failing on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3973] opened 2015-10-19 20:12 UTC
```C#
CultureInfo.CurrentCulture = new CultureInfo("en-US");
Console.WriteLine("Exhibit a\u0300\u00C0".IndexOf("\u0300"));
```
Using both StringComparison.CurrentCulture, CurrentCultureIgnoreCase, or OrdinalIgnoreCase, on Windows this prints out 9, but on Linux it prints out -1.

**Comment by steveharter** [comment] 2015-12-01 18:25
This is by design for ICU. The corresponding test will be fixed as part of this issue.

The diacritic 0x0300 is a "combining character" (https://codepoints.net/U+0300) and must be preceded by a valid character in order to be compared.

Debugging the ICU code without a preceding character encounters this check and sets found=FALSE: (usearch.cpp line ~3981)
        // Check for the start of the match being within a combining sequence.
        //   This can happen if the pattern itself begins with a combining char, and
        //   the match found combining marks in the target text that were attached
        //    to something else.
        //   This type of match should be rejected for not completely consuming a
        //   combining sequence.
        if (!isBreakBoundary(strsrch, mStart)) {
            found = FALSE;
        }

**Comment by steveharter** [comment] 2015-12-01 20:27
Test fixed

**Closed by steveharter** 2015-12-01 20:27 UTC
Labels: System.Globalization, X-Plat
