### ISSUE TITLE
System.Net.Http.HttpClient SendAsync throws "The requested header was not found" when parsing 307 HTTP response from server

### ISSUE THREAD

**Issue by Hochman85** [dotnet/corefx#5065] opened 2015-12-18 17:25 UTC
Hi I am actually having ta weird issue with System.Net.Http.HttpRequestMessage when trying to add a custom header. The header is added and yet SendAsync throws an exception about "header was not found"! Here in the team, we have spent 4 days in vain to get this to work. Any help would be appreciated.

private static async Task MakeRequestExample(string url)
{
   try
   {
           HttpMethod httpMethod = HttpMethod.Get;

            using (HttpClient httpClient = new HttpClient())
            {
                using (HttpRequestMessage httpRequestMessage = new HttpRequestMessage(httpMethod, url))
                {
                    //httpRequestMessage.Headers.Accept.TryParseAdd("text/plain"); <-- not sure about this             

                    bool added = httpRequestMessage.Headers.TryAddWithoutValidation("Client-Id", "314");
                    // added will be true and when I debug this I actually find the header

                    using (HttpResponseMessage httpResponse = await httpClient.SendAsync(httpRequestMessage))
                    {
                        switch (httpResponse.StatusCode)
                        {
                            case HttpStatusCode.OK:
                                // logic 1
                                break;

                            case HttpStatusCode.RedirectKeepVerb:
                            case HttpStatusCode.NotFound:
                            case HttpStatusCode.Moved:
                            case HttpStatusCode.BadRequest:
                            case HttpStatusCode.InternalServerError:
                                // logic 2
                                break;

                            default:
                                // logic 3
                                break;
                        }
                    }
                }
            }
        }
        catch (Exception e)
        {
            Debug.WriteLine("MakeRequest - Exception message: " + e.Message);
            Debug.WriteLine("MakeRequest - Exception stack trace: " + e.StackTrace);
            Debug.WriteLine("MakeRequest - Exception HResult: " + e.HResult);
            Debug.WriteLine("MakeRequest - Exception inner ex: " + e.InnerException);
        }
    }
The exception:

Exception message: An error occurred while sending the request.
Exception stack trace: at System.Net.Http.HttpClientHandler.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Proj.Api.d__7.MoveNext()
Proj.Api=> Exception HResult: -2147012746
Proj.Api=> Exception inner ex: System.Runtime.InteropServices.COMException (0x80072F76): The text associated with this error code could not be found.

The requested header was not found

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpHandlerToFilter.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpClientHandler.d__1.MoveNext()

**Comment by SidharthNabar** [comment] 2015-12-18 22:52
I tried this code snippet  and it worked just fine against my server - can you share the server URI that you're trying to hit? Also, what OS are you trying this on?

**Comment by Hochman85** [comment] 2015-12-21 10:11
@SidharthNabar the OS I am using for development is Windows 8.1 Enterprise. I am deploying to Win 10 emulators and devices from Visual Studio Community 2015.
I do not think I can share the URL because it belongs to the company I work for. I need to check first with my manager.

The equivalent code in Win Forms is working fine - I am not sure if System.Net.Http classes on Win 10 require any other parameters to be set.

**Comment by SidharthNabar** [comment] 2015-12-21 17:34
@Hochman85 - I just tried again on a Windows 8.1 target and it still works. Do you repro this against another, generic URI? Or only with your server? Does it repro if you do not add the Client-Id header? At this point, it seems like the issue could be on the server side.

**Comment by Hochman85** [comment] 2015-12-22 09:59
@SidharthNabar - if I remove the header and I make a basic request that works fine and I get 200. The moment I add a header (used for a different scenario) to the same request the method crashes.
The reason why I do not think it is a server issue is: I am not getting any error from the server - my understanding: if it was server-related I would get an error code (e.g. bad request or not acceptable). But here the method is crashing.

**Comment by SidharthNabar** [comment] 2015-12-22 17:57
`P.S. actually my target is Universal Windows not 8.1` - good, this makes sense given the stack trace.

Have you tried against another server/URI as I mentioned above? When I said it could be a server issue, I was referring to the fact that the server could be sending a malformed response or a response with a header missing, etc. If  sending the request (with the custom header added) to another server works, we should look at what is unique about this server.

Another thing to try: Can you name your header "X-Client-Id" instead of "Client-Id"? It's possible that the lower layers in the HTTP Stack of the OS don't allow adding a custom header that doesn't have the X- prefix.

If that also doesn't work, I think we'll need the exact URI of the server and the full VS sln.

Thanks,
Sid

**Comment by SidharthNabar** [comment] 2016-01-22 17:00
@Hochman85 - Any updates on this - did you get a chance to try the above steps? Are you still seeing this issue?

**Comment by davidsh** [comment] 2016-02-03 04:06
We are unable to repro this.  We will close this issue for now.  If this repros, please attach a Visual Studio solution (you can create a separate repo for that) and re-open the issue.  Thx.

**Comment by Hochman85** [comment] 2016-03-08 13:15
Hi David and Sid, sorry I've been away recently and prior to that I had moved to another task. Now I'm back and this issue is actually still a valid one. However, now I've managed to narrow it down.

The issue is actually not caused by adding a custom header but rather when 307 http response (redirect) is received in the app from the server. The custom header scenario was a 307 case too; that is what confused me (was thinking it was the custom header).

**I have attached a complete standalone troubleshooting zip (as David suggested) containing:**
- sample app which tries to send a GET http request to localhost
- a test server node JS which sends 307 with the headers that our actual server uses (simulation of the real problem)
- a screenshot of the operation: app running, server running and receiving the request (you can see "Test" output in the command line which is only printed when a request is received) and the console output

**N.B.**
1. if you run the node JS test server, run the app in a simulator (so you can access localhost) and hit "Test Http Request" button, you should be able to see the COM exception stating "an error occurred while sending the request".
2. since the request is received on the server side this means:
HttpRequestMessage httpRequestMessage = new HttpRequestMessage(httpMethod, url)
is not failing when sending but rather when trying to parse the response into an HttpRequestMessage  object (it actually complains about a header not found!).

Could we please re-open this issue?

[307 issue.zip](https://github.com/dotnet/corefx/files/163191/307.issue.zip)

**Comment by davidsh** [comment] 2016-03-08 17:57
@Hochman85 
Thank you for posting the ZIP file.  When I looked at the screenshot of the error you have, I noticed that you are not running an ASP.NET Core scenario.  Instead, it appears you are developing a Windows UWP App.  It looks like you have a phone simulator running in Visual Studio.

Specifically, I see that the stack trace is using HttpHandlerToFilter.cs source file.  That means that while you are using part of the CoreFx library for System.Net.Http, it is actually the NETCORE50 version and not the DNXCORE50 version.  You are seeing an error coming from the implementation layer of System.Net.Http which for UWP apps using the Windows WinRT Windows.Web.Http libraries.

You are getting a WININET_E_HEADER_NOT_FOUND (0x80072F76) HRESULT being returned.

What is the version of Windows OS that you are using to reproduce this problem.  If it is Windows 10, can you further clarify the specific release.  For example, open up a CMD.EXE window and type 'ver'. What is the output?

This is important information which will help us diagnose this issue. Thanks.

**Comment by Hochman85** [comment] 2016-03-09 11:16
@davidsh 
Hi David and thanks for your quick reply. Just to clarify, the whole issue is a UWP (Win 10) issue as we are not using ASP.Net at all.

I do not have CMD on the phone so I just used About from All Settings:
**My device**
Version: 1511
The Windows OS version: Windows 10 Mobile
OS build: 10.0.10586.107
Firmware revision number: 02177.00000.15184.36005

**The emulator**
![nuget](https://cloud.githubusercontent.com/assets/5698730/13633613/165ba420-e5e8-11e5-96de-9b5dc4bb6c05.JPG)

Version: 1511
The Windows OS version: Windows 10 Mobile
OS build: 10.0.10586.11
Firmware revision number: 0

I have also attached a screenshot of my NuGet view (installed packages). The System.Net.Http version is 4.0.0 (updated a few weeks ago.

Please let me know if there is anything else you need for this investigation.
Thanks for your help.

**Comment by davidsh** [comment] 2016-03-12 23:20
I looked into why you are getting the `WININET_E_HEADER_NOT_FOUND` error exception from the HTTP stack.  The reason is a combination of your test server HTTP response and your settings on HttpClientHandler.

Your test server is generate a redirection response, 307 status code.  Redirection responses are normally required to have a `Location` response header field.  That field tells the client where to do a redirection.  Since you are also using `HttpClientHandler.AllowAutoRedirect = true` (the default setting), the HTTP stack is trying to do the redirection.  But it is unable to since there is no `Location` response header present.  This combination is causing this error exception indicating that the "header is not found".  It is unfortunate that the error message is not clearer, i.e. indicating which particular header is not found.  But basically, this error is by-design.

So, there are two choices you can use to solve this. 1) You can modify your test server to make sure that redirection responses (i.e. 301, 302, 307) include a `Location` response header, or 2) Turn off automatic redirection handling in HttpClientHandler.

According to the HTTP RFC 7231:
http://tools.ietf.org/html/rfc7231#section-6.4

>6.4.7.  307 Temporary Redirect
   The 307 (Temporary Redirect) status code indicates that the target
   resource resides temporarily under a different URI and the user agent
   MUST NOT change the request method if it performs an automatic
   redirection to that URI.  Since the redirection can change over time,
   the client ought to continue using the original effective request URI
   for future requests.
   The server SHOULD generate a Location header field in the response
   containing a URI reference for the different URI.  The user agent MAY
   use the Location field value for automatic redirection.  The server's
   response payload usually contains a short hypertext note with a
   hyperlink to the different URI(s).

**Comment by Hochman85** [comment] 2016-03-14 11:00
@davidsh 
Thanks for your help David. It works fine now!

I am setting AllowAutoRedirect to false to stop it from looking for Location. But I agree, if the internal exception gives more information (e.g. which header it's failing to find) it'll be easier to troubleshoot :)

Thanks a lot for your support again!

**Comment by davidsh** [comment] 2016-03-14 14:02
Since this is now resolved, closing the issue.

**Closed by davidsh** 2016-03-14 14:02 UTC
Labels: System.Net, Windows UWP
