### ISSUE TITLE
RuntimeFeature.IsSupported("EmitIL") would be a useful feature check.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#25944] opened 2017-12-15 17:27 UTC
Whether one can emit IL or not is a significant difference between platforms, that impacts on the best approach to some problems, so it would be useful if `RuntimeFeature` could be queried about it.

This should close #10470 as well, which wishes to be able to enquire as to whether `LamdbaExpression.Compile()` can emit IL, which in turn depends on that feature.

**Comment by danmosemsft** [comment] 2017-12-15 23:28
https://github.com/dotnet/corefx/issues/25530

**Comment by karelz** [comment] 2017-12-16 18:16
Duplicate of #25530

**Closed by karelz** 2017-12-16 18:16 UTC
