### ISSUE TITLE
Desktop System.Globalization test need strong name skip verification entries to run

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8617] opened 2016-05-17 19:06 UTC
All failing tests Log [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/38/)

```
System.IO.FileLoadException : Could not load file or assembly 'System.Globalization.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)\r\n---- System.Security.SecurityException : Strong name validation failed. (Exception from HRESULT: 0x8013141A)
+++++++++++++++++++
STACK TRACE:
at System.Globalization.Tests.GetStringComparerTests.Compare(String x, String y, String cultureName, CompareOptions options, Int32 expectedWindows, Int32 expectedICU) ----- Inner Stack Trace -----
```

**Comment by ellismg** [comment] 2016-05-17 19:08
@tarekgh Could this be related to desktop testing?

**Comment by tarekgh** [comment] 2016-05-17 19:09
I'll take a look but I am wondering is this first time the test runs on Windows 7? I think this was working before. right?

**Comment by tarekgh** [comment] 2016-05-17 19:29
> @tarekgh Could this be related to desktop testing?

@ellismg yes looks so.

@stephentoub what version of framework installed on that Windows 7 machine?

**Comment by Priya91** [comment] 2016-05-17 19:40
@tarekgh 4.6.1 full framework, release is 394271

**Comment by krwq** [comment] 2016-05-18 00:55
are api-*.dll files on the machine?

**Comment by tarekgh** [comment] 2016-05-18 20:53
@krwq the problem is not api-*, the problem is on desktop, the signing verification is applied and because our assemblies are not fully signed we fail to load it. the problem doesn't happen in most of the machines because on these machine the signing verification is skipped by setting some registry key. 

@ellismg is going to patch the failing machines for now to include these registry keys to unblock the ci. 
@ellismg do you think we need to keep this for RTM or we can push to 1.1.0? as you know there is no easy solution here so it'll need to have some more investigations.

**Comment by ellismg** [comment] 2016-05-18 22:18
> @ellismg do you think we need to keep this for RTM or we can push to 1.1.0? as you know there is no easy solution here so it'll need to have some more investigations.

The thing we should ensure, before RTM, is that these tests work when using a fully signed version of the assembly when skip verification is not enabled.  If we do that manually, I think that's sufficient.

I'll take this work item to track fixing CI, and we should file two more, one to do the manual validation and one to figure out how we want this to work long term.

**Comment by tarekgh** [comment] 2016-05-18 23:04
@ellismg 
> The thing we should ensure, before RTM, is that these tests work when using a fully signed version of the assembly when skip verification is not enabled. If we do that manually, I think that's sufficient.

I have tried to run the test with the fully signed library (got it from myget.org) and it ran without any complains. I tried that on the test failing with this issue. The question now how we'll force our runs to use the official packages instead of the locally built assemblies. that is I don't know yet. 

CC @ericstj to get his opinion.

**Comment by ericstj** [comment] 2016-05-18 23:23
Shouldn't OSS-signing alleviate the need for even skip verification?  That was the whole point.

**Comment by ellismg** [comment] 2016-05-18 23:27
> Shouldn't OSS-signing alleviate the need for even skip verification? That was the whole point.

Do you understand the cases where that doesn't work, on Desktop?  I thought that OSS-signing was not fully supported on desktop, just on CoreCLR.

**Comment by ericstj** [comment] 2016-05-18 23:30
@gkhanna79 can fill in.  My impression was that it worked for Desktop so long as you don't try to install to the GAC.

**Comment by gkhanna79** [comment] 2016-05-18 23:33
I am not aware of the details of OSS signing and how it works on Desktop. @jkotas Do you know? @terrajobst may know as well.

**Comment by tarekgh** [comment] 2016-05-18 23:36
cc @weshaggard 

To clarify, when building a library we'll use MSFT.snk to sign the assembly with SignType=oss. the produced assembly cannot get loaded on the desktop without skipping the signing verification. 

for the test assemblies we sign it with Test.snk and having SignType=real, this one seems to load on the desktop.

**Comment by tarekgh** [comment] 2016-05-19 00:30
cc @nguerrera too

**Comment by nguerrera** [comment] 2016-05-19 00:56
In addition to not being able to GAC at least shadow-copying does not work with "OSS" signing. How are these tests getting executed on desktop. xunit defaults to shadow copying. The command line runner has a flag to prevent it and you can also put the following in an app.config of your test project for the VS integration to honor it:

``` XML
<appSettings> 
  <add key="xunit.shadowCopy" value="false" /> 
</appSettings> 
```

**Comment by tarekgh** [comment] 2016-05-19 01:01
@nguerrera we run xunit.console.exe and passing the parameters -noshadow which take care with this issue.

**Comment by nguerrera** [comment] 2016-05-19 01:05
@tarekgh Odd. Did something in the build switch the signing from "OSS" to delay-signed mistakenly?

**Comment by nguerrera** [comment] 2016-05-19 01:06
IOW, are we sure SignType=oss is doing what we think it does?

**Comment by tarekgh** [comment] 2016-05-19 01:08
I checked the assembly signing bit and it shows it is signed but yet fail to pass the signing

**Comment by nguerrera** [comment] 2016-05-19 01:14
So 'OSS' signed binaries work on desktop to the extent that signing verification is skipped as performance optimization. If we hit a code path where verification kicks in, then it will (of course!) fail. I am curious what is special about this case that causes the verification to kick in. 

We have had a good deal of success elsewhere (e.g. Roslyn) running unit tests on desktop with OSS-signed bits and no skip verification entries registered. (Shadow copying was the only pain-point there.)

**Comment by tarekgh** [comment] 2016-05-19 01:28
the interesting thing is the test assembly load fine. so the issue looks the difference between how we sign our library and how we sign the test. obviously we use different keys for signing and also we set the sign type to OSS for the library and we set it to real for the tests.

here is the stack that do the signing and then fail.

```
clr!AssemblyNative::LoadFile
clr!AssemblyNative::GetPostPolicyAssembly
clr!AppDomain::LoadDomainAssemblyInternal
clr!AppDomain::LoadDomainFile
clr!AppDomain::TryIncrementalLoad
clr!DomainAssembly::Allocate
clr!AssemblySecurityDescriptor::CheckAllowAssemblyLoad
clr!AssemblySecurityDescriptor::Resolve
clr!PEAssembly::VerifyStrongName
clr!PEImage::VerifyStrongName
clr!StrongNameSignatureVerification
clr!VerifySignature
```

**Comment by tarekgh** [comment] 2016-05-19 02:20
one more thing to mention is the library that failing the test is partial façade which has 

```
[assembly: TypeForwardedTo(typeof(IdnMapping))]
[assembly: TypeForwardedTo(typeof(NormalizationForm))]
```

maybe this a factor in why the signing validation is triggered too but I am not sure yet.

**Comment by ellismg** [comment] 2016-05-19 18:56
I added skip verification entries to our Win7 machines to unblock outerloop CI.  I'm keeping this bug open so we can figure out the right way to solve this issue, but I'm moving it to 1.1.

**Comment by tarekgh** [comment] 2016-05-19 19:07
with more investigation I found the library doesn't have the strong name signing flag 
```
COMIMAGE_FLAGS_STRONGNAMESIGNED     =0x0000000
```

while corflags showing 

```Signed    : 1```

so I'll look why this bit is not set and I think this should take care with the signing problem

**Comment by tarekgh** [comment] 2016-05-19 20:15
ok I think I understand what is going on here. the problem is the target CopyFilesToOutputDirectory get executed before the target OpenSourceSign. which mean we copy the assembly to the out folder before signing it. 

CopyFilesToOutputDirectory get executed first because ValidateApiCompatForSrc depends on it. looks we need to try reorder the targets execution to fix this issue. the interesting thing, in the sign.tagets files I am seeing the comment 

```
* BeforeTargets=CopyFilesToOutputDirectory -> does not work on Mono.
```

and we do the following 

```
   <PrepareForRunDependsOn>OpenSourceSign;$(PrepareForRunDependsOn)</PrepareForRunDependsOn>
```

will try to look more but I hope @weshaggard will have a chance to recommend the best way we can fix that.

**Comment by nguerrera** [comment] 2016-05-19 20:41
Are tools sufficiently updated in corefx build to replace the buildtools bit-twiddling with `csc /publicsign+`?

**Comment by tarekgh** [comment] 2016-05-19 21:06
@nguerrera is there specific csc version I can check?

**Comment by nguerrera** [comment] 2016-05-19 21:14
@tarekgh See if `csc /?` lists `/publicsign`? (cc @jaredpar)

**Comment by tarekgh** [comment] 2016-05-19 22:01
looks we are using ""C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe""  and the one I have is supporting /publicsign

**Comment by tarekgh** [comment] 2016-05-19 22:10
By the way adding OpenSourceSign to the depends on targets of ValidateApiCompatForSrc fixed the issue. I'll let @weshaggard comment on that.

```Xml
  <!-- ApiCompat for Implementation Assemblies  -->
  <Target Name="ValidateApiCompatForSrc"
          DependsOnTargets="OpenSourceSign;CopyFilesToOutputDirectory"
          Condition="'$(RunApiCompatForSrc)' == 'true' AND '$(RunApiCompat)' == 'true' AND Exists('$(ContractProject)')" >
```

**Comment by Priya91** [comment] 2016-05-19 23:20
These failures are happening on Windows10 outerloop tests as well..

**Comment by tarekgh** [comment] 2016-05-19 23:28
@Priya91 yes this can happen if the skip signing verification is not there. we can patch the machine till we submit the fix. I just want to @weshaggard review as he knows all details around the apicompat and signing targets

**Comment by ellismg** [comment] 2016-05-19 23:50
I added the skip entries and I am going to restart the W10 outer loop jobs.

**Comment by tarekgh** [comment] 2016-05-20 00:00
thanks @ellismg for your help.

**Comment by tarekgh** [comment] 2016-05-20 15:33
Talked to Wes offline and he mentioned the APICompat target causing other problems too. so he is going to fix that.

CC @ericeil

**Comment by weshaggard** [comment] 2016-05-20 15:52
I've got PR https://github.com/dotnet/buildtools/pull/737 which should fix the Copy target from running before signing.

**Closed** 2016-05-20 16:23 UTC
Labels: Infrastructure

**Comment by weshaggard** [comment] 2016-05-20 17:36
Corefx should be fixed with https://github.com/dotnet/corefx/pull/8720

**Comment by tarekgh** [comment] 2016-05-20 17:55
thanks @weshaggard
