### ISSUE TITLE
System.Data.SqlClient package regression: no DNXCore50 build in 4.0.0-beta-23409

### ISSUE THREAD

**Issue by NickCraver** [dotnet/corefx#3982] opened 2015-10-20 10:34 UTC
I can't find anywhere this is intentional - so assuming it's a bug. Between `4.0.0-beta-23225` and `4.0.0-beta-23409` (current) the DNXCore50 lib was dropped. This of course breaks anyone with `4.0.0-beta-*` doing a `dnxcore50` build. Here's a better illustration of the problem:

<img width="901" alt="screen shot 2015-10-20 at 6 20 01 am" src="https://cloud.githubusercontent.com/assets/454813/10604594/627b72d6-76f3-11e5-933e-c73747f6a81f.png">

Was this an intentional change I just can't find the documentation for, or does nuget.org just need an fixed build here? Or am I an idiot? All of these are valid options.

**Comment by joshfree** [comment] 2015-10-20 14:47
@chcosta @saurabh500 @ericstj can you please take a look?

**Comment by ericstj** [comment] 2015-10-20 15:19
The implementation comes from the runtime package.  It is associated via the runtime.json.  For details see issue https://github.com/dotnet/corefx/issues/3927.

**Comment by ericstj** [comment] 2015-10-30 17:21
Closing this since the description of the issue is just observing an intentional change to the package to split out for x-plat.  You should be able to resolve the implementation per the details in the linked issue.  If you have any trouble let me and @chcosta know.

**Closed by ericstj** 2015-10-30 17:21 UTC
Labels: DNX / DNU, System.Data
