### ISSUE TITLE
HttpClient.SendAsync(request, httpcompletionoption, cancellationtoken) should be virtual.

### ISSUE THREAD

**Issue by nertim** [dotnet/corefx#26721] opened 2018-01-31 22:59 UTC
Hello,

Similar to implementation of SendAsync(req, cancellationToken) the sendAsync(req, httpcompletion, cancellationtoken) should be also virtual. Currently we are able to override SendAsync(req, cancellationToken) with some custom code and would like to do the same for sendAsync(req, httpcompletion, cancellationtoken)

Thanks.

**Comment by davidsh** [comment] 2018-01-31 23:31
This is by design.  This method is not meant to virtual nor overridden.

Custom code should create a new handler based on DelegatingHandler, HttpMessagerHandler. and then override the virtual SendAsync() method in the handler.

**Comment by davidsh** [comment] 2018-01-31 23:31
This particular question came up before in a earlier GitHub issue.  I need to find that issue to link this as a duplicate.

**Comment by davidsh** [comment] 2018-01-31 23:32
cc: @dotnet/ncl

**Comment by rmkerr** [comment] 2018-01-31 23:57
I think the issue was discussed in #23812.

**Comment by karelz** [comment] 2018-02-01 00:24
Yep, looks like dupe, closing.
BTW: The docs were updated in https://github.com/dotnet/docs/pull/3105

**Closed by karelz** 2018-02-01 00:24 UTC
Labels: area-System.Net.Http, documentation

**Comment by ti24horas** [comment] 2018-10-05 18:32
> This is by design. This method is not meant to be virtual nor overridden.
> 
> Custom code should create a new handler based on DelegatingHandler, HttpMessagerHandler. and then override the virtual SendAsync() method in the handler.

If i do that, I cannot control the RequestUri value just before sending the request because it crashes when HttpClient.CheckRequestMessage checks for url.
