### ISSUE TITLE
Serializing rich payload events with Nullable properties fails

### ISSUE THREAD

**Issue by pharring** [dotnet/corefx#32606] opened 2018-10-03 21:34 UTC
Originally reported via Application Insights at https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/850

If you call `System.Diagnostics.Tracing.EventSource.Write<T>` passing in an object with nullable properties (`int?` or `double?`, for example) whose value is null (i.e. `HasValue` returns `false`), you get a System.Reflection.TargetException (full call-stack below).

This looks like a bug in .NET Core because there is an attempt to deal with Nullable properties via `NullableTypeInfo`. It also worked in .NET 4.6 which makes me think it should work in CoreCLR too.

```
Exception thrown: System.Reflection.TargetException: Non-static method requires a target.
 at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
 at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
 at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
 at System.Diagnostics.Tracing.PropertyValue.<>c__DisplayClass33_0.<GetBoxedValueTypePropertyGetter>b__0(PropertyValue container)
 at System.Diagnostics.Tracing.NullableTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
 at System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
 at System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
 at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)
 at System.Diagnostics.Tracing.EventSource.Write[T](String eventName, EventSourceOptions options, T data)
```

**Comment by pharring** [comment] 2018-10-03 23:38
Here's a repro:

```C#
using System.Diagnostics.Tracing;

namespace ConsoleApp
{
    public class MyEventListener : EventListener
    {
    }

    class Program
    {
        static void Main(string[] args)
        {
            var eventSource = new EventSource("MyCompany-MyApp-MyEventSource", EventSourceSettings.EtwSelfDescribingEventFormat | EventSourceSettings.ThrowOnEventWriteErrors);
            using (var listener = new MyEventListener())
            {
                listener.EnableEvents(eventSource, EventLevel.Verbose, EventKeywords.All);
                eventSource.Write("Test", new { Value = (int?)null });
            }
        }
    }
}
```

If targeting .NET 4.6 (or above), this completes successfully. However, if compiled for .NET Core, this throws a System.Diagnostics.Tracing.EventSourceException with an InnerException of
```
System.Reflection.TargetException: Non-static method requires a target.
    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
    at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
    at System.Diagnostics.Tracing.PropertyValue.<>c__DisplayClass33_0.<GetBoxedValueTypePropertyGetter>b__0(PropertyValue container)
    at System.Diagnostics.Tracing.NullableTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
    at System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
    at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)
```

**Comment by vancem** [comment] 2018-10-04 00:03
Thanks Paul.  That is super helpful to have a nice small repro like this.

**Comment by jbhensley** [comment] 2018-10-09 21:36
It looks like the problem is `NullableTypeInfo.WriteData`:

```C#
public override void WriteData(TraceLoggingDataCollector collector, PropertyValue value)
{   
	var hasValue = hasValueGetter(value);
	collector.AddScalar(hasValue);
	var val = hasValue.ScalarValue.AsBoolean ? valueGetter(value) : valueInfo.PropertyValueFactory(Activator.CreateInstance(valueInfo.DataType));
	this.valueInfo.WriteData(collector, val);
}
```

Ultimately, `var hasValue = hasValueGetter(value)` leads down a path that calls `PropertyInfo.GetValue` on the null object, leading to `Non-static method requires a target`. Easy to demostrate with the C# REPL:

![nullable error](https://user-images.githubusercontent.com/13544395/46699445-ad89f080-cbce-11e8-944a-5d45f3d1885b.png)

NetFx avoids this because it takes a ref to the value itself and checks the `IsNull` property:

```C#
public override void WriteData(TraceLoggingDataCollector collector, ref T? value)
{
  bool hasValue = value.HasValue;
  collector.AddScalar(hasValue);
  T obj = hasValue ? value.Value : default (T);
  this.valueInfo.WriteData(collector, ref obj);
}
```

The question is, what's the correct method for null check here? Is it as simple as replacing:

```C#
var hasValue = hasValueGetter(value);
``` 

with 

```C#
var hasValue = value != null;
```

**Comment by vancem** [comment] 2018-10-09 22:28
I did not write this code, but after looking it over I can say the following:

First, PropertyValue is like a variant, it can hold 'any' type.   WriteData's job is to take this value and write it to the buffer.   The format is a boolan (hasValue) followed by the serialization of the T (which is a default entry if hasValue is false).      

The crux of the question is what is the representation of a nullable as a PropertyValue (which is what is being passed in.    The code in WriteData is written such that it is a non-null PropertyValue (using the Boolean scaler and the object, but the way a PropertyValue is made is using the method
```
Func<object, PropertyValue> GetFactory(Type type)
```
And this method falls into the 'default' case and returns the property value with a _reference = value where value is the boxed value (which may be null).    This is the representation of a Nullable as a property value.  

Knowing this, makes things straightforward.  
I believe the code of WriteData should be
```
            bool hasValue = (value.Reference != null);   // The nullable is boxed, and thus is null if it does not have a value.  
            collector.AddScalar(new PropertyValue(hasValue));  // We write out this boolean first. 
            var val = hasValue ? valueGetter(value) : valueInfo.PropertyValueFactory(Activator.CreateInstance(valueInfo.DataType));  // We write out the value (or a default value) next.  
            this.valueInfo.WriteData(collector, val);
```
You can remove the 'hasValueGetter' since we don't use it.

I would also add a comment to the code about how the Nullable is represented. 

We clearly need some tests as well (passing null to a nullable).

**Comment by jbhensley** [comment] 2018-10-10 19:46
Ok, I opened a PR for this and put in a unit test on the corefx side that we can include once the coreclr changes sync up. The only thing I don't like is that two of the unit tests for `System.Diagnostics.Tracing` were already failing before I made any changes. I'll grab the latest corefx bits and rebase to see if they resolve.

Separately, I think we should consider the question of whether `HasValue` should be accessible through reflection at all times and not just when true. I'll open a corefx issue to see if we can get some discussion.

**Comment by noahfalk** [comment] 2018-10-13 00:29
Thanks to @jbhensley we just merged a fix for this in master. We've also located a likely 2nd bug if you try to listen to EventSource events using EventListener, tracked by https://github.com/dotnet/corefx/issues/32796.

Master leads to the 3.0 release, separately we now need to investigate back-porting this fix into 2.2 and servicing branches.

**Comment by ahsonkhan** [comment] 2019-05-11 07:51
@noahfalk, any updates on whether the fix need to be backported to 2.1/2.2?

**Comment by noahfalk** [comment] 2019-05-15 00:08
I no longer recall the details, but at this point I'm assuming we either already backported the change or concluded it wasn't necessary. @jorive probably would have been the one to do it if it happened. @jorive do you recall the result here?

**Comment by ahsonkhan** [comment] 2019-05-16 03:01
Looks like it already got ported in https://github.com/dotnet/coreclr/pull/20572.

Closing as fixed. @jorive, please confirm or re-open if I am mistaken.

**Closed by ahsonkhan** 2019-05-16 03:01 UTC
Labels: area-System.Diagnostics.Tracing, bug
