### ISSUE TITLE
OSX runs failing in package restore

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7902] opened 2016-04-20 01:38 UTC
```
[18:26:30.98] Restoring all packages...
18:21:02 EXEC : error : End of Central Directory record could not be found. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/build.proj]
18:21:02 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/build.proj(80,5): error MSB3073: The command ""/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/Tools/dotnetcli/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ --infer-runtimes "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug/pkg"" exited with code -1.
18:21:02   [18:26:49.54] Restoring all packages...Done.
```

cc @ericstj @dagood

**Comment by mellinoe** [comment] 2016-04-20 01:52
It looks like this has happened in the outer loop run as well:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug/7/consoleFull
WARNING: 200 MB log file

**Comment by dagood** [comment] 2016-04-20 15:19
I can repro this locally, and according to the logs the culprit is [`runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR 1.0.2-rc3-24018-00`](https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc3-24018-00) being corrupt. (We really need to get better logs from CI... or is there already a way to grab the `sync.log` that I haven't seen?)

This has happened before in the TFS build on the internal share, and @weshaggard fixed it. I'll try out a "fresh" copy from the network share build drop on my mac to see if it works and update MyGet if so, but otherwise uptaking newer packages would probably fix it.

**Comment by dagood** [comment] 2016-04-20 15:51
Interesting, now it looks like this is the same symptom, but a different cause. The shasum of the packages are the same, and restore succeeds on an independent project with only this one dependency. After trying that out, though, the sync.sh succeeds on a second try. (Without clearing the cache.) When I clear the cache and packages dir and try again, it succeeds again.

So it would seem that having old packages in the cache causes this... but that really shouldn't be a problem as far as I know. @ericstj, any ideas?

**Comment by ericstj** [comment] 2016-04-20 16:21
So you are seeing this issue when a machine has some old packages in the cache and you restore?

I could imagine if some project is not getting an exact match version NuGet would enumerate local packages to determine if any of those packages were a better match than what it finds on feeds.

If you have a reliable repro you could debug.  Error is coming from here: https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/ZipArchive.cs#L593

**Comment by dagood** [comment] 2016-04-20 19:05
Ah, good call. My version mismatch tool came up with these (on a bunch of lockfiles):

```
Desired version NETStandard.Library 1.0.0-rc3-24018-00 not restored, found '1.5.0-rc2-23911'
Desired version System.Linq.Expressions 4.0.11-rc3-24018-00 not restored, found '4.0.11-rc2-23923, 4.1.0-rc3-24018-00'
Desired version System.Net.Http 4.0.1-rc3-24018-00 not restored, found '4.1.0-rc3-24014-01'
Desired version System.Runtime.WindowsRuntime 4.0.0 not restored, found '4.0.10'
Desired version System.Security.Principal 4.0.0-rc3-24018-00 not restored, found '4.0.0'
Desired version System.Text.RegularExpressions 4.0.12-rc3-24018-00 not restored, found '4.0.12-rc2-23923, 4.1.0-rc3-24018-00'
```

I was able to force a repro by deleting some stuff from the beginning and end of the `nupkg_System.Runtime.InteropServices.PInvoke.4.0.0-rc3-24015-00.dat` file (although I imagine other files would work fine too).

Fixing the dependency versions fixed the error, so I'll put up a PR.

**Comment by ericstj** [comment] 2016-04-20 19:11
Cool.  Need that tool in the build :wink:

**Comment by dagood** [comment] 2016-04-20 19:21
Yeah, definitely. One thing that's been holding me back is https://github.com/dotnet/buildtools/issues/517 but this has been enough of a problem that I think I should bring in the Json.NET that I have and we can convert it to a project model later.

**Comment by weshaggard** [comment] 2016-04-20 20:32
I agree we should get this added to our package validation tasks.

**Comment by stephentoub** [comment] 2016-04-21 02:15
This appears to be failing the OSX legs of every PR.  Will this be fixed soon?

**Comment by dagood** [comment] 2016-04-21 14:36
@stephentoub This will be fixed with https://github.com/dotnet/corefx/pull/7931. I'm currently redoing it because basically every project.json was conflicting but luckily those changes are tooled so it will be done this morning.

**Comment by stephentoub** [comment] 2016-04-21 14:38
Thanks, @dagood.  The project.json conflicts are because of https://github.com/dotnet/corefx/pull/7945?  @ericstj asked me to revert that, so there's a PR at https://github.com/dotnet/corefx/pull/7951 doing that.  Up to you whether you want that revert PR merged or closed, whatever's easier for you.  Thanks for fixing this.

**Comment by bartonjs** [comment] 2016-04-21 17:13
@dagood I saw this same failure again after you had your fix in.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/77/consoleFull#205152537279494335-f7bd-47d0-8771-8661e00c2db2

> 09:14:01 EXEC : error : End of Central Directory record could not be found. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/build.proj]

**Comment by stephentoub** [comment] 2016-04-21 18:29
This is still happening across multiple PRs.

**Comment by dagood** [comment] 2016-04-21 18:33
Dang, ok, I'm looking at this again.

**Comment by ericstj** [comment] 2016-04-21 18:44
Davis, your earlier investigation found that you could reproduce this by truncating NuGet's HTTP cache.  We know NuGet is not resilient to that.  It's going to go to the HTTP cache in all cases.  We were also seeing the same error if a random nupkg in the packages folder was truncated.  Your fix to ensure exact version fixed that but not the HTTP cache.

Perhaps we just need to clear NuGet's HTTP cache on these machines to let them get past this?

**Comment by dagood** [comment] 2016-04-21 18:54
Ah, yep, and I'm realizing now that I may have just gotten lucky with which OSX node my PR's OSX Debug run used. I agree, clearing the caches is the way to go for now.

**Comment by ericstj** [comment] 2016-04-21 18:58
@mmitche can you help with this?

**Comment by dagood** [comment] 2016-04-21 19:47
In my attempts to repro this, if I actually corrupt the cache entry the restore wants to install, it handles it correctly like this:

```
info :   CACHE https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.IO/4.1.0-rc3-24020-00
warn : An invalid cache entry was found for URL 'https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.IO/4.1.0-rc3-24020-00' and will be replaced.
warn : The nupkg at 'https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.IO/4.1.0-rc3-24020-00' is not valid.
warn :   End of Central Directory record could not be found.
info :   GET https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.IO/4.1.0-rc3-24020-00
info :   OK https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.IO/4.1.0-rc3-24020-00 6063ms
```

That's with a simpler project.json, but the same thing happens when I try to corrupt packages for the corefx restore. (Running restore using `./build.sh`.)

I'm going to try taking down dci-macpro-02 leniently to repro. I think we really need some way in the build to get restore logs.

**Comment by mmitche** [comment] 2016-04-21 20:14
@ericstj What do you need me to do?

**Comment by ericstj** [comment] 2016-04-21 20:20
We need to delete the HTTP caches on the mac machines.  On windows these are under %LOCALAPPDATA%\NuGet, and can be deleted with nuget.exe locals all -clear.  Not sure how to do so on Mac.  Let's make sure @dagood is in the loop so we don't blow away his repro.

**Comment by dagood** [comment] 2016-04-21 20:20
I'm not actually sure anymore that the problem is the cache anymore--it looks like the CI actually sets a temp `home` dir so the cache isn't kept from run to run anyway.

@mmitche We were hoping you could clear the caches but I'm not sure that would help anymore. I'm investigating on dci-macpro-02.

**Comment by dagood** [comment] 2016-04-21 21:20
Well, it looks like upgrading the CLI fixes it. For completeness though, here's some stuff about the problem that seems to tell me that it was a threading issue:

I got a [solid restore repro on the build machine with verbose logging](https://gist.github.com/dagood/0978b7844bd73384268b7236979e3d51). It's a different package each time, but always terminates within about 10 seconds. I haven't been able to repro on my own machine. [It has also errored with a `FileNotFoundException`](https://gist.github.com/dagood/cbc95d4a148ef733ab8e822bea2db961) Clearing the cache does nothing. Running with `--disable-parallel` takes a very long time but it doesn't crash. But upgrading the CLI lets the restore succeed.

Putting up a PR very shortly.

**Comment by dagood** [comment] 2016-04-22 15:49
It looks like we're getting good OSX builds now, closing. :smile:

For anyone who hasn't seen it already, here's the issue for making CLI auto-upgrade like the package dependencies: https://github.com/dotnet/corefx/issues/7952. (Will help avoid wasting time debugging things like this in the future... and help find any actual restore bugs in new versions of CLI.)

**Closed by dagood** 2016-04-22 15:49 UTC
Labels: blocking-clean-ci
