### ISSUE TITLE
HttpClient: HTTPS requests fail in .NET Core 2.1 under proxy

### ISSUE THREAD

**Issue by talanc** [dotnet/corefx#30587] opened 2018-06-22 00:05 UTC
HTTPS requests fail on .NET Core 2.1 under a proxy, the response is a 407 proxy required error.

I've made a repo demonstrating it working under netcore20 and not under netcore21: https://github.com/talanc/dotnetcore-proxytest
You need to be in a proxy environment for netcore21 to fail.

Background: I was in the process of converting an ASP.NET Core 2.0 application to 2.1 and I saw 1 of my tests fail when moving the target framework from netcore20 to netcore21 (no code changes). I thought it was a bit odd because I have two very similar tests with the only difference being 1 does a HTTP GET and the other does HTTPS GET.

Environment: I'm running Windows 7 (x64) under a corporate network proxy.

I'm willing to help with testing potential fixes and workarounds.

**Comment by davidsh** [comment] 2018-06-22 00:09
This is probably a dupe of #30330

**Comment by davidsh** [comment] 2018-06-22 03:40
>Will this get a fix in a 2.1.X update?

Yes, we plan to put this into a servicing release of 2.1 in the next few months.

**Comment by karelz** [comment] 2018-06-23 01:40
Closing as dupe of #30330

@talanc if you can verify on our daily builds (see [how](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md)) that it is addressed, it would help us a lot!

**Closed by karelz** 2018-06-23 01:40 UTC
Labels: area-System.Net.Http

**Comment by davidsh** [comment] 2018-06-25 00:57
That exception is bug #30327.    Now that you have a fix for #30330, you are getting an exception due to your proxy server closing the first connection after the 407 response.  That is issue #30327 which has not yet been fixed.
