### ISSUE TITLE
HttpClient Connection Reset By Peer when using HttpClientExtensions

### ISSUE THREAD

**Issue by arielmoraes** [dotnet/corefx#35505] opened 2019-02-21 21:27 UTC
Tested using .NET Core Versions 2.1 and 2.2

We have a `HttpClient` that makes some requests using the `PostAsJsonAsync ` and `PutAsJsonAsync ` from the `HttpClientExtensions` in the `System.Net.Http.Formatting` assembly but in some cases we are getting an exception with a message saying the Connection was reset by peer. The Stack Trace we have is:

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
> --- End of inner exception stack trace ---
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
> at System.Net.Http.HttpConnection.FillAsync()
> at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
> at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
> --- End of inner exception stack trace ---
> at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
> at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
> at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

Now the strange and unbelievable solution we happen to achieve is to create a dummy Handler that just prints the Request and Response content to the ILogger as follows:

```csharp
public class LoggingHandler : DelegatingHandler
{
	ILogger<TenantSeeder> logger;

	public LoggingHandler(HttpMessageHandler innerHandler, ILogger<TenantSeeder> logger)
		: base(innerHandler)
	{
		this.logger = logger;
	}

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		logger.LogTrace("Request:");
		logger.LogTrace(request.ToString());
		if (request.Content != null)
		{
			logger.LogTrace(await request.Content.ReadAsStringAsync());
		}

		HttpResponseMessage response = await base.SendAsync(request, cancellationToken);

		logger.LogTrace("Response:");
		logger.LogTrace(response.ToString());
		if (response.Content != null)
		{
			logger.LogTrace(await response.Content.ReadAsStringAsync());
		}

		return response;
	}
}
```

When using that Handler the request completes successfully. 

Some more info: the connection is using SSL and when called directly from Postman it works as expected and the JSON being sent is very simple: 

```csharp
var response = await httpClient.PostAsJsonAsync("api/tenants", new
{
	Name = tenant.CompanyName,
	UniqueName = uniqueName,
	ClientId = uniqueName,
	ClientSecret = $"{uniqueName}secret",
	Enabled = tenant.IsActivated
})
```

**Comment by khaledsobhy83** [comment] 2019-07-12 16:57
Are there any updates on this? I am having the same problem, getting random connection reset by peerer when there are many requests to an api hosted on IIS. Till now I could not find the root cause.

**Comment by fredericaltorres** [comment] 2019-08-06 01:43
Same problem here when I run my code on a 4 core Linux azure vm, one a 2 cores vm things seems ok

**Comment by karelz** [comment] 2019-10-08 21:14
Triage: It looks like server closed the connection.
To make it actionable we need either a repro, or traces. Trying out 3.0 might be good first step.
Closing for now, we can reopen when there is tracing (Wireshark) or repro available.

**Closed by karelz** 2019-10-08 21:14 UTC
Labels: area-System.Net.Http

**Comment by ndphuong** [comment] 2019-12-11 02:32
I face the same problem too, I think it is big problem of Net Core 3.0
