### ISSUE TITLE
System.Uri(string uriBase, string uriRelative) does not work properly if uriRelative contains special characters

### ISSUE THREAD

**Issue by sepidehkh** [dotnet/corefx#14750] opened 2016-12-28 19:58 UTC
[This test](https://github.com/dotnet/corefx/blob/a7d6c2c5fbf870092535b6e70e25c97c2187f959/src/System.Private.Xml/tests/Xslt/XslCompiledTransformApi/XslCompiledTransform.cs#L3877) fails on Linux with error: `"System.ArgumentOutOfRangeException : Length cannot be less than zero"`

Here's a smaller repro of the issue on Linux (defining `XmlNullResolver` locally):
```
string uriRelative = "Stra%C3%9Fe.xml";
Uri uriResolved = XmlNullResolver.Singleton.ResolveUri(null, uriRelative);
Console.WriteLine("uriResolved = " + uriResolved);
```

which results in the following failure:
```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
Stack trace:
     at System.String.Substring(Int32 startIndex, Int32 length)
     at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
     at System.Uri.CreateHostString()
     at System.Uri.GetComponentHelper(UriComponents uriComponents, UriFormat uriFormat)
     at System.Uri.ToString()
     at System.String.Concat(Object arg0, Object arg1)
.../corefx/src/System.Private.Xml/tests/Xslt/XslCompiledTransform.cs(3394,0): at System.Xml.Tests.CTransformRegressionTest.RegressionTest1(XslInputType xslInputType, ReaderType readerType, OutputType outputType, NavType navType)
```

Please note that the presence of special character in `uriRelative` is causing this failure.

**Comment by nikitozz** [comment] 2017-02-22 22:48
Actually, the issue is not related to special characters. It might be related to the way CLR handles `ref` parameters on Lunix\Unix.

Here is a simple code snippet:
```
Uri baseUri = new Uri("file:///home/nikita/file1.txt");
Uri relativeUri = new Uri("file2.txt", UriKind.RelativeOrAbsolute);
Uri newUri = new Uri(baseUri, relativeUri);
```

1. I put a breakpoint on line 3, stepped into the `Uri` constructor, and reached the following line: `CreateThis(newUriString, dontEscape, UriKind.Absolute)` (https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/Uri.cs#L525). At this point, `_flags` value is `0` (assigned on line 522).
2. I stepped into `CreateThis(newUriString, dontEscape, UriKind.Absolute);` and reached the following line:  `ParsingError err = ParseScheme(_string, ref _flags, ref _syntax);` (https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/UriExt.cs#L31). `_flags` value is still `0`, and it's passed as a ref parameter to  `ParseScheme(_string, ref _flags, ref _syntax)`.
3. I stepped into `ParseScheme` and reached the following line: `return ParsingError.None;` (https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/Uri.cs#L1976). `flags` value, which is our ref parameter for `_flags`, is `5` at this point.
4. I stepped out of `ParseScheme`. But now `_flags`, that is supposed to get a value of `5`, gets `3221225472` instead.

The issue is reproducible only in Linux, the same code works as expected on Windows.

**Comment by danmosemsft** [comment] 2017-02-23 07:58
@jkotas the above observation seems odd. Thoughts?

**Comment by jkotas** [comment] 2017-02-23 14:30
Sounds like a JIT bug. cc @dotnet/jit-contrib

**Comment by nikitozz** [comment] 2017-02-24 01:16
Actually, might be debugger related. I observe this behavior only when I'm debugging using VS Code. Not reproducible when `lldb` is used.

**Comment by pjanotti** [comment] 2018-07-24 22:53
Issue didn't repro for the test nor for the code on the first comment, closing the issue.

**Closed by pjanotti** 2018-07-24 22:53 UTC
Labels: area-System.Runtime, bug, disabled-test, os-linux, up-for-grabs
