### ISSUE TITLE
transactionScope Error. Enlisting in Ambient transactions is not supported

### ISSUE THREAD

**Issue by paulmctigue** [dotnet/corefx#24374] opened 2017-10-02 14:36 UTC
> Enlisting in Ambient transactions is not supported

I get this error when dedugging the code below in .net core 2 console app on my win 10 PC with VS 2017 15.3.2 (System.Data.SqlClient v4.4.0)

```
using (TransactionScope scope = new TransactionScope())
{
  using (SqlConnection connection1 = new SqlConnection(_configuration["ConnectionString"]))
  {
    connection1.Open();
  }
  scope.Complete();
}
```
Transactionscope is part of the .net standard 2 and the code above was taken from microsoft's documentation https://docs.microsoft.com/en-gb/dotnet/api/system.transactions.transactionscope?view=netcore-2.0

**Comment by paulmctigue** [comment] 2017-10-02 15:46
oh is this same issue as #24282 
https://github.com/dotnet/corefx/issues/24282

**Comment by karelz** [comment] 2017-10-02 15:57
Closing as duplicate of #24282 in that case.

**Closed by karelz** 2017-10-02 15:57 UTC
