### ISSUE TITLE
System.IO.Pipelines.Tests.CopyToAsyncTests/MultiSegmentWritesUntilFailure

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#36800] opened 2019-04-11 21:38 UTC
cc: @pakrym @davidfowl 

This test seem to be intermittently failing on netfx (full framework) queues (i.e. `Windows.10.Amd64.ClientRS5.Open-x86-Release`):

```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Pipelines.Tests.CopyToAsyncTests.<MultiSegmentWritesUntilFailure>d__5.MoveNext() in D:\a\1\s\src\System.IO.Pipelines\tests\PipeReaderCopyToAsyncTests.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

i.e. https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36775~2Fmerge/test~2Ffunctional~2Fcli~2F/20190411.35/workItem/System.IO.Pipelines.Tests/analysis/xunit/System.IO.Pipelines.Tests.CopyToAsyncTests~2FMultiSegmentWritesUntilFailure

**Comment by davidfowl** [comment] 2019-04-11 22:53
I’ll take this I know what the problem is

**Comment by davidfowl** [comment] 2019-04-13 14:46
Closing this as it should be fixed.

**Closed by davidfowl** 2019-04-13 14:46 UTC
Labels: area-System.IO.Pipelines
