### ISSUE TITLE
Can't open XML

### ISSUE THREAD

**Issue by makarychev13** [dotnet/corefx#27901] opened 2018-03-09 17:13 UTC
Hello. I'm trying to open XML with this code:
`XDocument File = XDocument.Load(FileName); //FileName = "SomeFile.xml"`
Unfortunately I am getting an error ArgumentOutOfRangeException: Index and count must refer to a location within the string.

What am I doing wrong?

P.S. Windows 8
ASP.NET Core 2.0
.NET Framework 4.6.1

**Comment by stephentoub** [comment] 2018-03-09 17:24
Can you share the XML file that's producing the error, as well as the full details of the exception you get, e.g. stack trace?

**Comment by makarychev13** [comment] 2018-03-09 17:28
https://pastebin.com/MUk49kLV - XML
http://prntscr.com/iozdn1 - stack trace

**Comment by danmosemsft** [comment] 2018-03-09 18:10
Looks like https://github.com/dotnet/corefx/issues/26210

@makarychev what is the URL you are passing to XDocument.Load literally just "SomeFile.xml"? What is the directory of that file, does it have diacritics in it? If so does it work OK if you just put it in a folder like c:\test ?

**Comment by danmosemsft** [comment] 2018-03-09 18:10
@rmkerr

**Comment by makarychev13** [comment] 2018-03-09 18:29
string FileName = "freelance.ru.xml"
Path.GetFullPath(FileName) = "C:\\Users\\Михаил\\source\\repos\\Notify\\Notify\\freelance.ru.xml"

This code with absolute path is working:
`string FileName = "SomeFile.xml"
XDocument File = XDocument.Load(Path.GetFullPath(FileName)); `

But in [msdn example](https://msdn.microsoft.com/ru-ru/library/bb343181(v=vs.110).aspx) a relative path is used

**Comment by rmkerr** [comment] 2018-03-09 18:35
This does look like a duplicate of #26210. I think that there must be an issue with how we parse Unicode in file paths. It may be resolved in the 2.1 pre-release but I have not verified that yet.

**Comment by makarychev13** [comment] 2018-03-09 18:38
Thank you!

**Closed** 2018-03-13 21:18 UTC
Labels: area-System.Xml
