### ISSUE TITLE
Some packages need to be built in source build

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/corefx#39793] opened 2019-07-26 01:22 UTC
As part of the investigation at https://github.com/dotnet/source-build/issues/1132. We need two packages to be built by corefx in source build:

1. System.Diagnostics.EventLog
2. System.Security.Cryptography.Xml
3. System.IO.Pipelines
4. System.Security.Cryptography.Pkcs
5. System.Security.Permissions

These packages are not included in the Microsoft.NETCore.App shared framework but is included in the Microsoft.AspNetCore.App shared framework. CoreFx will need to build these packages in source build so AspNetCore can consume them.

This is orthogonal to https://github.com/dotnet/corefx/issues/39787 but is required to remove two prebuilts from Extensions.

cc @crummel @dseefeld @nguerrera

**Comment by ViktorHofer** [comment] 2019-07-26 08:36
cc @ericstj

**Comment by ericstj** [comment] 2019-07-26 16:31
I agree the cause of this is not the same as #39787 but the work is the likely the same.  You need some libraries that aren't part of the base shared framework in order to make source-build work.  @JunTaoLuo I see ASPNET also uses the following, do you need these too?

System.IO.Pipelines
System.Security.Cryptography.Pkcs
System.Security.Permissions

**Comment by JunTaoLuo** [comment] 2019-07-26 19:05
Ah yes, I didn't look at AspNetCore dependencies when I compiled the list. I updated the top comment.

**Comment by ericstj** [comment] 2019-08-05 17:14
We should handle this as follows:
1. Build a small set of packages only during source build.
2. Set BuildPackageLibraryReferences=false so that we do not attempt to build more project configurations than source build already builds (since those configurations would require more prebuilts).
2. Set AllowPartialPackages=true so that we omit anything that wasn't built.
3. (potentially) Include more configurations into package so that we satisfy the configurations that folks upstack need: for instance have packages include BuildConfigurations rather than just PackageConfigurations.

I'll put together a PR that does this.

**Comment by nguerrera** [comment] 2019-08-06 15:09
These are getting flagged as prebuilt on dotnet/toolset and I think need to added as part of this

System.CodeDom
System.Security.Cryptography.ProtectedData

System.Text.Encoding.CodePages is also getting flagged, but I can remove that now that it is in shared framework.

**Comment by nguerrera** [comment] 2019-08-06 15:57
I might need a System.Text.Encoding.Extensions after all so that I can reference it with ExcludeAssets. It needs to be greater than all the versions referenced by components in the toolset that target netcoreapp2.1. It could be reference only, but I think it would be simpler to build it as part of this.

**Comment by ericstj** [comment] 2019-08-06 16:30
The fix for this will enable all packages to build as partial packages.  It's not particularly useful to cherry-pick package since we can use a general approach to build everything and not have to worry about getting all transitive dependencies.

**Comment by JunTaoLuo** [comment] 2019-08-07 02:55
Also, it seems like we will need Microsoft.Win32.Registry to be built as well. This is a package that we need only for compilation (which is why I missed it the first time around) since it's included in the shared framework but not the ref pack. By the way why is this missing from the ref pack anyway?

**Comment by ViktorHofer** [comment] 2019-08-07 07:47
Probably because of https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.Registry/Directory.Build.props#L7. @ericstj can provide more details on this as he made the change three years ago.

**Comment by ericstj** [comment] 2019-08-07 19:48
Yep this will be addressed. We don’t expose some assemblies as default references because we don’t want them available by default since they aren’t supported on all platforms. It’s expected that you need to reference the package to get a reference.

**Comment by ericstj** [comment] 2019-08-07 23:36
Fixed in #40061

**Closed** 2019-08-12 16:35 UTC
Labels: area-Infrastructure
