### ISSUE TITLE
ValueTuple in desktop 4.6 app clashes with that of mscorlib 4.7

### ISSUE THREAD

**Issue by jcouv** [dotnet/corefx#16195] opened 2017-02-15 18:01 UTC
Repro:
1. Make a trivial app targeting 4.6 involving tuples (you must add a reference to ValueTuple package)
2. On a machine with 4.7 installed, try to debug that program
3. The program runs fine, with modules listed below (ValueTuple.dll from the corefx package included in the app, mscorlib.dll from desktop 4.7)
4. In the EE (Immediate Window, Watch, QuickWatch) type something that involves tuple syntax
This will give an error CS8179, because the compiler found two instances of the well-known type (that is ambiguity).

![image](https://cloud.githubusercontent.com/assets/12466233/22987819/f5db50b6-f364-11e6-9bc2-051b4781a2e4.png)

```
(1, 2)
error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
t = (1, 2)
error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported
```

```C#
        static void Main(string[] args)
        {
            (int first, int second) t = (1, 1);
            while(true)
            {
                Thread.Sleep(1000);
                Console.WriteLine(t.first);
                t.first++;
            }
        }
```

FYI @tmat @VSadov @cston @AlekseyTs

**Comment by tmat** [comment] 2017-02-15 18:06
A fix would be to include System.ValueTuple.dll in .NET Framework 4.7 that type-forwards all types to mscorlib and add it to GAC. When loading System.ValueTuple the loader would prefer this library over the one in the app dir. So there would be no duplicates loaded and EE wouldn't pick it up.

**Comment by tmat** [comment] 2017-02-15 18:09
Issue https://github.com/dotnet/roslyn/issues/17157 has the same root cause.

**Comment by jcouv** [comment] 2017-02-15 18:17
Discussed with @weshaggard 
If we made a change to desktop 4.7 to have type unification to System.ValueTuple.dll version 4.0 (type unification only cares about major and minor version), then we'd introduce another problem.
System.ValueTuple.dll 4.0.1.1 has `ITuple`, but desktop 4.7 doesn't.
An app that used `ITuple` on desktop 4.6 would lose it when loaded on a machine with 4.7. (Maybe that isn't so bad?)
I'm going to explore an EE/compiler solution and I'll get back with some findings.

**Comment by tmat** [comment] 2017-02-15 18:46
Why doesn't 4.7 have ITuple? Can we add it?

**Comment by jcouv** [comment] 2017-02-15 18:49
I shiproom rejected the ITuple PR when I made it (a few days past code complete alas), so I doubt they would take it now. 
@weshaggard Let me know if I'm being too pessimistic.

**Comment by tmat** [comment] 2017-02-15 18:49
The shiproom didn't know we have a bigger problem.

**Comment by tmat** [comment] 2017-02-15 18:52
If the compiler resolved the ambiguity by picking the type from mscorlib, wouldn't we have the same problem with ITuple? That EE wouldn't see ITuple, so expression evaluation would behave differently than the application code. That would be confusing for the user.

**Comment by jcouv** [comment] 2017-03-30 22:59
Ping @weshaggard This is the issue I mentioned, which will require work in desktop 4.7.1 (to the GAC and type unification), but not to corefx itself.

**Comment by jcouv** [comment] 2017-03-30 23:07
Relates to https://devdiv.visualstudio.com/DevDiv/_workitems?id=275242

**Comment by danmosemsft** [comment] 2017-04-18 17:37
@AlexGhiondea is this going to be part of what you're doing? 
Also should you move it to the desktop bug tracker?

**Comment by AlexGhiondea** [comment] 2017-04-19 02:06
Yes it is. And there is no need for an additional issue -- i am handling this as part of a larger work item.

**Comment by ericstj** [comment] 2017-04-25 20:02
I believe I've also addressed this in the NETStandard.Support package.  Closing this.

**Closed by ericstj** 2017-04-25 20:02 UTC
Labels: area-System.Runtime, bug
