### ISSUE TITLE
Core Class Library pointed to .Net standard 1.0 throws GuidAttribute failure 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/corefx#7869] opened 2016-04-19 17:54 UTC
Repro Steps 
- Create a Core Class Library 
- By default the project.json will point to netstandard1.5 change that to netstandard1.0 

Expected 
Builds successfully 

Actual 
![grid](https://cloud.githubusercontent.com/assets/12449387/14649682/0bb0b286-061d-11e6-8956-f29897a46b3f.JPG)

**Comment by ericstj** [comment] 2016-04-26 19:25
GuidAttribute is part of System.Runtime.InteropServices which is only supported in netstandard1.1 and higher.  What CS file is including GuidAttribute?  That may need to be fixed in the template.

**Comment by ericstj** [comment] 2016-04-26 20:40
Found the cause, this is coming from Properties\AssemblyInfo.cs:
```
// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("692790bf-cd5c-4c9b-86a0-927a5e13d923")]
```

That should be remove the project template.  In fact most of the stuff in AssemblyInfo.cs should probably be removed since it looks like this is redundant to info in the project.json.

@Pilchie is this something you own?

**Comment by Pilchie** [comment] 2016-04-26 21:39
Yes.  +rchande.  I think we decided not to fix for U2, given that you have to retarget down manually however.

**Comment by ericstj** [comment] 2016-04-27 16:22
@rchande do you have an issue tracking this in for the VS templates?  If so we'll close this one.

For folks that hit this, they can workaround by deleting assemblyinfo.cs from the project.

**Comment by ericstj** [comment] 2016-04-27 22:48
I've opened TFS bug 217061 on the templates to fix this.

**Closed by ericstj** 2016-04-27 22:48 UTC
Labels: question
