### ISSUE TITLE
Failure in System.Net.Http.Functional.Tests

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#27834] opened 2018-03-07 23:58 UTC
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/9469/consoleFull

```
System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed(maxConnections: 2, numRequests: 2, secure: False) [FAIL]
12:06:05         System.Threading.Tasks.TaskCanceledException : A task was canceled.
12:06:05         Stack Trace:
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:06:05              at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
12:06:05           --- End of stack trace from previous location where exception was thrown ---
12:06:05              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:06:05              at System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.<GetAsync_MaxLimited_ConcurrentCallsStillSucceed>d__3.MoveNext()
12:06:05           --- End of stack trace from previous location where exception was thrown ---
12:06:05              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:06:05           --- End of stack trace from previous location where exception was thrown ---
12:06:05              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:06:05           --- End of stack trace from previous location where exception was thrown ---
12:06:05              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
12:06:05              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12:06:05     Finished:    System.Net.Http.Functional.Tests

```

**Comment by davidsh** [comment] 2018-03-08 00:58
Duplicate of #26092

**Closed by davidsh** 2018-03-08 00:58 UTC
Labels: area-System.Net.Http
