### ISSUE TITLE
Trouble consuming System.ComponentModel.Annotations 4.5.0 in Powershell

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#33107] opened 2018-10-29 16:47 UTC
Filing an issue on behalf of a user who emailed 'Contact Owners' on https://www.nuget.org/packages/System.ComponentModel.Annotations/

> **_sends the following message to the owners of Package 'System.ComponentModel.Annotations 4.5.0'._**
The version on lib\netstandard2.0\System.ComponentModel.Annotations.dll is 4:2:1:0 The version on ref\netstandard2.0\System.ComponentModel.Annotations.dll is 4:2:0:0
Is this intended? I had problems consuming dlls built using this package in Powershell and had to use a lower version.

cc: @lajones, @divega, @ajcvickers

**Comment by ajcvickers** [comment] 2018-10-29 17:09
See also https://github.com/aspnet/EntityFrameworkCore/issues/13268 and https://github.com/dotnet/standard/issues/450

**Comment by ajcvickers** [comment] 2019-02-22 23:06
Closing as dupe of https://github.com/dotnet/corefx/issues/33643

**Closed by ajcvickers** 2019-02-22 23:06 UTC
Labels: area-System.ComponentModel.DataAnnotations, packaging
