### ISSUE TITLE
Allow BitConverter.ToString to format without dashes

### ISSUE THREAD

**Issue by nvivo** [dotnet/corefx#519] opened 2015-01-24 11:23 UTC
I think BitConverter is not even in CoreFx yet, but for when it is, please allow to convert to an hex string without dashes. This is to avoid this pattern: 

```
BitConverter.ToString(data).Replace("-", string.Empty);
```

This representation of bytes is common enough that .NET should have a simple method to do this without extra code or an extra memory allocation.

**Comment by ebickle** [comment] 2015-02-02 17:53
BitConverter needs a lot of work, potentially a new API altogether. It's once place that desperately needs both Little Endian and Big Endian support. The number of lacks on StackOverflow with people trying to flip the order of their byte arrays before calling BitConverter methods is truly frightening.

**Comment by zii-dmg** [comment] 2015-02-02 19:37
Maybe .NET Core should include [DataConverter class](https://github.com/mono/mono/blob/master/mcs/class/corlib/Mono/DataConverter.cs) from Mono?

**Comment by Eirenarch** [comment] 2015-03-09 08:17
I agree with @ebickle . I just ran into the little endian vs big endian issue 2 days ago. Also I think we should have a way to convert a hex string to a byte array. I mean the Convert class has methods to convert to/from base64 but for hex you have to roll your own method and it makes no sense to me.

**Comment by CodesInChaos** [comment] 2015-09-16 17:30
I'd add these methods to `Convert`:

    public static string ToHexStringUpper(byte[] data);
    public static string ToHexStringLower(byte[] data);
    public static byte[] FromHexString(string hexString);

I'd also consider having them return `null` when the argument is `null` since that simplifies printing byte arrays that may be `null`.

**Comment by fujiy** [comment] 2016-11-28 12:09
I plan to work on it

**Comment by fujiy** [comment] 2016-12-14 15:51
Hi, I'll work on it.
@karelz would you assign me please?

**Comment by karelz** [comment] 2016-12-14 16:46
The API is not approved yet, so we won't assign it to anyone.

Next step: We need formal API proposal.

**Comment by andreujuanc** [comment] 2017-06-05 22:51
+1 to this. So simple yet really good.

**Comment by danmosemsft** [comment] 2017-06-05 23:15
@andreujuanc do you want to take a shot at formalizing the format? Link to a good example from this doc.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by andreujuanc** [comment] 2017-06-05 23:19
@danmosemsft Sure. But I would like to have a small discussion if possible. Gitter, slack, or should we keep everything in here?

**Comment by danmosemsft** [comment] 2017-06-05 23:33
We tend to keep stuff in here because otherwise it doesn't scale well. If you have alternatives or other proposals etc feel free to share them here or pick one suggestion for others to give feedback.

**Comment by mpollock11p** [comment] 2018-03-19 19:49
I'm new at this but this sure helped out a hole lot!  I was trying to get a whole packet out and don't know why anyone would even want the dashes in there??  Thanks much!!

**Comment by jeremyVignelles** [comment] 2019-04-10 09:51
Is it a duplicate of #10013 or am I missing something?
That issue has a formal API defined and offers methods for the reverse conversion.

**Comment by mfalkvidd** [comment] 2019-04-10 10:00
@jeremyVignelles 10013 was created 1.5 years after this issue was created, and has a significantly larger scope. The larger scope might delay implementation and might therefore be a less desirable solution. But if 10013 was implemented, it would solve this issue as well.

**Comment by stephentoub** [comment] 2019-09-09 00:43
@mfalkvidd, valid concerns.  At the same time, more recent forward progress has been made on that issue and not on this one, and we don't need two issues covering the same scope, so I'm going to close that one. Thanks, all.

**Closed by stephentoub** 2019-09-09 00:43 UTC
Labels: api-needs-work, area-System.Runtime.Extensions, up-for-grabs

**Comment by mfalkvidd** [comment] 2019-09-09 08:42
20 days ago the "api-ready-for-review" label was removed from 10013, calling for a survey to be conducted. Since then it seems like nothing has happened. That doesn't sound like forward progress to me ;-)

But if you can make things happen in 10013, please do. I'm just worried it will be mothballed.

**Comment by stephentoub** [comment] 2019-09-09 11:35
> That doesn't sound like forward progress to me

It's been looked at and talked about, leading to that status change. That's more than had happened here.

>  I'm just worried it will be mothballed

If it doesn't happen, this one wouldn't either. Deciding to go ahead with an issue doesn't mean it's done exactly as outlined; it effectively represents a desire to explore the space further, whch could mean doing more or less than is described, or something different entirely.
