### ISSUE TITLE
Support for Rijndael encryption

### ISSUE THREAD

**Issue by adsolutbe** [dotnet/corefx#12064] opened 2016-09-26 08:44 UTC
I need to port some existing code that uses Rijndeal encryption to .net core. Unfortunately, Rijndeal encryption (RijndaelManaged class) with a blocksize key of 256 bit is not available for .net core. Any idea's when and if this will be made available?

**Comment by lextm** [comment] 2016-09-26 10:02
Related to #9984 so you might check that out first.

**Comment by karelz** [comment] 2016-09-26 15:40
Closing as dupe of #9984.

**Closed by karelz** 2016-09-26 15:40 UTC

**Comment by bartonjs** [comment] 2016-10-03 16:32
@adsolutbe Rijndael will only be supported with a block size of 128 in .NET Core (the RijndaelManaged type will only compute AES).  We're not maintaining managed implementations of algorithms any longer, and neither of our native implementation providers have support for Rijndael (except when it's AES).

**Comment by Looooooka** [comment] 2017-09-18 11:01
Well this just sucks.

**Comment by whoisj** [comment] 2017-09-18 13:58
@adsolutbe , @Looooooka may I introduce you to [OpenSSL](https://github.com/openssl/openssl)?

**Comment by Looooooka** [comment] 2017-09-18 14:08
The problem for me is we have a lot of data encrypted using the 256 bit blocksize option.
So now I'll have to somehow load/call a standard. net lib to access the data or decrypt and encrypt everything using 128 bit blocksize.
Needless to say I am not a happy camper. Was kinda hoping someone would have created their own provider with 256 blocksize support but I can see I'll just have to sell option 1 or 2.
This is the sort of thing that could have management pull the plug on our transition to .net core.
Oh well.
Life :)

**Comment by karelz** [comment] 2017-09-18 14:51
@Looooooka did you look at alternative crypto implementations like BouncyCastle? Based on your comments, it may satisfy your needs.

**Comment by Looooooka** [comment] 2017-09-18 15:04
No but thank you very much!! 
Will have a look tomorrow.
I'd rather just rewrite the code than deal with all that data :)

**Comment by niemyjski** [comment] 2017-12-28 17:38
I get that we probably shouldn't of been using 256 blocksize or this encryption in general. But this really sucks and now I have to have a migration for all existing encrypted values.

**Comment by jnm2** [comment] 2017-12-29 17:06
Why doesn't .NET Core support whatever block size the native implementation does? Or doesn't CNG support any block size but 128?

**Comment by Looooooka** [comment] 2017-12-29 17:11
As suggested above I switched to BouncyCastle and since the code works for. NET and core life is good again. There was no need to change the existing encrypted entries at all :)

**Comment by niemyjski** [comment] 2017-12-29 17:18
@Looooooka Would you mind sharing the code you used for .NET Core for 256bit. I tried for a few hours to convert my encrypt and decrypt with bouncy and a different library but failed.

**Comment by bartonjs** [comment] 2017-12-29 20:21
> Why doesn't .NET Core support whatever block size the native implementation does?

That's what the situation is.  CNG, OpenSSL, and Security.framework all support AES, none of them support Rijndael (except for Rijndael with a 128-bit block, which is AES).

.NET Framework has a managed implementation of the Rijndael algorithm.  .NET Core does not.

**Comment by jnm2** [comment] 2017-12-29 20:31
@bartonjs So I'm looking at the first entry under CNG Cryptographic Algorithm Providers:

Name | Supported modes | Key size in bits (Default/Min/Max)
:-- | :-- | :--
Advanced Encryption Standard (AES) | ECB, CBC, CFB8, CFB128, GCM, CCM, GMAC, CMAC, AES Key Wrap, XTS | 128/192/256

(https://msdn.microsoft.com/en-us/library/windows/desktop/bb931354.aspx#symmetric_algorithms)

**Comment by jnm2** [comment] 2017-12-29 20:32
@bartonjs Oh, never mind. This is hard to google for.

**Comment by niemyjski** [comment] 2018-01-03 11:11
I get that, not sure why it wasn't ported since it had a managed implementation and marked obsolete. We moved to data protection api but the migration isn't easy.... It would be much easier if there was options once you are on .net core.

**Comment by jnm2** [comment] 2018-01-03 14:31
Shipping an encryption implementation is a huge liability.

**Comment by niemyjski** [comment] 2018-01-03 14:48
Could have been marked as deprecated and not supported and even put in a shim / compat library. This is really a huge pain point for those converting to .net core.. As they now have to figure this out once they hit this (it compiles) and then figure out the issue and then back port a migration to legacy code.

**Comment by karelz** [comment] 2018-01-03 15:58
Maybe we should mark it as compat difference in https://github.com/dotnet/platform-compat?

**Comment by simonjlawson** [comment] 2018-09-14 16:17
This has been a big problem for my migration however `BouncyCastle.NetCore` mentioned above has worked great for me as it still supports AES 256.  I am now able to decrypt existing files into a future cipher within the new codebase.

```
var keyBytes = password.GetBytes(Keysize / 8);
var engine = new RijndaelEngine(256);
var blockCipher = new CbcBlockCipher(engine);
var cipher = new PaddedBufferedBlockCipher(blockCipher, new Pkcs7Padding());
var keyParam = new KeyParameter(keyBytes);
var keyParamWithIV = new ParametersWithIV(keyParam, ivStringBytes, 0, 32);

cipher.Init(false, keyParamWithIV);
var comparisonBytes = new byte[cipher.GetOutputSize(cipherTextBytes.Length)];
var length = cipher.ProcessBytes(cipherTextBytes, comparisonBytes, 0);
cipher.DoFinal(comparisonBytes, length);
```

**Comment by phillijw** [comment] 2019-01-20 20:57
Am I mistaken that BouncyCastle doesn't support all of the same paddings and ciphers that RijndaelManaged supported? I'm having a hard time matching up the two implementations because Zero padding gets used in various places with 256 bit block size among the other slight variations.

**Comment by Looooooka** [comment] 2019-01-20 21:17
You are correct. But there are plenty of examples online on how to overcome this using PaddedBufferedBlockCipher, CbcBlockCipher(or others) and RijndaelEngine. Using the Net Standard libraries it will work in Net Core and Net Framework.

**Comment by Looooooka** [comment] 2019-01-20 21:32
Unfortunately I wouldn't know. When I was stuck with the block part(I was using PKCS7Padding), I got help here, so hopefully someone with more knowledge will come to the rescue with your problem as well.

**Comment by phillijw** [comment] 2019-01-20 22:07
For anyone else wondering, I was able to implement my own `PbeParametersGenerator` and `ZeroPadderCipherParameters : KeyParameter` to zero-pad a byte array to a certain length. This allowed me to move forward without having to using the other ways of padding.

```
    public class ZeroPadderCipherParameters : KeyParameter
    {
        public ZeroPadderCipherParameters(byte[] key) : base(key)
        {
        }

        public ZeroPadderCipherParameters(byte[] key, int keyOff, int keyLen) : base(key, keyOff, keyLen)
        {
        }
    }
```
```
    public class ZeroPadderThingy : PbeParametersGenerator
    {
        public override ICipherParameters GenerateDerivedMacParameters(int keySize)
        {
            while (Password.Length*8 < keySize)
            {
                Password[Password.Length] = 0;
            }

            return new ZeroPadderCipherParameters(Password);
        }

        public override ICipherParameters GenerateDerivedParameters(string algorithm, int keySize)
        {
            //TODO: Make this not crappy
            return GenerateDerivedMacParameters(keySize);
        }

        public override ICipherParameters GenerateDerivedParameters(string algorithm, int keySize, int ivSize)
        {
            //TODO: Make this not crappy
            return GenerateDerivedMacParameters(keySize);
        }

        [Obsolete]
        public override ICipherParameters GenerateDerivedParameters(int keySize)
        {
            throw new NotImplementedException();
        }

        [Obsolete]
        public override ICipherParameters GenerateDerivedParameters(int keySize, int ivSize)
        {
            throw new NotImplementedException();
        }
    }
```
and then I was able to use these with something like this...
```
            PbeParametersGenerator generator = new ZeroPadderThingy();
            generator.Init(Encoding.UTF8.GetBytes(Passphrase), new byte[], 0); //ugh
            key = (KeyParameter)generator.GenerateDerivedParameters("this isn't used", _keyBitSize);
```

It's not pretty but might be useful for someone else trying to accomplish the same thing for legacy projects.
