### ISSUE TITLE
xpath concat not working.

### ISSUE THREAD

**Issue by kronic** [dotnet/corefx#22030] opened 2017-07-10 06:46 UTC
```c#
using System;
using System.Xml.Linq;
using System.Xml.XPath;

namespace ConsoleApp1
{
  class Program
  {
    static void Main(string[] args)
    {
      var xElement =
 XElement.Parse(@"<?xml version=""1.0"" encoding=""UTF - 8""?>
<t>
    <a>1</a>
    <b>2</b>
</t>
");
      var xPathEvaluate = xElement.XPathEvaluate("/t/concat(a, b)");
      Console.ReadKey();
    }
  }
}
```
System.Xml.XPath.XPathException: "'/t/concat(a, b)' has an invalid token."

[EDIT] @karelz formatting change - code indentation for easier reading

**Comment by stephentoub** [comment] 2017-07-10 13:15
The error message is correct: the xpath query is invalid. Try either:
- Change `"/t/concat(a, b)"` to `"concat(/a, /b)"`, or
- Change `XElement.Parse` to `XDocument.Parse` and change `"/t/concat(a, b)"` to `"concat(t/a, t/b)"`

**Comment by kronic** [comment] 2017-07-10 14:19
@stephentoub Altova XmlSpy 2017 is return valid result.
![2017-07-10_17-14-44](https://user-images.githubusercontent.com/483422/28022384-ae386bd0-6593-11e7-964d-f97b1ecb4f4d.png)

example2 
````C#
using System;
using System.Xml.Linq;
using System.Xml.XPath;

namespace ConsoleApp1
{
 class Program
 {
  static void Main(string[] args)
  {
   var xElement = XDocument.Parse(@"<?xml version=""1.0"" encoding=""UTF-8""?>
<t>
  <n>
   <a>1</a>
   <b>2</b>
  </n>
  <n>
   <a>1</a>
   <b>2</b>
  </n>
  <n>
   <a>1</a>
   <c>7</c>
  </n>
  <n>
   <a>5</a>
   <b>2</b>
  </n>
</t>
");
   var xPathEvaluate = xElement.XPathEvaluate("/t/n/concat(/a, '_', (./b | ./c)/concat(name(), '=', ./text()))");
   Console.ReadKey();
  }
 }
}
````
````C#
System.Xml.XPath.XPathException: "'/t/n/concat(/a, '_', (./b | ./c)/concat(name(), '=', ./text()))' has an invalid token."
````

**Comment by krwq** [comment] 2017-07-20 23:01
Hi @kronic,

I have checked XPath 1.0 Spec ( https://www.w3.org/TR/xpath/ ) and we are searching for a path between two AST nodes in a grammar:
- RelativeLocationPath https://www.w3.org/TR/xpath/#NT-RelativeLocationPath
- FunctionCall https://www.w3.org/TR/xpath/#NT-FunctionCall

I have got lost in recursion when searching a path by hand so I wrote a simple script analyzing that for me. (nodes are AST nodes and children are other AST nodes which that AST node depends on)

Based on that I believe this is a feature request and not a bug.

Please let me know if you find a bug in this script (I did few manual tests and it showed the path correctly).

<details>
<summary>Code here</summary>

```csharp
using System;
using System.Collections.Generic;

class Program
{
    static void FindPathInternal(string source, string destination, Dictionary<string, string[]> grammarDependencyTree, List<string> path, List<string[]> solutions, HashSet<string> visited)
    {
        if (!grammarDependencyTree.ContainsKey(source))
            throw new Exception($"Incomplete grammer. Missing `{source}`.");

        if (!visited.Add(source))
            return;

        if (source == destination)
        {
            solutions.Add(path.ToArray());
            return;
        }

        foreach (var child in grammarDependencyTree[source])
        {
            path.Add(child);

            FindPathInternal(child, destination, grammarDependencyTree, path, solutions, visited);

            path.RemoveAt(path.Count - 1);
        }
    }

    static List<string[]> FindPath(string source, string destination, Dictionary<string, string[]> grammarDependencyTree)
    {
        if (!grammarDependencyTree.ContainsKey(destination))
            throw new Exception($"Incomplete grammer. Missing destination `{destination}`.");

        var visited = new HashSet<string>();
        var ret = new List<string[]>();
        var path = new List<string>();
        path.Add(source);

        FindPathInternal(source, destination, grammarDependencyTree, path, ret, visited);

        return ret;
    }

    static string[] TODO = new string[0] { /*TODO - irrelevant for search*/ };

    static Dictionary<string, string[]> xpathGrammarDependencyTree = new Dictionary<string, string[]>()
        {
            { "LocationPath", new[] { "RelativeLocationPath", "AbsoluteLocationPath" } },
            { "AbsoluteLocationPath", new[] { "RelativeLocationPath", "AbbreviatedAbsoluteLocationPath" } },
            { "RelativeLocationPath", new [] { "Step", "RelativeLocationPath", "AbbreviatedRelativeLocationPath" } },
            { "Step", TODO },
            { "AbbreviatedAbsoluteLocationPath", new [] { "RelativeLocationPath" } },
            { "AbbreviatedRelativeLocationPath", new [] { "RelativeLocationPath", "Step" } },
            { "PrimaryExpr", new [] { "VariableReference", "Expr", "Literal", "Number", "FunctionCall" } },
            { "FunctionCall", TODO },
        };

    static void Main(string[] args)
    {
        try
        {
            var solutions = FindPath("RelativeLocationPath", "FunctionCall", xpathGrammarDependencyTree);
            foreach (var path in solutions)
            {
                Console.WriteLine(string.Join(" --> ", path));
            }

            if (solutions.Count == 0)
            {
                throw new Exception("No paths found.");
            }
        }
        catch (Exception e)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Error.WriteLine(e.Message);
            Console.ResetColor();
        }
    }
}

```

</details>

**Comment by krwq** [comment] 2017-07-28 15:49
Closing, please reopen if you find some bug in above grammar dependency check.

**Closed by krwq** 2017-07-28 15:49 UTC
Labels: area-System.Xml
