### ISSUE TITLE
RangeAttribute with string constructor fails on various locales

### ISSUE THREAD

**Issue by MrJul** [dotnet/corefx#2648] opened 2015-08-06 09:30 UTC
`RangeAttribute(Type, string, string)` can be used to validate various types implementing `IComparable`. However, it does the conversion from the string parameters using the current culture, which is wrong.

Simple repro:

```
Thread.CurrentThread.CurrentCulture = new CultureInfo("fr");
new RangeAttribute(typeof(decimal), "0.1", "0.9").IsValid(123m)
```

fails with a `FormatException`: _0.1 is not a valid value for Decimal._

While in this sample the strings could be adjusted at runtime to represent numbers using the current culture, the typical usage of an attribute is

```
[Range(typeof(decimal), "0.1", "0.9")]
public decimal Value { get; set; }
```

where the values **must** be constants, and can't change depending on the culture.

Culprit line:

https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RangeAttribute.cs#L203

The fix can't be to simply change `CurrentCulture` to `InvariantCulture` here, since this will alter the runtime validation behavior: `InvariantCulture` should be used to convert the `min` and `max` parameters (maybe falling back to `CurrentCulture` for back-compat, if the constructor was used directly), but `CurrentCulture` should be kept to validate the user-entered value.

If accepted, I can add some unit tests and a fix for this issue.

**Comment by joshfree** [comment] 2015-08-11 17:57
@steveharter

**Comment by steveharter** [comment] 2015-09-22 21:28
Moving to rc1. Will likely assign to a mef contact as well, as this is an issue with the RangeAttribute, and not with globalization. The suggested fix of having the attribute values as Invariant makes sense because the use of commas, decimal, etc literals can vary between cultures and should thus be stored as an invariant format.

**Comment by dsplaisted** [comment] 2015-11-02 17:34
Fixing this looks like it will have a compat impact, so we will probably need to quirk this.

**Comment by karelz** [comment] 2016-11-14 23:36
@weshaggard what are the options for quirks here? We want portable libraries targeting .NET Standard 2.0 have the same behavior on .NET Core and Desktop I assume.

**Comment by karelz** [comment] 2016-11-18 22:43
Ping @weshaggard?

**Comment by weshaggard** [comment] 2016-11-21 18:00
Sorry I don't know the space in question much here so it is hard to say. Assuming it is just code as opposed to attribute discovery then we have the usual AppContext switches that can be considered to enable folks to opt into the same behavior. I would defer to @divega about whether we feel a quirk would be warranted here or not.

**Comment by divega** [comment] 2017-02-09 21:21
@karelz @weshaggard we discussed this in triage today and we believe the issue is worth addressing. Compatibility is also important so we don't think it is a good idea to change the default behavior. We are not sure whether having a quirk or a new member is a better option:
- It seems both approaches would require work in .NET Core and .NET Framework for the issue to be completely addressed
- A quirk would be a little less discoverable, but it would keep the surface on the attribute simpler

It would be good to get your input on which one is best.

**Comment by lajones** [comment] 2017-04-18 22:28
We would consider a PR which provided either a new constructor (taking an extra bool indicating whether to use `InvariantCulture`) or a new member which did the same thing.

**Closed** 2018-02-12 16:30 UTC
Labels: area-System.ComponentModel.DataAnnotations, bug, up-for-grabs
