### ISSUE TITLE
Can not send email on .Net Core 2.0 with SmtpClient or TcpClient

### ISSUE THREAD

**Issue by DenisKot** [dotnet/corefx#27228] opened 2018-02-17 12:57 UTC
I'm trying to send email using Google SMTP server but its throwing exception on socket connection.
Simple code that works fine on .Net but not on .Net Core 2.0: 

```
var client = new SmtpClient("smtp.gmail.com", 587);
      client.UseDefaultCredentials = false;
      client.Credentials = new NetworkCredential("email@gmail.com", "some password");
      client.EnableSsl = true;

        MailMessage mailMessage = new MailMessage();
        mailMessage.From = new MailAddress("email@gmail.com");
        mailMessage.To.Add("otheremail@gmail.com");
        mailMessage.Body = "Hello World!";
        mailMessage.Subject = "Subjeeect";

        client.Send(mailMessage);
```

Exception:

> System.Net.Mail.SmtpException: 'Failure sending mail.'

> ExtendedSocketException: An attempt to establish a connection was unsuccessful, because from another computer for the required time, the desired response was not received, or the already established connection was broken because of the incorrect response of the computer already connected. 64.233.162.109:587

Same error will be if use TcpClient:

```
using (var client = new TcpClient())
{
    await client.ConnectAsync("smtp.gmail.com", 587);
}
```

I'm running this code on Windows 10 if it's important.

**Comment by davidsh** [comment] 2018-02-17 15:57
cc: @Priya91

**Comment by wfurt** [comment] 2018-02-18 04:27
You can try to get packet captures @DenisKot  to see if that is code or networking problem. 
Tha fact that even plain socket cannot connect is suspicious and may be caused by some security setting or network problems.

**Comment by DenisKot** [comment] 2018-02-18 10:24
@wfurt same code works on .Net 4.6.1 fine, but throws an error on .Net Core 2.0 so it's not a network problem :)

**Comment by DenisKot** [comment] 2018-02-18 10:31
@wfurt you are right, it's seams that is working on some other WiFi networks but not at my local nerwork.
But how to fix it ...

**Comment by wfurt** [comment] 2018-02-19 03:40
packet capture still may be useful. For example, different networks may resolve to different addresses. 
Also depending on the resolver you may get IPv6 address instead of IPv4. You may try it again with fixed IP known to work just to gain more information. 
When you comparing to framework, is it running on same machine?

**Comment by DenisKot** [comment] 2018-02-19 07:22
@wfurt yep, same laptop but different networks.

**Comment by DenisKot** [comment] 2018-02-23 20:40
My internet provider had been blocking google smtp server :)
That is well that they fixed it))

**Comment by davidsh** [comment] 2018-02-23 20:48
Since the problem was your internet provider and not a .NET Core issue, we can close this issue then.  Thx.

**Closed by davidsh** 2018-02-23 20:48 UTC
Labels: area-System.Net
