### ISSUE TITLE
ADOMD.NET support for .NET Core

### ISSUE THREAD

**Issue by twenzel** [dotnet/corefx#34803] opened 2019-01-24 15:04 UTC
This is a follow up for #20809.

When does MS provide a client library to connect to SSAS supporting .NET Core/.netstandard?
At the moment the only option to query cubes is the [unofficial adomd.net client](https://github.com/bdebaere/Unofficial.Microsoft.AnalysisServices.AdomdClientNetCore).

There must be a library from Microsoft that can access SSAS.

**Comment by Wraith2** [comment] 2019-01-24 15:37
Would it not be better to ask the group in charge of developing the SSAS package? This repo is developing .net core itself which is essentially the BCL and some core packages. Upstream consumers are free to consume or not as they wish.

**Comment by twenzel** [comment] 2019-01-25 07:09
Unfortunately, I don't have any contact for this group.

**Comment by karelz** [comment] 2019-02-22 01:32
Duplicate of #20809

**Closed by karelz** 2019-02-22 01:32 UTC
