### ISSUE TITLE
HttpClientHandler on Linux/OSX doesn't correctly implement Digest authentication

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#9672] opened 2016-06-24 20:29 UTC
When making a request to a server requiring Digest authentication, the username is incorrectly specified as `realm\\username` in the challenge response. WCF has an implementation of the digest authentication algorithm in our tests which the following is from. The details of the authentication handshake that we're seeing uses the following credential information.

```
Username:  be70abb0
Password:  c84613c28bee44e5
Realm:  bfd3c
```

A request is first made to the server with no authorization header. The server responds with a 401 Access Denied response and provides the following response header,  
`WWWAuthenticate: Digest realm="bfd3c", nonce="Ni8yNC8yMDE2IDEyOjMyOjI0IFBN", opaque="0000000000000000", stale=false, algorithm=MD5, qop="auth"`  
The client then sends the following response headers.  
`Authorization:  Digest username="bfd3c\\be70abb0", realm="bfd3c", nonce="Ni8yNC8yMDE2IDEyOjMyOjI0IFBN", uri="//HttpDigestNoDomain.svc/http-digest-nodomain", cnonce="MTliMzMyYmFlNmZiZWZiMTAwMTE2NDQ4MDAwMDFjNjc=", nc=00000001, qop=auth, response="d632601dd17ae997ec1fd065da22cf7f", opaque="0000000000000000", algorithm="MD5"`  
The digest username sent is `bfd3c\\be70abb0` which is `realm\\username`. This is incorrect as the username should be sent without the realm.

**Comment by mconnew** [comment] 2016-06-24 20:46
@stephentoub, @davidsh

**Comment by stephentoub** [comment] 2016-06-24 20:53
Thanks, @mconnew. Just to clarify, what does the NetworkCredential you're providing look like?
```C#
new NetworkCredential("be70abb0", "c84613c28bee44e5");
```
or
```C#
new NetworkCredential("be70abb0", "c84613c28bee44e5", "bfd3c");
```
or something else?

**Comment by mconnew** [comment] 2016-06-25 01:33
It looks like the second one.

**Comment by stephentoub** [comment] 2016-06-25 03:12
And if you change it to look like the first, it works fine?

**Comment by mconnew** [comment] 2016-06-27 19:56
I have no idea, I'll try it out. A couple more pieces of data. On Windows, the username is sent as just the username as expected when using the NetworkCredential constructor with the 3 parameters. Also it looks like when authenticating with a windows server using the built in digest authentication (which authenticates against a domain account), the server is tolerant of the realm\\username format. So this will only fail against an HTTP server using digest authentication which isn't using integrated Windows authentication.

**Comment by mconnew** [comment] 2016-06-27 20:07
If I exclude the realm, it succeeds. Which makes some sense as I've now stated the credentials are domain/realm-less.

**Comment by mconnew** [comment] 2016-06-27 21:15
If you look at [this technet article](https://technet.microsoft.com/en-us/library/cc780170(v=ws.10).aspx) in the Digest Hashes section there is a not below the table which says that FlatDomainName\SamAccountName is considered a NetBiosName username. It also shows in the table that if this form is being used, it is expected that the Realm is either null or the string "Digest".

**Comment by stephentoub** [comment] 2016-06-28 01:03
Thanks for the extra info.

I don't think there's anything we can do about this.  We simply pass a username and password to libcurl, along with the auth schemes we accept.  If the NetworkCredential includes a domain, then we pass "domain\username" to libcurl, and if it doesn't, we don't.  And we don't know in advance whether the auth scheme that will be chosen necessitates the domain be included, so we simply use it if it's provided and don't if it's not.

**Comment by mconnew** [comment] 2016-06-28 01:23
The realm is being passed in the header, do you get notified of the Realm that was included in the WWWAuthenticate header? If so, then if the Realm and domain match, you can strip off the Realm from the username. If the user account is in a different domain/realm than the server, than it's expected that the domain should be provided as part of the username, otherwise it should be just the username.

**Comment by mconnew** [comment] 2016-06-28 01:30
I'm looking at the [WinHttpAuthHelper code](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpAuthHelper.cs#L339) and it is actually setting the username that it passes to WinHTTP to domain\\username. So it looks like WinHTTP removes the domain off the front if it matches.

**Comment by mconnew** [comment] 2016-07-11 22:19
A few more pieces of information about the behavior. The UWP HttpClient and libcurl on centos both do something which is incorrect according to the spec. They don't escape the \ in the username so instead of sending to the server `domain\\username`, they are sending `domain\username`. According to the Digest RFC, this is incorrect as the username should be escaped. I have tested all these variants against the integrated digest authentication in IIS and it is tolerant of all these incorrect username variants. I don't know how tolerant other platforms will be though.

**Comment by karelz** [comment] 2017-02-23 19:40
@mconnew which WCF/other scenarios are blocked by this issue?

**Comment by zhenlan** [comment] 2017-05-30 21:52
> @mconnew which WCF/other scenarios are blocked by this issue?

Please see @mconnew's explanation at https://github.com/dotnet/wcf/issues/1332#issuecomment-231890739

**Comment by karelz** [comment] 2017-05-30 22:11
@zhenlan I am not quite sure how to translate that to importance of the scenario? What doesn't work when where?

**Comment by mconnew** [comment] 2017-07-28 00:16
It's a spec violation which means when communicating with a server which is strict, authentication may not be possible.

**Comment by rmkerr** [comment] 2018-04-24 19:47
I investigated this same issue as part of #28065. I'm able to reproduce this issue even if I skip CurlHandler completely and use only Curl. Even using their escaping mechanism, I can't make Curl send a single slash in a digest username. It either doubles the slash as you saw, or leaves it escaped. 

Since this works in SocketsHttpHandler and appears to be an external bug without a workaround, I'm going to close this issue.

**Closed by rmkerr** 2018-04-24 19:47 UTC
Labels: area-System.Net.Http, bug, os-linux, os-mac-os-x
