### ISSUE TITLE
HttpClient don't send SSL server_name extension

### ISSUE THREAD

**Issue by zokiad** [dotnet/corefx#23362] opened 2017-08-17 21:17 UTC
Hi,

The aim is to test a web farm. DNS is configured with one IP (behind there are several servers) and redirect to one web server.

To test one server in web farm, in framework 4.6.2, I use with sample code:

```C#
          string host = "www.ebay.fr";

            IPHostEntry hostEntry;
            hostEntry = Dns.GetHostEntry(host);

            ///// HttpClient Test
            HttpClientHandler httpClientHandler = new HttpClientHandler();
            HttpClient client = new HttpClient(httpClientHandler);
            client.BaseAddress = new Uri("https://" + hostEntry.AddressList[0].ToString());
            client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (compatible;" + DateTime.Now + " " + DateTime.Now.Millisecond + ")");
            client.DefaultRequestHeaders.Host = host;

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, client.BaseAddress);
            request.Headers.Host = host;
            request.Headers.UserAgent.ParseAdd("Mozilla/5.0 (compatible;" + DateTime.Now + " " + DateTime.Now.Millisecond + ")");

            Task<HttpResponseMessage> task = client.SendAsync(request);
            task.Wait();
            HttpResponseMessage respones = task.Result;

```

With framework 4.6.2, it is work fine.

**But in .net core 2**, with a test on IIS server web server, the connexion close when web client try to negociate SSL.
Here I use "ebay" server but it is work on it. I don't found a IIS server on web. My web farm is not access from web.

I debug the connection with WireShark to see the network data:
**With .net core2**
![image](https://user-images.githubusercontent.com/20461115/29434016-b34561e2-83a1-11e7-81f8-2f2af5786660.png)

**With Framework 4.6.2**
![image](https://user-images.githubusercontent.com/20461115/29434003-aa4457ba-83a1-11e7-9d9c-04dd54f65982.png)

📌  I think the issue is with .net core, **the extension server_name is not defined**. IIS server should need known the certificat to take.
.net core 2 should define server_name from client.DefaultRequestHeaders.Host or request.Headers.Host (even if BaseAddress is an IP)  ?

**For more information:**
[https://idea.popcount.org/2012-06-16-dissecting-ssl-handshake/](url)

> TLS introduces a number of extensions. Most notably the server_name / Server Name Indication (SNI) extension is used to specify a remote host name. This allows the server to choose appropriate certificate based on the requested host name. With this extension one can host many SSL-enabled vhosts on a single IP address.

**Comment by davidsh** [comment] 2017-08-18 00:22
Is this on Windows or Linux?

**Comment by zokiad** [comment] 2017-08-18 13:37
On windows 10.

**Comment by davidsh** [comment] 2017-09-01 04:27
Please let us know the specific version of Windows 10.  Please run 'CMD.EXE' window.  And then type "ver".  Let us know what the output it.  Thx.

**Comment by zokiad** [comment] 2017-09-01 20:50
Hi,

You can find the project with test:
[TestSSL.zip](https://github.com/dotnet/corefx/files/1271478/TestSSL.zip)

I test again today, server_name is not defined on Windows but also on Debian.
The test define host to site name (for example: www.google.fr) but call web site with its IP adress.
With framework .net, server_name is define with host defined. But in .net, not.

Windows: Microsoft Windows [Version 10.0.15063]
Debian 9.0:  4.9.0-3-amd64 GNU/Linux

Regards

**Comment by geoffkizer** [comment] 2017-11-21 23:07
Maybe I'm missing something here, but it looks like you're using an IP address in your URL:

`            client.BaseAddress = new Uri("https://" + hostEntry.AddressList[0].ToString());`

We can't send SNI info if you use an IP address.  Use the DNS name instead.

**Comment by zokiad** [comment] 2018-01-07 14:57
No, like on framework .net, .net core should take host for SNI because you can have several host on same web server.

`client.DefaultRequestHeaders.Host = host;`

**Comment by karelz** [comment] 2018-01-07 20:24
@zokiad the issue was closed as "invalid" per [closing comment](https://github.com/dotnet/corefx/issues/23362#issuecomment-346190846), so it was not fixed.

I was able to reproduce the difference in behavior - .NET Core 2.0 does not send SNI in the repro above, while .NET Framework 4.7.1 does.

**Comment by davidsh** [comment] 2018-01-07 20:37
>No, like on framework .net, .net core should take host for SNI because you can have several host on same web server.
client.DefaultRequestHeaders.Host = host;

The behavior of HTTP stack on Windows is handled by native Windows WinHTTP.

I don't think WinHTTP will use the 'Host' header for SNI.  It relies on the DNS name itself.  We'll need to check into this.

**Comment by karelz** [comment] 2018-01-17 22:54
Triage: It is important scenario. Given the limited interest so far (1 customer) and complications (it may be WinHTTP limitation), we won't address it in 2.1. ManagedHandler should be able to handle that (and will eventually become the default), so let's keep it opened.

**Comment by geoffkizer** [comment] 2018-01-18 08:23
I believe Stephen changed the managed handler to do this already.  @stephentoub?

**Comment by stephentoub** [comment] 2018-01-18 15:36
> I believe Stephen changed the managed handler to do this already. @stephentoub?

https://github.com/dotnet/corefx/pull/24820

**Comment by karelz** [comment] 2018-01-18 17:57
OK, let's close it then. Eventually it will become default in .NET Core. Now it is opt-in.

**Closed by karelz** 2018-01-18 17:57 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
