### ISSUE TITLE
EntryPointNotFoundException: Unable to find an entry point named 'SystemNative_RealPath' in DLL 'System.Native'.

### ISSUE THREAD

**Issue by miguellira** [dotnet/corefx#7239] opened 2016-03-25 01:15 UTC
This may be the wrong repo but since I found "SystemNative_RealPath" [in this file](https://github.com/dotnet/corefx/blob/d091dd59b943e0024e92a1df9280bf192932ec7b/src/Common/src/Interop/Unix/System.Native/Interop.RealPath.cs) I figured I'd start here.

After installing the latest `dotnet cli` on OS X:
```console
.NET Command Line Tools (1.0.0-beta-001842)

Product Information:
 Version:     1.0.0-beta-001842
 Commit Sha:  778e63a5a6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```
I modified the latest sample MVC app: https://github.com/aspnet/cli-samples/tree/master/HelloMvc to target `netstandardapp1.5`.

After running `dotnet restore` I ran into `runtime.unix.*` dependency issues required by the `dotnet-publish-iis` tool:
```console
    Unable to resolve runtime.unix.System.IO.Compression (>= 4.1.0-rc2-23911) for .NETStandardApp,Version=v1.5 (osx.10.11-x64).
    Unable to resolve runtime.unix.System.Security.Cryptography.X509Certificates (>= 4.1.0-rc2-23911) for .NETStandardApp,Version=v1.5 (osx.10.11-x64).
    Unable to resolve runtime.unix.System.Security.Cryptography.Algorithms (>= 4.1.0-rc2-23911) for .NETStandardApp,Version=v1.5 (osx.10.11-x64).
```
After removing the tool, building, and running the app I run into the following exception:
```
      An unhandled exception has occurred while executing the request
System.EntryPointNotFoundException: Unable to find an entry point named 'SystemNative_RealPath' in DLL 'System.Native'.
   at Interop.Sys.RealPath(String path)
   at System.IO.FileSystemWatcher.RunningInstance.Start()
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetMemoryCacheEntryOptions(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String normalizedPath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

```

**Comment by ellismg** [comment] 2016-03-25 02:21
Can you share out your project.lock.json file?  This is usually indicative of some old package getting pulled into the package graph, causing nuget to restore a very old copy of a file.

**Comment by miguellira** [comment] 2016-03-25 04:08
@ellismg Since posting the issue I've done many changes in the hopes that I get this to run. Including: 

1) Re-running the OS X CLI installer which coincidently states is version `1.0.0-beta-001998` yet running `donet --version` still outputs:
```console
.NET Command Line Tools (1.0.0-beta-001842)

Product Information:
 Version:     1.0.0-beta-001842
 Commit Sha:  778e63a5a6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

NOTE: the path `/usr/local/share/dotnet/sdk/1.0.0-beta-001998` does exist.

2) Added `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json` to the `NuGet.Config` file one directory up. Which now results in `dotnet -v restore --no-cache` indicating:
```console
Detected package downgrade: NuGet.Versioning from 3.5.0-beta-1034 to 3.4.0-rtm-0763 
```

3) `git reset --hard` the sample CLI app several times to try and go back to a previous state.

Anyway, here's my current `project.lock.json`: https://gist.github.com/miguellira/8e144f733af40b2527dc

Hopefully, it helps lead you to a resolution. Thanks!

**Comment by miguellira** [comment] 2016-03-25 04:13
@ellismg Uh, oh, I just ran `dotnet build` and `dotnet run` and got the following error:
```console
An unhandled exception has occurred while executing the request
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Extensions.DependencyInjection.DataProtectionServices.<>c.<GetDefaultServices>b__0_0(IServiceProvider services)
```
Why a `Microsoft.Win32.Registry` reference would pop up on OS X is beyond me.

Ugh, is there some proper way to **nuke** my current version of dotnet CLI, clear caches, etc. and just start over?

**Comment by ellismg** [comment] 2016-03-25 04:45
> Ugh, is there some proper way to nuke my current version of dotnet CLI, clear caches, etc. and just start over?

@blackdwarf @mellinoe What's the correct way to blow away the CLI after it's been installed via the PKG?

> Anyway, here's my current project.lock.json: https://gist.github.com/miguellira/8e144f733af40b2527dc

Looking at this everything seems fine to me.  The System.Native that is getting pulled in should have the exports that are expected.  Maybe you could verify their existence with `nm -gU <path-to-system.native.dylib>`?

@ericstj Anything jump out at you as weird about this?

**Comment by miguellira** [comment] 2016-03-25 05:01
@ellismg The readme links off to a site suggesting the use of `pkgutil` to identify and clean out the pkg installation files/folders but I'm hestitant to sudo wipe the `/usr/local/share/dotnet/` folder unless that's the best approach.

Is there a way to clear out the dotnet CLI  cache similar to how one would simply wipe `~/.dnx/packages/` for DNX?

Anyway, here's the output from `nm -gU /usr/local/share/dotnet/bin/System.Native.dylib`: https://gist.github.com/miguellira/49e43fba4ed021ecd07f

**Comment by ellismg** [comment] 2016-03-25 05:17
Looking at the lock file a little more as well as when that export was introduced, I think the problem is that the version of System.Native that is restored via nuget is older than the version of System.FileSystem.Watcher.  This export was added recently and so it's throwing things off.

You might try updating the version of NETStandard.Library in the project.json file to `"NETStandard.Library": "1.0.0-rc2-*"` and see if that helps things along.

If not, Eric can probably give you the magic incantation to prevent the older version of the native library from getting downloaded.

**Comment by miguellira** [comment] 2016-03-25 05:28
@ellismg Thanks for being so responsive. I updated the version to the more restrictive `rc2-*` you suggested and now I'm back to the `System.EntryPointNotFoundException`.

```console
An unhandled exception has occurred while executing the request
System.EntryPointNotFoundException: Unable to find an entry point named 'SystemNative_RealPath' in DLL 'System.Native'.
```

Maybe it's best just to wait for another drop CLI drop.

**Comment by blackdwarf** [comment] 2016-03-25 07:02
@miguellira @ellismg there is no way other than the one that was specified in the known issues document. This is a thing with PKGs unfortunately. However, if you want to just blow away your package cache, you can do that by nuking `~/.nuget/packages` which is the default location.

**Comment by miguellira** [comment] 2016-03-25 11:49
@blackdwarf Thanks. So I took the plunge and in short, I resolved some issues and found some new ones. For those who care to follow along...

Ran through the manual `pkgutil` removal process outlined in the read me and removed the following four packages:
```console
com.microsoft.dotnet.cli.pkg.dotnet-osx-x64
com.microsoft.dotnet.sdk.osx.x64
com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.1.0.0-rc2-23911.component.osx.x64
com.microsoft.dotnet.sharedhost.osx.x64
```

I then reinstalled the latest dotnet CLI for OSX (which appers to be behind all the others) and it now shows the proper version:
```console
.NET Command Line Tools (1.0.0-beta-001998)

Product Information:
 Version:     1.0.0-beta-001998
 Commit Sha:  cd35ba2a1a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```
I then nuked the `~/.nuget/packages` directory and attempted a restore, build, run against the HEAD version of the CLI sample HelloMvc application which still targets `netstandardapp1.3` which resulted in the following error:
```console
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
This appears to be an issue that affected other CLI versions (https://github.com/dotnet/cli/issues/1488) and (https://github.com/dotnet/cli/issues/1827)

I then added the dotnet myget feed to the parent NuGet.config file:
```c#
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```
I did another `dotnet -v restore --no-cache` which results in the following error:
```console
Errors in /Users/miguellira/Documents/Github/aspnet/cli-samples/HelloMvc/project.json
    Microsoft.Win32.Registry 4.0.0-rc3-23909 provides a compile-time reference assembly for Microsoft.Win32.Registry on .NETStandardApp,Version=v1.3, but there is no run-time assembly compatible with osx.10.11-x64.
    Some packages are not compatible with .NETStandardApp,Version=v1.3 (osx.10.11-x64).
```
and although it still builds and runs I now get the following exception:
```console
      An unhandled exception has occurred while executing the request
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(JObject root)
   ...[snip]...
```
At this point I decided to run `dotnet new` on a seperate folder and see if I can restore, build, run without any issue and indeed everything worked.

So I then updated the `project.json` file to target the same framework in the dotnet new app, namely `netstandard1.5`, restore, build, run and now I get the following error:
```console
Project HelloMvc (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Could not load host policy library [/Users/miguellira/Documents/Github/aspnet/cli-samples/HelloMvc/bin/Debug/netstandard1.5]
```
which someone has already logged (https://github.com/dotnet/cli/issues/2037)

Maybe when the OS X CLI installers catches up with the other OSes I'll have better luck.

**Comment by blackdwarf** [comment] 2016-03-25 14:22
@miguellira those seem like bugs that should indeed be resolved with latest (once it catches up). A ot of stuff going in these days...

**Comment by miguellira** [comment] 2016-03-25 14:26
@blackdwarf Yep. Thanks for feedback nonetheless.

Curiously, I was just reading your post regarding templating with `dotnet new` (https://github.com/dotnet/cli/issues/2052) and looking through @DamianEdwards dotnet-new2 spike.

Guess this approach will trump `yo` and any related generators.

**Comment by blackdwarf** [comment] 2016-03-25 14:27
@miguellira "trump"? ;) It will be good, yes. The idea is that you get a nice tool for getting started in the core package.

**Comment by miguellira** [comment] 2016-03-25 14:45
@blackdwarf Ha. "Make dotnet great again".

Thanks again for the help.

**Comment by ericstj** [comment] 2016-03-25 16:08
> If not, Eric can probably give you the magic incantation to prevent the older version of the native library from getting downloaded.

Looked at the lock file, I see the following:
```
"System.IO.FileSystem.Watcher/4.0.0-rc2-23923": {
...
"dependencies": {
...
"runtime.native.System": "4.0.0-rc2-23923"
...
"runtime.native.System/4.0.0-rc3-23909": 
```
So even though libraries requested a higher version of the shim they got a lower version.  Root cause here was the reversioning of NETStandard.Library. /cc @weshaggard   Project brought in 
```
      "NETStandard.Library >= 1.0.0-*"
```
However the version has been changed to 1.5.0.  So this was picking up the last build of NETStandard.Library (rc2-23909) where all the other packages were picking up latest builds of the other CoreFx libraries.

I would have expected a mess of warnings from NuGet when restoring this project about downgrading versions.  We need to start paying attention to those warnings.

**Comment by ericstj** [comment] 2016-03-29 21:21
After fixing the dependencies to get a consistent set can you let me know if you are still having the issue?  If so we will re-open.

**Closed by ericstj** 2016-03-29 21:21 UTC
Labels: packaging

**Comment by miguellira** [comment] 2016-03-30 00:01
@ericstj Thanks. Although the `cli-samples` repo hasn't been updated to target the proper framework, changing the `project.json` to the following works without issue on the latest CLI (`1.0.0-beta-002115`):
```json
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    }
```
