### ISSUE TITLE
Add value to HttpStatusCode enum: TooManyRequests (=HTTP 429)

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/corefx#17149] opened 2017-03-15 12:28 UTC
This statuscode is often returned when quotas or throttling limits are being applied to an API. This is often done using an API platform such as Azure API Management or Nginx. Since API's are gaining popularity and more companies are introducing these limits, this statuscode will appear more often in real live scenarios and therefore deserves a representation in this enum.

See the commit on my fork (1 file change): https://github.com/kwaazaar/corefx/commit/f52cd49a696b7c39bc209b09f3058815fd9396ea

**Comment by davidsh** [comment] 2017-03-15 16:39
Pushing to Future. We do not plan to take any API change for 2.0 release. Doing so requires we push the Http contract out of NETStandard2.0.

Also, see #4382.  There are other status codes we would like to add to the HttpStatusCode enum type as well.  The 429 status code is already included in that issue #4382.

**Comment by davidsh** [comment] 2017-03-15 16:40
Dupe of #4382.

**Closed by davidsh** 2017-03-15 16:40 UTC
Labels: api-ready-for-review, area-System.Net.Http

**Comment by stephentoub** [comment] 2017-03-15 17:35
> Doing so requires we push the Http contract out of NETStandard2.0.

What does this mean?  We can add to the .NET Core API surface area without impacting netstandard2.0.

**Comment by davidsh** [comment] 2017-03-15 17:39
>What does this mean? We can add to the .NET Core API surface area without impacting netstandard2.0.

Yes, we could add it to just .NET Core 2.0 surface and not to NETStandard20.  But there is a lot of work in API changes including packaging, testing, etc.

We are prioritizing reliability and other high-impact things at this point for .NET Core 2.0.  Adding API surface area like this is not high priority and so will be deferred.

**Comment by karelz** [comment] 2017-03-15 19:07
> @davidsh ... we could add it to just .NET Core 2.0 surface and not to NETStandard20.

FYI: That is the default way we add any new APIs in CoreFX these days. We do not push NetStandard contracts. Especially given that we plan to stop shipping Desktop packages.
BTW: While we push many issues to Future as they are not "must-have" for 2.0, we still take community contributions (PRs) for Future issues as well.
