### ISSUE TITLE
Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#29873] opened 2018-05-23 13:54 UTC
_From @amshekar on May 23, 2018 10:36_

Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions
General
We have a .Net core 2.0 webapi project and want to call a old vb.net method. The method have some string functions like Left,right,space and trim . We added the DLL as a reference . But in runtime we are getting method not found exception.

like

> Method not found: 'System.String Microsoft.VisualBasic.Strings.Left(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Space(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Right(System.String)'.'
> 

Any help\advice is most appreciated .
We might not changes the old custom dll code which have dependencies with other systems.
If we want to do the modification in old dll if possible what would be the better approach with minimum impact

_Copied from original issue: dotnet/coreclr#18095_

**Comment by danmosemsft** [comment] 2018-05-30 02:47
@weshaggard @VSadov, @OmarTawfik we have almost none of the Strings type ported - only 3 methods. Maybe all the others were considered redundant with other .NET API?

Assuming that's the reasoning - it seems to me we should not be so fussy - folks have existing code and we should let it work. Is there any reason the community should not port the remaining members? It looks like it would be mostly a matter of writing tests.

**Comment by VSadov** [comment] 2018-05-30 03:14
I believe the string functions and other nonessential functionality was cut when making compactFX/Silverlight versions of VB runtime. The size of the binary was a real concern then.

The Core version of VB runtime is based on that codebase since it was relatively small and platform-neutral. It might make sense to bring some of that functionality back.

**Comment by danmosemsft** [comment] 2018-05-30 03:56
Thanks @VSadov. 

@OmarTawfik are you OK with such a port, and sharing NDP\fx\src\vb\runtime\msvbalib\Strings.vb for this purpose?  Conversely, do you believe there is any code in NDP\fx\src\vb\runtime\msvbalib that should not be ported (assuming a need/will to do it emerges)?

**Comment by OmarTawfik** [comment] 2018-05-30 18:33
I'm ok with such a port. I don't see a reason why people should be broken by a few methods that we can easily bring back.
However, I believe all such pieces should be reviewed under a formal API proposal. I am not familiar with all of them, and we might need to think about compat and other concerns in review.

**Comment by danmosemsft** [comment] 2018-06-25 18:38
This seems a dupe of https://github.com/dotnet/corefx/issues/29878 ?

**Closed by danmosemsft** 2018-06-25 18:38 UTC
Labels: area-Microsoft.VisualBasic, bug
