### ISSUE TITLE
Update performance docs

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#17981] opened 2017-04-06 05:42 UTC
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md seems to be very out of date. We need to get the docs updated or removed and pointers to a more generic document that explains how to run them in multiple repos.

**Comment by Clockwork-Muse** [comment] 2017-04-06 15:59
Duplicate of #9257 ?

**Comment by brianrob** [comment] 2017-04-06 22:01
Yes, it is a duplicate of #9257.

**Closed by brianrob** 2017-04-06 22:01 UTC
Labels: documentation
