### ISSUE TITLE
NU1605 Package downgrade with EFCore.Sqlite 2.2 on UWP

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#34055] opened 2018-12-13 00:17 UTC
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/14090 filed by @devsko

I get this two package downgrade warnings. 
```
NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 UwpApp -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
 UwpApp -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)
NU1605: Detected package downgrade: System.Reflection.TypeExtensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 UwpApp -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> System.Dynamic.Runtime 4.0.11 -> System.Linq.Expressions 4.1.0 -> System.Reflection.Extensions 4.0.1 -> runtime.aot.System.Reflection.Extensions 4.3.0 -> System.Reflection.TypeExtensions (>= 4.3.0) 
 UwpApp -> Microsoft.EntityFrameworkCore.Sqlite 2.2.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 2.2.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> System.Dynamic.Runtime 4.0.11 -> System.Reflection.TypeExtensions (>= 4.1.0)
```
Minimal repro with following references
- UWP Target version 17763 / Min version 16299
- Microsoft.NETCore.UniversalWindowsPlatform 6.1.9
- System.Runtime.WindowsRuntime 4.3.0
- Microsoft.EntityFrameworkCore.Sqlite 2.2.0

**Comment by ajcvickers** [comment] 2018-12-13 00:18
Moving here because the issues are down in the corefx/UWP dependencies

**Comment by bricelam** [comment] 2019-01-09 19:00
Similar issue for .NET Core on Unix: aspnet/EntityFrameworkCore#14354

**Comment by igormcoelho** [comment] 2019-01-09 22:14
Should I close https://github.com/aspnet/EntityFrameworkCore/issues/14354 ?

**Comment by bricelam** [comment] 2019-01-10 22:11
Hmm... looks like a 2.2 version of Microsoft.Extensions.DependencyModel was never released... @weshaggard?

**Comment by weshaggard** [comment] 2019-01-10 22:39
As far as I know there was never a 2.2 version of Microsoft.Extensions.DependencyModel however I'm no longer on corefx team so I'm unsure. @danmosemsft or @joperezr might be able to take a look.

**Comment by karelz** [comment] 2019-01-14 20:53
@ajcvickers what is the impact? Just warnings or real damage?
Do you know what is the root cause, how it was introduced or how it should be fixed?
cc @wtgodbe

**Comment by ajcvickers** [comment] 2019-01-14 21:01
@karelz It's being reported to us as an error.  For example, see https://github.com/aspnet/EntityFrameworkCore/issues/14354. We believe it was introduced by not releasing `DependencyModel` for 2.2. However, none of this is EF-specific. It would be the same for any package with these dependencies.

**Comment by ViktorHofer** [comment] 2019-03-04 22:57
cc @ericstj

**Comment by ericstj** [comment] 2019-03-05 00:10
NuGet claiming the downgrade is actually a bug: https://github.com/NuGet/Home/issues/3541

The one reference to 4.3.0 package brings in the new version of the runtime.json which is what triggers the "downgrades". 

I believe you can workaround it by referencing all of the 4.3.0 packages at a higher point in the dependency graph, so NuGet will avoid seeing the downgrade.  I've suggested in the past that folks reference NETStandard.Library meta-package from the same release (1.6.1 or later).

**Closed** 2019-10-21 12:01 UTC
Labels: area-Infrastructure, bug, os-windows-uwp, packaging
