### ISSUE TITLE
System.Threading.Tests.MutexTests hanging in Uap

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#21151] opened 2017-06-16 22:51 UTC
This two tests are hanging in uap: 

CrossProcess_NamedMutex_ProtectedFileAccessAtomic
AbandonExisting

Sorce code:
https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/MutexTests.cs#L142-L201

They both hang when calling `new Mutex(false, name)` and the name contains `"Global\\"` as its prefix. 

cc: @kouvel @AntonLapounov

**Comment by danmosemsft** [comment] 2017-06-16 22:55
I'm assuming this is because they are hitting app container and not gracefully handling that.

**Comment by AntonLapounov** [comment] 2017-06-16 23:39
Need to port changeset 1656573 from ProjectN branch.

**Comment by danmosemsft** [comment] 2017-06-17 01:25
@tijoytom this will come automatically right?

**Comment by kouvel** [comment] 2017-06-17 01:50
CoreCLR issue: https://github.com/dotnet/coreclr/issues/11306

Does this need to go into 2.0 or is 2.1 sufficient?

**Comment by kouvel** [comment] 2017-06-17 02:11
I'll go ahead and port this, it needs some changes in the PAL as well

**Comment by tijoytom** [comment] 2017-06-19 18:30
@danmosemsft CoreCLR changes are not syn'd to N/CoreRT , need to be manually ported.  Thanks @kouvel for doing it.

**Comment by danmosemsft** [comment] 2017-06-19 20:13
@tijoytom fyi there is some sharing: corelib\src\mscorlib\shared syncs with corert\src\System.Private.CoreLib\shared automatically

**Comment by kouvel** [comment] 2017-06-20 06:41
Closing as dupe of https://github.com/dotnet/coreclr/issues/11306

**Closed by kouvel** 2017-06-20 06:41 UTC
Labels: area-System.Threading, disabled-test, test-run-uwp-coreclr

**Comment by safern** [comment] 2017-06-20 07:04
Note that the affected tests where disabled with `[ActiveIssue]` pointing to this issue.

**Comment by kouvel** [comment] 2017-06-20 07:06
Yes I have added a link to those to the other issue as well
