### ISSUE TITLE
Spam messages during the build

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1462] opened 2015-04-21 22:39 UTC
When building from clean repo I get bunch of warnings like (not repeating similar ones):
```
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [E:\oss\corefx\src\System.ComponentModel.Annotations\tests\System.ComponentModel.Annotations.Tests.csproj]
```

Also there is a significant portion of spam like (I really mean significant, it is like every few lines and can occur multiple times in a row):
```
Running NuGet package resolution with TFM DNXCore,Version=v5.0
```

**Comment by AlfredoMS** [comment] 2015-04-22 00:29
That specific message comes from the Task 'ResolveNuGetPackageAssets'.

@ericstj should now if those messages are actually important.

But seems they have already changed from MessageImportance.High to MessageImportance.Low, so maybe they won't appear when we bump the buildtools version in corefx.

https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/ResolveNuGetPackageAssets.cs#L224

**Comment by mellinoe** [comment] 2015-04-22 19:55
Additionally, there are some new messages (warnings, actually) about test projects having no tests to run. Why is that a warning if it's normal and expected behavior?

**Comment by krwq** [comment] 2015-04-22 21:03
+ @Priya91

**Comment by ericstj** [comment] 2015-04-28 06:10
//cc @weshaggard who also pinged me on these.
A lot of the warnings are showing up because we don't flow package refs across project-refs.  The result is that the only thing we see via package resolve task is the indirect ref from the package on an older package version, that gets passed to RAR as a "primary" reference and preferred over the project-ref's dependency, thus the conflict.

A lot of this will be fixed once nuget restore starts considering project references.  @jasonmalinowski and @emgarten are working on this now.  Once this gets solid I'll pick it up and run a dependency minimization tool I wrote (I can't run it now because it will just introduce more warnings) after which we should be warning free.  

There is a separate problem with the xunit packages in that they build against the latest package versions but don't declare those dependencies, that will also need to be fixed @FiveTimesTheFun.

**Comment by stephentoub** [comment] 2015-07-15 16:13
@krwq, is this still an issue?  I don't see "warning MSB3277" warnings any more locally.

**Closed** 2015-10-12 22:20 UTC
