### ISSUE TITLE
.NET Framework 4.7.1 compatibility issue with reflection-only loading

### ISSUE THREAD

**Issue by bording** [dotnet/corefx#24847] opened 2017-10-24 22:05 UTC
Now that netstandard.dll is in the GAC, this can cause failures when attempting to use reflection-only loading.

For example, given the following:
```c#
class Program
{
    static void Main(string[] args)
    {
        var path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

        Console.WriteLine("Scanning assemblies");

        foreach (var file in Directory.EnumerateFiles(path, "*.dll"))
        {
            Console.WriteLine($"Found {file}");
            var assembly = Assembly.ReflectionOnlyLoadFrom(file);

            foreach (var referencedAssembly in assembly.GetReferencedAssemblies())
            {
                Console.WriteLine($"    Reference: {referencedAssembly}");

                try
                {
                    var reference = Assembly.ReflectionOnlyLoad(referencedAssembly.FullName);
                }
                catch { }
            }
        }
    }
}
```
If that project targets net461 and includes a reference to a project that targets netstandard2.0, then the behavior of this program will vary based on whether 4.7.1 is installed or not.

If run on a machine that does not have 4.7.1 installed, then it will complete successfully. 

If run on a machine that does have 4.7.1 installed, then it it will fail with the following exception:
```
System.IO.FileLoadException: API restriction: The assembly 'file:///C:\LoadingRepro\LoadingRepro\bin\Debug\net461\netstandard.dll' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.
```

I've included a full repro solution: [LoadingRepro.zip](https://github.com/dotnet/corefx/files/1412644/LoadingRepro.zip)

ATTN: @karelz @AlexGhiondea 

[EDIT] Added C# syntax by @karelz

**Comment by karelz** [comment] 2017-10-24 22:26
I wonder what loaded the netstandard.dll into the AppDomain in this case ... @ericstj @weshaggard any idea?

**Comment by AlexGhiondea** [comment] 2017-10-24 22:40
I looked at this and here is what I think is happening:

While iterating over the assemblies, we find an assembly that has a reference to netstandard.dll. So we ask the binder to load the netstandard.dll.

Because on 4.7.1 netstandard.dll is in the GAC, we load that assembly.

Continuing to iterate over the assemblies we get to the netstandard.dll that is in the application folder. So we try to load it.  

And then an exception is thrown because the netstandard.dll is already loaded.

I think you can run into this problem even on 4.6.1 if you manually GAC netstandard.dll.

**Comment by karelz** [comment] 2017-10-24 22:50
That would mean the code is missing [ReflectionOnlyAssemblyResolve](https://msdn.microsoft.com/en-us/library/system.appdomain.reflectiononlyassemblyresolve(v=vs.110).aspx) event

**Comment by bording** [comment] 2017-10-25 15:23
> I think you can run into this problem even on 4.6.1 if you manually GAC netstandard.dll.

@AlexGhiondea While that does seem true, the likelyhood of someone doing that is low. However, upgrading to 4.7.1 makes this guaranteed to happen, and code that was running perfectly fine before the upgrade now breaks.

We've already had one support case around this and we're anticipating more as more people update to 4.7.1.

> That would mean the code is missing ReflectionOnlyAssemblyResolve event

@karelz I'm not sure how that makes a difference. If I add a handler for that event to my repro, it is not called, and I still see the same exception.

**Comment by karelz** [comment] 2017-10-25 15:52
It's a pity ReflectionOnlyAssemblyResolve event doesn't kick in. Might be interesting to find out if it is because of being in GAC or being in unifications list (part of the platform). Either way, it is not going to change the fact that this is by design.
It seems that Reflection was always brittle in this space and the only way how to not technically break it is not change anything at all, which is of course not an option.
I think the same thing will happen to any other OOB which we make part of .NET Framework. Loading it via reflection on version where it is inbox will fail. Similar situations happened in the past many times.

What are the real-world scenarios where this kind of ReflectionOnly iteration is needed? Is it tooling? Plugin model?
How common is the scenario / how many customers are impacted?
Is it reasonable to work around the problem by swallowing such exception?

**Comment by bording** [comment] 2017-12-20 21:25
@karelz To follow up on this, we ended up shipping a patch that added the public key token of netstandard.dll to our internal list of assemblies to skip trying to load, which solved the issue for us.

Our scenario is basically a plugin model, so we're scanning assemblies on disk for relevant types.

**Comment by weshaggard** [comment] 2018-01-18 01:04
Sounds like you have a workaround for this @bording I'm not sure there is much else we can do to help with this scenario from our end, so closing.

**Closed by weshaggard** 2018-01-18 01:04 UTC
Labels: area-Infrastructure, bug
