### ISSUE TITLE
Leaking System.Net.WebSockets.WinHttpWebSocketState in WCF stress

### ISSUE THREAD

**Issue by KKhurin** [dotnet/corefx#5847] opened 2016-02-02 20:50 UTC
We see a fast memory leak on WCF stress using web sockets binding for duplex streaming.
The leaked objects are all rooted by strong GC handles:
~~~
0:011> !gcroot 000000e90c1162b8 
HandleTable:
    000000e58bc85250 (strong handle)
    -> 000000e90c116170 System.Net.WebSockets.WinHttpWebSocketState
    -> 000000e90c1162b8 System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib]]
~~~
And their state indicates that they were disposed:
~~~
 !do 000000e90c116170 
Name:        System.Net.WebSockets.WinHttpWebSocketState
MethodTable: 00007fff0fd7cd58
EEClass:     00007fff0fd83ed8
Size:        120(0x78) bytes
File:        C:\Users\kkhurin\.dnx\packages\runtime.win7.System.Net.WebSockets.Client\4.0.0-rc2-23617\runtimes\win7\lib\dotnet5.4\System.Net.WebSockets.Client.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff678f15e8  400002e        8        System.Object  0 instance 000000e90c1161e8 _lock
00007fff0fd7d468  400002f       10 ...SafeWinHttpHandle  0 instance 0000000000000000 _sessionHandle
00007fff0fd7d468  4000030       18 ...SafeWinHttpHandle  0 instance 0000000000000000 _connectionHandle
00007fff0fd7d580  4000031       20 ...andleWithCallback  0 instance 0000000000000000 _requestHandle
00007fff0fd7d580  4000032       28 ...andleWithCallback  0 instance 0000000000000000 _webSocketHandle
00007fff678f3628  4000033       68 ...Services.GCHandle  1 instance 000000e90c1161d8 _operationHandle
00007fff0fd77078  4000034       58         System.Int32  1 instance                5 _state
00007fff678f5d90  4000035       64       System.Boolean  1 instance                0 _pendingReadOperation
00007fff678f5d90  4000036       65       System.Boolean  1 instance                0 _pendingWriteOperation
00007fff678f5d90  4000037       66       System.Boolean  1 instance                1 _disposed
00007fff0fb9d278  4000038       30 ...olean, mscorlib]]  0 instance 0000000000000000 <TcsUpgrade>k__BackingField
00007fff0fb9d278  4000039       38 ...olean, mscorlib]]  0 instance 000000e88c115ed8 <TcsSend>k__BackingField
00007fff0fb9d278  400003a       40 ...olean, mscorlib]]  0 instance 000000e90c1162b8 <TcsReceive>k__BackingField
00007fff0fb9d278  400003b       48 ...olean, mscorlib]]  0 instance 000000e80c138b70 <TcsClose>k__BackingField
00007fff0fb9d278  400003c       50 ...olean, mscorlib]]  0 instance 000000e90c116320 <TcsCloseOutput>k__BackingField
00007fff0fd7cc00  400003d       5c         System.Int32  1 instance                4 <BufferType>k__BackingField
00007fff67919930  400003e       60        System.UInt32  1 instance                0 <BytesTransferred>k__BackingField
~~~
A repro app is available upon request.

**Comment by davidsh** [comment] 2016-02-02 20:59
Dupe of #3256.

**Closed by davidsh** 2016-02-02 20:59 UTC
Labels: bug, System.Net
