### ISSUE TITLE
System.IO.Compression should support *tar files

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#9673] opened 2016-06-24 21:46 UTC
Now that we have x-plat implementation it'd be great to be able to work with .tar & .tar.gz.

**Comment by jasonwilliams200OK** [comment] 2016-06-27 02:17
Also .bz2 if possible (http://www.bzip.org/1.0.3/html/zlib-compat.html). :)

**Comment by ianhays** [comment] 2016-06-27 17:26
closing as duplicate of https://github.com/dotnet/corefx/issues/3253.

**Closed by ianhays** 2016-06-27 17:26 UTC
Labels: System.IO.Compression
