### ISSUE TITLE
InvalidCastException randomly thrown in WinHttpHandler

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#22251] opened 2017-07-14 04:21 UTC
I haven't been able to repro this since it occured, but am looking into seeing what caused this.

Moved from https://github.com/aspnet/Diagnostics/issues/394

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidCastException: [A]<>f__AnonymousType0`3[System.Net.Http.HttpRequestMessage,System.Guid,System.Int64] cannot be cast to [B]<>f__AnonymousType0`3[System.Net.Http.HttpRequestMessage,System.Guid,System.Int64]. Type A originates from 'System.Net.Http.WinHttpHandler, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Users\hugh\.nuget\packages\system.net.http.winhttphandler\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.Http.WinHttpHandler.dll'. Type B originates from 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Net.Http.dll'.
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.PropertyFetcher.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpCoreDiagnosticSourceListener.OnNext(KeyValuePair`2 evnt)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Net.Http.HttpHandlerDiagnosticListenerExtensions.LogHttpRequestCore(DiagnosticListener diagnosticListener, HttpRequestMessage request)
   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsync(Uri requestUri)
   at System.Net.Http.HttpClient.GetStringAsync(String requestUri)
   at Facebook.GraphClient.<ExecuteRequest>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facebook.GraphClient.<GetPage>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsiaChat.Controllers.PageController.<VerifyFacebookPage>d__19.MoveNext() in C:\Users\hugh\Documents\GitHub\asia-chat\src\backend\AsiaChat.WebAPI\Controllers\PageController.cs:line 232
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AsiaChat.Controllers.PageController.<Update>d__16.MoveNext() in C:\Users\hugh\Documents\GitHub\asia-chat\src\backend\AsiaChat.WebAPI\Controllers\PageController.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1851.0059ms 500 text/html; charset=utf-8
```

**Comment by davidsh** [comment] 2017-07-15 03:29
>Microsoft.ApplicationInsights.DependencyCollector.Implementation.PropertyFetcher.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)

@brianrob @vancem Can you take a look at this?  The `InvalidCastException` is really coming from the ApplicationInsights code which is using information generated by the Diagnostics.

**Comment by vancem** [comment] 2017-07-17 15:47
Including @SergeyKanzhelev from app-insights.

**Comment by hughbe** [comment] 2017-07-18 02:30
Thanks. We're now hitting this on our production server - it seems to be random at this point

**Comment by lmolkova** [comment] 2017-07-18 18:10
@hughbe 
> System.InvalidCastException: [A]<>f__AnonymousType0`3[System.Net.Http.HttpRequestMessage,System.Guid,System.Int64] cannot be cast to [B]<>f__AnonymousType0`3[System.Net.Http.HttpRequestMessage,System.Guid,System.Int64]. Type A originates from 'System.Net.Http.WinHttpHandler, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Users\hugh\.nuget\packages\system.net.http.winhttphandler\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.Http.WinHttpHandler.dll'. Type B originates from 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Net.Http.dll'.

Perhaps AsiaChat.ImportExport.csproj depends on WinHttpHandler assembly (`C:\Users\hugh\.nuget\packages\system.net.http.winhttphandler\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.Http.WinHttpHandler.dll`).

However WinHttpHandler is also compiled into System.Net.Http.dll.

Application Insights listens to diagnostics events with complex payload from System.Net.Http/WinHttpHanler and attempts to cache the type of the payload to improve performance. Since types are different, it fails.

I'll provide some workarounds in the 
https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/650 shortly.

Also, it should not reproduce with .NET Core 2.0 as diagnostics events were moved away from WinHttpHandler.

**Comment by hughbe** [comment] 2017-07-19 02:10
The deps for AsiaChat.ImportExport is
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="CsvHelper" Version="3.0.0-chi06" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsiaChat.Core\AsiaChat.Core.csproj" />
  </ItemGroup>
  
</Project>
```

And for AsiaChat.Core
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Auth0" Version="3.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Facebook.NET" Version="1.0.8" />
    <PackageReference Include="Pagination.Elasticsearch" Version="1.0.7" />
    <PackageReference Include="System.ValueTuple" Version="4.3.1" />
  </ItemGroup>

</Project>
```

I think the issue is in a package further down, [Facebook.NET](https://github.com/hughbe/Facebook.NET/blob/master/src/Facebook.NET/Facebook.NET.csproj)

And here we see `WinHttphandler`:
```
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
    <PackageReference Include="Pagination.Primitives" Version="1.0.0" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="4.3.0" />
  </ItemGroup>
```

As a package author, is it safe to conclude that referencing `System.Net.Http.WinHttpHandler` can and will break clients upstream? This sounds pretty bad.

**Comment by lmolkova** [comment] 2017-07-19 16:48
@hughbe 
Thanks for the update.

Referencing WinHttpHandler does not break the app. It's the issue in the ApplicationInsights (https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/650) that breaks them.

it happens under following conditions 
- app targets  .net core < 2.0
- app or its dependency uses WinHttpHanlder directly AND HttpClient
- app depends on AppInsights SDK 2.1+ (with dependency collection module enabled - by default)

Please follow workarounds described in the AppInsights issue (stay on the old SDK or disable single module that causing the error)

**Comment by davidsh** [comment] 2017-11-22 21:33
>Also, it should not reproduce with .NET Core 2.0 as diagnostics events were moved away from WinHttpHandler.

Closing this issue since it no longer occurs in current .NET Core versions.

**Closed by davidsh** 2017-11-22 21:33 UTC
Labels: area-System.Net.Http, bug
