### ISSUE TITLE
Cross Platform GUI for desktop applications?

### ISSUE THREAD

**Issue by Phidler** [dotnet/corefx#27712] opened 2018-03-05 00:35 UTC
As one of the co-founders of a local startup, my partners and I were looking for a framework that could do it all and do it well. .NET Core very closely hit the mark but fell short in just one specific area: a cross-platform library for a Graphical User Interface.

I wasn't sure where to post this but I thought it was worth mentioning as an important feedback, my partners and I are big fans of what .NET Core is able to achieve (and the tools available for it) but we had to look elsewhere due to the fact that we need to be as efficient as possible due to our limited resources.

Hopefully our feedback and request makes a difference.

Phidler

**Comment by ahoefling** [comment] 2018-03-05 01:03
Technically you can use Xamarin.Forms and build out an app that works on Mobile, Windows Desktop, Ubuntu Desktop, MacOS and more.

Last time I checked it supports the following popular platforms:
* iOS
* Android
* UWP
* WPF
* MacOS
* GTK (ubuntu)
* Ooui.Forms (asp.net core, but it is still very experimental)
* I know there is more but these are the popular

**Comment by Clockwork-Muse** [comment] 2018-03-05 06:37
Also [Avalonia](https://github.com/AvaloniaUI/Avalonia) (still in beta)

**Comment by gfoidl** [comment] 2018-03-05 08:11
Also see https://github.com/dotnet/designs/issues/12

**Comment by karelz** [comment] 2018-03-05 17:10
Duplicate of https://github.com/dotnet/designs/issues/12

**Closed by karelz** 2018-03-05 17:11 UTC
Labels: area-Meta, question
