### ISSUE TITLE
Span: Fix fast Span TFM in System.Memory

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#14682] opened 2016-12-22 08:35 UTC
Right now fast span has a netcoreapp1.1 but the fast span doesn't actually exist in there. It should be whatever the next version of netcoreapp is going to be called.

/cc @ahsonkhan @ericstj @weshaggard @KrzysztofCwalina

**Comment by davidfowl** [comment] 2016-12-22 08:36
Here's the error you get when you run in on 1.1:

Unhandled Exception: System.MissingMethodException: Method not found: 'System.Span`1\<Byte\> System.Buffers.IOutput.get_Buffer()'.    at System.IO.Pipelines.Samples.RawLibuvHttpServerSample.Run()    at System.IO.Pipelines.Samples.Program.Main(String[] args)

**Comment by ericstj** [comment] 2016-12-22 16:11
Duplicate of https://github.com/dotnet/corefx/issues/14501

**Comment by ericstj** [comment] 2016-12-22 16:14
I believe you're just stating that we ought to use the netstandard1.0 implementation rather than the facade on netcoreapp1.1.  That will happen when @alexperovich finishes the rename that moves nearly all netcoreapp1.1 assets to netcoreapp2.0.

**Closed by ericstj** 2016-12-22 16:14 UTC

**Comment by KrzysztofCwalina** [comment] 2016-12-22 17:01
cc: @ahsonkhan

**Comment by davidfowl** [comment] 2016-12-22 21:54
@ericstj Do you know when that's happening?

**Comment by ericstj** [comment] 2016-12-23 00:23
He's in the middle of it, but I guess did not finish before holidays.  I suspect as soon as he comes back he'll finish.
