### ISSUE TITLE
Is there a way to port System.Beep to multiplattform?

### ISSUE THREAD

**Issue by paule96** [dotnet/corefx#32070] opened 2018-09-01 23:29 UTC
Hallo .NET Communtiy,

I have play a little bit with System.Beep. but then I see [here](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/Interop/Windows/kernel32/Interop.Beep.cs) in the source code that only supports Windows. (and also I try it on a ubuntu bash...)

Can we port this to the other plattforms too? It would be very great! Currently [this](https://github.com/nickvdyck/nyancat.cs/issues/1) project would be very thankful.

**Comment by danmosemsft** [comment] 2018-09-02 01:09
Hello! Would you like to offer a PR?

**Comment by jkotas** [comment] 2018-09-02 05:08
Duplicate of https://github.com/dotnet/corefx/issues/25746

**Closed** 2018-09-02 05:41 UTC
Labels: area-System.Console
