### ISSUE TITLE
Loading assemblies with dependencies at runtime

### ISSUE THREAD

**Issue by pushist1y** [dotnet/corefx#13057] opened 2016-10-26 20:35 UTC
Trying to implement loose coupling approach in my new application i've run into problem. 
I have a main application, an assembly with abstractions and an assembly which i want to load dynamically. The actual loading code is:

`foreach (var path in paths)
                {
                    var fullPath = Path.Combine(System.AppContext.BaseDirectory, path);
                    if (!File.Exists(fullPath)) continue;
                    var asm = AssemblyLoadContext.Default.LoadFromAssemblyPath(fullPath);
                    moduleTypes.AddRange(
                        asm.GetTypes().Where(mytype => mytype.GetInterfaces().Contains(typeof(IDynamicModule))));
                }`

After that i instatiate IDynamicModule classes and make them do some work. On the `GetTypes()` operation i'm getting an exception:
`{System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Не удается найти указанный файл.
File name: 'Microsoft.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'}`

(Entity Framework is referenced by dynamic assembly).
Playing with framework and assembly versions i've somehow managed to load the assembly and run some code in it, but when it comes to actually working with `DbContext` i'm also getting the same exception but for `Npgsql.EntityFrameworkCore.PostgreSQL`.

Looks like there are some problems with loading assemblies that have their own references on external modules. I've implemented sample project illustrating this problem. 

https://github.com/pushist1y/ErrorReproductions/tree/master/DotNetCoreAssemblyLoading

**Comment by karelz** [comment] 2017-03-01 00:14
Looks like dupe of #11639.

**Closed by karelz** 2017-03-01 00:14 UTC
Labels: area-System.Reflection
