### ISSUE TITLE
Type 'System.TimeZoneInfo' cannot be serialized by DCS

### ISSUE THREAD

**Issue by mlacouture** [dotnet/corefx#27773] opened 2018-03-06 13:12 UTC
Originally reported as a [VS Feedback issue](https://developercommunity.visualstudio.com/content/problem/200357/unable-to-create-web-service-reference-on-net-core.html).  
Try the following code:
```
TimeZoneInfo tzi = TimeZoneInfo.Local;
DataContractSerializer ser = new DataContractSerializer(typeof(TimeZoneInfo));
MemoryStream stream = new MemoryStream();
ser.WriteObject(stream, tzi);
```

The following exception is thrown:

> System.Runtime.Serialization.SerializationException
>   HResult=0x8013150C
>   Message=Type 'System.TimeZoneInfo+AdjustmentRule[]' with data contract name 'ArrayOfTimeZoneInfo.AdjustmentRule:http://schemas.datacontract.org/2004/07/System' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

**Comment by huanwu** [comment] 2018-03-09 18:55
This can also be reproed in full framework with the following simple code. When to serialize the following type, it will fail when to check if MySubClass is a known type. If adding [KnownType(typeof(MySubClass[]))] on MyClass, all works as expected.

```
   [Serializable]
    public class MyClass : ISerializable
    {
        public MySubClass[] MySubClassArray { get; set; }

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("MySubClassArray", MySubClassArray);
        }
    }

    [Serializable]
    public class MySubClass : ISerializable
    {
        public string MySubString { get; set; }

        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("MySubString", MySubString);
        }
    }
```

**Comment by huanwu** [comment] 2018-03-13 22:34
After investigation, TimeZoneInfo need fix this problem so it can support DCS.  The error is because it try to serialize AdjustmentRule but AdjustmentRule is not a  known type for TimeZoneInfo. Actually, AdjustmentRule should not be serialized. It need be ignored during serialization and reconstructed during deserialization based on OS information.

**Comment by Clockwork-Muse** [comment] 2018-03-13 22:51
@huanwu - Note that doing so may mean a deserialized datetime value no longer represents the same instant in time.

On the one hand, normally you _don't_ want to transmit the full set of rules (due to size), so making this automatic is nice.
On the other, I really wish people would make this explicit by passing the id, since whoever receives it on the other end (or even you, if there's a big enough time delay) may not have the same set of rules, and looking up the rule from the id would at least be a big hint that the situation was possible.

**Comment by tarekgh** [comment] 2018-03-15 18:46
> The error is because it try to serialize AdjustmentRule but AdjustmentRule is not a known type for TimeZoneInfo

@huanwu what you mean by that? AdjustmentRule is a class defined inside TimeZoneInfo. why it is not known? please elaborate more on that.

**Comment by tarekgh** [comment] 2018-03-15 23:20
@huanwu 

> Actually, AdjustmentRule should not be serialized. It need be ignored during serialization and reconstructed during deserialization based on OS information.

This is not possible because TimeZoneInfo can be created using custom rules which would be user specific.

**Comment by huanwu** [comment] 2018-03-16 17:16
@tarekgh I will take a look if any workaround works for you case.

**Comment by tarekgh** [comment] 2018-03-16 22:36
@mlacouture here is the way you can allow DCS to serialize the TimeZoneInfo object. but in general, if you have the choice, don't serialize the TimeZoneInfo object and instead serialize the zone id (i.e. TimeZoneInfo.Id). I am closing this issue but feel free to send any more questions if you have any. Thanks for reporting the issue.

```C#
    [DataContract]
    [KnownType(typeof(System.TimeZoneInfo))]
    [KnownType(typeof(System.TimeZoneInfo.AdjustmentRule))]
    [KnownType(typeof(System.TimeZoneInfo.AdjustmentRule[]))]
    [KnownType(typeof(System.TimeZoneInfo.TransitionTime))]
    [KnownType(typeof(System.DayOfWeek))]
    public class TimeZoneInfoDataContarct
    {
        [DataMember]
        private TimeZoneInfo _zone;

        public TimeZoneInfoDataContarct()
        {
            _zone = TimeZoneInfo.Local;
        }

        public TimeZoneInfo TimeZone => _zone;
    }
```
And then you can do 

```C#
            DataContractSerializer ser = new DataContractSerializer(typeof(TimeZoneInfoDataContarct));
            MemoryStream stream = new MemoryStream();
            ser.WriteObject(stream, new TimeZoneInfoDataContarct());
```

**Closed by tarekgh** 2018-03-16 22:36 UTC
Labels: area-System.Runtime

**Comment by mlacouture** [comment] 2018-03-16 23:17
@tarekgh, thanks for providing the workaround but unfortunately it can't be used in the context of the [orginal issue](https://developercommunity.visualstudio.com/content/problem/200357/unable-to-create-web-service-reference-on-net-core.html) as the serialization is done by a tool.

**Comment by tarekgh** [comment] 2018-03-16 23:27
@mconnew can you think of any workaround for the @mlacouture scenario?

**Comment by wadebaird** [comment] 2018-09-26 02:49
@tarekgh : Above you mentioned that ideally the TimeZoneInfo.Id should be sent. However the issue is on some devices the TimeZones are identified as "America/Los_Angeles" where as on a Windows server it is identified as "Pacific Standard Time". 

How is this reconciled?  I am trying to send the timezone from my device to the server in order to get date times in the device local time.

**Comment by Clockwork-Muse** [comment] 2018-09-26 02:58
@wadebaird - The primary non-Windows Timezone database is the Olson/IANA tzdb, used by pretty much everybody else.  For interoperability, you almost certainly want to expose/use the Olson ones.

How you interoperate depends on a couple of things, but you're essentially looking at a couple of third-party nuget packages:
 - Just go for translating the ids, using @mj1856's [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter)
 - For fuller date/time support, which includes translated ids, use [NodaTime](https://nodatime.org/)

**Comment by tarekgh** [comment] 2018-09-26 03:53
@clockwork-muse is correct. You can use @mj1856 library for I’d translation between the windows Id and IANA id.
