### ISSUE TITLE
Propose: new method Enumerable.IndexOf 

### ISSUE THREAD

**Issue by Ricciolo** [dotnet/corefx#1415] opened 2015-04-15 15:30 UTC
Hi, I would like to propose a new member for Enumerable class:

    int IndexOf<T>(IEnumerable<T> source, T item, IEqualityComperer<T> comparer)

It's useful to find the index of an item inside the source. Only `IList` has a similar method but it forces me to completely materialize all the source. The implementation can enumerate list or, if the original source type is `IList`, call the `IList.IndexOf` method. If the source type is an `Array` we can call `Array.IndexOf`.

What do you think?

**Comment by svick** [comment] 2015-04-15 15:50
> It's useful to find the index of an item inside the source.

When is that useful? Finding an index is useful for `IList`, because you can then use that index to quickly read or write the item at that index. But that doesn't apply to `IEnumerable` (`ElementAt()` can be O(n)).

**Comment by Ricciolo** [comment] 2015-04-15 16:06
Many times I need to find the index of an item inside an IEnumerable. An easy example

    var source = new [] { 1, 2, 3, 4 };
    var i = source.Skip(2).IndexOf(3);
    // i == 0

**Comment by svick** [comment] 2015-04-15 16:46
My question is, how are you going to use that index?

**Comment by Aevitas** [comment] 2015-04-15 17:18
You cannot index directly into an `IEnumerable`, therefore it'd make little sense to provide an `IndexOf` for this specific case in my opinion.

**Comment by saguiitay** [comment] 2015-04-15 17:22
I can see scenarios where the index itself is the needed information. For example, sorting high-scores of a game, and getting the "position" of the player ("You are in the 4th place")...

**Comment by Aevitas** [comment] 2015-04-15 17:37
@saguiitay There are already ways to achieve this: calling either `ToArray()` or `ToList()` on the `IEnumerable` and then using `IndexOf`. `IEnumerable` is a declaration of a certain behaviour while `List<T>` et. al implement this behaviour.

Using an `IEnumerable` provides the option of deferred execution, something you would have to sacrifice in order to provide an `IndexOf` as the compiler would have to reify it on the spot to gather that information.

**Comment by bbarry** [comment] 2015-04-15 18:05
You could also do it with `.TakeWhile(...).Count()`

**Comment by Clockwork-Muse** [comment] 2015-04-15 21:30
...And would return nonsense results for unordered PLINQ queries.  You'd need to use ordering **and** completely run it out to an array/list - what happens if your ordering key is non-unique?
(Granted, that's true of a number of other order-requiring operations, like `ElementAt(...)`)

**Comment by krwq** [comment] 2015-04-16 00:44
I believe you should be using IList instead of IEnumerable. IEnumerable by design doesn't have indices. You can always add static extension method if you need that functionality

**Comment by Ricciolo** [comment] 2015-04-16 09:56
@Aevitas `ToList` and `ToArray` force me to materialize all the list. Why should I create an in memory array for all elements when the item I've to find is at the beginning? You are right, `IEnumerable` is for deferred exceution, but some methods are for final execution. `Single`, `SingleOrDefault`, `First`, `FirstOrDefault`, `Count`, `Any`, ecc do the final execution. So `IndexOf` can be added without any problem.

@bbarry  `.TakeWhile(...).Count()` is a good solution but not complete. What happen if the item is not inside the source? `Count` returns the number of items inside the source and it's wrong. I should call `Count` without calling the `TakeWhile` in order to get how many items the list has.

@Clockwork-Muse @krwq take a look at `ElementAt`, `Select`, `Where`, `SkipWhile`, `TakeWhile`. They have an overload with an index parameter, so your statements are wrong. If I'm using a PLINQ I've the same issue calling ToList and ToArray: the result is unorderer. I can use AsOrdered to get an orderer result and call IndexOf.

**Comment by Clockwork-Muse** [comment] 2015-04-16 13:34
@Ricciolo - It has those methods/overrides because **LINQ** has them.
It would be extremely expensive to use an `IndexOf`/`ElementAt` pair (safely) - you're looking at `O(n)` for both (and an additional `O(n log(n))` each if the needed ordering is different than the current), plus the actual costs of the parallelization (which isn't cheap either).  You're materializing the entire range at least twice, possibly more than 4 times; you'd probably be better off actually calling `ToArray()` (or whichever) in such a case.

Why is `ElementAt(...)` part of LINQ anyways?  It feels more like a pitfall - you wouldn't want to call it repeatedly on a dataset (it'd be really bad to try using it for iteration).

Note that if you really need to find the index of an element so you can later retrieve it, you could do something like (ab)use `Select((item, index) => Tuple.Create(item, index)).First(...)`, which  is more likely to do a single `O(n)` run through the origin source and net you both.

**Comment by Ricciolo** [comment] 2015-04-16 13:49
@Clockwork-Muse the PLINQ problem is not mine :-) but it's example done by you. If it's slow in a particular case, is up to me. It's slow if I use `Select` or other methods too. We're not talking about if the method is slow or fast in particular case. If we think in this way we should remove all LINQ methods.
I have an `IEnumerable` and I need the index of an item. If the source is parallized I know that the index doesn't make sense and must be orderer. In other case, where the source is filtered, it makes sense.

Sorry but  `Select((item, index) => Tuple.Create(item, index)).First(...)` is slower (the index is ordered? No, you need to call AsOrderer) like `IndexOf/ElementAt` if the source is parallelized.

**Comment by SamuelEnglard** [comment] 2015-04-17 02:36
I'm against this under the idea the `IEnumerable<T>` and the Linq methods are stream like and `IndexOf` breaks that. `IndexOf` is an idea that belongs on collections that are ordered at the very least. something that `IEnumerable<T>` does not provide.

If you want to put it on `IOrderedEnumerable<TSource>` that I could see making some sense, though I'm still not a huge fan of the idea.

As I'm writing this what I think could work is a `T Till<T>(this IEnumerable<T> collection, T item)` method. The method simply tells you how many iterations it went through to get to the item. No guarantees that if you call it again the result will be the same. And yes on types that implement `ICollection` we could just call `IndexOf `

**Comment by Ricciolo** [comment] 2015-04-17 08:27
Thank you @SamuelEnglard. I like the idea of `Till` :-) I understand the worries about the stream approach, but if so, why there is `ElementAt`? Moreover consider that `Array.IndexOf` and `List.IndexOf` don't use `IEqualityComparer` and this is very important in LINQ

**Comment by Clockwork-Muse** [comment] 2015-04-17 09:29
@Ricciolo - I'm becoming rather less fond of `ElementAt`, too, for the exact same reason (although I'm starting to think of LINQ more like SQL).
What actual, real-world problem are you trying to solve?  If you're working with streams, `IndexOf`/`ElementAt` sound like the wrong approach.  Can you show us something where'd you actually use it?  In your previous snippet, **why** do you need to know the index of `3`, and what do you plan to do with this information?

**Comment by SamuelEnglard** [comment] 2015-04-17 15:39
@Clockwork-Muse I think `ElementAt` is meant to be a shortcut for `Skip(x).First()`
@Ricciolo The fact that `IndexOf` does not use `IEqualityComparer` or provide a way to use a lambda to compare with is something that should be fixed but not on `IEnumerable<T>`. I'd put such a method as an extension to `ICollection<T>`, which arrays indirectly implement.

**Comment by stephentoub** [comment] 2015-04-22 15:16
> Many times I need to find the index of an item inside an IEnumerable

@Ricciolo, you provided a code sample, and @svick asked "My question is, how are you going to use that index?".  I don't think I saw an answer to that (apologies if I just missed it), and I have the same question... after getting the index, what do you then do with it?

**Comment by joshfree** [comment] 2015-10-13 14:34
I'm closing out this issue as the discussion ended ~6 months ago.  Please feel free to reactivate the issue if you disagree or if you have more to add (ie., how the index would be used).  Thank you

**Closed by joshfree** 2015-10-13 14:34 UTC
Labels: needs more info, suggestion, System.Linq
