### ISSUE TITLE
Inconsistent behavior between net461 and netappcore2.0/2.1

### ISSUE THREAD

**Issue by devcrafting** [dotnet/corefx#32415] opened 2018-09-22 22:07 UTC
Hi,

I got different behavior with HTTP request to the following URL : `https://ti.urssaf.fr/tbl_telepaiements?s4yYdH0QoNhh2COxV4F24GmPNGD/9jTM+CvU4H9hYWvC96bR/YLtGprWBLEidvt8/eqhprwq04KZBpUL/7ByydHcjhibpk4DFaywYdtgsarBvaYpS9OPLuH1Sr3+uBxg9jCq3QjivHLrtQHeWhiG4YzuvBLTGs4LV0L7c3bxACG8qWPH1qgdhx77IjXyGCAUZYq9dPjI2EtBol0ET298bsTSVqrgWYRqtwThmD5KlQPr6qhq5/52N+hZFKRM2zEx+ojaO4S2K8p1wNotw/aAvEzKH89Edo2pO7lKd8gGIw1oM/ZIcTaOgiqTK//O4eLfW+7v7ECG5WdLNu2bpLwYj+R+ZYJmhA8tqx78dkC1HSfn1DaLwTc7nnl0LH50VYq2diA/vGwlNUmaLMZHQ67sl2st1RAQKSg1mBxR4sJcVd+fa3x/VviZzhyGHzVZ4JGTOS4wVOkrcmP0EufPeMPSDxFs+jpMEWU76EOxeo48cGY1y+ixLaeu2kChgES1q7HklamVLpVkbfvYTAkdtNgIEwnUkOg04mW1VGGTSBIFP8IRquSyiXW1uOEFCucp+JSNbhL4W8xcavJwdKShnFSf0Z4kwf6eNybhurnUomItLnumI+CN17eYwYNovdJopgRE6MOwl8OfcO+iQ/2nx3RdQ9kczgP+K6l7yQDZQo45NjGT38CzTmqztdbhP87pRHSAo+7GIbpt9uX8X11k0VI9+VvA2QW6zMeCZ1MtQdm8fyhiEzrpV5UkyU84Rh3rwiU86GEW1/4Q9fM8NjrQvaOdOqtPzUs5hB723gGuhnBBrVC8/1mX9jfnDrrRqVIOador9ALu+6sXTmgAlOYQcbAKgcbpWYUH72q12yld8LNSSmUBQR2IzhqUcZ4vILuL8o9aiJVu/QjLTUDN0+fsMR4DSVrXWlcOApY4RgDyUYodRtGHxBYP2RwtjSAwifLvVDu9w8R2xUpudO24G5wgD/7Ic6ono2T7m7ajF5Hu8rDJtvXEILuhxa/JymW+vanpa3wK4UPckLL06hCK3+j8W0bJPu+Uo8mZKBsGmGDh3CekM7An8fA+eQtvH/LSZT3IGEpo2QTfog4q6NqL6zfcFCb9FZY59Zz2Ci8WlQO1uNdEhBc=,1#0`

I discovered it with FSharp.Data, but I reproduced it with the following very simple code :
```c#
var req = WebRequest.CreateHttp(url);
req.CookieContainer = cookieContainer;
var resp = req.GetResponse();
```

I am using dotnet SDK 2.1.402. Launched with netcoreapp2.1 or netcoreapp2.0, I got WebException with HTTP 404 error. When I switch to net461, I got expected HTTP 200. 
I checked the raw HTTP request with Fiddler, I saw that net461 version stripped `#0` at the end of the URL, whereas netcoreapp2.x did not. I don't know if stripping comes from low level API (WinINET, WinHTTP...) or from .NET 4.6.1. Could you check and ensure that it behaves the same way ? Thank you.

Note the provided URL returns "error" in HTML content (because of missing auth cookies), but I got the exact same results with or without cookies. So you can reproduce with this URL.

**Comment by davidsh** [comment] 2018-09-22 22:52
@rmkerr @karelz

**Comment by geoffkizer** [comment] 2018-09-25 02:58
This looks like the same issue as #32378. 

Since this appears to repro on netcoreapp2.0, I assume WinHttpHandler is sending fragments as well.

**Comment by karelz** [comment] 2018-10-01 18:08
Duplicate of 32378

**Closed by karelz** 2018-10-01 18:08 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
