### ISSUE TITLE
text.json, how to surface meaningful GetString() exception?

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#36109] opened 2019-03-17 22:14 UTC
The current "there is a type mismatch exception" is like the following without extra effort . It is very hard for the user to figure out which field has the type mismatch.

```
System.InvalidOperationException: The requested operation requires an element of type 'Number', but the target element has type 'String'.
   at System.Text.Json.JsonDocument.TryGetValue(Int32 index, Int32& value)
   at System.Text.Json.JsonElement.GetInt32()
```

I tried to handle the exception on the call side. However i would bloat every GetBlah() to multi line try catch.

from 
```c#
                    if (root.TryGetProperty("isRoot", out var isRoot))
                    {
                        serializableLocalToolsManifest.IsRoot = isRoot.GetBoolean();
                    }
```

to

```c#
                    if (root.TryGetProperty("isRoot", out var isRoot))
                    {
                        try
                        {
                            serializableLocalToolsManifest.IsRoot = isRoot.GetBoolean();
                        }
                        catch (InvalidOperationException ex)
                        {
                            throw new ToolManifestException($"try to get field isRoot, but {ex.Message}");
                        }
                    }
```

I cannot extract a simple common method since i would need to make overload for GetBoolean(), GetString()... 

It is possible to make a generic `Get<T>()` ? 
Or add an API TryGetBoolFromProperty(string property) so it knows the property name and surfaces that in error message?
Or somehow make the error message has the original property name or the line number?
Or do you have other suggestion/pattern so the code won't be too crazy just to handle the error?

my code 
```c#
               using (JsonDocument doc = JsonDocument.Parse(json))
                {
                    JsonElement root = doc.RootElement;

                    if (root.TryGetProperty("version", out var version))
                    {
                        serializableLocalToolsManifest.Version = version.GetInt32();
                    }

                    if (root.TryGetProperty("isRoot", out var isRoot))
                    {
                        serializableLocalToolsManifest.IsRoot = isRoot.GetBoolean();
                    }

                    if (root.TryGetProperty("tools", out var tools))
                    {
                        serializableLocalToolsManifest.Tools =
                            new Dictionary<string, SerializableLocalToolSinglePackage>();

                        foreach (var toolJson in tools.EnumerateObject())
                        {
                            var serializableLocalToolSinglePackage = new SerializableLocalToolSinglePackage();
                            if (toolJson.Value.TryGetProperty("version", out var versionJson))
                            {
                                serializableLocalToolSinglePackage.Version = versionJson.GetString();
                            }

                            var commands = new List<string>();
                            if (toolJson.Value.TryGetProperty("commands", out var commandsJson))
                            {
                                foreach (var command in commandsJson.EnumerateArray())
                                {
                                    commands.Add(command.GetString());
                                }

                                serializableLocalToolSinglePackage.Commands = commands.ToArray();
                            }

                            serializableLocalToolsManifest.Tools.Add(toolJson.Name, serializableLocalToolSinglePackage);
                        }
                    }
                }
```

**Comment by wli3** [comment] 2019-03-17 22:17
@ahsonkhan @steveharter

**Comment by wli3** [comment] 2019-03-17 22:31
interesting found, compare with deserializer of newtonsoft.json, "1" vs 1 is not an error. But if it is an array vs an int it results in the following error (one of the subtle behavior change i am afraid of breaking after the feature is released). With line number, it is still easy to act upon.
```
Newtonsoft.Json.JsonSerializationException: Error converting value 1 to type 'System.Collections.Generic.Dictionary`2[System.String,Microsoft.DotNet.ToolManifest.ToolManifestEditor+SerializableLocalToolSinglePackage]'. Path 'tools', line 4, position 11. ---> System.ArgumentException: Could not cast or convert from System.Int64 to System.Collections.Generic.Dictionary`2[System.String,Microsoft.DotNet.ToolManifest.ToolManifestEditor+SerializableLocalToolSinglePackage].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
```

**Comment by ahsonkhan** [comment] 2019-03-18 23:35
cc @bartonjs

**Comment by bartonjs** [comment] 2019-03-19 00:26
> It is possible to make a generic Get<T>() ?

`JsonElement.Get<T>` seems unfortunate to me, because it either

A) only supports a small list of types (and as you go forward/backward across API editions you can't know when you gained/lost support for those types)
B) does conversion magic, leading to unpredictability (e.g. int.Parse on `"1"` because you asked for it as an int... which seemed to be a surprise)

You would be free, of course, to write a `Get<T>` extension method and switch on the target type; as something inside your own code it doesn't suffer the drawbacks of having unclear levels of support.  But I'm not sure that solves the "what property is this?" (unless it was `Get<T>(string propertyName)`)

> Or somehow make the error message has the original property name?

A JsonElement could have come from a property (value), an array (position) or was the payload root; so it can't just generically emit "the property name".  (It also currently doesn't actually know how you got to it).

There's then also the general context/history problem of how much data should the API leak across call boundaries.  If I'm an API that accepts JsonElement should I be allowed to know how you got to it? (Since my main area is security I always start with "don't share more than you need to", but I'm perhaps not normal in this regard.)

> ... or the line number?

The only piece of data that JsonElement can really recover is how many bytes into the payload did it start.  But even that piece of data will become weird soon, as we're working on a feature to "Detach" a (copy of a) JsonElement from its JsonDocument, which would reset its byte offset to zero.  ... and that's also against one of the design goals of JsonDocument, which is to not have the API leak out any details about the original input text encoding (currently only UTF-8, but we've removed things from the API which would make that be a requirement).

> Or add an API TryGetBoolFromProperty(string property) so it knows the property name and surfaces that in error message?

This one is a little tricky.  One of the rules of the Try(-Parse) pattern is that the try must be defined in "strict" terms (and exceptions cover the rest of the cases).  So, ideally, the false return maps either to the property not existing, or the value not being a valid Boolean, but not both.  This mixes both state and argument semantics, so it's unclear which one would be a return and which would be a throw.

> Or do you have other suggestion/pattern so the code won't be too crazy just to handle the error?

```C#
internal static bool GetBooleanProperty(this JsonElement element, string propertyName)
{
    if (element.TryGetProperty(out JsonElement value))
    {
#if TESTER_DOER
        if (value.Type == JsonValueType.True && value.Type == JsonValueType.False)
        {
            return value.GetBoolean();
        }
        else
        {
#else
        try
        {
            return value.GetBoolean();
        }
        catch (InvalidOperationException)
        {
#endif
            throw new [SomeSortOf]Exception($"Property {propertyName} should be boolean, but has type {value.Type}.");
        }
    }

    throw new [SomeSortOf]Exception($"Required property {propertyName} was not found.")
}
```

Or

```C#
internal static T GetPropertyValue<T>(this JsonElement element, string propertyName)
{
    Type t = typeof(T);

    if (!element.TryGetProperty(propertyName, out JsonElement value))
    {
        throw new [SomeSortOf]Exception($"Required property {propertyName} was not found.");
    }

    try
    {
        if (t == typeof(bool))
            return (T)(object)value.GetBoolean();
        if (t == typeof(int))
            return (T)(object)value.GetInt32();
        ...

        throw new ArgumentOutOfRangeException(
            nameof(T),
            $"Destination type {t.FullName} is not supported");
    }
    catch (InvalidOperationException e)
    {
        throw new [SomeSortOf]Exception($"Failed to read property '{propertyName}': {e.Message}", e);
    }
}
```
---

In general, the thought processes so far have been around server high-throughput scenarios, and trying to keep both CPU and memory utilization low.  Servers, at least historically, tend to not want contextual data (e.g. a property name) in their exceptions.   And there's a question of how much space we want to pay for storing context for exceptions, since that penalizes mainline/golden-path scenarios.

**Comment by wli3** [comment] 2019-03-21 05:11
> Servers, at least historically, tend to not want contextual data

I worked in service before. I would also use GetPropertyValue<T>. A lot of time it is impossible to log the full request json due to privacy. If I am a DRI and see this error in my log, it is really not helpful. 
 And the other party calling it would also get confused when there is no schema at hand.

What worries me more is newtonsoft.json does not validate type like "42" vs 42, so some end user will start to get the System.InvalidOperationException if there are such problem in existing json file, even API calls. And it would be hard act on this error due to the lack of context.

**Comment by wli3** [comment] 2019-03-21 05:12
Thank you for the write up. `GetPropertyValue<T>` is good enough for me

**Comment by wli3** [comment] 2019-04-01 22:59
Circle back. In the code review `GetPropertyValue<T>` is still not good enough. I end up writing overload for bool, string, number. Plus the nesting is deep and error handling have to mix with parsing code.

**Comment by ahsonkhan** [comment] 2019-06-04 23:28
Adding an unconstrained generic API which only works for a small set of types is not something we have precedence for within .NET. The scenario here relates to the user wanting to control the exception behavior (and throw custom exception) and that would have to be resolved by the caller writing custom code to do so. Hence, this is by-design and the issue is non-actionable. Closing.

**Closed by ahsonkhan** 2019-06-04 23:28 UTC
Labels: area-System.Text.Json
