### ISSUE TITLE
Publishing Core application targeting net461

### ISSUE THREAD

**Issue by capiono** [dotnet/corefx#13504] opened 2016-11-09 00:22 UTC
In order to use Oracle I'm targeting net461 in my Core application. After  publishing IIS on win server 2012. 
I get this error:
![image](https://cloud.githubusercontent.com/assets/9387260/20122641/2cc1cd10-a5e7-11e6-8fed-c819c6e104d0.png)
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetApplicationBasePath()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```
my config file:

 `<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" disableStartUpErrorPage="true"/>`

after publishing looks like this:

`<aspNetCore processPath=".\Fwims.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />`

[project.json.txt](https://github.com/dotnet/corefx/files/579673/project.json.txt)

However, if I target: 

```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
```
It works fine. 

How do I make it work with net461?

**Comment by karelz** [comment] 2016-11-09 00:37
@weshaggard @ericstj any advice here?

**Comment by weshaggard** [comment] 2016-11-09 00:42
It looks like when you are targeting net461 the System.AppContext library is missing. In your project.json file I don't see any direct references to that package perhaps it is missing from the dependencies from the PlatformAbstractions when targeting net461. 

@capiono try adding a package dependency to System.AppContext version 4.1.0 and see if that helps.

**Comment by capiono** [comment] 2016-11-09 00:57
No, that didn't help.

**Comment by weshaggard** [comment] 2016-11-09 16:43
@davidfowl does this issue look familiar?

**Comment by capiono** [comment] 2016-11-11 09:17
Any update on this?

**Comment by karelz** [comment] 2016-11-11 16:17
@davidfowl ping?

**Comment by capiono** [comment] 2016-11-14 07:05
the .exe is ran in a command prompt, it throws this exception: 
`Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'System.Diagnostics.DiagnosticSourceEventSource' threw an exception. ---> Syst
em.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.Ev
entSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)'.
   at System.Diagnostics.DiagnosticSourceEventSource..ctor()
   at System.Diagnostics.DiagnosticSourceEventSource..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.DiagnosticListener..ctor(String name)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()`

**Comment by capiono** [comment] 2016-11-14 11:36
I added System.AppContext version 4.1.0 again, I'm now getting the error below:

`Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'System.Diagnostics.DiagnosticSourceEventSource' threw an exception. ---> Syst
em.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.Ev
entSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)'.
   at System.Diagnostics.DiagnosticSourceEventSource..ctor()
   at System.Diagnostics.DiagnosticSourceEventSource..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.DiagnosticListener..ctor(String name)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()`

**Comment by nil4** [comment] 2016-11-14 13:03
I am experiencing the same issue as @capiono with a project targeting .NET 4.6.2 and .NETCoreApp 1.1 preview 1.

**Comment by weshaggard** [comment] 2016-11-14 17:42
Looks like there are some mixed up package dependencies in this configuration from the AspNetCore packages. Adding some more asp.net folks. @glennc @danroth27 have you guys seen these issue reported?

**Comment by danroth27** [comment] 2016-11-14 18:27
@muratg @Eilon

**Comment by Eilon** [comment] 2016-11-14 20:01
It looks like perhaps the project.json file in 1.0.0 of Microsoft.Extensions.PlatformAbstractions was incorrect, but I think it's been fixed for 1.1.0.

**Comment by Eilon** [comment] 2016-11-14 20:09
The fix is to add a reference to System.AppContext from your own app's project.

**Comment by capiono** [comment] 2016-11-14 22:03
I added System.AppContext  to my dependencies, still not working:

`  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Session": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0-preview1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0-preview1-final",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha4",
    "System.AppContext": "4.3.0-preview1-24530-04"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
  },

  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0"
      }
    }
  },`

**Comment by capiono** [comment] 2016-11-17 01:49
I was able to make it work by doing the following:

- installed net461 on the server (windows 2012)
- Updated my project.json to this:

` "dependencies": {
   "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.Session": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha4"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
      },

  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0"
      }
    }
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
`

**Comment by halter73** [comment] 2016-11-17 22:45
@capiono @nil4 I think figured out what's going on.

You should install .NET 4.6.(1|2) on the server since you are targeting net461 and Win Server 2012 only comes with .NET 4.5. Alternatively, you can change "net461" in the "frameworks" section to "net451".

Both fixes worked for me when I got a 502.5 error from IIS while trying to run an app with the same dependencies on a fresh install of Win Server 2012. The exception I got was different, but I think that's just because I was testing a different app. I'm pretty sure the root cause is the same.

    Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Diagnostics.DiagnosticSourceEventSource' threw an exception. ---> System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)'.
       at System.Diagnostics.DiagnosticSourceEventSource..ctor()
       at System.Diagnostics.DiagnosticSourceEventSource..cctor()
       --- End of inner exception stack trace ---
       at System.Diagnostics.DiagnosticListener..ctor(String name)
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at WebApplication2.Program.Main(String[] args) in C:\Users\shalter\Documents\Visual Studio 2015\Projects\WebApplication2\src\WebApplication2\Program.cs:line 22

**Comment by tarekgh** [comment] 2017-03-02 18:10
Is there anything else need to be done here? I am closing the issue as adding the needed references to project.json and running on the correct targeted platform solve the issue. feel free to reopen if needed to.

**Closed by tarekgh** 2017-03-02 18:10 UTC
Labels: area-Meta, question, tracking-external-issue

**Comment by syclee** [comment] 2017-03-10 04:31
I had a similar situation where we have an Azure App Service that we had deployed running on .NET Core runtime. A couple of days ago we realized our Application Insights was not working correctly, the dependency tracker feature of App Insights is not supported when running on .NET Core runtime. We then decided to switch our runtime to the full .NET Framework.

Our project.json was modified to run on "net461". This then was deployed via ARM Templates. I noticed this same error happening when testing it. I downloaded the build artifacts and ran locally and got the same error

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0

I tried deleting the App Service from Azure Portal and deployed again. The error was fixed.

I am guessing what happened was when switching runtimes the ARM Template deployment skipped some DLL's resulting in this error.

**Comment by wdnijdam** [comment] 2017-05-08 13:16
I had this issue when running .net core code for framework version 4.6.2 on a machine with version 4.5.2 installed. Advise: check the .net framework version on your machine.
Check the version: https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx
