### ISSUE TITLE
Directory Delete tests failing on Unix

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#20034] opened 2017-05-20 02:30 UTC
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170520.01/workItem/System.IO.FileSystem.Tests

@JeremyKuhne perhaps related to 801dde95 / https://github.com/dotnet/corefx/pull/19959

```
Assert.Throws() Failure\nExpected: typeof(System.IO.IOException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/'.
Stack Trace :
   at System.IO.UnixFileSystem.RemoveDirectory(String fullPath, Boolean recursive) in /root/corefx/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs:line 317
   at System.IO.Directory.Delete(String path, Boolean recursive) in /root/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 589
   at System.IO.Tests.Directory_Delete_str_bool.Delete(String path) in /root/corefx/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 216
   at System.IO.Tests.Directory_Delete_str.<DeleteRoot>b__6_0() in /root/corefx/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 67
```
```
Assert.Throws() Failure\nExpected: typeof(System.IO.IOException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/'.
Stack Trace :
   at System.IO.UnixFileSystem.RemoveDirectory(String fullPath, Boolean recursive) in /Users/buildagent/agent/_work/24/s/corefx/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs:line 315
```

**Comment by danmosemsft** [comment] 2017-05-20 02:46
@JeremyKuhne looks like you missed it because this is `[OuterLoop]`. I'm not sure why but perhaps because it tries to delete the root directory!
Since your change `Directory.Delete('C:\')' is throwing DNFE on Unix instead of IOEX as it does on Windows (and I assume it does on Desktop - I dare not try..)

**Comment by karelz** [comment] 2017-05-21 04:43
Marking as 2.0 as it is likely regression of #19959 which we want to port to 2.0 in #20040

**Comment by karelz** [comment] 2017-05-22 05:57
Reopening to port the change (PR #20049) into 2.0.

**Comment by v-haren** [comment] 2017-05-22 08:03
failed again here: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_release/52/testReport/

**Comment by stephentoub** [comment] 2017-05-22 11:57
@v-haren, that's from before the fix in #20049 was merged.

**Comment by stephentoub** [comment] 2017-05-22 11:58
@karelz, we should just port it as https://github.com/dotnet/corefx/issues/20040; see my comment there from yesterday.

**Comment by karelz** [comment] 2017-05-22 14:52
Do you mean to track all the porting changes necessary in a single issue #20040? That works for me. Thanks for info.

**Comment by stephentoub** [comment] 2017-05-22 14:56
> Do you mean to track all the porting changes necessary in a single issue #20040? That works for me. Thanks for info.

This issue is a regression caused by the other one.  It doesn't make sense to port one without the other.

**Comment by CIPop** [comment] 2017-05-22 21:49
Reopening:

Failing on Ubuntu:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.04_debug_prtest/23/consoleFull

```
System.IO.Tests.DirectoryInfo_Delete.DeleteRoot
System.IO.Tests.DirectoryInfo_Delete_bool.DeleteRoot
System.IO.Tests.Directory_Delete_str_bool.DeleteRoot
System.IO.Tests.Directory_Delete_str.DeleteRoot
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.04_debug_prtest/23/testReport/junit/System.IO.Tests/Directory_Delete_str/DeleteRoot/
```
Regression

System.IO.Tests.Directory_Delete_str.DeleteRoot (from (empty))

Failing for the past 1 build (Since Failed#23 )
Took 0 ms.
add description
Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.IO.IOException)\nActual: typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/'.
+++++++++++++++++++
STACK TRACE:
at System.IO.UnixFileSystem.RemoveDirectory(String fullPath, Boolean recursive) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs:line 317 at System.IO.Directory.Delete(String path) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 582 at System.IO.Tests.Directory_Delete_str.Delete(String path) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 15 at System.IO.Tests.Directory_Delete_str.<DeleteRoot>b__6_0() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 67
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu16.04_debug_prtest/23/testReport/junit/System.IO.Tests/Directory_Delete_str_bool/DeleteRoot/
```
System.IO.Tests.Directory_Delete_str_bool.DeleteRoot (from (empty))

Failing for the past 1 build (Since Failed#23 )
Took 1 ms.
add description
Stacktrace

MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.IO.IOException)\nActual: typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/'.
+++++++++++++++++++
STACK TRACE:
at System.IO.UnixFileSystem.RemoveDirectory(String fullPath, Boolean recursive) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs:line 317 at System.IO.Directory.Delete(String path, Boolean recursive) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/src/System/IO/Directory.cs:line 589 at System.IO.Tests.Directory_Delete_str_bool.Delete(String path) in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 216 at System.IO.Tests.Directory_Delete_str.<DeleteRoot>b__6_0() in /mnt/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_ubuntu16.04_debug_prtest/src/System.IO.FileSystem/tests/Directory/Delete.cs:line 67
```

**Comment by CIPop** [comment] 2017-05-22 21:50
Also on OSX: 
- https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_debug_prtest/39/consoleFull#9832431179fe3b83-f408-404c-b9e7-9207d232e5fc
- https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_osx_release_prtest/19/
(same errors)

**Comment by JeremyKuhne** [comment] 2017-05-22 22:13
@CIPop Are you sure this is currently failing? The first job I looked at started 3 days ago and I'm not seeing the hashes in master's log.

**Comment by CIPop** [comment] 2017-05-22 22:37
> Are you sure this is currently failing? 

They were failing in the links above (tests started last Friday). I didn't submit any PRs today.

**Comment by JeremyKuhne** [comment] 2017-05-22 22:39
Closing- the fix went in yesterday- these all appear to predate the fix.

**Closed by JeremyKuhne** 2017-05-22 22:39 UTC
Labels: area-System.IO, blocking-clean-ci, test-run-core
