### ISSUE TITLE
The new JsonSerializer fails to serialize Guid

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/corefx#38043] opened 2019-05-30 04:37 UTC
It produces '{}' for a Guid. However, it appears to be deserializing it fine.

**Comment by ahsonkhan** [comment] 2019-05-30 04:41
Can you please provide a sample repro with more details?

```C#
var foo = new Foo
{
    guid = Guid.NewGuid()
};

Assert.Equal($"{{\"guid\":\"{foo.guid}\"}}", Serialization.JsonSerializer.ToString(foo)); // Passes

public class Foo
{
    public Guid guid { get; set; }
}
```

**Comment by nvmkpk** [comment] 2019-05-30 17:16
I am using it from asp.net core 3.0 preview 5. I will try with a new project.

**Comment by nvmkpk** [comment] 2019-05-30 20:47
Here is a simple repro:

[JsonGuid.zip](https://github.com/dotnet/corefx/files/3238677/JsonGuid.zip)

**Comment by ahsonkhan** [comment] 2019-05-31 00:55
> Here is a simple repro

I don't see any calls to the `JsonSerializer` here. 

cc @pranavkm, @rynowak

**Comment by pranavkm** [comment] 2019-05-31 01:25
MVC is serializing the `IEnumerable<Guid>` on behalf of the user. An equivalent test would be:

```C#
IEnumerable<Guid> guids = new[] { Guid.NewGuid(), Guid.NewGuid() };

Assert.Equal($"[\"{guids[0]}\", "\"{guids[1]"\"}}", Serialization.JsonSerializer.ToString(guids));
```

**Comment by ahsonkhan** [comment] 2019-05-31 01:59
> . An equivalent test would be:

This test passes, so I am not sure what the issue is here.
```C#
var guid0 = Guid.NewGuid();
var guid1 = Guid.NewGuid();

IEnumerable<Guid> guids = new[] { guid0, guid1 };

Assert.Equal($"[\"{guid0}\",\"{guid1}\"]", Serialization.JsonSerializer.ToString(guids));
```

**Comment by pranavkm** [comment] 2019-05-31 02:29
@ahsonkhan this was reported using preview5 builds. Perhaps the issue has since been fixed.

**Comment by nvmkpk** [comment] 2019-05-31 16:17
The version of `System.Text.Json` nuget package I have is `4.6.0-preview6.19259.10`.

**Comment by ahsonkhan** [comment] 2019-06-01 03:59
That was a one-off publish of the package from a nightly build a few weeks ago (right after preview 5). Can you either retry by referencing the latest package version from the dev feed (currently, the latest available is `4.6.0-preview7.19281.7`, with the last preview6 being `4.6.0-preview6.19281.8`)? Otherwise, you would have to wait for the preview6 to ship and become available on NuGet.

Add the dev feed (see https://github.com/dotnet/arcade#getting-started):
```text
https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
```

**Comment by nvmkpk** [comment] 2019-06-01 18:53
I tried with version `4.6.0-preview7.19301.2` and it is working.

**Comment by ahsonkhan** [comment] 2019-06-03 23:41
Closing as fixed.

**Closed by ahsonkhan** 2019-06-03 23:41 UTC
Labels: area-System.Text.Json, needs more info
