### ISSUE TITLE
Contributor Guidance regarding "Squash and Merge"

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#20841] opened 2017-06-08 23:59 UTC
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md

suggests that "Squash and Merge" be used only to squash and "only by the contributor on request" (which doesn't make sense to me since it's the guy who does the merge that clicks the button...)

I would recommend that the guidance be changed so that "Squash and Merge" is the always the preferred choice even when there's only one commit in the PR. "Squash and Merge" isn't just about squashing commits - it's about having a sane history log without every contribution creating two commit objects - one with a useless title ("Merge Pull Request") and the other with a useless timestamp (I care about when the change was merged into the branch, not when the author built the commit before pushing it to the PR.)

**Comment by tarekgh** [comment] 2017-06-09 01:13
@karelz @danmosemsft @stephentoub @jkotas any objection to apply what @AtsushiKan suggesting here? I think it make sense

**Comment by stephentoub** [comment] 2017-06-09 01:18
I'm ok with that as the new default, but it's still just a default... sometimes merge rather than squash is better IMHO. For example:
- in PRs that end up containing commits from multiple individuals, such as an auto update PR we then need to patch for done reason
- in PRs where there are multiple distinct commits, e.g. one that refactors and another that fixes a bug, and you want to keep that clear b and understandable in the history

**Comment by davidsh** [comment] 2017-06-09 01:19
>any objection to apply what @AtsushiKan suggesting here?

I have noticed that when "Squash and Merge" is done (even with just one commit), then after doing a "git pull dotnet master" into your repo, then one can't do a "git branch -d mybugfix".  It will say I must do a "git branch -D mybugfix", i.e. a forced delete of the branch because it says that the branch may not be fully merged.  That seems annoying.

**Comment by jkotas** [comment] 2017-06-09 01:20
"(squashing) should only be done by the contributor upon request" was trying to say that the contributors should append commits and not squash them because it breaks codereview workflow (reviewers are not able to see the delta with codereview feedback).

**Comment by danmosemsft** [comment] 2017-06-09 01:34
Agree, prefer squash on commit in 95% case.

**Comment by sharwell** [comment] 2017-06-09 02:26
I would only advocate for a squash approach in cases where a PR contained intermediate commits which are not in a buildable state (e.g. negatively impacting git bisect). I withhold a strong objection only on the basis that I don't frequently work in this repository.

**Comment by AtsushiKan** [comment] 2017-06-09 12:41
@stephentoub, @sharwell 

For the "useful as stages" contribution and the "want to preserve email addy" scenarios, the "Rebase and Merge" button preserves the separate commit stages and author email addy, and still satisfies my goal of avoiding the creation of the two-parent commit and braided history for every individual contribution. Unfortunately, the author time stamp is still the earlier timestamp (and the author time stamp is the one that github chooses to show) but given that this is a rarer case and the history is still linear (and thus, effectively sorted by committer timestamp) this is still a big improvement from my perspective.

For merges of long lived branches with multiple contributors, creating the merge commit still makes sense of course - but that's something done by maintainers and bots - not quite the target audience of the contributer's doc.

I don't think we attach importance to signatures from submitters.

Note that squashing has always been the preferred policy for this repo even before GitHub had a "squash and merge" - this issue is less about whether we squash but about how we do it.

So how about this guidance for invidual contributors:

- **Squash and Merge** as the 95% default.

- **Rebase and Merge** for these situations:

  - Contribution is best understood as a series of well-factored staged commits (each one should be buildable.)
  - Contributor wants to preserve original author email addy (needs to request this in PR and
    and will be asked to squash manually before we hit the merge button.)

**Comment by sharwell** [comment] 2017-06-09 13:39
I frequently use merge commits to understand individual contributions and when they are introduced into a main branch. In other words, starting at any individual branch of a root repository, I expect to be able to following the parent[0] links of each commit and find a chain of merge commits representing the precise order in which changes were pushed to the branch.

I also depend heavily on the use of merge commits to allow deleting local branches after they have been merged. For projects I contribute to frequently, any other merge strategy is a notable drawback and likely to result in either a general understanding that I expect my changes to be an exception to the norm, or a reduction in the amount of submissions I make to that repository.

The only merge policy I could ever advocate for, for any contribution, is a merge with `--no-ff`. If a branch contains commits which need to be squashed (e.g. to reduce a substantial amount of churn), it should be squashed prior to the merge, but this would be a minority case that I try and avoid.

**Comment by karelz** [comment] 2017-06-11 15:21
> Contributor wants to preserve original author email addy (needs to request this in PR and will be asked to squash manually before we hit the merge button.)

What situation would this be true? Has it ever happen? If not, let's not even mention it in the docs (keep them simple), until it becomes a problem/real request.

**Comment by sharwell** [comment] 2017-06-11 16:55
> What situation would this be true?

This is true for all pull requests I send as part of my current employment.

**Comment by karelz** [comment] 2017-06-11 18:32
Is that a common practice on GitHub? It seems to me like a very thin line to distinguish.

**Comment by tannergooding** [comment] 2017-06-11 20:37
@karelz, My GitHub account is setup with two e-mails (my Microsoft work address and my Personal address). I have notifications related to my job route to my work address and other notifications (related to personal interests) routed to my personal e-mail.

Additionally, I have my work computer and personal computer configured separately. This helps identify things that I am doing as part of my job vs things that I do in my own time. This is less important for me, but may be extremely important to other contributors who may have more stringent policies around contributing code to open source repositories.

Squashing and merging can also make it more difficult to track down regressions and to understand the state of the repo when a particular change was made. For example, imagine I make a change and it gets merged. It did not have any merge conflicts nor did it introduce a build break, but it did introduce a subtle runtime bug due to another change made in between the time I started on my change and when it was merged. Later when the subtle bug is discovered, it is now more difficult to track down and understand how the bug was introduced in the first place.

**Comment by karelz** [comment] 2017-06-11 20:46
Good reason, thanks for explanation. From that perspective it makes sense.

Re: Tracking down regressions ... such subtle regressions are pretty rare (one per half a year, maybe once per month top). It is IMO not worth introducing more process/limitations to address such a rare event. Just my 2 cents.

**Comment by AtsushiKan** [comment] 2017-06-12 14:23
>Good reason, thanks for explanation. 

I think GitHub needs to support specifying which email-identity you want to open a PR as. That way, the PR author can control what email addy "Squash and Merge" inserts into the commit and not be stuck with the primary email-addy associated with the GitHub account. I don't think identity tracking can be done reliably otherwise - the reality is that "Squash and Merge" exists, many people already use it in this repo, and I would be very much against going back to the bad old days where all contributers had to be asked to manually squash as the last hurdle before getting their PR's accepted. Our "contributor experience" is already non-optimal without that.

I am souring a bit on "Rebase and Merge" now that I've had time to explore it more. Aside from the commit timestamps, it also loses the link to the PR. I think we can stay on "Merge and Commit" for those cases - just not as the default.

I've opened a PR for the contribution doc: https://github.com/dotnet/corefx/pull/20937

**Closed** 2017-06-12 16:10 UTC
Labels: area-Meta, documentation
