### ISSUE TITLE
Discrepancy between Utf8Parser and double.TryParse between x64 and x86

### ISSUE THREAD

**Issue by ppekrol** [dotnet/corefx#35730] opened 2019-03-03 08:36 UTC
Hi,

I'm using .NET Core 2.2.2 and this is my code:

```csharp
var eps = double.Epsilon;
var epsTimesTwo = eps * 2;
var input = epsTimesTwo.ToString("R", CultureInfo.InvariantCulture);
var bytes = Encoding.UTF8.GetBytes(input);
var parsed = Utf8Parser.TryParse(new ReadOnlySpan<byte>(bytes), out double output, out var consumed) && bytes.Length == consumed;
var dblParsed = double.TryParse(input, out var dblOutput);
Console.WriteLine($"Input: {epsTimesTwo} ({input})");
Console.WriteLine($"Bytes length: {bytes.Length}");
Console.WriteLine($"Parsed (parser): {parsed}");
Console.WriteLine($"Output (parser): {output} ({output.ToString("R", CultureInfo.InvariantCulture)})");
Console.WriteLine($"Parsed (double): {dblParsed}");
Console.WriteLine($"Output (double): {dblOutput} ({dblOutput.ToString("R", CultureInfo.InvariantCulture)})");
```

The output on x64 (Windows) is as follows: 

```
Input: 9.88131291682493E-324 (9.8813129168249309E-324) // notice that 'R' format differs
Bytes length: 23
Parsed (parser): True
Output (parser): 9.88131291682493E-324 (9.8813129168249309E-324)
Parsed (double): True
Output (double): 9.88131291682493E-324 (9.8813129168249309E-324)
```

And the x86 (Windows) output is:

```
Input: 9.88131291682493E-324 (9.88131291682493E-324) // no difference
Bytes length: 21
Parsed (parser): True
Output (parser): 4.94065645841247E-324 (4.94065645841247E-324)
Parsed (double): True
Output (double): 9.88131291682493E-324 (9.88131291682493E-324)
```

Please note that `double.TryParse` is handling the difference between 'R' format on both platforms in the same manner, but `Utf8Parser` does not.

I'm aware that 'R' format does not guarantee successful round-trips, but I would expect the same behavior between both of the platforms.

**Comment by danmosemsft** [comment] 2019-03-04 00:19
@tannergooding

**Comment by tannergooding** [comment] 2019-03-04 16:32
Looking into this.

> I'm aware that 'R' format does not guarantee successful round-trips, but I would expect the same behavior between both of the platforms.

Just as an FYI. In netcoreapp3.0, "R" now does guarantee successful round-trips and should always return the shortest roundtrippable string.

In netcoreapp3.0, your program (for both x86 and x64) will give:
```
Input: 1E-323 (1E-323)
Bytes length: 6
Parsed (parser): True
Output (parser): 1E-323 (1E-323)
Parsed (double): True
Output (double): 1E-323 (1E-323)
```

**Comment by tannergooding** [comment] 2019-03-04 18:01
The issue is that, prior to netcoreapp3.0, x86 and x64 had different algorithms for parsing floating-point numbers. I removed this difference in https://github.com/dotnet/coreclr/pull/19775 as part of the netcoreapp3.0 work.

I would speculate that backporting the relevant commit (https://github.com/dotnet/coreclr/pull/19775/commits/b7c368658f5dd853abd821c642c59c89057aed48) to make x64 and x86 consistent may not meet the shiproom bar, considering it impacts full framework and all netcoreapp versions prior to 3.0.

@danmosemsft could you confirm the above?

**Comment by tannergooding** [comment] 2019-03-04 18:02
Also worth noting that this difference only exists on x86 for Windows. x86 Unix systems use the same C algorithm that x64 uses.

**Comment by danmosemsft** [comment] 2019-03-05 04:32
@tannergooding it would have to have a large impact to consider requesting servicing. I do not see that here. Also if it is feature level work it would not be considered for servicing.

**Comment by tannergooding** [comment] 2019-03-27 16:46
I'm going to close this as non-actionable at this point.

The algorithms are now the same for all platforms/architectures in netcoreapp3.0. In prior versions, the behavior on x86 vs x64 Windows is consistent with the behavior on full framework and other prior .NET Core versions.

Getting this serviced on older releases is going to be increasingly unlikely to happen especially given the scope of the fix.

**Closed by tannergooding** 2019-03-27 16:46 UTC
Labels: area-System.Numerics, question
