### ISSUE TITLE
Add frameworkAssembly entries on desktop when facade is inbox

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#5952] opened 2016-02-07 15:13 UTC
When I install the System.Runtime.Numerics package to a portable library, I can use `BigInteger`. But when I install the same package to a net45 targeted project, no reference is added. 

.NET 4.5 includes System.Numerics.dll in the framework. But in a project.json world where we try to express all references as packages, and such a facade package exists for BigInteger, I'm surprised it doesn't work, and I have to add the System.numerics.dll reference manually.

Is this by design?

**Comment by mellinoe** [comment] 2016-02-08 18:50
@ericstj

**Comment by ericstj** [comment] 2016-02-08 20:34
Yes, this is by design.  We don't have any asset to harvest classic references from for inbox assemblies.  When this work was originally done @davkean and @nguerrera mentioned that the behavior was consistent with PCLs.

We could do better but it'd require some additional work during the package build.

**Comment by ericstj** [comment] 2016-04-23 16:56
Updated the title of this issue.  The problem here is that packages which represent inbox contracts on desktop don't contribute anything to the build.  This is because the facade is added automatically by the msbuild targets for desktop.  Those targets don't, however, add frameworkReferences for the implementation assemblies that the facades forward to (eg: system, system.core, system.xml, etc).  To fix this we could add a non-packaged file to the pkgproj that just harvests the dependencies.

**Comment by mellinoe** [comment] 2016-05-24 06:14
Once new versions of packages are published, this should be fixed. Please give it a try once tomorrow's build is out.

**Closed** 2016-05-24 06:13 UTC
Labels: 2 - In Progress, packaging
