### ISSUE TITLE
ManagedWebSocket HTTP scenarios implementation

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#14480] opened 2016-12-13 20:21 UTC
Tracking the implementation of the following items:

- [ ] ClientWebSocketOptions.UseDefaultCredentials
- [ ] ClientWebSocketOptions.Credentials
- [ ] ClientWebSocketOptions.Proxy
- [ ] ClientWebSocketOptions._sendBufferSize

**Comment by karelz** [comment] 2017-03-02 20:01
Dupe of #5120

**Closed by karelz** 2017-03-02 20:01 UTC
Labels: area-System.Net, enhancement, untriaged
