### ISSUE TITLE
System.Net.Http.Functional.Tests.PlatformHandler_HttpRetryProtocolTests/GetAsync_RetryOnConnectionClosed_Success CI failure

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#28719] opened 2018-04-02 17:54 UTC
OSX.1013.Amd64.Open-x64-Debug

```
System.Exception : Unexpected EOF trying to read request header
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 378
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c.<<GetAsync_RetryOnConnectionClosed_Success>b__3_2>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.<>c.<<GetAsync_RetryOnConnectionClosed_Success>b__3_1>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpRetryProtocolTests.GetAsync_RetryOnConnectionClosed_Success() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpRetryProtocolTests.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment] 2018-04-02 20:25
Duplicate of #28537

**Closed by karelz** 2018-04-02 20:25 UTC
Labels: area-System.Net.Http

**Comment by bartonjs** [comment] 2018-04-02 20:28
Fair enough.  I didn't know if the EOFness was unique to the proxy aspect of the test or not (the failed tests in the other issue both are related to proxying)
