### ISSUE TITLE
Regression: UseShellExecute on non-Windows hangs parent process

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/corefx#40193] opened 2019-08-09 19:56 UTC
This is a regression in .NET Core 3.0 from .NET Core 2.1 and only repros on Linux and macOS.

```powershell
invoke-item .
```

With PSCore6.2 based on .NET Core 2.1, this will open the OS File Explorer and you can still type commands in PowerShell.
With PS7 based on .NET Core 3.0 (Preview.6 or Preview.7 using nightly build of PS7), this will open the OS File Explorer, but PowerShell is no longer responding to input

**Comment by stephentoub** [comment] 2019-08-09 21:41
cc: @tmds

**Comment by tmds** [comment] 2019-08-10 05:27
I think this may be the same root cause as https://github.com/dotnet/corefx/issues/40137. @SteveL-MSFT can you check using corefx master?

**Comment by iSazonov** [comment] 2019-08-10 18:09
@tmds is there an updated nuget package we could reference in PowerShell repo to check for this fix?

**Comment by tmds** [comment] 2019-08-10 18:46
The fix was just added yesterday. In a couple of days it should be part of [daily builds](https://github.com/dotnet/core/blob/master/daily-builds.md).

I just took the reproducer code from https://github.com/dotnet/corefx/issues/40137 and changed it to `UseShellExecute =true`,`FileName=.`. It hangs with preview7, and works with corefx master.

**Comment by SteveL-MSFT** [comment] 2019-08-15 22:06
@tmds would it be correct to say this fix will show up in Preview.9?

**Comment by tmds** [comment] 2019-08-16 08:25
Yes, it was merged on 3.0 branch.

**Comment by danmosemsft** [comment] 2019-08-29 17:38
@tmds @stephentoub it seems this can be closed, am I right?

**Comment by tmds** [comment] 2019-08-29 18:27
Yes, on master: https://github.com/dotnet/corefx/pull/40160 and release/3.0: https://github.com/dotnet/corefx/pull/40191.

**Closed** 2019-08-29 20:09 UTC
Labels: area-System.Diagnostics.Process
