### ISSUE TITLE
DataContractResolver ignored

### ISSUE THREAD

**Issue by ivanbottero** [dotnet/corefx#12828] opened 2016-10-20 06:47 UTC
Hello,

I'm developing a WCF service that is called from a WPF app and from an UWP app

The service is full duplex (with netTcp binding) and it uses a custom DataContractResolver for dynamic types resolution

All is ok when I call the service from the WPF app

When I try to call the same service from a UWP app I get a SerializationException. It seems that the DataContractSerializer is ignored (no breakpoint is hit)

The version of Microsoft.NETcore.UniversalWindowsPlatform is 5.2.2

I tried to use the beta version but the problem is stiil the same. The resolver is not called

At the moment the only workaround for me is a custom DataContractSerializerOperationBehavior where I override the CreateSerializer method and I pass to it my Known types

Thank you

Ivan

**Comment by karelz** [comment] 2016-10-20 15:40
@shmao can you please help/route?

**Comment by shmao** [comment] 2016-10-20 16:55
@ivanbottero Thanks for opening the issue. Can you please share a repro app/code for the issue with us?

**Comment by ivanbottero** [comment] 2016-10-21 09:04
Hi,
I made a repro app/code for the issue
The solution contains:
- WPF app
- Universal app
- WCF service
- NetCore library with the service reference (used by wpf app and universal app)
- A class library with the DataContractResolver

The wpf app can call the service with success because the resolver is called (you can set a breakpoint on TryResolveType)
The universal app can call the service but can't deserialize the message (TryResolveType is not called)

Thanks
Ivan

[TestDataContractResolver.zip](https://github.com/dotnet/corefx/files/543905/TestDataContractResolver.zip)

**Comment by huanwu** [comment] 2016-10-21 20:48
@ivanbottero, thanks for reporting this issue. I can repro this issue. We will investigate.

**Comment by karelz** [comment] 2016-11-04 18:46
Does it repro also on .NET Core (@huanwu?)

**Comment by huanwu** [comment] 2016-11-04 21:54
@karelz yes, I can repro.

**Comment by huanwu** [comment] 2016-11-21 22:18
It is caused by https://github.com/dotnet/wcf/issues/1673

**Comment by karelz** [comment] 2016-11-21 23:06
Can we close this issue on corefx then?

**Closed** 2016-11-22 21:38 UTC
Labels: area-Serialization, bug, up for grabs
