### ISSUE TITLE
HttpClientHandler is not honoring UseDefaultCredentials set to false

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#5045] opened 2015-12-17 20:53 UTC
We're trying to enable [WebListener](https://github.com/aspnet/WebListener) tests on CoreCLR, however we're running into some issues on authentication tests.

We have tests that check that an anonymous request to a server requiring authentication gets a 401 status back along with challenges. The request is made using an `HttpClient` taking an `HttpClientHandler` with `UseDefaultCredentials` set to `false`. On desktop CLR, we only see one HTTP request/response pair in the network:

![image](https://cloud.githubusercontent.com/assets/924164/11881634/cc350af6-a4bc-11e5-83b4-9be7f4bc9861.png)

Which is expected for the test to pass. On CoreCLR however, we're seeing the client trying to negotiate authentication even when `UseDefaultCredentials` is set to `false`:

![image](https://cloud.githubusercontent.com/assets/924164/11881643/e1365590-a4bc-11e5-9b72-805c7d629375.png)

Here's what we see when setting `UseDefaultCredentials` to `true`:

![image](https://cloud.githubusercontent.com/assets/924164/11881665/f63bcd30-a4bc-11e5-9f83-617a440601fb.png)

Which is essentially the same as when it's set to `false`, which means the `UseDefaultCredentials` is not being honored in requests.

Our tests are failing because they don't expect authentication to be successful in those requests.

cc @Tratcher

**Comment by SidharthNabar** [comment] 2015-12-28 18:23
@cesarbs - I have currently set the milestone as RTM. Please let us know if this is blocking you and needs to be fixed in RC2 timeframe.

**Comment by cesarbs** [comment] 2015-12-28 22:08
It's not blocking but it does require us to disable some WebListener tests on CoreCLR. Any specific reason why this is not being addressed in RC2?

**Comment by SidharthNabar** [comment] 2015-12-29 17:58
@cesarbs - No specific reason, just based on resources and timeline, we may not get to it before RC2. Also, I just tried a repro with another URI, and it seems to work (UseDefaultCredentials = true gave me a 200 response, and UseDefaultCredentials = false gave me a 401). Can you share the URI/server that you are trying this against?

**Comment by cesarbs** [comment] 2015-12-29 20:20
@SidharthNabar It repros pretty consistently - doesn't look like a case of the OS caching credentials.

**Comment by cesarbs** [comment] 2016-02-04 20:06
In which build will this fix be available?

**Comment by davidsh** [comment] 2016-02-04 21:02
The fix is available in the System.Net.Http package with a version number of v4.0.1-rc3-23803 or later. You can get this version from the CoreFx Dev feed:

https://dotnet.myget.org/gallery/dotnet-core

I do not know how/when DNX runtimes will import this latest version of System.Net.Http.

**Comment by cesarbs** [comment] 2016-02-05 20:26
@davidsh Doesn't look it... I'm looking at the assembly in ILSpy and I don't see the fix there.

**Comment by davidsh** [comment] 2016-02-05 20:30
@cesarbs I don't understand what you are saying.  Are you saying that you inspected the CoreFx dev feed latest binary of System.Net.Http and didn't see my fix?  Or are you saying that DNX is having trouble loading the updated binary?

Keep in mind that the actual IL for System.Net.Http is not in that DLL.  Rather it is redirected to the runtime*System.Net.Http* packages where there is a separate runtime for each platform (windows, linux, osx).

**Comment by cesarbs** [comment] 2016-02-05 20:36
@davidsh I've inspected the IL for `runtime.win7.System.Net.Http` version 4.0.1-rc3-23803 and didn't see the fix there.

**Comment by davidsh** [comment] 2016-02-05 20:41
The PR was merged into dotnet/corefx [master].  So, the fix is in the repo.  It was merged a few days ago, so it should be in the builds.

**Comment by davidsh** [comment] 2016-02-05 20:50
Ok.  I looked in the DLL itself:
```
runtime.win7.System.Net.Http.4.0.1-rc3-23803.nupkg\runtimes\win7\lib\DNXCore50\System.Net.Http.dll
```

and you're right.  The fix is not there.  I suspect it is because the build is still not caught up fully. It should definitely be in the next build iteration (23804).

**Comment by cesarbs** [comment] 2016-02-05 21:42
@davidsh Thanks for confirming :+1: I was afraid I could be doing something wrong :grin:

**Comment by cesarbs** [comment] 2016-02-08 18:21
Even with the fix in place, I am still seeing the exact same behavior. Reopening.

**Comment by davidsh** [comment] 2016-02-08 20:26
Can you clarify on which build you tested?  Also, if you are using DNX, it doesn't load newer System.Net.Http binaries due to how the DNX runtime works.  So, I'd like to understand how you tested this?

We tested the fixes in CoreFx with an explicit set of new tests and those tests pass.

**Comment by cesarbs** [comment] 2016-02-08 22:16
@davidsh I've put it all here: https://github.com/cesarbs/HttpClientCredentialRepro

**Comment by cesarbs** [comment] 2016-02-22 20:58
@davidsh Did you or someone in your team get a chance to look at the repro I provided?

**Comment by davidsh** [comment] 2016-02-22 22:55
@cesarbs It is on our list to re-investigate. As I said earlier, the fix was originally tested against the test case in the CoreFx repo.

**Comment by davidsh** [comment] 2016-02-29 03:15
@cesarbs I tried the repro. And I can reproduce the results you say.

FWIW, I tested the code fix against our test server in Azure by modifying your client repro:

```c#
using System;
using System.Net.Http;

namespace HttpClientHandlerClient
{
    public class Program
    {
        public static void Main(string[] args)
        {
            //const string uri = "http://localhost:8080";
            const string uri = "http://corefx-net.cloudapp.net/Echo.ashx?auth=negotiate";

            var handler = new HttpClientHandler();
            handler.UseDefaultCredentials = false;
            using (var client = new HttpClient(handler))
            {
                var response = client.GetAsync(uri).Result;
                Console.WriteLine($"Response status: {(int)response.StatusCode} {response.StatusCode}");
            }
        }
    }
}
```

and I get `401`.  That said, when I try to connect to the http://localhost server you have, I do see the 200 response, which implies that default credentials are getting sent.

So, I will need to investigate this further.

**Comment by davidsh** [comment] 2016-02-29 03:24
cc: @CIPop @stephentoub @SidharthNabar 

@cesarbs I found out why it appears that my fix doesn't work on your http://localhost server.

According to MSDN documentation for native WinHTTP (which is what System.Net.Http uses on CoreFx):

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384066(v=vs.85).aspx

>WINHTTP_OPTION_AUTOLOGON_POLICY
Sets an unsigned long integer value that specifies the Automatic Logon Policy with one of the following values.
WINHTTP_AUTOLOGON_SECURITY_LEVEL_HIGH
Default credentials are not used. Note that this flag takes effect only if you specify the server by the actual machine name. It will not take effect, if you specify the server by "localhost" or IP address.
WINHTTP_AUTOLOGON_SECURITY_LEVEL_LOW
An authenticated log on using the default credentials is performed for all requests.
WINHTTP_AUTOLOGON_SECURITY_LEVEL_MEDIUM
An authenticated log on using the default credentials is performed only for requests on the local Intranet.

When `UseDefaultCredentials=false`, we are setting the WINHTTP_AUTOLOGIN_SECURITY_LEVEL_HIGH flag.  However, because the server is being accessed via "localhost", that flag doesn't take affect. And so, default creds are getting thru.

This is a behavior that we don't have control over. I would suggest that for building tests for your server, that you have your server on a different box or reference it via machine name instead of "localhost".  Then you will discover that the fix does work.

I realize that the .NET Framework (Desktop) System.Net.Http client works differently. But this is how CoreFx works due to WinHTTP.

**Comment by davidsh** [comment] 2016-05-09 00:47
Closing this now since issue was addressed except for "localhost" use which is a winhttp limitation regarding using default creds for loopback connections.

**Closed by davidsh** 2016-05-09 00:47 UTC
Labels: bug, System.Net
