### ISSUE TITLE
ASP.NET Core 3.0 doesn't stream IAsyncEnumerable<T> as chunk of data

### ISSUE THREAD

**Issue by tangkhaiphuong** [dotnet/corefx#41378] opened 2019-09-27 02:29 UTC
I start the sample project with ASP.NET Core 3.0 API and implement the Route like

``` CSharp
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async IAsyncEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            for (var index = 0; index < 10; ++index)
            {
                yield return new WeatherForecast
                {
                    Date = DateTime.Now.AddDays(index),
                    TemperatureC = rng.Next(-20, 55),
                    Summary = Summaries[rng.Next(Summaries.Length)]
                };
                await Task.Delay(2000).ConfigureAwait(false);
            }
        }
    }
```

The hit the F5 in VS 2019. On browser http://localhost:53237/weatherforecast I need to wait after the 20s then receive the full JSON array. I found on headers response include Content-Length: <number>
I expect ASP.NET Core should return in-stream JSON item continuously instead wait to full buffer then return the whole large JSON. 

Is there any configuration to enable to allow stream data chunk to the client immediately without blocking and wait?

**Comment by ahsonkhan** [comment] 2019-09-27 02:51
This is a known issue/duplicate of https://github.com/dotnet/corefx/issues/38523.
The JSON serializer doesn't currently support IAsyncEnumerable.

Hence, closing.

> Is there any configuration to enable to allow stream data chunk to the client immediately without blocking and wait?

I don't think so, but I would defer to @mkArtakMSFT, @pranavkm can help answer this.
See related issue: https://github.com/aspnet/AspNetCore/issues/12883

**Closed by ahsonkhan** 2019-09-27 02:51 UTC
Labels: area-System.Text.Json
