### ISSUE TITLE
Address code reviews for porting System.IO.FileSystem.AccessControl

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#5221] opened 2016-01-07 00:32 UTC
@weshaggard  
Please assign @GiriSr to address the code reviews posted here
https://github.com/dotnet/corefx/pull/4946

**Comment by weshaggard** [comment] 2016-01-07 01:55
This is a duplicate of #4953 so closing.

**Closed by weshaggard** 2016-01-07 01:55 UTC
