### ISSUE TITLE
[ManagedHandler] Which Windows proxy settings should be default?

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26493] opened 2018-01-21 08:30 UTC
As mentioned in #24574, there are actually two different ways to configure proxy settings on Windows: "wininet style" and "winhttp style".  

For the "default" proxy in the managed handler, it's not clear which of these settings to use.

WinHttpHandler uses "wininet style" today, but there are scenarios where this is probably not the right choice (see linked issue above).

cc @davidsh @wfurt

**Comment by davidsh** [comment] 2018-01-21 15:52
.NET Framework doesn't support "winhttp" style proxy settings (i.e. using 'netsh').  It only supports reading the proxy settings via INETCPL (IE registry settings) to find a proxy via PAC file, WPAD protocol, or explicit in the per-user settings.

.NET Framework also supports having a custom IWebProxy defined in the handler (same as .NET Core).

Customers that need "machine-wide" settings (such as the what winhttp-style provides) can also use the app.config/machine.config to read a fixed proxy setting.  And since the config can be in the machine.config file, it is considered "machine-wide".

I think the solution here should not be to emulate reading settings from 'netsh' for winhttp but rather support app.config/machine.config and use the existing System.Net XML entries for that:

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

**Comment by karelz** [comment] 2018-02-01 18:39
Duplicate of #23150 where the work is tracked. If we need more discussion which settings to use, let's move it to that issue.
cc @wfurt

**Closed by karelz** 2018-02-01 18:39 UTC
Labels: area-System.Net.Http.ManagedHandler, enhancement
