### ISSUE TITLE
UDP socket throw SocketException(10054)

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#33049] opened 2018-10-25 15:36 UTC
_From @sillyousu on October 25, 2018 11:16_

`connection was forcibly closed by the remote host.`

Since UDP is connectionless, why does it throw such weird exception?

_Copied from original issue: dotnet/coreclr#20608_

**Comment by stephentoub** [comment] 2018-10-25 15:52
@sillyousu, can you share repro code?

**Comment by sillyousu** [comment] 2018-10-25 16:35
I can't share the repro code right now. 

It seems like a win socket problem:

https://social.msdn.microsoft.com/Forums/en-US/f8d9b559-fa29-4596-b6db-35f455fd88f8/problem-with-udpclient?forum=netfxnetcom

>if you send a UDP datagram and the destination is not reachable (because nobody is listening on that port), this should generate an ICMP Port Unreachable error. When this happens, the next call to Receive will cause the 10054 WSAECONNRESET to be returned (and hence the SocketException).

**Comment by karelz** [comment] 2018-10-25 16:38
OK, that would make it by design then.
Closing the issue. (Let me know if I misunderstood and it should be kept opened from some reason)

**Closed by karelz** 2018-10-25 16:38 UTC
Labels: area-System.Net.Sockets, bug

**Comment by sillyousu** [comment] 2018-10-25 17:00
@karelz 

Throwing `connection was forcibly closed by the remote host.` from a **functioning UDP socket** is bad design, if it's not a bug.

I hope dotnet team could do something to workaround it.

**Comment by karelz** [comment] 2018-10-25 17:10
@sillyousu what would you suggest?
Based on your link I thought we will get exactly that error from OS APIs. Or did I misunderstand and we will get another one earlier and we should just cache it?
