### ISSUE TITLE
NETStandard.Library is incompatible with netstandard1.0

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#7881] opened 2016-04-19 20:42 UTC
I tried to create a library for `netstandard1.0` that depends on NETStandard.Library (latest version from dotnet-core MyGet: 1.5.0-rc3-24019-00). My project.json:

```json
{
  "version": "1.0.0-*",
  "dependencies": {
    "NETStandard.Library": {
      "version": "1.5.0-rc3-24019-00"
    }
  },
  "frameworks": {
    "netstandard1.0": {}
  }
}
```

NETStandard.Library seemingly should support `netstandard1.0`, but it depends on `System.Threading.Timer`, which doesn't. This means that when I run `dotnet restore` for the project.json above, I get this error:

     Package System.Threading.Timer 4.0.1-rc3-24019-00 is not compatible with netstandard1.0 (.NETStandard,Version=v1.0). Package System.Threading.Timer 4.0.1-rc3-24019-00 supports:
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net451 (.NETFramework,Version=v4.5.1)
      - netcore50 (.NETCore,Version=v5.0)
      - netstandard1.2 (.NETStandard,Version=v1.2)
      - portable-net451+win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile151)
      - win81 (Windows,Version=v8.1)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
      - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
      - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
    One or more packages are incompatible with .NETStandard,Version=v1.0.

**Comment by GuardRex** [comment] 2016-04-19 23:26
@svick You might want to try droping that feed and stick to RC2 packages right now just inside of the RC2 release. If you go with the cli-samples set ...
```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
... it will only restore RC2 packages, and that might just clear up your exception. Worth a shot. :smile:

**Comment by svick** [comment] 2016-04-19 23:43
@GuardRex I'm not doing anything serious, so I like to live dangerously and use the latest code. That means that I don't need a work-around (maybe I should have said so). Thanks for the suggestion anyway, it does indeed fix the issue.

**Comment by ericstj** [comment] 2016-04-21 20:18
This seems to have regressed recently in RC3.  I'll see what caused it.

**Comment by ericstj** [comment] 2016-04-22 18:23
The issue is in buildtools, preparing a fix.

**Comment by ericstj** [comment] 2016-04-26 17:43
Fix is in rc3-24026-00.

**Closed by ericstj** 2016-04-26 17:43 UTC
Labels: packaging
