### ISSUE TITLE
Runtime Ids: Ubuntu 15.10 has been released

### ISSUE THREAD

**Issue by borgdylan** [dotnet/corefx#4324] opened 2015-11-04 21:01 UTC
I am not sure how runtime ids are computed, but if the ubuntu release version gets used, please remember that 15.10 is now officially released with people getting upgrade prompts.

**Comment by joshfree** [comment] 2015-11-04 22:00
@ericstj PTAL

**Comment by ericstj** [comment] 2015-11-05 00:10
/cc @anurse 
Right now 15.10 is not considered compatible so it's been omitted from https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

See https://github.com/aspnet/dnx/blob/ed98b4c687cf0785650d59e7b7a65a371bc5332f/src/Microsoft.Dnx.Tooling/Restore/ImplicitPackagesWalkProvider.cs#L96

**Comment by anurse** [comment] 2015-11-05 04:47
Unfortunately the version of `libicu` in Ubuntu is different from 15.04 so I believe this will require a new version of the globalization packages from corefx.

**Comment by joshfree** [comment] 2015-11-05 18:49
@ellismg can you take a look at the icu differences here?

**Comment by borgdylan** [comment] 2015-11-05 18:53
Can't .NET Core be packaged in a way that libicu gets included with the CoreCLR libraries i.e. xcopy deployed?

**Comment by ellismg** [comment] 2015-11-05 19:07
The ICU differences are just due to a different version of ICU, so the export names are decorated with a different version number.  There are not functional differences.

If we want to produce different packages, we'll need to build the native shims for that distro.  Note the problem is not specific to ICU.  For example, were now seeing cases where libcurl supports different flags across different distros, so we couldn't have binary compatibility for any of the shims across OS versions.

I think a sane sustainable path is to provide a way for the community to produce packages for RIDs they care about.  My understanding is that the system allows this, we just need to provide guidance around how folks can create their own RIDs and produce packages for them.  @ericstj would know more.

@borgdylan We do not want to go down a path of either statically linking or rolling our dependencies into our nuget packages.  The rationale is we don't want to end up shipping different versions from what's on the OS.

If you compile CoreCLR from source on Ubuntu 15.04, you will generate a System.Globalization.Native.so which will work on that target platform.  You should actually rebuild all the native shims (in both CoreFX and CoreCLR) in case there are other ABI differences.

**Comment by joshfree** [comment] 2015-11-06 19:37
I'm moving this to RC2; we will need to address this as part of the overall shim packaging story (tracked by https://github.com/dotnet/corefx/issues/2302)

**Comment by ericstj** [comment] 2015-11-24 18:28
A couple things to decide here:
1. Are we going to support Ubuntu 15.10 with binaries in our own packages?  If so it sounds like we need to cross-compile and provide new native shims.
2. Are we going to map Ubuntu 15.10 as a compatible RID with 15.04.  We will do this if we do 1, if not then I imagine we will leave it out and allow the same party that builds the native pieces to extend the RID graph. https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

**Comment by joshfree** [comment] 2015-11-24 19:03
We're supporting 14.04LTS and we will support 16.04LTS after it's released next year.  There are currently no plans to support 15.04/15/.10 (non-LTS minor versions) at this time.

**Closed by joshfree** 2015-11-24 19:03 UTC
Labels: X-Plat

**Comment by fergalmoran** [comment] 2015-12-16 22:30
MASSIVE oversight here - developers are using 15.x on their workstations and if we can't get this installed then we're not going to be developing. I'm currently bootstrapping a greenfield project and was looking forward to using this. I'm happy enough to jump through hoops to get it running on my machine but if the rest of my team can't apt-get their way to a working environment then it's back to django.

**Comment by photex** [comment] 2015-12-30 11:23
I'd like to echo the sentiment of @fergalmoran here. Not supporting a version of Ubuntu that many developers will in fact be using on their workstations doesn't seem like a great idea. At least updating the dotnet.github.io page with an alternative installation method for distro releases that aren't officially supported would be a possible solution here (not unlike downloading the JDK tarball *cough cough*).

I say all of this without knowing fully what would be required to do this of course. Perhaps we can open a separate ticket for establishing a ppa for "unstable" packages for the non-lts Ubuntu releases? I'd be happy to help!

**Comment by vaelen** [comment] 2016-02-16 15:45
Is there a guide to easily building from source so that I can build my own binaries for my OS version? I'm not going to roll back my system's OS version just to run .NET.
