### ISSUE TITLE
on ArgumentOutOfRange Exception and String.IndexOf and other related methods.

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/corefx#31785] opened 2018-08-15 19:19 UTC
Hello all,

When reviewing some code today I came across a situation where I would have assumed that no exception would be thrown from the aforementioned methods when provided with a index which is out of bounds giving a string context.

Looking at MSDN for the [IndexOf ](https://msdn.microsoft.com/en-us/library/k8b1470s(v=vs.110).aspx)method one is not immediately presented with the fact that the method will thrown an Exception until they dig down to the method which is called from the underlying overload, in this case [IndexOf](https://msdn.microsoft.com/en-us/library/ms224423(v=vs.110).aspx)(string, int, int, StringComparison).

In both cases the Return Value is clearly stated to be:

Type: System.Int32
The zero-based index position of value if that string is found, or -1 if it is not. If value is String.Empty, the return value is 0.

My gripe here is when the index exceeds the Length you can just return -1, as you know what index you called the function on it also doesn’t serve much purpose throwing an exception however it does seem to waste a bit of resources IMHO.

1) Whats the reason for forcing the exception? I believe the same with the null or empty string, we should return -1 and not throw the Exception.

2) If we are not going to change this perhaps we can have an alternate set of methods which would be able to accommodate such, for instance would the the same thing happening on the Span<char> based overloads and we probably wouldn't want to throw an exception in that case right? (We should probably return the empty span in that case)

Please let me know if there is consensus and if so we can then determine what way to proceed, e.g. removing the exception of providing alternative methods.

**Comment by danmosemsft** [comment] 2018-08-15 19:25
Some decisions about throwing vs return value are lost in time, we can speculate but if the behavior has been the same for 20 years, it cannot reasonably change now. (If the docs are deficient, they would welcome a PR at https://github.com/dotnet/docs)

**Comment by juliusfriedman** [comment] 2018-08-15 19:25
Why not? Those who were expecting the exception must also be handling the -1 case? Whats the breaking change with this?

**Comment by danmosemsft** [comment] 2018-08-15 19:37
If the index exceeds the length it may well be because of a bug in the caller's code, which is likely why it was chosen to throw -- so the developer would know there is a bug, and fix it. C++ made a different choice.

As for what the breaking change is - there are billions of lines of C# happily running and that number is so large that it is not hard to believe that there is code that is happily catching the exception and doing X (for whatever reason maybe accident) and sending it down the Y path (-1) would cause some bug elsewhere in the program. We have many times seen this when making seemingly less impactful changes to the .NET Framework. In such a case it is often not feasible or reasonable to ask the application to be debugged, rebuilt and redeployed to work again.

For .NET Core we do have more freedom to make potentially breaking changes, mainly because of side by side deployment. However we still need a good reason to change and particularly so when it is something as fundamental and heavily used as the String class.

**Comment by juliusfriedman** [comment] 2018-08-15 22:28
Thanks for your feedback, your welcome to close the issue or reference as. you see fit.

I haven't taken the time to review the span based apis but it would be a shame to have to roll your own implementations especially for Span given they were created with performance in mind.

Perhaps if those API's didn't throw since they were just recently added as extension methods that would be nicest solution IMHO

**Comment by svick** [comment] 2018-08-16 11:34
> Looking at MSDN for the [IndexOf ](https://msdn.microsoft.com/en-us/library/k8b1470s(v=vs.110).aspx)method one is not immediately presented with the fact that the method will thrown an Exception until they dig down to the method which is called from the underlying overload, in this case [IndexOf](https://msdn.microsoft.com/en-us/library/ms224423(v=vs.110).aspx)(string, int, int, StringComparison).

As far as I can tell, all overloads that take an `index` have `ArgumentOutOfRangeException` documented. The one you linked to doesn't, but that's because it's the one that can't throw it, because it doesn't take an `index`.

You don't have to consider what overload is called internally, what you have to consider is which overload you're actually calling.

**Comment by danmosemsft** [comment] 2018-08-16 17:06
@juliusfriedman just curious what the scenario where the index is beyond the length of the string so commonly that an exception becomes a perf problem, and it's not a bug?

**Comment by juliusfriedman** [comment] 2018-08-18 12:58
Well it's almost two fold, someone handling strings must always call if(string.IsNullOrEmpty) which can be expected if they want to avoid the initial exceptions for null or empty.

However consider some parse scenario which doesn't substring either in http headers or ini files,where you parse after the IndexOf another known ordinal say : or = etc, you can only skip the exception there by comparing against the length before trying to IndexOf again otherwise ArgumentOutOfRange.

Most of the time one will and should be working off the length first which can minimize this however in cases where it's not you can lead to those two exceptions where returning the -1 or string.empty, would be much more desired at the very least so my code in my catch case didn't have to jump through hoops to be unified with the try (variable placement etc) and the I could probably drop the try altogether in that case.

Please let me know if I can clarify further.

**Comment by juliusfriedman** [comment] 2018-12-01 22:42
Also noting here that exposing a NoThrow version of the Api for performance critical code is helpful in code review where you have an expectation that the string passed was previously checked for those conditions.

**Comment by bartonjs** [comment] 2019-02-27 18:57
I can, to me, justify IndexOf in terms of LastIndexOf.

```C#
int pos = "short".LastIndexOf("t", 840);
```

Two different callers could want two different answers.  Caller A wants the last index less than 840, which in this case is 4.  Caller B wants "this was out of bounds, so return no match (-1)".  The resolution to the ambiguity is to throw an Argument(OutOfRange)Exception indicating that this data made no sense.

Caller A can achieve their scenario by doing `pos = str.LastIndexOf("t", Math.Min(str.Length, 840))`.  Caller B can achieve theirs by `pos = str.Length < 840 ? -1 : str.LastIndexOf("t", 840)`

Since LastIndexOf throws on out of bounds, it stands to reason that (First)IndexOf also would.

For the other direction (negative indexes), throwing prevents this sort of oops bug

```
int pos = 0;

while (pos < 840)
{
    // assume no match, so pos gets set to -1.
   pos = str.IndexOf("t", pos);
}
```

(yes, it should get caught by negative tests)

And, again, for symmetry LastIndexOf throws in that case.

---

If you feel the documentation led you wrong, please report an issue through the docs site.

If you think that the platform would benefit from a non-throwing alternate method, you could propose an API suggestion; but I'm not finding any public `_NoThrow`-type variants in the platform off of a cursory glance.

For local workaround you could define an extension method

```C#
public static int IndexOf_NoThrow(this string haystack, string needle, int startIndex)
{
    if ((uint)startIndex < (uint)haystack.Length)
        return -1;

    return haystack.IndexOf(needle, startIndex);
}
```

Closing the issue since it seemed mainly about asking why IndexOf throws for out of range (which isn't specifically known at this remove, my statements are just conjecture) or suggesting that it be changed (which is a pretty subtle change with a too-high risk of impact).

**Closed by bartonjs** 2019-02-27 18:57 UTC
Labels: area-System.Runtime, question
