### ISSUE TITLE
[Question] Give a timeout to async socket on .net core (linux)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29063] opened 2018-04-12 15:49 UTC
_From @316181444 on April 12, 2018 4:19_

How set a timeout for Socket.ConnectAsync, Socket.SendAsync, Socket.ReceveAsync APIs?

Thanks.

_Copied from original issue: dotnet/coreclr#17525_

**Comment by karelz** [comment] 2018-04-12 19:08
For `ConnectAsync,` there seems to be [`CancelConnectAsync`](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.cancelconnectasync(v=vs.110).aspx). `SendAsync` and `ReadAsync` currently don't have timeouts/cancellations AFAIK - you can use `Socket.Close` only.
@geoffkizer @stephentoub @davidsh are you aware of better ways to do that?

Seems to be related to #5749 #9698 and #24430

**Comment by geoffkizer** [comment] 2018-04-12 21:11
We don't support this today.  Best way to handle it is to close the socket if you want to cancel the IO.

**Comment by stephentoub** [comment] 2018-04-12 21:12
Yes, until #24430 is implemented, closing the socket is the only real option.

**Comment by karelz** [comment] 2018-04-12 21:25
Closing as duplicate of #24430

**Closed by karelz** 2018-04-12 21:25 UTC
Labels: area-System.Net.Sockets, question
