### ISSUE TITLE
Remove_PrefixExistsStarted_ReturnsTrue failure in CI

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#19539] opened 2017-05-09 18:21 UTC
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/7597/consoleFull#145732169079fe3b83-f408-404c-b9e7-9207d232e5fc

> System.Net.Tests.HttpListenerPrefixCollectionTests.Remove_PrefixExistsStarted_ReturnsTrue [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.Http.HttpRequestException)
        Actual:   (No exception was thrown)
        Stack Trace:
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs(390,0): at System.Net.Tests.HttpListenerPrefixCollectionTests.<Remove_PrefixExistsStarted_ReturnsTrue>d__28.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by bartonjs** [comment] 2017-05-09 18:21
Also https://ci.dot.net/job/dotnet_corefx/job/master/job/portablelinux_debug_prtest/4880/consoleFull#90892433279fe3b83-f408-404c-b9e7-9207d232e5fc.  Both were from a docs-only PR.

**Comment by Priya91** [comment] 2017-05-10 00:22
cc @hughbe Can you please take a look, it's one of the newly added tests..

**Comment by karelz** [comment] 2017-05-10 01:38
We don't want flaky tests in 2.0 servicing branch - we need to either disable the test, or fix it in 2.0.
@Priya91 @hughbe can you please disable it? (unless we know how to fix it right away)

**Comment by karelz** [comment] 2017-05-10 01:39
Moving it to 2.0, because it failed twice in last day, way above the threshold we want to tolerate.

**Comment by hughbe** [comment] 2017-05-10 01:40
It's already disabled: https://github.com/dotnet/corefx/commit/61019d50ce88722207bcbfcea7e02f5cf7ba33a2

**Comment by karelz** [comment] 2017-05-10 01:47
OK, closing as dupe of #19526.
Please shout out if it is incorrect.

**Closed by karelz** 2017-05-10 01:47 UTC
Labels: area-System.Net.Http, bug
