### ISSUE TITLE
Accent and Special Characters

### ISSUE THREAD

**Issue by eflorespalma** [dotnet/corefx#20944] opened 2017-06-12 20:56 UTC
I have a problem with this code

```c#
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseWelcomePage("/welcome");
            
            app.Run(async (context) =>
            {
                //var message = Configuration["Greeting"];
                await context.Response.WriteAsync("¿Cómo estas?");
            });
```

And when render the output show me this text Â¿CÃ³mo estas?

**Comment by karelz** [comment] 2017-06-12 22:47
Can you provide small repro which compiles? Which .NET Core version do you use? Did you try latest? (2.0 Preview 1)

**Comment by eflorespalma** [comment] 2017-06-13 13:01
I´m not using the version 2.0, but when i return the same text from a mvc controller, it works fine, The problem is only when I do it from the startup class.
`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.2",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.2",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.1.3",
    "System.Text.Encoding.CodePages": "4.4.0-preview1-25305-02"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by tarekgh** [comment] 2017-06-13 15:51
@eflorespalma

> And when render the output show me this text Â¿CÃ³mo estas?

Where you render the output? do you render it to the console? or you see it in VS? please clarify. Also could you dump the character ordinal value before rendering it? I am trying to know where the problem is. Thanks.

**Comment by eflorespalma** [comment] 2017-06-13 16:27
Its a web application... and it renders to localhost web page.... I dont have more code.. thats all. I used this for a demo.

**Comment by karelz** [comment] 2017-06-13 16:31
For web apps you can ask on https://github.com/aspnet/Home. For isolated repro in console app, this is the right place - is such case, please post full repro we can compile locally, otherwise we can't make much progress.

**Comment by tarekgh** [comment] 2017-06-13 16:39
@eflorespalma I have moved the issue to aspnet repo https://github.com/aspnet/Home/issues/2058 so you can follow up there and I am closing the issue here. 

It'll be nice if you can provide there a complete sample project reproing the issue as you are seeing. Thanks.

**Closed by tarekgh** 2017-06-13 16:39 UTC
Labels: area-System.Globalization, bug
