### ISSUE TITLE
XsdDataContractExporter.DataContractSet always returns null

### ISSUE THREAD

**Issue by huanwu** [dotnet/corefx#13355] opened 2016-11-04 18:30 UTC
The following code in DataContractSet is commented. So XsdDataContractExporter.Export will always fail because of NullReferenceException
        DataContractSet DataContractSet
        {
            get
            {
                //if (dataContractSet == null)
                //{
                //    dataContractSet = new DataContractSet((Options == null) ? null : Options.GetSurrogate());
                //}
                return _dataContractSet;
            }
        }

**Comment by karelz** [comment] 2016-11-04 19:33
Dupe of #12772 (GetSurrogate is the common theme there)

**Closed by karelz** 2016-11-04 19:33 UTC
Labels: area-Serialization
