### ISSUE TITLE
Socket.DontFragment throws not supported exception on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#16739] opened 2017-03-06 01:14 UTC
Presumably due to https://github.com/dotnet/corefx/blob/7a230270559cfbef056aaafc022cdfd8fd3d829e/src/Native/Unix/System.Native/pal_networking.cpp#L2043 (i.e. lack of a translation for the option).  It's not clear to me whether/why this is by design, but it should be investigated.

**Comment by geoffkizer** [comment] 2017-03-08 19:28
Apparently the equivalent on Linux is setting the IP_MTU_DISCOVER option to IP_PMTUDISC_DO.  It's not clear to me that this is *exactly* equivalent to the existing Windows behavior, though.

See https://linux.die.net/man/7/ip

**Comment by mellinoe** [comment] 2017-03-08 21:03
Duplicate of https://github.com/dotnet/corefx/issues/9652

Also related: https://github.com/dotnet/corefx/issues/9350

**Closed by mellinoe** 2017-03-08 21:03 UTC
Labels: area-System.Net.Sockets, os-linux, os-mac-os-x
