### ISSUE TITLE
Issue with Microsoft.Window.Compatibility 

### ISSUE THREAD

**Issue by BrijeshKrSingh** [dotnet/corefx#37127] opened 2019-04-23 20:36 UTC
Hi Team,

I am using core2.1 and having issue with Ldap search. I am calling BeginSendRequest function and it is working for all options except NoPartialResultSupport. It is throwing error as "Operation is not supported on this platform." Is it known issue?

**Comment by karelz** [comment] 2019-04-24 09:21
Which API do you use? Small code snippet would help.
Which OS do you run on?
If it is System.DirectoryServices APIs, then it is known limitation that it does not work on Linux/Mac.

**Comment by BrijeshKrSingh** [comment] 2019-04-24 11:56
I am using window and Microsoft.Window.Compatibility version 2.0.1.

 ```
string[] attributes = new string[] { "Some Attributes" };
            string serverName = "SomeServer:SomePort";
            string DN = "SomeDn";
            using (var con = new LdapConnection(serverName))
            {
                con.SessionOptions.AutoReconnect = true;
                con.SessionOptions.ProtocolVersion = 3;
                con.SessionOptions.SaslMethod = "SomeMethod";
                con.SessionOptions.Sealing = false;
                con.AuthType = AuthType.Negotiate;
                var filter = "(mail=brijesh@test.com)";
                var request = new SearchRequest(DN, filter, SearchScope.Subtree, attributes);
                con.BeginSendRequest(
                    request,
                    PartialResultProcessing.NoPartialResultSupport, ar =>
                    {
                        //needs to impliment
                    }, null);

            }
```

**Comment by BrijeshKrSingh** [comment] 2019-04-24 12:04
By Mistake clicked to close

**Comment by karelz** [comment] 2019-04-24 14:14
That is type `System.DirectoryServices.Protocols.LdapConnection`

**Comment by karelz** [comment] 2019-04-24 14:16
That should be implemented as of .NET Core 2.1 - see #2089.
Can you try .NET Core 2.1+ version?

**Comment by BrijeshKrSingh** [comment] 2019-04-24 14:45
We are still using .NET Core 2.1 and were under impression that core 2.1 should work. It is working for all values(PartialResultProcessing.ReturnPartialResults,PartialResultProcessing.ReturnPartialResultsAndNotifyCallback) other than NoPartialResultSupport. Is it a bug with core 2.1?

**Comment by karelz** [comment] 2019-04-24 16:06
That's an importnat clarification.
Which OS version.
Did you try to get full callstack of the exception?
Did you try to look at the sources?

**Comment by BrijeshKrSingh** [comment] 2019-04-24 16:34
**Window OS version:**  Version 6.1.7601
**Source**: System.DirectoryServices.Protocols
![Screen Shot 2019-04-24 at 12 31 20 PM](https://user-images.githubusercontent.com/36520491/56676743-fa29aa80-668c-11e9-8c72-6764ce6c40ee.png)

**Comment by karelz** [comment] 2019-04-24 16:39
Screenshots are not searchable or copy-pastable.
Please post callstack in text form.
Also please try to check the source code first.
Which OS version is the number above? Win7? Win10?

**Comment by BrijeshKrSingh** [comment] 2019-04-24 17:33
Hi Karel,
I am using window7. There is no much code as I have created console Application to test it and it is having as much code as I have provided above.

**Stacktrace**: 
`at System.DirectoryServices.Protocols.GetLdapResponseCallback.BeginInvoke(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeout,                                                                                    Boolean exceptionOnTimeOut, AsyncCallback callback,Object object)             at             System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request,TimeSpan requestTimeOut, PartialResultProcessing partialMode, AsyncCallback callback, object state)              at             System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, PartialResultProcessing partialMode, AsyncCallback callback, object state)             at             ConsoleApp7.Program.Main(String[] args) in C:\Users\Brijesh\ConsoleApp7\ConsoleApp7\Program.cs:line 38`

**Comment by karelz** [comment] 2019-04-25 21:43
I don't understand how this could be that call stack.
Did you try to debug it? Which lines throws and why?

**Comment by BrijeshKrSingh** [comment] 2019-04-25 21:56
below line is throwing error from my program. I have provided the stacktrace from exception.

```
var request = new SearchRequest(DN, filter, SearchScope.Subtree, attributes);
               con.BeginSendRequest(
                   request,
                   PartialResultProcessing.NoPartialResultSupport, ar =>
                   {
                       //needs to impliment
                   }, null);
```

**Comment by karelz** [comment] 2019-04-25 22:00
Did you try to debug into the CoreFX source code?
I have never used DirectoryServices, so unless there is HelloWorld I can copy-paste into VS and debug, I am afraid I can't help.

**Comment by tquerec** [comment] 2019-06-13 19:58
duplicate of #34730

**Closed** 2019-06-13 20:06 UTC
Labels: area-System.DirectoryServices, needs more info, question
