### ISSUE TITLE
Selective reflection enable CompilerServices.RuntimeOps in S.L.Expressions rdxml

### ISSUE THREAD

**Issue by tijoytom** [dotnet/corefx#18112] opened 2017-04-08 17:23 UTC
Right now the whole type is included , this might not be necessary.
<Type Name="System.Runtime.CompilerServices.RuntimeOps" Dynamic="Required All" />

**Comment by karelz** [comment] 2017-04-08 21:20
@tijoytom why is it assigned to @shmao?
Can you please follow [CoreFX triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) in future? Setting labels would be also helpful -- not sure if this one is bug or enhancement.

**Comment by VSadov** [comment] 2017-07-07 22:07
RuntimeOps  primarily exists to hold helpers that are being called at run time via reflection, often from generated/interpreted code.
I think everything public in that class is needed. (otherwise it would not be public). 

@vitek-karas - assuming everything public in that class is needed at run time, is there anything actionable here?

**Comment by VSadov** [comment] 2017-07-07 22:15
Is this something that is needed for 6.0 or can be moved to after?

**Comment by vitek-karas** [comment] 2017-07-07 22:25
If we need all of the public members at runtime through reflection, then there's nothing we can do here - the current state is as good as it gets.
Eventually it would be nice to understand the size implications of this and if we can somehow trim it down... but that's work definitely after 6.0.

I don't think there's anything for 6.0 here - it's not a bug per se (it works), it's an improvement for size-on-disk (and compilation times).

**Comment by VSadov** [comment] 2017-07-07 22:39
Moving to after6.0 - not sure if there is a lot to be gained here, but may be worth looking at.

@jaredpar - FYI

**Closed** 2019-10-21 11:50 UTC
Labels: area-System.Linq.Expressions, os-windows-uwp
