### ISSUE TITLE
ExpandPrime will throw when near MaxPrimeArrayLength

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#2765] opened 2015-08-12 20:33 UTC
Call ExpandPrime in HashHelpers.cs and HashTable.cs with MaxPrimeArrayLength + 1.

The function looks like this:

public static int ExpandPrime(int oldSize)
{
            int newSize = 2 * oldSize;

            if ((uint)newSize > MaxPrimeArrayLength && MaxPrimeArrayLength > oldSize)
            {
                return MaxPrimeArrayLength;
            }

            return GetPrime(newSize);
}

MaxPrimeArrayLength + 1 become -2097156 which, when cast to uint becomes	4292870140 which
passes the 'if' condition and GetPrime is then called with a negative value. This caused GetPrime to: throw new ArgumentException(SR.Arg_HTCapacityOverflow);

proposed solution:

public static int ExpandPrime(int oldSize)
{
            int newSize = 2 * oldSize;

            // newSize will be negative if it overflows so we return the largest possible instead
            if (newSize < 0 || oldSize > MaxPrimeArrayLength)
            {
                return MaxPrimeArrayLength;
            }

            return GetPrime(newSize);
}

**Comment by JonHanna** [comment] 2015-08-26 11:04
The problem isn't the test of newSize, which is correct; it should be true for a negative, which it is, and it should be true if it itself ends up as `2146435070` or greater, which your suggestion breaks.

The problem is the test also requires `MaxPrimeArrayLength > oldSize` which isn't true if `oldSize` is `MaxPrimeArrayLength + 1` or more importantly if it is `MaxPrimeArrayLength`, which is a possible result from a previous result.

However, this isn't really a problem.

If `MaxPrimeArrayLength <= oldSize` then we can't settle for `MaxPrimeArrayLength`, so what we have to do is:

1. If `newSize` is positive but larger than `MaxPrimeArrayLength`, just use it directly, despite it not being prime.
2. Otherwise throw an `ArgumentException` with the message "Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table." or the localised equivalent.

These are also what we have to do if `GetPrime()` is called directly with a number that is either negative or greater than `MaxPrimeArrayLength`, and indeed what `GetPrime()` does in those cases.

As such, to trigger either correct behaviour (depending on whether `newSize` is negative or not) we can just call `GetPrime()` with `newSize`.

So the current code is fine.

Yours though misses cases it should return `MaxPrimeArrayLength` on.

**Comment by ianhays** [comment] 2015-12-11 03:28
Thanks Jon! I looked into this and agree. Closing.

**Closed by ianhays** 2015-12-11 03:28 UTC
Labels: System.Collections
