### ISSUE TITLE
Failing unit tests in clean macOS development environment

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/corefx#15202] opened 2017-01-15 09:05 UTC
I've followed the instructions outlined [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md), and after running `./build-tests.sh`, two unit tests failed:

```
      <test name="System.Diagnostics.Tests.ProcessTests.TestProcessStartTime" type="System.Diagnostics.Tests.ProcessTests" method="TestProcessStartTime" time="0.457767" result="Fail">
        <failure exception-type="Xunit.Sdk.InRangeException">
          <message><![CDATA[Assert.InRange() Failure\r\nRange:  (1/15/17 8:51:09 AM - 1/15/17 8:51:15 AM)\r\nActual: 1/15/17 12:36:59 AM]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.Tests.ProcessTests.TestProcessStartTime() in /Users/yaakov/Development/ThirdParty/corefx/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 416]]></stack-trace>
        </failure>
      </test>
```

```
       <test name="System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(format: DateTimeFormatInfo { AbbreviatedDayNames = [\&quot;dim.\&quot;, \&quot;lun.\&quot;, \&quot;mar.\&quot;, \&quot;mer.\&quot;, \&quot;jeu.\&quot;, ...], AbbreviatedMonthGenitiveNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AbbreviatedMonthNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AMDesignator = \&quot;AM\&quot;, Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }, expected: [\&quot;Dimanche\&quot;, \&quot;Lundi\&quot;, \&quot;Mardi\&quot;, \&quot;Mercredi\&quot;, \&quot;Jeudi\&quot;, ...])" type="System.Globalization.Tests.DateTimeFormatInfoGetDayName" method="GetDayName" time="0.000331" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Dimanche\nActual:   dimanche\n          ↑ (pos 0)]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(DateTimeFormatInfo format, String[] expected) in /Users/yaakov/Development/ThirdParty/corefx/src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetDayName.cs:line 44]]></stack-trace>
        </failure>
      </test>
```

This occurred on macOS 10.12.2 (16C67).

**Comment by karelz** [comment] 2017-01-17 16:48
Did they fail just once?
We might need to slit them into separate issues.

**Comment by yaakov-h** [comment] 2017-01-17 19:46
The second time I set up a clean workspace those two failed, plus another one in WebProxy. I didn't catch the name at the time.

**Comment by danmosemsft** [comment] 2017-01-22 04:54
The second one looks like it needs the same workaround as in https://github.com/dotnet/corefx/pull/6257. I don't see an active issue to make the tests work on those platforms. cc @tarekgh for info that this is happening on Mac.

**Comment by danmosemsft** [comment] 2017-01-22 04:56
The first one is odd, it means Process.GetCurrentProcess().StartTime.ToUniversalTime() was several hours (but not an even difference, like a timezone) different to DateTime.UtcNow.

**Comment by yaakov-h** [comment] 2017-01-22 06:05
Just set up a clean workspace again and built and re-tested.

Build warnings:

```
/private/tmp/corefx/Tools/Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/private/tmp/corefx/src/Tools/CoreFx.Tools/CoreFx.Tools.csproj]
/private/tmp/corefx/src/System.Configuration.ConfigurationManager/src/Resources/Strings.resx : warning MSB3568: Duplicate resource name "Config_base_unrecognized_element" is not allowed, ignored. [/private/tmp/corefx/src/System.Configuration.ConfigurationManager/src/System.Configuration.ConfigurationManager.csproj]
```

Then, failed tests:

```
/private/tmp/corefx/Tools/tests.targets(210,5): warning :    System.Diagnostics.Process.Tests  Total: 108, Errors: 0, Failed: 1, Skipped: 0, Time: 23.338s [/private/tmp/corefx/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning MSB3073: The command "/private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Diagnostics.Process.Tests/netstandard/RunTests.sh /private/tmp/corefx/Tools/testdotnetcli" exited with code 1. [/private/tmp/corefx/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning :    System.Globalization.Tests  Total: 1635, Errors: 0, Failed: 2, Skipped: 0, Time: 4.899s [/private/tmp/corefx/src/System.Globalization/tests/System.Globalization.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning MSB3073: The command "/private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Globalization.Tests/netstandard/RunTests.sh /private/tmp/corefx/Tools/testdotnetcli" exited with code 1. [/private/tmp/corefx/src/System.Globalization/tests/System.Globalization.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning :    System.Net.WebProxy.Tests  Total: 21, Errors: 0, Failed: 1, Skipped: 0, Time: 6.973s [/private/tmp/corefx/src/System.Net.WebProxy/tests/System.Net.WebProxy.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning MSB3073: The command "/private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Net.WebProxy.Tests/netstandard/RunTests.sh /private/tmp/corefx/Tools/testdotnetcli" exited with code 1. [/private/tmp/corefx/src/System.Net.WebProxy/tests/System.Net.WebProxy.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning :    System.Net.NameResolution.Pal.Tests  Total: 13, Errors: 0, Failed: 2, Skipped: 0, Time: 10.575s [/private/tmp/corefx/src/System.Net.NameResolution/tests/PalTests/System.Net.NameResolution.Pal.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(210,5): warning MSB3073: The command "/private/tmp/corefx/bin/Unix.AnyCPU.Debug/System.Net.NameResolution.Pal.Tests/netstandard/RunTests.sh /private/tmp/corefx/Tools/testdotnetcli" exited with code 1. [/private/tmp/corefx/src/System.Net.NameResolution/tests/PalTests/System.Net.NameResolution.Pal.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(218,5): error : One or more tests failed while running tests from 'System.Diagnostics.Process.Tests' please check /private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Diagnostics.Process.Tests/netstandard/testResults.xml for details! [/private/tmp/corefx/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(218,5): error : One or more tests failed while running tests from 'System.Globalization.Tests' please check /private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Globalization.Tests/netstandard/testResults.xml for details! [/private/tmp/corefx/src/System.Globalization/tests/System.Globalization.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(218,5): error : One or more tests failed while running tests from 'System.Net.WebProxy.Tests' please check /private/tmp/corefx/bin/AnyOS.AnyCPU.Debug/System.Net.WebProxy.Tests/netstandard/testResults.xml for details! [/private/tmp/corefx/src/System.Net.WebProxy/tests/System.Net.WebProxy.Tests.csproj]
/private/tmp/corefx/Tools/tests.targets(218,5): error : One or more tests failed while running tests from 'System.Net.NameResolution.Pal.Tests' please check /private/tmp/corefx/bin/Unix.AnyCPU.Debug/System.Net.NameResolution.Pal.Tests/netstandard/testResults.xml for details! [/private/tmp/corefx/src/System.Net.NameResolution/tests/PalTests/System.Net.NameResolution.Pal.Tests.csproj]
Command execution failed with exit code 1.
```

Some failures are the same as above, some look new.

```
      <test name="System.Diagnostics.Tests.ProcessTests.TestProcessStartTime" type="System.Diagnostics.Tests.ProcessTests" method="TestProcessStartTime" time="0.292751" result="Fail">
        <failure exception-type="Xunit.Sdk.InRangeException">
          <message><![CDATA[Assert.InRange() Failure\r\nRange:  (1/22/17 5:50:13 AM - 1/22/17 5:50:19 AM)\r\nActual: 1/22/17 4:24:11 AM]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.Tests.ProcessTests.TestProcessStartTime() in /private/tmp/corefx/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 416]]></stack-trace>
        </failure>
      </test>
```

Interesting that the difference between process start time and current time here is different to the previous failure in the original post above.

```
       <test name="System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedDayName.GetAbbreviatedDayName(info: DateTimeFormatInfo { AbbreviatedDayNames = [\&quot;dim.\&quot;, \&quot;lun.\&quot;, \&quot;mar.\&quot;, \&quot;mer.\&quot;, \&quot;jeu.\&quot;, ...], AbbreviatedMonthGenitiveNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AbbreviatedMonthNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AMDesignator = \&quot;AM\&quot;, Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }, expected: [\&quot;Dim.\&quot;, \&quot;Lun.\&quot;, \&quot;Mar.\&quot;, \&quot;Mer.\&quot;, \&quot;Jeu.\&quot;, ...])" type="System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedDayName" method="GetAbbreviatedDayName" time="0.000306" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Dim.\nActual:   dim.\n          ↑ (pos 0)]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.DateTimeFormatInfoGetAbbreviatedDayName.GetAbbreviatedDayName(DateTimeFormatInfo info, String[] expected) in /private/tmp/corefx/src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetAbbreviatedDayName.cs:line 43]]></stack-trace>
        </failure>
      </test>
```

```
      <test name="System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(format: DateTimeFormatInfo { AbbreviatedDayNames = [\&quot;dim.\&quot;, \&quot;lun.\&quot;, \&quot;mar.\&quot;, \&quot;mer.\&quot;, \&quot;jeu.\&quot;, ...], AbbreviatedMonthGenitiveNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AbbreviatedMonthNames = [\&quot;janv.\&quot;, \&quot;févr.\&quot;, \&quot;mars\&quot;, \&quot;avr.\&quot;, \&quot;mai\&quot;, ...], AMDesignator = \&quot;AM\&quot;, Calendar = GregorianCalendar { AlgorithmType = SolarCalendar, CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, ... }, ... }, expected: [\&quot;Dimanche\&quot;, \&quot;Lundi\&quot;, \&quot;Mardi\&quot;, \&quot;Mercredi\&quot;, \&quot;Jeudi\&quot;, ...])" type="System.Globalization.Tests.DateTimeFormatInfoGetDayName" method="GetDayName" time="0.017261" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Dimanche\nActual:   dimanche\n          ↑ (pos 0)]]></message>
          <stack-trace><![CDATA[   at System.Globalization.Tests.DateTimeFormatInfoGetDayName.GetDayName(DateTimeFormatInfo format, String[] expected) in /private/tmp/corefx/src/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoGetDayName.cs:line 44]]></stack-trace>
        </failure>
      </test>
```

These two Globalisation ones look like capitalisation issues.

```
      <test name="System.Net.Tests.WebProxyTest.BypassOnLocal_MatchesExpected" type="System.Net.Tests.WebProxyTest" method="BypassOnLocal_MatchesExpected" time="0" result="Fail">
        <failure exception-type="System.Net.Internals.SocketExceptionFactory+ExtendedSocketException">
          <message><![CDATA[System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured]]></message>
          <stack-trace><![CDATA[   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /private/tmp/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 422
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /private/tmp/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 561
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult) in /private/tmp/corefx/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 651
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext() in /private/tmp/corefx/src/System.Net.WebProxy/tests/WebProxyTest.cs:line 146
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /private/tmp/corefx/src/System.Linq/src/System/Linq/Select.cs:line 133]]></stack-trace>
        </failure>
      </test>
```

```
      <test name="System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName" type="System.Net.NameResolution.PalTests.NameResolutionPalTests" method="GetHostByName_HostName" time="5.025076" result="Fail">
        <failure exception-type="System.Net.Internals.SocketExceptionFactory+ExtendedSocketException">
          <message><![CDATA[System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Device not configured]]></message>
          <stack-trace><![CDATA[   at System.Net.NameResolutionPal.GetHostByName(String hostName) in /private/tmp/corefx/src/System.Net.NameResolution/src/System/Net/NameResolutionPal.Unix.cs:line 151
   at System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName() in /private/tmp/corefx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 40]]></stack-trace>
        </failure>
      </test>
```

These two were a `Device not configured` exception in DNS resolution.

```
      <test name="System.Net.NameResolution.PalTests.NameResolutionPalTests.GetHostByName_HostName_GetHostByAddr" type="System.Net.NameResolution.PalTests.NameResolutionPalTests" method="GetHostByName_HostName_GetHostByAddr" time="0.084207" result="Pass" />
      <test name="System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName" type="System.Net.NameResolution.PalTests.NameResolutionPalTests" method="TryGetAddrInfo_HostName" time="5.010565" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: Success\nActual:   HostNotFound]]></message>
          <stack-trace><![CDATA[   at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName() in /private/tmp/corefx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 116]]></stack-trace>
        </failure>
      </test>
```

This one suggests there are no DNS records for my current hostname, which, testing with `dig`, does appear to be true.

**Comment by tarekgh** [comment] 2017-01-23 16:42
will take a look at the globalization tests when have a chance. yes I can see the capitalization issue but I need to double check the data on MAC

**Comment by tarekgh** [comment] 2017-01-23 16:43
will take a look at the Process failing too.

**Comment by karelz** [comment] 2017-01-23 18:22
I wonder if this is some bad/weird machine setup causing the failures. We're running the tests in CI on Mac and on several dev Macs - they don't fail anywhere ...
Anyway, let's try to root cause at least one test failure, then hopefully we can make some conclusions ...

**Comment by tarekgh** [comment] 2017-01-25 17:35
I confirmed seeing the failures on macOS 10.12.3. this is Sierra mac release which looks changed some stuff on it. I have fix for the globalization failure will try to submit a PR for it today. also looked at the Process failure and the problem looks there is some change that broke the assumption how we calculate the process start time (note that is not related to Time zones). I am looking more deeply on that. 

will try to look at the networking failures too to know if there is easy fix or I have to get the networking guys take a look.

**Comment by karelz** [comment] 2017-01-25 17:43
Thanks @tarekgh! Any idea why it slipped through our internal testing? Is it because we do not test on Sierra?

**Comment by tarekgh** [comment] 2017-01-25 17:47
most likely we don't test on Sierra. is there a way can I get the CI configuration machine? I mean what MacOS version used in the runs? 

CC @mmitche

**Comment by mmitche** [comment] 2017-01-25 17:48
@tarekgh El Cap

**Comment by tarekgh** [comment] 2017-01-25 17:49
thanks @mmitche. as expected :-)

**Comment by karelz** [comment] 2017-01-25 17:53
@mmitche is there a plan to keep our Mac running on latest MacOS?

**Comment by mmitche** [comment] 2017-01-25 17:55
@karelz I don't have a plan to upgrade currently.  It's up to the .NET Core LT to decide what to do.

**Comment by tarekgh** [comment] 2017-01-25 17:56
I would say it will be good to wait a little till we clear the current failures

**Comment by karelz** [comment] 2017-01-25 17:58
@mmitche which LT do you mean? Let's kick off that discussion internally ...

@tarekgh I am not pushing for any immediate change. I am curious if we have any long-term plans how to continuously keep testing latest MacOS - the answer seems to be none yet. We have it kind of covered for latest Linux distros.

**Comment by danmosemsft** [comment] 2017-01-25 18:02
Duplicate reosurce warning was already fixed https://github.com/dotnet/corefx/pull/15433/

**Comment by tarekgh** [comment] 2017-01-25 21:18
The Process issue is very interesting. I was able to repro it first time I setup the machine and I was seeing the calculation of the process start time was wrong because the boot time was not right. it was shifted by around 30 minutes or so. 

https://github.com/dotnet/corefx/blob/9a39684c851c14bd8190cfa21bdda41b3762a5c5/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L417

I came today and had to reboot the machine and everything is working fine now and I cannot repro it any more. and the boot time was calculated right.

@Priya91 

Is it safe to assume 

```C#
TimeSpan.FromSeconds(Stopwatch.GetTimestamp() / (double)Stopwatch.Frequency)
```

will always give us the time since booting? I am not sure if this is reliable. could you please have a look at that?

@yaakov-h could you please try to reboot your machine and find out if the Process test still failing?

**Comment by tarekgh** [comment] 2017-01-25 21:40
I am able to repro it again. will continue taking look.

**Comment by Priya91** [comment] 2017-01-25 22:21
Synced with @tarekgh offline. We guess it's most probably the issue with assuming that the time units from OSX API is in nano seconds [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs#L58), as we couldn't find clear documentation on the OSX API. Requires investigation on the calculation.

**Comment by yaakov-h** [comment] 2017-01-26 01:52
@tarekgh The Process test passes immediately after boot, up to at least 117 minutes after boot.

FWIW I'm now running 10.12.3 (16D32).

There appears to be a harmless bug in `proc_pid_rusage` though - it's passing in `RUSAGE_SELF` rather than `RUSAGE_INFO_V3`, but as far as I can tell this gets interpreted as `RUSAGE_INFO_V0`, which just means that all fields starting with `ri_child_user_time` until the end of the struct won't be filled in.

The calculation does appear to correctly be in nanoseconds, which has me quite confused now. I've stepped through corefx and compared each value side-by-side with a C implementation, and can't see why this would fail.

One interesting thing I discovered with this C implementation (below) is that `clock_gettime()` returns a value earlier than that of `ri_proc_start_abstime` for the current process - at least initially - i.e. `Process.GetCurrentProcess().StartTime` can be greater than `DateTime.Now`.

**C implementation:** <details>

```
#include <stdio.h>
#include <time.h>
#include <libproc.h>
#include <assert.h>
#include <stdlib.h>
#include <unistd.h>

const int kSecondsToNanoseconds = 1000000000;

int main(int argc, const char * argv[])
{
	int pid;
	if (argc <= 1)
	{
		pid = getpid();
	}
	else
	{
		pid = atoi(argv[0]);
	}
	
	printf("PID to check: %d\n", pid);
	
	struct timespec ts;
	int result = clock_gettime(_CLOCK_MONOTONIC, &ts);
	assert(result == 0);
	
	long totalNanoseconds = (ts.tv_sec * kSecondsToNanoseconds) + ts.tv_nsec;
	
	printf("Time since boot (ns): %ld\n", totalNanoseconds);
	printf("Time since boot (s): %ld\n", totalNanoseconds / kSecondsToNanoseconds);
	printf("Time since boot (m): %ld\n", totalNanoseconds / kSecondsToNanoseconds / 60);
	
	struct rusage_info_v3 usage;
	result = proc_pid_rusage(pid, RUSAGE_SELF /* intentionally replicating corefx bug */, (rusage_info_t *)&usage);
	assert(result >= 0);
	
	uint64_t startTime = usage.ri_proc_start_abstime;
	printf("Process start time (ns): %llu\n", startTime);
	printf("Process start since boot (s): %llu\n", startTime / kSecondsToNanoseconds);
	printf("Process start since boot (m): %llu\n", startTime / kSecondsToNanoseconds / 60);
	
	int64_t timeDiff = totalNanoseconds - startTime;
	printf("Process started %lld ns ago.\n", timeDiff);
	printf("Process started %lld s ago.\n", timeDiff / kSecondsToNanoseconds);
	printf("Process started %lld m ago.\n", timeDiff / kSecondsToNanoseconds / 60);
	
	printf("ri_proc_start_abstime > clock_gettime(): %s\n", startTime > totalNanoseconds ? "YES" : "NO");

    return 0;
}
```

</details>

<br />

**C implementation sample output:** <details>

```
PID to check: 12793
Time since boot (ns): 6921116422000
Time since boot (s): 6921
Time since boot (m): 115
Process start time (ns): 6921294043963
Process start since boot (s): 6921
Process start since boot (m): 115
Process started -177621963 ns ago.
Process started 0 s ago.
Process started 0 m ago.
ri_proc_start_abstime > clock_gettime(): YES
```

</details>

**Comment by tarekgh** [comment] 2017-01-26 16:32
@yaakov-h

thanks for your investigation. I am still investigating the issue and already went through the steps you did. I have strong believe that in Sierra the value of ri_proc_start_abstime is not really in nanoseconds and looks in different units but I couldn't confirm that as I couldn't find any documentation talking about the time unit for ri_proc_start_abstime. 

regarding getting RUSAGE_INFO_V0 instead RUSAGE_INFO_V3, this is ok as we don't really care about the rest of the structure as we are interested only on  ri_proc_start_abstime.

I'll try to play more with the issue and hope to get some idea what is going on.

**Comment by tarekgh** [comment] 2017-01-28 21:08
@stephentoub @Priya91 I heard from @karelz that you are contacts for the non Windows networking issues. on Sierra, there are a couple of net tests are failing for the same reason. what is happening is we are calling gethostname() which will return the current local host name (something like ```Tarek-MacBook-Pro.local``` and then we try to get the host entry info by calling gethostbyname() and passing the local host name we got from gethostname(). gethostbyname() is failing with the error HOST_NOT_FOUND. 

I have tried to run ```getent hosts``` and it shows the only registered host is ```localhost```. in other Linux machines the command show the expected full local host name.

do you know if there is any configuration before running the tests to add the full local host name to the ns DB on the machine? 

I am going to mark this issue as System.Net as I have fixed the other listed issues.

CC @davidsh @CIPop just FYI

**Comment by karelz** [comment] 2017-01-29 00:50
cc @steveharter @ianhays

**Comment by tarekgh** [comment] 2017-01-29 22:53
sorry @karelz looks I mentioned wrong contacts

**Comment by karelz** [comment] 2017-01-30 06:16
@tarekgh nope, you did good. I just added whose who are helping us with our stability of Networking tests effort.

**Comment by Priya91** [comment] 2017-01-30 20:27
This is fixed with @tarekgh PR #15562 . Should we close this?

**Comment by karelz** [comment] 2017-01-30 20:30
I thought @tarekgh mentioned there is still something left -- this is a bit messy issue :(. We should carve out big/independent chunks into separate issues next time.

**Comment by tarekgh** [comment] 2017-01-30 20:45
we still need to fix the System.Net test failures. @Priya91 are you the right one to look at this issue?

**Comment by Priya91** [comment] 2017-01-30 21:57
The webproxy failure is logged here in this issue #13309

**Comment by Priya91** [comment] 2017-01-30 21:58
All the networking errors seems to be of same issue as #13309, host not found error is getting percolated as Device not found through .net wrapper. Requires more investigation, and can be tracked with the linked issue.

**Comment by tarekgh** [comment] 2017-01-30 22:04
@Priya91 if you think this is exactly the same issue you can close this issue.

**Comment by karelz** [comment] 2017-01-30 22:04
OK, anything left in this issue to track?

**Comment by tarekgh** [comment] 2017-01-30 22:06
No, System.Net failures is the last we had in this issue.

**Comment by Priya91** [comment] 2017-02-16 00:10
Closing issue as all networking errors are tracked.

**Closed by Priya91** 2017-02-16 00:10 UTC
Labels: bug, os-mac-os-x, untriaged
