### ISSUE TITLE
InterpreterTests.CompileInterpretCrossCheck_OrAssign failed in CI on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5662] opened 2016-01-25 04:00 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst/272/console
```
18:30:18    System.Linq.Expressions.Tests.InterpreterTests.CompileInterpretCrossCheck_OrAssign [FAIL]
18:30:18       System.NullReferenceException : Object reference not set to an instance of an object.
18:30:18       Stack Trace:
18:30:18             at System.Linq.Expressions.Tests.InterpreterTests.Verify(Expression expr)
18:30:18             at System.Linq.Expressions.Tests.InterpreterTests.CompileInterpretCrossCheck_OrAssign()
```
cc: @bartdesmet, @VSadov

**Comment by bartdesmet** [comment] 2016-01-25 04:51
Interesting... Looks like it may be failing in InterpreterTests.cs within the error handler:

```
catch (Exception ex) 
{ 
    throw new Exception(string.Format("Error for expression '{0}':\r\n\r\n{1}", typeof(Expression).GetType().GetProperty("DebugView").GetValue(expr), ex.ToString())); 
} 
```

Change https://github.com/dotnet/corefx/commit/183eb5ccf4240ad93495945c58b12428ca275195 made `DebugView` private, so the `GetProperty` call here will return `null`. However, this would simply be masking a real error in the interpreter and/or compiler.

Is this error occurring consistently in CI now? Upon quick inspection I'm not seeing recent changes in the code that could account for this regression.

**Comment by JonHanna** [comment] 2016-01-25 10:07
I found that when looking at #5512 and included https://github.com/dotnet/corefx/pull/5512/files#diff-129967b14f65299aa45c0b478157ad38R102 to deal with it, but forgot to call it out when I came to submit it.

**Comment by stephentoub** [comment] 2016-01-25 13:19
> Is this error occurring consistently in CI now?

No, I've only seen it this once.

**Comment by JonHanna** [comment] 2016-01-25 13:44
If we pull in the change in #5512 it would at least mean that the real exception got reported rather than get masked there. If we aren't going to decide on #5512 soon, should we just have that fix to the test made?

**Comment by bartdesmet** [comment] 2016-01-25 15:17
I'd suggest to fix the error reporting in the test code for sure. We may need to run the tests in a loop or under stress to repro the issue if it is non-deterministic.

**Comment by VSadov** [comment] 2016-01-25 19:02
I have accepted https://github.com/dotnet/corefx/pull/5512 , it seems to be mostly the same as https://github.com/dotnet/corefx/pull/4157

We should see more informative exception now if this reproduces.

**Comment by VSadov** [comment] 2016-01-25 19:05
Since it is Mac only, it could be a JIT issue. If the reason is something like uninitialized memory access, it may take a while for this to reproduce and may not be so easy to force it.
Let's hope it is something more deterministic.

**Comment by VSadov** [comment] 2016-01-26 22:54
The actual NRE is a test bug and should be fixed by the https://github.com/dotnet/corefx/pull/5512  

The underlying reason for the failure may still be there, but would be very hard to trace to without additional information. It could be possible the reasons for the failure were external - OOM or smth like that. 
I will close this until we have more data.

**Closed by VSadov** 2016-01-26 22:54 UTC
Labels: System.Linq.Expressions
