### ISSUE TITLE
FileSystemWatcher_Changed_Negative failed on OS X in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4830] opened 2015-12-04 17:33 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/21/console
```
09:19:28    ChangedTests.FileSystemWatcher_Changed_Negative [FAIL]
09:19:28       Should not observe a changed event within 500ms
09:19:28       Expected: False
09:19:28       Actual:   True
09:19:28       Stack Trace:
09:19:28             at Utility.ExpectNoEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
09:19:28             at ChangedTests.FileSystemWatcher_Changed_Negative()
```

**Comment by stephentoub** [comment] 2015-12-04 17:38
Also failed here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/22/console

**Comment by sokket** [comment] 2015-12-04 19:01
Will be fixed by #4781

**Comment by stephentoub** [comment] 2015-12-04 19:02
> Will be fixed

Great, but how so?  What's the problem?

**Comment by sokket** [comment] 2015-12-04 20:11
This issue and #4831 are caused by an underlying issue around FileSystem changes in OS X; file moves are done in CoreFX by linking and unlinking to cause a move, this generates hard links, which in turn cause a metadata change notification on the parent folder. Some other tests are disabled due to this (around nested folders) but these tests will pass since we are incorrectly sending change notifications on the root watch folder in OS X. There should be a separate discussion around notification smoothing here (#4839)

**Closed** 2015-12-04 21:16 UTC
Labels: X-Plat
