### ISSUE TITLE
Strange InvalidCastException of System.Text.Json for 3.0 preview7 only

### ISSUE THREAD

**Issue by iron9light** [dotnet/corefx#39770] opened 2019-07-25 16:08 UTC
https://github.com/aspnet/AspNetCore/issues/12569

### Describe the bug
```csharp
        [HttpGet]
        public ActionResult<IEnumerable<ValueB>> Get()
        {
            var valueAs = Enumerable.Range(0, 10).Select(x => new ValueA { Value = x }).ToList();
            return new ActionResult<IEnumerable<ValueB>>(valueAs.Select(x => new ValueB { Value = x.Value }));
        }
```
It will throw `InvalidCastException: Unable to cast object of type 'aspnetcorebug.Controllers.ValueB' to type 'aspnetcorebug.Controllers.ValueA'.`
by `System.Text.Json.JsonPropertyInfoNotNullable<TClass, TDeclaredProperty, TRuntimeProperty, TConverter>.OnWrite(ref WriteStackFrame current, Utf8JsonWriter writer)`

### To Reproduce
Sample code:
https://github.com/iron9light/aspnetcore_issue12569
clone and run
browse to http://localhost:port/api/Values

### Expected behavior
It should return serialized json list.
It works with preview6 and works with NewtonsoftJson.

### Additional context
Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450
```

**Comment by ericstj** [comment] 2019-07-25 17:31
@layomia it looks like this may have been addressed in https://github.com/dotnet/corefx/commit/6005a1ed7772772e211a962141cb17dfc4e26539.  I couldn't tell if this intentionally fixed the cast or just resulted in a different codepath being hit.  Can you take a look?

**Comment by ericstj** [comment] 2019-08-19 16:17
Lets add a regression test for this case.

**Comment by layomia** [comment] 2019-08-22 18:25
Adding a regression test for this in https://github.com/dotnet/corefx/pull/40510 which will close this issue. 
Serialization of `IEnumerable<ValueB>` should have worked fine in preview 7, given correct invocation of the serialize methods. I ran the regression test in ae79f49a7aa96cc6a8be59bb09b2246150587392 (the commit before https://github.com/dotnet/corefx/commit/6005a1ed7772772e211a962141cb17dfc4e26539) and it worked as expected.
Perhaps ASP.Net Core was [passing](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs#L80-L81) in the wrong object type at some point.

**Closed** 2019-08-22 19:54 UTC
Labels: area-System.Text.Json, test enhancement
