### ISSUE TITLE
PostLongerContentLengths_UsesChunkedSemantics failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8496] opened 2016-05-13 10:45 UTC
"The handle is invalid"
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/304/consoleText
```
System.Net.Http.Functional.Tests.PostScenarioTest.PostLongerContentLengths_UsesChunkedSemantics(contentLength: 64512) [FAIL]
        System.Net.Http.HttpRequestException : Error while copying content to a stream.
        ---- System.IO.IOException : The read operation failed, see inner exception.
        -------- System.Net.Http.WinHttpException : The handle is invalid
        Stack Trace:
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\src\System\Net\Http\HttpContent.cs(365,0): at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__50.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(171,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostHelper>d__22.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\tests\FunctionalTests\PostScenarioTest.cs(123,0): at System.Net.Http.Functional.Tests.PostScenarioTest.<PostLongerContentLengths_UsesChunkedSemantics>d__18.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\src\System\Net\Http\StreamToStreamCopy.cs(171,0): at System.Net.Http.StreamToStreamCopy.<CopyAsyncToPreSizedLimitMemoryStream>d__2.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Http\src\System\Net\Http\HttpContent.cs(358,0): at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__50.MoveNext()
           ----- Inner Stack Trace -----
```

**Comment by davidsh** [comment] 2016-05-26 19:24
Moving post RTM.

**Comment by davidsh** [comment] 2016-06-17 16:37
Closing this since it is a dupe of the root issue in #9228

**Closed by davidsh** 2016-06-17 16:37 UTC
Labels: System.Net
