### ISSUE TITLE
ConditionalFact/ConditionalTheory tests are skipped with` netfx

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#18483] opened 2017-04-17 13:03 UTC
Following test fails with `msbuild /T:BuildAndTest` but passes with `msbuild /T:BuildAndTest /P:TargetGroup=netfx`. The test isn't being run.

```cs
public static bool AlwaysTrue { get; } = true;

[ConditionalFact(nameof(AlwaysTrue))]
public void Test()
{
    Assert.False(true);
}
```

**Comment by stephentoub** [comment] 2017-04-17 13:18
@safern, you were investigating / working on fix this, right?

**Comment by safern** [comment] 2017-04-17 17:52
That is correct, I'm currently investigating why this is happening. Thanks for assigning it to me.

**Comment by hughbe** [comment] 2017-05-16 00:58
@safern were you looking into this? I ask as HttpListener has a bunch of tests that aren't running on netfx right now so it's harder to say with confidence there are no regressions.

**Comment by safern** [comment] 2017-05-16 01:00
> @safern were you looking into this? I ask as HttpListener has a bunch of tests that aren't running on netfx right now so it's harder to say with confidence there are no regressions.

I haven't looked deep into this as we had higher priorities, but I can take a look at this in the few next days.

**Comment by safern** [comment] 2017-05-19 00:44
@hughbe just FYI: the issue is detailed here: https://github.com/xunit/xunit/issues/1291 and submitted a fix in here: https://github.com/xunit/xunit/pull/1292

**Closed** 2017-05-24 02:39 UTC
Labels: area-Infrastructure, test bug
