### ISSUE TITLE
XPathNavigable.PrependChild/AppendChild not working for netcoreapp2.0

### ISSUE THREAD

**Issue by harshjain2** [dotnet/corefx#24913] opened 2017-10-27 08:21 UTC
## Description
XPathNavigable.AppendChild and XPathNavigable.PrependChild are not behaving as expected for netcoreapp2.0 when the logic is present in ClassLibrary targetting netstandard1.4
[ConsoleApp7.zip](https://github.com/dotnet/corefx/files/1421267/ConsoleApp7.zip)

## Repro Steps 
1. Unzip the attached project and open ConsoleApp7.sln
2. Run ConsoleApp7 project. ConsoleApp7 project refers ClassLibrary1 which as the logic to create xml file.
3. You will get this output
```xml
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors />
  </DataCollectionRunSettings>
</RunSettings>
```

4. Run ConsoleApp1 project. ConsoleApp1 project has the same code that is present in ClassLibrary1. 
5. You will get this output
```xml
<RunSettings>
  <MSTest>
    <SettingsFile>C:\temp\r.testsettings</SettingsFile>
    <ForcedLegacyMode>true</ForcedLegacyMode>
  </MSTest>
  <DataCollectionRunSettings>
    <DataCollectors />
  </DataCollectionRunSettings>
</RunSettings>
```

## Observation
If you notice, there is a difference in the output of ConsoleApp7 and ConsoleApp1, even though same code is used.
`navigator.PrependChild(settingsNode);`, PrependChild is not behaving as expected and is not appending setttingsNode.

cc:@codito

**Comment by danmosemsft** [comment] 2017-10-27 19:03
@krwq may have an idea why this is.

**Comment by krwq** [comment] 2017-11-07 23:14
@harshjain2, currently the solutions which should workaround your problem are:
- update ClassLibrary1 to use netstandard2.0
- do not use System.Xml.XPath.XmlDocument's extension methods in ClassLibrary1

Problem is caused by ClassLibrary1 depending on System.Xml.XPath.XmlDocument which does not ship in netstandard2.0 and does not provide type forwards (S.X.XPath.XmlDocument implements extension methods which exist as instance members in System.Private.Xml in ns2.0 which makes System.Xml.XPath.XmlDocument incompatible with ns2.0)

For more details please refer to following threads which removed System.Xml.XPath.XmlDocument:
https://github.com/dotnet/corefx/pull/18368
https://github.com/dotnet/corefx/issues/17190

I'll close this issue since I do not believe we will be able to provide any better solution for this at this moment. If you strongly believe we should fix this we can start conversation about this and we can review if we can figure out some better solution.

**Closed by krwq** 2017-11-07 23:14 UTC
Labels: area-System.Xml
