### ISSUE TITLE
Overflow behavior of double.Parse changed in .Net Core 3.0

### ISSUE THREAD

**Issue by CornedBee** [dotnet/corefx#36446] opened 2019-03-28 13:32 UTC
Consider this program:

```c#
var invariant = CultureInfo.InvariantCulture;
Console.WriteLine(double.Parse(double.MaxValue.ToString(invariant), NumberStyles.Float, invariant));
```

In .Net Core <= 2.2 as well as .Net Framework, this throws `OverflowException`.

In .Net Core 3.0 Preview it returns `double.PositiveInfinity`.

This seems to be a rather significant change, but so far I haven't seen it called out at all. The preview documentation of Double.Parse has not yet been updated. (Also, the documentation of TryParse claims that it throws, which was never correct.) The [most relevant blog post](https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/) does not call out the change.

The only mention of this change is [in a few review comments on the PR](https://github.com/dotnet/coreclr/pull/20707#pullrequestreview-170443963). The PR does not link to any follow-up issues to update the documentation and the change list for the release announcement.

I think the correct resolution of this issue is one of communication rather than reverting to the old behavior, but I want to make sure this is not forgotten.

**Comment by tannergooding** [comment] 2019-03-28 19:52
Sorry, I could have done a better job of calling out the changes around both overflow and negative zero handling.

This change is by design and according to the IEEE specification. I do agree we need to update the documentation to call this out.

The issue should likely be opened against the https://github.com/dotnet/dotnet-api-docs repo, however.

**Comment by danmosemsft** [comment] 2019-05-30 19:16
@tannergooding can you please move this to the docs repo if that is the next step and close this out?

**Comment by tannergooding** [comment] 2019-05-30 19:24
Opened.

**Closed by tannergooding** 2019-05-30 19:24 UTC
Labels: area-System.Numerics, documentation
