### ISSUE TITLE
Xml schema validation does not fail on trailing line-feed

### ISSUE THREAD

**Issue by justindrocco** [dotnet/corefx#33949] opened 2018-12-10 06:58 UTC
Using the XmlReader, I'm performing schema validation on XML elements who's datatype does not allow line-feeds.  If the value contains a line-feed at the beginning or anywhere before the end of the string, schema validation fails as expected.  If the value ends with space before the line-feed, it fails schema.  Only when the line-feed is at the end of the string does the schema validation not fail.  I believe that it should fail.

Here is an example schema:

```XML
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="StringContent" type="an" />
  <xs:simpleType name="an">
    <xs:restriction base="xs:string">
      <xs:pattern value="[ !-~]*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema> 
```
Here is example code:

```C#
var xmlSchemaSet = new XmlSchemaSet();
xmlSchemaSet.Add(XmlSchema.Read(new StringReader(schema),  
        (sender, args) => { Console.WriteLine(args.Exception.Message); }));

var xmlReaderSettings = new XmlReaderSettings
{
    ValidationType = ValidationType.Schema,
    Schemas = xmlSchemaSet
};

xmlReaderSettings.ValidationEventHandler += 
        delegate (object sender, ValidationEventArgs args)
             {
                Console.WriteLine($"{description}: {args.Exception.Message}"); 
             };

var xmlDateReader = XmlReader.Create(
    new StringReader("<StringContent>some string content\n</StringContent>"), xmlReaderSettings);

while (xmlDateReader.Read()) { } 
```

I've attached a set of unit test that demonstrates the problem.  

[TrailingLineFeed.zip](https://github.com/dotnet/corefx/files/2661856/TrailingLineFeed.zip)

**Comment by krwq** [comment] 2019-02-06 17:05
@justindrocco thanks for offering help! Before we can fix this we need to make sure the proposed behavior is conforming xml and regex spec.

Just to clarify `*` accepts from 0 to any number of characters and your regex pattern does not have start or end anchors (`^` and `$`) which means that it technically should never fail since the empty sequence always matches

**Comment by buyaa-n** [comment] 2019-02-07 19:56
[XML Schema specification](https://www.w3.org/TR/xmlschema11-2/#rf-pattern) saying `·pattern· provides for: `

> Constraining a ·value space· to values that are denoted by ·literals· which match each of a set of ·regular expressions·. 
But it is not saying explicitly  which special character we should use for start and end of the input. 

Here [regular-expressions.info](https://www.regular-expressions.info/xml.html) site mentioned 

> Particularly noteworthy is the complete absence of anchors like the caret and dollar, word boundaries, and lookaround. XML schema always implicitly anchors the entire regular expression. The regex must match the whole element for the element to be considered valid. If you have the pattern regexp, the XML schema validator will apply it in the same way as say Perl, Java or .NET would do with the pattern **^regexp$**. 

So it seems to me using care and dollar sign for matching expression is by design, not seems we should change '$' to '\z'

**Comment by buyaa-n** [comment] 2019-02-20 21:33
@justindrocco do you agree with it is by design? can we close this issue?

**Comment by buyaa-n** [comment] 2019-02-20 21:34
Please let me know if we should reopen

**Closed by buyaa-n** 2019-02-20 21:33 UTC
Labels: area-System.Xml, bug

**Comment by justindrocco** [comment] 2019-02-21 02:06
I think that it should be reopened.  Sorry for going silent,  I have been working on a response as I have had time.  Below is that response.

### The Pattern and Regular Expressions
@krwq Your correct that the pattern I gave does not have start and end anchors. But as @buyaa-n found and is stated [here](https://www.w3.org/TR/xmlschema-2/#regexs), XML schema always implicitly anchors the entire regular expression.  So the pattern would behave as though it was "^[ !-~]*$".  Using that pattern and [Regex.Match](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.match?view=netcore-2.1); a value such as "abc\t" or "abc\r" would fail to match.  "\nabc" also fails, but "abc\n" does match.  This is by design.  If using \z instead of $ to anchor the pattern, then all for values fail to match.  Value "abc" matches for both patterns.  I don't think that there is anything wrong with the Regex implementation.  

Here is the documentation on MSDN for those anchors:
> '$' - [End of String or Line](https://docs.microsoft.com/en-us/dotnet/standard/base-types/anchors-in-regular-expressions#End) By default, the match must occur at the end of the string or before \n at the end of the string

> '\z'  [End of String](https://docs.microsoft.com/en-us/dotnet/standard/base-types/anchors-in-regular-expressions#EndOnly) The match must occur at the end of the string only.

The XML parser can and does normalize line endings, that is why I'm focused on the line-feed. Normalization of line endings is discussed: [End-of-Line Handling](https://www.w3.org/TR/2000/REC-xml-20001006#sec-line-ends) and
[Attribute-Value Normalization](https://www.w3.org/TR/2000/REC-xml-20001006#AVNormalize)

### Constraining the Value Space
I'll start with a premise, that the value space is all character data, including whitespace, that exists as the content of an element and that a pattern facet needs to match the whole value space.

The type used in the example is derived by restriction from the string datatype.  The string datatype represents a character string made up of characters that match the [Char production](https://www.w3.org/TR/2000/WD-xml-2e-20000814#NT-Char) as defined in the XML standard.  
> [Char](https://www.w3.org/TR/2000/WD-xml-2e-20000814#NT-Char)       ::=        #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF] 
 [Definition:]((string data type - https://www.w3.org/TR/xmlschema-2/#string))  The string datatype represents character strings in XML. The value space of string is the set of finite-length sequences of characters (as defined in [XML 1.0 (Second Edition)]) that match the Char production from [XML 1.0 (Second Edition)].  

The pattern facet used in the example then constrains the value space to chars ! through ~ and space (\x20)
> [Definition:](https://www.w3.org/TR/xmlschema-2/#rf-pattern)   pattern is a constraint on the value space of a datatype which is achieved by constraining the lexical space to literals which match a specific pattern. The value of pattern must be a ·regular expression.

The string datatype also defines the [whiteSpace](https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace) facet with the value of 'preserve' and is not changed in by the derived type.  Because whiteSpace is preserved, a trailing linefeed lies in the value-space that the pattern constraints.  

So, because, a trailing linefeed is apart of the value space it should not be ignored. But because that pattern is being anchored with '$' it is ignored and does not fail to match.  The pattern anchored with '\z' would result in the trailing linefeed not being ignored.

Below is the line that I think needs to change (assuming that I understand the code correctly :)): 
https://github.com/dotnet/corefx/blob/36167bc544b968ed0bd67915f6512043a07734e0/src/System.Private.Xml/src/System/Xml/Schema/FacetChecker.cs#L742

**Comment by buyaa-n** [comment] 2019-02-27 18:37
Thank you for digging into it @justindrocco, your point makes sense, but from another aspect it could impact out customers badly as the change you are requesting would fail validations which was passing before. What is your thoughts about customer impact about this change?
