### ISSUE TITLE
System.IO.FileSystem.Watcher.Tests - Tests passed but project failed?

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/corefx#1157] opened 2015-03-17 17:02 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/407/
--
Build #407 (Mar 16, 2015 11:22:23 AM)
PR #1133: Add System.Linq.Queryable S...
 
No changes.
 
GitHub pull request #1133 of commit 0f60d399123ce4b4f2ec4d4e242837a5899467f7 automatically merged.
 
Test Result (no failures)
 
Identified problems
	Subproject build: dotnet_corefx_windows_debug_prtest (#402)

	No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
--

On the page at :
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/402/console
It shows:
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00017\lib\tests.targets(68,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.IO.FileSystem.Watcher.Tests.dll  -xml .\testResults.xml -notrait category=failing " exited with code -1073741819. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\System.IO.FileSystem.Watcher.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00017\lib\tests.targets(74,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests' please check log for details! 
but it also shows:
=== TEST EXECUTION SUMMARY ===
     System.IO.FileSystem.Watcher.Tests  Total: 49, Errors: 0, Failed: 0, Skipped: 0, Time: 4.766s
so it seems like the file system watcher tests passed but then the file system watcher xunit process failed?

**Comment by ellismg** [comment] 2015-03-17 22:09
@FiveTimesTheFun or @mmitche Have you ever seen this before where the tests all pass but the targets think the process failed?

**Comment by mmitche** [comment] 2015-03-17 22:31
That's definitely an A/V in the process, not an issue with the target.  So it could have failed post-printing that message.

**Comment by mmitche** [comment] 2015-03-17 22:31
(and no :()

**Comment by stephentoub** [comment] 2015-03-25 06:13
This has happened several more times over the past few days, such as in http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug/217/console

**Comment by stephentoub** [comment] 2015-03-25 20:07
And again:
    http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/554/console
This issue is taking out PR CI builds not infrequently... we should really try to figure out the cause.

**Comment by ellismg** [comment] 2015-03-25 20:14
Has anyone tried running this locally in a loop and seeing if you can hit the same xunit failure?

**Comment by eatdrinksleepcode** [comment] 2015-03-25 20:20
I am not sure if it is the same issue, but in my local builds (on Win7) I have seen CoreCLR crash with a Watson dialog several times during FileSystemWatcher tests.

**Comment by mmitche** [comment] 2015-03-25 20:35
I haven't seen it yet locally.  The CI machines have Watson turned off.  Next time we see this i'll pull the machine immediately out of rotation and see whether running it over and over can reproduce the issue.

**Comment by stephentoub** [comment] 2015-07-15 15:18
We saw a brief spurt of this back in March, and then I don't believe we've seen it at all since.  For now I'm going to wrack it up to being a temporary issue and close this out.  We can reopen this if we see it again.

**Closed by stephentoub** 2015-07-15 15:18 UTC
