### ISSUE TITLE
CopyToOutputDirectory

### ISSUE THREAD

**Issue by ichensky** [dotnet/corefx#40532] opened 2019-08-23 11:37 UTC
1. Create solution with two  .net core projects "Pr1", "Pr2". 
2. Make "Pr1" as default solution project.
3. Add "Settings.cs" class with some code to the "Pr1". 
4. Add the same file "Settings.cs" but with another code to the "Pr2".
5. Add to the "Pr1", "Pr2" `.proj` files:

```xml
<ItemGroup>
    <Compile Update="Settings.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

```
6. Add reference of project "Pr2" to "Pr1".
7. Build project "Pr1"

Actual result: 
in /bin directory there is only one file "Settings.cs" from "Pr1"

Expected result: 
warring/error that file "Settings.cs" from "Pr2" was replaced with "Settings.cs" file from "Pr1"

**Comment by khellang** [comment] 2019-08-23 12:49
Duplicate of https://github.com/microsoft/msbuild/issues/989?

**Comment by tarekgh** [comment] 2019-08-23 18:29
This issue was moved to microsoft/msbuild#4654

**Closed by tarekgh** 2019-08-23 18:29 UTC
