### ISSUE TITLE
Test project debug command line arguments in VS are broken

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1148] opened 2015-03-16 13:52 UTC
The command-line arguments generated for .Tests projects in VS are incorrect, such that attempting to F5/ctrl-F5 a test project no longer successfully runs the tests for the project.

As an example, the command-line args generated for System.Threading.Tasks.Dataflow.dll are:
```
xunit.console.netcore.exe System.Threading.Tasks.Dataflow.Tests.dll  -xml .\testResults.xml -notrait category=failing {XunitTraitOptions} -wait
```
That ```{XunitTraitOptions}``` is causing the problem.

**Comment by weshaggard** [comment] 2015-03-16 16:45
This is a duplicate of https://github.com/dotnet/buildtools/issues/112 and with PR https://github.com/dotnet/buildtools/pull/115 fixing the issue. The next time I do a build tools package update the fix will be included.

**Comment by weshaggard** [comment] 2015-03-24 04:17
This has been fixed as the build tools that contains my fix has been integrated into corefx.

**Closed by weshaggard** 2015-03-24 04:17 UTC
