### ISSUE TITLE
Inconsistent System.Net.Http reference issue with .NET 4.6.2 and VS 15.7.5

### ISSUE THREAD

**Issue by thuannguy** [dotnet/corefx#31449] opened 2018-07-28 09:51 UTC
I have a big codebase that I need to update all outdated dependencies to their latest versions. Originally, I wanted to also upgrade all projects to .NET 4.7.2 because it is promised that the System.Net.Http problem is solved completely there. After getting some guides from https://github.com/dotnet/corefx/issues/29622, I was finally able compile and run my application, but ended up with another problem https://github.com/Microsoft/dotnet/issues/812 that doesn't seem to get any answer. Therefore, I made another attempt to upgrade but this time I keep my projects at .NET 4.6.2. After searching around, I found many suggestions that the right way to deal with the System.Net.Http nightmare in 4.6.2 is to reference from "framework" so that was exactly what I did. Except this time I ran into an inconsistent problem as follow.

Repo: https://github.com/thuannguy/ReproduceIssues/tree/master/Net462SystemNetHttp

Description:
- I have two projects.
- I used the "Add reference" to add reference to System.Net.Http
- After that, right clicked to check the paths, both of them point to _"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Net.Http.dll"_. However, when I checked content of the csproj files, I found

> Reference Include="System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL

in the Model.csproj file but found 

> &lt;Reference Include="System.Net.Http" /> in the WebStuff.csproj file.

- Compiled and got errors. Only the Model project gave that error while the WebStuff project compiled successfully: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'HttpClient' exists in both 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Model	D:\Freelancer\GitSource\thuannguy\ReproduceIssues\Net462SystemNetHttp\Model\Dummy2.cs	10	Active

And warning

> Severity	Code	Description	Project	File	Line	Suppression State
Warning		No way to resolve conflict between "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.	Model			

- Adding redirect bindings didn't help.
- If I edited Model.csproj manually to add 

> "&lt;Reference Include="System.Net.Http" />" 

to it, all projects compiled successfully. Right clicking to check its path revealed _"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Http.dll

Do you know what is the cause of this inconsistency? Is it because the other packages the Model project references to? What is the correct solution for this issue?

Thank you for reading 😃

**Comment by davidsh** [comment] 2018-07-28 14:34
cc: @ericstj

**Comment by davidsh** [comment] 2018-09-11 17:32
@joperezr is this expected behavior?  Is there an updated link that contains ways to solve this now?

**Comment by joperezr** [comment] 2018-09-18 15:42
Taking a look...

**Comment by joperezr** [comment] 2018-09-18 16:34
Not sure why the reference on your Model.csproj was added automatically like that, but I basically did two things in your project which fixed the issue. First I converted your dependencies from packages.config to PackageReference. I believe this step isn't absolutely required in order for your projcet to build succesfully, however it makes your projects faster and more reliable plus they will now be easily able to build on other computers without the need of carrying nuget.exe as you do today. The other thing I changed was that Reference in Model.csproj to look like the other project `<Reference Include="System.Net.Http" />` and then built the projects succesfully. Here are the changes I made to a fork of your repo: https://github.com/joperezr/ReproduceIssues/commit/c0113cdd17cc956e1b505657e5ac6df043bfdd24

**Comment by joperezr** [comment] 2018-09-18 16:36
Closing since I believe that my above response should resolve the issue. For the fact that the reference that was added automatically by visual studio, I believe that might be an issue with VS. Not sure where the right place to log that issue would be, but I would start with https://github.com/dotnet/sdk and perhaps they car re-route if needed.

**Closed by joperezr** 2018-09-18 16:36 UTC
Labels: area-System.Net.Http

**Comment by thuannguy** [comment] 2018-09-20 02:33
@joperezr  thank you for your response. I had to move on from that a leave with it for now, but when I have time again to look at it, I will try your fix 😄
