### ISSUE TITLE
ServerCertificateCustomValidationCallback throws PlatformNotSupportedException in CentOS.7-x64

### ISSUE THREAD

**Issue by deepumi** [dotnet/corefx#17045] opened 2017-03-13 13:13 UTC
As @bartonjs  suggested, I am creating a new issue for CentOS. #9728

When using ServerCertificateCustomValidationCallback in .Net Core 1.0.1 CentOS 7 64 bit Azure VM, I am getting the following error

```
System.PlatformNotSupportedException: The libcurl library in use (7.29.0) and its 
SSL backend ("NSS/3.19.1 Basic ECC") do not support custom handling of certificates. 
A libcurl built with OpenSSL is required.
 
 at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
   at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
   at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)


End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at hwapp.Program.<MakeWebRequest>d__1.MoveNext()

```

**Sample code**

```csharp
static void Main(string[] args)
{
   MakeWebRequest().GetAwaiter().GetResult();
   Console.WriteLine("Press any key to exit!");
   Console.ReadKey();
}

private static async Task MakeWebRequest()
{
   var handler = new HttpClientHandler()
   {
     AllowAutoRedirect = false,
     AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip 
   };
  
   handler.ServerCertificateCustomValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

  try
  {
     using (var client = new HttpClient(handler))
     {
        var result = await client.GetAsync("https://www.google.com");
	Console.WriteLine(result.StatusCode.ToString());
     }
  }
  catch (Exception exception)
  {
    Console.WriteLine(exception.ToString());
  }
}

```

**Comment by stephentoub** [comment] 2017-03-13 17:04
The exception message describes the cause and the limitation and suggests the workaround:
```
The libcurl library in use (7.29.0) and its 
SSL backend ("NSS/3.19.1 Basic ECC") do not support custom handling of certificates. 
A libcurl built with OpenSSL is required.
```
Custom handling of certificates, e.g. ServerCertificateCustomValidationCallback, requires interaction with System.Security.Cryptography.X509Certificates, which is based on OpenSSL.  Thus if libcurl is using a different SSL backend (in your case, NSS), this functionality won't work, because the certificate data won't be understood by the X509Certificates library.  The workaround is to switch which libcurl you're using to one that uses OpenSSL.

**Comment by karelz** [comment] 2017-03-13 17:36
Closing as by design - see answer above.

**Closed by karelz** 2017-03-13 17:36 UTC
Labels: area-System.Net.Http, os-linux, question

**Comment by deepumi** [comment] 2017-03-13 18:09
@stephentoub Do you have any documentation to deal the switch part.

>  The workaround is to switch which libcurl you're using to one that uses OpenSSL.

**Comment by deepumi** [comment] 2017-03-13 18:16
Similar issue with PowerShell #2511. This issue is still open.

**Comment by karelz** [comment] 2017-03-13 21:30
@Priya91 do oyu know if we have docs on that? If not, we should create issue to track adding it.

**Comment by deepumi** [comment] 2017-03-16 19:45
@Priya91 @stephentoub @karelz Thank you all. 

The issue has been resolved.
