### ISSUE TITLE
 HttpWebRequest/HttpClient with self-signed client certificate 

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/corefx#8165] opened 2016-04-29 07:58 UTC
Is there a way to do a HttpWebRequest/HttpClient request with a self signed client certificate that is _not_ trusted by the OS (i.e. not stored as trusted root)?

**Comment by nicolasr75** [comment] 2016-04-29 13:50
I was about to ask that too. #7623 describes a new ServerCertificateCustomValidationCallback on HttpClientHandler but I can't find it. Is this something we can use with rc2 at all?

**Comment by fubar-coder** [comment] 2016-04-29 13:54
@nicolasr75 This issue is about the certificate used for client authentication, not the server certificate.

**Comment by nicolasr75** [comment] 2016-04-29 13:58
@fubar-coder Sorry, overlooked that

**Comment by davidsh** [comment] 2016-04-29 13:59
`ServerCertificateCustomValidationCallback` is a new method for the upcoming 4.1.* System.Net.Http contract (HttpClient).  It is not part of HttpWebRequest (System.Net.Requests contract).

We are finalizing the 4.1 contract.  This work is not part of RC2.

In addition, there will methods for handling client certificates as well as part of System.Net.Http 4.1 contract.

**Comment by davidsh** [comment] 2016-04-29 16:27
Closing this now that the question has been answered.  Additional APIs for System.Net.Http are tracked by the issue referenced above.  You can also try out the pre-release version of System.Net.Http 4.1 by using the sources directly here in CoreFx or on the MYGET feed:
https://dotnet.myget.org/gallery/dotnet-core

**Closed by davidsh** 2016-04-29 16:27 UTC
Labels: question, System.Net

**Comment by fubar-coder** [comment] 2016-05-26 07:21
I just want to be sure: I can ensure that the HttpClient uses my own client certificate - even when Windows thinks that it's invalid when I use `ServerCertificateCustomValidationCallback`? This property suggests, that it's only for the server certificate validation?

The current behavior is, that when I use a self-signed client certificate, which Windows thinks it's invalid, then it doesn't get used by the HttpClient request - regardless of the value of `ClientCertificateOptions`.

**Comment by davidsh** [comment] 2016-05-31 20:11
>I just want to be sure: I can ensure that the HttpClient uses my own client certificate 

`ServerCertificateCustomValidationCallback` is only for server certificate validation.

Using client certificates that are untrusted by the client machine depends on whether or not a server has sent down a "Trusted Issuers" list to the client when requesting client certificates.  If so, then that list is used to filter out eligible client certificate to send to the server.  If the server doesn't send a "Trusted Issuers" list, then the trusted authorities on the client are used to filter down the eligibility list. FYI, by default latest versions of Windows Server no longer send the Trusted Issuers list down (but settable via registry key).

There is no standard mechanism for handling fully untrusted client certificates

**Comment by ElasticCoder** [comment] 2018-04-04 17:57
I've repeated the tests again today, this time running the emulator in a VM and the client on the host laptop.

### ServicePointManager doesn't work in .NET Core
The code below works if you compile as a normal .NET Console app, but fails if you compile it as a .NET Core app.  The `ServicePointManager` callback is not called and SSL verification fails. `ServicePointManager` does not work for .NET core apps.

```
using System;
namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            // This doesn't work in dotnet core
            System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, errors) =>
            {
                Console.WriteLine("Ignoring SSL verification");
                return true;
            };

            try
            {
                var client = new System.Net.Http.HttpClient();
                var response = client.GetAsync("https://myVMname:8081/_explorer/index.html").GetAwaiter().GetResult();
                Console.WriteLine(response.StatusCode);
            }
            catch (Exception e)
            {
                while (e != null)
                {
                    Console.WriteLine(e.Message);
                    e = e.InnerException;
                }
            }
        }
    }
}
```

### Importing the certificate doesn't help
I've followed [other peoples articles](https://stackoverflow.com/questions/46641624/azure-cosmos-db-emulator-on-local-network-throwing-security-error) by exporting the Self-Signed certificate from the emulator onto the client machine, but this doesn't work with .NET Core still. It still errors.
I can see the SSL certificate provides localhost and <machinename> as the subject alternative names, and have navigated using <machinename> but this does not help. If you use a browser to navigate to the Data Explorer it still warns that the certificate is presented by localhost. You can accept the warning on a browser and navigate to the page, but any code will error.

The bottom line is that we cannot use `ServicePointManager.ServerCertificateValidationCallback` to bypass self-signed certificate verification for the emulator running over the network.

### The problem
Why is bypassing the certificate verification on the emulator so important to us? We are building high-density change feed clients that subscribe to Cosmos DB. These are currently deployed as Cloud Services but this is an incredibly wasteful use of compute and our strategy is to move to Kubernetes and AKS. Net Core is our strategic choice. We want to run our clients in containers and for the developers they should use the local emulator. (The last time we used a real Cosmos resource for Acceptance testing as part of our CI/CD process we ran up a bill of $15,000 in a month, which is not ideal). If our developers cannot connect to the emulator from a container then we either can't move to Kubernetes or we have to adopt a different database technology. We want to use both (and I'm sure many others do too)!

### Suggested solution
We are using the .NET core version of Microsoft.Azure.DocumentDB.Core (version 1.9.1) and I can see that this uses System.Net.Http (version 4.1.0.0).
The DocumentClient constructs a HttpClient, so the constructor could accept a HttpClientHandler and therefore the HttpClientHandler.ServerCertificateCustomValidationCallback could be used to override SSL certificate verification.

Could the ConnectionPolicy class be extended to provide a [DisableSSLVerification ](https://github.com/Azure/azure-documentdb-node/blob/8a5f353cab484271ecd2cc6c6b22c0481eeec8f7/source/lib/documents.js#L281)property, to keep it similar with the Node SDK?

**Comment by karataliu** [comment] 2019-03-25 08:38
@davidsh 
I've tried 'ServerCertificateCustomValidationCallback' doesn't solve this case。

I've same question with @fubar-coder , the issue is for sending self-signed client cert. And it got ignored even ServerCertificateCustomValidationCallback set to always true.

Whether server trust client cert is another topic, here we mean 'HttpClient' refuse to send the client cert if it's self-signed.

Can we reopen this issue?

**Comment by davidsh** [comment] 2019-04-15 18:42
>Can we reopen this issue?

If you have a repro for this using the latest .NET Core, please open a new issue.  Please include enough details on the OS for the client and server and how we can run your repro to demonstrate the problem.

**Comment by karataliu** [comment] 2019-04-17 02:38
@davidsh  Thanks, should repro. I'll give a try.
