### ISSUE TITLE
Distributed transactions are not supported

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/corefx#16755] opened 2017-03-06 07:51 UTC
[ActiveIssue("Distributed transactions are not supported.")]

Test methods:
Vol0_Dur1_2PC()
Vol0_Dur2()
under: corefx\src\System.Transactions\tests\EnlistTest.cs

Details:
https://github.com/dotnet/corefx/blob/master/src/System.Transactions.Local/tests/EnlistTest.cs#L145
https://github.com/dotnet/corefx/blob/master/src/System.Transactions.Local/tests/EnlistTest.cs#L450

**Comment by danmosemsft** [comment] 2017-03-06 17:50
Known limitation - since we have some tests there, they are disabled against this tracking issue for potential future support.

**Comment by danmosemsft** [comment] 2017-03-06 19:05
Alternatively the tests can be deleted. I imagine if we added this feature we'd need more than 2 tests :)

**Comment by stephentoub** [comment] 2017-03-06 20:49
Already have https://github.com/dotnet/corefx/issues/13532 as well

**Comment by dmetzgar** [comment] 2017-03-09 18:58
Duplicate of #10353

**Comment by karelz** [comment] 2017-03-09 20:06
@dmetzgar did you update the tests to point to the new issue? If not, please reopen and make the change prior to closing -- otherwise our vendors will reopen it again in next sweep.

**Comment by dmetzgar** [comment] 2017-03-09 20:14
@karelz no I didn't realize they made a code change
@qizhanMS could you make that change?

**Comment by karelz** [comment] 2017-03-09 20:18
@dmetzgar FYI: it's the 'disabled-test' label which tracks that. I said it also in the offline email that it may be easier just to dupe the old issue against this one ...

**Comment by qizhanMS** [comment] 2017-03-16 16:15
@karelz I got confused on which issue number we should use in the code. Please specify. Also should we close some issues because #16755, #13532 and #10353 are same root cause.

**Comment by karelz** [comment] 2017-03-16 16:23
If you have duplicates, mark as as duplicates and close them.
The issue which is used in ActiveIssue on disabled tests has to be open. It is up to you if you want to go and update the attributes on tests, or make you life easier and keep open the issue which is disabled from ActiveIssue in tests.
Does it help?

Overall: No process, just common sense ;)

**Comment by qizhanMS** [comment] 2017-03-16 16:29
We now may have trouble because I updated the code and changed 16755 to 13532. Right now, should I change the code back to 16755, or add "disabled-test" label to 13532?

**Comment by karelz** [comment] 2017-03-16 16:31
I am lost what is what now.

Here are the rules of common sense:
1. Don't keep multiple issues tracking the same thing, resolve them as duplicates.
2. If a test is disabled (via ActiveIssue), the issue should be opened, not closed.

Does it help?

**Comment by evil-shrike** [comment] 2017-08-24 12:17
Apart from problems of issue tracking what are your plans for distributed tx support (System.Transactions) in netcore?

**Comment by dmetzgar** [comment] 2017-08-24 18:44
Distributed transaction support in Sys.Tx in the Framework depends on MSDTC. There is no equivalent transaction coordinator on other platforms. We left room in Core to create assemblies such as System.Transactions.Msdtc or System.Transactions.ElasticTransactions (for example) so that a transaction coordinator could be plugged in and a transaction could be promoted to use the available coordinator. No plans yet to build a MSDTC plugin since we haven't seen much demand.

**Comment by StephenBonikowsky** [comment] 2019-06-03 23:04
Closing, the tests remain disabled and can be enabled if distributed transactions become supported in Core.

**Closed by StephenBonikowsky** 2019-06-03 23:04 UTC
Labels: area-System.Transactions, disabled-test, enhancement
