### ISSUE TITLE
Establishing TLS secure channel fails when NewSessionTicket message received

### ISSUE THREAD

**Issue by aarondcoleman** [dotnet/corefx#3889] opened 2015-10-15 20:44 UTC
**Overview**
HttpWebRequest throws error a connection error when a TLS key on the server is changed. Specifically this is the implementation done by CloudFlare. Every hour, on the hour xx:00 a web service fronted by CloudFlare will throw the following exception on the first execution, but all subsequent ones succeed: 

*System.Net Error: 0 : [7328] Exception in HttpWebRequest#58000300::EndGetResponse - The request was aborted: Could not create SSL/TLS secure channel.*

**Sample**
Reproducible example here, but it needs to be running right before the hour (xx:59:59) through the following hour (xx:00:00) in order to observe the exception. We are using Fitbit.com as the example as this is fronted by the CloudFlaire service:

https://github.com/aarondcoleman/FitbitProxyTest

**Other Links**
* More info on how CloudFlare works: https://blog.cloudflare.com/tls-session-resumption-full-speed-and-secure/
* Forum thread on this issue: https://social.msdn.microsoft.com/Forums/vstudio/en-US/eb999cd4-b43b-4779-b01b-4a04017714e3/httpwebrequest-ssl-caching-bug-cloudflare-the-request-was-aborted-could-not-create-ssltls?forum=netfxbcl
* System.Net.Trace showing the occurence at the changeover of hour: https://github.com/aarondcoleman/FitbitProxyTest/blob/master/System.Net.Trace.Log

This is of high importance as our integration with the Fitbit API is affected. Every first call of the hour to the API fails per server node of our infrastructure.

**Comment by ericlaw1979** [comment] 2015-10-15 21:00
Verified on Windows 8.1 with all patches using the example scenario provided.

This looks like it *may* be a bug in the underlying SChannel `InitializeSecurityContext` function. The server returns a `NewSessionTicket` message (`0x04`) during the establishment of the new HTTPS connection (which was part of an existing HTTPS session with a cached SessionTicket). See https://github.com/aarondcoleman/FitbitProxyTest/blob/master/System.Net.Trace.Log#L6683

This `NewSessionTicket` message arriving at this time appears to cause SChannel to return `IllegalMessage` and fail the connection. .NET sees this result and performs a `RST` on the underlying TCP/IP connection.

![newsessionticket](https://cloud.githubusercontent.com/assets/4192774/10527163/a4d29724-7354-11e5-9230-0574f3a425ff.png)

![image](https://cloud.githubusercontent.com/assets/4192774/10527263/345417d8-7355-11e5-82db-ab784daeff85.png)

It's *remotely* possible that there's a bug in what CloudFlare is sending (e.g. in the ChangeCipherSpec message) but I think it's far more likely that there's a problem in the handling of the NewSessionTicket message at this point in the handshake. This message is relatively uncommon and .NET is historically known to be frail when it comes to unexpected alerts and messages during handshaking.

A Microsoft Message Analyzer Network capture of the failure can be found here: https://onedrive.live.com/redir?resid=D2FAD6A7909B0897!37926&authkey=!ANf4JrBtKlSP8EI&ithint=file%2cmatp

**Comment by stephentoub** [comment] 2015-10-15 21:14
cc: @davidsh, @cipop, @SidharthNabar, @bartonjs

**Comment by davidsh** [comment] 2015-10-15 21:17
Is this repro on CoreFx code or .NET Framework (desktop)?

**Comment by davidsh** [comment] 2015-10-15 21:18
I ask this question because the log entry cited above looks like something from a System.Net trace using .NET Framework (Desktop).

>System.Net Error: 0 : [7328] Exception in HttpWebRequest#58000300::EndGetResponse - The request was aborted: Could not create SSL/TLS secure channel.

**Comment by ericlaw1979** [comment] 2015-10-15 21:19
The log is from the .NET Framework on Windows. Is SslStream done differently on CoreFx?

**Comment by aarondcoleman** [comment] 2015-10-15 21:21
The trace was done on my local dev, but we run into this problem in production (Azure Websites) ASP.NET as well.

**Comment by davidsh** [comment] 2015-10-15 21:22
In terms of the HTTP stack, the implementation in CoreFx of the System.Net.Http and System.Net.HttpWebRequest API are TOTALLY DIFFERENT.  On CoreFx, the Http APIs on Windows are built directly on top of WinHTTP.  It does not use "SslStream" nor .NET managed Sockets.

The SslStream class in CoreFx, though, is built on managed .NET Sockets and would be essentially the same architecture using SCHANNEL api's.

But your repro here regarding use of Http APIs will probably NOT repro in CoreFx.

**Comment by ericlaw1979** [comment] 2015-10-15 21:25
Fair enough. My interest, of course, is for Fiddler, which is based on the SslStream class. And if the root cause of this is a problem in SChannel (as I suspect it may be) it would also repro in anything based on it (like WinHTTP/WinINET).

**Comment by aarondcoleman** [comment] 2015-10-15 21:59
@davidsh are you suggesting we file this elsewhere, or change the label?

**Comment by pencoyd** [comment] 2015-10-15 22:02
Paying attention at CloudFlare here. We'd love to see this addressed. Workarounds we've contemplated would reduce TLS performance notably.

**Comment by CIPop** [comment] 2015-10-15 22:18
@aarondcoleman, @ericlaw1979  It's not clear: can you repro this on CoreFX with either SslStream or the HTTP stack?

For Desktop, please report using https://connect.microsoft.com/.

**Comment by SidharthNabar** [comment] 2015-10-15 22:26
Yes - it would be very helpful if you can file this as a Connect issue since this repo does not cover components of the Windows OS such as Schannel, WinInet/WinHTTP, etc. Thanks!

**Comment by CIPop** [comment] 2015-10-15 22:30
@aarondcoleman @ericlaw1979 It would be useful to also collect the following Schannel traces for debugging purposes (note that the resulting log  _may contain private information_):

```
     logman start schannel_trace -p "{37D2C3CD-C5D4-4587-8531-4696C44244C8}" 0x4000ffff -o schannel.etl -ets -ln schannel
     Run the repro.
     logman stop schannel_trace –ets
```

**Comment by aarondcoleman** [comment] 2015-10-15 22:30
@CIPop so, Using System.Net.HttpClient on a sample ASP.NET website? I can certainly repro there, that's the main use case where we ran in to this.

@SidharthNabar as in, here? https://connect.microsoft.com/VisualStudio

**Comment by CIPop** [comment] 2015-10-15 22:35
> so, Using System.Net.HttpClient on a sample ASP.NET website? I can certainly repro there, that's the main use case where we ran in to this.

That should work.

**Comment by SidharthNabar** [comment] 2015-10-15 22:35
@aarondcoleman - Yes, that's the right Connect path.

**Comment by aarondcoleman** [comment] 2015-10-15 22:37
@CIPop and what kind of tracing / logging do you need?

**Comment by CIPop** [comment] 2015-10-15 22:47
> and what kind of tracing / logging do you need?

You'll need to follow the instructions in my previous message regarding Schannel tracing:

> @aarondcoleman @ericlaw1979 It would be useful to also collect the following Schannel traces for debugging purposes (note that the resulting log  _may contain private information_):

>```
     logman start schannel_trace -p "{37D2C3CD-C5D4-4587-8531-4696C44244C8}" 0x4000ffff -o schannel.etl -ets -ln schannel
     Run the repro.
     logman stop schannel_trace –ets
```

**Comment by ericlaw1979** [comment] 2015-10-15 23:15
@CIPop: Your "-ets" argument was corrupted by Word or something else that converts hypens to en-dashes.

After running the command in question, what file should be attached to the bug report filed (somewhere?) on CONNECT?

**Comment by aarondcoleman** [comment] 2015-10-15 23:24
I've started a CONNECT bug issue as well here: https://connect.microsoft.com/VisualStudio/feedback/details/1906395

I'm waiting for the hour changeover to capture the error.

**Comment by CIPop** [comment] 2015-10-15 23:25
> Your "-ets" argument was corrupted by Word or something else that converts hypens to en-dashes.

@ericlaw1979 Sorry about that. Updated the comments above. 

> After running the command in question, what file should be attached to the bug

The last command should generate a `schannel.etl` file in the working directory. Please compress and upload here or on the Connect bug.

@aarondcoleman Thanks for opening the Connect!

**Comment by aarondcoleman** [comment] 2015-10-16 00:17
@davidsh @CIPop @ericlaw1979  I can confirm that this issue exists on CoreFX.

Here's the simple test, ran before and after the hour when the TLS keys change (HomeController.cs -> Index):
https://github.com/aarondcoleman/FitbitProxyTest/blob/master/FitbitProxyASPNetCoreFxTest/Controllers/HomeController.cs

Same problem, exact same reproducibility where you can request https://www.fitbit.com using HttpClient right before the hour and then the first call right after the hour produces the same error:

`Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll`

```
An error occurred while sending the request. at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at FitbitProxyASPNetCoreFxTest.Controllers.HomeController.<Index>d__0.MoveNext() in C:\Repositories\FitbitProxyTest\FitbitProxyASPNetCoreFxTest\Controllers\HomeController.cs:line 24 
```
 
Also attaching that trace that was running before the hour, then after when the exception occurred here.
https://www.dropbox.com/sh/x9fsxjemuk07mt2/AAARKEeKaDXImvY63IBeLrwza?dl=0

Thanks.

**Comment by davidsh** [comment] 2015-10-16 13:59
This is probably an issue in the OS layer (Windows) with SCHANNEL. We are having the SCHANNEL team take an initial look at this since session tickets are generally supported in Windows.

**Comment by aarondcoleman** [comment] 2015-10-16 21:09
Thanks @davidsh. Please update us when we you something. You've got the attention of us at Fitabase, and the folks at Fitbit, CloudFlare, and @ericlaw1979 Fiddler/Telerik. Any guidance from that team as well on workarounds and/or what kinds of patch options would be helpful. I know our band-aid code around this would change if this was a "months, not days" scenario.

**Comment by davidsh** [comment] 2015-10-16 21:18
The SCHANNEL team has investigated the issue and confirmed that a fix will be needed in that component to address this issue. I don't have a timeline yet for a fix. Further communication on this issue will be done via the Connect site.

**Comment by prdonahue** [comment] 2015-10-16 22:49
CloudFlare PM here for TLS. Chiming in now to provide an update on our planned workaround.

First off, glad to hear that Microsoft has confirmed that this is an SChannel bug. We're looking forward to hearing about the timeline for the fix.

Ideally, would be able to detect (i.e., fingerprint) UAs with broken session ticket implementations and automatically disable for them, but doesn't seem to be practical -- or necessarily worth the complexity and effort. Am all hears, however, if someone can provide the exact ClientHello parameters that unambiguously identify versions of Windows with the issue.

Barring that unlikely scenario, we will be deploying our per-certificate workaround to an internal test environment, and vet it there for a few days with real traffic before pushing live to the edge. @ericlaw1979 has graciously offered his support in verifying our fix, so I will be contacting him as soon as we have a public facing test environment. Our hope is to have the workaround live and available for use sometime during the middle of next week, at which point customers will be able to request we disable for their zone(s).

If anything in the above plan changes (e.g., timing), I'll provide another update here.

**Comment by ericlaw1979** [comment] 2015-10-16 22:56
@prdonahue - FWIW, I would be VERY surprised if this doesn't repro on ALL Windows clients that support SessionTicket (e.g Win8+). 

In terms of fingerprinting, it's probably the case that Chrome and Firefox have distinct ClientHello parameters you could use to distinguish from SChannel, but that seems very hacky.

I assume you can't decrease the likelihood of problems by changing the ticket rollover to something more infrequent, since it sounds like the actual ticket lifetime is 18 hours?

**Comment by grimhellion** [comment] 2015-10-29 19:17
@prdonahue, any updates on your internal testing at Cloudflare? We've been dealing with this issue well over a year now and are excited you are nearing a workaround for this MS bug.  Please update.

**Comment by ericlaw1979** [comment] 2015-10-29 19:22
@grimhellion: To be clear, CloudFlare's workaround is to just disable SessionTicket support for customers who request they do so; this avoids the issue, but at a performance cost.

**Comment by prdonahue** [comment] 2015-10-29 19:25
Yes, as @ericlaw1979 said, we now have the ability to disable session tickets on a per-certificate basis. If you're a CloudFlare customer and want this disabled for your zone, please submit a ticket.

Unfortunately, the proper fix will require Microsoft patching SChannel. I'll be posting a blog with all the granular details, but unless someone can devise a better way to work around we'll be going with this simple fix.

**Comment by grimhellion** [comment] 2015-10-29 19:25
Thanks @ericlaw1979, so the actual fix is in @davidsh with Microsoft SCHANNEL team's court?

**Comment by prdonahue** [comment] 2015-10-29 19:27
Correct. We've been in communication with Microsoft (as has Eric). @davidsh may be able to provide an update on timing of the distribution of the actual fix?

**Comment by grimhellion** [comment] 2015-10-29 19:27
Thanks @prdonahue! Are we talking seconds or milliseconds in terms of performance degradation?

**Comment by prdonahue** [comment] 2015-10-29 19:29
@grimhellion please take a peek at https://blog.cloudflare.com/tls-session-resumption-full-speed-and-secure/. We did some performance testing on abbreviated session resumption and it's basically 50% as costly. Your actual performance depends on how many separate HTTPS requests need to be processed.

**Comment by grimhellion** [comment] 2015-10-29 19:44
Thanks all, ticket submitted to cloudflare for testing. Looking forward to update from MS on the real fix.

**Comment by grimhellion** [comment] 2015-10-29 20:34
Got response from Cloudflare. This workaround is only available for Business and higher customer domains. All of our domains are at the Pro level and they can't make a widespread change like this there. Looks like I'm stuck waiting for Microsoft on this one.

**Comment by prdonahue** [comment] 2015-10-29 20:42
Yes, due to our lazy loading logic, we can only apply this workaround at the certificate level. And at Pro (or Free), you share certificates with other users so making a change there would negatively effect other customers' performance.

With Business and up, we allow you to upload your own custom certificate which allocates dedicated IP addresses for it/you and thus allows us to apply certificate-specific settings. (Note that this same limitation applies for enabling insecure, long deprecated protocols such as SSLv3; allowing a non-dedicated certificate to enable would compromise the security of others on the same IP/certificate.)

**Comment by grimhellion** [comment] 2015-10-29 20:43
Makes sense... if only the jump from Pro to Business wasn't so steep... :)

**Comment by couellet** [comment] 2015-11-23 18:42
Any updates on a timeline for the fix from Microsoft? We are having a Worker Role on Azure that makes HTTP requests to Webhook endpoints of our customers. Whenever a customer is using a SSL from CloudFlare we get the issue described here.

Any ideas how the fix will be rolled out? Will it be automatically rolled out on Azure Cloud Services or we'll have an update to do?

**Comment by aarondcoleman** [comment] 2015-11-23 20:42
In our case, CloudFlare did work out a workaround on their end that required some work on their end & their customer's end. We got some indications from Microsoft that an official, OS-level patch in SCHANNEL would be a long ways out. Anecdotal, but my experience is that Azure VMs lag behind a bit, so if you're looking for a fix sooner than 6mo-1yr, all things combined (!!), you probably need to rally all parties involved. 

Or try{} catch{} in your codebase everywhere you hit that API. That didn't even always solve the issue for us and some delays lasted longer than 5-10 seconds before a successful call could be made, so it's a nasty bug for sure. The code below worked MOST of the time, and is provided without warranty 

```csharp
bool bHitTLSResetBug = false;
try{
    //do your api call
}
catch(HttpRequestException webEx) //catchint the SSL/TLS bug
{
    if (webEx.InnerException is WebException && ((WebException)webEx.InnerException).Status == WebExceptionStatus.SecureChannelFailure)
    {
        bHitTLSResetBug = true;
    }
    else
        throw webEx; //if this isn't the SSL/TLS bug, 
}

if (bHitTLSResetBug)
{
   //attempt to do your api call again
}

```

**Comment by couellet** [comment] 2015-11-24 00:38
Thanks! We will give it a try.

**Comment by SidharthNabar** [comment] 2015-11-24 17:17
@couellet - A quick update regd the Microsoft Windows fix: this fix will be on the client side of the TLS protocol, and will be included in a future Windows release. The team that owns this fix doesn't have a specific ETA yet, but Pat, Eric and I are working with them on it. Currently, it is not clear if this fix will also be ported to older Windows versions, and if so, when that will be available.

I would recommend using the try-catch workaround above for now since the timeline for the fix and for the fixed OS version to be available in Azure VMs will take us beyond Q1 2016 at least.

Thanks,
Sid

**Comment by couellet** [comment] 2015-11-24 22:39
Thanks guys,

I tried using `Polly` to retry automatically when the exception matches the criteras @aarondcoleman suggested. Here's the code:

```cs
var policy = Policy
    .Handle<HttpRequestException>(x =>
    {
        var inner = x.InnerException as WebException;

        return inner != null &&
               inner.Status == WebExceptionStatus.SecureChannelFailure;
    })
    .WaitAndRetryAsync(3, x => TimeSpan.FromSeconds(4));

var client = new HttpClient();

return await policy.ExecuteAsync(async () =>
{
    var request = new HttpRequestMessage(
        HttpMethod.Post,
        webhookRequest.RequestUrl)
    {
        Content = new ObjectContent(
            content.GetType(),
            content,
            GetJsonFormatter()),
    };

    var response = await client.SendAsync(request);

    var hookResponse = new WebhooksResponse<T>(response);
    var contentAsString = await response.Content.ReadAsStringAsync();

    RecordRequest(account, content, request, response, hookResponse, contentAsString, webhookRequest);

    if (!hookResponse.IsSuccessStatusCode)
        return hookResponse;

    if (hookResponse.ContentType == null ||
        hookResponse.ContentType.MediaType != "application/json")
        hookResponse.StatusCode = HttpStatusCode.BadRequest;
    else
        hookResponse.Content = await response.Content.ReadAsAsync<T>();

    return hookResponse;
});
```

It retries as expected but never works :/ We don't have a SSL certificate installed in the cloud service, could it be the problem?

**Comment by prdonahue** [comment] 2015-11-25 03:25
We'd love to fix this for all users, not just those that request disabling of TLS session tickets.

@SidharthNabar et al., is there any way we can unambiguously identify the defective SChannel implementation based on the ClientHello? If we could fingerprint that way, we could simply not issue RFC 5077 tickets (until the fix is widely distributed from Microsoft).

**Comment by yuhong** [comment] 2015-12-02 07:15
You probably want to flush the session cache using Reflection before retrying the failed API call.

**Comment by aarondcoleman** [comment] 2015-12-02 19:21
I suppose so. The try{}catch{} did not always succeed, even with a few seconds of thread delay, so a reflection flush might have been the missing piece but I wasn't comfortable stepping out in to reflection from managed code in our webserver production environment. 
--Aaron

**Comment by prdonahue** [comment] 2015-12-04 00:01
Stay tuned, we're working on a solution for all customers (that doesn't require a custom certificate). I'm optimistic based on early testing, but won't know for sure for another week or so. I'll be sure to update this bug once I've got better data and expected timing.

**Comment by yuhong** [comment] 2016-01-12 19:09
https://technet.microsoft.com/library/security/3109853.aspx

**Comment by grimhellion** [comment] 2016-01-14 20:58
Yes! Thanks @yuhong!

**Comment by SidharthNabar** [comment] 2016-01-22 19:26
Closing this since it has been resolved in the Windows OS layer: https://technet.microsoft.com/library/security/3109853.aspx

**Closed by SidharthNabar** 2016-01-22 19:26 UTC
Labels: bug, System.Net
