### ISSUE TITLE
CertificateValidationClientServer_EndToEnd_Ok if failing on Windows7

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8437] opened 2016-05-10 21:29 UTC
```
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable)\r\n---- Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout) at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at System.Net.Security.Tests.CertificateValidationClientServer.ServerSideRemoteClientCertificateValidation(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SslStream.UserCertValidationCallbackWrapper(String hostName, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback) at System.Net.Security.SslState.CompleteHandshake() at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

Has been failing consistently in past 3 builds.

**Comment by Priya91** [comment] 2016-05-10 21:35
@CIPop Can you please help triage this bug. Thanks!

**Comment by CIPop** [comment] 2016-05-10 21:58
Thanks @Priya91! 

> Has been failing consistently in past 3 builds.

@Priya91 Do you have information that this was passing before the last 3 builds? (Unfortunately we just got our on-prem test system up and running a few days ago in Win7 because of #8369.)

@stephentoub Could this be related to the latest test enhancements that use the local HTTP server?

```
 Starting:    System.Net.Security.Tests
     System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok(useClientSelectionCallback: False) [FAIL]
        System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
        Expected: RemoteCertificateChainErrors
        Actual:   RemoteCertificateNotAvailable)
        ---- Assert.Equal() Failure
        Expected: RemoteCertificateChainErrors
        Actual:   RemoteCertificateNotAvailable
        Stack Trace:
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
              at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
              at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           ----- Inner Stack Trace -----
              at System.Net.Security.Tests.CertificateValidationClientServer.ServerSideRemoteClientCertificateValidation(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
              at System.Net.Security.SslStream.UserCertValidationCallbackWrapper(String hostName, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
              at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback)
              at System.Net.Security.SslState.CompleteHandshake()
              at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
              at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
              at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
              at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
  Finished:    System.Net.Security.Tests
```

**Comment by stephentoub** [comment] 2016-05-10 22:00
> Could this be related to the latest test enhancements that use the local HTTP server?

No, I just merged that about five minutes ago.

**Comment by Priya91** [comment] 2016-05-10 22:09
> @Priya91 Do you have information that this was passing before the last 3 builds?

It is failing from [Build #23 (May 4, 2016 11:16:57 AM)] (http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/23/)

Could have been from earlier as well, and masked by buildtools failure before this build.

**Comment by CIPop** [comment] 2016-05-16 21:14
The test variant that is failing is the one with automatic certificate selection. If the client certificate is selected by the callback, the end to end test works on Win7.

```C#
        [Theory]
        [InlineData(false)] //Fails in Win7.
        [InlineData(true)]  //Works in Win7.
        public async Task CertificateValidationClientServer_EndToEnd_Ok(bool useClientSelectionCallback)
```

Win7:

```
Microsoft-System-Net-Security/CertsAfterFiltering	27224.723	CoreRun (6420)	ThreadID="4,792" FormattedMessage="Left with 1 client certificates to choose from." filteredCertsCount="1" secureChannelHash="40,535,505" 
Microsoft-System-Net-Security/CertsAfterFiltering	27534.128	CoreRun (6420)	ThreadID="4,552" FormattedMessage="Left with 0 client certificates to choose from." filteredCertsCount="0" secureChannelHash="40,535,505" 
```

Win10 Insider build:

```
Microsoft-System-Net-Security/CertsAfterFiltering	18674.433	CoreRun (35196)	ThreadID="52,076" FormattedMessage="Left with 1 client certificates to choose from." filteredCertsCount="1" secureChannelHash="40,535,505" TaskIndex="2292" 
Microsoft-System-Net-Security/CertsAfterFiltering	18818.856	CoreRun (35196)	ThreadID="51,572" FormattedMessage="Left with 1 client certificates to choose from." filteredCertsCount="1" secureChannelHash="40,535,505" TaskIndex="2305" 
```

I'm noticing the same behavior in Win7 Desktop .Net 4.6.

**Comment by CIPop** [comment] 2016-05-17 23:29
We have determined that this is by design in systems running Win8+:
https://technet.microsoft.com/en-us/library/hh831771.aspx#BKMK_Changes2012R2

I'm changing the test to detect Win7 and expect a client certificate only if the client certificate chain can be verified.

**Closed** 2016-05-19 03:42 UTC
Labels: 2 - In Progress, blocking-clean-ci, bug, System.Net
