### ISSUE TITLE
Utf8JsonWriter.WriteString do not honor escape=false

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/corefx#34958] opened 2019-01-30 18:50 UTC
When writing an unescaped value like "jwt+secevent", the `Utf8JsonWriter` is honoring the contract by not escaping the value, as illustrated in the following test:
```C#
        [Fact]
        public void JsonWriter_UnescapedValue()
        {
            var output = new FixedSizedBufferWriter(100);
            var jsonUtf8 = new Utf8JsonWriter(output);
            jsonUtf8.WriteStringValue("jwt+secevent", false);
            jsonUtf8.Flush();

            string actualStr = Encoding.UTF8.GetString(output.Formatted);
            Assert.Equal(@"""jwt+secevent""", actualStr); 
            // actualStr == "jwt+secevent"
        }
```
When writing an unescaped value, the `Utf8JsonWriter` is not honoring the contract by escaping the value:
```C#
        [Fact]
        public void JsonWriter_UnescapedProperty()
        {
            var output = new FixedSizedBufferWriter(100);
            var jsonUtf8 = new Utf8JsonWriter(output);
            jsonUtf8.WriteStartObject();
            jsonUtf8.WriteString("unescaped", "jwt+secevent", false);
            jsonUtf8.WriteEndObject();
            jsonUtf8.Flush();

            string actualStr = Encoding.UTF8.GetString(output.Formatted);
            Assert.Equal(@"{""unescaped"":""jwt+secevent""}", actualStr); 
            // actualStr == "{"unescaped":"jwt\u002bsecevent"}"
        }
```
In this test, the '+' character is escaped to '\u002b'.

The expected behavior is to have an unescaped string when it is a JSON value and a value of a JSON property.

**Comment by ycrumeyrolle** [comment] 2019-01-30 22:01
I haven't seen the comment:
        /// The value is always escaped
It is inconsistent to always escape a value from a property, but not from an array.

**Comment by ycrumeyrolle** [comment] 2019-01-30 22:11
In addition, I do not understand the reason that the '+' is escaped. Same remark for  '&', '<', '>' and '`'.
This characters are legit (I assume...)

**Comment by ahsonkhan** [comment] 2019-02-03 21:14
`WriteString(string propertyName, string value, bool escape)` <= the escape bool only applies to the property name, not to the value.

> The value is always escaped

Right. This is by design. Usually, property names are known/constant values, so the `bool escape` applies to the property name only, not to the value. We decided not to provide an additional `bool escapeValue` argument as it didn't seem useful for common uses and complicated the api surface.

> It is inconsistent to always escape a value from a property, but not from an array.

That's a good point. I don't know if there is a strong use case for writing unescaped string arrays, so for consistency, we should consider removing the escape argument on `WriteStringValue`. 

> In addition, I do not understand the reason that the '+' is escaped. Same remark for  '&', '<', '>' and '`'.
This characters are legit (I assume...)

These are common Html characters that need to be escaped since JSON can end up embedded within html web pages.

cc @GrabYourPitchforks

**Comment by stephentoub** [comment] 2019-02-04 15:59
> the escape bool only applies to the property name, not to the value.

Seems like the parameter should be renamed then to avoid any ambiguity? e.g. escape => escapeName

**Comment by ccnxpt** [comment] 2019-02-10 12:02
I just tried Utf8JsonWriter.WriteString(name, value, false), then

Original value = "春夏秋冬" (12bytes)
Escaped value = "\u6625\u590f\u79cb\u51ac" (24bytes)

Is this by design? Too long.

**Comment by steveharter** [comment] 2019-07-10 16:43
Closing this as https://github.com/dotnet/corefx/issues/37192 addresses this by passing a custom escaper to the writer.

**Closed by steveharter** 2019-07-10 16:43 UTC
Labels: area-System.Text.Json, json-functionality-doc

**Comment by taadis** [comment] 2019-09-27 07:02
it work!!!

``` csharp
object jsonObject = new { symbol = @"~`!@#$%^&*()_-+={}[]:;'<>,.?/ " };
string aJsonString = Newtonsoft.Json.JsonConvert.SerializeObject(value: jsonObject);
string bJsonString = System.Text.Json.JsonSerializer.Serialize(
     value: jsonObject,
     options: new System.Text.Json.JsonSerializerOptions
     { 
           Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
      });
Assert.AreEqual(expected: aJsonString, actual: bJsonString);
```
