### ISSUE TITLE
[x64] System.InvalidOperationException : Cannot process request because the process has exited.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/corefx#39004] opened 2019-06-17 01:20 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190615.1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestProcessorAffinity

**Failed tests:**
 System.Diagnostics.Tests.ProcessTests/TestProcessorAffinity 

**Log:**
```
System.InvalidOperationException : Cannot process request because the process (10611) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 343
   at System.Diagnostics.Process.EnsureState(State state) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 940
   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 536
   at System.Diagnostics.Tests.ProcessTests.TestProcessorAffinity() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 865
```

**Comment by CarolEidt** [comment] 2019-06-27 21:13
I was unable to reproduce the failure mentioned above, even in a debian-9 container.
I don't think it's worth attempting to reproduce this, but I do think it would be worthwhile to at least extend the timeout on the process creation.

**Comment by stephentoub** [comment] 2019-06-27 23:28
Should be addressed by https://github.com/dotnet/corefx/pull/39002.  If it's not, we can revisit.

**Closed by stephentoub** 2019-06-27 23:28 UTC
Labels: area-System.Diagnostics, area-System.Diagnostics.Process
