### ISSUE TITLE
Frequently hit app manifest error while trying to run tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#34455] opened 2019-01-09 03:34 UTC
Repro:
```
git clean -xdf
build.cmd
cd src\System.Collections\src
.. // edit any .cs file, just adding a space or something to make it dirty
dotnet msbuild
cd ..\tests
dotnet msbuild /t:rebuildandtest
```
produces:
```
  Error:
    An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:
      package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.1.3'
      path: 'runtimes/win-x64/native/apphost.exe'
```
and crashes.

cc: @ViktorHofer

**Comment by ViktorHofer** [comment] 2019-01-09 16:55
cc @ericstj @safern. I'm not sure yet what is causing the regression. @ahsonkhan told me that he is hitting this more frequently now.

**Comment by ViktorHofer** [comment] 2019-01-09 17:08
Unfortunately not reproing for me locally :(

**Comment by ericstj** [comment] 2019-01-09 18:05
I can repro.  It looks like something is rewriting the deps file in the testhost directory.  To workaround you can rerun dotnet msbuild src\dirs.proj /t:GenerateTestSharedFrameworkDepsFile.

I didn't catch what overwrote that deps file but I suspect its one of the depproj's.

**Comment by ViktorHofer** [comment] 2019-01-09 18:55
@ericstj could you please take a look as it repros for you?

**Comment by safern** [comment] 2019-01-09 19:55
I tried reproing this locally as well to try and help, but I haven't being able to repro it either.

**Comment by ahsonkhan** [comment] 2019-01-09 21:06
> @ahsonkhan told me that he is hitting this more frequently now.

For what it's worth, I see this issue every time I change sources and rebuild before running tests.

**Comment by ericstj** [comment] 2019-01-09 22:20
I was already in repro state, haven't yet "caught it in the act"

**Comment by ericstj** [comment] 2019-01-09 22:58
So taking a look at a the actual package runtime.win-x64.microsoft.netcore.app\2.1.3 it doesn't contain apphost.exe.  So it looks like this is some change made by a previous run of GenerateTestSharedFrameworkDepsFile then a delete.  I'll try @stephentoub's repro from clean state to see if I can see what's going on.

**Comment by ericstj** [comment] 2019-01-10 00:37
I am able to understand the repro now.  What's happening is that when building the runtime.depproj with the .dotnet SDK that is acquired into .dotnet folder the apphost.exe dependency gets binplaced into the testhost directory.  When you manually rebuild the source CSProj with dotnet (or even point at the acquired dotnet.exe without setting DOTNET_MULTILEVEL_LOOKUP=0) and you have a newer dotnet installed on your machine, you use that one and due to some change in the SDK (I suspect a change in a public target name) it isn't resolving the apphost.exe as a dependency and ends up deleting it as part of incremental clean.

**Comment by ericstj** [comment] 2019-01-10 01:13
Funny.  The latest SDK explicitly removes apphost.exe, which is why we're hitting this:
https://github.com/dotnet/sdk/commit/1936ebd7307cebd6c5d1d8d699b9844f73b8fb2c#diff-726c4af93875efa855c29e94f7c0b33eR506

We'll need to workaround that somehow.  We don't really use apphost.exe so perhaps just excluding it will be easiest.

**Comment by stephentoub** [comment] 2019-01-10 01:37
Thanks for tracking it down, @ericstj!

**Closed** 2019-01-10 19:53 UTC
Labels: area-Infrastructure
