### ISSUE TITLE
MongoDB driver is incompatible with preview4

### ISSUE THREAD

**Issue by godrose** [dotnet/corefx#37019] opened 2019-04-19 11:03 UTC
Repro steps:

1. Create a .NETCore 3.0-preview4 project
2. Install `MongoDB.Driver` latest stable package - 2.8.0
3. Add a class which represents mappable BSON document like so:
```
 public sealed class MongoUser
    {
        public ObjectId Id { get; set; }
        [BsonElement("Login")]
        public string Login { get; set; }
        [BsonElement("Password")]
        public string Password { get; set; }        
    }
```

4. Start MongoDB service to accept incoming connections
5. Instantiate a client with `new MongoClient("mongodb://localhost:27017")`
6. Call `_client.GetDatabase()`
7. Call `_database.GetCollection@<MongoUser@>("whatever")

Expected: It just works
Actual: It throw `TypeInitializationException`

Note: This works in the previous version - .NETCore Preview 3

**Comment by karelz** [comment] 2019-04-24 09:15
Duplicate of https://github.com/dotnet/core/issues/2611

**Closed by karelz** 2019-04-24 09:15 UTC
