### ISSUE TITLE
WinHttpHandler: cookies received on a 401 response are not added to the CookieContainer

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#26986] opened 2018-02-09 05:37 UTC
If the server sends a 401 auth challenge with a Set-Cookie header, the cookie is not added to the CookieContainer.

SocketsHttpHandler and CurlHandler handle this correctly.

**Comment by davidsh** [comment] 2018-02-09 20:54
Duplicate of #26722

**Closed by davidsh** 2018-02-09 20:54 UTC
Labels: area-System.Net.Http, bug
