### ISSUE TITLE
NuPkg Signing needs to pick up the packages to be signed from the artifacts directory

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#33264] opened 2018-11-06 01:38 UTC
@weshaggard is actively working to fix this presently.

Symptoms:  Builds will place (for example) their NuPkgs now into paths like : .```...\s\corefx\artifacts\packages``` but eng\Signing.props and other build files expect it in ```\s\corefx\bin\packages\Release```

As a result, builds are broken like this one:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2183905&view=logs

**Comment by weshaggard** [comment] 2018-11-06 01:40
I think the problem is slightly different where the packages are getting put into a different location now but I think that location might still be wrong. A first attempt to fix that was with https://github.com/dotnet/corefx/pull/33256 but that didn't appear to fix it so I'm taking another look.

**Comment by weshaggard** [comment] 2018-11-06 16:46
Fixed with https://github.com/dotnet/corefx/commit/d77cd27bd6542bc851153f64d9bf9cd02da89bd7

**Closed by weshaggard** 2018-11-06 16:46 UTC
