### ISSUE TITLE
Console.ReadLine(); cause process hung when execute dotnet core console app from PowerShell ISE

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/corefx#13708] opened 2016-11-16 05:38 UTC
```C#
using System;
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.Write("Enter>");
            var read = Console.ReadLine();
        }
    }
}
```
```JSON
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "runtimes": {
    "win7-x64": {}
  }
}
```

When execute the console app published by `dotnet publish` from PowerShell ISE, the process will hung and not able to finish readline, also privouse `Console.Write()` will not be print out.
![image](https://cloud.githubusercontent.com/assets/1750815/20335994/eb9edd74-ab94-11e6-8204-c11279e4c0a3.png)

**Comment by ianhays** [comment] 2016-11-18 23:25
I can repro this on ISE. The first time I ran the exe, it opened another window and immediately closed it.

I'd suggest raising this issue with the ISE devs as they'll have better context than we do. This works fine in a regular powershell window, so that makes me think the issue is in something ISE is doing with the exe.

**Closed by ianhays** 2016-11-18 23:25 UTC
Labels: area-System.Console
