### ISSUE TITLE
ReaderWriterLockSlim.AcquireWriterLock timing out does not wake up waiting readers

### ISSUE THREAD

**Issue by mormegil-cz** [dotnet/corefx#3364] opened 2015-09-22 12:39 UTC
The [documentation for `ReaderWriterLockSlim.TryEnterWriteLock`](https://msdn.microsoft.com/en-us/library/bb339812.aspx) states:

> While threads are blocked waiting to enter write mode, additional threads that try to enter read mode or upgradeable mode **block until all the threads waiting to enter write mode have either timed out or** entered write mode and then exited from it.

(emphasis mine). However, the implementation does not behave like the bolded part of the documentation states. Imagine the following scenario with three threads (_T1_, _T2_, _T3_):
1. _T1_ acquires a read lock.
2. _T2_ tries to acquire a write lock and blocks, waiting for a timeout (as _T1_ holds the lock).
3. _T3_ tries to acquire a read lock and blocks (because _T2_ is blocked waiting for the write lock, and per the documentation, this means all further readers are blocked until _T2_ times out).
4. _T2_’s timeout expires. Per the documentation, _T3_ should now wake up and acquire the read lock. However, this does not happen and _T3_ is blocked forever (or, until some other event, e.g. _T1_ releasing the read lock, causes the implementation to wake up waiting threads).

[Reproducible code for this scenario is available on StackOverflow](http://stackoverflow.com/a/32656459/304138), with some discussion.

AFAICT, this is a simple bug caused by the fact that `TryEnterWriteLock` blocks further attempts to acquire a read lock, but when leaving by timeout, it does not wake them up. Specifically, I’d guess the `ExitMyLock` call in [`ReaderWriterLockSlim’s WaitOnEvent`](https://github.com/dotnet/corefx/blob/master/src/System.Threading/src/System/Threading/ReaderWriterLockSlim.cs#L923) should have been `ExitAndWakeUpAppropriateWaiters`.

The same bug seems to exist for the non-slim `ReaderWriterLock`.

**Comment by kouvel** [comment] 2016-09-17 08:53
Fixed in ReaderWriterLockSlim, but reopening to fix in ReaderWriterLock after it is exposed by dotnet/corefx#11634

**Comment by kouvel** [comment] 2016-11-02 09:29
After going through ReaderWriterLock in detail, it looks like there is no easy way to fix this bug there. There are a whole bunch of races to consider, and possibly a new state would be necessary to prevent certain checked invariants from changing while releasing waiting readers. It's probably not worth the risk or effort. The issue is fixed in ReaderWriterLockSlim, closing this issue again.

**Closed by kouvel** 2016-11-02 09:29 UTC
Labels: area-System.Threading, netstandard2.0
