### ISSUE TITLE
TryGetAddrInfo_HostName_TryGetNameInfo test failing on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#10764] opened 2016-08-15 00:06 UTC
``` System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo [FAIL]
        Assert.Equal() Failure
        Expected: Success
        Actual:   HostNotFound
        Stack Trace:
              at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo()

```
```

**Comment by Priya91** [comment] 2017-02-21 23:16
Requires investigation.

**Comment by Priya91** [comment] 2017-02-28 23:17
This test passes on local osx.

This looks similar to GetHostEntryAsync calling into getaddrinfo not resolving the ipaddress for local host name. This looks like a dupe of #13309

**Comment by bartonjs** [comment] 2017-03-01 18:40
@Priya91 We just added a 10.12 machine to CI and this is failing: https://ci.dot.net/job/dotnet_corefx/job/dev_apple_crypto/job/osx10.12_debug_prtest/1/

**Comment by mmitche** [comment] 2017-03-01 19:15
@bartonjs Remote login is on in a non-Sierra machine, but not file sharing.  I am changing the sierra machine to see what happens if I make the settings identical.

**Comment by Jiayili1** [comment] 2017-03-03 01:51
This issue is repro on build [20170302.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170302.02/workItem/System.Net.NameResolution.Pal.Tests/wilogs)

No result generated. detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170302.02/workItem/System.Net.NameResolution.Pal.Tests/wilogs

Result:
~~~
2017-03-02 14:26:13,810: INFO: proc(54): run_and_log_output: Output: Discovering: System.Net.NameResolution.Pal.Tests
2017-03-02 14:26:13,946: INFO: proc(54): run_and_log_output: Output: Discovered:  System.Net.NameResolution.Pal.Tests
2017-03-02 14:26:13,993: INFO: proc(54): run_and_log_output: Output: Starting:    System.Net.NameResolution.Pal.Tests
2017-03-02 14:26:14,491: INFO: proc(54): run_and_log_output: Output:    System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo [FAIL]
2017-03-02 14:26:14,494: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-03-02 14:26:14,494: INFO: proc(54): run_and_log_output: Output:       Expected: Success
2017-03-02 14:26:14,494: INFO: proc(54): run_and_log_output: Output:       Actual:   HostNotFound
2017-03-02 14:26:16,288: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/0b18b372-c748-4a7c-ae8a-daa023d7e2af/Work/5ecaa543-de19-4282-a988-794ddb16e745/Unzip/RunTests.sh: line 83:  1784 Segmentation fault      (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
2017-03-02 14:26:16,288: INFO: proc(54): run_and_log_output: Output: command exited with ExitCode: 139
2017-03-02 14:26:16,288: INFO: proc(54): run_and_log_output: Output: command failed, trying to collect dumps
2017-03-02 14:26:16,290: INFO: proc(54): run_and_log_output: Output: corefile: core
2017-03-02 14:26:16,290: INFO: proc(54): run_and_log_output: Output: uploading core to dumpling service
2017-03-02 14:26:44,709: INFO: proc(54): run_and_log_output: Output: bind: Invalid command `enable-meta-key'.
~~~

**Comment by Priya91** [comment] 2017-03-03 19:28
@Jiayili1 That build might not have had the fix that went in the PR #16549. Checking the latest build [20170303.02](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170303.02), i dont see this failure. Hence closing the issue as resolved.

**Comment by Jiayili1** [comment] 2017-03-06 01:35
@Priya91 Checked this issue on build 20170304.02, this issue is not repro.

**Comment by Jiayili1** [comment] 2017-03-07 05:52
This issue is repro on build 20170307.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170307.01/workItem/System.Net.NameResolution.Pal.Tests/wilogs

**Comment by Priya91** [comment] 2017-03-08 01:33
@MattGal @karelz  This test was fixed, and the error hostnotfound should not be hit, as can be seen from source code [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs#L171). Can you confirm which version of the source is used in the 20170307.01 build? The stack strace from console doesn't have line numbers as well, so it's not clear if old source is used or if the previous assert failed.

Also there seems to have been a segmentation fault in runtests.sh, what does that mean?

```
/home/helixbot/dotnetbuild/work/0b18b372-c748-4a7c-ae8a-daa023d7e2af/Work/5ecaa543-de19-4282-a988-794ddb16e745/Unzip/RunTests.sh: line 83:  1784 Segmentation fault      (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

**Comment by MattGal** [comment] 2017-03-08 02:27
All the builds will be based on corefx at 1ac6bacd61c067cb96344cab41f4a1c636a97246 which should definitely be newer than your test fix.  You can see that by finding the build from Mission control or VSTS (in this case, say https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=600923) and clicking on the "Git checkout" step.

Just randomly guessing, but since all the other Linuxes passed, and this one SEGFAULT'ed while doing string operations, I suspect something went terribly wrong with the NameResolutionPal.TryGetNameInfo call such that 1) the string error was mis-terminated or otherwise super long and 2) doing stuff with this string later crashed the process.

**Closed** 2017-03-09 00:42 UTC
Labels: area-System.Net, bug, disabled-test, os-linux, os-mac-os-x, test-run-core, up for grabs
