### ISSUE TITLE
Environment.CommandLine does not work as expected.

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29335] opened 2018-04-25 21:56 UTC
_From @RabdPnguin on April 24, 2018 21:44_

Let's say I call a command with the following options:
cmd --option "--whatever"

Environment.CommandLine returns something different depending on whether it's a dotnet core app or full framework app.

4.7: "cmd.exe --option "--whatever""
core 2.0: "cmd.exe --option --whatever"

This presents a problem making it impossible (or at least difficult) to pass arguments that start with a hyphen to an option. Core should work just like the full framework. Return the unparsed args.

This also affects the dotnet core cli.

// [powershell] create a directory called "-o"
mkdir "-o" <-- notice this works in powershell which was built on the full framework/mono

dotnet new console -o -o
^ it will assume the 2nd -o is an option (which it should)
dotnet new console -o "-o"
^ it will strip the quotes and assume the 2nd -o is an option (which it shouldn't)

// speaking of the dotnet cli specifically...
dotnet new console -o:-o
dotnet new console -o:"-o"
^ the above two commands will create the console app in the current directory, NOT the "-o" directory.

dotnet new console -o=-o
dotnet new console -o="-o"
^ this actually works and will create the console app in the "-o" directory.

however, all the following should do the same thing.

dotnet new console -o "-o" //  command doesn't work
dotnet new console -o:"-o" // command works but creates the console app in wrong directory
dotnet new console -o="-o" // command works as expected

Why does : work differently than =?

_Copied from original issue: dotnet/coreclr#17761_

**Comment by RussKeldorph** [comment] 2018-04-25 21:56
@danmosemsft @karelz

**Comment by RussKeldorph** [comment] 2018-04-25 21:56
_From @karelz on April 24, 2018 22:24_

@RabdPnguin thanks for your report - it seems there are 2 issues mixed together here:

4.7 vs. Core 2.0 difference in `Environment.CommandLine`. Is the main problem of stripping quotes around --whatever option? Can you please file an issue with repro on https://github.com/dotnet/corefx repo?
I wonder if it was introduced for Linux-Windows compat on purpose, or if it is a bug.

.NET CLI uses argument parser which deals with : vs. =. The issue should be routed to CLI or core-setup repo. @steveharter can you advice which one?

**Comment by RabdPnguin** [comment] 2018-04-25 22:30
After being directed to the correct repo this may be a duplicate of "https://github.com/dotnet/corefx/issues/29014".

In which case the answer is: Windows works different than Linux. I can't do what I want (get exact string as entered at commandline with quotes) in a cross platform way. If this is the case, this ticket can be closed.

I created a new ticket for the cli discrepancy between : and =
https://github.com/dotnet/cli/issues/9144

**Comment by danmosemsft** [comment] 2018-04-25 22:35
@RabdPnguin yes, I think [this ](https://github.com/dotnet/corefx/issues/29014#issuecomment-380484617) answers your question. In Linux it is not available.

I'm going to close as you suggest. Thanks for the report.

**Closed by danmosemsft** 2018-04-25 22:35 UTC
