### ISSUE TITLE
[2.1] Redirect with location having an anchor fails in a HTTP 400 on some servers

### ISSUE THREAD

**Issue by PatrickHofman** [dotnet/corefx#34728] opened 2019-01-21 16:22 UTC
NOTE by @krwq: this is tracking 2.1 issue (currently unclear if we want to port the fix or what fix needs to be ported)

### Problem

I think we are hitting a bug when having a third party (OAuth authentication server) returning a HTTP 302 redirect with the location set to a URL having a anchor (`#`). The redirected request returns a HTTP 400.

### Test case

```c#
WebClient wc = new WebClient();
wc.DownloadString("http://corefx-net.cloudapp.net/Redirect.ashx?uri=%2FEcho.ashx#something");
```

I am not sure if this issue is the same as the following code, but it will at least give the exact same error message:

```c#
WebClient wc = new WebClient();
wc.DownloadString("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx%23something");
```

### Expected result

I expected that a request to `http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx%23something` would return in a redirect to `http://corefx-net.cloudapp.net/Echo.ashx#something` resulting in a HTTP 200.

### Details

The problem reproduces on .NET Core 2.2 and 2.1, but it doesn't on .NET Core 2.0 and below. The problem doesn't reproduce on .NET Framework 4.7.2 and 4.7.

Good to mention it concerns OAuth on Exact Online, a cloud accounting program, which support the Implicit Grant Flow of OAuth.

It reproduces as an error from Microsoft HTTPAPI (http.sys). Does not reproduce on AWS CloudFront hosted site as redirect URL.

**Comment by karelz** [comment] 2019-02-21 17:07
@PatrickHofman are you able to reproduce it on simple server redirect? Without OAuth involved?

**Comment by PatrickHofman** [comment] 2019-02-21 22:22
The test case provided doesn't use OAuth. So it isn't related to OAuth in particular, just to the redirect done frequently by the OAuth flow.

**Comment by PatrickHofman** [comment] 2019-02-21 22:25
@karelz Please let me know if I can do anything to help you reproduce this issue.

**Comment by karelz** [comment] 2019-02-22 04:33
@PatrickHofman can you give me code that I can copy paste into new project, run it and see the failure?

**Comment by PatrickHofman** [comment] 2019-02-22 06:49
@karelz See the test cases in my original post.

**Comment by karelz** [comment] 2019-02-22 18:02
@PatrickHofman are you able to reproduce the same problem  with `HttpClient`? `WebClient` is old ancient API for back compat only.

**Comment by PatrickHofman** [comment] 2019-02-22 18:13
@karelz We use `HttpWebRequest` and associated classes. We didn't test with other options. I am mobile now so I can't test now unfortunately.

**Comment by karelz** [comment] 2019-02-25 01:32
@PatrickHofman `HttpWebRequest` and friends (incl `WebClient`) are compat-only APIs. They don't have all functionality correctly built-in (some settings are ignored, the APIs are super-non-performant).
If there is strong feedback (large impact on key customers/workloads, or significant number of customers impacted), we may fix some of it to ease migration from .NET Framework to .NET Core, but the future for high-perf and new features is and will be `HttpClient`.

`HttpClient` is the main implementation. If things don't work there, we would fix it ASAP (other bugs and features in the space permitting of course).

**Comment by PatrickHofman** [comment] 2019-03-04 13:24
Sorry it took me some time. I was on leave for personal reasons.

The issue reproduces using HttpClient unfortunately. Both attempts in the code I used failed:

```
HttpClient hc = new HttpClient();
string s = await hc.GetStringAsync("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx%23something");
string s = await hc.GetStringAsync("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx#something");
```

**Comment by PatrickHofman** [comment] 2019-03-04 13:26
As noted, this problem does not reproduce on .NET Core 2.0, but does on 2.1 and 2.2.

**Comment by karelz** [comment] 2019-03-04 17:32
2.1 brought brand new implementation of Networking stack, so I am not shocked there are compat bugs ... we will take a look.
If it is blocking you, you can opt-out from SocketsHttpHandler in the meantime ...

**Comment by PatrickHofman** [comment] 2019-03-11 13:25
> If it is blocking you, you can opt-out from SocketsHttpHandler in the meantime ...

How @karelz?

**Comment by davidsh** [comment] 2019-03-11 13:50
>Will AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false); do?

Yes.

**Comment by krwq** [comment] 2019-05-23 17:08
Following works on 3.0:

```csharp
        [Fact]
        public async void Test()
        {
            HttpClient hc = new HttpClient();
            var result = await hc.GetAsync("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx%23something");
            Assert.Equal(HttpStatusCode.OK, result.StatusCode);

            Console.WriteLine(await hc.GetStringAsync("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx%23something"));
        }
```

output:

```
{"Method":"GET","Url":"/Echo.ashx","Headers": {
    "Host": "corefx-net.cloudapp.net"
  },
  "Cookies": {},
  "BodyContent": "",
  "BodyLength": 0,
  "SecureConnection": false,
  "ClientCertificatePresent": false,
  "ClientCertificate": null
}
```

has something changed between 2.1/3.0 around that?

**Comment by scalablecory** [comment] 2019-06-15 00:28
I'm unable to reproduce this in 3.0 with either `SocketsHttpHandler` or `WinHttpHandler`. Can you please see if this reproduces in 3.0 for you @PatrickHofman?

**Comment by PatrickHofman** [comment] 2019-06-17 08:32
> I'm unable to reproduce this in 3.0 with either `SocketsHttpHandler` or `WinHttpHandler`. Can you please see if this reproduces in 3.0 for you @PatrickHofman?

This indeed doesn't reproduce any more in .NET Core 3!

Since we are not ready to move to .NET Core 3 yet, what is the best action to take now?

**Comment by krwq** [comment] 2019-06-17 16:36
@PatrickHofman have you tried if System.Net.Http.UseSocketsHttpHandler workarounds the issue for you?

**Comment by PatrickHofman** [comment] 2019-06-19 07:38
@krwq Yes, that workarounds the issue for now. Thanks!

Also note this post on StackOverflow, which describes the same issue: https://stackoverflow.com/q/56662272/993547.

**Comment by davidsh** [comment] 2019-09-04 18:33
>This indeed doesn't reproduce any more in .NET Core 3!

Glad it's working in current .NET Core 3.0 builds!

>@krwq Yes, that workarounds the issue for now. Thanks!

Since the workarounds (disable SocketsHttpHandler) work for you, this would not qualify to meet the bar for servicing for release/2.1 branch. So, we will close this issue now.

**Closed by davidsh** 2019-09-04 18:33 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
