### ISSUE TITLE
ClientWebSocket client certificate not working with .NET Core

### ISSUE THREAD

**Issue by mvput** [dotnet/corefx#20191] opened 2017-05-23 17:21 UTC
Using the ClientWebSocket to establish a secure WebSocket connection with client certificates. The project is targeting `netcoreapp1.1`. With the following code, the `ConnectAsync` throws an exception: `WinHttpException: A certificate is required to complete client authentication`. When changing the TFM to `net461` the connection is successfully established. I removed the template id of the certificate for security reasons.

```csharp
ClientWebSocket client = new ClientWebSocket();

X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
var cert = store.Certificates.Find(X509FindType.FindByTemplateName, "<templateid>", true);

client.Options.ClientCertificates = new X509CertificateCollection();
client.Options.ClientCertificates.Add(cert[0]);
client.ConnectAsync(new Uri("wss://localhost:44301/path"), CancellationToken.None).Wait();
```

**Comment by davidsh** [comment] 2017-05-23 17:43
This is a known issue.  WebSocketOptions is not supported/implemented yet on .NET Core.

**Comment by davidsh** [comment] 2017-05-23 17:44
Dupe of #5120.

**Closed** 2017-05-23 17:44 UTC
Labels: area-System.Net

**Comment by pinchizzo** [comment] 2018-06-12 18:49
Is ir resolved?

**Comment by stephentoub** [comment] 2018-06-12 19:02
> Is it resolved?

Yes, in .NET Core 2.1 ClientCertificates should work.

**Comment by pinchizzo** [comment] 2018-06-12 19:31
So what am I doing wrong then? I get the same error as above when trying to create similar websocket request to visualization tool Qlik as in this Node.js example:

![image](https://user-images.githubusercontent.com/6654132/41312379-2f2dcecc-6e87-11e8-833b-39a282b2a4c3.png)

https://help.qlik.com/en-US/sense-developer/April2018/Subsystems/EngineAPI/Content/GettingStarted/connecting-to-engine-api.htm

Here is my code snippet:

var certificate = this.LoadQlikCertificate();
X509CertificateCollection certCollection = new X509CertificateCollection();
certCollection.Add(certificate);

ClientWebSocket ws = new ClientWebSocket();
ws.Options.ClientCertificates = certCollection;
ws.Options.SetRequestHeader("X-Qlik-User", "UserDirectory=internal; UserId=sa_engine");
await ws.ConnectAsync(new Uri(qlikRef.EngineApiUrl), CancellationToken.None);

Certificate should be ok as I use it in REST API without any problem. I'm using .NET Core 2.1. preview.

Many thanks.
Michal

**Comment by davidsh** [comment] 2018-06-12 19:46
>System.Net.Http.WinHttpException (80072F0C, 12044): A certificate is required to complete client authentication
at System.Net.WebSockets.WinHttpWebSocket.d__18.MoveNext()

This tells me that you aren't running against .NET Core 2.1.  WinHTTP is only used for WebSocket on .NET Core 2.0.

Please re-target your app to .NET Core 2.1.

**Comment by davidsh** [comment] 2018-06-12 19:48
Also, please try out the final .NET Core 2.1 release:
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by pinchizzo** [comment] 2018-06-12 20:06
Unfortunately, got this error when tried to update :(
![image](https://user-images.githubusercontent.com/6654132/41314357-dac36d1e-6e8c-11e8-902d-a54b1fdf1163.png)
