### ISSUE TITLE
File.GetLastWriteTime inconsistencies.

### ISSUE THREAD

**Issue by quoctruong** [dotnet/corefx#15633] opened 2017-01-30 17:51 UTC
On Windows, File.GetLastWriteTime does not throw an error if the file does not exist. On Linux, however, this function throws an error.

**Comment by danmosemsft** [comment] 2017-01-30 18:06
That seems like it should be fixed.

**Comment by stephentoub** [comment] 2017-01-30 18:11
https://github.com/dotnet/corefx/issues/1728

**Comment by ianhays** [comment] 2017-01-30 18:15
I took this issue to a design review forever ago and sentiment was strong that the Linux versions should throw. So, it is definitely a purposeful difference in behavior. 

This is a dupe of #1728, so we should reopen and continue discussion there if we want to change the behavior to match Windows.

**Closed by ianhays** 2017-01-30 18:15 UTC
Labels: area-System.IO, bug

**Comment by ianhays** [comment] 2017-01-30 18:17
FWIW, my vote is/was consistency between platforms. Since the overall sentiment on compat has changed since #1728, it's possible we may want to make them the same now.
