### ISSUE TITLE
ReuseUnicastPort_CreateSocketSetOption_NoSocketsReuseUnicastPortSupport_Throws failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11088] opened 2016-08-24 11:48 UTC
Appears to be failing all Windows builds, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/1115/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3747/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release/1113/
```
System.Net.Sockets.Tests.SocketOptionNameTest.ReuseUnicastPort_CreateSocketSetOption_NoSocketsReuseUnicastPortSupport_Throws [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.Sockets.SocketException)
        Actual:   (No exception was thrown)
        Stack Trace:
           D:\j\workspace\windows_nt_debug88592b53\src\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(56,0): at System.Net.Sockets.Tests.SocketOptionNameTest.ReuseUnicastPort_CreateSocketSetOption_NoSocketsReuseUnicastPortSupport_Throws()
```
cc: @davidsh, @cipop, @ericeil

**Comment by davidsh** [comment] 2016-08-24 17:28
Have the Windows CI machines been changed recently?  Are they running a different build of Windows? What build of Windows are they running?

**Comment by bartdesmet** [comment] 2016-08-24 17:34
Logs contain `Building remotely on Azure0823221948 (auto-win2012-20160627)`; according to https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy this is "Windows Server 2012 R2".

**Comment by davidsh** [comment] 2016-08-24 17:42
If it is indeed Windows Server 2012 R2, that means it is not Windows 10.  The "ReuseUnicastPort" support for sockets was a feature only added in Windows 10.

So, the test itself is validating that on non Windows 10 system, an exception is thrown for the new "ReuseUnicastPort" socket option.  However, the test is failing because an exception is not being thrown as expected.

So, either the CI machine is really running Windows 10 (which is not true as stated above), or this feature has been backported to Windows Server 2012 R2 via a recent Windows Update mechanism. I wasn't aware of that happening but it is possible that the feature was backported to versions of Windows earlier than Windows 10.

I think for now, the tests related to this should be disabled.

**Comment by CIPop** [comment] 2016-08-24 18:17
Assigning to @davidsh : it appears there is something wrong with platform detection (`Capability.SocketsReuseUnicastPortSupport();`) / or actual product-code activation of the feature. 
@stephentoub @davidsh 
* From the error, it appears that we expect that the test fails but it doesn't. Is the test system properly configured to work with `ReuseUnicastPort`? 
* Is this the first time we're running these on a 2012 R2 server SKU?

**Comment by davidsh** [comment] 2016-08-24 18:30
It appears that the "ReuseUnicastPort" socket option was back ported to Windows Server 2012 R2 via a recent update rollup patch:

https://support.microsoft.com/en-us/kb/3149157

**Comment by davidsh** [comment] 2016-08-24 18:33
The current CI machines are using "auto image" feature of Azure VMs.  So, they are getting newer VM images.  The current image is as of June 2016.  The previous image was March 2016.

The update to Windows Server 2012 R2 for the June 2016 image now includes the "ReuseUnicastPort" feature.

So, this is why this broke recently in CI.

**Comment by davidsh** [comment] 2016-08-24 19:33
Re-opening issue.  Need to decide whether to fix these tests to properly detect the feature or just remove them.

**Comment by davidsh** [comment] 2016-09-14 00:45
reopen since the [activeissue] tag with this issue number is still in the code. The tests are disabled right now. This issue tracks whether to completely remove these tests from the code or fix up the tests so that we can recognize feature light-up to verify expected behavior.

**Comment by joperezr** [comment] 2016-09-14 15:41
@davidsh sorry, looks like when I did the merge, pushing the commit that had the message that fixed this issue closed it.

**Closed** 2016-09-25 23:42 UTC
Labels: area-System.Net
