### ISSUE TITLE
System.Text.Json Deserialization: It should overwrite the original property value while deserializing

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#40100] opened 2019-08-07 14:33 UTC
Use .NET Core 3.0 preview 7:
This is ok:
```csharp
using System.Collections.Generic;
using System.Text.Json;

namespace FixedTest
{
    class Test
    {
        public string A { get; set; } = "123";
        public string[] B { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var x = new Test();
            x.B = new[] { "test" };
            var json = JsonSerializer.Serialize(x);
            var result = JsonSerializer.Deserialize<Test>(json);
            return;
        }
    }
}
```

However this is not:
```csharp
using System.Collections.Generic;
using System.Text.Json;

namespace FixedTest
{
    class Test
    {
        public string A { get; set; } = "123";
        public string[] B { get; set; } = new[] { "test" };
    }
    class Program
    {
        static void Main(string[] args)
        {
            var x = new Test();
            var json = JsonSerializer.Serialize(x);
            var result = JsonSerializer.Deserialize<Test>(json);
            return;
        }
    }
}
```

Got exception:
```
Unhandled exception. System.NotSupportedException: Collection was of a fixed size.
   at System.SZArrayHelper.Add[T](T value)
   at System.Text.Json.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)     
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)   
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)        
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

I think it should overwrite the original value while deserializing, otherwise it will cause:
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace FixedTest
{
    class Test
    {
        public string A { get; set; } = "123";
        public List<string> B { get; set; } = new List<string> { "test" };
    }
    class Program
    {
        static void Main(string[] args)
        {
            var x = new Test();
            var json = JsonSerializer.Serialize(x);
            var result = JsonSerializer.Deserialize<Test>(json);
            foreach (var i in result.B)
            {
                Console.WriteLine(i);
            }
            return;
        }
    }
}
```

Output:
```
test
test
```

**Comment by steveharter** [comment] 2019-08-07 17:20
This is a duplicate of https://github.com/dotnet/corefx/issues/38435 which was fixed. I verified your sample locally.

Please install the latest build of 3.0.x ([runtime + SDK](https://github.com/dotnet/core-sdk#installers-and-binaries) or [just runtime](https://github.com/dotnet/core-sdk#installers-and-binaries)) to verify or wait for Preview 8. Thanks

Please re-open this issue if this is not the case. Thanks

**Closed by steveharter** 2019-08-07 17:20 UTC
Labels: area-System.Text.Json, bug

**Comment by kieronlanning** [comment] 2019-10-29 09:36
Can we re-open this, @steveharter? I've this exact problem with the release version when specifying `IgnoreNullValues = true` in the `JsonSerializationOptions`.

Any combination of an array property will cause this to fail when that property is set to true: default value (`Array.Empty<T>()` or just `nul`l).

Repo for bug: https://github.com/kieronlanning/SystemTextJsonArraySerializationBug
