### ISSUE TITLE
System.Text.Json ModelStateDictionary

### ISSUE THREAD

**Issue by joshmouch** [dotnet/corefx#41399] opened 2019-09-27 16:43 UTC
I'm switching to System.Text.Json from Json.Net, and the following is no longer serializable:
`Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary`.

The exception is:
```
System.InvalidCastException : Unable to cast object of type 'Enumerator' to type 'System.Collections.IDictionaryEnumerator'.
   at System.Text.Json.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.HandleObject(JsonPropertyInfo jsonPropertyInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at 
```

Will this be supported? Are there any workarounds?

**Comment by Gnbrkm41** [comment] 2019-09-29 06:29
Seems to have the same root cause as https://github.com/dotnet/corefx/issues/41329#issuecomment-535272256

**Comment by joshmouch** [comment] 2019-09-29 17:43
That's correct. Is there a workaround we can have instead of waiting for the next release?

**Comment by Gnbrkm41** [comment] 2019-09-29 17:53
Could you try writing a JsonConverter for ModelStateDictionary and using that to serialize the dictionary?

**Comment by joshmouch** [comment] 2019-09-29 19:11
Yes, but I was thinking something more generic. I'm going to run into this with multiple classes. Maybe an IDictionary jsonconverter to override the way that's currently done. I'll dig into the source code more to see what my options are.

**Comment by joshmouch** [comment] 2019-09-30 15:39
I attempted to just create a converter that uses Json.Net until this bug is fixed, but it appears I can't do that because there's no `WriteRaw` method on `Utf8JsonWriter`.  This seems like a pretty important method to include.

```
	public class ModelStateDictionaryConverter : System.Text.Json.Serialization.JsonConverter<ModelStateDictionary>
	{
		public override bool CanConvert(Type typeToConvert)
		{
			var canConvert = base.CanConvert(typeToConvert);
			return canConvert;
		}

		public override ModelStateDictionary Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			var value = reader.GetRaw(); // WHERE IS THIS METHOD?
			return (ModelStateDictionary)JsonConvert.DeserializeObject(value, typeof(ModelStateDictionary));
		}

		public override void Write(Utf8JsonWriter writer, ModelStateDictionary value, JsonSerializerOptions options)
		{
			var valueAsString = JsonConvert.SerializeObject(value);
			writer.WriteRaw(valueAsString);  /// WHERE IS THIS METHOD?
		}

	}

```

**Comment by joshmouch** [comment] 2019-09-30 17:16
@Gnbrkm41 
I must be missing something here with not seeing a `GetRaw` or `WriteRaw` method.  It seems odd that this is so hard to write an object serialized outside of the handful of limited methods exposed by `Utf8JsonWriter`.

**Comment by joshmouch** [comment] 2019-09-30 17:53
Here's a working converter.  I couldn't find a way to use JSON.Net to do the serialization inside a System.Text.Json converter, but for some reason the following code works.  It's probably pretty slow, since it goes through the Serializer for each property.

```
	public class ModelStateEntryJsonConverter : System.Text.Json.Serialization.JsonConverter<ModelStateEntry>
	{
		public override ModelStateEntry Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		{
			throw new NotSupportedException();
		}

		public override void Write(Utf8JsonWriter writer, ModelStateEntry value, JsonSerializerOptions options)
		{
			writer.WriteStartObject();

			var properties = typeof(ModelStateEntry).GetProperties();
			foreach (var propertyInfo in properties)
			{
				var propertyName = propertyInfo.Name;
				if (propertyName != string.Empty && char.IsUpper(propertyName[0]))
				{
					propertyName = char.ToLower(propertyName[0]) + propertyName.Substring(1);
				}

				var propertyValue = propertyInfo.GetValue(value);
				
				writer.WritePropertyName(propertyName);
				JsonSerializer.Serialize(writer, propertyValue, options);
			}

			writer.WriteEndObject();
		}

	}

```

**Comment by ahsonkhan** [comment] 2019-10-18 21:12
This is a duplicate of https://github.com/dotnet/corefx/issues/41329, closing.

> I must be missing something here with not seeing a `GetRaw` or `WriteRaw` method.  It seems odd that this is so hard to write an object serialized outside of the handful of limited methods exposed by `Utf8JsonWriter`.

@joshmouch - could you please file a separate issue for this and what you expect the input to WriteRaw on the writer, and it's behavior, if you still have that requirement? Thanks!

**Closed by ahsonkhan** 2019-10-18 21:12 UTC
Labels: area-System.Text.Json

**Comment by steveharter** [comment] 2019-10-22 00:18
@joshmouch can you provide a stand-alone repro please.

The works on 3.0 for me:
```cs
            var obj = new ModelStateDictionary();

            obj["key"] = new ModelState();
            obj.AddModelError("key2", "foo");

            string json = JsonSerializer.Serialize(obj);
            obj = JsonSerializer.Deserialize<ModelStateDictionary>(json);
```

**Comment by ahsonkhan** [comment] 2019-10-23 19:53
@joshmouch - can you please retry using the latest nightly build and see if your issue is fixed with ModelStateDictionary?

You can reference the latest System.Text.Json NuGet package from https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
