### ISSUE TITLE
Wrong .NET Core console output encoding on Windows

### ISSUE THREAD

**Issue by Maxim-Kornilov** [dotnet/corefx#15986] opened 2017-02-09 04:56 UTC
Command prompt on my computer have a 866 (OEM - Russian) encoding, but .NET Core app says it is Unicode (UTF-8).

Source code:
```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string helloWorld = "Здравствуй, Мир!";
            Console.WriteLine(Console.OutputEncoding.EncodingName);
            Console.WriteLine(helloWorld);

            Console.OutputEncoding = Console.OutputEncoding;
            Console.WriteLine(Console.OutputEncoding.EncodingName);
            Console.WriteLine(helloWorld);
        }
    }
}
```
Console output:
```
D:\ConsoleApp1>dotnet run
Unicode (UTF-8)
╨Ч╨┤╤А╨░╨▓╤Б╤В╨▓╤Г╨╣, ╨Ь╨╕╤А!
Unicode (UTF-8)
Здравствуй, Мир!

D:\ConsoleApp1>dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by ianhays** [comment] 2017-02-09 19:14
Heya @Maxim-Kornilov, this is a duplicate of https://github.com/dotnet/corefx/issues/10054 and is expected behavior. Please comment over there after reading the comments if you have any further concerns :)

**Closed by ianhays** 2017-02-09 19:14 UTC
Labels: area-System.Console, bug

**Comment by Maxim-Kornilov** [comment] 2017-02-12 11:28
OK. But it is still looks like a bug even if it is an expected behavior. It is working as expected on a full .NET Framework.

**Comment by JohnRusk** [comment] 2017-07-02 23:50
@ianhays I'm having the same problem.  How can there be no bug here?  I can reproduce the following sequence of events:

1. Start app
2. Read Console.OutputEncoding.  It says its UTF-8
3. Display output. It does not come out in UTF-8, even though that was reported as the current encoding.
4. _Set_ the encoding to UTF-8.  (I.e. set it to its existing value).
5. Display output again. Now it does come out in UTF-8.

If setting a property to its existing value changes behavior, how can that not be a bug?  (In this the case, the bug is present before the "set", since at that point in the process the getting is returning a value which clearly is not actually being used).

**Comment by ianhays** [comment] 2017-07-05 15:57
Hey @JohnRusk, please comment on #10054 instead, as this issue is a duplicate and the discussion is focused in #10054.
