### ISSUE TITLE
Consider being lazy in Enumerable.Reverse if the input is an IList

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#11459] opened 2016-09-06 06:02 UTC
The moment an iterator returned by `Enumerable.Reverse()` is called `MoveNext` on, it creates a copy of the entire enumerable in an array, and sets starts iterating from the last index in that array. While this is inevitable for lazy enumerables, it should be avoidable for `IPartition` and `IList`, since those interfaces give us random access to the underlying collection. We should consider specializing this iterator for those types so as not to copy, and use the index to index into the actual collection instead of a copied array.

The downside of this would be that we are now making N virtual calls where before we only made 1 while enumerating. For example, consider

```cs
int[] numbers = ...
numbers.Reverse();
```

Before we would do the equivalent of

```cs
var @new = new int[numbers.Length];
numbers.CopyTo(@new, 0); // 1 virtual call
for (int i = @new.Length - 1; i >= 0, i--)
{
    yield return @new[i]; // This is not a virtual call since we know the type is an array, it will be fast
}
```

Now we're doing

```cs
// No @new
IList<int> list = numbers;
for (int i = numbers.Length  - 1; i >= 0; i--)
{
    yield return list[i]; // We are now doing numbers.Length virtual calls. We avoid the allocation, but this is slower
}
```

However citing dotnet/coreclr#6941 even if the new implementation is slower in terms of CPU time, this may still be a worthwhile change since less allocations is better for the entire process.

**Comment by svick** [comment] 2016-09-06 10:05
This sounds like a duplicate of https://github.com/dotnet/corefx/issues/4750.

**Comment by stephentoub** [comment] 2016-09-06 13:56
It's also observable in its behavioral change.  Previously once you started enumerating, any changes to the original would not be visible in the output; with such a change, changes in the original might show up in the output, since the copy is being removed.  Or similarly, in your list example, clearing the list once iteration had started wouldn't previously have been visible; with this change, it would result in an exception getting thrown trying to index beyond the end of the list.

**Comment by stephentoub** [comment] 2016-09-06 13:57
Closing as a dup.

**Closed by stephentoub** 2016-09-06 13:57 UTC
