### ISSUE TITLE
Test failure: MonoTests.System.Runtime.Caching.MemoryCacheTest / TestCacheSliding

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#26586] opened 2018-01-25 07:30 UTC
## History of failures

Day | Build | OS | Details
-- | -- | -- | -- 
1/14 | 1373384c81e62be7b9f7e75f2ba62ffabea2d269 | Win10 | Actual null
1/16 | a55fcd0822253d51c4be1bd6a24c7398476adb79 | Win10 | Actual null
1/29 | 20180129.05 | Win8.1 | Actual 42 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180129.05/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTest~2FTestCacheSliding)
2/1 | 654d82c699b3d0a8d2740d79f066e32cf4bccfc1 | Win10 | Actual null
2/7 | 20180207.02 | Win7 | Actual: 42 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180207.02/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTest~2FTestCacheSliding)
2/9 | 20180209.03 | Win7 | Actual: 42 - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180209.03/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTest~2FTestCacheSliding)

# Original report

Test: MonoTests.System.Runtime.Caching.MemoryCacheTest.TestCacheSliding (from (empty))  has failed.

```
Assert.NotEqual() Failure
Expected: Not null
Actual: null

at MonoTests.System.Runtime.Caching.MemoryCacheTest.TestCacheSliding() in D:\j\workspace\outerloop_net---7a39cc82\src\System.Runtime.Caching\tests\System.Runtime.Caching\MemoryCacheTest.cs:line 1053
```
Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_windows_nt_release/285/testReport/MonoTests.System.Runtime.Caching/MemoryCacheTest/TestCacheSliding/

**Comment by KKhurin** [comment] 2018-01-25 21:12
Need to harden the test - looks like we'd occasionally get a sleep longer than 2 seconds (when asked for 100ms). One simple fix would just be to increase the SlidingExpiration beyond reasonable delays. Its unclear what this reasonable delay would be: 5 seconds? 10 seconds? This can also affect the test execution time... 
Another (more robust) option is to measure the actual duration of each sleep and address the case when we accidentally slept for too long and the item had expired (instead of intended extension of its expiration).

**Comment by danmosemsft** [comment] 2018-02-02 23:12
@KKhurin this broke CI again, this time on Nano. Could you please tweak the test? 

Note we have found in other tests that we have to set timeouts to several times the value you might need running locally -- because the machines can run slow due to concurrent activity.

https://mc.dot.net/#/user/lroca88/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/654d82c699b3d0a8d2740d79f066e32cf4bccfc1/workItem/System.Runtime.Caching.Tests/analysis/xunit/MonoTests.System.Runtime.Caching.MemoryCacheTest~2FTestCacheSliding

**Comment by KKhurin** [comment] 2018-02-07 01:26
Should be fixed now.

**Comment by Sunny-pu** [comment] 2018-02-08 07:05
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/401/testReport/

**Comment by KKhurin** [comment] 2018-02-08 21:31
A new PR is ready to fix the regression I introduced with the previous fix.

**Comment by karelz** [comment] 2018-02-10 20:10
2 more hits in official Helix runs - see updated top post.

**Comment by KKhurin** [comment] 2018-03-15 19:11
Will wait for another failure to investigate.

**Comment by karelz** [comment] 2018-03-15 19:15
@KKhurin please look proactively into test results history (e.g. Kusto). The bugs are not updated with each failure.

**Comment by karelz** [comment] 2018-03-15 20:18
Top post updated with history as of 3/15. No repro since 2/9, maybe it got fixed?
If you think it might have, I recommend to close it and wait for another occurrence to reopen the issue.

**Comment by KKhurin** [comment] 2018-03-15 20:21
yes, it might have (at least this particular place). 
There might be more time-dependent tests and I'd open separate bugs for them.

**Closed by KKhurin** 2018-03-15 20:21 UTC
Labels: area-System.Runtime.Caching, test bug, test-run-core
