### ISSUE TITLE
[System.Text.Json] Serializing class that has array of children of the same class throws StackOverflowException

### ISSUE THREAD

**Issue by oskardudycz** [dotnet/corefx#37610] opened 2019-05-12 12:58 UTC
As in title: Serializing class that has array of children of the same class throws StackOverflowException.

Simplest repro steps:

```
public class TestClass
{
    public TestClass[] Children { get; set; }
}

var document = new TestClass();
var str = JsonSerializer.ToString(document);
```
I create repository that reproduces this issue: https://github.com/oskardudycz/System.Text.Json.Fail

**Comment by oskardudycz** [comment] 2019-05-12 13:17
I added also failing test scenario for this case: https://github.com/dotnet/corefx/pull/37611

**Comment by ahsonkhan** [comment] 2019-05-14 04:02
I believe this is a duplicate of https://github.com/dotnet/corefx/issues/37313. Closing.

Feel free to re-open if you disagree.

**Closed by ahsonkhan** 2019-05-14 04:02 UTC
Labels: area-System.Text.Json, bug
