### ISSUE TITLE
Some tests are failing when decimal separator is not a dot

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#1491] opened 2015-04-23 23:45 UTC
Some XML tests are failing if decimal separator is not a dot.

Example repro:
- Start->Run (WinKey + R) -> `intl.cpl`
- Change format (no need to change locale) to `Ukrainian (Ukraine)`
- `build /p:WithCategories=OuterLoop`

Example error:

```
TestCase:WriteFullEndElement -
ERROR: RECA
Expected: -4582,24
Actual  : -4582.24
        elem.WriteValue(floatToUri)
```

**Comment by Maxwe11** [comment] 2015-04-29 06:59
I saw this issue but after pulling from dotnet/master couldn't repro now. It's possible to run outer loop tests for individual project?

**Comment by khellang** [comment] 2015-05-12 13:25
I guess this one can be closed from #1592?

**Comment by Maxwe11** [comment] 2015-05-12 13:27
@khellang no, xml tests not fixed

**Comment by ctyar** [comment] 2016-07-13 09:57
@krwq I cant reproduce this, is this somehow fixed?

format changed to `Ukrainian (Ukraine)` and
`C:\corefx\src\System.Xml.ReaderWriter\tests\XmlConvert>msbuild /t:BuildAndTest  /p:xunitoptions="-trait category=Outerloop`

Just some warnings, but no error

**Comment by krwq** [comment] 2016-07-14 20:12
@ctyar, not sure if that runs OuterLoop - try:
```
msbuild /t:BuildAndTest /p:OuterLoop=true
```

**Comment by ctyar** [comment] 2016-07-15 07:12
@krwq I tried that too, nothing fails in `System.Xml.ReaderWriter\tests\XmlConvert` 
but this was the only project I tried(based on your error sample)

**Comment by sepidehMS** [comment] 2016-12-16 23:13
Fixed by https://github.com/dotnet/corefx/issues/14462

**Closed by sepidehMS** 2016-12-16 23:13 UTC
Labels: area-System.Xml, test bug, up for grabs
