### ISSUE TITLE
DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging Assert failing area-System.Net.Http.Functional.Tests

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#16109] opened 2017-02-13 17:49 UTC
Test appears to be added with https://github.com/dotnet/corefx/pull/15971 and is affecting Linux tests
cc@lmolkova
cc@stephentoub 

Assert.Equal() Failure
18:57:42         Expected: 42
18:57:42         Actual:   134
18:57:42         Stack Trace:
18:57:42            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse42.1_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(167,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
18:57:42            /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_opensuse42.1_debug/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs(219,0): at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging()
18:57:42   Finished:    System.Net.Http.Functional.Tests

**Comment by stephentoub** [comment] 2017-02-13 17:54
Is there any stack trace earlier in the log from an unhandled exception? Exit code 134 suggests the remote executor app crashed.

**Comment by Priya91** [comment] 2017-02-13 18:47
This is a dupe of #16098

**Comment by danmosemsft** [comment] 2017-02-13 18:58
Closing as dupe. I tagged the other one as blocking as it's making the badges red. We should either fix now or disable.

**Closed** 2017-02-13 22:31 UTC
Labels: area-System.Net.Http, blocking-clean-ci, test-run-core
