### ISSUE TITLE
GDPR + Always Encrypted

### ISSUE THREAD

**Issue by MSRiganti** [dotnet/corefx#22324] opened 2017-07-17 14:04 UTC
Hi,

please read this EU regulation [GDPR](http://ec.europa.eu/justice/data-protection/reform/files/regulation_oj_en.pdf).

We will need functional support for SQL **Always Encrypted** before **25. may 2018** .

When it will be implemented in **EF Core**?
(Please, give it priority. It will be before 25 may 2018?)

Thanks

**Comment by shaggygi** [comment] 2017-07-17 14:09
Probably need to move this issue to: https://github.com/aspnet/EntityFramework

**Comment by danmosemsft** [comment] 2017-07-17 23:21
@MSRiganti please open the issue in the EF repo linked above. Thanks

**Comment by richlander** [comment] 2017-07-17 23:22
Naive question ... will this feature require any change to System.Data? It's not an EF-only thing.

**Comment by divega** [comment] 2017-07-18 04:19
@richlander @danmosemsft It needs support in SqlClient for it to work in .NET Core first. This support it is not in place yet, and I am not sure when it is planned but it is the gap list we have been discussing. 

There is an issue tracking it for SqlClient: https://github.com/dotnet/corefx/issues/18276. We don’t have an issue tracking it for EF Core yet because we don’t consider it actionable yet.

**Comment by richlander** [comment] 2017-07-18 04:51
We are aware of GDPR and it is something we are interested in.

**Comment by MSRiganti** [comment] 2017-07-18 05:40
OK, done, issue is moved: [github.com/aspnet/EntityFramework/issues/9193](https://github.com/aspnet/EntityFramework/issues/9193)

(I have seen: [18276](https://github.com/dotnet/corefx/issues/18276) and [9142](https://github.com/aspnet/EntityFramework/issues/9142) and many more.)

Thanks

**Comment by richlander** [comment] 2017-07-19 19:03
Can you stop closing this @karelz?

I found this resource: https://blogs.msdn.microsoft.com/sqlsecurity/2017/05/24/now-available-guide-for-enhancing-privacy-and-addressing-gdpr-requirements-with-the-microsoft-sql-platform/.

We are still talking about this and I am following up with @MSRiganti on mail to learn more.

**Comment by karelz** [comment] 2017-07-19 23:30
@richlander I closed it based on the text [above](https://github.com/dotnet/corefx/issues/22324#issuecomment-315963460). If you think it tracks something different it would help if you can clarify what the issue actually tracks ;)
If you are following up, please assign it to yourself to express that -- see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)

**Comment by MSRiganti** [comment] 2017-07-20 07:24
Hi @karelz, nice presentation yesterday in Prague at Microsoft, I was there.
In this case, I think @richlander  is right.

When I run the application, and an exception occurs, which says: **"Keyword not supported: 'column encryption setting'."**
Because I add **`Column Encryption Setting=Enabled;`** in the **Connection String**.

The stack trace includes:

>    at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary2 parsetable, String connectionString, Boolean buildChain, Dictionary2 synonyms)
>    at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary2 synonyms)
>    at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
>    at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
>    at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
>    at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
>    at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
>    at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
>    at Microsoft.EntityFrameworkCore.Internal.LazyRef1.get_Value()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_02.<Execute>b__0(DbContext c, TState s)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func3 operation, Func3 verifySucceeded)
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func2 operation, Func2 verifySucceeded, TState state)
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func2 operation)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()

If you search in the [dotnet/corefx](https://github.com/dotnet/corefx) for **"ColumnEncryptionSetting"** you will find: [DbConnectionStringCommon.cs](https://github.com/dotnet/corefx/blob/e7723074a7ee7cfbc1da516108d2ad85082d77d4/src/System.Data.Odbc/src/Common/System/Data/Common/DbConnectionStringCommon.cs).
There is a commented out line:
> `//internal static readonly SqlConnectionColumnEncryptionSetting ColumnEncryptionSetting = SqlConnectionColumnEncryptionSetting.Disabled;`
and the line:
> `internal const string ColumnEncryptionSetting = "Column Encryption Setting";`

If you search: **"Keyword not supported"** you can find the definition: 
> `<value>Keyword not supported: '{0}'.</value>`

in file [Strings.resx](https://github.com/dotnet/corefx/blob/c273376e24f7ed5f56f0cae807ef4ab17c6bdc1b/src/System.Data.SqlClient/src/Resources/Strings.resx)
and the file where it throws the exception [DbConnectionOptions.Common.cs](https://github.com/dotnet/corefx/blob/edfbb59a338cc586b7f6b1a66e409538142eba7b/src/Common/src/System/Data/Common/DbConnectionOptions.Common.cs) line 572
> `throw ADP.KeywordNotSupported(keyname);`

in method 
>  `private static NameValuePair ParseInternal(Dictionary<string, string> parsetable, string connectionString, bool buildChain, Dictionary<string, string> synonyms, bool firstKey)`

Am I wrong if I think that the right place for this issue is here? ([dotnet/corefx](https://github.com/dotnet/corefx))
Please explain it to me, thank you.

**Comment by karelz** [comment] 2017-07-20 08:21
Thanks for explanation @MSRiganti ... I was confused by previous replies.

@richlander can you please mark the bug according to our triage? Is it about new API? Which area? (System.Data or all over)
I let @tarekgh push it further in Meta area ...

**Comment by tarekgh** [comment] 2017-07-20 16:11
I moved it to System.Data.SqlClient area as it is the only stack affected here. and assigned it to @richlander as he is already following up,

**Comment by richlander** [comment] 2017-07-20 16:13
@MSRiganti Does https://github.com/dotnet/corefx/issues/18276 cover this scenario?

**Comment by MSRiganti** [comment] 2017-07-21 07:57
No.
Because #18276 cover the funkcionality, not the answer, when it will be done.
My (and not just my :-) ) question is: When?
**Will it be released before 25 may 2018?**
According to the answers we can, or we cannot build new projects with this framework.
I found, that this funkcionality is not in plan yet. 
Stackowerflow: [41027953](https://stackoverflow.com/questions/41027953/sql-server-always-encrypted-with-net-core-not-compatible?rq=1) and [41175489](https://stackoverflow.com/questions/41175489/column-encryption-in-asp-mvc-app-with-sql-server-2016-using-net-core-ef-core)
Both are from December 2016.
I guess, nothing changed. :-(

@richlander @karelz @divega @tarekgh @danmosemsft @shaggygi @corivera @stephentoub 
Can someone at least tell if this functionality was included in a future version of .Net Core? What number?
Thank you very much :-)

![gdpr 83 encryption](https://user-images.githubusercontent.com/29543565/28453674-94caa150-6df8-11e7-83d3-ac17dbfa4e32.png)
[Source GDPR](http://ec.europa.eu/justice/data-protection/reform/files/regulation_oj_en.pdf)

![gdpr section 2 - article 32 - security of processiong - encryption](https://user-images.githubusercontent.com/29543565/28453991-d217ac32-6df9-11e7-8d4c-e7514f62dda4.png)
[Source GDPR with description](http://data.consilium.europa.eu/doc/document/ST-5419-2016-INIT/en/pdf) 
[(česky)](http://data.consilium.europa.eu/doc/document/ST-5419-2016-INIT/cs/pdf) and in other languages, if you change the url.

**Comment by tarekgh** [comment] 2017-07-21 16:18
CC @saurabh500 @corivera

**Comment by MSRiganti** [comment] 2017-07-21 18:00
Thank you.

**Comment by saurabh500** [comment] 2018-02-12 22:33
Moving to future, because the owning team, won't be addressing this in 2.1

**Comment by rudiv** [comment] 2018-05-11 13:39
With the push for GDPR updates on ASP.NET Core (yes I realise that's not .NET Core), it's sad that this hasn't made the cut for inclusion.

I'd say that it's almost critical in this current climate for data breaches and such, ensuring data integrity at rest and seamlessly for developers is quite key. Unless I'm mistaken there isn't particularly a suitable workaround at this time either, unless we moved our DB Layer to a Full Framework library?

**Comment by AhmedElbatt** [comment] 2018-05-14 10:52
@MSRiganti 
May I ask you if have currently any updates regarding this issue , or any kind of workaround solution ?
Thanks

**Comment by kevbry** [comment] 2018-11-01 17:53
With the announcement that asp.net core 3.0 won't support full framework, lack of always encrypted support in .net core is going to block our further development using the platform. Would be good to have some feedback on when/if this is going to be available so that we can start making plans.

**Comment by karelz** [comment] 2018-11-01 18:06
@divega can you please help here to bubble it up?

**Comment by divega** [comment] 2018-11-19 23:19
@karelz This is duplicate of https://github.com/dotnet/corefx/issues/18276, which we are discussing already with the SQL Server team, or at least I don't see anything in this issue that makes it different. 

There is an EF Core-level issue at https://github.com/aspnet/EntityFrameworkCore/issues/3380.

**Comment by karelz** [comment] 2018-11-19 23:30
Duplicate of #18276

**Closed by karelz** 2018-11-19 23:30 UTC
Labels: area-System.Data.SqlClient

**Comment by divega** [comment] 2018-11-19 23:48
Based on the title and most of the discussion this is definitively a duplicate of #18276. 

But @richlander [asked before for this issue not to be closed](https://github.com/dotnet/corefx/issues/22324#issuecomment-316485372), presumably because there was something that he wanted to follow up on?... Rich, is that still the case?
