### ISSUE TITLE
System.Threading.AccessControl won't load from asp.net Core 2.0 (netcoreapp2.0) website

### ISSUE THREAD

**Issue by CarlosOnline** [dotnet/corefx#26084] opened 2017-12-28 06:14 UTC
# System.Threading.AccessControl won't load from asp.net Core 2.0 (netcoreapp2.0) website

Referencing .net 4.5.1 framework class library from asp.net Core 2.0 (netcoreapp2.0), where class library references System.Threading.AccessControl leads to receives FileNotFound exception.

**System.IO.FileNotFoundException** occurred
  HResult=0x80070002
  Message=Could not load file or assembly '**System.Threading.AccessControl**, Version=4.0.2.0, 
```
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=Util
  StackTrace:
   at Util.MutexTest..ctor(String name) in C:\temp\projects\DotNetCore20MutexSetAccessControl\Util\MutexTest.cs:line 18
   at DotNetCore20MutexSetAccessControl.Controllers.HomeController.Index() in C:\temp\projects\DotNetCore20MutexSetAccessControl\spa\Controllers\HomeController.cs:line 11
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

# Repro
Problem solution uploaded to [DotNetCore20MutexSetAccessControl](https://github.com/CarlosOnline/DotNetCore20MutexSetAccessControl.git)

# Manual Repro
dotnet new --install "Microsoft.AspNetCore.SpaTemplates"
dotnet new aurelia
npm intstall
add new Utils .Net Framework 4.51 project (version doesn't matter)
add class below to Utils .Net Framework 4.51

```c#
using System.Security.AccessControl;
using System.Security.Principal;
using System.Threading;

namespace Util
{
    public class MutexTest
    {
        public MutexTest(string name)
        {
            var mutexId = $"Global\\{name}";
            var mutex = new Mutex(false, mutexId);

            var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), MutexRights.FullControl, AccessControlType.Allow);
            var securitySettings = new MutexSecurity();
            securitySettings.AddAccessRule(allowEveryoneRule);
            mutex.SetAccessControl(securitySettings);
        }
    }
}
```

add Utils project reference to asp.net core app project
update HomeController.cs
```c#
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Util;

namespace DotNetCore20MutexSetAccessControl.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var mutexTest = new MutexTest("MyTest");
            return View();
        }

        public IActionResult Error()
        {
            ViewData["RequestId"] = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View();
        }
    }
}
```
start debugging

[EDIT] Add C# syntax highlighting by @karelz

**Comment by CarlosOnline** [comment] 2017-12-28 06:20
# System.MissingMethodException when preview1 nuget package added.
Install-Package System.Threading.AccessControl **-Version 4.5.0-preview1-25914-04** into the .netcore20 app project

# Exception
  HResult=0x80131513
  Message=**Method not found: 'Void System.Threading.Mutex.SetAccessControl**
```(System.Security.AccessControl.MutexSecurity)'.
  Source=Util
  StackTrace:
   at Util.MutexTest..ctor(String name) in C:\temp\projects\DotNetCore20MutexSetAccessControl\Util\MutexTest.cs:line 18
   at DotNetCore20MutexSetAccessControl.Controllers.HomeController.Index() in C:\temp\projects\DotNetCore20MutexSetAccessControl\spa\Controllers\HomeController.cs:line 11
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

# Repro
_Install-Package System.Threading.AccessControl -Version 4.5.0-preview1-25914-04_ into the .netcore20 app project.

start debugging

**Comment by karelz** [comment] 2017-12-28 17:39
How does the ASP.NET Core app play a part here? Can you reproduce it with simple console app?

**Comment by CarlosOnline** [comment] 2017-12-28 17:52
It works on .netcore 1.1 and in .net451 wpf application.  It doesn't work
in .netcore2.0.

**Comment by karelz** [comment] 2017-12-28 18:23
OK, if it works on .NET Core 1.1, that is important information.
Back to my previous question - are you able to reproduce it with console app (no ASP.NET Core involved)?

**Comment by CarlosOnline** [comment] 2017-12-28 19:35
Yes it does work on console app. 
Problem is that it works everywhere except for .netcore2.0.

See similar issue: [System.DirectoryServices.AccountManagement ](https://github.com/dotnet/corefx/issues/24488)

It would be great if it was added to the [Windows Compatibility Pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/)

**Comment by karelz** [comment] 2017-12-28 20:31
@safern @weshaggard can you check this please? Seems to be similar to #24488.

**Comment by safern** [comment] 2017-12-28 20:35
Yes, I will take a look.

**Comment by CarlosOnline** [comment] 2018-01-03 01:18
Another missing issue: **System.Runtime.Remoting** fails to load from **.netcore 2.0**.  Works from .netcore 1.1.

**Comment by weshaggard** [comment] 2018-01-03 01:24
Do you have a sample .NET Core 1.1 application where these work? I wouldn't expect either of them to work on .NET Core 1.1 either.

**Comment by safern** [comment] 2018-01-03 23:19
I took a look at the issue and this is expected. When you have a .NET Framework library and you reference it from a .NET Core app you will likely hit issues like this one, we don't guarantee that this scenarios will work all the time (it is almost impossible to make this a 100% compatible scenario). 

The main issue here is that the full framework library that you're building is using `mutex.SetAccessControl` which is an instance method there. However in .NET Core this method is an extension method: https://github.com/dotnet/corefx/blob/86ece56a880a4364fb40303c87f1c64e6c1cd8a1/src/System.Threading.AccessControl/src/System/Threading/ThreadingAclExtensions.cs#L41 

Which will cause the runtime exception to happen, because when building the full framework library it will build against its own reference assemblies and find the instance method and produce the IL against that. When you try to run you .NET Core app it will try to call that method using the .NET Core runtime which doesn't have that instance method under Mutex, so it will never work and there is not a fix we can do because of that. 

However that is why we create .NET Standard, for cross compatibility across runtimes and platforms, so what I suggest is that your .NET Framework library, you port it to .NET Standard which should be simple and then reference it from you .NET Core application and it should work fine, and you should stop hitting issues like the ones you've been hitting. 

Will close the issue since this is not expected to work.

**Comment by CarlosOnline** [comment] 2018-01-04 00:12
Why is this closed.  I have mentioned that this works in .netcore 1.1.  I was hoping to upgrade the project to .netcore 2.0.

**Comment by weshaggard** [comment] 2018-01-04 00:14
@CarlosOnline can you please point us at .NET Core 1.1 application that can correctly consume your .NET Framework library? I don't expect this to work.

**Comment by safern** [comment] 2018-01-04 00:18
Sorry for closing. I thought the System.Runtime.Remoting one was the one working in netcore1.1 but System.Threading.AccessControl scenario wasn't.

**Comment by weshaggard** [comment] 2018-01-04 00:31
I took your .NET Framework Util class and consumed it from a .NET Core 1.1 console application and it failed with:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.Security.Principal.SecurityIdentifier' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at Util.MutexTest..ctor(String name)
   at netcore11.Program.Main(String[] args) in D:\git\temp\DotNetCore20MutexSetAccessControl\netcore11\Program.cs:line 10
```
That is expected because those types and members didn't exist anywhere in .NET Core 1.1.

Next I did the same thing with your .NET Framework Util class and consumed it from a .NET Core 2.0 console application and it failed with:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.AccessControl, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Util.MutexTest..ctor(String name)
   at netcore11.Program.Main(String[] args) in D:\git\temp\DotNetCore20MutexSetAccessControl\netcore11\Program.cs:line 10
```

Which is to be expected because it needs the package reference to that library. So I added the reference `<PackageReference Include="System.Threading.AccessControl" Version="4.4.0" />` and then ran and failed with:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Threading.Mutex.SetAccessControl(System.Security.AccessControl.MutexSecurity)'.
   at Util.MutexTest..ctor(String name)
   at netcore11.Program.Main(String[] args) in D:\git\temp\DotNetCore20MutexSetAccessControl\netcore11\Program.cs:line 10
```

Which is expected because of the reason @safern called out above which is that your Util library is looking for that instance method on Mutex in mscorlib but it doesn't exist there in .NET Core, it is an extension method instead. To fix this you would need to compile your Util library as a netstandard (assuming you need to share it between .NET Core and .NET Framework) or just a netcoreapp library if you don't need to share.

**Comment by CarlosOnline** [comment] 2018-01-04 17:23
I have added **spa1.1** to the solution:: [DotNetCore20MutexSetAccessControl](https://github.com/CarlosOnline/DotNetCore20MutexSetAccessControl)
from a project I originally created from dotnet core 1.0 and upgraded.

I noticed that the targetframework in spa1.1 is net451, and not netcore1.1.  However it is still using .netcore.  **How is this possible?**

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net451</TargetFramework>
    <DefineConstants>$(DefineConstants);DotNetCore,StreamingManager</DefineConstants>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <AssemblyName>StreamingManager</AssemblyName>
    <RootNamespace>StreamingManager</RootNamespace>
    <OutputType>Exe</OutputType>
    <PackageId>StreamingManager</PackageId>
    <UserSecretsId>skeleton-typescript-aspnetcore-{E0EE09F7-ABEB-45D0-A957-2163DB134112}</UserSecretsId>
    <TypeScriptToolsVersion>2.5</TypeScriptToolsVersion>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="node_modules\**\*;" />
    <None Update="wwwroot\**\*;Views\**\*;default.config.dat;*.pdb">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNet.IISPlatformHandler" Version="1.0.0-*" />
    <PackageReference Include="Sendgrid" Version="7.0.5" />
    <PackageReference Include="SendGrid.SmtpApi" Version="1.3.1" />
    <PackageReference Include="SendGrid.SmtpApiPlus" Version="1.0.1" />
    <PackageReference Include="System.Linq.Queryable" Version="4.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>

    <ItemGroup>
        <None Update="wwwroot\**\*;Views\**\*;default.config.json;default.config.dat;*.pdb">
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <Target Name="DebugRunWebpack" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('wwwroot\dist') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />

    <!-- In development, the dist files won't exist on the first run or when cloning to
         a different machine, so rebuild them if not already present. -->
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec Command="npm install" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="cd&#xD;&#xA;echo $(SolutionDir)External\PocoToTypescriptGenerator\PocoToTypescriptGenerator.exe --commands=$(ProjectDir)custom_typings\StreamingManager.d.json&#xD;&#xA;if exist &quot;$(SolutionDir)External\PocoToTypescriptGenerator\PocoToTypescriptGenerator.exe&quot; $(SolutionDir)External\PocoToTypescriptGenerator\PocoToTypescriptGenerator.exe --commands=$(ProjectDir)custom_typings\StreamingManager.d.json&#xD;&#xA;" />
  </Target>

</Project>
```

**Comment by weshaggard** [comment] 2018-01-04 18:05
>I noticed that the targetframework in spa1.1 is net451, and not netcore1.1. However it is still using .netcore. How is this possible?

It isn't using .NET Core it is running on .NET Framework. Part of the confusion here I think is that ASP.NET Core runs on both .NET Core and .NET Framework so you can definitely have ASP.NET Core application that will work and run on .NET Framework as well.

**Comment by CarlosOnline** [comment] 2018-01-04 19:13
Can ASP.NET Core 2.0 also run on .Net Framework?
If so how would I achieve that?

**Comment by weshaggard** [comment] 2018-01-04 19:31
Yes I do believe it would. The version of ASP.NET Core is controlled by the package references you use https://github.com/CarlosOnline/DotNetCore20MutexSetAccessControl/blob/master/spa/DotNetCore20MutexSetAccessControl.csproj#L11 being the key one. The key to get it to run on .NET Framework is the TargetFramework property, try setting https://github.com/CarlosOnline/DotNetCore20MutexSetAccessControl/blob/master/spa/DotNetCore20MutexSetAccessControl.csproj#L4 to net451 (or whichever version you want to try and run on). I'm not sure what the min version of .NET Framework ASP.NET requires or if there is more you need to change beyond that property.

You might want to read over https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server to understand the benefits of both.

**Comment by safern** [comment] 2019-01-25 23:10
Closing for age, one year without update/reply. Please feel free to re-open if necessary.

**Closed by safern** 2019-01-25 23:10 UTC
Labels: area-System.Threading, tenet-compatibility
