### ISSUE TITLE
Test "System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging" failed with "Xunit.Sdk.EqualException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#16098] opened 2017-02-13 06:51 UTC
Failed test: System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging

Configuration: OuterLoop_Centos7.1_debug (build#94)

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/94/consoleText

Message:
~~~
System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   134
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(167,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs(219,0): at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledLogging()
~~~

**Comment by Jiayili1** [comment] 2017-02-13 08:47
This issue is also repro on following configurations:
1.	OuterLoop_Centos7.1_debug (build#94)
2.	OuterLoop_Centos7.1_release (build#92)
3.	OuterLoop_OpenSUSE42.1_debug (build#99)
5.	OuterLoop_OSX10.11_debug (build#84)
6.	OuterLoop_OSX10.11_release (build#80)
7.	OuterLoop_RedHat7.2_debug (build#99)
8.	OuterLoop_RedHat7.2_release (build#96)
9.	OuterLoop_Ubuntu14.04_debug (build#101)
10.	OuterLoop_Ubuntu14.04_release (build#101)
11.	OuterLoop_Ubuntu16.04_debug (build#99)
12.	OuterLoop_Ubuntu16.04_release (build#99)
13.	OuterLoop_Ubuntu16.10_debug (build#92)
14.	OuterLoop_Ubuntu16.10_release (build#100)
15.	OuterLoop_PortableLinux_release (build#11)
16.	OuterLoop_Windows8.1_release (build#95)
17.	OuterLoop_Windows10_debug (build#91)

**Comment by danmosemsft** [comment] 2017-02-13 18:58
Tagged as blocking as it's making the badges red. We should either fix now or disable.

**Comment by Priya91** [comment] 2017-02-13 19:54
Disabling the test in #16114 

cc @lmolkova Can you help take a look at the failing test..

**Comment by stephentoub** [comment] 2017-02-13 22:32
The actual source of the problem is detailed earlier in the log, an unhandled exception in the remoted function:
```
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (Assert.Throws() Failure
  Expected: typeof(System.IO.IOException)
  Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.) ---> Xunit.Sdk.ThrowsException: Assert.Throws() Failure
  Expected: typeof(System.IO.IOException)
  Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
     at Xunit.Assert.Throws(Type exceptionType, Exception exception)
     at Xunit.Assert.<ThrowsAsync>d__51`1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
     at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c__DisplayClass5_2.<<SendAsync_ExpectedDiagnosticCancelledLogging>b__2>d.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 248
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 57
     at System.Threading.Tasks.Task.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Threading.Tasks.Task.Wait()
     at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticCancelledLogging>b__5_0() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 238
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
```

**Comment by karelz** [comment] 2017-02-14 01:00
@lmolkova @vancem can you please take a look at the test failure?

**Comment by danmosemsft** [comment] 2017-02-14 01:24
Removing tag as now disabled while we fix.

**Comment by lmolkova** [comment] 2017-02-14 01:39
Please check #16135 PR

**Comment by danmosemsft** [comment] 2017-02-14 17:17
Should be fixed by https://github.com/dotnet/corefx/pull/16135

**Closed by danmosemsft** 2017-02-14 17:17 UTC
Labels: area-System.Net.Http, blocking-clean-ci, test bug, test-run-core
