### ISSUE TITLE
Unable to use System.Net.NetworkCredential inside docker

### ISSUE THREAD

**Issue by BharatRajMeriyala** [dotnet/corefx#16598] opened 2017-03-02 06:30 UTC
I am trying to authenticate my call to a SSRS report server hosted outside the docker application. And to accress the report I do the following:

```c#
HttpWebRequest webRequest = WebRequest.Create(sTargetURL) as HttpWebRequest;
webRequest.Credentials = new NetworkCredential(strReportUser, strReportUserPW);
WebResponse HttpWResp = await webRequest.GetResponseAsync();
```

But I continuesly get 401 unauthorized.

The approach of NetworkCredentials works fine when I am doing the same inside my Azure Hosted App service and also my local.

The credentials that I set on the header inside the docker environment, simply do not carry forward upto the report server and I get the error.

**Comment by karelz** [comment] 2017-03-02 07:00
Which OS? Which .NET Core version do you use 1.0 or 1.1?

**Comment by BharatRajMeriyala** [comment] 2017-03-02 07:05
The docker machine runs on linux and I am using dotnet core 1.1

**Comment by karelz** [comment] 2017-03-02 17:32
@BharatRajMeriyala which Linux distro and version?

**Comment by BharatRajMeriyala** [comment] 2017-03-03 04:38
Basically I have followed following steps mentioned in the article to create a docker machine.

https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-docker-machine?toc=%2fazure%2fvirtual-machines%2flinux%2ftoc.json#create-vms-with-docker-machine

and then I am running the usual docker commands to create a image of my dotnet core code which has this logic of setting network credentials and run the container. Inside the image I do a "dotnet publish" and then do a "dotnet web.dll"..

**Comment by BharatRajMeriyala** [comment] 2017-03-03 04:43
All I see is Operating system as "Linux" on my Azure portal for Docker-machine. I am afraid I am not sure of the specific version here ..

**Comment by BharatRajMeriyala** [comment] 2017-03-03 04:56
canonical:UbuntuServer:16.04.0-LTS:latest is the linux version.

**Comment by karelz** [comment] 2017-03-03 08:01
Which OS is used on your local and in Azure host - in places where it works?

**Comment by BharatRajMeriyala** [comment] 2017-03-03 10:36
On my local machine, I have windows 7 and I have deployed the app on Azure App Service for Dotnet Core application. It works fine in these places. Only on my docker container running linux I have the issue.

**Comment by karelz** [comment] 2017-03-03 16:54
@Priya91 is it worth quick investigation to assess the impact?
Just based on description it seems to be a bit worrisome, but I may be wrong.
You moved it to Future, so I wonder what kind of additional insight you have ...

**Comment by Priya91** [comment] 2017-03-03 18:34
@BharatRajMeriyala Can you try this on the terminal in your docker container,

```
curl --user <username>:<password> <request-url>
```

**Comment by BharatRajMeriyala** [comment] 2017-03-08 11:01
This is what I get on my docker machine...

$ curl --user asdf\xxxx:xxxx "http://xx.xxx.xxx.xxx/ReportSer
ver/Pages/ReportViewer.aspx?%2fXXXX_XXX%2fXXXXX&rs:Command=Render&rs:for
mat=pdf"
[1]+  Done                    curl --user asdf\xxxx:xxxx http:
//xx.xxx.xxx.xxx/ReportServer/Pages/ReportViewer.aspx?%2fXXXX_XXX%2fXXXXX

**Comment by BharatRajMeriyala** [comment] 2017-03-08 11:02
> Can you post the headers received from the server?

Can you tell me how exactly I can do that?

**Comment by Priya91** [comment] 2017-03-14 23:21
In your code, you can do 

```c#
WebResponse HttpWResp = await webRequest.GetResponseAsync();
var headers = (HttpWResp as HttpWebResponse).Headers;
```

and print out the headers..

**Comment by BharatRajMeriyala** [comment] 2017-03-17 11:14
Sorry for the delayed response and thanks for the code... 
The 401 unauthorized error actually happens at webRequest.GetResponseAsync().. So I am unable to print the Headers as mentioned in the code above.

Below is my approach to access the report server url..

[HttpGet("[action]")]
        [AllowAnonymous]
        public async Task<FileContentResult> DownloadReport()
        {
            string strReportUser = "rshankla";
            string strReportUserPW = "december2886$";
            string strReportUserDomain = "azuresqlserver";

            try
            {
                string sTargetURL = "http://52.168.2.227/ReportServer?%2fTestReport&rs:Command=Render&rs:Format=pdf";

                HttpWebRequest webRequest = WebRequest.Create(sTargetURL) as HttpWebRequest;

                webRequest.Credentials = new NetworkCredential(strReportUser, strReportUserPW, strReportUserDomain);

                WebResponse HttpWResp = await webRequest.GetResponseAsync();

                Stream fStream = HttpWResp.GetResponseStream();

                Byte[] fileBytes = null;

                using (var memoryStream = new MemoryStream())
                {
                    fStream.CopyTo(memoryStream);
                    fileBytes = memoryStream.ToArray();
                }

                return File(fileBytes, "application/pdf", "sdfsdf.pdf");
            }
            catch (Exception ex)
            {
                ExceptionLoggerHelper.UploadException(this._exceptionLoggerSettings, ex);
            }

            return File(new byte[50], "application/pdf");
        }

**Comment by karelz** [comment] 2017-03-17 15:04
@BharatRajMeriyala your reply seems to be deleted. Was it on purpose or by mistake?

**Comment by BharatRajMeriyala** [comment] 2017-03-17 16:12
I changed the report server to a differebt VM on my Azure subscription and I dont seem to face this issue. I will update the issue in greater issue soon.

**Comment by argoLein** [comment] 2017-05-29 13:07
same problem here. Any Updates?

**Comment by BharatRajMeriyala** [comment] 2017-05-29 13:47
If you are deploying on azure, you might want to check the outgoing port configuration on azure vm once.




-------- Original message --------

**Comment by argoLein** [comment] 2017-05-29 15:19
No. After 4 hours i solved the issue. My Client runs inside a Linux container and i changed my code to this:

```
var httpClientHandler = new HttpClientHandler();

CredentialCache cc = new CredentialCache();
cc.Add(new Uri(_apiBaseAddress), "NTLM", new NetworkCredential(_user, _password, "mydomain"));
httpClientHandler.Credentials = cc;

var client = new HttpClient(httpClientHandler);
```
outside from docker on a windows shell i dont need the credentialCache so i passed the NetworkCredential object directly to the handler. But that dont worked in docker. Inside the container, the wget command response with 2 unauthorized exceptions but the next one with 200. I think some kind of handshaking. Maybe the Cache object do the job right and dont throw an exception on the first request.

**Comment by karelz** [comment] 2017-05-30 16:37
> @argoLein Any Updates?

No updates - if you read the bug, you can notice that we don't have enough information to make any reasonable next steps. No one has a repro either.
Do you have a minimal isolated repro?

**Comment by argoLein** [comment] 2017-05-30 17:06
@karelz i already posted a suitable Solution for the problem yesterday.

**Comment by karelz** [comment] 2017-05-30 18:24
@argoLein it sounded like a workaround without clear understanding why it works. If you're fine with that, then that's ok ...

**Comment by mstephano** [comment] 2017-08-10 17:36
I got the exact same problem where I wanted to make a GET using HttpClient, and the property UseDefaultCredentials=true is not behaving the same as when debugging locally in VisualStudio or attached to a Docker container. Here is my example of code:


```
var baseAddress = "http://www.example.com";
var queryString = "param1=abc&param2=def";

var handler = new HttpClientHandler { UseDefaultCredentials = true };
using (var httpClient = new HttpClient(handler))
{
    httpClient.BaseAddress = new Uri(baseAddress);
    var response = httpClient.GetAsync($"{baseAddress}?{queryString}").Result; //csharp6 string interpolation
    if (response.IsSuccessStatusCode)
    {
        return response.Content.ReadAsAsync<myReturnedObject>().Result;
    }

    //log  error response.ReasonPhrase
    throw new ApplicationException(response.ReasonPhrase); //was exiting all the time here in Docker
}
```

My solution is to use RestSharp librairy (http://restsharp.org/) and it seams to work using the default constructor (it is using CredentialCache.DefaultCredentials - see implementation: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/NtlmAuthenticator.cs)

Here is my code using it:

```
using RestSharp;
.. ..

var baseAddress = "http://www.example.com";
var queryString = "param1=abc&param2=def";

RestClient client = new RestClient($"{baseAddress}?{queryString}");
client.Authenticator = new NtlmAuthenticator();
var restRequest = new RestRequest();
// restRequest.AddParameter() if needed

try
{
    return client.Execute<myReturnedObject>(restRequest).Data;
}
catch (Exception ex)
{
    //log  error ex
    throw;
}
```

Now my local debug using VisualStudio or attached to a Docker Container is working the same using the same code.

**Comment by kietbahuynh** [comment] 2017-08-30 00:56
Any updates on this? 

I'm having the same issue. Have tried the workaround suggested by @argoLein but no luck.

**Comment by argoLein** [comment] 2017-08-30 04:50
Hi , my Solution with the credentialcache works only inside a Linux based docker Container. if i want to start outside of a Container i have to remove the credentialcache. I made a simple switch with a OS ENV var.

**Comment by kietbahuynh** [comment] 2017-08-30 05:57
@argoLein Thanks for your comment

I think I have the same setup as yours except that I'm using dotnet core 2.0. 

I'm able to use NetworkCredentials just fine outside of docker. However, once inside docker, I keep having 401 error. 

I've tried your suggestion and then call the code below but doesn't seem to work
`var result = client.GetStringAsync(requestUrl).Result;`

A bit more information about my setup, I use port mapping as following:
`docker run -p 5000:80 myapp`

and also expose ports 80, 443, 500

Any help is much appreciated

**Comment by kietbahuynh** [comment] 2017-08-31 06:42
@argoLein Just ignore my previous comment. It works now.

For anyone who's having the same problem, the key here is use "NTLM" authentication type and it has to authenticate using base URL.

**Comment by mstephano** [comment] 2017-09-01 00:16
I had the same problem before but managed to resolve it. My container was supposed to call a webapi inside the same domain using the service account set on the app pool (in my case, it was a group Managed Service Account - gMSA). The webapi was secured and we were allowing only the service account to be able to access that webapi, so no employee in the company could hack and call the webapi manually (confidential data). When running in debug in Visual Studio 2017, the container was running using a local IP in the nat network of the host.

So using HttpClient with param UseDefaultCredential=true or setting the CredentialCache to use the NetworkCredential always result with 401 unauthorized.

The fix was:
1. Run your container with a fixed IP.
2. Create a DNS entry in your domain controller server (test.yourdomain.com for example) using the container fixed IP. This dns can only be used by the host of the container if the IP is in its nat network, unless you have created a transparent network, or else..
3. Properly create SPN for the service account with entry HTTP/<test.yourdomain.com>
4. Connect to your website using http://test.yourdomain.com.

Any questions let me know and I will try to help.

**Comment by BogdanovKirill** [comment] 2017-11-03 20:25
Same issue in AWS + Cluster + Windows spot instance + Docker. My solution is to manually set Authorization header in HttpWebRequest.

            HttpWebRequest request = WebRequest.CreateHttp(snapshotUri);
            request.Method = WebRequestMethods.Http.Get;
            request.KeepAlive = false;
            request.PreAuthenticate = false;
            request.UseDefaultCredentials = false;
            request.Proxy = null;

            if (authenticator != null)
            {
                string value = authenticator.GetResponse(1, snapshotUri, request.Method);
                request.Headers.Add("Authorization", value);
            }

            return (HttpWebResponse) await request.GetResponseAsync()
                .WithTimeoutAndCancellation(_connectionParameters.NetworkTimeout, token);

**Comment by davidsh** [comment] 2018-05-05 16:51
Based on reading the discussion on this issues and some workarounds that worked, I suspect the problem is related to several things.

What authentication schemes is the server requesting?  It sounds like either Negotiate or NTLM is being requested by the server.

Using default credentials from a Linux host trying to authenticate against a Windows Active Directory has many requirements in order to success.  The Linux machine must be "joined" to the Windows Active Directory domain.  This is usually done with a separate step using Kerberos tools on the Linux machine.

If both Negotiate and NTLM schemes are offered by the server, Negotiate will be chosen first since it is considered more secure. Negotiate has the ability to try Kerberos first. If that isn't possible, then NTLM will be tried. However, some Linux distros have problems with Negotiate and can't downgrade to NTLM. So, the authentication will fail with 401.

Any item to consider is that you usually must specify the domain name in the `NetworkCredential` constructor if you are passing explicit credentials on a Linux machine.  This isn't always required on the Windows machine because it can determine the default domain implicitly.

So this code pattern is usually recommended:

```c#
new NetworkCredential(_user, _password, "mydomain");
```

Since there are many variables here, it would be best if you could re-try the repro scenario.  Please attach WireShark and/or Fiddler traces so that we can see what kind of network traffic is being used especially in terms of what authentication schemes the server is attempting.

You might also want to try out the new .NET Core 2.1 Preview 2 release which uses a newer HTTP stack, SocketsHttpHandler:

See: https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/

For now, we'll close this issue.  But please report back when you have a new repro case.

**Closed** 2018-05-05 16:52 UTC
Labels: area-System.Net.Http, bug, needs more info, os-linux

**Comment by kwaazaar** [comment] 2019-10-18 14:37
The [SocketsHttpHandler only support basic auth](https://github.com/rmkerr/corefx/blob/f76c969782ff7e1bff099a1b1755d67b814aca95/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs#L177), so make sure you disable it there, as described in [the blogpost mentioned above](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/). Once you do, on Linux you will fallback to the CurlHandler, which [seems to have the fix](https://github.com/rmkerr/corefx/blob/f76c969782ff7e1bff099a1b1755d67b814aca95/src/System.Net.Http/src/System/Net/Http/CurlHandler/CurlHandler.cs#L593) mentioned above as well.

**Comment by davidsh** [comment] 2019-10-18 16:43
>The SocketsHttpHandler only support basic auth,

This isn't true.  HttpClient and all the handlers (i.e. SocketsHttpHandler) support Basic/Digest/NTLM/Negotiate schemes.

**Comment by kwaazaar** [comment] 2019-10-21 06:47
> > The SocketsHttpHandler only support basic auth,
> 
> This isn't true. HttpClient and all the handlers (i.e. SocketsHttpHandler) support Basic/Digest/NTLM/Negotiate schemes.

But check my link. What does that comment mean?:
"// Just look for basic credentials.  If in the future we support preauth
// for other schemes, this will need to search in order of precedence."

**Comment by davidsh** [comment] 2019-10-21 13:18
>But check my link. What does that comment mean?:
"// Just look for basic credentials. If in the future we support preauth
// for other schemes, this will need to search in order of precedence."

The comment is only about handling a certain kind of optimization for pre-authenticate where the 'Authorization:' request header can be added even before any HTTP 401/407 response code is returned by a server.

SocketsHttpHandler handles Basic/Digest/NTLM/Negotiate authentication flows and will use the .Credentials property as the credentials. It also handles these authentication schemes for proxy authentication as well as server authentication.
