### ISSUE TITLE
Intermittent Matrix4x4DecomposeTest01 failed in CI on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4833] opened 2015-12-04 18:03 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/19/console

```
08:54:36    System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01 [FAIL]
08:54:36       Matrix4x4.Decompose did not return expected value. Expected:<10, 20, 30> actual:<10, 20.19675, 30>.
08:54:36       Expected: True
08:54:36       Actual:   False
08:54:36       Stack Trace:
08:54:36             at System.Numerics.Tests.Matrix4x4Tests.DecomposeTest(Single yaw, Single pitch, Single roll, Vector3 expectedTranslation, Vector3 expectedScales)
08:54:36             at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01()
```

**Comment by mellinoe** [comment] 2015-12-04 18:13
Huh, that's a bizarre one. Did we just recently start to test this configuration or something?

**Comment by stephentoub** [comment] 2015-12-04 18:48
I believe we only just started running OS X release in the lab, though @mmitche can correct me if that's not true.  We did just start running them on every PR, which means we're running things more frequently.  This isn't failing consistently; this is the only time I saw it, but obviously that difference in value means something is going on.

**Comment by mmitche** [comment] 2015-12-04 18:55
It's running debug and release I believe.

**Comment by stephentoub** [comment] 2015-12-04 18:56
> It's running debug and release I believe.

Right, it is now.  But before your recent changes, it wasn't running release tests nightly with the debug tests nightly, was it?

**Comment by mellinoe** [comment] 2016-01-22 19:13
We attempted to get a repro of this (see discussion at dotnet/coreclr#2266), but even running on the same CI machine, with the same bits as one of the past failures, we were unable to get a repro. Since this seems to be such an obscure problem, I'm moving to Future but leaving it open for now. Hopefully we can get some better information in the future regarding why this happens. In any case, the issue is almost certainly in the runtime, as the code here is unchanged for a very long time and passes in all other configurations.

This is related (most likely same issue) to #4882 .

**Comment by stephentoub** [comment] 2016-06-05 23:20
These tests were re-enabled.  Closing the issue.

**Comment by stephentoub** [comment] 2016-07-10 20:26
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release/697/consoleText
```
     System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01 [FAIL]
        Matrix4x4.Decompose did not return expected value.
        Expected: True
        Actual:   False
        Stack Trace:
  /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release/bin/tests/AnyOS.AnyCPU.Release/System.Reflection.CoreCLR.Tests/netcoreapp1.0/System.Reflection.pdb already exists, not copying.
              at System.Numerics.Tests.Matrix4x4Tests.DecomposeTest(Single yaw, Single pitch, Single roll, Vector3 expectedTranslation, Vector3 expectedScales)
              at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01()
```

**Comment by stephentoub** [comment] 2016-09-15 03:59
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/162/consoleText
```
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01 [FAIL]
        Matrix4x4.Decompose did not return expected value Expected:<2, 3, 4> actual:<2, 2.459692, NaN>.
        Expected: True
        Actual:   False
        Stack Trace:
  Finished running tests. End time=15:47:33. Return value was 0
              at System.Numerics.Tests.Matrix4x4Tests.DecomposeTest(Single yaw, Single pitch, Single roll, Vector3 expectedTranslation, Vector3 expectedScales)
              at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4DecomposeTest01()
```

**Comment by karelz** [comment] 2016-09-26 21:45
This is tracking the occasional test failure in CoreFX, which is cause by some problem in Runtime/OS - see https://github.com/dotnet/coreclr/issues/2266

**Comment by stephentoub** [comment] 2016-10-19 19:44
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1816/

**Closed** 2016-11-18 13:13 UTC
Labels: area-System.Numerics, os-mac-os-x, tenet-reliability, test-run-core, tracking-external-issue
