### ISSUE TITLE
Turn on CheckForOverflowUnderflow on all projects in Debug

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3140] opened 2015-09-09 17:26 UTC
Right now, only System.Reflection.Metadata has CheckForOverflowUnderflow on in Debug.

I think there's value in doing this across the board. Expressions that are allowed to overflow by design should be explicitly marked `unchecked`.

cc @weshaggard @stephentoub

**Comment by weshaggard** [comment] 2015-09-09 17:54
Sounds like a good idea.

**Comment by mellinoe** [comment] 2016-11-11 19:01
@weshaggard Do you still think this is something we should enable? If we enable this across the board and don't see any errors, is it something we should just go ahead and do?

**Comment by stephentoub** [comment] 2016-11-11 19:05
> If we enable this across the board and don't see any errors

I'm 100% sure there will be errors / regressions if/when we enable this everywhere. ;)

**Comment by weshaggard** [comment] 2016-11-11 19:25
I do think this is probably worth doing, but I agree that it is likely not as simple as flipping a build configuration on.

**Comment by mellinoe** [comment] 2016-11-12 00:01
Yes I spoke too soon 😄 . We'd definitely need a lot of work to enable it globally. Perhaps it's smarter to start with a few valuable projects and see how much work it is.

**Comment by karelz** [comment] 2016-11-14 19:02
Next steps: Flip individual projects and mark code which overflows on purpose as unchecked.

**Comment by stephentoub** [comment] 2016-11-14 19:04
> Next steps

And measure critical paths to ensure nothing regresses perf-wise.

**Comment by nguerrera** [comment] 2016-11-14 19:10
> (unless we're only flipping the switch for debug, in which case it doesn't matter).

I opened this suggesting debug-only. I'd still recommend starting with that.

**Comment by dennisdietrich** [comment] 2017-01-31 20:23
I could take this one. Is it sufficient to run the outerloop tests after turning checks on for a project or is there anything else I should try?

**Comment by mellinoe** [comment] 2017-01-31 20:34
@dennisdietrich I think that would be a good start. Like @nguerrera said, it's probably a good idea to enable this for Debug builds only, to start. In order to do that, you can condition the property on `"'$(ConfigurationGroup)' == 'Debug'"` in the project file.

**Comment by dennisdietrich** [comment] 2017-01-31 20:37
@mellinoe, definitely. Performance aside, turning this on for Release obviously could introduce breaking changes in the form of unexpected exceptions being thrown. Very well, please assign to me.

**Comment by dennisdietrich** [comment] 2017-02-01 17:16
@mellinoe After thinking about this some more I don't think going for the individual project files is the right approach. We do want this for all projects so it makes more sense to have this in a props file used by all projects. I've noticed that there's already a whole bunch of them so I'll first check if any of those would be suitable (pointers welcome ;)).

**Comment by JonHanna** [comment] 2017-02-01 17:25
If you do it across all projects, it's very likely that there'd be a very large number of regressions, so you'd have to change all of those regressions, so it would likely be a massive one-shot PR. If you do it project by project it's more likely to lead to small easier-to-review PRs, and then the setting could be moved up to being global after that.

**Comment by karelz** [comment] 2017-02-01 17:27
For the sake of reviewers: Please do NOT do large PRs, break them up :)

**Comment by dennisdietrich** [comment] 2017-02-01 17:31
@JonHanna Fair enough. @karelz Also fair enough. Though, was exactly is considered 'large' in the corefx team? :)

**Comment by karelz** [comment] 2017-02-01 17:37
Imagine you doing the code review: For how long do you want to scroll down and review code?

Here's recent example of rather larger-ish PR: #15597. I would personally break it down into smaller chunks - it is easier to review each chunk in 1 session, rather than to remember where you last left off. If the chunk is large ... you are forced to push through all of it at once.
Just my 2 cents.

**Comment by dennisdietrich** [comment] 2017-02-01 19:51
Suspending further work on this until @stephentoub 's concerns raised in RP #15690 are addressed.

**Comment by danmosemsft** [comment] 2017-02-03 18:32
Another reason piecewise change can be nice is (if we merge without squashing) we can selectively revert or bisect if there's an issue that emerges.

**Comment by jkotas** [comment] 2017-02-05 19:01
FWIW, turning on overflow checks in debug builds by default was considered several times in full .NET Framework. It was never done because of it did not have positive ROI. It never found enough bugs to pay for its cost. There is a price you pay for diverging behavior of debug and release build, maintaining annotations in large body of the code, and dealing with bugs introduced by maintaining the annotations.

Having said that, doing experimental runs with overflow checks on and adding some annotations for the heavy hitters should be ok.

**Comment by jkotas** [comment] 2017-02-05 19:03
> measure critical paths to ensure nothing regresses perf-wise

I am pretty sure that turning this on for release builds is non-starter.

**Comment by dennisdietrich** [comment] 2017-02-09 00:19
Quick update: Including some code changes I haven't committed yet I'm down to about 50 failing inner loop test projects on Windows so it'll probably be a few more days until I'm done with that, after which I'll take a look at running inner loop on Linux (and after that, obviously, I'll check outer loop).

**Comment by tarekgh** [comment] 2017-02-09 00:22
thanks @dennisdietrich this is awesome!

**Comment by dennisdietrich** [comment] 2017-02-09 01:47
Just noticed some UAP PAL source files. Is that an environment I should check too? If so, how? The building and debugging instructions for Windows don't seem to mention UAP.

**Comment by karelz** [comment] 2017-02-09 01:50
We are just bringing UAP back to life, I think it is fine to skip it for now cc: @joperezr @weshaggard.

**Comment by dennisdietrich** [comment] 2017-02-09 18:39
@karelz Okay. What about endianness? I believe that ARM is typically bi-endinan (or fixed to little) and with Xbox having moved to x64 I don't think anyone cares about PowerPC anymore. Still, did just come across some PAL code with ```if# BIGENDIAN```so I wonder if there's anything I should check.

**Comment by karelz** [comment] 2017-02-09 18:42
How is endianness related to CheckForOverflowUnderflow? It should be transparent to most of the system, right?

**Comment by dennisdietrich** [comment] 2017-02-09 18:50
It is not, but keep in mind that I'm working my way through overflow exception; I'm not doing a manual code inspection so any code that's big-endian only will go untested with the current approach.

**Comment by karelz** [comment] 2017-02-09 20:53
I see.
We should make at least small effort to not change code which we won't cover in tests. That said, I expect we will make a few mistakes -- CI will catch such cases. If particular build is not covered by CI, I am fine discovering such issues later.

**Comment by dennisdietrich** [comment] 2017-02-09 20:55
Fair enough. That said, what about the System.IO.Ports tests? Since I'm running the tests in a VM that doesn't even have a (virtual) serial port I get 425 skipped tests. Is there a virtual null modem I could install to get those to run?

**Comment by dennisdietrich** [comment] 2017-02-13 22:00
Update: I have an almost clean inner loop run on Windows 10 at this point. Outer loop runs and inner loop on macOS and Ubuntu are not clean but as far as I can tell the failures are all due to environmental issues (e.g. DNS tests, HTTP tests, certificate tests). Regarding the last inner loop issue on Windows 10 I've already enlisted @tarekgh's support (thanks Tarek! :)) as I'm not sure what's going on.

**Comment by tarekgh** [comment] 2017-02-14 23:56
People on this issue, we are getting close to enable CheckForOverflowUnderflow for the whole corefx  for the debug build. this may happen in the next couple of days. please let's know if you have any concern before doing that. Thanks.

**Comment by dennisdietrich** [comment] 2017-02-15 16:18
@tarekgh @karelz I have not created a PR yet but I have prepared a new branch and **this one includes the change to dir.props**: https://github.com/dennisdietrich/corefx/commits/Unchecked-Part9
Local inner loop results:
 - Windows 10: Clean
 - macOS 10.12: A few failures due to my network setup (I think)
 - Ubuntu 16.04: Clean (one failure, but it's a known issue)
However, I can't get a clean outer loop run on any of my VMs but going through the test failures they still look like environmental issues. That said, at this point I would like to get test run results from the CI machines.
Also, I'd like to point out that there was at least one test (i.e. I only noticed and confirmed it in one case) that didn't consistently fail because of how the scenario used random data, so there may be issues left even in inner loop runs that I just haven't hit.

**Comment by tarekgh** [comment] 2017-02-15 16:38
@dennisdietrich you may start submitting the PR and enable all CI checks on this PR and let's look what is failing there and we can progress from there.

**Closed** 2017-02-16 22:42 UTC
Labels: area-Meta, enhancement, simple, up for grabs

**Comment by tarekgh** [comment] 2017-02-16 23:31
@dennisdietrich I would to thank you for all your work done here. that is really awesome.

**Comment by dennisdietrich** [comment] 2017-02-16 23:41
Don't mention it. Happy to contribute. :)

**Comment by karelz** [comment] 2017-02-17 05:11
Agreed, great job @dennisdietrich.
If you're interested in more CoreFX contributions,  would recommend to grab some ['up for grabs' issues](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22up%20for%20grabs%22%20-label%3Aapi-needs-work) (which are not API proposals) - the most valuable/impactful things are:
1. [2.0.0 (next release) up for grabs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A%22up%20for%20grabs%22%20milestone%3A2.0.0) issues
2. [wishlist](https://github.com/dotnet/corefx/labels/wishlist) issues
3. [simple](https://github.com/dotnet/corefx/labels/simple) issues for newbie contributors (not applied too much yet - we just started experimenting with it recently)

**Comment by dennisdietrich** [comment] 2017-02-17 06:57
@karelz Sure am. Looks like #14344 will be next.
