### ISSUE TITLE
HTTP2: Canceling token given to HttpClient.SendAsync does not send RST_STREAM

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#40904] opened 2019-09-06 21:29 UTC
Found by a customer: https://twitter.com/stevejgordon/status/1169995743568048129

This is a high impact bug. A user will cancel a streaming gRPC call on the client, but the server will never be notified. If the server is checking `CancellationToken.IsCancellationRequested` then it will hang open forever.

This is a regression of https://github.com/dotnet/corefx/issues/38391

Related: https://github.com/dotnet/corefx/issues/39049

---

Repro:
1. `git clone https://github.com/JamesNK/grpc-dotnet.git`
2. `git checkout jamesnk/duplex-cancellation-regression`
3. `dotnet test test\FunctionalTests --filter Name~ServerStreaming_CancellationOnClient_SentToServer`

Logic in the test is something like:
1. Client makes a server streaming call to the server. This means the client is sending one message in the request's HttpContent, which then completes.
2. Server streams multiple messages to the client
3. Client triggers the cancellation token given to gRPC client. HttpClient.SendAsync token is canceled
4. The HttpClient should be sending RST_STREAM to the server, and the server should report the call is canceled. This isn't happening so the server will stream messages forever.

Wireshark log: [cancellation-regression.zip](https://github.com/dotnet/corefx/files/3585848/cancellation-regression.zip)

**Comment by davidsh** [comment] 2019-09-06 21:32
@wfurt @geoffkizer @stephentoub

**Comment by stephentoub** [comment] 2019-09-06 21:34
@JamesNK, what version?  Is there a repro?  How does it differ from the test @wfurt says he added?  Etc.

**Comment by JamesNK** [comment] 2019-09-06 21:36
I'm writing a regression test now.

**Comment by JamesNK** [comment] 2019-09-06 21:37
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc1-014031
 Commit:    a4f411d3b7
```

**Comment by geoffkizer** [comment] 2019-09-06 21:45
To echo what @stephentoub said: how is this different from existing tests we have, either for GRPC or HttpClient? We know that cancellation does send RST_STREAM for the tests we have, so what's special about this?

**Comment by JamesNK** [comment] 2019-09-06 21:55
Repro and description of the test added.

**Comment by geoffkizer** [comment] 2019-09-06 22:03
In duplex scenarios, once SendAsync completes, the token you passed to it won't cancel the request anymore. See discussion in #39049.

What will cause the request to be cancelled is:
(1) If you throw while sending the request body. It sounds like in this scenario, the request body is already completed. Correct?
(2) If you dispose the response body before we've received it all, then we'll cancel the request. However, if we've already received the entire response body, then we won't (and can't) cancel the request, because it's already been fully received. Does that apply here?

**Comment by JamesNK** [comment] 2019-09-06 22:07
> In duplex scenarios, once SendAsync completes, the token you passed to it won't cancel the request anymore. See discussion in #39049.

I got the impression from reading the issue that the opposite was true.

**Comment by davidsh** [comment] 2019-09-06 22:07
>Edit: To clarify in (2) above, we won't and can't cancel the request if the request body is completed and the response body is fully received.

What does "fully received" even mean here?  When would it be fully received? The server is simply streaming messages constantly. Although at some point the server will stop.

**Comment by geoffkizer** [comment] 2019-09-06 22:09
> I got the impression from reading the issue that the opposite was true. 

See: https://github.com/dotnet/corefx/issues/39049#issuecomment-509871804

**Comment by geoffkizer** [comment] 2019-09-06 22:10
> What does "fully received" even mean here? When would it be fully received? The server is simply streaming messages constantly. Although at some point the server will stop.

Meaning we've received the end of the response stream (EndStream flag)

**Comment by JamesNK** [comment] 2019-09-06 22:11
Hmmm, ok. I was sure this worked at this point: https://github.com/dotnet/corefx/issues/38391

Theory: Maybe what was fixed then was that disposing wasn't sending a cancellation.

**Comment by wfurt** [comment] 2019-09-06 22:12
it should be clear from packet capture that we either should reach end of stream or send RST, right @geoffkizer ? If not that means operation did not finish and that would be bug.

**Comment by geoffkizer** [comment] 2019-09-06 22:13
> it should be clear from packet capture that we either should reach end of stream or send RST, right @geoffkizer 

Yep. Trying to look now, but wireshark is being weird.

**Comment by JamesNK** [comment] 2019-09-06 22:17
I think the current behavior is unexpected, but if there is no time to rethink/improve it in 3.0 then this could be fixed in the gRPC client. We can dispose the HttpResponseMessage on cancellation.

**Comment by geoffkizer** [comment] 2019-09-06 22:23
Unexpected in that you expect the cancellation token from SendAsync to cancel the request, even after SendAsync completes?

I agree it's not obvious. We went around on this in #39049, and this is where we landed. For better or worse, I think it's too late to change this.

**Comment by geoffkizer** [comment] 2019-09-06 22:25
The wireshark trace shows:

(1) Client sends a POST and full request body
(2) Server sends response headers and then sends partial response body chunks every ~1 second

So it looks like what's happening here is that because GRPC never disposes the response body, we are never sending a RST_STREAM. Changing GRPC to dispose the response body should fix this.

**Comment by JamesNK** [comment] 2019-09-06 22:30
Confirmed disposing HttpResponseMessage works and no other gRPC unit tests regressed.

**Comment by geoffkizer** [comment] 2019-09-06 22:37
I should add that the discussion in #39049 doesn't really apply here because it's not duplex.

It's always been the case that when you use ResponseHeadersRead and SendAsync completes, the cancellation token passed to SendAsync will no longer cancel receiving the response. This is how it works for HTTP/1.1 too.

**Comment by karelz** [comment] 2019-09-06 23:49
Looks like this is by design, closing.

**Closed by karelz** 2019-09-06 23:49 UTC
Labels: area-System.Net.Http
