### ISSUE TITLE
Fix perf hit from WinHttpGetProxyForUrl 

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28543] opened 2018-03-28 07:17 UTC
The recent addition of calling WinHttpGetProxyForUrl by default for each SocketsHttpHandler request on Windows is adding non-trivial overhead, at least 5% to each request in a local measurement.  We should avoid that.  For example, by using WinHttpDetectAutoProxyConfigUrl to see if there's an autoproxy, and if there isn't, caching that knowledge and then skipping WinHttpGetProxyForUrl for all subsequent requests.  We may also need/want to query WinHttpGetIEProxyConfigForCurrentUser in that case, again caching the results, similar to what's done on Unix.

cc: @karelz, @wfurt, @geoffkizer

**Comment by karelz** [comment] 2018-03-28 15:54
That sounds reasonable. @stephentoub @geoffkizer is it something you can help with? @wfurt's plate is rather full for the rest of the week :(

**Comment by karelz** [comment] 2018-03-28 22:15
2.1 decision: If there is no proxy, cache the information to optimize in that case.

**Comment by wfurt** [comment] 2018-03-29 05:40
BTW independent email thread mentioned network-change notifications.  Do we already have hook for that and if not, shall we consider it past 2.1?

**Comment by caesar1995** [comment] 2018-03-29 06:27
In corefx, we have `NetworkChange` class, which has `NetworkAvailabilityChanged` and `NetworkAddressChanged` events. But those cannot meet all the various network change events.

In framework, we have a `RasHelper` class help to detect it, which has below states:
```
enum RASCONNSTATE {
                RASCS_OpenPort = 0,
                RASCS_PortOpened,
                RASCS_ConnectDevice,
                RASCS_DeviceConnected,
                RASCS_AllDevicesConnected,
                RASCS_Authenticate,
                RASCS_AuthNotify,
                RASCS_AuthRetry,
                RASCS_AuthCallback,
                RASCS_AuthChangePassword,
                RASCS_AuthProject,
                RASCS_AuthLinkSpeed,
                RASCS_AuthAck,
                RASCS_ReAuthenticate,
                RASCS_Authenticated,
                RASCS_PrepareForCallback,
                RASCS_WaitForModemReset,
                RASCS_WaitForCallback,
                RASCS_Projected,
                RASCS_StartAuthentication,    // Windows 95 only
                RASCS_CallbackComplete,       // Windows 95 only
                RASCS_LogonNetwork,           // Windows 95 only
                RASCS_SubEntryConnected,
                RASCS_SubEntryDisconnected,
                RASCS_Interactive = RASCS_PAUSED,
                RASCS_RetryAuthentication,
                RASCS_CallbackSetByCaller,
                RASCS_PasswordExpired,
                RASCS_InvokeEapUI,
                RASCS_Connected = RASCS_DONE,
                RASCS_Disconnected
            }
```

We should consider porting the code to corefx if we decide to do the optimization, which seems like a overhead. (The `RasHelper` code is around [300 lines in Framework](https://github.com/Microsoft/referencesource/blob/90b323fe52bec428fe4bd5f007e9ead6b265d553/System/net/System/Net/UnsafeNativeMethods.cs#L183))

**Comment by karelz** [comment] 2018-03-30 21:19
Given this issue was discovered very close to ZBB cut off (3/29) and we couldn't finish the fix yet due to other higher priority bug fixes, marking it as Post-ZBB.

**Comment by caesar1995** [comment] 2018-04-11 21:30
Per offline discussion, the approach that: caching the result from `WinHttpDetectAutoProxyConfigUrl` to reduce the number of calling into `WinHttpGetProxyForUrl` is not acceptable. Because even if in general the cost is to do `WinHttpDetectAutoProxyConfigUrl` for the first request made per SocketsHttpHandler, it's still too high (10X regression in test). The detailed explanation is here: https://github.com/dotnet/corefx/pull/28965#issuecomment-380598185

If user want to achieve better performance when no proxy is used. They can specify `handler.UseProxy = false`, or uncheck the "Automatic detect settings" in IE settings, so that we will not calling into `WinHttpGetProxyForUrl`. From our side, there is nothing much we can do: if "Automatic detect settings" is on, we don't know for sure if proxy is used or not, thus it's risky to skip calling `WinHttpGetProxyForUrl`.

However, if "Automatic detect settings" is on, there is still optimization we can do to avoid calling into `WinHttpGetProxyForUrl` for every request - adding an error cache.
1. If `WinHttpGetProxyForUrl` returns true, we need to rely on `WinHttpGetProxyForUrl` to retrieve the proxy data for the specified URL. We cannot avoid this.
2. If `WinHttpGetProxyForUrl` returns false, depends on the error code, we can cache it and skip calling into `WinHttpGetProxyForUrl` for subsequent requests in a time period. For example, `ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT` could suggest server is not available right now, we can wait a while before calling `WinHttpGetProxyForUrl` again.

**Comment by karelz** [comment] 2018-04-11 22:24
@davidsh can you please help identify the behavior of `WinHttpGetProxyForUrl`? Especially if we can distinguish between no PAC file vs. no proxy returned by JavaScript. In the worst case we could consider caching result "no proxy for URL" for a period of time (in theory violating proxy rules).

Current thinking:
* Do not cache successfully found proxy (having overhead in such case is acceptable for now).
* Do not bother to cache transient errors (they are not contributing to the primary problem "5% perf overhead").
* Cache information that there is no PAC file for a while (if the information is available) or consider caching result "there is no proxy for this URL" for a while - let's decide collectively once we have the behavior confirmed.

**Comment by stephentoub** [comment] 2018-04-12 00:43
FYI, I think my initial "5%" estimate for what this is costing us is way off, at least for extreme cases.  I just tried a little make-shift test, with a process that just repeatedly times an HttpClient making 4000 requests to a dummy sockets host in the same process:
```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        using (var c = new HttpClient())
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(int.MaxValue);
            var ep = (IPEndPoint)listener.LocalEndPoint;
            var uri = new Uri($"http://{ep.Address}:{ep.Port}/");

            Task.Run(async () =>
            {
                while (true)
                {
                    Socket s = await listener.AcceptAsync();
                    var ignored = Task.Run(() =>
                    {
                        using (var ns = new NetworkStream(s))
                        using (var reader = new StreamReader(ns))
                        using (var writer = new StreamWriter(ns) { AutoFlush = true })
                        {
                            while (true)
                            {
                                while (!string.IsNullOrEmpty(reader.ReadLine())) ;
                                writer.Write("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nhello");
                            }
                        }
                    });
                }
            });

            var sw = new Stopwatch();
            while (true)
            {
                sw.Restart();
                for (int i = 0; i < 4000; i++)
                {
                    c.GetStringAsync(uri).Wait();
                }
                sw.Stop();
                Console.WriteLine($"Time: {sw.Elapsed.TotalSeconds:F4}");
            }
        }
    }
}
```
With my default proxy settings on my machine (Automatically Detect Settings is true but it doesn't find a configuration file), I get output like this:
```
Time: 0.7834
Time: 0.8677
Time: 0.8752
Time: 0.8321
```
When I then disable Automatically Detect Settings on my machine, it drops to this:
```
Time: 0.2741
Time: 0.2658
Time: 0.2811
Time: 0.2609
```
So that's not 5%, that's 3x.

**Comment by davidsh** [comment] 2018-04-12 00:58
I tried your experiment (your code above) on my dev box attached to the corporate network  And I don't see any difference from having that checkbox set vs not having it.

![image](https://user-images.githubusercontent.com/7684835/38650622-c90b2dca-3db1-11e8-87e8-829d118e21af.png)

**Comment by davidsh** [comment] 2018-04-12 01:07
Oops.  The numbers above are using .NET Core 2.0 which is using WinHttpHandler.  And that is always calling WinHttpGetProxyForUrl().

But when I ran your experiment on .NET Core 2.1 I did get results similar to you:

![image](https://user-images.githubusercontent.com/7684835/38650885-328d8756-3db3-11e8-8a1e-eb31beb80497.png)

**Comment by stephentoub** [comment] 2018-04-12 01:08
Using recent bits? What does dotnet --info show?

**Comment by stephentoub** [comment] 2018-04-12 01:08
Ah, good :)

**Closed** 2018-04-13 00:13 UTC
Labels: Post-ZBB, area-System.Net.Http.SocketsHttpHandler, enhancement, tenet-performance
