### ISSUE TITLE
dotnet-core MyGet gallery flags old version of package as latest

### ISSUE THREAD

**Issue by livarcocc** [dotnet/corefx#35263] opened 2019-02-12 17:31 UTC
@livarcocc commented on [Tue Feb 12 2019](https://github.com/dotnet/roslyn/issues/33324)

@KexyBiscuit commented on [Mon Feb 11 2019](https://github.com/dotnet/core-sdk/issues/466)

For example, [Microsoft.CSharp](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.CSharp) tells me that 4.6.0-preview1-27018-01 is the latest, but 4.6.0-preview.19111.6 is published today, why isn't that the latest? I wonder if there's some rule preventing ones from downloading the latest bit of these package, or it's just a operation mistake.

---

@livarcocc commented on [Tue Feb 12 2019](https://github.com/dotnet/core-sdk/issues/466#issuecomment-462846028)

Moving this to Roslyn. We don't produce this package on the SDK.

**Comment by filipnavara** [comment] 2019-02-12 17:39
It's an unfortunate consequence of the naming. MyGet sorts by the name, not the upload time, and the "preview1" vs "preview[X]" suffix is sorted incorrectly.

It was bothering me a lot too, but I am not sure whether MyGet is still going to be used, so I didn't care to open an issue for it. The move from dotnet/buildtools to dotnet/arcade seems to introduce new dependency flow that doesn't use MyGet anymore but instead publishes to some other feeds. Hopefully someone can provide more details.

**Comment by vcsjones** [comment] 2019-02-12 17:50
I think this is "correct" according to the semver v2 spec which I believe MyGet tries to respect.

>A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1

That would seem then to imply that "preview" < "preview1", so I don't think this is an issue with myget, just that the labels used in the package version make it so that official previews always have a "higher" version number than nightlies.

**Comment by filipnavara** [comment] 2019-02-12 18:08
@vcsjones Thanks for insight. I didn't even realize that it could have been deliberate :-)

**Comment by ViktorHofer** [comment] 2019-02-12 22:05
Right that's because of a change in the labeling schema. The current situation is not ideal but will be resolved when .NET Core 3 is released. Also we are probably going to move to the blob feed only. Closing as by design.

**Closed by ViktorHofer** 2019-02-12 22:05 UTC
Labels: area-Infrastructure
