### ISSUE TITLE
[HttpListener][Porting] authentication failures with GetContextAsync throw an Unhandled inner exception for NativeOverlapped used for multiple operations

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#20400] opened 2017-05-27 04:43 UTC
Steps to reproduce:

1. Pull in this commit https://github.com/hughbe/corefx/commit/aa948b02cc9ad4f23fde77502382f5f6a9c42e8b
2. Run the tests

Observe:

```
Discovering: System.Net.HttpListener.Tests
  Discovered:  System.Net.HttpListener.Tests
  Starting:    System.Net.HttpListener.Tests

  Unhandled Exception:
  Unhandled Exception:
  Unhandled Exception:
  Unhandled Exception: System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOv
  erlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOve
  rlapped* pOVERLAP)
  System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOv
  erlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOve
  rlapped* pOVERLAP)
  System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOv
  erlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOve
  rlapped* pOVERLAP)
  System.InvalidOperationException: NativeOverlapped cannot be reused for multiple operations.
     at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOv
  erlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOve
  rlapped* pOVERLAP)

  Finished running tests.  End time=11:41:39.75, Exit code = -532462766
```

@CIPop you were taking a look at authentication recently

**Comment by hughbe** [comment] 2017-05-27 04:45
Also something is completely off with the stack traces. Visual Studio gives me the following:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=NativeOverlapped cannot be reused for multiple operations.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

```

**Comment by karelz** [comment] 2017-05-28 19:14
Is it difference against Desktop?

**Comment by hughbe** [comment] 2017-05-29 02:16
Yes. Windows netcoreapp has this bug, netfx doesn't

**Comment by stephentoub** [comment] 2017-05-30 02:48
I suggest this be looked at for 2.0. cc: @cipop, @davidsh, @schen381

**Comment by CIPop** [comment] 2017-06-01 23:15
Thanks @hughbe for reporting this! It may be that after fixing the NRE exception we are now uncovering other lifetime issues with the IOCP handle. 

@DavidGoll @davidsh @karelz 

The implementation in CoreFX differs substantially from the one in Framework with regard to overlapped operations. I agree with @stephentoub: this needs to be investigated and fixed, ideally in 2.0.

**Comment by CIPop** [comment] 2017-06-07 17:46
/cc @DavidGoll @karelz 

The issue is caused by an incorrect re-use of a `NativeOverlapped` struct.
The code responsible with IOCP for HttpListener has been substantially changed part of the .Net Core as the ThreadPool IOCP API contracts are different in Core vs Desktop.

A short summary of IOCP operations in .Net Core: a `ThreadPoolBoundHandle` is used to associate a `SafeHandle` (in this case the `HttpRequestQueueV2Handle`) with a thread-pool that will be used by asynchronous operations completions. For each I/O, a new `NativeOverlapped` struct is required (reusing them will cause this error).

I have two findings:

1. The place where the failure originates is not immediately apparent as the stack includes only the IOCP thread:
```
0e:M 0000003d6a97f110 00007ffb83810566 System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)(+0x0 IL,+0x29eb96 Native) [E:\A\_work\750\s\src\mscorlib\src\System\Threading\ClrThreadPoolBoundHandleOverlapped.cs @ 34,13]
0f:M 0000003d6a97f160 00007ffb8356d7a3 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)(+0x32 IL,+0x73 Native) [E:\A\_work\750\s\src\mscorlib\src\System\Threading\Overlapped.cs @ 102,21]
```

Determining which operation failed from code-review only is not possible as the code is using multiple patterns for IOCP operations using the HttpRequestV2Handle: `AsyncRequestContext`/`ListenerAsyncResult`, `DisconnectAsyncResult`, `ListenerClientCertAsyncResult`, `HttpRequestStreamAsyncResult`, `HttpResponseStreamAsyncResult` and `WebSocketHttpListenerDuplexStream`. 

From the stack I noticed that when this issue occurs on multiple threads, the handle corresponding to the `ThreadPoolBoundHandle` is disposed:

```
0:021> !mdt 000001a3d96742c0
000001a3d96742c0 (System.Threading.ThreadPoolBoundHandle)
    _handle:000001a3d9674168 (System.Net.HttpRequestQueueV2Handle)
    _isDisposed:true (System.Boolean)   <-----------------
```

According to @kouvel it is OK to dispose of the TPBH even if there are IOCP operations still pending: all operations will be cancelled internally by the new Core ThreadPool (based on the Windows ThreadPool).

2. By looking at the `_userState` of the `ThreadPoolBoundHandleOverlapped` found on a faulty stack, I believe that the operation causing this problem is derived from a `ListenerAsyncResult`/`AsyncRequestContext`:

```
0:021> !mdt 000001a3d9a7a5f0
000001a3d9a7a5f0 (System.Threading.ThreadPoolBoundHandleOverlapped)
    m_overlappedData:000001a3d9a5b2e8 (System.Threading.OverlappedData)
    _userCallback:000001a3d9a5a860 (System.Threading.IOCompletionCallback)
    _userState:000001a3d9674268 (System.Object)    <-----------------
    _preAllocated:NULL (System.Threading.PreAllocatedOverlapped)
    _nativeOverlapped:000001a3d9a5b330 (System.UIntPtr)
    _boundHandle:000001a3d96742c0 (System.Threading.ThreadPoolBoundHandle)
    _completed:true (System.Boolean)

0:021> !mdt 000001a3d9674268 
000001a3d9674268 (System.Net.ListenerAsyncResult)    <-----------------
    _debugAsyncChain:0000000000000000 (System.Object)
    _protectState:false (System.Boolean)
    _asyncObject:000001a3d9671d00 (System.Object)
    _asyncState:000001a3d9671d00 (System.Object)
    _asyncCallback:000001a3d9674228 (System.AsyncCallback)
    _result:000001a3d9619de8 (System.Object)
    _errorCode:0x0 (System.Int32)
    _intCompleted:0x80000000 (System.Int32)
    _endCalled:false (System.Boolean)
    _userEvent:false (System.Boolean)
    _event:0000000000000000 (System.Object)
    _requestContext:000001a3d96742e0 (System.Net.AsyncRequestContext)    <-----------------
```

Next, I will be reviewing the code to understand how(/if) this particular object is guaranteeing unique usages of `NativeOverlapped` structures.

**Comment by karelz** [comment] 2017-06-09 20:39
Reopening to track port to release/2.0.0

**Comment by CIPop** [comment] 2017-06-16 03:06
Keeping this open: need to forward-port changes made after @DavidGoll PR in #21100.

**Comment by DavidGoll** [comment] 2017-06-16 23:49
release/2.0.0 port has been merged. The follow-up change is for the next milestone.

**Comment by karelz** [comment] 2017-06-17 00:45
Please file a separate bug for the follow up. Closing this one with 2.0 milestone.

**Closed by karelz** 2017-06-17 00:45 UTC
Labels: area-System.Net.Http, bug, os-windows, tenet-compatibility
