### ISSUE TITLE
System.IO.FileSystem can't find System.Runtime.Extensions

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#3018] opened 2015-08-30 09:59 UTC
Specifically, when building the project from VS, the output message is:

> Could not copy the file "C:\Users\xande\repositories\corefx\bin\Windows_NT.AnyCPU.Debug\System.Runtime.Extensions.CoreCLR\System.Runtime.Extensions.dll" because it was not found.

...and it does it even when the current compile target is **not** Windows Debug.

Rebuilding System.Runtime.Extensions via command line/VS adds the requested file.
(side note: would it be too much to ask to get the default compile target to be the host platform?  It's not like I can run anything made when it defaults to FreeBSD et al...)

**Comment by weshaggard** [comment] 2015-09-04 19:09
@JeremyKuhne do you think this is related to your changes?

**Comment by stephentoub** [comment] 2015-09-16 13:39
@Clockwork-Muse, are you still hitting this?

**Comment by JeremyKuhne** [comment] 2015-09-16 18:02
@Clockwork-Muse it is possible to make Windows the default- it is alphabetical. We'd have to change the solution configuration name in the sln files from Windows to _Windows. There is no way to dynamically switch, but .sln files are essentially VS and therefore Windows specific.

@weshaggard This shouldn't have anything to do with my changes.

**Comment by Clockwork-Muse** [comment] 2015-09-16 21:28
@JeremyKuhne - I don't think I'd want to break the naming scheme like that.  I was more curious if there was some form of conditional ordering available, but in that case probably not.

**Comment by Clockwork-Muse** [comment] 2015-09-18 05:52
@stephentoub - yes, I am.  
It looked like the csproj references were still there, so I removed them (since there's nuget references).  PR is #3305 .

Now we just have to figure out why VS is complaining about not being able to install targets/props in the case of multiple frameworks (only warnings, builds otherwise).

**Comment by weshaggard** [comment] 2015-09-30 06:02
@Clockwork-Muse I suspect this issue might be caused by the same root issue that was fixed with https://github.com/dotnet/corefx/pull/3413. Can you please verify that this helps or not?

**Comment by weshaggard** [comment] 2016-01-02 23:25
I believe this is fixed by #3413 so closing. Please re-open if this issue still persists for you @Clockwork-Muse.

**Closed by weshaggard** 2016-01-02 23:25 UTC

**Comment by Clockwork-Muse** [comment] 2016-01-03 03:50
@weshaggard - Actually, it didn't.  The process was still complaining if the file didn't exist previously.  However, it's now possible to remove the project references and rely on the nuget packages, so I submitted a PR for that.

Not sure how I missed this earlier....
