### ISSUE TITLE
System.InvalidOperationException on calling Process.GetCurrentProcess().StartInfo

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#38059] opened 2019-05-30 13:41 UTC
I was porting one of my applications and the following line of code fails in .NET Core 3 while it works perfectly fine in .NET Framework (WPF application):

`var startInfo = Process.GetCurrentProcess().StartInfo;`

Exception:
```
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll
Process was not started by this object, so requested information cannot be determined.
```
Happens when running within VS and outside. If this exception is expected to happen, how can I port this line of code to .NET Core 3 ? Is there an alternative to retrieve the start info object of the current process?

**Comment by vcsjones** [comment] 2019-05-30 14:09
This is likely a duplicate of #37674.

**Comment by Symbai** [comment] 2019-05-30 15:05
Everything. I'm using this to restart my application with or without runas flag. I need to make sure it's launched exactly the same as before (same command arguments, same environments, same start directory) etc.

**Closed** 2019-05-30 15:24 UTC
