### ISSUE TITLE
Several x86 intrinsic APIs are "missing"

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#25926] opened 2017-12-14 19:10 UTC
In the process of adding the APIs for #23519 (see https://github.com/dotnet/coreclr/pull/15341), I found several non-scalar x86 intrinsic APIs that are "missing".

We should determine which of these need to be added and which were explicitly excluded.

```
int _mm_movemask_ps (__m128 a)                                      // movmskps

__m128d _mm_loadh_pd (__m128d a, double const* mem_addr)            // movhpd
__m128d _mm_loadl_pd (__m128d a, double const* mem_addr)            // movlpd
__m128i _mm_loadl_epi64 (__m128i const* mem_addr)                   // movq

void _mm_stream_si32 (int* mem_addr, int a)                         // movnti
void _mm_stream_si64 (__int64* mem_addr, __int64 a)                 // movnti

__m256i _mm256_permute2f128_si256 (__m256i a, __m256i b, int imm8)  // vperm2f128

__m256i _mm256_stream_load_si256 (__m256i const* mem_addr)          // vmovntdqa

// The following 8 have intrinsics which take an imm8 and emit the same underlying instruction
__m128i _mm_sll_epi16 (__m128i a, __m128i count)                    // psllw
__m128i _mm_sll_epi32 (__m128i a, __m128i count)                    // pslld
__m128i _mm_sll_epi64 (__m128i a, __m128i count)                    // psllq
__m128i _mm_sra_epi16 (__m128i a, __m128i count)                    // psraw
__m128i _mm_sra_epi32 (__m128i a, __m128i count)                    // psrad
__m128i _mm_srl_epi16 (__m128i a, __m128i count)                    // psrlw
__m128i _mm_srl_epi32 (__m128i a, __m128i count)                    // psrld
__m128i _mm_srl_epi64 (__m128i a, __m128i count)                    // psrlq

// The following 6 have the corresponding _mm256 forms exposed
__m128i _mm_sllv_epi32 (__m128i a, __m128i count)                   // vpsllvd
__m128i _mm_sllv_epi64 (__m128i a, __m128i count)                   // vpsllvq
__m128i _mm_srav_epi32 (__m128i a, __m128i count)                   // vpsravd
__m128i _mm_srlv_epi32 (__m128i a, __m128i count)                   // vpsrlvd
__m128i _mm_srlv_epi64 (__m128i a, __m128i count)                   // vpsrlvq
```

**Comment by tannergooding** [comment] 2017-12-14 19:12
From the discussion so far on dotnet/coreclr#15341.

`int _mm_movemask_ps (__m128 a)` is missing from `Sse`. It was an oversight and the corresponding `Sse2` intrinsic already exists.

`__m256i _mm256_permute2f128_si256 (__m256i a, __m256i b, int imm8)` is discouraged from use due to a data bypass penalty, but we may be able to complement the types to make the API simpler via `Permute2x128<T>`.

**Comment by tannergooding** [comment] 2017-12-14 19:14
`void _mm_stream_si32 (int* mem_addr, int a)` and `void _mm_stream_si64 (__int64* mem_addr, __int64 a)` are streaming store for scalar types. There needs to be further thought about their usefulness

**Comment by tannergooding** [comment] 2017-12-14 19:14
CC. @fiigii. Moved the discussion here so that dotnet/coreclr#15341 stays on track and isn't blocked by this.

**Comment by 4creators** [comment] 2017-12-14 19:26
```
// The following 8 have intrinsics which take an imm8 and emit the same underlying instruction
__m128i _mm_sll_epi16 (__m128i a, __m128i count)                    // psllw
__m128i _mm_sll_epi32 (__m128i a, __m128i count)                    // pslld
__m128i _mm_sll_epi64 (__m128i a, __m128i count)                    // psllq
__m128i _mm_sra_epi16 (__m128i a, __m128i count)                    // psraw
__m128i _mm_sra_epi32 (__m128i a, __m128i count)                    // psrad
__m128i _mm_srl_epi16 (__m128i a, __m128i count)                    // psrlw
__m128i _mm_srl_epi32 (__m128i a, __m128i count)                    // psrld
__m128i _mm_srl_epi64 (__m128i a, __m128i count)                    // psrlq
```
IMO we should implement them with imm8. This allows for faster implementations as call may skip Vector creation and setting shift values on Vector. The missing language feature for supporting immediate / compile constants parameters can be compensated with analyzer and attribute like previously discussed (I can implement support for this feature).

**Comment by 4creators** [comment] 2017-12-14 19:28
Ahh forgot it - we should have corresponding AVX/AVX2 instructions as well. They really can be very handy in many situations.

**Comment by karelz** [comment] 2017-12-15 01:13
cc @CarolEidt @RussKeldorph

**Comment by 4creators** [comment] 2017-12-15 01:26
> // The following 8 have intrinsics which take an imm8 and emit the same underlying instruction

Emitted instruction is not the same for imm8 and _mm128i / _mm256i arguments, encoding is different.

**Comment by tannergooding** [comment] 2017-12-15 01:32
> Emitted instruction is not the same for imm8 and _mm128i / _mm256i arguments, encoding is different.

The encoding is different, but it is still `psll*`, `psra*`, and `psrl*`, which is what I meant.

**Comment by 4creators** [comment] 2017-12-20 09:48
There is a large class of instructions missing: all that may take as an argument both SIMD register `xmm`, `ymm` or memory address i.e.:

```
__m128i _mm_add_epi64 (__m128i a,  __m128i b)
paddq xmm, xmm
public static Vector128<ulong> Add(Vector128<ulong> left, Vector128<ulong> right);
// missing
paddq xmm, m128
public static unsafe Vector128<ulong> Add(Vector128<ulong> left, ulong* right);
```
_it could be that there was Api Review decision to not implement these variants, than this would be to just remind what is missing by design_

cc @tannergooding @fiigii

**Comment by mikedn** [comment] 2017-12-20 09:53
> public static unsafe Vector128<ulong> Add(Vector128<ulong> left, Vector128<ulong>* right);

What for? You can just write `Add(left, *pRight)`.

**Comment by 4creators** [comment] 2017-12-20 09:55
> What for? You can just write Add(left, *pRight)

Providing RyuJIT will generate `paddq xmm, m128` without separate load instruction.

**Comment by fiigii** [comment] 2017-12-20 09:55
@4creators We do not expose these reg-mem/mem-reg instructions as intrinsics. The compiler will fold `Load`/`Store` into `paddq xmm, m128`. Please see the discussion https://github.com/dotnet/coreclr/pull/15538#issuecomment-352090230

**Comment by 4creators** [comment] 2017-12-20 09:56
@fiigii OK I have expected it was by design.

**Comment by 4creators** [comment] 2017-12-21 00:05
@fiigii @tannergooding 
Just went through SSE2 shift intrinsics again and based on the list from top post and my double check it seems we are missing:
1. the following logical shifts:
```C#
       /// <summary>
        /// __m128i _mm_sll_epi16 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<short> ShiftLeftLogical(Vector128<short> value, Vector128<short> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_sll_epi16 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<ushort> ShiftLeftLogical(Vector128<ushort> value, Vector128<ushort> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_sll_epi32 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<int> ShiftLeftLogical(Vector128<int> value, Vector128<int> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_sll_epi32 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<uint> ShiftLeftLogical(Vector128<uint> value, Vector128<uint> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_sll_epi64 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<long> ShiftLeftLogical(Vector128<long> value, Vector128<long> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_sll_epi64 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<ulong> ShiftLeftLogical(Vector128<ulong> value, Vector128<ulong> count) => ShiftLeftLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi16 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<short> ShiftRightLogical(Vector128<short> value, Vector128<short> count) => ShiftRightLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi16 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<ushort> ShiftRightLogical(Vector128<ushort> value, Vector128<ushort> count) => ShiftRightLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi32 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<int> ShiftRightLogical(Vector128<int> value, Vector128<int> count) => ShiftRightLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi32 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<uint> ShiftRightLogical(Vector128<uint> value, Vector128<uint> count) => ShiftRightLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi64 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<long> ShiftRightLogical(Vector128<long> value, Vector128<long> count) => ShiftRightLogical(value, count);
        /// <summary>
        /// __m128i _mm_srl_epi64 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<ulong> ShiftRightLogical(Vector128<ulong> value, Vector128<ulong> count) => ShiftRightLogical(value, count);
```
2. the following right arithmetic shifts:

```C#
        /// <summary>
        /// __m128i _mm_sra_epi16 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<short> ShiftRightArithmetic(Vector128<short> value, Vector128<short> count) => ShiftRightArithmetic(value, count);
        /// <summary>
        /// __m128i _mm_sra_epi32 (__m128i a,  int immediate)
        /// </summary>
        public static Vector128<int> ShiftRightArithmetic(Vector128<int> value, Vector128<int> count) => ShiftRightArithmetic(value, count);
```

Can we have decision on implementing these APIs and get them merged?

**Comment by fiigii** [comment] 2017-12-21 00:40
@4creators Thank you! Actually, I already have a fix on my local machine. Will upload tomorrow.

**Comment by 4creators** [comment] 2017-12-21 00:51
> Actually, I already have a fix on my local machine. Will upload tomorrow.
Great to hear that 😄

**Comment by tannergooding** [comment] 2017-12-24 19:02
The `Shuffle` APIs are also going to be less than easy to work with.

With MSVC, they provide a `_MM_SHUFFLE` macro:
```
 /*******************************************************/
 /* MACRO for shuffle parameter for _mm_shuffle_ps().   */
 /* Argument fp3 is a digit[0123] that represents the fp*/
 /* from argument "b" of mm_shuffle_ps that will be     */
 /* placed in fp3 of result. fp2 is the same for fp2 in */
 /* result. fp1 is a digit[0123] that represents the fp */
 /* from argument "a" of mm_shuffle_ps that will be     */
 /* places in fp1 of result. fp0 is the same for fp0 of */
 /* result                                              */
 /*******************************************************/
#define _MM_SHUFFLE(fp3,fp2,fp1,fp0) (((fp3) << 6) | ((fp2) << 4) | \
                                     ((fp1) << 2) | ((fp0)))
```

However, C# doesn't provide any macros nor does it support `constexpr`.

As such, you will end up having to make your code extra verbose or have additional comments to ensure you understand how the values are being shuffled.

It might be helpful to have an intrinsic for generating the immediate value passed into `Shuffle` (the intrinsic would need to always be constant folded).

Thoughts?

**Comment by fiigii** [comment] 2017-12-25 01:57
> It might be helpful to have an intrinsic for generating the immediate value passed into Shuffle (the intrinsic would need to always be constant folded).

The dynamic semantic makes sense, but the static semantic seems not working with `const` parameters.

**Comment by tannergooding** [comment] 2018-01-04 16:35
> The dynamic semantic makes sense, but the static semantic seems not working with const parameters.

I'm not sure what you mean?

I am proposing we add a `byte Sse.ShuffleParameter(byte fp3, byte fp2, byte fp1, byte fp0)` API. Said API would require that all four parameters are `GT_CNS_INT`. The importer would then transform it to a gtIconNode with a value of `(fp3 << 6) | (fp2 << 4) | (fp1 << 2)) | fp0`

Users would then need to consume that via: `Sse.Shuffle(left, right, Sse.ShuffleParameter(3, 2, 1, 0))` (for example). At the very least, it maintains the requirement that `imm8` be constant and is significantly easier to understand/read than `Sse.Shuffle(left, right, 228)` or `Sse.Shuffle(left, right, ((3 << 6) | (2 << 2) | (1 << 2) | 0))`

**Comment by fiigii** [comment] 2018-01-04 16:47
I meant Roslyn cannot recognize the return value of ShuffleParameter as `const`(we don’t have the `constexpr`).

**Comment by tannergooding** [comment] 2018-01-04 16:58
Yes. It would need to be handled by the JIT, but provided that `ShuffleParameter` is folded (and it can be, provided all four arguments passed to it are GT_CNS_INT), it should work in all the same places that directly specifying a constant would.

**Comment by fiigii** [comment] 2018-01-04 17:01
But it would need to be handled by Roslyn also.

**Comment by tannergooding** [comment] 2018-01-04 17:01
> But it would need to be handled by Roslyn also.

Why?

**Comment by mikedn** [comment] 2018-01-04 17:03
Roslyn does not need to be involved in this. As long as the JIT recognizes `ShuffleParameter` everything should work fine. In fact, it's not even necessary that the JIT specifically recognizes `ShuffleParameter`, aggressive inlining should be enough.

**Comment by fiigii** [comment] 2018-01-04 17:06
We will change these IMM intrinsic APIs to have `const byte control`.

**Comment by tannergooding** [comment] 2018-01-04 17:10
> We will change these IMM intrinsic APIs to have `const byte control`

I thought that the language team decided to not support that at this time and that an analyzer "should" be sufficient.

**Comment by tannergooding** [comment] 2018-01-04 17:13
Ah, no, it looks like it hasn't gone to LDM (and if it has, the notes might not be up yet).

The PR proposing the functionality (https://github.com/dotnet/csharplang/pull/886) has had quite a bit of pushback due to the ease of implementing it as an analyzer and cost of implementing it in the language.

**Comment by tannergooding** [comment] 2018-01-05 21:09
> In fact, it's not even necessary that the JIT specifically recognizes ShuffleParameter, aggressive inlining should be enough.

@mikedn, I didn't think aggressive inlining worked under `minopts`?

**Comment by mikedn** [comment] 2018-01-05 21:16
>  I didn't think aggressive inlining worked under minopts?

Ah, minopts, that may be a problem :smile:

**Comment by 4creators** [comment] 2018-01-06 00:58
> I thought that the language team decided to not support that at this time and that an analyzer "should" be sufficient.

AFAIR there was short discussion about proposal during LDM but I do not know what is final decision - short discussion resulted in analyzer is OK (see https://github.com/dotnet/roslyn/issues/22304), however, some csharplang memebers were quite positive about implementing it.

**Comment by 4creators** [comment] 2018-01-06 02:31
Ahh, I am always forgetting to ask about special intrinsics like:

```C++

// Hardware random data generation

int _rdrand16_step (unsigned short* val)
int _rdrand32_step (unsigned int* val)
int _rdrand64_step (unsigned __int64* val)

int _rdseed16_step (unsigned short * val)
int _rdseed32_step (unsigned int * val)
int _rdseed64_step (unsigned __int64 * val)

// Hashing intrinsics - not necessarily only for cryptographic applications
sha1msg1
__m128i _mm_sha1msg1_epu32 (__m128i a, __m128i b)
sha1msg2
__m128i _mm_sha1msg2_epu32 (__m128i a, __m128i b)
sha1nexte
__m128i _mm_sha1nexte_epu32 (__m128i a, __m128i b)
sha1rnds4
__m128i _mm_sha1rnds4_epu32 (__m128i a, __m128i b, const int func)
sha256msg1
__m128i _mm_sha256msg1_epu32 (__m128i a, __m128i b)
sha256msg2
__m128i _mm_sha256msg2_epu32 (__m128i a, __m128i b)
sha256rnds2
__m128i _mm_sha256rnds2_epu32 (__m128i a, __m128i b, __m128i k)

// Memory control
void _mm_clflushopt (void const * p)
void _mm_clwb (void const * p)

// Missing Sse2
void _mm_clflush (void const* p)
void _mm_mfence (void)

// Some utilities
unsigned __int64 __rdtscp (unsigned int * mem_addr)
```

Should we add them with this PR?
@CarolEidt  @tannergooding @fiigii @jkotas

**Comment by tannergooding** [comment] 2018-01-06 02:49
@4creators, there are a number of other hardware instructions for which exposing intrinsics may be useful.

However, I don't think we want to get too far ahead of ourselves right now.

We already have enough intrinsics to cover the next 2 point releases (2.1 and whatever the next version is) and they will take some time to implement, test, and tune.

Not to mention that the ARM work will be going on in parallel.

It might be useful to have an issue listing the hardware instructions we should investigate in the future, but I don't think we should be adding any more at this time (and likely not until our current backlog clears more).

This issue was specifically tracking the intrinsics that were part of the approved list of x86 ISAs, but which were missed in the initial PR (it was also a useful place to mention the `ShuffleParam` idea, since an equivalent is traditionally part of the intrinsics/macros provided for the approved ISAs).

**Comment by 4creators** [comment] 2018-01-22 14:56
There are still couple of Sse2 HW intrinsics missing either as missing instruction or missing overload:

```C#
// __m128i _mm_move_epi64 (__m128i a)
public static Vector128<long> MoveScalar(Vector128<long> upper, Vector128<long> value) => MoveScalar(upper, value);
public static Vector128<ulong> MoveScalar(Vector128<ulong> upper, Vector128<ulong> value) => MoveScalar(upper, value);

// __m64 _mm_movepi64_pi64 (__m128i a)
public static long* StoreScalar(Vector128<long> value);
public static ulong* StoreScalar(Vector128<ulong> value);

// void _mm_clflush (void const* p)
public static void FlushCache(void* p);

// void _mm_mfence (void)
public static void MemoryFence();
```
cc @fiigii @tannergooding

**Comment by tannergooding** [comment] 2018-02-08 17:09
This should be resolved now.

**Closed** 2018-02-08 17:09 UTC
Labels: api-needs-work, area-System.Runtime.Intrinsics
