### ISSUE TITLE
ManagedHandler: ManagedHandler_DefaultCredentialsTest tests are disabled

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#23140] opened 2017-08-11 12:50 UTC
These tests are disabled for the managed handler.  They need to be investigated and either src or tests fixed.

**Comment by wfurt** [comment] 2017-08-23 18:39
This one is only for windows platforms.

**Comment by Priya91** [comment] 2017-09-07 22:16
These tests are for testing credentials with negotiate and ntlm auth. The infrasturcture to run these tests doesn't exist yet, closing this bug as dupe of #10041

**Closed by Priya91** 2017-09-07 22:16 UTC
Labels: area-System.Net.Http, wishlist

**Comment by davidsh** [comment] 2017-09-07 22:21
cc: @karelz

**Comment by Priya91** [comment] 2017-09-07 22:22
@davidsh I was just creating a PR as we speak :)

**Comment by davidsh** [comment] 2017-09-07 22:22
ok.  sounds good.  But to avoid confusion, please close the issue after the PR? As you can see, I was confused. :)

**Comment by karelz** [comment] 2017-09-07 22:36
Should we assign it to @Priya91 then? Or will it be just partial fix?
