### ISSUE TITLE
[BigInteger] Parse test with trailing spaces fails on some cultures

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#1642] opened 2015-05-06 13:27 UTC
```
System.Numerics.Tests.parseTest.RunParseToStringTests [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.FormatException)
    Actual:   (No exception was thrown)
    Stack Trace:
       m:\Workspace\github\corefx\src\System.Runtime.Numerics\tests\BigInteger\parse.cs(408,0): at System.Numerics.Tests.parseTest.VerifyParseToString(String num1, NumberStyles ns, Boolean failureNotExpected, String expected)
       m:\Workspace\github\corefx\src\System.Runtime.Numerics\tests\BigInteger\parse.cs(380,0): at System.Numerics.Tests.parseTest.VerifyParseToString(String num1, NumberStyles ns, Boolean failureNotExpected)
       m:\Workspace\github\corefx\src\System.Runtime.Numerics\tests\BigInteger\parse.cs(247,0): at System.Numerics.Tests.parseTest.VerifyNumberStyles(NumberStyles ns, Random random)
       m:\Workspace\github\corefx\src\System.Runtime.Numerics\tests\BigInteger\parse.cs(33,0): at System.Numerics.Tests.parseTest.RunParseToStringTests()
Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
System.Runtime.Numerics.Tests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 20,751s
```

Repro steps:
1. Start->Run (WinKey + R) -> intl.cpl
2. Change format (no need to change locale) to Ukrainian (Ukraine)
3. `build /p:WithCategories=OuterLoop`

**Possible solution:** https://github.com/dotnet/corefx/pull/1592#issuecomment-99520215

**Comment by Maxwe11** [comment] 2015-05-07 13:58
Possible solution https://github.com/dotnet/corefx/pull/1592#issuecomment-99520215

**Comment by AlexGhiondea** [comment] 2016-12-05 21:39
Looks like we know what needs to happen here. It is a simple fix that would be a great place to start looking at the CoreFx code.

**Comment by dennisdietrich** [comment] 2017-01-26 04:14
I'm looking for an opportunity to get started contributing to .NET Core. Would it be possible to get this issue assigned to me?

**Comment by mellinoe** [comment] 2017-01-26 18:36
> I'm looking for an opportunity to get started contributing to .NET Core. Would it be possible to get this issue assigned to me?

Sure!

I'll try to give you an updated set of instructions to use to repro this. Since this was filed so long ago (almost 2 years), we're not even sure if it still repros. Chances are it still does, though, because none of us run the tests in a Ukrainian environment as far as I know.

Steps:
* Clone repo
* Run `build.cmd`
Run `build-tests.cmd -- /p:Outerloop=true`

If you then want to repro the individual test project that is failing, you can run

`msbuild src\System.Runtime.Numerics\tests\System.Runtime.Numerics.Tests.csproj /t:RebuildAndTest /p:Outerloop=true`

**Comment by mellinoe** [comment] 2017-01-26 18:37
@karelz I think we need to add @dennisdietrich to the "Contributors" group before I can assign him any issues. How do we do that, again?

**Comment by karelz** [comment] 2017-01-26 18:43
Invitation sent (you need super-powers in dotnet org to make it happen).
@dennisdietrich please ping me here, when you accept and I will assign it to you.

**Comment by dennisdietrich** [comment] 2017-01-26 18:54
Thanks @karelz! Done.

**Comment by dennisdietrich** [comment] 2017-01-27 00:13
@mellinoe, quick question (I'm sure this is documented somewhere but I can't find it): What about line endings? Should they be Windows or UNIX-style/what value is preferred for core.autocrlf?

**Comment by mellinoe** [comment] 2017-01-27 01:03
> what value is preferred for core.autocrlf

True, I believe. TBH I've never actively thought of this; we use the default as far as I know.

**Comment by dennisdietrich** [comment] 2017-01-27 22:15
@mellinoe, the good news (I guess) is that I can repro the issue. Unfortunately, so far I'm unable to build System.Runtime.Numerics.sln in VS (trying to get help on Gitter).

**Comment by dennisdietrich** [comment] 2017-01-28 16:49
Still stuck trying to build/debug corefx in VS so it's difficult to do a root cause analysis. However, since I can reproduce on the command line I've looked at the stack trace and so far this looks like a legitimate product bug to me (though it is labeled 'test bug'). First of all, the test passes for invariant, en-US, de-DE, and hi-IN. Second, it chokes on trailing 0x20 characters for uk-UA which is just a regular space.

**Comment by dennisdietrich** [comment] 2017-01-28 18:16
N/m. Found this method in FormatProvider.Number so I guess this is by-design and it's interpreting the trailing 0x20 as a trailing group separator. Preparing a PR on the basis of this assumption.
```c#
private static unsafe char* MatchChars(char* p, char* str)
{
    Debug.Assert(p != null && str != null);

    if (*str == '\0')
    {
        return null;
    }

    // We only hurt the failure case
    // This fix is for French or Kazakh cultures. Since a user cannot type 0xA0 as a
    // space character we use 0x20 space character instead to mean the same.
    while (*p == *str || (*str == '\u00a0' && *p == '\u0020'))
    {
        p++;
        str++;
        if (*str == '\0') return p;
    }
    return null;
}
```

**Comment by karelz** [comment] 2017-01-28 18:19
> Still stuck trying to build/debug corefx in VS

Can you provide some details, maybe @weshaggard @mellinoe can help ...

**Comment by dennisdietrich** [comment] 2017-01-28 19:03
Already discussing this with Eric on Gitter (seemed like the better place for figuring this out). Thanks!

**Closed** 2017-01-31 20:43 UTC
Labels: area-System.Numerics, simple, test bug
