### ISSUE TITLE
Process.WaitForExit() doesn't always return when the process ends on linux

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/corefx#31713] opened 2018-08-11 01:11 UTC
We're seeing some odd behavior in one of our Razor build server [tests](https://github.com/aspnet/Razor/blob/master/test/Microsoft.AspNetCore.Razor.Design.Test/IntegrationTests/BuildServerIntegrationTest.cs#L150-L168) when running on a linux machine in VSTS.
The test seems to hang at the WaitForExit call [here](https://github.com/aspnet/Razor/blob/master/src/Microsoft.AspNetCore.Razor.Tools/ShutdownCommand.cs#L64) even though the process has completed execution. The build server process(PID 2121) seems to hang around as a `<defunct>` process.
![image](https://user-images.githubusercontent.com/1579269/43986528-01720fca-9cc7-11e8-97d4-5d25eec6e79b.png)
Note, the test actually starts `dotnet build` in a separate process which in turn starts the build server in another process.

Here is the flow,
- Run `dotnet build` in a separate process from a test which creates a build server process
- Send shutdown command and wait for process exit
- Expected: The build server process finishes execution, process exits and WaitForExit returns
- Actual: The build server process finishes execution, process goes to zombie state and WaitForExit spins forever

I haven't been able to successfully create a minimal repro yet but I thought it might be worth filing a bug given similar issues like https://github.com/dotnet/corefx/issues/31559 have already been filed.

Sdk version: 2.1.302

**Comment by danmosemsft** [comment] 2018-08-11 09:37
@tmds

**Comment by krwq** [comment] 2018-08-15 17:33
@ajaybhargavb, yes both issues look similar - do you perhaps have a simple repro? (ok if needs to be run in a loop)

**Comment by wtgodbe** [comment] 2018-09-14 21:56
@ajaybhargavb any update here?

**Comment by ajaybhargavb** [comment] 2018-09-14 22:04
I spent some time on this earlier but was having a hard time creating a simpler repro. The issue still exists though. I'll try and spend some more time later. Is there anything else I can provide? Like any specific data I can collect to help with the investigation?

**Comment by wtgodbe** [comment] 2018-09-14 22:13
I think the most helpful thing for us would be a programmatic repro, @krwq any other thoughts?

**Comment by krwq** [comment] 2018-09-14 22:57
@ajaybhargavb I do not have much experience with defunct processes but from what I've read it means that process is already finished and parent process should acknowledge death of its child i.e. by calling `wait` syscall, I suspect that parent is stuck incorrectly waiting for the child.

Could we perhaps attach to the parent process and see what's happening in the WaitForExit why it's stuck?
Other thing which might be useful is to inspect what syscalls is parent process doing (i.e. use `strace`) and check if wait was in fact called.

What is the OS where this repros? Is it any non-Windows or only some specifc distros?

**Comment by wfurt** [comment] 2018-09-18 19:49
what version of .net do you use? @tmds did some re-factoring in this area for 2.1
But this could also be bug in the application, depending how Process API is used. 
On Unix each child process needs to be cleaned by somebody - parent or sometimes init process. 
It may be useful to track what processes are becoming zombies and who starts them.

**Comment by krwq** [comment] 2018-09-18 20:59
For .NET version from @wfurt's question use `dotnet --info`

**Comment by ajaybhargavb** [comment] 2018-09-18 21:16
> Could we perhaps attach to the parent process and see what's happening in the WaitForExit why it's stuck? (what is it waiting for specifically)
Other thing which might be useful is to inspect what syscalls is parent process doing (i.e. use strace) and check if wait was in fact called.
What is the OS where this repros? Is it any non-Windows or only some specifc distros?

We hit this when running our builds on VSTS(dnceng) - Linux hosted preview (I think it runs Ubuntu 16.04 I'll double check). This is not happening on Windows or Mac. I can try running this locally and attaching to the process as you suggested.

> what version of .net do you use?

I already mentioned the version in my original post. It's `2.1.302`. And it's also happening in `2.1.400`

**Comment by wfurt** [comment] 2018-09-18 21:42
sorry, I missed that. Can you please take a look @tmds ?
BTW the ppid 1 suggest that parent is gone. 
It is interesting that init does not finish the cleaning. 
Perhaps because it exited while parent was running and consumed SIGCHLD.

**Comment by tmds** [comment] 2018-09-19 19:29
> BTW the ppid 1 suggest that parent is gone.
It is interesting that init does not finish the cleaning.

Interesting observation! Pid 1 here is the Agent.Listener.
What process is calling WaitForExit? And how does it relate to the defunct dotnet processes (it is not the parent)?

**Comment by wfurt** [comment] 2018-09-19 20:08
Is this container @ajaybhargavb  ??? I would expect pid 1 to be init.

**Comment by wfurt** [comment] 2018-09-19 21:33
is it ever possible for p3 finish before p2 quits? How exactly p1 collects status? Since p1 has no clue about p3, it may be looking for wrong pid. In this case we would need to be looking for any pid from that process group (e.g. -1 or 0) 

Minimal repro would be great @ajaybhargavb . I think the important parts are timing and relations. 

and yes, I was asking about Docker. I'm not aware of any issue right now but there were some weird corner cases before.

**Comment by tmds** [comment] 2018-09-19 22:43
> P1 sends shutdown command to P3 and waits for P3 to exit

Because P3 is not a direct child of P1, this doesn't work via SIGCHLD. So this issue is different from https://github.com/dotnet/corefx/issues/31559.
For non-child processes, the exit is detected by polling the pid using kill with signo 0.

If you reproduce this, try running strace on P1: `strace -f -e kill -p <P1>`.
You should see kill calls being made each 100ms for P3.

**Comment by tmds** [comment] 2018-09-20 02:34
> For non-child processes, the exit is detected by polling the pid using kill with signo 0.

The root cause is this doesn't work for defunct processes. `kill` returns as if the process is still running.

**Comment by wfurt** [comment] 2018-09-20 03:35
I think you would need to poll waitpid(-1, NOHANG)

**Comment by tmds** [comment] 2018-09-20 09:12
You need a PID 1 that takes care of the orphaned children. You can add one by specifying `--init` on the `docker run` command.

**Comment by tmds** [comment] 2018-10-03 09:18
@ajaybhargavb does the suggested fix work for you?

**Comment by ajaybhargavb** [comment] 2018-10-03 22:30
Sorry, I haven't had the chance to try out the suggestions yet. I should get around to this sometime next week.

**Comment by tmds** [comment] 2019-01-07 08:37
@ajaybhargavb is it ok to close this issue?

**Comment by ajaybhargavb** [comment] 2019-01-07 20:21
@tmds, I spent a good amount of time trying to get a minimal repro for this but I have nothing so far. But I know for sure that this is still happening consistently on our CI machines. We have currently skipped that test on Linux. I would be happy to help/work with anyone who has a little more context and wants to investigate this further. Having said that, I'm not 100% sure if there is an actual bug in corefx, so I'll let you guys decide whether this issue should remain open or not.

**Comment by tmds** [comment] 2019-01-08 07:50
@ajaybhargavb did you try this suggestion?

> You need a PID 1 that takes care of the orphaned children. You can add one by specifying --init on the docker run command.

**Comment by ajaybhargavb** [comment] 2019-01-08 21:06
> @ajaybhargavb did you try this suggestion?

No. I'm not sure how to modify the docker run command in the CI. We don't have any control over how the agents are created in VSTS.

**Comment by ajaybhargavb** [comment] 2019-01-08 23:09
I was wrong.  There is a way to pass arguments to startup. I just tried it and the test passed 🍾. Thanks! 
Is `--init` something we should always be passing in? Or is this just a workaround for a different bug?

**Comment by tmds** [comment] 2019-01-09 07:47
> Is --init something we should always be passing in? Or is this just a workaround for a different bug?

This is expected behavior. Orphaned children are cleaned up by the PID 1 process. Adding `--init` adds a PID 1 process that will do that.

To get into a state with orphaned children, you need a PID 1 that has grand children that survive their  parents. If you can get into such a situation, you should add the `--init` flag.

**Comment by ajaybhargavb** [comment] 2019-01-09 18:42
> This is expected behavior.

Okay then it looks like there is no action here and this issue can be closed.

> To get into a state with orphaned children, you need a PID 1 that has grand children that survive their parents

Could you please elaborate this a bit more? I'm not sure I fully understand.

**Comment by tmds** [comment] 2019-01-11 13:42
> Could you please elaborate this a bit more? I'm not sure I fully understand.

When a process terminates, it becomes a 'zombie'. This is the state where there are still some resources in the kernel that must be cleaned up. Those gets cleaned up by someone calling the `waitpid` system function. Usually this is the parent. A .NET Core process will ensure this happens for all it's children when they terminate. When the parent terminates before its children, it becomes the responsibility of the PID 1 process. For the reported issue, PID 1 is Agent.Listener, and doesn't feel responsible. Adding `--init` makes PID 1 an init process (that will launch Agent.Listener) that also does this waitpid-cleanup.

So to get in this sort of problematic state, you need grand children that survive their parents.

**Comment by tmds** [comment] 2019-02-21 13:59
This may be closed.

**Closed** 2019-02-21 16:15 UTC
Labels: area-System.Diagnostics.Process, bug, os-linux
