### ISSUE TITLE
System.Net.Sockets.Tests.TimeoutTest.SendTimesOut_Throws failed with "Xunit.Sdk.InRangeException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23207] opened 2017-08-14 07:54 UTC
Failed test: System.Net.Sockets.Tests.TimeoutTest.SendTimesOut_Throws

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_debug/178/testReport/System.Net.Sockets.Tests/TimeoutTest/SendTimesOut_Throws_forceNonBlocking__False_/

Configuration: outerloop_netcoreapp_win7_debug

MESSAGE:
~~~
Assert.InRange() Failure\r\nRange: (1500 - 3000)\r\nActual: 3075.975
~~~
STACK TRACE:
~~~
at System.Net.Sockets.Tests.TimeoutTest.SendTimesOut_Throws(Boolean forceNonBlocking) 
in D:\j\workspace\outerloop_net---92764178\src\System.Net.Sockets\tests\FunctionalTests\TimeoutTest.cs:line 128
~~~

**Comment by karelz** [comment] 2017-12-29 00:56
Duplicate of #24804

**Closed by karelz** 2017-12-29 00:56 UTC
Labels: area-System.Net.Sockets, test-run-core
