### ISSUE TITLE
DateTimeOffset.FromUnixTimeSeconds and DateTimeOffset.FromUnixTimeMilliseconds with float and double as argument

### ISSUE THREAD

**Issue by Thaina** [dotnet/corefx#34309] opened 2019-01-02 06:39 UTC
DateTimeOffset has precision to nanosecond and so it should support UnixTime microsecond precision which would come in float/double format from another system. Most of the time we serialize time in database with unixtime format. So C# should natively support this instead of need us mess with unix epoch

**Comment by danmosemsft** [comment] 2019-01-02 20:38
dupe of  https://github.com/dotnet/corefx/issues/24555 ?

**Closed** 2019-01-03 01:56 UTC
Labels: api-suggestion, area-System.Runtime
