### ISSUE TITLE
NameResolution TryGetAddrInfo_HostName test failed then seg faulted in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8944] opened 2016-05-28 11:17 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/opensuse13.2_release_tst/483/consoleText
```
System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
./RunTests.sh: line 208:  8433 Segmentation fault      ./corerun xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

**Comment by ericeil** [comment] 2016-06-01 21:12
The HostNotFound error could just be a spurious DNS issue.  The segfault is a different matter.  Maybe related to #8657, #8983, and/or #8992.

**Comment by joshfree** [comment] 2016-06-03 21:13
@ericeil are you actively trying to reproduce this seg fault with a loop run or is there no further action being taken?

**Comment by ericeil** [comment] 2016-06-03 21:23
I've been unable to reproduce this.  Closing this as non-actionable; hopefully this was the same issue as one of the other segfault/AV issues that can be reproduced.

**Closed by ericeil** 2016-06-03 21:23 UTC
Labels: System.Net, tenet-reliability, X-Plat
