### ISSUE TITLE
System.Text.Json failing assert crashed CI in CacheTests.MultipleThreads test

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38835] opened 2019-06-24 19:04 UTC
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38829~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.38/workItem/System.Text.Json.Tests/wilogs
```
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 982 of 1008 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 4)
    System.Text.Json.Serialization.Tests.ValueTests.WriteKeyValuePairOfList [SKIP]
      Disabled until writer enables property name to be set
Process terminated. Assertion failed.
   at System.Text.Json.JsonSerializer.HandlePropertyName(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandlePropertyName.cs:line 91
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs:line 52
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 22
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 74
   at System.Text.Json.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 31
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__DeserializeObjectNormal|1_1() in /_/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 26
   at System.Text.Json.Serialization.Tests.CacheTests.<>c.<MultipleThreads>b__1_4() in /_/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 42
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2449
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2428
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2389
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2327
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2312
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 663
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
```

Looks like that maps to https://github.com/dotnet/corefx/blob/db1ef41efc7757bc88c52f46141092611855f2b0/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandlePropertyName.cs#L91-L94
and was caused by
https://github.com/dotnet/corefx/blob/e3ec42fb156c0354aa4095b125f3f56c27d0ecf7/src/System.Text.Json/tests/Serialization/CacheTests.cs#L16

cc: @steveharter, @ahsonkhan, @JeremyKuhne

**Comment by stephentoub** [comment] 2019-06-24 19:05
Might be the same root cause as https://github.com/dotnet/corefx/issues/38802, which was a release build.  But I'm leaving this open until it's proven it's the same.

**Comment by ahsonkhan** [comment] 2019-06-25 08:14
Failed again in https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38865~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190625.1/workItem/System.Text.Json.Tests/wilogs from https://github.com/dotnet/corefx/pull/38865

OSX.1013.Amd64.Open-x64:Debug

```text
    System.Text.Json.Serialization.Tests.ValueTests.WriteKeyValuePairOfList [SKIP]
      Disabled until writer enables property name to be set
Process terminated. Assertion failed.
   at System.Text.Json.JsonSerializer.HandlePropertyName(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandlePropertyName.cs:line 91
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs:line 52
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 22
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 74
   at System.Text.Json.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 31
   at System.Text.Json.Serialization.Tests.CacheTests.<MultipleThreads>g__DeserializeObjectNormal|1_1() in /_/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 26
   at System.Text.Json.Serialization.Tests.CacheTests.<>c.<MultipleThreads>b__1_4() in /_/src/System.Text.Json/tests/Serialization/CacheTests.cs:line 42
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2449
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2428
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2389
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2327
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2312
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 663
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
```

**Comment by steveharter** [comment] 2019-07-10 16:35
Treating this as a duplicate of https://github.com/dotnet/corefx/issues/38802; that issue goes into more detail about the expected cause and I'll keep that open until I can stress-test locally to ensure there are no caching issues.

**Closed by steveharter** 2019-07-10 16:35 UTC
Labels: area-System.Text.Json, bug
