### ISSUE TITLE
Cannot resolve method .ctor when using ValueTuples and Expression Trees.

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#36744] opened 2019-04-09 19:09 UTC
Consider the following simple expression::
```cs
Expression<Func<int, int, string>> e = (a, b) => new ValueTuple<int, int>(a, b).ToString();
```

Yields the following exception::

> Cannot resolve method Void .ctor(Int32, Int32) because the declaring type of the method handle System.ValueTuple`2[T1,T2] is generic. Explicitly provide the declaring type to GetMethodFromHandle. 
> + System.Reflection.MethodBase.GetMethodFromHandle(System.RuntimeMethodHandle)

Tuple literal syntax is not allowed in expression trees. 

This error happens in netfx 4.7.2 and core 2.2

**Comment by bartdesmet** [comment] 2019-04-10 19:36
Seems like a duplicate of https://github.com/dotnet/roslyn/issues/24517. There have been several reports of this and it'd be great if this were addressed sooner than later.

**Comment by cston** [comment] 2019-05-22 19:03
@mburbea, thanks for reporting this bug. I'll close this issue since the bug is tracked in Roslyn.

**Closed by cston** 2019-05-22 19:03 UTC
Labels: area-System.Linq.Expressions, bug
