### ISSUE TITLE
[Perf] Investigate Xml/XmlSerializer benchmark regressions in 2.1 (part 2)

### ISSUE THREAD

**Issue by valenis** [dotnet/corefx#27484] opened 2018-02-26 23:21 UTC
[Perf] Investigate Xml/XmlSerializer benchmark regressions in 2.1 (part 2)

Second regression across multiple tests in Xml/XmlSerializer of >15% from this range of commits:

https://github.com/dotnet/corefx/compare/6f5d255a76a192906f692fd3d2b9104ab6aeb2f2...dotnet:504781cbfb166c71204b9077c0528623c85cf68c

**Comment by huanwu** [comment] 2018-03-22 17:48
@jorive Could you provide more context/details about this issue

**Comment by danmosemsft** [comment] 2018-03-30 21:32
https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61761,61768,61770,61771,61769,61777,61762,61775,61767,61779,61776,61766,61778,61773,61772,61765,61764,61774,61763,61786,61788,61789,61787,61795,61780,61793,61785,61797,61794,61784,61796,61791,61790,61783,61782,61792,61781]&jobid=94550&

shows the full history. The jump mentioned here is Feb 1st. Probably from coreclr update. Although it is mostly regained on Feb 28 again associated with CoreCLR update.

![image](https://user-images.githubusercontent.com/6385855/38154489-1cc845c2-3427-11e8-8e29-bdbdf060b189.png)

**Comment by Lxiamail** [comment] 2018-04-02 22:39
Need further investigation on this issue, but no resource to finish before ZBB. Keep it in 2.1, but have to work on it in Post-ZBB.

**Comment by Lxiamail** [comment] 2018-04-24 20:47
It's not 2.1 RTM blocker. Moving to 2.2

**Comment by mconnew** [comment] 2018-04-27 01:33
From this issue: https://github.com/dotnet/corefx/issues/27484#issuecomment-384074541

There's a link to this data in corefx with a screenshot showing Linux data in the same comment:

https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=%5B957%5D&archids=%5B23%5D&mpids=%5B1292%5D&cfgids=%5B2785,2706%5D&testids=%5B61761,61768,61770,61771,61769,61777,61762,61775,61767,61779,61776,61766,61778,61773,61772,61765,61764,61774,61763,61786,61788,61789,61787,61795,61780,61793,61785,61797,61794,61784,61796,61791,61790,61783,61782,61792,61781%5D&jobid=94550&

When I go to that url, it doesn't show any data for Linux.

Sent from my Windows 10 phone

________________________________

**Comment by danmosemsft** [comment] 2018-04-30 19:27
@adamsitnik can you help

**Comment by adamsitnik** [comment] 2018-05-08 16:41
This issue is a duplicate of #27786 which was closed by @mconnew and marked as [solved](https://github.com/dotnet/corefx/issues/27786#issuecomment-385565277)

**Closed by adamsitnik** 2018-05-08 16:41 UTC
Labels: Post-ZBB, area-Serialization, tenet-performance-benchmarks
