### ISSUE TITLE
HttpClient and Cookies not working with redirects under netcore50

### ISSUE THREAD

**Issue by hardcodet** [dotnet/corefx#7750] opened 2016-04-14 17:00 UTC
I have a test project that uses an HTTP-Client to connect to a service, which in term uses cookies to store user information. Once done, it performs a redirect. Here's the service API:

```
    [HttpGet]
    [Authorize(ActiveAuthenticationSchemes = "Cookies")]
    [Authorize(ActiveAuthenticationSchemes = "Bearer")]
    public async Task<ActionResult> SelectTenant([FromQuery]string tenant)
    {
        ...
        var identity = (ClaimsIdentity) User.Identity;
        identity.AddClaim(new Claim("foo", bar));

        // sign in again to persist the new claim in the cookie
        await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, User);

        // redirect to the index (which won't realize we just logged in on DNX Core)
        return Redirect("/");
    }
```

Now, when on dnx451, the code works just fine. The index page is invoked, recognizes the cookie and the caller (HttpClient) also gets the cookie information. However, as soon as I switch to netcore50, the redirect isn't working properly anymore, as authentication data (in the cookie) seems to be lost. This is happening **before** `GetAsync` returns control to me.

Here is the console output when running on DNX Core as of the redirect. Note that server-side authorization failed after the redirect:

```
info: Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationMiddleware[3]
      AuthenticationScheme: Cookies signed in.
2016-04-14 18:43:15 [Information] Executing RedirectResult, redirecting to "/".
info: Microsoft.AspNet.Mvc.RedirectResult[1]
      Executing RedirectResult, redirecting to /.
2016-04-14 18:43:15 [Information] Executed action "OrderManager.Controllers.AccountController.SelectTenant" in 0.0016ms
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action OrderManager.Controllers.AccountController.SelectTenant in 0.0016ms
2016-04-14 18:43:15 [Information] Request finished in 0.0016ms 302
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0016ms 302
2016-04-14 18:43:15 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: localhost:5000  PathBase:   Path: /  Quer
yString:
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
2016-04-14 18:43:15 [Warning] Authorization failed for the request at filter '"Microsoft.AspNet.Mvc.Filters.AuthorizeFilter"'.
warn: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[0]
      Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.Filters.AuthorizeFilter'.
2016-04-14 18:43:15 [Information] AuthenticationScheme: "Cookies" was challenged.
info: Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationMiddleware[5]
      AuthenticationScheme: Cookies was challenged.
2016-04-14 18:43:15 [Information] Executing ChallengeResult with authentication schemes (["Cookies"]).
info: Microsoft.AspNet.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes (Cookies).
2016-04-14 18:43:15 [Information] Executed action "OrderManager.Controllers.HomeController.Index" in 0.0015ms
```

It's worth noting that once control is returned to my code, HttpClient actually does get Cookies returned (just the wrong ones, since the Index page does another redirect to the logon because it doesn't realize I already logged in). So I guess that after `HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, User);` is executed, and the redirect happens, `HttpClient`on Core50 doesn't resubmit the cookie to the Index page or something.

Here's the client call btw:

```
    internal static async Task GetAuthCookie()
    {
        var c = new AuthenticationApiClient(new Uri("https://foo.auth0.com"));

        AuthenticationRequest request = new AuthenticationRequest
        {
            ...
        };

        // authenticate with auth0
        var authToken = await c.AuthenticateAsync(request);

        // set the authorization header
        var authHeader = new AuthenticationHeaderValue("Bearer", authToken.IdToken);

        var httpHandler = new HttpClientHandler();
        using (var client = new HttpClient(httpHandler) { BaseAddress = new Uri(Settings.Uri) })
        {
            client.DefaultRequestHeaders.Authorization = authHeader;
            string selectTenantUrl = "Account/SelectTenant?tenant=bar";

            //THIS IS THE CALL THAT DOESN'T WORK THE SAME ON CORE50
            var result = await client.GetAsync(selectTenantUrl);
            Cookies = httpHandler.CookieContainer;
        }
    }
```

**Comment by davidsh** [comment] 2016-04-14 17:09
We have made many changes/fixes to this code in the last several months. Can you please clarify the project.json, project.lock.json settings for your repro? We need to understand exactly which builds of binaries you are using.

**Comment by hardcodet** [comment] 2016-04-14 17:25
This is running on 1.0.0-rc1-update1, Project.json:

    {
        "version": "1.0.0-*",

        "dependencies": {
            "FluentAssertions": "4.2.2",
            "xunit": "2.1.0",
            "xunit.runner.dnx": "2.1.0-rc1-build204",
            "xunit.runner.visualstudio": "2.1.0",
            "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc1-final",
            "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
            "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
            "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
            "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
            "System.Net.Http": "4.0.1-beta-23409",
            "Microsoft.AspNet.Authentication": "1.0.0-rc1-final",
            "Auth0.AuthenticationApi": "3.0.0"
        },

        "commands": {
            "test": "xunit.runner.dnx"
        },

        "frameworks": {
            "dnxcore50": { }
        },

        "exclude": [ ],
        "publishExclude": [
            "**.user",
            "**.vspscc"
        ]
    }

Let me know if you wan't me to post the full lock file or parts of it.

**Comment by davidsh** [comment] 2016-04-14 17:29
Yes, please post the full 'project.lock.json'. In fact, if you can, please post the entire repro solution.  You can set up a repo for that on GitHub if you want.

**Comment by hardcodet** [comment] 2016-04-14 17:40
I can't post a repro unfortunately - hope this will get you somewhere. For now, we'll just switch back to dnx451.

I just realized that the Net.Http package has an more recent version. Updated to the latest beta, but still the same result. The lock file is too long to be posted here, so I attached it here:

[projectfiles.zip](https://github.com/dotnet/corefx/files/219659/projectfiles.zip)

**Comment by davidsh** [comment] 2016-04-14 22:36
You mentioned that this didn't work on "netcore50".  "netcore50" means UWP, i.w. Windows 10 Store App.

Looking at your project.json, it looks like you might have meant "dnxcore50", i.e. ASP.NET running on .NET Core vs. "dnx451" running on .NET Framework.

So, I'm just trying to confirm what client application type you are having trouble with. Thx.

**Comment by davidsh** [comment] 2016-04-14 22:44
Since you didn't post a full repro, there is only the source code you mentioned above. It looks like this is the same as #4960 which we already fixed.  In that bug, cookies coming from the server in a redirect response would get "lost" and thus not sent back to the server in the subsequent request after the redirect.

You're currently using older beta binaries.  You will need to try out the newest binaries when we publish RC2 to NuGet later this month.

**Comment by davidsh** [comment] 2016-11-18 20:32
This is possibly a dupe of #9003.

**Comment by davidsh** [comment] 2016-11-22 17:02
Closing this as a duplicate of #9003.

**Closed by davidsh** 2016-11-22 17:02 UTC
Labels: area-System.Net, bug, os-windows-uwp
