### ISSUE TITLE
null reference exception while using transactionScope in async method on linux

### ISSUE THREAD

**Issue by autyan** [dotnet/corefx#27686] opened 2018-03-03 11:28 UTC
I was developing a blog project based on asp.net core mvc and trying to deploy my project on ubuntu 16.04 LTS x86-64.

And I encountered a null reference exception while using transactionScope with dapper on inserting object to sql server.

the sql server version is :12.0.4100.1 running on a windows 2012SP1 system. and the code was running just fine on windows 10 (OS Build 17074.1002). but when i deploy project to ubutun, it throws null refernce exceptions.

the exception details was like:

{System.NullReferenceException: Object reference not set to an instance of an object.
at System.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj) at System.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject) at System.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory) at System.Data.SqlClient.SqlConnection.CloseInnerConnection() at System.Data.SqlClient.SqlConnection.Close() at Dapper.SqlMapper.d__641.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 1191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Autyan.NiChiJou.Repository.Dapper.BaseDapperRepository1.<InsertAsync>d__22.MoveNext() in /home/alex/Documents/Github/Autyan.NiChiJou/src/Autyan.NiChiJou.Repository.Dapper/BaseDapperRepository.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Autyan.NiChiJou.Repository.Dapper.LongKeyDapperRepository1.<InsertAsync>d__1.MoveNext() in /home/alex/Documents/Github/Autyan.NiChiJou/src/Autyan.NiChiJou.Repository.Dapper/LongKeyDapperRepository.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Autyan.NiChiJou.Service.Blog.ArticleService.d__10.MoveNext() in /home/alex/Documents/Github/Autyan.NiChiJou/src/Autyan.NiChiJou.Service.Blog/ArticleService.cs:line 39}

my code that throws exception is like this:

            using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
        {
            var create = await ArticleRepo.InsertAsync(article);
            if (create <= 0)
            {
                return Failed<Article>("create article failed");
            }
            create = await ContentRepo.InsertAsync(new ArticleContent
            {
                ArticleId = create,
                Content = content
            });
            if (create <= 0)
            {
                return Failed<Article>("create articleContent failed");
            }
            scope.Complete();
        }
I tried to remove the transactionScope and after that , my codes runs just fine with everything

the new code was like:

var create = await ArticleRepo.InsertAsync(article);
        if (create <= 0)
        {
            return Failed<Article>("create article failed");
        }
        create = await ContentRepo.InsertAsync(new ArticleContent
        {
            ArticleId = create,
            Content = content
        });
        if (create <= 0)
        {
            return Failed<Article>("create articleContent failed");
        }
Am i using trancsationScope the wrong way? Or it's just a bug from dotnet core it self?

**Comment by saurabh500** [comment] 2018-03-03 21:57
@autyan This issue is a duplicate of  https://github.com/dotnet/corefx/issues/26965 
and is already fixed as part of https://github.com/dotnet/corefx/pull/27523

**Closed by saurabh500** 2018-03-03 21:57 UTC
Labels: area-System.Data, bug

**Comment by johnkors** [comment] 2018-03-06 18:01
Just hit this issue as well. As a fix has been merged - how can I follow what version this will be deployed as part of..?

**Comment by saurabh500** [comment] 2018-03-06 18:37
If you are open to using our nightly builds, then try https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient v 

4.5.0-preview2-26305-02

Else this should be in preview 2

**Comment by johnkors** [comment] 2018-03-07 14:55
Thanks!

**Comment by johnkors** [comment] 2018-03-07 19:06
For reference. I ended up with a working version using 

`<PackageReference Include="System.Data.SqlClient" Version="4.5.0-preview2-26307-06" />`

from 

`<add key="beta-feed" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />`
