### ISSUE TITLE
JsonSerializer.Deserialize<dynamic> is not producing a dynamic

### ISSUE THREAD

**Issue by Corys9** [dotnet/corefx#41290] opened 2019-09-24 17:38 UTC
JsonSerializer.Deserialize&lt;dynamic&gt; does not produce a dynamic, but System.Text.Json.JsonElement instead. Is this going to be supported in the near future?

**Comment by scalablecory** [comment] 2019-09-24 17:42
Closing as duplicate of #38007. We're looking for some good use cases for this, and would appreciate a comment there on how you'd use this.

**Closed by scalablecory** 2019-09-24 17:42 UTC
Labels: area-System.Text.Json
