### ISSUE TITLE
System.Text.Json serialize accurate DateTime incorrectly!

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#37515] opened 2019-05-08 15:54 UTC
_From @kennywangjin on Wednesday, 08 May 2019 06:35:39_

aspnetcore3.0 preview5 using System.Text.Json as input- and outputformatter:
if DateTime is too accurate (sqlserver datetime2), it will serialize it to invalid format like: **2019-05-08T00:00:5406760219**
This kind of result could not even be recognized by **DateTime.Parse**.
I think it should be **2019-05-08T00:00:54.06760219** (with a dot between seconds number and others) which can be parsed by DateTime class.

![批注 2019-05-08 143028](https://user-images.githubusercontent.com/3364218/57354392-e9edf100-719d-11e9-88b9-be9d2c86744a.png)

_Copied from original issue: aspnet/AspNetCore#10070_

**Comment by Eilon** [comment] 2019-05-08 15:54
_From @pranavkm on Wednesday, 08 May 2019 21:17:00_

@Eilon please move to dotnet/corefx.

**Comment by vcsjones** [comment] 2019-05-08 16:59
Dupe of #37147.

**Comment by vcsjones** [comment] 2019-05-08 17:11
It looks like the fix was committed in 5f4dede but preview5 was cut at d06ce9d (two days before the PR was merged), so the fix isn't in preview5.

**Comment by layomia** [comment] 2019-05-08 17:49
> It looks like the fix was committed in [5f4dede](https://github.com/dotnet/corefx/commit/5f4dedeb0db50f7d5224fe29a9c6d27cf03fa26b) but preview5 was cut at [d06ce9d](https://github.com/dotnet/corefx/commit/d06ce9d2116cb4bda528822e63d32ce3735ea653) (two days before the PR was merged), so the fix isn't in preview5.

+1. This has been fixed.

**Closed by layomia** 2019-05-08 17:49 UTC
Labels: area-Serialization, area-System.Text.Json

**Comment by layomia** [comment] 2019-05-08 18:22
> +1. This has been fixed.

The fix will be added in preview 6. You can also use the fix by consuming the [nightly .NET Core build.](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md)
