### ISSUE TITLE
System.Net.Sockets.Tests.LoggingTest failed with TargetInvocationException in ILC mode

### ISSUE THREAD

**Issue by caesar1995** [dotnet/corefx#21391] opened 2017-06-22 23:27 UTC
Can't find related issue. Please close it if there is a dup.

Type: System.Net.Sockets.Tests.LoggingTest+<>c
  Method: Int32 <EventSource_EventsRaisedAsExpected>b__1_0()
```
  Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.InRangeException: Assert.InRange() Failure
  Range:  (1 - 2147483647)
  Actual: 0
     at Xunit.Assert.InRange(Int32 actual, Int32 low, Int32 high, Collections.Generic.IComparer<System.Int32> comparer)
     at Xunit.Assert.InRange(Int32 actual, Int32 low, Int32 high)
     at System.Net.Sockets.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0()
     at RemoteExecutorConsoleApp!<BaseAddress>+0xc5ce7a
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa77023
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa76e23
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa76f6f
     at RemoteExecutorConsoleApp!<BaseAddress>+0xdbf53d
     at RemoteExecutorConsoleApp!<BaseAddress>+0xda481c
     at RemoteExecutorConsoleApp.Program.Main(String[] args)
  Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.InRangeException: Assert.InRange() Failure
  Range:  (1 - 2147483647)
  Actual: 0
     at Xunit.Assert.InRange(Int32 actual, Int32 low, Int32 high, Collections.Generic.IComparer<System.Int32> comparer)
     at Xunit.Assert.InRange(Int32 actual, Int32 low, Int32 high)
     at System.Net.Sockets.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0()
     at RemoteExecutorConsoleApp!<BaseAddress>+0xc5ce7a
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa77023
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa76e23
     --- End of inner exception stack trace ---
     at RemoteExecutorConsoleApp!<BaseAddress>+0xa76f6f
     at RemoteExecutorConsoleApp!<BaseAddress>+0xdbf53d
     at RemoteExecutorConsoleApp!<BaseAddress>+0xda481c
     at RemoteExecutorConsoleApp.Program.Main(String[] args)
     at RemoteExecutorConsoleApp.Program.Main(String[] args)
     at RemoteExecutorConsoleApp!<BaseAddress>+0x7a1065
     at RemoteExecutorConsoleApp!<BaseAddress>+0x7d7920
     System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   255
        Stack Trace:
              at xunit.console.netcore!<BaseAddress>+0xb5a139
              at System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected()
              at xunit.console.netcore!<BaseAddress>+0xc82347
              at xunit.console.netcore!<BaseAddress>+0xa9f193
              at xunit.console.netcore!<BaseAddress>+0xa9ef93
```

**Comment by tijoytom** [comment] 2017-06-27 19:04
@caesar1995 Do you know what this failure is about , is the test trying to do remote execution ?

**Comment by davidsh** [comment] 2017-06-27 19:41
This is a dupe of #20470.  NetEventSource is broken in ILC right now, at least in terms of us testing it.

I thought this Sockets related logging test was already disabled via ActiveIssue(UapAot) ?

**Comment by caesar1995** [comment] 2017-06-27 19:43
@davidsh Yes, I have disabled the test. I opened this issue to describe the problem, and keep track of status.

**Closed** 2017-06-27 19:44 UTC
Labels: area-System.Net.Sockets, os-windows-uwp, test-run-uwp-ilc
