### ISSUE TITLE
HTTP2: SendAsync cancellation token does not send RST_STREAM - Add test

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#38391] opened 2019-06-10 04:59 UTC
Canceling `HttpClient.SendAsync` does not send a RST_STREAM from the client to the server.

Repro:
1. git clone https://github.com/JamesNK/grpc-dotnet.git
2. git checkout jamesnk/httpclient-cancel-bug
3. examples\Server -> dotnet run
4. examples\Clients\Greeter -> dotnet run

Expected:
HttpClient sends RST_STREAM (CANCELLED) when the cancellation token is triggered. Server receives cancellation and stops streaming.

Actual:
HttpClient doesn't send RST_STREAM. Server streams messages until app closes.

Client:
```
C:\Development\Source\grpc-dotnet\examples\Clients\Greeter [jamesnk/httpclient-samples ≡]> dotnet run
Greeting: Hello GreeterClient
Greeting: How are you GreeterClient? 1
Greeting: How are you GreeterClient? 2
Greeting: How are you GreeterClient? 3
Greeting: How are you GreeterClient? 4
Stream cancelled.
Shutting down
Press any key to exit...
```

Server:
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /Greet.Greeter/SayHellos'
info: GreeterService[0]
      Connection id: 0HLNDC12C7MKM
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 1.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 2.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 3.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 4.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 5.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 6.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 7.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 8.
info: GreeterService[0]
      Sending greeting How are you GreeterClient? 9.
```
Note that server was never notified that the client has canceled the call and so will continue streaming until the client app exits.

**Comment by JamesNK** [comment] 2019-06-10 21:00
@wfurt

**Comment by wfurt** [comment] 2019-06-10 21:05
That should be fixed with https://github.com/dotnet/corefx/pull/38226/ 
I will trey to add test for that scenario.

**Comment by JamesNK** [comment] 2019-06-10 21:29
Cool.

A unit test would be good. Cancelling HTTP/2 calls is used quite often in gRPC. Accidentally regressing it in the future would have a large effect.

**Comment by JamesNK** [comment] 2019-06-24 19:53
Did this get properly fixed? RST_STREAM is not sent when I test with 3.0.100-preview7-012592 (it is possible the PR changes haven't made it into this SDK)

**Comment by wfurt** [comment] 2019-06-26 04:01
Can we tell somehow @wtgodbe ? Did you use 3.0.100-preview7-012592 from master or 3.0 branch?

**Comment by JamesNK** [comment] 2019-06-26 09:09
That was from master. I haven't re-tested on a newer build. I'm on holiday until Thursday.

**Comment by wfurt** [comment] 2019-06-26 09:18
Thanks @JamesNK . I'm all the road as well. I'l grab a build and I'll try to rerun posted test.

**Comment by wtgodbe** [comment] 2019-06-26 16:12
`3.0.100-preview7-012592` was built against core-sdk commit `3cea274e447d0a0934b69cde9b04ff5c0d5c28af` (I got this by opening the zip file, and navigating to `sdk/3.0.100-preview7-012592/.version`). 

That version of core-sdk consumed Core-Setup commit e1d780539e85f4d8de263957715f9d08db2ceef4: https://github.com/dotnet/core-sdk/blob/3cea274e447d0a0934b69cde9b04ff5c0d5c28af/eng/Version.Details.xml#L11

Which consumed CoreFx commit 468355e66daf9eaeb1978703fa6365cd1e37e644: https://github.com/dotnet/core-setup/blob/e1d780539e85f4d8de263957715f9d08db2ceef4/eng/Version.Details.xml#L14

Which was made 6 days ago, well after the change @wfurt referenced: https://github.com/dotnet/corefx/commit/468355e66daf9eaeb1978703fa6365cd1e37e644

So it looks like the change didn't work fully as expected.

**Comment by wfurt** [comment] 2019-06-27 20:16
I did testing with sightly more recent version of dotnet and it seems to be working unless I missed something.
The server side does not show anything e.g. looks just like @JamesNK  described. But I do see RST on the wire (pkt 31): 

![image](https://user-images.githubusercontent.com/14356188/60297606-ddc61a80-9928-11e9-8393-22a009dccc06.png)

We may need to look at it deeper when @JamesNK comes back. For now, I'm going to remove from 3.0 target to take it off 3.0 watchlist.

**Comment by JamesNK** [comment] 2019-06-27 23:13
I confirmed it works now.

Please do this post 3.0. I worry about future regressions for a feature that worked, then regressed, then was fixed without an explicit test.

**Comment by wfurt** [comment] 2019-06-27 23:17
it has explicit test in corefx. I could not find 3.0.100-preview7-012592 so I could not do any verification with it. The RST code did not changed so I have no explanation why it did not worked for you.

**Comment by JamesNK** [comment] 2019-06-27 23:21
I mean it regressed in preview 6. I'm guessing the build I had 3 days ago didn't include the change.

**Comment by wfurt** [comment] 2019-06-27 23:24
ok. Since you opened this I added new test and that should avoid regression. There is at least one more pending cancelation issue and when we add new test, I'll also make sure we check for RST as well.

**Closed by wfurt** 2019-06-27 23:24 UTC
Labels: area-System.Net.Http.SocketsHttpHandler, test enhancement
