### ISSUE TITLE
CurrentPrincipal changed after await a task

### ISSUE THREAD

**Issue by snowwaft** [dotnet/corefx#37262] opened 2019-04-29 07:17 UTC
I use Thread.CurrentPrincipal to store user's information, such as username, token, etc. through difference threads.
In .Net Framework 4.6.1, this works well.
However, when I switch to .NetCore, the CurrentPrincipal changed after awaited a task.

```
class Program
{
    static Random random = new Random();

    static AsyncLocal<string> _AsyncLocalName = new AsyncLocal<string>();

    static void Main(string[] args)
    {
        for (var i = 0; i < 50; i++)
        {
            Task.Factory.StartNew((o) => Test(o), i.ToString());
        }
        Console.ReadLine();
    }

    static async void Test(object state)
    {
        var name = (string)state;
        Thread.CurrentPrincipal = new GenericPrincipal(new GenericIdentity(name), new string[] { });
        _AsyncLocalName.Value = name;
        Debug.Assert(name == Thread.CurrentPrincipal.Identity.Name);    //always true
        Debug.Assert(name == _AsyncLocalName.Value);                    //always true
        await Task.Delay(random.Next(1000));
        Debug.Assert(name == Thread.CurrentPrincipal.Identity.Name);    //may fail, even more, Thread.CurrentPrincipal may equal null
        Debug.Assert(name == _AsyncLocalName.Value);                    //always true
    }
}
```

**Comment by davidsh** [comment] 2019-04-29 18:16
Could be related to:
#34489
#36562

Thread.CurrentPrincipal behaves differently in .NET Core compared with .NET Framework

**Comment by stephentoub** [comment] 2019-04-29 21:15
This test consistently passes for me on .NET Core 3.0 Preview 4.

Previous .NET Core releases did not flow the current principal as part of ExecutionContext.  Now it does, as of https://github.com/dotnet/corefx/pull/34747.

**Comment by jkotas** [comment] 2019-04-30 03:07
Duplicate of #34489

**Closed by jkotas** 2019-04-30 03:07 UTC
Labels: area-System.Threading
