### ISSUE TITLE
When calling a vb.net public method of .net standard 2.0 dll within .Net core 2.1 web api project throwing Runtime exceptions

### ISSUE THREAD

**Issue by NainaChauhan** [dotnet/corefx#33127] opened 2018-10-30 12:36 UTC
Could not load type 'Microsoft.VisualBasic.DateAndTime' from assembly 'Microsoft.VisualBasic, Version=10.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

It might be issue comes, because of .net 2.0 dll shared method is using 'Microsoft.VisualBasic.DateAndTime'  class methods/properties ex- now, datediff and DateInterval enum and we can not changes the existing DLL code because providing by another team.

**Comment by NainaChauhan** [comment] 2018-10-31 06:35
@danmosemsft Thanks. So to process current development our team have to go back to .net framework 4.6.1. for web api project.

**Comment by cston** [comment] 2019-02-25 20:19
@NainaChauhan, thanks for reporting this issue. Closing since this is by design.

**Closed by cston** 2019-02-25 20:19 UTC
Labels: area-Microsoft.VisualBasic
