### ISSUE TITLE
Application crash because of unhandled exception in DbConnectionPool

### ISSUE THREAD

**Issue by Crimscent** [dotnet/corefx#26026] opened 2017-12-22 07:02 UTC
This line of code is causing application to crash, because of unhandled exception. This exception is thrown in other thread, started by ThreadPool.QueueUserWorkItem and there is no way for user code to handle it.
https://github.com/dotnet/corefx/blob/ec22edc155aa13289770c9f49630cc7ab588fca4/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L755

**Comment by divega** [comment] 2018-02-06 02:42
Moving to SqlClient area since this is provider implementation code and not common ADO.NET code. 

FWIW, this looks like a possible duplicate of other issues that have been reported.

cc @saurabh500

**Comment by saurabh500** [comment] 2018-02-12 22:41
Dupe of https://github.com/dotnet/corefx/issues/14615

**Closed by saurabh500** 2018-02-12 22:41 UTC
Labels: area-System.Data.SqlClient, bug
