### ISSUE TITLE
Test failure: System.Text.RegularExpressions.Tests.RegexGroupTests/Groups(pattern: ...)

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#31985] opened 2018-08-27 21:41 UTC
The test `System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(pattern: "[B-D\u0130]+", input: "aAeEĩıh BCDbcDİip", options: IgnoreCase, expectedGroups: ["BCDbcDİi"])` has failed.

Assert.Equal() Failure ↓ (pos 7) Expected: BCDbcDİi Actual: BCDbcDİ ↑ (pos 7) 

Stack Trace: 
```
at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String pattern, String input, RegexOptions options, CultureInfo cultureInfo, String[] expectedGroups) 
at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String pattern, String input, RegexOptions options, String[] expectedGroups)
```

Failing in: `macOS Mojave (10.14)`
Not in: `macOS High Sierra (10.13)`

branch: release/1.0.0

**Comment by danmosemsft** [comment] 2018-08-29 00:01
We know that Mojave upgraded their LIBICU. But this test has not changed since 1.0 - and does not appear to have any special casing for the LIBICU version. Perhaps Mojave has a version that no other distro tested so far has?

@maryamariyan this is failing only on release/1.0, not on 1.1, 2.1, master on Mojave?

`yield return new object[] { @"[B-D\u0130]+", "aAeE\u0129\u0131\u0068 BCDbcD\u0130\u0069\u0070", RegexOptions.IgnoreCase, new string[] { "BCDbcD\u0130\u0069" } }`

**Comment by danmosemsft** [comment] 2018-08-29 19:38
@ViktorHofer 1.0 and 1.1 are in support until June 2019. We would need an excellent reason to service them at this point. I do not see much chance that this meets the bar - it is almost certainly not a bug (or not our bug) anyway.

**Comment by danmosemsft** [comment] 2018-08-29 19:38
https://www.microsoft.com/net/support/policy

**Comment by ViktorHofer** [comment] 2019-03-21 12:13
Closing of age.

**Closed by ViktorHofer** 2019-03-21 12:13 UTC
Labels: area-System.Text.RegularExpressions, bug, os-mac-os-x
