### ISSUE TITLE
.NET Core 2 type load exception when using full .net framework dll

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/corefx#22469] opened 2017-07-20 12:04 UTC
We've developed an app on top of "Full .NET/Owin". We managed to run that app on top of "Full .NET/ASP.NET Core" very easily.
Then we started to test that on .net core 2 as it accepts referencing full .net assemblies. Interestingly lots of things are working (signalr, web api, static files middleware etc).
Now we're working on "ASP.NET Web API / OData" as it has no suitable equivalent in .net core world).
In web api parts, we've used swagger, and by running its UI, I received an interesting exception:

```
"System.TypeLoadException","Message":"Could not load type
'System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider' from assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToke
n=31bf3856ad364e35'
```

This is a link of repository which contains the sample app you need to reproduce the problem:
https://github.com/ysmoradi/WebApiOwinSwaggerProblemOnDotNetCore2Preview

Run http://localhost:5000/api/swagger and you'll see that exception in console. Note that swagger itself works(!). You can fix this problem by commenting BadController class easily. You'll see GoodController methods in swagger ui and you can invoke them.

I think there is a problem in .NET full shim in .NET Core 2.

**Comment by ysmoradi** [comment] 2017-07-20 12:12
https://github.com/dotnet/corefx/issues/16101 I saw this now. Sorry. Could you please add this type to .net core 2?

**Comment by danmosemsft** [comment] 2017-07-21 22:45
@AlexGhiondea what criteria did you use for selecting the S.CM types to port? We have some parts of eg System.ComponentModel.DataAnnotations.dll from 4.6.1 and not others.

Below are the concrete types In S.CM (except Composition) that are in 4.6.1 but not Core.
```
ID
T:System.ComponentModel.CurrentChangedEventManager
T:System.ComponentModel.CurrentChangingEventArgs
T:System.ComponentModel.CurrentChangingEventHandler
T:System.ComponentModel.CurrentChangingEventManager
T:System.ComponentModel.DependencyPropertyDescriptor
T:System.ComponentModel.DesignerProperties
T:System.ComponentModel.ErrorsChangedEventManager
T:System.ComponentModel.GroupDescription
E:System.ComponentModel.GroupDescription.PropertyChanged
E:System.ComponentModel.GroupDescription.System#ComponentModel#INotifyPropertyChanged#PropertyChanged
T:System.ComponentModel.ICollectionView
E:System.ComponentModel.ICollectionView.CurrentChanged
E:System.ComponentModel.ICollectionView.CurrentChanging
T:System.ComponentModel.ICollectionViewFactory
T:System.ComponentModel.ICollectionViewLiveShaping
T:System.ComponentModel.IEditableCollectionView
T:System.ComponentModel.IEditableCollectionViewAddNewItem
T:System.ComponentModel.IItemProperties
T:System.ComponentModel.ItemPropertyInfo
T:System.ComponentModel.PropertyChangedEventManager
T:System.ComponentModel.PropertyFilterAttribute
T:System.ComponentModel.SortDescription
T:System.ComponentModel.SortDescriptionCollection
E:System.ComponentModel.SortDescriptionCollection.CollectionChanged
E:System.ComponentModel.SortDescriptionCollection.System#Collections#Specialized#INotifyCollectionChanged#CollectionChanged
T:System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider
T:System.ComponentModel.DataAnnotations.BindableTypeAttribute
T:System.ComponentModel.DataAnnotations.MetadataTypeAttribute
T:System.ComponentModel.DataAnnotations.ScaffoldTableAttribute
T:System.ComponentModel.Design.ActiveDesignSurfaceChangedEventArgs
T:System.ComponentModel.Design.ActiveDesignSurfaceChangedEventHandler
T:System.ComponentModel.Design.ArrayEditor
T:System.ComponentModel.Design.BinaryEditor
T:System.ComponentModel.Design.ByteViewer
T:System.ComponentModel.Design.CollectionEditor
T:System.ComponentModel.Design.CollectionEditor.CollectionForm
T:System.ComponentModel.Design.ComponentDesigner
T:System.ComponentModel.Design.ComponentDesigner.ShadowPropertyCollection
T:System.ComponentModel.Design.DateTimeEditor
T:System.ComponentModel.Design.DesignerActionHeaderItem
T:System.ComponentModel.Design.DesignerActionItem
T:System.ComponentModel.Design.DesignerActionItemCollection
T:System.ComponentModel.Design.DesignerActionList
T:System.ComponentModel.Design.DesignerActionListCollection
T:System.ComponentModel.Design.DesignerActionListsChangedEventArgs
T:System.ComponentModel.Design.DesignerActionListsChangedEventHandler
T:System.ComponentModel.Design.DesignerActionMethodItem
T:System.ComponentModel.Design.DesignerActionPropertyItem
T:System.ComponentModel.Design.DesignerActionService
E:System.ComponentModel.Design.DesignerActionService.DesignerActionListsChanged
T:System.ComponentModel.Design.DesignerActionTextItem
T:System.ComponentModel.Design.DesignerActionUIService
E:System.ComponentModel.Design.DesignerActionUIService.DesignerActionUIStateChange
T:System.ComponentModel.Design.DesignerActionUIStateChangeEventArgs
T:System.ComponentModel.Design.DesignerActionUIStateChangeEventHandler
T:System.ComponentModel.Design.DesignerCommandSet
T:System.ComponentModel.Design.DesignSurface
E:System.ComponentModel.Design.DesignSurface.Disposed
E:System.ComponentModel.Design.DesignSurface.Flushed
E:System.ComponentModel.Design.DesignSurface.Loaded
E:System.ComponentModel.Design.DesignSurface.Loading
E:System.ComponentModel.Design.DesignSurface.Unloaded
E:System.ComponentModel.Design.DesignSurface.Unloading
E:System.ComponentModel.Design.DesignSurface.ViewActivated
T:System.ComponentModel.Design.DesignSurfaceCollection
T:System.ComponentModel.Design.DesignSurfaceEventArgs
T:System.ComponentModel.Design.DesignSurfaceEventHandler
T:System.ComponentModel.Design.DesignSurfaceManager
E:System.ComponentModel.Design.DesignSurfaceManager.ActiveDesignSurfaceChanged
E:System.ComponentModel.Design.DesignSurfaceManager.DesignSurfaceCreated
E:System.ComponentModel.Design.DesignSurfaceManager.DesignSurfaceDisposed
E:System.ComponentModel.Design.DesignSurfaceManager.SelectionChanged
T:System.ComponentModel.Design.EventBindingService
T:System.ComponentModel.Design.ExceptionCollection
T:System.ComponentModel.Design.IComponentDesignerDebugService
T:System.ComponentModel.Design.IComponentDesignerStateService
T:System.ComponentModel.Design.IDesignTimeAssemblyLoader
T:System.ComponentModel.Design.IMultitargetHelperService
T:System.ComponentModel.Design.InheritanceService
T:System.ComponentModel.Design.LoadedEventArgs
T:System.ComponentModel.Design.LoadedEventHandler
T:System.ComponentModel.Design.LocalizationExtenderProvider
T:System.ComponentModel.Design.MenuCommandsChangedEventArgs
T:System.ComponentModel.Design.MenuCommandsChangedEventHandler
T:System.ComponentModel.Design.MenuCommandService
E:System.ComponentModel.Design.MenuCommandService.MenuCommandsChanged
T:System.ComponentModel.Design.MultilineStringEditor
T:System.ComponentModel.Design.ObjectSelectorEditor
T:System.ComponentModel.Design.ObjectSelectorEditor.Selector
T:System.ComponentModel.Design.ObjectSelectorEditor.SelectorNode
T:System.ComponentModel.Design.ProjectTargetFrameworkAttribute
T:System.ComponentModel.Design.UndoEngine
T:System.ComponentModel.Design.UndoEngine.UndoUnit
E:System.ComponentModel.Design.UndoEngine.Undoing
E:System.ComponentModel.Design.UndoEngine.Undone
T:System.ComponentModel.Design.Data.DataSourceDescriptor
T:System.ComponentModel.Design.Data.DataSourceDescriptorCollection
T:System.ComponentModel.Design.Data.DataSourceGroup
T:System.ComponentModel.Design.Data.DataSourceGroupCollection
T:System.ComponentModel.Design.Data.DataSourceProviderService
T:System.ComponentModel.Design.Data.DesignerDataColumn
T:System.ComponentModel.Design.Data.DesignerDataConnection
T:System.ComponentModel.Design.Data.DesignerDataParameter
T:System.ComponentModel.Design.Data.DesignerDataRelationship
T:System.ComponentModel.Design.Data.DesignerDataSchemaClass
T:System.ComponentModel.Design.Data.DesignerDataStoredProcedure
T:System.ComponentModel.Design.Data.DesignerDataTable
T:System.ComponentModel.Design.Data.DesignerDataTableBase
T:System.ComponentModel.Design.Data.DesignerDataView
T:System.ComponentModel.Design.Data.IDataEnvironment
T:System.ComponentModel.Design.Data.IDesignerDataSchema
T:System.ComponentModel.Design.Serialization.BasicDesignerLoader
T:System.ComponentModel.Design.Serialization.CodeDomComponentSerializationService
T:System.ComponentModel.Design.Serialization.CodeDomDesignerLoader
T:System.ComponentModel.Design.Serialization.CodeDomLocalizationProvider
T:System.ComponentModel.Design.Serialization.CodeDomSerializer
T:System.ComponentModel.Design.Serialization.CodeDomSerializerBase
T:System.ComponentModel.Design.Serialization.CodeDomSerializerException
T:System.ComponentModel.Design.Serialization.CollectionCodeDomSerializer
T:System.ComponentModel.Design.Serialization.DesignerSerializationManager
E:System.ComponentModel.Design.Serialization.DesignerSerializationManager.SessionCreated
E:System.ComponentModel.Design.Serialization.DesignerSerializationManager.SessionDisposed
E:System.ComponentModel.Design.Serialization.DesignerSerializationManager.System#ComponentModel#Design#Serialization#IDesignerSerializationManager#ResolveName
E:System.ComponentModel.Design.Serialization.DesignerSerializationManager.System#ComponentModel#Design#Serialization#IDesignerSerializationManager#SerializationComplete
T:System.ComponentModel.Design.Serialization.ExpressionContext
T:System.ComponentModel.Design.Serialization.ICodeDomDesignerReload
T:System.ComponentModel.Design.Serialization.MemberCodeDomSerializer
T:System.ComponentModel.Design.Serialization.ObjectStatementCollection
T:System.ComponentModel.Design.Serialization.RootContext
T:System.ComponentModel.Design.Serialization.SerializeAbsoluteContext
T:System.ComponentModel.Design.Serialization.StatementContext
T:System.ComponentModel.Design.Serialization.TypeCodeDomSerializer
```

**Comment by danmosemsft** [comment] 2017-07-21 22:47
It would be interesting to know the full set you need @ysmoradi ... not sure how to find out though unless you want to add this type locally and see what happens,.

**Comment by ysmoradi** [comment] 2017-07-22 04:30
@danmosemsft I'm ready! Just tell me how to add this type locally to my app. Then I try to do the same for other types as needed. I can copy its code from mono code / reference source, but how can I add this type locally? I'm gonna spend time no matter how hard it would be.

**Comment by danmosemsft** [comment] 2017-07-22 05:08
@ysmoradi OK, it wil lbe a bit of work if you've not previously got set up to contribute. You'll want to clone this corefx repo, and then follow the docs (start [here](https://github.com/dotnet/corefx/wiki)) to build it. Then follow the docs [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) to use the result. Hopefully the docs are accurate - if not please let us know and maybe submit a fix. Ping back if you get stuck.

**Comment by danmosemsft** [comment] 2017-07-22 05:09
Once you are successfully consuming bits you built yourself, you can add the type. You'd edit src\System.ComponentModel.Annotations\ref\System.ComponentModel.Annotations.cs to add the declaratoin, and put the implementation in src\System.ComponentModel.Annotations\src.

**Comment by ysmoradi** [comment] 2017-07-22 06:40
Thanks. I'm gonna try these steps (:

**Comment by divega** [comment] 2017-07-24 10:42
@ysmoradi isn’t this issue a duplicate of https://github.com/dotnet/corefx/issues/16101? Otherwise, what is different between them?

**Comment by ysmoradi** [comment] 2017-07-24 11:27
@divega Yeah, I've mentioned it in my second comment. I realized that late.

**Comment by danmosemsft** [comment] 2017-07-24 16:22
Incidentally the focus of System.ComponentModel.* API additions in 2.0 was those that in Desktop are in System.dll. These we ported into System.ComponentModel.dll. This type is in System.ComponentModel.DataAnnotations.dll. Some types from that were already in .NET Core, but not this one. I think we would be glad in general to have more of DataAnnotations ported.

**Comment by danmosemsft** [comment] 2017-07-24 16:35
Let's dupe this against https://github.com/dotnet/corefx/issues/16101 and make progress on S.CM.DA there.

**Closed by danmosemsft** 2017-07-24 16:35 UTC
Labels: area-System.ComponentModel.DataAnnotations

**Comment by ysmoradi** [comment] 2017-07-24 16:42
It's ok. So, I'll report my progress there (:

**Comment by divega** [comment] 2017-07-25 03:52
@ysmoradi sounds good. Thanks!

**Comment by gummadikalyan** [comment] 2017-09-25 14:16
Why System.ComponentModel.Composition is not available in .Net core 2.0?
i need this for [PartCreationPolicy(CreationPolicy.Shared)] is there any other way to migrate in to .net core 2.0?

**Comment by danmosemsft** [comment] 2017-09-25 18:49
@gummadikalyan this is tracked by https://github.com/dotnet/corefx/issues/11857. We haven't got a lot of interest so far. You might add your request there to help priortize.

**Comment by AndreyBespamyatnov** [comment] 2018-09-05 12:45
@LuisPignataro Have you found a solution? I have the same issue when I'm using the EF6 with EFcore asp.net project

`TypeLoadException: Could not load type 'System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider' from assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

**Comment by LuisPignataro** [comment] 2018-09-05 14:17
No @AndreyBespamyatnov ! My solution was to recreate EF6 model with EFcore.
