### ISSUE TITLE
`[DllImport]` library dependencies. 

### ISSUE THREAD

**Issue by tactical-drone** [dotnet/corefx#33879] opened 2018-12-06 20:59 UTC
- system: `dotnet-sdk-2.2` in a Windows 10 bash (ubuntu). 

Currently `DllImport`does not support calling libraries that depend on other libraries. You get symbol not found errors. 

The proposed hack is to `[DllImport("dl")] dlopen` with `RTLD_GLOBAL` set. But this does not work. For some reason the handles for most libs returned are `0`, even for libraries that work with `DllImport`. The ones that do return handles, do so randomly. They are generated in the same way as the other libs with just different code in them. It makes no sense what so ever. 

Regardless, pre loading libraries with `dlopen` before `DllImport` calls do not solve the dependency problem. For now I had to recompile the code into a custom library, but this requires upkeep. I would rather just that it worked. But how?

How do you get interop to work with shared libraries that depend on other shared libraries?

**Comment by jkotas** [comment] 2018-12-06 21:23
This is not easily possible today with DllImport. We have plans to add new APIs in .NET Core 3.0 to allow customizing loading of the libraries for DllImport. #32015 and related issues track this work.

cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment] 2018-12-06 21:34
The implementation of `LoadLibrary`, `FreeLibrary`, `GetLibraryExport` APIs in #32015 are checked in, and will be available in the next release. You can give it a try if you build CoreCLR from the current enlistment. Thanks.

**Comment by jkotas** [comment] 2018-12-06 21:38
@swaroop-sridhar This issue is about the callback that allows loading native libraries using custom flags (`RTLD_GLOBAL` in this case). The callback was not done yet.

**Comment by tactical-drone** [comment] 2018-12-07 11:50
Thanks for the help. 

I wish I could switch to dotnet core 3.0 but netstandard 2.0 does not support it, and some of the libraries I use are netstandard. Do you guys know when dotnet core 3.0 will be supported by netstandard? I cannot find any roadmaps.

**Comment by jkotas** [comment] 2018-12-07 17:47
The roadmap for netstandard is explained in https://blogs.msdn.microsoft.com/dotnet/2018/11/05/announcing-net-standard-2-1/

**Comment by danmosemsft** [comment] 2019-05-30 19:15
@jeffschwMSFT @swaroop-sridhar is this still targeting 3.0? Unless it is a must have it seems it should be marked Future. 3.0 is only for must have at this point.

**Comment by jkotas** [comment] 2019-05-30 19:29
Duplicate of https://github.com/dotnet/coreclr/issues/22028

**Closed by jkotas** 2019-05-30 19:29 UTC
Labels: area-System.Runtime.InteropServices
