### ISSUE TITLE
System.SpanTests.ReadOnlySpanTests.OnSequenceEqualOfEqualSpansMakeSureEveryElementIsCompared failed with "Xunit.Sdk.TrueException" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23430] opened 2017-08-21 07:46 UTC
Failed test: System.SpanTests.ReadOnlySpanTests.OnSequenceEqualOfEqualSpansMakeSureEveryElementIsCompared 

COnfiguration: ubuntu16.10_release

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.10_release/3504/testReport/System.SpanTests/ReadOnlySpanTests/OnSequenceEqualOfEqualSpansMakeSureEveryElementIsCompared/

MESSAGE:
~~~
Assert.True() Failure\nExpected: True\nActual: False
~~~
STACK TRACE:
~~~
at System.SpanTests.ReadOnlySpanTests.OnSequenceEqualOfEqualSpansMakeSureEveryElementIsCompared() 
in /mnt/j/workspace/dotnet_corefx/master/ubuntu16.10_release/src/System.Memory/tests/ReadOnlySpan/SequenceEqual.T.cs:line 67
~~~

**Comment by danmosemsft** [comment] 2017-08-21 16:28
@ahsonkhan

**Comment by ahsonkhan** [comment] 2017-08-22 01:58
How can I get a repro for the test failure? Is it intermittent? There hasn't really been any code changes in the test/API implementation (https://github.com/dotnet/corefx/commits/master/src/System.Memory) so it is difficult for me to find the root cause without a way to reproduce the failure.

@AtsushiKan, any ideas of what could cause this intermittent failure in this test? I would image that each element of the array is still only being compared ones and yet on ubuntu, we see this test fail.

**Comment by AtsushiKan** [comment] 2017-08-22 14:00
Might be worth instrumenting the test to log what the actual compareNumber was. (0 or greater than 1?)

**Comment by shiftylogic** [comment] 2017-08-22 18:33
Seems like an odd place for that test to be failing. Agree with the instrumentation. I'd take is a step further and dump the tuples from the TIntLog instance as well (on a failure). It feels like memory corruption to the Span<T> instances.

**Comment by ahsonkhan** [comment] 2017-09-09 00:36
> Might be worth instrumenting the test to log what the actual compareNumber was. (0 or greater than 1?)

> Seems like an odd place for that test to be failing. Agree with the instrumentation. I'd take it a step further and dump the tuples from the TIntLog instance as well (on a failure). It feels like memory corruption to the Span instances.

https://github.com/dotnet/corefx/pull/23901

@Jiayili1, have you observed this test failing recently? If so, is it always only on ubuntu16.10?

**Comment by ahsonkhan** [comment] 2017-09-18 19:50
The last 100 Ubuntu 16.10 release builds have passed (https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.10_release/buildTimeTrend). I am not sure if this issue is reproducible or actionable. The extra logging will help if the issue re-occurs. Closing the issue.

**Closed by ahsonkhan** 2017-09-18 19:50 UTC
Labels: area-System.Memory, test-run-core
