### ISSUE TITLE
IPAddress.Parse("4294967296") does not throw FormatException on OS X

### ISSUE THREAD

**Issue by moander** [dotnet/corefx#11843] opened 2016-09-18 02:37 UTC
System.Net.IPAddress.Parse("4294967296") does not throw FormatException on OS X.

```
$ uname -a
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

$ dotnet --version
1.0.0-preview2-003121
```

Steps to reproduce

```
mkdir foo
cd foo
dotnet new
dotnet restore
sed -i '9i Console.WriteLine(System.Net.IPAddress.Parse("4294967296"));' Program.cs
dotnet run
```

The sed command writes `Console.WriteLine(System.Net.IPAddress.Parse("4294967296"));` to line 9 in Program.cs

IPAddress.Parse returns `0.0.0.0` on my Mac when using dotnet run.

```
$ dotnet run
Project bug (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
0.0.0.0
Hello World!
```

On Windows, Ubuntu, Docker on Mac, and Mono on Mac I get the expected FormatException: 

```
$ mono bin/Debug/netcoreapp1.0/bug.dll 

Unhandled Exception:
System.FormatException: An invalid IP address was specified.
```

**Comment by moander** [comment] 2016-09-18 06:15
Travis did not get an exception either:
https://travis-ci.org/aspnet/BasicMiddleware/jobs/160775559

```
info:       Expected: False
info:       Actual:   True
fail:     Microsoft.AspNetCore.HttpOverrides.IPNetworkTest.ParseAndTryParse_ShouldNotParse(networkString: "4294967296") [FAIL]
info:       Stack Trace:
info:         /Users/travis/build/aspnet/BasicMiddleware/test/Microsoft.AspNetCore.HttpOverrides.Tests/IPNetworkTest.cs(94,0): at 
```

**Comment by moander** [comment] 2016-10-14 21:04
Ping? :)

**Comment by karelz** [comment] 2017-03-04 02:02
@Priya91 can you please triage it offline? What is the impact on 2.0?

**Comment by stephentoub** [comment] 2017-03-08 14:53
https://github.com/dotnet/corefx/issues/8361

**Comment by karelz** [comment] 2017-03-08 16:01
Dupe of #8361

**Comment by stephentoub** [comment] 2017-03-08 16:23
@karelz, there's some new info in this issue though: apparently mono is generating a FormatException... at the very least, I suggest we understand why, e.g. is mono doing its own parsing?  is it using a different OS API? etc.

**Comment by karelz** [comment] 2017-03-08 17:45
Fair point, I missed that part.

**Comment by Priya91** [comment] 2017-03-08 22:16
This is a platform difference on OS X, inet_aton doesn't return invalid address for single part i-address that's greater than 32 bits. Instead it returns address of 0.0.0.0. We can identify this behavior and handle the difference in the wrapper.

```c
#include <stdio.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <arpa/inet.h>

int main()
{
	char *ipaddress = "4294967296";
	struct in_addr inaddr;

	int result = inet_aton(ipaddress, &inaddr);

	if (result == 0)
		printf("Address is invalid\n");

	else printf("address is %s\n", inet_ntoa(inaddr));

	return 0;
}
```

return,

```
lasekar-osx:myprograms lakshmipriya$ ./a.out
address is 0.0.0.0
```

**Comment by karelz** [comment] 2017-03-09 00:16
If it is documented behavior and if it is easy to do in Mac PAL, let's do it.

**Comment by akoeplinger** [comment] 2017-03-09 01:46
@stephentoub 

> e.g. is mono doing its own parsing?

We're actually using referencesource in this case: [IPAddress.cs#L307](https://github.com/mono/mono/blob/d455c0d23462d34352e4accd9953b1f487351c7f/mcs/class/referencesource/System/net/System/Net/IPAddress.cs#L307)

**Comment by stephentoub** [comment] 2017-03-09 04:05
@cipop, @pgavlin, why did we move away from this implementation for corefx?  i.e. why didn't we keep using the managed implementation that desktop is using?
https://referencesource.microsoft.com/#System/net/System/Net/IPAddress.cs,272

**Comment by CIPop** [comment] 2017-03-09 20:21
> why did we move away from this implementation for corefx? 

I have changed the code in the (very) early componentization stages (before .Net Core) to be compliant with OneCore. 
For reasons having to do with RFC compliance, support, code unification and binary size the networking architect as well as the Winsock team recommended the new APIs (e.g. `RtlIpv4AddressToStringExW`).

**Comment by karelz** [comment] 2017-03-09 22:19
@CIPop that should not prevent us from using the Desktop code on Linux/Mac, right?

It also raises a question if we want to have differences between platforms ... if we are going to use managed implementation on Linux/Mac, maybe we should use it also on Windows ... thoughts?

**Comment by CIPop** [comment] 2017-03-09 23:09
In general, this is a tough question:

On one hand, if we write/use our own parser, other apps using different frameworks (not .Net), running on the system or even the OS may not understand/allow that same string. This means we're making our framework incompatible with apps running on the same platform (e.g. a similar issue: this URI works fine in my browser but doesn't work in .Net Framework.) 
On the other hand if the string was serialized/stored in a DB by the same app running on OS A and now tries to get deserialized on OS B, having a different parser will prevent de-serialization. (e.g. continuing the one above: if we would fix URI we'd break existing apps)

We could add configuration knobs to control the sensitive behaviors but that will increase code complexity.

In this particular, I don't see this bug falling in the category above: to me this appears as a bug in the PAL layer (the way we're using the platform API) or the platform API itself.

**Comment by geoffkizer** [comment] 2017-04-17 20:27
I also think we should just parse in managed code and be consistent across platforms.

> RFC compliance

Were there issues with RFC compliance here previously?  If so what?

> support, code unification 

Having different implementations between Windows and various Unices seems to work against these goals.

In general, having a single managed implementation is better for consistency, maintenance, and often performance.  The fact that there seems to be a platform bug here (or at best, a quirk) is an argument in favor of having a single managed implementation.  In some cases we want or need to expose the behavior of the underlying OS, but this doesn't seem to be one of them.

I propose we just move back to the managed implementation here.

**Comment by stephentoub** [comment] 2017-04-17 20:36
I'm working on this now.  I currently have the managed implementation being used for Unix, but it'll be trivial to rip out the PAL and just use the managed implementation everywhere.

**Closed** 2017-04-18 22:10 UTC
Labels: area-System.Net, bug, os-mac-os-x, tenet-compatibility
