### ISSUE TITLE
FileStream.ReadAsync with FILE_FLAG_NO_BUFFERING at end of non-sector-aligned file causes ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by kevin-david** [dotnet/corefx#13270] opened 2016-11-02 18:03 UTC
I was doing some perf testing with `FILE_FLAG_NO_BUFFERING` and found that it doesn't seem to work with async whole-`FileStream` reads. I think the bug is FileStream.cs around [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileStream.Win32.cs#L919). `numBytes` gets set to a non-sector-aligned value and reused for the `ReadFileNative` which [is illegal with FILE_FLAG_NO_BUFFERING](https://msdn.microsoft.com/en-us/library/windows/desktop/cc644950(v=vs.85).aspx).

 I'm testing with .NET 4.6.2, so the source looks a bit different, but the same bug appears to be there.

If I set `numBytes = 512` in the debugger (original read size), everything works as expected for the 2nd-to-last-read. On the last `ReadAsync` (the one that should return 0 because EOF has been reached), `numBytes` is `0` so we do a seemingly-needless `SeekCore(0, SeekOrigin.Current);` then a `ReadFileNative(_handle, bytes, offset, numBytes, intOverlapped, out hr);`, which causes a `hr = 87` (`ERROR_INVALID_PARAMETER`) - apparently 0 byte reads are also illegal :) 

I wasn't quite sure where the fix should go, but it seems like using a separate variable to determine how much to `SeekCore` and returning early when `numBytes = 0` would fix the problem.

Note that using the synchronous `Read` without `FileOptions.Asynchronous` also works around this problem.

Here's a minimal repro:
```c#
static void Main(string[] args)
{
    Run().GetAwaiter().GetResult();
}

static async Task Run()
{
    var fs = GetStream(@"C:\Users\kedavid\Desktop\third_order.PNG");
    using (var ms = new MemoryStream())
    {
        var buf = new byte[512];
        int read = 0;

        while ((read = await fs.ReadAsync(buf, 0, buf.Length)) != 0)
        {
            ms.Write(buf, 0, read);
        }
    }
}

static FileStream GetStream(string fullPath)
{
    FileOptions FILE_FLAG_NO_BUFFERING = (FileOptions)0x20000000;

    return new FileStream(
       fullPath,
       FileMode.Open,
       FileAccess.Read,
       FileShare.None,
       8,
       FileOptions.Asynchronous | FILE_FLAG_NO_BUFFERING);
}
```

**Comment by ianhays** [comment] 2016-11-15 21:46
>I wasn't quite sure where the fix should go

@kevin-david FileStream was recently [moved to coreclr](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/corefx/System/IO/FileStream.cs) so any changes would need to go there.

As to the actual issue, I'm not surprised there are issues with `FILE_FLAG_NO_BUFFERING` as it isn't included as a `FileOption`. I agree that there is an issue here, but I'm not sure if that issue is that we're allowing potentially unsupported FileOptions (and not throwing an exception in the ctor) or if the issue is that we should handle these cases correctly and expose `FileOptions.NoBuffer`.

[This comment in FileOptions](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/mscorlib/src/System/IO/FileOptions.cs#L23) suggests we purposefully excluded `FILE_FLAG_NO_BUFFERING`.

cc: @JeremyKuhne

**Comment by kevin-david** [comment] 2016-11-15 22:02
Yeah, the only reason I even tried it was because of [this check](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/corefx/System/IO/FileStream.cs#L178) that explicitly allows `FILE_FLAG_NO_BUFFERING`, and it worked fine in the synchronous case. 

If the "fix" is to remove that from the allowed flags, then that's fine, but it seems like a breaking change - granted, an undocumented one - but especially so because synchronous I/O works as expected. 

If the fix isn't as simple as it appears, perhaps a short-term solution would be to disallow the combination of `NoBuffering` and `Asyncronous`

**Comment by JeremyKuhne** [comment] 2016-11-15 22:13
I think that we should create an issue to add the `FILE_FLAG_NO_BUFFERING` flag and fix the issue here while we sort out getting the flag officially added. We'll also want to try and fix this for `FileStream`s created on existing handles.

@ericstj What are your thoughts?

**Comment by ianhays** [comment] 2016-11-15 22:13
> this check that explicitly allows FILE_FLAG_NO_BUFFERING, and it worked fine in the synchronous case.

That's an odd check. I wonder why we would explicitly allow it but not include it in FileOptions. [We even have a test for it as well](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.IO.FileSystem/tests/FileStream/ctor_str_fm_fa_fs_buffer_fo.cs#L43). My guess would be that it's because we didn't want to/couldn't support it on Unix so we left it out of FileOptions but still allowed it on Windows when explicitly specified. @ericstj or @stephentoub may know the reasoning.

>If the fix isn't as simple as it appears, perhaps a short-term solution would be to disallow the combination of NoBuffering and Asyncronous

That seems like a reasonable suggestion, though I don't want us to be in that state when release time comes around. Since the same issue is present on 4.6.2, we can assume it's a low enough priority that we can fix it with a long-term solution.

**Comment by czifro** [comment] 2016-12-26 21:49
May I ask why `O_DIRECT` is not supported in the `pal_io.cpp`? I may be mistaken, but wouldn't this address this?

**Comment by ianhays** [comment] 2017-01-03 21:59
I'm marking this as `up for grabs` if anyone wants to submit an API proposal to add `FILE_FLAG_NO_BUFFERING` or submit the fix from the OP into the current code.

**Comment by JeremyKuhne** [comment] 2020-01-17 19:26
You can manually set the flag, as we allow it. We should make this one public if this is hitting enough people. We should also consider removing validation for the options. Closing for now pending more data on need/usage.

**Closed by JeremyKuhne** 2020-01-17 19:26 UTC
Labels: area-System.IO, enhancement, up-for-grabs
