### ISSUE TITLE
Deserialization of negative enum not working 

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#37727] opened 2019-05-16 20:48 UTC
Serialization test for negative enum is working but failing for deserialization
--- UPDATE: updated enum values to numeric as string not supported, removed flag enum, nullable enum class tests as not supported too
```csharp
public enum NegativeEnum
{
    Negative = -1,
    Zero = 0,
    Positive = 1
}

public class NegativeEnumClass
{
    public NegativeEnum Value1 { get; set; }
    public NegativeEnum Value2 { get; set; }
}

[Fact]
public static void DeserializeNegativeEnum()
{
    string json = @"{
  ""Value1"": -1,
  ""Value2"": -2147483648
}";
    NegativeEnumClass negativeEnumClass = JsonSerializer.Parse<NegativeEnumClass>(json);
    Assert.Equal(NegativeEnum.Negative, negativeEnumClass.Value1);
    Assert.Equal((NegativeEnum)int.MinValue, negativeEnumClass.Value2);
}

Exception: System.Text.Json.JsonReaderException: 'The JSON value from [NegativeEnumClass].Value1 could not be converted to NegativeEnum.'
 
[Fact]
public static void DeserializeZeroPaddedEnum()
{
    string json = @"{
  ""Value1"": 01,
  ""Value2"": 0
}";
    NegativeEnumClass negativeEnumClass = JsonSerializer.Parse<NegativeEnumClass>(json);
    Assert.Equal(NegativeEnum.Positive, negativeEnumClass.Value1);
    Assert.Equal(NegativeEnum.Zero, negativeEnumClass.Value2);
}

Exception: System.Text.Json.JsonReaderException: ''1' is an invalid end of a number. Expected a delimiter. LineNumber: 2 | BytePositionInLine: 13.'

```

**Comment by ahsonkhan** [comment] 2019-05-16 23:24
cc @JeremyKuhne

**Comment by krwq** [comment] 2019-05-23 00:05
First issue is already fixed. Second issue is by design and might be fixed in the future ([octal numbers are not supported](https://github.com/dotnet/corefx/issues/37882))

**Closed by krwq** 2019-05-23 00:05 UTC
Labels: area-System.Text.Json, bug
