### ISSUE TITLE
System.Uri escaping result is incorrect

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#38904] opened 2019-06-25 21:40 UTC
This issue is copied from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934651. 

1. Open C# interactive window.
2. Type `new Uri("C:\\%20hello world.txt", UriKind.Absolute). AbsolutePath`.
3. The result is `C:/%2520hello%20world.txt`. [Good]
4. Then type `new Uri("C:\\%20hello world中文字符.txt", UriKind.Absolute). AbsolutePath`.
5. The result is `C:/%20hello%20world%E4%B8%AD%E6%96%87%E5%AD%97%E7%AC%A6.txt`. [NG]
6. Expected: The "%2520" between "C:/" and "hello" should be escaped.

**Comment by davidsh** [comment] 2019-06-25 22:19
Sounds like a duplicate of other escaping issues.

@wtgodbe

**Comment by wtgodbe** [comment] 2019-06-25 22:27
Looks to be a dupe of https://github.com/dotnet/corefx/issues/32301

**Closed by wtgodbe** 2019-06-25 22:27 UTC
Labels: area-System.Net, bug
