### ISSUE TITLE
System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success failed with "System.ObjectDisposedException"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#22845] opened 2017-08-02 06:34 UTC
Failed test: System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_opensuse42.1_release/126/testReport/System.Net.WebSockets.Client.Tests/SendReceiveTest/SendReceive_VaryingLengthBuffers_Success_server__wss___corefx_net_cloudapp_net_WebSocket_EchoWebSocket_ashx_/

MESSAGE:
~~~
System.OperationCanceledException : Aborted
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'SslStream'.
~~~
STACK TRACE:
~~~
at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 740 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.WebSockets.Client.Tests.SendReceiveTest.<SendReceive_VaryingLengthBuffers_Success>d__9.MoveNext() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/System.Net.WebSockets.Client/tests/SendReceiveTest.cs:line 309 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
----- Inner Stack Trace ----- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 446 
at System.Net.Security.SslState.get_SecureStream() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 384 
at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult) 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 556 
at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__70.MoveNext() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 1141 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext() 
in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_opensuse42.1_release/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 708
~~~

**Comment by Jiayili1** [comment] 2017-08-04 02:50
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170804.01/workItem/System.Net.WebSockets.Client.Tests

**Comment by Jiayili1** [comment] 2017-08-04 06:21
This issue is repro on Full Framework Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170804.01/workItem/System.Net.WebSockets.Client.Tests/analysis/xunit/System.Net.WebSockets.Client.Tests.SendReceiveTest~2FSendReceive_VaryingLengthBuffers_Success(server:%20ws:~2F~2Fcorefx-net.cloudapp.net~2FWebSocket~2FEchoWebSocket.ashx)

**Comment by Jiayili1** [comment] 2017-08-04 07:13
This issue is also repro in CI, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_ubuntu14.04_debug/131/testReport/System.Net.WebSockets.Client.Tests/SendReceiveTest/SendReceive_VaryingLengthBuffers_Success_server__ws___corefx_net_cloudapp_net_WebSocket_EchoWebSocket_ashx_/

**Comment by Jiayili1** [comment] 2017-08-24 06:27
failed again in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170824.01/workItem/System.Net.WebSockets.Client.Tests/analysis/xunit/System.Net.WebSockets.Client.Tests.SendReceiveTest~2FSendReceive_VaryingLengthBuffers_Success(server:%20wss:~2F~2Fcorefx-net.cloudapp.net~2FWebSocket~2FEchoWebSocket.ashx)

**Comment by Jiayili1** [comment] 2017-08-28 07:10
Now it fails: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fuwp~2F/build/20170828.01/workItem/System.Net.WebSockets.Client.Tests/analysis/xunit/System.Net.WebSockets.Client.Tests.SendReceiveTest~2FSendReceive_VaryingLengthBuffers_Success(server:%20ws:~2F~2Fcorefx-net.cloudapp.net~2FWebSocket~2FEchoWebSocket.ashx)

The test `System.Net.WebSockets.Client.Tests.SendReceiveTest/SendReceive_VaryingLengthBuffers_Success(server: ws://corefx-net.cloudapp.net/WebSocket/EchoWebSocket.ashx)` has failed.

Assert.Equal() Failure\r
    Expected: 65535\r
    Actual:   1376

        Stack Trace:

           at System.Net.WebSockets.Client.Tests.SendReceiveTest.<SendReceive_VaryingLengthBuffers_Success>d__9.MoveNext() in E:\A\_work\1017\s\corefx\src\System.Net.WebSockets.Client\tests\SendReceiveTest.cs:line 319
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Build : Master - 20170828.01 (UWP F5 Tests)
Failing configurations:
- Windows.10.Arm64-arm
  - Release

**Comment by karelz** [comment] 2017-12-24 05:52
Duplicate of #23765

**Closed by karelz** 2017-12-24 05:52 UTC
Labels: area-System.Net, test-run-core
