### ISSUE TITLE
HttpClient is not sending cookies to server in some scenarios

### ISSUE THREAD

**Issue by kichalla** [dotnet/corefx#6737] opened 2016-03-08 00:21 UTC
**Repro code solution:**
https://github.com/kichalla/httpclientnotsendingcookie

**Steps to run the repro code**
- `dotnet restore` and `dotnet build` the `WebApplication1` app. This is a simple ASP.NET Core web app which has couple of middleware.
- Now do `dotnet run` the web app and it should listen at the default address `http://localhost:5000`
- Now for the client `dotnet restore`, `dotnet run` the project `coreclrhttpclient`.

**Expected:**
Postdata action received the following cookies:  
.AspNetCore.Session : RAExEmXpoCbueP_QYM,
.AspNetCore.Antiforgery.Xam7_OeLcN4 : CfDJ8NGNxAt7CbdClq3UJ8_6w_4661wRQZT1aDtUOIUKshbcV4P0NdS8klCL5qGSN-PNBBV7w23G6MYpQ81t0PMmzIN4O04fqhZ0u1YPv66mixtkX3iTi291DgwT3o5kozfQhe08-RAExEmXpoCbueP_QYM

**Actual:**
Postdata action received the following cookies:  
.AspNetCore.Session : RAExEmXpoCbueP_QYM

@natemcmaster @Tratcher @muratg

**Comment by stephentoub** [comment] 2016-03-08 00:25
@kichalla, what OS is this?  Or is this for all platforms?

**Comment by davidsh** [comment] 2016-03-08 00:26
Also, what version of the packages are you using?  Please make sure to use the latest packages on MYGET.ORG and not NuGet.org.  There were many fixes made to cookie logic.  For example, does this scenario use redirection?  If so, there was a bug fixed in HttpClient several months ago in that area.

**Comment by kichalla** [comment] 2016-03-08 00:37
@stephentoub This was on Windows. I can try to repro on other platforms and will update this thread. (BTW, dotnet cli seems to have a issue template. Probably this repo also should have it :smile: )

@davidsh I am pointing to the myget feed `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`. This does not use redirection. I probably know the bug related to redirection and cookies that you are referring to as it was filed by me.

**Comment by davidsh** [comment] 2016-03-08 17:41
@kichalla 

I am getting errors trying to do the `dotnet restore` of the WebApplication.

Do I need a special feed configuration to restore this?

>C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\WebApplication1>dotnet restore
info : Restoring packages for C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\WebApplication1\project.json...
error: Unable to resolve Microsoft.AspNetCore.IISPlatformHandler (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Mvc.Dnx (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Mvc (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Diagnostics (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.StaticFiles (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Mvc.TagHelpers (>= 1.0.0) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.IISPlatformHandler (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Mvc (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Diagnostics (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.StaticFiles (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.Mvc.TagHelpers (>= 1.0.0) for .NETFramework,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNetCore.IISPlatformHandler (>= 1.0.0) for .NETStandardApp,Version=v1.5.
error: Unable to resolve Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0) for .NETStandardApp,Version=v1.5.
error: Unable to resolve Microsoft.AspNetCore.Mvc (>= 1.0.0) for .NETStandardApp,Version=v1.5.
error: Unable to resolve Microsoft.AspNetCore.Diagnostics (>= 1.0.0) for .NETStandardApp,Version=v1.5.
error: Unable to resolve Microsoft.AspNetCore.StaticFiles (>= 1.0.0) for .NETStandardApp,Version=v1.5.
error: Unable to resolve Microsoft.AspNetCore.Mvc.TagHelpers (>= 1.0.0) for .NETStandardApp,Version=v1.5.
info : Committing restore...
info : Restore failed in 9271ms.
Restoring Tool 'dotnet-razor-tooling' for 'C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\WebApplication1\obj\3c10ffed-522e-4314-8aaa-265fbb5ce613\bin\project.json' in 'C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\WebApplication1\obj\3c10ffed-522e-4314-8aaa-265fbb5ce613\bin'
info : Restoring packages for C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\WebApplication1\obj\3c10ffed-522e-4314-8aaa-265fbb5ce613\bin\project.json...
error: Unable to resolve dotnet-razor-tooling (>= 1.0.0) for DNXCore,Version=v5.0.
info : Committing restore...
info : Restore failed in 1974ms.
Object reference not set to an instance of an object.

**Comment by kichalla** [comment] 2016-03-08 17:48
Oh yes. I just now pushed the appropriate Nuget.config file to the repo.

**Comment by davidsh** [comment] 2016-03-08 18:03
I'm still getting errors.  Here are some when doing `dotnet restore` of the client:

>C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\coreclrhttpclient>dotnet restore
info : Restoring packages for C:\Users\dshulman\Downloads\httpclientnotsendingcookie-master\coreclrhttpclient\project.json...
error: System.Net.Http 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Net.Http on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with win7-x64.
error: System.Net.Primitives 4.0.11-rc3-23908 provides a compile-time reference assembly for System.Net.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with win7-x64.
error: System.Text.Encoding 4.0.11-rc3-23908 provides a compile-time reference assembly for System.Text.Encoding on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with win7-x64.
error: System.Threading.Tasks 4.0.11-rc3-23908 provides a compile-time reference assembly for System.Threading.Tasks on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with win7-x64.
error: Microsoft.Win32.Primitives 4.0.1-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with win7-x64.

**Comment by kichalla** [comment] 2016-03-08 18:34
Hmm, I do not see the package restore issue. (I had tried after deleting the lock.json, nuget v3-cache and .nuget\packages)

**Comment by natemcmaster** [comment] 2016-03-08 18:36
> error: System.Net.Primitives 4.0.11-rc3-23908

@davidsh it appears you have rc3 packages on your computer. Kiran's repo is on RC2. Try clearing caches.

**Comment by kichalla** [comment] 2016-03-08 18:38
Actually the restore at my end also used RC3 packages. Just FYI...It repros in both rc2 and rc3. But yeah you can restrict to rc2 if you want in the project.json dependencies

**Comment by davidsh** [comment] 2016-03-08 21:24
@kichalla I'm still unable to restore and run the web server part of the repro.  Due to all the tools in flux and the change from DNX to NETSTANDARDAPP and to dotnetcli, etc., it is just not building on my machine.

Can you create a .NET Framework 4.6 version of your MVC localhost server?  Then  I could probably build that easier.  I don't need help with the client part of the repro.  I still can't build it but the source code of the Program.cs is simple enough that I can redo it as an Xunit test.

**Comment by muratg** [comment] 2016-03-08 21:29
Are you guys both on the same dotnet CLI version?  Restore behavior may have changed between two versions, as CLI team consumes new nuget bits often.

**Comment by kichalla** [comment] 2016-03-08 21:35
Good point @muratg . My CLI version is 1.0.0-beta-001540

@davidsh Sure, I can create one.

**Comment by davidsh** [comment] 2016-03-08 21:37
FWIW I am using the very latest dotnetcli:
https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe

**Comment by kichalla** [comment] 2016-03-08 22:01
I added a MVC5 app (.NET Framework 4.6) to the solution now and pushed. The client code did not change. Just FYI, you might need to change the server port in the client code depending on where the app is hosted.

**Comment by davidsh** [comment] 2016-03-08 22:46
@kichalla Thx, I'm able to repro this now.

@justinvp I'm still debugging this but I suspect that the recent changes in PR #3199 seems to have broken WinHttpResponseParser.GetResponseHeader().  It is no longer iterating to the next duplicate header when using the overload using the `index` parameter:

```c#
        public unsafe static bool GetResponseHeader(
            SafeWinHttpHandle requestHandle,
            uint infoLevel,
            ref char[] buffer,
            ref uint index,
            out string headerValue)
```

In this case, it is "iterating" by returning two `Set-Cookie` headers but they are the same first header and not the second `Set-Cookie-Header`.  I'm still investigating.

**Comment by justinvp** [comment] 2016-03-08 23:14
> In this case, it is "iterating" by returning two Set-Cookie headers but they are the same first header and not the second Set-Cookie-Header. I'm still investigating.

@davidsh, Hmm, I thought I tested this, but it's possible I screwed something up. Let me know if you'd like me to take over the investigation.

**Comment by kichalla** [comment] 2016-03-08 23:21
Just FYI...one thing that I noticed while investigating this issue at my end was that if had renamed the cookies to be something like (cookie1, cookie1-value) and (cookie2, cookie2-value), then they get sent without any issue.
Now I you change the value of Cookie2 to the same value as in my repro, it does not get sent. Probably something related to length of the value may be, not sure.

**Comment by davidsh** [comment] 2016-03-09 00:03
Yes, I have discovered it has something to do with the length.

This test fails. Still investigating as to what length triggers the problem:

```c#
        [Fact]
        public async Task BugRepro()
        {
            var handler = new HttpClientHandler();
            handler.AllowAutoRedirect = false;

            string cookie1Name = ".AspNetCore.Session";
            string cookie1Value = "RAExEmXpoCbueP_QYM";
            string cookie2Name = ".AspNetCore.Antiforgery.Xam7_OeLcN4";
            string cookie2Value = "CfDJ8NGNxAt7CbdClq3UJ8_6w_4661wRQZT1aDtUOIUKshbcV4P0NdS8klCL5qGSN-PNBBV7w23G6MYpQ81t0PMmzIN4O04fqhZ0u1YPv66mixtkX3iTi291DgwT3o5kozfQhe08-RAExEmXpoCbueP_QYM";
            using (var client = new HttpClient(handler))
            {
                string url = string.Format(
                    "http://httpbin.org/cookies/set?{0}={1}&{2}={3}",
                    cookie1Name,
                    cookie1Value,
                    cookie2Name,
                    cookie2Value);
                HttpResponseMessage response = await client.GetAsync(url);
                _output.WriteLine("Response headers: " + Environment.NewLine + response.ToString());
                int count = handler.CookieContainer.Count;
                _output.WriteLine("CookieContainer count: {0}", count);
                Assert.Equal(2, count);
            }
        }
```

**Comment by davidsh** [comment] 2016-03-09 00:20
Looks like if `cookie2Value` has a length of 84 it doesn't work but it does work for a length of 83.

```c#
string cookie2Value = "12345678901234567890123456789012345678901234567890123456789012345678901234567890123"; // works

string cookie2Value = "123456789012345678901234567890123456789012345678901234567890123456789012345678901234" // does not work;
```

**Comment by davidsh** [comment] 2016-03-09 00:20
@justinvp Can you take a look at this?  I think there is something broken in the buffer logic.

**Comment by justinvp** [comment] 2016-03-09 00:22
Yeah, looking into it now.

**Comment by davidsh** [comment] 2016-03-09 00:23
This looks like suspicious.  It has a fixed length of 128 chars:

```c#
        public unsafe static bool GetResponseHeader(
            SafeWinHttpHandle requestHandle,
            uint infoLevel,
            ref char[] buffer,
            ref uint index,
            out string headerValue)
        {
            const int StackLimit = 128;

            Debug.Assert(buffer == null || (buffer != null && buffer.Length > StackLimit));

            int bufferLength;

            if (buffer == null)
            {
                bufferLength = StackLimit;
                char* pBuffer = stackalloc char[bufferLength];
```

**Comment by justinvp** [comment] 2016-03-09 01:18
I found the root cause. It has to do with `WinHttpQueryHeaders` always incrementing the index, even if it fails due to `ERROR_INSUFFICIENT_BUFFER`. When we get that failure, the index has already been incremented, so when we retry with a larger buffer, it's already looking for the next index. The fix is to reset the index on `ERROR_INSUFFICIENT_BUFFER` so it can try that same index again with the larger buffer, instead of looking for the next index.

I'm working on the fix and will submit a PR.

**Comment by justinvp** [comment] 2016-03-09 02:35
I've submitted #6764 with a fix. Sorry for the regression.

**Closed** 2016-03-09 18:13 UTC
Labels: blocking-partner, bug, System.Net
