### ISSUE TITLE
Improve boolean type conversion support

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#37971] opened 2019-05-27 19:32 UTC
I think JsonSerializer should support at least these values [1, 0, "true", "false"]
```csharp
    [Fact]
    public void DeserializeBooleans()
    {
        IList<bool> l = JsonSerializer.Parse<IList<bool>>(@"[
  1,
  0,
  1.1,
  0.0,
  ""true"",
  ""TRUE"",
  ""false"",
  ""FALSE""
]");

        int i = 0;
        Assert.Equal(true, l[i++]);
        Assert.Equal(false, l[i++]);
        Assert.Equal(true, l[i++]);
        Assert.Equal(false, l[i++]);
        Assert.Equal(true, l[i++]);
        Assert.Equal(true, l[i++]);
        Assert.Equal(false, l[i++]);
        Assert.Equal(false, l[i++]);
    }
```

**Comment by ahsonkhan** [comment] 2019-05-28 20:23
Duplicate of https://github.com/dotnet/corefx/issues/37740.

We generally want to avoid any type coercion/inference by default and only let users opt-in to such behavior if they implement custom converters.

**Comment by ahsonkhan** [comment] 2019-05-28 20:56
The extension/converter feature is tracked by https://github.com/dotnet/corefx/issues/36639.

Closing as by-design.

**Closed by ahsonkhan** 2019-05-28 20:56 UTC
Labels: area-System.Text.Json, enhancement
