### ISSUE TITLE
System.Text.Encodings.Web.TextEncoder.EncodeIntoBuffer throws ArgumentException on 32-bit Mono

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#4455] opened 2015-11-11 23:34 UTC
Simple repro:

    using System;
    using System.Text.Encodings.Web;
    
    namespace EncodeIssue
    {
        public class Program
        {
            public void Main(string[] args)
            {
                Console.WriteLine(UrlEncoder.Default.Encode("na me"));
            }
        }
    }

When run:

    System.ArgumentException: Argument encoder does not implement MaxOutputCharsPerInputChar correctly.
      at System.Text.Encodings.Web.TextEncoder.EncodeIntoBuffer (System.Char* value, Int32 valueLength, Int32 firstCharacterToEncode, System.Char* buffer, Int32 bufferLength) [0x00000] in <filename unknown>:0 
      at System.Text.Encodings.Web.TextEncoder.Encode (System.String value) [0x00000] in <filename unknown>:0 
      at EncodeIssue.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
      at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
      at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
      at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
      at Microsoft.Dnx.ApplicationHost.Program+<>c__DisplayClass3_0.<ExecuteMain>b__0 () [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.Task`1[System.Threading.Tasks.Task`1[System.Int32]].InnerInvoke () [0x00000] in <filename unknown>:0 
      at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 

Make sure you're using a 32-bit Mono to repro, since it doesn't happen on 64-bit.

**Comment by Tratcher** [comment] 2015-11-11 23:47
@KrzysztofCwalina

**Comment by eerhardt** [comment] 2015-11-19 00:20
So I was able to repro this exception on my mac using dnx 1.0.0-rc2-16128 -r mono.

I traced the problem down to the stackalloc call here: https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/TextEncoder.cs#L63

```C#
string result;
if (bufferSize < 1024)
{
    char* wholebuffer = stackalloc char[bufferSize];
    int totalWritten = EncodeIntoBuffer(valuePointer, value.Length, firstCharacterToEncode, wholebuffer, bufferSize);
    result = new string(wholebuffer, 0, totalWritten);
}
```

The issue isn't the stackalloc itself - mono appears to be creating the memory correctly. Instead the issue is what happens to the `bufferSize` variable after the stackalloc. On my machine, before the call to stackalloc `bufferSize` is 45 (5 input characters X UrlEncoder.MaxOutputCharactersPerInputCharacter which is 9).  `bufferSize` is then passed into the EncodeIntoBuffer method. However, once execution reaches the EncodeIntoBuffer method, the value of the `bufferLength` parameter being passed in is now 0.

If I happen to touch `bufferSize` right after doing the stackalloc (say call `bufferSize.ToString()`), then the value passed into EncodeIntoBuffer is correctly 45 and the exception no longer repros.  But the way the code is written now, it appears that the parameter is not being passed correctly after the stackalloc.  I also commented out the stackalloc section and just always declare the buffer on the heap, and the code works fine then as well.

@KrzysztofCwalina - do you know someone on the Mono team that can take this issue from here?  I think the best approach would be to log the issue in the Mono project and close this issue out since there isn't anything wrong with the corefx code.

**Comment by ellismg** [comment] 2015-11-19 00:24
@eerhardt You can open a bug against mono here: https://bugzilla.xamarin.com/.  Good find!

**Comment by eerhardt** [comment] 2015-11-19 17:00
I've opened https://bugzilla.xamarin.com/show_bug.cgi?id=36052 for the underlying Mono issue.

For now to unblock ASP.NET, I am testing switching the order of the parameters to EncodeIntoBuffer, which seems to workaround the issue.

**Closed** 2015-11-20 03:05 UTC
Labels: 2 - In Progress, System.Text.Encoding
