### ISSUE TITLE
DateTime? proprety value cannot be set correctly

### ISSUE THREAD

**Issue by TongQijie** [dotnet/corefx#16703] opened 2017-03-04 00:57 UTC
i have a class contains a property whose type is DateTime?

```cs
public class SubItem
{
    public string StringValue { get; set; }

    public int? IntegerValue { get; set; }

    public DateTime? DateValue { get; set; }

    public bool? BooleanValue { get; set; }
}
```

i set value to property 'DateValue' like this:

```cs
var subItem = new SubItem();
subItem.DateValue = DateTime.Now;
```

the problem is that subItem.DateValue is always {01/01/0001 00:07:28}. why?

please help me...

**Comment by TongQijie** [comment] 2017-03-04 00:59
here is my dotnet --info:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

**Comment by TongQijie** [comment] 2017-03-04 07:21
it works fine on windows.

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by svick** [comment] 2017-03-04 15:40
The following code works fine for me on Linux:

```c#
using System;

public class SubItem
{
    public string StringValue { get; set; }

    public int? IntegerValue { get; set; }

    public DateTime? DateValue { get; set; }

    public bool? BooleanValue { get; set; }
}

public class Program
{
    public static void Main()
    {
        var subItem = new SubItem();
        subItem.DateValue = DateTime.Now;
        Console.WriteLine(subItem.DateValue);
    }
}
```

 Could you share a complete program that demonstrates the issue? How exactly are you viewing the value? Are you using some debugger or IDE? Are you sure your machine has the correct time set?

**Comment by TongQijie** [comment] 2017-03-05 01:39
```cs
public class Program
{
    public static void Main(string[] args)
    {
        var subItem = new SubItem();
        subItem.DateValue = DateTime.Now;

        Console.WriteLine(subItem.DateValue?.ToString());
    }

    public class SubItem
    {
        public string StringValue { get; set; }

        public int? IntegerValue { get; set; }

        public DateTime? DateValue { get; set; }

        public bool? BooleanValue { get; set; }
    }
}
```

today, i found it worked fines, but it was weird to watch variable's value when debugging.

[[https://github.com/TongQijie/resource/blob/master/img/201703050001.png]]

**Comment by svick** [comment] 2017-03-05 03:42
I can see the same behavior in VS Code on Linux.

I believe this is https://github.com/OmniSharp/omnisharp-vscode/issues/753, which is in turn caused by https://github.com/dotnet/coreclr/issues/7115, which should be fixed in the next version of .Net Core. But it is only a debugging bug, so it shouldn't affect how your application actually executes.

**Comment by tarekgh** [comment] 2017-03-05 18:33
Issue moved to [dotnet/coreclr #9967](https://github.com/dotnet/coreclr/issues/9967) via [**ZenHub**](https://www.zenhub.com/)

**Closed by tarekgh** 2017-03-05 18:33 UTC
Labels: area-System.Globalization
