### ISSUE TITLE
ReadAsync might never return if FlushAsync cancellation token is cancelled

### ISSUE THREAD

**Issue by pakrym** [dotnet/corefx#31201] opened 2018-07-19 18:37 UTC
It has to happen while FlushAsync is running.

**Comment by danmosemsft** [comment] 2018-07-24 18:05
@pakrym @davidfowl process for 2.1 ports is (1) fill in template below here in the issue (2) create 2.1 PR (3) mail netcoreship with link to issue (4) if okayed, they (me) will mark servicing-consider for big shiproom (5) big shiproom will mark servicing-approved (6) check branch is open before merging.

		#### Description
		 
		#### Customer Impact
		 
		#### Regression?
		 
		#### Risk

**Comment by Eilon** [comment] 2018-08-02 23:41
To shiproom: This affects ASP.NET Core scenarios such as static files (extremely common) and SignalR (extremely cool). Because the cancellation token isn't working as expected, listeners can be left in the dark, which can lead to broken clients.

**Comment by vivmishra** [comment] 2018-08-07 18:31
Approved for 2.1.5.

**Comment by danmosemsft** [comment] 2018-08-14 20:45
Moving label to PR per new process

**Comment by danmosemsft** [comment] 2018-08-21 18:49
This needs a 2.1. PR

**Comment by pakrym** [comment] 2018-08-21 19:43
https://github.com/dotnet/corefx/pull/31871

**Comment by karelz** [comment] 2018-09-06 18:01
Fixed in release/2.1 branch in PR #31871. Will be part of 2.1.5 release.

**Closed by karelz** 2018-09-06 18:01 UTC
Labels: area-System.IO.Pipelines, bug
