### ISSUE TITLE
SQL Server connection fails via web app, but succeeds in all other tools

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/corefx#4586] opened 2015-11-19 19:38 UTC
I'm running ASP.NET 5, RC1 and am trying to connect to a MSSQL server instance on the local network.  There are no firewalls between here and there.  *If I try the same code in the same environment under MVC 5, everything works fine.*

I am able to connect to the server successfully with the VS2015 Server Explorer as well as SQL Management Studio.

When I attempt to connect to the DB with the following connection string (which I got from the VS2015 Server Explorer), it fails with the given error:

string cs = @"Data Source=DBSERVER\INSTANCE1;Initial Catalog=MyDb;User ID=ASPNET-Db-User;Password=thepassword";

The code is:
 System.Data.SqlClient.SqlConnection con = new System.Data.SqlClient.SqlConnection(cs);
 con.Open();

The exception is:

An exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.SqlClient.dll but was not handled in user code

Additional information: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

The stack is:
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Isengard.Startup.ConfigureServices(IServiceCollection services) in C:\TFS\Isengard\src\Isengard\Startup.cs:line 46

**Comment by joshfree** [comment] 2015-11-19 21:25
@corivera @saurabh500 @kkurni PTAL

**Comment by saurabh500** [comment] 2015-11-19 22:21
@SimonOrdo  Named Instances are not supported in CoreFX. 
SSMS and VS2015 server explorer do not use the CoreFX .Net for SqlServer connections.

To connect to the SqlServer instance using an app running on CoreFX, use the server name "dbname.example.com" and in case the port of the running instance is different from the default port, then you need to specify the port in the connection string.

e.g. dbname.example.com:1234

**Comment by saurabh500** [comment] 2015-11-19 22:39
@SimonOrdo I am closing this issue. 
Please reopen if the suggested fix doesn't work for you

**Closed by saurabh500** 2015-11-19 22:39 UTC
Labels: System.Data

**Comment by SimonOrdo** [comment] 2015-11-19 22:40
@saurabh500 
I've made the changes you suggested and got a " (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.)" error.

Connecting to port 1434, which is where the SqlBrowser is listening does not work because I believe it tries to connect to TCP port 1434, whereas the SqlBrowser is listening on the UDP port.

Using a port scanner (PortQry.exe) I was able to see the TCP port at which the actual instance is listening on.  If I specify that TCP port, then it connects.

Shouldn't the provider negotiate with the SqlBrowser on UDP 1434 to see where the actual instance is listening?

**Comment by saurabh500** [comment] 2015-11-19 22:54
@SimonOrdo  
The Sql Browser plays a role when the named instance support is present. 

SqlBrowser can map  named instances to the ports. But in case many instances are running on the same server, then it won't know which port to connect to just by the server name. 
More details at 
https://msdn.microsoft.com/en-us/library/hh510203.aspx

>> I've made the changes you suggested and got a " (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.)" error.

You can also use Sql Server Configuration Manager to look up the port of any server instance that you are running apart from the port scanner.

**Comment by SimonOrdo** [comment] 2015-11-20 15:57
@saurabh500 I've got it all sorted now!  Thanks a ton.  Interesting gotcha about CoreCLR not supporting named pipes.  Is that a temporary thing or a "by design" issue?

**Comment by saurabh500** [comment] 2015-11-20 22:24
@SimonOrdo No problem. Glad to be of help.
 Named pipes are supported on CoreCLR on windows (but not on Linux and OSX). 
Named Instances are not supported on any platform. The issue you are facing are related to Named Instance.

This is by design that we had omitted the capability in the interest of concentrating on TCP connectivity across platforms to come to a MVP.
