### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientHandlerTest / PostAsync_RedirectWith307_LargePayload 

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#23768] opened 2017-09-02 23:26 UTC
## History of failures

Day | Build | OS | Error message
-- | -- | -- | --
8/1 | 20170801.02 | Ubuntu17.10 | TaskCanceledException: A task was canceled.
8/1 | 20170801.03 | Ubuntu16.04 | TaskCanceledException: A task was canceled.
8/2 | 20170802.01 | Ubuntu16.04 | TaskCanceledException: A task was canceled.
8/4 | 20170804.01 | Win7 | [ManagedHandler] TaskCanceledException: A task was canceled.
8/4 | 20170804.01 | Win7 | TaskCanceledException: A task was canceled.
8/16 | 20170816.01 | Debian90 | [ManagedHandler] OperationCanceledException: The operation was canceled.
9/1 | 20170901.01 | Debian90 | [ManagedHandler] OperationCanceledException: The operation was canceled.
9/1 | 20170901.02 | Ubuntu17.10 | [ManagedHandler] OperationCanceledException: The operation was canceled.
1/19 | | | Test re-enabled in PR #26399
1/21 | 20180121.02 | SLES12 | [ManagedHandler] OperationCanceledException : The operation was canceled. - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180121.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest~2FPostAsync_RedirectWith307_LargePayload)
1/22 | 20180122.02 | Ubuntu16.04 | [ManagedHandler] OperationCanceledException : The operation was canceled. - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.02/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandlerTest~2FPostAsync_RedirectWith307_LargePayload)

# Original report

Test failed during PR run:
https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/169daaad2062ab623fdafa738c3fdbc778d3652e

Unhandled Exception of Type System.Threading.Tasks.TaskCanceledException
Message :
System.Threading.Tasks.TaskCanceledException : A task was canceled.

**Comment by Jiayili1** [comment] 2017-09-04 02:33
Following tests failed with same issue:
PostAsync_CallMethod_StreamContent
SendAsync_SendRequestUsingMethodToEchoServerWithContent_Success

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_debian8.4_debug/157/testReport/System.Net.Http.Functional.Tests/HttpClientHandlerTest/PostAsync_CallMethod_StreamContent_remoteServer__http___corefx_net_cloudapp_net_VerifyUpload_ashx__content__StreamContentWithSyncAsyncCopy___Headers_________expectedData___62__23__186__150__174_______/
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_debian8.4_debug/157/testReport/System.Net.Http.Functional.Tests/HttpClientHandlerTest/SendAsync_SendRequestUsingMethodToEchoServerWithContent_Success_method____DELETE____secureServer__True_/

**Comment by karelz** [comment] 2018-01-23 06:32
New hits, reopening - top post updated with history.

**Comment by pjanotti** [comment] 2018-01-23 15:11
This test goes against a remote server perhaps we should add a retry of some sort, on the short run I will disable it again, while we investigate other issues related to managed handler.

**Comment by karelz** [comment] 2018-01-23 15:51
We have many remote-server hitting tests and they don't fail that often. I would not blame remote-servers, until we have some evidence.

**Comment by pjanotti** [comment] 2018-01-23 16:40
Yes, the fact that there are more failures with the managed handler is unlike to be a coincidence.

**Comment by davidsh** [comment] 2018-01-23 22:00
>We have many remote-server hitting tests and they don't fail that often. I would not blame remote-servers, until we have some evidence.

This might be related to the test failures that @rmkerr was investigating which might be due to Xunit threadpool scaling/deadlock issues when running tests in parallel.

**Comment by pjanotti** [comment] 2018-01-23 23:34
@rmkerr do you have an issue # tracking that?

**Comment by rmkerr** [comment] 2018-01-23 23:42
We have an issue tracking the specific failure we're seeing (#26092). Unfortunately I haven't been able to make much progress on the issue, and am still only speculating on what might be causing it. I can reproduce the issue on my machine and have logs of the failures, but not much more than that.

**Comment by pjanotti** [comment] 2018-01-24 16:28
The data below comes from 312 test runs in my Windows 10 box including OuterLoop but with `-parallel none` to reduce non-determinism and to avoid test deadlocks that I still need to investigate.


| # Failures | Remote | Type & Test |
| ----------:| ------ |:----------- |
| 1 | No | HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses |
| 2 | Yes | HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed |
| 5 | Yes | HttpClientHandlerTest.GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock |
| 6 | Yes | ManagedHandler_HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed |
| 7 | Yes | ManagedHandler_HttpClientHandlerTest.GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock |

The 1st failure is not related at all to remote servers, but likely to non-determinism in `LoopbackServer`. When concurrent tests are allowed we hit many more failures related to LoopbackServer non-determinism (notice that these can be real bugs but we need to make the tests behavior deterministic, the non-determinism is coming basically from when the server closes the connection).

The remaining failures are related to two tests `GetAsync_MaxLimited_ConcurrentCallsStillSucceed` and `GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock` since there are many more tests accessing remote servers I suspect that there is something particular about these tests.

Notice that for these two tests the managed handler had basically twice as many failures, the numbers are too small to conclude that this is something inherent to the managed handler but we should keep an eye on those.

I will do a series of steps to make the tests more deterministic after that I will get back to run the tests concurrently and try to identify the root cause of deadlock on my machine,

**Comment by rmkerr** [comment] 2018-01-24 18:05
I think the root cause here must be different from #26092, since that issue does not occur with ```-parallel none``` set.

**Comment by rmkerr** [comment] 2018-03-29 17:51
Based off of these two lines it seems like we're sending 22 megabytes of content along with this POST. 
https://github.com/dotnet/corefx/blob/50d4e1ce620f26ec4aebe26c121a769fc8e724ab/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L2426-L2427
Do you think that's enough that we would plausibly be hitting the 90 second timeout?

**Comment by pjanotti** [comment] 2018-03-29 18:48
I don't think so: the server is just echoing it back and we had issues with echoing in the WCF stress tests (which was fixed since we disabled this test). That said there were some differences: it repro-ed consistently for WCF but we just got intermittent hits for this one (always in CI). If I don't get a repro in some attempts from the PR and my local tries I think we should try to re-enable it and see the results.

**Comment by pjanotti** [comment] 2018-03-29 19:11
The first issue found in the WCF stress tests was a bug in handling the response when the server was echoing back a stream, which is basically the same thing done in this test. The issue that fixed the handling of the echo response was PR #27341, at this point I am not 100% sure that this is the same issue but it seems likely.

**Comment by karelz** [comment] 2018-03-29 19:18
If you think there is decent chance that it may have been addressed, then we should re-enable the test. Or do you have other suggestion how to verify it is addressed?

**Comment by pjanotti** [comment] 2018-03-30 22:35
No repros in 500 local runs on Windows and Ubuntu 16.04, nor on the 4 attempts on a PR trying to get a repro. I will give more tries in the PR but this should be safe to move to future.

**Comment by karelz** [comment] 2018-03-30 22:44
We should try to re-enable the test then. Let's do it after integration into release/2.1 just in case (we do not want to disrupt the test results) - marking as Post-ZBB

**Comment by karelz** [comment] 2018-04-02 19:23
Thanks @pjanotti! Can you please re-enable the test in that case, then close this bug? Thanks!

**Closed** 2018-04-04 23:54 UTC
Labels: Post-ZBB, area-System.Net.Http, disabled-test, test bug, test-run-core

**Comment by karelz** [comment] 2018-04-05 00:01
Thank you @pjanotti!
