### ISSUE TITLE
Canceling Http task may result in faulted task instead of canceled\completed

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#16248] opened 2017-02-17 01:11 UTC
See related issue https://github.com/dotnet/corefx/issues/13938

In Windows, when a response task is canceled, the request handle is destroyed, which may cause an ObjectDisposedException (or other http exception) in other tasks. The expectation should be the same as in Linux - a task status of Canceled, or perhaps RanToCompletion if the task already completed

For example, the last Assert below may fail randomly (especially consistent in Windows 2008r2) because task.Status will be Faulted.

````
    var cts = new CancellationTokenSource();
    using (var client = new HttpClient())
    using (HttpResponseMessage response = await client.GetAsync(Configuration.Http.RemoteEchoServer, HttpCompletionOption.ResponseHeadersRead))
    using (Stream stream = await response.Content.ReadAsStreamAsync())
    {
        var buffer = new byte[2048];
        Task task = stream.ReadAsync(buffer, 0, buffer.Length, cts.Token);
        cts.Cancel();
        Assert.True(((IAsyncResult)task).AsyncWaitHandle.WaitOne(new TimeSpan(0, 5, 0)));
        Assert.True(task.Status == TaskStatus.RanToCompletion || task.Status == TaskStatus.Canceled);
     }
````

We need to decide if we should harden the code to check the cancellationtoken and\or invalid handle in the various windows-only Http code such as in WinHttpResonseStream and avoid a random ObjectDisposedException, task canceled exception or other http exception depending on timing. Avoiding a race condition in this check may or may not be feasible (as handle or cancellationtoken may change to invalid\cancel in other thread) so consider try\catch of certain exceptions instead and then verify handle and\or cancellationtoken.

cc @stephentoub @CIPop @davidsh

**Comment by Jiayili1** [comment] 2017-02-17 07:38
Test "System.Net.Http.Functional.Tests.ResponseStreamTest.ReadAsStreamAsync_Cancel_TaskIsCanceled" failed with "System.ObjectDisposedException : Safe handle has been closed".

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/99/testReport/System.Net.Http.Functional.Tests/ResponseStreamTest/ReadAsStreamAsync_Cancel_TaskIsCanceled/

Message:
~~~
System.ObjectDisposedException : Safe handle has been closed
~~~

Stack Trace:
~~~
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) at Interop.WinHttp.WinHttpReadData(SafeWinHttpHandle requestHandle, IntPtr buffer, UInt32 bufferSize, IntPtr parameterIgnoredAndShouldBeNullForAsync) at System.Net.Http.WinHttpResponseStream.<ReadAsyncCore>d__22.MoveNext() in D:\j\workspace\outerloop_win---75d58f69\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpResponseStream.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.ResponseStreamTest.<ReadAsStreamAsync_Cancel_TaskIsCanceled>d__5.MoveNext() in D:\j\workspace\outerloop_win---75d58f69\src\System.Net.Http\tests\FunctionalTests\ResponseStreamTest.cs:line 114 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

So added "blocking-clean-ci" label.

**Comment by steveharter** [comment] 2017-02-17 17:30
@Jiayili1 that failure was before the changes made in pull https://github.com/dotnet/corefx/issues/16248, so remove the blocking label and deleting the comment.

**Comment by davidsh** [comment] 2017-02-21 17:24
See #9228.

**Comment by davidsh** [comment] 2017-02-26 19:45
Dupe of #9228.

**Closed by davidsh** 2017-02-26 19:45 UTC
Labels: area-System.Net.Http, bug
