### ISSUE TITLE
String should implement IReadOnlyList<char>

### ISSUE THREAD

**Issue by dpugh** [dotnet/corefx#16786] opened 2017-03-06 20:20 UTC
The .Net String class does not implement any API that provides allows random access without also implying that the characters are all in contiguous memory. There are many string-like data structures, however, that give random access to immutable sequences of characters without the characters being in contiguous memory.

**Rational and usage:**
As things stand, the API & implementation for the VS TextBuffer is complicated because we need two versions of several methods: one that takes a string and one that takes our piece table. Having string implement `IReadOnlyList<char>` would eliminate the need to duplicate the methods (and the while overhead of calling the character indexer via a virtual method is annoying it isn't critical in most of our scenarios since users rarely paste in megabytes of text).

**Proposed change:**
Change the signature of String from this:
``` c#
    public sealed class String : IComparable, ICloneable, IConvertible, IComparable<String>,
                                               IEnumerable<char>, IEnumerable, IEquatable<String>
```
to this:
``` c#
    public sealed class String : IComparable, ICloneable, IConvertible, IComparable<String>,
                                               IEnumerable<char>, IEnumerable, IEquatable<String>,
                                               IReadOnlyList<char>
```
And add an implementation for `int IReadOnlyList<char>.Count {get;}.`

A more challenging request would be to have string implement something slightly more robust than `IReadOnlyList<char>` which would provide some useful methods that avoid some of the performance issues (specifically, allowing a Substring-like capability and a copy ability that wouldn't have the overhead of going through the character indexer for each character).
``` c#
    public interface ISubsetableReadOnlyList<T> : IReadOnlyList<T>
    {
        ISubsetableReadOnlyList<T> Slice(int start, int length);
        public void CopyTo(int sourceIndex, T[] destination, int destinationIndex, int count);
    }
```

It would also be convenient of ReadOnlySpan<T> also implemented IReadOnlyChar<T> (or ISubsettableReadOnlyList<char>) so it could be used in scenarios where the consumer doesn't require the elements to be in contiguous memory.

**Comment by mellinoe** [comment] 2017-03-06 20:22
Related discussions:

https://github.com/dotnet/corefx/issues/14336
https://github.com/dotnet/corefx/issues/14572

**Comment by karelz** [comment] 2017-03-06 22:37
Dupe of #14336.

**Closed by karelz** 2017-03-06 22:37 UTC
Labels: area-System.Runtime
