### ISSUE TITLE
WebProxy_BypassOnLocal_MatchesExpected fails in Linux CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#23231] opened 2017-08-14 22:13 UTC
https://mc.dot.net/#/user/ericstj/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/58821d965b53932b09804845d6d0f752aff9c28d/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FWebProxy_BypassOnLocal_MatchesExpected

Appears to be transient issue.  Test leg was Ubuntu.1604.Amd64.Open-Release-x64.

```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
Stack Trace :
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 46
   at System.Net.Dns.ResolveCallback(Object context) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 290
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 420
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 562
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Tests.WebProxyTest.<BypassOnLocal_MemberData>d__10.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Linq/src/System/Linq/Select.cs:line 129
```

**Comment by Jiayili1** [comment] 2017-08-16 07:24
This issue is repro in Core Tests (Master), detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170816.01/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FWebProxy_BypassOnLocal_MatchesExpected

**Comment by Jiayili1** [comment] 2017-08-21 06:58
This issue is repro in Master branch, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170821.01/workItem/System.Net.WebProxy.Tests/analysis/xunit/System.Net.Tests.WebProxyTest~2FWebProxy_BypassOnLocal_MatchesExpected

**Comment by karelz** [comment] 2017-12-24 09:35
Duplicate of #23766

**Closed by karelz** 2017-12-24 09:35 UTC
Labels: area-System.Net, os-linux, test-run-core
