### ISSUE TITLE
IDbDataParameter.Precision is broken for SqlClient 4.3.0

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#23899] opened 2017-09-08 23:27 UTC
The implementations of IDbParameter.Precision and IDBParameter.Scale in System.Data.Common.DbParameter got replaced with dummy implementations by commit  7888677b3c53596085c2fa53860d9a0519eeecfd.

This demo application reproduces the problem in .NET Core 2.0 but works just fine in .NET Core 1.1. Expected output: 19; got 0.
[Program.zip](https://github.com/dotnet/corefx/files/1289338/Program.zip)

**Comment by danmosemsft** [comment] 2017-09-08 23:39
Ack. That does seem apparently wrong -- although the change was to match Desktop, the code suggests it's a bug: https://referencesource.microsoft.com/#System.Data/System/Data/Common/DBParameter.cs,68

@corivera do you see any reason why these two shouldn't match the implicit implementations just below them?

**Comment by danmosemsft** [comment] 2017-09-08 23:40
@jhudsoncedaron given this is the same in desktop, is this a real scenario or you just noticed?

**Comment by jhudsoncedaron** [comment] 2017-09-08 23:44
Real scenario; it broke on upgrade to .NET Core 2.0. I just spent three hours determining the issue wasn't in my code.

I don't care what desktop does; desktop has bugs in the specification as soon as you step off Windows.

**Comment by jhudsoncedaron** [comment] 2017-09-08 23:46
The real code has a db-agnostic connection stored in a variable of type IDbConnection(), calls IDbConnection.CreateCommand() on that to get a command, calls IDbCommand.CreateParameter() on that to get a parameter, sets up the parameter type, name, precision, and scale, and calls IDbCommand.Prepare() which now goes kaboom.

**Comment by danmosemsft** [comment] 2017-09-09 00:00
Would you be interested in throwing up a PR @jhudsoncedaron ? If area owner @corivera agrees, it could potentially get into 2.0.2 servicing if we are quick.

**Comment by corivera** [comment] 2017-09-09 00:31
@jhudsoncedaron Your repro actually works fine in master. I'm checking to see if there's a fix that needs to be backported to 2.0.2

**Comment by jhudsoncedaron** [comment] 2017-09-09 00:37
Given the bug still exists in master; I'd suggest that editing the referenced version of System.Data.SqlClient might cause the bug to reappear. I don't know how it's picking up the new version with the old version number but it certainly is here.

**Comment by corivera** [comment] 2017-09-09 01:08
This problem also doesn't repro in release/2.0.0 or in .NET Framework.

**Comment by jhudsoncedaron** [comment] 2017-09-09 01:16
C:\Users\jhudson\dev\scratch\precision>dotnet --version
2.0.0

C:\Users\jhudson\dev\scratch\precision>dotnet run
0

C:\Users\jhudson\dev\scratch\precision>

**Comment by jhudsoncedaron** [comment] 2017-09-09 01:44
[Program (2).zip](https://github.com/dotnet/corefx/files/1289463/Program.2.zip)

So I tried to figure out why editing the framework version is the controlling variable. Something about the default template is causing it to haul in newer versions of dlls than I asked for. I haven't a clue why.

1.0:
C:\Users\jhudson\dev\scratch\precision>dotnet run
19
System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

1.1:
C:\Users\jhudson\dev\scratch\precision>dotnet run
19
System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

2.0:
C:\Users\jhudson\dev\scratch\precision>dotnet run
0
System.Data.Common, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

I have no idea why it does that; but it certainly explains the variance in behavior.

**Comment by danmosemsft** [comment] 2017-09-09 04:16
@jhudsoncedaron I am not a packaging expert, but S.D.Common is part of .NET Core (part of its shared framework) so it would be expected if you change the target framework that it pulls the 2.0 version.

**Comment by jhudsoncedaron** [comment] 2017-09-09 05:04
@danmosemsft : I wouldn't expect it to change over an explicit order in the .csproj file though. I'd much rather use the old one as it doesn't have have DataSet or DataTable in it.

**Comment by jhudsoncedaron** [comment] 2017-09-09 05:25
@corivera : I'm certain the reason you can't reproduce is you aren't using my project file. The code in DbParameter is wrong and forces every derived class to re-implement IDbDataParameter, which defeats the purpose of having the DbParameter class in the first place. The project file is specifying an old System.Data.Common and an old System.Data.SqlClient; but something that should not be is force-upgrading System.Data.Common but not System.Data.SqlClient.

**Comment by danmosemsft** [comment] 2017-09-09 06:33
@weshaggard would you expect an explicit reference to the 4.1.0 (the 1.1 version) of S.D.Common to be respected, if TF is netcoreapp2.0 ? It does not surprise me that we force everything to the netcoreapp2.0 supported combination
```xml
  <TargetFramework>netcoreapp2.0</TargetFramework>
    <WarningsAsErrors></WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.Common" Version="4.1.0"></PackageReference>
```

**Comment by weshaggard** [comment] 2017-09-11 17:15
No. We always prefer the newer version of the library and we include the newer version of System.Data.Common in .NET Core 2.0 shared framework so that will be preferred over a Package reference to the older version.

**Comment by corivera** [comment] 2017-09-12 18:18
I won't be able to fix this issue in this round of servicing, due to some other issues popping up. However, I found that targeting System.Data.SqlClient 4.4.0 or Microsoft.NETCore.App (where the latest System.Data.Common gets packaged now) resolves this issue.

**Comment by danmosemsft** [comment] 2017-10-05 20:00
Moving to 2.x. If this is larger impact we can consider servicing.

**Comment by saurabh500** [comment] 2017-10-11 19:36
In my opinion, there should be no behavior change in S.D.Common.
The reason the provider is expected to implement interfaces directly is because interfaces came before base classes in the history of ADO.Net (Desktop) and all providers had implemented these interfaces. When the base classes were created, the behavior was kept such that the Interface behavior is not broken. 
With the change in .Net Core 2.0 to be compatible with .Net Framework, the existing code makes sense because it keeps the providers working the same way as they used to, on Desktop.

**Comment by jhudsoncedaron** [comment] 2017-10-11 19:56
@saurabh500 : Try inheriting from the base class System.Data.Common.DbParameter and overriding  Precision and trying to call it via the interface IDbParameter. Your code won't work either. That's the actual bug.

**Comment by divega** [comment] 2018-03-23 20:38
@jhudsoncedaron If we changed the implementation of IDbParameter.Precision and IDbParameter.Scale to preserve the value passed as you ask that would make this simple test pass:

``` C#
IDbCommand cmd = new SqlCommand();
var parameter = cmd.CreateParameter();
parameter.DbType = DbType.String;
parameter.Precision = 19;
Assert.AreEqual(parameter.Precision, 19);
```
But SqlClient 4.3.0 would still have a bug because it would not use the new stored value. The [implementation](https://github.com/dotnet/corefx/blob/de7ae0edd4ad53a1142f2cf9fdfa944bca7dbc8c/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameter.cs#L532) uses its own storage as you can see:

``` C#
        public override Byte Precision
        {
            get
            {
                return PrecisionInternal;
            }
            set
            {
                PrecisionInternal = value;
            }
        }
```

So the values stored in the interface property would be ignored.

Given this I would encourage you to just update to a newer version of SqlClient that contains [this bug fix](https://github.com/dotnet/corefx/commit/2cc6211699ef5e6e414d09fb7cd13b6e675fffcf#diff-cc02fe5238df67f66dcb2756cb68ff96), e.g. 4.4.0.

All that said, I believe however that changing the default implementation for the interface property to preserve the value could be a reasonable thing to do from the perspective that then future providers would never need to re-implement the interface anymore and could use the values stored through the members of the base class.

Just to expand on @saurabh500 comment and provider a little more information about the history of how this came to be the way it is:

- When `DbParameter` was introduced in .NET Framework, it didn't have Precision and Scale at all. If you need to set/get the values in a provider agnostic way, you had to use the interface `IDbParameter` and hence provider were required to implement the interface in their `XyzParameter` objects.

- When we did the initial System.Data.Common unification work (pre .NET Core v1, around .NET Framework 4.5.1) we were going for the minimal required API and the plan was that System.Data.Common would never have the interfaces, but only the base classes under System.Data.Common.

- We needed a provider-agnostic way to access precision and scale without the interface, so we introduced Precision and Scale on the base class.

- We had to do this in a backwards and forwards compatible way:
   - "Old-style" providers didn't know about the members of the base class but always implemented the members on the interface, so we had the default implementation of the class members delegate to the interface members. Since "old-style" providers implemented the interface, so it didn't matter too much what the implementation of the interface members in the base class was. However, keep in mind that Precision and Scale are concepts that don't apply to some parameter types (in the general case, an unknown set of types that depends on the specific provider), so I believe it was by design (as opposed to just dummy) that by default they return 0 and ignore the value set.

   - "New-style" provider for what ended up being .NET Core 1.0 were expected to just derive from the base class (remember that on .NET Core the interface doesn't exist). The default implementation of DbParameter.Scale and DbParameter.Precision on System.Data.Common for .NET core 1.0, also discarded the values set and always returned 0, by design.  

   - Providers that needed to operate in both .NET Framework and .NET Core would need to cross-compile, so that they could implement the interface in .NET Framework and avoid mentioning the interface in .NET Core. 

- .NET Core 2.0 changed the goals from having a minimal API to have greater compatibility. When https://github.com/dotnet/corefx/commit/7888677b3c53596085c2fa53860d9a0519eeecfd was committed, this brought back not only the interface but also the requirement that providers implement the interface. Unfortunately, SqlClient 4.3.0 didn't have this.

**Comment by jhudsoncedaron** [comment] 2018-03-23 20:48
@divega : I think you didn't check what my patch actually does. It just changes it so the implementation of IDBDataParameter calls the virtual method so that override in the derived class picks up either call.

**Comment by divega** [comment] 2018-03-23 20:48
@ajcvickers @roji @bricelam @bgrainger @cincuranet this seems to be a subtle issues that could affect any provider that was written for .NET Core 1 (with the notable exception of Microsoft.Data.Sqlite which ignores Precision and Scale anyway :smile:). Probably worth having a "spec test" for this.

**Comment by divega** [comment] 2018-03-23 20:49
@jhudsoncedaron I missed that you have submitted a patch. Can you pleas point me to it?

**Comment by jhudsoncedaron** [comment] 2018-03-23 20:51
(scrolls up)
https://github.com/joshudson/corefx/commit/d3599fcc23be92987b2374c29a24187ed025db42
https://github.com/dotnet/corefx/pull/23902

**Comment by divega** [comment] 2018-03-23 21:14
@jhudsoncedaron it would be really nice if we could simplify things like this. Unfortunately that would break the existing providers that like SqlClient [don't override the properties from the base class but instead re-implement the interface](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameter.cs#L547): If you use the base class to set precision or scale in a provider-agnostic way, then you are no longer invoking the actual implementation in the provider.

E.g. try this:

``` C#
using System;
using System.Data;

namespace ConsoleApp18
{
    class Program
    {
        static void Main(string[] args)
        {
            FakeDbParameter parameter = new FakeSqlParameter();
            parameter.Precision = 19;
            Console.WriteLine(parameter.Precision);
        }
    }

    public class FakeDbParameter: IDbDataParameter
    {
        public DbType DbType { get; set; }
        public ParameterDirection Direction { get; set; }
        public bool IsNullable { get; }
        public string ParameterName { get; set; }
        public string SourceColumn { get; set; }
        public DataRowVersion SourceVersion { get; set; }
        public object Value { get; set; }
        public int Size { get; set; }
        public virtual byte Precision
        {
            get { return 0; }

            set { }
        }
       
        public virtual byte Scale
        {
            get { return 0; }

            set { }
        }
    }

    public class FakeSqlParameter: FakeDbParameter, IDbDataParameter
    {
        public new byte Precision { get; set; }
        public new byte Scale { get; set; }
    }
}

```

**Comment by divega** [comment] 2018-03-23 21:30
@jhudsoncedaron That wouldn't work because you are not going to be able to change all existing providers. I disagree that there is a defect here. The defect was in SqlClient 4.3.0, because it had not transitioned to the correct pattern, and I would like to understand why can you just move to 4.4.0.

**Comment by jhudsoncedaron** [comment] 2018-03-23 21:52
No matter how many times I rewrite this it still comes out sounding rude. Boo.

Having to re-impalement the interface in the derived class defeats the purpose of having the base class. That's the defect I'm trying to get rid of and you already acknowledged it. I am quite capable of searching this tree and fixing all the providers within. As for providers not in this tree, some of them will be broken no matter what you do now.

But I have a bug outstanding far worse than this defect here that requires a 2 line workaround. I'm probably going to have to fork the dotnet codebase over the other one. (I can fix it only under the limiting case of my caller follows thread-safety rules as it involves DangerousGetHandle() so I can't put in a PR for that one.)

**Comment by divega** [comment] 2018-03-23 21:58
@jhudsoncedaron I don't disagree that making this simple would have been nice. We wanted to do it in .NET Core 1.0 and we did. But compatibility comes with a baggage of complexity.

**Comment by divega** [comment] 2018-03-23 23:18
I noticed the issue @bgrainger filed. @roji, at first glance your provider has the same issue, correct?

Since the correct pattern is hard to enforce without common tests, we may have ended with .NET Core providers that were built for 1.0 and don’t work correctly in 2.0. We should consider our options.

**Comment by roji** [comment] 2018-03-27 21:28
As mentioned above the issue exists for Npgsql and is tracked in https://github.com/npgsql/npgsql/issues/1867.

FWIW having the provider-specific parameter class extend IDbDataParameter as a fix isn't pretty but seems OK to me: we know that ADO.NET isn't ideal in that it has this kind of baggage, but there's no actual visible downside to this fix AFAIK.

**Comment by divega** [comment] 2018-03-28 02:25
We discussed this also with @ajcvickers and we agreed we will have to live with this pattern now: the provider-specific parameter object needs to implement the interface and hide the methods in the base class.

This would be a good thing for a suite of “ADO.NET spec tests” to check for. Although we don’t have such thing here, @bgrainger has been putting together one that looks promising so I filed https://github.com/mysql-net/AdoNetApiTest/issues/6.

**Closed by divega** 2018-03-28 02:25 UTC
Labels: area-System.Data
