### ISSUE TITLE
Package descriptions are badly formatted and have -1548494 at the end of it

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#4742] opened 2015-12-01 00:32 UTC
The commonly used types section has extra line between the types which looks weird, and the latest version of every package has a -1548494 at the end of the description for some reason:

![image](https://cloud.githubusercontent.com/assets/1103906/11488962/ccefac16-977f-11e5-82c3-f48a22c0304c.png)

**Comment by stephentoub** [comment] 2015-12-01 00:35
cc: @ericstj, @chcosta

**Comment by ellismg** [comment] 2015-12-01 00:41
FWIW, that number is the TFS Changeset ID of the build.  The long term plan is to include the relevant git hashes as well (I think we already do this for builds published on myget).

**Comment by chcosta** [comment] 2015-12-01 00:45
Yes, what ellismg says is correct.  The formatting could be improved though.  Being more verbose about the "- 1548494" may improve readability as well.

**Comment by davkean** [comment] 2015-12-01 00:52
How is the tfs changset meaningful to me?

Sent from my Windows Phone
________________________________

**Comment by davkean** [comment] 2015-12-01 04:44
ie I understand why TFS changeset is useful to MS, but why to external developers in the package description? 

(I get why the commit hash is useful - assuming it's a public hash from http://github/dotnet/corefx)

**Comment by chcosta** [comment] 2015-12-03 22:09
Is this information causing a headache?  The problem is that there is no good place in the nuspec to include this information.  Yes, this is not useful to external developers, but it does provide use to MS internal developers.  The other option was to include this in metadata in the package itself, but we didn't want to invest a lot in temporary work.  The issue is point-in-time as we are moving packaging into the open and this information will not be included for those packages.

**Comment by davkean** [comment] 2015-12-03 22:12
Right now it looks unprofessional, will this be fixed before you RTM these packages?

**Comment by chcosta** [comment] 2016-03-23 23:03
This should be fixed with https://github.com/dotnet/buildtools/commit/0ec4a20c43f00eed59ac818260102af0fd8dd367

**Closed by chcosta** 2016-03-23 23:03 UTC
Labels: bug, packaging
