### ISSUE TITLE
Unused code, incompatible with Roslyn > 2.0.0 rc

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#20942] opened 2017-06-12 20:27 UTC
Roslyn made a breaking change sometime between rc and beta2, which flags unused fields(https://github.com/dotnet/roslyn/pull/14628/files) and events as warnings.  

CoreFx will be unable to update to a newer version of Roslyn until these warnings are fixed / suppressed.

```
System.Diagnostics.Tracing.cs(120,64): error CS0067: The event 'EventListener.EventSourceCreated' is never used [E:\gh\chcosta\corefx\src\System.Diagnostics.Tracing\ref\System.Diagnostics.Tracing.csproj]
System.Diagnostics.Tracing.cs(121,58): error CS0067: The event 'EventListener.EventWritten' is never used [E:\gh\chcosta\corefx\src\System.Diagnostics.Tracing\ref\System.Diagnostics.Tracing.csproj]
System.Runtime.Loader.cs(35,108): error CS0067: The event 'AssemblyLoadContext.Resolving' is never used [E:\gh\chcosta\corefx\src\System.Runtime.Loader\ref\System.Runtime.Loader.csproj]
System.Runtime.Loader.cs(36,50): error CS0067: The event 'AssemblyLoadContext.Unloading' is never used [E:\gh\chcosta\corefx\src\System.Runtime.Loader\ref\System.Runtime.Loader.csproj]

 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(111,24): error CS0169: The field 'XmlSerializationReader._positiveIntegerID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(33,27): error CS0169: The field 'XmlSerializationReader._types' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(34,27): error CS0169: The field 'XmlSerializationReader._typesReverse' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(79,24): error CS0169: The field 'XmlSerializationReader._base64ID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(42,22): error CS0169: The field 'XmlSerializationReader._isReturnValue' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(37,27): error CS0169: The field 'XmlSerializationReader._referencedTargets' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(93,24): error CS0169: The field 'XmlSerializationReader._gMonthID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(92,24): error CS0169: The field 'XmlSerializationReader._gDayID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(84,24): error CS0169: The field 'XmlSerializationReader._unsignedLongID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(116,24): error CS0169: The field 'XmlSerializationReader._timeSpanID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(103,24): error CS0169: The field 'XmlSerializationReader._NCNameID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(82,24): error CS0169: The field 'XmlSerializationReader._unsignedShortID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(90,24): error CS0169: The field 'XmlSerializationReader._ENTITYID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(95,24): error CS0169: The field 'XmlSerializationReader._gYearID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(76,24): error CS0169: The field 'XmlSerializationReader._timeID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(74,24): error CS0169: The field 'XmlSerializationReader._qnameID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(105,24): error CS0169: The field 'XmlSerializationReader._NMTOKENSID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(85,24): error CS0169: The field 'XmlSerializationReader._oldDecimalID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(118,29): error CS0649: Field 'XmlSerializationReader.s_checkDeserializeAdvances' is never assigned to, and will always have its default value false [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(80,24): error CS0169: The field 'XmlSerializationReader._unsignedByteID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(97,24): error CS0169: The field 'XmlSerializationReader._IDID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(32,27): error CS0169: The field 'XmlSerializationReader._callbacks' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(100,24): error CS0169: The field 'XmlSerializationReader._integerID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(73,24): error CS0169: The field 'XmlSerializationReader._dateTimeID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(104,24): error CS0169: The field 'XmlSerializationReader._NMTOKENID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(40,27): error CS0169: The field 'XmlSerializationReader._collectionFixups' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(108,24): error CS0169: The field 'XmlSerializationReader._nonNegativeIntegerID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(68,24): error CS0169: The field 'XmlSerializationReader._shortID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(38,27): error CS0169: The field 'XmlSerializationReader._targetsWithoutIds' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(96,24): error CS0169: The field 'XmlSerializationReader._gYearMonthID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(94,24): error CS0169: The field 'XmlSerializationReader._gMonthDayID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(107,24): error CS0169: The field 'XmlSerializationReader._nonPositiveIntegerID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(70,24): error CS0169: The field 'XmlSerializationReader._floatID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(102,24): error CS0169: The field 'XmlSerializationReader._nameID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(88,24): error CS0169: The field 'XmlSerializationReader._anyURIID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(109,24): error CS0169: The field 'XmlSerializationReader._normalizedStringID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(86,24): error CS0169: The field 'XmlSerializationReader._oldTimeInstantID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(106,24): error CS0169: The field 'XmlSerializationReader._negativeIntegerID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(75,24): error CS0169: The field 'XmlSerializationReader._dateID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(112,24): error CS0169: The field 'XmlSerializationReader._tokenID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(65,24): error CS0169: The field 'XmlSerializationReader._stringID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(114,24): error CS0169: The field 'XmlSerializationReader._charID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(36,27): error CS0169: The field 'XmlSerializationReader._targets' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(91,24): error CS0169: The field 'XmlSerializationReader._ENTITIESID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(98,24): error CS0169: The field 'XmlSerializationReader._IDREFID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(81,24): error CS0169: The field 'XmlSerializationReader._byteID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(78,24): error CS0169: The field 'XmlSerializationReader._base64BinaryID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(71,24): error CS0169: The field 'XmlSerializationReader._doubleID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(67,24): error CS0169: The field 'XmlSerializationReader._booleanID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(110,24): error CS0169: The field 'XmlSerializationReader._NOTATIONID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(115,24): error CS0169: The field 'XmlSerializationReader._guidID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(66,24): error CS0169: The field 'XmlSerializationReader._intID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(99,24): error CS0169: The field 'XmlSerializationReader._IDREFSID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(83,24): error CS0169: The field 'XmlSerializationReader._unsignedIntID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(89,24): error CS0169: The field 'XmlSerializationReader._durationID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(39,27): error CS0169: The field 'XmlSerializationReader._fixups' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(101,24): error CS0169: The field 'XmlSerializationReader._languageID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(69,24): error CS0169: The field 'XmlSerializationReader._longID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(72,24): error CS0169: The field 'XmlSerializationReader._decimalID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(77,24): error CS0169: The field 'XmlSerializationReader._hexBinaryID' is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(43,22): error CS0414: The field 'XmlSerializationReader._decodeName' is assigned but its value is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
 179:2>E:\gh\chcosta\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializationReader.cs(31,29): error CS0414: The field 'XmlSerializationReader._d' is assigned but its value is never used [E:\gh\chcosta\corefx\src\Microsoft.XmlSerializer.Generator\src\Microsoft.XmlSerializer.Generator.csproj]
```

/cc @weshaggard @ellismg

**Comment by weshaggard** [comment] 2017-06-12 20:30
Why can't we add this to the nowarn list?

**Comment by chcosta** [comment] 2017-06-12 20:34
That's a viable option (suppress).  I'm going through the repo's now to see if there are any crazy issues building on desktop / Linux with upgrading to the newer Roslyn.  I wanted to track these as I go so that when I actually get buildtools updated and then go through and update each of the repo's, i'm not investigating again (or perhaps somebody has already fixed these, but probably not).

**Comment by danmosemsft** [comment] 2017-06-15 22:33
I'm going to move to Future because we don't need to do this for 2.0 - you can baseline as mentioned.

**Comment by jaredpar** [comment] 2017-06-16 23:54
When you see breaks like this with new compiler versions please do alert the compiler team directly about it. Compat is super important to us and we want to make sure we know about any unexpected breaks.

**Comment by weshaggard** [comment] 2017-06-16 23:57
@jaredpar Consider yourself notified :) What is the right path for these? Should we add to NoWarn list or try to fix all the instances?

**Comment by jaredpar** [comment] 2017-06-17 00:01
@weshaggard 

Still trying to understand why warnings are being generated here. Lets take a look at the first few warnings:

``` txt
System.Diagnostics.Tracing.cs(120,64): error CS0067: The event 'EventListener.EventSourceCreated' is never used [E:\gh\chcosta\corefx\src\System.Diagnostics.Tracing\ref\System.Diagnostics.Tracing.csproj]
System.Diagnostics.Tracing.cs(121,58): error CS0067: The event 'EventListener.EventWritten' is never used [E:\gh\chcosta\corefx\src\System.Diagnostics.Tracing\ref\System.Diagnostics.Tracing.csproj]
```

That seems to map to the following code in [System.Diagnostics.Tracing.cs](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs):

```
    public abstract partial class EventListener : System.IDisposable
    {
#if FEATURE_ETLEVENTS
        public event EventHandler<EventSourceCreatedEventArgs> EventSourceCreated;
        public event EventHandler<EventWrittenEventArgs> EventWritten;
#endif
```

These are public members in a public type. Unlikely we are actually warning on these as written. Otherwise pretty much no project out there would build (including ourselves).

**Comment by danmosemsft** [comment] 2017-08-21 22:00
@joperezr are you hitting these? you didn't mention you were -- in which case I guess we can close this?

**Comment by joperezr** [comment] 2017-08-24 17:57
Yes, I hit all of those and had to #pragma disable them.

**Comment by weshaggard** [comment] 2017-08-25 16:07
cc @ericstj

**Comment by ericstj** [comment] 2017-08-25 16:31
I looked into this, and I think the warnings are legit.  Yes those are public events, but the public exposure is add/remove.  The class itself is the only thing that can call them.

I hit this same set of warnings when picking up an updated buildtools which had the CSC update.

See https://github.com/dotnet/corefx/pull/23513.

**Comment by jaredpar** [comment] 2017-08-25 19:36
CC @OmarTawfik 

Gotcha. That makes sense. We did fix a bug recently around unused members and accessibility. But it was just restoring an error we accidentally regressed. Based on the error message and source code of corefx it looked like the event was public in a public type. That should never warn.

**Comment by ericstj** [comment] 2017-08-25 19:54
It is public in a public type.  You can reproduce the warning with this code snippet:
```C#
    public class Foo
    {
        public event Action<int> Event;
    }
```
Building with the 2.0 SDK results in the warning `warning CS0067: The event 'Foo.Event' is never used`

Also, I've hit some more alarming failures with this new build.

The following syntax used to work, but now results in an error:
```C#
    public class Test
    {
      [Theory
        InlineData(1)
        InlineData(2)]
      public void TestMethod(int foo)
      {
      }
    }
```
Build produces
```
error CS1003: Syntax error, ',' expected
error CS1003: Syntax error, ',' expected
```

**Comment by jaredpar** [comment] 2017-08-25 19:57
The errors on the attributes are expected. There was a bug in C# 6.0 where we didn't force commas between attributes. The restriction was added back in C# 7.0.

**Comment by ericstj** [comment] 2017-08-28 17:39
I think we can close this as a result of https://github.com/dotnet/corefx/pull/23559 and https://github.com/dotnet/corefx/pull/23610.

**Closed** 2018-12-11 00:51 UTC
Labels: area-Infrastructure, bug
