### ISSUE TITLE
Using locally build mscorlib in test project bin makes CoreRun.exe crash

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#8381] opened 2016-05-08 07:39 UTC
Some libraries (for some reason still unknown to me) are contained in mscorlib, such as System.Text.Encoding, System.Runtime etc.
I wanted to run a coverage report for these projects, so @stephentoub suggested the following.

> 1. Do a normal code coverage run for System.Runtime. This will populate a folder corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Runtime.Tests\dnxcore50 will lots of stuff and also spit out to the console the commands that were used to invoke OpenCover and ReportGenerator. The actual code coverage report generated doesn't matter.
2. Build coreclr locally in debug.
3. Copy the debug binaries (e.g. mscorlib.dll, coreclr.dll, mscorlib.pdb, etc.) from the coreclr build to that dnxcore50 folder, overwriting files already there.
4. Delete the mscorlib.ni.dll file from that dnxcore50 folder.
5. In that dnxcore50 folder, run the OpenCover command, then run the ReportGenerator command.

I've produced an automated bash script to do this ([here](https://gist.github.com/hughbe/511331a3d264d48b390d1803475a91cf)), but thats not really too important.

Basically, my issue is whenever I run **any other test project** or the current test project with `msbuild /T:BuildAndTest`, I get an error code
![log](https://cloud.githubusercontent.com/assets/1275900/15096598/527e6f16-14f8-11e6-8b04-9da753529823.png)

Apparently, the error code means, but I'm not sure this is correct
> Error code 0x80004005
> This problem may occur if a file that the Windows Product Activation (WPA) requires is damaged or missing. This behavior occurs if one or both of the following conditions are true:
A third-party backup utility or an antivirus program interferes with the installation of Windows XP.
A file that WPA requires is manually modified.

### Solution
This can be fixed by deleting the packages and bin folder and running the command again, however obviously this takes time and effort and means I have to go through the original process to get an updated coverage report.

**Comment by ellismg** [comment] 2016-05-08 19:30
> Some libraries (for some reason still unknown to me) are contained in mscorlib, such as System.Text.Encoding, System.Runtime etc.

In a perfect world, the implementation factoring would match 1:1 with the contract factoring.  In that world, mscorlib.dll would not exist at all.  The CoreRT get's closer to this idealized world, since we started that project after coming up with the contract factoring, but mscorlib.dll grew up in a world where we didn't have such factoring.  Because of this, there are both implementation dependencies within the assembly itself (e.g. you have string which has methods which depends on stuff from globalization) and places where we have to be careful about pulling stuff up and out of mscorlib, because if mscorlib indirectly exposes a type (say via the concrete implementation of an interface, and we return that interface from a method) and if someone downcasts that type it needs to match the type identity of the actual type we exposed from the higher level assembly.

Regarding this specific error, I'm going to dig in.  I have suspicions about what could be causing this this specific test to fail when re-run, but the fact that other test projects fail is a little confusing to me.  One workaround you could try (and I'd be interested to hear what happens) is to update your batch script to also copy of the mscorlib.ni.dll that your CoreCLR build generated.

It would also be useful to understand if you do that, do you still get code coverage numbers for mscorlib?

**Comment by hughbe** [comment] 2016-05-08 20:30
I only get coverage numbers when I delete mscorlib.ni.dll. I'm not sure what that file does - any ideas?

**Comment by ellismg** [comment] 2016-05-08 20:49
> I only get coverage numbers when I delete mscorlib.ni.dll. I'm not sure what that file does - any ideas?

It's the [native image](https://github.com/dotnet/coreclr/blob/ebb839f3218a9410f76f4595574155304c5e101e/Documentation/building/crossgen.md) for mscorlib.dll.  I thought we were now able to profile against the native image, but apparently that is not the case.

I have suspicions as to what the problem is, but I have to run for a bit before I can confirm.i  In the mean time, could you update your batch script to first delete `coreclr.dll`, `mscorlib.dll` and `mscorlib.ni.dll` before copying over your new `coreclr.dll` and `mscorlib.dll` and let me know if that fixes the issue where other tests fail to run?  If my suspicions are correct, you will still hit errors when you try to run tests (via `msbuild /t:BuildAndTest`) for the specific assembly you are messing around with, but you shouldn't harm other assemblies.

**Comment by hughbe** [comment] 2016-05-09 16:04
> could you update your batch script to first delete coreclr.dll, mscorlib.dll and mscorlib.ni.dll before copying over your new coreclr.dll and mscorlib.dll and let me know if that fixes the issue where other tests fail to run?

Okay: you're correct - deleting the files first in the batch script does indeed fix the problem for other test projects. However, I'm not hitting errors when running `msbuild /T:BuildAndTest` for the specific assembly either!

**Comment by hughbe** [comment] 2016-05-09 16:09
Also btw I edited my previous post pretty much right as you answered it, could you take a look at that too (mainly r.e. the time difference between running tests)

**Comment by ellismg** [comment] 2016-05-10 01:34
> Okay: you're correct - deleting the files first in the batch script does indeed fix the problem for other test projects. However, I'm also not hitting errors when running msbuild /T:BuildAndTest for the specific assembly either!

So here's one of the things that's going on.  When we produce the test layouts, to save disk space we use hard linking so that the version of `coreclr.dll` (and all other assemblies) point at the version in the packages directory.  Edits to any one of the copies are reflected everywhere.  We you were doing the copy before, because of the hard link, the contents of all the `coreclr.dlls` were getting updated.

Since `coreclr.dll` and `mscorlib.ni.dll` are tightly coupled (the native image needs to be generated by the same version of the runtime) your script was updating `coreclr.dll` with your private copy but the native image everywhere else was not getting updated (there are additional issues tied to the fact that mscorlib.dll's layout differs between release and debug, so even if the native images were tolerant we'd likely continue to blow up, since every other test folder would have a debug runtime but a release mscorlib).

By deleting the files first, we don't end up stomping over the files in the packages.

> Also btw I edited my previous post pretty much right as you answered it, could you take a look at that too (mainly r.e. the time difference between running tests). Thanks!

There will definitely be a time difference.  In addition to all the JITing that we need to do now, since we don't use the native image, we are now using a debug runtime instead of retail one, which has a bunch of debug checks it will be doing.  The slowdown you're seeing seems high to me, but there is definitely going to be an impact.

**Comment by hughbe** [comment] 2016-05-10 06:16
Thanks for the diagnosis - seems like a pretty esoteric problem! 
Ill see what happens if I copy the release build of coreclr and run the test project in release mode

**Comment by hughbe** [comment] 2016-05-15 07:42
I might send in a PR to update the documentation describing how to run a coverage report for the local mscorlib build. I can reference and close this issue in that PR unless want to keep it open

Thanks again for the help

**Comment by ellismg** [comment] 2016-05-15 07:45
> I might send in a PR to update the documentation describing how to run a coverage report for the local mscorlib build. I can reference and close this issue in that PR unless want to keep it open

We might as well close it up once your change lands, since we have no plans to move away from the hard linking due to the space savings.  You can add the "Fixes #8381" metadata to the commit message.

**Closed** 2016-06-28 17:32 UTC
Labels: question
