### ISSUE TITLE
Azure deploy - Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) [but it IS there]

### ISSUE THREAD

**Issue by tiefling** [dotnet/corefx#14085] opened 2016-11-29 10:44 UTC
I am deploying a dotnet core app to my Test environment on Azure and getting the following error. This is blocking critical product development now and I've been banging my head against it for days...

> Application startup exception: System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
>    at System.Data.SqlClient.SNILoadHandle..ctor()
>    at System.Data.SqlClient.SNILoadHandle..cctor()
>    --- End of inner exception stack trace ---
>    at System.Data.SqlClient.TdsParser..cctor()
>    --- End of inner exception stack trace ---
>    at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
>    at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
>    at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
>    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
>    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
>    at System.Data.SqlClient.SqlConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass11_0.<Exists>b__0(DateTime giveUp)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
>    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    at Esoterix.Modle.Data.DbInitializer.Initialize(ApplicationDbContext context, RoleManager`1 roleManager, UserManager`1 userManager, IHostingEnvironment env) in C:\a\1\s\src\Esoterix.Modle\Data\DbInitializer.cs:line 18
>    at Esoterix.Modle.Portalweb.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ApplicationDbContext context, RoleManager`1 roleManager, UserManager`1 userManager) in C:\a\1\s\src\Esoterix.Modle.Portalweb\Startup.cs:line 180
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
>       Application startup exception
> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
>    at System.Data.SqlClient.SNILoadHandle..ctor()
>    at System.Data.SqlClient.SNILoadHandle..cctor()
>    --- End of inner exception stack trace ---
>    at System.Data.SqlClient.TdsParser..cctor()
>    --- End of inner exception stack trace ---
>    at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous)
>    at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, TimeoutTimer timeout)
>    at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, Boolean redirectedUserInstance)
>    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
>    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
>    at System.Data.SqlClient.SqlConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass11_0.<Exists>b__0(DateTime giveUp)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
>    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    at Esoterix.Modle.Data.DbInitializer.Initialize(ApplicationDbContext context, RoleManager`1 roleManager, UserManager`1 userManager, IHostingEnvironment env) in C:\a\1\s\src\Esoterix.Modle\Data\DbInitializer.cs:line 18
>    at Esoterix.Modle.Portalweb.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ApplicationDbContext context, RoleManager`1 roleManager, UserManager`1 userManager) in C:\a\1\s\src\Esoterix.Modle.Portalweb\Startup.cs:line 180
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> warn: Microsoft.AspNetCore.Server.Kestrel[0]
>       Unable to bind to http://localhost:27679 on the IPv6 loopback interface.
> System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
>    at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
> ---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)<---
> 
> Hosting environment: Test
> Content root path: D:\home\site\wwwroot
> Now listening on: http://localhost:27679
> Application started. Press Ctrl+C to shut down.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://catchthebuzz-portal-test.azurewebsites.net/  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 303.7181ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://catchthebuzz-portal-test.azurewebsites.net/  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 2.1775ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://catchthebuzz-portal-test.azurewebsites.net/  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 1.2613ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://catchthebuzz-portal-test.azurewebsites.net/  
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 1.4498ms 500 text/html; charset=utf-8
> 

My project.json looks like this...

```
{
    "userSecretsId": "aspnet-Esoterix.Modle-BLAHBLAHBLAHBLAH",

    "dependencies": {
        "Esoterix.Modle": {
            "target": "project"
        },
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Routing": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
        "Microsoft.Extensions.Caching.SqlServer": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.NETCore.App": "1.1.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
        "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"
    },

    "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview3-final"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "runtimes": {
        "win81-x64": {},
        "win81-x86": {}
    },

    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "**/*.cshtml",
            "appsettings.json",
            "appsettings.*.json",
            "web.config"
        ]
    },

    "scripts": {
        "prepublish": [ "npm install", "gulp build-server" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}
```

The project.json of the referenced library looks like this...

```
{
    "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.1.0",
        "Microsoft.AspNetCore.Session": "1.1.0",
        "Microsoft.EntityFrameworkCore.Design": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.Extensions.Caching.SqlServer": "1.1.0",
        "Microsoft.Extensions.Configuration": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
        "Microsoft.NETCore.App": "1.1.0",
        "NETStandard.Library": "1.6.1",
        "Newtonsoft.Json": "9.0.1",
        "SendGrid.NetCore": "1.0.0-rtm-00002"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "tools": {
        "Microsoft.Extensions.Caching.SqlConfig.Tools": "1.1.0-preview4-final",
        "Microsoft.EntityFrameworkCore.Tools.DotNet": {
            "version": "1.1.0-preview4-final",
            "imports": "portable-net451+win8"
        }
    },

    "buildOptions": {
        "emitEntryPoint": true
    },

    "runtimes": {
        "win81-x64": {},
        "win81-x86": {}
    }
}
```

The app runs fine under IIS Express on my local machine.

**Comment by tiefling** [comment] 2016-11-29 12:05
I have tried publishing through VSTS and publishing directly from Visual Studio with the same result. I did notice that I seem unable to compile x86 at all - only the x64 runtimes are generated on build on my machine.

To maximise compatibility I tried editing my runtime settings to...

```
    "runtimes": {
        "win7-x64": {},
        "win81-x64": {}
    },
```

in all of my project.json files but this made little difference. I have tried direct runtime specification of both these types when publishing from visual studio as well and the message doesn't change.

**Comment by tiefling** [comment] 2016-11-29 13:11
I have spent 2 hours this morning trying to reproduce this by publishing to my local IIS instance but, after a little (expected) tweaking, that seems to be working fine so I am unable to reproduce the issue locally at all. I'm now open to all ideas.

**Comment by tiefling** [comment] 2016-11-29 15:33
I fixed this in the end by only having one option in my runtimes as follows...

```
    "runtimes": {
        "win7-x64": {}
    },
```

But in order for it to take effect I had to make sure that I manually deleted all the files from the site via FTP before redeploying. That was the key. Is there a bug here where the publish files contain mixed content in some way?

There are several issues here...

1. Lack of documentation on required platform runtime requirements for deploying to Azure - This needs to be very visible in the documentation, along with instructions for clearing down if the runtime is changed.
2. Is there a bug around sni.dll inclusion where multiple runtimes are specified?

**Comment by karelz** [comment] 2016-11-29 16:10
Dupe of #13267

**Closed by karelz** 2016-11-29 16:10 UTC

**Comment by tiefling** [comment] 2016-11-29 16:20
Is it worth adding in a target runtime of "azure" which inherits from "win7-x64" to make the developer experience here better?

**Comment by karelz** [comment] 2016-11-29 17:33
Not sure if that is achievable or if it is a good idea - @ericstj?

**Comment by ericstj** [comment] 2016-11-29 17:50
>  "azure" which inherits from "win7-x64" to make the developer experience here better

That's not really correct.  Azure isn't `win7-x64` nor should that be required to deploy to azure.  The correct RID to use for standalone is the one that matches the OS you're targeting.

> Is there a bug around sni.dll inclusion where multiple runtimes are specified?

Not in the packages at least.  You can examine the project.lock.json to see if it had the correct information for those runtimes and sni.dll.  If I copy your project.json and restore myself I do see the correct info.  See https://gist.github.com/ericstj/2681f6170e8db9f23023efb1e65233c2
```
  "targets": {
...
    ".NETCoreApp,Version=v1.0/win81-x64": {
...
      "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni/4.3.0": {
        "type": "package",
        "native": {
          "runtimes/win7-x64/native/sni.dll": {}
        }
      },
...
    ".NETCoreApp,Version=v1.0/win81-x86": {
...
      "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni/4.3.0": {
        "type": "package",
        "native": {
          "runtimes/win7-x86/native/sni.dll": {}
        }
      },
```

What runtime was being used for publishing?  It seems to me the more likely culprit here was something in the publishing tooling was getting confused by more than one RID in the project.json.  I believe that points to a bug in the ASP.NET publish tooling.  @BillHiebert @pranavkm can you route this?

**Comment by tiefling** [comment] 2016-11-29 18:04
Agreed here but the underlying issue from a usability perspective is that “azure” isn’t any of the available options. The issue here is that the underlying OS of the Azure platform should not be a deploying developers concern (unless they are using a VM which is a whole other story). This would allow “azure” to be regarded as a platform in it’s own right (which it is really), whether it mirrors “win7-x64” for now is just an observation. Azure is to all intents and purposes the OS I'm targeting.

The fact I have to use “win7-x64” is quite obtuse when my real target is “azure”.

As for the runtime for publishing, I didn’t specify one to start with (as I was using VSTS) and then I tried win81-x64 and win7-x64. It wasn’t until I manually cleared out all the files that I got a working build under win7-x64. I think you’re right – I don’t think dotnet publish-iis is working properly unless everything is specified for it.

**Comment by pranavkm** [comment] 2016-11-29 20:15
@vijayrkn is involved in the VS publishing feature.

@tiefling might not be super relevant, but why not make this a portable app? You wouldn't need to juggle around with runtime identifiers.

**Comment by vijayrkn** [comment] 2016-11-29 21:47
In the pubxml file, there is an msbuild property 'PublishRuntime'. 

Publish looks at this property to determine which RID to use. If this property is not defined, then the RID is inferred for standalone apps (inferred runtime is shown in the settings page on the publish dialog).

**Comment by tiefling** [comment] 2016-11-30 09:17
@vijayrkn The VS Publishing feature makes this a lot clearer, I think the inferred state was happening when I was deploying from VSTS (which is using command line).

@pranavkm How do I make it a portable app? Is that another runtime option?

**Comment by pranavkm** [comment] 2016-11-30 15:54
Change

```js
"Microsoft.NETCore.App": "1.1.0",
```

to
```json```
"Microsoft.NETCore.App": {
   "version": "1.1.0",
   "target": "platform"
}
```

and remove the `runtimes` section.

**Comment by tiefling** [comment] 2016-11-30 17:15
I'll give that a try - would I lose anything from this?

**Comment by pranavkm** [comment] 2016-11-30 17:20
See https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/ for what the differences are.

**Comment by tiefling** [comment] 2016-11-30 17:45
Thanks for that - I may give that a try.

**Comment by tiefling** [comment] 2016-12-01 10:31
This doesn't work. dotnet restore fails with the error...
"error: Invalid dependency target value 'platform'"
