### ISSUE TITLE
Why does RuntimeInformation.OSArchitecture lie to me on ARM64? 💔

### ISSUE THREAD

**Issue by riverar** [dotnet/corefx#31180] opened 2018-07-19 03:54 UTC
Consult your nearest `Console.WriteLine(RuntimeInformation.OSArchitecture)` code, target x86, .NET Framework 4.7.2, and run the result on an ARM64 device running Windows on ARM.

Expected: ARM64
Actual: x86

Windows 10 17713 rs5_release

Related issues:
https://github.com/dotnet/corefx/issues/28856
https://github.com/dotnet/corefx/issues/27386
https://github.com/dotnet/corefx/issues/25706
https://github.com/dotnet/corefx/issues/19313

Pulled in some previous players from related issues:
cc: @AlexGhiondea @joperezr @luqunl @danmosemsft @terrajobst

**Comment by danmosemsft** [comment] 2018-07-19 04:48
Presumably because Windows is telling us x86. What do you get if you call it manually? Code roughly pasted below.

```c#
                        Interop.Kernel32.SYSTEM_INFO sysInfo;
                        Interop.Kernel32.GetNativeSystemInfo(out sysInfo);

                        switch ((Interop.Kernel32.ProcessorArchitecture)sysInfo.wProcessorArchitecture)
                        {
                            case Interop.Kernel32.ProcessorArchitecture.Processor_Architecture_ARM64:
                                s_osArch = Architecture.Arm64;
                                break;
                            case Interop.Kernel32.ProcessorArchitecture.Processor_Architecture_ARM:
                                s_osArch = Architecture.Arm;
                                break;
                            case Interop.Kernel32.ProcessorArchitecture.Processor_Architecture_AMD64:
                                s_osArch = Architecture.X64;
                                break;
                            case Interop.Kernel32.ProcessorArchitecture.Processor_Architecture_INTEL:
                                s_osArch = Architecture.X86;
                                break;
                        }

internal partial class Interop
{
    internal partial class Kernel32
    {
        [StructLayout(LayoutKind.Sequential)]
        internal struct SYSTEM_INFO
        {
            internal ushort wProcessorArchitecture;
            internal ushort wReserved;
            internal int dwPageSize;
            internal IntPtr lpMinimumApplicationAddress;
            internal IntPtr lpMaximumApplicationAddress;
            internal IntPtr dwActiveProcessorMask;
            internal int dwNumberOfProcessors;
            internal int dwProcessorType;
            internal int dwAllocationGranularity;
            internal short wProcessorLevel;
            internal short wProcessorRevision;
        }

        internal enum ProcessorArchitecture : ushort
        {
            Processor_Architecture_INTEL = 0,
            Processor_Architecture_ARM = 5,
            Processor_Architecture_IA64 = 6,
            Processor_Architecture_AMD64 = 9,
            Processor_Architecture_ARM64 = 12,
            Processor_Architecture_UNKNOWN = 0xFFFF
        }
    }
}
```

Probably it's the same cause as https://github.com/dotnet/corefx/issues/28856. Someone would have to ask the OS folks why they do this - probably so that existing apps do'nt break.

Why do you need to know what the architecture is BTW?

**Comment by jkotas** [comment] 2018-07-19 05:37
Yes, this is Windows returning fake values from existing APIs to make most of the existing applications work.

Duplicate of https://github.com/dotnet/corefx/issues/30658

**Closed by jkotas** 2018-07-19 05:37 UTC

**Comment by riverar** [comment] 2018-07-19 05:43
We found this API and thought it'd be a clean way to determining the architecture for loading some architecture-dependent OS resources. `Kernel32.GetNativeSystemInfo` returns x86 as well so I guess this API will never be correct.

Am a little confused why this was added at all, if it's not doing anything differently and will always require me to understand the OS lies/implementation internals.

**Comment by danmosemsft** [comment] 2018-07-19 05:46
@riverar try a pinvoke to https://docs.microsoft.com/en-us/windows/desktop/api/wow64apiset/nf-wow64apiset-iswow64process2

**Comment by riverar** [comment] 2018-07-19 05:54
@danmosemsft The applicability matrix is wrong and using this limits us to RS3+. But no worries, we'll get this info via other means. Thanks.
