### ISSUE TITLE
Possible unintended NullReferenceException thrown from JsonSerializer.Deserialize

### ISSUE THREAD

**Issue by am11** [dotnet/corefx#40449] opened 2019-08-20 15:20 UTC
Tested with master branch (as of 2fac89f63c644ab81d936d62c91e6003302e718d)
The following code:

```c#
using System.Text.Json;
using System.Collections.Generic;

interface X {}

class A : List<X> {}

class Program
{
  static void Main(string[] args) => JsonSerializer.Deserialize<A>("false");
}
```

throws `NullReferenceException`:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

if we remove `: List<X>`, then it throws `JsonException`:

```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to myApp.A. Path: $ | LineNumber: 0 | BytePositionInLine: 5.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message, Utf8JsonReader& reader, String path, Exception innerException)
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType, Utf8JsonReader& reader, String path, Exception innerException)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

if we keep `: List<X>` and replace `"false"` with `"{}"`, then we get `NotSupportedException`:

```
Unhandled exception. System.NotSupportedException: Deserialization of interface types is not supported. Type 'X'
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_DeserializePolymorphicInterface(Type invalidType)
   at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

I think `NotSupportedException` is desired in place of NRE from the original repro until there is an interface support. After the support is added, `JsonException` would be desired here (similar to the one we get without `: List<X>`).

**Comment by ahsonkhan** [comment] 2019-08-20 17:42
cc @steveharter, @layomia

**Comment by steveharter** [comment] 2019-08-29 18:56
NRE should never be thrown, so that is not by design.

A `JsonException` is the correct exception since the JSON is valid as the PR https://github.com/dotnet/corefx/pull/40501 is doing.

It is not a breaking change for 5.0 to change a NRE to JsonException, so this will not likely be ported to 3.0 (doesn't meet the bar; 3.0 is pretty much in lockdown).

**Comment by steveharter** [comment] 2019-08-29 20:46
I am assuming that the object model is invalid -- thus the NRE will be detected and the object model fixed. However is there a known case where the object model is valid and a NRE is thrown? (I will investigate soon)

**Comment by steveharter** [comment] 2019-09-05 14:46
Closing as fixed with the PR linked above.

**Comment by steveharter** [comment] 2019-10-01 19:52
Setting milestone to 3.1 for consideration.

**Comment by ahsonkhan** [comment] 2019-10-03 02:03
From https://github.com/dotnet/corefx/issues/41459 by @Firefly74940:

> with the following structure deserializing invalid json ( see end of issue ) crash instead of using appropriate exeption
> 
> ```
> class ArticleTypesData
>     {
>         public IList<ArticleType> ItemTypes { get; set; }
>     }
>     class ArticleType
>     {
>         public string Name { get; set; }
>     }
> ```
> 
> logic used :
> 
> ```
> var options = new JsonSerializerOptions
>  {
>     AllowTrailingCommas = true
> };
> 
> var ArticleTypesDatas = JsonSerializer.Deserialize<ArticleTypesData>(file, options);
> ```
> 
> Actual result : Null ptr exeption :
> 
> Expeted result :
> use of System.Text.Json.JsonException . with message like
> `System.Text.Json.JsonException : ''"' is an invalid start of an object Array. Expected a '{'. Path: $.ItemTypes[0] | LineNumber: 4 | BytePositionInLine: .'`
> 
> valid json :
> 
> ```
> {
>     "ItemTypes": [
>     
>         {
> 			"Name": "Where to Stay",
> 		},
> 		{
> 			"Name": "Where to Stay",
> 		},
>     
> 	]
> }
> ```
> 
> invalid json :
> 
> ```
> {
>     "ItemTypes": [
> 
> 			"Name": "Where to Stay",
> 
> 			"Name": "Where to Stay",
> 
> 	]
> }
> ```

**Closed** 2019-10-16 22:29 UTC
Labels: area-System.Text.Json, bug, tenet-reliability
