### ISSUE TITLE
Extremely slow queries when when running on Linux with SQL 2017 on the same machine 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/corefx#24582] opened 2017-10-11 19:57 UTC
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/10043 submitted by @sdb-dev

I am experiencing 5-10x slower queries on a fresh dedicated server with Ubuntu 16.04 and SQL Server 2017. 

This issue is ONLY happening when the SQL Server and the .NET Core application is running on the same linux machine (Ubuntu).

I created a simple application which does a .ToList() on 2 tables (one with 500 records, another with 10,000)

Running the .NET Core application on my local computers, connecting to the SQL Server remotely, I get the following results:
```
Loaded (Table 1) 500 in 851.00 ms
Reloading context.
Loaded (Table 1) 500 in 95.00 ms
Loaded (Table 2) 10000 in 262.00 ms`
```
Running the same .NET Core application on the remote machine with SQL Server on it (localhost)
```
Loaded (Table 1) 500 in 2,362.00 ms
Reloading context.
Loaded (Table 1) 500 in 1,524.00 ms
Loaded (Table 2) 10000 in 42,976.00 ms
````

If I run the same .NET Core application on the machine which experiences the slow-down with another remote server, it runs perfectly fine - it seems to only occur when both SQL and the .NET app are on the same machine. 

For whatever reason, there seems to be a huge send queue from SQL to my application, which leads me to believe EF Core may be very slow materializing the data from sql - SQL sends the data perfectly fine.

For reference, here is the testing code:
```Console.WriteLine("Starting...");
var sw = new Stopwatch();
sw.Start();
var db = new MyDbContext("connString");
var attrs = db.TableOne.ToList();
sw.Stop();

Console.WriteLine($"Loaded (Table 1) {attrs.Count} in {sw.ElapsedMilliseconds:N2} ms");
Console.WriteLine("Reloading context.");
db.Dispose();

sw.Reset();
sw.Start();
db = new MyDbContext("connString");
attrs = db.TableOne.ToList();
Console.WriteLine($"Loaded (Table 1) {attrs.Count} in {sw.ElapsedMilliseconds:N2} ms");
sw.Stop();
sw.Reset();
sw.Start();
var items = db.TableTwo.ToList();
Console.WriteLine($"Loaded (Table 2) {items.Count} in {sw.ElapsedMilliseconds:N2} ms");

sw.Stop();

Console.WriteLine("Press any key to continue.");
Console.Read();```

**Comment by ajcvickers** [comment] 2017-10-11 19:57
Comment from https://github.com/aspnet/EntityFrameworkCore/issues/10043 by @sdb-dev

I found a way to 'fix' this issue - setting the packet size to on the connection string (`Packet Size=32768;`) makes the data load extremely fast as it normally should...

I just have absolutely no idea why that would make a difference. That value is not set on my remote strings. 

Anyhow, with that option, the 10k records now load in under 100ms instead of 40 seconds.. quite a big difference.

**Comment by ajcvickers** [comment] 2017-10-11 19:58
https://github.com/aspnet/EntityFrameworkCore/issues/10043 submitted by @ralmsdeveloper 

By default in ADO.NET, the packet value in (bytes) is 8000.

So, SQL will use the SinglePage Allocator, but if you set a value greater than 8000, we will force SQL Server to work in a MultiPage Allocator, so the performance gain is much greater

**Comment by ajcvickers** [comment] 2017-10-11 20:01
FYI @sebastienros @mikeharder @anpete @divega--it was mentioned in triage that this may be related to an issue you guys have been seeing with the benchmarks.

**Comment by sebastienros** [comment] 2017-10-11 20:05
I am seeing a similar slow performance with a Linux container, I will try with your connection string.

**Comment by sdb-dev** [comment] 2017-10-12 03:38
Is there any reason this would only occur when connecting to a locally hosted SQL Server?
If I connect to an azure (or another external database) from the same machine, the issue doesn't occur.

**Comment by divega** [comment] 2017-10-12 06:28
> Is there any reason this would only occur when connecting to a locally hosted SQL Server?
If I connect to an azure (or another external database) from the same machine, the issue doesn't occur.

Don’t know, but perhaps this will ring a bell for @saurabh500 or @corivera.

**Comment by saurabh500** [comment] 2017-10-12 06:33
We are investigating similar issues at https://github.com/dotnet/corefx/issues/24480

**Comment by wfurt** [comment] 2018-01-16 19:10
#24480 is closed (and fixed) now. Did any of the workarounds solve your problems @ajcvickers ?
Is there any work left here or should this be closed?

**Comment by saurabh500** [comment] 2018-02-03 01:51
Closing as dupe of https://github.com/dotnet/corefx/issues/24480

**Closed by saurabh500** 2018-02-03 01:51 UTC
Labels: area-System.Data.SqlClient
