### ISSUE TITLE
System.Net.Tests.TaskWebClientTest.UploadData_LargeData_Success failed with "System.Net.WebException : The operation has timed out" in CI

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23777] opened 2017-09-04 02:41 UTC
Failed test: System.Net.Tests.TaskWebClientTest.UploadData_LargeData_Success

MESSAGE:
~~~
System.Net.WebException : The operation has timed out.
~~~
STACK TRACE:
~~~
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_debian8.4_debug/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1261 
at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result) in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_debian8.4_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 256 
at System.Net.WebClient.<GetWebResponseTaskAsync>d__112.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_debian8.4_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 269 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() 
at System.Net.WebClient.<DownloadBitsAsync>d__150.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_debian8.4_debug/src/System.Net.WebClient/src/System/Net/WebClient.cs:line 865 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at System.Net.Tests.WebClientTestBase.<UploadData_LargeData_Success>d__21.MoveNext() in /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_debian8.4_debug/src/System.Net.WebClient/tests/WebClientTest.cs:line 657 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

**Comment by karelz** [comment] 2017-12-22 21:25
Older error message for failure to connect to EchoServers
Duplicate of #26032

**Closed by karelz** 2017-12-22 21:25 UTC
Labels: area-System.Net, Azure test infra changes needed, test-run-core
