### ISSUE TITLE
Environment.GetFolderPath(SpecialFolder) returns empty string in Nano Server docker containers

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#22049] opened 2017-07-10 21:32 UTC
In Windows Nano Server containers, `Environment.GetFolderPath(SpecialFolder folder)` returns an empty string  for many vaules of `Environment.SpecialFolder`, but not all.

## Repro

1. Install Docker for Windows. Make sure to use Windows containers, not Linux containers.
2. Create a project with 3 files, Dockerfile, Program.cs, and specialfolder.csproj (below)
3. Run these commands
```
docker build . --tag test
docker run --rm test
```
#### Project files
```Dockerfile
FROM microsoft/dotnet-nightly:2-sdk AS builder

WORKDIR /source
COPY specialfolder.csproj .
COPY Program.cs .
RUN dotnet restore
RUN dotnet publish -o pub/ -c Release

FROM microsoft/dotnet-nightly:2-runtime
WORKDIR /app
COPY --from=builder /source/pub .
ENTRYPOINT ["dotnet", "specialfolder.dll"]
```
```c#
using System;

class Program
{
    static void Main(string[] args)
    {
        foreach (var item in Enum.GetValues(typeof(Environment.SpecialFolder)))
        {
            var value = (Environment.SpecialFolder)item;
            Console.WriteLine($"Environment.SpecialFolder.{value} = {Environment.GetFolderPath(value)}");
        }
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

## Expected

I would have expected common values like `Environment.SpecialFolder.System` and `Environment.SpecialFolder.Windows` to have a non-empty file paths. 

## Result
Some return empty strings, others return the expected value.
```
Environment.SpecialFolder.Desktop =
Environment.SpecialFolder.Programs =
Environment.SpecialFolder.MyDocuments =
Environment.SpecialFolder.MyDocuments =
Environment.SpecialFolder.Favorites =
Environment.SpecialFolder.Startup =
Environment.SpecialFolder.Recent =
Environment.SpecialFolder.SendTo =
Environment.SpecialFolder.StartMenu =
Environment.SpecialFolder.MyMusic =
Environment.SpecialFolder.MyVideos =
Environment.SpecialFolder.DesktopDirectory =
Environment.SpecialFolder.MyComputer =
Environment.SpecialFolder.NetworkShortcuts =
Environment.SpecialFolder.Fonts =
Environment.SpecialFolder.Templates =
Environment.SpecialFolder.CommonStartMenu =
Environment.SpecialFolder.CommonPrograms =
Environment.SpecialFolder.CommonStartup =
Environment.SpecialFolder.CommonDesktopDirectory =
Environment.SpecialFolder.ApplicationData =
Environment.SpecialFolder.PrinterShortcuts =
Environment.SpecialFolder.LocalApplicationData = C:\Users\ContainerAdministrator\AppData\Local
Environment.SpecialFolder.InternetCache = C:\Users\ContainerAdministrator\AppData\Local\Temporary Internet Files
Environment.SpecialFolder.Cookies = C:\Users\ContainerAdministrator\Cookies
Environment.SpecialFolder.History = C:\Users\ContainerAdministrator\AppData\Local\Microsoft\Windows\History
Environment.SpecialFolder.CommonApplicationData = C:\ProgramData
Environment.SpecialFolder.Windows =
Environment.SpecialFolder.System =
Environment.SpecialFolder.ProgramFiles = C:\Program Files
Environment.SpecialFolder.MyPictures =
Environment.SpecialFolder.UserProfile = C:\Users\ContainerAdministrator
Environment.SpecialFolder.SystemX86 =
Environment.SpecialFolder.ProgramFilesX86 =
Environment.SpecialFolder.CommonProgramFiles =
Environment.SpecialFolder.CommonProgramFilesX86 =
Environment.SpecialFolder.CommonTemplates =
Environment.SpecialFolder.CommonDocuments =
Environment.SpecialFolder.CommonAdminTools =
Environment.SpecialFolder.AdminTools =
Environment.SpecialFolder.CommonMusic =
Environment.SpecialFolder.CommonPictures =
Environment.SpecialFolder.CommonVideos =
Environment.SpecialFolder.Resources =
Environment.SpecialFolder.LocalizedResources =
Environment.SpecialFolder.CommonOemLinks =
Environment.SpecialFolder.CDBurning =
```

## Details
Microsoft.NETCore.App: 2.0.0-preview3-25510-01
Dockerfile: https://github.com/dotnet/dotnet-docker-nightly/blob/c42606da40a7c22f523a1c64f426339f3fc6ad34/2.0/runtime/nanoserver/Dockerfile
Base image: `microsoft/nanoserver:10.0.14393.1358`

Docker info:
```
Server Version: 17.06.0-ce
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
```

**Comment by rainersigwald** [comment] 2017-07-10 21:53
https://github.com/dotnet/corefx/pull/18443 could possibly be related: it removes a fallback path "not availableon some mincore versions of Windows" -- maybe it was supported on nanoserver and the fallback was necessary for System?

**Comment by rainersigwald** [comment] 2017-07-11 16:11
I think that was a red herring; the MSBuild bug that led to this investigation is unrelated because we have our own wrapper around `SHGetFolderPath` that's behaving oddly in this case. The behavior described in this bug is still surprising to me, though.

**Comment by rainersigwald** [comment] 2017-07-11 16:57
Looks like this is a duplicate of #19110.

**Comment by natemcmaster** [comment] 2017-07-11 17:00
cc @danmosemsft

**Comment by danmosemsft** [comment] 2017-07-11 20:23
Yes, it's a dupe. ShGetKnownFolderPath is a partial stub on Nano. Please use other means such as environment variables until we have improved this.

**Comment by pjanotti** [comment] 2017-07-11 23:53
Closing since it is a dup of #19110

**Closed by pjanotti** 2017-07-11 23:53 UTC
