### ISSUE TITLE
WebSocket can crash UWP apps if the server does not close the connection gracefully

### ISSUE THREAD

**Issue by moozzyk** [dotnet/corefx#19854] opened 2017-05-16 23:34 UTC
I am investigating a [SignalR issue](https://github.com/aspnet/SignalR/issues/412) where a netstandard SignalR client is being used in a UWP app. The client uses webSockets to connect to the server. The expectation is that when the server is being closed the client will notify the user by raising an event. However the application crashes due to an unhandled exception with the following stack trace:

```
System.Exception: Exception from HRESULT: 0x80072EFE
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
```

If I read the code correctly it seems that if the exception happens here: https://github.com/dotnet/corefx/blob/ec2a6190efa743ab600317f44d757433e44e859b/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WinRTWebSocket.cs#L282 it won't be handled anywhere but can't also be caught which causes the crash. 

SignalR client [expects](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.Sockets.Client/WebSocketsTransport.cs#L80-L81) receive result with WebSocketMessageType.Close result type.

**Comment by davidsh** [comment] 2017-05-16 23:59
This is a dupe of #17317.

**Closed** 2017-05-17 00:00 UTC
Labels: area-System.Net.Sockets, os-windows-uwp

**Comment by moozzyk** [comment] 2017-05-17 02:21
SignalR is hitting this as well: https://github.com/aspnet/SignalR/issues/412
