### ISSUE TITLE
Desktop: Tests under "DataContractJsonSerializerTests" failed with "strings differ at index 2"

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#18723] opened 2017-04-21 09:18 UTC
Failed tests:
 DataContractJsonSerializerTests.DCJS_StringAsRoot
 DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary
 DataContractJsonSerializerTests.DCJS_StringAsRoot
 DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/26/consoleText

~~~
DataContractJsonSerializerTests.DCJS_StringAsRoot [FAIL]
strings differ at index 2
               
  [expected]:"\b"
  [actual  ]:"\u0
               
  [Expected (with length=4)]:
  "\b"
  [Actual (with length=8)]:
  "\u0008"
        Test failed for input: 
        Expected: "\b"
        Actual: "\u0008"
        Expected: True
        Actual:   False

        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(2861,0): 
at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
          D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(248,0): 
at DataContractJsonSerializerTests.DCJS_StringAsRoot()

DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary [FAIL]
        strings differ at index 2
               
  [expected]:{"_dictionary":[{"Key"
  [actual  ]:{"m_dictionary":[{"Key
               
  [Expected (with length=65)]:
  {"_dictionary":[{"Key":"Foo","Value":1},{"Key":"Bar","Value":2}]}
  [Actual (with length=66)]:
  {"m_dictionary":[{"Key":"Foo","Value":1},{"Key":"Bar","Value":2}]}
        Test failed for input: System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.Int32]
        Expected: {"_dictionary":[{"Key":"Foo","Value":1},{"Key":"Bar","Value":2}]}
        Actual: {"m_dictionary":[{"Key":"Foo","Value":1},{"Key":"Bar","Value":2}]}
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(2861,0): at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
          D:\j\workspace\outerloop_net---903ddde6\src\System.Runtime.Serialization.Json\tests\DataContractJsonSerializer.cs(1700,0): at DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary()
~~~

**Comment by shmao** [comment] 2017-04-21 23:19
@danmosemsft On Desktop, the fix for DataContractJsonSerializerTests.DCJS_StringAsRoot was made for 4.6.2 (or 4.7). As the test ran on desktop 4.6.1, the test failure is as expected. How do we want to deal with this test in this case?

The failure of DataContractJsonSerializerTests.DCJS_ReadOnlyDictionary is a duplicate of https://github.com/dotnet/corefx/issues/18312.

**Comment by danmosemsft** [comment] 2017-04-22 00:06
Ideally you would add a property to PlatformDetection.cs that parses the frameowrk version from RuntimeInformation.FrameworkDescription and then you can use that like `[ConditionalFact(nameof(IsAtLeast426))]`

Or else you could disable entirely like `[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "Implemented in 4.6.2. and Xunit runner currently targets 4.5.2 ")]`

**Comment by Jiayili1** [comment] 2017-04-26 09:08
This issue is repro on desktop, detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netfx_windows_nt_debug/31/testReport/(root)/DataContractJsonSerializerTests/DCJS_ReadOnlyDictionary/

**Comment by danmosemsft** [comment] 2017-04-28 04:09
DCJS_ReadOnlyDictionary is covered by https://github.com/dotnet/corefx/issues/18312

**Closed by danmosemsft** 2017-04-28 04:09 UTC
Labels: area-Serialization, test bug, test-run-desktop
