### ISSUE TITLE
Indexing into a large stringbuilder is extremely innefficient

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/corefx#5585] opened 2016-01-21 17:40 UTC
Run the following program (reverse a string in a string builder)

Results: 

When i runs up to 100,000. About 1 : 13 elapsed time.
When i runs up to 1,000,000: 1 : 5000 elapsed time.

On 10,000,000 you give up.

```c#
using System;
using System.Diagnostics;
using System.Text;

namespace ConsoleApplication32
{
    class Program
    {
        static void Main(string[] args)
        {
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < 1000000; i++)
            {
                builder.Append("ABCDEF");
            }

            var input = builder.ToString().ToCharArray();

            var last = input.Length - 1;
            var mid = last / 2;
            Stopwatch sw1 = new Stopwatch();
            sw1.Start();

            char temp;
            for (int i = 0; i <= mid; i++)
            {
                temp = input[i];
                input[i] = input[last - i];
                input[last - i] = temp;
            }

            sw1.Stop();
            Console.WriteLine(sw1.ElapsedMilliseconds);

            Stopwatch sw2 = new Stopwatch();
            sw2.Start();

            for (int i = 0; i <= mid; i++)
            {
                temp = builder[i];
                builder[i] = builder[last - i];
                builder[last - i] = temp;
            }

            sw2.Stop();
            Console.WriteLine(sw2.ElapsedMilliseconds);
        }
    }
}
```

**Comment by stephentoub** [comment] 2016-01-21 18:02
cc: @vancem 

The problem is that StringBuilder is implemented as a chain of StringBuilders, in order to improve performance of certain situations (Vance can elaborate on what those are and why this change was made).  The downside is that because it's built up in chunks as a linked list, indexing can become an O(N) operation.  You can see the impact of this by pre-sizing the StringBuilder, e.g. if you change:
```C#
new StringBuilder();
```
to:
```C#
new StringBuilder(1000000 * "ABCDEF".Length);
```
it completes much more quickly, as it's all in a single chunk and indexing becomes O(1) again.

**Comment by yishaigalatzer** [comment] 2016-01-21 18:12
@stephentoub that's pretty clear from the code. However creating a large allocation upfront drops us into LOH again, which was the first reason to use the string builder.

FYI this is not a blocking issue, just a problem I was seeing as part of another exercise.

**Comment by vancem** [comment] 2016-01-22 01:20
This performance characteristic is basically by design.   Yes, we gave up perf on the indexing operation for other value.  By far the most important performance case is  'Append' operations, secondarily the constructor and 'ToString' operations.   Everything else is not nearly as important (it is not even clear that they were worth supporting, but that decision has been made for better or worse).

I do not believe you can fix the peformance characterisitcs of [] without non-trivial change in the design and/or increase in complexity (correct me if I am wrong).   The first step in deciding to do something like this would be 1 or (preferably) more scenarios that justify the effort.  (Keeping in mind the simple work-around Stephen indicated).  

In the absence of that, we would close this issue.

**Comment by yishaigalatzer** [comment] 2016-01-22 01:45
Here is some info on the matter to help with the decision

1. Priority - From my side, pretty low
2. Stephen's suggestion (repeating my above statement) - Making the buffer large gets you into LOH land, which is the reason to use StringBuilder to begin with
3. You can make performance better if you make the assumption that all the linked buffers are of the same size (not sure if you can or can't) at that point the operation becomes follow the link N times (still o(N) but less operations), but if you maintain a tree or table of pointers to the buffers instead of a linked list its o(1) again.
4. Finally I'm not opposing to closing the bug.

**Comment by vancem** [comment] 2016-01-22 17:10
As suggested, I am closing the issue

**Closed by vancem** 2016-01-22 17:10 UTC
Labels: performance, System.Runtime
