### ISSUE TITLE
Intermittent Numeric Tests Failures on OSX

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#5511] opened 2016-01-19 02:52 UTC
If you look a the history for the [OSX Release Test Job](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst/) some of the matrix tests have been failing intermittently.  I'm not sure if the failures are machine specific (one of the Matrix 4x4 tests has failed twice on -1 mac but passes elsewhere).

**Comment by mellinoe** [comment] 2016-01-19 19:08
I haven't been able to repro this on my machine. This is related to #4882 , it seems. By the way, these tests are deterministic, so I don't really understand why they are only failing occasionally when each run should be identical.

**Comment by ellismg** [comment] 2016-01-19 19:17
@mellinoe I am wondering if it passes on some machines but fails on others?  Would the code we run differ based on what sort of machine we are running on?

**Comment by mellinoe** [comment] 2016-01-19 19:25
As far as I know it shouldn't differ across machines, especially not on OSX, because SIMD isn't enabled on OSX yet

For other context, these same tests have been running unchanged for a long time, on .NET Native, Desktop, CoreCLR, etc. So I strongly suspect there's a bug in the (OSX) JIT somewhere, but I don't know where. The fact that it is an unreliable repro also makes it very hard to diagnose. I filed https://github.com/dotnet/coreclr/issues/2266, but we weren't able to repro the issue there. There were some JIT fixes at the time so we assumed it was fixed. I'll re-open that as it's still occurring.

**Comment by mellinoe** [comment] 2016-01-22 19:09
I'm going to close this issue as it's a duplicate of #4882, and that is the issue that's referenced in the ActiveIssue in the code. Most of the discussion was happening in https://github.com/dotnet/coreclr/issues/2266.

**Closed by mellinoe** 2016-01-22 19:09 UTC
Labels: bug, Mac OSX, System.Numerics
