### ISSUE TITLE
Maestro-Corefx-GeneralExecutor build is modifying the REDMOND\dlab14 user's nuget.config file

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#33807] opened 2018-12-03 20:45 UTC
in this build:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2245324
--
it was detected that:
11/30/2018 5:20 PM (UTC) : Contents of \\DDVSOWINAGE007\C$\Users\dlab14\AppData\Roaming\NuGet\NuGet.Config changed from <?xml version="1.0" encoding="utf-8"?>
 
and

2018-11-30T17:20:10.4603689Z dotnet-install: Adding to current process PATH: "E:\A\_work\2039\s\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.

**Comment by robertborr** [comment] 2018-12-03 21:56
ref: https://github.com/dotnet/core-eng/issues/4721

**Comment by wtgodbe** [comment] 2018-12-05 18:01
Sure, looking now.

**Comment by wtgodbe** [comment] 2018-12-05 18:38
Just confirmed with @MattGal that the PATH issue is benign, we're just modifying the process shell's PATH, not the global one. Looking into nuget.config now.

**Comment by wtgodbe** [comment] 2018-12-05 19:01
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="CliFallbackFolder" value="C:\Users\dlab14\.dotnet\NuGetFallbackFolder" />
  </packageSources>
</configuration> to <?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>`

**Comment by wtgodbe** [comment] 2018-12-05 19:02
@livarcocc I see that the CLI is calculating a NugetFallbackFolder that's identical to the one in the log: https://github.com/dotnet/cli/blob/54bce746005c1ef0bdec0a7f4c560c3dbc0d79a0/test/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs#L31. Do you know if/where CLI inserts that into the nuget.config? We run into issues when `.dotnet\NuGetFallbackFolder` isn't present on disk

**Comment by wtgodbe** [comment] 2018-12-05 20:54
@MattGal is there a way to check if subsequent builds of this def had the same issue? It looks like our CLI version is new enough that it wouldn't have the nuget.config-writing behavior , so I'm wondering if maybe this instance was a red herring (also seems from https://github.com/dotnet/core-eng/issues/4721 like this issue was mainly affecting legacy builds, so seems weird we'd hit it in master). Still looking into what else might be capable of writing to nuget.config

**Comment by MattGal** [comment] 2018-12-05 21:13
It may be a red-herring.  I definitely suspect the CLI as the only thing that would put the lines we're looking at into the machines in this case. I've made some improvements to the alerting tool, so I'm fine w/ closing this one for now and reopening / filing new one when it happens next.

**Comment by wtgodbe** [comment] 2018-12-05 21:15
Sounds good, please let me know if it happens again

**Closed by wtgodbe** 2018-12-05 21:15 UTC
Labels: area-Infrastructure, bug
