### ISSUE TITLE
VS Code has trouble opening projects from CoreFX

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/corefx#19890] opened 2017-05-17 15:58 UTC
I've been trying to use VS code for CoreFx development, but with very little luck so far.
First of all there doesn't seem to be a master solution, some assemblies have their own solutions some don't, there doesn't seem to be much of an order in the .sln files.
Opening the repo in VS Code, one needs to pick the .sln to work with (so that OmniSharp has a way to load the projects).
Just two examples:
- System.Threading.tasks.sln - there are several warnings and failures reported when opening this. The end result is that intellisense doesn't work at all - no Go to Definition or anything like that.
- System.Private.Xml.sln - this one seems to open without fatal errors, so some of the intellisense lights up, but then the IDE reports a huge number of errors. Opening a random source file like XmlResolver.cs shows a lot of red squiggles. Basically it seems that types from CoreLib don't resolve at all.

**Comment by karelz** [comment] 2017-05-17 16:21
This is weird and blocks/demotivates some of our contributors. @weshaggard @mellinoe can you please take a look at it when you're done with high-pri fires? This is fairly important IMO.

**Comment by vitek-karas** [comment] 2017-05-17 16:32
Let me add that full VS is not much better. I tried both of the solutions above and neither really works. System.Threading.Taks.sln doesn't show any .cs files in the "product" project.
System.Private.Xml is better, as the project opens nicely, but VS didn't manage to get intellisense working anyway (go to definition between types from inside System.Private.Xml still didn't work).

**Comment by mellinoe** [comment] 2017-05-17 19:05
One thing to note if you're opening these projects: you need to run a build (build.cmd/sh) first, in order to produce all of the reference assemblies used when compiling the product assemblies. At the very least, it should work reliably in full VS.

> System.Threading.Taks.sln doesn't show any .cs files in the "product" project.

System.Threading.Tasks doesn't have any source files in its src project, so that is expected. It is a facade assembly, so it only contains type-forwards, which are auto-injected as part of our build process.

**Comment by garfbradaz** [comment] 2017-05-17 19:14
> System.Threading.Tasks doesn't have any source files in its src project, so that is expected. It is a facade assembly, so it only contains type-forwards, which are auto-injected as part of our build process

Arrgghh i was wondering this myself. Is this documented as a "FYI" somewhere? Thanks for clarifying @mellinoe .

**Comment by mellinoe** [comment] 2017-05-17 22:24
@garfbradaz We have some brief explanation of what facade assemblies are [here](https://github.com/dotnet/corefx/blob/0723e486ba880be7bce85723b7834d2d60fd2741/Documentation/coding-guidelines/project-guidelines.md#facades). If you look at a project file and see [this property](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks/src/System.Threading.Tasks.csproj#L7), it means the assembly will be a facade. It may be either a "full facade" or a "partial facade" depending on whether the project also defines source files to include (despite the fact that the property is called "IsPartialFacadeAssembly"). If there are no source files (like System.Threading.Tasks), then that means it is a "full facade".

**Comment by joperezr** [comment] 2017-05-17 22:28
I'm not sure if its documented, but take a look at [this line](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks/src/System.Threading.Tasks.csproj#L7), what that means is that if there is a type in the contract(ref project) and it wasn't compiled in the sources, then a type forward will be added to the assembly that has the implementation.

**Comment by weshaggard** [comment] 2017-05-18 16:39
@vitek-karas if you run a build.cmd at least once from the root (which is documented https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md) does working in VS Code work better?

**Comment by karelz** [comment] 2017-05-18 17:13
Why do we need the build from root as prereq? ... the problem is that people rarely read docs ahead of time. IMO things should just work if at all possible.

Can SLN do the build from root on user's behalf? Or at minimum, can the SLN warn user "this is what you have to do"?

cc @FransBouma as he worked in VS recently as well.

**Comment by vitek-karas** [comment] 2017-05-18 17:51
I have to apologize as it does actually work.

What happened is that I did run build, but some time ago, and then I pulled new sources and it broke. This is non-obvious as the behavior will be as described above, but I guess there's not much we can do about this.

So I did a build today, which first hung in init (several times, no CPU usage at all), then it passed the init stages but failed on missing files and such. So finally somebody said to delete the packages and tools folder after which build finally worked. And now both VS Code and full VS seem to be working well when the right solution is opened.

One more comment: Apparently if the packages folder contains lot of older packages (and we don't clean this up during build in any way as far as I can tell), the init stages of the build.cmd can take really long time - I've seen the dotnet.exe spend more than 10 minutes fully using one core on the box. This feels rather excessive.

**Comment by weshaggard** [comment] 2017-05-18 17:55
>Why do we need the build from root as prereq? 

Because we have to bootstrap our tools and setup our targeting packs to we know what to build. 

>Can SLN do the build from root on user's behalf? 

Unfortunately no it cannot because VS fails to load the projects if it doesn't have the necessary imports. 

>Or at minimum, can the SLN warn user "this is what you have to do"?

We did have this at one point I will look to see if there is anyway to have this work at least.

**Comment by mellinoe** [comment] 2017-05-18 18:01
> One more comment: Apparently if the packages folder contains lot of older packages (and we don't clean this up during build in any way as far as I can tell), the init stages of the build.cmd can take really long time - I've seen the dotnet.exe spend more than 10 minutes fully using one core on the box. This feels rather excessive.

That's interesting. So you're saying that it was faster after the folder was totally empty? It sounds like nuget might be taking a really long time searching through the existing files to determine if a package already exists, or needs to be downloaded again. It's kind of ironic that it ends up taking longer than just downloading everything from scratch... I wonder if there is anything we can do there, or at least detect the situation and either 1) give a warning or 2) clear out the folder ourselves.

Obviously this isn't the "ideal workflow", but generally speaking if I pull down a large set of changes, or switch to a very different branch, I will just run a `git clean -xdf` on my repo. A full build of the repo (excluding running tests) should not take a very long time (~5-10 minutes depending on your machine), so it's often better to just start with that.

**Comment by vitek-karas** [comment] 2017-05-18 18:03
After I deleted the packages the init stage (including downloading everything) took cca 1 minute. Before it was like 10-15 minutes.

**Comment by weshaggard** [comment] 2017-05-18 18:42
I just did a clean on my repo and opened up VS and I see the following error:
`The tools directory [D:\git\corefx\Tools/] does not exist. Please run init-tools.cmd in your enlistment to ensure the tools are installed before attempting to build an individual project`	

So that helps however if I just run init-tools.cmd and try building in VS again then I get other errors about the refs not resolving so it is still needs some work. We have issue https://github.com/dotnet/corefx/issues/15121 on our backlog to improve these error conditions.

**Closed by weshaggard** 2017-05-18 18:42 UTC
Labels: area-Infrastructure, bug
