### ISSUE TITLE
Build corefx from build.cmd fails

### ISSUE THREAD

**Issue by Simon-IT** [dotnet/corefx#41441] opened 2019-09-30 08:36 UTC
Visual Studio Community 2019  16.4.0 Preview 1.0
Windows 10 1903 build SO 18362.387
NET Core 3.0.100
CMake 3.14.5

After has been pulling the latest comimts the build procedure fails with these two errors:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB8065: Custom build for item "D:\Sources\NetFoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\CMakeFiles\af7b5fb01ed3438277a908fb1341432f\INSTALL_force.rule" succeeded, but specified output "d:\sources\netfoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [D:\Sources\NetFoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\install.vcxproj] [D:\Sources\NetFoundation\dotnet\corefx\src\Native\build-native.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB8065: Custom build for item "D:\Sources\NetFoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\CMakeFiles\af7b5fb01ed3438277a908fb1341432f\INSTALL_force.rule" succeeded, but specified output "d:\sources\netfoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [D:\Sources\NetFoundation\dotnet\corefx\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\install.vcxproj] [D:\Sources\NetFoundation\dotnet\corefx\src\Native\build-native.proj]
```
`git clean -xdf` has no effects

**Comment by davidsh** [comment] 2019-09-30 17:29
I was able to sync the latest 'master' branch and rebuild fine.

I have cmake version 3.11.4.

**Comment by scalablecory** [comment] 2019-09-30 17:32
Closing as duplicate of https://github.com/dotnet/corefx/issues/41077

This is a cmake bug that has been fixed for CMake 3.15. We are waiting for them to make a new release.

**Closed by scalablecory** 2019-09-30 17:32 UTC
Labels: area-Infrastructure

**Comment by Simon-IT** [comment] 2019-10-01 10:38
The issue remains for CMake 3.15.3.
@davidsh What VS version have you ?

**Comment by davidsh** [comment] 2019-10-01 16:56
>@davidsh What VS version have you ?

![image](https://user-images.githubusercontent.com/7684835/65983071-95d7f780-e431-11e9-9bd8-968cceb6156b.png)

>The issue remains for CMake 3.15.3.

If you're still having the problem with that version of CMake, then you should comment/re-open issue #41077.
