### ISSUE TITLE
HttpWebRequest create many connections in windows

### ISSUE THREAD

**Issue by itn3000** [dotnet/corefx#26373] opened 2018-01-17 00:20 UTC
Steps to reproduce
------------------

1. run http service in localhost with port 80
2. run the following code with TargetFramework=netcoreapp2.0
3. view network connection stat(in windows, `netstat -n`)

```csharp
using System;

namespace httpwebrequesttest
{
    using System.Net;
    class Program
    {
        static void Main(string[] args)
        {
            for(int i = 0;i<1000;i++)
            {
                var client = WebRequest.CreateHttp("http://localhost:80");
                using(var res = client.GetResponse())
                {

                }
                Console.WriteLine($"{i}");
            }
            Console.WriteLine($"press enter then exit");
            Console.ReadLine();
        }
    }
}
```

Expected behavior
-----------------

there is only one socket directed to localhost:80 like this(state is "ESTABLISHED" or "TIME_WAIT"):
```
  TCP         [::1]:63063            [::1]:80               ESTABLISHED
```

Actual behavior
---------------

there are one thousand "TIME_WAIT" or "ESTABLISHED" connections

Environment data
-----------------

here is my `dotnet info` output

```
.NET コマンド ライン ツール (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

Notes
-----------------

when TargetFramework=net461, It does not create many connections.
And when run in linux, It does not create many connections.

**Comment by itn3000** [comment] 2018-01-17 00:24
I think this is because creating HttpClient on every request?
https://github.com/dotnet/corefx/blob/cf191eb22e762ad740ae8a91a3fdb948d29a7b0c/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1111

**Comment by davidsh** [comment] 2018-01-17 01:00
Yes, this issue is tracked here already.
https://github.com/dotnet/corefx/issues/15460

**Comment by itn3000** [comment] 2018-01-17 01:08
thank you for informing, I will track #15460

**Comment by davidsh** [comment] 2018-01-17 01:09
Duplicate of #15460.

**Closed by davidsh** 2018-01-17 01:09 UTC
Labels: area-System.Net

**Comment by karelz** [comment] 2018-01-17 01:26
Also note that HttpWebRequest API is compat-only API - in general we recommend developers to move to `HttpClient` if they can to get performance wins and modern protocol support.
See details here: https://github.com/dotnet/platform-compat/blob/master/docs/DE0003.md
