### ISSUE TITLE
[Question] System.Collections.Immutable.ImmutableDictionary reorders

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefx#23317] opened 2017-08-17 01:16 UTC
This is probably by design to help with the immutable types, but why does an ImmutableDictionary reorder keys after adding?  For example compared to regular Dictionary:

```c#
ImmutableDictionary<string, bool>.Builder isdBuilder = ImmutableDictionary.CreateBuilder<string, bool>();
            isdBuilder.Add("one", false);
            isdBuilder.Add("two", true);
            isdBuilder.Add("three", false);
            isdBuilder.Add("four", false);
            ImmutableDictionary<string, bool> isd = isdBuilder.ToImmutableDictionary();
```
**Not Expected**: The order by keys are "two", "one", "three", "four"

```c#
Dictionary<string, bool> dic = new Dictionary<string, bool>();
            dic.Add("one", false);
            dic.Add("two", true);
            dic.Add("three", false);
            dic.Add("four", false);
```
**As Expected**: "one", "two", "three", "four"

I've tried the ImmutableSortedDictionary and appears to reorder by key.  I would like to have it stay in the same order as they are added.

Is there a way of making the ImmutableDictionary store KeyValuePairs in a specific order?

[EDIT] Add C# syntax highlight by @karelz

**Comment by danmosemsft** [comment] 2017-08-17 02:53
@AArnott

**Comment by danmosemsft** [comment] 2017-08-17 02:54
Actually I guess I can answer tihs one. Dictionary<K,V> does not preserve ordering either. You are just getting lucky with the keys you picked.

**Comment by sharwell** [comment] 2017-08-17 04:38
It sounds like you are looking for the equivalent of Java's LinkedHashMap, but in .NET and as an immutable collection. Currently no such collection exists, but you could create a new collection that maintains both a dictionary and a list as the backing store.

**Comment by karelz** [comment] 2017-08-17 21:57
Closing as it seems to be answered.

**Closed by karelz** 2017-08-17 21:57 UTC
Labels: area-System.Collections, question

**Comment by AArnott** [comment] 2017-08-17 22:28
Yes, @danmosemsft there is an `ImmutableSortedDictionary<K,V>` class in this library. 
And yes, dictionaries (immutable or otherwise) are generally not _ordered_ collections. So this is by design.

**Comment by shaggygi** [comment] 2017-08-17 22:49
Thanks for the clarification.

**Comment by jnm2** [comment] 2017-08-18 00:31
KeyedCollection indexes both by insertion order and key, contains both list and dictionary, no?

**Comment by Clockwork-Muse** [comment] 2017-08-19 02:33
@jnm2 - yeah, but there isn't an immutable version.

I've started to see `List` and anything similar with an index key as essentially another dictionary (indeed, in some cases this is exactly how it's used: "the item at index 1 is blah, ignore index 2, the item at index 3 is blah2....").
Coming from a more database perspective, I find it interesting that essentially guaranteeing insert order is actually the easier thing to do (where it's almost always irrelevant).
