### ISSUE TITLE
[RC1 blocker] Access violation while running System.Collections.Tests in CI on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4076] opened 2015-10-22 16:30 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3747/consoleFull
```
08:32:50 Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
08:32:50    at System.Collections.Generic.HashSet`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
08:32:50    at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection, IEqualityComparer`1 comparer)
08:32:50    at Tests.HashSet_HashSetTestSupport.HashSetTestSupport`1.<>c__DisplayClass2.<VerifyHashSet>b__1(T item)
08:32:50    at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
08:32:50    at Tests.HashSet_HashSetTestSupport.HashSetTestSupport`1.VerifyHashSet(HashSet`1 set, ICollection`1 contents, IEqualityComparer`1 comparerToUse)
08:32:50    at Tests.HashSet_TrimExcessTests.TrimExcess_Test6()
08:32:50    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
08:32:50    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
08:32:50    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
08:32:50    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
08:32:50    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
08:32:50    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
08:32:50    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
08:32:50    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
08:32:50    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
08:32:50    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
08:32:50    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
08:32:50    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestClassRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
08:32:50    at System.Threading.Tasks.Task`1.InnerInvoke()
08:32:50    at System.Threading.Tasks.Task.Execute()
08:32:50    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:32:50    --- End of inner exception stack trace ---
08:32:50    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
08:32:50    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
08:32:50    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
08:32:50    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
08:32:50    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
08:32:50    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
08:32:50    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
08:32:50    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
08:32:50    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
08:32:50    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
08:32:50    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
08:32:50    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
08:32:50    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestClassRunner`1.RunAsync()
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
08:32:50    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
08:32:50    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
08:32:50    at System.Threading.Tasks.Task`1.InnerInvoke()
08:32:50    at System.Threading.Tasks.Task.Execute()
08:32:50    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:32:50    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
08:32:50    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
08:32:50    at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
08:32:50    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:32:50    at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
08:32:50    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
08:32:50    at System.Threading.Tasks.Task.Execute()
08:32:50    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:32:50    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
08:32:50    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
08:32:50    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
08:32:50 ./run-test.sh: line 130: 32445 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
08:32:50 One or more tests failed while running tests from 'System.Collections.Tests'.  Exit code 134.
```

**Comment by joshfree** [comment] 2015-10-23 20:46
we're also seeing an AV in SqlClient (EF tests) -- #4110

**Comment by ellismg** [comment] 2015-10-30 00:21
I've been unable to reproduce this locally and I don't think we've seen it in CI recently.  I'm wondering if it was addressed by one of the recent runtime or JIT fixes.  Closing for now.

**Closed by ellismg** 2015-10-30 00:21 UTC
Labels: bug, System.Collections
