### ISSUE TITLE
Add Base64 conversion APIs that support UTF-8 for Span<T> 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#24568] opened 2017-10-11 03:33 UTC
## Updated API Proposal
Details https://github.com/dotnet/corefx/issues/24568#issuecomment-338833370
```C#
// System.Memory.dll
namespace System.Buffers.Text {
    public static class Base64 {
        public static OperationStatus EncodeToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus EncodeToUtf8InPlace(Span<byte> buffer, int dataLength, out int written);
        public static int GetMaxEncodedToUtf8Length(int length);
        public static OperationStatus DecodeFromUtf8(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus DecodeFromUtf8InPlace(Span<byte> buffer, int dataLength, out int written);
        public static int GetMaxDecodedFromUtf8Length(int length);
    }
}
```
<details> 
  <summary>Details and Usage from previously proposed API</summary>

## Rationale
These API allow for encoding of a Span\<byte\> into UTF-8 Base64 encoded span (binary to text operation) and decoding of a UTF-8 Base64 encoded span to Span\<byte\> (text to binary operation). They will be used by SignalR (for example [here](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/Infrastructure/DefaultProtectedData.cs#L22), [here](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/Infrastructure/DataProtectionProviderProtectedData.cs#L40), and [here](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Encoders/Base64Encoder.cs)).

A prototype of the API is available in corefxlab: 
https://github.com/dotnet/corefxlab/tree/master/src/System.Binary.Base64

Part of https://github.com/dotnet/corefx/issues/24174

Previous review: https://github.com/dotnet/apireviews/tree/master/2017/06-16-System.Text.Buffers

## Usage

For valid input data:
```C#
Span<byte> input; // input buffer to be encoded containing binary data
Span<byte> encodedBytes = new byte[Base64.BytesToUtf8Length(input.Length)];
OperationStatus status = Base64.BytesToUtf8(input, encodedBytes, out int consumed, out int encodedBytesCount);
// status == OperationStatus.Done
// encodedBytes.Length == encodedBytesCount
// consumed == input.Length
```
```C#
Span<byte> input; // input buffer to be decoded containing textual data
Span<byte> decodedBytes = new byte[Base64.Utf8ToBytesLength(input.Length)];
OperationStatus status = Base64.Utf8ToBytes(input, decodedBytes, out int consumed, out int decodedByteCount);
// status == OperationStatus.Done
// decodedBytes.Length >= decodedByteCount
// consumed == input.Length
```

Using these new APIs, we can take the following code snippet (from [here](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Common/Internal/Encoders/Base64Encoder.cs)):
```C#
public byte[] Decode(byte[] payload)
{
    var buffer = new ReadOnlyBuffer<byte>(payload);
    LengthPrefixedTextMessageParser.TryParseMessage(ref buffer, out var message);

    return Convert.FromBase64String(Encoding.UTF8.GetString(message.ToArray()));
}
```
And re-write it as follows (if we want to keep the input/output as byte arrays):
```C#
public byte[] Decode(byte[] payload)
{
    var buffer = new ReadOnlyBuffer<byte>(payload);
    LengthPrefixedTextMessageParser.TryParseMessage(ref buffer, out var message);
    
    // assume message.Span is UTF-8 encoded (for instance, using the upcoming UTF8 encoder APIs)
    Span<byte> bytes = new byte[Utf8ToBytesLength(message.Span.Length)];
    Base64.Utf8ToBytes(message.Span, bytes, out int consumed, out int written);
    return bytes.Slice(0, written).ToArray();
}
```
For potentially invalid (or incomplete) input, the user can check the returned status. For example, change the above code as follows:
```C#
    Span<byte> bytes = new byte[Utf8ToBytesLength(message.Span.Length)];
    OperationStatus status = Base64.Utf8ToBytes(message.Span, bytes, out int consumed, out int written);
    return status == OperationStatus.Done ? bytes.Slice(0, written).ToArray() : <user-defined behavior>;
}
```

## Proposed API
```C#
// System.Memory.dll
namespace System.Buffers.Text {
    public static class Base64 {
        public static OperationStatus BytesToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus BytesToUtf8InPlace(Span<byte> buffer, int bytesLength, out int written, bool isFinalBlock = true);
        public static int BytesToUtf8Length(int bytesLength);
       // public static int BytesToUtf8Length(ReadOnlySpan<byte> utf8, bool isFinalBlock);
        public static OperationStatus Utf8ToBytes(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus Utf8ToBytesInPlace(Span<byte> buffer, out int consumed, out int written, bool isFinalBlock = true);
        public static int Utf8ToBytesLength(int utf8Length);
        // public static int Utf8ToBytesLength(ReadOnlySpan<byte> utf8, bool isFinalBlock);
    }
}
```
**Note:** OperationStatus is the same as TransformationStatus (https://github.com/dotnet/corefx/issues/22412).

### 1
For computing length, another approach could be to add the following overloads, which give the "actual", precise length:
```C#
public static int BytesToUtf8Length(ReadOnlySpan<byte> utf8, bool isFinalBlock);
public static int Utf8ToBytesLength(ReadOnlySpan<byte> utf8, bool isFinalBlock);
```

The behavior of the currently proposed APIs is similar to the ones listed above for when isFinalBlock is true. For example:
```C#
// input = ABC DEF G
BytesToUtf8Length(input, false); // returns 8
BytesToUtf8Length(input, true); // returns 12 == BytesToUtf8Length(input.Length)
```

### 2
To extend the functionality of the currently proposed APIs to include new line support (for example, for the MIME variant of Base64), we could add the following overloads that take a ParsedFormat parameter:

```C#
public static OperationStatus BytesToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, ParsedFormat format, bool isFinalBlock = true);
public static OperationStatus BytesToUtf8InPlace(Span<byte> buffer, int bytesLength, out int written, ParsedFormat format, bool isFinalBlock = true);
public static OperationStatus Utf8ToBytes(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, ParsedFormat format, bool isFinalBlock = true);
public static OperationStatus Utf8ToBytesInPlace(Span<byte> buffer, out int consumed, out int written, ParsedFormat format, bool isFinalBlock = true);
public static int BytesToUtf8Length(int bytesLength, ParsedFormat format);
public static int Utf8ToBytesLength(int utf8Length, ParsedFormat format);
```

Which creates a dependency on ParsedFormat (https://github.com/dotnet/corefx/issues/24607)

The usage would then look like:
```C#
ParsedFormat format = new ParsedFormat('N', 76);
int requiredSize = Base64.BytesToUtf8Length(source.Length, format);
Span<byte> encodedBytes = new byte[outputSize];
Base64.BytesToUtf8(source, encodedBytes, out int consumed, out int written, format);
```

### 3
Should we rename `Utf8ToBytesLength(int utf8Length)` to `Utf8ToBytesMaxLength` to indicate it isn't the precise length (but rather could be a few bytes larger)? Same with `BytesToUtf8Length(int bytesLength)`?

</details>

cc @KrzysztofCwalina, @GrabYourPitchforks, @davidfowl, @terrajobst, @karelz

**Comment by benaadams** [comment] 2017-10-17 18:58
Is it validating the Utf8? If I wanted to convert binary bytes to Base64 it would be same function `Utf8ToBytes`

So is namespace `Text` correct? should there be a more general `Base64` type or will there be multiple in different namespaces? (e.g. for binary)

**Comment by terrajobst** [comment] 2017-10-17 19:01
This needs more work. Raw notes:

### Rough shapes of API

```C#
// System.Memory.dll
namespace System.Buffers.Text {
    public static class Base64 {
        public static OperationStatus EncodeToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus EncodeToUtf8InPlace(Span<byte> buffer, int bytesLength, out int written, bool isFinalBlock = true);
        public static int GetMaxEncodedUtf8Length(int length);
        public static OperationStatus DecodeFromUtf8(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus DecodeFromUtf8InPlace(Span<byte> buffer, out int consumed, out int written, bool isFinalBlock = true);
        public static int GetMaxDecodedBytesLength(int length);
    }
}
```

### isFinalBlock

We need it, using a more general term (as opposed to usePadding) avoids the caller having to understand the format/specification.

### OperationStatus/TransformationStatus

It would brought that we may not need the enum at all.

Ahson/Levi: Look at the general pattern and decide whether the API is needed. In the past we concluded that the code becomes too convoluted and the conditions are easy to get wrong.

### Length

We should not take a the input, only the size. We should also not take the `isFinalBlock`. Basically, the contract is "give an upper bound".

**Comment by benaadams** [comment] 2017-10-17 19:03
`int GetMaxDecodedBytesLength(int length)` is ambiguous if you add `Utf16`, `Ascii` etc

**Comment by stephentoub** [comment] 2017-10-17 19:21
> int GetMaxDecodedBytesLength(int length) is ambiguous if you add Utf16, Ascii etc?

I agree. I believe the anti-ambiguous argument is that it wouldn't be ambiguous because regardless of whether the encoding is UTF8, UTF16, or ASCII, the Base64-encoded output would always result in the same number of code points, e.g. "c3RlcGhlbg==" as UTF8 would be 12 bytes and as UTF16 would be 12 chars.  The problem with that is an assumption that the UTF16 data is represented as 16-bit units; if the developer has a `Span<byte>` containing the UTF16 data instead of a `Span<char>` containing the UTF16 data, span.Length would produce an incorrect value as input to this method.

The easy solution here is to just have a GetMaxUTF8DecodedLength(int bytesLength), GetMaxUTF16DecodedLength(int charsLength), etc., such that it's spelled out and very clear what the units are in question.  This also then keeps things consistent, with each of UTF8, UTF16, ASCII, and whatever else having a "to" method", a "from" method, a count method in each direction, rather than trying to share methods across them.  Trying to share might be feasible with some assumptions, but IMHO it's confusing and doesn't save anything meaningful.

**Comment by GrabYourPitchforks** [comment] 2017-10-17 20:35
If you want to allow reading a byte stream directly from disk / network and passing it to the base64 APIs, then yes, you'll need to add `GetMaxUtf16DecodedLength`. In fact, you'll need to go even further and add specifically `ToUtf16BigEndian`, `ToUtf16LittleEndian`, `FromUtf16BigEndian`, and `FromUtf16LittleEndian`. And all of their in-place equivalents.

However, I am strongly opposed to using a single type `Span<byte>` to represent all four of: (a) truly binary data, (b) binary data that might be UTF8 textual data, (c) binary data that might be UTF16BE textual data, and (d) binary data that might be UTF16LE textual data. This makes the API surface difficult to use, it prohibits the type system from producing compiler errors when the developer accidentally does the wrong thing, and it means that the developer needs to keep in mind "this is a `Span<byte>` that has _xyz_ meaning" every place they use the type in their code.

I'm fleshing out some proposals for addressing this particular concern. However, we shouldn't let it rathole the base64 API discussion. If the consensus is that you need to read byte streams directly from network / disk and that those streams could represent UTF16BE / UTF16LE data, go ahead and add the necessary APIs for now.

**Comment by benaadams** [comment] 2017-10-17 22:04
>  I am strongly opposed to using a single type Span<byte> to represent all...

I'd assume `EncodeFromUtf8` is unchecked and `DecodeToUtf8`  is checked (though are named wrong as `Base64.EncodeToUtf8` and `Base64.DecodeFromUtf8`)

So EncodeUtf8 would just be a pass through on a binary version?

I'm not suggesting they should be merged to one method; the typed distinction is important - However; is `.Text` the right namespace?

Where would the `Base64` binary version live? (i.e. are their multiple `Base64` classes?)
 
```csharp
namespace System.Buffers.Text {
    public static class Base64 {
        EncodeToBinary(ReadOnlySpan<byte> bytes, Span<byte> binary, ...
        DecodeFromBinary(ReadOnlySpan<byte> utf8, Span<byte> binary, ...
    }
}
```

**Comment by karelz** [comment] 2017-10-17 23:20
FYI: The API review discussion was recorded - see https://youtu.be/BEBq3__WfDc?t=3306 (60 min duration)

**Comment by ahsonkhan** [comment] 2017-10-18 00:55
> I'd assume `EncodeFromUtf8` is unchecked and `DecodeToUtf8`  is checked (though are named wrong as `Base64.EncodeToUtf8` and `Base64.DecodeFromUtf8` above)
So EncodeFromUtf8 would just be a pass through on a binary version?
Where would the `Base64` binary version live?

I don't understand what you mean by checked/unchecked. The APIs in this proposal convert binary data to UTF-8 text (they are the Base64 binary version). EncodeToUtf8 goes from bytes to utf8 text and DecodeFromUtf8 goes from utf8 text to bytes.

---

- The "InPlace APIs" now return a bool instead of OperationStatus
- Renamed the get length methods:
   - GetMaxEncodedUtf8Length -> GetMaxEncodedToUtf8Length
   - GetMaxDecodedBytesLength -> GetMaxDecodedFromUtf8Length
- There is no real downside of having the APIs return the OperationStatus enum instead of them being TryX methods that return bool. The OperationStatus enables the caller of these primitive operations to handle the cases for DestinationTooSmall or NeedMoreSourceData differently, if they choose to, while hiding the complexity of detecting those states based on the out parameters. We could additionally implement the TryX APIs that return bool (for convenient, "one-shot" methods), on top of the API that return the enum, but not the other way around. The conditions to detect the states correctly also end up requiring operation specific information/constants other than just the out parameters which means the API must return the status. The only reason to return a bool instead of an enum is if we are certain that no user will ever care about distinguishing between some of the return status and choose different code paths based on the enum.

For example, for Base64, here are the different status and how they could be derived if the method returned a bool:

STATUS | Condition to detect status
-- | --
Done | true OR (source.Length ==   bytesConsumed)
DestinationTooSmall | false AND (destination.Length -   written < 3)
NeedMoreSourceData | false AND (sourceSpan.Length -   bytesConsumed < 4)
InvalidData | false AND (sourceSpan.Length -   bytesConsumed >= 4)

**Based on the above adjustments, here is the proposed shape of the API:**
```C#
// System.Memory.dll
namespace System.Buffers.Text {
    public static class Base64 {
        public static OperationStatus EncodeToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, bool isFinalBlock = true);
        public static bool EncodeToUtf8InPlace(Span<byte> buffer, int bytesLength, out int written, bool isFinalBlock = true);
        public static int GetMaxEncodedToUtf8Length(int length);
        public static OperationStatus DecodeFromUtf8(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
        public static bool DecodeFromUtf8InPlace(Span<byte> buffer, out int consumed, out int written, bool isFinalBlock = true);
        public static int GetMaxDecodedFromUtf8Length(int length);
    }
}
```

@dotnet/corefxlab-contrib

**Comment by benaadams** [comment] 2017-10-18 04:23
> I don't understand what you mean by checked/unchecked. 

Whether it will return `InvalidData` e.g. 
Is UTF8 -> Base64 check if its valid utf8 or just outputting it (unchecked). 
Base64 ->UTF8 obv is checking it is valid Base64, might also be checking for valid utf8 (checked)

**Comment by GrabYourPitchforks** [comment] 2017-10-18 04:32
I think there was a miscommunication. The encode routine goes from binary data to textual base64 representation, and the decode method does the opposite. There's no "is this a valid textual representation of base64-encoded data?" API under consideration right now.

**Comment by benaadams** [comment] 2017-10-18 04:48
So they are exactly the same functions as a hypothetical
```csharp
    public static class Base64 {
        DecodeToBinary(ReadOnlySpan<byte> bytes, Span<byte> binary, ...
        EncodeFromBinary(ReadOnlySpan<byte> binary, Span<byte> bytes, ...
    }
```
e.g. If the two methods existed the Utf8 Encode/Decode pair could be implemented as
```csharp
DecodeToUtf8(...) => DecodeToBinary(bytes, utf8,...
EncodeFromUtf8(...) => EncodeFromBinary(utf8, bytes,,...
```

**Comment by benaadams** [comment] 2017-10-18 04:49
On api; isn't Base64 called "Base64 Encoding"?

So isn't Encode utf8 -> Base64 and Decode Base64 -> utf8?

**Comment by benaadams** [comment] 2017-10-18 04:50
On api; isn't Base64 called "Base64 Encoding"?

So isn't Encode utf8 -> Base64 and Decode Base64 -> utf8?

Its also Utf8 encoding, so maybe that doesn't help

**Comment by GrabYourPitchforks** [comment] 2017-10-18 16:06
@ahsonkhan Regarding the OperationStatus enum, can you describe exactly what each state means, what actions callers are expected to take when seeing each enum value, and the requirements on implementers re: how they’re supposed to set the out parameters for each case? The behavioral contract is part of the API so this has to be set in stone before commit.

**Comment by ahsonkhan** [comment] 2017-10-24 00:17
**Here is the updated API shape, ready for review:**

```C#
// System.Memory.dll
namespace System.Buffers.Text {
    public static class Base64 {
        public static OperationStatus EncodeToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus EncodeToUtf8InPlace(Span<byte> buffer, int dataLength, out int written);
        public static int GetMaxEncodedToUtf8Length(int length);
        public static OperationStatus DecodeFromUtf8(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
        public static OperationStatus DecodeFromUtf8InPlace(Span<byte> buffer, int dataLength, out int written);
        public static int GetMaxDecodedFromUtf8Length(int length);
    }
}
```

**Changes:**
- Rename argument for "InPlace" APIs from bytesLength to dataLength.
- The "InPlace" APIs do not need isFinalBlock since they are "one-shot" APIs and cannot be called with partially completed results in a loop. Either the entire buffer is available in the input or it fails. This is because there is no guarantee (especially with expanding transformations like Base64.Encode) that the data in input buffer that the user provided hasn't been trampled on. 
  - Given that they are "one-shot", also changing DecodeFromUtf8InPlace to take in an `int dataLength` rather than have an `out consumed` parameter similar to EncodeToUtf8InPlace, for consistency.
- The "InPlace" APIs return OperationStatus as originally stated.
  - This is because the OperationStatus is needed for the general purpose IBuffertransformation Transform API (which call these in-place methods). For example, [SpanWriter](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Experimental/System/Buffers/SpanWriter.cs#L30-L52). It is unnecessary for the primitives to return bool and then we map the bool values to the enum when we can return the enum directly.
  - Additionally, if we return false, the semantics of "false" changes depending on the transformation. An advantage of returning an enum is that the user code explicitly shows the conditions, which is more clear, imo. 

If returning bool, false could mean invalid data or buffer too small (for Base64, depending on the direction of the transformation):
```C#
            if (!Base64.DecodeFromUtf8InPlace(source, dataLength, out int written))
            {
                // invalid data
            }

            if (!Base64.EncodeToUtf8InPlace(source, dataLength, out int written))
            {
                // buffer too small
            }
```

If returning enum, that difference is made clear, essentially making the user code self-documenting:
```C#
            if (Base64.DecodeFromUtf8InPlace(source, dataLength, out int written) == OperationStatus.InvalidData)
            {
            }

            if (Base64.EncodeToUtf8InPlace(source, dataLength, out int written) == OperationStatus.DestinationTooSmall)
            {
            }

```
---
**OperationStatus:**
- Done - the entire input buffer has been consumed, i.e. `consumed == input.Length`, the operation is complete. No additional calls required. If you want the output precisely, slice the output buffer from 0 to written to remove the slack.
- DestinationTooSmall - the input is partially consumed, up to what could be fit into the destination buffer, i.e. `output.Length - written < *operation specific constant*` and `consumed < input.Length`
  - The user can slice the input on consumed, enlarge the output buffer (slicing by what has been written), and re-call the API.
- NeedMoreData - the input is partially consumed, up to the last valid chunk of the input that could be consumed, i.e. `input.Length - consumed < *operation specific constant*` along with `written < output.Length`
  - The user can stitch the remaining unprocessed input with more data, slice the output on written and re-call the API. If there is no more data, throw or try to fail gracefully (similar to InvalidData).
- InvalidData - the input is partially consumed, up to the last valid byte, i.e. `consumed < input.Length` and `consumed == *index of first confirmed invalid byte*` (guarantees there is no possibility that more data yet to be processed would make the byte valid, in which case it would be NeedMoreData)  along with `written < output.Length`
  - If some recovery heuristic is applicable, the user can slice the input on consumed and output on written and try to recover by replacing the bytes in the input buffer at the returned index, with possible data shifting, and call the API again. Otherwise throw or try to fail gracefully.

**Comment by benaadams** [comment] 2017-10-24 07:13
Still think the functions are named reveresed as they are currently 
```
Text, Encoded in Utf8 <-> Text, Encoded in Utf8, Encoded in Base64
           ----- DecodeFromUtf8 ----->
           <----  EncodeToUtf8  ------
```

**Comment by GrabYourPitchforks** [comment] 2017-10-24 07:22
@benaadams The input to Base64Encode is not UTF8 text. The input is a binary blob. The binary data is encoded into an ASCII-friendly representation, hence encode is binary-to-text.

(As an aside, this thread provides strong evidence for the argument I was making earlier that UTF8 text and binary data should be represented as two different types in the type system.)

**Comment by benaadams** [comment] 2017-10-24 07:49
> The input to Base64Encode is not UTF8 text. The input is a binary blob. The binary data is encoded into an ASCII-friendly representation, hence encode is binary (original data) to text (transformed data).

The methods are:
```csharp
Base64.DecodeFromUtf8("Hello", bytes, ...); // bytes now == "SGVsbG8="
Base64.EncodeToUtf8("SGVsbG8=", utf8, ...); // utf8 now == "Hello"
```
This is giving primacy to Base64 as the representation; whereas its the temporary; it wraps the otherway

Reversing the name
```csharp
Base64.EncodeFromUtf8("Hello", bytes, ...); // bytes now == "SGVsbG8="
Base64.DecodeToUtf8("SGVsbG8=", utf8, ...); // utf8 now == "Hello"
```
Gives primacy to Utf8 as the representation and suggests Base64 is the temporary

Re-framing it in a different context as written `text<->http<->tcp<->ip` would be written as:

Currently
```csharp
// Put text on wire
Http.DecodeFromUtf8("Hello", bytes, ...);
TCP.DecodeFromHttp(...);
IP.DecodeFromTCP(...);

// Get text from wire
IP.EncodeToTCP(...);
TCP.EncodeToHttp(...);
Http.EncodeToUtf8(bytes, utf8, ...); // Now have "Hello"
```
I'm suggesting it would be better as
```csharp
// Put text on wire
Http.EncodeFromUtf8("Hello", bytes, ...);
TCP.EncodeFromHttp(...);
IP.EncodeFromTCP(...);

// Get text from wire
IP.DecodeToTCP(...);
TCP.DecodeToHttp(...);
Http.DecodeToUtf8(bytes, utf8, ...); // Now have "Hello"
```

**Comment by GrabYourPitchforks** [comment] 2017-10-24 15:45
@benaadams you've reversed your first two examples. The method which takes [ 48 65 6C 6C 6F ] and returns "SGVsbG8=" is EncodeToUtf8, _not_ DecodeFromUtf8. DecodeFromUtf8 takes "SGVsbG8=" and returns [ 48 65 6C 6C 6F ]. This means that binary representation is the original representation, and UTF8 / ASCII is the temporary.

**Comment by benaadams** [comment] 2017-10-24 16:17
> DecodeFromUtf8 takes "SGVsbG8=" and returns [ 48 65 6C 6C 6F ]

Its the other way in the api 
```
DecodeFromUtf8(ReadOnlySpan<byte> utf8, Span<byte> bytes
```
`utf8` is readonly; and `bytes` is writable

**Comment by benaadams** [comment] 2017-10-24 16:42
Ohhh... ok have been getting this wrong

I assumed it was doing the conversion Utf8 <-> Base64 Ascii (e.g. like putting Utf8 in a cookie, as it isn't representable as 7-bit)

So if you wanted to put Utf8 in a cookie you'd do:
```
Span<byte> utf8CookieValue;
Span<byte> utf8EncodedCookieValue;
EncodeToUtf8(utf8CookieValue, utf8EncodedCookieValue, ...
```
To convert utf8 to utf8? Still seems a bit weird

**Comment by benaadams** [comment] 2017-10-24 16:43
`EncodeToAscii`?

**Comment by benaadams** [comment] 2017-10-24 16:45
```csharp
static OperationStatus EncodeToBase64(ReadOnlySpan<byte> bytes, Span<byte> base64, out int consumed, out int written, bool isFinalBlock = true);
public static OperationStatus DecodeFromBase64(ReadOnlySpan<byte> base64, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
```
Would be more clear

**Comment by benaadams** [comment] 2017-10-24 16:48
```csharp
static OperationStatus EncodeToBase64(ReadOnlySpan<byte> bytes, Span<byte> base64, out int consumed, out int written, bool isFinalBlock = true);
static OperationStatus DecodeFromBase64(ReadOnlySpan<byte> base64, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
```
or
```csharp
class Base64
{
    static OperationStatus EncodeTo(ReadOnlySpan<byte> bytes, Span<byte> base64, out int consumed, out int written, bool isFinalBlock = true);
    static OperationStatus DecodeFrom(ReadOnlySpan<byte> base64, Span<byte> bytes, out int consumed, out int written, bool isFinalBlock = true);
}
```
Would be more clear

**Comment by bartonjs** [comment] 2017-10-24 16:53
@benaadams I think the UTF-8-ness is the representation of the Base64 character string.  So it's really `EncodeToBase64Utf8`, but since it's on a `Base64` class the redundant noun disappears.

So `new byte[] { 1, 2, 3, 4, 5 }` => (logical) "AQIDBAU=" => (UTF-8 or ASCII encoding) `41 51 49 44 42 41 55 3D`.

At least, that's what I'm assuming happens.

**Comment by benaadams** [comment] 2017-10-24 16:58
Yeah; but the problem is utf8 isn't a representable as base64; so if you have utf8 to then need to convert it with a method called `EncodeToUtf8`

Since its a `Span<byte>` field call it `base64` instead of `utf8` and drop `Utf8` from the method name.

`Utf8` is a spurious element (and confused me)

**Comment by GrabYourPitchforks** [comment] 2017-10-24 17:06
@ahsonkhan You mentioned that `InvalidData` means the input has been partially consumed up to the first invalid byte. Is this a requirement we're willing to place on _all_ transform implementations? Imagine a function like `Base64Decode`, which can tell ahead of time if some input has no hope at all of being valid (e.g., its length is not an even multiple of 4). Are we forcing all implementations to attempt to operate on the data anyway just so that they can return an index to the caller?

**Comment by ahsonkhan** [comment] 2017-10-24 17:32
> Is this a requirement we're willing to place on _all_ transform implementations? 

Yes. That is how our current implementation of the transformation behave and is necessary for fallback logic. However, I think this question about all transformation is more about the transformation interface ([IBufferOperation](https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/Transformation.cs)/etc.) rather than the specific primitives and we can finalize that when we bring that to review.

> Imagine a function like `Base64Decode`, which can tell ahead of time if some input has no hope at all of being valid (e.g., its length is not an even multiple of 4).

I wouldn't consider that as InvalidData since we the length does not imply that there are actual invalid bytes in the input. Not being a multiple of 4 just implies that we have incomplete data (need more data).

**Comment by GrabYourPitchforks** [comment] 2017-10-24 17:34
@ahsonkhan I meant "not a multiple of 4 bytes" _and_ "isFinalChunk = true". This is `InvalidData`, not `NeedsMoreData`, and there's no action the caller can take to recover. So why take the time to even bother processing what's clearly a corrupt input?

**Comment by terrajobst** [comment] 2017-10-24 19:01
Looks good as proposed. It seems @GrabYourPitchforks conceded that the enum is useful. We should, however, remove the `dataLength` parameter from `DecodeFromUtf8InPlace` -- it's not needed.

**Comment by karelz** [comment] 2017-10-24 20:18
FYI: The API review discussion was recorded - see https://youtu.be/OZnaGV2omvI?t=5258 (28 min duration)

**Closed** 2017-10-27 04:56 UTC
Labels: api-approved, area-System.Memory
