### ISSUE TITLE
WinHttpHandler on < Win8.1 ignores AutomaticDecompression settings

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#29747] opened 2018-05-16 21:03 UTC
On Win8.1 and later, WinHTTP supports the WINHTTP_OPTION_DECOMPRESSION option, which allows it to be told what compression schemes to automatically decompress, and on 8.1 or later, WinHttpHandler uses that setting.  On < Win8.1, attempting to set that option will fail, and WinHttpHandler will fall back to doing its own decompression, using GZipStream and DeflateStream.  When it does this, however, it ends up ignoring the AutomaticDecompression option set on the handler:
https://github.com/dotnet/corefx/blob/30ab651fcb4354552bd4891619a0bdd81e0ebdbf/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseParser.cs#L78-L92
~so even if it was left as the default of None, WinHttpHandler will still automatically decompress the response encoded as deflate or gzip~ so if, for example AutomaticDecompression was set to Deflate, WinHttpHandler would still automatically decompress the response encoded as gzip.

**Comment by davidsh** [comment] 2018-05-16 22:14
I think this is a dupe of #26991

**Comment by stephentoub** [comment] 2018-05-16 23:13
It's related but different. That issue is about how if the option isn't supported by WinHTTP, WinHttpHandler didn't appropriately set the request headers. This issue highlights that if the option isn't supported by WinHTTP, the response is decompressed regardless of the AutomaticDecompression option chosen.

**Comment by davidsh** [comment] 2018-05-23 21:29
@stephentoub 
I looked into this issue.  Do you have a repro of this? Or was this issue opened due to code inspection?

Expanding on the code snippet you have above, there is a variable 'doManualDecompressionCheck' that is passed into this method.  And only if that variable is true, would the handler decompress any content.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseParser.cs#L68-L93

That variable is set in WinHttpHandler.  And is only true if 1) the AutomaticDecompressionOptions is not None, and 2) We're on a platform where WinHTTP can't do it automatically.

https://github.com/dotnet/corefx/blob/1f59cb91f9350732c747e6d60422c9c579e1dfed/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1052-L1080

**Comment by stephentoub** [comment] 2018-05-23 21:36
> Do you have a repro of this?

Yes, the tests in https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Decompression.cs (which after this issue and the others related to it, I just left as being SocketsHttpHandler-specific, such that they're not currently running for other handlers), and in particular:
https://github.com/dotnet/corefx/blob/1f59cb91f9350732c747e6d60422c9c579e1dfed/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Decompression.cs#L95

> That variable is set in WinHttpHandler. And is only true if 1) the AutomaticDecompressionOptions is not None, and 2) We're on a platform where WinHTTP can't do it automatically.

Right.   So on Win7 let's say you set AutomaticDecompression to DecompressionMethods.Deflate, so it's not None.  It'll then attempt to set the WINHTTP_OPTION_DECOMPRESSION option and will fail because it's not supported on that OS, so the catch block will set _doManualDecompressionCheck to true.  Now let's say the response comes back with gzip compression; it shouldn't be automatically decompressed, because only Deflate was specified.  But the response parser doesn't look at AutomaticDecompression, only at the response encoding:
https://github.com/dotnet/corefx/blob/30ab651fcb4354552bd4891619a0bdd81e0ebdbf/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseParser.cs#L68-L93
so it will automatically decompress with a GZipStream even though DecompressionMethods.GZip was not specified.

**Comment by davidsh** [comment] 2018-05-23 21:40
Thanks for clarifying the repro.  I was confused by your original comment here:

>so even if it was left as the default of None, WinHttpHandler will still automatically decompress the response encoded as deflate or gzip.

That implied that the repro required the handler "None" option.  But that wasn't really the repro for this bug.

I'll work on a fix.

**Comment by stephentoub** [comment] 2018-05-23 21:41
> I was confused by your original comment here

Sorry, my original comment was wrong, I've fixed it.

**Closed** 2018-05-25 21:48 UTC
Labels: area-System.Net.Http, bug, os-windows
