### ISSUE TITLE
Consider using an alternative implementation for the Stream.CopyToAsync in some scenarios

### ISSUE THREAD

**Issue by mkosieradzki** [dotnet/corefx#17524] opened 2017-03-25 20:21 UTC
I have created an alternative CopyToAsync implementation which behaves way better than the default one if source stream serves the data in small chunks and the destination stream write has non-zero latency.

It **might** be useful in some scenarios, but I am not sure. Leaving it here - for details in the original context please see:
aspnet/Proxy#57

**Comment by karelz** [comment] 2017-03-25 23:03
Do you have any perf measurements for your vs. current implementation?
What about impact on other scenarios?

cc @stephentoub @benaadams

**Comment by stephentoub** [comment] 2017-03-25 23:05
Similar to https://github.com/dotnet/corefx/issues/13322

**Comment by karelz** [comment] 2017-03-25 23:09
Closing as dupe of #13322. If there are new findings or data, feel free to reopen.

**Closed by karelz** 2017-03-25 23:09 UTC
Labels: area-System.IO, enhancement, tenet-performance

**Comment by karelz** [comment] 2017-03-25 23:15
cc @JeremyKuhne @ianhays for awareness (area notifications didn't get chance to send the issue to them)

**Comment by mkosieradzki** [comment] 2017-03-25 23:56
@karelz No perf measurements at the moment for other scenarios. In this scenario for which I have written this the performance gain is huge, but I don't believe it will be really that common scenario.

@stephentoub It's not exactly the same, but some of the issues apply to this one as well. And I definitely agree with those concerns. Especially that it introduces concurrent read and write in some cases + the throw dilemma :)

Important fact is that in this specific design there are no double buffers, no overlapping writes and no overlapping reads. This is why I see it completely different from #13322 .

There are obvious benefits of this design as it allows much more efficient buffer utilization and performs really great in scenarios with read-segmentation + write-latency. It should not be underperforming in the other scenarios, but I have no data for confirmation.

It's quite funny as if the read buffer gets saturated quickly (it behaves very similar to the current implementation - read does not overlap with write). Read-Write overlap occurs only in scenario when Read is not able to fill the entire buffer at once.

Let's check first if this implementation can be accepted for Http Proxy scenarios and then maybe consider it in some different places if applicable.
