### ISSUE TITLE
CurlHandler.MaxConnectionsPerServer unsupported on Centos 7

### ISSUE THREAD

**Issue by bling** [dotnet/corefx#14614] opened 2016-12-18 16:10 UTC
### Steps to reproduce
run the following statements:

```
var client = new System.Net.Http.HttpClientHandler();
client.MaxConnectionsPerServer = 8; // any value >= 1
```

### Expected  behavior
no exceptions.

### Actual behavior
```
Unhandled Exception: System.PlatformNotSupportedException: Unknown option
  at System.Net.Http.CurlHandler.set_MaxConnectionsPerServer(Int32 value)
  at System.Net.Http.HttpClientHandler.set_MaxConnectionsPerServer(Int32 value)
  at ConsoleApplication.Program.Main(String[] args)
```

### Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
```

### Comments

it appears to only affect Centos.   it works fine on Ubuntu.

**Comment by karelz** [comment] 2016-12-19 17:27
Is it possible that the error comes from cURL library? Did you try to debug it?

cc: @Priya91

**Comment by Priya91** [comment] 2016-12-23 01:01
The error denotes that the Curl version on your machine does not recognize the option. Can you check if the version of curl on your centos is the same as on ubuntu? If not upgrading curl should work.

**Comment by bling** [comment] 2016-12-23 16:10
@Priya91 looks like that was the problem.  i'm on centos 7.3 (latest release), which has 7.29 for curl.  ubuntu appears to have 7.50.

i grabbed some unofficial rpms to upgrade curl and libcurl to 7.52 and the problem is fixed.

**Comment by karelz** [comment] 2016-12-26 23:04
Closing as it seems to be external problem.

**Comment by bling** [comment] 2016-12-26 23:24
@karelz if possible, the documentation on [dot.net](http://www.dot.net) should be updated.  just like `libunwind` and `libicu` are required, users should upgrade `libcurl` to what the minimum version is recommended so they don't run into unexpected errors like this.  thanks.

**Comment by karelz** [comment] 2016-12-26 23:36
That sounds like a good idea:
I assume you mean list of prereqs here: https://www.microsoft.com/net/core#linuxcentos (step [1])
Do you know if it affects other Linux distros?

What should be the right setup step? `sudo yum install libunwind libicu libcurl`? (sorry, I don't have much Linux background in this space :()

**Comment by bling** [comment] 2016-12-27 00:37
this is actually quite tricky...

it's not that i had `libcurl` missing, it's that the version that comes with the distribution is too old.  i'm already running centos 7.3, which is 2 point releases newer than the 7.1 listed on the website.  running `yum upgrade` won't do anything here.

there's really only two options here.

1.  install from a third party.  you can either download/install RPMs manually or add an external yum repository.  in either case, it's probably preferable that microsoft be the one that provides the updated version.
2.  compile from source

RHEL should also be affected by this, since centos is supposed to be built from the same sources.  ubuntu 14.04 might also be affected, since the version of curl there is only 7.35, which is a couple points newer than the 7.29 of centos 7.3.

**Comment by karelz** [comment] 2016-12-27 01:03
Hmmm, that makes it challenging.
I don't believe Microsoft should be repackaging 3rd party libraries like libcurl. It has further complexities, time investment and security implications.

Maybe the right solution is to leave it as it is now ... we should not be compensating too much for the limitations of the OS to install newer versions of 3rd party libraries ... thoughts?

**Comment by bling** [comment] 2016-12-27 02:12
i'm happy to defer to your judgement; whether it's to start some sort of "known issues" type of thing, or this issue getting picked up by search engines.

**Comment by bling** [comment] 2017-01-02 18:14
i'll leave this here in case someone else ran into the same problem and needs a fix.  disclaimer: use at your own risk 😉 

first, you'll need to download the curl source.  after extracting, you can run:

    ./configure --prefix=/path/to/prefix
    make
    make install

once that's done, you can (ab)use the `LD_LIBRARY_PATH` environment variable, e.g.

    LD_LIBRARY_PATH=/path/to/prefix dotnet run

that will allow dotnet to search for where you installed curl before searching for the system installed version.  there are other better ways to configure search paths, but this will do the trick.

**Comment by danmosemsft** [comment] 2017-04-05 06:37
@janvorli is your libcurl work relevant to this?

**Comment by janvorli** [comment] 2017-04-05 08:13
@danmosemsft no, it is not. This seems like something that would need to be handled on the managed side of things.

**Comment by stephentoub** [comment] 2017-04-05 11:57
> no, it is not.

It would be relevant if we decide to build/ship a libcurl:
https://github.com/dotnet/corefx/issues/17647
In that case, it'll be new enough to have this option.

> This seems like something that would need to be handled on the managed side of things.

We can't implement this on the managed side of things; that's something that could only be done in libcurl's implementation.  However, we could choose to ignore the error the comes back from libcurl in this case, and just make it a nop.

**Comment by janvorli** [comment] 2017-04-05 12:19
@stephentoub 
>However, we could choose to ignore the error the comes back from libcurl in this case, and just make it a nop.

That's what I meant by handling on the managed side.

**Comment by karelz** [comment] 2017-04-06 10:45
Does it mean that we can add the `if (CentOS()) { try { DoWork(); } catch (ThisFailure) { /* ignore */ }` even today?
If yes, let's flip it to up-for-grabs, as we would take the contribution ...

**Comment by stephentoub** [comment] 2017-04-06 10:48
> Does it mean

It means we need to decide whether we want that or not.  If we did that, we'd be ignoring an explicit setting, without the developer knowing, and the developer could catch it the same way as we could in order to ignore it.  Conversely, maybe it doesn't matter if we implicitly eat the failure.

**Comment by stephentoub** [comment] 2017-04-06 10:53
(It also wouldn't be a try/catch... we simply wouldn't throw an exception for this case, regardless of platform.)

**Comment by karelz** [comment] 2017-04-07 07:12
Stupid question ... given that we will most likely package libcurl (with some latest-ish version), won't this problem go away? @janvorli?
Or what am I missing?

**Comment by stephentoub** [comment] 2017-04-07 10:55
> given that we will most likely package libcurl

I'm less certain about that.

**Comment by janvorli** [comment] 2017-04-07 15:37
@karelz it looks like that we are not going to do that for 2.0.0 after all.

**Comment by karelz** [comment] 2017-04-07 17:39
I see, thanks for info ... it's a bummer, but understood :(

**Comment by karelz** [comment] 2017-04-07 19:00
Back to the design then:
@stephentoub @geoffkizer @Priya91 can you please recommend one of the options:
1. Swallow & hide known curl error when dev sets `MaxConnectionsPerServer` on system where it is not supported. It will look like API success, while it didn't do what user asked for.
2. Keep throwing `PlatformNotSupportedException` when developer sets `MaxConnectionsPerServer` on system where it is not supported. It means, library and app writers have to be careful with the property, and have to test on particular OS version to catch it (esp. troublesome for library writers).
    * Note: We can list the difference in https://github.com/terrajobst/pns-scan tool, so library and app writers will know ahead of time.

**Comment by stephentoub** [comment] 2017-04-07 20:37
The default is essentially "unlimited", so setting MaxConnectionsPerServer means you're trying to limit the number of connections the library is able to make, and if we silently ignore the error, it could end up making more connections than you wanted to limit it to.  I don't know how bad that is.  @davidsh, any precedent for treating MaxConnectionsPerServer as a hint rather than a strict limit?  If we think of it as a hint rather than a hard limit, it'd be fine to simply stop translating the CURLE_UNKNOWN_OPTION into a PNSE, though I'd also want to then avoid storing the new value, so that subsequent gets of the property continue to show the default of int.MaxValue rather than looking like the value actually took.  If instead we think of it as a hard limit, it seems bad to accept a new limit but silently ignore it.

**Comment by davidsh** [comment] 2017-04-07 20:45
> @davidsh, any precedent for treating MaxConnectionsPerServer as a hint rather than a strict limit?

Historically, the .NET connection limit per destination endpoint used to be 2.  That was the old recommended value long ago. It was based on browser behavior.  Over time, that went up to 6. For certain high-scale applications (not browser scenarios), more connections were needed and were useful. So, folks using .NET tended to set `ServicePointManager.DefaultConnectionLimit` to high values.

Devs seemed to then want more granular control over this setting, i.e. per HttpClient object (or handler), so we ended up putting this property on the handler.

In practice, though, it is better to let the underlying stack optimize this.  For things like HTTP/2, for example, you don't actually make lots of TCP connections (since they take a long time to make). Instead, things are more multiplexed.  The guidance historically from the native Winodws HTTP stack teams (Wininet, WinHTTP) were to just leave the defaults as-is.  The mantra was "the stack knows how to do this better than the dev".

There is no precedent of a "hint". If there is a manual setting, then the expectation is that it should work as set. But the normal best practice is to have good system defaults and just leave them alone.

**Comment by stephentoub** [comment] 2017-04-07 20:49
Thanks, @davidsh.  @karelz, I think we should leave it as-is then.  But I won't put up a fight if @geoffkizer or @Priya91 disagrees and want to change it to avoid throwing.

**Comment by davidsh** [comment] 2017-04-07 21:01
> But I won't put up a fight if @geoffkizer or @Priya91 disagrees and want to change it to avoid throwing.

While it is more "accurate" to throws PNSE, it is disuptive.  It is not a runtime exception that we would normally want developers to write try/catch for.  It is similar to ArgumentException, etc.  So, it is more of a development bug if they get those exceptions.  So, by throwing PNSE, we are forcing devs to catch a "dev error" type of exception. They wouldn't be doing that for ArgumentException.

I think it is "better" to not throw PNSE and just document (clearly) that it doesn't work (yet) for that platform.

**Comment by Priya91** [comment] 2017-04-07 21:07
From @davidsh's comments, I get the idea that setting these values will be done by a developer, only if they really want to go against the best behavior they can get by overriding the defaults. Then shouldn't the developer be notified that his explicit configuration was ignored?

**Comment by davidsh** [comment] 2017-04-07 21:09
>Then shouldn't the developer be notified that his explicit configuration was ignored?

Developers writing a library against 'netstandard' might not be testing all platforms.  They won't even see this exception perhaps because only certain *Nix systems don't work as expected.

I still vote for not throwing PNSE.

**Comment by wfurt** [comment] 2017-04-10 17:21
There are probably few different angles:

Conceptual: do we care about consistency? Linux distributions are different and this is going to be ongoing problem. We can either use only common features (sucks) or have distro/platform differences (sucks).
One way how to eliminate this (as much as possible) is to eliminate external dependencies (as much as possible) 

Another way is to use proper packaging. For example rpm (and other package systems as well) allows to specify exact or minimal version of other packages you need. That allows to control better execution environment.

Practical: I do hate silent failures. I also do not like catastrophic errors handling. I think Stephen pretty nailed it with two options. 
Since this is not critical feature, I would probably go towards eating the error internally as @davidsh suggested.  If there is any debug mechanism or audit log, this would deserve warning entry there. (once on first  use)
I would also update documentation and explicitly state that is option is supported only on platforms with curl x.y.z or simply say it is ignored on platforms which do not support it. 
 
Strategic: I did look at some pages talking about high performance e IO with Curl. I think is we want performance and scalability we may need to manage connections and IO events within framework. We can use curl & libhttp2 to construct request and parse protocol. With this we can implement connection limits without dependency on curl.

Regression: Going back to first point. We cannot assume things do work on each Linux distro same way. We need automation and test test each distro separately. 
I know it is moving target but for example my company is on Centos6 and our automation runs on Centos5. We need way how to turn this easily into regression test. Tracking distro differences and changes manually is not going to work.

**Comment by geoffkizer** [comment] 2017-04-11 17:30
Silently ignoring this seems like a recipe for angry customers when they realize we aren't behaving as they (quite reasonably) expect us to.

**Comment by Priya91** [comment] 2017-04-18 23:55
I count 2 votes for silent behavior and 3 for throwing. Should we conclude this with current behavior, which is to throw?

**Comment by karelz** [comment] 2017-04-19 00:18
Let's ask community: https://twitter.com/ziki_cz/status/854489134060101632

**Comment by Drawaes** [comment] 2017-04-19 15:44
Can you not require a certain version of curl like you do for openssl.

**Comment by karelz** [comment] 2017-04-19 16:22
@Drawaes I think higher version is not available on Centos 7 - see https://github.com/dotnet/corefx/issues/14614#issuecomment-269252015

**Comment by Priya91** [comment] 2017-04-19 21:30
@karelz I'm not able to see the results of the vote without being a twitter member :P So what's the consensus?

**Comment by karelz** [comment] 2017-04-19 22:51
:D I didn't realize that you can't see the results. The discussion is actually more important - @terrajobst had some strong opinions. We should check with him.

**Comment by tmds** [comment] 2017-04-24 16:13
RHEL and CentOS system libraries are not updated to avoid unintentional breaking.
dotnet for RHEL is packaged as a software collection, which brings it's own version of libcurl. This is newer than the system version.
I find it appropriate to throw PNSE in this case, since the platform doesn't meet minimal requirements.
It would be nice if we can specify a minimal version of libcurl.

**Comment by karelz** [comment] 2017-04-24 16:52
@tmds can you tell me more about the "*dotnet for RHEL is packaged as software collection*"?
We expose a download without libcurl bundled, so how does it play together with your claim? Are you guys releasing wrappers for our installers on RHEL and CentOS? (please excuse my very limited knowledge about Linux packaging, also will be happy to chat offline if it helps ...)

**Comment by tmds** [comment] 2017-04-24 18:39
@karelz For rhel, we build .net core from source. We consider this a must as part of our long-term support commitment. The outcome is a software collection (scl), which includes dotnet but also dependent libraries such as libcurl. The user 'enables' the software collection, which makes the dotnet binary available and makes uses of the scl specific libraries. The dotnet install procedure for rhel explains the steps to install and enable the software collection: https://www.microsoft.com/net/core#linuxredhat.

**Comment by stephentoub** [comment] 2017-05-05 22:57
> Historically, the .NET connection limit per destination endpoint used to be 2. That was the old recommended value long ago. It was based on browser behavior. Over time, that went up to 6. For certain high-scale applications (not browser scenarios), more connections were needed and were useful. So, folks using .NET tended to set ServicePointManager.DefaultConnectionLimit to high values.

This argument suggests that someone is likely setting this property based on a historical knowledge of other .NET API behaviors and wanting to increase to a sufficiently high value rather than limit it; am I understanding correctly?  If so, since the default now is effectively infinite anyway, if the developer is trying to effectively make it infinite by setting it, we wouldn't want to fail for such a case where the setting wouldn't have measurable impact, anyway.

Given that, and the fact that this will work on most platforms and a dev might end up being surprised by the failures in the wild on older systems, seems reasonable to suppress / nop.

**Closed** 2017-05-06 02:52 UTC
Labels: area-System.Net.Http, enhancement, os-linux
