### ISSUE TITLE
WinHttp exception "The handle is in the wrong state for the requested operation" in GetAsync_AllowedSSLVersion_Succeeds test on Win7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#24886] opened 2017-10-26 02:00 UTC
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5ecea8ff47c03a073a77916a9c7d1d806f8c7ce3/workItem/System.Net.Http.Functional.Tests/wilogs
```
2017-10-26 00:34:29,598: INFO: proc(54): run_and_log_output: Output:    System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds(acceptedProtocol: Tls, requestOnlyThisProtocol: True) [FAIL]
2017-10-26 00:34:29,598: INFO: proc(54): run_and_log_output: Output:       System.Net.Http.HttpRequestException : An error occurred while sending the request.
2017-10-26 00:34:29,614: INFO: proc(54): run_and_log_output: Output:       ---- System.Net.Http.WinHttpException : The handle is in the wrong state for the requested operation
2017-10-26 00:34:29,614: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<>c__DisplayClass4_1.<<GetAsync_AllowedSSLVersion_Succeeds>b__0>d.MoveNext()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass3_0.<CreateServerAsync>b__0(Task t)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_AllowedSSLVersion_Succeeds>d__4.MoveNext()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from previous location where exception was thrown ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          ----- Inner Stack Trace -----
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Environment.get_StackTrace()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.ExceptionServices.ExceptionStackTrace.AddCurrentStack(Exception exception)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpException.CreateExceptionUsingError(Int32 error)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpRequestCallback.OnRequestError(WinHttpRequestState state, WINHTTP_ASYNC_RESULT asyncResult)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpRequestCallback.RequestCallback(IntPtr handle, WinHttpRequestState state, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpRequestCallback.WinHttpCallback(IntPtr handle, IntPtr context, UInt32 internetStatus, IntPtr statusInformation, UInt32 statusInformationLength)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at Interop.WinHttp.WinHttpReceiveResponse(SafeWinHttpHandle requestHandle, IntPtr reserved)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at Interop.WinHttp.WinHttpReceiveResponse(SafeWinHttpHandle requestHandle, IntPtr reserved)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpHandler.InternalReceiveResponseHeadersAsync(WinHttpRequestState state)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.ThreadPoolWorkQueue.Dispatch()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:          --- End of stack trace from AddCurrentStack ---
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2017-10-26 00:34:29,677: INFO: proc(54): run_and_log_output: Output:             at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by karelz** [comment] 2017-12-22 20:00
Duplicate of #25980

**Closed by karelz** 2017-12-22 20:00 UTC
Labels: area-System.Net.Http, bug, os-windows
