### ISSUE TITLE
Conditional regex strange behavior

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/corefx#30253] opened 2018-06-10 16:10 UTC
While I am testing Verex I tried this regex ```(?(ab)a)```.
I know it can be better written as ```a(?=b)```, but as I say I was testing for any cases.
So, when I use ```(?(ab)a)``` to match "abac" It returns two results:
1-	the a before b.
2-	the empty position before the second a !
The second result is not desired, and things gets messy if the condition is more complex and the string is longer, so you can get a ressult before each char where the condition is false!
I know that this design is useful when the ```(?(ab)a)``` is a part of a bigger regex such as ```c(?(ab)a)``` which will match c in "abac", but you conseder the previous case as well.
I couldn't use the ```(?!)``` to be the false part as a general solution. It will make the first case ```(?(ab)a|(?!))``` work as expected but it will make the second case ```c(?(ab)a|(?!))``` fail!

**Comment by ViktorHofer** [comment] 2018-06-11 19:53
Related and probably a duplicate of: https://github.com/dotnet/corefx/issues/26787

**Comment by MohammadHamdyGhanem** [comment] 2018-06-11 21:35
@ViktorHofer 
No, this is different. Here we get extre results. I suggested to add | there to solve an issue, but here if I do this< I get a new set of reseults, i.e:
```(?(ab)a|)``` gives different results than ```(?(ab)a)``` !!!!
Something is wrong for sure!

**Closed** 2019-03-04 16:11 UTC
Labels: area-System.Text.RegularExpressions, question
