### ISSUE TITLE
Available Benchmarks

### ISSUE THREAD

**Issue by jchannon** [dotnet/corefx#5074] opened 2015-12-19 09:46 UTC
Hi,

I see in the [performance related](https://github.com/dotnet/corefx/labels/performance) issues you have some examples of `[Benchmark]` to prove there are problems on Linux for example.  Is there a suite of benchmarks that you have that you are running on all the OS's to check perf?  I'd be interested in seeing the results of those and possibly running them.

Thanks

**Comment by ellismg** [comment] 2015-12-30 18:50
The benchmarking infrastructure is still coming online, but here's an overview of where we are:

1. We have ~140 benchmarks checked in today.  They are annotated with with `[Benchmark]` attribute, so they are easy to find via `git grep` if you want to look in more detail.  They are much closer to micro-benchmarks than end to end scenarios. 
2. @ianhays wrote up some very good [documentation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md) on how to run the benchmarks.
3. Ian is also working on getting these benchmarks running in Jenkins so we can easily track regressions.  Right now he runs them manually to look for regressions.
4. We have a larger suite of internal benchmarks which we'll continue to open source (they require that we move them to this `[Benchmark]` framework, so it takes time.
5. The benchmarks today simply measure execution time, but we have folks working on augmenting the infrastructure to collect additional data from the runtime on things like allocations.

ASP.NET has their own set of [end-to-end benchmarks](https://github.com/aspnet/benchmarks) that they track closely. Sometimes this points to improvements that can be made in CoreCLR itself, sometimes CoreFX and sometimes the ASP.NET Stack.

**Comment by ellismg** [comment] 2015-12-30 18:51
> I'd be interested in seeing the results of those and possibly running them.

@ianhays Do you have an idea of when we'll be publishing the daily results of our benchmark runs?

**Comment by ianhays** [comment] 2015-12-30 21:24
>Do you have an idea of when we'll be publishing the daily results of our benchmark runs?

I'm expecting it to come somewhere in the post RTM timeline. Reporting is a lower priority than actually running the tests as part of the CI which hasn't made much progress since the holiday season started. I'm expecting it to move more quickly once everyone is back from vacation and I finish my last few RC2/RTM issues (most of which are just pending feedback). 

>The benchmarks today simply measure execution time, but we have folks working on augmenting the infrastructure to collect additional data from the runtime on things like allocations.

The Windows benchmarks produce ETW trace files for the perf runs. Unix is only execution time though.

>Ian is also working on getting these benchmarks running in Jenkins so we can easily track regressions. Right now he runs them manually to look for regressions.

Here's my outline:

The first step is running the tests consistently and I'm considering two different paths for this:
- Build perf tests from Jenkins machine, upload to an Azure Share, then kick off a Helix perf run.
  - Joel Hendrix wrote some great build targets to build for Helix, submit, and kick off the run, but the Azure keys aren't secure. Chris Rummel is working on a Jenkins plugin that will circumvent that issue.
  - Last I checked there wasn't Linux capability which is a must-have.
- Build and run perf tests directly on Jenkins machine.
  - Requires specific perf machines hooked into Jenkins.
  - Will run perf tests on the same machines every run

Once we complete one of the above we'll be getting results and the next step is validation of those results. This will be a fairly simple program that:
- Go through every perf test in the current run:
  - Compares the perf results of the current run with the perf results of the past X runs
    - If this result is a regression of more than Y%, count this result as failed.

The final step is reporting all regressions to Jenkins as if they were failed unit tests such that the ```Outerloop Windows_NT Release Performance Test``` (or Ubuntu, mac, etc.) check will be red.

**Comment by ellismg** [comment] 2015-12-31 19:27
I feel like @jchannon's are answered now, so I'm going to close the issue.

**Closed by ellismg** 2015-12-31 19:27 UTC
Labels: performance
