### ISSUE TITLE
Enumerable.OrderBy() infinite loops in the presence of a bad comparer

### ISSUE THREAD

**Issue by madelson** [dotnet/corefx#20563] opened 2017-06-01 11:23 UTC
An `IComparer<T>` which does not properly detect equal elements can cause an infinite loop in the evaluation of an `IEnumerable<T>` sorted with `OrderBy`:

```c#
var sequence = Enumerable.Range(0, 2);
var comparer = Comparer<int>.Create((int a, int b) => a == b ? -1 : a.CompareTo(b));
sequence.OrderBy(i => i, comparer).ToArray(); // never terminates
```

This is not necessarily a bug since a non-transitive `IComparer<T>` should cause undefined behavior. However, it would be nice if the result were a thrown exception or nonsensically sorted sequence instead of an infinite loop to simplify debugging.

In comparison, `Array.Sort` applied to the same sequence and `IComparer<T>` does not result in an infinite loop.

**Comment by svick** [comment] 2017-06-01 14:01
> it would be nice if the result were a thrown exception or nonsensically sorted sequence instead of an infinite loop to simplify debugging

Would nonsensically sorted sequence actually simplify debugging? Infinite loop pretty clearly indicates there is some issue, but nonsensically sorted sequence can be easily overlooked. An exception would be even better, but the cost of ensuring that inconsistent comparer throws an exception might be too high.

**Comment by madelson** [comment] 2017-06-01 23:02
@svick I agree that a non-deterministic sort would not necessarily make debugging easier. I guess my thinking was that I am familiar with this outcome from Array.Sort and other platforms, but I hadn't encountered a system sort that went infinite before.

As I said in my original post: this is not necessarily a bug. An exception would be great (if it could be efficient) and non-sensical sorting would at least be consistent with Array.Sort, but even just documenting this somewhere would be nice.

**Comment by JonHanna** [comment] 2017-11-14 11:31
As a request for documenting it, this is a duplicate of #1939.

**Comment by stephentoub** [comment] 2019-07-18 22:13
While it could be nice to catch such user errors, I don't see how it would be done in LINQ without adding considerable cost to correct code.  And as @svick highlights, an infinite loop should be fairly easy to debug.  Thanks for the suggestion.

**Closed by stephentoub** 2019-07-18 22:13 UTC
Labels: area-System.Linq, enhancement
