### ISSUE TITLE
Add CipherSuite property to HttpClientHandler

### ISSUE THREAD

**Issue by grzegorz-ogrodowski** [dotnet/corefx#24541] opened 2017-10-10 08:09 UTC
It's really nice to have opportunity to change CipherSuite per connection, when HttpClientHandler is using.
At this time there is only possibility to define SslProtocol.
I have read issues and this topic appeared few times.

## **Proposed API**
```
namespace System.Net.Http

public class HttpClientHandler: HttpMessageHandler
{
// Other properties... 
   public CipherSuite CipherSuite { get; }
}
```

## **Example Usage**

```
var handler = new HttpClientHandler 
{
   CipherSuite = CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA 
}
```

This API review is strongly connected with:
https://github.com/dotnet/corefx/issues/21577

**Comment by Drawaes** [comment] 2017-10-10 20:56
Spelling Suite ;)

**Comment by Drawaes** [comment] 2017-10-10 20:57
So my problem with it at this level is that it will need support from SslStream. So there needs to be an API change on SslStream.

**Comment by Priya91** [comment] 2017-12-08 22:03
Closing as dupe of #21577

**Closed by Priya91** 2017-12-08 22:03 UTC
Labels: api-suggestion, area-System.Net.Http
