### ISSUE TITLE
Can not send email with SmtpClient on Ubuntu 18.4 LTS

### ISSUE THREAD

**Issue by shakeri** [dotnet/corefx#32063] opened 2018-09-01 04:58 UTC
I'm trying to send email using Google SMTP server but its throwing exception:
```
An unhandled exception occurred while processing the request.
Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (Unknown error).

System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(string package, bool isServer, NetworkCredential credential)
SmtpException: Failure sending mail.

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
At `Startup` Class:
```c#
 services.AddScoped<SmtpClient>((provider) =>
            {
                var config = provider.GetRequiredService<IConfiguration>();
                return new SmtpClient()
                {
                    Host = config.GetValue<String>("MailService:Smtp"),
                    Port = config.GetValue<int>("MailService:Port"),
                    Credentials = new NetworkCredential(
                            config.GetValue<String>("MailService:Username"),
                            config.GetValue<String>("MailService:Password")
                        )
                };
            });
```
And in `Controller`:
```c#
        private readonly SmtpClient _smtpClient;

        public ValuesController(
            SmtpClient smtpClient
        )
        {
            _smtpClient = smtpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            await _smtpClient.SendMailAsync(new MailMessage(
                from: "sender@domain.com",
                to: "receiver@domain.com",
                subject: "Test message subject",
                body: "Test message body"
                        ));
            return Ok();
        }
```

**Comment by danmosemsft** [comment] 2018-09-02 05:43
Hello, it may not help, but can you please confirm this reproes on 2.1 (or master)? 2.0 is about to go out of support.

**Comment by shakeri** [comment] 2018-09-03 10:40
@danmosemsft thanks for reply.
I upgraded this project to version 2.1, but there is still a similar error:
```
An unhandled exception occurred while processing the request.
Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (Unknown error).

System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(string package, bool isServer, NetworkCredential credential)
SmtpException: Failure sending mail.
```

**Comment by danmosemsft** [comment] 2018-09-03 15:18
Thanks. Do you have a different machine to try? Not much to go on.

**Comment by shakeri** [comment] 2018-09-04 06:31
I tested this project on Windows Server 2012 R2 on the same network and it worked without problems.

**Comment by karelz** [comment] 2018-09-04 16:08
I suspect a problem with configuration on Linux - similar to #29087
@tmds @wfurt any tips & tricks for troubleshooting?

**Comment by wfurt** [comment] 2018-09-04 16:18
I would suggest packet capture with wireshark or tcpdump. I would also suggest to install gss-ntlmssp package (or verify that it is in place) 
Just some background @shakeri: Windows do have all the necessary parts needed for NTLM and Kerberos. On Unix, this varies based on distribution and configuration.

**Comment by karelz** [comment] 2018-09-05 18:44
Closing as answered.

**Closed by karelz** 2018-09-05 18:44 UTC
Labels: area-System.Net, os-linux, question

**Comment by danmosemsft** [comment] 2018-09-05 19:11
@karelz I wonder if it would make sense for the exceptoin message to suggest installing it.

**Comment by wfurt** [comment] 2018-09-05 20:44
we talk about it while back @danmosemsft. I think that would be good idea.

**Comment by davidsh** [comment] 2018-09-05 20:51
>we talk about it while back @danmosemsft. I think that would be good idea.

It's not a trivial problem to solve.  The error message we get back when doing NTLM operations is not always specific enough to determine that the problem is configuration (i.e. gss-ntlmssp not installed).
