### ISSUE TITLE
Dictionary_ContainsValue_String* regressed 112%

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#28511] opened 2018-03-27 16:39 UTC
Dictionary_ContainsValue_Int* dropped 42% but the various string ones rose ~100%.

https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2706]&testids=[59909,59910,59911,59939,59915,59916,59918,59917,59928,59929,59930,59900,59901,59902,59894,59895,59896,59903,59904,59905,59940,59941,59942,59912,59913,59914,59891,59892,59893,59925,59926,59927,59936,59937,59938,59932,59922,59923,59924,59933,59934,59935,59931,59919,59920,59921,59906,59907,59908,59897,59898,59899]&jobid=94205&

In this range of changes https://github.com/dotnet/corefx/compare/a2cb15caef95911a0c6a118c62bb447cd65c6563...dotnet:59f6987b7fc919a438060f6c502c3c9cf7c8af29 the following are most likely culprits

02b5689
 @benaadams
Improve Dictionary FindEntry CQ  …
c340cd3
 @benaadams
Improve Dictionary TryInsert CQ  …
5cad7a5
 @benaadams
Use EqualityComparer<TKey>.Default Intrinsic  …
926183e
 @benaadams
1-base Dictionary buckets to reduce initalization  …
e12a5ec
 
![image](https://user-images.githubusercontent.com/6385855/37981583-ee19013e-31a2-11e8-9c75-8f870e08e095.png)

**Comment by danmosemsft** [comment] 2018-03-27 16:42
These changes did not regress Contains**Key** ...

**Comment by ianhays** [comment] 2018-03-27 17:54
Probably this one: https://github.com/dotnet/corefx/commit/926183e3cba0cb9b24685fb0fa308b386fed61df

**Comment by danmosemsft** [comment] 2018-03-27 17:56
It makes sense that ContainsValue is hit much harder, as ContainsKey should only hit Equals roughly once, rather than for n/2 elements.

**Comment by ianhays** [comment] 2018-03-27 18:01
we also stopped caching the comparer in containsvalue: https://github.com/dotnet/corefx/commit/926183e3cba0cb9b24685fb0fa308b386fed61df#diff-72146f1d0ccb2f246a39b3aaceef746dR298

**Comment by benaadams** [comment] 2018-03-27 18:09
>we also stopped caching the comparer in containsvalue:

`EqualityComparer<TValue>.Default` is an intrinsic and caching it to var would regress? https://github.com/dotnet/coreclr/pull/14125

**Comment by benaadams** [comment] 2018-03-27 18:14
Unless... because its a shared generic it won't devirtualize?

**Comment by ianhays** [comment] 2018-03-27 18:20
I missed that it's an intrinsic. Maybe not then.

Here's the test: https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Performance/Perf.Dictionary.cs#L301

**Comment by benaadams** [comment] 2018-03-27 18:26
Oh my days... just realized what `ContainsValue` does, it searches every entry in the dictionary for the value. Can see why that might be sensitive to changes :)

**Comment by ianhays** [comment] 2018-03-27 18:33
lol yeah, it just goes over every entry and uses the comparer against the value.

**Comment by benaadams** [comment] 2018-03-27 18:46
Looking at this, feel a little responsibility from the commits @danmosemsft highlighted 😄

**Comment by danmosemsft** [comment] 2018-03-27 18:53
That wasnt my intent @benadams and for the record the data also shows big wins from some of those changes.

**Comment by AndyAyersMS** [comment] 2018-03-27 19:33
We can probably specialize `ContainsValue` for ref types and cache the comparer only for that case,.

It looks like the extra cost of comparer lookup is indeed the root cause, as this has to access a generic static and that is costly, and the jit can't reason that it is safe to hoist all that out.

Inner loop for ref type value:
```asm
G_M22106_IG09:
       488B4E10             mov      rcx, gword ptr [rsi+16]
       3B5908               cmp      ebx, dword ptr [rcx+8]
       7377                 jae      SHORT G_M22106_IG16
       4863D3               movsxd   rdx, ebx
       488D2C52             lea      rbp, [rdx+2*rdx]
       837CE92000           cmp      dword ptr [rcx+8*rbp+32], 0
       7C49                 jl       SHORT G_M22106_IG11
       488B0E               mov      rcx, qword ptr [rsi]
       488B5138             mov      rdx, qword ptr [rcx+56]
       488B12               mov      rdx, qword ptr [rdx]
       488B4268             mov      rax, qword ptr [rdx+104]
       4885C0               test     rax, rax
       750C                 jne      SHORT G_M22106_IG10
       488D1500000000       lea      rdx, [(reloc)]
       E800000000           call     CORINFO_HELP_RUNTIMEHANDLE_CLASS

G_M22106_IG10:
       488BC8               mov      rcx, rax
       E800000000           call     System.Collections.Generic.EqualityComparer`1[__Canon][System.__Canon]:get_Default():ref
       488B4E10             mov      rcx, gword ptr [rsi+16]
       3B5908               cmp      ebx, dword ptr [rcx+8]
       7339                 jae      SHORT G_M22106_IG16
       488B54E918           mov      rdx, gword ptr [rcx+8*rbp+24]
       488BC8               mov      rcx, rax
       4C8BC7               mov      r8, rdi
       488B00               mov      rax, qword ptr [rax]
       488B4048             mov      rax, qword ptr [rax+72]
       FF5020               call     qword ptr [rax+32]System.Collections.Generic.EqualityComparer`1[__Canon][System.__Canon]:Equals(ref,ref):bool:this
       85C0                 test     eax, eax
       7512                 jne      SHORT G_M22106_IG14

G_M22106_IG11:
       FFC3                 inc      ebx
       3B5E38               cmp      ebx, dword ptr [rsi+56]
       7C99                 jl       SHORT G_M22106_IG09
```

inner loop for int type value
```asm
G_M58268_IG03:
       488BC8               mov      rcx, rax
       443B4108             cmp      r8d, dword ptr [rcx+8]
       733A                 jae      SHORT G_M58268_IG09
       4D63D0               movsxd   r10, r8d
       4F8D1452             lea      r10, [r10+2*r10]
       4A8D4CD110           lea      rcx, bword ptr [rcx+8*r10+16]
       83790800             cmp      dword ptr [rcx+8], 0
       7C0F                 jl       SHORT G_M58268_IG04
       8B4910               mov      ecx, dword ptr [rcx+16]
       3BCA                 cmp      ecx, edx
       0F94C1               sete     cl
       0FB6C9               movzx    rcx, cl
       85C9                 test     ecx, ecx
       750F                 jne      SHORT G_M58268_IG07

G_M58268_IG04:
       41FFC0               inc      r8d
       453BC1               cmp      r8d, r9d
       7CCE                 jl       SHORT G_M58268_IG03
```

**Comment by AndyAyersMS** [comment] 2018-03-27 19:45
Hmm, maybe the jit can mark the call to `get_Default ` as safe to hoist as we basically know this is true since it is an intrisnic. Let me see if that is viable.

**Comment by AndyAyersMS** [comment] 2018-03-27 20:37
Being able to hoist calls to `get_Default` is probably the right approach longer term but it looks like we'd have to rework a bunch of assumptions in the jit to make this work.

Let me see what a source fix looks like as that would certainly be less risk.

I think any fixes here whether in jit or in Dictionary need to originate in CoreCLR ... so perhaps we need a companion issue over there.

**Comment by benaadams** [comment] 2018-03-27 20:45
Same with `FindEntry` etc then..?

> Let me see what a source fix looks like as that would certainly be less risk.

Can do something with ye'olde `default(T) != null`?

**Comment by benaadams** [comment] 2018-03-27 20:55
```csharp
public bool ContainsValue(TValue value)
{
    if (value == null)
    {
        for (int i = 0; i < _count; i++)
        {
            if (_entries[i].hashCode >= 0 && _entries[i].value == null) return true;
        }
    }
    else
    {
        for (int i = 0; i < _count; i++)
        {
            ref var entry = ref _entries[i];
            if (default(TValue) != null)
            {
                // ValueType: Devirtualize with EqualityComparer<TValue>.Default intrinsic
                if (entry.hashCode >= 0 && EqualityComparer<TValue>.Default.Equals(entry.value, value)) return true;
            }
            else
            {
                // Shared Generic (object type) 
                if (entry.hashCode >= 0 && value.Equals(entry.value)) return true;
            }
        }
    }
    return false;
}
```
Produces (also drops one range check)
```asm
; Lcl frame size = 40
G_M44580_IG01:
       push     rdi
       push     rsi
       push     rbp
       push     rbx
       sub      rsp, 40
       mov      qword ptr [rsp+20H], rcx
       mov      rsi, rcx
       mov      rdi, rdx
G_M44580_IG02:
       test     rdi, rdi
       jne      SHORT G_M44580_IG08
       xor      ebx, ebx
       mov      ebp, dword ptr [rsi+56]
       test     ebp, ebp
       jle      G_M44580_IG11
       mov      rax, gword ptr [rsi+16]
G_M44580_IG03:
       mov      rdx, rax
       mov      ecx, dword ptr [rdx+8]
       cmp      ebx, ecx
       jae      G_M44580_IG15
       movsxd   rcx, ebx
       lea      rcx, [rcx+2*rcx]
       cmp      dword ptr [rdx+8*rcx+24], 0
       jl       SHORT G_M44580_IG04
       mov      rdx, rax
       cmp      gword ptr [rdx+8*rcx+16], 0
       je       SHORT G_M44580_IG06
G_M44580_IG04:
       inc      ebx
       cmp      ebx, ebp
       jl       SHORT G_M44580_IG03
G_M44580_IG05:
       jmp      SHORT G_M44580_IG11
G_M44580_IG06:
       mov      eax, 1
G_M44580_IG07:
       add      rsp, 40
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
G_M44580_IG08:
       xor      ebx, ebx
       mov      ebp, dword ptr [rsi+56]
       test     ebp, ebp
       jle      SHORT G_M44580_IG11
G_M44580_IG09:
       mov      rdx, gword ptr [rsi+16]
       cmp      ebx, dword ptr [rdx+8]
       jae      SHORT G_M44580_IG15
       movsxd   rcx, ebx
       lea      rcx, [rcx+2*rcx]
       lea      rdx, bword ptr [rdx+8*rcx+16]
       cmp      dword ptr [rdx+8], 0
       jl       SHORT G_M44580_IG10
       mov      rdx, gword ptr [rdx]
       mov      rcx, rdi
       mov      rax, qword ptr [rdi]
       mov      rax, qword ptr [rax+64]
       call     qword ptr [rax+8]Object:Equals(ref):bool:this
       test     eax, eax
       jne      SHORT G_M44580_IG13
G_M44580_IG10:
       inc      ebx
       cmp      ebx, dword ptr [rsi+56]
       jl       SHORT G_M44580_IG09
G_M44580_IG11:
       xor      eax, eax
G_M44580_IG12:
       add      rsp, 40
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
G_M44580_IG13:
       mov      eax, 1
G_M44580_IG14:
       add      rsp, 40
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
G_M44580_IG15:
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
; Total bytes of code 196, prolog size 19 for method Dictionary`2:ContainsValue(ref):bool:this
```

**Comment by AndyAyersMS** [comment] 2018-03-27 20:56
Yes, via `default(T) == null` or similar.

I am puzzled why some methods like `ContainsValue` refer only to `EqualityComparer<T>.Default` and don't look at the `_comparer` value. Anybody know why?

`FindEntry` I suppose should be fixed in the same way. We will only loop in there if there are collisions so perhaps the extra overhead only shows up cases that are already in a bad way.

**Comment by benaadams** [comment] 2018-03-27 20:58
> don't look at the _comparer value. Anybody know why?

Comparer is only for the key, not the value

**Comment by AndyAyersMS** [comment] 2018-03-27 20:58
Ah never mind, keys vs values.

**Comment by benaadams** [comment] 2018-03-27 21:05
Added issue https://github.com/dotnet/coreclr/issues/17273

@AndyAyersMS I'm happy to do the C# workarounds?

**Comment by AndyAyersMS** [comment] 2018-03-27 21:44
Yes, please do so. A change in C# is going to be much more tractable then trying to fix this in the jit.

if it's ok with you I'll probably adapt dotnet/coreclr#17273 since what we really want is for common caching/non-caching patterns to work equally well across value/ref type `T`. Getting there will require a fair amount of work in the jit.

Right now caching is good for ref type `T` and bad for non-ref type `T`, and non-caching is the other way around, so when you are doing a lot of comparing you run the risk of losing out one way or another.

**Comment by benaadams** [comment] 2018-03-27 21:58
> if it's ok with you I'll probably adapt dotnet/coreclr#17273 

Fine by me :)

**Comment by benaadams** [comment] 2018-03-27 23:02
As @AndyAyersMS pointed out the equality could be `object.Equals` or `IEquatable<T>.Equals(T)` which may be different implementations so think will have to fallback to caching in local as previous (for non-value types)

**Comment by benaadams** [comment] 2018-03-28 07:11
Resolved by https://github.com/dotnet/coreclr/pull/17285

Dictionary size 10,000 
Pre
```
                               Method |      Mean |     Error |    StdDev |
------------------------------------- |----------:|----------:|----------:|
 Dictionary_ContainsValue_String_True | 680.11 ms | 9.8396 ms | 9.2039 ms |
    Dictionary_ContainsValue_Int_True |  58.46 ms | 0.0844 ms | 0.0748 ms |
```
Post
```
                               Method |      Mean |     Error |    StdDev |
------------------------------------- |----------:|----------:|----------:|
 Dictionary_ContainsValue_String_True | 369.92 ms | 6.6659 ms | 6.2353 ms |
    Dictionary_ContainsValue_Int_True |  51.49 ms | 0.8062 ms | 0.7541 ms |
```
https://gist.github.com/benaadams/e7ec75119ec5eb98f56f17cfbaf2f0d4

**Closed** 2018-03-29 17:06 UTC
Labels: area-System.Collections, tenet-performance
