### ISSUE TITLE
Serial Port support on Unix/OSX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#18012] opened 2017-04-06 17:06 UTC
Support the existing Windows API on OSX/Linux machines.

Original Windows thread was https://github.com/dotnet/corefx/issues/984

Any volunteers interested in starting to scope this out? Please thumbs up if you would use this library.

@willdean

**Comment by shaggygi** [comment] 2017-04-22 19:52
This is somewhat related, but is more to do with WSL.  I thought I would add as a link if it helps...

https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/

Also, Rich Turner mentions SerialPort as one of the currently most features asked as it relates to IoT and such.  You can watch here (around 1:55:30 mark) [Windows Weekly 514: Bash on Windows](https://www.youtube.com/watch?v=oiekJGfzsHM&t=6910s)

**Comment by daniel-mcassey-tmsuk** [comment] 2017-05-23 13:35
Has there been any further progress on this?

**Comment by willdean** [comment] 2017-05-23 13:44
@daniel-mcassey-tmsuk No, not yet.  Somebody needs to do a big refactor on SerialPort to get it into the proper multi-platform shape, then things will be a little more straightforward for someone to do the Unix port.

I think the MS guys are very busy with the 2.0 release right at the moment, and I'm very busy with commercial stuff, so after the big push to port the Windows libraries and tests earlier in the year progress has rather slowed.

**Comment by chrisobermeier** [comment] 2017-05-30 19:40
Also currently busy with commercial stuff, but if anything is learnt in that area we can pass it on.

**Comment by JeremyKuhne** [comment] 2017-06-02 18:05
When we do the refactoring to enable this we should make sure we allow for fault testing, notably that we surface errors from the background thread. #19146

**Comment by dima117** [comment] 2017-06-15 06:35
Mono's Posix Library now ported to .NET Core is available. 
https://www.nuget.org/packages/Mono.Posix.NETStandard
It seems, now there is an opportunity to port code from the Mono project to .NET Core
https://github.com/mono/mono/tree/master/mcs/class/System/System.IO.Ports

**Comment by dima117** [comment] 2017-07-19 13:38
I tried to compile the source [code from Mono](https://github.com/mono/mono/tree/master/mcs/class/System/System.IO.Ports) for .NET Standard 2.0 using the [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard) library. The compilation was successful and I was testing COM port reading and writing on the Mac OS.

Is there any way which I can help in the implementation of the serial port API on Unix/Mac OS? I can provide the working source code. Also, I'm ready to participate in the development, but I do not know about the development process.

**Comment by jamespettigrew** [comment] 2017-07-27 17:10
@dima117, I'd love to see how you got it working. I've got a library with the Mono serial port implementation building  just fine but I think I have a packaging issue as the DllImports fail to find MonoPosixHelper.

**Comment by dima117** [comment] 2017-07-27 17:15
@jamespettigrew, you can find MonoPosixHelper library in the [Mono.Posix.NETStandard package](https://preview.nuget.org/packages/Mono.Posix.NETStandard/1.0.0-beta1) in NuGet.

**Comment by jamespettigrew** [comment] 2017-07-27 17:18
@dima117 It appears to be working now that I've referenced Mono.Posix.NETStandard in my CLI project. For some reason it's not being included in my library project's build output.

**Comment by danmosemsft** [comment] 2017-07-27 17:38
@dima117 we would love to include Unix/Mac support. One way to do this might be to follow the pattern of System.Drawing, which is to move the Mono code into CoreFX, and Mono pulls it from CoreFX via submodule. @mellinoe the motivation for doing that (rather than just pulling from Mono repo) was to include the Windows implementation in the same package, right?

I assume it is fine for CoreFX code to depend on Mono.Posix.NETStandard package although I don't know of precedent for an outgoing Nuget dependency. @weshaggard would there be concerns about that?

Is there any anecdata to help gauge the level of interest in Unix/Mac support?

/cc @marek-safar @mellinoe

**Comment by weshaggard** [comment] 2017-07-27 17:58
>I assume it is fine for CoreFX code to depend on Mono.Posix.NETStandard package although I don't know of precedent for an outgoing Nuget dependency. @weshaggard would there be concerns about that?

We cannot depend on that package unless we pull the building of it into our closure for our build from source efforts. That is certainly possible but it will require work and we will need to think twice before taking that dependency.

**Comment by danmosemsft** [comment] 2017-07-27 22:58
Interesting. @eerhardt are you aware of other cases where we might want to take a dependency from CoreFX onto Mono.Posix? I believe you had ideas for other Unix libraries we could offer, and those presumably would sit on Mono.Posix. So you will need to solve this problem.

**Comment by danmosemsft** [comment] 2017-07-27 23:00
@dima117 @jamespettigrew I'm also curious what your code uses serial ports for? For newly written code, we'd probably direct them to a different library, since the System.IO.Ports API's are not necessarily satisfactory. We've ported them mainly for preexisting code.

**Comment by jamespettigrew** [comment] 2017-07-27 23:12
@danmosemsft I'm using it to communicate over RS-485 for a Linux based IoT type HVAC application. I'm not aware of any other suitable libraries, have I missed some?

**Comment by danmosemsft** [comment] 2017-07-27 23:14
@jamespettigrew ha, no I just assumed they existed. @willdean do you know of any?

**Comment by nicolasr75** [comment] 2017-07-27 23:30
@jamespettigrew @danmosemsft  I did a few tests with https://github.com/jcurl/SerialPortStream and was able to connect to my z-wave usb stick from an rpi with Ubuntu. That will hopefully allow me to talk to z-wave compatible sensors and actors for home automation.

**Comment by dima117** [comment] 2017-07-28 06:37
@danmosemsft I'm using it to communicate with [FT232R](http://www.ftdichip.com/Drivers/VCP.htm) device over USB on MacOS and Linux.

@nicolasr75 I have tested SerialPortStream library too, but it not works for me. SerialPortStream depends on unmanaged `libnserial` library, which I can't compile (on MacOS). When I try to compile it, I see uninformative error message. I also [asked for help](https://github.com/jcurl/SerialPortStream/issues/33) to SerialPortStream developer, but he didn't help me.

**Comment by willdean** [comment] 2017-07-28 07:25
> @jamespettigrew ha, no I just assumed they existed. @willdean do you know of any?

Alternatives to SerialPort on unix?  I don't know much about it, but SerialPortStream is the main alternative to SerialPort.  I don't personally have as much of a problem with SerialPort as some of the world seems to, so I'm not really up on the alternatives.

**Comment by nicolasr75** [comment] 2017-07-28 09:14
@dima117 Can't say much about MacOS. I had to compile `libnserial` myself too to get it working on ARM but that worked without any issues. You may want to check the tips I got here https://github.com/jcurl/SerialPortStream/issues/29

**Comment by dima117** [comment] 2017-07-28 10:06
@nicolasr75 Yes, `libnserial` compiles fine on Linux, but it not compiles on MacOS out of box. Now I see this error message
```
CMake Error at libnserial/CMakeLists.txt:85 (install):
  install TARGETS given no FRAMEWORK DESTINATION for shared library FRAMEWORK
  target "nserial".
```

**Comment by eerhardt** [comment] 2017-08-21 19:46
>>>I assume it is fine for CoreFX code to depend on Mono.Posix.NETStandard package although I don't know of precedent for an outgoing Nuget dependency. @weshaggard would there be concerns about that?

>>We cannot depend on that package unless we pull the building of it into our closure for our build from source efforts. That is certainly possible but it will require work and we will need to think twice before taking that dependency.

> Interesting. @eerhardt are you aware of other cases where we might want to take a dependency from CoreFX onto Mono.Posix? I believe you had ideas for other Unix libraries we could offer, and those presumably would sit on Mono.Posix.

I don't think it is the plan to have CoreFX depend on Mono.Posix.NETStandard, at least it was never my intention.  Mono.Posix.NETStandard is intended for code outside of the BCL that needs to call POSIX APIs.  For code inside of the BCL, we have our own set of "shim" libraries (`System.Native`, `System.Net.Http.Native`, `System.IO.Compression.Native`, etc.) when we need to call into native libraries.  I think we would follow the same pattern here.

I think we should port the [System.IO.Ports native shim code from MonoPosixHelper](https://github.com/mono/mono/blob/3cd3c4d53e3895643b80b87f63eb04cc40b8e61e/support/serial.c) into either a new shim library, or an existing shim library in dotnet/corefx.

**Comment by JohnRusk** [comment] 2017-10-11 21:00
I got caught out by this.  I ran the [.NET Portability Analyzer](https://docs.microsoft.com/en-us/dotnet/standard/portability-analyzer) over an assembly, and it said that everything used by the assembly was supported on Core.  But it used System.IO.Ports.Serial, which doesn't work on *nix.  Isn't that some kind of documentation, or metadata bug, somewhere, if we are reporting the API as supported, but it just doesn't work on some platforms?  Shouldn't we be reporting it as _not_ yet supported?

**Comment by danmosemsft** [comment] 2017-10-11 21:48
@terrajobst @dsplaisted (not sure who owns portability analyzer right now) ... can .NET Portability Analyzer tell you anything about Linux portability and if not is that planned?

**Comment by JairoMarques** [comment] 2018-02-10 13:17
Any news?

**Comment by danmosemsft** [comment] 2018-02-21 17:55
@JairoMarques we do not have it on our schedule. As mentioned above - we would welcome a community effort if folks are interested along the lines of @eerhardt's suggestion above.

**Comment by KylePreuss** [comment] 2018-03-10 13:28
This would be a wonderful thing for .NET Core apps running in Docker. If one could deploy services to a remote system and allow for serial communication with devices like GPS receivers, cellular/satellite modems, avionics, sensors etc. without having to write hardware-specific wrappers in another language/framework...

**Comment by kasper3** [comment] 2018-03-10 21:05
The significance of SerialPort has been established, there are some serious (even industrial) workloads which require serial communication and consider it as a main factor in choosing platform.

Should we ask contributors of https://github.com/mono/mono/blob/3b0c0bd1/support/serial.c and/or someone familiar with CoreFX shims can help moving the implementation forward.

@danmosemsft, @eerhardt, any suggestions on "where to start"? 
Does it require all-in-one-go kind of scary PR, or else what would be the best logical division of this work into smaller chunks implementable one at a time (like port discovery, port opening, port closing, sending message etc.)?

If we can lay down a checklist-y plan, based on your previous shim-driven API implementation experiences, that may lead to a successful implementation of Serial Port on Unix in near future. To me at least, it's quite overwhelming to understand https://github.com/mono/mono/blob/3b0c0bd1/support/serial.c and it's includes, then where these are being P/Invoked in mono, then translate it into CoreFX style shims and filter out unsupported platforms before begin to implement the C# mechanics.

**Comment by danmosemsft** [comment] 2018-03-10 23:02
How important is it to folks that the Unix API March the existing Windows API? Same API would mean code could be ported, but I understand the API is not that well designed for Unix semantics (I don't have details handy)

Maybe we can do a quick survey, vote this comment up if you prefer the same API AS windows , down if it doesn't matter for your scenario.

**Comment by wfurt** [comment] 2018-03-11 01:28
I look at System.IO.Ports.Serial and it seems reasonable. I think ability to configure Serial port e.g. speed, parity and flow control and ability to read and write data would be good start @kasper3.
After all, on Unix this is just a device file you an open. If we use tcgetattr/tcsetattr I would put them to Unix specific PAL. That should also work for macOS and BSD. 

Aside from minimal implementation it would be good to find anything from the API which would not make sense on Unix or would be hart to impossible implement.

**Comment by danmosemsft** [comment] 2018-03-11 01:30
Someone want to take a shot at throwing up a minimal PR?

**Comment by wfurt** [comment] 2018-03-11 02:54
BTW What is the deal with this? I tried to follow this on Windows https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netcore-2.0
And I cannot build it. Both VS and dotnet on Windows cannot find the name space.

Tomas

**Comment by wfurt** [comment] 2018-03-12 07:44
I've got basic prototype working on Ubuntu using existing System.IO.Port synchronous API.
I can get/set signals, do basic configuration and send/receive data via RS-232. 
So far I have NOT done any testing with  OSX, USB devices, Raspberry or RS-423.
I think most of it should work on any Unix with exception of GetPortNames(). 
That currently use sysfs (/sys) on Linux. 
I can probably get it in in next few days if there is interest.

**Comment by JensNordenbro** [comment] 2018-06-25 14:14
@wfurt, will this work using docker Ubuntu Images?

**Comment by wfurt** [comment] 2018-06-25 16:30
Yes, it should as long as you can access the device files. (you can always create them with mknod)
I somewhat lost momentum on this distracted with other work. I can try to bump it up on my TODO list if there would be some interest in beta testing. 

related to #29033

**Comment by karbeny** [comment] 2018-10-03 10:59
I work with serialPort in Linux like fileStream and it's working realy great.

**Comment by shaggygi** [comment] 2018-10-03 11:27
@karbeny you have any code examples to share?

**Comment by karbeny** [comment] 2018-10-03 12:53
Here is example of my using.... It's not complete code.

`ExecuteCommand("stty 115200 raw -echo -F /dev/ttyUSB0");
FileStream fs = new FileStream("/dev/ttyUSB0",FileMode.Open);

        public static void ExecuteCommand(string command)
        {
            System.Diagnostics.Process proc = new System.Diagnostics.Process ();
            proc.StartInfo.FileName = "/bin/bash";
            proc.StartInfo.Arguments = "-c \" " + command + " \"";
            proc.StartInfo.UseShellExecute = false; 
            proc.StartInfo.RedirectStandardOutput = true;
            proc.Start ();

            
        }`

**Comment by karbeny** [comment] 2018-10-03 13:04
Here is implementation inside c# code.

`using System;
using System.IO;
using SimpleWebServer;
using System.Net;
using System.Threading;
using System.Timers;
using System.Text;


namespace Test
{
    class Program
    {
        static string serialString = "";
        public delegate void ZobrazZpravu(byte zprava);
        public static ZobrazZpravu myDelegate;
        static Thread vlakno;
        public static FileStream fs;
        static byte[] komunikace = new byte[1024];
        static byte[] serout_buffer = new byte[64];
        static int pozice_komunikace = 0;
        static bool active_serial = true;
        static void Main(string[] args)
        {
            ExecuteCommand("stty 115200 raw -echo -F /dev/ttyUSB0");
            System.Timers.Timer aTimer = new System.Timers.Timer();
            aTimer.Elapsed += new ElapsedEventHandler(OnTimedEvent);
            aTimer.Interval = 3000;
            aTimer.Enabled = true;

            try{
            fs = new FileStream("/dev/ttyUSB0",FileMode.Open);

            myDelegate = new ZobrazZpravu(UkazKomunikaci);
            vlakno = new Thread(new ThreadStart(ReceiveMessage));
            vlakno.IsBackground = true;
            vlakno.Start();
            }
            catch {}
            WebServer ws = new WebServer(SendResponse, new string[] { "http://192.168.0.173:80/", "http://localhost:80/" });
            ws.Run();
            Console.WriteLine("Easy WebServer. Press any key for exit");
            Console.ReadKey();
            ws.Stop();
            fs.Close();
        }

        public static byte[] SendResponse(HttpListenerRequest request)
        {
            Console.WriteLine(request.RawUrl);
            Console.WriteLine(request.Url.ToString());
            Console.WriteLine(request.HttpMethod);
            if (request.RawUrl.Length > 1)
            {
                StreamReader sr = new StreamReader("web_data" + request.RawUrl);
                byte[] ret = new byte[sr.BaseStream.Length];
                for (int i = 0; i < sr.BaseStream.Length; i++)
                    ret[i] = (byte)sr.BaseStream.ReadByte();
                return ret;
                
            }
            return new byte[0];
        }

        private static void UkazKomunikaci(byte zprava)
        {
            serialString += (char)zprava;
            komunikace[pozice_komunikace] = zprava;
            pozice_komunikace++;
        }

        private static void ReceiveMessage()
        {

            while (active_serial)
            {
                while (active_serial)
                {
                    byte serbuff = (byte)fs.ReadByte();
                    if (serbuff > 0) UkazKomunikaci(serbuff);

                }
                
            }





        }
        private static void OnTimedEvent(object source, ElapsedEventArgs e)
        {
            for(int i = 0;i < pozice_komunikace;i++)
            Console.Write((char)komunikace[i]);
            fs.Write(komunikace,0,pozice_komunikace-1);
            serialString = "";
            pozice_komunikace = 0;
        }

        public static void ExecuteCommand(string command)
        {
            System.Diagnostics.Process proc = new System.Diagnostics.Process ();
            proc.StartInfo.FileName = "/bin/bash";
            proc.StartInfo.Arguments = "-c \" " + command + " \"";
            proc.StartInfo.UseShellExecute = false; 
            proc.StartInfo.RedirectStandardOutput = true;
            proc.Start ();

            
        }
    }
}
`

**Comment by haiduc32** [comment] 2018-11-08 07:16
macOS user here. I managed to port the previous example to macOS but it's really unstable. At least with my Arduino project. I had to put some Thread.Sleep in place to make it work, which means there is a problem somewhere. I really need it for my project so I'll keep digging and post when I have something stable.

**Comment by karbeny** [comment] 2018-11-08 13:48
you must use FileStream.flush() to stable using.

**Comment by haiduc32** [comment] 2018-11-09 06:40
That's the bit of the code that writes the last byte, sleeps and flushes. Won't work without sleep (at least in my case):

```
            _fs.WriteByte((byte)'\n');
            Thread.Sleep(1500);
            _fs.Flush(true);
```
As I write that, I realised that I should try to move the sleep just before writing the first byte, and see if that still works. Maybe there is some kind of delay before the serial port can actually receive data..

**Comment by karbeny** [comment] 2018-11-09 07:43
Arduino serial buffer size is 64 bytes. If you write more that 64 bytes you must optimize read function in arduino.

**Comment by haiduc32** [comment] 2018-11-09 07:53
I send: "hello\n"
And the board to replies with a short greeting.

**Comment by krwq** [comment] 2018-11-09 19:22
Hey @haiduc32 and @karbeny, could you try using the latest SerialPort bits from corefx repo?

Here is how you can consume them (this assumes you build for arm, change RuntimeIdentifier accordingly):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RootNamespace>SerialPortsApp</RootNamespace>
    <!-- this can also be passed from the command line (i.e. dotnet publish -r linux-arm) but currently it is also used -->
    <RuntimeIdentifier>linux-arm</RuntimeIdentifier>
    <!--
        To use the latest version of core-setup we can pass the version manually:
        <RuntimeFrameworkVersion>4.6.0-preview.18559.1</RuntimeFrameworkVersion>
        Latest versions of all packages used here can be found here
           (RuntimeFrameworkVersion is related to Microsoft.NETCore.App package):
            https://github.com/dotnet/versions/blob/master/build-info/dotnet/core-setup/master/Latest_Packages.txt
        Currently this is not needed because we consume private corefx.
        Once this gets public the following line and package reference to Microsoft.Private.CoreFx.NETCoreApp
        can be removed.
    -->
    <PackageConflictPreferredPackages>Microsoft.Private.CoreFx.NETCoreApp;runtime.$(RuntimeIdentifier).Microsoft.Private.CoreFx.NETCoreApp;$(PackageConflictPreferredPackages)</PackageConflictPreferredPackages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Private.CoreFx.NETCoreApp" Version="4.6.0-preview.18559.1" />
    <PackageReference Include="System.IO.Ports" Version="4.6.0-preview.18558.3" />
  </ItemGroup>

</Project>
```

You will also need nuget.config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

and latest dotnet sdk which you can download from here: https://github.com/dotnet/core-sdk

Soon doing it should be slightly simpler as all packages get published.

I've tried talking with Arduino Circuit Playground Express from Rapsberry Pi 3 Model B and everything was working.

**Comment by haiduc32** [comment] 2018-11-10 07:16
@krwq my pain is on macOS. I'll try it on a Raspberry Pi if I'm not lazy, but I can't promise.

Ok, so, on **macOS** there is indeed a delay between when I open the FileStream till I can safely send and receive the data. I've measured it at around 600ms with my Arduino. How I tested:

```
            _fs = new FileStream(comPortName,FileMode.Open);
            
            Task t = Task.Factory.StartNew(() =>
            {
                int b = 0;
                while ((b = _fs.ReadByte()) >=0)
                {
                    Console.Write((char)b);
                }
            });

            for (int i = 0; i < 20; i++)
            {
                foreach (char c in i.ToString())
                {
                    _fs.WriteByte((byte)c);
                }
                _fs.WriteByte((byte)'\n');
                _fs.Flush(true);
                Thread.Sleep(100);
            }
```
And what I typically get(meaning I can get even faster results sometimes):
```
R6
7
8
9
10
11
12
13
14
15
16
17
18
19
```
R - is because of timing, some bits get messed up and I get one more broken character (at random).

Now that I know that, I'll just write my code to ping the board till it gets data that makes sense. After that initial delay, everything works ok.

**Comment by wfurt** [comment] 2018-11-10 08:10
What hardware do you have @haiduc32 ? I assume USB<->Serial adapter? There is HW complexity right there.  However I did some testing on OSX and code we have should be portable. 
Adding OSX support would be mostly build changes.

**Comment by haiduc32** [comment] 2018-11-10 08:18
I'm using a macbook pro connected to an Arduino UNO compatbile board, which uses a FT231X chip for serial adapter.
My guess is that there is something in the way macOS handles these serial file streams. Previously, I did write a Swift app that was communicating with an arduino using a serial driver and there were no such problems, so when .net core gets proper support for serial, it should also work ok.

**Comment by shaggygi** [comment] 2018-11-10 15:39
See https://github.com/dotnet/corefx/issues/33374

**Comment by krwq** [comment] 2018-11-10 18:29
@shaggygi the instructions I gave here: https://github.com/dotnet/corefx/issues/18012#issuecomment-437467286 are not affected by packaging bug - the issue is that you have to use latest dotnet sdk from https://github.com/dotnet/core-sdk instead of 2.1

**Comment by shaggygi** [comment] 2018-11-10 18:55
@krwq good to know.  i was mainly just trying to connect similar issues on serial topic.  thx

**Comment by Tragetaschen** [comment] 2018-11-19 18:47
I have just tested my (up until now) mono-only project with System.IO.Ports using the .NET Core 3.0 development bits from myget on linux-arm. My platform is an NXP (formerly Freescale) i.MX6 SoloX, but the serial devices are a USB RFID reader and a USB bar code reader driven by the CDC/ACM class driver.

Everything worked out of the box, so: yay! Admittedly though, the communication isn't complex at all and I had to trim down the API surface considerably to work with mono: It's a BinaryReader/Writer on top of the `SerialPort.BaseStream` in one case and blocking `Read`, `ReadChar`, `ReadExisting`, `Write` in the other.

I haven't seen any i.MX6 platforms mentioned before and would like to offer help with testing. Are you interested?

**Comment by krwq** [comment] 2018-11-19 21:12
@Tragetaschen I've already tested with Hummingboard Edge but if you got some more devices it would be nice to try it out :-) (also GetPortNames if possible). Thanks for trying this out - I'm glad it worked!

**Comment by bigdnf** [comment] 2018-12-06 16:38
I'm trying to run SerialPort on RaspberryPI with Raspbian and .NET Core 2.2 and when Open is executed I have this exception:

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'System.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.IO.Ports.Native: cannot open shared object file: No such file or directory

**Comment by Tragetaschen** [comment] 2018-12-06 17:48
@bigdnf On Linux, System.IO.Ports requires a native library and that one only ships with .NET Core 3. You can find more details in #33374.

**Comment by krwq** [comment] 2018-12-06 19:04
@bigdnf also hacky (and not supported) way to fix it is to copy the native dll from .NET Core 3.

**Comment by wfurt** [comment] 2018-12-10 20:42
This should throw PNSP, right @krwq ? Unless we polluted 2.2 with 3.0 work.

**Comment by krwq** [comment] 2018-12-12 16:51
@wfurt, see #33374. Even though System.IO.Ports is OOB it depends on 3.0

**Comment by wfurt** [comment] 2018-12-12 17:08
That is not the point. This used to throw and it does not any more even if it does not work.
That seems unintentional to me.

**Comment by krwq** [comment] 2018-12-12 18:55
@wfurt I do not recall changing anything related to that. Is there an easy way to fix this?

**Comment by wfurt** [comment] 2018-12-12 18:58
I don't know either. And I don't know if anybody depends on the exception.

**Comment by stephentoub** [comment] 2019-01-07 16:24
@krwq, @wfurt, can this issue be closed now, or if not, what work remains?  Wondering if more specific issues should be opened for any remaining work rather than keeping open this overarching issue.

**Comment by wfurt** [comment] 2019-01-07 17:12
I think this should be closed.

**Closed by wfurt** 2019-01-07 17:12 UTC
Labels: area-System.IO, enhancement, os-linux, os-mac-os-x

**Comment by krwq** [comment] 2019-02-15 19:00
https://github.com/dotnet/corefx/issues/33374 is now fixed
package should work correctly now for apps also targeting netcoreapp2.1 or netstandard2.0 (no need to copy any binaries). Make sure to use at least following version or later:
`dotnet add package System.IO.Ports --version 4.6.0-preview4.19114.5 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

**Comment by danielmeza** [comment] 2019-09-25 19:21
The Unix/OS include android?

**Comment by wfurt** [comment] 2019-09-25 20:11
I don't think it was tested on android. But I think it should work as far as there is access to /dev/ttyS (or equivalent)

**Comment by danielmeza** [comment] 2019-09-26 14:00
@wfurt  I was try it with Xamarin.Android but since the mono dos't use corefx yet it not work, I suppose that I need to run directly in .net core arm in a android with 4.14+ kernel

**Comment by wfurt** [comment] 2019-09-26 22:30
I think you can get package from NuGet. @krwq can perhaps guide you.

**Comment by krwq** [comment] 2019-09-27 00:09
Yes https://www.nuget.org/packages/System.IO.Ports/ - System.IO.Ports is an OOB (out of the box) nuget package so I think it should just work

**Comment by danielmeza** [comment] 2019-09-27 15:05
@krwq I thest that package in android 9.0 win visual studio 16.3 and dos't work. It should work?

**Comment by krwq** [comment] 2019-09-27 16:18
@danielmeza what's the error you're seeing?

**Comment by danielmeza** [comment] 2019-09-30 14:15
@krwq  I get a System.PlatformNotSupportedException: 'System.IO.Ports is currently only supported on Windows.', I have the 4.6.0 System.IO.Ports package installed in both project, .NET Standard project and in the Android project.

**Comment by krwq** [comment] 2019-09-30 18:34
@danielmeza package version sounds correct to me so I think we will need to do some extra work for this to work on Android.
I'm not sure where this specific error is coming from since the message is not exactly correct (Unix is supported as well) - I suspect this is auto-generated somewhere.

I believe the only work which would need to happen here is to upgrade RIDs (runtime identifiers) here:
https://github.com/dotnet/corefx/tree/master/pkg/runtime.native.System.IO.Ports

and test it on android. @danielmeza how do you connect serial port device to android? Is this some specific device, emulator or something else? I haven't personally tried running .NET on android yet.

Also there is a tiny chance we might need to produce build on android to get the native assets which I'm not sure if we currently do and how viable that is.

It would be useful to create a separate issue for that.

**Comment by wfurt** [comment] 2019-09-30 18:39
can we force linux-x64 rid for the package?

**Comment by krwq** [comment] 2019-09-30 18:46
@wfurt possibly but we still need to test it somehow

**Comment by am11** [comment] 2019-09-30 23:22
Although linux is currently the whitelisted RID [for System.IO.Ports project](https://github.com/dotnet/corefx/blob/6f82bd59a05ea9556397596ae9e59f39b904b222/src/System.IO.Ports/src/System.IO.Ports.csproj#L5), it somehow works on Alpine (linux-musl-x64) through RID inheritance, but not Android (both are derived from linux in `Microsoft.NETCore.Platforms/runtime.json`).

---

While testing with a simple example on Alpine Linux, I noticed that `ReadExisting()` is not returning anything: https://dotnetfiddle.net/ezolW0

outputs without `Hello from ..` strings:

```
Working with: /dev/ttyS0

Working with: /dev/ttyS1

```

---

btw, the example [in docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netcore-3.0#examples) can probably be modernized, as it is 198 lines long and does not work outside of Windows (because of `if (portName == "" || !(portName.ToLower()).StartsWith("com"))` condition).

**Comment by krwq** [comment] 2019-09-30 23:50
I've just talked with @Anipik offline and he might have some clues about this.

**Comment by Anipik** [comment] 2019-10-01 18:18
@am11 can you open a new issue with an isolated repro ?
And can you also attach the output info of dotnet --info on the android machine.

**Comment by danielmeza** [comment] 2019-10-02 12:09
@krwq I investigate this issue, in resume it will only run in Linux with kernel 4.14 since .net core needs this kernel to work properly.

Another reason is that I'm not using .net core as run time but mono instead, so the compilation process is not generating the redirect assemblies for the linux run time so I suppose that if we run a .net core application in a android device with kernel 4.14+ it will work, but at the moment in a mono application (Xamarin.Android) it will not work. 

So if we want to work with a Xamarin.Android app we need to wait until Xamarin use .net core as run time instead mono, in other words we need to wait for .Net 5.
