### ISSUE TITLE
[arm32] corefx System.Net.Http.Functional.Tests fails

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/corefx#29292] opened 2018-04-23 23:46 UTC
_From @BruceForstall on April 23, 2018 21:44_

60 failures in this test suite:

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/3/consoleText

Some seem like timeout (which is probably just too tight):
```
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: Token) [FAIL]
      Elapsed time 00:00:31.6604110 should be less than 30 seconds, was 31.660411
      Expected: True
      Actual:   False
```

There are many other error modes, though, e.g.,
```
      Assert.Throws() Failure
      Expected: typeof(System.Net.Http.HttpRequestException)
      Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
```

_Copied from original issue: dotnet/coreclr#17739_

**Comment by rmkerr** [comment] 2018-04-24 21:03
Hey @RussKeldorph. I don't know much about our ARM testing setup. Are these running on physical machines or in QEMU? I think that this is going to be an interesting problem to solve -- it looks like we assume some minimum level of performance that we just don't get on ARM.

**Comment by RussKeldorph** [comment] 2018-04-24 21:58
@rmkerr These are runs on physical machines.  Note they are Checked builds of the runtime, which are substantially slower than Release as well.  I don't know enough about what the test is doing to make suggestions, but I'm happy to brainstorm ideas if you want to share more.

**Comment by rmkerr** [comment] 2018-04-24 22:27
@RussKeldorph thanks! I think that the first thing we should do is see if this is just caused by our tests running slower on ARM, or if there is a real behavior difference affecting networking performance.

Is it possible to run just one of the failing tests, and see if it still fails? Or, even better, to run the HTTP functional tests with parallelism disabled? It sounds like that might take a while, so maybe starting with just one test is better :)

If you have other ideas that I can help with just let me know!

**Comment by kasper3** [comment] 2018-06-16 14:17
Happened here again https://mc.dot.net/#/user/kasper3/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c600941fab07efb20704eecb0aa496fac36439a8/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientTest~2FGetAsync_InvalidUrl_ExpectedExceptionThrown

**Comment by BruceForstall** [comment] 2018-12-07 00:36
@wfurt Have you investigated this?

**Comment by wfurt** [comment] 2018-12-07 01:49
I think I look at it while back and it looked more like a timing issue. I don't know if we have any recent failures.

**Comment by wfurt** [comment] 2018-12-20 22:56
This seems to be reverse of #30032. The problem is that we can get one or the exception without much determinism. We could make the test more flexible but root cause lives inside HTTP/Async code. 
Aside from timing, there seems to be nothing ARM specific.

**Comment by BruceForstall** [comment] 2018-12-20 23:13
I don't understand this sentence: "The problem is that we can get one or the exception without much determinism." Grammar?

Are you suggesting that there is no way to adjust the test such that it won't randomly fail?

Note that this test assembly is disabled in coreclr runs for Linux/arm32 here: https://github.com/dotnet/coreclr/blob/04c4df8c9ecf53499838945197af70f11ddf840a/tests/arm/corefx_linux_test_exclusions.txt#L11

**Comment by wfurt** [comment] 2018-12-20 23:21
missing 'other'. We could fix the test to expect either exception but that won't fix the root cause. After internal discussion we disabled test causing #30032.

I'll talk to @karelz to get it on radar again.

**Comment by BruceForstall** [comment] 2018-12-21 00:18
Are you saying that you might choose to disable the test causing this failure (which appears to be System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly) ?

Maybe another option is to at least disable it for CI runs? I think there's a "IgnoreForCI" category we don't run.

**Comment by wfurt** [comment] 2019-04-04 07:03
I'm going to close this @RussKeldorph as it is so old and corefx tests are passing. Please open new issue if anybody hits this again. I think we still have some work to do but it should not be tracked as ARM issue.

**Closed by wfurt** 2019-04-04 07:03 UTC
Labels: arch-arm32, area-System.Net.Http, bug, os-linux, test-run-core
