### ISSUE TITLE
Brotli Compression not working in an Azure Web App

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#27317] opened 2018-02-21 05:56 UTC
Opened on behalf of @jmkni from https://github.com/dotnet/corefxlab/issues/2068

---

Hi all

I have the Brotli compression working nicely in development, but when I push it to Azure the files just don't compress.

The Content-Encoding is returned as **br**, but the files are no smaller than with GZIP. Running locally, they are significantly smaller.

On my Azure Web App, I have installed the **Brotli HTTP Compression (x86)** extension, and I am running on 32-bit.

Any ideas?

Cheers

Edit, have tried switching to 64-bit, and using the 64-bit extension. Same issue. I have also tried both 32 and 64 bit without the extension, no joy!

Buffer size: 65520
Quality: CompressionLevel.Optimal

**Comment by ianhays** [comment] 2018-02-26 18:13
Hey @jmkni could you please provide some more details here? It would be helpful to have an example showing your code that is running locally vs your code that pushes to Azure. 

It also sounds like you might be using a third party Brotli HTTP extension and that is causing you problems?

If the actual BrotliStream is working correctly locally, then I would guess the issue is somewhere in either the extension or the code that does the submission to Azure. It's unlikely to be an issue with the actual Brotli implementation if your local copy is working correctly, so you would probably have better luck filing an issue against the Azure extension you're using.

**Comment by ianhays** [comment] 2018-03-05 17:33
Closing this as it is likely unrelated to .net core brotli compression and there hasn't been an update by the OP.

**Closed by ianhays** 2018-03-05 17:33 UTC
Labels: area-System.IO.Compression
