### ISSUE TITLE
SignalR serialize date timezone

### ISSUE THREAD

**Issue by zehavibarak** [dotnet/corefx#42208] opened 2019-10-27 04:54 UTC
# SignalR date serialization

While serializing response, the new Core 3.0 System.Text.Json.JsonSerializer adds offset to dates.

# General

This behavior was previously resolved on Core 2.2 using Newtonsoft `PayloadSerializerSettings.DateTimeZoneHandling` and `services.AddSingleton _ => new JsonSerializer`. 
Using the new 3.0, there is no way of setting this, unless using the `AddNewtonsoftJsonProtocol()`, which I would rather avoid.

**Comment by scalablecory** [comment] 2019-10-29 22:57
not sure if belongs in asp.net or json @ahsonkhan @Pilchie

**Comment by Pilchie** [comment] 2019-10-29 23:51
also @anurse for signalr.

**Comment by anurse** [comment] 2019-10-30 00:05
It sounds like this may be a feature that Newtonsoft.Json had but System.Text.Json does not. I know Newtonsoft did a whole bunch of funky stuff with dates. SignalR doesn't really do anything special here, I think it's most likely a serializer feature-request

**Comment by zehavibarak** [comment] 2019-10-30 02:29
Actually , the inconsistency of date serialization in Net Core vs SignalR was there in 2.2. If you were to serialize the same data from controller, and forward it via SignalR in v2.2 - you'd run into the same issue. This makes it likely to be more of a time zone thing than serialization one. Only that in pervious SignalR, you could set the DateTimeZoneHandling, which would make the serialization align in both controller and SignalR.

**Comment by zehavibarak** [comment] 2019-10-30 15:44
@anurse as I've said, it is likely 2b a SignalR issue, since the same date value serialize with and without timezone. The only other thing I can think of, is that EF serialization omits timezone

**Comment by ahsonkhan** [comment] 2019-10-31 08:38
> Using the new 3.0, there is no way of setting this, unless using the `AddNewtonsoftJsonProtocol()`, which I would rather avoid.

For customizing the serialization of dates using S.T.Json's serializer, you'd need to register your converter that formats the dates to the output you expect (as part of `JsonSerializerOptions`, by setting `PayloadSerializerOptions`).
See this document for more details:
https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#custom-support-for--and-

@zehavibarak - can you share a sample repro of the type you want to serialize with expected/actual output? What `DateTimeZoneHandling` setting did you previously use to get the behavior you needed?

**Comment by Clockwork-Muse** [comment] 2019-10-31 16:04
nit: `-08:00` isn't a timezone, it's an offset.

Note that deserializing into `DateTimeKind.Local` is inherently dangerous, since even if the instant (same UTC value) is retained this still distorts the apparent value and what adjustments would need to be performed with regards to DST and other cross-zone comparisons.  If you get passed an offset, use `DateTimeOffset`.
And unless you're _very_ careful, `DateTimeKind.Unspecified` is going to shoot you in the foot.

**Comment by zehavibarak** [comment] 2019-10-31 17:26
I’m setting from DateTime.UtcNow, sending via SignalR and saving to EF context. That value is later serialized via MVC – with a different offset. How would you suggest to write this better?

**Comment by zehavibarak** [comment] 2019-10-31 17:33
@ahsonkhan JsonSerializerOptions doesn't have the Newtonsoft JsonSerializationSettings DateTimeZoneHandling = DateTimeZoneHandling.Utc. The value I'm using is DateTime.UtnNow, which serialize with offset from SignalR, while serialize without offset from controller (in my code I first persist it via EF, so maybe the prob is there)

**Comment by Clockwork-Muse** [comment] 2019-10-31 18:08
> I’m setting from DateTime.UtcNow, sending via SignalR and saving to EF context. That value is later serialized via MVC – with a different offset. How would you suggest to write this better?

Generally speaking, any serialization of a date-time value falls into one of two categories:
 1. A "logged" value representing the exact instant in time something occurred, usually expressed in UTC for historical/interop reasons.
 1. A "future" value representing an estimate of a future time, almost never in UTC (because UTC is usually not relevant for schedules).

If you're dealing with a logged value, serializing it (wherever) as either UTC or some other explicit offset is fine - the exact instant is recoverable.  Although UTC (or any other offset) can be listed in the documentation (or in the column name in a database), it's preferable to explicitly include it in the value, when possible (ie, appending `'Z'`, or the offset amount).

If you're dealing with a future value, you have to worry about changes in DST offset rules (the record between announcement and change taking effect is ~1 day).  This is because _most_ cases for future scheduling will be human-related, and there isn't an actual UTC timezone where anybody lives.  You need to include:
 1. The local time, to the necessary resolution.
 1. The anticipated offset in effect.
 1. The time-zone identifier.  If this is going over the wire you're usually going to want to use the [tzdb identifiers](https://en.wikipedia.org/wiki/Tz_database), but you at least need to be aware that others exist (so definitely include that in your documentation).  Note that these identifiers don't change when DST occurs, so the offset is needed to disambiguate the local time.

It's going to be on whoever deserializes the values to figure out what they want to do if the offset you provide and the one they calculate from the identifier don't match.  Most often you'll want to retain the local time from the originating zone, which may not be the zone of the local machine or user.

<hr />
So what does the date/time value you're capturing represent?  Additionally, what is it being displayed as?  If it's something like, "this message was sent at", capturing in UTC and translating into the local zone on the client application side is fine.  If it's something like, "this store made $40,000 between A and B", you can capture in UTC, but you shouldn't translate to the client timezone (it should likely be translated to the store timezone).  Other cases exist.

**Comment by zehavibarak** [comment] 2019-11-07 03:31
Indeed I log DateTime.UtcNow, and display the date to the user according to his or her's locale timezone (utilizing momentjs).

My issue is, that data is stored using Sql DATETIME data type, and serialized from EF and controller in like `2019-11-07T03:15:51`
while SignalR returns a value like `2019-11-07T03:15:51Z`

So a code as:
```c#
public class Chat {
    public DateTime Time {get; set; }    
}
public IEnumerable<Chat> Get() => _store.Chats.ToList();
public Chat Post() {
    var model = new Chat {
        Time = DateTime.UtcNow
    };
    _store.Chats.Add(model);
    _store.SaveChanges();
    return model;
}
```
that posts (1) a model and return it will result in inconsistent values, since the `Time` property of the `Chat` model would have lost its `Kind` by the time it is retrieved from database (2).

To resolve this, I added a simple `JsonConverter`  that ignores `Kind` on the `Post` method phase (1)  as well.
```c#
    public class JsonDateTimeConverter : JsonConverter<DateTime>
    {
        public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => reader.GetDateTime();

        public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options) => 
            writer.WriteStringValue(value.ToString("s"));
    }
public class Chat {
    [JsonConverter(typeof(JsonDateTimeConverter))]
    public DateTime Time {get; set; }    
}

```

I suggest adding a `DateFormat` property to the `JsonOptions` class, to control the `ToString` value used when serializing dates.

**Comment by Clockwork-Muse** [comment] 2019-11-07 05:11
>My issue is, that data is stored using Sql DATETIME data type, and serialized from EF and controller in like `2019-11-07T03:15:51`
while SignalR returns a value like `2019-11-07T03:15:51Z`

... I don't understand what the problem is?  SignalR is appending the offset (`'Z'` is used to designate `'Zulu'` - that is, UTC).  moment-timezone should understand this - and in fact, having the `'Z'` would make it unambiguous.  Having it is usually preferred for that reason alone.

> that posts (1) a model and return it will result in inconsistent values, since the `Time` property of the `Chat` model would have lost its `Kind` by the time it is retrieved from database (2).

The correct thing to do here is to make sure to apply the `Kind` on values you pull out of the database (or switching to `DateTimeOffset` and specifying the offset, if the `Kind` is going to be anything other than UTC.  Although I'm not sure what happens if only the C# side is switched to `DateTimeOffset`.).  [This can be done relatively simply with attributes](https://stackoverflow.com/questions/4648540/entity-framework-datetime-and-utc), and that post goes into a couple of other options.  Leaving `Kind` as `Unspecified` is going to bite you, even if you only work with the value on the server side.

>I suggest adding a `DateFormat` property to the `JsonSerializerOptions` class, to control the `ToString` value used when serializing dates.

:winces:

The problem is that this is dangerous, because if the format used is anything other than ISO, it's going to make programmers want to [fold, spindle, and mutilate](https://en.wikipedia.org/wiki/Punched_card#Do_Not_Fold,_Spindle_or_Mutilate) the author for poor API design.

**Comment by layomia** [comment] 2019-11-23 11:48
@zehavibarak it looks like you were able to make progress with a custom converter, so I'm closing this issue. Please feel free to re-open if you still have trouble with this.

**Closed by layomia** 2019-11-23 11:48 UTC
Labels: area-System.Text.Json
