### ISSUE TITLE
[release/1.0.0] Numerics StackCalc returning unexpected result on Win10 release

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9247] opened 2016-06-08 12:40 UTC
Please take a look

System.Numerics.Tests.divremTest.RunDivRemTests

```
MESSAGE:
Assert.Equal() Failure\r\nExpected: 0\r\nActual: -4966759395308350
+++++++++++++++++++
STACK TRACE:
at System.Numerics.Tests.StackCalc.VerifyOutParameter() in d:\j\workspace\outerloop_win---d963201a\src\System.Runtime.Numerics\tests\BigInteger\stackcalculator.cs:line 252 at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring) in d:\j\workspace\outerloop_win---d963201a\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 185 at System.Numerics.Tests.divremTest.RunDivRemTests() in d:\j\workspace\outerloop_win---d963201a\src\System.Runtime.Numerics\tests\BigInteger\divrem.cs:line 147
```

**Comment by mellinoe** [comment] 2016-06-08 17:29
Related: https://github.com/dotnet/corefx/issues/7806

**Comment by joshfree** [comment] 2016-06-08 23:51
@mellinoe please give an update by EOD

**Comment by mellinoe** [comment] 2016-06-08 23:58
Closing this as a dupe of #7806

**Closed by mellinoe** 2016-06-08 23:58 UTC
Labels: os-windows
