### ISSUE TITLE
Test failures: Remote servers unreachable

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#26032] opened 2017-12-22 21:24 UTC
## Types of failures

Affected tests:
* System.Net.Tests.TaskWebClientTest / [UploadFile_Success](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L669)
* System.Net.Tests.TaskWebClientTest / [UploadString_Success](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L688)
* System.Net.Tests.WebClientTest / [RequestHeaders_AddHostHeaderAndSendRequest_ExpectedResult](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L411-L415)
* System.Net.Tests.SyncWebClientTest / [UploadData_LargeData_Success](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L652)
* System.Net.Tests.SyncWebClientTest / [OpenWrite_Success](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L624)
* System.Net.Tests.SyncWebClientTest / [UploadData_Success](https://github.com/dotnet/corefx/blob/b227000d7d2b3d79224a95278d3e76dc74ff6b0c/src/System.Net.WebClient/tests/WebClientTest.cs#L637)

### CurlException: SSL connect error

```
System.Net.WebException : An error occurred while sending the request. SSL connect error
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Http.CurlException : SSL connect error
```

### CurlException: Couldn't resolve host name

Ubuntu17.04:

```
System.Net.WebException : An error occurred while sending the request. Couldn't resolve host name
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Http.CurlException : Couldn't resolve host name
```

### WinHttpException: The server name or address could not be resolved

Windows:

```
System.Net.WebException : An error occurred while sending the request. The server name or address could not be resolved
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Http.WinHttpException : The server name or address could not be resolved
```

## History of failures

Day | Build | OS | Error message | Test
-- | -- | -- | -- | --
6/28 | 20170628.02 | Fedora26 | CurlException: SSL connect error | UploadData_Success
7/8 | 20170708.04 | Fedora26 | CurlException: SSL connect error | UploadData_Success
9/2-9/3 | N/A | various | System.Net.WebException : The operation has timed out. | All tests
9/28 | 20170928.03 | Fedora25 | CurlException: SSL connect error | UploadFile_Success
9/29 | 20170929.02 | Fedora25 | CurlException: SSL connect error | UploadFile_Success
10/9 | 20171009.04 | Fedora25 | CurlException: SSL connect error | OpenWrite_Success
10/17 | 20171017.02 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
10/18 | 20171018.02 | Fedora25 | CurlException: SSL connect error | UploadData_Success
10/19 | 20171019.01 | Ubuntu17.04 | CurlException: Couldn't resolve host name | UploadData_Success
10/19 | 20171019.01 | Ubuntu17.04 | CurlException: Couldn't resolve host name | UploadData_Success
10/19 | 20171019.01 | Ubuntu17.04 | CurlException: Couldn't resolve host name | UploadFile_Success
10/19 | 20171019.01 | Ubuntu17.04 | CurlException: Couldn't resolve host name | UploadFile_Success
10/19 | 20171019.01 | Ubuntu17.04 | CurlException: Couldn't resolve host name | RequestHeaders_AddHostHeaderAndSendRequest_ExpectedResult
10/24 | 20171024.02 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success
10/25 | 20171025.02 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
10/25 | 20171025.05 | Fedora25 | CurlException: SSL connect error | UploadFile_Success
10/28 | 20171028.03 | Fedora26 | CurlException: SSL connect error | UploadString_Success
10/29 | 20171029.01 | Fedora25 | CurlException: SSL connect error | UploadFile_Success
11/3 | 20171103.01 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success
11/3 | 20171103.08 | Fedora26 | CurlException: SSL connect error | UploadData_Success
11/4 | 20171104.04 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success
11/8 | 20171108.02 | Fedora25 | CurlException: SSL connect error | OpenWrite_Success
11/13 | 20171113.01 | Fedora26 | CurlException: SSL connect error | UploadData_Success
11/15 | 20171115.03 | Fedora25 | CurlException: SSL connect error | UploadFile_Success
11/16 | 20171116.51 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success
11/19 | 20171119.01 | Fedora26 | CurlException: SSL connect error | UploadData_Success
11/29 | 20171129.01 | Fedora26 | CurlException: SSL connect error | UploadData_LargeData_Success
12/10 | 20171210.01 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | UploadFile_Success
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | UploadFile_Success
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | RequestHeaders_AddHostHeaderAndSendRequest_ExpectedResult
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | UploadString_Success
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | UploadString_Success
12/13 | 20171213.03 | Win7 | WinHttpException: The server name or address could not be resolved | UploadFile_Success
12/13 | 20171213.11 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
12/14 | 20171214.03 | Fedora26 | CurlException: SSL connect error | UploadData_Success
12/16 | 20171216.06 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
12/17 | 20171217.02 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
12/28 | 20171228.02 | Fedora26 | CurlException: SSL connect error | UploadData_Success
1/7 | 20180107.01 | Fedora26 | CurlException: SSL connect error | OpenWrite_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180107.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FOpenWrite_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/9 | 20180109.01 | Fedora26 | CurlException: SSL connect error | UploadFile_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180109.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/19 | 20180119.06 | Fedora26 | CurlException: SSL connect error | UploadData_LargeData_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180119.06/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadData_LargeData_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/22 | 20180122.02 | Fedora26 | CurlException: SSL connect error | UploadFile_Success -[link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180122.02/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/28 | 20180128.01 | Fedora26 | CurlException: SSL connect error | UploadFile_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180128.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/30 | 20180130.01 | Fedora26 | CurlException: SSL connect error | UploadFile_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180130.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
1/31 | 20180131.01 | Fedora26 | CurlException: SSL connect error | UploadFile_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180131.01/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
2/2 | 20180202.05 | Fedora26 | CurlException: SSL connect error | UploadFile_Success - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180202.05/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx))
3/7 | 20180307.03 | Fedora26 | CurlException: SSL connect error | UploadFile_Success
3/13 | 20180313.03 | Fedora26 | CurlException: SSL connect error | UploadFile_Success

**Comment by davidsh** [comment] 2017-12-22 21:47
These errors might be due to DNS resolution issues on the test machines or infrastructure.  They are not necessarily that the actual test servers are unavailable.

**Comment by karelz** [comment] 2017-12-22 22:08
Fair, title changed.

It would be still good to mark all errors against remote servers in a unified way for easier categorization and filtering out noise from real test failures - no matter if the remote server errors are caused by infra misconfiguration, or real remote server hiccup.

**Comment by karelz** [comment] 2017-12-22 23:18
@wfurt it seems it is often broken on Fedora25 and Fedora26. Maybe some occasional misconfiguration?
All these tests hit remote servers and are unable to do so.

**Comment by wfurt** [comment] 2017-12-28 00:33
I don't know. We don't have enough evidence to triage.  I can run tests on Fedora to see if I can reproduce it. I can also try to get repro snapshot on next failure. With the WinHttpException there is probably more than just Fedora.

**Comment by karelz** [comment] 2017-12-28 21:40
On 2017/**11/16** - build **20171116.51** there was even larger number of test failures:
* 1 failure of OpenWrite_Success test on Fedora26 - see this issue
* 4 failures of NameResolution tests on SLES12 - #24355
* 15 failure of TcpClientTests on Ubuntu17.04:
  * `System.Net.Http.Functional.Tests.HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test` / [`InvalidCertificateServers_CertificateValidationDisabled_Succeeds`](https://github.com/dotnet/corefx/blob/1adc5b27283de6e9627e183ef24e0631ee7bab9a/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AcceptAllCerts.cs#L70) - 4x
  * `System.Net.Http.Functional.Tests.ManagedHandler_HttpClientHandler_ServerCertificates_Test` / [`UseCallback_BadCertificate_ExpectedPolicyErrors`](https://github.com/dotnet/corefx/blob/1adc5b27283de6e9627e183ef24e0631ee7bab9a/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ServerCertificates.cs#L337) - 3x
  * `System.Net.Sockets.Tests.TcpClientTest`
    * [`ConnectAsync_DnsEndPoint_Success`](https://github.com/dotnet/corefx/blob/7eba4bf88983ac276348ea1626c81595e1b237c6/src/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs#L131) - 6x
    * [`Connect_DnsEndPoint_Success`](https://github.com/dotnet/corefx/blob/7eba4bf88983ac276348ea1626c81595e1b237c6/src/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs#L188) - 1x
    * [`Properties_PersistAfterConnect`](https://github.com/dotnet/corefx/blob/7eba4bf88983ac276348ea1626c81595e1b237c6/src/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs#L380) - 1x

OS | Error message | Test
-- | -- | --
Fedora26 | CurlException : Couldn't connect to server | 2x InvalidCertificateServers_CertificateValidationDisabled_Succeeds
Fedora26 | SocketException : Connection refused | 2x [ManagedHandler] InvalidCertificateServers_CertificateValidationDisabled_Succeeds
Fedora26 | SocketException : Connection refused | 3x [ManagedHandler] UseCallback_BadCertificate_ExpectedPolicyErrors
Ubuntu17.04 | ExtendedSocketException : No such device or address | 6x ConnectAsync_DnsEndPoint_Success
Ubuntu17.04 | ExtendedSocketException : No such device or address | Connect_DnsEndPoint_Success
Ubuntu17.04 | ExtendedSocketException : No such device or address | Properties_PersistAfterConnect

**Comment by Priya91** [comment] 2018-01-18 01:14
Failed again in CI here: https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5ea2021bec9ad75556bd5ce2c23784f35f4fafb5/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.SyncWebClientTest~2FUploadData_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by Priya91** [comment] 2018-01-19 19:53
https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3542bcf21a328e227799a4b84475328d7ffed3ff/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by Priya91** [comment] 2018-01-19 19:54
https://mc.dot.net/#/user/Priya91/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/3542bcf21a328e227799a4b84475328d7ffed3ff/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.TaskWebClientTest~2FUploadFile_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by Priya91** [comment] 2018-01-19 19:54
Failed again in CI in PR #26435

**Comment by stephentoub** [comment] 2018-02-13 13:37
Again here:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/ef885152773a91855c00b36b7863acfb32d2a968/workItem/System.Net.WebClient.Tests/analysis/xunit/System.Net.Tests.SyncWebClientTest~2FUploadString_Success(echoServer:%20https:~2F~2Fcorefx-net.cloudapp.net~2FEcho.ashx)

**Comment by davidsh** [comment] 2018-05-25 19:55
While this test issue is titled with a generalized problem, "Test failures: Remote servers unreachable", the problem is all within the System.Net.WebClient tests.

I think the solution here to improve test reliability is to change the tests to use the loopback server. These tests were written before we had the src/Common/tests loopback server class.

**Comment by stephentoub** [comment] 2019-03-13 19:37
@wfurt, should this issue remain open or can it be closed now?

**Comment by davidsh** [comment] 2019-03-13 19:49
I suggest we close this.  There are probably other more specific and more actionable issues in the repo.

**Closed** 2019-03-13 19:49 UTC
Labels: area-System.Net, test bug, test-run-core
