### ISSUE TITLE
Get AdministratorsMembers SIDs

### ISSUE THREAD

**Issue by mferraricloudsurfers** [dotnet/corefx#30011] opened 2018-05-31 12:51 UTC
I wrote this function to retrieve all Administrators Members SIDs:

```c#
private IList<byte[]> GetAdministratorsMembersSIDs()
{
    IList<byte[]> adminMembers = new List<byte[]>();

    SecurityIdentifier id = new SecurityIdentifier(administratorsSid);
    string name = id.Translate(typeof(NTAccount)).Value.Split('\\')[1];

    using (DirectoryEntry adminGroupEntry = new DirectoryEntry(string.Format("WinNT://./{0},group", name)))
    {                
        foreach (object member in (IEnumerable)adminGroupEntry.Invoke("Members"))
        {
            using (DirectoryEntry memberEntry = new DirectoryEntry(member))
            {
                adminMembers.Add((byte[])memberEntry.InvokeGet("objectSid"));
            }
        }
    }

    return adminMembers;
}
```

In .NET Core 2.1 adminGroupEntry.Invoke("Members") throw a System.PlatformNotSupportedException: IDispatch and IDispatchEx are not supported.
Anyone knows a workaround compatible in .NET Core 2.1 ?

**Comment by michielpeeters** [comment] 2018-07-03 09:36
I'm experiencing the exception only it is not related to the code above. When calling the group.GetMembers(true) it throws IDispatch and IDispatchEx PlatformNotSupported exception. When I change this code to the full dotnet framework, everything is starting to work. I'm running the application on windows (local machine) and I'm trying to understand why it isn't working :-).

```csharp
            var members = new List<string>();

            try
            {
                var context = new PrincipalContext(ContextType.Machine);

                using (context)
                {
                    foreach (var groupName in new [] { "Group-1", "Group-2"})
                    {
                        using (var group = GroupPrincipal.FindByIdentity(context, groupName))
                        {
                            if (group == null)
                            {

                                continue;
                            }

                            var users = group.GetMembers(true);
                            foreach (var principal in users)
                            {
                                if (!(principal is UserPrincipal user))
                                    continue;

                                if (!members.Contains(user.Name))
                                    members.Add(user.Name);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                members = new List<string>();
            }
```

**Comment by jkotas** [comment] 2018-07-03 17:49
> IDispatch and IDispatchEx are not supported.

cc @AaronRobinsonMSFT @luqun @jeffschwMSFT

**Comment by AaronRobinsonMSFT** [comment] 2018-07-03 18:28
@michielpeeters We are presently looking into add some support for CoreCLR when running on Windows. Some of this work will be related to [coreclr#18640](https://github.com/dotnet/coreclr/issues/18640).

Unfortunately as implied by the exception at present this is unsupported.

**Comment by luqunl** [comment] 2018-07-04 00:10
The root cause is related to lack of custommarshaller support. if you are blocked, you can try to use/implement the workaround mentioned in https://github.com/dotnet/corefx/issues/26257

**Comment by jkoritzinsky** [comment] 2018-12-11 19:41
This should be fixed as of dotnet/coreclr#21343 getting merged in.

**Closed by jkoritzinsky** 2018-12-11 19:41 UTC
Labels: area-System.DirectoryServices, area-System.Runtime.InteropServices, question

**Comment by michaelschmit** [comment] 2019-05-31 16:24
I'm running core 3.0 preview 5 and still seem to be running into this issue.  I'm doing a directoryEntry.Invoke("Members", null).  It fails with a IDispatch and IDispatchEx not supported error, but works on .NET framework.

**Comment by jkoritzinsky** [comment] 2019-05-31 17:07
@michaelschmit can you create a small repro? I can't reproduce the failure on 3.0 preview 5.

**Comment by michaelschmit** [comment] 2019-05-31 18:26
I will work on getting that together.  In the meantime I wanted to state that I'm using LDAP in this case to grab members from an AD group.  I'm not sure if that is supported in core or not.  I've been having a hard time finding concrete answers on some of this stuff.

**Comment by AaronRobinsonMSFT** [comment] 2019-05-31 21:18
@michaelschmit Thanks for the clarifying. Glad all it working now.

**Comment by mtschneiders** [comment] 2019-05-31 21:36
Is there a way to make it work on .net 2.2? 
I'm specifically dealing with this error on getting Active Directory group members via the System.DirectoryServices.AccountManagement namespace.

**Comment by AaronRobinsonMSFT** [comment] 2019-05-31 21:43
@mtschneiders Unfortunately not. Enabling this feature required supporting `IDispatch`. The support of `IDispatch` required a lot of work throughout the runtime and there is no plan to port that support down to 2.2.

**Comment by mtschneiders** [comment] 2019-05-31 21:46
@AaronRobinsonMSFT OK, thanks.
