### ISSUE TITLE
WinHttpException: The connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by ManuelDev1810** [dotnet/corefx#29888] opened 2018-05-24 08:52 UTC
I am getting this error doing a Get Request. This is code that I've made.

       public async Task<Image> GetImg(int id)
        {
            try
            {
                HttpResponseMessage httpresponse = await client.GetAsync("/api/home/" + id);
                string stringresponse = await httpresponse.Content.ReadAsStringAsync();
                Image image = JsonConvert.DeserializeObject<Image>(stringresponse);
                return image;

            } catch(Exception e)
            {
                throw e;
            }
        }

The request go to the Image Repository and get the data like this, I have to say that without the include all works just fine.

        public async Task<Image> Image(int id)
        {
            try
            {
                Image image = await context.Images.Include(m => m.Comments)
                    .ThenInclude(a => a.Image).SingleOrDefaultAsync(m => m.Id == id);
                return image;

                //Image image = await context.Images.SingleOrDefaultAsync(m => m.ImageId == id);
                //return image;
            }
            catch(Exception e)
            {
                throw e;
            }
        }

How you see, the data it's obtained correctly the problem is that after this it starts to read the Models in the Api and when get to Image relationship in the Comment class, throw the exception.

    public class Comment
    {
        public int Id { get; set; }
        [Required]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        public int ImageId { get; set; }
        [ForeignKey("ImageId")]
        public Image Image { get; set; }

        public string UserId { get; set; }
    }

When it reads the Image object that I create, throws the exception.

    An unhandled exception occurred while processing the request.
    WinHttpException: The connection with the server was terminated abnormally
     Unknown location

    IOException: The read operation failed, see inner exception.
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

    HttpRequestException: Error while copying content to a stream.     
    ExquisiteImages.Infrastructure.ImageClient.ImageClient+<GetImg>d__2.MoveNext() in ImageClient.cs, 
     line 42.

     WinHttpException: The connection with the server was terminated abnormally

Relationships

    public class Image
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Path { get; set; }
        [Required]
        public string Description { get; set; }
        public DateTime Date { get; set; }
        [Required]
        public string UserId { get; set; }

        public List<Comment> Comments { get; set; }
    }

    public class Comment
    {
        public int Id { get; set; }
        [Required]
        public string Content { get; set; }

        public DateTime Date { get; set; }

        public int ImageId { get; set; }
        [ForeignKey("ImageId")]
        public Image Image { get; set; }

        public string UserId { get; set; }
    }

**Comment by ManuelDev1810** [comment] 2018-05-25 12:51
@karelz  Sorry I am a little noob. I'm not understand English very well. I am going to try Fiddler or 
Wireshark. I didn't even knew those guys.  Can you explain me what do you men by 100% repro?

I am using .Net Core 2.0.

**Comment by davidsh** [comment] 2018-05-25 18:32
>Can you explain me what do you mean by 100% repro?

It means "does this problem always occur?".  In order to troubleshoot this, please submit (via ZIP file) a complete, small, solution (Visual Studio solution etc.) so that we can compile the code and run it under the debugger to see the problem.

**Comment by ManuelDev1810** [comment] 2018-05-26 00:08
Oh thanks for the answer about 100% repro. In that case @davidsh @karelz  is not 100% repro, because the exception only occurs when I use Eager Loading to get the Comments of the Image.

If I use this code works : Image image = await context.Images.SingleOrDefaultAsync(m => m.Id == id);
If I use this it doesn't work:      Image image = await context.Images.Include(m => m.Comments)
                                                 ThenInclude(a => a.Image).SingleOrDefaultAsync(m => m.Id == id);

@davidsh  This is the solution of my Project, thank you very much to both of you.

[ExquisiteImages.zip](https://github.com/dotnet/corefx/files/2041130/ExquisiteImages.zip)

**Comment by davidsh** [comment] 2018-05-26 04:18
Thanks for submitting the ZIP file.

You indicated above that you thought you were running .NET Core 2.1.  According to the CSPROJ file, you are still targeting and building with the .NET Core 2.0 libraries.  That is why you still see the WinHttpException at times.

You need to change your CSPROJ so that you can target .NET Core 2.1.

Here is one of your CSPROJ files, 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
```

**Comment by ManuelDev1810** [comment] 2018-05-26 04:54
Thank you very much @davidsh I am going to do the guidance and then I am going to tell you what happen.

**Comment by ManuelDev1810** [comment] 2018-05-26 06:15
How you said @davidsh  the exception has changed.

An unhandled exception occurred while processing the request.
SocketException: An existing connection was forcibly closed by the remote host
Unknown location

IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)

HttpRequestException: Error while copying content to a stream.
ExquisiteImages.Infrastructure.ImageClient.ImageClient.GetImg(int id) in ImageClient.cs, line 42

**Comment by davidsh** [comment] 2018-05-26 14:49
On .NET Core 2.0, the WinHttpException is **"The connection with the server was terminated abnormally"**.

On .NET Core 2.1, the SocketException is **"An existing connection was forcibly closed by the remote host"**.

Both of them mean the same thing. These exceptions are being caused by the server disconnecting the client abruptly.    

The server in this case is a localhost server ASP.NET MVC project.  This appears to be either a bug in the ASP.NET code or in your project, ExquisiteImagesApi, that builds on ASP.NET.

ASP.NET bugs/issues are not tracked here. I suggest you open up a bug in the ASP.NET Core Repo. 
https://github.com/aspnet/home

They will be able to help you further.  You should link to this issue as well to give them more information.

cc: @Tratcher

**Comment by davidsh** [comment] 2018-05-30 22:13
@ManuelDev1810 Looks like this issue might be due to a problem with your ASP.NET code as suggested by @Tratcher .  So, we'll close this issue for now.

Also, .NET Core 2.1 has been released now.  Please try out the final build:
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Closed by davidsh** 2018-05-30 22:13 UTC
Labels: area-System.Net.Http, needs more info, question
