### ISSUE TITLE
Enable compilation from CodeDOM

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#25555] opened 2017-11-28 19:34 UTC
Reported by @jlahteen:

> However, the current version of [System.CodeDom](https://github.com/dotnet/corefx/tree/master/src/System.CodeDom) throws PlatformNotSupported for every CompileAssembly* method of [CSharpCodeGenerator](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.cs) since they all end up to the method [FromFileBatch](https://github.com/dotnet/corefx/blob/master/src/System.CodeDom/src/Microsoft/CSharp/CSharpCodeGenerator.PlatformNotSupported.cs) which throws that exception systematically. Just wondering whether this is still the current state of development or should it already work. Everything works well in my experiment project if I just change the target framework from netcoreapp2.0 to net462.

That's unfortunately by-design as the compilers are not part of the .NET Core runtime. However, given that CodeDOM isn't referenced by the core (it only comes in when people depend on it/via the compat pack) we could probably fix this.

@weshaggard, any reason why the CodeDOM NuGet package couldn't depend on Roslyn? Practically speaking, folks depending on CodeDOM probably need to compile anyways so probably end up pulling in Roslyn anyway. The benefit of us doing it avoids consuming code having to pipe the data & settings correctly through to Roslyn.

**Comment by stephentoub** [comment] 2017-11-28 19:54
https://github.com/dotnet/corefx/issues/12180

**Comment by karelz** [comment] 2017-11-29 20:33
Closing as dupe of #12180

**Closed by karelz** 2017-11-29 20:33 UTC
Labels: area-System.CodeDom
