### ISSUE TITLE
List<T>.Sort(Comparison<T>) does not increment internal version, allowing enumeration to continue

### ISSUE THREAD

**Issue by CodeCasterNL** [dotnet/corefx#15028] opened 2017-01-10 11:04 UTC
A `List<T>` internally keeps a version number to prevent modification while enumerating. Every modification to the list should therefore increment the version number.

This does happen in `Add(T)`, `Remove(T)`, `Clear()`, `Sort()` and perhaps other methods, but **not** in [`Sort(Comparison<T>)`](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Collections/src/System/Collections/Generic/List.cs#L1095). The following code does not throw the expected exception _"Collection was modified; enumeration operation may not execute"_:

```
var list = new List<string>
{
    "foo",
    "bar",
};

foreach (var l in list)
{
    Console.WriteLine(l);
    list.Sort((x, y) => x.CompareTo(y));
}
```

But instead prints:

> foo
> foo

**Comment by mikedn** [comment] 2017-01-10 13:27
Dupe of https://github.com/dotnet/coreclr/issues/8071

**Comment by CodeCasterNL** [comment] 2017-01-10 13:32
@mikedn thanks. Don't know why I didn't find that one.

**Closed** 2017-01-10 13:59 UTC
