### ISSUE TITLE
(Packaging issue in System.IO.FileSystem) System.IO.File in .NET Standard library fails when run in unit test 

### ISSUE THREAD

**Issue by smadala** [dotnet/corefx#16322] opened 2017-02-20 14:59 UTC
_From @davkean on January 20, 2017 3:49_

_From @gulbanana on December 16, 2016 11:28_

Possibly this issue should be in a vstest repository but I can't find one.
Repro: https://github.com/gulbanana/repro-netstandard-systemio

When using System.IO in a .NET Standard 1.4 class library, unit tests referencing the library fail. The error is
`Message: System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

_Copied from original issue: dotnet/roslyn-project-system#975_

_Copied from original issue: Microsoft/vstest#363_

**Comment by smadala** [comment] 2017-02-20 14:59
_From @davkean on January 20, 2017 3:49_

_From @srivatsn on December 16, 2016 20:31_

@codito

**Comment by smadala** [comment] 2017-02-20 14:59
_From @davkean on January 20, 2017 3:49_

_From @srivatsn on December 20, 2016 22:57_

@dotnet/vstest

**Comment by smadala** [comment] 2017-02-20 14:59
_From @davkean on January 20, 2017 3:49_

_From @codito on December 21, 2016 12:50_

We're investigating this issue. As a workaround, please use `<PackageReference Include="NETStandard.Library" Version="1.6.0" />` instead of `1.6.1` in netstdlib.csproj.

**Comment by smadala** [comment] 2017-02-20 14:59
_From @davkean on January 20, 2017 3:49_

_From @gulbanana on December 21, 2016 13:47_

I've verified that the workaround works on my system (until I want to use a nuget package which references 1.6.1 :-) )

**Comment by smadala** [comment] 2017-02-20 14:59
There is mismatch between version number of `.nuget\packages\system.io.filesystem\4.3.0\ref\netstandard1.3\System.IO.FileSystem.dll (4.0.1)` and `.nuget\packages\system.io.filesystem\4.3.0\lib\net46\System.IO.FileSystem.dll(4.0.2)`.
There is no .nuget\packages\system.io.filesystem\4.3.0\lib\netstandard1.3\System.IO.FileSystem.dll file.

Due this mismatch System.IO.FileSystem 4.0.1 getting bind in compile time. which is not found in runtime.

This issue can be repro with simple console app referring netstdlib.

[Sln with console app - repro-netstandard-systemio.zip](https://github.com/Microsoft/vstest/files/787770/repro-netstandard-systemio.zip)

**Comment by smadala** [comment] 2017-02-20 14:59
_From @codito on February 20, 2017 14:55_

@smadala packaging issue in corefx?

**Comment by smadala** [comment] 2017-02-20 14:59
Could be, moving to corefx.

**Comment by ianhays** [comment] 2017-03-10 20:52
cc @ericstj @mellinoe for packaging.

**Comment by ericstj** [comment] 2017-03-13 17:22
Mismatch is expected.  You need to use bindingRedirects with any of these packages.

**Comment by daveaglick** [comment] 2017-03-13 20:39
FWIW, I'm seeing something similar to this when using Roslyn 2.0.0 from within an MSBuild task (the fact that's it's an MSBuild task is probably not germaine, other than that it makes diagnosing the binding problems harder).

I've tried every combination of binding redirects I can think of without luck. I've also tried installing System.IO.FileSystem 4.3.0 directly into the MSBuild task project without any change.

Note that while the example below was created for use in a test, I'm not running it through the unit testing framework here - this is directly calling MSBuild on the test solution from the console to eliminate the unit test framework as a source of problems.

<details>
<summary>Output</summary>

```
e:\Code\Scripty\src\Scripty.MsBuild.Tests>"C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" /p:ScriptyAssembly="E:\Code\Scripty\src\Scripty.MsBuild.Tests\bin\Debug\Scripty.MsBuild.dll";Include1=true;Include3=true
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/13/2017 4:24:57 PM.
Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" (1) is building "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolu tion\Proj\Proj.csproj" (2) on node 1 (default targets).
EvaluateScriptyFiles:
  Starting out-of-process script evaluation...
  Arguments: --solution "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" --p "ScriptyAssembly=E:\Code\Scripty\src\Scripty.MsBu
  ild.Tests\bin\Debug\Scripty.MsBuild.dll" --p "Include1=true" --p "Include3=true" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\P
  roj.csproj" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Test.csx"
  Finished script evaluation
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System .IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file spec ified. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : File name: 'System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture= neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [E:\Code\Scripty\src\Scripty.MsBui ld.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.3 0319\clr.dll [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Running under executable  E:\Code\Scripty\src\Scripty.MsBuild.Tests\bin\ Debug\Scripty.exe [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : --- A detailed error log follows.  [E:\Code\Scripty\src\Scripty.MsBuild. Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : === Pre-bind state information === [E:\Code\Scripty\src\Scripty.MsBuild. Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :  (Fully-specified) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolu tion\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Appbase = file:///E:/Code/Scripty/src/Scripty.MsBuild.Tests/bin/Deb ug/ [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Initial PrivatePath = NULL [E:\Code\Scripty\src\Scripty.MsBuild.Tes ts\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Calling assembly : Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neut ral, PublicKeyToken=31bf3856ad364e35. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : === [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj. csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: This bind starts in default load context. [E:\Code\Scripty\src\Scri pty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using application configuration file: E:\Code\Scripty\src\Scripty.M sBuild.Tests\bin\Debug\Scripty.exe.Config [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using host configuration file:  [E:\Code\Scripty\src\Scripty.MsBuil d.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Fram ework\v4.0.30319\config\machine.config. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem.DLL. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.DLL. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem.EXE. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.EXE. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Roslyn.Utilities.FileUtilities.OpenFileStream(String path) [E:\Cod e\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInterna l(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\Sample Solution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFrom Assembly(Assembly assembly) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__D isplayClass4_0`2.<SelectChecked>b__0(T item) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() [E:\Co de\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRan geChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj .csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ToImmu tableArrayChecked[T](IEnumerable`1 items, String parameterName) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnu merable`1 references) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnu merable`1 references) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Scripty.Core.ScriptEngine.<Evaluate>d__6.MoveNext() in E:\Code\Scr ipty\src\Scripty.Core\ScriptEngine.cs:line 74 [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
  Output file count: 0
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "Manage dMinimumRules.ruleset". [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Proj -> E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\bin\Debug\ProjA.dll
Done Building Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj" (default targets).

Done Building Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" (default targets).


Build succeeded.
```

</details>

**Comment by Portikus** [comment] 2017-03-17 08:01
I had a similar issue with "System.Runtime.Serialization.Primitives". I have the same structure, a .netstandard 1.4 library and a net461 UnitTest project.
Adding System.Runtime.Serialization.Primitives nuget package (Version 4.1.1)  to the UnitTest project works as a workaround.

**Comment by olegtk** [comment] 2017-04-02 04:51
Any updates on this? What's a workaround for project.json based projects?

**Comment by gulbanana** [comment] 2017-04-03 10:12
Here's an example of the binding redirects I had to write recently to use Roslyn 2.0.0 in an old-msbuild test project.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.1.0" newVersion="1.2.1.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Algorithms" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by ericstj** [comment] 2017-04-03 15:41
As @gulbanana suggests you can workaround this by manually specifying the bindingRedirects in the old tooling.  For MSBuild based tooling please see https://github.com/Microsoft/msbuild/issues/1310 that is tracking missing bindingRedirects for dlls. 

Closing this issue since the problem is in the tooling.

**Closed by ericstj** 2017-04-03 15:41 UTC
Labels: area-System.IO, bug

**Comment by olegtk** [comment] 2017-04-03 17:32
@gulbanana, @ericstj That doesn't help, now 4.0.2.0 is not found. How do I know which version should I redirect to? My lib is just targeting .netstandard 1.3.

**Comment by gulbanana** [comment] 2017-04-03 18:21
I found out what versions to use by examining the contents of the bin/Debug folder and opening the DLLs with ilspy to discover their AssemblyVersion. I don't think this issue should be closed - it's a terrible UX and it will never be realistic to expect all .net hosts and tools to work around it.

**Comment by ericstj** [comment] 2017-04-03 19:29
That sounds like more reason to push MSBuild to fix automatic bindingRedirects.  AssemblyVersion mismatches are a reality of the package-based ecosystem.  The .NET Core loader handles them, but desktop still requires bindingRedirects.  We need a central fix for this.  Please ref-count the MSBuild issue or open a new one if you don't think its covered by existing issues.

**Comment by asanx** [comment] 2017-04-12 21:16
It sounds funny, but adding Nuget package "System.IO.FileSystem" to the test project resolved the issue.
Have the same set:
- NETStandard 1.4 class library + Nuget package "System.IO.FileSystem"
- NET Framework 4.6.1 project + NUnit

**Comment by olegtk** [comment] 2017-04-27 02:12
@asanx which version? I guess you were just lucky to add specifically the version you needed. Doesn't work for me.

**Comment by juandrn** [comment] 2017-05-29 18:12
I've solve this adding 
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
in .csproj file.
Ref:
https://msdn.microsoft.com/en-us/library/2fc472t2.aspx

**Comment by Jose-CF** [comment] 2017-06-13 07:06
Any updates other than hack manually the binding redirects ... ?

**Comment by ericstj** [comment] 2017-06-13 16:26
@Jose-CF if you're still seeing issues with the automatic generated bindingRedirects in MSBuild it'd be good to file that issue in the MSBuild repository.

**Comment by dazinator** [comment] 2017-07-26 16:27
I experienced this with my xunit project not generating binding redirects. You also have make sure you have this:

```
 <OutputType>Exe</OutputType>
```

As binding redirects are only generated for executables not libraries.

**Comment by kzu** [comment] 2017-08-28 12:46
I think the underlying cause for this is that the nuget package for System.IO.FileSystem (i.e. [4.3.0](https://www.nuget.org/packages/System.IO.FileSystem/4.3.0) at the moment) contains:

- ref\netstandard1.3\System.IO.FileSystem.dll, version 4.0.1.0
- lib\net46\System.IO.FileSystem.dll, version 4.0.2.0

This looks like a serious packaging mistake to me. netstandard libraries compiled against this package will bind to 4.0.1.0 and as a consequence, *everyone* else consuming the library MUST do the binding redirect just to get a *core* scenario working, since they will get whichever platform lib they need, which will *always* be the wrong version.

It should be considered a build error to generate a package that contains different version numbers between the ref and lib assemblies, since this pretty much guarantees you will get binding errors at runtime. 

Also, consider that not all "hosts"/apps can control what binding redirects are applied (i.e. a VS extension can hardly make a decision on provinding a binding redirect for such a core assembly without risking breaking everyone else).

Maybe there is an actual design decision that went into making the versioning inconsistent within the same package. If so, I'd love to know it so I can understand how this applies (or not) to other nuget authoring scenarios.

**Comment by bradwilson** [comment] 2017-08-28 15:13
Binding redirects being generated only for executables should be considered a Pri 1 bug.

**Comment by ericstj** [comment] 2017-08-28 15:17
Folks, please direct feedback to the https://github.com/Microsoft/MSBuild repo on this.  https://github.com/Microsoft/msbuild/issues/1310 in particular covers making that work for class libraries.  IMO it should also be the default for every project.

**Comment by ericstj** [comment] 2017-08-28 15:42
> this looks like a serious packaging mistake to me. netstandard libraries compiled against this package will bind to 4.0.1.0 and as a consequence, everyone else consuming the library MUST do the binding redirect just to get a core scenario working

That's not a mistake, it is very intentional.

In a nutshell, here is how we **must** version the assemblies in those packages:
1. Desktop assemblies must always have a matching version for ref and lib so that they get correct binding redirects.
2. Desktop assemblies must version with every release of the package so that folks don't get downgraded when someone installs an older version of the package in the GAC.
3. NETStandard reference assemblies which have external implementers (EG: inbox in xamarin, desktop) can never version since that would put them at a higher version than external implementers.

That results in bindingRedirects on desktop, but really just the first two criteria are sufficient (which *ANY* package that ships a desktop implementation must follow).  The fact that we cannot version the netstandard refs makes it more common.

**Comment by ericstj** [comment] 2017-08-28 15:47
Furthermore.  We realize how painful this can be, which is why in netstandard 2 we reduced the number of assemblies to 1, and it *only* represents what's inbox in the framework.  That way we no longer need to distribute new assemblies of the pieces that make up netstandard surface area in packages.

We will still run into some of the versioning constraints like this once we start to graduate things from packages to the framework (System.ValueTuple, System.Memory) but moving forward those problems only exist along the transition as opposed to forever in the future.
