### ISSUE TITLE
Change ref projects to .NET Core

### ISSUE THREAD

**Issue by rahku** [dotnet/corefx#11682] opened 2016-09-13 19:10 UTC
These AppContext APIs can be in .NET Core but not .NET Standard yet. We will need to change these these ref projects to .NET Core. 
Check file src/System.Runtime/src/ApiCompatBaseline.net463.txt
https://github.com/dotnet/corefx/pull/11275/files#r78505041

**Comment by karelz** [comment] 2016-11-16 21:41
@weshaggard what is this issue tracking? Even @AlexGhiondea doesn't understand.

**Comment by karelz** [comment] 2016-11-16 21:42
Actually looks like dupe of #12456.

**Comment by ericstj** [comment] 2016-11-16 21:43
It's not a dup.  These were APIs previously added for all platforms but they need to be scoped to just NETCore.

**Comment by ericstj** [comment] 2016-11-16 21:47
Specifically: https://github.com/dotnet/corefx/blob/b8701fabcded3a340b09779bad9f89c1821a05e8/src/System.Runtime/ref/System.Runtime.cs#L87 needs to be if'defed so that it isn't in the netstandard reference assembly.

Surround it in `#if netcoreapp11` and remove https://github.com/dotnet/corefx/blob/b8701fabcded3a340b09779bad9f89c1821a05e8/src/System.Runtime/src/ApiCompatBaseline.net463.txt

**Comment by AlexGhiondea** [comment] 2016-11-16 21:55
@ericstj that should cover both GetData and TargetFrameworkName, right?

**Comment by ericstj** [comment] 2016-11-16 21:56
Whichever ones were not in net461.

**Closed** 2016-11-17 17:24 UTC
Labels: area-System.AppContext
