### ISSUE TITLE
Add a JsonAttribute to allow null-value handling on a per-property basis

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#39416] opened 2019-07-11 23:35 UTC
The ask is for an attribute that does the equivalent of `JsonSerializerOptions.IgnoreNullValues` on a per property basis.

**Comment by stephentoub** [comment] 2019-07-12 01:54
I'm marking this as Future.  If that's not correct, please add more details.

**Comment by layomia** [comment] 2019-11-23 09:49
Closing as a duplicate of https://github.com/dotnet/corefx/issues/40600 which discusses conditional igoring on a per-property basis.

**Closed by layomia** 2019-11-23 09:49 UTC
Labels: api-needs-work, area-System.Text.Json
