### ISSUE TITLE
ValueTuple.IStructuralComparable/Equatable throws NRE instead of ArgumentNullException

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#13429] opened 2016-11-07 16:16 UTC
The following tests demonstrates this.
```
[Fact]
public void IStructuralEquatable_Equals_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralEquatable structuralEquatable = ValueTuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralEquatable.Equals(Tuple.Create(1), null));
}

[Fact]
public void IStructuralEquatable_GetHashCode_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralEquatable structuralEquatable = ValueTuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralEquatable.GetHashCode(null));
}

[Fact]
public void IStructuralComparable_CompareTo_NullEqualityComparer_ThrowsNullReferenceException()
{
    IStructuralComparable structuralComparable = ValueTuple.Create(1);
    Assert.Throws<NullReferenceException>(() => structuralComparable.CompareTo(Tuple.Create(1), null));
}
```

Spun off from #13410

/cc @karelz (who can help triage this :) )

**Comment by karelz** [comment] 2016-11-07 16:48
@terrajobst @weshaggard @stephentoub do we have room to tweak ValueTuple to follow the right patterns? I think we don't have the huge compatibility burden yet.

**Comment by weshaggard** [comment] 2016-11-07 18:03
@jcouv would be able to talk to this

**Comment by jcouv** [comment] 2016-11-07 18:49
@karelz Let me check with F# folks. I tried to keep `ValueTuple` as close as possible to `Tuple` for their purpose.

**Comment by jcouv** [comment] 2016-11-07 19:54
Talked with @KevinRansom and he confirmed that matching the logic to `System.Tuple` should take precedence over any conventions (although reasonable), so that we facilitate users switching between `Tuple` and `ValueTuple` without having to remember to update their exception-checking code.

So we recommend resolving this issue as "by design".

**Comment by hughbe** [comment] 2016-11-07 20:00
Awesome - I'll close this when I send in some tests documenting the behaviour

**Closed** 2016-11-09 14:21 UTC
Labels: area-System.Runtime, bug
