### ISSUE TITLE
NewExpression without constructor for certain system type

### ISSUE THREAD

**Issue by smitpatel** [dotnet/corefx#21060] opened 2017-06-14 21:25 UTC
```C#
using System;
using System.Linq.Expressions;

namespace NewExpressionWithNullCtor
{
    class Program
    {
        static void Main(string[] args)
        {
            Expression<Func<int, Post>> expression = e => new Post { A = new DateTime() };

            Console.WriteLine((((expression.Body as MemberInitExpression)?.Bindings[0] as MemberAssignment).Expression as NewExpression).Constructor);
            Console.WriteLine((((expression.Body as MemberInitExpression)?.Bindings[0] as MemberAssignment).Expression as NewExpression).Constructor == null);

            Console.WriteLine("Hello World!");
        }

        public class Post
        {
            public DateTime A { get; set; }
        }
    }
}
```
In the `NewExpression` created for `new DateTime()` the `Constuctor` property is null. Looking at the source of `NewExpression`, it does not seem to be possible to define a `NewExpression` without ctor (even need to pass the default parameterless one). So the Expression tree created looks incorrect.

Instead of `new DateTime` if `new Post` is used then property has default ctor. So this seems to be specific to DateTime only (or may be other similar system types)

```
PM> dotnet --info
.NET Command Line Tools (2.0.0-preview2-006443)

Product Information:
 Version:            2.0.0-preview2-006443
 Commit SHA-1 hash:  3a5612f153

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\smpatel\.dotnet\x64\sdk\2.0.0-preview2-006443\
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by svick** [comment] 2017-06-14 21:57
`DateTime` does not actually have a parameterless constructor, so there is no `ConstructorInfo` that could be returned from the `Constructor` property. When you write `new DateTime()`, it's the same as if you wrote `default(DateTime)`, i.e. the `struct` is zero-initialized.

And if you manually call `Expression.New(typeof(DateTime))`, you also get a `NewExpression` with `null` `Constructor`.

So I don't see any issue here, I think everything behaves as it should.

**Comment by smitpatel** [comment] 2017-06-15 00:57
Thanks for explanation. It make sense why certain new operators wouldn't have ctor info. (bit strange regardless)

With regards of `Expression.New(typeof(DateTime))` it seems to have exact type of `NewValueTypeExpression` derived from `NewExpression` but internal type.

Are we saying that NewExpression.Constructor property can be nullable? We just wanted to clarify that, if this is by design or a bug so that we can write our code accordingly.

**Comment by JonHanna** [comment] 2018-02-03 02:18
Yes, it's by design, so that expressions analogous to `new DateTime()`, `new int()` etc. in C# and the equivalent in other languages that create a default instance of a value type without a nullary constructor.

**Comment by OmarTawfik** [comment] 2018-02-05 23:24
Closing per by design.

**Closed by OmarTawfik** 2018-02-05 23:24 UTC
Labels: area-System.Linq.Expressions
