### ISSUE TITLE
About 40% regression or the XmlDocument performance test Create()

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#29260] opened 2018-04-21 03:52 UTC
_From @maryamariyan on April 21, 2018 1:43_

The Regression for the XmlDocument performance test [Create()](https://github.com/dotnet/corefx/blob/697e2b910e6cccbc1f3d58be111e309db4823ab7/src/System.Private.Xml/tests/XmlDocument/Performance/Perf.XmlDocument.cs#L16) is illustrated in the chart below.

<img width="1062" alt="screen shot 2018-04-20 at 6 03 33 pm" src="https://user-images.githubusercontent.com/5897654/39078880-32feeb30-44c5-11e8-9886-3b5f311fb9c5.png">

Refer to [benchview](https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61756]&jobid=94550&) for more details.

@krwq I was looking at the Marvin hashcode commit dotnet/corefx@697e2b9 you submitted in January and it seems when instantiating XmlDocument it suddenly regressed. Was this by design or not intentional?

Overall the regression is about 45% on Linux (and around 30% on Windows). Although the regression seems to have started from January, there have been some ups and downs since so not exactly sure if I can find the exact root cause for the overall regression here in a straightforward way.

The test Create() as seen [here](https://github.com/dotnet/corefx/blob/697e2b910e6cccbc1f3d58be111e309db4823ab7/src/System.Private.Xml/tests/XmlDocument/Performance/Perf.XmlDocument.cs#L16), just attempts to create new XmlDocument() multiple times.

cc: @kouvel @danmosemsft

_Copied from original issue: dotnet/coreclr#17715_

**Comment by jkotas** [comment] 2018-04-21 03:52
_From @RussKeldorph on April 21, 2018 3:48_

@maryamariyan Can you clarify why this was opened in coreclr instead of corefx?

**Comment by maryamariyan** [comment] 2018-04-21 05:13
_From @maryamariyan on April 21, 2018 5:08_

@RussKeldorph please accept my sincerest apology here. This was meant to be created for corefx.

I copied the template from another issue I had opened earlier by right clicking on the "new issue" button (creating the issue in that repo), not noticing the original was already in coreclr.

I was paying much attention to the content of the issue that I missed this detail.

**Comment by stephentoub** [comment] 2018-04-23 13:26
> do we know if benchmark is doing warm up first or does it measure the first iteration as well?

It ignores warmup costs appropriately.

> This particular regression (Create) might be due to static field initialization

That's very unlikely. The XmlDocument ctor is adding more than a dozen strings to the name table, such that each is hashed. That slower hashing is almost certainly the cause, though you could easily test to see.

The values added to the table are constants. This could be addressed by simply adding an Add internal overload that takes the hash code as an argument and caching the result once at the call site to be used on all future calls. If we cared. I agree it's unlikely to matter for most uses of XmlDocument, but it's possible there are some where it does?

**Comment by stephentoub** [comment] 2018-04-24 21:09
It may not matter, but I don't think such a raw look at cost is the way to determine that. We have lots of things that are significantly cheaper than 1μs, and we'd definitely care if we regressed those by 40% (e.g. delegate invocation). The question is whether constructing an XmlDocument is done like this in scenarios where little else is done and it's a hot path.

**Comment by danmosemsft** [comment] 2018-04-24 21:11
You're right, implicit in my statement was the assumption that the constructor is not run on a hot path. I agree that's not based on much evidence.

**Comment by krwq** [comment] 2018-04-24 21:31
I don't think this will be a problem in general and can't think of anything creating XmlDocuments that frequently but since someone decided it is a good idea to measure performance of the constructor it is worth investigating why and if we should care about that. I suspect if it matters anywhere it will be somewhere in the XmlSerializer code.

**Comment by pjanotti** [comment] 2018-05-09 22:33
While I also doubt that it is used in a hot path it can be relevant for some services that create/destroy a high number of XmlDocument instances. I will take a look at it.

**Closed** 2018-05-17 13:06 UTC
Labels: area-System.Xml, tenet-performance
