### ISSUE TITLE
SendRecvPollSync_TcpListener_Socket failed on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7150] opened 2016-03-22 20:32 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/3854/consoleFull
```
12:13:24      System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: False) [FAIL]
12:13:24         System.AggregateException : One or more errors occurred. (Read poll after completion should have succeeded
12:13:24         Expected: True
12:13:24         Actual:   False)
12:13:24         ---- Read poll after completion should have succeeded
12:13:24         Expected: True
12:13:24         Actual:   False
12:13:24         Stack Trace:
12:13:24               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
12:13:24               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
12:13:24            d:\j\workspace\windows_nt_de---06b7984d\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs(506,0): at System.Net.Sockets.Tests.SendReceive.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation)
```

**Comment by ericeil** [comment] 2016-04-25 18:44
I've been unable to reproduce this, even artificially.  I'd guess we're hitting some corner case in Windows itself.  Closing this for now.

**Closed by ericeil** 2016-04-25 18:44 UTC
Labels: System.Net
