### ISSUE TITLE
The method "GetCustomAttributes(this ParameterInfo element, bool inherit)" in CustomAttributeExtensions returns wrong value in case of generated property+method..

### ISSUE THREAD

**Issue by StefH** [dotnet/corefx#7792] opened 2016-04-16 15:13 UTC
The method `var attributes = p.GetCustomAttributes(false);` returns **null** in case the property and get/set-methods are generated using the ILGenerator.

However according to the specifications, it should return:
`A collection of the custom attributes that are applied to <paramref name="element"/>, or an empty collection if no such attributes exist.
`.
For details s this issue #7596.

**Comment by karelz** [comment] 2016-11-28 22:36
Looks like dupe of #7596, or is there something else you meant to track by this issue?

**Closed by karelz** 2016-11-28 22:36 UTC
Labels: area-Microsoft.CSharp
