### ISSUE TITLE
Merge Future branch into Master

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#12505] opened 2016-10-10 16:16 UTC
New APIs were added in the Future branch a while ago. It'd be nice if the changes were merged into Master so we could make the new APIs available in netcoreapp1.1.

https://github.com/dotnet/corefx/compare/future

Some examples:
 - #1384 - Regex group should have a Name property
 - #1783 - Add ConcurrentDictionary GetOrAdd/AddOrUpdate overloads with generic arg
 - #1756 - Implement generic interfaces on Regex collections
 - #2436 - Add async XLinq document/element loading and saving
 - #2862 - Add HashSet<T> ctors with capacity

**Comment by stephentoub** [comment] 2016-10-10 16:23
https://github.com/dotnet/corefx/issues/2869

**Comment by karelz** [comment] 2016-10-10 16:37
Dupe of #2869

**Closed by karelz** 2016-10-10 16:37 UTC
