### ISSUE TITLE
NTLM not working on Linux

### ISSUE THREAD

**Issue by stevenruizhang** [dotnet/corefx#38173] opened 2019-06-03 15:14 UTC
@davidsh , I create one .net core 2.1 project and can run will in my local windows OS. But when i follow the AWS toolkit for VS tool to push that in AWS lambda it will throw GSSAPI issue. I check this is regarding NTLM auth does not work by default on Unix issue, I setup Ubuntu 16.04 VM local and run apt-get -y install gss-ntlmssp, also add AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false) in the dotnet code, finally i got 401 error in ubuntu, do u have any idea how to resolve that ?
Before install gss-ntlmssp and add AppContext.SetSwitch
![image](https://user-images.githubusercontent.com/13114985/58812584-c448f000-8654-11e9-82a1-9fdd6c1d87cf.png)
After install gss-ntlmssp and add AppContext.SetSwitch
![image](https://user-images.githubusercontent.com/13114985/58812525-a4b1c780-8654-11e9-81fa-cbf1f8023ae9.png)
![image](https://user-images.githubusercontent.com/13114985/58812697-f4908e80-8654-11e9-81f5-730533cd3706.png)

_Originally posted by @stevenruizhang in https://github.com/dotnet/corefx/issues/28961#issuecomment-498299281_

**Comment by davidsh** [comment] 2019-06-03 17:56
>@davidsh , I create one .net core 2.1 project and can run will in my local windows OS.

The NTLM bug you reference in #28961 was fixed in .NET Core 3.0.  It is not fixed in .NET Core 2.1.

Please try out .NET Core 3.0 latest Preview:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-5/

If you are still having problems, please update this issue and include the code sample that you are using.  From the screenshot above, it appears you are using WebRequest.  But it is not clear how you are setting up credentials for your application.

**Comment by davidsh** [comment] 2019-06-03 17:57
Also, do not use this code in your application:

```c#
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)
```

It will not help.  The NTLM fixes require the new SocketsHttpHandler.  So, you shouldn't be turning it off with that app context switch.

**Comment by stevenruizhang** [comment] 2019-06-04 02:59
@davidsh , please see below steps , i want to firstly test in my local ubuntu if passed, then i can ask AWS team if u can install the gss-ntlmssp library in the lambda vm or they can use  .NET Core 3.0 latest Preview directly. see related issue https://github.com/dotnet/corefx/issues/38157
1) i use .net core 2.1 in VS 2017 to push the code, and that code can run well in my local
2) i remove the AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false); code as u suggested
3) i use the below code to setup the credential 
![image](https://user-images.githubusercontent.com/13114985/58847550-f5a5d800-86b5-11e9-8b26-5e5277c39b87.png)
4) i check API which i used has below header  for www-authenticate in POST man tool
![image](https://user-images.githubusercontent.com/13114985/58847615-356cbf80-86b6-11e9-8fed-0c9ca88f3e90.png)
5) put the pushed code in my local linux VM , still get below error
![image](https://user-images.githubusercontent.com/13114985/58847765-b2983480-86b6-11e9-977e-79d018490d5a.png)
My concers:
a) how can i use .net core 2.1 run success in my local VM ubuntu , only to install the  gss-ntlmssp library is enough any other library is needed? the credential set up above is fine?
b) if .net core 2.1 can not resolve this issue, we had to use .NET Core 3.0 latest Preview, no any library and code need to change when use for .NET Core 3.0, i think even i can pass that in my local but AWS lambda only support up to .net core 2.1
c) is the issue related to linux version , my local vm is ubuntu 16.04 but the lamdba VM os is 
the Linux kernel version is 4.14.88-90.76.amzn2.x86_64 or 4.14.94-73.73.amzn1.x86_64 according to AWS doc

**Comment by davidsh** [comment] 2019-06-04 03:04
.NET Core 3.0 still requires the gss-ntlmssp package to be installed in a Linux VM.

**Comment by stevenruizhang** [comment] 2019-06-04 03:07
@davidsh could u answer the other questions below , thanks
a) how can i use .net core 2.1 run success in my local VM ubuntu , only to install the gss-ntlmssp library is enough any other library is needed? the credential set up above is fine?
b) if .net core 2.1 can not resolve this issue, we had to use .NET Core 3.0 latest Preview, no any library and code need to change when use for .NET Core 3.0, i think even i can pass that in my local but AWS lambda only support up to .net core 2.1
c) is the issue related to linux version , my local vm is ubuntu 16.04 but the lamdba VM os is
the Linux kernel version is 4.14.88-90.76.amzn2.x86_64 or 4.14.94-73.73.amzn1.x86_64 according to AWS doc

**Comment by davidsh** [comment] 2019-06-04 03:49
.NET Core 2.1 has bugs that are only fixed in .NET Core 3.0.  Specifically Negotiate protocol won't auto-fallback from kerberos to NTLM.  So your a) won't work.

b) is not true either.  You need to install gss-ntlmssp to use NTLM protocol even with .NET Core 3.0.

c) The issue is not related to linux version.

The basic requirements are:

* .NET Core 3.0.
* Install gss-ntlmssp package to the Linux VM

**Comment by davidsh** [comment] 2019-06-04 03:54
Also, you cannot use "Default Credentials" on Linux with NTLM.  There is no such thing because there is no default identity on Linux.

So, code like this won't work on Linux with NTLM:

```c#
request.Credentials = CredentialCache.DefaultCredentials;
```

Using DefaultCredentials only work when a Linux VM is correctly configured and joined to a Kerberos realm or Windows Active Directory domain.  And you must pre-initialize the credential with a "kinit" command.

However, you can use explicit credentials such as:

```c#
request.Credentials = new NetworkCredentials(username, password, domain);
```

**Comment by davidsh** [comment] 2019-06-04 03:57
It sounds like your issue is actually the same as #35383.  And that requires .NET Core 3.0 as well as the gss-ntlmssp package to be installed.

**Comment by davidsh** [comment] 2019-06-04 03:59
Please try out .NET Core 3.0 with your Linux VM and install the gss-ntlmssp package.  If you are still having trouble with Negotiate or NTLM authentication, then we can re-open this issue.

**Closed by davidsh** 2019-06-04 03:59 UTC
Labels: area-System.Net.Http, needs more info

**Comment by stevenruizhang** [comment] 2019-06-04 07:49
i will try , thanks

**Comment by math084m** [comment] 2019-10-11 12:06
@stevenruizhang Will you please confirm if you got it to work or not?
I am currently struggling with the same issue.

**Comment by stevenruizhang** [comment] 2019-10-23 10:53
it can work  well with .NET Core 3.0 with my Linux VM and install the gss-ntlmssp package in my local VM machine

**Comment by srsrsrsrsrsrsr** [comment] 2019-11-20 20:28
I would like to use NTLM on Linux without having to hardcode the credentials - is this possible at all? (I can connect to GSSAPI/Kerberos-authenticated services from my Linux box without any problem as I initialized a keytab using "kinit", and "klist" shows the ticket from the TGT)

When using "request.Credentials = CredentialCache.DefaultCredentials" I get the following error, even with gss-ntlmssp installed in .NET Core 3.0 : "NTLM authentication is not possible with default credentials on this platform"

**Comment by davidsh** [comment] 2019-11-20 20:32
>I would like to use NTLM on Linux without having to hardcode the credentials - is this possible at all? 

Not possible.  On Windows machines can use "default credentials" for NTLM.  But Linux has no OS concept of "default credentials".  On Linux "default credentials" means to use an existing cache of a Kerberos ticket, presumably created via a prior 'kinit' command.

**Comment by stefanruijsenaars** [comment] 2019-11-21 00:04
>  On Linux "default credentials" means to use an existing cache of a Kerberos ticket, presumably created via a prior 'kinit' command.

I do have those - but if I understand correctly, I can't use those for NTLM auth, as it's not possible to use the credentials in the existing cache (KRB5CCACHE) to authenticate to a http service that allows NTLM authentication only, as these are not "OS-level default credentials", and can be used for Kerberos authentication only (and not NTLM)?

> Using DefaultCredentials only work when a Linux VM is correctly configured and joined to a Kerberos realm or Windows Active Directory domain. And you must pre-initialize the credential with a "kinit" command.

Just to clarify, if all of these conditions are met I still can't use NTLM auth without having to set request.Credentials to `new NetworkCredentials(username, password, domain)` (i.e. hardcoding the password)?

**Comment by davidsh** [comment] 2019-11-23 01:26
>Just to clarify, if all of these conditions are met I still can't use NTLM auth with DefaultCredentials (i.e. without having to set request.Credentials to new NetworkCredentials(username, password, domain), hardcoding the password)?

Correct. Linux has not implicit concept of DefaultCredentials. On Windows, DefaultCredentials is the windows account identity that you logged in as on the machine (local machine account or Active Directory). So, on Windows, it always can use that identity for either Negotiate (Kerberos) or NTLM.

Linux doesn't have the same concepts.  DefaultCredentials on Linux means to use a cached Kerberos ticket. That is something you might get when you do a 'kinit' command.

But there is no NTLM equivalent. So, .NET Core only supports explicit credentials for NTLM.
