### ISSUE TITLE
SocketException when sending on HttpClient after upgrading to core 2.2

### ISSUE THREAD

**Issue by kristofferpagels** [dotnet/corefx#41275] opened 2019-09-24 06:48 UTC
Hi,

We are in the process of upgrading from DotNetFramework 4.6.2 to DotNetCore 2.2. After upgrading a lot of our tests are failing when executing a send on a httpclient. It seems to be timing related as the same http requests are working fine if executed by themselves. Any help would be deeply appreciated.

Exception details:
```csharp
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.
-------- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MyTest.Test.MyTest.RunTest(HttpClient httpClient) in C:\workinprogress\20190924 httpclienterror\MyTest\MyTest\MyTest.cs:line 37
   at MyTest.Test.MyTest.GIVEN_WithStaticHttpClient() in C:\workinprogress\20190924 httpclienterror\MyTest\MyTest\MyTest.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
----- Inner Stack Trace -----
```

We have created a sample to reproduce the error. It fails when sending the second http request:
```csharp
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;

namespace MyTest.Test
{
    public class MyTest
    {
        private static readonly HttpClient _httpClient = new HttpClient();

        [Fact]
        public async Task GIVEN_WithStaticHttpClient()
        {
            await RunTest(_httpClient);
        }

        [Fact]
        public async Task GIVEN_WithNewHttpClient()
        {
            using (var httpClient = new HttpClient())
            {
                await RunTest(httpClient);
            }
        }

        private async Task RunTest(HttpClient httpClient)
        {
            var serviceUri = new Uri("http://httpstat.us/200");

            var response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Post, serviceUri));
            response.EnsureSuccessStatusCode();

            DoSomeAction();

            response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Put, serviceUri) { Content = new StringContent("my message") });
            response.EnsureSuccessStatusCode();
        }

        private void DoSomeAction()
        {
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    CreateNoWindow = true,
                    FileName = "ping.exe",
                    UseShellExecute = false
                }
            };

            process.Start();

            process.WaitForExit();
            process.Close();
        }
    }
}

```

The csproj file for the project contains the following nuget packages:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />    
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by wfurt** [comment] 2019-10-01 18:06
I could not reproduce it. Can you get packet capture with Wireshark @kristofferpagels?

**Comment by scalablecory** [comment] 2019-10-31 20:57
@wfurt was not able to reproduce. Closing this out -- please feel free to reopen if you're still encountering this problem and can provide more detail.

**Closed by scalablecory** 2019-10-31 20:57 UTC
Labels: area-System.Net.Http, needs more info
