### ISSUE TITLE
Consider generic support for Shuffle and Shift operations on Vector<T>

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#993] opened 2015-02-23 18:47 UTC
Two useful operations that we have long-considered adding to Vector<T> are shuffle and shift. These are pretty fundamental operations that low-level algorithms could very often take advantage of. One of the challenges was developing a generic but straightforward interface for utilizing such operations across all of the (integral) numeric types that Vector<T> supports.

Work to be done:

* Define which operations are supported (shuffle at a minimum)
* Determine which operations could benefit from SIMD instructions
    * These should be able to benefit greatly
* Create a simple working prototype (without hardware instructions)
* Create formal API design speclet and follow regular procedure

**Comment by AdamSpeight2008** [comment] 2015-02-24 18:45
**Needs more info** like what is meant by `shuffle` and `shift`
Also see #461

**Comment by mikedn** [comment] 2015-02-24 19:03
The `shuffle` that is being discussed here is SIMD specific, it has nothing to do with #461. And `shift` is bitwise shift as in `>>` and `<<` but for SIMD.

**Comment by benaadams** [comment] 2015-02-25 17:31
is the ```shuffle``` more a ```swizzle```?

e.g.
```csharp
Vector4 vec2 = vec1.xxyz;
```

**Comment by mikedn** [comment] 2015-02-25 18:27
SSE's `shuffle` is related to `swizzle` but it's not the same thing as it can combine values from 2 different sources. See this MSDN [page](https://msdn.microsoft.com/en-us/library/vstudio/4d3eabky(v=vs.100).aspx) for an example.

**Comment by mellinoe** [comment] 2016-09-26 20:38
We still need a concrete proposal for this to be actionable, but @CarolEidt and I have discussed some possible options on various occasions.

**Comment by karelz** [comment] 2016-09-26 21:16
Dupe of #1168 which has more useful info.

**Closed by karelz** 2016-09-26 21:16 UTC
Labels: api-needs-work, area-System.Numerics, needs more info, up for grabs
