### ISSUE TITLE
System.IO.Tests.PathTooLongExceptionInteropTests.From_HR failed in Windows PR CI

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#13025] opened 2016-10-26 00:29 UTC
```
MESSAGE:
Assert.NotNull() Failure
+++++++++++++++++++
STACK TRACE:
at System.IO.Tests.PathTooLongExceptionInteropTests.From_HR() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\IO\PathTooLongException.InteropTests.cs:line 18
```

Refer job [here](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2164/), [here](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2160/)

**Comment by stephentoub** [comment] 2016-10-26 01:54
Also here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2165/consoleText
and here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2165/consoleText

```
System.IO.Tests.FileLoadExceptionInteropTests.Fom_HR(hr: -2146232799) [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\IO\FileLoadException.InteropTests.cs(43,0): at System.IO.Tests.FileLoadExceptionInteropTests.Fom_HR(Int32 hr)
```

```
System.IO.Tests.PathTooLongExceptionInteropTests.From_HR [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime\tests\System\IO\PathTooLongException.InteropTests.cs(19,0): at System.IO.Tests.PathTooLongExceptionInteropTests.From_HR()
```

@yizhang82, has something changed recently with regards to handling of interop and HRs?

**Comment by stephentoub** [comment] 2016-10-26 01:56
And here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/2163/
```
System.IO.Tests.DirectoryNotFoundExceptionInteropTests.From_HR(hr: -2147024893) [FAIL]
        Assert.NotNull() Failure
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Runtime\tests\System\IO\DirectoryNotFoundException.InteropTests.cs(20,0): at System.IO.Tests.DirectoryNotFoundExceptionInteropTests.From_HR(Int32 hr)
```

**Comment by karelz** [comment] 2016-10-26 15:45
@JeremyKuhne @ianhays can you please take a look? Looks like impactful intermittent failure ...

**Comment by stephentoub** [comment] 2016-10-26 15:50
This set of tests has been very stable for months.  That it's such a simple test and just started failing so frequently suggests a regression of some kind.

**Comment by yizhang82** [comment] 2016-10-26 21:06
@stephentoub We are not making any change in this area. Mostly we are focusing on adding APIs and completing CoreRT/.NET native interop story.

**Comment by AlexGhiondea** [comment] 2016-10-26 21:15
The tests are failing with this message:

MESSAGE:
Assert.IsAssignableFrom() Failure
Expected: typeof(System.IO.PathTooLongException)
Actual: typeof(System.IO.FileNotFoundException)
+++++++++++++++++++
STACK TRACE:
at System.IO.Tests.PathTooLongExceptionInteropTests.From_HR() in D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime\tests\System\IO\PathTooLongException.InteropTests.cs:line 16

**Comment by stephentoub** [comment] 2016-10-26 21:16
@yizhang82, ok, but something significant has changed.  This test hasn't changed since April, yet it's now failing very frequently, with errors like the one @AlexGhiondea just shared, highlighting that it's returning a different exception type than expected.

**Comment by karelz** [comment] 2016-10-26 21:30
This may very well be caused by some bug in underlying stack (CoreCLR, JIT, etc.). Given that this is just 1 particular test showing these symptoms, we will start with test owner first.

@yizhang82 who has the best chance to find out what is going on? You/your team or @JeremyKuhne.

We need someone to take a look right now. First step should be disable the test, immediately followed by investigation.

**Comment by AlexGhiondea** [comment] 2016-10-26 21:33
@karelz I have a PR out to disable the 3 tests (#13059)

**Comment by karelz** [comment] 2016-10-26 21:45
@AlexGhiondea great, thanks! I assume you don't plan to investigate it further ... (just checking)

**Comment by yizhang82** [comment] 2016-10-27 00:06
Ah, I have a theory. Have we started recently running the tests together in-proc? This might be a case of leaking IErrorInfo in the same thread from a previous test. I can repro a similar issue with this two lines:
```
            // This leaks IErrorInfo of FileNotFoundException
            int hr  = Marshal.GetHRForException(new FileNotFoundException());
            // OOps! Returning FileNotFoundException instead!
            Exception ex = Marshal.GetExceptionForHR(COR_E_PATHTOOLONG);
```

**Comment by karelz** [comment] 2016-10-27 00:22
AFAIK xunit runs tests in-proc by default ...

What you described sounds like a real bug to me ... could it be recent regression?

**Comment by yizhang82** [comment] 2016-10-27 00:30
It's not a bug and not a regression (I can repro that in desktop CLR) - but a really unfortunate by-design. Marshal.GetHRForException is mainly meant to be used at interop boundary to return HR + IErrorInfo to native code and it's really easy to be used incorrectly. 

The right way to write the code is simply (new FileNotFoundException()).HResult - no side effect.

**Comment by yizhang82** [comment] 2016-10-27 00:57
I'll send a PR out to fix the System.Runtime.InteropServices\tests\System\Runtime\InteropServices\MarshalTests.cs. It needs to clear IErrorInfo by calling Marshal.GetExceptionForHR(hr).

**Comment by stephentoub** [comment] 2016-10-27 01:58
> I'll send a PR out to fix

Thanks, appreciated.

**Comment by yizhang82** [comment] 2016-10-28 20:56
Fixed by https://github.com/dotnet/corefx/pull/13087

**Closed by yizhang82** 2016-10-28 20:56 UTC
Labels: area-System.IO
