### ISSUE TITLE
Add Last-Modified to HttpResponseHeaders

### ISSUE THREAD

**Issue by cknaap** [dotnet/corefx#24372] opened 2017-10-02 13:54 UTC

**Comment by davidsh** [comment] 2017-10-02 14:11
You can already get any header you want by using `HttpResponseMessage.Headers.TryGetValues` or `HttpResponseMessage.Content.Headers.TryGetValues`

https://msdn.microsoft.com/en-us/library/system.net.http.headers.httpheaders.trygetvalues(v=vs.118).aspx

**Comment by Priya91** [comment] 2017-12-08 22:30
Dupe of #24373

**Closed by Priya91** 2017-12-08 22:30 UTC
Labels: area-System.Net.Http, enhancement

**Comment by sako9** [comment] 2018-09-19 15:34
From my understanding of https://tools.ietf.org/html/rfc7232#section-2.2 a server should return a Last-Modified header whenever feasible which to me means even when there is no content. Currently, to set the Last-Modified header you would do ```HttpResponseMessage.Content.Headers.LastModified = someDateTimeOffset``` which would throw and error is you didn't set the content which you might not do in the case of a 204. So I think adding Last-Modified to HttpResponseHeaders is a good idea
