### ISSUE TITLE
System.Text.Json.Serialization.JsonExtensionDataAttribute not working with dotnet 3 preview 8 release

### ISSUE THREAD

**Issue by lambrech** [dotnet/corefx#40618] opened 2019-08-27 14:12 UTC
I am using the System.Text.Json.Serialization.JsonExtensionDataAttribute and have some code that worked perfectly with dotnet core 3 preview 7 release.
Today I updated to preview 8 and it looks like the deserialization logic was changed which broke the (or at least my) usage of the JsonExtensionDataAttribute.

I created a small repository to demonstrate the issue.
[https://github.com/lambrech/JsonExtensionDataAttributeIssue](https://github.com/lambrech/JsonExtensionDataAttributeIssue)
Please note, that I am using dotnetcoreapp2.2 on purpose, so I could easily switch between the System.Text.Json nuget packages for preview 7 and 8 to verify my problem.

TheProgram.cs contains code for 2 TestCases. Both work as expected with the preview7 nuget package.
With preview8 nuget package in the first testcase the deserializer tries to Deserialize into the wrong datatype:
"System.InvalidCastException: 'Unable to cast object of type 'JsonExtensionDataAttributeIssue.Two' to type 'JsonExtensionDataAttributeIssue.One'.'"

In the second testcase I get an unexpected System.NullReferenceException.

I am not that experienced so maybe I am just using it wrong. But since it was working perfectly with the preview7 build I thought its worth opening an issue for that.

As mentioned before I am not that experienced, so if you need more information or the like, just tell me.

**Comment by steveharter** [comment] 2019-08-28 22:44
@lambrech thanks for creating this issue. This was a regression due to the way extension properties are now serialized - previously they were serialized as the extension property's dictionary elements; now they are serialized as standard properties (without serializing the extension property).

This should be fixed in time for 3.0 since it deserialization is broken in many cases.

**Comment by ahsonkhan** [comment] 2019-08-31 01:01
Fixed in 3.0 by https://github.com/dotnet/corefx/pull/40691 and in master by https://github.com/dotnet/corefx/pull/40662

**Closed by ahsonkhan** 2019-08-31 01:01 UTC
Labels: area-System.Text.Json

**Comment by lambrech** [comment] 2019-09-17 19:50
I just tried to verify this fix with dotnet core 3 release 3.0.100-rc1-014190.

And I was able to make both of my "TestCases" work. But I had to make the setter of the JsonExtensionData Dictionary public. This is not a problem for me, but it wasn't like that before (fyi with Newtonsoft.Json it is also not necessary that the JsonExtensionData property has a public setter). 

So I just wanted to ask, whether the requirement of having a public setter is intended or not.

**Comment by ahsonkhan** [comment] 2019-09-18 02:24
> So I just wanted to ask, whether the requirement of having a public setter is intended or not.

It is. The serializer primarily works on POCOs containing properties with public getters/setters. @steveharter - please correct me if I am mistaken for this particular case (`JsonExtensionData` without a public setter wouldn't work).
