### ISSUE TITLE
'build -test' fails with the message 'It was not possible to find any installed dotnet SDKs'

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#35563] opened 2019-02-25 17:43 UTC
Tools used:
* Windows 10 Pro 1809 (Build 17763.316) x64. I also had similar problem on another Windows 10 Home 1809 (build unknown).
* VS Enterprise 2019 Preview 3.0 with the followings installed:
```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 3.0
VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2019   00435-10000-00000-AA929
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.0.20206.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12185.18740
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.0.12185.18740
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12185.18740
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.0.12185.18740
Azure Functions and Web Jobs Tools

C# Tools   3.0.0-beta3-19105-04+f9fc5ea40f861ac30e7ad1a322b7517d4af5d47b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.8.0.6762
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

IntelliCode Extension   1.0
IntelliCode Extension

JetBrains ReSharper Ultimate 2018.3.2   Build 183.0.20190124.112722
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61901.26130
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10206.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta3-19105-04+f9fc5ea40f861ac30e7ad1a322b7517d4af5d47b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: b5c01b8cc65af6381d2dd558ee63a4aa9e0e98d5.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

* CMake 3.14.0-rc2 x64
* .NET Core SDKs (x86)
```
2.2.104 [C:\Program Files (x86)\dotnet\sdk]
3.0.100-preview-010184 [C:\Program Files (x86)\dotnet\sdk]
```
* .NET Core Runtimes (x86)
```
Microsoft.AspNetCore.All 2.2.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.2.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.2.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```
* .NET Core SDKs (x64)
```
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]
```
* .NET Core Runtimes (x64)
```
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview-27122-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I've cloned directly from the dotnet/corefx repo when [this commit was at the top of the master branch](https://github.com/dotnet/corefx/commit/327def063eb5eddb723edcee84815d9495b4021c) , and using Developer Command Prompt for VS2017/2019, I ran `build -restore`, `build` prior to running `build -test`. the former two scripts ran with no problem, however trying `build -test` gave me hundreds of following errors before failing with 465 errors.

```  C:\Users\gotos\.nuget\packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19121.4\build\core\Core.targets(189,5): error MSB3073: The command "C:\Users\gotos\source\repos\corefx\artifacts\bin\tests\System.DirectoryServices.Protocols.Tests\netcoreapp-Windows_NT-Debug-x64\RunTests.cmd C:\Users\gotos\source\repos\corefx\artifacts\bin\testhost/netcoreapp-Windows_NT-Debug-x64/ C:\Users\gotos\source\repos\corefx\.dotnet\ C:\Users\gotos\source\repos\corefx\artifacts\tools\" exited with code -2147450735. [C:\Users\gotos\source\repos\corefx\src\System.DirectoryServices.Protocols\test
s\System.DirectoryServices.Protocols.Tests.csproj]
C:\Users\gotos\.nuget\packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19121.4\build\core\Core.targets(200,5): error : One or more tests failed while running tests from 'System.DirectoryServices.Protocols.Tests'. [C:\Users\gotos\source\repos\corefx\src\System.DirectoryServices.Protocols\tests\System.DirectoryServices.Protocols.Tests.csproj]
    It was not possible to find any installed dotnet SDKs
    Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
        https://aka.ms/dotnet-download
  ----- end 17:35:58.33 ----- exit code -2147450735 ----------------------------------------------------------
```

I do have a `build.binlog` file from the `build -test` run, but GitHub seems to refuse it due to its size (34,577KB). Should I submit it somewhere and leave a link here?

**Comment by Clockwork-Muse** [comment] 2019-02-25 18:12
Did you build tests first?  `build -test` may not be sufficient.

What do you get if you do this (may have to log out to release locks first):
```
clean -all
build -restore
build -build -buildtests
build -test
```

This has been affecting me too, although explicitly building the tests via the `build -build -buildtests` seems to have given me at least _mostly_ valid output (the initial part of the run still can't find any SDKs, but starts showing up later).

**Comment by Gnbrkm41** [comment] 2019-02-25 19:07
@Clockwork-Muse it definitely did reduce the number of errors(465 -> 15). The failing ones still do fail with the same error message though.

**Comment by danmosemsft** [comment] 2019-02-25 19:22
@ViktorHofer ?

**Comment by ViktorHofer** [comment] 2019-02-26 17:27
Running locally right now and trying to reproduce.

**Comment by Gnbrkm41** [comment] 2019-02-26 17:29
Please do ask if you need anything regarding this.

**Comment by ViktorHofer** [comment] 2019-02-26 19:11
Found the reasons for the failures. The order of the action chain is wrong. I forgot to push a change which I made locally. Thanks for submitting the issue! Will close this when the fix landed in master.

**Comment by ViktorHofer** [comment] 2019-02-26 19:52
Please wait a few more hours till we consume the change in corefx :)

**Comment by tmds** [comment] 2019-02-27 08:54
@VictorHofer I'm hitting this issue. Can I work around it locally?

**Comment by ViktorHofer** [comment] 2019-02-27 10:48
This is already fixed. Make sure to be in latest master.

**Comment by tmds** [comment] 2019-02-27 13:15
Is there something I should clear? I'm at f44142b855330ca9274827a230b8ad9a3ccda357 and I get this test. I tried `rm -rf ~/.nuget/packages` but that didn't help.

**Comment by ViktorHofer** [comment] 2019-02-27 14:56
I just tested this locally, the errors are gone as expected. Sounds like you are running on Unix, I will test on Ubuntu also. Yes I would recommend doing a full clean: ./clean.sh --all

**Comment by ViktorHofer** [comment] 2019-02-27 15:21
Works fine on Ubuntu (WSL). Please try it again after cleaning your repository.

**Comment by Gnbrkm41** [comment] 2019-02-28 17:43
Actually... I still am experiencing the same issue. Tried removing and re-cloning the repo from the latest one. Can I re-open the issue?

**Comment by ViktorHofer** [comment] 2019-02-28 17:52
Sure.

**Comment by ViktorHofer** [comment] 2019-02-28 17:52
What command do you use?

@tmds does that also still affect you?

**Comment by Gnbrkm41** [comment] 2019-02-28 18:45
It is the same as before. build -restore, build then build -test.

**Comment by Clockwork-Muse** [comment] 2019-02-28 19:36
@Gnbrkm41 - did you specifically build the tests:  `build -buildtests` (#35661)

**Comment by ViktorHofer** [comment] 2019-02-28 19:53
1. Make sure that `git log` tells you that you are on the latest master, preferrably from today.
2. Use this command: `build.cmd -restore -build -buildtests -test`.

**Comment by Gnbrkm41** [comment] 2019-02-28 20:00
Right, I must have missed something from the docs... I remember `build -test` taking care of all the things, was missing that one. 😶 Blame my ignorance. Ran `build & build -buildtest -test

Feel free to close the issue again, sorry about that.

**Comment by ViktorHofer** [comment] 2019-02-28 20:05
No reason to apologize. `build -test` also built the tests before but with a change that went into master last week we fixed the CLI experience. Not your fault! Make sure to read https://github.com/dotnet/corefx/issues/35661 :)

**Closed by ViktorHofer** 2019-02-28 20:05 UTC
Labels: area-Infrastructure

**Comment by tmds** [comment] 2019-03-01 08:49
I was also missing the `--buildtests`.

**Comment by ViktorHofer** [comment] 2019-03-01 09:37
Note that now the single hyphen (cross-plat) syntax also works: `-buildtests` as described in https://github.com/dotnet/corefx/issues/35661
