### ISSUE TITLE
Holding X509Certificate2 reference prior to HttpClientHandler causes access violation in ServerCertificateCustomValidationCallback

### ISSUE THREAD

**Issue by imbushuo** [dotnet/corefx#14818] opened 2017-01-03 15:22 UTC
## Symptoms
I would like to implement cert pinning in my own project. When a `System.Security.Cryptography.X509Certificates.X509Certificate2` was held, and a `ServerCertificateCustomValidationCallback` callback from a `System.Net.Http.HttpClientHandler` (or `WinHttpHandler` on Windows) was triggered from a request sent by `System.Net.Http.HttpClient`, `System.ExecutionEngineException` will be thrown. In native debug mode, an access violation was caught.

**Update: This bug doesn't affect Linux platform.**

Creating `System.Security.Cryptography.X509Certificates.X509Certificate2` object inside the callback will be a good workaround for this.

![Access violation](https://imbushuos3.azureedge.net/Snippets/Repro/AccessViolation.jpg)

![Callstack](https://imbushuos3.azureedge.net/Snippets/Repro/Callstack.jpg)

## Reproduce
A 100% reproducible code repository is here: https://github.com/imbushuo/CertCheckAccessViolationRepro

```c#
using System;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;

public class ReproProgram
{
    private static X509Certificate2 _cert;

   public static void Main(string[] args)
    {
        // Hold a reference of X509Certificate2
        _cert = new X509Certificate2("test.cer");

        // Create a HTTP handler and repro the bug
        using (var clientHandler = new HttpClientHandler())
        {
            clientHandler.ServerCertificateCustomValidationCallback = 
                (msg, cert, chain, errors) => {
                    return _cert.Thumbprint == cert.Thumbprint;
                };

            using (var httpClient = new HttpClient(clientHandler))
            {
                // Boom
                var req = httpClient.GetAsync("https://imbushuo.net");
                req.Wait();
            }
        }

        Console.WriteLine("Hello World!");
    }
}
```

**Comment by karelz** [comment] 2017-01-03 17:36
@Priya91 any idea?

**Comment by danmosemsft** [comment] 2017-01-04 01:05
@bartonjs

**Comment by bartonjs** [comment] 2017-01-04 01:30
@imbushuo Does this still reproduce for you if you launch the program with `COMPlus_ReadyToRunExcludeList=System.Security.Cryptography.X509Certificates` (environment variable)?

It sounds similar to an issue we're already tracking.

**Comment by imbushuo** [comment] 2017-01-04 02:03
@bartonjs No. I was unable to reproduce it anymore after setting environment variable.

**Comment by bartonjs** [comment] 2017-01-04 02:06
Okay, so this is a different instance of https://github.com/dotnet/coreclr/issues/8148.   (@JohnChen0 this is a different triggering symptom of the X509Certificates ExecutionEngineException, but I'm guessing it's the same underlying cause/fix).

**Comment by karelz** [comment] 2017-01-04 02:22
Ah, the NULL AV confused me (I missed the debug only part). We have the issue [documented](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1-known-issues.md#systemexecutionengineexception-in-systemsecuritycryptographyx509cerificatesdll-on-windows).
I don't think we need to change the symptoms there, but let me know if you think otherwise.

**Comment by imbushuo** [comment] 2017-01-04 04:52
@karelz Good to know that. That confused me too - I thought there was related to HttpHandler itself, not X509Certificate2. Now the situation is clear and I have two workarounds before the 1.1.1 release. Sweet!

**Comment by Priya91** [comment] 2017-01-04 19:57
Tried the program with @bartonjs workaround, the issue didn't repro.

**Comment by karelz** [comment] 2017-01-04 20:00
We can close it as confirmed dupe of https://github.com/dotnet/coreclr/issues/8148.

**Closed by karelz** 2017-01-04 20:00 UTC
Labels: area-System.Net.Http, bug, os-windows
