### ISSUE TITLE
System.Text.Json.JsonNamingPolicy Deafult

### ISSUE THREAD

**Issue by VassilAtanasov** [dotnet/corefx#41384] opened 2019-09-27 09:27 UTC
Developers need to be able to use it pass through PascalCase
```
    public abstract partial class JsonNamingPolicy
    {
        protected JsonNamingPolicy() { }
        public static System.Text.Json.JsonNamingPolicy CamelCase { get { throw null; } }
        public static System.Text.Json.JsonNamingPolicy SnakeCase { get { throw null; } }
/// <summary>
/// Property names are not changed
/// </summary>
public static System.Text.Json.JsonNamingPolicy Deafult{ get { throw null; } }
```

_Originally posted by @VassilAtanasov in https://github.com/dotnet/corefx/pull/41354_

**Comment by GrabYourPitchforks** [comment] 2019-09-27 18:55
Dupe of https://github.com/dotnet/corefx/issues/41383.

**Closed by GrabYourPitchforks** 2019-09-27 18:55 UTC
