### ISSUE TITLE
Add an API to determine whether the current environment supports JIT vs is native

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#13535] opened 2016-11-10 00:39 UTC
There is no way to determine whether the current environment is a JIT one or a .NET Native one.

Please add a way to discover this information at runtime so libraries and applications can enable or disable using features like IL emit which required a JIT environment.

// cc @terrajobst

**Comment by svick** [comment] 2016-11-10 01:21
If you want to know whether IL emit, or some other feature, is available, wouldn't an API that tells you exactly that be better?

Distinguishing between JIT and AOT would work now, but I can imagine that it might not work in the future.

**Comment by karelz** [comment] 2018-04-21 16:41
Duplicate of #29258

**Closed by karelz** 2018-04-21 16:41 UTC
Labels: api-needs-work, area-Meta
