### ISSUE TITLE
Add System.Net.Sockets.Socket SendTo method overloads accepting Spans.

### ISSUE THREAD

**Issue by dv00d00** [dotnet/corefx#30915] opened 2018-07-09 15:19 UTC
### Motivation:

There are span based overloads for Send and Receive methods on a socket class already. My proposal is to add two overloads for SendTo which would allow squeezing extra bits of performance for intensive UDP usage scenarios (e.g. stats, logging), which took significant processing time in our case.

### Proposed API:

```csharp
 public partial class Socket : IDisposable
 {
    ...
    public int SendTo(ReadOnlySpan<byte> buffer, EndPoint remoteEP);
    public int SendTo(ReadOnlySpan<byte> buffer, SocketFlags socketFlags, EndPoint remoteEP);
    ...
}
```

Draft implementation: https://github.com/dotnet/corefx/pull/30900/files

**Comment by narciero** [comment] 2019-01-15 15:44
+1 - would be nice to be able to use Span<T> for sending UDP...the Send APIs using byte[] are consistent for Send/SendTo...any reason these were left out?

**Comment by karelz** [comment] 2019-04-03 01:40
Not critical for 3.0, pushing it into Future milestone.

**Comment by karelz** [comment] 2019-04-03 01:41
Actually, covered by #35861.

**Comment by karelz** [comment] 2019-04-03 01:41
Duplicate of #35861

**Closed by karelz** 2019-04-03 01:41 UTC
Labels: api-suggestion, area-System.Net.Sockets
