### ISSUE TITLE
Test System.Transactions.Tests.AsyncTransactionScopeTests.VerifyNestedTxScope failed in CI.

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/corefx#29940] opened 2018-05-28 07:06 UTC
Test: System.Transactions.Tests.AsyncTransactionScopeTests.VerifyNestedTxScope has failed.

MESSAGE:
Assert.Equal() Failure\nExpected: (null)\nActual: CommittableTransaction { IsolationLevel = Serializable, PromoterType = 00000000-0000-0000-0000-000000000000, TransactionInformation = TransactionInformation { CreationTime = 2018-05-26T22:01:32.6788934, DistributedIdentifier = 00000000-0000-0000-0000-000000000000, LocalIdentifier = \"66c9483a-cdcb-4cc9-bacb-9f35c47cdf13:34\", Status = Committed } }
+++++++++++++++++++
STACK TRACE:
at System.Transactions.Tests.AsyncTransactionScopeTests.VerifyNestedTxScope(TransactionScopeOption parentScopeOption, TransactionScopeAsyncFlowOption parentAsyncFlowOption, TransactionScopeOption childScopeOption, TransactionScopeAsyncFlowOption childAsyncFlowOption) in /mnt/resource/j/workspace/dotnet_corefx/master/rhel7.2_release/src/System.Transactions.Local/tests/AsyncTransactionScopeTests.cs:line 850

Details: https://ci.dot.net/job/dotnet_corefx/job/master/job/rhel7.2_release/6062/testReport/System.Transactions.Tests/AsyncTransactionScopeTests/VerifyNestedTxScope_parentScopeOption__Required__parentAsyncFlowOption__Suppress__childScopeOption__Required__childAsyncFlowOption__Enabled_/

**Comment by karelz** [comment] 2018-05-30 17:21
@Sunny-pu master branch is now 3.0, not 2.1.0. Can you please open future test failures in master with 3.0 milestone please? Thanks!
cc @danmosemsft

**Comment by jimcarley** [comment] 2018-06-06 00:08
This looks to be a duplicate of https://github.com/dotnet/corefx/issues/30146, which was closed today with PR https://github.com/dotnet/corefx/pull/30151.

**Closed by jimcarley** 2018-06-06 00:08 UTC
Labels: area-System.Transactions, test-run-core
