### ISSUE TITLE
dotnet core 1.1.0 and net461 now gets System.IO.FileSystem System.TypeLoadException

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#16913] opened 2017-03-09 18:16 UTC
@jeremyBass commented on [Thu Mar 09 2017](https://github.com/dotnet/coreclr/issues/10062)

I hope this is  the right place for this issue.  I have been betting my head on the wall on this. 

I will say that I have this on [stackoverflow](http://stackoverflow.com/q/42693085/746758) as well, but believe it may be helpful to have it logged here.  I realize there are a few other issues that seem related, but they are not 100% the same and I got no traction on a fix/workaround.

 I keep getting this error on the server 
[![enter image description here][1]][1] 

> Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.Di rectory' from assembly 'System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. at fais.printing_services.Program.Main(String[] args)

I have done ever trick I can think of, followed all the newest issues to resolve with no luck.  Here is my project file:

    
    {
        "userSecretsId": "aspnet-fais.printing_services-6f6dbf21-da98-45d2-a187-08ae49d09d62",
        "dependencies": {
            "DataTables.AspNet.AspNetCore": "2.0.2",
            "Microsoft.ApplicationInsights.AspNetCore": "2.0.0",
            "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
            "Microsoft.AspNetCore.Diagnostics": "1.1.0",
            "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
            "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
            "Microsoft.AspNetCore.Mvc": "1.1.1",
            "Microsoft.AspNetCore.Routing": "1.1.0",
            "Microsoft.AspNet.Session": "1.0.0-*",
            "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
            "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
            "Microsoft.AspNetCore.StaticFiles": "1.1.0",
            "Microsoft.EntityFrameworkCore": "1.1.0",
            "Microsoft.EntityFrameworkCore.Design": "1.1.0",
            "Microsoft.EntityFrameworkCore.Relational.Design": "1.1.0",
            "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
            "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
            "Microsoft.EntityFrameworkCore.Tools": {
                "type": "build",
                "version": "1.1.0-preview4-final"
            },
            "Microsoft.Extensions.Caching.Memory": "1.1.0-*",
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
            "Microsoft.Extensions.Configuration.Json": "1.1.0",
            "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
            "Microsoft.Extensions.Logging": "1.1.0",
            "Microsoft.Extensions.Logging.Console": "1.1.0",
            "Microsoft.Extensions.Logging.Debug": "1.1.0",
            "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
            "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
            "Microsoft.VisualStudio.Web.CodeGeneration": "1.1.0-preview4-final",
            "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
            //"Microsoft.VisualStudio.Web.CodeGeneration.Design": "1.1.0-msbuild3-final",
            "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final",
            "Microsoft.AspNetCore.Session": "1.1.0",
            "Microsoft.NETCore": "5.0.1-rc2-24027",
            "Microsoft.NETCore.Portable.Compatibility": "1.0.1-rc2-24027",
            "BundlerMinifier.Core": "2.4.337",
            "Microsoft.AspNetCore.ResponseCompression": "1.0.1",
            "Microsoft.AspNetCore.Cors": "1.1.1",
            "hiqpdf": "10.6.0",
            "Novell.Directory.Ldap.NETStandard": "2.3.6"
        },
        "tools": {
            "Microsoft.EntityFrameworkCore.Tools": {
                "version": "1.1.0-preview4-final",
                "imports": [
                    "portable-net45+win8"
                ]
            },
            "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0.0-preview4-final",
            "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
                "version": "1.1.0-msbuild3-final",
                "imports": [
                    "portable-net45+win8"
                ]
            }
        },
        "frameworks": {
            "net461": {
                "dependencies": {
                },
                "frameworkAssemblies": {
                    "System.Drawing": "4.0.0.0"
                }
            },
            "netcoreapp1.0": {
                "imports": [
                    "dotnet5.6",
                    "portable-net45+win8",
                    "net461"
                ],
                "dependencies": {
                    "Microsoft.NETCore.App": "1.1.0",
                    "CoreCompat.System.Configuration": "4.2.3-r4"
                }
            }
        },
        "buildOptions": {
            "emitEntryPoint": true,
            "preserveCompilationContext": true
        },
        "runtimeOptions": {
            "configProperties": {
                "System.GC.Server": true
            }
        },
        "publishOptions": {
            "include": [
                "wwwroot",
                "**/*.cshtml",
                "appsettings.json",
                "web.config"
            ]
        },
        "runtimes": {
            "win10-x64": {}
        },
        "scripts": {
            "prepublish": [ "bower install", "dotnet bundle" ],
            "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
        }
    }

So the reason for `.net4.6.1` is `hiqpdf`, it is the only thing that is really the reason i had to load it.  

My app runs on IISExpress, but as soon as i publish it to the IIS box it gets as `HTTP Error 502.5 - Process Failure`.  I run the exe in the command prompt as Microsoft asks as got what i put up here.  

I keep thinking i just have to move the right item in place and it will work on the server.  What is the difference?  Why does it would great locally but falls on it's face on the server?  Can i include System.IO.FileSystem at a version that will fix this? (which i have tried and failed to).

I know the project.json file needs some clean up again, but it is working in one spot so i figured I would keep it here.

**Server Details:**

[![enter image description here][2]][2]

[![enter image description here][3]][3]

[![enter image description here][4]][4]

[1]: https://i.stack.imgur.com/gcg9a.png
[2]: https://i.stack.imgur.com/dWgMs.png
[3]: https://i.stack.imgur.com/HKSpG.png
[4]: https://i.stack.imgur.com/c8NZj.png

**Other information**
I figured it would be worth noting thing i have done that wouldn't be known from this:
- cleared out the nuget cache from the user path
- cleared the bin
- down graded what i thought i could
- tried to include the `System.IO.File` directly at v. `4.3.0` but it downgrades to `4.0.0.1` I believe.

**Comment by gkhanna79** [comment] 2017-03-09 18:17
@karelz @danmosemsft @weshaggard  PTAL

**Comment by jeremyBass** [comment] 2017-03-09 19:36
@gkhanna79 thank you for porting it in the right spot.  Any info needed or any help to clear things up on my end I am happy to jump right on it.

**Comment by jeremyBass** [comment] 2017-03-10 08:06
I just wanted to report back, I switched to just using the `net452` framework for the moment and dropped  `"Novell.Directory.Ldap.NETStandard": "2.3.6"` .  I am working on the POC for the project so dropping LDAP out for the moment is ok.   I figured I would share this news in case it helps.

**note:** I used the templates on a new project and didn't update them, only added the needed items

    {
        "userSecretsId": "aspnet-fais.printing_services-6f6dbf21-da98-45d2-a187-08ae49d09d62",

        "dependencies": {

            "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
            "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
            "Microsoft.AspNetCore.Diagnostics": "1.0.0",
            "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
            "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
            "Microsoft.AspNetCore.Mvc": "1.0.1",
            "Microsoft.AspNetCore.Razor.Tools": {
                "version": "1.0.0-preview2-final",
                "type": "build"
            },
            "Microsoft.AspNetCore.Routing": "1.0.1",
            "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
            "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
            "Microsoft.AspNetCore.StaticFiles": "1.0.0",
            "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
            "Microsoft.EntityFrameworkCore.SqlServer.Design": {
                "version": "1.0.1",
                "type": "build"
            },
            "Microsoft.EntityFrameworkCore.Tools": {
                "version": "1.0.0-preview2-final",
                "type": "build"
            },
            "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
            "Microsoft.Extensions.Configuration.Json": "1.0.0",
            "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
            "Microsoft.Extensions.Logging": "1.0.0",
            "Microsoft.Extensions.Logging.Console": "1.0.0",
            "Microsoft.Extensions.Logging.Debug": "1.0.0",
            "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
            "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
            "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
                "version": "1.0.0-preview2-final",
                "type": "build"
            },
            "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
                "version": "1.0.0-preview2-final",
                "type": "build"
            },
            //"Microsoft.NETCore.Portable.Compatibility": "1.0.1-rc2-24027",
            //POC needed items
            "Microsoft.AspNetCore.ResponseCompression": "1.0.1",
            "Microsoft.AspNetCore.Cors": "1.1.1",
            "DataTables.AspNet.AspNetCore": "2.0.2",
            "hiqpdf": "10.6.0",
            //"Novell.Directory.Ldap.NETStandard": "2.3.6"
        },

        "tools": {
            "BundlerMinifier.Core": "2.0.238",
            "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
            "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
            "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
            "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
            "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
                "version": "1.0.0-preview2-final",
                "imports": [
                    "portable-net45+win8"
                ]
            }
        },

        "frameworks": {
            "net452": {}
        },

        "buildOptions": {
            "emitEntryPoint": true,
            "preserveCompilationContext": true
        },

        "runtimeOptions": {
            "configProperties": {
                "System.GC.Server": true
            }
        },

        "publishOptions": {
            "exclude": [
                "wwwroot/prints",
                "node_modules"
            ],
            "include": [
                "wwwroot",
                "**/*.cshtml",
                "appsettings.json",
                "web.config"
            ]
        },
        "runtimes": {
            "win10-x64": {}
        },
        "scripts": {
            "prepublish": [ "bower install", "dotnet bundle" ],
            "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
        }
    }

**Comment by ianhays** [comment] 2017-03-10 21:05
Looks potentially related to https://github.com/dotnet/corefx/issues/16322.

CC: @mellinoe @ericstj

**Comment by daveaglick** [comment] 2017-03-13 20:40
FWIW, I'm seeing something similar to this when using Roslyn 2.0.0 from within an MSBuild task (the fact that's it's an MSBuild task is probably not germaine, other than that it makes diagnosing the binding problems harder).

I've tried every combination of binding redirects I can think of without luck. I've also tried installing System.IO.FileSystem 4.3.0 directly into the MSBuild task project without any change.

Note that while the example below was created for use in a test, I'm not running it through the unit testing framework here - this is directly calling MSBuild on the test solution from the console to eliminate the unit test framework as a source of problems.

<details>
<summary>Output</summary>

```
e:\Code\Scripty\src\Scripty.MsBuild.Tests>"C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" /p:ScriptyAssembly="E:\Code\Scripty\src\Scripty.MsBuild.Tests\bin\Debug\Scripty.MsBuild.dll";Include1=true;Include3=true
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/13/2017 4:24:57 PM.
Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" (1) is building "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolu tion\Proj\Proj.csproj" (2) on node 1 (default targets).
EvaluateScriptyFiles:
  Starting out-of-process script evaluation...
  Arguments: --solution "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" --p "ScriptyAssembly=E:\Code\Scripty\src\Scripty.MsBu
  ild.Tests\bin\Debug\Scripty.MsBuild.dll" --p "Include1=true" --p "Include3=true" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\P
  roj.csproj" "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Test.csx"
  Finished script evaluation
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System .IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file spec ified. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : File name: 'System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture= neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [E:\Code\Scripty\src\Scripty.MsBui ld.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.3 0319\clr.dll [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Running under executable  E:\Code\Scripty\src\Scripty.MsBuild.Tests\bin\ Debug\Scripty.exe [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : --- A detailed error log follows.  [E:\Code\Scripty\src\Scripty.MsBuild. Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : === Pre-bind state information === [E:\Code\Scripty\src\Scripty.MsBuild. Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :  (Fully-specified) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolu tion\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Appbase = file:///E:/Code/Scripty/src/Scripty.MsBuild.Tests/bin/Deb ug/ [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Initial PrivatePath = NULL [E:\Code\Scripty\src\Scripty.MsBuild.Tes ts\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : Calling assembly : Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neut ral, PublicKeyToken=31bf3856ad364e35. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : === [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj. csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: This bind starts in default load context. [E:\Code\Scripty\src\Scri pty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using application configuration file: E:\Code\Scripty\src\Scripty.M sBuild.Tests\bin\Debug\Scripty.exe.Config [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using host configuration file:  [E:\Code\Scripty\src\Scripty.MsBuil d.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Fram ework\v4.0.30319\config\machine.config. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem.DLL. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.DLL. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem.EXE. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error : LOG: Attempting download of new URL file:///E:/Code/Scripty/src/Scripty. MsBuild.Tests/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.EXE. [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Roslyn.Utilities.FileUtilities.OpenFileStream(String path) [E:\Cod e\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInterna l(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\Sample Solution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFrom Assembly(Assembly assembly) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__D isplayClass4_0`2.<SelectChecked>b__0(T item) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() [E:\Co de\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRan geChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj .csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ToImmu tableArrayChecked[T](IEnumerable`1 items, String parameterName) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnu merable`1 references) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnu merable`1 references) [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
E:\Code\Scripty\src\Scripty.MsBuild\Scripty.MsBuild.targets(27,5): error :    at Scripty.Core.ScriptEngine.<Evaluate>d__6.MoveNext() in E:\Code\Scr ipty\src\Scripty.Core\ScriptEngine.cs:line 74 [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
  Output file count: 0
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "Manage dMinimumRules.ruleset". [E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj]
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Proj -> E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\bin\Debug\ProjA.dll
Done Building Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Proj\Proj.csproj" (default targets).

Done Building Project "E:\Code\Scripty\src\Scripty.MsBuild.Tests\SampleSolution\Sample.sln" (default targets).


Build succeeded.
```

</details>

**Comment by ianhays** [comment] 2017-03-23 21:55
I'm closing this as a duplicate of #16322. 

cc: @karelz another binding-redirects related issue.

**Closed by ianhays** 2017-03-23 21:55 UTC
Labels: area-System.IO, bug
