### ISSUE TITLE
Nano CI builds completely broken

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#15280] opened 2017-01-18 18:25 UTC
cc: @Priya91, @karelz, @mmitche 
Our Windows Server Nano 2016 builds have been red for as long as we have history.  Looking at the error message, it looks like the Jenkins configuration is broken:
```
08:56:50 Schedule job dotnet_corefx » master » outerloop_winnano16_debug_tst
08:56:50 ERROR: Failed to run DSL Script
08:56:50 com.cloudbees.plugins.flow.CouldNotScheduleJobException: Could not schedule job outerloop_winnano16_debug_tst, ensure it is not already queued with the same parameters or is not disabled
08:56:50 	at sun.reflect.GeneratedConstructorAccessor1731.newInstance(Unknown Source)
08:56:50 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
08:56:50 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08:56:50 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
...
```
If we care about Nano (I assume we do!), we should fix this immediately.
If we don't, we should delete the jobs and remove the badges from the home page.

**Comment by benaadams** [comment] 2017-01-18 18:30
I care...

**Comment by mmitche** [comment] 2017-01-18 19:17
@stephentoub The issue is that the nodes themselves don't seem to dynamically provision properly, and TP5 is really old now (which is what our old static image had).  So we need to figure that out first

**Comment by karelz** [comment] 2017-01-18 20:08
cc @danmosemsft

**Comment by danmosemsft** [comment] 2017-02-14 01:19
Engineering work:
https://github.com/dotnet/core-eng/issues/358
https://github.com/dotnet/core-eng/issues/406
https://github.com/dotnet/core-eng/issues/135
https://github.com/dotnet/core-eng/issues/436

Other:
https://github.com/dotnet/corefx/issues/9975
https://github.com/dotnet/corefx/issues/7434
https://github.com/dotnet/corefx/issues/7433

**Comment by willdean** [comment] 2017-02-17 13:06
The core-eng links don't work here - are they ms-private or has something been renamed?

**Comment by danmosemsft** [comment] 2017-02-17 17:39
Oops, @willdean, I recall now they currently are as at present they also track internal engineering infra.

**Comment by steveharter** [comment] 2017-04-05 17:31
Looping in @CIPop as he also would like to move off of TP5

**Comment by mmitche** [comment] 2017-04-05 17:34
@smile21prc Is working on this.

**Comment by danmosemsft** [comment] 2017-04-17 18:55
@smile21prc is working on this ETA this week apparently and the failure rate looks OK.

**Comment by smile21prc** [comment] 2017-04-28 21:31
Re-implementing the old Nano CI isn't the correct way to fix the broken Nano CI builds because that approach is a bit of a hack.

@mmitche is working on the portable build + Helix in CI (dotnet/core-eng#643), which will fix Nano CI builds correctly once complete. As a result, this task doesn’t need to be tracked as a separate issue any more, as there won’t be additional Nano-specific work after his work is complete.

Closing this one as a dup of that ongoing work.

**Closed** 2017-04-28 21:33 UTC
Labels: area-Infrastructure, test bug
