### ISSUE TITLE
Getting a ref return value using PropertyInfo

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#26053] opened 2017-12-26 00:56 UTC
```c#
    public class RefAndRefReadonlyTestClass
    {
        private int _refField;
        private readonly int _refReadonlyField;

        public RefAndRefReadonlyTestClass(int refReadonlyField)
        {
            _refReadonlyField = refReadonlyField;
        }

        public ref int RefField => ref _refField;

        public ref readonly int RefReadonlyField => ref _refReadonlyField;

        public void SetRefField(int value)
        {
            _refField = value;
        }
    }

    [Test]
    public void GetRefReturnProperty()
    {
        PropertyInfo property = TestReflectionUtils.GetProperty(typeof(RefAndRefReadonlyTestClass), nameof(RefAndRefReadonlyTestClass.RefField));

        RefAndRefReadonlyTestClass c1 = new RefAndRefReadonlyTestClass(123);
        c1.SetRefField(456);

        object v = property.GetValue(c1, null);
    }
```

The code above throws this exception from PropertyInfo.GetValue: `System.NotSupportedException: 'ByRef return value not supported in reflection invocation.'`

Can you use a PropertyInfo to get the value of a ref return property?

[EDIT] Add C# syntax highlight by @karelz

**Comment by benaadams** [comment] 2017-12-26 01:30
Perhaps related?

Bring back `TypedReference` https://github.com/dotnet/corefx/issues/14088 (Resolved and part of .NET Standard 2.0)
"Proposal for high-performance codegen-less Reflection factory APIs" https://github.com/dotnet/corefx/issues/24390

Though I assume is a current issue for serializing to and from `ref` returns?

**Comment by benaadams** [comment] 2017-12-26 19:30
Currently it looks like is definately going to [`ThrowNoInvokeException`](https://github.com/dotnet/coreclr/blob/aacefc0f47ba94f228281da9a4a8fe64a29e92da/src/mscorlib/src/System/Reflection/RuntimeMethodInfo.cs#L506-L510)

![image](https://user-images.githubusercontent.com/1142958/34362925-a0fdde26-ea6f-11e7-813b-069d451a6ad8.png)

Ref returns themselves are an issue with boxing; however...

I think it makes sense that `PropertyInfo.GetValue` and `PropertyInfo.SetValue` would operate on the referenced **value** rather than the reference itself; behaving like `FieldInfo.GetValue` and `FieldInfo.SetValue`

Or... like `FieldInfo` should be methods?
```csharp
public partial class PropertyInfo
{
    public virtual object GetValueDirect(TypedReference obj)
    public virtual void SetValueDirect(TypedReference obj, object value)
}
```

/cc @VSadov @jkotas

**Comment by jkotas** [comment] 2017-12-26 19:36
cc @AtsushiKan @KrzysztofCwalina @ahsonkhan `Span<T>` end-to-end gap.

**Comment by JamesNK** [comment] 2017-12-26 22:18
There is a difference between getting a ref return by value and by ref, right?

e.g.
```
    RefAndRefReadonlyTestClass c1 = new RefAndRefReadonlyTestClass(123);
    c1.SetRefField(456);

    int byValue = c1.RefField;
    ref int byRef = ref c1.RefField;
```

I would expect PropertyInfo.GetValue to do the first instead of throwing.

**Comment by AtsushiKan** [comment] 2018-04-09 14:25
This is a subset of https://github.com/dotnet/corefx/issues/15960 (15960 covers all existing Invoke methods, not just `PropertyInfo.GetValue`. So I'm closing this as a dupe of that.

**Closed by AtsushiKan** 2018-04-09 14:25 UTC
Labels: area-System.Reflection

**Comment by AtsushiKan** [comment] 2018-04-09 14:27
Any preference for what should happen if the method returns a null ref?

Here are the possibilities (ranked in descending order of my preference)

1. Return `System.Reflection.Missing.Value`
2. Throw `NullReferenceException`
3. Return `null`

**Comment by codan-toughb** [comment] 2018-12-04 04:43
Sorry to trouble you folks, but is this working in some form in .NET now?
Looking at this https://github.com/dotnet/coreclr/pull/17639 it would seem to suggest that it's possible.
