### ISSUE TITLE
FileSystemWatcher doesn't trigger in the temp folder on OSX

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#6675] opened 2016-03-04 22:49 UTC
I found a very peculiar bug that happens only under certain conditions. So, you need:

- To be running on OSX (ElCapitain in my case)
- The watched folder must be in the temp folder returned by `Path.GetTempPath()`

Here's the code to reproduce:

```csharp
// This works (update the username):          
// var folder = Path.Combine("/Users/victorhurdugaci/temp", Guid.NewGuid().ToString());

// This fails:
var folder = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

Console.WriteLine(folder);

Directory.CreateDirectory(folder);

using (var watcher = new FileSystemWatcher(folder))
{
    watcher.Created += (s, e) =>
    {
        Console.WriteLine("### Triggered");
    };
    
    watcher.EnableRaisingEvents = true;
    
    File.WriteAllText(folder + "/f2", "");
    
    Console.WriteLine("waiting...");
    System.Threading.Thread.Sleep(10000);
}
```

With the temp folder, it only prints

```
waiting...
```

With the user folder, it prints:

```
### Triggered
waiting...
```

Not sure if it's something special about the path characters or length. On my machine, the generated temp folder looks like `/var/folders/x4/h490d6xs4mndqfg5sk231_mw0000gn/T/1cc8944d-b218-4f95-8dd0-ea208fb9b9b7`

`System.IO.FileSystem.Watcher` version is `4.0.0-rc2-23826`

**Comment by victorhurdugaci** [comment] 2016-03-04 23:20
cc @sokket

**Comment by sokket** [comment] 2016-03-07 18:47
Interesting... @victorhurdugaci, can you open a terminal window and run

```mount```

and print the output? I'm curious to see if your tmp directory is mounted as a different file system or something. I'll dig into this shortly

**Comment by victorhurdugaci** [comment] 2016-03-07 19:03
The output of `mount`:

```
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
```

**Comment by sokket** [comment] 2016-03-07 19:05
Curious...that's what I have too. I'll dig in and see what I can come up with. Thanks for finding this @victorhurdugaci!

**Comment by sokket** [comment] 2016-03-08 19:38
@victorhurdugaci Is this blocking an rc-2 specific scenario around ASP.NET or can this be pushed to RTM?

**Comment by vcsjones** [comment] 2016-03-08 20:33
So I had a look at this for fun. I was able to reproduce the behavior on El Capitan. Looking through the source, I see that it is based on FSEvents API. I checked that my volume did not have fsevents disabled (and anything else that would make this fail).

Using `fswatch`, which is also backed by FSEvents, it did see the changes. So the issue isn't FSEvents or anything that is preventing the operating system from seeing the change.

**Comment by sokket** [comment] 2016-03-08 20:54
@vcsjones Thanks for the info, I can repro this locally as well. There shouldn't be anything in the FSW to prevent this scenario specifically...I'll step through and see what I come up with

**Comment by vcsjones** [comment] 2016-03-08 20:56
I suspect it is path length related, perhaps. If I use a path like `/Users/kjones/dfsdfdsfsdfjhsdlfksdhdfkdhfkjdhfgsdkfslfsldfkhsdkfdshflksdfldskjfh` then no event is fired, either.

**Comment by sokket** [comment] 2016-03-08 21:42
Ah I found the problem...The temp directory is ```/var/folders/<other things>```; however, this path is an alias to the ACTUAL temp path, which is ```/private/var/folders/<same other things>```, so the FSW thinks that the notifications are not under the watched directory and throws them away. It looks like the OS gives the full, non-aliased directory whereas ```Path.GetFullPath``` does not resolve through the alias. The fix is to resolve the actual target path and use that and not use the alias path

**Comment by victorhurdugaci** [comment] 2016-03-09 17:03
@sokket no, this is not blocking. It's just some test code for `dotnet-watch` creating a temp project

**Comment by sokket** [comment] 2016-03-09 18:42
Okay cool...I've tested a hacky fix for this but I'll try to get a real one in before RC2

**Comment by sokket** [comment] 2016-03-10 00:57
PR #6792 is out to fix this

**Comment by sokket** [comment] 2016-03-11 17:59
Fixed. Thanks @victorhurdugaci for finding this!

**Closed by sokket** 2016-03-11 17:59 UTC
Labels: Mac OSX, System.IO
