### ISSUE TITLE
Ping not working

### ISSUE THREAD

**Issue by markusmobius** [dotnet/corefx#35030] opened 2019-02-01 19:23 UTC
I am running a scraper which spawns up to 50 child processes that each perform a scraping tasks - either through headless Chrome (calling node/puppeteer) or HttpClient. I recently switched to NetCore (currently running 3.0 preview 2 but had the same issues under 2.2).

I am also periodically checking if the internet connection is up. On Windows everything works fine. However, on Ubuntu 18.04 I am getting inconsistent performance and network requests seem to take a long time. For example aboiut 10% of pings have timeout errors:

```c#
        static bool CheckForInternetConnection()
        {
            var pingSender = new Ping();
            var start = DateTimeOffset.UtcNow;
            var reply = pingSender.Send("www.google.com", 5000);
            Console.WriteLine(reply.RoundtripTime);
            Console.WriteLine(reply.Status+":"+(DateTimeOffset.Now-start).TotalMilliseconds);
            return reply.Status == IPStatus.Success;
        }
```

```
TimedOut:4279.9648
TimedOut:1093.1479
TimedOut:782.6614
TimedOut:344.7731
TimedOut:922.3762
Success:22.5606
TimedOut:1221.1045
```

I am puzzled because I can simultaneously ping from the command line and all the ping work just fine while I am simultaneously seeing these failures in my code. (as an aside, I also don't understand why TimeOut often happens earlier than 5000 milliseconds given that I specified 5000 explicitly). 

Right now this is preventing me from running this code on Linux. I am also using the new SocketsHTTPHandler for HttpClient in the child processes. The machine is a large VM with 16 cores and tons of I/O - and the same type of VM runs the same code on Windows fine.

**Comment by wfurt** [comment] 2019-02-01 19:42
Do you run this as root or not @markusmobius ? If not, could you give it try? (non-admin start new ping process for every request) 

Also I don't know how many sites you trying get to but make sure you descriptor limit is pretty high. 
  
From the description (wild guess) is sounds like you may have issues with DNS. 

You can also try ping with specific pattern and than do wireshark/tcpdump to get more information from the wire.

**Comment by markusmobius** [comment] 2019-02-01 20:05
I just ran as admin.

I get the same timeouts but now it seems to respect the milliseconds parameter:

TimedOut:5041.5637
TimedOut:5007.4177

I don't know what could be wrong with DNS - for testing I instructed 40 HTTPclient child processes to scrape my homepage - www.markusmobius.org 

When I run ping in a command window I consistently get 5ms for the roundtrip.

When I observe at the same time the output from my testprogram which runs the pings after each scrape then I get these timeouts (but only on Ubuntu).  On the other hand, for the successful pings the roundtime for the ping within the C# program is also exactly 5ms (as on the command line).

I suspect that the same issues happen within the child processes too because the scraper is half as slow on Linux compared to Windows with many queries taking much longer than expected.

**Comment by wfurt** [comment] 2019-02-01 20:13
ok. now, lets do one more test. For the ping, use address www.google.com resolves to from command line. 

You can also look for any suspicious error counters: `netstat -s` and `ifconfig -a` It sounds like you have issues is not specific only to ping. Is this VM or physical server?

**Comment by wfurt** [comment] 2019-03-13 22:23
do you have any more information @markusmobius ? This is currently not actionable as seems related to your setup. I could not reproduce it locally.

**Comment by karelz** [comment] 2019-04-02 22:00
Unable to reproduce, closing.
Feel free to reopen if there is more info.

**Closed by karelz** 2019-04-02 22:00 UTC
Labels: area-System.Net, needs more info, os-linux
