### ISSUE TITLE
StartsWith extremly slow on Linux if Culture is not en-US

### ISSUE THREAD

**Issue by mshobohm** [dotnet/corefx#41313] opened 2019-09-25 13:46 UTC
I noticed some situations where String.StartsWith is getting extremly slow on Linux-x64 under certain conditions:
 - CultureInfo of the Thread is not en-US (depending on OS-Environment) 
- using StringComparison.CurrentCulture (which is default for .NET Core!!!!)
Output of my test program on Linux:
sc: CurrentCulture       ci: en-US  time:                28443 µs
sc: CurrentCulture       ci: en-EN  time:              1722245 µs
sc: CurrentCulture       ci: de-DE  time:              1381201 µs
sc: CurrentCulture       ci: fr-FR  time:              1411512 µs
sc: InvariantCulture     ci: en-US  time:                 6705 µs
sc: Ordinal              ci: en-US  time:                 1355 µs

[StartsWithSlow.zip](https://github.com/dotnet/corefx/files/3652751/StartsWithSlow.zip)

**Comment by vcsjones** [comment] 2019-09-25 14:46
I beleive this is a mostly known issue as discussed in #40674. There is an open pull request to improve the performance here https://github.com/dotnet/coreclr/pull/26621

**Comment by mshobohm** [comment] 2019-09-25 15:03
StringComparison.Ordinal is much faster in any way, why isn't it the default? I think most programmers don't need this luxury comparison.

**Comment by jkotas** [comment] 2019-09-25 21:22
Duplicate of #40674.

**Comment by jkotas** [comment] 2019-09-25 21:23
cc @adamsitnik

**Closed by jkotas** 2019-09-25 21:22 UTC
