### ISSUE TITLE
'Implicit conversion loses integer precision' error

### ISSUE THREAD

**Issue by jcagme** [dotnet/corefx#25682] opened 2017-12-04 17:39 UTC
Of the last 5 builds, 4 have failed with the following:

> /root/corefx-1191223/src/Native/Unix/System.Native/pal_networking.c:2286:29: error: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Werror,-Wshorten-64-to-32]

Links to these:

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1190370
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1191223
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1191695
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1192572

**Comment by weshaggard** [comment] 2017-12-04 17:45
@stephentoub looks like it is caused by your recent changes.

**Comment by weshaggard** [comment] 2017-12-04 17:47
Looks related to PR https://github.com/dotnet/corefx/pull/25579

**Comment by stephentoub** [comment] 2017-12-04 17:47
Are we using a different compiler in those builds?  This is compiling just fine in PRs and rolling builds from master.

**Comment by weshaggard** [comment] 2017-12-04 17:53
That is a question for @dotnet/dnceng

**Comment by markwilkie** [comment] 2017-12-04 17:59
There is a bit of a "mix" right now between dev15 and dev14  as we're moving to 2017.  @mmitche - what's the right way to determine which VSTS machines are which?

**Comment by stephentoub** [comment] 2017-12-04 18:00
> There is a bit of a "mix" right now between dev15 and dev14 as we're moving to 2017

This is on Unix, though.

**Comment by mmitche** [comment] 2017-12-04 18:02
Only 2015 should be in use for the official builds.  On Unix, the same docker containers should be being using in PR/Official.   This warrants investigation

**Comment by markwilkie** [comment] 2017-12-04 18:04
@stephentoub - sigh....read this too fast.  I've not heard that we've updated compilers on those images recently.  But clearly, to your point - something is different.  @JohnTortugo - can you take a look please?

**Comment by JohnTortugo** [comment] 2017-12-04 18:13
@markwilkie Sure, will do!

**Comment by markwilkie** [comment] 2017-12-04 21:35
Thanks @stephentoub - is this a work around and there's still a mis-matched compiler issue going on?

**Comment by stephentoub** [comment] 2017-12-04 21:37
> is this a work around and there's still a mis-matched compiler issue going on?

It's a workaround for what could be a valid compiler error, but it doesn't reproduce in PR / master builds from the repo.  So there's still an investigation that should be done to understand why it breaks in one place but not the other.

**Comment by markwilkie** [comment] 2017-12-04 21:38
Thanks for unblocking the builds @stephentoub.  @JohnTortugo, please continue your investigation as to why there's a mis-match.  @chcosta can help where needed.

**Closed** 2017-12-05 02:32 UTC
Labels: area-Infrastructure, bug
