### ISSUE TITLE
DateTimeFormat.FirstDayOfWeek returns different days

### ISSUE THREAD

**Issue by piotrkolodziej** [dotnet/corefx#34278] opened 2018-12-29 15:39 UTC
Hello,

On macos with the Polish culture set (Monday being first day of the week) in the system the following piece of code returns different results depending on the method used to run the app:

CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek

1. 'Sunday' when running app from terminal via dotnet run (also tried with -c Release)
2. 'Sunday' when running app from Rider debug/terminal
3. 'Monday' when run via terminal built in vs code
4. 'Sunday' when run via vs code debug

We are getting ready to deploy the feature on production and would greatly appreciate your insight.

Version: 2.2

**Comment by danmosemsft** [comment] 2018-12-29 19:15
How curious. Can you please log Culture Info.CurrentCulture to make sure that it is the same in all cases? Also please log the environment variables. Are any different?

**Comment by piotrkolodziej** [comment] 2018-12-29 19:34
@danmosemsft indeed the culture is different. I can only add that when I was installing the system I've chosen the British language for the system and polish keyboard. What is peculiar is that the culture is British even though I have a Region set to Poland in system settings. Anyway, without further ado, here is the piece of code along with the output (simple console project generated with dotnet new console CLI command).

`
Console.WriteLine(CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek);
Console.WriteLine(CultureInfo.CurrentCulture.EnglishName);

foreach(System.Collections.DictionaryEntry e in System.Environment.GetEnvironmentVariables())
{
    Console.WriteLine(e.Key  + ":" + e.Value);
}
`

VS Code terminal output:

`
Monday
English (United Kingdom)
_:/usr/local/share/dotnet/dotnet
SHELL:/bin/bash
XPC_FLAGS:0x0
USER:shanti
LANG:en_GB.UTF-8
__CF_USER_TEXT_ENCODING:0x1F5:0x0:0x0
SSH_AUTH_SOCK:/private/tmp/com.apple.launchd.ABcUYkJjdt/Listeners
TMPDIR:/var/folders/dt/z6_mdxs17y3g81qm79_rj0mc0000gn/T/
Apple_PubSub_Socket_Render:/private/tmp/com.apple.launchd.HhZPoxoNfG/Render
XPC_SERVICE_NAME:0
TERM_PROGRAM:vscode
TERM_PROGRAM_VERSION:1.30.1
PWD:/Users/shanti/Desktop/culturetest
TERM:xterm-256color
PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin
HOME:/Users/shanti
LOGNAME:shanti
SHLVL:2
`

MacOS terminal output:

`
Invariant Language (Invariant Country)
XPC_SERVICE_NAME:0
SHELL:/bin/bash
TERM_PROGRAM_VERSION:421.1
TERM:xterm-256color
SHLVL:1
TERM_PROGRAM:Apple_Terminal
__CF_USER_TEXT_ENCODING:0x1F5:0x0:0x0
TMPDIR:/var/folders/dt/z6_mdxs17y3g81qm79_rj0mc0000gn/T/
SSH_AUTH_SOCK:/private/tmp/com.apple.launchd.ABcUYkJjdt/Listeners
PWD:/Users/shanti/Desktop/culturetest
USER:shanti
LC_CTYPE:UTF-8
TERM_SESSION_ID:8A76ABE4-B806-4405-AB3F-43E51B064A6B
LOGNAME:shanti
PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin
Apple_PubSub_Socket_Render:/private/tmp/com.apple.launchd.HhZPoxoNfG/Render
_:/usr/local/share/dotnet/dotnet
OLDPWD:/Users/shanti/Desktop
HOME:/Users/shanti
XPC_FLAGS:0x0
`

**Comment by danmosemsft** [comment] 2018-12-29 19:53
Yeah I guess VS Code remembered your preference and sets LANG:en_GB.UTF-8 on itself, which propagates to dotnet. Maybe there is a setting for that. Anyway I guess this issue is resolved?

**Comment by piotrkolodziej** [comment] 2018-12-29 20:00
@danmosemsft the issue is NOT resolved as far as I am concerned. Can you tell me why dotnet core is not recognising the culture based on the region set on the macos system and setting the invariant culture?

When I worked with .NET Framework on windows some time ago it correctly read the region settings and correctly set the culture.

**Comment by danmosemsft** [comment] 2018-12-29 20:09
I believe that on Unix the LANG environment variable can be used to force the culture. My interpretation of your listing above is that VS Code is setting it for some reason. When it launches the child process, environment variables are inherited, including this one. Therefore dotnet is behaving as designed. In Windows there is no such variable (that I am aware of).

I am not an expert in this area..@krwq is this correct?

**Comment by danmosemsft** [comment] 2018-12-29 20:41
@krwq or @tarekgh will have to comment on that.

**Comment by tarekgh** [comment] 2019-01-02 20:59
@piotrkolodziej there is manythings can change the default locale which don't match the region. I would suggest you run ```locale``` command on your terminal and send the output. 

you may look at the post https://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/ as example of some settings can affect the default locale. 

in general .Net Core depends on ICU getting the default locale and we just special case the "C" and "POSIX" locales and return invariant for that. ICU just return what the user/system set the default locale. I think the problem is in your settings on the system.

**Comment by tarekgh** [comment] 2019-01-17 16:38
@piotrkolodziej I am closing this issue but feel free to reply back and we can activate it again if there is any help we can provide from the framework side. so far, this issue is kind of environment configuration more than a framework issue.

**Closed by tarekgh** 2019-01-17 16:38 UTC
Labels: area-System.Globalization, question
