### ISSUE TITLE
Some characters are missing when drawing Chinese characters【System.Drawing.Common】

### ISSUE THREAD

**Issue by LuceLuo** [dotnet/corefx#31091] opened 2018-07-16 08:41 UTC
`var font = new Font("黑体", 16, FontStyle.Regular);`
`var font4 = new Font("宋体", 16, FontStyle.Regular);`

`g.DrawString("黑体：中文姓名", font, brush, 30, 100);`
`g.DrawString("宋体：刘三名", font4, brush, 30, 190);`

Using the above code, only show "黑体：中文姓" 、"宋体：刘".
If other non Chinese characters are added to the tail, it can be displayed normally.
Like this:

`g.DrawString("黑体：中文姓名(1111)", font, brush, 30, 100);`

**Comment by filipnavara** [comment] 2018-07-16 08:44
Duplicate of #30867.

**Comment by LuceLuo** [comment] 2018-07-16 09:44
@filipnavara 
I read a lap of articles and I know the problem, but I don't know the specific solution. Can you tell me how to install libgdiplus with pango?

**Comment by karelz** [comment] 2018-07-16 18:22
Duplicate of #30867

**Closed by karelz** 2018-07-16 18:22 UTC
