### ISSUE TITLE
Vaildation of ETW events need TraceEvent

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#4864] opened 2015-12-07 20:36 UTC
EventSource needs TraceEvent to validate ETW events in the tests.

**Comment by AndyAyersMS** [comment] 2016-05-10 17:37
Any progress on this?

**Comment by davmason** [comment] 2016-05-12 04:52
Do you need TraceEvent for something? I haven't done any work towards this, but others may have.

@vancem may know more.

**Comment by vancem** [comment] 2016-05-12 16:05
I looked into this a few months ago.   At the time I knew next to nothing about getting things built on CoreCLR, which slowed the investigation, but what I did learn suggested that it was straightforward but not trivial (there are missing APIs that you have to work around).    At the time I wanted to wait for CoreCLR build tools to mature (I did not want to be on the bleeding edge).   
 
Sadly we are still not in a great position as build tools for CoreCLR (VS still does not formally support them), however I think I am in a better position to hack around the problem to at least determine how much work would be involved (hopefully measured in hours).   

I will look into it.  Ping me again in a week if I have not reported back by then.

**Comment by karelz** [comment] 2017-03-02 21:28
Triage: Belongs to PerfView repo - @vancem can you please link it and close this one?

**Comment by karelz** [comment] 2017-03-02 22:05
Dupe of the PerfView linked issue

**Comment by ViktorHofer** [comment] 2017-04-14 10:53
@karelz we have some disabled tests in corefx which refer to this issue (https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs#L122), therefore I wouldn't close it but set the milestone to future.

**Comment by karelz** [comment] 2017-04-14 15:09
Makes sense, thank you!
cc @brianrob

**Comment by ViktorHofer** [comment] 2017-08-23 21:05
@vancem just ported Microsoft.Diagnostics.Tracing.TraceEvent (nuget package) to .NET Core. We should include the package in our runs and remove the `#if USE_ETW` conditions in the System.Diagnostics.Tracing sources to enable the tests.

cc @weshaggard (FYI, for adding the package to the runs)

**Closed** 2018-02-14 04:25 UTC
Labels: area-System.Diagnostics.Tracing, disabled-test, test enhancement
