### ISSUE TITLE
System.Diagnostics.Process should not inherit handles by default

### ISSUE THREAD

**Issue by whoisj** [dotnet/corefx#14238] opened 2016-12-06 17:35 UTC
When a Windows process starts another process, the parent gets the option of having the child process inherit all of the parent's inheritable handles. Additionally, every handle has a flag on it specifying if it is inheritable or not. 

CoreFx has the `bInheritHandles` argument hard coded to `true`. While this feature can be useful, it can cause untold number of problems.

This of the situation where you have a file handle, and you've acquired that file handle with `FileShare.None` set. While the handle is opened, you start a child process. That child gets a copy of that handle, now they cannot use it because you've selected no sharing, but they have a copy of it. Since closing of file handles is a reference counting game, you're now unable to close the file. Sure, you can close your local handle, but you'll be unable to re-open it until the child process' handle is closed as well.

If the child spawns a child, the grand-child process will also keep a copy of the handle and could never get your file back.

This becomes worse in the case of redirected pipes. Imagine this setup:

1. Thread A starts creating a new process with redirected output
2. Thread B starts creating a new process designed as a long running service (think redis or something)
3. Thread A creates the necessary handles to redirect output.
4. Thread B calls Kernel32.dll!CreateProcess to create the process, the new process inherits the handles Thread A created for its child (but it doesn't know that and it cannot use them).
5. Thread A calls Kernel32dll!CreateProcess.
6. Thread A attempts to read standard output until it closes.
7. Thread A child process exits, and closes the handles it was given __BUT__ the pipes do not close because Thread B child process has a handle on them (and closing is a reference counting game).

Effectively, Thread A is deadlocked attempting to read from the stand output pipe of its child process (even though said process has exit already) until Thread B child process exits (and closes its handles).

This is a disaster. Handle inheritance should be take seriously, and it appears the CoreFx library isn't doing so. Ideally, the `bInheritHandles` parameter would be null unless `STARTF_USESTDHANDLES` is specified. When `STARTF_USESTDHANDLES`, then the advice of Raymon Chen should be followed: "[The case of the redirected standard handles that won’t close even though the child process has exited](https://blogs.msdn.microsoft.com/oldnewthing/20131018-00/?p=2893)".

There is an attempt to correct this bad behavior via a `Monitor` lock placed around the calls to `CreateProcess` calls. This is fine so long as all code in a process is running though CoreFx, but in any reasonable sized project that cannot be assumed.

**Comment by akoeplinger** [comment] 2016-12-06 17:38
There were some concerns raised in the api review of this issue (which seems like a dupe): https://github.com/dotnet/corefx/issues/306

**Comment by karelz** [comment] 2016-12-06 17:40
Closing as a dupe of #306.
Please let me know if you think there are other reasons to keep this one opened.

**Closed by karelz** 2016-12-06 17:40 UTC
Labels: area-System.Diagnostics.Process

**Comment by whoisj** [comment] 2016-12-06 17:50
@karelz I disagree that this is a dupe of #306.

That issue suggest that CoreFx expose an option to make the handle inheritable. I am suggesting that CoreFx should default to false, and only inherit handles if a `ProcThreadAttributesList` is correctly prepared as associated with the call to `CreateProcess`.

If CoreFx wants to accept an `IEnumerable<SafeHandle>` or similar to add to the `ProcThreadAttributeList` then so be it, but a blind inheritance of all handles seems dangerous and unnecessary; if not down right harmful and/or dangerous.

**Comment by karelz** [comment] 2016-12-06 18:01
@Priya91 would it be a breaking change to change the default?

@whoisj mentioned good motivation for it -- it causes lots of trouble in VS where 3rd party plugins do the wrong thing ... in Desktop we would have to quirk it, but maybe changing the default on .NET Core might be desirable for long-term?

**Comment by whoisj** [comment] 2016-12-06 18:02
For the record, we (VSVC) are seeing this happen in our product. Ironically, it was the Roslyn team which first reported the issue and this is the root cause of the hangs they were seeing.

Effectively, we got reports that VS was hanging with our code at the top of the stack. Every time we were stuck in `ReadNativeFile` attempting to read from standard output of a process with redirected outputs. In every case, the process had exited long ago but the pipe wasn't closing and call to `ReadNativeFile` never returned.

Eventually, we discovered that third-party plug-ins were getting accidental copies of the handles and never closing them, thus the pipe stayed open for the life of VS; and VS was "hung" from the user's experience. 

As a work around, we've minimized the window in which a System.Diagnostics.Process could "steal" handles from us, but it'll continue to be a race condition until this gets resolved.

Thanks!

**Comment by Priya91** [comment] 2016-12-07 07:43
> @Priya91 would it be a breaking change to change the default?

Yes it would be. There's an another issue filed long back on this to expose a new property to control this behavior. 

This issue will be a dupe of #306 

There was an api review on this long time back, it would be worth it to revisit this once again. @whoisj Feel free to drop your comments on the tagged issue.

**Comment by whoisj** [comment] 2016-12-07 15:16
It seems the heavens are aligning on this issue:

https://blogs.msdn.microsoft.com/oldnewthing/20161207-00/?p=94875

**Comment by stephentoub** [comment] 2016-12-07 15:22
> Changing the default behavior won't be supported, as it will introduce a compat risk on desktop

I  expect it would also break a lot of code even on core, such as apps using anonymous pipes  and expecting the handles to be inherited.

Implementing this on Unix would I expect also be tricky. The only way I'm aware of doing it would be making ~30K calls to close all file descriptors > 2, which would be expensive and potentially error prone.

I'm fine seeing an option added, but I'd be concerned about the default changing.

**Comment by paultetley** [comment] 2017-05-29 07:17
@stephentoub - As a cheaper implementation, could you not just iterate over /proc/<pid>/fd ?

As a consumer of this API I don't have a strong view on what the default behaviour should be but we very much need a mechanism to avoid inheritance, as our application which makes extensive use of System.Diagnostics.Process is suffering from exactly the sorts of issues the OP describes.

**Comment by stephentoub** [comment] 2017-05-29 14:58
> As a cheaper implementation, could you not just iterate over /proc/<pid>/fd ?

Maybe, on platforms where procfs exists (e.g. not on macOS)

**Comment by tmds** [comment] 2017-05-29 16:05
On Linux, there shouldn't be many handles that get inherited. Sockets and files are opened with CLOEXEC.
