### ISSUE TITLE
What about adding interfaces to FileInfo and DirectoryInfo?

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/corefx#2022] opened 2015-06-12 18:29 UTC
When testing it would be nice to be able to mock the filesystem. Would a PR introducing interfaces be accepted?

**Comment by KrzysztofCwalina** [comment] 2015-06-19 22:59
Yeah, I think we need to improve our file i/o APIs here. In general I am conservative on mocking (I think some people mock too much), but file system is a heavy dependency that just needs to be mocked in many cases. 

But, I am not sure if it's FileInfo, DirectoryInfo, or some other APIs (File.Open, FileStream, etc). It would be great if somebody wrote a solid proposal analyzing the scenarios, problems, and showing how proposed changes would solve the problems.

**Comment by akoeplinger** [comment] 2015-06-19 23:06
Some discussion about mocking file APIs also happened here: https://github.com/dotnet/corefx/issues/312

**Comment by ckuhn203** [comment] 2016-02-07 14:34
@KrzysztofCwalina what would you consider a "solid proposal". I too think the API needs some work, and you're right, this goes beyond the classes originally mentioned and into a great portion of the API in general. I'm absolutely sure that people working on cross platform stuff struggle with this as the file systems for different platforms are vastly different. Having a nice abstraction to work with goes beyond being able to stub or mock the file system, albeit, that is my greatest motivation for being interested in this. 

Sometimes it's not only necessary to stub the file system for testing, but also to verify that you're writing/reading as expected. It is certainly much nicer to do this in memory when there are multiple devs or a CI server involved. 

I'm 100% willing to work on this if you can clarify what you expect out of a proposal.

**Comment by KrzysztofCwalina** [comment] 2016-02-10 22:03
Solid proposal would talk about the following:
1. Write motivation for the feature, including an example, e.g. what are the tests testing that need file i/o abstracted.
1. Show new APIs that are being proposed (all types, members, namespaces, assemblies).
2. Show existing APIs that would need to change, i.e. what types implement and consume the abstractions (consume meaning take as parameters)
3. Show how these new APIs would be used.
4. Explain why these new abstractions need to be in CoreFx as opposed to in user code (e.g. in tests)
5. Explain why it's ok for existing code to use concrete APIs as opposed to these abstractions, e.g. File.ReadAllLines would not use these, would it?

**Comment by karelz** [comment] 2016-10-11 21:26
Dupe of #312

**Closed by karelz** 2016-10-11 21:26 UTC
Labels: api-needs-work, area-System.IO, up for grabs
