### ISSUE TITLE
Why HttpClient can't run on linux(coreclr-1.0.0-beta8-15776)

### ISSUE THREAD

**Issue by lo87** [dotnet/corefx#3550] opened 2015-09-30 12:40 UTC
It's not ready yet?
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;

namespace ConsoleApp2
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (HttpClient client = new HttpClient())
            {
                Task<string> task = client.GetStringAsync("https://github.com/");
                task.Wait();
                Console.WriteLine(task.Result);
            }
            Console.WriteLine("exit!!");
        }
    }
}
```

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Net.Http, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Http'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at ConsoleApp2.Program.Main(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Http'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by davidsh** [comment] 2015-09-30 14:05
This is a dupe of #2155.

The work of including cross-platform binaries into the NuGet packages has not yet been completed.  The team is actively working on it.

cc: @ericstj @chcosta

**Comment by davidsh** [comment] 2015-09-30 14:05
I will close this issue since it is a dupe. Updated status will be posted to #2155.

**Closed by davidsh** 2015-09-30 14:05 UTC
Labels: System.Net, X-Plat

**Comment by davidsh** [comment] 2015-09-30 19:56
@lo87 

Beta8 should be released soon.  You can try it out by using this MyGet feed which has cross-platform support in the packages.

https://www.myget.org/gallery/aspnetbeta8
