### ISSUE TITLE
Add attribute to System.Text.Json.Serialization to include nulls

### ISSUE THREAD

**Issue by lfr** [dotnet/corefx#42034] opened 2019-10-23 12:55 UTC
Please add the equivalent to Newtonsoft's `[JsonProperty(NullValueHandling = NullValueHandling.Include)]` that forces inclusion of a member with null value even when the general options dictate that null valued members not be included.

**Comment by steveharter** [comment] 2019-10-24 15:55
This is a duplicate of https://github.com/dotnet/corefx/issues/40600. Please take a look at that. Thanks.

**Closed by steveharter** 2019-10-24 15:55 UTC
Labels: area-System.Text.Json

**Comment by lfr** [comment] 2019-11-13 09:51
@steveharter it's not a duplicate, if you look carefully that suggestion only allows overriding the default behavior from not ignoring to ignoring a specific property. Json.NET's [NullValueHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm) attribute allows also enables overriding the default behavior in the other direction, from ignoring nulls by default to **including nulls** for a specific property. I believe this issue should remain open to ensure the new feature allows overriding the default behavior in both ways.
