### ISSUE TITLE
API Proposal: System.Text.Json: Handle default value in serialization

### ISSUE THREAD

**Issue by bharathm03** [dotnet/corefx#42636] opened 2019-11-19 05:22 UTC
# Overview
To enable option to ignore properties from serialization when its current value is equal to default value. We can reuse the existing `DefaultValueAttribute` class for defining the default value for each property. 

# Why
This API is needed to reduce the payload size of JSON text transferred between services which will improve the app performance. 

# API Proposal
Add new API `IgnoreDefaultValue` in `System.Text.Json.Serialization.JsonSerializerOptions` class.

Example usage
```CSharp
public class Cookie
{
  [DefaultValue(false)]
  public bool HasConsent  {get; set;}

  public string Name {get; set;}
}

public class Program
{
  static void Main()
  {
    var cookie = new Cookie { Name = "Test", HasConsent = false };

    var options = new JsonSerializerOptions();
    options.IgnoreDefaultValue = true;

    string json = JsonSerializer.Serialize(cookie, options);
    // Expected output:  {"Name":"Test"}
  }
}
```

Edit:
- Added expected output in example

**Comment by layomia** [comment] 2019-11-20 22:56
Duplicate of https://github.com/dotnet/corefx/issues/42635.

**Closed by layomia** 2019-11-20 22:56 UTC
Labels: area-System.Text.Json

**Comment by ahsonkhan** [comment] 2019-11-25 23:35
> Duplicate of #42635.

Which is a duplicate of https://github.com/dotnet/corefx/issues/38878
