### ISSUE TITLE
Port/improve Mono's managed Dns implementation?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#28892] opened 2018-04-06 19:09 UTC
@migueldeicaza highlighted to me today that Mono has a managed DNS implementation:
https://github.com/mono/mono/tree/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/System/Mono.Net.Dns
We should look into whether it would make sense to port and improve upon that, so as to be able to avoid depending on the DNS resolution capabilities built into specific OSes (e.g. we rely on Windows for its overlapped I/O support, but an equivalent doesn't exist built-in on Linux, and so there our async support is based on queueing work items that in turn invoke the synchronous APIs).

cc: @migueldeicaza, @geoffkizer

**Comment by kasper3** [comment] 2018-04-06 19:36
What are the restrictions in it for not being able to run on mobile device: https://github.com/mono/mono/blob/2f211770198d741a35cf1f713e639cc66505db44/mcs/class/System/System.Net/Dns.cs#L47 ?

**Comment by marek-safar** [comment] 2018-04-21 03:33
@stephentoub you can find the code under https://github.com/mono/mono/tree/master/mcs/class/System/Mono.Net.Dns the main entry point is SimpleResolver.cs. It's an opt-in feature enabled via an environment variable called `MONO_DNS`. Looking at the history you can see we didn't touch it much recently ;-)

**Comment by migueldeicaza** [comment] 2018-05-03 19:34
It lacks some of the new features, like secure DNS, but it is a starting point.

**Comment by karelz** [comment] 2019-10-01 21:56
Duplicate of #13890

**Closed by karelz** 2019-10-01 21:56 UTC
Labels: area-System.Net, enhancement
