### ISSUE TITLE
HTTP2: Http2Stream ObjectDisposedException

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#38711] opened 2019-06-20 02:55 UTC
1. git clone https://github.com/grpc/grpc-dotnet.git
2. examples/server -> dotnet run
3. examples/clients/mailer -> dotnet run
4. Press ESC

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Http2Stream'.
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.ReadMessageCoreAsync[TResponse](Stream responseStream, ILogger logger, Func`2 deserializer, CancellationToken cancellationToken, Boolean canBeEmpty, Boolean singleMessage) in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\StreamExtensions.cs:line 61
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken) in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\HttpContentClientStreamReader.cs:line 123
   at Sample.Clients.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext() in C:\Development\Source\grpc-dotnet\examples\Clients\Mailer\Program.cs:line 50
```

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012518
 Commit:    da94a8cc8d
```

**Comment by JamesNK** [comment] 2019-06-20 03:09
I think there is a race condition.

https://github.com/grpc/grpc-dotnet/blob/7713ed096f204d6f4546e7ae0c0f21c0f33acdfb/src/Grpc.Net.Client/Internal/GrpcCall.cs#L171-L181

Line 171 will cancel the token that is passed to ResponseStream.ReadAsync.
Line 181 disposes the response. Commenting out 181, or adding `Thread.Sleep(1000)` before it will stop the error.

**Comment by JamesNK** [comment] 2019-06-20 03:09
@wfurt

**Comment by wfurt** [comment] 2019-06-20 04:24
so far I could not reproduce it but if that it race, it may be hard. What do you expect here? OperationCanceled? 

This is related to discussion in  as Cancelation is ignored by ReadDataAsync()

cc: @stephentoub @geoffkizer

**Comment by wfurt** [comment] 2019-06-20 05:03
missed to add reference to #38226

**Comment by JamesNK** [comment] 2019-06-20 10:18
I consistently get ObjectDisposedException. It is only when I add a Thread.Sleep that it isn't thrown.

**Comment by wfurt** [comment] 2019-06-23 22:08
This should be fixed by #38226

**Closed by wfurt** 2019-06-23 22:08 UTC
Labels: area-System.Net.Http.SocketsHttpHandler
