### ISSUE TITLE
Hardware Details API - Hardware Fingerprint

### ISSUE THREAD

**Issue by louislewis2** [dotnet/corefx#3324] opened 2015-09-19 18:56 UTC
It would be great to add an api that we could use to get hardware specific information.
Some of these may include 
1. Mac Addresses
2. Processor Information
3. Graphic card Information
4. Base Board Information
5. Unique fingerprint based on hardware

I think many applications out there implement features depending on what hardware is available.
Furthermore like us, licensing applications in certain scenarios is a must, and I am sure that many applications out there currently, make use of hardware information to create a unique fingerprint which is calculated from hardware information.

**Comment by Clockwork-Muse** [comment] 2015-09-19 23:28
Random stuff to consider:
What's a hardware fingerprint supposed to look like in the case of virtualization (or other emulation)?
Does providing a fingerprint touch privacy information that the OS wants to control?
To what extent is "my grandfather's ax" supported?  
What MAC address is returned if the value has been remapped?

I personally am a little unclear on some of the effects due to our current open-source status and project setup; would it be possible for interested users to recompile (potentially the whole stack) and run things?  IE, able to change the answers for any of this?

(side note: fingerprinting hardware really only does you any good if you have a central auth server, which probably means floating/per-seat licensing is achievable)

**Comment by cdrnet** [comment] 2015-09-20 05:44
I assume that disabling the advertisement ID in the Windows privacy settings would have to disable such a fingerprint off as well?

**Comment by Clockwork-Muse** [comment] 2015-09-20 12:50
@cdrnet - hmm, something like that, although I think I'd go for a separate setting, especially as there's a number of cases where the user can't change it/reset it (ie, tablets).  It's more pervasive and harder or "impossible" to get an 'anonymous' one.

I kinda feel like a per-hardware license (for programs) runs counter to where Windows is going ("use the same app on every device you own").  Proliferation of 'cloud' services and virtualization in general would play havoc wrt to hardware ids, too; be interesting to see where things go in the future.

**Comment by louislewis2** [comment] 2015-09-21 10:57
I think that there should be a distinction between user applications and server applications. While it may make sense for a user app to be able to transition from device to device the same should not be said for server applications. 

If providing a "fingerprint" method is harder to achieve, I think providing developers with an api that will allow them to get hardware details which they can use to create their own fingerprint for their software.

This also has other use cases other than licensing, I was involved in a project which delivers a service to customers, where each instance of the application gets a unique fingerprint for the hardware that it is currently running on, it then dynamically creates Azure service bus items. This allowed customers to not require a public ip address for the software to which devices and services connect too.

While virtualisation comes with its own set of issues, those issues are more relevant and perhaps more problematic when it comes to licensing as a use case.

**Comment by Clockwork-Muse** [comment] 2015-09-21 23:25
@louislewis2 - I wasn't expecting a machine to be externally addressable via a fingerprint.  How did that work?

**Comment by louislewis2** [comment] 2015-09-21 23:53
I am merely trying to show that licensing is not the only use case to have a fingerprint or the ability to create one from hardware information. The example I added was just 1 feature we have built before that required a unique per device id, which we called a fingerprint.

Of course that solution was on Windows and we used the .Net framework's (System.Management.ManagementClass) to get hardware information and then from that constructed a fingerprint.

In another project, we are using the above to create a fingerprint used for licensing server instances of our software. While it is not hack proof if there even still exists such a notion, we find that in our specific industry it serves us well.

As for the particulars for the example you had a question about, an instance of that software connects a local running service (SOAP as example) and then connects it to the public internet via Azure Service Bus, specifically a relay binding. That allowed us to deliver software without requiring the customer in question to first acquire a static ip address to expose their services to mobile devices and other server instances. I think that solution sat well with clients because within 3 months if memory serves me correctly, there was around 100Gb moving through Azure a month.

In another example we are using that fingerprint to identify nodes in a distributed communication system. I really think there is a need for such an api to exist as their are truly many use cases that warrant it.

**Comment by karelz** [comment] 2016-11-23 23:04
We need formal API proposal

**Comment by louislewis2** [comment] 2017-05-09 19:24
@karelz Your last comment, seemed at the time like one meant for internal discussion.
Did you want anyone to suggest an API? All though not technically your problem, the lack of this feature in .Net Core and with the change that is currently being discussed in the link above, simply put means that we need to drop using ASP.NET Core all together. This would only put us back around 2 years, as we have been developing on the app since ASP.NET Core began its life.

This is also the primary key in our licensing server.

Any new news here?

Thanks

**Comment by karelz** [comment] 2017-05-09 21:33
I updated the text above with link and "next steps" prefix, that will hopefully clarify it -- sorry for the text not being clear (it was at the time we just started with proper triage).

It is marked Future = we do not intend to work on it now. It is up-for-grabs, so anyone is welcome to take a stab at it. See [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified) for details.

I don't understand why lack of this API would affect your decision to drop ASP.NET Core. Can you please explain that?
My understanding is (please correct me if I am wrong) that this API does NOT exist in Desktop/full .NET Framework today, right?

Stating the obvious, just in case:
* If other decisions (e.g. the issue linked above) require this feature to happen sooner, it may get funding sooner.
* In general, I would recommend to collect votes on issues you think are important -- for example DirectoryServices, Drawing PerfCounters, and few other libraries have lots of votes = lots of customers need them, therefore they are on top of our backlog. I see only 1 vote here, hence it is naturally lower in the backlog.

**Comment by louislewis2** [comment] 2017-05-09 22:47
To the best of my knowledge it does exist in the full framework today.
I refer to the link below, or am I misunderstanding?

https://msdn.microsoft.com/en-us/library/system.management.managementclass(v=vs.110).aspx

As the decision that has been made for ASP.NET Core to stop support for the .Net Framework, it means that our applications that are running on Core would no longer be able to work correctly. Our entire licensing eco-system revolves strongly around this part of the API. Not only does our license server rely on this, but also our client package for the license manager.

The fact is that we need to be able to create a unique identifier of some sorts, that map to hardware, sure there are many other licensing techniques, but this is the model we went for and has been doing great over the past few years.

As that issue that I have linked says many times over, that the decision to drop support for the full framework, worries people because of 3rd party dependencies / libraries still mainly target the full framework. In this specific instance I am an author of a few libraries which I would like to keep up to date and working for Core.

**Comment by karelz** [comment] 2017-05-09 22:59
Well you didn't point any existing APIs before, I don't know all of them :) - that itself explains why you view is a blocker.

If you're interested "only" in port, then this is dupe of #14762 - that one should be updated.
This one was understood as "create brand new API".

> As the decision that has been made for ASP.NET Core to stop support for the .Net Framework,

The linked issue is active discussion about that decision. AFAIK it is not final yet (I may be wrong - I am not directly involved in that).

If you agree, I will close it as dupe, as you are not interested in new API, but only in port of System.Management. Can you please confirm?

**Comment by louislewis2** [comment] 2017-05-10 05:29
I totally agree that this is a dupe of the issue you linked. This one can certainly be closed and continue being tracked there. Sorry for not providing the actual API in the beginning, I just assumed that this is common knowledge :)

**Comment by karelz** [comment] 2017-05-10 05:49
Thanks for confirmation, closing as dupe.

**Closed by karelz** 2017-05-10 05:49 UTC
Labels: api-needs-work, area-Meta, up-for-grabs
