### ISSUE TITLE
SEHException on Sse.Shuffle(Vector128<uint>, byte) and segfault during Jitting a method with Crc32

### ISSUE THREAD

**Issue by buybackoff** [dotnet/corefx#34543] opened 2019-01-11 09:29 UTC
The following test fails with SEHException in Shuffle. However, when manually inlining the `shuffle_ulong` method it works OK.

The code used to work on 2.1 with the intrisic package from MyGet and `StaticCast` instead of `Vector128.As<>`.

Using Runtime 3.0.0-preview-27310-6 and SDK 3.0.100-preview-010046. 

```c#
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static Vector128<ulong> shuffle_ulong(Vector128<ulong> x, byte m)
        {
            var y = x.As<uint>();
            var z = Sse2.Shuffle(y, m); // SEHException
            return z.As<ulong>();
        }

        [Test]
        public void CouldSse2ShullfeZero()
        {
            var x = new Vector128<ulong>();

            var y = x.As<uint>();
            var z = Sse2.Shuffle(y, (byte)78); // OK
            var res =  z.As<ulong>();

            var res2 = shuffle_ulong(x, (byte)78);
        }
```

**Update:**
Maybe related issue: while using Crc32 I get segfault exception but in a method that calls a method that uses Crc32 intrinsics. The error on [this line](https://github.com/Spreads/Spreads/blob/7c3574f3ec9d80c1abc8347bcd853c98d3b880dd/src/Spreads.Core/Algorithms/Hash/CRC32C.cs#L292). The error happens during method JITting: when Crc32 is in false branch I still get the error, if I comment out all Crc32 methods in the false branch the method works OK.

**Update2:**
Managed to create a repro. When dereferencing a pointer to a temp variable everything works, but dereferencing inside `Crc32(0, *data)` causes the error:

```c#
        private static uint MethodWithCrc32OK(byte* data)
        {
            var b = *data;
            var x = System.Runtime.Intrinsics.X86.Sse42.Crc32(0, b);
            return x;
        }

        private static uint MethodWithCrc32Fail(byte* data)
        {
            var x = System.Runtime.Intrinsics.X86.Sse42.Crc32(0, *data); // Unsafe.Read works OK
            return x;
        }

        [Test]
        public unsafe void CouldCallCrc32()
        {
            var data = (byte*)Marshal.AllocHGlobal(1);
            var x1 = MethodWithCrc32OK(data);
            var x2 = MethodWithCrc32Fail(data);
        }
```

**Comment by karelz** [comment] 2019-01-15 17:24
Sounds like JIT bug? @CarolEidt 
cc @tannergooding

**Comment by tannergooding** [comment] 2019-01-15 17:48
Dupe of https://github.com/dotnet/coreclr/issues/21855

**Closed by tannergooding** 2019-01-15 17:48 UTC
Labels: area-System.Runtime.Intrinsics, bug
