### ISSUE TITLE
SemaphoreSlim and Wait(0)

### ISSUE THREAD

**Issue by JB4GH** [dotnet/corefx#28884] opened 2018-04-06 07:44 UTC
Hi,

I am very new with C# so I apologise in advance if this is dumb. I read a lot of docs and conversation threads and it is pretty clear that the "wait(0)" is supposed to return immediately with either true or false.

Problem is that when I make basic test, I can see that the "wait" calls can take a lot of time (multiple seconds) to return.

Might just be the way I run the multiple threads test, but still, if someone could confirm the behavior?

In theory in the following test the time difference between "Enter" log and "Wait" log should be very small, but as explained when I run it (with a lot of threads) I get large difference, like 10 seconds.

```
static SemaphoreSlim s = new SemaphoreSlim(1, 1);

static void Test(object x)
        {
            Console.Write("Enter" + x + " " + System.DateTime.Now + "\n");
            bool b = s.Wait(0);
            Console.Write("Wait" + x + " " + System.DateTime.Now + "\n");
            if (b)
            {
                try
                {
                    Console.Write(b + " " + x + "\n");
                    for (long i = 1; i <= 5000000000; i++) {
                        //
                    }
                }
                finally
                {
                    Console.Write("Exit" + x + " " + System.DateTime.Now + "\n");
                    s.Release();
                }
            } else {
                Console.Write(b + " " + x + "\n");
                Console.Write("Exit False " + x + " " + System.DateTime.Now + "\n");
            }
        }
```

Thank you for your time.

**Comment by svick** [comment] 2018-04-06 12:28
Can you post a complete example that reproduces the issue?

**Comment by JB4GH** [comment] 2018-04-06 12:59
As said the example is pretty basic and I might just do it wrong, but here it goes. Note that I had to run couple of times (abort and restart), and now after that it shows at every run.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

using System.Threading;


namespace AsyncTest
{
    class Program
    {
        static SemaphoreSlim s = new SemaphoreSlim(1, 1);

        static void Main(string[] args)
        {
            int i = 1;
            while(true) {
                new Thread(Test).Start(i);
                i++;
            }

        }


        static void Test(object x)
        {
            DateTime d = System.DateTime.Now;
            Console.WriteLine("Enter Wait: " + x + " " + d);
            bool b = s.Wait(0);
            d = System.DateTime.Now;
            Console.WriteLine("Exit Wait:" + x + " " + d);
            if (b)
            {
                try
                {
                    Console.WriteLine(b + " " + x);
                    for (long i = 1; i <= 10000000000; i++) {
                        //
                    }
                }
                finally
                {
                    s.Release();
                }
            } else {
                Console.WriteLine(b + " " + x);
            }
        }

    }
}
```

And my last run produced this
```
Enter Wait: 16 04/06/2018 15:54:58
Enter Wait: 19 04/06/2018 15:54:58
Enter Wait: 1 04/06/2018 15:54:58
Enter Wait: 12 04/06/2018 15:54:58
Enter Wait: 4 04/06/2018 15:54:58
Exit Wait:4 04/06/2018 15:55:00
False 4
Exit Wait:16 04/06/2018 15:55:00
True 16
Enter Wait: 20 04/06/2018 15:54:58
Exit Wait:20 04/06/2018 15:55:18
False 20
Enter Wait: 7 04/06/2018 15:54:58
Enter Wait: 8 04/06/2018 15:54:58
Exit Wait:8 04/06/2018 15:55:18
False 8
Exit Wait:7 04/06/2018 15:55:18
False 7
Exit Wait:1 04/06/2018 15:55:18
False 1
Enter Wait: 2 04/06/2018 15:54:58
Exit Wait:2 04/06/2018 15:55:18
False 2
Enter Wait: 3 04/06/2018 15:54:58
Exit Wait:3 04/06/2018 15:55:18
False 3
Enter Wait: 10 04/06/2018 15:54:58
Exit Wait:10 04/06/2018 15:55:18
False 10
Enter Wait: 5 04/06/2018 15:54:58
Exit Wait:5 04/06/2018 15:55:18
False 5
Enter Wait: 6 04/06/2018 15:54:58
Exit Wait:6 04/06/2018 15:55:18
False 6
Enter Wait: 13 04/06/2018 15:54:58
Enter Wait: 22 04/06/2018 15:54:58
Exit Wait:22 04/06/2018 15:55:18
False 22
```

So as an example we get this one (taking 20 seconds)
Enter Wait: 20 04/06/2018 15:54:58
Exit Wait:20 04/06/2018 15:55:18

**Comment by svick** [comment] 2018-04-06 13:54
I find it suspicious that lines with timestamps that are 20 seconds later appear earlier in the output. Though I can't think of what could be causing that.

What OS are you using? And what is your version of .Net Core?

**Comment by JB4GH** [comment] 2018-04-06 14:08
OSX .NET Framework 4.5

**Comment by stephentoub** [comment] 2018-04-06 14:31
Your main method:
```C#
            int i = 1;
            while(true) {
                new Thread(Test).Start(i);
                i++;
            }
```
is creating an unbounded number of threads as quickly as it can.  I'm surprised your machine isn't entirely falling over.  Then all of those threads are synchronizing on the same semaphore; that's going to create a huge log jam.

> OSX .NET Framework 4.5

This is a contradiction :smile: .NET Framework 4.5 doesn't run on mac.

**Comment by JB4GH** [comment] 2018-04-06 14:48
Well, the 4.5 was from our project file config :)

The test on the other hand seems to be using the 2.0.0 NETCore version. Anyway, it's running on Mac with the latest Visual Studio.

I have the same test with a 10 threads limit (while (i < 10)) and got this kind of output: 

Enter Wait: 2 04/06/2018 17:39:22
Exit Wait:2 04/06/2018 17:39:22
True 2
Enter Wait: 1 04/06/2018 17:39:22
Exit Wait:1 04/06/2018 17:39:22
False 1
Enter Wait: 3 04/06/2018 17:39:22
Exit Wait:3 04/06/2018 17:39:40
True 3
Enter Wait: 4 04/06/2018 17:39:22
Exit Wait:4 04/06/2018 17:39:40
False 4
Enter Wait: 5 04/06/2018 17:39:22
Exit Wait:5 04/06/2018 17:39:57
True 5
Enter Wait: 6 04/06/2018 17:39:22
Exit Wait:6 04/06/2018 17:39:57
False 6
Enter Wait: 7 04/06/2018 17:39:22
Exit Wait:7 04/06/2018 17:40:15
True 7
Enter Wait: 8 04/06/2018 17:39:22
Exit Wait:8 04/06/2018 17:40:15
False 8
Enter Wait: 9 04/06/2018 17:39:22
Exit Wait:9 04/06/2018 17:40:33
True 9

So how do I interpret your comment? Too many threads will create some slowness while trying to acquire the semaphore (even with the wait(0))? 

In our main application we try to initialise some variables from our DB. When the application scales under heavy load, it fires too many calls to the DB for the initialisation. Therefore we thought we could introduce semaphores to call the DB only once and cache the value, with some logic to refresh the cache every 15 minutes or so.

It works with normal load, but when we perform load testing it hangs and all requests timeout. I am assuming we are using the semaphore wrong. While debugging the code though I started to wonder if the wait(0) really returns immediately (in our case it seems to hang). And that's why I tried to reproduce with a simple test.

**Comment by svick** [comment] 2018-04-06 14:54
@stephentoub 

> Your main method is creating an unbounded number of threads as quickly as it can. I'm surprised your machine isn't entirely falling over.

My Windows machine can handle that code just fine. I suspect it's because the vast majority of those threads run for a very short time.

> Then all of those threads are synchronizing on the same semaphore; that's going to create a huge log jam.

I don't see why it would create a jam on the semaphore, since I think most threads are going to ["fail fast"](https://github.com/dotnet/coreclr/blob/76ba8d5/src/mscorlib/src/System/Threading/SemaphoreSlim.cs#L327-L332).

Though all the threads are going to be synchronizing on the `Console` lock.

**Comment by wfurt** [comment] 2018-09-25 00:57
Is there anything left to answer @stephentoub or should close this or turn into a bug?

**Closed** 2018-09-25 13:36 UTC
Labels: area-System.Threading, question
