### ISSUE TITLE
HttpStatusCode compatibility across framework

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#28172] opened 2018-03-17 17:34 UTC
@incompletude commented on [Sat Mar 17 2018](https://github.com/dotnet/core/issues/1358)

Is there any reason for this?

[ProducesResponseType(HttpStatusCode.OK)] // requires cast
return StatusCode(HttpStatusCode.OK); // requires cast

Thx

**Comment by karelz** [comment] 2018-03-17 17:42
Duplicate of #28157

**Closed by karelz** 2018-03-17 17:42 UTC

**Comment by incompletude** [comment] 2018-03-18 07:11
Sorry karelz. I messed up here. I thought I ask the wrong repo. Now I did.

**Comment by karelz** [comment] 2018-03-18 18:06
@incompletude no problem. It is sometimes not super-simple to navigate through our repos - the ["file new issue" template in core repo](https://github.com/dotnet/core/blob/master/ISSUE_TEMPLATE) has some pointers to our repos.
