### ISSUE TITLE
VBCollection - Remove key and insert before the previous non existing item

### ISSUE THREAD

**Issue by medoni** [dotnet/corefx#26676] opened 2018-01-30 10:13 UTC
The `VBCollection.Add` method has a bug if you pass a before key which was previously removed.

Following Code:
```VB
Dim coll As New Collection()
coll.Add("Foo", "kFoo")
coll.Add("Bar", "kBar")
coll.Add("Baz", "kBaz")

coll.Remove("kBar")
coll.Add("Bar", "kBar", Before:="kBar") 'Before isn't a valid key anymore. should raise an exception

Console.WriteLine($"Count: {coll.Count}") ' -> 3

For Each item In coll
    ' endless loop
    Console.WriteLine($"{Date.Now}-{item}")
Next
```

Output:
```
Count: 3
30/01/2018 11:05:49-Bar
30/01/2018 11:05:50-Bar
30/01/2018 11:05:50-Bar
30/01/2018 11:05:51-Bar
30/01/2018 11:05:51-Bar
30/01/2018 11:05:51-Bar
...
```
Source:
[VBCollectionBug.zip](https://github.com/dotnet/corefx/files/1677202/VBCollectionBug.zip)

**Comment by medoni** [comment] 2018-01-30 10:14
[VBCollectionBug.zip](https://github.com/dotnet/corefx/files/1677201/VBCollectionBug.zip)

**Comment by karelz** [comment] 2018-01-30 21:52
You can simplify the repro even more:
```vb
Dim coll As New Collection()
coll.Add("a", "b", Before:="c") 'Throws exception. If you change 'c' to 'b', it does not throw exception.
```
When you change `c` to `b` it won't throw exception. In other words, you can technically add item before "itself".

The type is not part of .NET Core - see [Collection info](https://apisof.net/catalog/Microsoft.VisualBasic.Collection), it is only part of .NET Framework. We do not track .NET Framework bugs here on GitHub - please file it on [developercommunity site](https://developercommunity.visualstudio.com/spaces/61/index.html).

BTW: Given the high compat bar of .NET Framework and the fact it likely existed in this form since .NET 1.1, I don't think it will be fixed, but rather considered as a weird 'By Design' case.

Closing on GitHub.

**Closed by karelz** 2018-01-30 21:52 UTC
Labels: area-Microsoft.VisualBasic
