### ISSUE TITLE
Http pipelining

### ISSUE THREAD

**Issue by efratshenhar** [dotnet/corefx#14612] opened 2016-12-18 07:46 UTC
I am trying to use HTTP pipeline (like this: [https://en.wikipedia.org/wiki/HTTP_pipelining ](https://en.wikipedia.org/wiki/HTTP_pipelining) ) in my .NET Core app.
Could you tell me how to do it or if it is even possible ?

**Comment by karelz** [comment] 2016-12-19 17:26
Quick search found this: [HttpWebRequest.Pipelined](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.pipelined(v=vs.110).aspx). Not sure if it is useful.

cc @CIPop if he can provide a quick hint ...

**Comment by CIPop** [comment] 2016-12-21 18:56
I don't think WinHttp supports HTTP pipelining. I will confirm internally with the team owning the OS component.

Curl supports this feature via [CURLMOPT_PIPELINING](https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html). The [code referencing this option ](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.MultiAgent.cs#L238) in CurlHandler will only enable multiplexing for HTTP/2.

/cc @stephentoub, @davidsh

**Comment by CIPop** [comment] 2016-12-21 18:59
@karelz looks like `HttpWebRequest.Pipelined` is always returning true (probably the original intent being app-compat) but is not used anywhere. As I've mentioned above, WinHttpHandler/CurlHandler don't have this feature enabled.

**Comment by CIPop** [comment] 2016-12-27 23:12
I have confirmed that WinHttp doesn't support pipelining. At least on Windows, this is not possible.
Please reopen if this is needed in Unix (Curl).

**Comment by Mpdreamz** [comment] 2017-06-14 15:44
Can we reopen this? it would be awesome if `CurlHandler` exposed this for `HTTP1/1` requests.

**Comment by karelz** [comment] 2017-06-14 16:54
@Mpdreamz what exactly should happen? Is there curl API we can call to get/set the flag? Or is there more to it?

**Comment by Mpdreamz** [comment] 2017-06-19 14:59
Hey @karelz, 

I think my ask boils down to having a way to toggle `CURLPIPE_HTTP1` for `CURLMOPT_PIPELINING` if you know the server supports it. For instance i'm writing the client for Elasticsearch and I know for sure the server will support HTTP1/1 pipelining and setting it generally yields a 30% boost in performance (number from memory if needed will report back with actual numbers of pipelining enabled/disabled on desktop clr).

**Comment by karelz** [comment] 2017-06-19 15:07
Do you expect it to be negotiated with the server on user's behalf and set automatically if supported by the server?
Or do you expect explicit API call to set it? (it may fail if Server does not support it)

**Comment by Mpdreamz** [comment] 2017-06-19 15:13
An explicit API to explicitly (un)set it suffices for my usecase

**Comment by karelz** [comment] 2017-06-19 15:43
The question is if it is the best thing for the platform. Is it possible to implement it without a new API?
Or does the user (caller) have to know about the Pipelininng support on the server / is the negotiation costly?

**Comment by karelz** [comment] 2017-06-19 15:44
cc @Priya91 @wfurt @stephentoub

**Comment by Mpdreamz** [comment] 2017-06-19 16:04
Not sure if negotiation is even needed.

From [wikipedia](https://en.wikipedia.org/wiki/HTTP_pipelining):

>HTTP/1.1 conforming servers are required to support pipelining. This does not mean that servers are required to pipeline responses, but that they are required not to fail if a client chooses to pipeline requests

**Comment by karelz** [comment] 2017-06-19 16:21
Should it be a default then? Maybe with opt-out in case there are troubles with some servers? (not everyone plays by the rules and by wikipedia ;))

**Comment by Mpdreamz** [comment] 2017-06-19 16:56
I guess so but I know better then to proclaim being an HTTP spec expert :)

**Comment by niemyjski** [comment] 2017-12-10 13:07
What's the status of this?

**Comment by karelz** [comment] 2017-12-11 17:33
There's no new status - it needs solid proposal from someone who is interested and who fully understands it.

From Networking team side point of view, this is not mainline scenario, it has unclear value (number of customers who would benefit) and it is not aligned with our Networking roadmap (https://github.com/dotnet/designs/issues/9), so it is unlikely going to be funded from our side. I would suggest to close this issue, unless someone else is interested in pushing it further.

We could entertain HTTP pipelining as a feature in our ManagedHandler implementation eventually.

**Comment by davidsh** [comment] 2018-05-06 20:07
HTTP/2.0 supports a very efficient stream multiplexing feature on a single TCP connection.  The goal is to add HTTP/2.0 to the new SocketsHttpHandler which is used on all platforms (Windows, Linux) starting with .NET Core 2.1.

Currently SocketsHttpHandler does not support HTTP/2.0. We hope to add this support in a future version after .NET Core 2.1.

Thus, there isn't a need to try to add legacy HTTP/1.1 pipelining support to the CurlHandler stack. And the current Windows .NET Core 2.0 stack (WinHttpHandler) isn't able to support pipelining due to using native WinHTTP.

**Closed by davidsh** 2018-05-06 20:07 UTC
Labels: api-needs-work, area-System.Net.Http
