### ISSUE TITLE
HTTP2: Adapt stream window size based on user consumption

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35388] opened 2019-02-18 05:37 UTC
[EDIT] Pipelines has some logic already to reach an optimal receive window -- should we leverage that?

Currently, our stream-level response window is 64K (the default). This is probably too small for many scenarios, and will end up stalling the server as it sends response data. 

We should increase this, but it's not clear what the right amount is. Further perf investigation is needed here.

As part of this, we should probably switch our response buffering strategy from using a single array buffer to using linked buffers that are allocated from the pool.

Related to #31299

**Comment by geoffkizer** [comment] 2019-02-28 07:55
Note that if we do increase the stream window size, we should also consider enforcing the connection window size. Currently we don't do this, because we assumed that the stream-level enforcement was sufficient. However, if we increase the stream-level window significantly, then this may no longer be true.

**Comment by scalablecory** [comment] 2019-09-23 23:43
Pipelines has some logic already to reach an optimal receive window; I wonder if we can leverage that.

**Comment by karelz** [comment] 2019-10-08 21:32
Duplicate of #31299

**Closed by karelz** 2019-10-08 21:32 UTC
Labels: area-System.Net.Http, enhancement, tenet-performance
