### ISSUE TITLE
PrinterSettings.IsValid always returning false for network printer.

### ISSUE THREAD

**Issue by groogiam** [dotnet/corefx#32465] opened 2018-09-25 22:19 UTC
System.Drawing.Printing.PrintDocument.PrinterSettings.IsValid always returns false for a network printer on Windows Server 2012 R2. 

When I run the same code under .NET Framework the IsValid property is set correctly on the same machine running under the same user credentials as the .NET Core Process.

**Comment by danmosemsft** [comment] 2018-09-26 03:18
Thanks for the report @googiam. Do you have an interest in doing some debugging to suggest the cause? Generally we ported the s.drawing code verbatim.

**Comment by groogiam** [comment] 2018-09-26 14:56
I can give it a shot, I don't really have much experience debugging framework code. Would you recommend I setup source linking to try and step through the code or is there some other mechanism you would recommend?

**Comment by MarcoRossignoli** [comment] 2018-09-26 16:08
@groogiam you could star forking repo https://github.com/dotnet/corefx/wiki/Checking-out-the-code-repository#fork-the-repository
And build corefx! https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md
If build succeeds you can open System.Drawing.Common.sln solution, it contains your prop(IsValid) source code(corefx contains some solutions)
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs#L245 
```
cd c:\git\corefx\src\System.Drawing.Common\
devenv System.Drawing.Common.sln
```
Solutions on corefx  are divided in 2 main directory `src` for source and `tests` for tests(https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/repo-organization.md)
Corefx repo uses xunit for testing, so you can debug tests/code following this guide https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md#debugging-tests-in-visual-studio
You can also rebuild and start test using msbuild
```
cd c:\git\corefx\src\System.Drawing.Common\
msbuild /t:rebuildandtest /v:m
```
For start you could add some trait to test and check if you can attach https://github.com/dotnet/corefx/wiki/Build-and-run-tests#run-and-debug-single-test-in-visual-studio
I hope I was helpful!

**Comment by danmosemsft** [comment] 2018-09-26 23:27
Thanks @MarcoRossignoli ! Now you are one of the experts on working here 😸

**Comment by karelz** [comment] 2018-10-01 17:41
Closing here as it seems to be external problem in Service Fabric. @groogiam feel free to reopen if it turns out to be problem in CoreFX after all.
Thanks!

**Closed by karelz** 2018-10-01 17:41 UTC
Labels: area-System.Drawing, bug

**Comment by groogiam** [comment] 2018-10-03 16:56
I cannot seem to get a response from the service fabric team on this. After attempting to check the printer is valid and calling Marshal.GetLastWin32Error(), I get 1801 which indicates that unc printer path is not being resolved. The FabricHost process runs under SYSTEM but the spawned services are running under a domain account which should have full access to the network. This seems like a bug in windows unc path resolution for printers. Any idea on where I can submit this issue for further trouble shooting if it is a bug in the Win32 api?

**Comment by karelz** [comment] 2018-10-04 18:15
First, I would wait for ServiceFabric response - it is part of their end-to-end story. If you need fast answer, you can always contact Microsoft support.
If you have proof it is Win32 bug, not limited to just ServiceFabric, it would be good to mention it + provide the "proof". I am not aware of any public channel for OS Win32 APIs bug reporting beside official Microsoft support.
