### ISSUE TITLE
[System.Text.Json] not support Dictionary<primitive type, T>

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#40566] opened 2019-08-25 09:14 UTC
Test code:
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace JsonTest
{
    class Entity
    {
        public string Value { get; set; }
    }
    class TestClass
    {
        public Dictionary<int, Entity> Value { get; set; } = new Dictionary<int, Entity>();
    }
    class Program
    {
        static void Main(string[] args)
        {
            var x = new TestClass();
            x.Value[1] = new Entity { Value = "test" };
            var value = JsonSerializer.Serialize(x);
            Console.WriteLine(value);
        }
    }
}
```

```
Unhandled exception. System.NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Int32,System.Collections.Generic.Dictionary`2[System.String,JsonTest.Entity]]' on 'JsonTest.TestClass.Value' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
yType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JsonTest.Program.Main(String[] args) in C:\Users\hez20\Desktop\JsonTest\Program.cs:line 22
PS C:\Users\hez20\Desktop\JsonTest> dotnet run
Unhandled exception. System.NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Int32,JsonTest.Entity]' on 'JsonTest.TestClass.Value' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JsonTest.Program.Main(String[] args) in ...\Program.cs:line 21
```

Expected value:
```json
{ "1": { "Value": "test" } }
```

**Comment by hez2010** [comment] 2019-08-25 09:19
Closed as duplicated with #40120

**Comment by poizan42** [comment] 2019-09-23 16:26
@ahsonkhan So this is closed and has the 3.0 milestone but is not actually implemented in 3.0?

**Comment by hez2010** [comment] 2019-09-23 16:28
@poizan42 I think I need to reopen this issue.

**Comment by poizan42** [comment] 2019-09-23 16:46
@hez2010 That doesn't really fix the problem. The definition of CoreFX features added in 3.0 given at https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0.md is "is:issue milestone:3.0 label:enhancement", so issues really shouldn't have the 3.0 milestone if they are not in 3.0.

**Comment by danmosemsft** [comment] 2019-09-23 18:03
@poizan42 changed milestone for clarity

**Comment by ahsonkhan** [comment] 2019-09-25 00:00
Thanks for the feedback @poizan42 - updating the milestone makes sense. Regardless, closing this issue as duplicate of https://github.com/dotnet/corefx/issues/40120.

**Closed by ahsonkhan** 2019-09-25 00:00 UTC
Labels: area-System.Text.Json, enhancement
