### ISSUE TITLE
Build failure on master (Ubuntu Desktop 14.04.3)

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5199] opened 2016-01-06 18:43 UTC
Installed fresh copy of Ubuntu Desktop 14.04.3 LTS in VirtualBox 5.0.12

**Build CoreCLR on Linux (Instructs to build CoreFx as well)**

https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md
installed git

1) clrjunkie@ubuntu-14-desktop:~$ cd ~
2) clrjunkie@ubuntu-14-desktop:~$ mkdir git
3) clrjunkie@ubuntu-14-desktop:~$ cd git
4) clrjunkie@ubuntu-14-desktop:~/git$ git clone https://github.com/dotnet/coreclr.git //today
5) clrjunkie@ubuntu-14-desktop:~/git$ git clone https://github.com/dotnet/corefx.git //today

6) clrjunkie@ubuntu-14-desktop:~/git$ echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" | sudo tee /etc/apt/sources.list.d/llvm.list
7) clrjunkie@ubuntu-14-desktop:~/git$ wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
8) clrjunkie@ubuntu-14-desktop:~/git$ sudo apt-get update
9) clrjunkie@ubuntu-14-desktop:~/git$ sudo apt-get install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev

10) clrjunkie@ubuntu-14-desktop:~/git$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
11) clrjunkie@ubuntu-14-desktop:~/git$ echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
12) clrjunkie@ubuntu-14-desktop:~/git$ sudo apt-get update
13) clrjunkie@ubuntu-14-desktop:~/git$ sudo apt-get install mono-devel

14) clrjunkie@ubuntu-14-desktop:~/git$ sudo nano /etc/security/limits.conf

Add:
 
clrjunkie soft nofile 50000
clrjunkie hard nofile 50000

15) clrjunkie@ubuntu-14-desktop:~/git$ sudo nano /etc/sysctl.conf 

Add:

fs.file-max = 100000 

16) clrjunkie@ubuntu-14-desktop:~/git$ sudo sysctl -p 

17)   logout & login

18) clrjunkie@ubuntu-14-desktop:~$  ulimit -Hn
    50000

19) clrjunkie@ubuntu-14-desktop:~$ cd git/coreclr
20) clrjunkie@ubuntu-14-desktop:~/git/coreclr$ ./build.sh

Repo successfully built.
Product binaries are available at /home/clrjunkie/git/coreclr/bin/Product/Linux.x64.Debug

21) clrjunkie@ubuntu-14-desktop:~/git/coreclr$ cd ../corefx

**Website doc error - Need to mention FX requires additional setup**

22) clrjunkie@ubuntu-14-desktop:~/git/corefx$ ./build.sh
    Setting up directories for build
    PCL reference assemblies not found. Please see https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md for more details.

[fxbuild.txt](https://github.com/dotnet/corefx/files/80209/fxbuild.txt)

**Building CoreFX on FreeBSD, Linux and OS X**

https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md 
	
23) clrjunkie@ubuntu-14-desktop:~/git/corefx$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
24) clrjunkie@ubuntu-14-desktop:~/git/corefx$ echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
25) clrjunkie@ubuntu-14-desktop:~/git/corefx$ echo "deb http://jenkins.mono-project.com/repo/debian sid main" | sudo tee /etc/apt/sources.list.d/mono-jenkins.list
26) clrjunkie@ubuntu-14-desktop:~/git/corefx$ sudo apt-get update
27) clrjunkie@ubuntu-14-desktop:~/git/corefx$ sudo apt-get install mono-snapshot-latest referenceassemblies-pcl
28) clrjunkie@ubuntu-14-desktop:~/git/corefx$ . mono-snapshot mono
29) [mono-2016.01.05+18.26.39]clrjunkie@ubuntu-14-desktop:~/git/corefx$ sudo ln -s /usr/lib/mono/xbuild-frameworks/.NETPortable/ $MONO_PREFIX/lib/mono/xbuild-frameworks/
30) [mono-2016.01.05+18.26.39]clrjunkie@ubuntu-14-desktop:~/git/corefx$ ./build.sh

 7 Warning(s)
    73 Error(s)

Time Elapsed 01:50:40.53
Build Exit Code = 1

(Attached full log)

**Comment by clrjunkie** [comment] 2016-01-06 18:44
[fxbuild.txt](https://github.com/dotnet/corefx/files/80212/fxbuild.txt)

**Comment by mellinoe** [comment] 2016-01-06 18:55
I see a couple issues, most probably caused by recent changes to project files and changes in the new .builds files:

* Some tests are running against the Windows version of the library. Registry, Threading.Overlapped, Crypto, Net.Security
* Creating NuGet packages isn't working because some of the libraries aren't being built.

I'll try this on my Ubuntu machine in a minute and see what issues I hit.

@weshaggard

**Comment by mellinoe** [comment] 2016-01-06 19:42
Didn't see it when looking through your log initially, but I'm hitting it too:

````
/home/clrjunkie/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00142/lib/partialfacades.targets(121,5): error : No single matching contract found. [/home/clrjunkie/git/corefx/src/System.Collections.Concurrent/src/facade/System.Collections.Concurrent.csproj]
````

**Comment by clrjunkie** [comment] 2016-01-06 20:15
@mellinoe 

Can you shed some light on how the CoreFX build process works?
Are the CoreFx assemblies partially compiled using references to Mono BCL Dll’s?
Is the Mono compiler used during build / something else ?
Are Mono DLL's used for missing CoreFX ports at runtime ?

A short explanation would highly be appreciated.

**Comment by mellinoe** [comment] 2016-01-06 21:10
Right now, mono is only used to run our x-plat version of MSBuild. MSBuild itself, as well as the Roslyn compiler, are provided by us. Also, we're aiming to remove the mono dependency very soon (and run MSBuild on CoreCLR). We don't compile against any Mono assemblies, nor do we use them at runtime (except for running MSBuild).

@weshaggard and I figured out the issue with the "No Matching Contract found" error. There were backslashes in the task I linked above, which meant the task was failing to find the project reference for every partial facade on Ubuntu. We had a fallback for that case, but the fallback mechanism didn't work for net46 configurations. I'm going to fix that particular issue in buildtools now. This may also fix some of the packaging errors that you see at the end of the build (caused by missing assemblies). I don't know what is the problem with the vbc error, yet.

**Comment by clrjunkie** [comment] 2016-01-06 21:22
Understood. Thanks!

Waiting for a fix.

**Comment by clrjunkie** [comment] 2016-01-07 15:15
Attached build log as of commit:

e0e13fc Merge pull request #5218 from justinvp/streamreader_preamble

[fxbuild2.txt](https://github.com/dotnet/corefx/files/81286/fxbuild2.txt)

 7 Warning(s)
    26 Error(s)

Time Elapsed 01:47:34.21
Build Exit Code = 1

**Comment by mellinoe** [comment] 2016-01-07 20:02
@clrjunkie Thanks for following up again. I've filed #5230 and #5233 to track the remaining issues that I see. The other issue that I didn't file is that tests that SHOULD be disabled on Ubuntu are not being disabled if you run `build.sh`. They are disabled properly if you run `run-tests.sh` (like our CI is doing), but it's hard to run that script by hand. In any case, `build.sh` should be fixed because it is just running the regular MSBuild project build.

**Comment by clrjunkie** [comment] 2016-01-07 20:42
>The other issue that I didn't file is that tests that SHOULD be disabled on Ubuntu are not being disabled if you run build.sh

Can you please open an issue for this?

I really don't know how to assess the current situation.. can I work with what did build?

How can I build individual projetcs on linux ? 1.5h is too long

**Comment by mellinoe** [comment] 2016-01-07 21:12
> can I work with what did build?

Yes, all of the assemblies that DID successfully build should be correct and fine to use. The test failures can be ignored because they should have been skipped in the first place.

> How can I build individual projetcs on linux ?

You can run msbuild on the individual project files, as you would on Windows. Here is what I do:

* Create an alias for msbuild, or set an environment variable. MSBuild.exe can be found in the packages directory once you have run the restore process (this is the first thing that happens when you run build.sh. It is under <root>/packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/MSBuild.exe. You need to run this with mono (it's a .NET executable), so I set my alias like this:
```
msbuild="mono <root>/packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/MSBuild.exe"
```
* You can then run msbuild on any of the .csproj files in the repo and it should build them individually. If the project has a Linux-specific configuration, then you need to pass another argument along to msbuild: /p:OSGroup=Linux. I set an alias for that too for convenience.
* To run tests, you can do the same as the above but on a test project, and pass /t:BuildAndTest as an additional argument.

**Comment by clrjunkie** [comment] 2016-01-07 21:32
Thanks. May I ask how you prefer to debug (step into source assemblies) on linux

**Comment by mellinoe** [comment] 2016-01-07 22:05
There's some instructions here, from the coreclr repo: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux.

Basic summary is to use lldb with libsosplugin, which should be downloaded with the rest of the necessary test assemblies.

**Comment by clrjunkie** [comment] 2016-01-07 22:28
Thanks! please reference this issue when things get resolved so I can know when to test a full build again.

**Comment by mellinoe** [comment] 2016-01-19 19:54
There's still a couple of fixes in the work for remaining issues, but I am moving this to RTM as I don't think we will necessarily port all of the build fixes to our Release branch. They will be available in the master branch, though.

**Comment by clrjunkie** [comment] 2016-01-19 20:44
Thanks!. Lots going on... would you mind listing those here? I think this is would be a good place to keep track of the overall progress just because of the title :)

**Comment by mellinoe** [comment] 2016-01-19 20:49
Here's what I remember and which are still not fixed:

* Lots of tests fail because the test runtime being used is out of date, and the native shims do not have the correctly-renamed functions in them. We can probably fix this one now, I'm assuming we can update the test runtime to use a newer version.
* NuGet packages cannot be built, resulting in a lot of build failures at the end. @ericstj was working on something that could fix this part.

Neither should block you from building all of the binaries, but you will see lots of errors during and after the build. It may be worthwhile to pass /p:SkipTests=true to the build if you are hitting the first bullet point above.

**Comment by clrjunkie** [comment] 2016-01-19 21:16
Than I suggest modifying the script to include a "disable package build" and make it top priority., because many errors can easily mask bugs / regressions in actual FX built code. If you are used to seeing a lot of red lines and assume these are "OK" it's easy to fail notice of actual blockers. The alternative would be to hack some log filtering tool but I guess modifying the build script would be much faster.. I think a clean and consistent log output of successful bin builds is a must.

**Comment by mellinoe** [comment] 2016-01-19 21:54
> I think a clean and consistent log output of successful bin builds is a must.

Completely agreed. The reason I hadn't disabled them when initially investigating was that we hoped we'd be able to get a quick fix out for it rather than disable them. Unfortunately, there are so many regressions in this area because we do not run this build logic in our CI test runs at all, and most everyone on the team is doing development work on Windows for the most part, especially since these issues popped up last month.

I'm currently doing a full build on Ubuntu to assess the current status.

**Comment by clrjunkie** [comment] 2016-01-19 22:46
Here is a suggestion:

Up until recently I wouldn't mind running the build in the morning and report errors. However following  #5335 this got more time consuming since the way the code is organized to accommodate  different platforms  it's not just a matter of a single run (at least when building on windows) and doing also for linux is an additional overhead that starts to have a negative impact on my productivity doing other stuff. Now I know you have automation for build/CI but these system tend to come with lots of bells and whistles, web interface and what not. If you want I can try to setup a VM on Azure that will run a simple sh daily that will: clone the repo, call build, send an email to some Dev DL with the log files attachment, and finally delete the entire cloned repo. It may take one or two iterations to play well, but I think this would be the most simple and objective processes since this VM won't have all sorts of dev dependencies and utilities installed. It also sits somewhere so it really doesn't grab attention. I think this is also simple enough such when I'm not around anyone can log into this machine and enhance/maintain the script. The only thing I would ask is not to be charged  by  Azure.

**Comment by mellinoe** [comment] 2016-01-19 23:23
@clrjunkie One thing that I forgot to mention is that we SHOULD be able to run the regular corefx build in our CI very soon. We are going to be migrating to a CoreCLR-based version of MSBuild (rather than mono), which will eliminate one of the big dependencies our build has. The work for that is [here](https://github.com/dotnet/buildtools/pull/396). Historically it has been a bit problematic because of the complicated pre-requisites the build needed (special version of Mono, etc.), not to mention the nuget-restore/build times on mono.

I expect that once we have our build running on MSBuild on CoreCLR, we will be able to run the x-plat build in CI more easily. It's definitely not our intention to just keep letting the x-plat builds regress continuously like they have been recently, but we need to make some infrastructure improvements first.

**Comment by mellinoe** [comment] 2016-04-18 22:14
There have been so many issues in the x-plat builds since this was filed that it's probably not valuable to keep this one open anymore. At this point in time, everything should build cleanly on Ubuntu, including the outer-loop tests, and we **finally** have per-pull-request CI tests running using build.sh on Ubuntu. So this should stay relatively clean for the foreseeable future.

Please let me know if you encounter any other x-plat build issues.

**Closed by mellinoe** 2016-04-18 22:14 UTC
Labels: Infrastructure, X-Plat
