### ISSUE TITLE
JsonSerializer creates unnecessary escape sequences when encoding strings.

### ISSUE THREAD

**Issue by NerdyDuck** [dotnet/corefx#38543] opened 2019-06-14 13:07 UTC
Using SDK 3.0.0-preview6-27804-01
I played around with different ways of serialization (binary, JSON, BSON) regarding size and speed, using randomly generated data. I noticed that JSON generated with System.Text.Json.Serialization.JsonSerializer was a bit larger than the same data serialized with Newtonsoft.Json.JsonSerializer/JsonWriter. The difference is in the serialized strings, as System.Text.Json.Serialization.JsonSerializer escapes more characters than Newtonsoft does, and mostly uses the hex character code, even if a shorter escape sequence exists. I did another test with all visible ASCII characters (0x20 to 0x7e), here are the results (hoping that Markdown won't screw it up).

```
Newtonsoft.Json:
{"msg":" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"}

System.Text.Json:
{"msg":" !\u0022#$%\u0026\u0027()*\u002b,-.\u002f0123456789:;\u003c=\u003e?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_\u0060abcdefghijklmnopqrstuvwxyz{|}~"}
```

So, Newtonsoft only escapes `"` and `\` (and only with 2-character escape sequences) while System.Text.Json escapes ``"&'+-<>\` ``  (using hex values - 6 characters - in all cases except one). I tried it with both `JsonSerializer.ToString` and `JsonSerializer.ToUtf8Bytes`, but the result is the same.

**Comment by nmain** [comment] 2019-06-14 14:35
Related https://github.com/dotnet/corefx/issues/38354

**Comment by ahsonkhan** [comment] 2019-06-18 05:49
This is a duplicate of existing issues:
https://github.com/dotnet/corefx/issues/35385
https://github.com/dotnet/corefx/issues/34958

We plan to add the ability for the caller to modify the default behavior by passing in a custom `JavaScriptEncoder` to `JsonWriterOptions`, `JsonSerializerOptions`, and `JsonEncodedText`.
https://github.com/dotnet/corefx/issues/37192

**Comment by ahsonkhan** [comment] 2019-06-18 21:51
Closing as duplicate.

**Closed by ahsonkhan** 2019-06-18 21:51 UTC
Labels: area-System.Text.Json
